### ISSUE TITLE
Support for Go back/Go forward

### ISSUE THREAD

**Issue by arjunattam** [microsoft/vscode-pull-request-github#1006]
Issue Type: <b>Feature Request</b>

I'd like to be able to use the "Go back" and "Go forward" commands on the PR diff views, like it is possible with normal files in the editor.

To repro:

1. Open a PR
2. Click on a file in the tree to open the diff view
3. Click on a different file in the tree to open a new diff view
4. Run the "Go back" command (Alt + left arrow on Windows, or Ctrl + hyphen on macOS)

Expected result: Go back should take me to the first diff view. Currently it doesn't do anything.

Extension version: 0.4.0
VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17763

**Comment by alexr00** [comment]
We now have a "Go to Next Diff in Pull Request command".
