### ISSUE TITLE
Missing context menu on pull request

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-pull-request-github#1007]
- Install Nightly build
- Find a pull request in the SCM viewlet
- Right click, nothing happens. I like to use the "checkout" option from here

**Comment by RMacfarlane** [comment]
This should be fixed with https://github.com/Microsoft/vscode-pull-request-github/commit/71e1cc021f7bcc3b55c25d49dab7b86b8d590c5b in the latest nightly build, 1.57.0
