### ISSUE TITLE
PR labels should be sorted case-insensitively

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-pull-request-github#1008]
Labels are sorted with caps letters first, I think `aaa` should come before `Bbb`.

![image](https://user-images.githubusercontent.com/323878/53391199-708a8480-394a-11e9-81a9-c54f5f68daff.png)

**Comment by tobudim** [comment]
I'd like to give a little help if someone could tell me where to look. Thanks! :)

**Comment by haryps** [comment]
Dear All,

Is this issue still open? I would like to work on this issue. I have made the changes accordingly in my local branch.
