### ISSUE TITLE
Extension installed, don´t see anywhere to sign in.

### ISSUE THREAD

**Issue by Yachont** [Microsoft/vscode-pull-request-github#1009]
I really would want to use this feature as it´s very useful so I´d appreciate some help.
I have the extension in vscode installed but I can´t use it at all because I can´t sign in. I´ve already tried Shift+Ctrl+B and type "Github" hoping that I could somehow log in.

Maybe I´m just stupid. Can someone help?

**Comment by RMacfarlane** [comment]
Hey @Yachont, the extension should show a notification asking to sign in when it detects that the folder you have open has a GitHub remote. What's the result of running `git remote -v` in your folder? Can you also check what is in the Output Channel when selecting `GitHub Pull Request` from the dropdown?

**Comment by Yachont** [comment]
Hello @RMacfarlane, thanks for the quick reply. 
When I type `git remote -v` into a terminal I get this: 

`origin  https://github.com/slavarosin/jakob_praktikum.git (fetch)
origin  https://github.com/slavarosin/jakob_praktikum.git (push)`

This is the output from the `Github Pull Request`:

`[Info] C:\Users\JakobsPC\.ssh\config: ENOENT: no such file or directory, open 'C:\Users\JakobsPC\.ssh\config'
[Info] Looking for git repository
[Info] Git repository found, initializing review manager and pr tree view.
[Info] No GitHub remotes found
[Info] Review> no matching pull request metadata found for current branch master
`
What does that mean?

**Comment by RMacfarlane** [comment]
Thanks for the info!

Here's a breakdown of what the output means:
The first line with `ENOENT` is ok, we check to see if there is a config file that has any aliases, in this case we didn't find any.
The extension finds that the current repository uses git and starts to initialize some parts.
The critical line is `No GitHub remotes found`, this means the extension wasn't able to resolve `https://github.com/slavarosin/jakob_praktikum.git` as pointing to GitHub for some reason.

Can you check what version of the extension you have? There was a bug with parsing remotes a while ago. The newest version of the extension requires VSCode version 1.31.0

**Comment by Yachont** [comment]
My current version of VSCode is 1.31.1

Maybe I messed something up because it didn´t work and I tried to fix it so I went and did the steps here: https://code.visualstudio.com/docs/editor/versioncontrol -> Common questions

In a terminal I put these lines in:

`git remote add origin https://github.com/slavarosin/jakob_praktikum
git push -u origin master`

Maybe that screwed something up?

**Comment by RMacfarlane** [comment]
Hmm. Those lines are fine, that should just be setting up the remote. You're on version 0.4.0 of the extension?

**Comment by Yachont** [comment]
Yeah, I am. I even tried previous versions of the extension to see if that would do something. Still no luck.

**Comment by RMacfarlane** [comment]
The expected behavior when you install the extension is that this notification should show up:
![screen shot 2019-02-27 at 9 28 40 am](https://user-images.githubusercontent.com/3672607/53510228-4f24b800-3a72-11e9-9203-5ac705474fa7.png)

and that the status bar should have a sign in button:
![screen shot 2019-02-27 at 9 28 29 am](https://user-images.githubusercontent.com/3672607/53510247-58ae2000-3a72-11e9-95eb-96c6a6fc254d.png)

and also a command to sign in:
![screen shot 2019-02-27 at 9 29 01 am](https://user-images.githubusercontent.com/3672607/53510268-64014b80-3a72-11e9-9154-04cbc1113f10.png)

From the output log, it looks like the extension is activating. Can you open the command palette and run `Developer: Toggle Developer Tools` to see if there are any errors in the console?

**Comment by Yachont** [comment]
@RMacfarlane thanks for helping me. I finally found a solution!! All I had to do was open the folder where the extension was, open the `README.md` file and then it asked me to sign in.

I wasn´t able to do that before. I am so happy. Thanks for helping me. It´s very appreciated.
