### ISSUE TITLE
no matching pull request metadata found

### ISSUE THREAD

**Issue by vinayakpyt** [Microsoft/vscode-pull-request-github#1014]
- Extension version: 0.4.0
- VSCode Version: 1.31.1
- OS: MacOS - 10.14.3

Steps to Reproduce:

1. Install github pull request vscode extension
2. Sign in using github enterprise account, browser opens with the vscode and also links to vscode, but no PR's are seen
Below is the log from the output window, tried multiple times with uninstall, still not working
[Info] Looking for git repository
[Info] Git repository found, initializing review manager and pr tree view.
[Info] Found GitHub remote
[Info] https://api.github.com: GraphQL support detected
[Info] {
  "data": {
    "viewer": {
      "login": "e",
      "__typename": "User"
    }
  },
  "loading": false,
  "networkStatus": 7,
  "stale": false
}
[Info] Review> no matching pull request metadata found for current branch hotfix/feb-26

**Comment by RMacfarlane** [comment]
By default the extension is looking for PRs for `upstream` and `origin` remotes - do your remotes match this? (`git remote -v`) This can be configured with the `githubPullRequests.remotes` setting

**Comment by vinayakpyt** [comment]
Just added git remote add upstream https://github.com/abcd/bcdg.git and it started to show, very strange,  had never done this in the past. The tool has been flaky and fragile, hope to see more stability, but the tool has been a great help - a clear winner with no easy alternative
