### ISSUE TITLE
Can't Sign In

### ISSUE THREAD

**Issue by robbiespeed** [microsoft/vscode-pull-request-github#1019]
- Extension version: 0.4.0
- VSCode Version: 1.31.1
- OS: Fedora 28 (Linux)

Steps to Reproduce:

1. Click link in notification to sing in
2. Browser window opens with "Authorize Visual Studio Code to access GitHub"
3. Click "Continue"
4. "Oh no! An error occurred!" "Please restart the sign in process from the editor." "Forbidden"
5. Retry by restarting the editor, same thing happens

**Comment by robbiespeed** [comment]
Noticed I had my VPN on, turned it off and it authentication worked.

**Comment by DanielKOcean** [comment]
You are a lucky one, I even have no auth notification, so my expention is useless right now...

**Comment by alexr00** [comment]
We have changed how auth works. If you're still seeing the issue, please feel free to ping!
