### ISSUE TITLE
Add more metrics for user type and pull request actions

### ISSUE THREAD

**Issue by meaghanlewis** [Microsoft/vscode-pull-request-github#1029]
I'd like to capture more data about our types of users and what they are doing in the Pull Requests extension.

**User data**
- How many users are GitHub users compared to GitHub Enterprise users?
  - Is it possible to know what version of Enterprise customers are on?

**Pull Request data**
- How many times are pull requests are merged? closed?
- How many times is the local pull request branch deleted?
- How many times an inline/review comment is added?

**Interaction with activity bar**
One other thing that would be interesting to know is how many times users click the GitHub icon on the activity bar.

Any others that you'd like to see?

**Comment by meaghanlewis** [comment]
See the metrics previously added here: https://github.com/Microsoft/vscode-pull-request-github/issues/228#issuecomment-418356099

**Comment by meaghanlewis** [comment]
@annthurium I think another good metric to add would be for how many times a PR is created.

**Comment by RMacfarlane** [comment]
Has been completed with https://github.com/Microsoft/vscode-pull-request-github/pull/1118
