### ISSUE TITLE
Select repo in when showInSCM: false and several repos in VS Code workspace

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/vscode-pull-request-github#1033]
While there is no option to show all PRs from multiple repos in a workspace (see #493) it became harder to switch between repos in workspace when `githubPullRequests.showInSCM` is set to `fasle` (default in insiders builds).
I have to open Source Control viewlet, pick repo, and switch back to GitHub Pull Request.

As possible solutions it can be
1. Same contorl as in the top of SCM viewlet
1. Selectbox (if it is possbile)
1. Tree structure with folders(repos) in the top level  (same as in Explorer view) that contain current list of sections.

Lastest solution will can be a way to address #493 (not sure if putting PRs from all repos into All is better option than having tree)

**Comment by joliveirarodrigues** [comment]
Switching does not work at all in linux version (fedora 29)

**Comment by forstermatth** [comment]
I'm having the same issue - multi source workspace always defaults, and I cannot switch, even if I remove the other sources.

I have attempted on both the insiders and GA versions of VS Code.

Related issues:
* https://github.com/microsoft/vscode-pull-request-github/issues/1179
* https://github.com/microsoft/vscode-pull-request-github/issues/1090
* https://github.com/microsoft/vscode-pull-request-github/issues/1069
* https://github.com/microsoft/vscode-pull-request-github/issues/1033

----

Extension version: 0.7.0
VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:22.738Z)
OS version: Darwin x64 18.6.0

----

Extension version: 0.7.0
VS Code version: Code - Insiders 1.35.0-insider (4ca38ce5584d7cd67b435b3c32ef1240c6a29628, 2019-05-21T05:17:12.031Z)
OS version: Darwin x64 18.6.0

---

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by RMacfarlane** [comment]
Closing as the third option, Tree structure with folders(repos) in the top level, has already been implemented. Thanks!
