### ISSUE TITLE
Lists with checkboxes render badly

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-pull-request-github#1038]
ext: 1.67.0
os: ubuntu 18.04.2

pr: https://github.com/Tyriar/xterm.js/pull/5

![image](https://user-images.githubusercontent.com/2193314/54052589-a6750780-4199-11e9-951f-5e33566af65a.png)

.com:

![image](https://user-images.githubusercontent.com/2193314/54052624-c5739980-4199-11e9-9392-62d0f97348f8.png)

**Comment by jrnail23** [comment]
I've got the same issue on mac
<img width="684" alt="Screen Shot 2019-03-08 at 5 13 50 PM" src="https://user-images.githubusercontent.com/392612/54059030-a985ed00-41c5-11e9-972c-647859e75360.png">

and here's what it looks like on GitHub:
![Screen Shot 2019-03-08 at 5 15 06 PM](https://user-images.githubusercontent.com/392612/54059058-c6222500-41c5-11e9-857e-b93f5e81090d.png)
