### ISSUE TITLE
"Unable to find current pull request" error when creating PR

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode-pull-request-github#1040]
Issue Type: <b>Bug</b>

1. Use the `Create Pull Request` command

Instead of opening the description view on completion, an error is shown. The PR is successfully created and the tree is updated, though.

Extension version: 0.5.0
VS Code version: Code - Insiders 1.33.0-insider (9b849d9de7168eb4f685823bf9b9e27a0a8dae74, 2019-03-08T06:57:39.083Z)
OS version: Darwin x64 18.2.0

**Comment by segevfiner** [comment]
Reproduced on:
Extension version: 0.5.0
VS Code version: 1.32.1
OS version: macOS 10.14.3

**Comment by bvhme** [comment]
Reproduced on:
Extension version: 0.5.0
VS Code version: Version 1.32.2
Os version: macOS 10.14.3
