### ISSUE TITLE
recent version no tree view

### ISSUE THREAD

**Issue by Thomazella** [Microsoft/vscode-pull-request-github#1042]
- Extension version: 0.5.0
- VSCode Version: 1.32.1
- OS: macOS 10.14.3

Steps to Reproduce:

1. go to source control view
2. expect to see pull requests tree view collapsed in bottom or open, but it's not there

After updating to a new version I can't access the extension from the source control view (where it shows changed files) It used to be there always, open or collapsed. Description still mentions this so I concluded it wasn't an intentional change. Hitting cmd+shift+P and typing `pull` will auto complete the extension's command and it'll show then, but then it takes the whole view.

![Screen Shot 2019-03-11 at 1 52 47 PM](https://user-images.githubusercontent.com/15015324/54141947-6dd96600-4405-11e9-951f-5b51e16e4a53.png)

![Screen Shot 2019-03-11 at 1 59 01 PM](https://user-images.githubusercontent.com/15015324/54142137-d7f20b00-4405-11e9-90d8-eee5b02be542.png)

**Comment by RMacfarlane** [comment]
Thanks @Thomazella, I merged the updates to the `README` after packaging the extension for publishing, so they were missed. The next time the extension gets updated the new instructions should be visible, they're on GitHub and called out in the changelog. You can revert to the old behavior with the `githubPullRequests.showInSCM` setting

**Comment by Thomazella** [comment]
thank you it works
