### ISSUE TITLE
Clicking Checkout with uncommitted files shows an unhelpful error with text "Error"

### ISSUE THREAD

**Issue by mrlubos** [Microsoft/vscode-pull-request-github#1046]
- Extension version: 0.5.0
- VSCode Version: 1.32.1 (1.32.1)
- OS: 10.14.3 (18D109)

Steps to Reproduce:

1. Have uncommitted files in current branch.
2. Try to checkout a PR.

Notes:

I tried my steps to reproduce but could not replicate this issue, so the condition must be slightly different from what I am reporting. The issue was that running `git checkout <branch>` from command line was throwing an error on its own with an informative message, but pressing the Checkout button showed only a message saying "Error" (without the instructions how to fix it).

**Comment by RMacfarlane** [comment]
Thanks for reporting this issue! There was a problem with VS Code not returning an error code for this case, fixed in https://github.com/Microsoft/vscode/commit/a5455afcef379d9a99723c2562f70d352c142642. Will be available with the next release of VS Code in two weeks.
