### ISSUE TITLE
Can't exit review mode

### ISSUE THREAD

**Issue by segevfiner** [microsoft/vscode-pull-request-github#1048]
- Extension version: 0.5.0
- VSCode Version: 1.32.1
- OS: macOS 10.14.3

Steps to Reproduce:
1. Click "Exit Review Mode" in a PR description.
2. You will need to choose the relevant repo in a multi-folder workspace (Separate issue https://github.com/Microsoft/vscode-pull-request-github/issues/654)
3. Choose a different branch.
4. The pull request remains in the status bar and still has a check mark in the pull requests view, if you switch back to the branch you will still be in review mode.

It makes sense for the pull request to be "deselected", that is, for it to disappear from the status bar and the check mark removed from the pull requests view. The same state you start in before you enter review mode. Might even make sense for this to not require switching a branch. Just "exit review mode" so you are back to the same state as checking out the branch normally.

**Comment by MartinSmeyer** [comment]
+1

**Comment by segevfiner** [comment]
There are multiple duplicates of this issue already. I for one am not using this extension due to this, and have seen others having to constantly disable/enable it or other workarounds when they do use it in situations where they would like to exit review mode and disable its UI without switching branch or when going back to a branch that was in review mode before.

**Comment by NateSackett** [comment]
Does anyone have a workaround to exit this? My coworker merged a pull request while I was still looking at it and deleted the branch, and now I can't exit that pull request.

**Comment by alexr00** [comment]
I tried the steps in the original issue and in https://github.com/microsoft/vscode-pull-request-github/issues/1048#issuecomment-858806590, but I wasn't able to repro the issue. Does anyone have other steps that reliably cause this?

**Comment by segevfiner** [comment]
This still happens.
1. Create a branch.
2. Make a change.
3. Create a pull request.
4. Exit review mode.
5. Return to the branch. The branch returns to review mode.

### Workaround
The associations between a branch and pull request is handled by a Git config value `branch.{name}.github-pr-owner-number`, you can remove it to remove the association of the branch to a pull request. (Or possibly remove and recheckout the branch).

It would have been nice if this extension also allowed to associate an existing branch with a pull request (When you already have it checked out and don't want another `pr/7` branch, but sadly this isn't supported as well.

**Comment by alexr00** [comment]
> Return to the branch. The branch returns to review mode.

This is intended. The original issue is about the status bar item and the checkmark next to the branch name not getting updated when you leave the PR branch. 

> It would have been nice if this extension also allowed to associate an existing branch with a pull request (When you already have it checked out and don't want another pr/7 branch, but sadly this isn't supported as well.

This is a good feature request! I have opened https://github.com/microsoft/vscode-pull-request-github/issues/3225.

**Comment by alexr00** [comment]
Closing this issue, as it doesn't seem that anyone is still seeing it.

**Comment by mattlubner** [comment]
> The associations between a branch and pull request is handled by a Git config value `branch.{name}.github-pr-owner-number`, you can remove it to remove the association of the branch to a pull request. (Or possibly remove and recheckout the branch).

Thank you for this! I have been stuck in "pull request mode" ever since we created a PR to merge our default branch into another one. Manually editing my `.git/config` file to remove that association has _finally_ gotten me out of pull request mode.

It would be nice if this extension removed that association when exiting review mode, so that it'd be possible to leave pull review mode without switching branches.

**Comment by EDIflyer** [comment]
Thank you @mattlubner - I was stuck in this mode too (VS Code version below). Had opened a PR on Github website, then edited some of it on VS Code then completed the merge on Github website. PR mode seemed to get 'stuck' on VS Code (clicking exit review mode didn't help) until I edited .git/config.  @alexr00 not sure if it is fixed given I experienced just now?

```
Version: 1.68.0 (user setup)
Commit: 4af164ea3a06f701fe3e89a2bcbb421d2026b68f
Date: 2022-06-08T11:44:16.822Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19044
```

**Comment by alexr00** [comment]
@EDIflyer we detect whether a branch is associated with a PR, so this view will keep showing. For an immediate solution to your problem, you might want to modify the setting `githubPullRequests.useReviewMode`.

https://github.com/microsoft/vscode-pull-request-github/issues/3590 will also help with this.

**Comment by NicolasHu11** [comment]
thanks @alexr00
- update `githubPullRequests.useReviewMode` helped me with closed PR. 
- The wording here "Exit Review Mode" is confusing, it actually does "Go to the default branch", not "Close the feature branch and go back to the previous branch you were on"

**Comment by alexr00** [comment]
@NicolasHu11 I can try changing the language for "exit review mode". Maybe "leave PR branch"? I'll gather some more feedback on that and see what others think.

**Comment by mattlubner** [comment]
@alexr00 To clarify, my issue was triggered by a _closed_ PR for merging the default branch into a different one.

> we detect whether a branch is associated with a PR

I was probably seeing the effects of some bug in that "PR detection" functionality. The thing is, storing that association in the `branch.{name}.github-pr-owner-number` Git config _could_ make the issue survive fixes to that detection code.

Perhaps it'd be prudent to add an FAQ entry mentioning the workaround – ie. manually deleting the `branch.{name}.github-pr-owner-number` Git config?

**Comment by mattlubner** [comment]
> I can try changing the language for "exit review mode". Maybe "leave PR branch"? I'll gather some more feedback on that and see what others think.

I think "leave PR branch" is much more clear! 👍

**Comment by alexr00** [comment]
Ok, we're going to try changing "Exit Review Mode" to "Checkout 'main'", where 'main' will be whatever the default branch is for the repo.
