### ISSUE TITLE
Urls do not appear clickable in comments. They are not clickable either

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode-pull-request-github#105]
Testing https://github.com/Microsoft/vscode/issues/55396 on Ubuntu

<img width="370" alt="screen shot 2018-07-31 at 2 42 00 pm" src="https://user-images.githubusercontent.com/16890566/43488893-0571f238-94d0-11e8-969e-5db58ac12590.png">

**Comment by rebornix** [comment]
Share the same root cause as https://github.com/Microsoft/vscode-pull-request-github/issues/66, let's track it there, thanks！
