### ISSUE TITLE
Error signing in

### ISSUE THREAD

**Issue by GodPingu** [microsoft/vscode-pull-request-github#1052]
- Extension version:0.5
- VSCode Version:1.32.2
- OS:Windows 10

Steps to Reproduce:
1.Fresh install of vscode
2.Fresh install of github pull request

After installing gh pr, for the first time on a fresh install of vscode I don't get prompted to login when I first install the extension and when using the command pallette I have no option to login instead only to logout, however when I select to signout I have no usernames or anything available to sign out on.

**Comment by RMacfarlane** [comment]
@GodPingu Can you make sure that you have a folder currently open in vscode? What's in the Output panel if you select `GitHub Pull Requests` from the dropdown?

**Comment by GodPingu** [comment]
No dropdown/ github tab appears for me in the sidebar

**Comment by askvortsov1** [comment]
I'm experiencing a similar issue. I'm running on the latest VSCode insiders, and there's no notification to log in. I'm assuming that https://github.com/microsoft/vscode-pull-request-github/pull/1626 should fix this, but it might make sense to change the 'No Remotes Match the Current Setting' message if there is no currently logged in user.

**Comment by RMacfarlane** [comment]
Closing as this should be fixed in the latest version of the extension - a sign in button should appear in the tree view when you have a git folder open
