### ISSUE TITLE
Enable auto-save

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-pull-request-github#1054]
When the user uses `auto-save` the PR overview page should auto-save updates to title and description and edits to comments. Same for the commenting widget. Not so sure about creating new comments.

**Comment by RMacfarlane** [comment]
@kieferrm Do you mean these changes should be persisted immediately to GitHub when the user stops typing?

**Comment by sandhya-sago** [comment]
Please do not persist to GitHub as it will trigger emails. I like the current behavior of explicitly saving them. That way, I can make sure that the comments are complete and there is no confusion.
