### ISSUE TITLE
Search the PRs

### ISSUE THREAD

**Issue by adrinjalali** [microsoft/vscode-pull-request-github#1062]
To have a search either by ID and/or by PR title. Adding the search included on the GH interface would also not be too hard I suppose.

**Comment by pwinston** [comment]
Being able to search by PR or issue number would be great. For us very often the PR or issue numbers and thrown around all the time, so those are how we think of things.

**Comment by saumyajyoti-mukherjee** [comment]
Need a VSCode command to search by PR number.

**Comment by tanhakabir** [comment]
+1 from GHPRI studies

**Comment by alexr00** [comment]
There is now a command to open a PR by PR number :)
