### ISSUE TITLE
Assign from the description view

### ISSUE THREAD

**Issue by adrinjalali** [microsoft/vscode-pull-request-github#1063]
To assign oneself to a PR from the description view.

**Comment by brianjmurrell** [comment]
I guess it missed the May 2019 sprint.  :-(

**Comment by rebornix** [comment]
Then I think this can be closed now.

**Comment by RMacfarlane** [comment]
We implemented adding/removing reviewers, not changing assignment, so I think this feature request should still be open :)

**Comment by DharmeshPandav** [comment]
would be good to have this option/feature added into Description view but it had been a year since any activity on this
