### ISSUE TITLE
I need to reload vscode after each open and close of the comment bubble

### ISSUE THREAD

**Issue by ahmelsayed** [Microsoft/vscode-pull-request-github#1064]
- Extension version: 0.5.1
- VSCode Version: 1.33.0-insider
- OS: Ubuntu 18.04.2 LTS

Steps to Reproduce:

1. Open a PR
2. Click on a line to add a comment.
3. Dismiss it, either by adding a comment or cancel, both work.
3. Try to add another comment.

I need to reload the window and then I can add another one. 

![Peek 2019-03-22 11-34](https://user-images.githubusercontent.com/645740/54845443-8fa0db80-4c96-11e9-842a-26cf7d271bf3.gif)

**Comment by RMacfarlane** [comment]
Thanks for reporting this! This is an issue with the insiders version of VSCode, using the stable version is a possible workaround

**Comment by RMacfarlane** [comment]
Fixed upstream, tomorrow's version of VSCode insider's will have the fix

**Comment by ahmelsayed** [comment]
Awesome! Thank you @RMacfarlane
