### ISSUE TITLE
Issue with authentication via login

### ISSUE THREAD

**Issue by sreenath1491** [microsoft/vscode-pull-request-github#1067]
- Extension version: 0.5.1
- VSCode Version: 1.32.3
- OS: Mac OS Mojave 10.14.3

Really love using vscode and excited to use this extension. Thank you !!

Steps to Reproduce:

I have never actually reported issue. First time doing this . So please let me know if I need to add more info or change anything in format or if I am doing something wrong with the configuration. 

Installed this version and it didn't work with my office enterprise github(uses SSO). So added the config for hosts with a personal access token. 
```
    "githubPullRequests.hosts": [
        {
            "host": "https://github.org",
            "token": "*****"
        }
    ]
```

Still not able to authenticate. Keep getting the below error:
```
[Debug 6722s 692ms] Looking for git repository
[Debug 6722s 692ms] Git repository found, initializing review manager and pr tree view.
[Debug 6722s 692ms] Migrating https://github.org from githubPullRequests.hosts to keychain
[Debug 6722s 946ms] PullRequestManager> update repositories
[Debug 6722s 947ms] PullRequestManager> Displaying origin remote
[Debug 6722s 974ms] Found GitHub remote
[Debug 6723s 99ms] Authentication> Token is no longer valid for host https://github.org.
[Debug 6723s 100ms] GitHubRepository> Fetch metadata - enter
[Debug 6723s 218ms] Authentication> Token is no longer valid for host https://github.org.
[Debug 10275s 374ms] PullRequestManager> update repositories
[Debug 10275s 374ms] PullRequestManager> Displaying configured remotes: origin
[Debug 10275s 377ms] Found GitHub remote
[Debug 10275s 388ms] Authentication> No token found for host https://github.org.
[Debug 10275s 389ms] GitHubRepository> Fetch metadata - enter
[Debug 10275s 400ms] Unable to resolve remote: Error: Not authenticated.
[Debug 10275s 400ms] GitHubRepository> Fetch mentionable users - enter
[Debug 10275s 407ms] Authentication> No token found for host https://github.org.
[Debug 10275s 407ms] Unable to resolve remote: Error: Not authenticated.
[Debug 10275s 414ms] Review> no matching pull request metadata found for current branch master
[Debug 10275s 626ms] GitHubRepository> Fetch all pull requests - enter
[Debug 10275s 627ms] GitHubRepository> Fetching all pull requests failed: Error: Not authenticated.
```

SignIn button redirects to this url: 
```
https://vscode-auth.github.com/authorize?authServer=https://github.org/&callbackUri=vscode://GitHub.vscode-pull-request-github/did-authenticate&scope=read:user%20user:email%20repo%20write:discussion
```
which goes to this url https://github.org/login/oauth/authorize and succeeds i think since i can see `vscode-for-github` under my authorized OAUTH apps. But then fails with 
```
https://vscode-auth.github.com/?browser_session_id=f6a61bdf67bdeb708710d750de74d38139dabd6d&code=219a0d84f171f094a150&state=ddIEHS86Eyr31FYjg0xIc1FGJvw%2FeyJhdXRoU2VydmVyIjoiaHR0cHM6Ly9naXRodWIuZGV2LnBhZ2VzLyIsImNhbGxiYWNrVXJpIjoidnNjb2RlOi8vR2l0SHViLnZzY29kZS1wdWxsLXJlcXVlc3QtZ2l0aHViL2RpZC1hdXRoZW50aWNhdGUiLCJpZCI6Ijo6ZmZmZjoxMC4xNDcuNTcuMTE1In0
Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail

```

So I tried to debug with source code (using Version 1.33.0-insider  and current master at commit: f6bb4cde35a1cc175b54f2d05515da91a06165e3). I was able to get the `validate with token`(https://github.com/Microsoft/vscode-pull-request-github/blob/master/src/authentication/githubServer.ts#L187) call working but when a token is not present or deleted from my keychain it goes to sign which fails same as in version 0.5.1. 

To get above token call work ,I had to modify the code a bit to accept token since the token was being converted to a file:// scheme uri and hence was not setting the token.
```
			try {
				const uri = vscode.Uri.parse(uriOrToken);
				if (!uri.scheme) { throw new Error; }
                                 if (uri.scheme == 'file') { throw new Error; } (Added by me)
				uriHandler.handleUri(uri);
			} catch (error) {
				// If it doesn't look like a URI, treat it as a token.
				const host = await vscode.window.showInputBox({ prompt: 'Server', placeHolder: 'github.com' });
				if (!host) { return; }
				setToken(host, uriOrToken);
			}
Trace: BAD uri lacks scheme, falling back to file-scheme.
	at /private/var/folders/g1/1fgm3tsj1sz7_9t_0ntkvpm1w45syh/T/AppTranslocation/EA0DB71E-F2A8-4A66-BFC7-1BFFEDC1AD83/d/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:656
	at new f (/private/var/folders/g1/1fgm3tsj1sz7_9t_0ntkvpm1w45syh/T/AppTranslocation/EA0DB71E-F2A8-4A66-BFC7-1BFFEDC1AD83/d/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:729)
	at new p (/private/var/folders/g1/1fgm3tsj1sz7_9t_0ntkvpm1w45syh/T/AppTranslocation/EA0DB71E-F2A8-4A66-BFC7-1BFFEDC1AD83/d/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:115:930)
	at Function.parse (/private/var/folders/g1/1fgm3tsj1sz7_9t_0ntkvpm1w45syh/T/AppTranslocation/EA0DB71E-F2A8-4A66-BFC7-1BFFEDC1AD83/d/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:115:279)
	at CredentialStore.<anonymous> (/Users/****/open_source/vscode/vscode-pull-request-github/media/extension.js:76338:40)
	at Generator.next (<anonymous>)
	at fulfilled (/Users/****/open_source/vscode/vscode-pull-request-github/media/extension.js:76305:58)
```

I couldn't replicate issue with `Token is no longer valid for host https://github.org` with Code-Insiders.

How do I make the version 0.5.1 work with a token after failing initially?

**Comment by RMacfarlane** [comment]
Hey @sreenath1491, thanks for doing so much debugging on your own! We should have a command called `GitHub Pull Requests: Manually Provide Authentication Response` that doesn't parse the input as a uri. This is now the way to provide a token, we've removed reading it out of settings, some of our documentation may have been stale when you were trying this. (Sorry!)

Were you ever able to get authentication working? Does `GitHub Pull Requests: Manually Provide Authentication Response` with a token in the latest version of the extension (0.6.0) work for you?

**Comment by sreenath1491** [comment]
Thanks for your response @RMacfarlane. I did try using `GitHub Pull Requests: Manually Provide Authentication Response` but it was not working earlier. Though after new vscode update it started working. So i am closing this issue since i doesn't happen anymore.

**Comment by seriousran** [comment]
There is no more `GitHub Pull Requests: Manually Provide Authentication Response`. Isn't it? What is alternatives?
