### ISSUE TITLE
Comments should support edit and delete

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode-pull-request-github#107]
The editor comment widget should have a way for extensions to provide edit and delete actions on comments

**Comment by lostintangent** [comment]
@RMacfarlane You beat me to this! 😄 The VS Live Share team would also like to see this functionality, as part of our exploration to allow adding comments within a Live Share session.

**Comment by hartra344** [comment]
@RMacfarlane  was just coming to open a issue on this 😛 Would be helpful, I just had to open Github to delete a comment

**Comment by scrossan-crown** [comment]
I think this would be a really useful addition to make the workflow from vscode even better
