### ISSUE TITLE
Ctrl+Enter should commit comment

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode-pull-request-github#1072]
Refs: https://github.com/Microsoft/vscode/issues/71103

When focus is in the comment box, `Ctrl/Cmd+Enter` should commit, same as in the GH web UI.

**Comment by RMacfarlane** [comment]
@bpasero Can you include any additional repro steps? `Ctrl/Cmd+Enter` is submitting the comment as expected on my machine

**Comment by RMacfarlane** [comment]
Nevermind, I think I fixed the problem. The shortcut would have failed when trying to create the first comment, should be fixed by https://github.com/Microsoft/vscode/commit/be7280d639e46b421ebe94ff21f70efb8b297ca1
