### ISSUE TITLE
Clicking into comments field in code does not focus editor

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode-pull-request-github#1073]
Refs: https://github.com/Microsoft/vscode/issues/71103

It looks like clicking anywhere below the first line does not focus that line:

![image](https://user-images.githubusercontent.com/900690/54993937-5e404c80-4fc3-11e9-9817-88c8d7e2cbfc.png)

**Comment by RMacfarlane** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/71156
