### ISSUE TITLE
Review comments are duplicated

### ISSUE THREAD

**Issue by meaghanlewis** [microsoft/vscode-pull-request-github#1077]
- Extension version: 1.79.0
- VSCode Version: 1.33.0
- OS: macOS

Steps to Reproduce:

1. Leave an inline review comment in the diff
2. Refresh the diff either by closing and re-opening or switching focus
3. Observe that all comments become duplicated

<img width="641" alt="Screen Shot 2019-03-26 at 2 07 49 PM" src="https://user-images.githubusercontent.com/10103121/55033647-dd884d00-4fd0-11e9-8769-bc8070b8a5f5.png">

Discovered when testing for: https://github.com/Microsoft/vscode/issues/71103

**Comment by RMacfarlane** [comment]
I haven't been able to repro this yet - do you remember if you had the PR checked out when this happened?

https://github.com/Microsoft/vscode-pull-request-github/commit/87d575835f8dfdf40ddfb3029d6b341b32b4baa6 may have fixed this

**Comment by meaghanlewis** [comment]
@RMacfarlane i just tested this out again in 1.86.0 on the nightly build and am still getting the same problem. The issue does seem to only occur when the PR is checked out.

**Comment by RMacfarlane** [comment]
Thanks, I can repro it!

**Comment by meaghanlewis** [comment]
Thanks Rachel! 🎉

**Comment by RMacfarlane** [comment]
I'm using the 1.98 version of the extension and just ran into this again, so I'm reopening this issue.

**Comment by snoozbuster** [comment]
Still happening to me on version 0.7.0

**Comment by RMacfarlane** [comment]
This should be fixed as of version 0.9.0 as part of https://github.com/microsoft/vscode-pull-request-github/pull/1168, there was another case where a newly added comment wasn't being added to the cache correctly

**Comment by ivanvoznyakovsky** [comment]
it's back again 😞 
Version: 1.39.0-insider
Commit: d157c2e941cae17acb79bf26a70bbfad732bdc83
Date: 2019-09-16T06:04:26.115Z
Electron: 6.0.9
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0
