### ISSUE TITLE
Not clear on how to finish review from pending review comment

### ISSUE THREAD

**Issue by meaghanlewis** [microsoft/vscode-pull-request-github#1078]
I found it confusing to figure out how to finish a review after leaving a comment that was pending. I don't think this is a bug, rather an enhancement that would improve the user experience.

- Extension version: 1.79.0
- VSCode Version: 1.33.0
- OS: macOS

Steps to Reproduce:

1. Comment on a line
2. Select to `Start Review`
3. See comment is pending

<img width="604" alt="Screen Shot 2019-03-26 at 2 12 59 PM" src="https://user-images.githubusercontent.com/10103121/55033855-4ec80000-4fd1-11e9-8cbc-9a435566c08e.png">

4. Clicking `Reply...` on the comment will expand the options shown below:

<img width="607" alt="Screen Shot 2019-03-26 at 2 13 07 PM" src="https://user-images.githubusercontent.com/10103121/55033894-6a330b00-4fd1-11e9-9cde-bab082d1535f.png">

Solution:
Is it possible to show these options without having to click into the Reply field?

Discovered when testing for: https://github.com/Microsoft/vscode/issues/71103

**Comment by pjquirk** [comment]
Same issue here.  Maybe an action I could run from the command palette (GitHub: Finish Review), since that was my first instinct after not seeing anything in the UI?  Also some sort of UI once you click/execute "Finish Review" would be nice, it wasn't clear anything actually happened :)

**Comment by mattdaviscodes** [comment]
This is still present and still frustrating.

**Comment by blackmad** [comment]
+1 to confusing/frustrating (but otherwise this plugin is amazing and I feel silly for not having started using it sooner)

+1 to could be a command palette entry, could also be a button on the description/overview page

**Comment by clair-ross** [comment]
+1, Switching the `Comment` button to be a `Finish Review` button option would be inline with what I had expected the functionality to be. Hope this is in the backlog!

**Comment by alexr00** [comment]
In the time since this issue was created we've renamed the button "Go to Review".

I've just moved "Go to Review" to be always visible on pending comments.
