### ISSUE TITLE
Disable option to Start Review when no comment text

### ISSUE THREAD

**Issue by meaghanlewis** [microsoft/vscode-pull-request-github#1079]
- Extension version: 1.79.0
- VSCode Version: 1.33.0
- OS: macOS

Steps to Reproduce:

1. Go to leave a comment on a line
2. Observe that the comment box has the `Start Review` option enabled by default.
<img width="607" alt="Screen Shot 2019-03-26 at 2 17 51 PM" src="https://user-images.githubusercontent.com/10103121/55034210-2ee50c00-4fd2-11e9-82a0-7d2baea67ade.png">

Solution:
This option should be disabled until some text is actually entered in the comment box.

Discovered when testing for: https://github.com/Microsoft/vscode/issues/71103

**Comment by meaghanlewis** [comment]
Side note: This also seems to confuse things on GitHub.com where it shows a review has been started but there are 0 pending comments.

<img width="787" alt="Screen Shot 2019-03-26 at 2 20 55 PM" src="https://user-images.githubusercontent.com/10103121/55034336-7ff50000-4fd2-11e9-9494-af28b03d947f.png">

**Comment by RMacfarlane** [comment]
I think fixing this might involve tweaking the API. Right now, buttons are added to comments by specifying an `acceptInputCommand` and an optional list of `additionalAcceptInputCommands`. Based on the names of those properties, it would make sense that they always be disabled when there is no input. The `acceptInputCommand` for us is always "Add Comment", the "Start Review", "Finish Review", and "Delete Review" buttons are all from `additionalAcceptInputCommands`. The "Finish Review" and "Delete Review" buttons we add can be run without input - running "Delete Review" with input would be very weird, but this button is also a bit odd in its current placement.

We could
- disable all `additionalAcceptInputCommands` buttons when there is no text, removing the delete review button from the list
- change the `additionalAcceptInputCommands` property to have a flag indicating if it can be run when there is no input

**Comment by meaghanlewis** [comment]
@RMacfarlane thanks for the additional context here, I appreciate it.

Just to clarify the proposed solution - it will disable the buttons "Start Review, "Finish Review" and "Delete Review" but then add a flag to indicate if the command can be run? So only "Start Review" will have a flag that indicates input is required before running the command?

**Comment by RMacfarlane** [comment]
Yeah, that's right.

So instead of having the API be `additionalAcceptInputCommands: Command[];`, it would be
```ts
additionalAcceptInputCommands: [{
	command: Command;
	disableWhenEmpty: boolean;
}]
````

**Comment by rebornix** [comment]
Right now we call them `additionalCommands` and their states are not determined by the textarea, which is designed this way. However if we call them `*AcceptInputCommands`, then they should behave the same as `acceptInputCommand`, which is disabled if the textarea is empty.

**Comment by rebornix** [comment]
> Side note: This also seems to confuse things on GitHub.com where it shows a review has been started but there are 0 pending comments

I'd love to start a review without creating comments first actually. Right now .com doesn't allow that but the api does.

**Comment by meaghanlewis** [comment]
Yeah that's a great point @rebornix. The API does allow it, but I had never noticed that until testing out the new comment provider and it seemed strange to me.

Are you suggesting we leave this implementation as-is?

**Comment by rebornix** [comment]
It sounds like a good feature to me but if you think we'd better avoid that, we can throw an error or show a notification when users try to create a review without comments. This way we don't need to wait for any vscode side code change, which is already late at this point.

**Comment by meaghanlewis** [comment]
I'm okay with just showing some notification that says review comments must be added before starting a review.

**Comment by RMacfarlane** [comment]
This was fixed as part of adopting the new comments API (https://github.com/microsoft/vscode-pull-request-github/pull/1168)
