### ISSUE TITLE
Buttons in the PR description page

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode-pull-request-github#108]
Testing https://github.com/Microsoft/vscode/issues/55396 on Ubuntu

There are 4 buttons or button like looking items in the PR description page
- Open
- Checkout Pull Request
- Close Pull Request
- Comment

`Open` is never actionable. But it looks just like the other 3 which are actionable.

`Comment` is not actionable until there is some text in the box. And when not actionable, the only difference is that the white of the text is a bit pale.

**Comment by joaomoreno** [comment]
Yup found this to be pretty weird as well.

**Comment by RMacfarlane** [comment]
Fixed with https://github.com/Microsoft/vscode-pull-request-github/pull/154 and https://github.com/Microsoft/vscode-pull-request-github/commit/e1b3fdcc65dbc32cad12331feadb0c0b0be7ad11
