### ISSUE TITLE
Extension seems needlessly slow on slow internet connections

### ISSUE THREAD

**Issue by queerviolet** [microsoft/vscode-pull-request-github#1091]
- Extension version: Insiders
- VSCode Version: Insiders
- OS: all

Steps to Reproduce:

1. Go somewhere with terrible internet
    *or*
    Throttle your internet
2. Enter review mode for a branch you already have locally.
3. Wait.
4. Wait.
5. Wait.
6. The checkout is complete.

I believe 3, 4, and 5 are unnecessary.

I think we're hitting the API for some reason, we should cache whatever we need so we don't have to.

**Comment by rebornix** [comment]
Set the log level to Debug and you can see timestamps from the output channel. @queerviolet can you share them here? The output can tell us which operations are time consuming.

**Comment by alexr00** [comment]
Closing since we don't have the debug log.
