### ISSUE TITLE
Origin does not update

### ISSUE THREAD

**Issue by bm-stschneider** [microsoft/vscode-pull-request-github#1095]
Issue Type: <b>Bug</b>

It seems that the extension is a bit locked in when there are multiple repos in the workspace. It currently doesn't seem to change the repository no matter what. Even if the repository is closed.

Extension version: 0.5.1
VS Code version: Code - Insiders 1.33.0-insider (4039ea871879ef8f654f27df5c32d209104b3a44, 2019-03-29T10:48:35.896Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 3|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|-psn_0_1433950|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by scrossan-crown** [comment]
I'm having the same issue. 
Extension version 0.6.0 
VS Code version: 1.34.0-insider (0ab39f4148f242e7b0802330385fc99b4845aa31)
OS: Windows_NT x64 10.0.17763

**Comment by RMacfarlane** [comment]
This should have been fixed with https://github.com/microsoft/vscode-pull-request-github/commit/cc9b8de1617486c38f3c88d53fc559dcb758fc42, changing the selected repository in the source control viewlet should cause the extension to update
