### ISSUE TITLE
Request gives timeout all times on the view description of pull request.

### ISSUE THREAD

**Issue by alexandremsouza1** [microsoft/vscode-pull-request-github#1100]
- Extension version: 0.5.1
- VSCode Version: 1.32.3
- OS: Windows 10

Steps to Reproduce:

1.  Try to view the pull request description by the plugin.

Screen error.

![image](https://user-images.githubusercontent.com/38253342/55476704-ad9f0200-55ed-11e9-81ea-4bcddd56e94d.png)

**Comment by alexr00** [comment]
I think this has been fixed. Please ping this issue if you are still seeing the problem.
