### ISSUE TITLE
No matching repository

### ISSUE THREAD

**Issue by PierreMarchand20** [microsoft/vscode-pull-request-github#1101]
- Extension version: 0.51
- VSCode Version: 1.32.3
- OS: macOS 10.14.4

Steps to Reproduce:

1. I just installed the package
2. I logged in
3. I forked a repository in GitHub
3. I cloned it, did some modifications that I committed
4. I try to create a pull request and I get:
![image](https://user-images.githubusercontent.com/15056323/55485395-a8ac7380-562a-11e9-80cb-29eb9782d33f.png)
So it seems it finds the repository upstream but then I get 
![image](https://user-images.githubusercontent.com/15056323/55485438-be219d80-562a-11e9-8884-f8c0a3c55b42.png)

**Comment by rbtcollins** [comment]
I think this means you need to set githubPullRequests.remotes (see the README.md)

**Comment by PierreMarchand20** [comment]
Does it mean that each time that I fork a repo with the web interface on github, and I clone it, I need to set the remote myself ? 

I thought it was done automatically

**Comment by SakamotoRyoutaMF** [comment]
@PierreMarchand20 

hello!
your target repository's URL may be `git@~~`.
In my case, I can create PR when I fix it `https://~~`.

I hope this information is helpful!!

**Comment by RMacfarlane** [comment]
Closing as I'm not able to reproduce this in the latest version of the extension, I believe this has been fixed.
