### ISSUE TITLE
Replace vscode-editor-font-* variables with vscode-font-* variables in webviews

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-pull-request-github#1102]
See https://github.com/Microsoft/vscode/commit/e88a32ff2cb11e750b57b7c844a4b17665f0f04a

In VS Code 1.34, the `vscode-editor-font-*` css variables used in webview now track the `editor.font*` settings in VS Code. They previously tracked the UI font settings.

To keep your existing styling, please change these variables to use the new `vscode-font-family`, `vscode-font-weight`, and `vscode-font-size` variables being added in VS Code 1.34.

**Comment by RMacfarlane** [comment]
Looking at this again, I think our current usage of `vscode-editor-font-*` is correct, since this is used for rendering code diff sections on the webview. So I believe no action is needed.
