### ISSUE TITLE
Github Actions not shown in PR checks

### ISSUE THREAD

**Issue by KnisterPeter** [microsoft/vscode-pull-request-github#1105]
- Extension version: 0.6.0
- VSCode Version: 1.33.0
- OS: Arch Linux

Steps to Reproduce:

1. Open a project with github actions and open PR which are marked as require in protected branch configuration 
2. In the shown check on the github website for this PR the actions are listed as checks, in vscode the github action checks are missing

**Comment by DanTup** [comment]
This seems quite dangerous - if you had a larger number of checks, you might not realise that there are failed checks not showing up 😕

![Screenshot 2020-05-07 at 12 03 28](https://user-images.githubusercontent.com/1078012/81287548-dd270600-905a-11ea-8c89-3a16982223eb.png)
<img width="698" alt="Screenshot 2020-05-07 at 12 03 33" src="https://user-images.githubusercontent.com/1078012/81287554-de583300-905a-11ea-907c-bc67edbeb062.png">

**Comment by JustinGrote** [comment]
The only checks I see come up are Appveyor even though I have many other checks (15 in total). @RMacfarlane any idea why they are being filtered? This seems more like a bug than a feature request.

![image](https://user-images.githubusercontent.com/15258962/81347123-5c730480-9070-11ea-901f-dda9e3b39b99.png)
![image](https://user-images.githubusercontent.com/15258962/81347196-80364a80-9070-11ea-96a5-415a1d9391b7.png)

**Comment by RMacfarlane** [comment]
The view in GitHub combines data from a couple of different sources. In the extension right now, we're using this "combined status for a specific ref" API: https://developer.github.com/v3/repos/statuses/#get-the-combined-status-for-a-specific-ref

Originally I thought this would return all of the checks, but GitHub action results are not included in this result. So, we need to make an additional query to get those, or change it to use a graphql query to get all of the data to display

**Comment by JustinGrote** [comment]
@RMacfarlane apparently the API required is in preview but it is here:
https://developer.github.com/v3/checks/runs/#list-check-runs-for-a-git-reference

**Comment by JustinGrote** [comment]
FYI it does still *enforce* the checks even if not visible in this URI, so I feel a bit better about that at least:
![image](https://user-images.githubusercontent.com/15258962/81453889-99f29300-913f-11ea-828c-7f98457148ce.png)

**Comment by JustinGrote** [comment]
As an update, I recently had to rebuild my Azure Pipelines connection, and now it started showing up in Checks API for some reason...
![image](https://user-images.githubusercontent.com/15258962/81751006-72633980-9463-11ea-9126-f6a37615bebe.png)
