### ISSUE TITLE
Unable to log in to GHE

### ISSUE THREAD

**Issue by colin-young** [microsoft/vscode-pull-request-github#1107]
- Extension version: 0.6.0
- VSCode Version: 
- OS: 1.33.0 (user setup)
- GHE: 2.15.9

Unable to login to GHE. Started with `settings.json` containing a `githubPullRequests.hosts` entry with my GHE location (as `https://github.{redacted}.com/`) and token. After launch, the following appears in the output:

```
[Info] C:\Users\{redacted}\.ssh\config: ENOENT: no such file or directory, open 'C:\Users\{redacted}\.ssh\config'
[Info] Looking for git repository
[Info] Git repository found, initializing review manager and pr tree view.
[Info] Migrating https://github.{redacted}.com/ from githubPullRequests.hosts to keychain
[Info] No GitHub remotes found
[Info] Review> no matching pull request metadata found for current branch master
[Info] Found GitHub remote
```

When the 4th line of the output appears, my hosts entry in `settings.json` has been removed. After all this, I get a message saying I need to authenticate with GitHub, and if I click that, a browser window opens up asking me to authorize VS Code. Clicking okay eventually results in a server error.

**Comment by StanleyGoldman** [comment]
Hey @colin-young so it turns out that the `hosts` configuration went away in version `0.3.0` of the extension. So we can start debugging this issue by just doing away with that.

Have you looked at this url lately? https://github.com/Microsoft/vscode-pull-request-github/wiki#2-is-github-enterprise-supported

**Comment by colin-young** [comment]
I took another look at that url, and after several attempts and a full reboot (likely unrelated and due to corporate security policies and software), I eventually got a "logged in" message. Now I'm getting "Fetching pull requests failed: Only absolute URLs are supported"

I know it worked at one point, and I'm pretty sure I saw that message before.

**Comment by scottwio** [comment]
Having the exact same thing with GHE

**Comment by jaywryan** [comment]
Same issue with GHE 2.13 `Fetching pull requests failed: Only absolute URLs are supported`

**Comment by charliegroll** [comment]
I get the same `Fetching pull requests failed: Only absolute URLs are supported`, too. When I add `https://` to the beginning of the url, it just hangs

**Comment by jaywryan** [comment]
vscode - Version 1.35.1 (1.35.1)
Name: GitHub Pull Requests
GitHub Pull Requests: Version: 0.8.0

[Debug 47974s 836ms] file:///api/v3: GraphQL not supported (Network error: Only absolute URLs are supported)

Is there any other information we can provide to move this along?

**Comment by jaywryan** [comment]
@StanleyGoldman Are you the right resource to look at this issue?  Please help us get this resolved.

**Comment by Romalouz** [comment]
Hello,

Same issue here for Github enterprise with github.vscode-pull-request-github v0.11.2 and vscode v1.38.1 on Windows 10.0.17763
I tried using git clone with ssh and https, the same kind of errors occur:

[Debug 624s 445ms] Unable to resolve remote: HttpError: Only absolute URLs are supported
[Debug 624s 445ms] GitHubRepository> Fetch mentionable users - enter
[Debug 624s 654ms] Review> no matching pull request metadata found for current branch master
[Debug 624s 655ms] Review> Validating state...
[Debug 624s 655ms] PullRequestManager> Displaying configured remotes: origin
[Debug 624s 662ms] Found GitHub remote
[Debug 624s 663ms] GitHubRepository> Fetch metadata - enter
[Debug 624s 663ms] Unable to resolve remote: HttpError: Only absolute URLs are supported
[Debug 624s 855ms] Review> no matching pull request metadata found for current branch master
[Debug 643s 480ms] GitHubRepository> Fetch pull request category is:open review-requested:${user} - enter
[Debug 643s 489ms] GitHubRepository> Fetching all pull requests failed: HttpError: Only absolute URLs are supported

Any idea what is the cause of the absolute URL message?
Is there a way to provide this absolute URL somewhere?

Thanks for the feedback.

**Comment by MartinSmeyer** [comment]
Same issue v0.11.2, vscode v1.38.1 , Linux:
Fetching all pull requests failed: HttpError: Only absolute URLs are supported

**Comment by voodoo144** [comment]
same issue

**Comment by Romalouz** [comment]
Same issue. 
Extension Version: 0.14.0
VS Code: 1.42.1
OS: Windows_NT x64 10.0.17763

**Comment by RMacfarlane** [comment]
We have discontinued support for GitHub Enterprise. https://github.com/microsoft/vscode-pull-request-github/wiki#2-is-github-enterprise-supported
