### ISSUE TITLE
PR web view in different color themes

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode-pull-request-github#111]
Testing https://github.com/Microsoft/vscode/issues/55396 on Ubuntu

Missing contrast in Kimble Dark between the section for user alias and the comment.
Same happens for Monokai

<img width="548" alt="screen shot 2018-07-31 at 3 04 38 pm" src="https://user-images.githubusercontent.com/16890566/43489810-119f9558-94d3-11e8-89c0-70a4881367a1.png">

Too much contrast in Light theme between the section for user alias and the comment

<img width="480" alt="screen shot 2018-07-31 at 3 05 12 pm" src="https://user-images.githubusercontent.com/16890566/43489841-29d89ae8-94d3-11e8-8dcb-f506132ad575.png">

**Comment by misolori** [comment]
This is all addressed in https://github.com/Microsoft/vscode-pull-request-github/pull/154

![image](https://user-images.githubusercontent.com/35271042/44046377-1e412ff8-9ee0-11e8-82ff-044d691d3bfe.png)

![image](https://user-images.githubusercontent.com/35271042/44046404-2e8591ec-9ee0-11e8-87ba-6c883d90c52e.png)
