### ISSUE TITLE
Not working when a VSCode Workspace has Multiple Repos

### ISSUE THREAD

**Issue by mainawycliffe** [Microsoft/vscode-pull-request-github#1111]
Before the April VSCode Update, I was able to to create pull request for my multi-repository workspace. But since then, the extension is always focused on the first repository and changing it under source control has no effect. 
Before, you could change the repository under which to create a pull request by choosing one of your git repos, under Source Control in the activity bar, not the most intuitive approach but it worked. This no longer works.

- Extension version: 0.6.0
- VSCode Version: 1.33.0
- OS: Windows 10

Steps to Reproduce:

1. Update to the latest version of VSCode
2. Open a VSCode Workspace with Multiple Repos
3. Try creating a pull request on any repo other than the first

**Comment by lihuanshuai** [comment]
same to me

**Comment by upugo-dev** [comment]
I am also experiencing this issue. I've got an organisation github account, with multiple repos, each cloned into a vscode workspace. Only the first repo in the alphabetically-sorted list under Source Control Providers is available to the PR extension. Switching the focused repo in the Source Control Provider does not affect what PRS are available/visible in the Github PR extension.

- Windows 10 Home
- VSCode 1.33.0
- GitHub Pull Requests extension 0.6.0

**Comment by RMacfarlane** [comment]
Thanks for reporting this! It looks like the `git` extension is not sending a selection change event when it should be. I'm creating a PR to fix this now.

**Comment by RMacfarlane** [comment]
I've just checked in the change in VSCode, so the fix should be available in tomorrows VSCode Insider's.

**Comment by upugo-dev** [comment]
> I've just checked in the change in VSCode, so the fix should be available in tomorrows VSCode Insider's.

Awesome, thanks! Whats it looking like for the fix to be pulled in to the stable build?

**Comment by RMacfarlane** [comment]
Based on https://github.com/Microsoft/vscode/issues/71830, the next stable build won't be until after May 10th

**Comment by upugo-dev** [comment]
@RMacfarlane ok thanks, not too long to wait. Cheers

**Comment by RMacfarlane** [comment]
Closing this since the fix is now available in Insiders.
