### ISSUE TITLE
GraphQL organization restriction

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-pull-request-github#1114]
Issue Type: <b>Bug</b>

```
Error: GraphQL error: Although you appear to have the correct authorization credentials,
the `Microsoft` organization has enabled OAuth App access restrictions, meaning that data
access to third-parties is limited. For more information on these restrictions, including
how to whitelist this app, visit
https://help.github.com/articles/restricting-access-to-your-organization-s-data/
```

not sure why I get this error but it seems new, cc @queerviolet 

Extension version: 1.98.0
VS Code version: Code - Insiders 1.34.0-insider (56f1b4795fed05677eb82a21dac4fc1ab62d747b, 2019-04-09T05:14:40.620Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.25GB free)|
|Process Argv|-psn_0_57358|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by queerviolet** [comment]
Uhhhh.... Do you suppose maybe the org just turned it on?

@StanleyGoldman @kuychaco Is this something you've seen before?

**Comment by fearthecowboy** [comment]
I'm seeing this too. I just installed the extension and tried to comment on an PR in a repo. 

![image](https://user-images.githubusercontent.com/133736/81420279-9db4f400-9104-11ea-9812-82a1b8af6a4f.png)

Is this something that can only be fixed at the org level?

**Comment by alexr00** [comment]
Closing as I haven't seen this recently.
