### ISSUE TITLE
Authentication fails for nightly build

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode-pull-request-github#1115]
Issue Type: <b>Bug</b>

Currently I can't authenticate for the nightly build (403).

Extension version: 1.98.0
VS Code version: Code - Insiders 1.34.0-insider (56f1b4795fed05677eb82a21dac4fc1ab62d747b, 2019-04-09T05:14:40.620Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.15GB free)|
|Process Argv|-psn_0_57358|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by queerviolet** [comment]
Fixed :)
