### ISSUE TITLE
Feat: Better multi-repo workspace support from within extension

### ISSUE THREAD

**Issue by upugo-dev** [microsoft/vscode-pull-request-github#1116]
As a user, I'd like to be able to switch repos (when in a multi-repo workspace) from within the PR extension, rather than having to do this via the source control menu. This would affect which PR's were 'available' for actions with the extension

As a user, I'd like to be able to see multiple PRs in the extension sidebar menu, grouped by repo

**Comment by upugo-dev** [comment]
related: https://github.com/Microsoft/vscode-pull-request-github/issues/1111

**Comment by RMacfarlane** [comment]
We have recently checked in a change to make the roots of the pull request the repo names in the case of multiple repositories (https://github.com/microsoft/vscode-pull-request-github/commit/b629b113f28050d5f311fae196b4297029eb7c89):
![Screen Shot 2020-08-18 at 10 43 39 AM](https://user-images.githubusercontent.com/3672607/90547045-c6a34700-e13f-11ea-9d5e-d20adfe01c6e.png)
The is more in line with the recent SCM viewlet changes for handling multiple repositories:
![Screen Shot 2020-08-18 at 10 44 50 AM](https://user-images.githubusercontent.com/3672607/90547159-ea668d00-e13f-11ea-9475-67bd1083363f.png)
