### ISSUE TITLE
Instead of a separate node for Description consider showing the description when the parent node is selected

### ISSUE THREAD

**Issue by ramya-rao-a** [microsoft/vscode-pull-request-github#112]
Testing https://github.com/Microsoft/vscode/issues/55396 on Ubuntu

The separate node for Description has the following issues:
- Its an odd person out among its siblings all of whom are files
- The icon for description doesn't really mean description. It means PR.
- When going through the diff, say the user wants to check out the PR, it is not intuitive to the user that they have to first click on description to get to the `Checkout PR` button. They would most likely click not the tree node for the PR expecting something to happen.

**Comment by rebornix** [comment]
Add `upstream/vscode` label here as right now there is no way to figure out when a node is focused or being expanded/collapsed.

**Comment by RMacfarlane** [comment]
@rebornix I think this would be possible using the newer `createTreeView` method instead of `registerTreeDataProvider` - it returns a tree view object that has events for expand/collapsed/select

**Comment by rebornix** [comment]
@RMacfarlane thanks for pointing that out, the APIs should work for detecting. Would that lead to any confusion when we differentiate the behaviors of clicking on the expansion icon and the node title? Usually I simply click on the node title to expand it.

**Comment by alexr00** [comment]
We now do this for the Changes in PR view.
