### ISSUE TITLE
Cant sign in if firefox using vscode:// link

### ISSUE THREAD

**Issue by SuddenGunter** [Microsoft/vscode-pull-request-github#1124]
Loged in in firefox and authorized extension to access my account. But I cant login in extension in firefox: vscode://GitHub.vscode-pull-request-github/did-authenticate?..... -
"The address wasn’t understood"

- Extension version: 0.6.0
- VSCode Version: 1.33.1
- OS: Arch Linux, kernel: x86_64 Linux 5.0.7-arch1-1-ARCH

Steps to Reproduce:

1. Install extension
2. Click sign in button on popup
3. Authorize
4. Try redirect to vscode:// ...

UPD: noticed small text in notification area 'sign in to github'. Clicked there, pasted link - IT WORKS!

**Comment by Ben-Voris** [comment]
Also a problem with Ubuntu 18.04 
VS Code Version: 1.34.0 OS: Linux x64 4.15.0-50-generic snap
Firefox 66.0.5

The workaround worked there too. 

Is https://github.com/Microsoft/vscode/issues/59235#issuecomment-424257036 related?
