### ISSUE TITLE
The editor tab for PR description is permanent i.e not in preview mode

### ISSUE THREAD

**Issue by ramya-rao-a** [microsoft/vscode-pull-request-github#113]
Testing https://github.com/Microsoft/vscode/issues/55396 on Ubuntu

The description web view uses the non-preview mode of the editor tab and the file changes use the preview mode. 

Say I have the description page open, then I click on one of the files to see the diff open in a new editor. When returning to the description page (that is already open), it is blank and there is a considerable lag in populating the page when the machine is seeing a high CPU usage 

An already open tab gives the perception that all data for that editor is already loaded and we are just switching back and forth (even though thats not the case based on our implementation).

I would suggest that the PR description page also use the preview mode. This would solve the perception problem

**Comment by alexr00** [comment]
We are actually moving away from using as much preview mode with editors so I think it is fair to say that we will not change this.
