### ISSUE TITLE
File views do not account for folded lines. 

### ISSUE THREAD

**Issue by PrashanthCorp** [microsoft/vscode-pull-request-github#1130]
- Extension version: 0.6.0
- VSCode Version:1.31.0
- OS:Windows

Steps to Reproduce:

1. Clone the vscode-azurefunctions extension. Then open this PR: https://github.com/Microsoft/vscode-azurefunctions/pull/1204/files
2. View FunctionCreateStepBase.ts. 
3. Look at the line numbers in github web, and the extension. You'll notice that lines are missing, leading to lines of code that don't seem to belong to any class or function.

**Comment by alexr00** [comment]
@PrashanthCorp can you give an example of how the lines should be folded to reproduce this issue? That PR is old so I cannot use it to repro the issue now.
