### ISSUE TITLE
Failure when trying to open merged PR

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-pull-request-github#1132]
Issue Type: <b>Bug</b>

I had a PR checked out that was merged by somebody else. When I tried to open the PR from the `Change in Pull Request` section I got an error. There was no way to get to GH or anything else. I could only recover by checking out master.

Extension version: 1.114.0
VS Code version: Code - Insiders 1.34.0-insider (0fde6619172c9f04c41f2e816479e432cc974b8b, 2019-04-25T05:14:44.969Z)
OS version: Darwin x64 18.0.0

**Comment by Helcaraxan** [comment]
Something along the same lines that I observed. I merged a PR via the plugin, then when the plugin refreshes the PR screen it actually fails to resolve with the pop-up error shown below.

![unresolvable_pr](https://user-images.githubusercontent.com/896592/57016506-69197d00-6c12-11e9-8af6-4dd94aa3143b.png)

But on actual GH the PR definitely exists and is accessible.
![unresolvable_pr_gh](https://user-images.githubusercontent.com/896592/57016507-69197d00-6c12-11e9-80fe-1c4567c6e675.png)

**Comment by garthk** [comment]
Log output:
```plain
[Info] Review> switch to Pull Request #751 - start
[Info] PullRequestGitHelper> Branch origin/branch-name doesn't exist on local disk yet.
[Info] PullRequestGitHelper> Fetch tracked branch refs/remotes/origin/branch-name
[Info] Review> checkout failed #{"message":"Failed to execute git","stdout":"","stderr":"fatal: couldn't find remote ref branch-name\n","exitCode":128,"gitCommand":"fetch"}
[Info] Review> Queuing additional validate state
[Info] Review> Validating state...
[Info] Found GitHub remote
[Info] Review> no matching pull request metadata found for current branch trunk
```
Is there some PR metadata by which the extension could figure out the merge ref and check it out?
