### ISSUE TITLE
Paste not working

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-pull-request-github#1133]
Issue Type: <b>Bug</b>

Paste doesn't work anymore in the Overview page of a PR.

Extension version: 1.114.0
VS Code version: Code - Insiders 1.34.0-insider (0fde6619172c9f04c41f2e816479e432cc974b8b, 2019-04-25T05:14:44.969Z)
OS version: Darwin x64 18.0.0

**Comment by johnpapa** [comment]
I also have this problem. I cannot copy nor paste in the description or comment fields. This makes it a pain to add hyperlinks

**Comment by alexr00** [comment]
I can't repro, so it should be fixed.
