### ISSUE TITLE
GitHub can not see viewlet in the active  bar

### ISSUE THREAD

**Issue by chinaxzy** [microsoft/vscode-pull-request-github#1134]
Issue Type: <b>Bug</b>

when i install this extension ,there is no viewlet in the active bar,i tried to restart  vscode  still not work

Extension version: 0.6.0
VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (2.50GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|

</details>

**Comment by m10x** [comment]
Got the same problem. Same versions.

**Comment by rivetta-fr** [comment]
Me too.

**Comment by ckadluba** [comment]
Same here. With the following configuration.

Version: 1.34.0-insider (user setup)
Commit: 473af338e1bd9ad4d9853933da1cd9d5d9e07dc9
Date: 2019-05-01T00:22:05.899Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

**Comment by RMacfarlane** [comment]
In the current version of the extension, there are 3 conditions that need to be met for the viewlet to show up:
- a folder tracked by git has to be open
- git has to be enabled 
- a remote has to be associated with github

Since this isn't made especially clear, I just merged a PR (https://github.com/Microsoft/vscode-pull-request-github/pull/1117) to have the viewlet just always be shown, with informational messages if one of these conditions isn't met. There may also be a timing issue on startup. We plan to release a new version of the extension on the 16th or 17th.

Can you all report what's in the output panel for `GitHub Pull Request` for you? You can bring up the panel with `F1`, `View: Toggle Output`, and then switch the dropdown to `GitHub Pull Request`.

**Comment by m10x** [comment]
[Info] C:\Users\maxim\.ssh\config: ENOENT: no such file or directory, open 'C:\Users\maxim\.ssh\config'

**Comment by tylerimplom** [comment]
Here my output,

![2019-05-07 08_38_14-Extension_ GitHub Pull Requests - DEV - Visual Studio Code](https://user-images.githubusercontent.com/1770437/57299899-afa02900-70a3-11e9-957e-0b49e15cb0ad.png)

I tried to use code you provided in a different topic for adding a new remote, though I'm not really sure why the origin remote isn't being found?

**Comment by Tatator01** [comment]
except @tylerimplom , I have the same problems and configuration than all above...

**Comment by ElvenSpellmaker** [comment]
Likewise, I get no viewlet:
![image](https://user-images.githubusercontent.com/2286713/57572702-21ff6900-7416-11e9-8066-46ca5dbee73e.png)

I am signed in and the repo has branches and git is working:
![image](https://user-images.githubusercontent.com/2286713/57572708-3e9ba100-7416-11e9-8adb-e1d0a25d7391.png)
![image](https://user-images.githubusercontent.com/2286713/57572748-e74a0080-7416-11e9-875c-7b8d992ee172.png)

**Comment by RMacfarlane** [comment]
In the newest version of the extension (0.7.0), the extension viewlet should now always be visible, and display some information if it is not able to render the list of pull requests. Does using the latest version of the extension resolve the issue? (Note that it requires the latest VS Code, 1.34.0)

**Comment by ElvenSpellmaker** [comment]
It doesn't seem to work for me, I still get similar output in the box as before:
![image](https://user-images.githubusercontent.com/2286713/58321798-10a35d00-7e17-11e9-8674-86e18b064e3b.png)
![image](https://user-images.githubusercontent.com/2286713/58321805-1600a780-7e17-11e9-960d-a483ad81a8c0.png)

**Comment by Tatator01** [comment]
no...the update change ... nothing

**Comment by RMacfarlane** [comment]
@ElvenSpellmaker From the output, it looks like the "githubPullRequests.remotes" setting is currently set to ["origin", "me"], which aren't matching remotes in the current workspace.  Can you double check that these are correct when compared with the remote names from `git remote -v`? You can modify the setting by clicking "Configure remotes..." on the tree.

@Tatator01 Can you share what the output of `git remote -v` is? What is the message you see in the tree?

**Comment by ElvenSpellmaker** [comment]
@RMacfarlane Where shall I run the command from sorry?
I have loads of remotes 🤔

**Comment by RMacfarlane** [comment]
@ElvenSpellmaker From the terminal in VS Code

**Comment by ElvenSpellmaker** [comment]
@RMacfarlane Ahh I never use the integrated terminal (forgot there was one kinda)...
![image](https://user-images.githubusercontent.com/2286713/58344700-5596b600-7e4e-11e9-9f49-e4c5b0d45691.png)

**Comment by Tatator01** [comment]
For git remote -v, result is 
origin  https://github.com/Tatator01/liturgik-web.git (fetch)
origin  https://github.com/Tatator01/liturgik-web.git (push)

**Comment by jacksbox** [comment]
@ElvenSpellmaker I had similar output in the debug window. For me helped this https://github.com/microsoft/vscode-pull-request-github/issues/1142#issuecomment-498630151, maybe for you as well?

**Comment by RMacfarlane** [comment]
With the latest version of the extension, 0.10.0, the pull request tree should now display "Loading..." while git information is being read. This should fix a timing issue on Windows where the tree would display the wrong message. Please try it out and let me know if you still have problems with it, thanks!
