### ISSUE TITLE
Checkout an existing branch

### ISSUE THREAD

**Issue by borekb** [microsoft/vscode-pull-request-github#1135]
I already have a branch of a pull request checked out locally, by previously running a [`hub`](https://hub.github.com/) command:

```
hub pr checkout 123
```

This created `feature-branch` in my local repository.

Now when I go to VSCode, it doesn't realize that this branch is related to a PR – fair enough, it doesn't have enough information about it.

However, I'm missing a way to tell the extension that my `feature-branch` represents PR 123. If I check out the branch via the GitHub Pull Requests sidebar, it creates a new branch. So I end up with this:

```
  master             4475b80e Merge pull request #122 from repo/branch
  feature-branch     e1b1886c Remove unnecessary strtolower
* pr/someuser/123    e1b1886c Remove unnecessary strtolower
```

I would like to end up with this instead:

```
  master             4475b80e Merge pull request #122 from repo/branch
* feature-branch     e1b1886c Remove unnecessary strtolower
```

**Comment by borekb** [comment]
Is `pr/someuser/<number>` a pattern that the extension needs to see to be able to recognize branches representing pull requests? That would make the implementation of this feature request tricky...

**Comment by RMacfarlane** [comment]
Thanks for reporting this, this sounds like a bug. The extension should try to do what you describe already.

The `pr/someuser/<number>` pattern should just be the default when it doesn't detect an existing branch, we do however write a different key value pair (`github-pr-owner-number = "<repo>#<pr number>"`) to the .git/config file

**Comment by borekb** [comment]
Does it make a difference that the branch was coming from a fork, i.e., non-`origin` remote?

**Comment by RMacfarlane** [comment]
Yep, you're exactly right. We have a bug with how we're handling those remotes. Thanks!
