### ISSUE TITLE
Only works in one window.

### ISSUE THREAD

**Issue by overflow** [microsoft/vscode-pull-request-github#1136]
- Extension version: 0.6.0
- VSCode Version: 1.33.1
- OS: Debian Linux  Stable

Steps to Reproduce:

1. Use and connect in a window
2. Open a new window with a different workspace.

**Comment by RMacfarlane** [comment]
Hey @overflow can you include some more details?

Does the extension consistently work for some workspaces and not others? In the different workspace where it doesn't run, can you run `git remote -v` in the terminal?

**Comment by RMacfarlane** [comment]
I'm closing this issue because it needs more information but hasn't had any recent activity. To reopen it, please provide more details. Thank you!
