### ISSUE TITLE
Validation failed

### ISSUE THREAD

**Issue by AAverin** [microsoft/vscode-pull-request-github#1149]
Issue Type: <b>Bug</b>

I keep getting this error even though I have logged in to my Github account in VSCode:

[Info] GitHubRepository> Creating pull requests failed: {"message":"Validation Failed","errors":[{"resource":"PullRequest","field":"head","code":"invalid"}],"documentation_url":"https://developer.github.com/v3/pulls/#create-a-pull-request"}

Extension version: 0.6.0
VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|../apps-backend-news-article-push|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by ScottAgirs** [comment]
Any updates on this? Perhaps just a misconfiguration or something? I'm having the same issue

**Comment by alexr00** [comment]
I was also seeing this issue, but I'm no longer seeing it. Closing as resolved.
