### ISSUE TITLE
Add setting to hide the GitHub username + icon from activity bar 

### ISSUE THREAD

**Issue by nikitavoloboev** [microsoft/vscode-pull-request-github#1151]
I want to be able to hide this from activity bar:

![2019-05-12 at 22 02](https://user-images.githubusercontent.com/6391776/57587201-98c56080-7501-11e9-9b91-3385a718bc31.png)

I believe it is added as result of using the extension.

Thanks.

**Comment by nikitavoloboev** [comment]
Is this possible to do?

**Comment by RMacfarlane** [comment]
@nikitavoloboev This is possible, I'm not sure if we want to do this. The VS Code team has been talking about adding a feature to control visibility of items in the status bar the same way as from the side bar, by right clicking the bar and unchecking items. Let's see if something like that makes it onto the next VS Code iteration plan

**Comment by RMacfarlane** [comment]
Hey @nikitavoloboev, hiding status bar items was just added in the latest release of VS Code: https://code.visualstudio.com/updates/v1_36#_hide-individual-status-bar-items

Closing since this has been implemented there. Thanks!
