### ISSUE TITLE
login notification doesn't appear

### ISSUE THREAD

**Issue by JurijTSL** [microsoft/vscode-pull-request-github#1158]
^^^^^^^^^^^^^^^^^^^^^^^^^^^
Read

**Comment by RMacfarlane** [comment]
Hey @jurijtsl, a couple of questions to help investigate:
- What OS are you using?
- Is this the most recent version of the extension?
- Can you press `F1`, then run `View: Toggle Output` and choose `GitHub Pull Requests from the dropdown and report what's in the logs?

**Comment by cloudtagger** [comment]
I have the same problem.
OSX Mojave 10.14.5
extension version 0.7.0
vs code version 1.34
output just says...
[Info] /Volumes/Users/alain/.ssh/config: ENOENT: no such file or directory, open '/Volumes/Users/alain/.ssh/config'
[Info] Looking for git repository
nothing else

**Comment by littl3viking** [comment]
Same problem here.

Output:
[Info] C:\Users\littl\.ssh\config: ENOENT: no such file or directory, open 'C:\Users\littl\.ssh\config'

Windows 10
VS Code 1.35.1
Extension version 0.8.0

**Comment by RMacfarlane** [comment]
This should already be fixed in the latest version of the extension (0.12.0). If you run into this problem again, please open a new issue. Thank you!

**Comment by ebubekirduman** [comment]
Hello, I am using version 0.12.0. I'm having the same problem. what is the solution?
