### ISSUE TITLE
Missing refresh button?

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-pull-request-github#1161]
I thought the PR view in the scm viewlet used to have a refresh button, but today I assigned a new PR to myself then was unable to get it to show up in the scm viewlet

![image](https://user-images.githubusercontent.com/323878/57876546-6e59f880-77ca-11e9-9b3f-c5f506bc2f36.png)

**Comment by RMacfarlane** [comment]
Hmm, I'm still seeing a refresh button there. Could you also send a list of other extensions you have enabled? I'm wondering if there could be some collision of "when" clauses for which view it gets shown on

**Comment by roblourens** [comment]
It reappeared noooo

**Comment by RMacfarlane** [comment]
I haven't been able to reproduce this - let me know if you see this again in the latest version of VSCode.
