### ISSUE TITLE
Notification saying "Error" while checking out PR

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode-pull-request-github#1165]
[ghpr.log](https://github.com/microsoft/vscode-pull-request-github/files/3192488/ghpr.log)
Issue Type: <b>Bug</b>

After clicking "Checkout" on the Discussion page, I received several notifications reading just "Error".

Attaching dev console log

Extension version: 1.135.0
VS Code version: Code - Insiders 1.34.20-insider (e83e24a0c9225becd7341e56952177a20d5d4629, 2019-05-15T18:06:45.467Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (6.90GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by RMacfarlane** [comment]
I haven't been able to reproduce this, from looking at the log, I think the problem may have been with the way we dispose comments on the VSCode side. There have been some changes there that may have fixed this
