### ISSUE TITLE
How to disable word based suggestions in comment boxes?

### ISSUE THREAD

**Issue by borekb** [microsoft/vscode-pull-request-github#1166]
Is there a special "language" for the comment boxes so that I can do something like this?

```json
{
  "[pull-request-comments]": {
    "editor.wordBasedSuggestions": false
  }
}
```

**Comment by RMacfarlane** [comment]
The comment boxes are markdown, but are not correctly honoring some markdown settings right now: https://github.com/microsoft/vscode-pull-request-github/issues/917

**Comment by borekb** [comment]
Ah, makes sense, I'll watch #917 then.
