### ISSUE TITLE
Add ability to copy link(s) to PR and commits

### ISSUE THREAD

**Issue by tnrich** [microsoft/vscode-pull-request-github#1172]
I often want to send a link of the PR I just made to my co-workers who I've requested to review it. Unfortunately it is a little difficult to do that right now. It would be awesome if there were a way to copy the link to the github PR from this view in vscode: 

![image](https://user-images.githubusercontent.com/2730609/58217090-0cabf980-7cb6-11e9-8653-f2dd5e6e01db.png)

Currently I have to actually click the link and then copy the link from the browser window that opens. 

Love the extension in general! 
Thanks!

**Comment by sh-tech** [comment]
I think so too 👍

**Comment by phatmann** [comment]
The Jira extension has a copy link icon next to their links. Works well and looks clean. We should do the same.

**Comment by phatmann** [comment]
Another (easier?) solution is to add a Copy Link command to the contextual menu for PRs in the Explorer.
