### ISSUE TITLE
"No GitHub repositories found." after updating to 0.0.7

### ISSUE THREAD

**Issue by Logerfo** [microsoft/vscode-pull-request-github#1178]
# Installation
- Extension version: 0.7.0
- VSCode Version: 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
- OS: Windows 10 Pro 1903 (Windows_NT x64 10.0.18362)

# Description
I tried to use a new token, but nothing seems to have changed.

# Screenshot
![image](https://user-images.githubusercontent.com/19306384/58425935-8c004b00-8071-11e9-9423-031bbe053ed3.png)

**Comment by ramya-rao-a** [comment]
I see the same. The output channel has the below

```
[Info] C:\Users\ramyar\.ssh\config: ENOENT: no such file or directory, open 'C:\Users\ramyar\.ssh\config'
[Info] Looking for git repository
[Info] Git repository found, initializing review manager and pr tree view.
[Info] No GitHub remotes found
[Info] Review> no matching pull request metadata found for current branch master
[Info] Found GitHub remote
```

**Comment by Logerfo** [comment]
FWIW, I'm using 0.8.0 and can't reproduce the issue anymore.

**Comment by ramya-rao-a** [comment]
I see the issue in the latest 0.8.0 version on the latest Insiders

**Comment by alethenorio** [comment]
I ran into this issue myself. I was able to overcome the problem by creating an ssh config file which I did not have (under `$HOME/.ssh/config`)

After this the plugin started working

**Comment by RMacfarlane** [comment]
This should already be fixed in the latest version of the extension (0.12.0). If you run into this issue again, please open a new issue. Thank you!

**Comment by durdenx** [comment]
It doesn't work for me. Is there anything to do to get logged in to github ?

**Comment by RMacfarlane** [comment]
@durdenx The extension should prompt you to log in when you open a folder that has a remote pointing to GitHub. If you have problems with the sign in process, it's also possible to manually provide a token following the steps here: https://github.com/microsoft/vscode-pull-request-github/wiki#personal-access-token-authentication

If you don't see a prompt to sign in or "Sign in to GitHub" in the status bar at the bottom, please file a new issue and include the text of the GitHub pull request view (from clicking on the icon in the activity bar), and the result of running `git remote -v` in the folder you open.
