### ISSUE TITLE
Weird line above the comment

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode-pull-request-github#118]
Testing https://github.com/Microsoft/vscode/issues/55396 

<img width="1053" alt="screen shot 2018-07-31 at 3 55 32 pm" src="https://user-images.githubusercontent.com/16890566/43491697-66a5bc38-94da-11e8-826c-b8e713284084.png">

**Comment by rebornix** [comment]
We can probably add "Start discussion/conversation" in the title bar for the new comment widget.

**Comment by RMacfarlane** [comment]
"Start discussion" was added in https://github.com/Microsoft/vscode/commit/8eeeed30d51f44e6a326a859b4608395c245d344, but the text needs to be localized

**Comment by RMacfarlane** [comment]
Localized with https://github.com/Microsoft/vscode/commit/32cb4411058c0301f22009a25c7fbbb6581a31b9

**Comment by misolori** [comment]
@RMacfarlane thanks, I'll avoid adding text via CSS.
