### ISSUE TITLE
Unable to add reviewers to Pull Request in PR Description View

### ISSUE THREAD

**Issue by GeorgeWL** [microsoft/vscode-pull-request-github#1181]
Issue Type: <b>Bug</b>

Steps to Reproduce:

1. Attempt to add Reviewers to a Private Repo Pull Request by pressing the plus symbol in the pull request
2. Action doesn't happen, notification of 
```
Cannot read property 'filter' of undefined
Source: Github Pull Requests (Extension)
```

On inspection with Developer Console of VSCode, the error comes from:
```js
onDidNotificationChange(e) {
     0 === e.kind && (this.triggerAriaAlert(e.item),
    e.item.severity === r.Severity.Error && (e.item.message.original instanceof Error ? console.error(e.item.message.original) : console.error(o.toErrorMessage(e.item.message.value, !0))))
}
```

Extension version: 0.7.0
VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.74GB (16.84GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/george/dev/lender-admin|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by curtisgibby** [comment]
A bit of additional info: the first time or two I attempted to use this functionality, it worked as expected, giving me a checklist of possible reviewers. Now, every time, I get the error message described above.

**Comment by GeorgeWL** [comment]
@RMacfarlane why has this been closed? I don't see a fix in the PRs.

**Comment by RMacfarlane** [comment]
@GeorgeWL I closed this in commit https://github.com/microsoft/vscode-pull-request-github/commit/5479c4e8e8de35e19623098757d4cbb9cd9e0b35. A version with the fix hasn’t been released yet

**Comment by GeorgeWL** [comment]
ah was confused, the usual process I've seen the devs do on this repo was to close with a comment of something like `resolved in `https://github.com/microsoft/vscode-pull-request-github/commit/5479c4e8e8de35e19623098757d4cbb9cd9e0b35
