### ISSUE TITLE
Set Default Values for PRs

### ISSUE THREAD

**Issue by GeorgeWL** [microsoft/vscode-pull-request-github#1186]
Issue Type: <b>Feature Request</b>

I would like settings in Preferences to be added to add Default Values, specifically;

- Automatic Self-assign: `boolean`
- Automatically Set reviewers as `['username1','username2','username3']` - error if username isn't assignable to current request
- Automatically set labels/tags `['label1', 'label2', 'label3']` - get list from the GH api to populate

Extension version: 0.7.0
VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17763

**Comment by GeorgeWL** [comment]
👍

**Comment by alexr00** [comment]
We already have the first one now: `githubPullRequests.assignCreated`.

**Comment by GeorgeWL** [comment]
I've also realised that "automatically add reviewers" isn't really needed, cause of CODEOWNERS now being a standardized convention for GitHub

So really the only that might be helpful is auto-labeling
