### ISSUE TITLE
Boolean Setting to Open Modal and Request Issue Name

### ISSUE THREAD

**Issue by GeorgeWL** [microsoft/vscode-pull-request-github#1187]
Issue Type: <b>Feature Request</b>

Needs a setting to be added that instead of using the message from the latest commit (which can often be something less-than-useful like "cleanup code") opens a modal just before openining the Decription view that requests the user to input a Title for the pull request.

Simple boolean setting, default to off, would make sense to notify the user of this option on first install.

Extension version: 0.7.0
VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17763

**Comment by alexr00** [comment]
The "Create PR" view solves this.
