### ISSUE TITLE
Unable to view Pull Requests in macOS

### ISSUE THREAD

**Issue by meaghanlewis** [Microsoft/vscode-pull-request-github#119]
I'm not sure if I'm doing something wrong, but I followed the steps to get setup and can't see Pull Requests for any repository.

Pressing the refresh symbol, I see the error `command 'pr.refreshList' not found`

<img width="1029" alt="no pr s found" src="https://user-images.githubusercontent.com/10103121/43493683-0e905760-94e4-11e8-9fc3-6287d06050c5.png">

Let me know if I can provide more information. Also wondering if any other Mac user is having this problem.

**Comment by RMacfarlane** [comment]
After reproducing it once I haven't been able to see it again :/

**Comment by meaghanlewis** [comment]
Thanks @RMacfarlane that fixes this error for me!
