### ISSUE TITLE
Feature Request: Automatic Refresh

### ISSUE THREAD

**Issue by smiller171** [microsoft/vscode-pull-request-github#1194]
Currently I have to hit the refresh button to check on the state of my automated tests. This is a huge barrier to keeping my full PR flow within VSCode, especially since I have to scroll to the top to hit refresh, then scroll all the way back down. In the browser these updates are automatic and don't need a full page refresh.

As a stopgap, a hotkey (ctl/cmd+r?) would make the experience much smoother than it is now.

**Comment by mplebanski** [comment]
+1

**Comment by mplebanski** [comment]
I believe you can create a hotkey for that because a command is exposed under Refresh Pull Requests.

**Comment by burkeholland** [comment]
Noted in scenario https://github.com/github/codespaces/issues/1608

**Comment by burkeholland** [comment]
This is now working in 2020.11.3841 (Nightly)
