### ISSUE TITLE
Comments are posted, but displays an error

### ISSUE THREAD

**Issue by robertmcodes** [microsoft/vscode-pull-request-github#1197]
Issue Type: <b>Bug</b>

![image](https://user-images.githubusercontent.com/23535075/58763790-8e5d1c00-852d-11e9-87cc-a5e50020e68b.png)

1. Begin a review
2. Commit on PR
3. Approve

Extension version: 0.6.0
VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:55:35.507Z)
OS version: Linux x64 5.0.0-15-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 3816)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 0|
|Memory (System)|31.13GB (20.36GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by alexr00** [comment]
I'm not able to repro this issue, but if you're still seeing it please ping this issue.
