### ISSUE TITLE
all github commands cannot be found.

### ISSUE THREAD

**Issue by Pooslice81** [microsoft/vscode-pull-request-github#1198]
i've installed github pull requests from within vs code. 
i received no github authentication prompts.
whenever i try to create a pull request, i get the following error: command 'pr.create' not found
trying to run any other GPR command gives the same type of error (not found error). 

- Extension version: 0.7.0
- VSCode Version: 1.34.0
- OS: Windows 10 (Windows_NT x64 10.0.17763)

Steps to Reproduce:

1. Install Github Pull Repository
2. Click on "+" to create a new pull request
![Screenshot - 3_06_2019 , 10_41_12 AM](https://user-images.githubusercontent.com/34494016/58769638-24577c00-85ec-11e9-8b0e-2f991c30c82e.png)

**Comment by MattWThomas** [comment]
I have had this same issue for a few says also. I was just about to report it. I have tried enabling/disabling and installing/uninstalling. There are still no commands found. 

I have also tried the option to Manually Provide an Authentication response. This gives an error
> command 'auth.inputTokenCallback' not found

I have also tried setting the `githubPullRequests.hosts` setting. This does not solve the problem.

**Comment by RMacfarlane** [comment]
@Pooslice81 @MattWThomas What do you see in the PR tree?
![tree](https://user-images.githubusercontent.com/3672607/58839720-c771bb00-8617-11e9-98da-2d7b205d7bdf.png)

The extension starts initializing some pieces on startup, but doesn't finish registering commands until a folder is open that has git. We should remove the "+" button and commands until this registration is finished.

**Comment by Pooslice81** [comment]
@RMacfarlane , initially, the PR tree was as empty as your screenshot. 
I then manually opened a folder that has git. 
this added some categories into the PR tree. 

![Screenshot - 5_06_2019 , 8_38_56 AM](https://user-images.githubusercontent.com/34494016/58918421-8db2c880-876d-11e9-9068-6a1b667b9796.png)
