### ISSUE TITLE
PR description view should show complete comment threads

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode-pull-request-github#120]
Testing https://github.com/Microsoft/vscode/issues/55396 on Ubuntu

- Open a PR where there is a comment on a change and further replies on the same comment
- The PR description page shows only the first comment, the file diff view shows the complete thread

**Comment by rebornix** [comment]
Duplicate of https://github.com/Microsoft/vscode-pull-request-github/issues/71#issuecomment-400525734, let's track it there.
