### ISSUE TITLE
Unable to add comment 

### ISSUE THREAD

**Issue by kuychaco** [microsoft/vscode-pull-request-github#1200]
- Extension version: 0.6.1 (on branch, commit 7e992d982e1ba0b3b656358d38f5d467796089c3 -- try repro-ing on master later)
- VSCode Version: Version 1.35.0-insider
- OS: MacOS High Sierra

<img width="964" alt="_Extension_Development_Host__-_src_github_credentials_ts_—_Untitled__Workspace_" src="https://user-images.githubusercontent.com/7910250/58840813-00ac2a00-861c-11e9-912f-d805b039659b.png">

Clicking "Add Comment" does nothing

**Comment by RMacfarlane** [comment]
Can you check if you're on the most recent version of Insiders? This should be fixed: https://github.com/microsoft/vscode/issues/74668

**Comment by kuychaco** [comment]
Yup, it's fixed! 🙏
