### ISSUE TITLE
Scroll position is not maintained

### ISSUE THREAD

**Issue by kuychaco** [microsoft/vscode-pull-request-github#1202]
Just had my first round of addressing code review comments in VSC. I took note of some areas of friction for me, and opportunities for us to improve the UX.

First off, I’m definitely liking the fact that there’s so much functionality that allows me to stay in the editor and in the context of my code! :sparkles: What we have is pretty sweet so far.

That said, I found myself choosing/having to go to dotcom for some things and doing some extra clicking/navigating around. Here’s when/why:

It’s not super smooth navigating from seeing a review comment in the overview page, to making changes in the code to address the comment. I have to click to the read-only editor that displays the inline comment, and then manually open the file:line-number to make the change. If there’s a more efficient way, it’s not super discoverable.

I noticed myself wanting to reply to a comment from the overview page, and feeling a bit annoyed that I had to click into the read-only editor to simply reply, and lose the context I was in while on the overview page.

This was exacerbated by the fact that when I go back to the overview page, the webview reloads and puts me back at the top. So I have to do lots of scrolling to go back to where I was while responding to review comments. I also find this irksome while testing changes during my normal development process.

Lastly, replying to a comment isn’t working for me. Might just be my setup (I’m currently on a branch, will test on master once I’m done addressing all of these code review comments). Curious to hear if others can repro this locally… https://github.com/microsoft/vscode-pull-request-github/issues/1200

**Comment by rebornix** [comment]
> It’s not super smooth navigating from seeing a review comment in the overview page, to making changes in the code to address the comment. I have to click to the read-only editor that displays the inline comment, and then manually open the file:line-number to make the change

Agree that if the pr is checked-out, we should open the file in local workspace instead of a readonly diff view

> I noticed myself wanting to reply to a comment from the overview page, and feeling a bit annoyed that I had to click into the read-only editor to simply reply,

If I understand correctly, you would expect an inline comment editor in the overview page, right?

> This was exacerbated by the fact that when I go back to the overview page, the webview reloads and puts me back at the top.

Can be fixed after 1.35 release https://github.com/microsoft/vscode-pull-request-github/pull/1201

**Comment by alexr00** [comment]
> I have to click to the read-only editor that displays the inline comment, and then manually open the file:line-number to make the change. If there’s a more efficient way, it’s not super discoverable.

Just fixed this with https://github.com/microsoft/vscode-pull-request-github/issues/5378

> I noticed myself wanting to reply to a comment from the overview page, and feeling a bit annoyed that I had to click into the read-only editor to simply reply, and lose the context I was in while on the overview page.

This is still the case. 

> This was exacerbated by the fact that when I go back to the overview page, the webview reloads and puts me back at the top. 

Looks like there's a bug here, which I will fix.

**Comment by alexr00** [comment]
Using this issue to fix the scroll bug. To repro:
1. Open a PR description
2. Scroll 
3. Open another file
4. Open the same PR description again from the same entry point that you opened it from before
5. Your scroll position should be preserved.
