### ISSUE TITLE
Serialize the overview page

### ISSUE THREAD

**Issue by queerviolet** [microsoft/vscode-pull-request-github#1203]
Currently, when you reload your window, you lose the PR overview panel if it's open.

I find that quite annoying, especially if I'm in the middle of a review or (more often) making changes, and I've set up the columns so the overview is visible. I believe we can fix this by [registering a serializer](https://code.visualstudio.com/api/extension-guides/webview).

**Comment by alexr00** [comment]
Closing as out of scope since I don't think we're going to work on this any time soon.
