### ISSUE TITLE
Audit & manicure CSS for overview page

### ISSUE THREAD

**Issue by queerviolet** [microsoft/vscode-pull-request-github#1204]
In the course of #1096, we restructured the HTML a bit and we were (read: I was) a bit careless about removing unnecessary styles and so on. This is a tracking bug to:
  - [ ] Do a styling pass and clear out the unused cruft
  - [ ] Consider adding colors in a theme-responsive way
  - [ ] Consider CSS modules
  - [ ] Make it prettier

**Comment by RMacfarlane** [comment]
@queerviolet I filed a couple of issues with styling things as I noticed them:
https://github.com/microsoft/vscode-pull-request-github/issues/1156
https://github.com/microsoft/vscode-pull-request-github/issues/1199

Feel free to close those in favor of tracking them here

**Comment by RMacfarlane** [comment]
Closing since I think there is not currently an work to do here
