### ISSUE TITLE
Cannot add keybinding to create a comment

### ISSUE THREAD

**Issue by snoozbuster** [microsoft/vscode-pull-request-github#1205]
- Extension version: 0.7.0
- VSCode Version: 1.34.0
- OS: macOS Mojave

Steps to Reproduce:

1. Bind `pr.replyComment` to a key
2. Open a file with a diff
3. Click on a line and use the keybinding

Expected behavior:
1. Comment thread on the selected line is created or replied to, as if the line gutter had been clicked

Actual behavior:
1. Error alert `Cannot read property 'createOrReplyComment' of undefined` appears
![image](https://user-images.githubusercontent.com/5778364/58848382-34e31300-863b-11e9-8aec-6c96008326f4.png)

**Comment by snoozbuster** [comment]
if I try to create the keybinding through the vim extension, as I was originally trying to do, a slightly different error is given:
![image](https://user-images.githubusercontent.com/5778364/58848416-5c39e000-863b-11e9-9cfb-3c1fb9434247.png)

**Comment by RMacfarlane** [comment]
@snoozbuster Sorry the documentation isn't clear on this, can you try binding `workbench.action.addComment` instead?

**Comment by snoozbuster** [comment]
Ah yes, that does work. I searched for "comment" in the keybindings but only found `editor.action.addCommentLine` for some reason... I see it now though, thank you!
