### ISSUE TITLE
Dates on comment not visible in the file diff view

### ISSUE THREAD

**Issue by ramya-rao-a** [microsoft/vscode-pull-request-github#121]
Testing https://github.com/Microsoft/vscode/issues/55396 on Ubuntu

Dates/timestamp not visible in the comments below

<img width="845" alt="screen shot 2018-07-31 at 5 47 00 pm" src="https://user-images.githubusercontent.com/16890566/43494870-c1e90960-94e9-11e8-977c-08eea4520eda.png">

**Comment by alexr00** [comment]
We now have timestamps in the comments.
