### ISSUE TITLE
Pull request extension should try to be a dynamic extension

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-pull-request-github#1216]
1. Uninstall the Pull request extension from vscode
2. Notice how vscode must be reloaded. This is due to the fact that Pull request extension is not dynamic. Not sure what would it take to make the transition but if possible we should make the PR extension dynamic

More about dynamic extension points can be found here https://github.com/Microsoft/vscode/issues/66574
I had to do this for some debug contribution points so I can help if you figure out that you can and want to do this.

fyi @rebornix @RMacfarlane

**Comment by RMacfarlane** [comment]
Extension does not require reload after installation now
