### ISSUE TITLE
Long comments are not wrapping in the comments panel

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode-pull-request-github#122]
Testing https://github.com/Microsoft/vscode/issues/55396 on Ubuntu

<img width="921" alt="screen shot 2018-07-31 at 6 24 47 pm" src="https://user-images.githubusercontent.com/16890566/43495853-29eb9488-94ef-11e8-9bd0-cab113408545.png">

**Comment by RMacfarlane** [comment]
Now doing what the problems panel does and using ellipsis on overflow. Since the full comment can be navigated to just by clicking and could be very long, only showing the first line of it in the panel seems fine

**Comment by ramya-rao-a** [comment]
Am using verion 0.0.8 I dont see the ellipsis

![image](https://user-images.githubusercontent.com/16890566/43872492-c63e00c6-9b36-11e8-9c54-16f232ea3a46.png)

**Comment by RMacfarlane** [comment]
Oh this is a change in core, so it should be fixed after updating insiders tomorrow
