### ISSUE TITLE
We couldn't find commit

### ISSUE THREAD

**Issue by scrossan-crown** [microsoft/vscode-pull-request-github#1220]
- Extension version: 0.8.0
- Version: 1.36.0-insider (user setup)
- Commit: 7a5bca9fafbbb23de289179be95e9c4832540c02
- Date: 2019-06-06T10:06:28.360Z
- Electron: 4.2.3
- Chrome: 69.0.3497.128
- Node.js: 10.11.0
- V8: 6.9.427.31-electron.0
- OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Check out a pull request
2. Click a file in the `CHANGES IN PULL REQUEST` view

```
We couldn't find commit 22c98d368fe556a7817496e69b8f2ee6a39e8789 locally. You may want to sync the branch with remote. Sometimes commits can disappear after a force-push
```

**Comment by eps1lon** [comment]
Got the same error message repeatedly. Worked after upgrading to `vscode@1.36.0`

**Comment by scrossan-crown** [comment]
Still having this issue on vscode@1.36.1 and extension@0.9.1

**Comment by RMacfarlane** [comment]
Should be fixed with https://github.com/microsoft/vscode-pull-request-github/commit/6f5b6051ed11b9c0b4c201d17a12d6316e70089a
