### ISSUE TITLE
Proposal: Improve user experience for code review receivers

### ISSUE THREAD

**Issue by vanessayuenn** [microsoft/vscode-pull-request-github#1222]
After having used the GitHub pull request extension for VS Code for a couple of weeks, I have noticed while we have a lot of great features, some are not presented in a way that is easy to use. @kuychaco, for example, wrote about her frustration with acting on the code review feedback in #1202. There are many ways we can improve the user experience of this extension, but in this issue, let's focus on discussing the workflow for a user who is a **code review receiver**.

#### 1. File-driven workflow vs comment-driven workflow

Our current UX favours a file-driven workflow, which works well for code review *authors*, who would likely go through each changed file in a PR and leave comments as they go. File-driven review comment workflow is not suitable for code review *receivers*, though. Once a user receives their first code review comment, their workflow of reviewing and acting on code review feedback becomes rather comment-driven. With our current UI, comments are difficult to locate, especially within PRs that consist of a long list of changed files; and it is not immediately clear that the ◆ decorations in filenames imply those files contain comments.

#### 2. Inconsistency between "GitHub Pull Requests" and "Changes in Pull Request"

Within the extension viewlet, there are two sections — one (titled "GitHub Pull Requests") contains all the GitHub pull requests associated with the working repo and the other (titled "Changes in Pull Request") contains data associated with a currently checked out PR. Conceptually, a checked out PR is just one of all the PRs; as a user, I would expect the checked out PR node to contain the same information as any PR node in the "GitHub Pull Requests" section, and I would expect the same model of navigation for both sections. In reality, however, the two sections contain similar information that is presented with different data hierarchies, resulting in two navigation models that are just similar enough to be confusing. 

#### 3. Inconsistent ability to edit a checked out PR

One of the biggest advantages of doing code review within an editor is that users are able to read code review comments, immediately act on the feedback by making changes directly to the files on disk, test the changes in their dev environment — all without having to leave the editor! In the pull request extension, clicking on a file from the list of PRs in "GitHub Pull Requests" can only open read-only editor, even when the PR branch has already been checked out. In order to act on the code review feedback, a user will have to know to open the file from the "Changes in Pull Request" section to get to a non-read-only editor. 

### Proposed solution

With these usability problems outlined, I would like to propose we add a "Comment Threads" tree node in each PR node, and unify how information is presented in "GitHub Pull Requests" and "Changes in Pull Request". To illustrate, let's pretend a user has `PR #1` branch checked out, and the tree view will look something like this:

    GITHUB PULL REQUESTS
    > ✓ [PR title] #1 by @x_user
    	Description
    	> Files (2)
    		> file1                             ◆, M
    		> file2                             ◆, M
    	> Comment Threads (3)
    		> file1 [2] @y_user: this is great add...
    		> file1 [53] @y_user: can we rename th...
    		> file2 [233] @z_user: how does this w...
    > [PR title] #2 by @someoneelse
    > [PR title] #3 by @someoneelse
    ...
    
    CHECKED OUT PULL REQUEST
    [PR title] #1 by @x_user
    	Description
    	> Files (2)
    		> file1                             ◆, M
    		> file2                             ◆, M
    	> Comment Threads (3)
    		> file1 [2] @y_user: this is great add...
    		> file1 [53] @y_user: can we rename th...
    		> file2 [233] @z_user: how does this w...
    	> Commits (37)
    		> ...

#### Explanation of behaviour

- "Files", "Comment Threads", and "Commits" will have an indicator of how many elements each contains.
- Comment Threads section will show each thread (not each comment) as one tree node.
- Clicking on a comment node will open the file diff view (if it's not already open) and scroll to the respective inline comment.
- As long as a PR is checked out, clicking on a PR's changed file node from either "GitHub Pull Requests" section or "Checked Out Pull Request" section will open an editable diff view.
- "Changes in Pull Request" is renamed to "Checked Out Pull Request" to reflect more accurately what information that section contains (another contender is "Current Pull Request).

### In search for... feedback

👀 CC: @queerviolet @kuychaco @smashwilson @meaghanlewis @RMacfarlane @rebornix 

Any feedback is welcome, of course. But because I have not dug deeply into the code base yet, I would appreciate any additional technical context to my proposal, specifically if anything is simply not possible to do without making changes to the API, or is more complicated to implement than it appears, etc. I am also interested in knowing if we can replace the ◆ comment indicator to an icon that is more universally understood to mean "comment".

**Comment by JReinhold** [comment]
I agree with all points, especially point 1 and 3. I didn't even know that ai could open a writable editor from the "Changes in Pull Request", so I've always opened files manually when I had to edit them, based on a comment from a reviewer.

**Comment by brianjmurrell** [comment]
I find the current workflow quite cumbersome.  I'm not even sure where I'm supposed to find "Changes in Pull Request".  I just open "Created By Me", find the PR I want to read the comments on and make changes to and then look for the files with the diamond as noted above.  However from there, the rest of the current workflow is just too difficult to even use.

In the PR I've selected, if I open the file the comment was made in, I don't seem to be able to edit in that view. It says the file is read-only. I can open a writable copy in a new tab I guess. But navigating back and forth between the comments in the Github view and the writable view is cumbersome at best. Unless I don't know how to do that properly.

Also, I don't seem to be able to Resolve comment threads in VS Code.

**Comment by JustinGrote** [comment]
This is incredibly frustrating that I can't just make a change right here when going thru PR review comments:
![image](https://user-images.githubusercontent.com/15258962/139879520-cdbc60d6-cd82-4117-b13d-03eb051537c6.png)

**Comment by alexr00** [comment]
We have since added a whole "Comments" view, which allows for easy navigation and filtering of comments.
