### ISSUE TITLE
Proposal: local pull request drafts

### ISSUE THREAD

**Issue by smashwilson** [microsoft/vscode-pull-request-github#1226]
When you invoke the `GitHub Pull Requests: Create Pull Request` or `GitHub Pull Requests: Create Draft Pull Request` commands, a new pull request is immediately opened on GitHub with an empty description and a title auto-generated from the HEAD commit.

I feel this isn't ideal because:

1. While you can edit the title and description after the fact easily, if any of that repository's watchers have email notifications enabled, the email notification will contain only the empty, autogenerated version.
2. Socially, pull request creation is a vulnerable moment for the creator, especially when opening one on a repository you haven't contributed to before. First impressions are hard! One way to ease this pressure is to provide the pull request creator as many opportunities to proofread and provide context as possible.

## Proposed changes

:bulb: Let's allow users to have a _local pull request draft_ they can work within before creating a pull request on GitHub.

* Change the `PullRequestChangesTreeDataProvider` to always be visible, rather than appearing only in review mode.
* While the repository's default branch is checked out, it displays an informative message and allows you to create a new branch to begin work on a new feature.
* While HEAD is a non-default branch that is not associated with an open pull request, it displays child nodes for a local pull request draft. This is a persistent, machine-local pull request model that the user can interact with as though it's a real one: they can set the title, draft a description, assign labels and reviewers, or add review comments just as they can on GitHub-backed pull requests.
  * Naturally, some features like status checks will be unavailable. We can disable these UI elements.
  * Rather than offering merge or close buttons, we offer buttons to create the PR in draft or non-draft mode. When clicked, these controls create the pull request in its drafted state: with its drafted title and description and labels, creating any pending review comments into a review, and so on.
* While HEAD is a branch that is associated with an open pull request, we display the tree as it is today.

## Challenges

We'll need the display for "local draft" pull requests to look similar enough to "real" ones that it's familiar and easy to navigate, but distinct enough that we avoid causing confusion about the current pull request's state. The absence of an assigned number and a dedicated state badge will help here, but we may wish to have a stronger signal.

It may also be confusing to introduce another layer of "draft" state that a pull request can be in. We might want to brainstorm some different terminology to further separate the two.

**Comment by smashwilson** [comment]
Next steps: I'll work on making a prototype to show what I'm thinking for the flow here more concretely. @kuychaco and @rebornix had some alternative proposals that would likely be easier to implement - if you two leave comments here, we can figure out the best way forward :smile:

**Comment by phil-blain** [comment]
This would also be great for reviewing branches from other contributors that do not currently have an open pull request. @smashwilson have you made any progress on this ?

**Comment by smashwilson** [comment]
Alas, no, I haven't worked on this project for a good while now. Sorry! 😅

**Comment by alexr00** [comment]
There have been a lot of changes since this issue was opened!
- You can always edit the PR title and description before creating the PR
- We show a nice set of file diffs before you create the PR
- We use GitHub's draft PR functionality.
