### ISSUE TITLE
Queries won't return correct results. PRs are missing.

### ISSUE THREAD

**Issue by sarpdoruk** [microsoft/vscode-pull-request-github#1233]
- Extension version: 0.8.0
- VSCode Version: 1.35.0 (1.35.0)
- OS: OSX 10.14.5 (18F203)

My personal account belongs to an organization and all repositories are private. I am using a personal access token for authentication. Appropriate permissions are set for the token, see below;

![image](https://user-images.githubusercontent.com/844954/59361816-1ec00b80-8d3b-11e9-8db3-ff1c74932efc.png)

My queries do not return correct results. For my account `Review Requests` filter provided by GitHub is `is:open is:pr review-requested:sarpdoruk archived:false`. At the moment there are 5 different PRs waiting for my review but when I take this query and paste it in plug-in's configuration there are no results.

Same thing goes for default queries provided with the plug-in. I can only see 4 PRs below `All` section but there should be tons of PRs listed there.

**Comment by RMacfarlane** [comment]
> I can only see 4 PRs below All section but there should be tons of PRs listed there.

Are all of the PRs you expect to see from the same remote? There's also a "githubPullRequests.remotes" setting that can take an array of remotes that should be used, this defaults to using "origin" and "upstream" if those are found

**Comment by sarpdoruk** [comment]
Yes, all branches of our repositories are under `origin`.

**Comment by sarpdoruk** [comment]
Magically, with today's VSCode update (1.35.1), the problem is gone.
