### ISSUE TITLE
Creating pull requests failed: HttpError: Validation Failed

### ISSUE THREAD

**Issue by gavrix** [microsoft/vscode-pull-request-github#1234]
Whenever I try to create a PR I get 
```
[Debug 28373s 194ms] GitHubRepository> Creating pull requests failed: HttpError: Validation Failed
```
right after I choose target branch 

- Extension version: 0.8.0
- VSCode Version: 1.35.1 (1.35.1)
- OS: MacOS Mojave

Steps to Reproduce:

1. Install exetnsion
2. restart VScode
3. Create new branch
4. Attempt to create new PR by pressing + button
5. Leave master as target branch
6. Observe error message

**Comment by jdwestbrook** [comment]
I believe I am having the same issue trying to create a pull request when following
the steps above, creating a new pull request using the '+' option using a local 
and published branch.  Output shown below.

I was able to create the pull request manually using the 'hub pull-request' command,
and once created I was able to see and navigate around in the pull request using the
extension which is great.    I am stuck trying to use the extension to create the PR from 
a branch.  

Installation details:

Code - Insiders
Version 1.36.0-insider (1.36.0-insider)
fe0c3e785c22c3ed2d5caa7178488c92d62bdb08
MacOs 10.14.5 Mojave

Installed Extensions:
formulahendry.code-runner@0.9.11
GitHub.vscode-pull-request-github@0.8.0
Hyzeta.vscode-theme-github-light@6.0.1
markis.code-coverage@1.1.0
ms-python.python@2019.6.22090
njpwerner.autodocstring@0.3.0
teabyii.ayu@0.18.0
tomoki1207.pdf@0.5.0
vscode-icons-team.vscode-icons@8.8.0

Pull request output: 

[Info] Looking for git repository
[Info] Git repository found, initializing review manager and pr tree view.
[Info] Found GitHub remote
[Info] https://api.github.com: GraphQL support detected
[Info] Review> no matching pull request metadata found for current branch undefined
[Info] Found GitHub remote
[Info] Review> no matching pull request metadata found for current branch undefined
[Info] Found GitHub remote
[Info] Review> no matching pull request metadata found for current branch master
[Info] Found GitHub remote
[Info] Review> no matching pull request metadata found for current branch master
[Info] Found GitHub remote
[Info] Review> no matching pull request metadata found for current branch azure-ci-v1
[Info] GitHubRepository> Creating pull requests failed: HttpError: Validation Failed
[Info] GitHubRepository> Creating pull requests failed: HttpError: Validation Failed
[Info] GitHubRepository> Creating pull requests failed: HttpError: Validation Failed
[Info] Found GitHub remote

**Comment by radmedov** [comment]
Any solution to this? I'm having the same issue

**Comment by marnovo** [comment]
+1 here.

**Comment by Unumus** [comment]
+1

**Comment by andycognitoiq** [comment]
+1

**Comment by Rody66** [comment]
The same issue. Please fix.

**Comment by 1adamf** [comment]
+1

**Comment by Ballzer0** [comment]
+1

**Comment by AmitKKhanchandani** [comment]
+1

Any Solution for this?

**Comment by RMacfarlane** [comment]
Unfortunately, the logs aren't currently detailed enough to know what the exact cause is - there are several reasons why validation might fail when creating a pull request. One common one is there being no difference in commits between the target branch and the current branch. Possibly the extension isn't correctly setting a title.

I have already check in a change that should fix the way we format the error from GitHub, so there should be more details in both the extension output log and in the notification. This is available in the nightly version of the extension (https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github-insiders), can you give it a try there to see if there's more information? Note that if you do install the nightly version, you should disable the normal version of the extension so that they don't conflict with each other

**Comment by horizon-it-uk** [comment]
+1

**Comment by RMacfarlane** [comment]
Extension version 0.12.0 should now show a more detailed error notification when this happens - please let me know what you see

**Comment by jzsplk** [comment]
+1

**Comment by RMacfarlane** [comment]
@jzsplk Was there any additional information in the error? What version of the extension are you using?

**Comment by JoyceMassau** [comment]
+1
Pull request creation failed. Validation failed: You can't perform that action at this time.
- OS: Windows 10 Home Single

Any Solution for this?

**Comment by yogevh** [comment]
I had the same issue. it appears that I was logged in with my private github user and not with the github user I have for work.
after logging in with my work user I was able to create the PR

**Comment by Scyfren** [comment]
I keep getting this warning when trying to create a pull request:

Creating pull requests for 'Scyfren:Scyfren/issue18' failed: Validation Failed: Value "undefined" cannot be set for field undefined (code: custom)

I'm sure that I'm putting in a title name when using custom. This even shows up when trying to use the commit and branch option. I think it started happening when I accidentally tried to create a pull request using the custom option but with no title.

**Comment by SturdyErde** [comment]
Reproduced with plugin version v0.18.0 and VS Code 1.47.3 with git version 2.27.0.windows.1 on Windows 10 1909.

**Comment by mrevow** [comment]
I also get this with visual code 1.47.3 running on ubuntu 18.04.1 VM in azure. The full  error message is  

Creating pull requests for 'mrevow:master' failed: Validation Failed: Value "undefined" cannot be set for field undefined (code: custom)

**Comment by hyungjunk** [comment]
I was trying to make a PR from my `local master branch` to `remote master branch` and got the same error message as what author got.

Then I changed my local branch from master to `another_branch`, set upstream, (since this was newly created branch at my local and not initiated at remote yet), made PR. 
Now it works.

**Comment by brianjmurrell** [comment]
Seems this issue has been open a **long** time with many people hitting it.

Can't anything be done about it?

**Comment by sebride4988** [comment]
I solved it by clearing the code source and doing a fresh clean copy.
I guess the git config was wrong.
I hope my solution will help others.

**Comment by Prasundas99** [comment]
Any solution to this? I'm having the same issue

**Comment by xclala** [comment]
The same issue. Please fix.

**Comment by alexr00** [comment]
I _think_ everyone who's seeing this is trying to create a PR where the "from" and "into" branches have the same head. We now show a better message:

![image](https://user-images.githubusercontent.com/38270282/142236153-8ad6e6d2-228b-410d-b77d-50a37075fda6.png)

If anyone is seeing something other than that, please comment!

**Comment by mike-koala-bear** [comment]
Ok thanks!!
