### ISSUE TITLE
Extension doesn't respect scm.diffDecorationsGutterWidth and scm.diffDecorations

### ISSUE THREAD

**Issue by svipas** [microsoft/vscode-pull-request-github#1235]
- Extension version: 0.8.0
- VSCode Version: 1.35.1
- OS: macOS

Steps to Reproduce:

Try to use any of these given settings with this extension: `scm.diffDecorationsGutterWidth` and/or `scm.diffDecorations`. It still shows the same gutter width or the decorations doesn't matter if they are different in the user settings.

**Comment by alexr00** [comment]
@RMacfarlane should this be moved to microsoft/vscode?

**Comment by RMacfarlane** [comment]
Actually, thinking about this more, I do not think the comments gutter should respond to these settings. The comments API is independent of SCM. Closing as out-of-scope
