### ISSUE TITLE
No option to sign in to GitHub

### ISSUE THREAD

**Issue by orffen** [microsoft/vscode-pull-request-github#1238]
Issue Type: <b>Bug</b>

I've installed the extension but have no notification asking me to authenticate to GitHub. Command palette does not show any options for GitHub - no sign in/out.

There are no extension settings to allow sign in either.

I have uninstalled and reinstalled the extension with the same effect.

Extension version: 0.8.0
VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.17134

**Comment by orffen** [comment]
This appears to have self-resolved, and on both of my machines I got the notification to sign in.\

However, in the meantime I did install node.js (npm) and performed
`npm install -g typescript`
`npm install -g eslint`

Doesn't seem like that should matter, not sure if it's related.

**Comment by RMacfarlane** [comment]
Closing since this has resolved itself - the issue may have been with the extension's ability to detect a GitHub remote.
