### ISSUE TITLE
WIP / draft Pull Request should look different

### ISSUE THREAD

**Issue by octref** [microsoft/vscode-pull-request-github#1241]
On GitHub:

![image](https://user-images.githubusercontent.com/4033249/59811218-706c2580-933b-11e9-9b9f-ba770e9561ef.png)

Locally:

![image](https://user-images.githubusercontent.com/4033249/59811221-76fa9d00-933b-11e9-82eb-76afef12ac7e.png)

If the PR didn't start with name WIP I wouldn't know it's a draft.
I suggest a prefix like `[Draft]`, or some unicode character to indicate "draft".

**Comment by phifa** [comment]
@octref good point. Also it would be great, if it would work the other way around. When creating a PR from VS Code, one should be able to select if it is a draft or not.

**Comment by IllusionMH** [comment]
Looks like it was implemented in #1173
`(draft)` is added to PR tree item description [code](https://github.com/microsoft/vscode-pull-request-github/pull/1173/files#diff-01df2fed876de92b7e2298ee7d0513f5R402)
![image](https://user-images.githubusercontent.com/1312662/72284419-98113b00-3649-11ea-87c1-eb4cd4365d2e.png)

Draft PR can be created using `>GitHub Pull Requests: Create Draft Pull Request` command.

**Comment by RMacfarlane** [comment]
Thanks @IllusionMH! Closing since this has been addressed with `(draft)` in the description
