### ISSUE TITLE
Error: Webview is disposed

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-pull-request-github#1247]
Issue Type: <b>Bug</b>

Click on
> Open pull request description to side

Close the window

Error toast thing pops up, saying "Webview is disposed"

Extension version: 0.8.0
VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:29:22.216Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by RMacfarlane** [comment]
I'm no longer able to reproduce this with version 0.12.0 of the extension
