### ISSUE TITLE
"Open all files" button

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-pull-request-github#1248]
Issue Type: <b>Feature Request</b>

It'd be nice to have a quick way to open all changed files in a PR in their own tabs. Idk, just a thought. 

Extension version: 0.8.0
VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:29:22.216Z)
OS version: Darwin x64 18.6.0

**Comment by JeffreyCA** [comment]
I can work on this 🙂

**Comment by alexr00** [comment]
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/3047, because that one has more discussion.
