### ISSUE TITLE
Color/theming issues on the overview page

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode-pull-request-github#125]
Testing: https://github.com/Microsoft/vscode/issues/55396

See attached screenshot below.

1. The Open status looks like a button. Compare with the Comment button. No difference.
2. The Comment button is disabled. The only way to figure that out is by hovering over it and seeing that it behaves differently than Close Pull Request or Checkout Pull Request.
3. The background of the commit entry is too dark so that the link is hard to read. I'd prefer a much lighter color as background.

![capture5](https://user-images.githubusercontent.com/4674940/43532994-9ecd4750-9568-11e8-9696-f800242b0137.PNG)

**Comment by RMacfarlane** [comment]
Has been fixed with https://github.com/Microsoft/vscode-pull-request-github/commit/e1b3fdcc65dbc32cad12331feadb0c0b0be7ad11
