### ISSUE TITLE
Overview page design

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode-pull-request-github#126]
Testing: https://github.com/Microsoft/vscode/issues/55396

See screenshot below.  The actual description of the PR (first comment) is important but is actually the smallest visual element on the screen. It's overpowered by the commit below and by the large commenting box.

The description should be what's drawing my attention when opening the Description page of an open PR.

![capture5](https://user-images.githubusercontent.com/4674940/43533564-f24bc360-9569-11e8-92fc-47010b2be60e.PNG)

Here is a more drastic example of "overpowering":

![image](https://user-images.githubusercontent.com/4674940/43534833-2a0556e2-956d-11e8-8868-c1a6eb2d826d.png)

**Comment by misolori** [comment]
All of these issues have been addressed via PR https://github.com/Microsoft/vscode-pull-request-github/pull/154

![image](https://user-images.githubusercontent.com/35271042/43967436-3d9ad6d8-9c79-11e8-8734-a25419f848f8.png)
