### ISSUE TITLE
When I download the extension I do not get "refresh" option

### ISSUE THREAD

**Issue by JKwaak** [microsoft/vscode-pull-request-github#1262]
- Extension version: 0.9.0
- VSCode Version: 1.36.1
- OS: Windows 10

When I download the extension I do not get the option to refresh. I do not know how to sign into my account without the refresh. I get the extension on the activity bar but nothing works.

**Comment by RMacfarlane** [comment]
Hey @JKwaak, thanks for reporting this! A couple of questions:

- When you click on the activity bar, what do you see?
- Can you look in the output log (Run `View: Toggle Output` and then choose `GitHub Pull Request` from the dropdown on the right side of the panel) and report what's in the log?

**Comment by JKwaak** [comment]
When I click on the activity the message I get is there is "no data provider registered that can provide view data."

Then when I click on the settings button I get the error 'pr.configurePRViewlet' not found

**Comment by RMacfarlane** [comment]
@JKwaak Thanks for the additional info, it sounds like the extension isn’t getting fully activated. Can you press `Ctrl + Shift +p` and run the command `Developer: Toggle Developer Tools` and check what is in the console there?

**Comment by JKwaak** [comment]
![Screenshot (3)](https://user-images.githubusercontent.com/33880567/61153487-614f4200-a4b9-11e9-8486-c8b324a642ac.png)
No, I am not using VSCodium.

**Comment by RMacfarlane** [comment]
@JKwaak can you check that the git extension is enabled?

1. In extensions viewlet, search `@builtin git`
2. Check that the setting `git.enabled` is checked/true

**Comment by fazo96** [comment]
![Screenshot_20190725_105712](https://user-images.githubusercontent.com/2546805/61860862-f7786480-aeca-11e9-86fe-9928beb0aa4d.png)

I am running VSCode on Manjaro Linux and I have the git builtin installed and enabled (I use it regularly). I have the same problems as @JKwaak and in the screenshot you can see the error that I have in the console.

**Comment by RMacfarlane** [comment]
@fazo96 Sorry I missed responding to this earlier - it looks like you might be using a community or OSS build of VSCode, can you try launching it with `code --enable-proposed-api GitHub.vscode-pull-request-github`? There's an existing issue to remove the need for this flag in this case https://github.com/microsoft/vscode-pull-request-github/issues/1310 that depends on a change from VSCode

**Comment by RMacfarlane** [comment]
@JKwaak Were you able to get this working after installing git?

**Comment by manekenpix** [comment]
@RMacfarlane I have the same problem as @JKwaak and @fazo96. Launching vscode with `code --enable-proposed-api GitHub.vscode-pull-request-github`. I wonder if there's a way to make that change permanent?
Thanks!

**Comment by manekenpix** [comment]
Sorry, sent the message before finishing it. I was saying that sending the message from terminal with the arguments you suggested works.

**Comment by tirelibirefe** [comment]
> @RMacfarlane I have the same problem as @JKwaak and @fazo96. Launching vscode with `code --enable-proposed-api GitHub.vscode-pull-request-github` it worked. I wonder if there's a way to make that change permanent?
> Thanks!

where did u enter that command?

**Comment by manekenpix** [comment]
@tirelibirefe terminal

**Comment by RMacfarlane** [comment]
Closing since the removal of the flag is covered in https://github.com/microsoft/vscode-pull-request-github/issues/1310, and I believe the original issue was that git was not installed, covered in https://github.com/microsoft/vscode-pull-request-github/issues/1615

**Comment by scottwallacesh** [comment]
>  Launching vscode with `code --enable-proposed-api GitHub.vscode-pull-request-github` it worked. I wonder if there's a way to make that change permanent?

There is!

Add an entry to `~/.vscode/argv.json`:
```javascript
{
    // Allow Github Pull Request to work
    "enable-proposed-api": [
        "GitHub.vscode-pull-request-github"
    ]
}
```
