### ISSUE TITLE
I can't authenticate to gitHub

### ISSUE THREAD

**Issue by DamirMakhmudov** [microsoft/vscode-pull-request-github#1265]
I installed extension and reload vscode app. But I can't find an method to authenticate to github account. In my gitHub profile I watch "GitHub for VSCode" in "Authorised OAuth  Apps" folder. It's strange. Help me pls...

ersion: 1.36.1 (user setup)
Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
Date: 2019-07-08T22:59:35.033Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 6.3.9600

Name: GitHub Pull Requests
Id: github.vscode-pull-request-github
Description: Pull Request Provider for GitHub
Version: 0.9.0
Publisher: GitHub
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github

**Comment by RMacfarlane** [comment]
Hey @DamirMakhmudov, can you try pressing `Ctrl + Shift + p` and then running the command `GitHub Pull Requests: Sign in to GitHub`?

**Comment by iv1660yg** [comment]
![image](https://user-images.githubusercontent.com/51352671/61844929-de3dcc80-ae66-11e9-865c-0faf503c90ed.png)

same issue

**Comment by RMacfarlane** [comment]
@iv1660yg Please open a folder and retry. The extension can’t finish activating until there is an open folder

**Comment by ElliottRosenfeld** [comment]
> Hey @DamirMakhmudov, can you try pressing `Ctrl + Shift + p` and then running the command `GitHub Pull Requests: Sign in to GitHub`?

Hi @RMacfarlane When i attempt this, it eventually times out and produces a Heroku error.
![image](https://user-images.githubusercontent.com/10214165/62656626-78971900-b919-11e9-8edc-8acad1dd9157.png)

Any advice?

Thanks

**Comment by NFerragut** [comment]
If you have any other GitHub plug-in in VSCode, try disabling it. I had the same problem and was able to sign in after I disabled the GitLens plug-in.

**Comment by ValeriyDevPro** [comment]
```
Version: 1.37.1
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:17:25.463Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.15.0-58-generic
```
Extension version is 0.10.0
The same issue I can't login to github

![Screenshot from 2019-08-20 10-06-02](https://user-images.githubusercontent.com/11663800/63325199-58f8eb00-c332-11e9-89a3-213d26c5d62f.png)

**Comment by johnlico** [comment]
Similar problem it keeps requesting that I install .Git.
Currently using GitHub Desktop so not too keen.
I'll wait until this is more robust before trying again. just thought I'd share my error.
![giterror](https://user-images.githubusercontent.com/24213845/64036129-5f653f00-cb4a-11e9-9b94-0d846f926eaa.jpg)

**Comment by DamirMakhmudov** [comment]
@RMacfarlane thanks! I'm not sure in it, but it started working after I installed GIT on my machine

**Comment by RMacfarlane** [comment]
Closing this since the original problem was resolved. If you're still having problems signing in, please open a new issue. Please check that you have a folder open with a GitHub remote, try running `git remote -v` in the terminal of that folder. Thanks!
