### ISSUE TITLE
Collapsed comment gets unfolded when switching tabs

### ISSUE THREAD

**Issue by octref** [microsoft/vscode-pull-request-github#1268]
- Extension version: 0.9.0
- VSCode Version: 1.37.0-insider
- OS: Darwin x64 18.6.0

Steps to Reproduce:

1. Open a PR
2. Collapse a comment
3. Navigate to another tab
4. Navigate back
5. Comment unwanted uncollapsed

![gif](https://user-images.githubusercontent.com/4033249/61075398-bf532b00-a3ce-11e9-97da-8f5f8e5a03ec.gif)

**Comment by alexr00** [comment]
This has been fixed in the mean time.
