### ISSUE TITLE
PR tree shows ‘No GitHub repositories found’ when not authenticated

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode-pull-request-github#1269]
1. Run sign out command of extension
2. Reload VS Code
3. Click on activity bar icon

Message says that there are no github repositories, when in fact there are, but auth has not been completed. Should show a ‘Sign in’ instead.

**Comment by todddunagan-bah** [comment]
Any insight into a workaround until this fix goes out with a release? I've attempted to fully remove the extension and reinstall but that does not appear to help. Thank you!

**Comment by RMacfarlane** [comment]
I think the following should work
1. Run sign in command and complete sign in process
2. Reload/restart VS Code

Sometimes it takes a bit for the tree to load and it still shows the ‘No GitHub repositories found’ message, I’d like to improve this even more to show ‘Initializing…’ then
