### ISSUE TITLE
PR number should appear first in the PR view's tree

### ISSUE THREAD

**Issue by dinofx** [microsoft/vscode-pull-request-github#1275]
When trying to find a specific PR in the tree, the tree item's text contains the PR's title followed by the PR #number.  If the title is too long, the text is truncated, making it impossible to find a PR by number.  If truncation can't be controlled (such that a trailing number is always shown), then the number should come first.

**Comment by tobudim** [comment]
Hi,

I tried to made some modifications to at least see what it would look like.
I did not found into the code where to do those modifications _(only my second potential contribution here, and I'm a very junior developper)_.

If someone could just tell me where to look I'd love to help out. :)

**Comment by RMacfarlane** [comment]
Hey @tobudim, the code for this is located here: https://github.com/microsoft/vscode-pull-request-github/blob/0bc18142a7b54215bf98836403ffb728c6452a3b/src/view/treeNodes/pullRequestNode.ts#L367

With the tree API from VS Code, we only have control over what the label and description are for each item displayed in the tree, we can’t control how the text is truncated

**Comment by rebornix** [comment]
We can allow users to control the label of the pull request node label, similar to how we control the display of Title in VS Code.

**Comment by almaceleste** [comment]
I think it is a very important feature request cause now it's very hard to find a desired pullrequest by its number. 
If we have `prNumber` variable why it is not added before `title` to the `label`?
https://github.com/microsoft/vscode-pull-request-github/blob/0bc18142a7b54215bf98836403ffb728c6452a3b/src/view/treeNodes/pullRequestNode.ts#L366
