### ISSUE TITLE
Support for the "Viewed" flag in github

### ISSUE THREAD

**Issue by alekkowalczyk** [microsoft/vscode-pull-request-github#1278]
Lately github introduced the "Viewed" flag on files in Pull Requests, which is a life saver when doing reviews of bigger pull requests where the review can take several hours.
 
 - to know which files were already reviewed
 - to see, that a file was changed since it was lastly viewed

Would be cool to have this feature available directly from VSCode with this extension.

**Comment by thommackey** [comment]
Is this a duplicate of #520?

**Comment by RMacfarlane** [comment]
Yes, closing as a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/520
