### ISSUE TITLE
Support Azure Repos

### ISSUE THREAD

**Issue by Camo30** [microsoft/vscode-pull-request-github#1285]
It would be amazing if this extension would support Azure Repos too.

**Comment by RMacfarlane** [comment]
Hey @Camo30, this extension is focused specifically on GitHub integrations and has a lot of GitHub specific code. We'd like to keep focusing on that here, we hope that another extension can do the same for Azure dev ops. There's some more info in our wiki on this: https://github.com/microsoft/vscode-pull-request-github/wiki#4-what-about-supporting-other-providers-such-as-gitlab-and-bitbucket

**Comment by Camo30** [comment]
Hi @RMacfarlane, thanks for following up. I've already read that wiki, but there is nothing specific for Azure dev ops there, and an information request to Microsoft was left without any reply. I know that you are trying to keep the extension clean, my intention is to draw attention that it would be great to get exactly the same extension for pull requests within Azure Repos. Otherwise it makes more sense to use GitHub than Azure as a repo.

**Comment by leoniDEV** [comment]
@Camo30 It seems that Microsoft is not more interested to support its own product, any way a user  (@argutec-sro) has [forked](https://github.com/argutec-sro/azure-repos-vscode) the Azure Repos repo and [republished](https://marketplace.visualstudio.com/items?itemName=argutec.argutec-azure-repos&ssr=false#overview) the extenstion in the marketplace.
Better than nothing, in the hope that someone will keep the extension up to date (unfortunately I don't have time to get involved)
