### ISSUE TITLE
Commits list in "Changes in pull request" tree only shows first 30 commits

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/vscode-pull-request-github#1286]
Issue Type: <b>Bug</b>

Looks similar to #375 but for commits list.

If PR has more than 30 commits ([example](https://github.com/microsoft/TypeScript/pull/32517/commits)) only first 30 are shown and there is no "Load more" button

Extension version: 2019.7.36902
VS Code version: Code - Insiders 1.37.0-insider (92da68a71cfb60bd3b9b0d7fbfb2a7e1fff9dbaf, 2019-08-01T05:37:54.848Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.72GB (17.67GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by IllusionMH** [comment]
At first I thought that it can be fixed just using approach from commit https://github.com/microsoft/vscode-pull-request-github/commit/cd5f1dd04e90655409765ee973ac4db611392431 in `getPullRequestCommits` function.

However, on second thought it looks like this function will always return list of commits from PR on GitHub, but if local repo doesn't have all commits from PR that there is chance to trigger diff view on commit that isn't available locally.
Do I understand correctly that proper solution will be using local git API to get all available commits in PR?

**Comment by haringsrob** [comment]
I found this today, opened a big pr, and indeed only a subset of the commits were visible.

I was checking settings but could not find anything related, refreshed, restarted all without any effect.

@rebornix: While this could be a feature request it seems more that this is a bug?

**Comment by costas90** [comment]
Is there a solution to this?

**Comment by alexr00** [comment]
To verify:
1. Install the pre-release version of the extension
2. Make a PR with > 30 commits
3. Check out the PR with the extension if you haven't already
4. In the "Changes in Pull Request" view, there's a "Commits" node. Expand that.
5. Verify that you have all of your commits listed there.
