### ISSUE TITLE
Diff view used to show diff on full file but now shows only the area around the diff

### ISSUE THREAD

**Issue by tom-thorne** [microsoft/vscode-pull-request-github#1288]
- Extension version: 0.9.1
- VSCode Version: 1.36.1
- OS: Mac osx

Steps to Reproduce:

1. Open Github PR panel.
2. Select a PR under 'All'
3. Select a changed file in the tree

Old (and desired) behaviour:
-The diff viewer shows the full file and the changes the PR makes

Current behaviour:
-The diff viewer shows the same diff view as gihub

The old diff viewer made evaluating complex PRs much easier.  The new truncated diff is no better than github.

I've searched for a setting to see if I can get back to the way it worked a few months back, but can't find anything.

**Comment by rebornix** [comment]
@tom-thorne is your local repository up to date? You can try to run `git fetch` to fetch all unsynced commits from upstream and then you should be able to see the full diff view.

**Comment by SumanthPuram** [comment]
@rebornix Git fetch worked. Thanks.

But surprisingly I had another PR (From a new branch which I never fetched), that was showing full diff. Two more PRs, which I reviewed earlier, not showing the full diff view. Why could that be happening?

After fetch, all PRs are showing the full diff view.

**Comment by tom-thorne** [comment]
I can confirm its now working again as expected - I will make sure to be up to date in future.
If its easy to do, a dialog prompting user to pull would help prevent others from making my mistake

**Comment by rebornix** [comment]
@tom-thorne @SumanthPuram the reason that you need to fetch is if we don't have the commit the PR is comparing to, we don't fetch that automatically for you. Instead we show the partial diff view, whose content is from GitHub.
