### ISSUE TITLE
diff type indicators are two big

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode-pull-request-github#129]
Testing https://github.com/Microsoft/vscode/issues/55396.

The two screenshots compare a regular diff editor (first) with one that has diff hunk decorations (second). The `+` indicators are much bigger in the second but shouldn't.

![image](https://user-images.githubusercontent.com/4674940/43534134-75d58c24-956b-11e8-96a4-78b2e6c7fdd5.png)

![image](https://user-images.githubusercontent.com/4674940/43533858-b801294c-956a-11e8-8956-cb02421ac804.png)

**Comment by rebornix** [comment]
Fixed in rebornix/comment-affordance branch.

**Comment by rebornix** [comment]
Reopen as the width of the decorations area is not large enough and the diff hunk decorations overlap with `+` sign.
