### ISSUE TITLE
Separate author and commit message

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-pull-request-github#1293]
![image](https://user-images.githubusercontent.com/323878/62484555-4a75d580-b76f-11e9-93a4-37b958b274ce.png)

The author name should be more separated from the commit message somehow so this doesn't just look like one sentence

**Comment by lifez** [comment]
@RMacfarlane If I just change color or bolder the author-name. Would be nice?

**Comment by RMacfarlane** [comment]
@lifez Yes, I think bolder would be nice! It would also be consistent with github.com where usernames are bold

**Comment by lifez** [comment]
@RMacfarlane I will take this :)

**Comment by lifez** [comment]
<img width="537" alt="Screen Shot 2562-10-20 at 21 29 52" src="https://user-images.githubusercontent.com/2588927/67161021-ca7c0680-f380-11e9-9f3a-ec8c4bdd12d6.png">

I think just bolder is not enough. What do you think if i change author color to white

<img width="497" alt="Screen Shot 2562-10-20 at 21 31 18" src="https://user-images.githubusercontent.com/2588927/67161058-02834980-f381-11e9-85bd-0918f19fea96.png">

**Comment by lifez** [comment]
@RMacfarlane

**Comment by RMacfarlane** [comment]
@lifez That looks good to me! But we need to be careful that it works for all themes. Instead of hardcoding a color, we should use a css variable for an existing theme color. `color: var(--vscode-editor-foreground)` is an example of this
