### ISSUE TITLE
Error when creating a PR

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-pull-request-github#1300]
Not sure what this means:

![image](https://user-images.githubusercontent.com/323878/62725126-607ed280-b9c9-11e9-8a93-bff522c52d3a.png)

I want the branch to be published to my fork, which it did, and the PR to go to the upstream repo, but it seems that it can't find it. My remotes look like this:

![image](https://user-images.githubusercontent.com/323878/62725234-97ed7f00-b9c9-11e9-88b7-5b780b229b33.png)

**Comment by RMacfarlane** [comment]
@roblourens Was this with the latest version of the insiders extension? I made a fix yesterday that addressed a similar problem (https://github.com/microsoft/vscode-pull-request-github/pull/1296)

**Comment by roblourens** [comment]
Sorry, I'm not using the nightly extension right now because then the Rich Code Navigation extension complains.

**Comment by arjun27** [comment]
@roblourens - does Rich Code Navigation prompt you to download the stable version of the extension? It just should work with nightly as well, if that would work better for you.

cc @jepetty

**Comment by roblourens** [comment]
Yes it just prompts me to install the stable version

**Comment by RMacfarlane** [comment]
Closing since I believe this was fixed with https://github.com/microsoft/vscode-pull-request-github/pull/1296, I'm not able to repro it. Let me know if you see it again
