### ISSUE TITLE
Undefined object TypeError on PR description page

### ISSUE THREAD

**Issue by john4** [microsoft/vscode-pull-request-github#1307]
`Cannot read property 'comments' of undefined`
- Extension version: 0.10.0
- VSCode Version: 1.36.1
- OS: macOS 10.14.6

Steps to Reproduce:
1. Expand PR details in side panel
2. Click Description

Doesn't load new page, VSCode surfaces the error. This appears to occur inconsistently between PRs, but consistently on affected PRs

**Comment by RMacfarlane** [comment]
@john4 I'm having trouble reproducing this - do you have an example PR where this happens? What do the reviews look like on such a PR?
