### ISSUE TITLE
Remove `enableProposedApi` when decorations API is stable

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode-pull-request-github#1310]
Now that the comments API has been finalized, we are almost at a point where we can stop using the proposed API switch.

The only other proposed API used by the extension is the DecorationsProvider.

**Comment by johanbrandhorst** [comment]
Is this stable yet? I find myself having to add this manually every time I update my version of VS Code.

**Comment by RMacfarlane** [comment]
No, the DecorationsProvider is still in proposed state

**Comment by alexr00** [comment]
This is done.
