### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by bm-stschneider** [microsoft/vscode-pull-request-github#1311]
- Issue Type: `Bug`
- Extension Name: `vscode-pull-request-github`
- Extension Version: `0.10.0`
- OS Version: `Darwin x64 17.7.0`
- VSCode version: `1.38.0-insider`

```json 
{
	"messages": [],
	"activationTimes": {
		"startup": false,
		"codeLoadingTime": 213,
		"activateCallTime": 2,
		"activateResolvedTime": 25,
		"activationEvent": "*"
	},
	"runtimeErrors": [
		{
			"name": "TypeError",
			"message": "Cannot read property 'inDraftMode' of undefined"
		}
	]
}
```

**Comment by RMacfarlane** [comment]
Thanks @bm-stschneider, this should have been fixed as part of https://github.com/Microsoft/vscode-pull-request-github/commit/3bc2d96209c17044c90985c41cde1efe47590730, commentHandlers were not be unregistered properly
