### ISSUE TITLE
Configure git credential based on current github login

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-pull-request-github#1313]
When reviewing a pull request, often I check out the PR and add a commit with changes. For that need the Git viewlet. But when pushing, I'm asked to to provide the git credentials.

As the github pull-request extension already has my github credentials, it would be cool if it could help me to configure the git credentials. I imagine the PR extension knows the github auth token. 

I believe all it needs to do is to invoke
```
git config --local user.name "userName"
git config --local user.password "oAuthToken"
```

**Comment by aeschli** [comment]
@joaomoreno FYI

**Comment by joaomoreno** [comment]
This is now in core VS Code 🎆
