### ISSUE TITLE
User can only have one pending review per pull request

### ISSUE THREAD

**Issue by kalyanaramansanthanam** [microsoft/vscode-pull-request-github#1317]
- Extension version: 0.10.0
- VSCode Version: 1.37.1
- OS: MacOS

```
[Info] Failed to start review: GraphQL error: User can only have one pending review per pull request
```

**Comment by RMacfarlane** [comment]
@kalyanaramansanthanam Are you using GitHub enterprise? I'm wondering if https://github.com/microsoft/vscode-pull-request-github/issues/947 is related to this

**Comment by chrisdias** [comment]
I see this today. I started one in the browser, then started another in VS Code.  

But now I'm in a state where I can't delete the comment and it shows pending.  I click on the "x", I confirm the modal dialog, but nothing happens.

![image](https://user-images.githubusercontent.com/1487073/88864300-b390fd00-d1b9-11ea-9091-26bbc23265f0.png)

If its a limitation, that's sort of understandable.  But, it would be nice to catch this error and give a friendlier message.  You could just say `You can only have one Pending review on a Pull Request. Please resolve the other review before starting a new one.` or something like that.

**Comment by alexr00** [comment]
This should be fixed. We always try to get the pending review before creating a new one.
