### ISSUE TITLE
Cannot create a PR if source branch is not included in remotes settings

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode-pull-request-github#1326]
1. Create a typical setup where you have an upstream remote and your fork remote added in your local repo.
2. Rename them. E.g. `microsoft` and `sbatten` respectively.
3. Use the `githubPullRequests.remotes` setting to add just `microsoft` as that's the only remote I care about PRs for. 
4. Try to create a PR where the source branch is from the fork `sbatten` in my case.

:bug: => this silently fails. Console logs show that it does not believe the fork is a github repo.

**Comment by RMacfarlane** [comment]
Pushed a change to at least show a notification in this case with an option to configure remotes
