### ISSUE TITLE
No pull requests show up for certain repositories

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode-pull-request-github#133]
1. Clone https://github.com/facebook/nuclide
2. Open vscode on the cloned repo
3. Go to the PR viewlet
4. Select `All`
-> `0 pull requests in this category`

-> https://github.com/facebook/nuclide/pulls shows pull requests

**Comment by RMacfarlane** [comment]
@kieferrm I still haven't been able to repro, even on Windows. Could you paste the output of the "GitHub Pull Requests" channel and also the contents of the git config file?

**Comment by kieferrm** [comment]
Reload Window with the GH viewlet open:
```
Looking for git repository
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
Git repository found, initializing review manager and pr tree view.
> git config --local --get remote.origin.github-pr-remote
> git config --local --get remote.origin.github-pr-remote
> git config --local --get branch.master.github-pr-owner-number
Review> no matching pull request metadata found for current branch master
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git config --local --get remote.origin.github-pr-remote
> git config --local --get branch.master.github-pr-owner-number
Review> no matching pull request metadata found for current branch master
> git config --local --get remote.origin.github-pr-remote
```

**Comment by kieferrm** [comment]
This is the git config:
```
[core]
        repositoryformatversion = 0
        filemode = false
        bare = false
        logallrefupdates = true
        symlinks = false
        ignorecase = true
[remote "origin"]
        url = git@github.com:kieferrm/nuclide.git
        fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
        remote = origin
        merge = refs/heads/master
````

**Comment by RMacfarlane** [comment]
Aha! The git config has solved the mystery. The repo you're opening is this fork https://github.com/kieferrm/nuclide, which doesn't have any pull requests

**Comment by kieferrm** [comment]
🙃

**Comment by psanthu123** [comment]
I have similar issue, but in my case i have pull request available. 
Basically "github pull request" tab is not available in SCM, so i have modified package.json and removed check "&& github:hasGitHubRemotes" in scm.

Here is git config, i have modified git url, as it is private. 
[core]
	repositoryformatversion = 0
	filemode = false
	bare = false
	logallrefupdates = true
	symlinks = false
	ignorecase = true
[remote "origin"]
	url = https://COMPANYNAME.visualstudio.com/PROJECT/_git/REPO
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
	merge = refs/heads/master

Regards
Santhosh
