### ISSUE TITLE
Extension doesn't function with a GitLab submodule present

### ISSUE THREAD

**Issue by onnoowl** [microsoft/vscode-pull-request-github#1330]
I've been trying to get this extension to work for GitHub Enterprise, but it seems to be getting stuck on the fact that my project has a submodule hosted by GitLab. In the output log, it appears to be trying to look for remotes there instead of at the GitHub Enterprise remote. I've checked with the main project's `git remote -v`, and everything looks fine:
```
origin	git@github.[redacted].git (fetch)
origin	git@github.[redacted].git (push)
```

Here's the log output.
```
[Debug 238387s 676ms] Looking for git repository
[Debug 238387s 677ms] Git repository found, initializing review manager and pr tree view.
[Debug 238387s 704ms] Review> Validate state in progress
[Debug 238387s 704ms] Review> Validating state...
[Debug 238388s 19ms] GitHubServer> Host https://gitlab.com/ntpsec/ntpsec is associated with GitHub: false
[Debug 238388s 19ms] No remote with name 'origin' found. Please update your 'githubPullRequests.remotes' setting.
[Debug 238388s 19ms] No remote with name 'upstream' found. Please update your 'githubPullRequests.remotes' setting.
[Debug 238388s 19ms] PullRequestManager> Displaying configured remotes: origin, upstream
[Debug 238388s 26ms] GitHubServer> Host https://gitlab.com/ntpsec/ntpsec is associated with GitHub: false
[Debug 238388s 26ms] No remote with name 'origin' found. Please update your 'githubPullRequests.remotes' setting.
[Debug 238388s 26ms] No remote with name 'upstream' found. Please update your 'githubPullRequests.remotes' setting.
[Debug 238388s 26ms] PullRequestManager> Displaying configured remotes: origin, upstream
[Debug 238388s 27ms] No GitHub remotes found
[Debug 238388s 27ms] Review> no matching pull request metadata found for current branch undefined
[Debug 238388s 28ms] No GitHub remotes found
```

Additionally, I'm not entirely sure I've authenticated correctly... Whenever I try to add this to my settings, it disappears:
```
"githubPullRequests.hosts": [ { "host": "https://github.[redacted]", "token": "[redacted]" } ]
```
I save the JSON file, but after reloading VS Code, it's gone.

Also, using the "Manually Provide Authentication Response" command doesn't give any errors, but I'm also not sure whether or not it's doing anything successfully.

**Comment by RMacfarlane** [comment]
@onnoowl So your project is a parent folder that has remotes to GitHub, and a subfolder pointing to GitLab? Can you describe how you're opening the folders, i.e. opening the parent or opening a number of folders as a workspace?

After authenticating, there should be change to the status bar, with your username showing up next to a GitHub icon:
![Screen Shot 2019-09-09 at 9 29 25 AM](https://user-images.githubusercontent.com/3672607/64548885-61ff2b80-d2e4-11e9-8f20-36784a57fc29.png)

The preferred auth method is now through the "Manually Provide Authentication Response" command if the normal sign in flow doesn't work, if putting something in settings, we read it, add it to the keychain, and then remove it from settings. I'll open another issue to make sure that there's a notification after "Manually Provide Authentication Response" succeeds

**Comment by onnoowl** [comment]
I'm opening the parent folder directly. I also tried creating a new workspace, and adding the parent folder to the workspace (as the only folder), and that gets the same result.

Thanks, I think that notification will be helpful!

I was confused about the authentication at first, but I believe I'm properly authenticated. I tried the plugin in another repository from our Enterprise GitHub, and that works just fine, but this repo still fails. The only difference is the lack of a submodule belonging to GitLab.

**Comment by RMacfarlane** [comment]
Ok, thanks for clarifying! I'm able to repro something similar to this, where the extension initializes with the wrong folder. As a workaround, in the source control viewlet at the top, if you change the selection to another folder and then back to the parent, it should cause the pull request view to refresh and point to the correct folder.

![Screen Shot 2019-09-09 at 10 03 08 AM](https://user-images.githubusercontent.com/3672607/64551384-bfe24200-d2e9-11e9-9bcf-44851e6e6588.png)

**Comment by onnoowl** [comment]
Great, that works!

Thanks so much for your help.
