### ISSUE TITLE
GPR plugin fails to get any repos, but after disabling/enabling it works again - "No git repositories found."

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/vscode-pull-request-github#1334]
- Extension version: 0.11.0
- VSCode Version: 1.38.0 (stable)
- OS: MacOS 10.14.6

Steps to Reproduce:
1. Open Github Pull Requests Plugin
2. Plugin says "No git repositories found."
3. Open terminal, set output to "github pull request" 
4. Shows `[Debug 19752s 997ms] Looking for git repository`
5. Disable Github Pull Requests plugin
6. Reload
7. Enable
8. Go back to plugin
9. It now works

There's nothing useful in the logs apart from  `[Debug 19752s 997ms] Looking for git repository`
Clicking the refresh icon does nothing, nor does restarting vscode.

**Comment by RMacfarlane** [comment]
Thanks for catching this! Pushed a fix and published a new version of the extension.

**Comment by jasonwilliams** [comment]
speedy response!
thank you
