### ISSUE TITLE
Extension not working in SSH remote

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#1335]
- Extension version: 2019.9.13862
- VSCode Version: 

Version: 1.39.0-insider (user setup)
Commit: 0f1bd7721b793ed8b7805ba621061ce5a1f5c263
Date: 2019-09-09T05:28:53.427Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18975

- OS: Windows 10

![image](https://user-images.githubusercontent.com/2193314/64642116-787bb480-d3c2-11e9-8cd5-6064cfabb355.png)

Output:

```
[Info] Looking for git repository
```

This happened when I first updated the extension, when I reloaded to bring in a new update, but it was fixed when I did another window reload after that.

**Comment by RMacfarlane** [comment]
Dup of https://github.com/microsoft/vscode-pull-request-github/issues/1334. Pushed a fix for this and published a new stable version of the extension, but missed publishing a new nightly version. Queueing a build for it now!
