### ISSUE TITLE
Show warning when using with OSS build

### ISSUE THREAD

**Issue by adrinjalali** [microsoft/vscode-pull-request-github#1338]
Issue Type: <b>Bug</b>

Similar issue to #1198, but opening a git repo folder doesn't fix the issue.

On the github pull requests extension, anything I click on, shows "command xxx not found". Including the `pr.configurePRVewlet`. I can see the configuration of the extension if I go to settings, and in my json config I have nothing related to this extension.

I have tried uninstalling installing the extension again as well.

The source control extension works as expected.

Extension version: 0.11.1
VS Code version: Code - OSS 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-05T13:09:16.557Z)
OS version: Linux x64 5.2.8-arch1-1-ARCH

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.40GB (3.77GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by RMacfarlane** [comment]
@adrinjalali It looks like you're using a community build of VSCode, please see https://github.com/microsoft/vscode-pull-request-github/issues/1309

Run with the command line flag `--enable-proposed-api GitHub.vscode-pull-request-github`

**Comment by RMacfarlane** [comment]
Actually, reopening - maybe it's possible to detect this case and show a notification

**Comment by adrinjalali** [comment]
Thanks, the warning would be nice, but this fixed my issue for the time being :)

**Comment by RMacfarlane** [comment]
I'm going to close this again since it's pretty low priority. There's this item (https://github.com/microsoft/vscode-pull-request-github/issues/1310) tracking removing the need for the `--enable-proposed-api` flag at all - I believe the API we're relying on will move to stable very soon
