### ISSUE TITLE
Can't comment after checking out pull request

### ISSUE THREAD

**Issue by melink14** [microsoft/vscode-pull-request-github#1339]
I left comments as part of a review in a PR and then sent it from VS Code and it worked great.

Later, I wanted to make some changes to the PR myself so I clicked the 'checkout' button on the description page which appears to have created a new branch for me to edit the PR in.

I started to modify the PR  but in a few places I wanted to add new comments to get clarification from PR author. 

When I click '+' button, the comment editor appears but typing in the text area does nothing. See a screenshot below of a new comment box which I can't type in (above previous comment which I already sent)

![image](https://user-images.githubusercontent.com/1176550/64931609-6351bc00-d7ee-11e9-9aa5-86220fa8d511.png)

Extension version: 0.11.1
VS Code version: Code - Insiders 1.39.0-insider (b7a5b7cf39f569a570599530ffc855b454e37b06, 2019-09-12T08:47:28.947Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (17.56GB free)|
|Process Argv|--remote=wsl+WLinux|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: WLinux|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4001)|
|Memory (System)|31.94GB (17.56GB free)|
|VM|0%|
</details>

**Comment by yulrizka** [comment]
I have similar issue, but after before checkout I can comment just fine, but after checkout on the right hand side, I'm missing the white bar to add comments, but replying to comments seems to be ok

**Comment by yulrizka** [comment]
Btw, any pointers where to look up? Maybe something that I can dig into and get familiar with the code?

**Comment by RMacfarlane** [comment]
@yulrizka I think your issue sounds different, mind opening another issue for this?

The white bar is controlled by the "Commenting Range Provider" that the extension registers. There are different providers registered based on whether or not the pull request is currently checked out. For the checked out case, the code is here: https://github.com/microsoft/vscode-pull-request-github/blob/760ce513a88c300333a9f59d9027e5b8769d1f6f/src/view/reviewCommentController.ts#L400

The commenting controller there is responsible for comments on 3 different types of files. Files open in an editor have a url associated with them, which is usually file://path/to/file
- Normal files in the workspace. If you open a file that was changed by the PR through the file explorer, it (normally) has the scheme "file"
- Files from the "Changes in Pull Request" tree. When you click on one of these files and the diff editor opens, the left hand side is content provided from the extension, and the right hand side is the "file" scheme file. This left hand side has "review" scheme and has some query parameters to it
- Files from the "GItHub Pull Request" tree for the checked out PR. For the diff editor opened from this tree, both sides are content provided from the extension, and have the "pr" scheme

From your screenshot, it looks like something is going wrong with the "file" scheme (`currentWorkspace.uri.scheme`) case

**Comment by RMacfarlane** [comment]
@melink14 Thanks for reporting this, it seems like something is going wrong with focus in the comment editor

**Comment by alexr00** [comment]
I'm not able to repro this. If you're still seeing the issue, please comment!
