### ISSUE TITLE
Duplicate entries in PR list

### ISSUE THREAD

**Issue by shana** [Microsoft/vscode-pull-request-github#134]
Testing https://github.com/Microsoft/vscode/issues/55396

Listing PRs on one of my local repos shows duplicate entries:

![screen shot 2018-08-02 at 4 01 15 pm](https://user-images.githubusercontent.com/310137/43588730-6afeed88-966d-11e8-9996-e014ad5d2a6c.png)

This is most likely due to the fact that I have multiple remotes pointing to the same underlying server, with different protocols (because apps like Visual Studio can only do git via http, but on the command line I always go through ssh):

```
origin	git@github.com:github-for-unity/Unity (fetch)
origin	git@github.com:github-for-unity/Unity (push)
origin-http	https://github.com/github-for-unity/Unity (fetch)
origin-http	https://github.com/github-for-unity/Unity (push)
shana	git@github.com:shana/Unity (fetch)
shana	git@github.com:shana/Unity (push)
```

**Comment by rebornix** [comment]
@shana right we should merge https and git remotes if they are pointing to the same server.
