### ISSUE TITLE
Add support for keyboard shortcuts for file navigation (next file and previous file)

### ISSUE THREAD

**Issue by plchampigny** [microsoft/vscode-pull-request-github#1342]
I would like to be able to move quickly into a PR files (like next file or previous file) with a hotkey. Currently there is a command to move to next changes (or previous) in vscode but not to move to next file. Adding those commands would greatly improve my experience in reviews.

**Comment by lifez** [comment]
I would take this.

**Comment by tanhakabir** [comment]
+1 keyboard navigation in the treeview isn't very well known

**Comment by dtinth** [comment]
## Workaround

To change file

1. Run **View: Focus into Side Bar** (Cmd+0).
2. Press Down then Enter to go to next file. The focus stays in the sidebar.
3. Run **Move to Next Change** (Alt+F5) to navigate the changes. The focus stays in the sidebar.
4. Press Tab then Enter to mark file as viewed. Repeat step 2 until all reviewed.

Unfortunately to add review comments I have not found a way to do this using only keyboard yet.

**Comment by ian-h-chamberlain** [comment]
For switching between files, I use this extension https://marketplace.visualstudio.com/items?itemName=geddski.macros

and create keyboard shortcut to a macro such as 
```json
        "githubPullRequest.nextFile": [
            "workbench.action.closeActiveEditor",
            "pr:github.focus",
            "macros.pullRequest.selectNextFile",
        ],
```

**Comment by mogelbrod** [comment]
Looking at the [declaration for `pr.markFileAsViewed`](https://github.com/microsoft/vscode-pull-request-github/blob/5c469d85006612b5590d7b4c8098b9005e83d520/src/commands.ts#L932) it seems to expect a URI object (`{ path: string }`). I tried adding the following keybinding:
```json
  {
    "key": "cmd+g v",
    "command": "pr.markFileAsViewed",
    "args": { "path": "${file}" },
  }
```
While it no longer shows any error message it also doesn't seem to mark the current file as viewed either. Not sure if the `${path}` interpolation is expanded as I expected either.

**Comment by alexr00** [comment]
`pr.markFileAsViewed` will mark the active file as viewed now (and it will close it).

There is also a command for going to next diff across files: Go to Next Diff in Pull Request.

**Comment by ian-h-chamberlain** [comment]
Nice! Is there any equivalent "Go to Previous Diff in Pull Request"? From a quick look I don't see one, should I file a new issue to request that?

**Comment by alexr00** [comment]
@ian-h-chamberlain Adding the "Go to Previous Diff in Pull Request" command here: https://github.com/microsoft/vscode-pull-request-github/pull/4328
It should be in the pre-release build of the extension tomorrow.
