### ISSUE TITLE
Adding comments to a review creates multiple reviews

### ISSUE THREAD

**Issue by abrookins** [microsoft/vscode-pull-request-github#1343]
- Extension version: 0.11.2
- VSCode Version: 1.38.1
- OS: MacOS High Sierra

Expected: When I write a comment on a review from within VS Code and click "Start a review," then add a second comment, both comments should appear in the same review. The review should only post to Github when I finish it.

Actual: When I write a comment on a review from within VS Code and click "Start a review," the review is posted immediately with my comment. If I add a second comment, a second review is posted.

Steps to Reproduce:

1. Authenticate via token with GHE
2. Open Pull Requests View
3. Open the "Description" of a pull request
4. Click Checkout
5. Navigate to a changed file and click + to add an inline comment
6. Type the comment and click "Start a review"
7. Check Github: a review has been posted with your comment
8. If I click + again, the option is to "Start a review"

**Comment by neils95** [comment]
- Extension version: 0.12.0
- VSCode Version: 1.40.0
- OS: Windows 10
- Github enterprise version: 2.15.6

I am still experiencing this @RMacfarlane  Every comment i add publishes a new review.
