### ISSUE TITLE
Text wrap option

### ISSUE THREAD

**Issue by jrodel17** [microsoft/vscode-pull-request-github#1344]
I think you should add an option to wrap text. I am writing a larger project report in latex using vscode and github. 

However when I write latex in vscode I have autowrap text on, but when reviewing pull requests the text is not wrapped, when using this extention for PRs, I think it should at least be an option.

NB! This is related to #446 , which I think is a good idea, but im not talking specifically about the comments here.

**Comment by alexr00** [comment]
VS Code lets you wrap text in diff editors now: `diffEditor.wordWrap`.
