### ISSUE TITLE
Cannot Log in or Authenticate

### ISSUE THREAD

**Issue by OliverHuntsman** [microsoft/vscode-pull-request-github#1346]
- Extension version: 0.11.2
- VSCode Version:  1.38.1
- OS: Mac OSX 10.14.4

Steps to Reproduce:

1. CMD + SHIFT + P to authenticate manually
2. Paste token generated from settings in github
3. Use the server github.com(not sure if this is the correct server) 

Nothing happens

**Comment by RMacfarlane** [comment]
@OliverHuntsman Did the normal auth flow fail for you? Are you using GitHub enterprise?

**Comment by OliverHuntsman** [comment]
Just nothing happened. 

I’m not using an Github enterprise

**Comment by RMacfarlane** [comment]
@OliverHuntsman To clarify, when you first tried to authenticate, did you use the `Github Pull Requests: Sign in to GitHub` command?

Can you check that the folder you have open is pointing to a GitHub remote? (Run `git remote -v`)

**Comment by lvarado** [comment]
FYI, I had the same issue and came here looking for clues. Turns out I had to open a folder in a new window with vscode to get this extension set up. I previously had a workspace open with multiple folders and there was no sign in button on the status bar, and manual setup didn't work. Might be something worth trying.

**Comment by OliverHuntsman** [comment]
Here’s the issue


https://drive.google.com/a/gemmasutton.com/file/d/1RryZVvLaiUNmS3NGLkqKM7YBcdcs4R7p/view?usp=drivesdk

How do you mean you opened a folder in a new window? Which folder? Any folder?

**Comment by lvarado** [comment]
That drive link needs sharing permissions, I'm not able to see it. To clarify what I said earlier, I opened one of my project folders which has a git repo in it. I'm not sure if the repo matters, you may be able to open any folder.

**Comment by OliverHuntsman** [comment]
@RMacfarlane There is no `Github Pull Requests: Sign in to GitHub `command?

**Comment by OliverHuntsman** [comment]
@lvarado I've changed the sharing now, the folder doesn't have a git repo in it bu tI get the same results with a folder which does have a git repo

**Comment by RMacfarlane** [comment]
@OliverHuntsman If you click on the GitHub icon on the activity bar on the right, what message is shown? Can you run the `View: Toggle Output` command (by Cmd + shift + p) and choose "GitHub Pull Requests" from the dropdown and copy the output from that?

**Comment by OliverHuntsman** [comment]
Hi, no output

![Screenshot 2019-10-10 at 22 12 14](https://user-images.githubusercontent.com/33024777/66607045-491bbb80-ebab-11e9-950e-3d8c89f4a297.png)

**Comment by RMacfarlane** [comment]
Ok, thanks, this helps. What's the result of running `git remote -v` in the terminal?

**Comment by OliverHuntsman** [comment]
Sorry for the delay on replying

![Screenshot 2019-11-04 at 15 47 34](https://user-images.githubusercontent.com/33024777/68134777-852c0d00-ff1a-11e9-85d3-f74af91cd04c.png)
![Screenshot 2019-11-04 at 15 47 47](https://user-images.githubusercontent.com/33024777/68134778-852c0d00-ff1a-11e9-8523-36a068ca96fa.png)

**Comment by OliverHuntsman** [comment]
OK, so now I've set the remote repository as Github using the terminal and pull requests is ow working - thank you so much for your help.

FYI I used this command when I created a new repository in GitHub for an existing directory on my machine. I guess the obvious was staring me in the face

![Screenshot 2019-11-04 at 15 58 33](https://user-images.githubusercontent.com/33024777/68135720-059f3d80-ff1c-11e9-94ce-ce9b4636ce0c.png)
