### ISSUE TITLE
Sign-out picker: do not close on focus lost

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-pull-request-github#1348]
I feel like the quick input picker to ask for which service to sign out should be configured to not close on focus lost because it asks for input (e.g. shows checkboxes).

![image](https://user-images.githubusercontent.com/900690/65960237-4c4cd400-e454-11e9-9701-4949e881a08e.png)

**Comment by JeffreyCA** [comment]
How should the user dismiss the picker without signing out?

**Comment by bpasero** [comment]
I do not understand. I have filed a PR to fix this: https://github.com/microsoft/vscode-pull-request-github/pull/1354

**Comment by RMacfarlane** [comment]
Pressing esc will cancel the action
