### ISSUE TITLE
Show loading indicator when waiting for auth

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode-pull-request-github#1355]
<img width="317" alt="image" src="https://user-images.githubusercontent.com/35271042/66140071-54248980-e5b6-11e9-93df-29e9d426fa13.png">

After I authorized GitHub from the browser and went back to VS Code, there was a slight delay (3-5s) where nothing was happening and I wasn't sure whether the auth worked. I expected there to be a progress/loading indicator on the "Sign In" section of the GH viewlet so that the I knew to wait (either a spinner or the viewlet progress bar up top).

**Comment by alexr00** [comment]
Closing as auth is part of core now.
