### ISSUE TITLE
Adding gif in PR shows "An error occurred while loading the image"

### ISSUE THREAD

**Issue by octref** [microsoft/vscode-pull-request-github#1356]
- Extension version: 2019.9.38342
- VSCode Version: 1.39.0-insider
- OS: macOS 10.14

Steps to Reproduce:

1. Have a PR that adds a gif (like https://github.com/microsoft/vscode-extension-samples/pull/108)
2. Open the Files -> demo.gif from "Changes in pull request"

![image](https://user-images.githubusercontent.com/4033249/66167508-27409880-e5ef-11e9-9f74-0b31d138a563.png)

**Comment by JeffreyCA** [comment]
Might be related to https://github.com/microsoft/vscode/commit/b8869cd9891e6653e2b8ca01e679d20e705f452c#diff-c4bac697371864c22d8c91f349b5865b
