### ISSUE TITLE
Commenting range not shown after checking out PR

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode-pull-request-github#136]
- Open [pullrequest-demo](https://github.com/auchenberg/pullrequest-demo/) repo
- Open `routes/index.js` under the "Remove unused variables" tree while on master
- Checkout that branch
- Click on `routes/index.js` within the PR tree again
- Comment affordance is only shown for existing comments, not around diff hunks

![screen shot 2018-08-06 at 4 14 39 pm](https://user-images.githubusercontent.com/3672607/43745498-e9313fac-9993-11e8-8f6a-b5a72b5ab63c.png)

**Comment by rebornix** [comment]
There are two bugs that contribute to this error

* When we expand a pr node and checkout from the tree view, the commenting providers are registered more than once (probably the first one is not disposed correctly)
* The comment contribution internally fails if comment thread id is not globally unique.
