### ISSUE TITLE
Comment drag handle is white when scrollbar is visible

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-pull-request-github#1361]
Dunno if you have control over this or if it's just the browser?

![Jul-31-2019 16-38-00](https://user-images.githubusercontent.com/323878/62255345-9dd3d680-b3b1-11e9-8830-2cd47eed41dc.gif)

**Comment by JeffreyCA** [comment]
The best I could get was setting the `::-webkit-scrollbar-corner` pseudo element background color to transparent.

```css
::-webkit-scrollbar-corner {
    background-color: transparent;
}
```

Result:
<img width="679" alt="Screen Shot 2019-10-14 at 10 01 25 PM" src="https://user-images.githubusercontent.com/9157833/66801891-81830880-eecf-11e9-82c3-40d117805699.png">

There is still a white border around the top and left sides of the square.

**Comment by RMacfarlane** [comment]
@JeffreyCA I think that looks better than before

**Comment by JeffreyCA** [comment]
I agree, I looked into whether there were any other instances of this. The Issue Reporter text area resizer also has the same appearance when there are scrollbars:

<img width="622" alt="Screen Shot 2019-10-15 at 10 26 20 PM" src="https://user-images.githubusercontent.com/9157833/66890440-13a41300-ef9b-11e9-8a05-22c709d9dbb7.png">
