### ISSUE TITLE
Don't autoexpand PR comments when switching files

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-pull-request-github#1363]
- Add PR comment in editor
- Switch to another file tab
- ctrl+tab back to the original tab
- All comments are visible

This gets in my way when adding lots of comments and switching around files. One thing I like about reviewing in vscode is that I can focus on the code. I can see why some people might like this so maybe it can be configurable?

**Comment by RMacfarlane** [comment]
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/1268
