### ISSUE TITLE
The "Delete Review" button **really** needs an "Are you sure?" dialog

### ISSUE THREAD

**Issue by bryceschober** [microsoft/vscode-pull-request-github#1364]
The "Delete Review" button **really** needs an "Are you sure?" dialog

Without thinking through what I was doing, I clicked on it, and my WTFs per minute spiked in the ensuing regret-fest.

**Comment by RMacfarlane** [comment]
Yes, we should definitely add an additional dialog to prevent this. Sorry for your lost work!
