### ISSUE TITLE
Remove the "Finish Review" button from the in-code comment dialog

### ISSUE THREAD

**Issue by bryceschober** [microsoft/vscode-pull-request-github#1365]
It really seems out-of-place, has no equivalent in the GitHub UI, and doesn't allow the user to specify the review result type. If nothing else, it deserves a dialog asking:
> Are you sure you want to submit all pending comments with a 'comment' review status?

**Comment by bryceschober** [comment]
I suppose it would be fine if it was just a convenience short-cut to the more full-featured dialog on the "Description" page...

But now that I look at that more closely, it's differences to the standard GitHub UI are confusing. It looks like the VS Code version in the "Description" page doesn't allow the "comment" review result that the GitHub UI does.

IMO, the GitHub UI is much more logical in both review submission contexts, and the VS Code extension deserves to be that good:

1. Both review submission contexts (conversation vs. files views) present all three review result options.
1. Both review submission contexts have a "global" comment context, out-of-line from file comments, which is as it should be.

**Comment by mattdaviscodes** [comment]
This could still use some work.

**Comment by dancoates** [comment]
I just had this same problem when using the pull request extension for the first time. I expected the "Finish Review" button to present me with options to "Approve", "Request Changes" or "Comment" but instead it just did the equivalent of the "Comment" option on github. 

This meant that I then had to Request Changes separately and leave a redundant comment as you can't Request Changes without a comment.

**Comment by RMacfarlane** [comment]
Closed with https://github.com/microsoft/vscode-pull-request-github/pull/2670, the "Finish Review" button is now replaced with an "Open Review" button that goes to the description page and scrolls the pending review into view. The "Approve", "Request Changes", and "Comment" buttons are visible there and the review is seen in it's entirety, so hopefully this is clearer now. Please let me know if you have any additional ideas on how to improve it!
