### ISSUE TITLE
Display pending label for all pending comments on the description page

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode-pull-request-github#1369]
![Screen Shot 2019-10-09 at 2 37 22 PM](https://user-images.githubusercontent.com/3672607/66522533-80eb0c00-eaa2-11e9-91b6-6bfa9905239a.png)

Comments that are pending should be marked with a label like they are on GitHub. In this example, I replied twice to an existing comment. Both "test" comments have not yet been posted, but look like they are already appended to the existing review.

![Screen Shot 2019-10-09 at 2 41 32 PM](https://user-images.githubusercontent.com/3672607/66522703-ed660b00-eaa2-11e9-8364-78a797bd1808.png)

**Comment by akosasante** [comment]
👋  I'd like to take a look at resolving this

**Comment by RMacfarlane** [comment]
@akosasante Great! The code that renders the comments is here: https://github.com/microsoft/vscode-pull-request-github/blob/1432e8ab94c2b046e810b08ea14c21d71f15b543/preview-src/comment.tsx#L20
