### ISSUE TITLE
Cant comment on added line when the repo is checked out

### ISSUE THREAD

**Issue by yulrizka** [microsoft/vscode-pull-request-github#1374]
- Extension version: v0.12.0
- VSCode Version: 1.40.0-insider
- OS: osx

Steps to Reproduce:

1. Open a pull request
2. Checkout the source code using Description page
3. Open a file with added line

expectation:
I would see the white gutter to be able to comments

reality:
The white gutter was not shown. See below on the right side
<img width="690" alt="a" src="https://user-images.githubusercontent.com/117752/66605421-5e471900-ebb0-11e9-9d82-0f4511e9fdfe.png">

This doesn't happens if i view the file using the "Github Pull Requests" section (branch not checked out)

see https://github.com/microsoft/vscode-pull-request-github/issues/1339#issuecomment-539727771 for extra details

**Comment by yulrizka** [comment]
I think i found the problem. This happens if the root of the root folder (project) is not the same as the git repository.

https://github.com/microsoft/vscode-pull-request-github/blob/93f6317869a62b885078072e6f816ef44ae3686c/src/view/reviewCommentController.ts#L441-L442

for example:
```
- repo
  - .git
  - a
    - b
      - c
        - file1
```

For example if `file1` changed:

* If I open open vscode on the root (`repo`), relative path would be `a/b/c/file1`
* If I open the root on `repo/a/b`, relative path would be `c/file1`
That's why it doesn't match.

Is there any way to get the directory relative to the git repository instead of the project?

**Comment by RMacfarlane** [comment]
Nice find! The comment controller stores a `_repository` property that has information about the git repository, including the path to the root: `this._repository.rootUri.path`. So I think something like `nodePath.relative(this._repository.rootUri.path, document.uri.path)` would work

**Comment by yulrizka** [comment]
Hmm it seems that it's not so easy to changed. For example this line now failed

https://github.com/microsoft/vscode-pull-request-github/blob/93f6317869a62b885078072e6f816ef44ae3686c/src/view/reviewCommentController.ts#L389-L393

It seems that this was design to be workspace related. I found 6 instances of `asRelativePath`.

**Comment by yulrizka** [comment]
I tried to change all of the them, seems to be working. But I'm not too familiar with the whole code thus I'm not sure what the impact will be :sweat_smile:
