### ISSUE TITLE
Multi line comments

### ISSUE THREAD

**Issue by urandu** [microsoft/vscode-pull-request-github#1376]
Currently on GitHub, it is possible to have multi line comments. It would be whorthwile to also have this feature on this extension.

I would be more than happy to take this up..

**Comment by RMacfarlane** [comment]
Yes, this would be great to have!

To get this to work will require some changes in VSCode, it controls the gutter that is used to add comments. It would need to add support for opening the comment editor from a selection.

**Comment by Chathula** [comment]
is there any update on this? waiting for this :(

**Comment by urandu** [comment]
@Chathula I will be pushing out a PR on this within a week from now

**Comment by ltshb** [comment]
> @Chathula I will be pushing out a PR on this within a week from now

Any news on when this will be released ? I'd be very interested in this feature :-)

**Comment by selrond** [comment]
@urandu have you made any progress?

**Comment by MarthinusBosman** [comment]
@urandu I believe this functionality worked a while back, but no longer does.

**Comment by gabrieledcjr** [comment]
@urandu any updates?

**Comment by urandu** [comment]
@gabrieledcjr @MarthinusBosman I'm testing this functionality ans should be able to publish a PR in the next few days. I will keep you posted.

**Comment by chaicesan** [comment]
What's the latest on this?

**Comment by 7azycoder** [comment]
Any updates on this?

**Comment by zoltan-patchworks** [comment]
This feature would be really useful.

**Comment by irenepc** [comment]
I hope there'll be some more progress soon! Every time I make another attempt at using the PR tools in vscode I seem to get stuck on a new snag. This would be awesome to have!

**Comment by dsinni** [comment]
This would be a great to have. I keep finding myself having to go back to GitHub to make these comments, which takes away from the great convenience this provides otherwise.

Looking forward to this feature!

Maybe slightly off topic, but it would also be great to have UI for adding code suggestions in the comments similar to how it works on GitHub.

**Comment by shamar-morrison** [comment]
Has there been any updates on this? Would love for it to get added

**Comment by alexr00** [comment]
Upstream issue: https://github.com/microsoft/vscode/issues/146510

**Comment by alexr00** [comment]
The upstream issue is complete!
