### ISSUE TITLE
Add Projects and Milestone when view pull request

### ISSUE THREAD

**Issue by beriberikix** [microsoft/vscode-pull-request-github#1379]
When viewing a pull request description there is an option to add a reviewer and label. On github.com you can also add Projects and Milestones. It would be very convenient
<img width="387" alt="Screen Shot 2019-10-12 at 9 03 54 AM" src="https://user-images.githubusercontent.com/178376/66704317-93965880-eccf-11e9-90c1-531a293c4b85.png">
 to mirror the options.

**Comment by lifez** [comment]
@RMacfarlane I would to work on this feature. But first could you please tell me how to develop without often press refresh button. Do we have something like hot reload ?

**Comment by RMacfarlane** [comment]
@lifez If you change code in the `preview-src` folder and close and reopen the webview after compiling, it should be updated. For code changes outside of that folder, the VSCode window needs to be reloaded to pick up the changes

**Comment by rfdunn** [comment]
This would be a really helpful enhancement. We track things across multiple project boards and so every pull request requires a project - which currently means you always have to go to the website to edit the PR and assign to the appropriate project, which sort of makes the Extension redundant.

**Comment by CatsMiaow** [comment]
There should also be `Assignees`. https://github.com/microsoft/vscode-pull-request-github/issues/1186

**Comment by alexr00** [comment]
We now have "Reviewers", "Assignees", "Labels", and "Milestones". No plans to add others at this time!
