### ISSUE TITLE
New PR filter option: Subscribed

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#139]
Looking at the like I think a very useful filter option should be subscribed PRs, that is the union of assigned, created, waiting for my review and PRs you have commented on (and excluding ones I've unsubscribed from if possible).

**Comment by alexr00** [comment]
The GitHub API doesn't provide a way to get items that you're subscribed to (as far as I can see). This would also be a large break with the existing GitHub issue/PR query language since it also doesn't provide a way to do that.
