### ISSUE TITLE
sign in problem

### ISSUE THREAD

**Issue by ebubekirduman** [microsoft/vscode-pull-request-github#1398]
Issue Type: <b>Bug</b>

I can't access Github. Output error:
"[Info] /Users/ebubekirduman/.ssh/config: EISDIR: illegal operation on a directory, read
[Info] Looking for Go repository "

how do I solve this problem?

Extension version: 0.12.0
VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:00.827Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|8.00GB (1.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by RMacfarlane** [comment]
@ebubekirduman The ssh config error can be ignored, it doesn't matter if this isn't found. The "Looking for Git repository" message indicates that the Git extension doesn't associate the folder you currently have open with a git repo. Do you have git installed and a folder associated with a git repo open?
