### ISSUE TITLE
Display of outdated comments on description page

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode-pull-request-github#1407]
- Extension version: 0.12.0

Steps to Reproduce:

1. Open the description page on a PR that has outdated comments

I believe there was previously a box rendered near the top of the comment saying "Outdated". At a minimum, we should bring that back. Even better would be having a collapsed view of these by default as they are on github.com and a way of toggling their visibility

**Comment by JacksonKearl** [comment]
> having a collapsed view of these by default as they are on github.com and a way of toggling their visibility

I actually don't see them collapsed by default on GitHub... on GitHub there is a separate "Mark Resolved" button, and "Resolved" threads are collapsed by default. A thread con be resolved even if it is not outdated, so I think this is an orthogonal feature.

**Comment by JacksonKearl** [comment]
Looks like resolving convos is already covered in #339. #1417 adds the "Outdated" label, I'll look into "Resolved" next.
