### ISSUE TITLE
Load more fails in Assigned To me

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-pull-request-github#1409]
Issue Type: <b>Bug</b>

```
Element with id Assigned To Me
https://github.com/microsoft/vscode/pull/80477 is already registered
```

Not sure yet if it's because of the recent change of caching.

Extension version: 2019.10.34029
VS Code version: Code - Insiders 1.40.0-insider (b53811e67e65c6a564a80e1c412ca2b13de02907, 2019-10-24T07:02:04.820Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.49GB free)|
|Process Argv|-psn_0_6198761|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by RMacfarlane** [comment]
@rebornix We added an `id` property to the pull request node, which allows the tree implementation to preserve collapsed state across refreshes: https://github.com/microsoft/vscode-pull-request-github/blob/b603c271aaf443301524118578902a6c2fbdbde3/src/view/treeNodes/pullRequestNode.ts#L452

Do you know how that PR is getting duplicated in the "Assigned to Me" section? Do you have differently named remotes that point to the same repo?
