### ISSUE TITLE
Spurious "This branch has conflicts that must be resolved" warning

### ISSUE THREAD

**Issue by foolip** [microsoft/vscode-pull-request-github#1412]
- Extension version: 0.12.0
- VSCode Version: 1.39.2
- OS: Debian 4.19.37

Steps to Reproduce:

1. Clone the wpt repo and find https://github.com/web-platform-tests/wpt/pull/19754 in the list of pull requests in VS Code. For me it's under "Created By Me" but for others it may be hard to find.
2.At the bottom of the "Description" view, "This branch has conflicts that must be resolved" will be shown. But there are no conflicts to resolve.

Screenshot:
![image](https://user-images.githubusercontent.com/498917/67551047-3c997600-f708-11e9-8979-299343575395.png)

**Comment by foolip** [comment]
If it'll help to debug this issue, at the time I was looking the `refs/pull/19754/merge` ref of the repo was pointing at https://github.com/web-platform-tests/wpt/commit/4c234adbd7ffa423a23deafecd9c1a9a832f24ce. The first parent of that merge is https://github.com/web-platform-tests/wpt/commit/b482734e5092c5f5a6aadc66aa1c599742f2dc67 (the master branch) and the second is https://github.com/web-platform-tests/wpt/commit/3cb58e960af6312e9792ec4bbd0e73bfdada1805 (head of the PR branch). No conflict.

**Comment by RMacfarlane** [comment]
Thanks for reporting this @foolip! Looks like we are missing a "pending" state for this message - should display that the mergability is still being calculated in that case

**Comment by foolip** [comment]
Aha, that would explain it. I had just created the PR then.
