### ISSUE TITLE
PRs view always show expanded on reload even if collapsed

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode-pull-request-github#1422]
- Extension version: `Nightly 2019.10.36902`
- VSCode Version: `1.40-insiders`
- OS: `Windows 10 (1903)`

I always keep the PRs view collapsed on the SCM sidebar, but every time I reload, the view expands itself

**Comment by RMacfarlane** [comment]
@eamodio This is with the `githubPullRequests.showInSCM` setting set to true? I'm also seeing this with VSCode stable

**Comment by eamodio** [comment]
@RMacfarlane Yup -- yeah, this is definitely not new.

**Comment by alexr00** [comment]
I can't repro this now (and that setting is deprecated).
