### ISSUE TITLE
Reviewers should be listed in a "relevance" order

### ISSUE THREAD

**Issue by curtisgibby** [microsoft/vscode-pull-request-github#1424]
Currently, the "Add Reviewers" popup lists potential reviewers in an order that I don't understand. It's not alphabetical, it doesn't appear to have anything to do with people who've recently interacted with the files in the PR, or even the repo itself. I simply see everyone in my organization.

![image](https://user-images.githubusercontent.com/1086964/67722302-610e8000-f99e-11e9-92b6-e82368fc3591.png)

It would be helpful if "relevant" people were at the top of the list, however you might define "relevant". Perhaps that's a simple local cache of previously-selected users; perhaps you would be able to use a GitHub API similar to the one that the GH site itself uses to suggest specific reviewers based on people who've edited the relevant files.

![image](https://user-images.githubusercontent.com/1086964/67723236-06c2ee80-f9a1-11e9-8b69-66cdcbbe31e4.png)

If nothing else, I'd prefer to have the list of possible reviewers sorted in alphabetical order (as seen in the lower section of the GH screenshot above) instead of the seemingly-random order that I get now.

**Comment by IllusionMH** [comment]
@RMacfarlane I can take a look at this suggestion today if there are no objections.

As I can see now all `mentionableUsers` are pulled for repository, however GitHub displays only `assignableUsers`.
Are there any drawbacks if I'll change request to `assignableUsers` instead?

**Comment by curtisgibby** [comment]
Also, would it be possible to pull the users' GitHub avatars into the list, for quick visual reference?

**Comment by IllusionMH** [comment]
At this moment built-in VS Code [Quick Pick component](https://code.visualstudio.com/api/references/vscode-api#window.showQuickPick) is used for list and it has limited API with only few text fields to display for an item.

Custom dropdown implementation inside WebView would be required to display avatars and it's up to maintainers to decide if it should be implemented.
IMHO it should be separate issue and this can be only for tracking list content improvements.

**Comment by RMacfarlane** [comment]
@IllusionMH That would be great!

The extension also registers a completion provider for completing usernames when using '@' in editor comments, so we should make sure that code path still uses `mentionableUsers`. Moving to `assignableUsers` for this makes sense to me.

**Comment by curtisgibby** [comment]
I agree that using the `assignableUsers` instead of the `mentionableUsers` makes sense, and should theoretically help pare down the list of users in that Quick Pick component. However, I'm unclear if something can be done about the sort order of the users in that list as well. Can someone help me understand the logic behind the current ordering?

**Comment by IllusionMH** [comment]
@RMacfarlane thanks I saw that there is another usage, but wasn't sure how to trigger it for sure (looks like only comments use this list and I tried in WebView). I'll create separate requests for reviewers.

@curtisgibby current order depends on what GitHub API returns - no sorting applied. So question is to GH devs.
But I'll add sort by `login` at least.
