### ISSUE TITLE
Add a confirmation prompt to 'Delete Review'

### ISSUE THREAD

**Issue by justasitsounds** [microsoft/vscode-pull-request-github#1429]
Currently clicking the 'Delete Review' button in the comment interface deletes the entire review, without prompting for confirmation. It also looks the same as the 'Finish Review' and 'Add Comment' buttons that it appears alongside - the only distinction being the text. I would argue that 'Delete Review' and 'Add Comment' functionality do not belong together - they should not be presented in the same part of the interface

I would like to suggest any of:
- change the colour/position of the 'Delete Review' button in the comment interface
- Add a confirmation prompt that makes it clear to the user that the button won't just delete the active comment, but the entire review session
- move the 'Delete Review' button to the top-level 'Description/Summary' view, rather than the comments interface

thanks for listening and thanks for a great product (minor UX issues aside)

**Comment by justasitsounds** [comment]
Some more UX ideas for how to prevent accidental data loss: https://uxmovement.com/buttons/how-to-design-destructive-actions-that-prevent-data-loss/

**Comment by RMacfarlane** [comment]
Thanks for the feedback @justasitsounds!

We've checked in a fix for adding a confirmation dialog here, but it hasn't been shipped yet: https://github.com/microsoft/vscode-pull-request-github/issues/1364 Our release schedule roughly follows VSCode so we should create a new version of the extension next week.

I agree that having the 'Delete Review' button doesn't really belong on individual comments, as it's destructive and acting on the review as a whole. There's similar feedback about the 'Finish Review' button: https://github.com/microsoft/vscode-pull-request-github/issues/1365 We were worried that it would be difficult to discover these if they were only on the Description page, but deleting or submitting a review makes the most sense from that page, where you can actually see all of the pending comments in the review. Maybe we could add a way to navigate to the whole review from a single comment

**Comment by RMacfarlane** [comment]
Closing as we're introducing a way to navigate to the whole review with an `Open Review` action, and removing the `Delete Review` button https://github.com/microsoft/vscode-pull-request-github/pull/2670
