### ISSUE TITLE
Deleting local pull request branch failed, branch not found

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode-pull-request-github#143]
1. Checkout the "Monokai Fixes" PR from the VSCode repo
2. Checkout master again
3. Try to delete the branch from the "Local Pull Request Branches" section

The branch name being used for the delete is incorrect

**Comment by rebornix** [comment]
@RMacfarlane this feature is a bit complex AFAIK, we may want to clean the remote and related configs which we create specifically for the PR branch.

**Comment by RMacfarlane** [comment]
Ah whoops I just saw your comment. Good point, I missed cleaning the git config

**Comment by RMacfarlane** [comment]
Added code to check if the remote should also be deleted. The git config automatically updates when running `branch -D` and `remote remove`, removing the whole branch or remote section, so that gets rid of any extension added keys
