### ISSUE TITLE
Support Azure DevOps Pull Requests

### ISSUE THREAD

**Issue by mjmatthiesen** [microsoft/vscode-pull-request-github#1432]
[I've read this](https://github.com/Microsoft/vscode-pull-request-github/wiki#4-what-about-supporting-other-providers-such-as-gitlab-and-bitbucket). I understand why you wouldn't necessarily support competitors. Github is MS. DevOps is MS. The current Azure extension is awful as far as PR support goes.

I have not delved into the source of this extension at all, so I cannot imagine what the difficulty of this would be. It just seems like MS is leaving behind people who invested in the once and still kind of awful devops in favour of a lot of often and mostly free users.

**Comment by RMacfarlane** [comment]
Hi @mjmatthiesen, I'm sorry for your frustration, but this request is out of the scope of this project.

This extension is tightly coupled to GitHub and is meant for that audience. It is a totally reasonable ask to build another extension that would do the same for Azure DevOps, or add it to an existing Azure extension, but we do not want to have to support both here. The GitHub API is similar to Azure DevOps, but it would require quite a lot of work to make sure that we can make equivalent calls for both and normalize data between them. Most users will be using one or the other, so we think a better solution would be to have them as separate extensions.

**Comment by Trass3r** [comment]
Someone already implemented it but it's not maintained: https://github.com/ankitbko/vscode-pull-request-azdo
