### ISSUE TITLE
Title in extensions sidebar too long

### ISSUE THREAD

**Issue by cbrnr** [microsoft/vscode-pull-request-github#1435]
The title in the extensions sidebar is "GITHUB PULL REQUESTS: GITHUB PULL REQUESTS". I guess one half can be removed so that it just reads "GITHUB PULL REQUESTS".

- Extension version: 0.12.0
- VSCode Version: 1.39.2
- OS: macOS 10.15.1

**Comment by RMacfarlane** [comment]
In VSCode for a custom viewlet, if there is only one view in it, it displays "{Viewlet name}: {View name}". 

We could considering showing the "Current Pull Request" view all the time to prevent this, with a message if the current branch is not associated with a PR.

**Comment by cbrnr** [comment]
Solved in the latest version (not just says "GITHUB").
