### ISSUE TITLE
Wrong minimum node version in wiki (minor)

### ISSUE THREAD

**Issue by wanderingstan** [microsoft/vscode-pull-request-github#1439]
tl;dr: Required _minimum_ version on wiki should be `>=8.9.3` not `>=8.9.1`. 

On the [Contributing](https://github.com/Microsoft/vscode-pull-request-github/wiki/Contributing#build-and-run) page of wiki it says node versions `>=8.9.1, <9.0.0`:

![image](https://user-images.githubusercontent.com/673455/68600202-4ee11700-045f-11ea-8d52-d7a038d2e0b3.png)

But the included module `vscode` seems to require `>=8.9.3`. (2 minor versions higher)
```
~/code/play-repos/vscode-pull-request-github$ yarn
yarn install v1.16.0
[1/5] 🔍  Validating package.json...
warning vscode-pull-request-github@0.13.0: The engine "vscode" appears to be invalid.
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
warning vscode-extension-telemetry@0.1.2: The engine "vscode" appears to be invalid.
error vscode@1.1.36: The engine "node" is incompatible with this module. Expected version ">=8.9.3". Got "8.9.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

Changing node version to 8.9.3 works.

**Comment by RMacfarlane** [comment]
@wanderingstan Thanks! I've updated the wiki.
