### ISSUE TITLE
Status bar button "Sign in on [Enterprise domain]" actually authorizes github.com

### ISSUE THREAD

**Issue by callumlocke** [microsoft/vscode-pull-request-github#1440]
- Extension version: 0.13
- VSCode Version: 1.40.0
- OS: macOS Mojave

Steps to Reproduce:

1. Open a GitHub Enterprise project in VSCode.
2. Note the status bar button offers to "Sign in on [github enterprise domain]":
  ![image](https://user-images.githubusercontent.com/250617/68600821-152e0180-049b-11ea-9258-9a151434ade3.png)
3. Click it, and it opens `vscode-auth.github.com/authorize...` in your browser, then when you click Continue, it wrongly takes you to to the authorization page on **github.com**. At the same time, it still misleadingly shows your Enterprise domain in the VSCode status bar:
  ![image](https://user-images.githubusercontent.com/250617/68600916-3db5fb80-049b-11ea-8d7f-99633dc85a1f.png)

**Comment by RMacfarlane** [comment]
@callumlocke Thanks for catching this! As a temporary work around, you can follow the directions here for manually adding an auth token: https://github.com/microsoft/vscode-pull-request-github/wiki#personal-access-token-authentication
