### ISSUE TITLE
Git: fatal: HttpRequestException encountered

### ISSUE THREAD

**Issue by Fleischhauer** [microsoft/vscode-pull-request-github#1443]
- Extension version: 0.13.0
- VSCode Version: 1.40.0 (user setup)
- OS: Windows_NT x64 10.0.17134

Steps to Reproduce:
1. Push commit
(Popup opens)
2. Enter credentials
(Pop-Down on top opens and asks again for username and password)
3. Enter credentials again
(Popup-Window shows error: Git: fatal: HttpRequestException encountered)

I use TFA. I'm behind a compony proxy and had to setup proxys in git to be able to clone the repo.
I tried signing in with the sign in button on the github tab, it opens the website but I can't click the authenticate button. I tried "manually provide Authentification Response", but nothing happens after I entered the token and github.com...

**Comment by RMacfarlane** [comment]
This sounds like two separate issues to me - pushing commits is handled by a separate, built in extension in VSCode. Do you see the same issue when pushing from command line?

For the authentication issue with this extension, can you go to the output panel in VSCode, choose "GitHub Pull Requests" from the dropdown, and paste the contents of the log here? Is there anything in the console log? (F1 -> Developer: Toggle Developer Tools)

**Comment by Fleischhauer** [comment]
You mean in the Command Palette? Git: Clone causes the same to happen.
Sorry, I'm not used to VSC and manually using GIT.

GitHub Pull Requests has several commands, which one?
When I toggle developer tools, the console on the right says:
[Extension Host] [vsonline][activate][info] Extension activating Object +94ms
console.ts:137 [Extension Host] [vsonline][EnvironmentDetailsExplorer][info] Updating environment details +17ms
The console on the bottom (git) says:
> git push origin master:master
Logon failed, use ctrl+c to cancel basic credential prompt.
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/Fleischhauer/writetest.git/'
Output (Github Pull Request) shows:
[Info] C:\Users\11305386\.ssh\config: ENOENT: no such file or directory, open 'C:\Users\11305386\.ssh\config'
[Info] Looking for git repository
[Info] Git repository found, initializing review manager and pr tree view.
[Info] Review> Validate state in progress
[Info] Review> Validating state...
[Info] No remote with name 'origin' found. Please update your 'githubPullRequests.remotes' setting.
[Info] No remote with name 'upstream' found. Please update your 'githubPullRequests.remotes' setting.
[Info] No GitHub remotes found
[Info] Review> Queuing additional validate state
[Info] Review> Validating state...
[Info] Review> Queuing additional validate state
[Info] Review> Validating state...
[Info] Review> no matching pull request metadata found for current branch master
[Info] Review> Queuing additional validate state
[Info] Review> Validating state...
[Info] No remote with name 'upstream' found. Please update your 'githubPullRequests.remotes' setting.
[Info] Found GitHub remote
[Info] Review> no matching pull request metadata found for current branch master
[Info] No remote with name 'upstream' found. Please update your 'githubPullRequests.remotes' setting.
[Info] No remote with name 'upstream' found. Please update your 'githubPullRequests.remotes' setting.
[Info] No remote with name 'upstream' found. Please update your 'githubPullRequests.remotes' setting.

**Comment by Fleischhauer** [comment]
I got it working now. I had to enter the token as password for git.
I also uninstalled this plugin and noticed that nothing changed. As I only wanted to push, it doesn't look like I need this plugin.

**Comment by RMacfarlane** [comment]
Ok, thanks for the update! I'll close this issue.
