### ISSUE TITLE
Improvements to merge squash

### ISSUE THREAD

**Issue by albireox** [microsoft/vscode-pull-request-github#1444]
It would be useful if the default commit message when using merge squash included the PR number, similar to what GitHub does. So, if the PR number is 16 the first line in the message would be "The Commit Message (#16)".

Similarly, the message could also contain a list of all the commit messages being squashed. The final commit message would be

```
The Commit Message (#16)

* The first commit

* The second commit

* Another commit

...
```

**Comment by felipecassiors** [comment]
The issue https://github.com/microsoft/vscode-pull-request-github/issues/1828 partially covers this, which have a PR open: https://github.com/microsoft/vscode-pull-request-github/pull/1924.

**Comment by brianjmurrell** [comment]
Second item of the original request is still open though.  When I squash and merge in the GitHub UI, it presents a default commit message of the commit messages from all of the commits in the PR merged together.

VS Code leaves the commit message completely empty.

**Comment by alexr00** [comment]
Fixed by https://github.com/microsoft/vscode-pull-request-github/issues/5306
