### ISSUE TITLE
Adding comments to a review creates multiple reviews

### ISSUE THREAD

**Issue by neils95** [microsoft/vscode-pull-request-github#1448]
- Extension version: 0.12.0
- VSCode Version: 1.40.0
- OS: Windows 10
- Github enterprise version: 2.15.6

I am still experiencing the bug reported in #1343  @RMacfarlane. Every comment i add publishes a new review.
Creating a new issue, since #1343 was closed.

**Comment by RMacfarlane** [comment]
@neils95 This has been fixed in the latest version of the extension, 0.13.0. I saw your other issue that caused you to downgrade to 0.12.0 and am working on a fix for it.
