### ISSUE TITLE
Fetching pull requests fails with "Not Found"

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode-pull-request-github#145]
@ramya-rao-a has a reliable repro, I haven't been able to repro on my machine

Clone Microsoft/vscode-go
When expanding any of the category nodes in the tree that isn't just "Local Pull Requests", the octokit/rest library throws

```
GitHubRepository> Fetching all pull requests failed: {"message":"Not Found","documentation_url":"https://developer.github.com/v3/pulls/#list-pull-requests"}
```

**Comment by ramya-rao-a** [comment]
Now everybody knows all the remotes I ever used...
