### ISSUE TITLE
PR Title hover edit icon causes reflow and click target moves (Bad UX)

### ISSUE THREAD

**Issue by mix3d** [microsoft/vscode-pull-request-github#1450]
- Extension version: 0.13.0
- VSCode Version: 1.40.1
- OS: MacOS Catalina, Windows 10
(has occurred for several versions of the plugin)

Steps to Reproduce:

1. Have a longer PR title in a somewhat narrow window.
2. Hover the title to edit or click the Link to see it in Github.com
3. The edit icon causes reflow and the target of click moves
![github vscode bug](https://user-images.githubusercontent.com/1474137/69171585-808a5b80-0ab9-11ea-901a-59dcf89bcd01.gif)

This is a UX _BadIdea<sup>TM</sup>_
Recommend some fixed padding so that the icon does not cause reflow when shown.

**Comment by phatmann** [comment]
This is actually so bad that I am considering not using the extension any more. Deeply distracting and disconcerting. 

@mix3d Would you consider submitting a PR to fix this?
