### ISSUE TITLE
"Element with id..." notification

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-pull-request-github#1452]
I keep seeing this pop up today, using the nightly extension

![image](https://user-images.githubusercontent.com/323878/69584373-e2ebcc00-0f91-11ea-9ef2-da376495b7a5.png)

**Comment by RMacfarlane** [comment]
@roblourens I'm having trouble reproing this, do you still see this?

**Comment by roblourens** [comment]
I haven't seen it recently.

**Comment by RMacfarlane** [comment]
Optimistically closing this, let me know if you see it again.
