### ISSUE TITLE
Changes in pullrequest empty left side

### ISSUE THREAD

**Issue by st-schneider** [microsoft/vscode-pull-request-github#1453]
Issue Type: <b>Bug</b>

When I click a file in the changes in pull request window the left side of the diff is empty as if the file was newly created/added. If I look at the file history with tools like gitlens I see the actual change.

Extension version: 0.13.0
VS Code version: Code - Insiders 1.41.0-insider (a63d88ec550107a66c08d813fb5d3c32c9e131a7, 2019-11-26T05:35:03.763Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by RMacfarlane** [comment]
@bm-stschneider I'm having trouble reproducing this, do you see this consistently for all files?

**Comment by bm-stschneider** [comment]
Currently I don't see this at all. Maybe some update fixed it?
