### ISSUE TITLE
Extra add comment

### ISSUE THREAD

**Issue by bm-stschneider** [microsoft/vscode-pull-request-github#1454]
Issue Type: <b>Bug</b>

There seem to be a leftover add comment in lowercase on inline discussions.
![image](https://user-images.githubusercontent.com/30625381/69619078-4d0c7b80-103b-11ea-8d29-61e99eec19e2.png)

Extension version: 0.13.0
VS Code version: Code - Insiders 1.41.0-insider (a63d88ec550107a66c08d813fb5d3c32c9e131a7, 2019-11-26T05:35:03.763Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by RMacfarlane** [comment]
@bm-stschneider Can you include your list of installed extensions? I don't see the string "Add comment" with this casing anywhere in the extension source code, so I'm unsure where it would be coming from

**Comment by bm-stschneider** [comment]
Not all of them are actually enabled, does that make a difference?

<details><summary>Extensions (66)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
cucumberautocomplete|ale|2.14.1
cypress-snippets|and|1.2.0
atlascode|atl|2.1.5
vscode-custom-css|be5|3.0.9
color-info|bie|0.5.1
markdown-mermaid|bie|1.4.1
mermaid-markdown-syntax-highlighting|bpr|1.0.1
better-toml|bun|0.3.2
twigcs|cer|1.1.0
vscode-opennewinstance|chr|0.0.6
scss-grammar-extended|dan|1.0.0
vscode-eslint|dba|1.9.1
eslint-disable-snippets|drK|1.2.0
gitlens|eam|10.2.0
vs-code-xml-format|fab|0.1.5
file-icons|fil|1.0.19
vscode-firefox-debug|fir|2.5.3
nightswitch|gha|1.1.0
vscode-architect|gil|0.1.0
comby-vscode|gil|0.0.1
vscode-pull-request-github|Git|0.13.0
todo-tree|Gru|0.0.162
rest-client|hum|0.23.0
output-colorizer|IBM|0.1.2
smarty|imp|0.3.0
path-autocomplete|ion|1.13.3
svelte-vscode|Jam|0.9.3
plantuml|jeb|2.13.5
polacode-2019|jef|0.5.1
browsersync|jer|2.1.1
vscode-peacock|joh|3.2.0
vscode-commitizen|Kni|0.8.4
twig-language-2|mbl|0.9.0
plantumlpreviewer|Meb|0.6.0
git-graph|mhu|1.19.0
vscode-scss|mrm|0.8.1
vscode-docker|ms-|0.8.2
remote-containers|ms-|0.85.0
remote-ssh|ms-|0.47.2
remote-ssh-edit|ms-|0.47.2
vscode-remote-extensionpack|ms-|0.17.0
references-view|ms-|0.0.31
debugger-for-chrome|msj|4.12.1
ts-prop-dag|nat|1.0.6
vscode-versionlens|pfl|0.24.0
prettier-vscode|pre|3.10.0
rpa-eslint-snippets|rav|0.0.2
vscode-yaml|red|0.6.1
elastic|ria|0.13.3
vscode-javascript-booster|sbu|0.11.0
code-settings-sync|Sha|3.4.3
stylelint|shi|0.51.0
svg-preview|Sim|2.7.7
sourcegraph|sou|1.1.0
tech-debt-tracker|Ste|0.15.0
cucumber|ste|0.12.0
gif-code-snippet|sub|1.0.2
vscode-mermaid-editor|tom|0.4.3
vscodeintellicode|Vis|1.2.0
vscode-icons|vsc|9.6.0
vim|vsc|1.11.3
vscode-mermaid-preview|vst|1.2.0
quokka-vscode|Wal|1.0.261
highlight-bad-chars|wen|0.0.3
scss-modules|won|1.0.1

(2 theme extensions excluded)

</details>

**Comment by bm-stschneider** [comment]
I don't have an idea where to look, sadly you can't see by which extension this was added. Should I check for multiple extension versions or reinstall?

**Comment by bm-stschneider** [comment]
Ok found it, hit that button and got an error in the dev console. Atlassian is to blame.
