### ISSUE TITLE
command: git.clone not found

### ISSUE THREAD

**Issue by GKServer** [microsoft/vscode-pull-request-github#1456]
Issue Type: <b>Bug</b>

I have tried reinstalling VS CODE and unable to open an online github repo
https://github.com/chucktomasi/sn-learn-javascript.git

Extension version: 0.13.0
VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.84GB (1.29GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by RMacfarlane** [comment]
@GKServer The `git.clone` command comes from the built in Git extension. Can you please file this issue on VSCode instead? https://github.com/microsoft/vscode 

The documentation here might be helpful: https://code.visualstudio.com/Docs/editor/versioncontrol#_git-support
