### ISSUE TITLE
UX: Plus/minus icons seem redundant

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode-pull-request-github#146]
![screenshot from 2018-08-09 15-46-28](https://user-images.githubusercontent.com/22350/43902954-999ac5d0-9beb-11e8-80bd-636a52dd4b9f.png)

**Comment by rebornix** [comment]
This is a core feature controlled by setting `diffEditor.renderIndicators`.

**Comment by joaomoreno** [comment]
Oh wow... I only noticed this now...? :open_mouth:
