### ISSUE TITLE
"Code Helper (Renderer) wants to use your confidential information..." osx pop-up

### ISSUE THREAD

**Issue by myartsev** [microsoft/vscode-pull-request-github#1464]
![image](https://user-images.githubusercontent.com/4885345/70551846-553dde00-1b46-11ea-8f65-6b1e739ed900.png)

- Extension version: 0.13.0
- VSCode Version: 1.40.2
- OS: macOS Mojave 10.14.6

![image](https://user-images.githubusercontent.com/4885345/70551736-1b6cd780-1b46-11ea-9a78-4948a53ff6f8.png)

Steps to Reproduce:

1. Open VS code
2. Get pop-up
3. Deny
4. Keep getting the pop-up intermittently throughout the day

**Comment by RMacfarlane** [comment]
@myartsev The extension stores your login credentials in the keychain, and tries to retrieve them when the extension loads. So seeing this popup the first time is expected. The keychain API doesn't expose a way for the extension to know if a user has explicitly clicked "Deny", so I don't believe there is a way for us to prevent additional asks if the window gets reloaded.

**Comment by myartsev** [comment]
@RMacfarlane sorry to be pedantic, but the "first time" for what? First time for when the extension gets installed (& it never needs it again?) or first time after launching vscode?

Either way, I've had the extension for a while, and this is somewhat recent, didn't use to have this come up before.

**Comment by Corry104** [comment]
it' one of your extensions that is causing this prompt to come out. Mine was Live-Share.
Disable all extensions, reload and then enable them again. You will see that the bugged one will show that prompt immediately as soon as you click the "enable" key. Remove the extension will fix it. If you really need that extension remove it and look for something that does the same but from a different source. If you can't find another source try a previous version of the same extension, sometimes it can be a bug during an update.
