### ISSUE TITLE
Delete local branches command surfacing branches that do not exist causing hang

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode-pull-request-github#1465]
In my case these were all the steps (not a minimal repro):

1. Have a bunch of branches from the extensions
2. Execute the `Delete local branches and remotes` command
3. Select all and delete

...wait... it did not terminate after several minutes

4. Reload window
5. Repeat 1 - 4
6. Execute the command again but select 1 branch.

:bug: => notice that the command hangs and Git output channel says the branch does not exist (which is true)

**Comment by RMacfarlane** [comment]
I checked in a fix to prevent showing the branch you are currently on in the quick pick and to properly exit on error. I'm still not sure why the git config is out of sync with git, I'm wondering if it's an issue with git for windows itself. What version are you using?

**Comment by sbatten** [comment]
```
git version 2.23.0.windows.1

Updates are available for:
	git: 2.23.0.windows.1 -> 2.24.0.windows.2
```
