### ISSUE TITLE
Unable to edit local file

### ISSUE THREAD

**Issue by OoDeLally** [microsoft/vscode-pull-request-github#1468]
- Extension version: 0.13.0
- VSCode Version: 1.41
- OS: Linux Mint 19.1

Steps to Reproduce:
1. Check out a PR 

![image](https://user-images.githubusercontent.com/1717629/70903060-5a93a080-1ffe-11ea-97e8-6ed48cffd258.png)

I'm on the correct PR branch.

2. Now I am unable to open the actual file to edit it.
The only option I have is to open it in GitHub.

![image](https://user-images.githubusercontent.com/1717629/70903144-8878e500-1ffe-11ea-9847-289af7d7a991.png)

I've seen screenshots where there are options in this contextual menu to open it.

The PR for that has been merged https://github.com/microsoft/vscode-pull-request-github/pull/1267

**Comment by OoDeLally** [comment]
When opening the local file in the regular way (edit-mode), I do have access to the comment.

![image](https://user-images.githubusercontent.com/1717629/70903513-55832100-1fff-11ea-992a-f386c4ec5cb7.png)

It proves that VSCode was able to make the connection between the remote file and the local file. But it simply doesnt give me the way to move from one to another.

**Comment by RMacfarlane** [comment]
Closing since this should now be easier when a PR is checked out. There is an inline action to go to the file in the "Change in Pull Request" view, and also an `Open File` button at the top of the file
