### ISSUE TITLE
keyboard shortcut Ctrl+P+Q for docker

### ISSUE THREAD

**Issue by jdkorigan** [microsoft/vscode-pull-request-github#1469]
Hello,

not sure if it is a bug, but when executing a container on VS code for Windows in a terminal and want to get out without killing it, Ctrl+P+Q should be used. But keyboard shortcuts are already assigned, 
so removing the intial keyboard shorcuts enable to make it work.
Ctrl-C doesn't work either, but exit can be used in that case.

Best regards

**Comment by RMacfarlane** [comment]
@jdkorigan I think you may have opened this issue in the wrong repository, this one is meant for the GitHub Pull Request extension. Perhaps https://github.com/Microsoft/vscode
