### ISSUE TITLE
Bad tree indent rendering

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode-pull-request-github#1470]
I am just using the GH PR extension, and the changes in src/lib are rendered less indented than the changes in the root

I was expanding this PR -- https://github.com/microsoft/monaco-typescript/pull/51

![image](https://user-images.githubusercontent.com/5047891/70984800-68f3c200-20bb-11ea-97a3-bc36e69e5cd4.png)

**Comment by alexr00** [comment]
This has been improved in microsoft/vscode.
