### ISSUE TITLE
command 'pr.refreshList' not found

### ISSUE THREAD

**Issue by Meno-101** [microsoft/vscode-pull-request-github#1472]
- Extension version: 0.13.0
- VSCode Version: 1.41.1
- OS: Windows 10 Pro latest update.

Steps to Reproduce:

1. cloned the repository and installed dependencies.
2. the actual extension works but the running doesn't.

It's very similar to the Issue #1411 other than it's a clone version, feel free to close this PR, I felt it's related but in a different approach.

the running command is npm run watch, screenshoot:
![Capture](https://user-images.githubusercontent.com/25272822/71603471-33d87c80-2b5d-11ea-9498-dc5e8ab7b208.PNG)

also it preducess same as this comment: https://github.com/microsoft/vscode-pull-request-github/issues/1411#issuecomment-547652737 same PR.

I've tried the fix but didn't work:
```diff
{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "extensionHost",
			"request": "launch",
			"name": "Launch Extension",
			"runtimeExecutable": "${execPath}",
			"args": [
				"--extensionDevelopmentPath=${workspaceFolder}",
-				 "--disable-extension=GitHub.vscode-pull-request-github-insiders"
+				"--enable-proposed-api GitHub.vscode-pull-request-github"
			],
			"skipFiles": ["<node_internals>/**/*.js", "**/node_modules/**/*.js"],
			"smartStep": true,
			"sourceMaps": true,
			"outFiles": [
				"${workspaceFolder}/media/*.js"
			]
		},
		{
			"name": "Extension Tests",
			"type": "extensionHost",
			"request": "launch",
			"runtimeExecutable": "${execPath}",
			"args": [
				"${workspaceFolder}/out/test",
				"--extensionDevelopmentPath=${workspaceFolder}",
				"--extensionTestsPath=${workspaceFolder}/out/test"
			],
			"outFiles": [
				"${workspaceFolder}/out/test/**/*.js"
			]
		}
	]
}
```

**Comment by RMacfarlane** [comment]
@Meno-101 Can you scroll up in the dev console to see if there is an error about the extension not activating?

**Comment by Meno-101** [comment]
Solved thanks 🙂
