### ISSUE TITLE
Unable to sign in - certificate expired error

### ISSUE THREAD

**Issue by TheSpyder** [microsoft/vscode-pull-request-github#1474]
- Extension version: 0.13.0
- VSCode Version: 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
- OS: macOS Catalina 10.15.2 (Darwin x64 19.2.0)

Steps to Reproduce:

1. Click sign in to github
2. Accept the browser authorization request
3. Whether the browser activates vscode, or I copy the authorization token into the `manually provide response` prompt myself, it fails with these details:

* VScode shows a notification `Error signing in to github.com`
* The status bar has changed to `Signed in to github.com` but when I close the notification it returns to `Sign in to github.com`
* The output panel for `GitHub Pull Request` shows a stack trace:
```
[Info] Error signing in to github.com: Error: certificate has expired
[Info] Error: certificate has expired
	at TLSSocket.onConnectSecure (_tls_wrap.js:1317:34)
	at TLSSocket.emit (events.js:200:13)
	at TLSSocket._finishInit (_tls_wrap.js:792:8)
	at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:606:12)
```

Nobody else I know is having this issue, so it's probably an issue with my config, what server is the extension trying to connect to? Both the GitHub website and the https://hub.github.com/ command line tool work perfectly 🤔

**Comment by benmcclelland** [comment]
I am seeing the same issue.

Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:57:51.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.2.0

extension version 0.14.0

**Comment by msgongora** [comment]
I'm having same issue after trying to sign in:

[```
Debug 167407s 650ms] PullRequestManager> Displaying configured remotes: origin, upstream
[Debug 167440s 213ms] Error signing in to github.com: Error: certificate has expired
[Debug 167440s 214ms] Error: certificate has expired
        at TLSSocket.onConnectSecure (_tls_wrap.js:1317:34)
        at TLSSocket.emit (events.js:200:13)
        at TLSSocket.EventEmitter.emit (domain.js:471:20)
        at TLSSocket._finishInit (_tls_wrap.js:792:8)
        at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:606:12)

```

**Comment by benmcclelland** [comment]
I just checked, and this happens starting with plugin version 0.12.0.  The last working version is 0.11.2.  I am able to install an older version by clicking setting icon for the plugin and selecting "Install Another Version..." then selecting 0.11.2.

**Comment by TheSpyder** [comment]
Seems to have fixed itself for the moment, decided to give it one more go before removing the extension and it worked. I'm not sure if there was a software update, or if whatever server the extension tries to connect to has changed certificates.

**Comment by l3ender** [comment]
I am still having this issue with VSC 1.42.1 on Windows with extension version 0.14.0.

I confirmed that the certificate is not expired and it is signed by a public CA.

```
[Info] Error signing in to git.myorg.org: Error: certificate has expired
[Info] Error: certificate has expired
	at TLSSocket.onConnectSecure (_tls_wrap.js:1317:34)
	at TLSSocket.emit (events.js:200:13)
	at TLSSocket._finishInit (_tls_wrap.js:792:8)
	at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:606:12)
```

@TheSpyder Could you please share any detail, or reopen the issue? Thanks!

**Comment by TheSpyder** [comment]
It's failing again for me too. What a mess.

**Comment by fpena06** [comment]
+1

**Comment by TheSpyder** [comment]
Using the vscode April 2020 update, the cert error pops up as a notification, so hopefully this issue will be a bit more visible now.

**Comment by TheSpyder** [comment]
vscode _itself_ is the one throwing the certificate error now. I guess I need to log this on the core vscode repo.

**Comment by gustavo-villalpando** [comment]
I solved the problem by adding:  **"secureOptions": { "rejectUnauthorized": false }**, on my sftp file.

{
 "name": "my server1",
 "host": "myhost.com",
 "port": 21,
 "type": "ftp",
 "username": "id",
 "password": "pw",
 "path" : "/",
 "secure": true,
 **"secureOptions": {"rejectUnauthorized": false}**
}

**Comment by TheSpyder** [comment]
A proper workaround has finally been found. The expired certificate is in the macOS keychain and vscode / nodejs is just using it incorrectly. For anyone who comes across this in the future, here's the fix:
https://github.com/microsoft/vscode/issues/97434#issuecomment-812094349

I'm closing this issue, because all that really needs to happen now is vscode adds detection of this issue and shows a useful error message.

**Comment by rainabba** [comment]
> A proper workaround has finally been found. The expired certificate is in the macOS keychain and vscode / nodejs is just using it incorrectly. For anyone who comes across this in the future, here's the fix:
> [microsoft/vscode#97434 (comment)](https://github.com/microsoft/vscode/issues/97434#issuecomment-812094349)
> 
> I'm closing this issue, because all that really needs to happen now is vscode adds detection of this issue and shows a useful error message.

It's only a "proper workaround" then if you're running OSX then :/

Any known workarounds for those running on Windows/WSL/Ubuntu?

**Comment by tempdeltavalue** [comment]
Try to open via site and got this error :( 
![Screenshot 2021-11-29 152605](https://user-images.githubusercontent.com/36921178/143867894-0068c3d9-ea18-4141-9996-e185bb8b1b77.png)

**Comment by clementnuss** [comment]
the issue only happens during sign-in, afterwards the sync works even without workaround.
I just did the following on my windows machine:
```cmd
; in a command line, e.g. cmd.exe
set NODE_TLS_REJECT_UNAUTHORIZED=0
code
```
you can then sign-in without issues. then restart vs code normally, without the `NODE_TLS_REJECT_UNAUTHORIZED` env variable and settings sync should work :)

For linux, I would expect that doing something such as 
```bash
export NODE_TLS_REJECT_UNAUTHORIZED=0
code
```
should produce the same results

**Comment by lixit** [comment]
> the issue only happens during sign-in, afterwards the sync works even without workaround. I just did the following on my windows machine:
> 
> ```batchfile
> ; in a command line, e.g. cmd.exe
> set NODE_TLS_REJECT_UNAUTHORIZED=0
> code
> ```
> 
> you can then sign-in without issues. then restart vs code normally, without the `NODE_TLS_REJECT_UNAUTHORIZED` env variable and settings sync should work :)
> 
> For linux, I would expect that doing something such as
> 
> ```shell
> export NODE_TLS_REJECT_UNAUTHORIZED=0
> code
> ```
> 
> should produce the same results

Thank you! Solved my problem. you are genius
