### ISSUE TITLE
Signing in after offline vscode startup requests new token

### ISSUE THREAD

**Issue by makeway4pK** [microsoft/vscode-pull-request-github#1476]
Issue Type: <b>Bug</b>

1. Disconnect internet.
2. Start vscode into a workspace/project/folder that uses git
3. Github Pull Requests doesn't sign in (expected)
4. Connect to internet, after a while.
5. Github Pull Requests doesn't detect internet connection (expected, but can 
    be a feature request).
6. Click on "Sign in to github.com" in status bar.
7. New browser window opens, asking for a new token (not expected)
    Old token is ignored and this repeats, creating tokens all the time.
Alternatively, if internet is available at the time of vscode's startup, Sign in is successful, no problems there.

Extension version: 0.14.0
VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2197)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (3.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by alexr00** [comment]
I don't see this happening now. Please feel free to ping this issue if it's still occuring!
