### ISSUE TITLE
Remotes UI not clear

### ISSUE THREAD

**Issue by jongio** [microsoft/vscode-pull-request-github#1478]
I want to add a remote using the extension, the UI only has one text box.  What does it expect?  The URL to the remote or the name?  I think it should be two text boxes the name of the remote, i.e. 'upstream' and the remote 'https://github..."

![image](https://user-images.githubusercontent.com/2163001/72918134-fef1bc80-3cf9-11ea-821d-640c29bf3f10.png)

**Comment by RMacfarlane** [comment]
Updated the setting description to note that it should be by name. By default, "origin" and "upstream" should appear in the list which would also hopefully make this clearer

**Comment by jongio** [comment]
Thank you Rachel!
