### ISSUE TITLE
Creating Pull Request from VS Code going on for too long

### ISSUE THREAD

**Issue by devuser300** [microsoft/vscode-pull-request-github#1482]
I am creating a new pull request from VS Code. It is going on for almost an hour. VS Code just shows the status as **Creating Pull Request: Start creating pull request**. No updates other than that.

**Comment by RMacfarlane** [comment]
@devuser300 Can you provide some more information?

- What version of the extension are you using?
- What version of VSCode are you using?
- What is printed in the output console? (`F1` -> `View: Toggle Output` -> Select "GitHub Pull Request" from the dropdown) It looks like this:
![Screen Shot 2020-01-28 at 5 02 38 PM](https://user-images.githubusercontent.com/3672607/73319025-016b7f00-41f0-11ea-807a-101ff3adff39.png)
- What's the value of your `githubPullRequests.remotes` setting?
- What's the result of running `git remote -v` to list your remotes?
