### ISSUE TITLE
Can't create comments from checkout pull request

### ISSUE THREAD

**Issue by Vallek** [microsoft/vscode-pull-request-github#1484]
- Extension version:
- VSCode Version: 1.41.1
- OS: Windows 10

How I can't add comments:
1. Go to PR side panel
2. Click "checkout pull request" from context menu
3. Open local version of file
4. Add comment (plus buttons)
5. Click "Add comment"
6. Get error (see screenshot)
![pr1](https://user-images.githubusercontent.com/22982571/73595370-e9199e00-4528-11ea-9879-e737babe6f22.png)

How I can add comment:
1. Open file from PR side panel.
2. I can add comments, they appear online.

I would prefer first option for less visual culter (red, green no wrap lines and so on).

**Comment by RMacfarlane** [comment]
Thanks for reporting this @Vallek! I'm having trouble reproducing this issue so far, I'll see if I can add some more logging to narrow down the problem. Do you consistently see this problem?

**Comment by Vallek** [comment]
Hi! I don't have a lot of repos to test it, but it never works with two repos I'm working with. I think it used to work some time ago. 
Could it be some settings?

**Comment by alexr00** [comment]
I think this is a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/1339
