### ISSUE TITLE
Refreshing causes comment boxes to be loaded again instead of updating the existing one

### ISSUE THREAD

**Issue by neverendingqs** [microsoft/vscode-pull-request-github#1492]
Issue Type: <b>Bug</b>

* Load a pull request
* Add a comment on the web UI
* Note: comment does not automatically show up in VS Code
* Hit refresh
* Comment box with comment shows up in VS Code
* Hit refresh again
* Another comment box with the same comment shows up underneath the first one

Extension version: 0.14.0
VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

Screenshot: 
![image](https://user-images.githubusercontent.com/8854618/74574176-cd62be80-4f50-11ea-8b95-f7d4c6256fb2.png)

This appears to be a regression of #1077.

**Comment by RMacfarlane** [comment]
Thanks for reporting this!
