### ISSUE TITLE
Issue links should only be created for comments or actual links

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#1493]
It's linkifying a bunch of CSS colors, ctrl+clicking them results in an error:

<img width="506" alt="Screen Shot 2020-02-15 at 4 49 18 AM" src="https://user-images.githubusercontent.com/2193314/74588109-b0f56f00-4fae-11ea-9107-0b29af698df9.png">

Code:

https://github.com/xtermjs/xterm.js/blob/5f0217cdb0baf353b3deedfab25e6e9b49c3d45f/addons/xterm-addon-webgl/src/WebglRenderer.api.ts#L898-L914

Some other problems I'm noticing with the detection:

- It matches on `", "` on some lines
- It should not match when the number starts with `#0`, if using regex maybe do something like `#[1-9][0-9]*`?
- It would be nice if giant numbers could be excluded based on the highest issue/PR number? Not sure if that's possible

**Comment by alexr00** [comment]
Hmm, I don't think we have real API for determining a SymbolKind at a position. @aeschli is that correct?
Checking if a potential link is actually an issue would be quite costly, so that doesn't seem like a good option either.

**Comment by alexr00** [comment]
This should be improved now.
However, there is no good way to determine if a something is a comment, so it's still not great.
