### ISSUE TITLE
Unwanted GitHub issue suggestions in untitled markdown file

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#1494]
This was very unexpected as a user of `"files.defaultLanguage": "markdown"`, I don't think this should happen for untitled files:

<img width="721" alt="Screen Shot 2020-02-18 at 2 13 55 PM" src="https://user-images.githubusercontent.com/2193314/74782784-005ec800-5259-11ea-94b3-83e6391e83a3.png">

**Comment by alexr00** [comment]
This should be fixed now.
