### ISSUE TITLE
Issue suggestions popping up when editor.quickSuggestions is false

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#1495]
I set this which is meant to disable all suggestions unless I explicitly ask for them:

```
  "[markdown]": {
    "editor.quickSuggestions": false
  }
```

Typing "C#" triggers it though:

<img width="391" alt="Screen Shot 2020-02-18 at 2 16 49 PM" src="https://user-images.githubusercontent.com/2193314/74782930-559ad980-5259-11ea-86e8-1089f26532f2.png">

Is this something that VS Code should prevent from happening based on the setting or should this extension respect editor.quickSuggestions?

**Comment by alexr00** [comment]
I think that setting only suppresses suggestions when typing characters that aren't trigger characters. If the suggestion providers uses a trigger character then you'll still see the suggestions. @alexdima can you confirm this?

**Comment by alexdima** [comment]
I don't know. @jrieken will know what the setting does.

@Tyriar your setting is for markdown files, are you typing in a markdown editor?

**Comment by jrieken** [comment]
> ... the suggestion providers uses a trigger character then you'll still see the suggestions.

Correct

* `editor.quickSuggestions` trigger IntelliSense as you type words
* `editor.suggestOnTriggerCharacters` trigger IntelliSense as type trigger characters

**Comment by alexr00** [comment]
Closing as desgined then.

**Comment by Tyriar** [comment]
fwiw this was an untitled file where the default language is markdown. I'll add `editor.suggestOnTriggerCharacters` to `[markdown]`, thanks.
