### ISSUE TITLE
Cannot submit pull request comment

### ISSUE THREAD

**Issue by phuongnd08** [microsoft/vscode-pull-request-github#1498]
- Extension version:
- VSCode Version:
- OS:

Steps to Reproduce:

1. Open a pull request
2. Select a file
3. Comment on a line
4. Expected: See commented posted. Actual:
![image](https://user-images.githubusercontent.com/184037/75000005-be6b9700-548f-11ea-9750-70c88f281a63.png)

**Comment by alexr00** [comment]
I haven't seen this "Validation Failed" message recently. Closing, but please comment and collect logs from the "GitHub Pull Request" output if you see again!
