### ISSUE TITLE
Only 2 suggestions single # 

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#1502]
![image](https://user-images.githubusercontent.com/2193314/75254745-afd5f600-5795-11ea-9f3c-af18da6831e6.png)

In this file but seems to be repo wide https://github.com/Tyriar/xterm.js/blob/master/test/api/MouseTracking.api.ts

Upstream repo is configured as `ups` and I set this:

```
  "githubPullRequests.remotes": [
    "origin",
    "ups"
  ]
```

Version: 1.43.0-insider (user setup)
Commit: 89cafb24e5d75a0c8d561a6cdd95e93b5679e152
Date: 2020-02-25T05:29:49.719Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

Ext: 2020.2.29762

**Comment by alexr00** [comment]
It's because the other issues there don't have a milestone assigned to them. I'll add a setting for including/excluding issues without a milestone.

**Comment by Tyriar** [comment]
I don't understand? Why would a milestone affect the completions?

**Comment by alexr00** [comment]
Projects use milestones to organize issues, so I build the query around milestones. I left out issues without a milestone because we rarely work on issues without a milestone. So I just need to include an option for allowing issues without a milestone.

**Comment by Tyriar** [comment]
@alexr00 key word there is _we_, shouldn't the default work on all issues and allow users to refine that to just the nearest milestone if they want to?

**Comment by alexr00** [comment]
I was worried that fetching all issues without a milestone might end up being a lot of data, but I can include them by default and if people don't like it they can configure.

**Comment by Tyriar** [comment]
@alexr00 can some of that loading be done lazily? If you had the highest issue or PR number you would know all the possibilities, then only going to the server when we need to display it?

**Comment by alexr00** [comment]
@Tyriar It's a trade off. When you type to filter, the issue body text is included in the filtering, which we couldn't do if it is lazily loaded.  I'll add no-milestone issues and we'll see what people think. Most projects are smaller, so it probably won't be an issue.

**Comment by Tyriar** [comment]
@alexr00 ah I see the problem, how many issues do you fetch?

Could you refine the results as you type or are they all needed up front? For example `#` fetches the latest x issues, `#1` fetches issues starting with 1 (1, 10, 11, ..., 100, 101, ...), `#12` fetches issues starting with 12, etc? It would be a shame if it only worked for a selection of issues.

**Comment by alexr00** [comment]
@Tyriar As a user, I don't pay any attention to the issue number so I value having the body as filter text more. I could fetch only the n most recently touched issues with no milestone and include those in the list. 

It is possible to refine the results as you type. I'm new to graphql, so maybe there's a way to do as you suggest with issues beginning with 1 with only one query, but I think it would have to be many queries, which wouldn't be idea for performance either.
