### ISSUE TITLE
Suggestion doesn't appear when triggering intellisense manually

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#1504]
Trigger completion with #:

![image](https://user-images.githubusercontent.com/2193314/75255040-2c68d480-5796-11ea-80d6-ffc8bbe60ca2.png)

Press esc and then ctrl+space:

![image](https://user-images.githubusercontent.com/2193314/75255009-1eb34f00-5796-11ea-8dcc-f77b063fc642.png)

Version: 1.43.0-insider (user setup)
Commit: 89cafb24e5d75a0c8d561a6cdd95e93b5679e152
Date: 2020-02-25T05:29:49.719Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

Ext: 2020.2.29762

**Comment by alexr00** [comment]
This is intentional so that the issues suggestions don't show up everywhere. The suggestions only show if you trigger manually and there is a '#' to the left of the cursor.

Do you find this behavior to aggressive?

**Comment by Tyriar** [comment]
So when I'm after suggestions it could make it difficult to correct it, or to view what that issue was quickly without touching the mouse, since I need to start with # and re-enter it. Wouldn't providing it when `<separator>#<number>` is the proceeding text be more natural?

**Comment by alexr00** [comment]
Yes, that would work too. I'll update the check to include numbers after the #.
