### ISSUE TITLE
Links to comments should preview the comment text, not the original issue text

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#1506]
![image](https://user-images.githubusercontent.com/2193314/75255829-671f3c80-5797-11ea-99c5-5acd01ceca84.png)

Expectation:

![image](https://user-images.githubusercontent.com/2193314/75255891-81f1b100-5797-11ea-9d86-20776a93970b.png)

https://github.com/xtermjs/xterm.js/issues/702#issuecomment-539105873

Version: 1.43.0-insider (user setup)
Commit: 89cafb24e5d75a0c8d561a6cdd95e93b5679e152
Date: 2020-02-25T05:29:49.719Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

Ext: 2020.2.29762

**Comment by alexr00** [comment]
New behavior:
![image](https://user-images.githubusercontent.com/38270282/79963774-1a4f9d80-848a-11ea-91dd-71507a14a706.png)

**Comment by alexr00** [comment]
To verify:
Install the nightly build of this extension
Hover over this in GitHub so you can see what it looks like: https://github.com/xtermjs/xterm.js/issues/702#issuecomment-539105873
Paste `https://github.com/xtermjs/xterm.js/issues/702#issuecomment-539105873` into an editor in vscode
Hover over that link and verify that it looks similar to the same hover on GitHub.
