### ISSUE TITLE
Hover preview whitespace and newlines should be combined into a single new line

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#1508]
![image](https://user-images.githubusercontent.com/2193314/75256380-3d1a4a00-5798-11ea-8f4e-c3a7059cf423.png)

There should be a space before "Related".

github.com:

![image](https://user-images.githubusercontent.com/2193314/75256419-4c00fc80-5798-11ea-903d-5215f6907892.png)

Version: 1.43.0-insider (user setup)
Commit: 89cafb24e5d75a0c8d561a6cdd95e93b5679e152
Date: 2020-02-25T05:29:49.719Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

Ext: 2020.2.29762

**Comment by Tyriar** [comment]
A more extreme case of the problem:

![image](https://user-images.githubusercontent.com/2193314/75257697-2ffe5a80-579a-11ea-80c3-f5c10965c99b.png)

**Comment by alexr00** [comment]
I think the way these hovers look on GitHub is that there are no new lines, but there are spaces. I've fixed the issue by adding in a space where the new line was.
