### ISSUE TITLE
Need to click `Load more` way too often

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-pull-request-github#151]
I find myself clicking `Load more` multiple times in the same session because at some point the whole list gets refreshed and only the first page appears.

**Comment by RMacfarlane** [comment]
We've reduced the number of situations that cause tree refreshes now, it shouldn't happen in the background anymore.

The tree refreshes on:
- Switching branches
- Changing the repo remotes
- Changing the remotes or tree layout settings
