### ISSUE TITLE
Links should follow redirects

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#1510]
This link simply doesn't work because the Googlechrome/puppeteer -> puppeteer/puppeteer redirect isn't followed.

![image](https://user-images.githubusercontent.com/2193314/75257372-b5cdd600-5799-11ea-849f-ca6aa85e4f7f.png)

```
# https://github.com/Googlechrome/puppeteer/issues/290#issuecomment-322921352
```

Version: 1.43.0-insider (user setup)
Commit: 89cafb24e5d75a0c8d561a6cdd95e93b5679e152
Date: 2020-02-25T05:29:49.719Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

Ext: 2020.2.29762

**Comment by alexr00** [comment]
The PR extension isn't providing that link, it's coming from core. I also see it followed correctly when I control click on it.

**Comment by Tyriar** [comment]
@alexr00 by link I meant hover; the hover for the link should follow redirects so there is information available from `puppeteer/puppeteer`.

**Comment by alexr00** [comment]
This seems to work now:

![image](https://github.com/microsoft/vscode-pull-request-github/assets/38270282/c58a180f-c76e-4ffb-b3eb-6c231e932c4d)
