### ISSUE TITLE
Issue link following hover title is redundant

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#1511]
The red link just adds visual noise imo since the link number and link is available with ctrl+clicking the actual link (where the cursor already is initially) or by clicking "Follow link".

![image](https://user-images.githubusercontent.com/2193314/75257519-f2013680-5799-11ea-88fe-e1c7032e30db.png)

Version: 1.43.0-insider (user setup)
Commit: 89cafb24e5d75a0c8d561a6cdd95e93b5679e152
Date: 2020-02-25T05:29:49.719Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

Ext: 2020.2.29762

**Comment by alexr00** [comment]
I'm going to remove the link provider, so this will be the way to go to the issue.

Until there is a different API for providing links in a more performant way, the link provider doesn't work well.
