### ISSUE TITLE
GH links seem to break actual URLs containing hash fragments

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#1512]
![image](https://user-images.githubusercontent.com/2193314/75257907-89668980-579a-11ea-95a2-f098dbe45a4f.png)

Line: https://github.com/xtermjs/xterm.js/blob/ae135ac181b080fce0a13853c19a768c973cc4be/yarn.lock#L40

Another case:

![image](https://user-images.githubusercontent.com/2193314/75258006-ae5afc80-579a-11ea-81e4-bd1032653a90.png)

Version: 1.43.0-insider (user setup)
Commit: 89cafb24e5d75a0c8d561a6cdd95e93b5679e152
Date: 2020-02-25T05:29:49.719Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

Ext: 2020.2.29762

**Comment by alexr00** [comment]
Removed the link provider, since that needed to be done anyway.
