### ISSUE TITLE
Register link provider after you know the maximum issue count

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#1513]
An extension of https://github.com/microsoft/vscode-pull-request-github/issues/1493 and suggestion to fix the linkifying CSS problems; Could you check the max issue count before registering a link provider and make sure at the very least that the number of digits does not exceed that? This would solve matching CSS numbers for the vast majority of repos (VS Code is only just now almost at 100000).

![image](https://user-images.githubusercontent.com/2193314/75258442-4d7ff400-579b-11ea-8e11-17facfe733c8.png)

Version: 1.43.0-insider (user setup)
Commit: 89cafb24e5d75a0c8d561a6cdd95e93b5679e152
Date: 2020-02-25T05:29:49.719Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

Ext: 2020.2.29762

**Comment by alexr00** [comment]
I removed the link provider, so this shouldn't be a problem anymore.
