### ISSUE TITLE
Ensure links are not provided when numbers are followed by alpha-numeric characters

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#1514]
In order to avoid matching on general hex values, could we make sure [a-zA-Z] does not follow the regex? This should not get matched:

![image](https://user-images.githubusercontent.com/2193314/75258714-c2ebc480-579b-11ea-8412-6a526d6beba0.png)

It might even be better to have a whitelist of allows characters afterwards if this works, for example whitespace, colon, semi-colon, comma, etc.

Version: 1.43.0-insider (user setup)
Commit: 89cafb24e5d75a0c8d561a6cdd95e93b5679e152
Date: 2020-02-25T05:29:49.719Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

Ext: 2020.2.29762

**Comment by alexr00** [comment]
Link provider has been removed. If we decide to add it back, I will definitely make this change.
