### ISSUE TITLE
Hovers can conflict with color picker

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#1515]
Not sure what the answer is here but it's a bit wonky when the color picker shows up for the text at the link. The follow link tooltip does not show up and holding ctrl+hover will flash the link on and off.

![image](https://user-images.githubusercontent.com/2193314/75259148-6b018d80-579c-11ea-8a7e-ae8620941b0c.png)

Version: 1.43.0-insider (user setup)
Commit: 89cafb24e5d75a0c8d561a6cdd95e93b5679e152
Date: 2020-02-25T05:29:49.719Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

Ext: 2020.2.29762

**Comment by Tyriar** [comment]
In settings:

![image](https://user-images.githubusercontent.com/2193314/75259552-0e52a280-579d-11ea-84c1-9336700911d0.png)

**Comment by alexr00** [comment]
Funny, the hover I see becomes scrollable. I'll fix the hover provider to not allow alpha numeric characters after it as you suggested in another issue.
