### ISSUE TITLE
Handle colon following create issue triggers

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#1516]
I think this format is pretty common:

![image](https://user-images.githubusercontent.com/2193314/75264311-195d0100-57a4-11ea-94c8-e445a2f7b9d6.png)

Version: 1.43.0-insider (user setup)
Commit: 89cafb24e5d75a0c8d561a6cdd95e93b5679e152
Date: 2020-02-25T05:29:49.719Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

Ext: 2020.2.29762

**Comment by connor4312** [comment]
Ran into this as well. Maybe it should match whitespace + todo + `.*`. I usually format my todos like `// todo(connor4312): something` so people know who to call if the blame gets obfuscated.

**Comment by egamma** [comment]
@connor4312 suggest that you also consider using `todo@connor4312`. It is one character less and the PR extension also offers completions when entering `@`.

**Comment by alexr00** [comment]
It now does the insert in the first whitespace after the "todo" (or whatever your "todo" is). It does the same for the suggested issue title too.
