### ISSUE TITLE
Issue are disabled for this repo

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#1517]
Trying to create an issue for this line https://github.com/Tyriar/xterm.js/blob/ae135ac181b080fce0a13853c19a768c973cc4be/addons/xterm-addon-webgl/src/renderLayer/CursorRenderLayer.ts#L137

![image](https://user-images.githubusercontent.com/2193314/75264649-938d8580-57a4-11ea-82da-5c125f0e5708.png)

Likely related to my `ups` setup

Version: 1.43.0-insider (user setup)
Commit: 89cafb24e5d75a0c8d561a6cdd95e93b5679e152
Date: 2020-02-25T05:29:49.719Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

Ext: 2020.2.29762

**Comment by Tyriar** [comment]
Still fails when I add an `upstream` remote:

```
$ git remote -v
...
ups     https://github.com/xtermjs/xterm.js (fetch)
ups     https://github.com/xtermjs/xterm.js (push)
upstream        https://github.com/xtermjs/xterm.js (fetch)
upstream        https://github.com/xtermjs/xterm.js (push)
```

**Comment by alexr00** [comment]
Looks like there does need to be a setting for the default remote for issues. Otherwise, there is no way to know which remote you actually want to use for issues.

**Comment by Tyriar** [comment]
@alexr00 that setting already exists: githubPullRequests.remotes, you should use whatever logic the PR part uses to get the main upstream.

**Comment by alexr00** [comment]
But if you have several remotes listed there then I still don't know where to create the issue.

**Comment by Tyriar** [comment]
@RMacfarlane does the PR part do something clever happen here or does it just pull all PRs from all remotes?

**Comment by RMacfarlane** [comment]
When listing PRs, it pulls PRs from all remotes, with some paging logic.

For creating PRs, we also have the issue of deciding which remote to use. We try to identify which one is the upstream, and show a quickpick to the user:
https://github.com/microsoft/vscode-pull-request-github/blob/773112bcc871ca16ae4922f2b7e7175deaa2e011/src/view/reviewManager.ts#L713-L717

Maybe it would be good enough to change the create issue command to use the result of `getPullRequestDefaults()`, our best effort at finding the upstream.

**Comment by alexr00** [comment]
Thanks @RMacfarlane !
@Tyriar I made the change that Rachel suggested, and I tested that it does find the correct upstream in your case. Let me know if it works for you after the next nightly build!
