### ISSUE TITLE
Issue links show loading state in editor until focus is restored

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-pull-request-github#1518]
1. Have your browser in another monitor
2. Click on an issue link in VS Code
3. The issue opens on the other monitor, but the loading state atop the editor sticks around until you focus back on the VS Code window

**Comment by alexr00** [comment]
I've removed links since they were not performant. But what platform were you seeing this with, and does it occur with non-issue links?

**Comment by connor4312** [comment]
I actually don't see this on OSX or my windows VM at work. I'll try to reproduce it again when I get home tonight and see if I can figure out what the difference is.

**Comment by connor4312** [comment]
Can't repro any more
