### ISSUE TITLE
Create issue from selection doesn't include selected code

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-pull-request-github#1519]
I made [this selection](https://memes.peet.io/img/20-02-18aad58e-b11d-4a59-a3c1-588e7931885a.png) in a repo and ran the command "create issue from selection". I expected the selected code to be embedded in the created issue https://github.com/connor4312/mopidy-azure/issues/2, but it wasn't.

**Comment by alexr00** [comment]
Your expectation was correct, this is a bug.

**Comment by alexr00** [comment]
Do you have anything atypical about your git remote? I tried the same thing and it worked (https://github.com/connor4312/mopidy-azure/issues/6 sorry for polluting your repos issues!). 
Can you also try the Open Permalink in GitHub command?

**Comment by connor4312** [comment]
I think this may be the same as https://github.com/microsoft/vscode-pull-request-github/issues/1520 -- I didn't originally have the branch tracked (I have gp and gl locally aliased to `git push origin $(git_current_branch)` and `git pull origin $(git_current_branch)`)

**Comment by alexr00** [comment]
That would do it. I'll call this a dupe of #1520 then, since there needs to better handling of remotes in general.
