### ISSUE TITLE
Code permalink fails if there's no remote tracked branch

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-pull-request-github#1520]
When I tried creating a permalink for some code, I got the rather cryptic message:

![](https://memes.peet.io/img/20-02-2c9a9631-ec37-41e6-ae35-0e6ab20cb331.png)

I figured out it's because my local branch wasn't tracking against the remote. It would be useful to show that, or open the permalink anyway if we see there's a remote branch that matches the local branch name.

**Comment by alexr00** [comment]
I updated the message to "'Unable to create a GitHub permalink for the selection. Check that your local branch is tracking a remote branch."
