### ISSUE TITLE
Only suggest issues if already in a comment?

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-pull-request-github#1521]
Python uses `#` as its comment delimiter, which triggers issue suggestions every time I start writing a comment. Is there a way to only offer the completion if the `#` is in the body of a comment?

![image](https://user-images.githubusercontent.com/2230985/75286463-6f926a00-57cd-11ea-9a1e-1a2c96654f6b.png)

**Comment by alexr00** [comment]
I wish I could do this, but the VS Code API doesn't have anything to support this. I've opened https://github.com/microsoft/vscode/issues/91555 to track this API request.

**Comment by mattstrayer** [comment]
Also keep running into this for comments in python and bash. 

@alexr00 Would it be sensible to offer a setting for the user to set a prefix character(s) for activating the auto-complete? Maybe adding a `!` prefix --> `!#`, `!@` ?

**Comment by alexr00** [comment]
This has since been completed.
