### ISSUE TITLE
Issues without a milestone don't appear in suggestions

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-pull-request-github#1522]
We can `ignoreMilestones`, but it seems like issues without a milestone are never shown in completion. Many smaller projects or maintenance-mode projects without planned releases don't use milestones.  Maybe we should show them and have some magic `<None>` option in ignoreMilestones to refer to them.

**Comment by alexr00** [comment]
Yes, will add. Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/1502
