### ISSUE TITLE
A way to reference closed issues or issues not assigned to the user

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-pull-request-github#1523]
For most of my personal projects, the workflow I follow is merging several PRs/issues and then listing them in the changelog in a followup commit, e.g. https://github.com/connor4312/cockatiel/commit/7b7c100e950e320d85ce285afdb2a562949bce8f. However, I won't be able complete them, since they're closed (and if I have other contributors who have issues assigned to them that I'm mentioning in the changelog, I can't complete those either). Maybe a command for "Insert Issue Reference" with the capability to search through all issues would be useful, or an option to change how filtering works in completions by default.

Edit: also, a similar thing for users in the same scenario would be nice, if Github exposes an API for that 🙂

**Comment by alexr00** [comment]
For the issues, we can definitely do this. What would be more useful for you: some setting that changes the the suggestion list to include closed issues, or the suggestion list switching to show only closed issues when you type "closed" after triggering the suggest? Or, as you suggest a command.

Users are harder. Currently, the user list comes from the repository. Where do the users you want to show come from?

**Comment by connor4312** [comment]
> or the suggestion list switching to show only closed issues when you type "closed" after triggering the suggest

I think this would be a good approach :)

> Users are harder. Currently, the user list comes from the repository. Where do the users you want to show come from?

Maybe the union of collaborators + [contributors](https://developer.github.com/v3/repos/#list-contributors)?

**Comment by IllusionMH** [comment]
Most broad option might be `mentionableUsers` in https://developer.github.com/v4/object/repository/

But not sure if it is frequent practice to mention issue authors, commenters, reviews in code.

**Comment by alexr00** [comment]
FYI, you can now customize the query that is used in the issues view and the issues suggestions. Check out the `githubIssues.customQuery` setting.

**Comment by alexr00** [comment]
Closing since customizing the query will solve this.
