### ISSUE TITLE
PR clogs up extension host for files with super long lines

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-pull-request-github#1526]
It seems that the todo code action provider cannot handle long lines. See [attached profile](https://github.com/microsoft/vscode-pull-request-github/files/4253229/GitHub.vscode-pull-request-github-insiders-unresponsive.cpuprofile.txt).

My use case: When generating updates for the GDPR registry I generate large single line `json` files. I can provide such a file. When I open one of those with the GHPR extension enabled the extension becomes unresponsive. In a remote setup, this causes the window to becomes unusable as the window goes through disconnect/reconnect cycles.

As we do for tokenization, it seems to make sense to skip lines that are too long.

**Comment by alexr00** [comment]
Limited lines to 150 characters.
