### ISSUE TITLE
Garbled rendering of issue content

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode-pull-request-github#1527]
Testing https://github.com/microsoft/vscode-internalbacklog/issues/947

* open `build/lib/standalone.ts` in vscode
* hover around line 295 on the link `https://github.com/Microsoft/monaco-editor/issues/148`

| ORIGINAL | VS CODE HOVER |
|---|---|
| ![image](https://user-images.githubusercontent.com/5047891/75323833-f569f000-5875-11ea-89dd-3e7a8f69a89b.png) | ![image](https://user-images.githubusercontent.com/5047891/75323861-0581cf80-5876-11ea-9099-504172e05f78.png) |

Problems:
* Notice how there is a general lack of line breaks.
* Notice how "find widget" is rendered as "fin#8229get" which is very weird

**Comment by alexr00** [comment]
Just putting a link to that same issue here so I can see GitHub's hover
https://github.com/Microsoft/monaco-editor/issues/148

**Comment by alexr00** [comment]
Caused by bad counting when finding links in the issue body. Between that fix and the fix for adding spaces for new lines it now shows this:
![image](https://user-images.githubusercontent.com/38270282/75332379-91025d00-5884-11ea-80d4-563c67f8583b.png)
