### ISSUE TITLE
User card hover should render the profile image larger

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode-pull-request-github#1528]
Testing https://github.com/microsoft/vscode-internalbacklog/issues/947

On GitHub, the user card preview renders the user avatar a lot larger than the VS Code hover does:

| GitHub | VS Code Hover |
|---|---|
| ![image](https://user-images.githubusercontent.com/5047891/75326894-be96d880-587b-11ea-9dc8-9e1a48a497e6.png) | ![image](https://user-images.githubusercontent.com/5047891/75326920-cbb3c780-587b-11ea-914a-1342e53fd8c7.png) |

**Comment by alexr00** [comment]
I can't align the text with the top of the image, but this still looks better
![image](https://user-images.githubusercontent.com/38270282/75780517-cc58cc00-5d5b-11ea-98fb-25bbd5ab6135.png)
