### ISSUE TITLE
Render user profile pictures as suggestion icons

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode-pull-request-github#1529]
Testing https://github.com/microsoft/vscode-internalbacklog/issues/947

IMHO it would be better if the user profile picture would be rendered as the suggestion icon instead of the current icon:

![image](https://user-images.githubusercontent.com/5047891/75327133-26e5ba00-587c-11ea-9459-8174ea8a8b78.png)

**Comment by alexr00** [comment]
https://github.com/microsoft/vscode/issues/91541, which could enable this.

**Comment by alexr00** [comment]
The API that was added still doesn't support using profile pictures. Closing as upstream.
