### ISSUE TITLE
A comment added on the right side of a diff editor may move to the left side on reload

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode-pull-request-github#153]
1. Open a file change from the PR tree
2. Add a new comment on the right hand side of the diff editor, on a line that isn't within an addition
3. Close and reopen the file change. Comment now appears on the base file on the left

Since the comment isn't on an addition, showing it on the base file is the correct thing to do. However, it's confusing to have it move - I thought a comment had been lost for a second because it wasn't where I had added it.
![comment_move](https://user-images.githubusercontent.com/3672607/43926815-43d9b81e-9be0-11e8-8251-3bebb15449fd.gif)

On GitHub, trying to add such a comment, the comment widget pops up on the left even though the click was on the right:
![lhs_comment](https://user-images.githubusercontent.com/3672607/43926244-8852d5e0-9bde-11e8-8705-5781304a3b41.gif)

**Comment by rebornix** [comment]
We need some specific *github review* logic to adjust the commenting range for the modified editor.
