### ISSUE TITLE
Render labels and open / close state in the issue hover

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode-pull-request-github#1530]
Testing https://github.com/microsoft/vscode-internalbacklog/issues/947

Labels are very useful for me to quickly figure out what an issue is about. I would find it helpful if the labels would be rendered in the issue hover.

For example, `https://github.com/Microsoft/vscode/issues/34162`:

![image](https://user-images.githubusercontent.com/5047891/75327444-b1c6b480-587c-11ea-88ff-9741896f0a60.png)

I find it difficult to tell if this issue is open or closed and if it is a bug or a feature request. Compare to the GH rendering, where a large emphasis is placed on open/closed state:

![image](https://user-images.githubusercontent.com/5047891/75327530-d753be00-587c-11ea-80d6-ff65e8c01fc3.png)

**Comment by alexr00** [comment]
@alexdima I had labels shown after the issue body, but removed it because folks thought they weren't useful without the colors. Would you still find labels useful if they were missing the colors?

**Comment by alexdima** [comment]
I would personally like to see labels.

I am not sure how the rendering was before, do you have a screenshot?

**Comment by alexr00** [comment]
I don't have a screen shot, but the hover is limited to markdown, so I showed them below the issue body in italics.

**Comment by alexr00** [comment]
For open/close state, we use the same icon that GitHub uses, albeit without the color:
![image](https://user-images.githubusercontent.com/38270282/75692487-f059d600-5ca5-11ea-8d83-f411d1f48f60.png)
vs
![image](https://user-images.githubusercontent.com/38270282/75692581-11222b80-5ca6-11ea-9ca7-1e0049c8a85b.png)

**Comment by alexr00** [comment]
And, here is how I had labels before:
![image](https://user-images.githubusercontent.com/38270282/75693756-b984bf80-5ca7-11ea-8fd1-158a9445c3b7.png)

I will re-add them and you can see what you think.

**Comment by alexdima** [comment]
Thank you for the screenshot. I see that it is almost impossible to get a good looking rendering using the current limited Markdown... We should also ask @jrieken for ideas... Maybe we can allow some subset of HTML ... ?
