### ISSUE TITLE
EH is unresponsive

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-pull-request-github#1537]
![image](https://user-images.githubusercontent.com/323878/75835124-de923480-5d72-11ea-932b-68f3eaabe7b7.png)

Seems to be spending a lot of time in `issueMarkdown`, I am only seeing this in the vscode repo. If I reload the window it works for awhile.

[GitHub.vscode-pull-request-github-insiders-unresponsive.cpuprofile.txt](https://github.com/microsoft/vscode-pull-request-github/files/4284530/GitHub.vscode-pull-request-github-insiders-unresponsive.cpuprofile.txt)

**Comment by roblourens** [comment]
I think this happens every time I start typing an issue number in the scm input

**Comment by alexr00** [comment]
`issueMarkdown` has gotten more expensive since I added link detection within the issue body text. This needs to move to resolveCompletionItem.
