### ISSUE TITLE
Unable to install latest nightly build

### ISSUE THREAD

**Issue by neverendingqs** [microsoft/vscode-pull-request-github#1539]
Issue Type: <b>Bug</b>

[GitHub Pull Request Nightly Build](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github-insiders) shows that the latest version is `2020.3.6730` as expected. The [nightly build pipeline](https://rebornix.visualstudio.com/Pull%20Request/_build/results?buildId=1043&view=logs&j=3bd52376-4866-57aa-dfdb-d04952b84d8d&t=14bd693e-34d1-5172-806f-7299de473e6e) also suggests that is the expected latest version.

However, VS Code is showing the nightly build is at version `2020.2.8161` when installed. Is there an issue with the Nightly build, or am I missing something with how the nightly build works?

![image](https://user-images.githubusercontent.com/8854618/76017384-7f582f80-5eec-11ea-8d7e-c1cdb54526a2.png)

Extension version: N/A (mainline version is `0.14.0`)
VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18362

**Comment by RMacfarlane** [comment]
@neverendingqs It looks like this dropdown filters to versions that are compatible with your version of VSCode. We bumped the required version of VSCode to 1.43 at that time, the insiders version: https://code.visualstudio.com/insiders/

So you should be able to get the latest if you download Insiders - you can run VSCode Stable and Insiders side by side.

**Comment by neverendingqs** [comment]
That was it - thanks!
