### ISSUE TITLE
Add support for "Hide Whitespace Changs".

### ISSUE THREAD

**Issue by Abhinickz** [microsoft/vscode-pull-request-github#1543]
* Add support for "Hide Whitespace Changs".

**Comment by alexr00** [comment]
VS Code has built in support for leading/trailing whitespace hiding already:

![image](https://user-images.githubusercontent.com/38270282/142397439-02f97860-efee-4979-97b9-4a4ba3d8f581.png)

**Comment by mghesh-yseop** [comment]
There might be a bug, or an unknown good reason, but this option does not appear for me in some files.
In my test case, I have a `.java` and `.adoc` file that do not have the button, but a `.sh` and `pom.xml` do have it.
In all cases, the button value is respected in all diff.
