### ISSUE TITLE
Contribute a GH repository picker to the Git: Clone command 

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#1547]

**Comment by eamodio** [comment]
If this helps, I've implemented this in RemoteHub here:

https://github.com/eamodio/vscode-remotehub/blob/bc2a8371d3480802ec000c880e94a19ea5cfa0ee/src/commands.ts#L51-L62

**Comment by alexr00** [comment]
Thanks for the pointer, I'll check it out!

**Comment by joaomoreno** [comment]
@alexr00 @RMacfarlane I'm having a very hard time to figure out where to properly plug this in.

I've already updated the Git extension API definition which provides the [`registerRemoteSourceProvider`](https://github.com/microsoft/vscode-pull-request-github/commit/a084de90bd11b1841af2087973b60384229cb023#diff-807d5af6d15181ce7e48f5cff15976a6R216) API. This API call isn't scoped to any repository... which goes against a lot of the functionality I've seen here related to PRs and Issues, in which a repository is always in scope. So, is there an authenticated utility where I can implement the `getRepositories` call using octokit?
