### ISSUE TITLE
Use extension on windows with WSL

### ISSUE THREAD

**Issue by CombeeMike** [microsoft/vscode-pull-request-github#1561]
I just installed this extension. Connecting to GitHub worked just fine but on PR checkout, i got the error message `Failed to execute git. Please check git output for more details`.

The git output shows the following:

```
// ...

> git pull --tags
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
> git fetch origin branch/name --depth=1
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

// ...
```

I guess that's due to the fact that I'm on Win 10 and have not set up the SSH agent etc. in the Git Bash since I usually perform all Git operations which need authentication from within my WSL Ubuntu Terminal which has the SSH agent running etc.

1) Is my assumption above correct?
2) Is there any way to work around this issue without having to set up the SSH agent in my Git Bash?

I really enjoy my current setup with the WSL and don't want to have to setup & maintain 2 systems (WSL & Git Bash) just to make this extension work...

**Comment by CombeeMike** [comment]
FYI: Checkout seems to be working if I manually switch to the PR branch & perform a `git pull` inside the WSL before clicking on the "checkout" button in the extension...

**Comment by alexr00** [comment]
@CombeeMike I'm closing this as a lot has changed since you filed the issue, but please comment if this is still not working for you!
