### ISSUE TITLE
Merge Conflict During Pull Request

### ISSUE THREAD

**Issue by RobelCSUN** [microsoft/vscode-pull-request-github#1562]
When making a pull request and there is a merge conflict that can not be resolved automatically, **vscode-pull-request-github** does not allow you to fix the merging conflict within the plugin itself. Currently, we have to go to the GitHub website to resolve the merging conflict occurred during pull request. It would  be nice if vscode-pull-request-github has this functionality.

**Comment by slwhitman** [comment]
This is really painful to have to step out of band to use GitHub to resolve conflicts. Any hope to allow users to do this in VSCode Conflict Editor?

**Comment by conradwt** [comment]
Are there any updates to this issue because this appears to be a regression for a feature that once worked?
