### ISSUE TITLE
Unnecessary explorer bar scrolling when selecting a file

### ISSUE THREAD

**Issue by heaths** [microsoft/vscode-pull-request-github#1572]
When selecting a file in the explorer view, the view is scrolled to make the selected file the vertically centered selected file. This is not only annoying and a distraction when reviewing PRs, but unnecessary and inconsistent with the rest of VSCode. Selecting a file in the file explorer view doesn't do this. If I want the region to scroll, I would like to do so myself. This also helps me keep track of which files I have reviewed if I bounce around a bit to checkout associated source file changes. When you scroll for me, it is easier to lose my place.

- Extension version: 0.14.0
- VSCode Version: 1.43.0 (user setup)
- OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Open a PR with a lot of files.
2. Select a file near the top or bottom.
3. Notice how the file is not at the vertical center (region was scrolled).

**Comment by alexr00** [comment]
This is a VS Code setting. I think you want `"explorer.autoReveal": "focusNoScroll"`
