### ISSUE TITLE
Indefinite load and an error

### ISSUE THREAD

**Issue by mhmmd-ysf** [microsoft/vscode-pull-request-github#1574]
It shows error message after i close a PR
**Error running command pr.pick: Cannot read property 'number' of undefined. This is likely caused by the extension that contributes pr.pick.**

- Extension version: 0.15.0
- VSCode Version: 1.43
- OS: Mac

Steps to Reproduce:

1. Close a Pull Request
2. The infinite loading begin
3. Plus an error message

**Comment by RMacfarlane** [comment]
Closing as I'm not able to repro this in the latest version of the extension and believe this has been fixed.
