### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by trepichio** [microsoft/vscode-pull-request-github#1575]
- Issue Type: `Bug`
- Extension Name: `vscode-pull-request-github`
- Extension Version: `0.15.0`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.43.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 407,
		"activateCallTime": 5,
		"activateResolvedTime": 72,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "GitHub.vscode-pull-request-github",
				"_lower": "github.vscode-pull-request-github"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": [
		{
			"name": "HttpError",
			"message": "request to https://api.github.com/ failed, reason: read ECONNRESET"
		}
	]
}
```

**Comment by RMacfarlane** [comment]
I haven't been able to reproduce this issue, please let me know if you continue to see this
