### ISSUE TITLE
Unable to connect to github enterprise which is only available via http

### ISSUE THREAD

**Issue by mchugh19** [microsoft/vscode-pull-request-github#1576]
Issue Type: <b>Bug</b>

Our github enterprise server is not available via https, only http. When first connecting, I am redirected properly to the github enterprise server to authenticate. Afterwards, vscode gets a URL like: vscode-insiders://github.vscode-pull-request-github/did-authenticate?code=...
Which simply creates a notification popup
> Error signing in to github...
Sign in failed: Received bad state

I've also submitted a created token through the vscode prompt rather than following the vscode:// link, but with similar results.

Extension version: 0.15.0
VS Code version: Code - Insiders 1.44.0-insider (798481c7978af034b054e14ace4e471e7a83f665, 2020-03-16T07:59:35.730Z)
OS version: Windows_NT x64 10.0.16299
Remote OS version: Linux x64 3.10.0-693.5.2.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz (2 x 2400)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|12.00GB (1.67GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|

|Item|Value|
|---|---|
|Remote|SSH: IP|
|OS|Linux x64 3.10.0-693.5.2.el7.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz (2 x 2399)|
|Memory (System)|7.64GB (3.99GB free)|
|VM|100%|
</details>

**Comment by usaroch** [comment]
I have the Same Issue.

VS COde Version: 1.43.0
Chrome Version: 80.0.3987.132 
Mac OS - Catalina: 10.15.3

**Comment by aermin** [comment]
I have the Same Issue, too.

Version: 1.44.2
Date: 2020-04-16T17:07:18.473Z (4 wks ago)
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

**Comment by RMacfarlane** [comment]
We have discontinued support for GitHub Enterprise. https://github.com/microsoft/vscode-pull-request-github/wiki#2-is-github-enterprise-supported
