### ISSUE TITLE
@user hovers are too wide

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-pull-request-github#1578]
pls see the screenshot below

![image](https://user-images.githubusercontent.com/172399/76832622-f6b18b80-6829-11ea-96a7-37100c9fdf97.png)

**Comment by alexr00** [comment]
There is currently no API to support setting a width for a hover, but https://github.com/microsoft/vscode/issues/56525 and https://github.com/microsoft/vscode/issues/14165 are a bit similar.

Opened https://github.com/microsoft/vscode/issues/92833 to specifically request API.
