### ISSUE TITLE
Using high cpu in provideHover

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-pull-request-github#1579]
[GitHub.vscode-pull-request-github-insiders-unresponsive.cpuprofile.txt](https://github.com/microsoft/vscode-pull-request-github/files/4351725/GitHub.vscode-pull-request-github-insiders-unresponsive.cpuprofile.txt)

![image](https://user-images.githubusercontent.com/323878/77014053-a5d78b00-692e-11ea-9ac5-33119b93ccd6.png)

Just noticed this. I don't have repro steps, sorry

**Comment by alexr00** [comment]
Tried to repro, but no luck. My guess is that this is caused one of our regular expressions used in `getWordRangeAtPosition`, but I haven't seen it happen.
