### ISSUE TITLE
Authentication flow issue

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode-pull-request-github#158]
Issue Type: <b>Bug</b>

1. installed new insiders and extension
2. Open "GitHub Pull Requests" and expanded "All"
3. ->Dialog popped up to sign into GitHub
4. enter user id and password
5. press "Sign in"
6. -> Notification in VS Code pops up telling me I need to sign in
7. walk through the sign-in flow

I'm confused about 3. Shouldn't it be 6 that happens after 2.

Extension version: 0.0.9
VS Code version: Code - Insiders 1.27.0-insider (e3e972589db57a16da6426828706ced9c2d52848, 2018-08-09T23:55:15.226Z)
OS version: Windows_NT ia32 10.0.17134

**Comment by shana** [comment]
> 3->Dialog popped up to sign into GitHub

What did the dialog look like? It might have been the Git Credential Manager being triggered for some reason. That will log you in to GitHub, but won't provide enough scopes to be able to use the PR feature. 
Not sure why it would be triggered, though... is there a log of git commands where we can see what the extension is running? If it performed a `git fetch`, that might trigger the GCM for the git credentials.

**Comment by shana** [comment]
This is fixed in https://github.com/Microsoft/vscode-pull-request-github/commit/90d078a1aa16abd32fdba36e0ec7792cdd9ddf27
