### ISSUE TITLE
Add alt command for "start working on issue" that always prompts for branch

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#1582]
Suggested by @eamodio

**Comment by connor4312** [comment]
@alexr00 can you provide instructions to verify this?

**Comment by alexr00** [comment]
Install the nightly build of the PR extension.
Open a repo where you have issues assigned to you.
Enable the issues view with `	"githubIssues.show": true`.
Open the issues view in the GitHub viewlet.
Alt+right click on on of the issues and start working on an issue. 
Verify that in the context menu there is an option to start working on an issue with a branch prompt.
Verify that if you use that option you get prompted to enter a branch name.

**Comment by misolori** [comment]
Verified

![image](https://user-images.githubusercontent.com/35271042/78272181-0be11800-74c2-11ea-907f-f0a182679925.png)

![image](https://user-images.githubusercontent.com/35271042/78272184-0d124500-74c2-11ea-8666-e9d67838157f.png)

However, when I go back to the issue and hit "Stop working on issue" any subsequent alt-clicks don't show that option:

![image](https://user-images.githubusercontent.com/35271042/78272355-434fc480-74c2-11ea-8a2d-77ada8cee0a5.png)

Suggestion: update the label to indicate that there is already a local branch like "Continue working on issue". Also, the text "Start Working with Branch Prompt" feels a bit robot-ish. Maybe "Start Working and Create Branch..." to indicate that the user needs to add an input.

**Comment by alexr00** [comment]
Thanks for verifying! I've opened a new issue with that feedback so I can polish it in April.
