### ISSUE TITLE
Show All PR's for All Repos?

### ISSUE THREAD

**Issue by Jonnokc** [microsoft/vscode-pull-request-github#1583]
I traditionally work out of workspaces that contain multiple repositories. As it stands, it appears I have to navigate between each repository individually from within source control.

Is there a way to just all all the PR's for every repo within my active workspace?

[This comment](https://github.com/microsoft/vscode-pull-request-github/issues/493#issuecomment-429975824) appears to possibly reference what I am referring too with multi select.

**Comment by eisenhowerj** [comment]
I'd like "Show PRs for All Repos for which I have the ability to review" whether I have a repo loaded into my workspace or not.

**Comment by MarttiR** [comment]
**This is a must-have feature:** it would greatly streamline working in a multi-repository environment. Without it, one needs to click back and forth between Explorer and GitHub panels, and wait for the PR lists to load every time.

**Comment by RMacfarlane** [comment]
Support for this has been added in version 0.20.0 of the extension, the pull request tree should now show all repos in the workspace at the top level
