### ISSUE TITLE
Focus on Pull Requests View doesn't work when Show In SCM is enabled

### ISSUE THREAD

**Issue by erihanse** [microsoft/vscode-pull-request-github#1586]
Issue Type: <b>Bug</b>

Stepts to reproduce:
1. Enable option "Github Pull Requests: Show In SCM"
2. Issue command "GitHub Pull Requests: Focus on GitHub Pull Requests View"

Expected: 
Pull Requests View is opened

Actual:
Focus is on folder explorer

Extension version: 0.15.0
VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:52:11.516Z)
OS version: Linux x64 4.15.0-91-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 3854)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|31.11GB (2.15GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by RMacfarlane** [comment]
Closing this since the "Show In SCM" setting has now been deprecated - you can instead drag the view there with the current version of VSCode.
