### ISSUE TITLE
Issues: Custom query not scoped to current repository

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-pull-request-github#1587]
I've added a custom query to the Issues View
```
		{
			"label": "Recent Issues",
			"query": "is:issue is:open "
		}
```
I would have expected that the query is scoped to the current repository. However, the result of the query is not scoped to the current repository but it appears to be all repositories:

![image](https://user-images.githubusercontent.com/172399/77630803-f14ff180-6f4b-11ea-8b48-e0539ea5ca60.png)

I can scope the query to a particular repo using the `repo:` attribute, but then I cannot write a query for 'the recent issues in this repository'.

**Comment by alexr00** [comment]
I should add new variables for current repo to solve this.

**Comment by alexr00** [comment]
To verify:
Modify a query in `githubIssues.queries` and use the `$(owner)` and `$(repository)` variables. Verify that they do what you expect!
