### ISSUE TITLE
Add setting to allow turning off github user completion

### ISSUE THREAD

**Issue by ClemensA4t1qbit** [microsoft/vscode-pull-request-github#1589]
When coding in Python, I want the typing of `@` to trigger autocompletion for potential decorators, not have it populated with a number of github names. As such, it would be great if this autocompletion feature of this extension could be turned off in a setting.

**Comment by egamma** [comment]
We should offer a similar setting as for `#` that can be defined per language.

@ClemensA4t1qbit there is a user setting `editor.suggest.showUsers` that you can use to turn this off.

**Comment by ClemensA4t1qbit** [comment]
> We should offer a similar setting as for `#` that can be defined per language and also use some more heuristics when to not show the user completions.
> 
> @ClemensA4t1qbit there is a user setting `editor.suggest.showUsers` that you can use to turn this off.

I tried adding that to `settings.json` but it has no effect. It also doesn't show up as one of the autocomplete options. I am on the latest version of VSCode on MacOS.

**Comment by RMacfarlane** [comment]
@ClemensA4t1qbit This setting is currently only available in the insiders version of VSCode: https://code.visualstudio.com/insiders

**Comment by 333fred** [comment]
Any idea when this will make it to the stable version? This bites me daily, sometimes hourly.

**Comment by alexr00** [comment]
It's already in stable version 1.44 :)

**Comment by Gama11** [comment]
That setting seems to do nothing for me in 1.44 with GitHub Pull Requests 0.15.0. Disabling the extension does the trick though...

What does this feature even have to do with pull requests?

**Comment by 333fred** [comment]
> That setting seems to do nothing for me in 1.44 with GitHub Pull Requests 0.15.0. Disabling the extension does the trick though...

Same.

**Comment by ecraig12345** [comment]
When will this be released? I'm disabling the extension until then because this behavior is too obnoxious...

**Comment by connor4312** [comment]
@ecraig12345 you can use the nightly version of the extension, `github.vscode-pull-request-github-insiders`, or wait until stable is bumped next week 🙂
