### ISSUE TITLE
Issue hovers: hard to distinguish between closes and open issues

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-pull-request-github#1591]
Issue Type: <b>Bug</b>

The only difference right now is the icons. Those, however, are visually very close and depending on which theme you use hard to distinguish.

Extension version: 2020.3.35461
VS Code version: Code - Insiders 1.44.0-insider (13b38d2a494612ace32c4fb878824d6329d4c51e, 2020-03-30T07:30:34.234Z)
OS version: Darwin x64 18.7.0
Remote OS version: Linux x64 5.0.0-1022-azure
Remote OS version: Linux x64 5.0.0-1022-azure

**Comment by alexr00** [comment]
Let's make the icons different colors as they are on GitHub.
