### ISSUE TITLE
Support editing 'Working Issue Branch' setting in the Settings editor

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-pull-request-github#1599]
I would have expected that I can edit the working issue branch in the Settings editor:

![image](https://user-images.githubusercontent.com/172399/78217409-5364a580-74bc-11ea-8c71-1f6e29403c9f.png)

**Comment by alexr00** [comment]
It can actually be a boolean too, which is why you can't edit it here.
I'll break it into two settings.

**Comment by alexr00** [comment]
![image](https://user-images.githubusercontent.com/38270282/78348745-d3fdd180-75a2-11ea-9a01-cff0c7c3fe53.png)
