### ISSUE TITLE
Ridiculously large vsix size

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode-pull-request-github#16]
At 141MB, this extension is ridiculously large. Is it please possible to trim some of the fat?

**Comment by joaomoreno** [comment]
OMG I just came here for this. Extracted, the extension totals 301MB, of which 280MB is the `dugite` dependency which ships an ENTIRE git installation with it.

We already have a great, `Promise`-based, [git api](https://github.com/Microsoft/vscode/blob/master/extensions/git/src/git.ts) in our Git extension, which is an [issue](https://github.com/Microsoft/vscode/issues/31103) away from getting its full API exported to other extensions.

Can we maybe do that instead?

**Comment by alexandrudima** [comment]
This is much much better!!
