### ISSUE TITLE
Inline diff does not work

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-pull-request-github#160]
Issue Type: <b>Bug</b>

I looked at  `/src/vs/editor/contrib/suggest/suggestWidget.ts` in https://github.com/Microsoft/vscode/pull/56052.
I switched the diff editor to inline mode. and got

![image](https://user-images.githubusercontent.com/4674940/43934373-eb6f2276-9c03-11e8-8636-bca5344bfd9d.png)

Extension version: 0.0.9
VS Code version: Code - Insiders 1.27.0-insider (e3e972589db57a16da6426828706ced9c2d52848, 2018-08-09T23:55:15.226Z)
OS version: Windows_NT ia32 10.0.17134

**Comment by rebornix** [comment]
The comments part in workspace has no knowledge of the state of the diff editor (whether it's inline or side by side). Right now we only take care of models bind to the diff editor (an original one and a modified one) so the extension has no idea with the view state info as well.

**Comment by rebornix** [comment]
One thing we can probably do is moving the viewzones/decorations from the original editor to the modified editor and displaying them next to where we show the deleted code from the original editor.

For example, someone left a comment in the deleted range in the original editor, it would be displayed as below for now

<img width="611" alt="image" src="https://user-images.githubusercontent.com/876920/44065156-f03f44c6-9f1d-11e8-8dca-2268f4b591f1.png">

If we move it up to the modified editor, it can look like

<img width="620" alt="image" src="https://user-images.githubusercontent.com/876920/44065380-1f90ba92-9f1f-11e8-9586-323d399a4d9a.png">

**Comment by macintacos** [comment]
@RMacfarlane is there an upstream issue we can follow to see if this will get fixed? I just discovered this and it's become quite the annoyance.

**Comment by alexr00** [comment]
Closing in favor of upstream issue: https://github.com/microsoft/vscode/issues/167733
