### ISSUE TITLE
Error signing into GHE

### ISSUE THREAD

**Issue by gee4vee** [microsoft/vscode-pull-request-github#1607]
Getting this error after authenticating with GHE using either the link or copy/paste method.

<img width="489" alt="image" src="https://user-images.githubusercontent.com/179807/78588366-196d0980-7804-11ea-88ad-fe98fa9bcf95.png">

- Extension version: 0.15.0
- VSCode Version: 1.43.2
- OS: 10.15.3

Steps to Reproduce:

1. Open a file contained in a GHE-enabled repo
2. Go the PR extension tab and click Sign In
3. Follow the prompts in the browser to authenticate.

**Comment by TheSpyder** [comment]
If you look in `view -> output` and change the dropdown to `GitHub Pull Request` it will have more info. That's the same error I see in #1474 but I'm signing in to the public github.com 🤔

**Comment by gee4vee** [comment]
This is what I see in the output view:
```
[Info] Looking for git repository
[Info] Git repository found, initializing review manager and pr tree view.
[Info] Review> Validate state in progress
[Info] Review> Validating state...
[Info] No remote with name 'upstream' found. Please update your 'githubPullRequests.remotes' setting.
[Info] No remote with name 'upstream' found. Please update your 'githubPullRequests.remotes' setting.
[Info] Found GitHub remote
[Info] Found GitHub remote
[Info] Review> no matching pull request metadata found for current branch fixes

```

**Comment by csullens-work** [comment]
> This is what I see in the output view:
> 
> ```
> [Info] Looking for git repository
> [Info] Git repository found, initializing review manager and pr tree view.
> [Info] Review> Validate state in progress
> [Info] Review> Validating state...
> [Info] No remote with name 'upstream' found. Please update your 'githubPullRequests.remotes' setting.
> [Info] No remote with name 'upstream' found. Please update your 'githubPullRequests.remotes' setting.
> [Info] Found GitHub remote
> [Info] Found GitHub remote
> [Info] Review> no matching pull request metadata found for current branch fixes
> ```

Same here with GHE...no errors in output, only in pop-up.

**Comment by RMacfarlane** [comment]
We have discontinued support for GitHub Enterprise. https://github.com/microsoft/vscode-pull-request-github/wiki#2-is-github-enterprise-supported
