### ISSUE TITLE
Need to move to file decorators for file with comments

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode-pull-request-github#161]
Issue Type: <b>Bug</b>

We now have file decorators in the custom trees. We should move to use those.

Extension version: 0.0.9
VS Code version: Code - Insiders 1.27.0-insider (e3e972589db57a16da6426828706ced9c2d52848, 2018-08-09T23:55:15.226Z)
OS version: Windows_NT ia32 10.0.17134

**Comment by rebornix** [comment]
Probably blocked by https://github.com/Microsoft/vscode/issues/54939#issuecomment-412399865

**Comment by rebornix** [comment]
As mentioned in https://github.com/Microsoft/vscode/issues/54939#issuecomment-412520619
 , decoration provider for all schemes will be implemented https://github.com/Microsoft/vscode/issues/54938

**Comment by roblourens** [comment]
I see a diamond shape on entries that have comments, I assume that's what this is about.
