### ISSUE TITLE
The remote '...' is not a GitHub repository

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#1610]
When checking out https://github.com/microsoft/vscode/pull/91243

![image](https://user-images.githubusercontent.com/2193314/78680546-79b18900-78a0-11ea-92a4-cb8a4bf559ea.png)

I guess it's related to a `#` in the branch name? https://github.com/dormesica/vscode/tree/%2390993

**Comment by Tyriar** [comment]
https://github.com/xtermjs/xterm.js/pull/2739

![image](https://user-images.githubusercontent.com/2193314/78994375-bc6b9f00-7af4-11ea-9829-98a20d9ca9d1.png)

```
[Info] /home/daimms/.ssh/config: ENOENT: no such file or directory, open '/home/daimms/.ssh/config'
[Info] Looking for git repository
[Info] Git repository found, initializing review manager and pr tree view.
[Info] Review> Validate state in progress
[Info] Review> Validating state...
[Info] Found GitHub remote
[Info] Found GitHub remote
[Info] Review> no matching pull request metadata found for current branch master
[Info] Review> Queuing additional validate state
[Info] Review> Validating state...
[Info] Found GitHub remote
[Info] Review> no matching pull request metadata found for current branch master
[Info] Review> Queuing additional validate state
[Info] Review> Validating state...
[Info] Found GitHub remote
[Info] Review> no matching pull request metadata found for current branch master
[Info] Review> switch to Pull Request #2739 - start
[Info] PullRequestGitHelper> Branch pr/felixse/2739 is from a fork. Create a remote first.
[Info] PullRequestGitHelper> create remote for https://github.com/felixse/xterm.js.
[Info] PullRequestGitHelper> associate pr/felixse/2739 with Pull Request #2739
[Info] Review> Review> switch to Pull Request #2739 - done
[Info] Review> Queuing additional validate state
[Info] Review> Validating state...
[Info] Found GitHub remote
[Info] Review> current branch pr/felixse/2739 is associated with pull request #2739
[Info] Review> Resolving pull request
[Info] Review> Fetching pull request data
[Info] Review> register comments provider
[Info] Review> display pull request status bar indicator and refresh pull request tree view.
```

**Comment by RMacfarlane** [comment]
@alexr00 It looks like this is from the issue's stateManager trying to do `setCurrentIssueFromBranch`, specifically `this.manager.getPullRequestDefaults()`. When the repository state updates, the pullRequestManager is eventually notified to update its own state of GitHub repositories. But here it gets called before it has had a chance to update. I'm worried about having two separate event listeners for repository state updates, could we maybe trigger the issue changes from within the one in `reviewManager`? The other advantage of putting things at the end of that event listener is that it filters out a lot of repository state changes that we don't care about, like working tree changes.

As a workaround I will change the prManager to always recalculate the GitHub repositories for that call

**Comment by alexr00** [comment]
@RMacfarlane I added a debt item so I don't forget about using only the one listener.
