### ISSUE TITLE
A list of files displayed in a PR is trimmed (very large PR)

### ISSUE THREAD

**Issue by phobos2077** [microsoft/vscode-pull-request-github#1613]
A PR with 1907 files is loaded and working, but there are many files missing in the extension UI. It seems like there is some kind of hard limit on the number of files loaded from github API and the rest is just discarded. Or some bug in the extension logic?

- Extension version: 0.15.0
- VSCode Version: 1.44.0
- OS: Windows 10 x64

Steps to Reproduce:

1. Open PR with 1907 files in "GitHub Pull Requests".
2. Observe as many files are missing.

**Comment by MFAshby** [comment]
I have observed the same problem. I think the problem is here https://github.com/microsoft/vscode-pull-request-github/blob/b7c553b2676cb6594cbda0c815737314e71d1fe4/src/github/pullRequestManager.ts#L1915

This is only returning 300 changed files maximum.

**Comment by MFAshby** [comment]
I think files should be listed with octokit.pulls.listFiles, I'll submit a PR for this.
