### ISSUE TITLE
Adopt VSCode Authentication Provider API

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode-pull-request-github#1616]
Now that VSCode ships with a GitHub authentication provider, we can leverage it to get the access token we need. This will help unify the accounts UI, so we can remove the status bar item.

**Comment by IllusionMH** [comment]
Looks like after this change I'm unable to access org repos without separate approve from admins. Is it expected change?

**Comment by drayfar** [comment]
After this change, I can no longer sign in to GitHub Enterprise using a PAT - the command `GitHub Pull Requests: Manually Provide Authentication Response` listed in the Wiki no longer exists.
