### ISSUE TITLE
Self-hosted github auth fails for non-https instance.

### ISSUE THREAD

**Issue by bedge** [microsoft/vscode-pull-request-github#1625]
The extension authentication fails for locally hosted github instances that are running over http.

When clicking on the "Sign into <my local github>" in the status bar, the generated URL is: 

> https://vscode-auth.github.com/authorize/?callbackUri=vscode-insiders://github.vscode-pull-request-github/did-authenticate%253FwindowId%253D10&scope=read:user%20user:email%20repo%20write:discussion&state=0a63e945-c153-4d99-82f3-153981269822&responseType=code&authServer=https://my.local.url/

while the actual configured URL is 
    http://my.local.url/
not
    https://my.local.url/
Note the missing "s" on http.

Editing the URL to change https -> http, gets me one step further, in that I get a token, but that then fails to authenticate.

**Comment by RMacfarlane** [comment]
Closing this as out-of-scope
