### ISSUE TITLE
OAuth demands too much

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode-pull-request-github#163]
This seems to be way too much access for this extension:

![image](https://user-images.githubusercontent.com/22350/43945056-5178b9e2-9c81-11e8-9b85-189c07e0f659.png)

**Comment by DanTup** [comment]
Related: https://github.com/Microsoft/vscode-pull-request-github/issues/563

> That is the standard permission set when an extension needs access to public and private repositories

Why do you need access to all public and private repos? It's bad enough that third party integrations all demand this; but I thought GitHub would do better. I wouldn't use this extension on the basis of this.. I'm aware GitHub essentially already has access to my private repos, but I won't install any extensions/apps/etc. that require more access than they need. It's a worrying trend that isn't encouraging users to care about security.
