### ISSUE TITLE
Bringing up quick pick of Reviewers takes a long time

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode-pull-request-github#1636]
```
Version: 1.45.0-insider
Commit: 92ff20ac39c7507fdf4164e2bedfdfb700805fe1
Date: 2020-04-14T18:06:32.175Z
Electron: 7.2.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 17.7.0
```

Nightly Build of extension: `2020.4.21062`

I am working on a PR in https://github.com/micrsoft/vscode-node-azure-pack

On the Description Page, click on the "+" next to Reviewers on the right side

![image](https://user-images.githubusercontent.com/1487073/79394420-49b35700-7f2c-11ea-9271-d3bd02927dfb.png)

result: after a few *minutes* the quick pick of people came up.

I realize there are a lot of people in the Microsoft org, but I had time to open the browser and search for a set of issues in this repository before the list came up :).  Maybe there is some progress we can show, or show just the first 100 and page in the rest ...

**Comment by alexr00** [comment]
We should show progress, even though we can't make it any faster.

**Comment by alexr00** [comment]
Looks like showing progress has been fixed in the meantime.
