### ISSUE TITLE
Enable Request Changes if no comment text

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode-pull-request-github#1637]
I can only click the "Request Changes" button if I am editing the comment text in the Description.  So either I add a comment OR I add a comment and say Request Changes.  I feel like Request Changes should always be enabled, like the "Approve" button is.

![image](https://user-images.githubusercontent.com/1487073/79395118-d27ec280-7f2d-11ea-9594-cd00646eaec3.png)

**Comment by RMacfarlane** [comment]
This is a limitation of GitHub - it's not possible to leave a "Request Changes" review without a comment

**Comment by chrisdias** [comment]
We could be better than github!  

We could have it enabled and if no comment exists, then we say "Please leave a comment in order to request changes".  Or, we could default a comment that says "Changes requested".  Or, we leave a single space comment!

**Comment by alexr00** [comment]
Given that no one else has noticed this, closing to maintain consistency with github.
