### ISSUE TITLE
Better issue data refresh

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#1642]
From @dbaeumer: add a keybinding so that you can refresh the issues while in the suggest widget (would still then need to retrigger widget, but then issues would be refreshed at that point).

This is in addition to the issue refresh that happens on certain git actions.

**Comment by alexr00** [comment]
To verify:
Trigger the issue suggestions
While the suggestions are showing, do `ctrl+shift+space`
Re-trigger issue suggestions and verify that they have been refreshed.

**Comment by aeschli** [comment]
A shortcurt for a refresh is a good thing, not just when doing code completions, but also to update the issue section in MyIssue. IMO it would be cool to have a shortcut that is available everywhere (I know, easier said than done, not many shortcurt left)

**Comment by dbaeumer** [comment]
I need to reopen this since it doesn't work for me under Windows in the Git input field when picking a issue.

**Comment by dbaeumer** [comment]
See screen shot
<img width="878" alt="capture" src="https://user-images.githubusercontent.com/1931590/80607306-a38c4480-8a35-11ea-8741-f17531381c49.png">

Although pressing Ctrl+Shift+Space the item 197 doesn't disappear. But it should.

**Comment by alexr00** [comment]
@dbaeumer did you retrigger the suggestions? I don't believe there's a way to refresh the widget itself from an extension.

**Comment by dbaeumer** [comment]
Yes, pressed `Ctrl+Shift+Space` a couple of times.

**Comment by alexr00** [comment]
But did you close the suggest widget and re-open it? It is still working for me.

**Comment by dbaeumer** [comment]
I was expecting that the widget reloads. Having to close and reopen it makes it pretty hard to use from a user perspective. A user has to open the widget, press ctrl+shift+space, close the widget and reopen it :-). Any objection to reopen the issue to make this refresh automatically?
