### ISSUE TITLE
Add setting to allow turning off issue completion

### ISSUE THREAD

**Issue by 333fred** [microsoft/vscode-pull-request-github#1645]
Like https://github.com/microsoft/vscode-pull-request-github/issues/1589, but for `#`. As I said in that issue, this bites me daily, and while user completion has actually been useful once, issue completion has not.

**Comment by RMacfarlane** [comment]
@333fred We have added a setting to turn this off:
<img width="603" alt="Screen Shot 2020-04-16 at 8 13 03 AM" src="https://user-images.githubusercontent.com/3672607/79473611-3b138100-7fba-11ea-8044-15a13acbc3bf.png">

however this change as not yet been shipped, it is only available in the nightly version of the extension: https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github-insiders

**Comment by 333fred** [comment]
Ah, given https://github.com/microsoft/vscode-pull-request-github/issues/1589#issuecomment-607654343 I had assumed that this setting didn't exist and the linked PR only added it for user completion. Sorry about that.

Any idea when it will be released on stable?
