### ISSUE TITLE
PR description draft / edit gets saved/copied into new PR

### ISSUE THREAD

**Issue by mix3d** [microsoft/vscode-pull-request-github#1646]
- Extension version: 0.15.0
- VSCode Version: 1.44.1
- OS: Windows 10

Steps to Reproduce:

1. Create a PR, begin to edit the comment. Close the tab. 
2. Create a new PR from a different branch. The PR window will open, with the Comment draft from the previous PR still open, including save/cancel buttons. (Normally the comment area is empty for a new PR, _"No description provided"_)

**Comment by alexr00** [comment]
This has been fixed in the mean time!
