### ISSUE TITLE
Can't add reviewers to a PR

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#1653]
I created a PR (in this repo actually), and then clicked the '+' Reviewers as I have many times. Instead of showing the list of possible reviewers to add, I got an error toast "e is not an iterable", which also showed in the console. 
Stack trace isn't very helpful, but here it is:
```
notificationsAlerts.ts:40 e is not iterable
onDidChangeNotification @ notificationsAlerts.ts:40
(anonymous) @ notificationsAlerts.ts:26
fire @ event.ts:587
addNotification @ notifications.ts:207
notify @ notificationService.ts:106
(anonymous) @ mainThreadMessageService.ts:83
_showMessage @ mainThreadMessageService.ts:44
$showMessage @ mainThreadMessageService.ts:38
_doInvokeHandler @ rpcProtocol.ts:402
_invokeHandler @ rpcProtocol.ts:387
_receiveRequest @ rpcProtocol.ts:303
_receiveOneMessage @ rpcProtocol.ts:230
(anonymous) @ rpcProtocol.ts:105
fire @ event.ts:587
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:587
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:203
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:276
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
```

**Comment by alexr00** [comment]
Now it has asked me to sign in again (which I did). It shows the user picker, but then shows an error "Must have admin rights to Repository"

**Comment by RMacfarlane** [comment]
I think I've fixed this with https://github.com/microsoft/vscode/commit/fd88fb9667a70f9b0a81dbf36ef07d7fb330d0c7

I believe you're in a state where when you signed out, the token got revoked but not removed from the keychain, and now when you try to sign out, trying to revoke it again throws, preventing it from being removed ever

Let me know if signing out and in again now works.

**Comment by alexr00** [comment]
It seems that I'm lacking a way to sign out of GitHub. What am I missing here?
![image](https://user-images.githubusercontent.com/38270282/79977287-4d039100-849e-11ea-995b-07b7f6c2c307.png)

**Comment by RMacfarlane** [comment]
If you have a `"configurationSync.store"` setting, can you remove it? That should cause the accounts icon to appear, where you can sign out from

**Comment by RMacfarlane** [comment]
I'm wondering if maybe I should expose logout in the auth provider API and we should keep the sign out command, it seems currently very hard to discover

**Comment by alexr00** [comment]
Done. I still get many sign in problems. The PR extension often claims I've signed out. I also appear to be lacking the scopes required (or have some other problem) to comment on a PR and to merge a PR.

**Comment by RMacfarlane** [comment]
I still haven't been able to reproduce the random sign outs - does it seem like it's always tied to a user action like starting a PR, or does it sometimes just happen?

For the comment/merge problem, when changing to the new authentication provider, we changed from using a first party GitHub app to a third party app. Accessing data on organization-owned private repos doesn't work by default for third party apps, and it seems like there are other operations that fail as well. I'm working on getting back to a first party app.

**Comment by RMacfarlane** [comment]
Closing as I believe this has been fixed by the upstream changes to the GitHub auth provider
