### ISSUE TITLE
Can't approve PR

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#1660]
Since we started doing PRs, I've been exclusively using the PR webview to approve them. Today, while reviewing https://github.com/microsoft/vscode-pull-request-github/pull/1658 I get `Approving pull request failed. Not Found`. Info in the console isn't very useful. 

Logs from the output:
```
[Info] Looking for git repository
[Info] Git repository found, initializing review manager and pr tree view.
[Info] Review> Validate state in progress
[Info] Review> Validating state...
[Info] No remote with name 'origin' found. Please update your 'githubPullRequests.remotes' setting.
[Info] No remote with name 'upstream' found. Please update your 'githubPullRequests.remotes' setting.
[Info] Review> Queuing additional validate state
[Info] Review> Validating state...
[Info] No GitHub remotes found
[Info] Review> no matching pull request metadata found for current branch master
[Info] Review> Queuing additional validate state
[Info] Review> Validating state...
[Info] No remote with name 'upstream' found. Please update your 'githubPullRequests.remotes' setting.
[Info] Found GitHub remote
[Info] Review> no matching pull request metadata found for current branch master
```

**Comment by alexr00** [comment]
It seems to be consistent. It also happened with the other PR I reviewed today.

**Comment by alexr00** [comment]
I also can't leave comments

**Comment by RMacfarlane** [comment]
Hmm, can you try signing out and in again? I'm wondering if something went wrong in token creation and you have a token with the wrong permissions

**Comment by alexr00** [comment]
I have tried that, though not by choice. Several times the PR view has gone from having all the PR queries to just "Sign in", so of course I sign in again. I now also can't create PRs.

**Comment by alexr00** [comment]
Ok, the way to repro the unintended sign out for me is to try to create a PR to this repo. It signs me out every time.

**Comment by alexr00** [comment]
Apparently it only signs me out 3ish times. If I try to create a pull request enough times it eventually worked.

**Comment by RMacfarlane** [comment]
Huh, ok, I'll see if I can repro it.

Which version of Insider's are you on now? 9328b32008089c515f39a13db9c71e57c7d36823?

**Comment by alexr00** [comment]
Yes. Now I'm on bd262894bbaac5156d5bf832160b7056c91decea and still having problems.

**Comment by aeschli** [comment]
I get the same error when trying to approve PRs. I tried with https://github.com/microsoft/vscode-css-languageservice/pull/200 and https://github.com/microsoft/vscode/pull/105716

[Info] Looking for git repository
[Info] Git repository found, initializing review manager and pr tree view.
[Info] Review> Validate state in progress
[Info] Review> Validating state...
[Info] No remote with name 'upstream' found. Please update your 'githubPullRequests.remotes' setting.
[Info] Found GitHub remote
[Info] Review> no matching pull request metadata found for current branch master

**Comment by aeschli** [comment]
Not sure if related, trying to start a review gives:
Starting a review failed: Error: GraphQL error: Although you appear to have the correct authorization credentials, the `microsoft` organization has enabled OAuth App access restrictions, meaning that data access to third-parties is limited. For more information on these restrictions, including how to whitelist this app, visit https://docs.github.com/articles/restricting-access-to-your-organization-s-data/

**Comment by RMacfarlane** [comment]
@aeschli Was this with desktop vscode? Can you try signing out and signing in again? A long time ago, the auth used a third party app, but we should currently be using a first party app

**Comment by connor4312** [comment]
I was able to approve and verify the linked issue. I also saw the "upstream" error but I think this expected for most repos (the 'call to action' in the error message is probably not necessary).

**Comment by alexr00** [comment]
Haven't seen this issue in > 1 year.
