### ISSUE TITLE
Copy Github Permalink is broken on Web

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-pull-request-github#1663]
![image (2)](https://user-images.githubusercontent.com/10746682/79867608-e5d2d780-83de-11ea-92a4-5431aaffd6f8.png)

**Comment by alexr00** [comment]
You weren't signed in for the PR extension (sign in doesn't seem to work in the web @RMacfarlane FYI)

I'll hide the commands when you aren't signed in.
