### ISSUE TITLE
Support to export code to GitHub

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-pull-request-github#1664]
There are a few scenarios:

- [x] **Single folder open, no repo.** Show welcome view content and status bar item to export the currently open file to a GitHub repository
- [x] **Single folder open, repo, but no remotes.** Show status bar item to export the currently open file to a GitHub repository.
- [x] **Multi folder open, some repos with no remotes.** Show status bar item to export one of the currently opened folder repos to a GitHub repository.
- [x] **Multi folder open, no repos.** Show status bar item to export one of the currently opened folder repos to a GitHub repository.

**Comment by joaomoreno** [comment]
A few considerations:

- In order to create a repo, the user must pick between public and private, and we must present this choice properly with a warning lest they end up accidentally publishing private data to the wild.
- Authentication is an issue when dealing with the git cli (`git push`). The auth token might be sufficient but it needs to be hooked up to the git cli. For now we prompt the user to choose between HTTPS and SSH and it's up to them to have auth properly configured in git cli. In the near future we can have a contribution mechanism in the git extension to have external authentication handlers and then have the GHPR extension be such a handler and use the token for auth in the git cli.

**Comment by joaomoreno** [comment]
Update:

- Authentication is now automatically handled in the core: https://github.com/microsoft/vscode/issues/96241
- Still need to figure out a `.gitignore` strategy

**Comment by joaomoreno** [comment]
**Verification:**

This month we added support to export a a repository to GitHub from the status bar, where the Sync action would normally be. If a repository has no remotes (multi-root or otherwise), it should still show the publish status bar icon which drives the user to export the repository to GitHub.

Additionally, when in a multi-root workspace and there are no repos, the `Publish to GitHub` action in the SCM welcome view should prompt the user to pick which workspace root it should publish.

**Comment by isidorn** [comment]
Works great. Created one small follow up item https://github.com/microsoft/vscode-pull-request-github/issues/1852
