### ISSUE TITLE
Clean up credential store API

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode-pull-request-github#1667]
Instead of exposing hasOctokit, getHub, loginWithConfirmation, login, etc., consolidate into a clearer API

**Comment by joaomoreno** [comment]
As a reference, here's what I converged on after lots of trial and error:

https://github.com/microsoft/vscode-pull-request-github/blob/a1d82e4c6f608fe89324240f81c66d7b2d4cd82f/src/gitExtensionIntegration.ts#L60:L70

**Comment by joaomoreno** [comment]
@RMacfarlane Thanks, looks great!
