### ISSUE TITLE
Strange build error

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-pull-request-github#1669]
I always have this error when running the build locally. Not really sure how to fix it.

```
    ERROR in /home/joao/Work/vscode-pull-request-github/src/gitProviders/vsls.ts
    ./src/gitProviders/vsls.ts
    [tsl] ERROR in /home/joao/Work/vscode-pull-request-github/src/gitProviders/vsls.ts(7,27)
          TS6059: File '/home/joao/Work/vscode-pull-request-github/node_modules/vsls/vscode.ts' is not under 'rootDir' '/home/joao/Work/vscode-pull-request-github/src'. 'rootDir' is expected to contain all source files.
```

Also see it in Code:

![image](https://user-images.githubusercontent.com/22350/79974281-53dbd500-8499-11ea-8c39-770b165934ce.png)

**Comment by RMacfarlane** [comment]
Are you still seeing this if you pull the latest and re-run yarn? I may have fixed this with https://github.com/microsoft/vscode-pull-request-github/commit/60006465c818d0227f0bb3a02b36582623a917d1

**Comment by joaomoreno** [comment]
I don't see it in Code, but I do see it in the build:

![image](https://user-images.githubusercontent.com/22350/81539136-14a1f500-9370-11ea-93fa-ab40761c98cf.png)

**Comment by alexr00** [comment]
This appears to be fixed.
