### ISSUE TITLE
New icon is thinner than the rest of the icons

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#1670]
It also appears to be an svg not an icon font which makes it look more out of place (do all extensions have this problem?)

![image](https://user-images.githubusercontent.com/2193314/79992426-5114bc00-8468-11ea-957a-f352e9e9d240.png)

![image](https://user-images.githubusercontent.com/2193314/79992468-5d991480-8468-11ea-9092-f594d0f1524b.png)

**Comment by misolori** [comment]
> do all extensions have this problem?
Yes, because every extension icon they provide is an svg.

**Comment by misolori** [comment]
There's nothing an extension can do here
