### ISSUE TITLE
Add settings for entirely turning off user and issue completion

### ISSUE THREAD

**Issue by ecraig12345** [microsoft/vscode-pull-request-github#1672]
Like #1589 and #1645 but not per-language. I do not find these features useful and would like to completely disable them, without enumerating every single language I use.

More background: the reason I don't find these useful is because there are too many other contexts in which I might type `@` or `#` (even in comments) which have nothing to do with GitHub. You might be able to make inference of GH-related intent a bit smarter, but it seems like that would be really hard to entirely get right.

**Comment by ecraig12345** [comment]
Also, even when I add the current language to the ignore list (using the nightly build), I'm still getting user completions?
```
  "githubIssues.ignoreUserCompletionTrigger": [
    "python",
    "javascript",
    "typescript",
    "javascriptreact",
    "typescriptreact",
    "markdown",
    "plaintext",
    "shellscript",
    "html",
    "css",
    "scss"
  ]
```

**Comment by alexr00** [comment]
Try out the two settings `"githubIssues.issueCompletions.enabled"` and `"githubIssues.userCompletions.enabled"` and verify that they correctly disable issue and user completions.

**Comment by ecraig12345** [comment]
Works for me. Thanks!
