### ISSUE TITLE
Creating comment failed: HttpError: Not Found

### ISSUE THREAD

**Issue by RikkiGibson** [microsoft/vscode-pull-request-github#1673]
Using the nightly build (2020.4.31142) or master (0aa30ea) gives this error when I hit the "Add Comment" button. The comment view then changes to the "edit" mode with cancel/save buttons.

I tried to get a stack for this but I didn't manage to hit a breakpoint for it. The error in the developer console has a stack with one frame, but it's core workbench code. I wonder if there's something that can be done in general to make it so more useful stacks are available in the developer console when errors happen.

0.15.0 stable creates comments just fine, so this may be a regression.

**Comment by RMacfarlane** [comment]
Do you remember if you had the PR checked out when trying to comment?

**Comment by RikkiGibson** [comment]
I had an unrelated feature branch checked out in my local repo. Is that what you mean?

**Comment by RMacfarlane** [comment]
Yeah, that's what I meant. I'm able to repro this, looking into it now.

**Comment by roblourens** [comment]
Should the fix be in the latest nightly build? I still repro this.

**Comment by RMacfarlane** [comment]
Yeah, it should be. Can you try signing out and in again? I'm wondering if the first-party vs third-party app registration is also making a difference here

**Comment by roblourens** [comment]
That worked
