### ISSUE TITLE
Squash and merge doesn't populate description

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#1679]
When I squash and merge a PR, I expect the description to be populated with something (I would prefer it just have the original description on the PR, but I think GitHub usually does all the commit titles).

![image](https://user-images.githubusercontent.com/38270282/80078149-cbb80700-854e-11ea-8abf-870067d0c084.png)

**Comment by felipecassiors** [comment]
I also agree that populating the commit message body with the PR description is better, but I think this behavior should be adopted by the entire GitHub, not only on this extension. So for the sake of fragmentation, the right path would be to mimic GitHub web functionalities.

**Comment by alexr00** [comment]
Fixed with https://github.com/microsoft/vscode-pull-request-github/issues/5306
