### ISSUE TITLE
Inline comments with `code` blocks should use editor font

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode-pull-request-github#168]
The `code` font looks out of place, in inline comments:

![image](https://user-images.githubusercontent.com/22350/43945649-11f308a2-9c83-11e8-9625-104496a593d8.png)

**Comment by rebornix** [comment]
@misolori any idea of how we are going to use editor fonts in comments?

**Comment by RMacfarlane** [comment]
The comment widget has a reference to the editor it belongs to, I think we could get the font information from that. (`this.editor.getConfiguration().fontInfo`?)

We apply other theme information for that widget here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/comments/electron-browser/commentThreadWidget.ts#L580

**Comment by misolori** [comment]
Is there a reason why we need to use the editor font here? It seems like we need to find a better monospace font that works in this view. GitHub uses `"SFMono-Regular",Consolas,"Liberation Mono",Menlo,Courier,monospace` for their code font. That would look like this in our view:

<img width="50%" src="https://user-images.githubusercontent.com/35271042/44220013-40a82c00-a132-11e8-89f7-3df6bc260b3e.png">

Thoughts?

**Comment by RMacfarlane** [comment]
I think that looks better, but IMO using the editor font seems like the best choice. Since the comment widget is part of the core of VSCode, it would make sense for it to honor user preferences/be styled consistently with other code

**Comment by rebornix** [comment]
Let's use editor font for the code in comments first and see users' feedback on this. Thanks you two for the feedback!
