### ISSUE TITLE
Can't see PRs for GitHub org

### ISSUE THREAD

**Issue by azec-pdx** [microsoft/vscode-pull-request-github#1695]
I am member of few organizations/teams in GitHub.
I contribute to multiple private repositories that belong to orgs.

When I installed VS Code extension for GitHub Pull Requests I used manually entered auth token with roles provided in [wiki doc](https://github.com/Microsoft/vscode-pull-request-github/wiki#personal-access-token-authentication).

- Extension version: `0.15.0`
- VSCode Version:
    ```
    Version: 1.44.2
    Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
    Date: 2020-04-16T17:07:18.473Z
    Electron: 7.1.11
    Chrome: 78.0.3904.130
    Node.js: 12.8.1
    V8: 7.8.279.23-electron.0
    OS: Darwin x64 19.2.0
    ```
- OS: `macOS Catalina , version: 10.15.2 (19C57)`

Steps to Reproduce:

1. Login to VSCode and go to SCM viewlet
2.Expand `GitHub Pull Requests` viewlet and click refresh icon to fetch all PRs (based on default queries).
3. Only PRs that belong to private/public repositories that I am owner of are shown. These repositories don't belong to any org. However, none of the PRs that are on repositories that belong to the org. which I am member of and for which I am requested as reviewer are shown. See screenshot...

<img width="1683" alt="Screen Shot 2020-04-25 at 3 23 23 PM" src="https://user-images.githubusercontent.com/1272830/80292138-c6062100-8708-11ea-9556-14a2c13ee11a.png">

4. Compared to this, if I do queries of PRs in GitHub UI, I can see many PRs on repos in my org for which I am requested as reviewer ... (see second screenshot) ...

<img width="1188" alt="Screen Shot 2020-04-25 at 3 25 20 PM" src="https://user-images.githubusercontent.com/1272830/80292165-38770100-8709-11ea-8c0c-7234d7a9a58e.png">

I am not sure if I am missing some permissions that should be assigned to my GitHub token, or maybe my organization needs to add specific access privileges to my GitHub user for each repository in org for which I am interested to manage PRs through VSCode extension? Or maybe it is VSCode bug? I couldn't find anything relevant through searches of existing issues.

**Comment by RMacfarlane** [comment]
The extension looks at the remotes of the currently open folder and shows pull requests based on those. Do you have open the repository belonging to an organization?

**Comment by azec-pdx** [comment]
Thank you @RMacfarlane ! Indeed that was my problem. I was assuming that like GitHub UI for Pull Requests searches does, VSCode plugin will show all my PRs (globally) instead of being focused just on currently opened folder (being valid git repo). 
I am closing the ticket therefore!
