### ISSUE TITLE
VSIX does not work on Windows

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode-pull-request-github#17]
![image](https://user-images.githubusercontent.com/5047891/41914202-9d9fd0be-7952-11e8-8372-b331ff14c015.png)

> Git could not be found at the expected path: `'C:\Users\alex\.vscode-insiders\extensions\microsoft.vscode-pull-request-github-0.0.1\node_modules\dugite\git\cmd\git.exe'`. This might be a problem with how the application is packaged, so confirm this folder hasn't been removed when packaging.: 

> Error: Git could not be found at the expected path: `'C:\Users\alex\.vscode-insiders\extensions\microsoft.vscode-pull-request-github-0.0.1\node_modules\dugite\git\cmd\git.exe'`. This might be a problem with how the application is packaged, so confirm this folder hasn't been removed when packaging.

I think you might have packaged some **binaries** for macOS inside the vsix...

![image](https://user-images.githubusercontent.com/5047891/41914146-71940e18-7952-11e8-8435-179c0b3e7334.png)

And ... see #16 ... why would you ship `git` and not use the one installed on the machine ...

**Comment by rebornix** [comment]
https://github.com/Microsoft/vscode-pull-request-github/releases/tag/v0.0.2 now uses local git, this issue should be gone now.

**Comment by alexandrudima** [comment]
This works fine now, closing!
