### ISSUE TITLE
Draft PR opens PR in 'review' mode

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-pull-request-github#1704]
https://github.com/microsoft/vscode-internalbacklog/issues/1021

This might need a 'work in progress' mode:
![image](https://user-images.githubusercontent.com/9205389/80495364-1a5b0c00-8968-11ea-866b-94f364e69613.png)

E.g., 'Approve' is enabled. 'Exit Review Mode' would need an other label.

**Comment by alexr00** [comment]
@burkeholland this might be a good one for you!
