### ISSUE TITLE
Ask if I want to create a new branch

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-pull-request-github#1706]
https://github.com/microsoft/vscode-internalbacklog/issues/1021

I might sometimes start a (draft) PR from the target branch and sometimes from an issue branch that already has changes against the target branch. It might make more sense to ask the user if the current branch should be used or a new one should be created:
![image](https://user-images.githubusercontent.com/9205389/80496892-1334fd80-896a-11ea-9524-74588fcc6cb8.png)

**Comment by alexr00** [comment]
Closing as as-designed since you're getting to this menu by clicking on the current issue status bar entry.
