### ISSUE TITLE
Issues pane shows no issues on load

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode-pull-request-github#1710]
Testing https://github.com/microsoft/vscode-internalbacklog/issues/1021

![image](https://user-images.githubusercontent.com/35271042/80514809-df3fe500-8935-11ea-943a-0cbb8add52f8.png)

It's a small repo with 2 issues, one is assigned to me, and when I first open the pane the issues list is empty, which is confusing and makes me think something is broken. I click re-fresh and nothing happens. I then hide the view and then show it again and it finally shows the issues:

![image](https://user-images.githubusercontent.com/35271042/80515135-507f9800-8936-11ea-924e-3df4500aefdc.png)

But I tried to repro this and even the steps above don't work so something weird is happening here.

**Comment by alexr00** [comment]
The issues pane starts out empty because we wait for auth and other extension setup to happen first. I think having the 'Loading...' message will help this, and I'll put an error in there if something goes wrong.
