### ISSUE TITLE
Issues pane needs better loading state

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode-pull-request-github#1712]
The PR pane uses both the loading bar and a loading entry, we also do this in other views. I think the issues pane should also show the loading entry.

**Issues pane**
![image](https://user-images.githubusercontent.com/35271042/80518305-27add180-893b-11ea-9659-8ed351575542.png)

**PR pane**
![image](https://user-images.githubusercontent.com/35271042/80518342-31373980-893b-11ea-8021-e948c6c204ab.png)

**Comment by alexr00** [comment]
Copied what the Pull Requests view does.
