### ISSUE TITLE
Commenting is not supported outside diff hunks error even if I am inside the diff hunk

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode-pull-request-github#172]
I checkedout the PR https://github.com/Microsoft/vscode/pull/56053 and trying to add a comment on a hunk when I got the `Commenting is not supported outside diff hunks`

![image](https://user-images.githubusercontent.com/16890566/43974797-74bac314-9c90-11e8-9633-5e950c740a39.png)

![image](https://user-images.githubusercontent.com/16890566/43974809-8184309e-9c90-11e8-879a-fcab41696507.png)

And the output says PR is no longer valid

![image](https://user-images.githubusercontent.com/16890566/43974821-8c750302-9c90-11e8-825a-aa326dbf46b3.png)

**Comment by rebornix** [comment]
@ramya-rao-a does the diff view you see only contain partial diff?

**Comment by ramya-rao-a** [comment]
After doing a `git fetch origin master`, I can comment
