### ISSUE TITLE
Missing issue view icon

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-pull-request-github#1724]
Issue Type: <b>Bug</b>

Testing https://github.com/microsoft/vscode/issues/96318. 

- drag the Issues view into the activity bar
-> 
![image](https://user-images.githubusercontent.com/4674940/80610118-ceeb4100-89ed-11ea-98fa-21625b10da2c.png)

The view should use the GH issues icon.

Extension version: 2020.4.39782
VS Code version: Code - Insiders 1.45.0-insider (4bd206856db30c27d38aa0f1fbe74bac6156edc7, 2020-04-29T05:31:36.229Z)
OS version: Darwin x64 18.7.0

**Comment by alexr00** [comment]
@sbatten The Pull Requests view has the same problem and it's using the exact same icon as the view container. Are we missing something:
https://github.com/microsoft/vscode-pull-request-github/blob/1f59d962f36b1e20ad447bfd8e3c07d70a3a7c74/package.json#L333-L348

**Comment by alexr00** [comment]
Now that https://github.com/microsoft/vscode/issues/93968 is fixed I've verified that this is working.
