### ISSUE TITLE
Gap between labels in issue preview

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-pull-request-github#1725]
I see this large gap between the two labels

![image](https://user-images.githubusercontent.com/323878/80617641-f949f800-8a07-11ea-8bc9-9589d5560433.png)

`https://github.com/xtermjs/xterm.js/issues/702#issuecomment-539105873`

**Comment by alexr00** [comment]
I had to use SVGs to create the issue labels. It was an ugly work around, but better than not showing labels at all. Now that the labels are done with spans, this is fixed.
