### ISSUE TITLE
Add Out-of-date Branch Workflow: Warning and Update Action

### ISSUE THREAD

**Issue by gi** [microsoft/vscode-pull-request-github#1726]
Situation:
* PR branch is no longer up-to-date with the base branch
* Project requires that PR branches be merged with latest changes

On the website, this warning is shown:
![Screen Shot 2020-04-29 at 10 29 58](https://user-images.githubusercontent.com/7407551/80627740-11138300-89ec-11ea-87ba-5b334590b25d.png)

In the extension, the Description view only shows:
![Screen Shot 2020-04-29 at 10 39 15](https://user-images.githubusercontent.com/7407551/80628094-8f702500-89ec-11ea-8d1d-fe7fb31ae0b7.png)

Side Note:
* If you attempt to click "Merge Pull Request", the error warns about the status checks that fail, but says nothing about the branch being out-of-date.

Feature Request:
* Warn the user if the branch is out-of-date
* Add a button to update the branch with the latest changes from the base branch

**Comment by antonphilin** [comment]
any updates?
