### ISSUE TITLE
Allow to edit the issue title when editing the issue description in the editor

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-pull-request-github#1727]
When editing the description I would also like to have the option to edit the title.

This could be done by a similar convention as for git comment, where the title of the commit message is separated from the body using an empty line.

![image](https://user-images.githubusercontent.com/172399/80646521-2da3cf80-8a6d-11ea-875a-8d2ff53ae913.png)

**Comment by alexr00** [comment]
Already done :)
