### ISSUE TITLE
"Delete Branch" loop

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-pull-request-github#1728]
- Verified https://github.com/microsoft/vscode-internalbacklog/issues/979
- Closed PR
- "Delete branch"
- Accepted the dialog to delete the local and remote branches
- Waited a couple seconds, and the Delete Branch button appears again
- If I click it, it asks to delete the remote branch, I accept it, repeat

![Apr-29-2020 17-56-45](https://user-images.githubusercontent.com/323878/80654989-35e71500-8a43-11ea-9239-f0f5f28db10f.gif)

Linking https://github.com/microsoft/vssaas-planning/issues/2176

**Comment by roblourens** [comment]
And the branch is not deleted on the remote

**Comment by RMacfarlane** [comment]
Anything in the output channel or dev console?

**Comment by roblourens** [comment]
No

**Comment by bamurtaugh** [comment]
@burkeholland Are you able to repro this?

**Comment by bamurtaugh** [comment]
Doesn't seem like this is happening anymore, so going to close this one out.
