### ISSUE TITLE
Line breaks not shown like they are in github

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode-pull-request-github#173]
The below is from the PR extension

![image](https://user-images.githubusercontent.com/16890566/43975285-e8c44446-9c91-11e8-9119-0aa90754cf04.png)

The below is from github

![image](https://user-images.githubusercontent.com/16890566/43975293-efadd312-9c91-11e8-9b37-b555ac2986a9.png)

Observe that after the first sentence, the former has no line break and the latter does

**Comment by RMacfarlane** [comment]
Fixed by https://github.com/Microsoft/vscode-pull-request-github/commit/9baed71f383ee169419c6cbce80cffbbfd13fc7d

**Comment by ramya-rao-a** [comment]
It looks great now

![image](https://user-images.githubusercontent.com/16890566/44177176-87017a80-a0a1-11e8-971f-f05669370da8.png)
