### ISSUE TITLE
No issue suggestions on non-writable repos

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-pull-request-github#1731]
1. Clone repo like https://github.com/egamma/egammaCase
2. In SCM, type `#`. No results
3. Trigger suggestions. Only user Egamma result shows.

**Comment by alexr00** [comment]
This is because there are no issues assigned to you there. Seems like if there are no issues assigned to you, we could use the most recently modified 10 issues or something like that.

**Comment by alexr00** [comment]
Our default issue queries now handle this.
