### ISSUE TITLE
Default issue query should be the actual query

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#1732]
![image](https://user-images.githubusercontent.com/2193314/80746035-10571b80-8ad6-11ea-91cf-0155b59285a3.png)

Can this be `"author:${user}"` or whatever the default is instead?

**Comment by Tyriar** [comment]
Hmm, maybe it's special how it's split up by milestone so this can't be accomplished.

**Comment by alexr00** [comment]
That is correct. Instead of using the `search` GitHub API, it uses a faster (or at least it should be) repository query API.
