### ISSUE TITLE
Cannot read property login of undefined

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-pull-request-github#1735]
- Extension version: 2020.4.42661
- VSCode Version: 1.45.0-insider@a0fe37870c42e0704a492cdc6b8550b4cf23f63c (2020-04-30T05:39:08.281Z)
- OS: Windows_NT x64 10.0.18363

Unfortunately I'm not sure how I got into this state. I updated my settings (to add "githubIssues.ignoreMilestones"), then the Github view (both issues and PRs) blanked out and this error was logged:

![](https://memes.peet.io/img/20-04-445028e1-11ac-47cf-88a3-778738f233bd.png)

I reloaded the window. I was prompted to sign in again. Doing so produced this error:

![](https://memes.peet.io/img/20-04-f9f10a2b-40d5-4785-b814-3b3364256537.png)

But seemed to work -- I could see the issues and extensions. On the third reload, everything was working again.

**Comment by RMacfarlane** [comment]
Hmm!  If you see this again, can you grab the log from the "GitHub Authentication" channel in the output panel?

**Comment by connor4312** [comment]
will do

**Comment by RMacfarlane** [comment]
@connor4312 Have you seen this recently?

**Comment by connor4312** [comment]
Nope, will close
