### ISSUE TITLE
Use a different icon for closed issues in the Issues view

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-pull-request-github#1736]
While testing https://github.com/microsoft/vscode-pull-request-github/issues/1591

I noticed that if I edited the issue query to include closed issues, we don't distinguish those in the issues view. We should use the "closed" icon as appropriate.

![](https://memes.peet.io/img/20-04-606de59d-448c-4019-8ea3-5021894d5c2e.png)

**Comment by alexr00** [comment]
To verify, you can use the `githubIssues.queries` setting to make a query that will show closed issues.
