### ISSUE TITLE
Comment deleted through web UI is not cleared

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-pull-request-github#1739]
- Open file in some PR (I didn't check out the PR)
- Leave a comment
- delete the comment in the browser
- It doesn't disappear from vscode
- Reply to the comment

![image](https://user-images.githubusercontent.com/323878/80829283-744c1380-8bac-11ea-9aec-f135b7cc0bac.png)

**Comment by burkeholland** [comment]
Related: https://github.com/microsoft/vscode-pull-request-github/issues/426

**Comment by alexr00** [comment]
Added a proper error with an option to refresh.
