### ISSUE TITLE
No "outdated" indication for review comments in overview page

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode-pull-request-github#174]
Would be nice to have some indication that a comment is on an "outdated" hunk, likely indicating that the author has already addressed it

**Comment by Tyriar** [comment]
Was about to report this one, it really clutters the PR as an outdated comment typically means it's no longer relevant.

**Comment by Tyriar** [comment]
Duplicate of https://github.com/Microsoft/vscode-pull-request-github/issues/89?
