### ISSUE TITLE
No remote with name 'origin' found. Please update your 'githubPullRequests.remotes' setting.

### ISSUE THREAD

**Issue by Haibao425** [microsoft/vscode-pull-request-github#1743]
- Extension version: 0.15.0
- VSCode Version: 1.44.2 
- OS: 10.15.4

Steps to Reproduce:
1. Private repo.
   Command "git remote -v" shows:
   origin https://xxx.xxxx.com/xx (fetch)
   origin https://xxx.xxxx.com/xx (push)

2. Change settings.json:
    Add:
    "githubPullRequests.hosts": [
         {"host": "https://xxx.xxxx.com/xx"}
    ]

3. Output shows:
[Info] Git repository found, initializing review manager and pr tree view.
[Info] Migrating https://xxx.xxxx.com/xx from githubPullRequests.hosts to keychain
....
[Info] Review> Validate state in progress
[Info] Review> Validating state...
[Info] No remote with name 'origin' found. Please update your 'githubPullRequests.remotes' setting.
[Info] No remote with name 'upstream' found. Please update your 'githubPullRequests.remotes' setting.
[Info] No remote with name 'origin' found. Please update your 'githubPullRequests.remotes' setting.
[Info] No remote with name 'upstream' found. Please update your 'githubPullRequests.remotes' setting.
[Info] No GitHub remotes found
[Info] No GitHub remotes found
[Info] Review> no matching pull request metadata found for current branch master

What should I do?

https://xxx.xxxx.com is the parent folder, it is not a repo, other git extension can recognize all repos in the parent folder, but github pull request extension cannot.

**Comment by RMacfarlane** [comment]
> https://xxx.xxxx.com is the parent folder, it is not a repo,

I'm not sure I understand this, is https://xxx.xxxx.com a github domain?

**Comment by Haibao425** [comment]
> > https://xxx.xxxx.com is the parent folder, it is not a repo,
> 
> I'm not sure I understand this, is https://xxx.xxxx.com a github domain?
https://xxx.xxxx.com is a github domain, but this is private git domain not in github.com, in this domain, we have many project folders, and each folder is a repo.

**Comment by alexr00** [comment]
There have been community improvements to GitHub enterprise since this issue was opened. Please comment if you still see this issue.
