### ISSUE TITLE
Suggest: Rename extension to simply "GitHub"

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode-pull-request-github#1745]
Because the name is so long ("GitHub Pull Requests and Issues"), its the PR and Issue part is lost in the Marketplace:

![image](https://user-images.githubusercontent.com/1487073/80927587-916f1680-8d53-11ea-887c-295d43e5d18c.png)

Suggest to simplify the naming, maybe just "GitHub"

**Comment by alexr00** [comment]
Given that we have a built in GitHub extension in VS Code and we have the Remote Repositories extension, let's keep the long name for now to disambiguate.
