### ISSUE TITLE
Consider refreshing the PR view when a pull request is approved

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#1749]
If I'm going through the "Waiting for my review" query and approving PRs, it would be nice if as I approve them they vanish from that query (which they will do when I click the button to refresh the view).

**Comment by rishab-pdx** [comment]
@RMacfarlane Can I take this? I see that the PR list tree must be refreshed and the PR overview panel must be refreshed if the PR is approved. 
This must be the flow I think

1. When PR is approved refresh the PR list tree to swipe off the approved PRs
2. Disable the Approve button if the PR is/was successfully approved
3. Should the PR overview panel disposed? I think it must not as the reviewer would want to use it to merge the PR. But once approved the Approve button must be disabled.

Let me know your thoughts on it?


![#1749](https://user-images.githubusercontent.com/7886919/82858146-da843780-9ec7-11ea-92a3-61192e25fa27.gif)

**Comment by RMacfarlane** [comment]
@rishab-pdx Yeah, absolutely!

I think 2 is covered by another issue (https://github.com/microsoft/vscode-pull-request-github/issues/473), so I would focus on just making the change for 1 to close this issue. I think leaving the PR overview panel open makes sense, as you say it's likely the user will want to merge the PR after this.

Code pointer: https://github.com/microsoft/vscode-pull-request-github/blob/17575c0978c7400cb00fbe3f7bac8fa422b2ec60/src/github/pullRequestOverview.ts#L582

**Comment by rishab-pdx** [comment]
I did not know about #473. I took off my changes/additions to disable/enable the "Approve" button based on the status of the review move them to another #1833 if required. Let me know.
