### ISSUE TITLE
user completions are rendered differently in the editor and in comments

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-pull-request-github#1750]
user completions in comments:

![image](https://user-images.githubusercontent.com/172399/80975240-1e80a100-8e22-11ea-89d7-80c1ce7efdbc.png)

user completions in the editor

![image](https://user-images.githubusercontent.com/172399/80975378-4f60d600-8e22-11ea-9128-be24ef253525.png)

**Comment by alexr00** [comment]
@RMacfarlane do you like the full name or the username more?

**Comment by RMacfarlane** [comment]
How about username with full name as detail? That would match GitHub most closely:
<img width="290" alt="Screen Shot 2020-05-05 at 9 53 29 AM" src="https://user-images.githubusercontent.com/3672607/81093033-5802ec00-8eb6-11ea-8d0d-13ee61955862.png">
