### ISSUE TITLE
How to reset my GitHub login credentials?

### ISSUE THREAD

**Issue by SawSeeSee** [microsoft/vscode-pull-request-github#1753]
I logged in with my GitHub account A, and I wanna log out and log in with another account. I tried to reinstall this plugin, but it didn't work.

**Comment by RMacfarlane** [comment]
Hey @SawSeeSee, there should be a command `GitHub Pull Requests: Sign out of GitHub` available from the command palette. It can also be accessed by clicking the gear icon on the pull request view:
<img width="666" alt="Screen Shot 2020-05-05 at 9 46 55 AM" src="https://user-images.githubusercontent.com/3672607/81092425-6c92b480-8eb5-11ea-8aa4-28c612c3a5a1.png">

**Comment by RMacfarlane** [comment]
I'm going to go ahead and close this issue. Please let me know if that doesn't work for you.
