### ISSUE TITLE
Add option to filter issues list

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode-pull-request-github#1764]
<img width="50%" src="https://user-images.githubusercontent.com/35271042/81229835-5532f480-8fa5-11ea-8761-f42d3c398ac9.png">

Looking through the sea of text on the issue view, I was scanning for a few keywords on an issue I know I want to start but had a hard time searching for it. Would love to have a quick filter icon to filter the queries, similar to the todo extension:

<img width="50%" src="https://user-images.githubusercontent.com/35271042/81230442-5add0a00-8fa6-11ea-8233-b03b19c4959d.png">

<img width="50%" src="https://user-images.githubusercontent.com/35271042/81229957-86132980-8fa5-11ea-8497-349de8cdd87f.png">

<img width="50%" src="https://user-images.githubusercontent.com/35271042/81230480-6c261680-8fa6-11ea-93ed-96f0489b2be3.png">

**Comment by alexr00** [comment]
@misolori does the usual tree search filter help with this?

**Comment by misolori** [comment]
That helps, though I was thinking more of a permanent one. Since this hasn't received any additional upvotes I'll close. Thanks!
