### ISSUE TITLE
Prompt to commit changes when creating a pull request with no changes

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode-pull-request-github#1765]
![image](https://user-images.githubusercontent.com/35271042/81231236-ae038c80-8fa7-11ea-8927-adbb12ba218a.png)

1. Start working on an issue
2. Start a pull request through the UI (status bar item)
3. :bug: Extension says I have no pending changes

Since I started working on the issue and have pending changes that haven't been committed (i just forgot to commit them), I expected the extension to ask if i wanted to commit the changes currently in staging and then proceed with creating the PR. Otherwise I have to go and commit, then go back through the same process. This would be a cherry on top.

**Comment by alexr00** [comment]
@RMacfarlane I think this makes a lot of sense to have when working on an issue. Is this something you are interested in having for all pull requests, or should I only add it for the "work on an issue flow"?
