### ISSUE TITLE
Comment string creates issue in a different repository

### ISSUE THREAD

**Issue by Randalphwa** [microsoft/vscode-pull-request-github#1768]
- Extension version 0.15.0
- VS Code version 1.44.2
- OS: Windows 10

Description:

I had one file open in Visual Studio Code. I entered a comment using the TODO string, clicked the problem solver and accepted the rest of the string as the issue title. The extension then created an issue in a different repository and updated the issue number in the current comment pointing to the issue in the other repository.

The status line showed the current repository and branch (master in this case). The SCM panel also showed the current file as being in the current repository. The panel also showed two repositories that contained files that I had opened (and closed) while in the current repository.

**Comment by alexr00** [comment]
Was the file you had open in the folder you had open?

**Comment by Randalphwa** [comment]
Yes -- the file that was open was in the root of my $(workspace)/ directory.

**Comment by alexr00** [comment]
Was either repository a fork? Can you share the repository you had open and the repository that the issue was created in?

**Comment by Randalphwa** [comment]
I just tried again with version 16, and the problem persists. This time I
was a bit more careful about the steps in the hopes I can give you a better
repo case.

I opened up a folder in a repository I wanted to change, and opened a file
in that repository. I then opened up a header file in a different
repository, and move that into a split window. I then opened up a different
file in that split window that was in the repository I wanted to change. I
then switched back to the main editor group, and used the status bar to
create a new branch in the repostiory I wanted to change. I then enteired
the line:

// TODO Usage strings should be resources

I clicked the lightbulb on that line and it correctly asked me if I wanted
to create an issue title " Usage strings should be resources ". It then
changed the comment to indicate it was issue #164 -- even though there are
only 26 closed issues and 4 open issues in this repository. I then went out
to GitHub and looked at the second repository and the issue was created
there.

The main repository I was working in is Private, so I can't give you a link
to that. The second repository is public. I will try again using two public
repositories, and if it repos, I will provide both links.

**Comment by Randalphwa** [comment]
Tried in a public repository, problem repros.

ttTrace: https://github.com/KeyWorksRW/ttTrace.git

This contains a submodule called ttLib.

1. Cd to src and run code
2. Open the file ../ttLib/include/ttlibspace.
3. Split the editor so that this file is on the right.
4. In the left editor group open the file traceview.cpp
5. In traceview.cpp, add a // TODO description line
6. Click the lightbulb and create the issue

Result: the issue is created in the ttLib repository at
https://github.com/KeyWorksRW/ttLib.git which is where the ttLib submodule
is pointing to.

Expected: the issue should have been created in the ttLib repository.

Additional notes: SCM shows ttTrace master* and ttLib baa8c88

**Comment by alexr00** [comment]
@Randalphwa thank you for the additional repro steps!
