### ISSUE TITLE
Make current repository more obvious in tree views

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode-pull-request-github#1769]
Currently in the github viewlet, there's no UI indicating what is being used as the repository. This can be confusing for a couple of different reasons - it's not obvious that the pull request searches are going to be done for the repo of the currently open folder, you might think that "Assigned To Me" would be across repos. And it also makes multiroot workspaces hard to work with. Changing the selected repo in the SCM viewlet should update the PR view, but having to switch back and forth between those viewlets isn't ideal.

One simple change would be to update the view or viewlet title to include the repo name. (Though, actually, I don't think this is currently possible, as far as I know the title can only be declared statically in the `package.json`.) So perhaps the tree title?

Another possibility is, in a multiroot workspace, showing the repos at the top level of the trees.

@alexr00 Any thoughts on this?

Extension version: 0.16.0
VS Code version: Code - Insiders 1.45.0-insider (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-06T08:25:01.764Z)
OS version: Darwin x64 18.7.0

**Comment by alexr00** [comment]
I like the idea of having the repo as the view title, but since issue queries can be outside that repo it will still be confusing. We could have another view that shows current information, like repo and user.

**Comment by RMacfarlane** [comment]
Closing this issue, as now the repo is shown within the tree in multiroot workspaces
