### ISSUE TITLE
"Checkout" should be "check out"

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-pull-request-github#177]
The git docs use "check out" except when referring to the command itself: https://git-scm.com/docs/git-checkout

**Comment by rebornix** [comment]
We use `Checkout` in VSCode core, GitHub for Visual Studio is using `Checkout` as well.

@shana may I have your opinion on this?

**Comment by roblourens** [comment]
https://writingexplained.org/checkout-or-check-out I think it's a pretty minor thing but I think `"Git: Checkout to..."` in vscode is also technically wrong.

**Comment by shana** [comment]
Hmmmm, let me see what our style guide says on this...

**Comment by shana** [comment]
So on GitHub we use "check out" as a verb, and only use "checkout" when talking about the command or if talking about a specific feature with that name (like if we named a feature "the checkout button"). I don't know if the VS docs team has different guidelines for that usage tbh.
