### ISSUE TITLE
Avoid showing user cards on module attributes or assigns

### ISSUE THREAD

**Issue by jeroenvisser101** [microsoft/vscode-pull-request-github#1770]
Issue Type: <b>Bug</b>

It should be possible to either disable (for a language) or to scope user hover cards to just comments.

In both Ruby and Elixir, the `@username` syntax is often used to refer to a module attribute or an assign.

Extension version: 0.15.0
VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:07:18.473Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-3245 CPU @ 3.20GHz (32 x 3200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|160.00GB (24.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by alexr00** [comment]
Done!

**Comment by jeroenvisser101** [comment]
Thank you 🙏
