### ISSUE TITLE
Add setting to allow turning off issue triggers

### ISSUE THREAD

**Issue by erihanse** [microsoft/vscode-pull-request-github#1774]
Issue Type: <b>Bug</b>

I tried to remove all the default items in the "Github Issues: Create Issue Triggers" option. Now every line has the option to file an issue on github. Is there a way for us to turn this feature off?

Extension version: 0.16.0
VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:10:24.511Z)
OS version: Linux x64 4.15.0-99-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 3276)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|31.11GB (2.45GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by RMacfarlane** [comment]
This sounds like a bug to me, if the "issue triggers" array is empty we should treat that it as off

**Comment by rishab-pdx** [comment]
@RMacfarlane I have fixed this in #1824. I could not find any test scripts for issueTodoProvider so just tested it manually. Let me know if this could be fixed in a better way. I would like to contribute.
