### ISSUE TITLE
Option to just copy the configured commit message from issues view

### ISSUE THREAD

**Issue by priv-kweihmann** [microsoft/vscode-pull-request-github#1775]
It would be nice to have an extra option beside "Copy ID" and "Copy URL" to copy the configured (by "workingIssueFormatScm") and expanded commit message to clipboard when selecting a single issue in the tree view.
Sometimes I need that information for none git related things and it would save me a few clicks to retrieve that information if the option existed.

**Comment by alexr00** [comment]
Thank you for the feature request but closing as we have no plans to address this issue.
