### ISSUE TITLE
Pull request results changed when navigating to source control tab

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode-pull-request-github#1776]
I had a similar issue. My solution (whilst it may be more luck), was getting into one of my pull requests on Github.com, assigning it to myself then restarting VSCode and they all appeared. I did notice when I moved the Github Extension Icon around on the activity bar, it completely lost all the pull requests and I had to restart VSCode for them to appear again. Not sure what the cause or trigger is.

Edit: Found the trigger. When you have the Pull Requests Github Activity Bar tab open in VSCode, then navigate to the Source Control tab in the Activity Bar, then navigate back to the Pull Requests tab, it'll lose all of the Pull Requests and requires VSCode to restart for them to reappear.

VSCode version: 1.45.0
Github Pull Requests version: 0.16.0
OS: macOS

_Originally posted by @mzavattaro in https://github.com/microsoft/vscode-pull-request-github/issues/1767#issuecomment-625650869_

**Comment by RMacfarlane** [comment]
@mzavattaro Do you have multiple folders open in the workspace? I'm wondering if the folder selection gets changed when you open the source control tab

**Comment by kgorking** [comment]
I have the same issue, as reported in #1757

**Comment by RMacfarlane** [comment]
Closing, as this should be fixed by https://github.com/microsoft/vscode-pull-request-github/issues/1936
