### ISSUE TITLE
API: Cannot sign in with VSCodium URI

### ISSUE THREAD

**Issue by 7automaton** [microsoft/vscode-pull-request-github#1778]
Hello,
I use Codium. The sign in/authentication API prevents me from signing in with Codium's URI, contrary to VS Code's URI. I've already authenticated the plugin with my account here. The API doesn't like the `vscodium://` URI, contrary to the `vscode://` URI, as shown in this GIF:

![vysCCNF8Cp](https://user-images.githubusercontent.com/56928485/81430002-50e11580-9124-11ea-893f-272079a63537.gif)

The API will let me through with the `vscode://` API with an `801` code (I don't have VS Code installed), and it forbids me if I use the `vscodium://` URI with `Forbidden`.

I got to this page from the `GitHub Pull Requests: Sign In` command - it redirected me here from this editor. This is the link to authenticate, with state and windowId redacted:

`https://vscode-auth.github.com/authorize/?callbackUri=vscodium://github.vscode-pull-request-github/did-authenticate%253F...&scope=read:user%20user:email%20repo%20write:discussion&responseType=code&authServer=https://github.com/`

The callback URI differs:
```diff
+ ✔️ (-> 801)       ?callbackUri=vscode://github.vscode-pull-request-github/did-authenticate
- ❌ (-> Forbidden) ?callbackUri=vscodium://github.vscode-pull-request-github/did-authenticate
```

If it helps, I'm using Codium as a portable binary, and I opened the link with it running in the background.
(Also, this shouldn't have anything to do with my container tabs.)

------------------------

Extension version: 0.15.0
VS Code version: VSCodium 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-18T10:22:21.470Z) - portable binary
OS version: Windows_NT x64 10.0.18362
Process Argv: --enable-proposed-api GitHub.vscode-pull-request-github

**Comment by 7automaton** [comment]
I figured out how to workaround this issue.

1. Go to your user settings on github.com, then go into Developer > Personal access tokens.
2. Click "generate new token".
3. Call the token whatever you want, like "VS Codium GitHub Pull Requests plugin token".
4. Check the following boxes: 
![image](https://user-images.githubusercontent.com/56928485/81442786-d9b67c00-9139-11ea-9d80-0fa2e0d872dd.png)
  - user:email
  - user:follow
  - write:discussion
5. Click generate token.
6. Copy the token ID when you're told to, and keep it in your clipboard. Like it says, you won't be able to find it again.
7. Enter VS Codium with the plugin installed. Click the "Sign in" button located on the bottom status bar. If a dialogue opens to redirect you to a website, hit cancel. Then click the sign in button again. A "Token" text field should appear.
8. Paste your token into that text field, and press enter. Then for the host, type github.com.
9. It should authenticate you into the plugin.

**Comment by soszilla** [comment]
After trying your solution this is the response i get from GitHub Authentication Provider: "The input did not matched the expected format".

VSCodium version: 1.45.0
GitHub PullRequests version: 0.16.0

**Comment by zyansheep** [comment]
I also have this problem, is there some way to enter the token manually in a config file or settings? If not, how can I configure the `git` command to use a token for all https requests to github?

**Comment by penyuan** [comment]
I can also confirm this problem as reported by @7automaton and mentioned by @marcorichetta in [this issue](https://github.com/VSCodium/vscodium/issues/401).

**My environment:**
 - OS: RHEL 8.2 (Gnome 3.32.2 in Xorg mode with Linux kernel 4.18.0)
 - Architecture: x86_64
 - VSCodium version: 1.45.0 (no Github extensions, just vanilla git support)

This is a jarring UX problem. How can we help fix it?

**Comment by DanielCostaCarvalho** [comment]
I changed the link:

> https://vscode-auth.github.com/authorize/?callbackUri=vscodium://github.vscode-pull-request-github/did-authenticate%[other parts]
to

> https://vscode-auth.github.com/authorize/?callbackUri=vscode://github.vscode-pull-request-github/did-authenticate%[other parts]
(The callback part from vscodium to vscode)
then a get the link for when you are not redirected:

> vscode://vscode.github-authentication/did-authenticate?[other parts]
and change the vscode part again to vscodium:

> vscodium://vscode.github-authentication/did-authenticate?[other parts]
then I past it in the browser and it works. :)

Sorry for my english. Its a work in progress. Feel free to correct me.

**Comment by penyuan** [comment]
Sorry @DanielCostaCarvalho I don't understand your workaround.

> I changed the link:
> `https://vscode-auth.github.com/authorize/?callbackUri=vscodium://github.vscode-pull-request-github/did-authenticate%[other parts]`

Where do you do this?

> (The callback part from vscodium to vscode) then a get the link for when you are not redirected:

What does this mean?

**Comment by DanielCostaCarvalho** [comment]
When I try to authenticate, I changed the URI like the GIF, but when a changed the mention of vscode, I am redirected to a new page saying that I am not redirected back to the vscode. In this page, they give me a token, this token is a URI that I changed vscode for vscodium and paste it in my browser.

**Comment by soszilla** [comment]
@DanielCostaCarvalho that worked but I had to use a browser session where I was not logged in to Github already.

**Comment by soszilla** [comment]
> Sorry @DanielCostaCarvalho I don't understand your workaround.
> 
> > I changed the link:
> > `https://vscode-auth.github.com/authorize/?callbackUri=vscodium://github.vscode-pull-request-github/did-authenticate%[other parts]`
> 
> Where do you do this?
After clicking "Sign in" from inside vscodium, that link is opened in your browser. Change "vscodium" to "vscode" in the URL and proceed with authorization. 

> 
> > (The callback part from vscodium to vscode) then a get the link for when you are not redirected:
> 
> What does this mean?

After auth you will receive a token in which you should change "vscode" to "vscodium".
Also note my comment above, it might be relevant to you as well.

**Comment by whizzzkid** [comment]
@DanielCostaCarvalho's solution works! This needs to be fixed on https://vscode-auth.github.com/ as it seems to be denying requests for vscodium.

**Comment by penyuan** [comment]
@marcorichetta over in [this issue](https://github.com/VSCodium/vscodium/issues/401#issuecomment-631502370) provided a graphical step-by-step walkthrough of the workaround, and it worked for me. I suspect @DanielCostaCarvalho was describing a similar process, sorry but I just wasn't able to understand the text of their description.

Anyway, I hope this issue can be solved more systematically so that this hacky workaround wouldn't be necessary.

**Comment by han-nes** [comment]
I believe that the authentication process on [https://vscode-auth.github.com/](https://vscode-auth.github.com/) does not allow a `callbackUri=vscodium://`

To get around that, just change that link in your browser to say `callbackUri=vscode://`. When the site is done authenticating, change the callback uri back to what it was and past it into your browser.

<img src="https://user-images.githubusercontent.com/35892607/94937973-91c13880-04d0-11eb-8605-98d176fef59e.png" width="60%"/>

**Comment by alexr00** [comment]
This extension doesn't officially support anything other than VS Code.

**Comment by jtagcat** [comment]
> This extension doesn't officially support anything other than VS Code.

If you are not for it, it doesn't hurt to not be against it.

**Comment by WernerLuiz92** [comment]
> I changed the link:
> 
> > [https://vscode-auth.github.com/authorize/?callbackUri=vscodium://github.vscode-pull-request-github/did-authenticate%[other](https://vscode-auth.github.com/authorize/?callbackUri=vscodium://github.vscode-pull-request-github/did-authenticate%%5Bother) parts]
> 
> to
> 
> > [https://vscode-auth.github.com/authorize/?callbackUri=vscode://github.vscode-pull-request-github/did-authenticate%[other](https://vscode-auth.github.com/authorize/?callbackUri=vscode://github.vscode-pull-request-github/did-authenticate%%5Bother) parts]
> 
> (The callback part from vscodium to vscode)
> then a get the link for when you are not redirected:
> 
> > vscode://vscode.github-authentication/did-authenticate?[other parts]
> 
> and change the vscode part again to vscodium:
> 
> > vscodium://vscode.github-authentication/did-authenticate?[other parts]
> 
> then I past it in the browser and it works. :)
> 
> Sorry for my english. Its a work in progress. Feel free to correct me.

-> Obrigado pela sua ajuda! Isto resolveu o meu problema!
-> Thanks for your help! This solved my problem!

**Comment by GitGangGuy** [comment]
@alexr00 
> This extension doesn't officially support anything other than VS Code.

VSCodium is the Open Source version of Visual Studio Code with slightly differing build instructions.
It is **NOT**:
1) a patchset
2) a fork
3) a different project

Microsoft says they _love_ open source. Are they also willing to back it up by allowing the [open source version](https://github.com/Microsoft/vscode) (which is officially maintained by Microsoft), community-driven binary releases of it (f.e. `code`, available from all kinds of [official FOSS software repositories](https://archlinux.org/packages/community/x86_64/code/))  and [VSCodium](https://vscodium.com/) (a precompiled, binary build of MICROSOFTS OSS Visual Studio Code) to also have access to official integrations, such as the one with GitHub? I think it is unreasonable to treat anything that isn't Microsofts branded proprietary release from their homepage as unsupported.  
  
As a side note, I don't think this is an issue with this extension, but with GitHub not allowing other types of editors to request PAT tokens. Try opening an issue there instead.

**Comment by pmahend1** [comment]
@GitGangGuy So should the extension contributors raise that ticket with Github? 
Would it solve perhaps [if **vscodium** or extension is registered as an OAuth app](https://docs.github.com/en/developers/apps/creating-an-oauth-app)? with supposed application name as `vscodium` and callback URL [vscodium://github.vscode-pull-request-github/did-authenticate](vscodium://github.vscode-pull-request-github/did-authenticate)

Unless these conditions are met OAuth would fail I think.

**Comment by ibrahimaroosi** [comment]
I switch from kali to parrot, then vscodium is pre-installed in it. I cannot even open account option to sign in. Then uninstalled vscodium and installed visual studio code by

sudo apt purge vscode
sudo apt purge vscodium
sudo apt purge codium

I installed VSC in .deb format and installed using

sudo apt install ./filename.deb

It is now working!!!

**Comment by unexploredtest** [comment]
> I changed the link:
> 
> > [https://vscode-auth.github.com/authorize/?callbackUri=vscodium://github.vscode-pull-request-github/did-authenticate%[other](https://vscode-auth.github.com/authorize/?callbackUri=vscodium://github.vscode-pull-request-github/did-authenticate%%5Bother) parts]
> 
> to
> 
> > [https://vscode-auth.github.com/authorize/?callbackUri=vscode://github.vscode-pull-request-github/did-authenticate%[other](https://vscode-auth.github.com/authorize/?callbackUri=vscode://github.vscode-pull-request-github/did-authenticate%%5Bother) parts]
> 
> (The callback part from vscodium to vscode)
> then a get the link for when you are not redirected:
> 
> > vscode://vscode.github-authentication/did-authenticate?[other parts]
> 
> and change the vscode part again to vscodium:
> 
> > vscodium://vscode.github-authentication/did-authenticate?[other parts]
> 
> then I past it in the browser and it works. :)
> 
> Sorry for my english. Its a work in progress. Feel free to correct me.

Thanks! This worked for me

**Comment by qnxdev** [comment]
> > vscode://vscode.github-authentication/did-authenticate?[other parts]
> 
> and change the vscode part again to vscodium:
> 
> > vscodium://vscode.github-authentication/did-authenticate?[other parts]
> 


Callback url dint work on brave worked with firefox

**Comment by adirz** [comment]
Hi, a bit late but maybe someone here can help.
I tried the personal access token solution (it does not give the option to authorize in the website) and nothing happens...
It opens the prompt to write the token, I do, and then nothing, not error message or anything, just nothing.
Anybody know where I can figure out what's wrong?

**Comment by TrainDoctor** [comment]
> Hi, a bit late but maybe someone here can help.
> I tried the personal access token solution (it does not give the option to authorize in the website) and nothing happens...
> It opens the prompt to write the token, I do, and then nothing, not error message or anything, just nothing.
> Anybody know where I can figure out what's wrong?

I've been having the exact same problem with codium. It's absurd that I cannot use an almost identical program to the microsoft distributed version because of their own proprietary nonsense.

**Comment by TylerLeonhardt** [comment]
The root of the issue is that GitHub auth redirects back to the application that started the flow and we can only support redirecting back to products we own. This is for security reasons as arbitrary redirection is a huge security flaw.

That said, GitHub auth has 3 different flows that we take the user through:
- redirection
- redirection a different way
- device code flow

The 3rd, since it doesn't use any redirection whatsoever, should work for codium.

For users of codium, assuming they're on the latest Code - OSS bits, they can click `Cancel` and then `Yes` on the notifications that pop up in codium after codium opens the auth page, and then after that, they should get the device code flow modal and be able to follow the regular steps from there.

For maintainers of codium, you should probably just use this flow in your fork and rip out the rest:

https://github.com/microsoft/vscode/blob/main/extensions/github-authentication/src/githubServer.ts#L198

Or ensure this function returns `false` for codium so it's not taken through the redirection auth:

https://github.com/microsoft/vscode/blob/main/extensions/github-authentication/src/common/env.ts#L7

**Comment by billyjbryant** [comment]
I am using VSCodium and have an entirely different (but similar in nature) issue with sign-in. When I click the "Sign-in" button in the extension, I get an error dialog :

![image](https://user-images.githubusercontent.com/3013565/186501852-34b3518b-6622-468b-8835-dcafed7a76cd.png)

I get no output logs to indicate the nature of the error.

**Comment by TylerLeonhardt** [comment]
@billyjbryant similar to my steps above... in this case, click `Try again?` instead of `Yes` in my steps.

In short, if there's only a Cancel button, click Cancel. If there are 2 buttons, click the non-Cancel button.... until you get the Device Code modal. Then follow that flow.

**Comment by cpascual** [comment]
Update for those using vscodium >=1.71: 
The "device code flow" mentioned in https://github.com/microsoft/vscode-pull-request-github/issues/1778#issuecomment-1218080143 is now the default (no hacking with URLs is needed anymore)

**BUT** I found that adding the PAT fails unless the PAT is created **at least** with the following scopes:
- repo, 
- workflow, 
- read:user, 
- user:email, 
- user:follow, 
- write:discussion

**Comment by cpascual** [comment]
Also, for those using KDE, you may get an error like this after setting the PAT:

"The name org.freedesktop.secrets was not provided by any .service files"

In that case, I confirm that using KeePassXC as a org.freedesktop.secrets provider worked for me. See [these instructions](https://c3pb.de/blog/keepassxc-secrets-service.html)

**Comment by itnishantha** [comment]
Install Codi Extension in VS Code: First, ensure that you have the Codi extension installed. You can find it in the VS Code extension marketplace.
Login Issues with GitHub or Google: If you encounter problems logging in using GitHub or Google, follow these steps:
Open VS Code.
Go to the Extensions view (shortcut: Ctrl+Shift+X).
Search for “Codi” and select the extension.
In the right-side settings panel, look for an option related to authentication or login.
Switch to Pre-Released Version:
Enable the option to switch to the pre-released version (if available).
Wait for the extension to install the pre-released version.
Restart VS Code:
Restart VS Code (or your entire computer if possible).
Login Again:
After restarting, return to the Codi extension.
Click the login button (either with Google or GitHub).
The login process should now work as expected.
Follow Steps 2 and 3 Again:
Once logged in, follow steps 2 and 3 again to switch back to the new release version.
Enjoy Using Codi:
You should now be able to enjoy using the Codi extension in VS Code.
