### ISSUE TITLE
Sometimes pointing subdirectory's git repository, not root directory's.

### ISSUE THREAD

**Issue by tamuhey** [microsoft/vscode-pull-request-github#1780]
- Extension version: 0.15.0

About vscode:

```
Version: 1.44.2
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T17:07:18.473Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0
```

Steps to Reproduce:

1. clone the repository: https://github.com/PKSHATechnology-Research/camphr
2. open with `$ code camphr`
3. create new issue via `quick fix`
4. **sometimes** opened new issue in another repository of subdirectory (It does **not always**)

**Comment by RMacfarlane** [comment]
This should be fixed as part of https://github.com/microsoft/vscode-pull-request-github/issues/1936
