### ISSUE TITLE
Permalink should use the upstream repo if possible

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#1781]
I copied the permalink to paste into github but it ended up using my fork which doesn't show the preview, it should have been xtermjs/xterm.js instead:

![image](https://user-images.githubusercontent.com/2193314/81475048-69057300-91be-11ea-8294-848103c7b3af.png)

I guess it should do this naively if the latest commit _for the file_ exists in upstream?

**Comment by alexr00** [comment]
Agree. Forks in general aren't really supported at the moment.

**Comment by bveeramani** [comment]
Hey, I'm running into this issue where the permalink uses my fork rather than upstream. Do I need to configure something to make this work?

**Comment by Tyriar** [comment]
I also still see this in Tyriar/xterm.js

**Comment by alexr00** [comment]
It's still working, but you need to have done `git fetch upstream main` (or equivalent for your setup) at some point such that your local copy of the upstream (forked from) main branch contains the commit at the head of the branch that you currently have checked out. Without this, we don't have the information required to know if your current head commit is actually available in the upstream repo.
