### ISSUE TITLE
Dozens of issues showing that are not from my repo, no issues from my repo are showing

### ISSUE THREAD

**Issue by ericblade** [microsoft/vscode-pull-request-github#1784]
- Extension version: 0.16.0
- VSCode Version: 1.45.0
- OS: Win 10 2004

Steps to Reproduce:

1. Open a folder that currently contains a checkout of https://github.com/ericblade/quagga2
2. Switch to the Github Pull Requests and Issues view

Results:
![image](https://user-images.githubusercontent.com/1451847/81492591-0320f600-9267-11ea-9a1f-645d11fcd7cd.png)

None of these issues are from my github, they appear to be selected mostly at random, all but the first few with the same title are from different repos.   Refreshing does not make any change.  

I have no idea what other information I can provide to help diagnose, sorry.

**Comment by ericblade** [comment]
This has gone away now, I'm not sure if it was fixed in the point release of VSC, or if github fixed something, or if it was just some kind of transient error.

**Comment by ericblade** [comment]
Re-opening it, as the issue has resumed happening.

Am I the only person this is happening to? o.O

**Comment by alexr00** [comment]
Do you have the setting `githubIssues.queries` set?

**Comment by ericblade** [comment]
I do not.  I just upgraded to the latest VSC that came out yesterday/today, and it's getting stranger.  Now most of my repos have a completely empty github view, even the Pull Requests side never populates, even though it should have a bunch of drop down thingees, even if there's nothing in them.  

On this particular repo, though, it works -- but it's now giving me a completely different set of issues.  

In attached screenshot, pull reqs are from this repo, but the issues appear to be taken from a completely random set of repos.  Every one of them is from a different repo, there's not a pile of duplicates from the same, like there were last week when i looked.

![image](https://user-images.githubusercontent.com/1451847/84368201-442c6300-aba3-11ea-968b-119901441a36.png)

**Comment by alexr00** [comment]
That isn't how the default task query should look. It groups issues by Milestone. Can you share your all your settings.json?

**Comment by ericblade** [comment]
sure, this is the user settings.json

````
{
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\cmd.exe",
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "workbench.colorTheme": "Visual Studio Dark",
    "git.autofetch": true,
    "enableTelemetry": false,
    "editor.minimap.enabled": false,
    "files.trimFinalNewlines": true,
    "files.trimTrailingWhitespace": true,
    "trailing-spaces.trimOnSave": true,
    "editor.fontFamily": "Fira Code, Consolas, 'Courier New', monospace",
    "editor.fontLigatures": true,
    "editor.fontSize": 13,
    "[html]": {
        "editor.defaultFormatter": "vscode.html-language-features"
    },
    "cSpell.userWords": [
        "ATVPDKIKX",
        "UPCE",
        "babel",
        "barcodes",
        "camelcase",
        "coalescing",
        "datapoints",
        "ericblade",
        "grayscale",
        "nullish",
        "operator",
        "plugin",
        "precoverage",
        "proposal",
        "quagga",
        "snyk"
    ],
    "javascript.updateImportsOnFileMove.enabled": "always",
    "remote.SSH.remotePlatform": {
        "arcade.lan": "windows"
    },
    "eslint.lintTask.enable": true
}
````

The workspace settings.json is empty.

**Comment by alexr00** [comment]
I still can't reproduce what you're seeing. If you open the Source Control view, how many repos does it say you have open (screen shot would be good)? I opened a clone of the repo that you link in the original post, and this is what I see:
![image](https://user-images.githubusercontent.com/38270282/84489032-5c82a780-aca1-11ea-952b-bdab6ebb25c6.png)

**Comment by ericblade** [comment]
The Issue list here is now back to identical to what it was the first time I posted. :-S  Is your screengrab there correct?  Is "Created Issues" supposed to contain any open issues in the repo, or only things that You have created?  If the former, there should be some 38 or so visible issues.  

I'm not sure what view it is you're wanting a capture of -- I'm not aware of any views that show the information you're asking for, or exactly what information it is you're asking for, really.  
The Source Control view only shows me a list of files with changes -- there are none

![image](https://user-images.githubusercontent.com/1451847/84553901-852b9100-ace3-11ea-9cdc-076772966042.png)

For all of my other code repos, the extension simply displays absolutely nothing -- completely empty on Pull Reqs and Issues.  This is the only one I've got where it displays anything, and it's the wrong information.

**Comment by alexr00** [comment]
When you have files from different repositories open, the Source Control viewlet will have two views: the one that you have a screenshot of (thanks, that's what I needed), and list of all the repositories you have opened (clearly not visible on yours indicating that you only have one repo open). 

The default queries for the issues view are My Issues (issues that are assigned to you in the current repository, there are none for me in your repo), and Created Issues (issues that _you_ created in the current repository, there are none from me in your repo).  I have no explanation as to why you don't even see the My Issues and Created Issues headers.

Can you run the Developer: Toggle Developer Tools command and see if there's anything in the console there? Do you have any ideas as to what may be different or unexpected about your setup?

**Comment by ericblade** [comment]
... i really don't know ... but it does look like the brand new release today seems to have solved it, this repo, as well as the other two i have open right now, are all working as expected.  previously, none of them did.

**Comment by alexr00** [comment]
> an option quickly available to display all issues

You can always set `"githubIssues.queries"` to include all issues if the default queries don't work for you.

**Comment by Mr-Pepe** [comment]
I originally used the following queries:

``` 
    "githubIssues.queries": [
        {
            "label": "My Issues",
            "query": "default"
        },
        {
            "label": "All Issues",
            "query": "state:open repo:${owner}/${repository} sort:created-desc"
        }
    ],
```

But that didn't yield any results for [my repo](https://github.com/Mr-Pepe/stroke-order-animator) (for neither of the queries), although there is one open issue created by me. 

When I remove the `repo` filter I suddenly get many issues from random repositories as results for the "All Issues" query. When explicitly  using `repo:Mr-Pepe/stroke-order-animator` I get the desired outcome. 

Looks like the variables are not correctly set somehow!?

I start the editor with `code --enable-proposed-api GitHub.vscode-pull-request-github`.
