### ISSUE TITLE
Notification showing copied to clipboard

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-pull-request-github#1787]
![image](https://user-images.githubusercontent.com/10746682/81565305-66ab4080-9399-11ea-99bb-b15438a6322b.png)

**Comment by alexr00** [comment]
@sandy081 you just want the notification to be removed?

**Comment by sandy081** [comment]
Sorry I thought I mentioned in the description.

yeah, I felt it is too obvious and noisy.

**Comment by alexr00** [comment]
You're not the first person to say that. I'll remove it.
