### ISSUE TITLE
Can't checkout PRs with a slash

### ISSUE THREAD

**Issue by travisgroth** [microsoft/vscode-pull-request-github#1789]
- Extension version: 0.16.0
- VSCode Version: 1.45.0
- OS: OSX

Steps to Reproduce:

1. Create a PR from a branch with a `/` in the name, eg `feat/myfeature`
2. Attempt to checkout the PR with this extension

This results in an error message and fails to check out the branch:

```
[Info] PullRequestGitHelper> Fetch tracked branch refs/remotes/upstream/feat/myfeature
[Info] Review> checkout failed #{"message":"Failed to execute git","stdout":"refs/remotes/upstream/feat/myfeature\n","stderr":"fatal: ambiguous argument 'refs/remotes/upstream/feat/myfeature': unknown revision or path not in the working tree.\nUse '--' to separate paths from revisions, like this:\n'git <command> [<revision>...] -- [<file>...]'\n","exitCode":128,"gitCommand":"rev-parse"}
```

**Comment by travisgroth** [comment]
Hi - any feedback on this?  Having a `/` in a branch name is pretty common.

**Comment by travisgroth** [comment]
This also happens with dashes:

```shell
> git rev-parse pr/rspier/146-3
fatal: ambiguous argument 'pr/rspier/146-3': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

**Comment by burkeholland** [comment]
Found in https://github.com/microsoft/vssaas-planning/issues/1529

**Comment by bamurtaugh** [comment]
Linking https://github.com/microsoft/vssaas-planning/issues/2176

**Comment by RMacfarlane** [comment]
I'm not able to reproduce this, what version of git are you using?
