### ISSUE TITLE
VS Code java editing and debugging

### ISSUE THREAD

**Issue by ryanmunene79** [microsoft/vscode-pull-request-github#1797]
I have been using vs code for sometime now and lately or maybe I didn't notice before but whenever I open a page *.java or java related a new jvm instance is created. This becomes a problem as its not managing its sessions as when I close the tabs the jvm(s) are still running. Attached screenshots
![Screenshot from 2020-05-13 02-42-20](https://user-images.githubusercontent.com/15321831/81755999-3069e000-94c3-11ea-9ae1-3b91614d0bbc.png)
![Screenshot from 2020-05-13 02-49-38](https://user-images.githubusercontent.com/15321831/81756029-3eb7fc00-94c3-11ea-95ea-99819ff08832.png)

**Comment by RMacfarlane** [comment]
Hey @ryanmunene79, it looks like you may have opened this issue on the wrong extension - did you mean to open this on the java extension?

**Comment by ryanmunene79** [comment]
yes

**Comment by RMacfarlane** [comment]
Ok, I'm going to go ahead and close this then.
