### ISSUE TITLE
Can't stop work or start work on a different issue

### ISSUE THREAD

**Issue by ermshiperete** [microsoft/vscode-pull-request-github#1799]
Issue Type: <b>Bug</b>

I was able to start working on an issue which created a branch and displays the checkmark in front of the issue.

However, I'm not able to stop work or start to work on a different issue. Trying those options simply do nothing.

I haven't tried what happens if the issue gets closed, but it should be possible to switch work on issues before that.

Extension version: 0.16.0
VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:10:24.511Z)
OS version: Linux x64 5.3.0-51-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 4075)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|31.26GB (3.68GB free)|
|Process Argv|. --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by b3u** [comment]
Does #1785 describe your bug?

**Comment by ermshiperete** [comment]
yes, this seems to be a duplicate of #1785 .
