### ISSUE TITLE
View commits in pull request rahter then merging all changes

### ISSUE THREAD

**Issue by pbrezina** [microsoft/vscode-pull-request-github#1809]
I'd like to go through commits in PR one by one instead of seeing all updated files with final diff.

**Comment by pbrezina** [comment]
E.g. what `tig` does.

**Comment by RMacfarlane** [comment]
Hey @pbrezina, this is currently possible if you click the "Checkout" button on a PR. This adds a new view which has a list of all commits and their diffs:
<img width="303" alt="Screen Shot 2020-05-15 at 6 18 06 AM" src="https://user-images.githubusercontent.com/3672607/82054479-dd835a80-9673-11ea-97f5-8202f3fdbc6e.png">
