### ISSUE TITLE
Show hover cards when issue numbers are followed by `)`

### ISSUE THREAD

**Issue by ScottTodd** [microsoft/vscode-pull-request-github#1813]
We'd like to have code comments like `// TODO(#123456)`, but a trailing space (or other whitelisted character) is needed for the hover cards to appear, like `// TODO(#123456 )`.

Looks like `\)` could be added to the final capture group here: https://github.com/microsoft/vscode-pull-request-github/blob/74e02d29f31fed271d46682a5651e2ff143c35a3/src/issues/util.ts#L16

Not sure if there are other usage patterns that would be false positives with that character allowed.

**Comment by GMNGeoffrey** [comment]
Perhaps the final capture group be broadened to just be a word boundary (`\b`)?

**Comment by GMNGeoffrey** [comment]
@alexr00 can you comment on whether this would make sense (either adding `\)` or replacing the whole thing with `\b`)?

**Comment by alexr00** [comment]
I added `)` to the expected characters in the regular expression.

**Comment by GMNGeoffrey** [comment]
Thanks!
