### ISSUE TITLE
Allow specifying a different repo for issue tracking

### ISSUE THREAD

**Issue by danhalson** [microsoft/vscode-pull-request-github#1819]
I'm currently working on a codebase where there's one repo for issues and another for code, this is to aid in separating concerns as far as I understand it. So I'm wondering if it would be a useful feature for others as well as myself to be able to optionally specify a different repo to use for issues. I expect this kind of use case isn't entirely uncommon on Github? however I'll happily stand corrected if it is. Thanks.

**Comment by levitate-chris** [comment]
@danhalson I am in a similar situation.  I just realized if you can put `repo:myApp/nameOfRepo` in the query.  I use my PR/code repo for PR queries and issue tracking repo for my issue queries.

**Comment by danhalson** [comment]
Thanks @levitate-chris this has solved the issue for me, I guess just a mention of this in the docs could be handy?

**Comment by danhalson** [comment]
Actually it is referenced in the query syntax link. Will close.
