### ISSUE TITLE
Activating extension fails with the following error - Activating extension 'GitHub.vscode-pull-request-github' failed: command 'github.publish' already exists.

### ISSUE THREAD

**Issue by rishab-pdx** [microsoft/vscode-pull-request-github#1821]
- Extension version: 0.16.0
- VSCode Version: 
VSCode insiders  
Version: 1.46.0
Commit: Unknown
Date: Unknown
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

- OS: Mac OS X Catalina 10.15.4

I am trying to set up and try out the extension. I would like to build it on my machine, try it out and debug with VSCode insiders, and extension fails to get activated as shown in the image. It works without any errors on normal VSCode build but fails on insiders build.

Am I missing anything here when I'm trying to setup?

Steps to Reproduce:

1. Setup VSCode Insiders from main [repo](https://github.com/microsoft/vscode)
2. Add extensions from the marketplace
3. I get the following error

<img width="1552" alt="Screen Shot 2020-05-19 at 10 02 55 PM" src="https://user-images.githubusercontent.com/7886919/82406854-85a27600-9a1c-11ea-8542-dbee39ebbe0e.png">

Do we have to use the nightly build of extension when working with insiders? vscode-pull-request-github-insiders gets activated without any errors.

**Comment by rishab-pdx** [comment]
Do we have to use the nightly build of extension when working with insiders?

**Comment by RMacfarlane** [comment]
No, the stable extension is expected to work in insiders, this is a bug.

We moved some of the functionality of the extension (specifically the `github.publish` command) into the core of vscode. The nightly build of the extension has this command removed, but the stable one doesn't, so the command is duplicated. I'll remove it from stable and publish a new version. Thanks for catching this!

**Comment by rishab-pdx** [comment]
Thanks for the update! I would like to take up this. Can I have some code pointers? I tried debugging it but couldn’t find the origin of the bug.

**Comment by RMacfarlane** [comment]
Thanks for the offer to help! 🙏 I actually just published a new version of the extension - there weren't any additional code changes, I just moved the commit that removes `github.publish` to our release branch.

It's this branch if you're curious: https://github.com/microsoft/vscode-pull-request-github/tree/release/0.16

**Comment by rishab-pdx** [comment]
Oh, gotcha!
