### ISSUE TITLE
Can't add a comment

### ISSUE THREAD

**Issue by MFAshby** [microsoft/vscode-pull-request-github#1825]
Issue Type: <b>Bug</b>

1. Checkout large pull request (~150 files)
2. In _some_ files I'm able to add comments on additions by clicking in the gutter. 
3. Other files don't allow me to, I get no indicator when hovering and clicking does nothing (see screenshot)

![image](https://user-images.githubusercontent.com/1760515/82438447-f97e6600-9a90-11ea-8eef-f5631a9fe703.png)

Extension version: 0.16.0
VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:22.494Z)
OS version: Linux x64 5.4.0-31-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 4299)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|31.31GB (0.25GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by alexr00** [comment]
Please comment if this issue is still occurring! Closing as some GitHub limits have been increased.
