### ISSUE TITLE
Issue description preview should more closely match the web UI

### ISSUE THREAD

**Issue by tetchel** [microsoft/vscode-pull-request-github#1827]
When I view an issue description in the hover preview, it jumped out to me that the comment at the top of the issue was shown. Since issues opened using templates (like this one!) often have comments at the top, I expect this will be seen relatively often. 

I also noticed that in the preview the newlines are not rendered (I guess you'd need `<br>`s).

![image](https://user-images.githubusercontent.com/8888438/82708290-e1067b00-9c4b-11ea-9c32-dafe475167cb.png)

vs. what I see in the web UI:
![image](https://user-images.githubusercontent.com/8888438/82708454-4e1a1080-9c4c-11ea-8bcc-db402f68571c.png)

**Comment by alexr00** [comment]
@tetchel this should already be fixed in the nightly build of the extension. Comments in the issue body are not shown.
