### ISSUE TITLE
[Remote] Blank Pull Request view

### ISSUE THREAD

**Issue by tfenster** [microsoft/vscode-pull-request-github#1835]
- Extension version: 0.16.1
- VSCode Version: 
```
Version: 1.46.0-insider (user setup)
Commit: da98a19a5d6724367bd99c8ec3b8f55054be37d1
Date: 2020-05-20T22:21:02.272Z
Electron: 8.3.0
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Windows_NT x64 10.0.19041
```
- OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Open a remote SSH development workspace (client and host are Windows)
2. Create a pull request --> works
3. Open the pull request --> blank page
![image](https://user-images.githubusercontent.com/15346084/83043077-b436d700-a042-11ea-9e33-4c8621fed303.png)

Webview developer tools show the following:
![image](https://user-images.githubusercontent.com/15346084/83043180-d4ff2c80-a042-11ea-848f-ba955fc6d2a0.png)

Please let me know if you need anything else

**Comment by mjbvz** [comment]
I believe this is the same issue as https://github.com/microsoft/vscode/issues/98768

**Comment by jasonwilliams** [comment]
im getting this on WSL

```
TreeError [pr:github] Data tree node not found: [object Object]: Error: TreeError [pr:github] Data tree node not found: [object Object]
```

**Comment by tfenster** [comment]
seems to be fixed for me
