### ISSUE TITLE
Allow use of org keyword in queries

### ISSUE THREAD

**Issue by davidanthoff** [microsoft/vscode-pull-request-github#1839]
It would be very convenient if one could query for PRs that are outside of the current repo, say all PRs in a given organization.

One way to implement this would be that if the `org:` search keyword is used in a query, it would search all repos in that org.

**Comment by rmariuzzo** [comment]
Yes, that would be very convenient when we work across several repos at once.

**Comment by alexr00** [comment]
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/1458
