### ISSUE TITLE
Missing 'Issues' viewer

### ISSUE THREAD

**Issue by sacredvoid** [microsoft/vscode-pull-request-github#1841]
- Extension version: 0.14.0
- VSCode Version: 1.42.1
- OS: macOS Catalina 

Steps to Reproduce:

1. After installing the extension, it's just showing me the PRs not the Issues unlike on my Ubuntu Laptop which is running 0.16.0 version of the extension. 

Has the issues viewer not yet been rolled out for MacOS?
<img width="1440" alt="Screenshot 2020-05-30 at 10 12 19 AM" src="https://user-images.githubusercontent.com/33939902/83319676-2800fb80-a25e-11ea-9805-d43aa89300eb.png">

**Comment by RMacfarlane** [comment]
@sacredvoid This is available in version 0.16 of the extension, please update your version of VSCode to get it. Thanks!
