### ISSUE TITLE
0.16 repeatedly prompts me to sign in

### ISSUE THREAD

**Issue by RikkiGibson** [microsoft/vscode-pull-request-github#1846]
Issue Type: <b>Bug</b>

When I upgraded the extension version to 0.16, the Pull Requests sidebar kept prompting me to sign in. Each time I sign in, it works for a while, but later on the pull requests list will be replaced again with the "sign in" button. The problem doesn't seem connected to restarting VSCode or not, it just seems to happen after a few hours have passed. This didn't happen in 0.15, and actually downgrading the extension version to 0.15 seems to fix the problem. Any ideas on how I can troubleshoot this?

Extension version: 0.16.0
VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3793)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (19.70GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/rikki/src/roslyn|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by RikkiGibson** [comment]
This is still present in 0.17.

**Comment by RikkiGibson** [comment]
I'm still experiencing this bug. Is there any additional diagnostic information I can furnish or troubleshooting steps I should try which would be helpful?

Since others do not seem to be +1ing this bug, I wonder if this is an uncommon scenario and I should just flatten and reinstall VS Code. It might be due to installing a locally-built 0.16 before installing the official build of 0.16.

**Comment by DaloLorn** [comment]
A year later, I've got a similar issue. Every time I open a repository, I'm asked to sign into GitHub again.

Extension version: 0.29.2
VSCode version: 1.59.0 (commit 379476f, updated 1 week ago)
OS: Win10 64-bit, version number 10.0.19043

**Comment by alexr00** [comment]
Can you share the logs from "GitHub Pull Request" and "GitHub Authentication"?
