### ISSUE TITLE
Publish to github: do not ask me which folder if only one has git

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-pull-request-github#1852]
Have a MR workspace with 2 folders
First folder has git initialised
Second folder does not

Click on the Publish to GitHub action in the status bar
I get asked which folder to publish. I think we should assume the one which has git initialised.

**Comment by joaomoreno** [comment]
Not really since you can publish either folder. Is having a git repo a better indicator of which folder the user will pick? Maybe... but both options should still appear.

**Comment by isidorn** [comment]
Well then you can argue that this status bar should appear also for folders that do not have git initialised.
