### ISSUE TITLE
Comment ranges expand and allow adding comments to unsaved changes

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode-pull-request-github#186]
![comment_range](https://user-images.githubusercontent.com/3672607/44066157-af551534-9f23-11e8-8437-60380262bb19.gif)

**Comment by RMacfarlane** [comment]
With https://github.com/Microsoft/vscode/commit/22ab03e7a4dcb975d24d174a8b842526840e54d2, the line decorations no longer move, but the new lines are still part of the commenting range. I think the correct behavior would be for the commenting range to actually get split in this case, which would be a more involved change

**Comment by alexr00** [comment]
Not entirely sure what this issue is about. Closing, as it can't actually be important if it's been sitting around for 5 years.
