### ISSUE TITLE
Suppress the error message "The remote '...' is not a GitHub repository"

### ISSUE THREAD

**Issue by tamuhey** [microsoft/vscode-pull-request-github#1863]
same error msg as #1610, but different issue.

I use my repo with multiple remote repositories, and one of these is not github. 
So this extension shows `"The remote '...' is not a GitHub repository"`, but I want to suppress the message.

**Comment by kamenminkov** [comment]
Similar scenario for me (`origin` is a GitLab repo and two other remotes are GitHub repos), would like to see that option as well.

**Comment by jkoritzinsky** [comment]
This is very annoying since it continually blocks visibility of the integrated terminal in the default VSCode view layout and shows back up after dismissal very quickly.

**Comment by ben181231** [comment]
+1

**Comment by CrazyIvan359** [comment]
+1 on this, anyone else also having problems where the issues and PRs in the github repo are not being displayed by the extension?

**Comment by ashuvssut** [comment]
I too have this annoying pop up coming up       : \

**Comment by mdgeus** [comment]
Make it optional to display this warning, please

**Comment by KaiSforza** [comment]
It doesn't even make sense for me, since you can set `githubPullRequests.remotes`, but it doesn't seem to respect this setting at all. I have a github remote in `origin` and a gitlab remote in `gitlab`, but it complains about the `gitlab` remote even though it's not set to look there.

**Comment by EppO** [comment]
It's supposed to be fixed by #2296 but I still experience the issue with 0.21.4. Here is a screenshot when I browse code from a GitLab repo

![Screen Shot 2020-12-11 at 10 19 21](https://user-images.githubusercontent.com/6111/101921175-b1dd3a00-3b9a-11eb-9dc8-168f8a296045.png)

**Comment by RMacfarlane** [comment]
This change hasn't been released yet, we were waiting on the next version of VSCode to ship. I'll start preparing a new release that includes this change now! Thanks!

**Comment by RMacfarlane** [comment]
Version 0.22.0 has been released
