### ISSUE TITLE
PR comment experience is *really* bad (when checked out branch is stale?)

### ISSUE THREAD

**Issue by AArnott** [microsoft/vscode-pull-request-github#1864]
- Extension version:
- VSCode Version:
- OS:

Steps to Reproduce:

1. Review https://github.com/NuGet/NuGet.Client/pull/3420 using a Codespace
1. Checkout the PR branch in the codespace.
1. Maybe leave a comment ("Start a Review").
1. Come back later, after the PR author has pushed to their source branch. (I think this is very important)
1. Open your PR codespace and try to leave comments, start or finish a review.

For me now this part of it no longer repros, but what I saw yesterday was that when I added a comment and clicked Add Comment or Start Review, it would briefly show saved, and then the comment would go back into Edit mode. At this point if I hit Save, the comment would be _duplicated_, as a comment on my own comment. If I click Cancel instead on that edit field, my comment remains as just one. 
But now this isn't happening. Maybe it's because the PR hasn't been pushed by the author lately, or maybe that isn't the critical part of the repro at all.
Yesterday when this repro'd, after all the struggle I eventually completed my review, and less than half of my comments actually showed up on the PR (and the missing ones had vanished from the Codespace too) so I had to rewrite them!

But here's a more consistent problem that I can still repro:
I've finished writing comments, and I used Start Review for the first one and Add Comment for the rest. **How in the world do I actually commit and publish my comments??** I don't see a "Complete Review" or "Publish Comments" button or command anywhere in the UI within the Codespace, although I do see my draft comments show up in the standard github PR web page and can publish from there.

**Comment by AArnott** [comment]
This is happening again!

**Comment by AArnott** [comment]
My codespace was created, and leaving a review comment was fine. But then the PR was pushed to, and now no comment I leave from my web-based Codespace is actually persisted.
Once I manually execute `git pull` within the codespace, my comments magically persist again.

**Comment by RMacfarlane** [comment]
Steps to verify fix:
1. Checkout a PR in the extension
2. Use GitHub web UI to make some edits to the PR and push a new commit
3. Back in extension, make a comment on the PR

The comment should be submitted with the commit id that the PR was checked out with
