### ISSUE TITLE
Validation failed creating an issue

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-pull-request-github#1868]
Testing https://github.com/microsoft/vscode-pull-request-github/issues/1857 I got an issue "validation failed"

![](https://memes.peet.io/img/20-06-08741ce5-52c3-40d6-86f6-9019415c60a3.png)

I might have messed up, but

 1. I don't know what I messed up
 2. The issue closed before this came up, and the text of the issue is lost; probably we should not close the issue 'file' until it's successfully posted

edit: looks like my sign in might have expired, I noticed in the view I am currently logged out

**Comment by alexr00** [comment]
Example of new error message:
Creating issue failed: Validation Failed: Value notauser cannot be set for field assignees (code: invalid)
