### ISSUE TITLE
Should we cache assignable users?

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-pull-request-github#1869]
I notice while looking at https://github.com/MicrosoftDocs/live-share/issues/3612 that vscode was making a bunch of requests to Github looking for assignable users over the span of a few minutes

![](https://memes.peet.io/img/20-06-a3b47b83-8cd0-4dec-8252-d7561d861d82.png)

It looks like these were paging through assignable users. I wonder whether we should cache these to avoid hitting the Github API each time we boot.

**Comment by alexr00** [comment]
Instead of caching, let's just wait until we actually need the users to get them, and then, only get them once per session.
