### ISSUE TITLE
Sign-in/Authentification failure

### ISSUE THREAD

**Issue by jacksonf21dev** [microsoft/vscode-pull-request-github#1876]
Everything seems to work until I get back to vscode itself. I get two error messages in the bottom-right corner of vscode. It is entirely possible that I am just doing something completely wrong, but either way I appreciate any help. I've been frustrated with this issue as I'm just getting started with learning Git and Github. I've included a picture of the error messages.
<img width="1280" alt="Screen Shot 2020-06-06 at 8 38 31 PM" src="https://user-images.githubusercontent.com/63982206/83958415-07750a80-a837-11ea-9fe2-3858699b8ac4.png">

- Extension version: 0.16.0
- VSCode Version: 1.45.1
- OS: MacOS High Sierra 10.13.6

Steps to Reproduce:

1. Click sign-in under pull requests on Github left side bar.
2. Successfully sign-in to Github on the browser.
3. Click to be redirected to vscode where error messages are encountered.

**Comment by RMacfarlane** [comment]
Hey @jacksonf21dev! Do you remember how you installed `git`? From the error message, I think this error is because of a configuration problem with your system, but not exactly sure what. https://stackoverflow.com/questions/43244071/ssl-unable-to-get-local-issuer-certificate might be relevant.

Can you also change the dropdown in the Output panel to "GitHub Authentication" and report what is in the log there?

**Comment by Obinnabii** [comment]
my sign in is missing

**Comment by jacksonf21dev** [comment]
Hi @RMacfarlane, thanks for your help! I believe I installed git with Homebrew. The curious part is that git works just fine through the terminal on my Mac, just not while attempting to login to Github through VSCode. In other words, unlike the question posed in https://stackoverflow.com/questions/43244071/ssl-unable-to-get-local-issuer-certificate I don't receive any error message using Git in the Mac terminal.

Here's the output from the "Github Authentication" log: 
------
[Info  - 03:22:20.241] Logging in...
[Info  - 03:22:24.617] Exchanging code for token...
[Error  - 03:22:24.814] Error: unable to get issuer certificate
------

**Comment by alexr00** [comment]
@TylerLeonhardt do those "GitHub Authentication" logs indicate a specific problem to you?

**Comment by TylerLeonhardt** [comment]
@jacksonf21dev are you behind a proxy in your organization? Can you try some of these troubleshooting steps?
https://code.visualstudio.com/docs/setup/network#_ssl-certificates

**Comment by RandomNoun7** [comment]
Hi. I'm not behind a firewall or proxy, and I know my git configuration works (at least from the commandline). My org uses OAuth so I had to authorize my ssh key, but that's been completed and everything but the extension works fine now. Pasting the log output below.

```
[Debug 1639157961.285s] Error signing in to GitHub: HttpError: Bad credentials
[Debug 1639157961.285s] HttpError: Bad credentials
	at c:\Users\Bill Hurt\.vscode-insiders\extensions\github.vscode-pull-request-github-0.35.2021121012\dist\extension.js:1063:23870
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async Wm.setCurrentUser (c:\Users\Bill Hurt\.vscode-insiders\extensions\github.vscode-pull-request-github-0.35.2021121012\dist\extension.js:1081:17701)
	at async Wm.createHub (c:\Users\Bill Hurt\.vscode-insiders\extensions\github.vscode-pull-request-github-0.35.2021121012\dist\extension.js:1081:18534)
	at async Wm.login (c:\Users\Bill Hurt\.vscode-insiders\extensions\github.vscode-pull-request-github-0.35.2021121012\dist\extension.js:1081:16809)
	at async dp.authenticate (c:\Users\Bill Hurt\.vscode-insiders\extensions\github.vscode-pull-request-github-0.35.2021121012\dist\extension.js:1163:16015)
	at async c:\Users\Bill Hurt\.vscode-insiders\extensions\github.vscode-pull-request-github-0.35.2021121012\dist\extension.js:1163:6176
	at async r._executeContributedCommand (c:\Users\Bill Hurt\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:95:31072)
```

**Comment by RandomNoun7** [comment]
Also got this from GitHub Authentication.log

```
[Info  - 17:39:02.420] Reading sessions from keychain...
[Info  - 17:39:03.86] Getting sessions for user:email...
[Info  - 17:39:03.86] Getting sessions for all scopes...
[Trace  - 17:39:03.97] Token acquired from secret storage.
[Info  - 17:39:03.97] Got stored sessions!
[Trace  - 17:39:03.97] Read the following session from the keychain with the following scopes: read:user,user:email,repo
[Trace  - 17:39:03.98] Read the following session from the keychain with the following scopes: repo
[Trace  - 17:39:03.98] Read the following session from the keychain with the following scopes: repo,workflow
[Trace  - 17:39:03.98] Read the following session from the keychain with the following scopes: read:user,user:email,repo
[Trace  - 17:39:03.99] Read the following session from the keychain with the following scopes: read:user,user:email,repo
[Trace  - 17:39:03.99] Read the following session from the keychain with the following scopes: read:user,user:email,repo
[Trace  - 17:39:03.99] Read the following session from the keychain with the following scopes: read:user,user:email,repo
[Trace  - 17:39:03.99] Read the following session from the keychain with the following scopes: read:user,user:email,repo
[Trace  - 17:39:03.99] Read the following session from the keychain with the following scopes: read:user,user:email,repo
[Trace  - 17:39:03.99] Read the following session from the keychain with the following scopes: read:user,user:email,repo
[Trace  - 17:39:03.99] Read the following session from the keychain with the following scopes: read:user,user:email,repo
[Trace  - 17:39:03.99] Read the following session from the keychain with the following scopes: read:user,user:email,repo
[Trace  - 17:39:03.99] Read the following session from the keychain with the following scopes: read:user,user:email,repo
[Trace  - 17:39:03.99] Read the following session from the keychain with the following scopes: read:user,user:email,repo
[Trace  - 17:39:03.99] Read the following session from the keychain with the following scopes: read:user,user:email,repo
[Trace  - 17:39:03.99] Read the following session from the keychain with the following scopes: read:user,user:email
[Trace  - 17:39:03.99] Read the following session from the keychain with the following scopes: user:email
[Info  - 17:39:03.103] Got 17 verified sessions.
[Info  - 17:39:03.103] Got 1 sessions for user:email...
[Info  - 17:39:03.103] Got 17 sessions for all scopes...
[Info  - 17:39:03.129] Getting sessions for read:user,user:email,repo...
[Info  - 17:39:03.133] Got 13 sessions for read:user,repo,user:email...
[Info  - 17:39:05.544] Getting sessions for read:user,user:email...
[Info  - 17:39:05.546] Got 1 sessions for read:user,user:email...
[Info  - 17:39:07.294] Getting sessions for repo...
[Info  - 17:39:07.294] Got 1 sessions for repo...
[Info  - 17:39:07.337] Getting sessions for repo...
[Info  - 17:39:07.337] Got 1 sessions for repo...
[Info  - 17:39:21.150] Getting sessions for read:user,user:email,repo...
[Info  - 17:39:21.150] Got 13 sessions for read:user,repo,user:email...
```

**Comment by TylerLeonhardt** [comment]
That giant block of:

```
[Trace  - 17:39:03.99] Read the following session from the keychain with the following scopes: read:user,user:email,repo
```

seems wrong... but your error "bad credentials" isn't the same as the original issue "unable to get issuer certificate".

@RandomNoun7 can you open a new issue with all that info? I will likely close this issue since the original filer hasn't responded in a while.

**Comment by TylerLeonhardt** [comment]
@RandomNoun7 your issue should be fixed now... I fixed it in https://github.com/microsoft/vscode/commit/e8a26d3ebf5095d4324ad4bf794787540ed3b33e

The original issue has gone stale so I'll close this.
