### ISSUE TITLE
No remote with name 'ups' found. Please update your 'githubPullRequests.remotes' setting.

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#1879]
I'm seeing this in the logs:

```
[Info] No remote with name 'ups' found. Please update your 'githubPullRequests.remotes' setting.
```

I have this in my settings:

```
  "githubPullRequests.remotes": [
    "origin",
    "ups"
  ],
```

It shouldn't be asking me to update the setting as I use that remote name in some repos, just as the standard `upstream` name isn't always there.

**Comment by RMacfarlane** [comment]
@Tyriar So to clarify, your request is just to remove or update the "Please update your 'githubPullRequests.remotes' setting." text?

**Comment by Tyriar** [comment]
Pretty much, if you still want to log it 😄
