### ISSUE TITLE
Creating a permalink is crazy slow when there are many branches

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#1884]
The git command that is used by the git extension API `getBranches` is extremely slow when there are many branches. Since `getBranches` is used to determine the best remote to create a permalink for, creating a permalink is now very slow.

**Comment by 9at8** [comment]
Verified on https://github.com/9at8/vscode-pull-request-github-test-1884 (300 branches). It takes about 1-2 seconds to open the link.
