### ISSUE TITLE
Error: AuthenticationRequired Issue

### ISSUE THREAD

**Issue by gselvarajPandi** [microsoft/vscode-pull-request-github#1886]
Hi,
I installed the plugin from VSCOde and i tried to configure the github pull request. Already my VScode is working fine with git and able to pull and push from VS code. Just to have additioanl feature to support pull request i installed this plugin, but it is not authencating to work in VSCode.

- Extension version:0.16.0
- VSCode Version:1.45.1
- OS: WIndows

Steps to Reproduce:

Click sign-in under pull requests on Github left side bar.
Successfully sign-in to Github on the browser.
Click to be redirected to vscode where error messages are encountered.

Github Authentication log:
[Info  - 19:12:52.23] Logging in...
[Info  - 19:12:59.922] Exchanging code for token...
[Error  - 19:13:00.16] Error: AuthenticationRequired

In browser
Copy the token.
Switch back to VS code.
Click Signing in to null... in the status bar.
Paste the token and hit enter.

**Comment by gselvarajPandi** [comment]
No, we see the error as
Github Authentication log:
[Info - 19:12:52.23] Logging in...
[Info - 19:12:59.922] Exchanging code for token...
[Error - 19:13:00.16] Error: AuthenticationRequired

Thanks

> Do you get the **"Error code 801"** on a failed attempt login?

**Comment by RMacfarlane** [comment]
@gselvarajPandi Is there anything special about your network configuration?

**Comment by gselvarajPandi** [comment]
we are behind the firewall and enterprise account

**Comment by gselvarajPandi** [comment]
> @gselvarajPandi Is there anything special about your network configuration?

we are behind the firewall and enterprise account

**Comment by alexr00** [comment]
These is now community provided support for enterprise.
