### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by leobmarques-dev** [microsoft/vscode-pull-request-github#1889]
- Issue Type: `Bug`
- Extension Name: `vscode-pull-request-github`
- Extension Version: `0.16.0`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.45.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by RMacfarlane** [comment]
Hey @leobmarques-dev, it looks like you missed pasting some data into this issue. Can you please describe the bug and what you were doing when it happened?

**Comment by RMacfarlane** [comment]
Closing since this issue still requires more information and has not been updated recently.
