### ISSUE TITLE
Missing authentication status UI

### ISSUE THREAD

**Issue by shana** [Microsoft/vscode-pull-request-github#189]
Right now there's no UI indicating the authentication status, there should probably be one :)
The current implementation only checks for the existence and validity of credentials when it needs to use them (usually when you expand one of the PR nodes), so that probably needs to happen earlier so that we can know whether the user is "signed in" or not.

**Comment by rebornix** [comment]
A status bar item can work.

**Comment by rebornix** [comment]
Added a status bar item when we find a github repository, users can click on this status bar item to login.

![image](https://user-images.githubusercontent.com/876920/44555573-a1afa100-a6ea-11e8-922e-3926cf3f39c3.png)

Once the login succeeds or we automatically login to github, the status bar item will update its content

![image](https://user-images.githubusercontent.com/876920/44555585-bab85200-a6ea-11e8-9601-81c2b35d9fa8.png)

For now there is no clicking event handler for the status bar when users already login, we can probably open the PR view or open the repository in browser

**Comment by RMacfarlane** [comment]
Closing via https://github.com/Microsoft/vscode-pull-request-github/commit/04f48a9fb47824ede2c5c47c117a38d2414d9299 and https://github.com/Microsoft/vscode-pull-request-github/commit/72ec1194b6bd0d8346c2275e02866dd8f9af4e82
