### ISSUE TITLE
Reuse the Git extension's API

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode-pull-request-github#19]
We already have a great, `Promise`-based, [git api](https://github.com/Microsoft/vscode/blob/master/extensions/git/src/git.ts) in our Git extension, which is an [issue](https://github.com/Microsoft/vscode/issues/31103) away from getting its full API exported to other extensions. It leverages the user's Git installation, so most authentication problems are solved already.

**Comment by RMacfarlane** [comment]
@rebornix has fixed this with https://github.com/Microsoft/vscode-pull-request-github/commit/ae575eab1123b83b37d721859d8f08bc0ef5d50a
