### ISSUE TITLE
Keychain error: User interaction is not allowed

### ISSUE THREAD

**Issue by sentience** [microsoft/vscode-pull-request-github#1900]
Issue Type: <b>Bug</b>

1. Launch VSCode.
2. Switch to Source Control tab, with GitHub Pull Requests pane visible. It contains a single line of text: Sign in
3. Click the text "Sign in". Choose Allow in the prompt: The extension 'GitHub Pull Requests and Issues' wants to sign in using GitHub.
4. In Safari, click Continue to authorize the GitHub access request.
5. Choose Allow in Safari to allow the resulting page to open "Visual Studio Code - Insiders".
6. In VSCode, choose Open to allow the extension to open the URL.
7. An error notification appears: "Writing login information to the keychain failed with error 'User interaction is not allowed.'."
8. Dismiss the error notification, and the GitHub Pull Requests panel populates successfully, and works normally for the rest of the session.
9. Restart VSCode and the same behavior occurs the next time it runs.

Extension version: 0.16.1
VS Code version: Code - Insiders 1.47.0-insider (7e4cc2c435927e5a2845897961a2af10ee7f784d, 2020-06-12T05:59:19.397Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 4, 5|
|Memory (System)|16.00GB (1.25GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by RMacfarlane** [comment]
This error is being returned from the keychain, can you open "Keychain Access" and check that the "login" keychain is unlocked?

**Comment by sentience** [comment]
Yes, it's unlocked. But I'm also not able to reproduce this issue anymore. Perhaps it got cured by a reboot? I'll reopen if this reoccurs.
