### ISSUE TITLE
U.I. Tree styling an view icons

### ISSUE THREAD

**Issue by boltex** [microsoft/vscode-pull-request-github#1902]
Maybe something broke with 1.46, but the styling and icon choice for the tree views rendered in this expansion lack visual appeal and creativity. 

They lack hover info/labels, disabled states when appropriate, the order is also seemingly random. having simple choices as icons on top of tree view for classifying by date, name , etc. is trivial. 

Otherwise this is a very useful & promising project! Love it & Hope you fix all this soon!

**Comment by chrmarti** [comment]
@boltex I assume you are referring to the Issues view?

**Comment by alexr00** [comment]
@boltex can you share some screenshots of what you're referring to?

**Comment by boltex** [comment]
Sure thing, 

Sorry for the delay. screenshot below, here's whats happening: 
Step 0:  I Startup on 'dev' (as most project's workflow start branching of from a 'dev'  branch to only put stuff in master when doing real 'releases') 
step 1: i use the feature from this 'issues/pullrequest' to 'start working' on issue 47, as you can see from the red arrows in the screenshots. 
step 2:  i then finished working on 47 and commited, pushed ,etc, not really thinking i'm really "done" with that but still I commited&pushed stable code on branch 47. 
step 3: with no modified files, but still on branch 47, and forgetting to click 'stop working on 47, I start working on my issue 15 because i'm silly  ;) 
step 4 I now realize this is great progress on my issue 15 but i look in the lower left corner, and see i'm still on branch 47, doh! I clicked on 'start working on issue 15' (blue arrow) hoping for this dirty state to now become a new local branch 15...  and the button reacted to the click, but nothing else. no notifications appeared in lower right corner to tell me what was happening , if anything.

Maybe this extension is still in early development and button clicks are just mapped to simple hard-coded webservices calls to github. So in the long run I hope you will add appropriate hover info that tells what will happen if things are clicked, and popup notifications in lower right when problems arises, and/or inform what was done like "Created local branch blabla". 

(UNRELATED ISSUE) : Also having the text of the issue in "hover popovers" in the tree view instead of opening in a virtual document in the editor space feels wrong. I know you dont want to replace the github website (I was the video intro for this extension) but that part in particular should have more integration. 

![image](https://user-images.githubusercontent.com/847716/84827862-173cdd80-aff3-11ea-93d8-e7220fb060ea.png)

So that it I guess please ask for more details _and as a vscode extension dev it's an honor to interact with real members of the team like you!_  Thanks for this great product!

**Comment by alexr00** [comment]
"Start working" not working sounds like a bug. Do you have any `githubIssues.*` settings set?

Some polish takeaways I see here:
- Have a notification when a new branch is created
- Have more descriptive text when hovering over Start Working and Stop Working
- There should definitely be a descriptive message of what went wrong if a branch can't be switched to.

**Comment by boltex** [comment]
Sorry for the delay in answering. 

Here is the config entry I had for this extension : 

```
  "githubIssues.queries": [
    {
      "label": "My Issues",
      "query": "default"
    },
    {
      "label": "Created Issues",
      "query": "author:${user} state:open repo:${owner}/${repository} sort:updated-desc"
    }
  ],
```

I don't remember entering this in my config so it must have been auto-generated. (unless i'm forgetting things. which is possible) 

Anyways this made me realize the somewhat random order was because of these config entries.

Which brings me to suggest yet another improvement to this extension: Ordering and queries etc. should be discoverable and changeable through menus, accessible through icons in the "view/title" sections of their tree views. (In a way that does not 'force' a workflow. )

Thanks again for your time and efforts!

**Comment by alexr00** [comment]
@boltex we already have an icon/action for editing queries in the tree. It's this pencil:
![image](https://user-images.githubusercontent.com/38270282/85269481-3bc40a00-b478-11ea-9e8c-059b1aa276c9.png)

**Comment by boltex** [comment]
I meant 'editing' with dialogs and gui controls to change those. not just opening the text settings file to edit. 

Anyways, Thanks for your time and dedication to this project! it's pretty cool! :)

**Comment by boltex** [comment]
@alexr00 Thanks! You rock!
