### ISSUE TITLE
Work on Issue: Support to create a fork when user has no commit rights

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-pull-request-github#1903]
A common OSS scenario is that someone from the community with no commit rights to a repository would like to contribute a fix to an issue. To support this scenario the 'Work on Issue' support should offer to create a fork when the user has no commit rights.

**Comment by alexr00** [comment]
This is a large feature, and I'd like to give it time to be tested in the nightly build for a few weeks before it is released in the stable build. Because of this, I'm moving it to the July 2020 Milestone to be merged after we make the next release.
