### ISSUE TITLE
Using multiple GitHub accounts

### ISSUE THREAD

**Issue by pfaltynek-als** [microsoft/vscode-pull-request-github#1904]
I would like to use more GitHub accounts (for example one for private projects and other for jobs) But I cannot to find any way to register two Github accounts.

**Comment by nsoria1** [comment]
Hi there! Thank you creating this extension. Just checking up if this feature request is in backlog or won't be in scope.

**Comment by alexr00** [comment]
Duplicate of upstream issue: https://github.com/microsoft/vscode/issues/127967
