### ISSUE TITLE
Enable user to copy to the clipboard the link to the PR

### ISSUE THREAD

**Issue by dkent600** [microsoft/vscode-pull-request-github#1906]
On the description page I would love to be able to copy to the clipboard the PR link.  Would save me having to click the link, go to the browser and copy the link from the browser URL input field.  The whole idea of this extension is to keep the workflow within VS Code.

![image](https://user-images.githubusercontent.com/1821666/84650690-c1731300-aed6-11ea-8ea9-4f3d548c2ba5.png)

Thanks!

**Comment by rishab-pdx** [comment]
@dkent600 If I'm right you're talking about providing a ```copy to clipboard``` action next to the title of PR. @RMacfarlane I would like to take this if no one has taken this yet. 

Ideally, I think there needs to be a copy icon(a notepad SVG) next to the edit icon which when clicked copies the link to clipboard. 
But for now, I have added a button that lets users copy to the link. Let me know if a notification toast or message box should be displayed on the success of copying the link.

![issue-#1960](https://user-images.githubusercontent.com/7886919/85795287-df1d5500-b6ec-11ea-95e8-1bd9811686d6.gif)

**Comment by ashrodan** [comment]
This looks good @rishab-pdx have you got a PR in the works?

Would of thought we could use the same icon from github or opensource icon?
<img width="35" alt="Inline_issue_action_to_go_to_query_by_alexr00_·_Pull_Request__1633_·_microsoft_vscode-pull-request-github" src="https://user-images.githubusercontent.com/8232214/94328836-1b689600-fff9-11ea-812f-25e6f33703c9.png">

**Comment by ashrodan** [comment]
Looks like a dupe of https://github.com/microsoft/vscode-pull-request-github/issues/1172 @RMacfarlane

**Comment by rishab-pdx** [comment]
@ashrodan I could not get back earlier. There is a [PR](https://github.com/microsoft/vscode-pull-request-github/compare/master...rishab-pdx:rishab-issue%231906) in work which makes use of ```vscode's clipboard api```. If you could provide the ```icon``` for copy then we can get something together and push it out.

**Comment by rishab-pdx** [comment]
#2203 addresses this! @RMacfarlane @ashrodan FYI

**Comment by rishab-pdx** [comment]
This is addressed in #1906

**Comment by partlythomas** [comment]
So #2203 is apparently reversed and the copy link is no longer visible?
