### ISSUE TITLE
Show active PRs the user has reviewed in a new section. 

### ISSUE THREAD

**Issue by danhendrix** [microsoft/vscode-pull-request-github#1910]
Currently if a user checks out a PR and makes a comment, that PR is no longer listed under "Waiting For My Review". It's only visible in "All", which in a large organization is a pain to have to go through and find. 

I think the best way to handle this would be for a new section to be added which shows all open PRs that the user has reviewed or commented on. That way they would be easier to track and come back to.

**Comment by RMacfarlane** [comment]
Hey @danhendrix, these categories are actually already configurable. The default categories match those shown under the "Pull requests" tab on GitHub, but you can edit them to be anything using the same search syntax as on GitHub.

To update to what you want, you can edit the "githubPullRequests.queries" setting to be:
```
	"githubPullRequests.queries": [

		{
			"label": "Waiting For My Review",
			"query": "is:open review-requested:${user}"
		},
		{
			"label": "Reviewed by Me",
			"query": "is:open commenter:${user} reviewed-by:${user}"
		},
		{
			"label": "Assigned To Me",
			"query": "is:open assignee:${user}"
		},
		{
			"label": "Created By Me",
			"query": "is:open author:${user}"
		}
	],
```

Here's GitHub's documentation on searching PRs: https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests

**Comment by danhendrix** [comment]
@RMacfarlane Ah great, thank you!
