### ISSUE TITLE
Should not prompt to delete master branch after merge

### ISSUE THREAD

**Issue by philipstarkey** [microsoft/vscode-pull-request-github#1911]
If a change is committed to <some fork>:master, and then merged, the PR (when viewed from within this plugin in VS Code) prompts you to delete the master branch. This prompt would obviously be fine if it was anything other than master, but deleting master is not really what anyone wants (particularly as selecting the "delete on remote" option puts the remote fork in a confused state where GitHub web interface thinks the forking process is still underway and the only way to fix that is to push master back to the remote fork).

Indeed, the GitHub web interface suggests deleting the **fork**, not the master branch in such situations.

Version information:
- Extension version: 0.16.0
- VSCode Version: 1.45.1 
- OS: Windows 10

Steps to Reproduce:

1. Fork repository.
2. Commit to master of fork.
3. Make a PR from within VS Code using this extension
4. Merge the PR
5. Refresh the PR in VS Code
6. See that it suggests deleting the master branch (which is inconsistent with the GitHub web interface)

Note: If this has to be coded as a special case, it may rear it's head again when [master is replaced with a different term](https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/).

**Comment by burkeholland** [comment]
Seeing this again in https://github.com/github/codespaces/issues/1608

**Comment by RMacfarlane** [comment]
@burkeholland This change hasn't been released yet, should be fixed in tomorrow's release

**Comment by connor4312** [comment]
I see this in the most recent nightly 2020.10.41223

![](https://memes.peet.io/img/20-10-96670c63-e7b2-46a9-b995-f0395f50568d.png)

**Comment by burkeholland** [comment]
Confirmed resolved in 2020.11.3841 (Nightly). 🎉

**Comment by RMacfarlane** [comment]
@connor4312 Oops, sorry, missed responding to this earlier. This is actually expected, we still offer deleting the local copy of the branch, just not the remote one
