### ISSUE TITLE
Notify user of a New PR for review

### ISSUE THREAD

**Issue by anatoly-yakubov-betpawa** [microsoft/vscode-pull-request-github#1913]
Notify user of new (assigned) PR for a review. 
Push or periodical refresh with extension's icon status is a minimum. 
Status bar + pop-up that opens PR when clicked is a preferred way.

Without it users have to use other channels to disturb / notify / ask each other for a review. GitHub's email notification opens web UI, while reviewing using this extension is a much better experience.

**Comment by alexr00** [comment]
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/1128
