### ISSUE TITLE
Selected milestone variable

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-pull-request-github#1915]
I'd like to refer in my queries to the 'current milestone'. Since that does not appear to exist on GitHub, I suggest to introduce a 'selected milestone' in the UI that can be referred to in the queries with `${selectedMilestone}`.

With that I could have personal queries showing my bugs / plan-items for the current milestone and I could also have the team-wide planning and endgame queries without having to update the milestone value inside the query when the next milestone begins. (And I can quickly switch between, e.g., the current and the next milestone.)

**Comment by alexr00** [comment]
It seems like this is easily done by updating your query in your settings.
