### ISSUE TITLE
The color to represent add or remove is reversed.

### ISSUE THREAD

**Issue by Duckuism** [microsoft/vscode-pull-request-github#1918]
- Extension version: 0.17.0
- VSCode Version: 1.46.0
- OS: macOS 10.15.5

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/24688568/84980912-46c42500-b16e-11ea-8ad6-d0150f6eea1f.png)

The colors that represent the added and deleted codes have been reversed. How can I fix it?
I wonder if this color is affected by the theme.

**Comment by RMacfarlane** [comment]
Hey @Duckuism, these colors are provided by VSCode, not the extension. Is it possible the theme you're using has updated? You can manually change the colors by adding this to your settings:
```
"workbench.colorCustomizations": {
	"diffEditor.insertedTextBackground": "#26343D",
	"diffEditor.removedTextBackground": "#321F37"
}
```

**Comment by RMacfarlane** [comment]
I'm going to go ahead and close this since this isn't a bug or feature request for this extension. Let me know if the above doesn't work for you.

**Comment by Duckuism** [comment]
@RMacfarlane Thank you for your help!
