### ISSUE TITLE
Don't show "The remote 'origin' is not a GitHub repository." for non-GitHub repositories

### ISSUE THREAD

**Issue by letmaik** [microsoft/vscode-pull-request-github#1919]
Extension version: 0.17.0
VS Code version: Code - Insiders 1.47.0-insider (7e4cc2c435927e5a2845897961a2af10ee7f784d, 2020-06-12T06:03:53.183Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 5.3.0-1028-azure

Steps to Reproduce:

1. Clone a git repo where the origin remote is not GitHub.
2. Observe millions of error notifications saying "The remote 'origin' is not a GitHub repository."

**Comment by stephanlachnit** [comment]
Same as #1863.

**Comment by RMacfarlane** [comment]
Thanks @stephanlachnit! Closing this as a duplicate.
