### ISSUE TITLE
Show notification when only the diff is shown

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode-pull-request-github#193]
Continuation of https://github.com/Microsoft/vscode-pull-request-github/issues/172

When the commit for a PR hasn't been fetched, we fall back to showing only the diff from the data we get from GitHub. We could show a notification in this case letting users know that they can run `git fetch` to update the file contents

**Comment by rebornix** [comment]
Either we show a popup or render some decorations in the editor area.
