### ISSUE TITLE
WebView Blank

### ISSUE THREAD

**Issue by bm-stschneider** [microsoft/vscode-pull-request-github#1931]
Issue Type: <b>Bug</b>

The web view for PRs is blank.
WebView Devtools say `index.js:1 Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME`

Extension version: 0.17.0
VS Code version: Code - Insiders 1.47.0-insider (0913b1aa43191d8af0ccb4a133d9a8d7c1a81d69, 2020-06-23T09:38:28.751Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.37GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by bm-stschneider** [comment]
Most likely it is related to https://github.com/microsoft/vscode/issues/89038

**Comment by RMacfarlane** [comment]
@mjbvz I'm still seeing this in today's insiders, is this expected to already be fixed?

**Comment by mjbvz** [comment]
Should be fixed by 33142d0202d018e0e5bc11304504c84c33c3e8d5
