### ISSUE TITLE
Not showing PRs for the selected repo in a multiroot workspace

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-pull-request-github#1932]
- Open a workspace with the vscode repo and some other repo
- Select the vscode repo in the scm view
- The PR view shows PRs for the other repo

Maybe there is an issue with the API for the selected repo after the scm view changes today

**Comment by alexr00** [comment]
It looks like a git API event that used to fire no long fires. https://github.com/microsoft/vscode/blob/92164dd93d7d3f96dcc44ba6af994a62e5def354/extensions/git/src/api/git.d.ts#L115-L115
@joaomoreno , we use this to determine which repo is the "current" repo: https://github.com/microsoft/vscode-pull-request-github/blob/2c575f9cd392e5e554f2f341a9b926d999cf8eb3/src/extension.ts#L71-L80
But that event no longer fires when you click between repos in the scm view.

**Comment by joaomoreno** [comment]
@alexr00 Can you check if this works now in `master`?

**Comment by alexr00** [comment]
Yes, this works now. Thank you!
