### ISSUE TITLE
Error when creating new pull request

### ISSUE THREAD

**Issue by AKershteynBSI** [microsoft/vscode-pull-request-github#1933]
I click on "plus" icon to create new pull request. Branch name defaults to the "Master". If i type in the branch name i want and choose any option (commit branch, custom) i get and error

**Creating pull requests for 'BeamSuntoryInc:AKTest' failed: Validation Failed: Value "undefined" cannot be set for field undefined (code: custom)**

![image](https://user-images.githubusercontent.com/25087816/85901299-1f510600-b7c7-11ea-98d6-8e20de0171e6.png)

**Comment by tymik** [comment]
I get the same issue, even trying open PR to master by default, the error is completely unhelpful
