### ISSUE TITLE
Adopt multi-repo model

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-pull-request-github#1936]
The entire _selected source control provider_ was based on this [still proposed API](https://github.com/microsoft/vscode/blob/a71c35310eb86c7e1c1e267e54a53f0c6e0abced/src/vs/vscode.proposed.d.ts#L932-L947). It was always a leaky abstraction only made obvious now that SCM doesn't use views to manage visibility. All repositories are visible at all times. The same way all root folders are visible in the file explorer at all times. So this API proposal won't make it into stable and will be deprecated.

Meanwhile, there's some backwards compatibility planned with https://github.com/microsoft/vscode/issues/101277, but the idea is that this notion will dissapear.

Let's sit together in July and discuss what this means for GHPR and how update its UI to reflect a simultaneous multi-repo model.

**Comment by alexr00** [comment]
Discusses with @RMacfarlane and the plan is to have one tree view for PRs and one for issues (as we already have). However, each tree view will now have as it's top level items the repos that are open. This will match the behavior in SCM, and it will remove the "current repo" concept.

**Comment by joaomoreno** [comment]
Yeah we totally forgot to sync on this. That strategy looks great to me, does it work for you as well?

**Comment by alexr00** [comment]
With this approach there would be no requirement to know the active repo from the git API. In places where one specific repo is needed, it will found by determining which repo the currently active file belongs to.

**Comment by alexr00** [comment]
All the work should be completed in the July iteration; however, given that we have already introduced potential instability with upgrade to the GitHub rest API, I will wait to merge until after we have release for the July iteration.

**Comment by alexr00** [comment]
Fixed with https://github.com/microsoft/vscode-pull-request-github/pull/2050
