### ISSUE TITLE
Comment blockquotes should be styled better

### ISSUE THREAD

**Issue by misolori** [Microsoft/vscode-pull-request-github#194]
They need more padding and should be aligned to the edge of the text

![image](https://user-images.githubusercontent.com/35271042/44119649-b93b44aa-9fce-11e8-8fa7-f98710c7365a.png)

**Comment by auchenberg** [comment]
Another example here, where the lack of borders/boundaries makes things look quite messy/unaligned.

VS Code:
<img width="1552" alt="screen shot 2018-08-15 at 11 13 57 am" src="https://user-images.githubusercontent.com/173559/44170693-f28d1d00-a08c-11e8-9446-27579b80f496.png">

GitHub:
<img width="1552" alt="screen shot 2018-08-15 at 11 14 01 am" src="https://user-images.githubusercontent.com/173559/44170734-10f31880-a08d-11e8-8e11-3cd93e04b8ef.png">

@misolori
