### ISSUE TITLE
Unable to Clone repository

### ISSUE THREAD

**Issue by sumanmba** [microsoft/vscode-pull-request-github#1942]
Issue Type: <b>Bug</b>

Tried multiple ways, still unable to clone my repository in to my editor 

Extension version: 0.17.0
VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4130T CPU @ 2.90GHz (4 x 2893)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (3.67GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by RMacfarlane** [comment]
@sumanmba Can you please provide some more details? Did you use the `Git: Clone` command? What was the result?

**Comment by sumanmba** [comment]
I'm trying to do it in VS Code editor directly. Unable to do the same. Didn't try any other alternatives

**Comment by RMacfarlane** [comment]
It sounds like the Git extension isn't activated, do you have Git installed? https://git-scm.com/download

**Comment by brettinternet** [comment]
This is probably related to https://github.com/microsoft/vscode-pull-request-github/issues/1331

I also get that error on Arch Linux. I do indeed have Git installed.

> Command 'GitHub Pull Requests: Configure Remotes...' resulted in an error (command 'pr.configureRemotes' not found)

**Comment by RMacfarlane** [comment]
@brettinternet Are you using VSCodium or other community build of VSCode?

**Comment by brettinternet** [comment]
@RMacfarlane Thank you, I should have clarified. I am using [code](https://www.archlinux.org/packages/community/x86_64/code/), which is built from VSCode upstream. I'm not sure of the licensing distinctions, however I am confident that it's not VSCodium.

**Comment by RMacfarlane** [comment]
Got it, thanks! For that build, you will need to start code as `code --enable-proposed-api GitHub.vscode-pull-request-github`, see here: https://github.com/Microsoft/vscode-pull-request-github/wiki#3-why-isnt-the-extension-starting

**Comment by brettinternet** [comment]
@RMacfarlane Wonderful! Thank you very much. This issue should now be more visible when users search that specific error.

**Comment by RMacfarlane** [comment]
Closing this issue, as the "Clone repository" feature has been moved to `vscode`. Please open a new issue there if you still see this problem. Thanks!
