### ISSUE TITLE
Option to not use pull request template

### ISSUE THREAD

**Issue by heaths** [microsoft/vscode-pull-request-github#1943]
I would like the option to not use a pull request template. We have one in our monorepos for the sake of irregular contributors, but during active development by the feature teams, I always have to open a PR after creating it with the extension to restore the template and instead use the commit description (if one commit, which for me is typical for initial PRs) I wanted in the first place.

Perhaps this could be an option similar to `githubPullRequests.pullRequestTitle` with a default to use the template as it is currently.

**Comment by heaths** [comment]
Ping. I have a PR ready for this as well. Our templates (meant for public or infrequent contributions) auto-populating my PRs otherwise prevent me from using this functionality. I want my commit description as the PR body to make sure the bugs are auto-closed upon merging.

**Comment by alexr00** [comment]
nit: I like that the input box is populated with the commit description when the `prompt` option is set, but if there are multiple newlines in the description, some whitespace is lost. For example, if my commit was:
`git commit -m "Title of commit" -m "Description of commit" -m "more desc"`
Then the input box has: 
Description of commitmore desc

**Comment by heaths** [comment]
Did you try that without my changes? IIRC, I saw the same behavior even before - that all commit lines were squashed into a single line. It might not have been this exact scenario, but it was one where the entirety of the commit was put into an input box.

That said, I'm happy to work on a change if the input box in VSCode even supports it.

**Comment by alexr00** [comment]
Squashing on to one line is expected, but I wanted all newlines to be replaced with a space so that it's easier to read.

**Comment by heaths** [comment]
I opened a new bug to track and taking a look into fix it, but wanted to confirm that behavior already existed with the "custom" (prompt, as you put it) setting.
