### ISSUE TITLE
Alternative names for issueTitleNoSpaces 

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode-pull-request-github#1946]
re https://github.com/microsoft/vscode-pull-request-github/issues/1939

The variable name `issueTitleNoSpaces` is a little clumsy. May `safeIssueTitle`, `santitizedIssueTitle`, or just `issueTitle`?

**Comment by alexr00** [comment]
`sanitizedIssueTitle` it will be.

**Comment by jrieken** [comment]
typo: `santitizedIssueTitle`

**Comment by alexr00** [comment]
😨 I even use a spell checker and it missed that
