### ISSUE TITLE
Setting name "githubIssues.workingIssueBranch"

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode-pull-request-github#1949]
re #1939

Maybe find a better name for `workingIssueBranch`. How about `issueBranchTitle` (similar to window.title) or `issueBranchNameTemplate`

**Comment by alexr00** [comment]
I like `issueBranchTitle`, but this setting is already in stable. Will need to migrate.

**Comment by Ahmeed2m** [comment]
@alexr00 I don't know if the blog posts needs to be up to date (But I think they're kind of vscode documentation?) but it still mentions the old setting name `githubIssues.workingIssueBranch`

https://code.visualstudio.com/blogs/2020/05/06/github-issues-integration#_working-on-issues

**Comment by alexr00** [comment]
Thanks @Ahmeed2m, I just pushed an update to our docs repo!

**Comment by robertwt7** [comment]
hey guys, I just read the vscode docs [here](https://code.visualstudio.com/docs/editor/github#_working-on-issues) and I still find the old setting name `workingIssueBranch`. I have to google to find this PR. Not sure where to open issue for that?

**Comment by alexr00** [comment]
Thanks @robertwt7, I've just pushed a change to replace the old setting name in the docs. Next time the website is updated the change will be picked up.
