### ISSUE TITLE
Assignees, Labels, field descriptions are gone when switching between tabs

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode-pull-request-github#1950]
Testing #1938

1. Open a file in the workspace
2. Invoke the `Create an Issue` command
3. The `Assignees`  and `Labels` fields have description
4. Switch to the file that was opened before the command was invoked
5. Switch back to the `NewIssue.md`
  - Expected: Field descriptions should still be present
  - Actual: Field descriptions are not present

**Comment by 9at8** [comment]
@alexr00 I can still repro this in v0.17.0. Am I not using the latest version?

**Comment by RMacfarlane** [comment]
These changes haven't been released in the stable version of the extension, you can disable "GitHub Pull Requests and Issues" and install "GitHub Pull Requests and Issues Nightly" to test against the latest
