### ISSUE TITLE
Suggestions for the label color element

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode-pull-request-github#1951]
Testing #1938

* I guess this is due to a limitation but the layout with two rectangles seems unnatural. Ideally we should display the color at the beginning of the list item instead of the icon. I would go as far as removing the current implementation of showing the color until this is supported.
* If we were to show that secondary element, its height should match the list element height
* Top and Left borders of the secondary element do not match the Top and Left borders of the list

![image](https://user-images.githubusercontent.com/3372902/86226229-a3bad480-bb8b-11ea-9986-c1fb87c3bba8.png)

**Comment by alexr00** [comment]
100% agree that the color is better shown in front of the label name. There isn't a way to do this using the existing `Color` suggestion, but I think this could be done without new API.

**Comment by alexr00** [comment]
The layout with two rectangles is the same for all uses of the suggest widget.

**Comment by alexr00** [comment]
Looks like what I wanted to do is already possible. Downside is that the color hex value shows up in the documenation:
![image](https://user-images.githubusercontent.com/38270282/87033723-0bee6380-c1e7-11ea-8aef-ff5a6be29d45.png)
