### ISSUE TITLE
Issue editor: code complete hangs with loaded

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode-pull-request-github#1953]
Testing https://github.com/microsoft/vscode-pull-request-github/issues/1938

Opened code complete at the top of the editor. Got

<img width="456" alt="capture" src="https://user-images.githubusercontent.com/1931590/86227544-74a56280-bb8d-11ea-9f1a-544ba12a8a3f.png">

**Comment by alexr00** [comment]
@dbaeumer I haven't seen other reports of this and I can't repro. Please re-open if you happen to see again!
