### ISSUE TITLE
Issue editor: provide code complete for assignees

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode-pull-request-github#1954]
Testing https://github.com/microsoft/vscode-pull-request-github/issues/1938

Title says it all.

**Comment by alexr00** [comment]
Huh, this is a bug since this should already be working.

**Comment by dbaeumer** [comment]
It does not :-)

**Comment by alexr00** [comment]
It looks like it works if you type the `@` character, but not when you run the Trigger Suggest command.
