### ISSUE TITLE
Cannot loads PRs

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode-pull-request-github#196]
I have installed the extension, successfully went through the auth process but when expanding any more the nodes, I get a warning that the fetching PRs failed. Nothing in the log, just this message

<img width="1236" alt="screen shot 2018-08-15 at 09 35 26" src="https://user-images.githubusercontent.com/1794099/44136874-b4e8730a-a06e-11e8-94e7-37d825b3a0f5.png">

**Comment by jrieken** [comment]
using 0.0.10

**Comment by RMacfarlane** [comment]
Looks like we're parsing the repository owner as "/Microsoft", which is causing the fetch to fail

**Comment by jrieken** [comment]
wow, didn't  notice that I have the leading slash...

**Comment by RMacfarlane** [comment]
we should now be able to handle the leading slash with https://github.com/Microsoft/vscode-pull-request-github/commit/869387e62d4c47e31eae65d91a0335aa2b8a6006
