### ISSUE TITLE
How can i Integrated with GHE?

### ISSUE THREAD

**Issue by mkumar87** [microsoft/vscode-pull-request-github#1967]
Which settings I need to modify to provide the Customized GHE end point for the PRs

**Comment by RMacfarlane** [comment]
This is currently not supported in the most recent version of the extension, but is supported in version 0.15.0. Please see https://github.com/microsoft/vscode-pull-request-github/wiki#2-is-github-enterprise-supported, https://github.com/microsoft/vscode-pull-request-github/issues/1793
