### ISSUE TITLE
Startup activation takes 650ms

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode-pull-request-github#197]
* Install extension
* Restarting VS Code
* Check the Running Extension view and/or Developer: Startup Performance
* 🐌 notice that the PR extension takes 649ms loading its code and its dependencies. (That's slower than loading *all* of ~6MB `workbench.main.js`)

**Comment by jrieken** [comment]
<img width="1144" alt="screen shot 2018-08-15 at 09 41 47" src="https://user-images.githubusercontent.com/1794099/44137094-7bdda4e4-a06f-11e8-866c-554bc9bb55da.png">

**Comment by rebornix** [comment]
It seems code bundling helps significantly with startup performance.

*Original*

![image](https://user-images.githubusercontent.com/876920/44174094-d55d4c00-a096-11e8-917f-77b59e04e7a5.png)

*Bundled*
![image](https://user-images.githubusercontent.com/876920/44174136-f887fb80-a096-11e8-896d-ea5c54dedd49.png)

**Comment by jrieken** [comment]
👯

**Comment by rebornix** [comment]
Fixed via https://github.com/Microsoft/vscode-pull-request-github/pull/213
