### ISSUE TITLE
Pull request - Reviewers

### ISSUE THREAD

**Issue by fpena06** [microsoft/vscode-pull-request-github#1971]
- Extension version: 2.6.6
- VSCode Version: 1.46.1
- OS: windows 10

Steps to Reproduce:

1. Create pull request
2. Add reviewers

I can no longer select reviewers with the extension. Just says "No Options".

**Comment by RMacfarlane** [comment]
@fpena06 Does this happen for all repos? Can you open the developer tools by running `Developer: Toggle Developer Tools` and see if there is anything in the console?

**Comment by fpena06** [comment]
@RMacfarlane so the problem is with the update I know have to select a branch before I can add reviewers. Before it would default to the last branch used. That's no longer the case. Now for every PR I have to select a branch. Anyway to default it to a specific branch?

Thanks
Francis

**Comment by alexr00** [comment]
@fpena06 Does this happen for all repos? Can you open the developer tools by running Developer: Toggle Developer Tools and see if there is anything in the console?
