### ISSUE TITLE
Duplicate "Publish to GitHub" Buttons

### ISSUE THREAD

**Issue by MohamedAlFahim** [microsoft/vscode-pull-request-github#1985]
- **Extension version:** v0.16.0
- **VSCode Version:** 1.46.1
- **OS:** macOS High Sierra, Version 10.13.6

Steps to Reproduce:

1. Create VSCode project that is not initialized with Git yet
1. Open "Source Control" side menu

When the extension is enabled:
<img width="297" alt="GitHub Extension Enabled" src="https://user-images.githubusercontent.com/31521089/87111678-c9487d80-c21e-11ea-97c4-d7ade32aaada.png">

When the extension is disabled:
<img width="292" alt="GitHub Extension Disabled" src="https://user-images.githubusercontent.com/31521089/87111690-d2d1e580-c21e-11ea-97bc-dec1f2d9a0b1.png">

**Comment by RMacfarlane** [comment]
Hey @MohamedAlFahim, please update to the latest version of the extension (0.17.0). The extension used to add this functionality but it has since been added to a built in extension that ships with VSCode, which is why you see it duplicated. It should be removed in 0.17.0. Thanks!

**Comment by MohamedAlFahim** [comment]
@RMacfarlane But the strange thing is when I looked at the Pull Request extension, it appeared up-to-date, even though in reality it wasn't. So I uninstalled the Pull Request extension, hoping to reinstall it, perhaps forcing it to update. But even after restarting VSCode, the Pull Request extension is gone from the marketplace!

<img width="304" alt="No GitHub Pull Request Extension" src="https://user-images.githubusercontent.com/31521089/87207219-47109580-c2c0-11ea-8af9-dec3a6829258.png">

**Comment by RMacfarlane** [comment]
Huh, I'm not sure what's going on, I'm still able to see it in extension search. Are you able to download it from https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github? Clicking the "Install" button should open VSCode

**Comment by MohamedAlFahim** [comment]
@RMacfarlane The even stranger thing is that when I installed it, it thinks the extension is:

<img width="1141" alt="Not The GitHub Extension" src="https://user-images.githubusercontent.com/31521089/87209382-7c1fe680-c2c6-11ea-85b8-c30d38b1e1f0.png">

I must be incredibly unlucky for this many bugs to occur in a row. 😅

**Comment by MohamedAlFahim** [comment]
@RMacfarlane After further testing, I figured out that all of these issues only occur in VSCodium, not VSCode. I will open an issue there and reference this issue. (I haven't found a similar issue on https://github.com/VSCodium/vscodium)
