### ISSUE TITLE
Create Issue flow should never lose data

### ISSUE THREAD

**Issue by jackfranklin** [microsoft/vscode-pull-request-github#1988]
I just spent a fair amount of time writing a new issue up in the New issue view (`NewIssue.md`). Rather than click the tick I mistakenly saved and closed the window. 

I now cannot find the issue that I wrote; I'm not sure if it even exists any more. If I try to create a new issue it now gives me a blank issue. I tried reopening the closed editor or `cmd-z`-ing my way back, but that didn't work unfortunately.

Are these issues saved anywhere? And if not, it would be great if there was a way to save them as drafts to avoid accidental lose of work.

Thanks!

**Comment by olix0r** [comment]
I lose about 50% of the issues I write due to muscle-memory close-saving it. I love writing issues in the editor but I'm desperate for a way to stop losing them :(

**Comment by alexr00** [comment]
New behavior will be:
- If you close a new issue without creating an issue, the contents will be cached.
- When you start to create a new issue, the cached content will be used.
- The cache is cleared when you open the workspace/reload the window.
- The cache is maintained per workspace.
