### ISSUE TITLE
Have a associated command to "leave" a PR

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-pull-request-github#199]
I see I can enter a PR by picking the "checkout" action. I think there should also be an action to do the inverse operation and bring me back to the branch I have been before.

**Comment by lszomoru** [comment]
@alexr00, it seems to me that `Exit Review Mode` and `Exit Pull Request` do the same thing.
Should we use a consistent name for this gesture independent whether it is in the web view or in the context menu.
