### ISSUE TITLE
Add email info to @user

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode-pull-request-github#1995]
Can the @ also be configured to insert email addresses of users, instead of usernames?

From: https://twitter.com/sangeeth96/status/1282722489592758273

**Comment by emtei** [comment]
Great idea!

Commit messages are handled by vscode itself, so this feature should be requested in [microsoft/vscode](https://github.com/microsoft/vscode) repository

**Comment by alexr00** [comment]
Closing as we don't plan to address this.
