### ISSUE TITLE
The merge button is enabled also if it's not possible to merge the PR

### ISSUE THREAD

**Issue by mcosta74** [microsoft/vscode-pull-request-github#1999]
- Extension version: v0.018.0
- VSCode Version: 1.47.1
- OS: macOS

Steps to Reproduce:
1. Checkout a PR
2. Click on "Request Change"
    - now the PR cannot be merged from GitHub interface
    - the "Merge Pull Request" button is enabled

**Comment by RMacfarlane** [comment]
@mcosta74 Do you remember why the PR could not be merged? Were there failing checks, conflicts, was it your own PR?

**Comment by mcosta74** [comment]
The was not mergable because I requested a change in my review.
Unfortunately it's a private repository so I cannot give access.

Later I'll try to reproduce on a public repo and I'll put more info
