### ISSUE TITLE
Bad experience when credentials are missing

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode-pull-request-github#20]
Could we rewrite the message such that it makes more sense to the user, such as

> No credentials found. You need to setup credentials because...

![image](https://user-images.githubusercontent.com/22350/41914869-aa1fa9c0-7954-11e8-8c96-b682216e3603.png)

Also, we should provide actions to guide the user to set up the credentials.

**Comment by misolori** [comment]
It looks like the error messages are not properly formatted:

![image](https://user-images.githubusercontent.com/35271042/42538858-037bd74c-844e-11e8-80aa-10712feb10a2.png)

**Comment by joaomoreno** [comment]
Yeah let's close it.
