### ISSUE TITLE
Modified diff/patch files in pull requests not displayed properly

### ISSUE THREAD

**Issue by chrstphrchvz** [microsoft/vscode-pull-request-github#2000]
- Extension version: 0.18.0
- VSCode Version: 1.47.1
- OS: macOS 10.15.5, Windows 10 2004

Steps to Reproduce:

1. Clone this test repository: https://github.com/chrstphrchvz/macports-ports
The repository has a large history, so I suggest doing a shallow clone: 
```git clone --depth 1 https://github.com/chrstphrchvz/macports-ports.git```
2. Open the folder for the git repository in VS Code (`code -g macports-ports`).
3. Go to the GitHub extension. Under Pull Requests, expand "All", then select "Test issue for vscode-pull-request-github".
4. View the modified version (or side-by-side comparison) for any of the .diff files for this pull request.

The modified version of the files are displayed erroneously: portions are displayed misordered, and the file will be mostly empty lines. The modified versions of the "Portfile" files in the pull request appear fine, though.

Example: lang/python38/patch-configure-xcode4bug.diff
Actual modified version:
```diff
https://trac.macports.org/ticket/49272
https://bugs.python.org/issue24844

Compiling python fails in Xcode 4 (clang < 3.3) where existence of 'atomic'
is detected by configure, but it is not fully functional.

--- configure.orig	2020-07-13 07:11:53.000000000 -0500
+++ configure	2020-07-15 10:20:09.000000000 -0500
@@ -16837,6 +16837,24 @@
     volatile int val = 1;
     int main() {
       __atomic_load_n(&val, __ATOMIC_SEQ_CST);
+
+      // https://bugs.python.org/issue24844
+      #define VERSION_CHECK(cc_major, cc_minor, req_major, req_minor) \
+          ((cc_major) > (req_major) || \
+          (cc_major) == (req_major) && (cc_minor) >= (req_minor))
+      #if defined(__clang__)
+          #if defined(__apple_build_version__)
+              // either one test or the other should work
+              // #if __apple_build_version__ < 5000000
+              #if !VERSION_CHECK(__clang_major__, __clang_minor__, 5, 0)
+                  #error
+              #endif
+          // not sure if this is 3.3 or 3.4
+          #elif !VERSION_CHECK(__clang_major__, __clang_minor__, 3, 3)
+              #error
+          #endif
+      #endif
+
       return 0;
     }
 

```
Modified version displayed by extension (line numbers + ellipses added):
```
1. https://trac.macports.org/ticket/49272
2. https://bugs.python.org/issue24844
3. 
4. Compiling python fails in Xcode 4 (clang < 3.3) where existence of 'atomic'
5. is detected by configure, but it is not fully functional.
6. 
7. +
8. +      // https://bugs.python.org/issue24844
9. +      #define VERSION_CHECK(cc_major, cc_minor, req_major, req_minor) \
10. +          ((cc_major) > (req_major) || \
11. +          (cc_major) == (req_major) && (cc_minor) >= (req_minor))
12. +      #if defined(__clang__)
13. +          #if defined(__apple_build_version__)
14. +              // either one test or the other should work
15. +              // #if __apple_build_version__ < 5000000
16. +              #if !VERSION_CHECK(__clang_major__, __clang_minor__, 5, 0)
17. +                  #error
18. +              #endif
19. +          // not sure if this is 3.3 or 3.4
20. +          #elif !VERSION_CHECK(__clang_major__, __clang_minor__, 3, 3)
21. +              #error
22. +          #endif
23. +      #endif
24. +
25.        return 0;
26.      }
27.  
28. 
29.
30.
⁝
16783.
16784.
16785. --- configure.orig	2020-07-13 07:11:53.000000000 -0500
16786. +++ configure	2020-07-15 10:20:09.000000000 -0500
16787.
16788.
⁝
16825.
16826.
16827.     volatile int val = 1;
16828.      int main() {
16829.        __atomic_load_n(&val, __ATOMIC_SEQ_CST);
```

Summary:
| File                                         | Actual no. of lines (`wc -l` + 1) | Displayed no. of lines | Actual no. of characters (`wc -c`) | Displayed no. of characters |
|----------------------------------------------|-----------------------------------|------------------------|------------------------------------|-----------------------------|
| lang/python38/patch-configure-xcode4bug.diff | 34                                | 16829                  | 953                                | 17947                       |
| lang/python38/patch-configure.diff           | 12                                | 3388                   | 315                                | 3691                        |
| lang/python38/patch-libedit.diff             | 177                               | 169311                 | 6205                               | 212808                      |

Without being familiar with how this extension works, I wonder if it is mistakenly treating diff/patch files in pull requests specially when it shouldn't treat them any differently than other files in a pull request.

**Comment by RMacfarlane** [comment]
Nice catch, thank you for the example PR!
