### ISSUE TITLE
Not able to see Icon GEAR in vs code 

### ISSUE THREAD

**Issue by vineet-goel-salesforce** [microsoft/vscode-pull-request-github#2002]
- Extension version:
![image](https://user-images.githubusercontent.com/60270018/87635203-4c585f00-c75c-11ea-8d25-07ef3f0a8013.png)

- VSCode Version:
![image](https://user-images.githubusercontent.com/60270018/87635261-5f6b2f00-c75c-11ea-8e5e-e8216cf96b11.png)

- OS: Windows WIndows 10 Pro

Steps to Reproduce:

1. Install the Extension Github Pull Request and Issues
2. Reload Vs code, but not able to see any gear for the same.
![image](https://user-images.githubusercontent.com/60270018/87635411-9ccfbc80-c75c-11ea-8fab-dc92430ca3e5.png)

**Comment by RMacfarlane** [comment]
@vineet-goel-salesforce I'm not sure what you mean by "icon gear", can you explain?

One of the gifs on the readme is outdated and shows the old activity bar icon, the new one is this one:
![Screen Shot 2020-07-16 at 8 46 11 AM](https://user-images.githubusercontent.com/3672607/87692874-1c4f9280-c741-11ea-8886-02e8ebd2adad.png)

**Comment by vineet-goel-salesforce** [comment]
OK got it, thanks
