### ISSUE TITLE
Issue list not updating

### ISSUE THREAD

**Issue by tamasfe** [microsoft/vscode-pull-request-github#2003]
- Extension version: 0.18.0
- VSCode Version: 1.47.0
- OS: Linux 5.6.18-200.fc31.x86_64

New issues aren't shown even after manually refreshing them. Any issue after tamasfe/taplo#20 will not show up.

Issues in VSCode:
![image](https://user-images.githubusercontent.com/25967296/87658958-254e5d00-c75d-11ea-8285-850537ac1128.png)

Issues in the repo:
![image](https://user-images.githubusercontent.com/25967296/87658876-0c45ac00-c75d-11ea-9010-8e7a35544fd2.png)

Steps to Reproduce:

1. Clone [this repo](https://github.com/tamasfe/taplo)
2. List issues

**Comment by RMacfarlane** [comment]
@tamasfe The category you currently have expanded is issues created by you, it looks like the issue in screenshot was created by someone else. To list all issues, you could edit the query for that category or add another category by changing the `githubIssues.queries` setting
```
	"githubIssues.queries": [

		{
			"label": "My Issues",
			"query": "default"
		},
		{
			"label": "Open Issues",
			"query": "state:open repo:${owner}/${repository} sort:created-desc"
		}
	],
```

**Comment by tamasfe** [comment]
Ah sorry, I expected to see all issues by default, or at least in commit message completions.

But this makes sense, thanks!
