### ISSUE TITLE
Do not trigger issue completions on '#' starting a comment

### ISSUE THREAD

**Issue by peey** [microsoft/vscode-pull-request-github#2005]
Steps to Reproduce:

1. make a `Makefile`
2. start a comment `# this is a comment`
3. continue the comment in the second line `# second line of comment`

At each line of comment, I'm badgered with autcomplete I don't need

**Comment by RMacfarlane** [comment]
@peey you can configure what filetypes have issues completions using the `githubIssues.ignoreCompletionTrigger` setting. Adding "makefile" to the list should disable it there

**Comment by peey** [comment]
Thanks for the quick fix!

I'm assuming that this might be a standard problem with other languages where comments begin with `#` as well. Are you maintaining a default list in the extension?

If not, I think a better solution may be to detect the comment delimiter, and if it is `#` then only trigger completion on the second #.

For example, a valid scenario may be:

```Makefile
all:
   cd target 
   # See #12345 
   <some-complex-command>
```

**Comment by RMacfarlane** [comment]
Yes, there is a default list in the extension, currently it just includes Python.

I like your proposal, but I think there are some file extensions that will be too conservative for, for example in Markdown, which is a fairly common use case, we still want completions at any point. I think expanding the default list is less error prone
