### ISSUE TITLE
Extension does not work w/code-server using browser as vscode UI

### ISSUE THREAD

**Issue by kford** [microsoft/vscode-pull-request-github#2007]
I'm running VS Code through my browser, on ChromeOS (crostini/Linux), which is hosting code-server.  When I use this extension, it does not connect to my git repo and retrieve issues.

- Extension version:
```0.16.0```

- VSCode Version:
  ```Code - OSS
  code-server: v3.4.1
  VS Code: v1.45.1```

- OS:
```Chromeos - Version 83.0.4103.119 (Official Build) (64-bit)```

Steps to Reproduce:

1. Install code-server in crostini on ChromeOS Linux
2. Launch browser (localhost:8080 by default)
3. Install extension
4. Open workspace that is a git repo
5. click Github extension icon on navbar
6. PRs and Issues viewlets exist but are empty

**Comment by kford** [comment]
![image](https://user-images.githubusercontent.com/821268/87730000-7ec58480-c77b-11ea-893e-270e0f659fe0.png)

**Comment by RMacfarlane** [comment]
@kford Can you open the developer tools by running the `Developer: Toggle Developer Tool` command? I suspect this may be an instance of https://github.com/microsoft/vscode-pull-request-github/wiki#3-why-isnt-the-extension-starting

**Comment by kford** [comment]
@RMacfarlane - I don't have that option "Toggle Developer Tools"  - I read the issue you referred to.  For context, I am running code-server on my machine, and the vscode UI through web browser.  If code-server is == OSS vscode, then maybe that is the problem.  The guidance though, differs, since I'm not launching vscode, but launching code-server and connecting to it via browser at :8080

```If you're using an OSS build of Visual Studio Code (for example, the archlinux community build), the extension will fail to activate unless you launch with the flag --enable-proposed-api GitHub.vscode-pull-request-github. In the official build of VSCode, we have a product.json file that has a list of extensions that are allowed to use the proposed APIs. Since this is absent in the OSS build, the flag is needed to enable the proposed api for this extension.```

Should I launch code-server with that flag? -- I don't have experience with systemctl, which is how code-server is configured to run, but I added the flag mentioned in the issue you ref'd, to the systemctl unit configuration, but that caused it to fail to launch.

![image](https://user-images.githubusercontent.com/821268/88082788-18ec4a80-cb37-11ea-9b1b-86853bcb1ea1.png)

Any ideas?

**Comment by kford** [comment]
Further debugging - when I try to execute code-server directly (outside of systemctl), using the --enable-proposed-api flag, it tells me it's an invalid option.

```➜  ~ /usr/bin/code-server --enable-proposed-api GitHub.vscode-pull-request-github
Unknown option --enable-proposed-api```

**Comment by kford** [comment]
I learned that code-server doesn't take flags, but you pass them in through config.yaml.. so I wrote a config.yaml and used the proposed api flag, but it wouldn't launch with that configuration..

My config.yaml
```
bind-addr: 127.0.0.1:8080
auth: password
password: <<REMOVED>>
cert: false
enable-proposed-api: GitHub.vscode-pull-request-github
```

output
```
➜  /usr/bin/code-server --config ~/dev/code-server-config.yaml
info  Using config file ~/dev/code-server-config.yaml
error reading /home/username/dev/code-server-config.yaml: Unknown option --enable-proposed-api=GitHub.vscode-pull-request-github
```

**Comment by chrisdias** [comment]
Sorry, I have to close this as we can't support/debug running in anything other than VS Code or out of the OSS repo per instructions above.
