### ISSUE TITLE
githubIssues.workingIssueBranch setting migration happening after issue branch create

### ISSUE THREAD

**Issue by pluma** [microsoft/vscode-pull-request-github#2011]
Issue Type: <b>Bug</b>

1. Set `githubIssues.workingIssueBranch` to literally anything (e.g. `issue-${issueNumber}`.
2. Start working on issue.

Expected result: the branch name should be respected.

Actual result: the default branch name format is used.

I'm using VSCode Insiders on WSL, the configuration is in my user settings but I've also tried putting it in the remote config to no avail. Note that `useBranchForIssues` also doesn't seem to have any effect when using a multi-folder workspace.

Extension version: 0.18.1
VS Code version: Code - Insiders 1.48.0-insider (ff6b1c5984a4c2116a06318f07e871a4169fdb1b, 2020-07-17T13:18:36.126Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.104-microsoft-standard
Remote OS version: Linux x64 4.19.104-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8705G CPU @ 3.10GHz (8 x 3096)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (3.41GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.104-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-8705G CPU @ 3.10GHz (8 x 3096)|
|Memory (System)|7.77GB (3.87GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.104-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-8705G CPU @ 3.10GHz (8 x 3096)|
|Memory (System)|7.77GB (3.87GB free)|
|VM|0%|
</details>

**Comment by dan1994** [comment]
I'm also seeing the same behavior. Was hoping to use the `sanitizedIssueTitle`, but the branch name remains the same no matter what I put in the setting (both in the user and workspace setting).
I work on Windows 10, and specifically also tried it in a multi root workspace.

**Comment by froggyling** [comment]
I also seem to have the same issue.

`${user}/issue${issueNumber}/${sanitizedIssueTitle}`

is actually only creating new branches in the format of:

`${user}/issue${issueNumber}`

**Comment by RMacfarlane** [comment]
This setting name was deprecated and replaced with `"githubIssues.issueBranchTitle"`: https://github.com/microsoft/vscode-pull-request-github/issues/1949

However, we should be automatically migrating it to the new setting. It looks like maybe there's a timing issue right now and the migration is happening after the branch is created.

**Comment by pluma** [comment]
I could swear I tried it with both names and neither would work in multi repo/folder projects.
