### ISSUE TITLE
This extension seems to assume all repos use https. Does not work for local github deployments over http

### ISSUE THREAD

**Issue by bedge** [microsoft/vscode-pull-request-github#2012]
- Extension version: 0.18

- VSCode Version, OS:

Version: 1.48.0-insider
Commit: ff6b1c5984a4c2116a06318f07e871a4169fdb1b
Date: 2020-07-17T13:13:00.639Z (2 days ago)
Electron: 8.3.3
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Darwin x64 18.7.0

Steps to Reproduce:

1. Install extension
2.Follow login prompts
3. no remotes are detected

Note that on a previous installation (attempted clean install by uninstalling and reinstalling the extension) I was directed to a url that matched my local github self-hosted instance, except that the "http" in the correct url had been replaced with an "https". I don't see that step anymore but mention it as it seems fundamental to the issue.
I removed the superfluous "s" and completed the login to my local github instance.

Now I just get this (redacted) browser page:
![Screen Shot 2020-07-19 at 2 02 45 PM](https://user-images.githubusercontent.com/499317/87885269-91cd9400-c9c9-11ea-9b0b-47d29b823a92.png)

Then I see only:
![Screen Shot 2020-07-19 at 2 04 14 PM](https://user-images.githubusercontent.com/499317/87885282-ad389f00-c9c9-11ea-9bd3-a330d90ab9a0.png)

My remotes are "origin" and "upstream".

I believe that there are more https vs http assumptions in this extension that are preventing this from working.

**Comment by RMacfarlane** [comment]
Thanks for reporting this, but supporting this is out-of-scope for this project
