### ISSUE TITLE
Cross Repo view like "Pull Requests" view on github.com

### ISSUE THREAD

**Issue by tchkreddy** [microsoft/vscode-pull-request-github#2013]
Currently, I can see PRs only from one repo.Most companies use tracks across multiple repos, so it would be better to simulate the list like the one on "Pull Requests" tab of github.com

**Comment by RMacfarlane** [comment]
This looks like a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/1583, let's track it there
