### ISSUE TITLE
Code review on merged pull request

### ISSUE THREAD

**Issue by bennyKY** [microsoft/vscode-pull-request-github#2014]
In GitHub there's an option to review a PR after it was merged.
I didnt saw the extension supports it.

It would be really helpful because there are companies that first merge a PR (if all tests are valid) and only afterwards review it. And off course there are urgent merges that being reviewed afterwards..

**Comment by RMacfarlane** [comment]
This looks like a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/2014, let's track it there
