### ISSUE TITLE
Not seeing "Assignee" section

### ISSUE THREAD

**Issue by vmo-mgosling** [microsoft/vscode-pull-request-github#2015]
- Extension version: 2020.7.13861
- VSCode Version: 1.47.2
- OS: Windows as Client, Host of remote workspace (where the extension is running) is CentOS

Steps to Reproduce:

1. Make PR
2. Look for Assignee section on right
3. Don't see it.

Note: I'm accessing an organization's repo, perhaps that has something to do with it. But I'm able to add labels, assign reviewers, the link works, I can edit the description, I can comment, close, merge, approve, everything (i think) except change/add Assignee.

**Comment by RMacfarlane** [comment]
Hey @vmo-mgosling, this hasn't been implemented yet, there is currently a feature request open for it: https://github.com/microsoft/vscode-pull-request-github/issues/1063

I'm going to go ahead and close this as a duplicate. Thanks!

**Comment by vmo-mgosling** [comment]
> Hey @vmo-mgosling, this hasn't been implemented yet, there is currently a feature request open for it: #1063
> 
> I'm going to go ahead and close this as a duplicate. Thanks!

https://github.com/microsoft/vscode-pull-request-github/issues/1696 I thought thats what got added here? The other issues I've found seem to suggest I should at least see the Assignees.

**Comment by RMacfarlane** [comment]
Ah, #1696 refers to the creating an issue flow, but the description page of a pull request still only shows reviewers and labels.

**Comment by vmo-mgosling** [comment]
Oh okay, that makes sense now. Thanks again, I'll keep an eye on the feature request you linked.
