### ISSUE TITLE
Cannot Login

### ISSUE THREAD

**Issue by yltx** [microsoft/vscode-pull-request-github#2019]
- Extension version:v0.18.1
- VSCode Version:1.48.0-Insiders
- OS:Windows10

Steps to Reproduce:

Here is my login video:

https://s31.aconvert.com/convert/p3r68-cdx67/7lplv-cawq5.gif

I tried two methods,but both of them didn't work.How can I login?

**Comment by RMacfarlane** [comment]
@yltx I'm not able to open the gif, can you please describe what you tried and what happened, or upload the gif to github?

**Comment by yltx** [comment]
I tried login by chrome and token,but both failed.

**Comment by yltx** [comment]
https://github.com/yltx/a/blob/master/toexv-ulp31.gif

**Comment by yltx** [comment]
ok.Now it works.Thank you.
