### ISSUE TITLE
Improve flow to checkout a PR

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-pull-request-github#202]
I like how I can checkout a PR and I am in that mode, but I find the new view in the SCM view that actually should be at the center of this experience hard to discover. Should we at least maybe show a notification (once?) that tells the user that there is a new view in the SCM view that shows the changes of the PR?

Or maybe actually expand and reveal the view and focus it?

**Comment by RMacfarlane** [comment]
Since we have introduced a new view for the extension that appears when you install it, I think this is now much easier to discover. So, closing this issue
