### ISSUE TITLE
"Creating comment failed"

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-pull-request-github#2020]
- Do a code review, add a comment like normal
- First the "Cannot read property 'push' of undefined" error showed up
- Click "save" a second time
- Then the second error

![image](https://user-images.githubusercontent.com/323878/88443954-81edef80-cdcf-11ea-9663-9aa48934055b.png)

The comment was actually successfully created according to github. I can't find a full stack anywhere so this isn't a helpful bug report, sorry.

**Comment by roblourens** [comment]
Also, I reloaded the window after hitting this, and stuff is kind of broken

![image](https://user-images.githubusercontent.com/323878/88444374-a64acb80-cdd1-11ea-8222-a64f2d34c6ae.png)

I get this message when clicking a file in the "Changes in pull request" view to see a diff. That commit is there, it's a commit in master though, not the feature branch, although master has been merged into the feature branch since then.

**Comment by roblourens** [comment]
Reloaded the window again, still got that error. Checkout master manually, then went back into review mode on the same PR, getting the same error. It's this PR if that helps https://github.com/microsoft/vscode/pull/103268

**Comment by alexr00** [comment]
Not sure how to take action on this one. If you see it again, can you grab logs from "GitHub Pull Request"?

**Comment by roblourens** [comment]
Don't remember seeing it since
