### ISSUE TITLE
GitHub Projects Support 

### ISSUE THREAD

**Issue by WilsontheWolf** [microsoft/vscode-pull-request-github#2021]
Hello There,

I’ve recently found out about GitHub projects and I was hoping that it was possible to work into this extension. Having access to GitHub projects in vscode would be very useful for me. 

Thank you,
WilsontheWolf

**Comment by froggyling** [comment]
is there a need for this?

I ask as I have a github board working with issues and pull-request, and it works well.

My workflow is simply:

- add an issue
- start working on issue (git pull create and checks out a branch)
- work as normal, committing and pushing as I need
- when done, I make a pull request  (wish pull request had an option to push to remote automatically here :) )
- do the usual pull / merge

during this time projects has:
- added issue to a todo column (right now cant seem to get projects to move issues to in progress on checkout)
- moved issue to complete one pull request is completed

from my findings to-date only the option of git issues being updated/moved to projects on a checkout is missing for a nice - never edit projects board for coding workflow after an issue is created.

sorry for messy comments here, doing this from a mobile device.

**Comment by RMacfarlane** [comment]
Closing this as out-of-scope
