### ISSUE TITLE
How to add comment UI to editor 

### ISSUE THREAD

**Issue by HaoboGu** [microsoft/vscode-pull-request-github#2023]
Hello, I am a VSCode extension developer. Your extension is awesome and I am wondering that how to attach the comment UI to an editor, like
![image](https://user-images.githubusercontent.com/8640918/88650383-428b1000-d0fb-11ea-9029-0be180b36500.png)

as far as I know, VSCode does not allow extensions to change the UI. I am quite curious about how to do it. 

Thanks if you can help!

**Comment by RMacfarlane** [comment]
Hi @HaoboGu, this extension uses the `Comment` API to do this. There's an example of this to get started with here: https://github.com/microsoft/vscode-extension-samples/tree/master/comment-sample

**Comment by HaoboGu** [comment]
@RMacfarlane  Thanks very much!
