### ISSUE TITLE
PR shows wrong diff

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode-pull-request-github#203]
* opened this https://github.com/Microsoft/vscode/pull/55107
* opened vscode.d.ts inside vscode
* :bug: the diff showing isn't the diff that shows on github

<img width="546" alt="screen shot 2018-08-15 at 18 08 26" src="https://user-images.githubusercontent.com/1794099/44158899-4b24e000-a0b6-11e8-87c8-2a9f84787948.png">

**Comment by rebornix** [comment]
GitHub Visual Studio ran into the same issue and got fixed via https://github.com/github/VisualStudio/pull/1008

**Comment by rebornix** [comment]
Already fixed.
