### ISSUE TITLE
Balloons for issues cover other issues.

### ISSUE THREAD

**Issue by voytas75** [microsoft/vscode-pull-request-github#2034]
I have a little business. Really petite. :)
This feature is there and it's great 🥇 Thx for whole ext.  However, it has disadvantage for me. I think a lot of people will agree: **Balloons for issues cover other issues**. The balloons appears either higher or lower (if this is the first issue) and thus **covers up other issues**. To select another issue, first move the mouse pointer outside the balloons and then it disappears. It is neither convenient nor intuitive. Personally, I would move it to the right so that the left edge of the balloon is on the right edge of the side bar.

**Comment by RMacfarlane** [comment]
Hi @voytas75, thanks for creating this issue! Do you mean the icons in the issues tree view? Could you add a screenshot showing the problem? Also, can you please include what VS Code version and extension version you are using?

**Comment by voytas75** [comment]
VSC version: 1.47.3
Extension version: v2020.7.13861
before mouse over: 
![image](https://user-images.githubusercontent.com/13856061/89206562-c17bbf00-d5b9-11ea-8a9a-de912a4f9c15.png)
after mouse over first issue: 
![image](https://user-images.githubusercontent.com/13856061/89206649-dce6ca00-d5b9-11ea-84cf-d2b3034cbef9.png)
after mouse over second issue: 
![image](https://user-images.githubusercontent.com/13856061/89206981-4a92f600-d5ba-11ea-9b03-7b82b32a715e.png)

**Comment by alexr00** [comment]
@voytas75 this should be improved in our August release next month: https://github.com/microsoft/vscode/issues/104058
