### ISSUE TITLE
Extension host terminated unexpectedly.

### ISSUE THREAD

**Issue by Shrestha7** [microsoft/vscode-pull-request-github#2035]
Issue Type: <b>Bug</b>

Hello,
After i clone my project from github. This error message showed up :
Extension host terminated unexpectedly. And i realise it was made by github extension which keeps crashing and asking me to initailaize repo saying dont have git init in the project folder but it already have.I even try from bash  git init it says it already git init. And also i can`t change my shell from bash to windows terminal. Can you guys fix it for me.

Extension version: 0.18.0
VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (2.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by alexr00** [comment]
Can you open the console (command Toggle Developer Tools) and see if there is any information there when the problem happens?

**Comment by RMacfarlane** [comment]
Closing since this issue still requires more information and has not been updated recently.

**Comment by ajjitn** [comment]
I am having this same error pop up repeatedly when using this extension on a Github repo I am working on. Here are the console errors I am seeing on the Developer Tools window:

```
[uncaught exception]: Error: read ECONNRESET
b @ bootstrap-window.js:260
bootstrap-window.js:263 Error: read ECONNRESET
    at Pipe.onStreamRead (internal/stream_base_commons.js:205)
b @ bootstrap-window.js:263
events.js:292 Uncaught Error: read ECONNRESET
    at Pipe.onStreamRead (internal/stream_base_commons.js:205)
abstractExtensionService.ts:536 Extension host terminated unexpectedly. Code:  null  Signal:  SIGABRT
_onExtensionHostCrashed @ abstractExtensionService.ts:536

```
