### ISSUE TITLE
Can't tell that 'github.hosts' is from this extension

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-pull-request-github#204]
![image](https://user-images.githubusercontent.com/323878/44160010-eb0a4b80-a06d-11e8-8cef-22b6a09ad259.png)

The configuration title should be more identifiable, like the name of the extension

**Comment by shana** [comment]
@rebornix Should the title be `GitHub for VS Code` or `GitHub Pull Requests`?

**Comment by RMacfarlane** [comment]
@shana I think it should match the extension name, GitHub Pull Requests
