### ISSUE TITLE
No prompt to fork on macOS when working on an issue

### ISSUE THREAD

**Issue by ornellaalt** [microsoft/vscode-pull-request-github#2043]
Testing #2037

Steps:

1. Cloned vscodespaces
2. Added 
`{
            "label": "All Issues",
            "query": "state:open"
        }`

to `githubIssues.queries`

3. Right clicked Documentation issue #130 and selected Start Working on Issue

No prompt was opened directing me to fork

**Comment by ornellaalt** [comment]
Edit: the prompt to create the fork comes up after I select Create Pull Request and try to set target branch and pick a name for upstream branch

**Comment by deepak1556** [comment]
Same on windows wrt fork prompt, but I couldn't get past the create pull request action https://github.com/microsoft/vscode-pull-request-github/issues/2046 to verify the above workaround.

**Comment by alexr00** [comment]
@ornellaalt did you use an account that didn't have permission to push the repo you used?

**Comment by ornellaalt** [comment]
@alexr00 yes, I tried it two different ways: as described above using vscodespaces, and also by going to my second GitHub account, making a closed repo and opening some issues in it, and then cloning it from this account

**Comment by alexr00** [comment]
Were you using the nightly build of the extension? https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github-insiders

**Comment by ornellaalt** [comment]
I was not. Let me download that and try it again.

**Comment by ornellaalt** [comment]
When using the nightly build, I do get the correct prompt when I click "start working on issue" (with the same / \ mixup as mentioned in https://github.com/microsoft/vscode-pull-request-github/issues/2042) It correctly sets origin and upstream. 
![image](https://user-images.githubusercontent.com/44654695/89680804-8ecb1280-d8a8-11ea-8f13-72c90d339488.png)

I was able to open a PR in the repo: ![image](https://user-images.githubusercontent.com/44654695/89680804-8ecb1280-d8a8-11ea-8f13-72c90d339488.png)
