### ISSUE TITLE
Authentication does not work when custom ssh host name is used for multiple git accounts.

### ISSUE THREAD

**Issue by v-y-a-s** [microsoft/vscode-pull-request-github#2047]
- Extension version: v0.18.0
- VSCode Version: 1.47.3
- OS: Windows 10 

Steps to Reproduce:

1. configure to use multiple git accounts like this - https://gist.github.com/oanhnn/80a89405ab9023894df7
2. try to view pull requests that are from the account that uses `$ ssh -T git@github.com` and it will work 
3. try to view pull requests from the account that uses `$ ssh -T git@github-superman` - you will get an error as follows: 

`Fetching pull requests for remote origin, please check if the url git@github-superman.com:xxxxxxx/xxxxxxx.git is valid.`

The git repo uses SSH login and custom hostname so the `remote` parsed from git config will have a different hostname. 

I think this is related to #1904 however since the remote is based on ssh based cloning, I have created a separate issue.

**Comment by RMacfarlane** [comment]
If your configuration is

```
# Other github account: superman
Host github-superman
   HostName github.com
   IdentityFile ~/.ssh/superman_private_key
   IdentitiesOnly yes
```

Then I believe the remote should be `git@github-superman:xxxxxxx/xxxxxxx.git`, matching the Host. Note that the `.com` was removed.
