### ISSUE TITLE
Keeps trying to reenter "working on issue" mode

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-pull-request-github#2049]
- Work on some issue
- "Stop working on issue" and check out a different branch
- After a minute, this shows up again

![image](https://user-images.githubusercontent.com/323878/89835087-e4a5f180-db18-11ea-8660-68e161451690.png)

The first time, it checked out the issue branch again. Then did "Stop working on issue" and switched branches a second time. After a minute, this showed up, like it is trying to check out the same branch again and failing:
![image](https://user-images.githubusercontent.com/323878/89835063-da83f300-db18-11ea-8dd1-5ec42c061378.png)

**Comment by roblourens** [comment]
Then I reloaded the window and it has managed to check out the branch again 
![image](https://user-images.githubusercontent.com/323878/89835192-1f0f8e80-db19-11ea-8339-5fff4dede3b6.png)

**Comment by roblourens** [comment]
Unrelated, I was going to work on another issue and decided to use this workflow for it since it was on my mind. But now it won't stay in issue mode! It keeps spontaneously checking out master.

**Comment by roblourens** [comment]
Then I re-entered issue mode again, was on the right branch, committed my change... and it checked out master and committed my change to master

**Comment by jpkrohling** [comment]
This is affecting me as well. It's really dangerous, as I keep thinking I'm on the right branch only to realize that I'm on master. I *almost* pushed a change directly to the master of an open source project I'm a maintainer because of this bug...

**Comment by roblourens** [comment]
@alexr00

**Comment by alexr00** [comment]
Is there anything in the console?

**Comment by jpkrohling** [comment]
Interesting, I disabled the extension after my last comment and just enabled it back. I do not see the behavior anymore. Once I see this again, I'll check the console and update this issue.

**Comment by alexr00** [comment]
Closing as 1) this appears to be fixed and 2) there are no logs or console output to investigate.
