### ISSUE TITLE
Missing padding in comments <textarea>

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode-pull-request-github#206]
![screen shot 2018-08-15 at 11 15 43 am](https://user-images.githubusercontent.com/173559/44170459-4b0fea80-a08c-11e8-9c68-348ad4745be9.png)
<img width="588" alt="screen shot 2018-08-15 at 11 15 18 am" src="https://user-images.githubusercontent.com/173559/44170604-b6f25300-a08c-11e8-846b-66eb246848d8.png">

**Comment by rebornix** [comment]
Already fixed.
