### ISSUE TITLE
Order of "changes in Pull Request" viewlet is wrong.

### ISSUE THREAD

**Issue by auchenberg** [microsoft/vscode-pull-request-github#207]
<img width="459" alt="screen shot 2018-08-15 at 11 13 14 am" src="https://user-images.githubusercontent.com/173559/44170645-d5584e80-a08c-11e8-924f-d2f658e3faa4.png">

**Comment by RMacfarlane** [comment]
Closing as a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/6
