### ISSUE TITLE
Close Pull Request doesn't work

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#2078]
Looks like there was a missing type check.

**Comment by Tyriar** [comment]
Not sure what the repro here is, but I checked out a PR and ran the `GitHub Pull Request: Close Pull Request` command and it did nothing.

Output:

```
[Info] Found GitHub remote
[Info] Review> current branch tyriar/kv is associated with pull request #495
[Info] Review> Resolving pull request
[Info] Review> Fetching pull request data
[Info] Review> register comments provider
[Info] Review> display pull request status bar indicator and refresh pull request tree view.
```

**Comment by Tyriar** [comment]
I was using version 2020.8.39781 in a WSL workspace

**Comment by misolori** [comment]
Not sure if this made it into the afternoon release (1pm) but this looks fixed on macOS. Double checking on WSL.

**Comment by RMacfarlane** [comment]
Yep! should have made it into the release then

**Comment by misolori** [comment]
Also verified that this is fixed on WSL
