### ISSUE TITLE
When fetching PRs for a remote fails, give option to remove that remote

### ISSUE THREAD

**Issue by ramya-rao-a** [microsoft/vscode-pull-request-github#208]
I got this when fetching all PRs

![image](https://user-images.githubusercontent.com/16890566/44174107-e312d180-a096-11e8-959f-eeb6cd749509.png)

That url indeed doesnt exist anymore. It would be nice to have a button in the above notification that removes that remote.

**Comment by RMacfarlane** [comment]
Since we now base the remotes used on the "githubPullRequests.remotes" setting, this notification is unlikely to be shown for remotes that have been removed
