### ISSUE TITLE
Opening diffs shows errors on the left side

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#2082]
Opening changes from a PR (without checking it out) shows errors on the left hand side:

![image](https://user-images.githubusercontent.com/38270282/90755904-0141e680-e2dc-11ea-9ee2-d5ed80656b9d.png)

**Comment by alexr00** [comment]
@RMacfarlane fyi this was feedback from the team.

**Comment by RMacfarlane** [comment]
Looks like this has been fixed upstream: https://github.com/microsoft/vscode/issues/105842
