### ISSUE TITLE
Approving pull request does not send comment text

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode-pull-request-github#2089]
Issue Type: <b>Bug</b>

1. On the description page of a PR, type something in the text box at the bottom and hit "Approve"

The approval succeeds, but without the text

Extension version: 2020.8.29701
VS Code version: Code - Insiders 1.49.0-insider (7df29b1236ecf8a21af9fe19a52923f6d69e0577, 2020-08-26T07:45:54.661Z)
OS version: Darwin x64 18.7.0

**Comment by aeschli** [comment]
I tried to verifify but could no approve any PR: https://github.com/microsoft/vscode-pull-request-github/issues/1660#issuecomment-686494289
