### ISSUE TITLE
Show PRs that don't have a remote

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#2093]
Not sure how common this is, but even when the remote has been deleted, we still have a patch URL. Instead of having pull requests missing, we can show them and have an option to apply the patch.

https://github.com/microsoft/vscode-pull-request-github/blob/9e50f4c4b40b90743a32e3f97572394f85f736e3/src/github/githubRepository.ts#L526-L527

@lszomoru FYI

**Comment by RMacfarlane** [comment]
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/1025?

**Comment by alexr00** [comment]
Indeed
