### ISSUE TITLE
Test multi-repo model

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#2095]
Refs: https://github.com/microsoft/vscode-pull-request-github/issues/1936

- [x] macOS @deepak1556
- [x] linux @roblourens
- [x] windows @jrieken

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode-pull-request-github/issues/new?body=Testing+%232095%0A%0A)

---

The whole extension has moved over to a multi-repo model. Previously, there was the concept of a "currently active repo" when you had multiple repos open in a multi-root workspace. Now, all repos are shown in the Pull Requests and Issues views. In some places, the correct repo is inferred by where the action is taken (ex: if you create an issue from a file, then the correct repo for that file should be used). Some areas verify, both with one repo open and with a multi-root workspace:

- Verify that the Pull Requests view shows PRs from all repos.
- Verify that the Issues view shows issues from all repos.
- Try creating some PRs and issues, and verify that they get created in the expected repos.
- Verify that # issue suggestions and @ user suggestions come from the right repos.
- Check out pull requests, both from one repo and multiple repos. Verify that the Changes in Pull Request view makes sense.
- Verify that comments/reviews on PRs (both when you have a PR checked out and when don't have it checked out) work as expected.
- Verify that you can change the issues and PRs queries using the corresponding settings.

**Comment by jrieken** [comment]
👏 works really well
