### ISSUE TITLE
"Start Working On Issue" should automatically assign the Issue to me

### ISSUE THREAD

**Issue by chipascc** [microsoft/vscode-pull-request-github#2096]
It seems like when I click the "Start Working on Issue" arrow, the Issue in question should be automatically assigned to me inside of GitHub.  Otherwise, I'm forced to visit the Issue's website to change the assignment which kinda defeats the purpose of the plug-in.

(This seems kind of obvious so maybe it is supposed to work this way already?  If so, it is not working for me for some reason.)

**Comment by chipascc** [comment]
Here's a little more background.  I've set up my Issues area with the following two queries:

    "githubIssues.queries": [
        {
            "label": "My Open Issues",
            "query": "assignee:${user} state:open repo:${owner}/${repository} sort:created-desc"
        },
        {
            "label": "Unassigned Open Issues",
            "query": "no:assignee state:open repo:${owner}/${repository} sort:created-desc"
        }
    ]

The idea is that open, unassigned issuse appear in the bottom area and developers use the "Start Working on Issue" arrow to... um... start working on an issue.  When they do that, if the issue was automatically assigned to them, it would move up into the first query area and no longer appear in the bottom area for other developers.

**Comment by meganrogge** [comment]
Hey @alexr00 perhaps I'm doing this wrong, but I created an [issue ](https://github.com/microsoft/vscode/issues/109613) within VS code and it didn't assign the issue to me.

**Comment by roblourens** [comment]
It actually worked for me. I triggered it by right clicking on the issue. Is that what you did @meganrogge?

**Comment by meganrogge** [comment]
@roblourens I just tried it again and this time it worked. Maybe I clicked too soon after creating the issue?

**Comment by RMacfarlane** [comment]
The nightly build failed today and I reran it, so possibly the change just hadn't been released
