### ISSUE TITLE
Hint which repo an issue will be opened in

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-pull-request-github#2099]
Testing https://github.com/microsoft/vscode-pull-request-github/issues/2095

I think it would be helpful if the new issue form editor would tell me which repo the issue is being opened in, just to give me confidence that it got it right.

**Comment by roblourens** [comment]
Actually, why does "create PR" ask which repo to create it in, but "create issue" guesses based on context?

**Comment by alexr00** [comment]
With create issue, if you open it from a file we assume you wanted the repo that the file is from. If you create an issue from the + in the issues view it should ask you which repo you want.

**Comment by alexr00** [comment]
Hmm, if you create a lot of issues back to back a decoration won't work because we don't know when a tab is closed to remove the decoration properly. You can get an old decoration which is extremely confusing. I'll have to add a new line to the document for the repo.

**Comment by mikeseese** [comment]
> We guess based on context because it seems likely that if you're creating an issue within VS Code you probably want to create an issue in the repo of the file you have open.

This is definitely not the case in my workflow. Sometimes I discover a bug via using the terminal and proceed to make an issue. The open file can be one of many repos in my case. Perhaps an opt-in setting to disable guessing context and always prompt could solve our needs?

**Comment by mikeseese** [comment]
@alexr00 I know this issue is pretty stale, so I took a stab at both options in #6115
