### ISSUE TITLE
Replace new line chars with a space when squashing commit description

### ISSUE THREAD

**Issue by heaths** [microsoft/vscode-pull-request-github#2107]
Squashing on to one line is expected, but I wanted all newlines to be replaced with a space so that it's easier to read.

_Originally posted by @alexr00 in https://github.com/microsoft/vscode-pull-request-github/issues/1943#issuecomment-686332852_

**Comment by heaths** [comment]
See repro in https://github.com/microsoft/vscode-pull-request-github/issues/1943#issuecomment-685737940.

**Comment by heaths** [comment]
This was an easier for than I originally anticipated, but it seems more impactful than I originally thought as I went through the scenarios without getting hyper-focused on the one you brought up during the previous PR.  Would it be worth pushing out a 0.20.1 so that for templates the newlines aren't squashed as well?

**Comment by alexr00** [comment]
@heaths since that's the only issue we'd be releasing for, I would wait until the next release.
