### ISSUE TITLE
Commits pushed to PR branch dont reflect in PR view

### ISSUE THREAD

**Issue by ramya-rao-a** [microsoft/vscode-pull-request-github#211]
- Checkout a PR
- Make some changes, commit and push
- Click on the file in the PR tree view. 

Expected: The diff view includes the new changes
Actual: The diff still shows the old changes

**Comment by RMacfarlane** [comment]
@rebornix This should be fixed now that we dynamically calculate file content, right?

**Comment by RMacfarlane** [comment]
Closing as this is no longer reproducible.
