### ISSUE TITLE
Several Github welcome login buttons

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-pull-request-github#2115]
Please see the screenshot below. One idea we have discussed was to hide or collapse the issues view when not signed in

![image](https://user-images.githubusercontent.com/172399/92410005-ef1cd080-f142-11ea-8c0e-1af1718f45e9.png)

**Comment by alexr00** [comment]
The way I wanted to address this is simply have one welcome view that shows when the user isn't logged in.

**Comment by alexr00** [comment]
There's a little bit of rearranging that happens, but I think it's an improvement. 

![recording (22)](https://user-images.githubusercontent.com/38270282/93188788-b5028e80-f741-11ea-9501-586b74bf3b19.gif)
