### ISSUE TITLE
Disable tooltip for @user on code comments

### ISSUE THREAD

**Issue by intrnl** [microsoft/vscode-pull-request-github#2116]
A way to disable these tooltip that appears on `@user` in code comments would be appreciated.

![image](https://user-images.githubusercontent.com/20620901/92478908-1049f380-f20d-11ea-8dac-a21436499819.png)

**Comment by RMacfarlane** [comment]
@intrnl There's a `githubIssues.ignoreUserCompletionTrigger` setting you can use for this, you can add 'javascript' and reload the window to turn them off

**Comment by intrnl** [comment]
it doesn't seem to help, the tooltip still persists.

**Comment by alexr00** [comment]
This has since been fixed

**Comment by yCodeTech** [comment]
Nope doesn't work. I've set all these language types in the setting and the username still persists.

![image](https://user-images.githubusercontent.com/31927084/230989155-dc1ee4d0-d2e3-4e72-953b-5a8757cf6086.png)

js file
![image](https://user-images.githubusercontent.com/31927084/230990475-572a3882-d7b0-4017-820a-290b52a733af.png)
