### ISSUE TITLE
Issues titles containing " or ' produce invalid branch names.

### ISSUE THREAD

**Issue by dipasqualew** [microsoft/vscode-pull-request-github#2117]
- Extension version: 0.19.0
- VSCode Version: 1.48.2
- OS: Ubuntu

Steps to Reproduce:

1. Create an issue with title containing `"` or `'`
2. Setup: `"githubIssues.issueBranchTitle": "${user}/${sanitizedIssueTitle}"`
3. Click on work on issue.

Git fails to checkout as `"`, `'` and more symbols  are not stripped out from the regex, see:
https://github.com/microsoft/vscode-pull-request-github/blob/master/src/issues/util.ts#L377

**Comment by RMacfarlane** [comment]
I'm not sure what you mean by "invalid branch names", I'm able to push and work with branches that have " or ' in the title. What happens when you try to use these branches?

**Comment by dipasqualew** [comment]
Did you try single or double quote?

```
$ git checkout -b test-"-branch
dquote> 
```

```
git checkout -b test-'-branch
quote>
```

But this more broadly applies to other symbols, such as `:`

```
g(master): git checkout -b test-:-branch
fatal: 'test-:-branch' is not a valid branch name.
```

I believe these are valid and common characters in issue titles and the branch based on their names fails at the moment.

PR #2118 should take care of all non-alphanumerical characters.

Cheers

**Comment by RMacfarlane** [comment]
I tried following the steps above, i.e. using the "start working on issue" button, with quote in the branch name. In that case, the name is a string and so seems to correctly escape the characters. Does it error for you when you try the original repro steps?

Other symbols such as `:` should already be handled by the line you linked: https://github.com/microsoft/vscode-pull-request-github/blob/d70ddbaebb7e4525f94fe975918ef15c5bba8cc5/src/issues/util.ts#L377

**Comment by dipasqualew** [comment]
Have you tried to set the following option in your `settings.json`?

```
    "githubIssues.issueBranchTitle": "${user}/${sanitizedIssueTitle}",
```

If the issue is named `Issue with ' character` this will be sanitised as `dipasqualew/Issue-with-'-character`; which will fail.

I think the regex should remove all characters outside of `[\w-]`. This ensures that there will only one `/` and it is also consistent with the same feature on GitLab.

I am not sure whether you environment (could be your OS?) allows for branch names with valid issue title characters. Mine (Ubuntu) doesn't.

Please note that the current regex does take care of `:` and `@` but it doesn't take care of many others, including `"`, `'`, `;`

**Comment by dipasqualew** [comment]
Another common character (at least form me) is `.` - It's reasonable to expect a full stop at the end of the issue title (just like this very issue, `Issues titles containing " or ' produce invalid branch names.`).

Clicking on `Start working on issue` produces:

```
Unable to checkout branch `$your-branch-name`. There may be file conflicts that prevent this branch change. Git error: undefined
```

That's because `git checkout $your-branch-name` fails as `$your-branch-name` may contain one or more invalid characters.

The regex I provided in my PR takes care of all invalid characters, transforming them to hyphens.

**Comment by dipasqualew** [comment]
I would love to use the extension, as it reproduces my preferred workflow on GitLab:

- Create an issue
- Create a branch based on the issue title
- Checkout & work on the issue

However at the moment the feature has been broken for me!
