### ISSUE TITLE
Commenting on PRs in Codespaces is quite broken

### ISSUE THREAD

**Issue by AArnott** [microsoft/vscode-pull-request-github#2127]
Very similar to #1864 (or perhaps that bug was never really fixed?)

**Repro steps**

Reviewing https://github.com/neuecc/MessagePack-CSharp/pull/988/files and clicked "Open with Codespaces" and got a new Codespace for myself.

The first comment I make asks whether to "add comment" or "start review". When I click "start review" the comment flickers for a while, then ends up still in an 'edit' mode with a Save button. When I click the save button, it just reveals that the comment is now *doubled* (one saved, and once more another in edit mode).

![brokencommenting](https://user-images.githubusercontent.com/3548/92983278-978ea580-f45f-11ea-83d0-54c220b17482.gif)

Also notice how broken the delete experience is. Deleting the 3rd deletes both 2nd and 3rd, and I can't delete the first no matter what I try.

![deletebroken](https://user-images.githubusercontent.com/3548/92982905-86dd3000-f45d-11ea-975e-944d88baee68.gif)

Link to https://github.com/microsoft/vssaas-planning/issues/2176

**Comment by burkeholland** [comment]
The initial failure as reported by the GraphQL toast seems to break the UI altogether. Items cannot be deleted. Save buttons still linger and pressing them appears to save and then duplicate the content.

**Comment by RMacfarlane** [comment]
It looks like the first comment is failing with "Resources not accessible by integration", so we must have a permissions problem in codespaces

**Comment by burkeholland** [comment]
This is occurring again with Nightly on Prod 7e73091

**Comment by burkeholland** [comment]
I'm not able to replicate this issue anymore.

**Comment by bamurtaugh** [comment]
Going to close since @burkeholland mentions he's not able to replicate anymore.
