### ISSUE TITLE
Clicking on entries in the changes view makes the tree always center the clicked item

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-pull-request-github#2132]
I do not see this behaviour e.g. with the explorer:

![recording](https://user-images.githubusercontent.com/900690/93230558-147b9100-f778-11ea-8af2-05debd774ac5.gif)

//cc @alexr00

**Comment by alexr00** [comment]
This appears to be intentional: https://github.com/Microsoft/vscode-pull-request-github/commit/7daef78abf06040b6280ec5caa4834d46ccce7ba

@RMacfarlane is this intensional?

**Comment by RMacfarlane** [comment]
Ah, the centering was not, this was a side effect of fixing https://github.com/microsoft/vscode-pull-request-github/issues/1270

**Comment by alexr00** [comment]
I can lo longer repro.
