### ISSUE TITLE
Duplicate commands 

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode-pull-request-github#2135]
- Extension version: v0.20.0
- VSCode Version: 1.49.0
- Commit: e790b931385d72cf5669fcefc51cdf65990efa5d
- OS: Mac

I am seeing duplicate commands from the GHPRI extension, happens when I reload too.

![image](https://user-images.githubusercontent.com/9721254/93383328-7946f200-f831-11ea-9cc8-a9ad93c7d931.png)

**Comment by RMacfarlane** [comment]
@sana-ajani Do you have both the nightly and stable version of the extension installed?

**Comment by sana-ajani** [comment]
oh silly me :) yup i do my bad!!
