### ISSUE TITLE
PR overview in sidebar

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode-pull-request-github#2136]
Below is a design exploration that places the PR overview into the sidebar using a combination of custom webviews and tree widgets. The main goal is to be able to view the details (commits, changes), write a review, and merge it. 

One of the questions that remains is whether we should promote exiting a review by placing it into a view or hide it within a context menu.

![image](https://user-images.githubusercontent.com/35271042/93420594-20448180-f864-11ea-8274-59830f5ea980.png)

Another thing I'm considering is being able to mark a file as "viewed" either via a right-click action or showing a ✔️ on hover that persists when clicked (cc @eamodio):

![image](https://user-images.githubusercontent.com/35271042/93421464-4703b780-f866-11ea-8764-e2b5e2571506.png)

**Comment by RMacfarlane** [comment]
This looks great! I like the idea of having the "Exit review" button be a context menu item, or an action that shows up on the view header. I really like the "viewed" checkmarks.

I started working on implementing a prototype of this, some additional thoughts:
- If I'm the author of a PR, I can only submit a "comment" review. I'm wondering if maybe we shouldn't show the text area and buttons at all in this case, or if we should just omit the "Approve" and "Request Changes" buttons
- Is it useful to display the reviewers and their status? (Possibly as a replacement to the text area when I'm the author?)
- Should there be a way to open the full description page from here?
- Weird case, but if I have multiple repos open, I could potentially have multiple PRs checked out at once. What should we display in this case?

**Comment by misolori** [comment]
Here's an updated version for the author where some actions are disabled (approving/requesting changes) and also showing reviewer status:

![image](https://user-images.githubusercontent.com/35271042/94281380-67391380-ff03-11ea-8f3f-1f0f9ab9599e.png)

**Comment by eamodio** [comment]
I feel like the "This branch has no conflicts with the base branch" indicator could be collapsed to just the icon and maybe moved to the right of the "merge" button? And then have the message show on hover? As it seems to take up a lot of space and not terribly useful until you are trying to merge
