### ISSUE TITLE
Getting "Fetching pull requests failed" message

### ISSUE THREAD

**Issue by gabog** [microsoft/vscode-pull-request-github#2144]
- Extension version: 0.20.0
- VSCode Version:
- OS: Windows 10

Steps to Reproduce:

1. Clone the https://github.com/microsoft/botframework-sdk repo
2. Go to the extension in VS Code and try to see the pull requests
3. VS Code will show an error saying 
_Fetching pull requests failed: Validation Failed: {"message":"The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them.","resource":"Search","field":"q","code":"invalid"}: The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them._:
![image](https://user-images.githubusercontent.com/12264946/93889138-d8d05200-fcb6-11ea-9e59-cb03a0ca0ba6.png)

It seems to be failing to create the categorized list because the All shows everything. 
![image](https://user-images.githubusercontent.com/12264946/93889351-17660c80-fcb7-11ea-8969-d385a3ee592f.png)

The categorized list of Issues works fine.
![image](https://user-images.githubusercontent.com/12264946/93889308-0b7a4a80-fcb7-11ea-8dcd-3246a3c658f1.png)

**Comment by scheric** [comment]
I am having the same error
Did you change anything in `githubPullRequests.queries` or `githubIssues.queries`

This does not give an error:
```json
    {
      "label": "participating open",
      "query": "is:open involves:${user}"
    },
```
This gives the error:
```json
    {
      "label": "participating open",
      "query": "is:open involves:${user} -author:${user}"
    },
```
full error:
```
[Info] GitHubRepository> Fetching all pull requests failed: HttpError: Validation Failed: {"message":"The listed users cannot be searched either because the users do not exist or you do not have permission to view the users.","resource":"Search","field":"q","code":"invalid"}
```

When using `is:open involves:{user} -author:{user}` in GitHub webpage it gives the result that I whant.

> `is open` AND `NOT author` AND (`assignee` OR `mentions` OR `commenter`)

**Comment by gabog** [comment]
I was able to get past this issue by signing out and signing back in from github.

Closing it.
