### ISSUE TITLE
Can't check out PRs while using WSL remote connection

### ISSUE THREAD

**Issue by maxwelldb** [microsoft/vscode-pull-request-github#2147]
Issue Type: <b>Bug</b>

With GitHub Pull Requests and Issues installed, on a system that uses WSL2 (Ubuntu) and VS Code:

1. View Pull Requests in the GitHub Pull Requests and Issues extension tab. 
2. Right click on a PR.
3. Click "Checkout Pull Request."
4. Wait. The PR is never checked out, and "Switching to Review Mode" spins forever at the bottom of the screen. 

Extension version: 0.20.0
VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:27:51.792Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2600 Six-Core Processor             (12 x 3394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (5.37GB free)|
|Process Argv|--crash-reporter-id 1747b875-2fc6-454b-bfdc-572e0002d65e|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|AMD Ryzen 5 2600 Six-Core Processor (12 x 3393)|
|Memory (System)|12.43GB (10.68GB free)|
|VM|0%|
</details>

**Comment by alexr00** [comment]
I'm not able to reproduce this issue.

**Comment by MattExact** [comment]
Could be related to VSCode / VSCode remote issues when using SSH keys with passphrases?
I had this issue, but realised I also could not sync / publish branches / ...,  whereas using the CLI worked fine.
Managed to fix this by adding keychain https://esc.sh/blog/ssh-agent-windows10-wsl2/
