### ISSUE TITLE
Unsaved comments are not persisted

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode-pull-request-github#215]
- Open a PR overview
- Start typing a comment
- Oh I forgot something, let me look at that file in another editor
- Come back to the editor that has the PR overview

All of my drafted comment is gone!!!

**Comment by jongio** [comment]
Absolutely need this.  
1. Drafts should be persisted automatically
2. If not #1, then warn user that comment will be lost.

**Comment by bessey** [comment]
I would go further and say without this, the main benefit of this extension; being able to truly explore the codebase while reviewing, is completely undermined. At least on GH I can scroll between PR files while writing a comment, with this extension I can't even look at a single other file!

**Comment by RMacfarlane** [comment]
@rebornix has fixed this: https://github.com/Microsoft/vscode/pull/61757

The fix was in the core of VSCode, so this should work in versions 1.29.0 and up
