### ISSUE TITLE
"Organization access" not showing up

### ISSUE THREAD

**Issue by jaunt** [microsoft/vscode-pull-request-github#2150]
- Extension version: V0.20.0
- VSCode Version: 1.49.1
- OS: Linux Mint 20

Steps to Reproduce:

1.  Add extension and authenticate with github following this guide:  https://code.visualstudio.com/docs/editor/github
2.  Verified that I can clone my personal repositories in vscode.  
3.  Of course I can't yet see my organisation repos. 
2.  From my github account, go to settings / applications / Authorized OAuth Apps
3.  Click on "Github For VSCode"
4.  I see the correct permissions, but "Organisation access" does not show up, so I can't request access.
5.  Sanity check:  When I go to another oath app, for example Smartgit, I do see the "Organization Access" section and can request authorisation without problem. 

![noaccess](https://user-images.githubusercontent.com/5732995/94049410-d12dad80-fd89-11ea-81e9-109348a87f35.png)

**Comment by Salzian** [comment]
I have the same issue. Also when trying to clone a repository using Remote-Containers, I cannot authorise my organisation anymore. Is this a problem with the registered GitHub app?

**Comment by RMacfarlane** [comment]
The GitHub OAuth app we're using was created by GitHub when this project started, and is a first party app. I believe first party apps are granted organizational access by default.

GitHub plans to eventually deprecate the auth server that we're using that uses this app, and then we will likely transition to our own oauth app. Until then, I think this is expected behavior

**Comment by mniemczyk** [comment]
I've the same issue. I can't access my repositories which have been created in organization with from my private github profile. The 3rd party apps policy in organization settings has been set to "no resitrctions" but repos are still not visible in VSC.

**Comment by etola** [comment]
same issue here

**Comment by lucasraziel** [comment]
Why is this issue closed?

**Comment by florianajir** [comment]
no workaround for organisations access to repo ?

**Comment by florianajir** [comment]
+1

**Comment by jmorris-dev** [comment]
> The GitHub OAuth app we're using was created by GitHub when this project started, and is a first party app. I believe first party apps are granted organizational access by default.

This belief is probably mistaken given that Github is not granting organizational access to the extension.

>Until then, I think this is expected behavior

To clarify, you believe the Github extension not having access to organization repos that our accounts have access to is expected behavior?

**Comment by vadrif-draco** [comment]
Why is this issue closed?!

**Comment by jacob-monarch** [comment]
Any news?

**Comment by veikkoruuskanen** [comment]
I also would need a solution for this.

**Comment by ghubjason** [comment]
Running into the exact same issue.  There isn't an option to see your organizational repositories with the extension.  You can only interact and see them if you've already either manually cloned the repository via command line, or another UI tool.  Seems shortsighted to close this issue when the support doesn't actually exist.

**Comment by artem-v-shamsutdinov** [comment]
Just tried - when I authorize Organizations do not show in the "from GitHub" list.  But when I clone an organization repo via a URL I'm able to push changes to it.

**Comment by makerovski** [comment]
Why is this closed ?I have the same issue

**Comment by greemo** [comment]
This is also an issue for me. This should not be closed.

**Comment by pbley-sbi** [comment]
same here...

**Comment by AllanOricil** [comment]
I have the same problem. Im part of an Organization and I cant see the PR's or Issues they open from VSCode. Can someone reopen this, please.

**Comment by yaronhay** [comment]
Same here

**Comment by pshroti** [comment]
This should not be a closed issue. I am still running into this issue.

**Comment by TheByrd92** [comment]
I too have this issue. Is this expected behavior or not?

**Comment by prodkt** [comment]
We have the same issue.

**Comment by TUNBudi06** [comment]
I think,for the solution now just input the link(of repository from your organization) in code space.


I tryed and its works.

**Comment by TUNBudi06** [comment]
I thought the repo you have in another organization Will not show up(except your repo in your account) until you put the link on it 
That Will give access but before make sure do You have to access that repo as owner or maintener

**Comment by Sherbb** [comment]
This can still happen today. I as able to resolve it by signing out of accounts in vscode. Then signing back in using the `gitlense` sign in option.

![image](https://github.com/microsoft/vscode-pull-request-github/assets/13370191/38947aaf-7f15-4fad-a97c-2dd4ddd6077e)

**Comment by khaledmahmoud78** [comment]
If you mean that you can't access your owned organization repos from VS Code.
I have the same issue.
The only solution that I found is adding myself to each repo in the organization as a collaborator!
