### ISSUE TITLE
Inline issue completion not working

### ISSUE THREAD

**Issue by ryanaklein** [microsoft/vscode-pull-request-github#2151]
- Extension version: v0.20.0
- VSCode Version: 1.49.1
- OS: macOS Catalina 10.15.6

Steps to Reproduce:

1. Using the steps suggested at https://github.com/microsoft/vscode-pull-request-github/blob/master/documentation/IssueFeatures.md#issues I am unable to get issue completion suggestions.

![image](https://user-images.githubusercontent.com/3856027/94051521-a2bdcb80-fda5-11ea-8f38-93dd4ac6855e.png)
![image](https://user-images.githubusercontent.com/3856027/94051495-99346380-fda5-11ea-9095-9b814e3905b7.png)

I did update the queries to be

```json
    "githubIssues.queries": [

        {
            "label": "Issues",
            "query": "state:open repo:${owner}/${repository} sort:created-desc"
        }
    ]
```

I do see all the open issues for a given repository in the side bar. If I manually type in an issue number, hovering does work.

The docs mention milestones, which we don't use, but I put an issue in a milestone to test it out and still was not getting an issue. I tinkered with quite a few settings including the queries and triggers but wasn't able to get anything to work. I also tried disabling other extensions that might interfere with code completion.

I can't confirm the last time it worked for me. I used the feature a few months ago but this is the first time I've come back to it in a while.

User suggestions do work for me. 

![image](https://user-images.githubusercontent.com/3856027/94051296-57a3b880-fda5-11ea-99e9-93cf5d2ad90d.png)

**Comment by alexr00** [comment]
There were a couple places (untitled files and files not available on your remote for example) that issues didn't use to show. These have since been fixed.
