### ISSUE TITLE
File system provider should contribute a label formatter

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-pull-request-github#2153]
That makes it clear where the resource is from. I was wondering what these entries are with relative paths in my quick open:

![image](https://user-images.githubusercontent.com/900690/94120202-28965100-fe50-11ea-9d98-de04b10fc485.png)

Turns out they originate from opening diffs from the GH PR extension. I would suggest to contribute a label formatter that makes it clear where these are coming from. Compare with how the git diff does it:

![image](https://user-images.githubusercontent.com/900690/94120332-46fc4c80-fe50-11ea-8361-8790f11d418e.png)

**Comment by alexr00** [comment]
We have this now.
