### ISSUE TITLE
Does this work with private repository

### ISSUE THREAD

**Issue by Ortega-Dan** [microsoft/vscode-pull-request-github#2155]
I've been trying but I don't see a way to achieve it and I don't see documentation about it.
(I'm using an Ubuntu machine, and even when the Github integration asks for control of private repositories, this doesn't work on private repos.)

I will appreciate response.

**Comment by dav3ku** [comment]
Si es funcional con repositorio privados. ¿te manda algún tipo de mensaje al momento iniciar sesión?

**Comment by RMacfarlane** [comment]
This should work with private repos, can you describe what you are seeing that doesn't work?

**Comment by RMacfarlane** [comment]
Closing this issue since it's been open for a while without any response. If you're still seeing an issue, please respond back with the version of the extension and vscode you are using, and a description of the problem. Thanks!

**Comment by Ortega-Dan** [comment]
Thanks, sorry I forgot about it ...
It just doesn't pull any information
Here a snippet:
![image](https://user-images.githubusercontent.com/24926168/100011950-7d970a80-2da0-11eb-80cd-29f8c46070e9.png)

(should I open a new issue [and commit to answer promptly] ?)

Will appreciate response.

What logs should I look at ?

**Comment by Ortega-Dan** [comment]
I also disabled all other extensions and reloaded. Still not bringing anything.

**Comment by Ortega-Dan** [comment]
Just got the error line in the log:
[Info] GitHubServer> No response from host https://ssh.github.com/ortega-dan/testing-project-name: write EPROTO 57015591881800:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:

**Comment by Ortega-Dan** [comment]
I just found out what was going on ...
I had the following information in my ~/.ssh/config file:

Host github.com
	Hostname ssh.github.com
	Port 443

Which was added for an issue I had before with something else.

Once removed it worked like a charm.

Very nice extension.
