### ISSUE TITLE
Activating extension failed

### ISSUE THREAD

**Issue by dbanisimov** [microsoft/vscode-pull-request-github#2168]
- Extension version: v0.20.0
- VSCode Version: 1.50.0-insider
- OS: Windows 10 x64  10.0.20221

Steps to Reproduce:

GitHub extension sidebar is not showing any issues or pull requests. DevTools console contains an error message:
```
Activating extension 'GitHub.vscode-pull-request-github' failed: t.onDidChange is not a function.
```

First appeared when installed in WSL remote, but also checked when running locally - same issue with the same error in the console.

**Comment by RikkiGibson** [comment]
For those blocked by this issue, please note this comment: https://github.com/microsoft/vscode/issues/107462#issuecomment-700921943

Installing the [nightly build](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github-insiders) gets the extension working in Insiders again.

**Comment by RMacfarlane** [comment]
There were some breaking changes in one of the APIs we're using, I've published v0.20.1 of the extension with the fix

**Comment by bm-stschneider** [comment]
Seems to work again 👌

**Comment by alexandremsouza1** [comment]
![image](https://user-images.githubusercontent.com/38253342/96049008-ced0e780-0e4d-11eb-8ff2-e5ccd9700116.png)

Failed on debug.

version: master 
git log last commit 
![image](https://user-images.githubusercontent.com/38253342/96049169-02137680-0e4e-11eb-9273-43957fe014a7.png)

**Comment by Asitkumar6205** [comment]
How to resolve this -->
                Activating the Pull Requests and Issues extension failed. Please make sure you have git installed.

**Comment by hermosir** [comment]
> How to resolve this -->
> Activating the Pull Requests and Issues extension failed. Please make sure you have git installed.

I'm also getting this error.  

Currently running: VScode version 1.58.0

**Comment by wavypng** [comment]
Any fix to this?

**Comment by Alladio** [comment]
me too
![image](https://user-images.githubusercontent.com/13860253/126022990-377fa348-b4ee-4c4b-9fb1-21a4433d5470.png)

**Comment by Alladio** [comment]
Guyss...

I'm install that: https://desktop.github.com/

And after that i put the path variables in edit system variables(Windows)

![image](https://user-images.githubusercontent.com/13860253/126023675-a7b29b29-3319-4447-b602-088a8edfdbc2.png)

**Comment by Jesseeka2001** [comment]
> How to resolve this -->
> Activating the Pull Requests and Issues extension failed. Please make sure you have git installed.

same issue

**Comment by Alladio** [comment]
> 
> 
> > How to resolve this -->
> > Activating the Pull Requests and Issues extension failed. Please make sure you have git installed.
> 
> same issue

https://github.com/microsoft/vscode-pull-request-github/issues/2168#issuecomment-881807595

do you try?
do you need do that after the installation.

**Comment by Jesseeka2001** [comment]
> > > How to resolve this -->
> > > Activating the Pull Requests and Issues extension failed. Please make sure you have git installed.
> > 
> > 
> > same issue
> 
> [#2168 (comment)](https://github.com/microsoft/vscode-pull-request-github/issues/2168#issuecomment-881807595)
> 
> do you try?
> do you need do that after the installation.

yes I tried this, it didn't work 
I downloaded git for windows (not github), and this worked for me 
thanks anyway

**Comment by Asitkumar6205** [comment]
> > > > How to resolve this -->
> > > > Activating the Pull Requests and Issues extension failed. Please make sure you have git installed.
> > > 
> > > 
> > > same issue
> > 
> > 
> > [#2168 (comment)](https://github.com/microsoft/vscode-pull-request-github/issues/2168#issuecomment-881807595)
> > do you try?
> > do you need do that after the installation.
> 
> yes I tried this, it didn't work
> I downloaded git for windows (not github), and this worked for me
> thanks anyway

Thanks, After downloading git, this error doesn't occur.

**Comment by pstanczak** [comment]
Make sure you are not in a restricted mode workspace.

**Comment by TidusWulf** [comment]
I downloaded and installed Git for Windows and this problem went away for me (VS Code version 1.61.1)

**Comment by mankey0** [comment]
Activating extension 'GitHub.vscode-pull-request-github' failed: t.onDidChange is not a function.

**Comment by vivekkumartiwari79** [comment]
I also getting Same problem

**Comment by Bruce-Jay** [comment]
> > > > How to resolve this -->
> > > > Activating the Pull Requests and Issues extension failed. Please make sure you have git installed.
> > > 
> > > 
> > > same issue
> > 
> > 
> > [#2168 (comment)](https://github.com/microsoft/vscode-pull-request-github/issues/2168#issuecomment-881807595)
> > do you try?
> > do you need do that after the installation.
> 
> yes I tried this, it didn't work I downloaded git for windows (not github), and this worked for me thanks anyway

Thank you!!!
After downloading the git again, the problem is solved immediately.

**Comment by cesareressa** [comment]
I got the same issue with MacOS Ventura. I solved it by reinstalling git.

**Comment by mrf** [comment]
For anyone else stuck here for some reason my vscode had the built in github authentication extension that this one depends on disabled. Good to check that before you spend hours on this issue like I did!
