### ISSUE TITLE
Fetching pull requests failed of authentication

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-pull-request-github#2170]
Issue Type: <b>Bug</b>

`Fetching pull requests failed: The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them.`

Ran into this in VS Code repo, not sure if it's because of SSO.

Extension version: 2020.9.39859
VS Code version: Code - Insiders 1.50.0-insider (772aa0723f7f6b04b710bc3a92b7a904b60ef439, 2020-09-28T05:41:42.988Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|32.00GB (1.10GB free)|
|Process Argv|-psn_0_18149710 --enable-proposed-api ms-vscode.vscode-notebook-history --enable-proposed-api vscode.notebook-editing --crash-reporter-id 1a907bbd-fa02-4595-81e0-63e1648afb31|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by alexr00** [comment]
Looks like it is because of SSO. If you are using a personal access token then you must enable SSO for that token in your GitHub access tokens settings.
