### ISSUE TITLE
Duplicated actions between PULL REQUESTS view and ISSUES view

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#2175]
![Screenshot 2020-09-29 at 15 07 37](https://user-images.githubusercontent.com/1926584/94562389-9209cb80-0265-11eb-917b-163a477328b8.png)

For example the Configure and the Reload view could live top level on the Viewlet action bar. Currentyl these actions live both on the PULL REQUEST view and the ISSUES view bringing unneeded details to an already hectic view.

**Comment by alexr00** [comment]
The only action that makes sense to move to the viewlet level is the Refresh. The configure and add actions are both very specific to either issues or PRs. However, splitting the refresh into issues and PRs is nice so that you are only refreshing the ones that you want to refresh (I usually only care about refreshing either issues or PRs, not both at the same time).

@RMacfarlane what do you think here?

**Comment by RMacfarlane** [comment]
My usual use case for refreshing one of the views is that I know some data on GitHub has changed, like I've assigned myself an issue and I want the issues view to be updated. So I think my preference is for keeping them separate, but I don't feel too strongly about it

**Comment by alexr00** [comment]
We will keep them separate then.
