### ISSUE TITLE
Changes in pull request: provide option to see changes as flat list

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-pull-request-github#2177]
Testing #2136

Similar to how the changes view in SCM can toggle between flat list and tree:

![image](https://user-images.githubusercontent.com/900690/94563319-d8abf580-0266-11eb-83ff-39dad0b5c000.png)

**Comment by RMacfarlane** [comment]
There is currently a setting to do this (`githubPullRequests.fileListLayout`), we should an action to toggle it like in the SCM view

**Comment by ejkim1996** [comment]
Hi, I'd like to do my first contribution here, if someone could tell me where to look I'd really appreciate it. Thanks!

**Comment by RMacfarlane** [comment]
Thanks @ejkim1996 for looking at this!

Two things need to be added for this:
- A new `command` that will [update](https://github.com/microsoft/vscode/blob/c13678f258248b38570ef08311047d29d40d9c45/src/vs/vscode.d.ts#L4858) the setting
- An icon at the top of the "Changes in Pull Request" view that triggers this command

You can look at the `commands.ts` file for some examples of adding commands and add this one there as well. You will also need to add it in the `package.json`, and then add it to the `view/title` section there. `pr.refreshChanges` is an example of a command that shows up on the "Changes in Pull Request" view.

**Comment by ejkim1996** [comment]
Thank you for the details @RMacfarlane!
I have quite a busy week at work, but I'll probably be able to get started on it sometime next week.
