### ISSUE TITLE
Focus mode: do not offer a merge button

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-pull-request-github#2178]
Testing #2136

I somehow feel that the webview in focus mode should not allow to merge the PR. I feel the task at hand is to review the changes, not merge them. I would leave merging to when the PR is opened.

![image](https://user-images.githubusercontent.com/900690/94563536-21fc4500-0267-11eb-8ffa-9192984bdf3b.png)

**Comment by bpasero** [comment]
I would also leave this out:

![image](https://user-images.githubusercontent.com/900690/94563899-9fc05080-0267-11eb-8413-9e7a66ab3762.png)

**Comment by alexr00** [comment]
I would say that merging a PR is part of my PR review process. I often merge from focus mode and would miss having the action there.
