### ISSUE TITLE
Font size should respect my editor font size

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode-pull-request-github#218]
Just filling this because on my large montior I have an increased font size for my editor.
However when using the pull request extension I noticed how the font used if too small.

I suggest to try to respect the editor.fontSize since the webView is a similar experience to the editor from a visual perspective

**Comment by rebornix** [comment]
@misolori can you help on this?

**Comment by roblourens** [comment]
The editor fontSize doesn't affect the fontsize anywhere else in the product. You can use zoom, or maybe a different fontSize setting is needed for UI.

**Comment by isidorn** [comment]
@roblourens the default size is probably already our default editor size (if that is not the case it should be fixed). Editor fontSize does not affect anything else in the product becuase it might break different ux rendering, here it might just work.
imho the extension can be released without this fix and we can wait for more feedback

**Comment by misolori** [comment]
I agree with @roblourens, we don't increase the font size outside of the editor. See below where the editor font size is set to `16px` but the extension view remains the same:

![image](https://user-images.githubusercontent.com/35271042/44414059-b2f98180-a521-11e8-8eac-4fb09734c66f.png)


If we get more requests for this then we can re-visit it.
