### ISSUE TITLE
blurry activity bar icon

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-pull-request-github#2180]
![image](https://user-images.githubusercontent.com/8586769/94579936-2ce6b380-022e-11eb-8004-e2571d623983.png)

icon looks much more pixelated than any of the others on my bar.

**Comment by alexr00** [comment]
It looks like codicons won't be supported there yet: https://github.com/microsoft/vscode/issues/106348
I will revert back to svgs for the release

**Comment by misolori** [comment]
I believe I updated the logo to a larger version via https://github.com/microsoft/vscode-pull-request-github/commit/8672e9815dbb316046bc4ef33028c62daaed7e29

![image](https://user-images.githubusercontent.com/35271042/95257309-f8986780-07d8-11eb-84ac-c0b21c1ab14f.png)

**Comment by JacksonKearl** [comment]
lgtm
