### ISSUE TITLE
Polish drop down button look

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-pull-request-github#2181]
Testing #2165

Windows, PR extension version  v2020.9.41222

![image](https://user-images.githubusercontent.com/6461412/94584606-25032f80-027f-11eb-8706-e3cca69dfd69.png)

**Comment by RMacfarlane** [comment]
Fixed with https://github.com/microsoft/vscode-pull-request-github/commit/46dcfc34dad4951fe948b97763c33ba367473c0f
