### ISSUE TITLE
Focused WebView view does not obviously show the result of my actions

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode-pull-request-github#2183]
Testing #2136

Repro Steps:

1. Write a comment in the focused mode webview view
2. Click request changes

I would like to see my name and status underneath showing that I have requested changes.

**Comment by RMacfarlane** [comment]
Added as part of https://github.com/microsoft/vscode-pull-request-github/commit/38e7347da0c7e3f9cf4735b000065013c11c6ec9
