### ISSUE TITLE
Codespaces: Created issues is empty?

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-pull-request-github#2185]
Using build 2020.9.41222 on codespaces (disabled stable), I'm unable to see this issue https://github.com/JacksonKearl/mixedCase/issues/2 in the created issues tree... it shows up fine in desktop. I tried out a few custom query strings, and I only seem to get any results with "default"

**Comment by NotMyself** [comment]
Just wanted to pop in and say I'm encountering this issue s as well.

Here are the GitHub Pull Request Log Messages:

```bash
[Info] /home/codespace/.ssh/config: ENOENT: no such file or directory, open '/home/codespace/.ssh/config'
[Info] Looking for git repository
```

**Comment by rzhao271** [comment]
I get the same log messages as NotMyself. Attached a pic:
![no-issues](https://user-images.githubusercontent.com/7199958/94856462-e25b6780-03e4-11eb-9b0c-cad471d36bb4.PNG)
