### ISSUE TITLE
"Pending" label is not centered

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-pull-request-github#2196]
I was using web:

![image](https://user-images.githubusercontent.com/900690/95174091-dd6a2f80-07b9-11eb-9831-b14f42b14ef2.png)

**Comment by alexr00** [comment]
Looks like this has been fixed in the mean time:

![image](https://user-images.githubusercontent.com/38270282/142457874-980ebb17-00ee-4f14-8c74-0b445353e833.png)
