### ISSUE TITLE
Issue Creation Docs

### ISSUE THREAD

**Issue by benedikt-mayer** [microsoft/vscode-pull-request-github#2197]
While creating issues with the extension, I tried finding documentation on its syntax in the [wiki](https://github.com/microsoft/vscode-pull-request-github/wiki) and elsewhere.

Questions I had were: Is there a way to add not only assignees and labels, but also projects and milestones?
AFAIK there is no mention that creating issues from something that isn't a TODO etc. is something the extension provides.

A short documentation on creating issues and the syntax would thus be great!

**Comment by cool-delete** [comment]
@alexr00 
How can I modify the content in the newIssue.md file to specify that the current issue belongs to an existing Milestone?

I tried to typed this, but it didn't work
![image](https://user-images.githubusercontent.com/13638610/113590775-a213c500-9665-11eb-8852-00bee6b598f1.png)

**Comment by alexr00** [comment]
Adding a milestone isn't a feature we have right now. Please see the new issue creation documentation: https://github.com/microsoft/vscode-pull-request-github/blob/main/documentation/IssueFeatures.md#creating-an-issue

**Comment by cool-delete** [comment]
> Questions I had were: Is there a way to add not only assignees and labels, but also projects and milestones?
> AFAIK there is no mention that creating issues from something that isn't a TODO etc. is something the extension provides.
@alexr00 
OH sorry 
I saw you closed this issue, so I think the pull-request should have this feature
