### ISSUE TITLE
Order of buttons different than on GitHub

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode-pull-request-github#220]
We changed how the buttons are ordered compared to GitHub.
What is the reasoning behind this?
I suggest that they should be the same since some users are used that the far right means ok, far left not ok. For us it seems to be the opposite

![screen shot 2018-08-16 at 16 53 14](https://user-images.githubusercontent.com/1926584/44216283-e086a980-a174-11e8-9054-b6ba7bc5c169.png)

![screen shot 2018-08-16 at 16 53 33](https://user-images.githubusercontent.com/1926584/44216317-ec726b80-a174-11e8-89c4-ce68a1779bbc.png)

**Comment by RMacfarlane** [comment]
Two buttons have been added and comment is now on the right side:

![screen shot 2018-08-16 at 11 15 06 am](https://user-images.githubusercontent.com/3672607/44354175-effc4000-a45d-11e8-9d7d-297a80d8240f.png)

GitHub has also pulled their `Comment` button all the way to the right now
![screen shot 2018-08-20 at 9 47 11 am](https://user-images.githubusercontent.com/3672607/44354200-086c5a80-a45e-11e8-8092-f9cae67ecef8.png)
