### ISSUE TITLE
Tab Labels are/really/quite/long

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-pull-request-github#2204]
I'd expect the tab to just have the basename but it seems to include the entire path.

![image](https://user-images.githubusercontent.com/8586769/95522999-69c74e80-0982-11eb-8891-0f339464b21e.png)

**Comment by RMacfarlane** [comment]
Closing as a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/952
