### ISSUE TITLE
Whole commit line should be clickable not only commit hash

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-pull-request-github#221]
In the description view of the PR if there is a commit attached, it is only possible to click on the commit hash to follow that commit.
instead the whole commit line should be clickable (just like on github)

![screen shot 2018-08-16 at 16 54 35](https://user-images.githubusercontent.com/1926584/44216451-42471380-a175-11e8-85ec-f154ba826be4.png)

**Comment by tobudim** [comment]
Hi, I'd like to do my first contribution here, if someone could tell me where to look. Thanks!

**Comment by RMacfarlane** [comment]
Thanks @tobudim! Here's a pointer to the code that renders the commits:
https://github.com/microsoft/vscode-pull-request-github/blob/master/preview-src/timeline.tsx#L39-L50

**Comment by tobudim** [comment]
Superb! Thank you for your help, I'm working on this then.

**Comment by tobudim** [comment]
[I did a pull request](https://github.com/microsoft/vscode-pull-request-github/pull/1260), I don't know if I did it well since it does not appear here.
Thanks for your guidance @RMacfarlane . Please tell me if I did right!
