### ISSUE TITLE
"… updates … for this pull request" notification displaying inappropriately

### ISSUE THREAD

**Issue by smarts** [microsoft/vscode-pull-request-github#2214]
If you're a user that rebases and force-pushes branches, it's annoying to keep seeing the "There are updates available for this pull request" notification because, while the notification is technically accurate, the updates are on your machine, not on `origin`. I.e., you wouldn't want to hit that **Pull** button on the notification.

**Comment by alexr00** [comment]
This should have already been improved with https://github.com/microsoft/vscode-pull-request-github/issues/3479

Also, there's a setting to not get prompted about this ever: `"githubPullRequest.pullBranch": "never"`
