### ISSUE TITLE
Focused mode: Select file in tree when diff opens

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode-pull-request-github#2219]
Issue Type: <b>Bug</b>

Currently, when a PR is checked out when the `githubPullRequests.focusedMode` setting is enabled, the first diff in the PR also gets opened. I think this should also highlight that file in the "Changes in Pull Request" tree, if possible, to make it clear what just opened.

Extension version: 2020.10.28261
VS Code version: Code - Insiders 1.51.0-insider (13b3c937dc5e3816c79bdd2cdf2cdf6f9c727b75, 2020-10-20T05:54:40.178Z)
OS version: Darwin x64 18.7.0

**Comment by alexr00** [comment]
This has since been fixed.
