### ISSUE TITLE
Checkout failed when there ssh key passphrase required

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-pull-request-github#222]
When using ssh, there are chances that a passphrase for ssh private key is required when doing checkout/pull/push/etc

```
Review> checkout failed #"git@github.com: Permission denied (publickey).\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n"
```

**Comment by rebornix** [comment]
I think this one is similar to https://github.com/Microsoft/vscode/issues/13680, @joaomoreno any idea how we can easily workaround this issue?

**Comment by joaomoreno** [comment]
No workaround on our side so far. Users should add key to agent.

**Comment by bkmeneguello** [comment]
I'm having this problem. My key was added to the agent but is still asking for username/password to checkout the PR.

**Comment by alexr00** [comment]
Closing as the upstream issue is closed.
