### ISSUE TITLE
Error when editing comment right after leaving it

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-pull-request-github#2221]
- Open a PR (in a codespace)
- Leave a comment on a review
- Immediately edit that comment
- Got this error

![image](https://user-images.githubusercontent.com/323878/96754702-82723400-1386-11eb-8d69-bea0c30d0aad.png)

```
GraphQL error: Could not resolve to PullRequestReviewComment node with the global id of 'MDEyOklzc3VlQ29tbWVudDcxMzcyNzE3NQ=='.
```

**Comment by alexr00** [comment]
I can no long reproduce this.
