### ISSUE TITLE
Markdown IntelliSense hangs at "Loading..."

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode-pull-request-github#2224]
- Extension version: v0.20.1
- VSCode Version: 1.50.1 (stable), 1.50 (insiders)
- OS: Windows 10

Steps to Reproduce:

1. Open a Markdown file in the editor
2. Try to open IntelliSense with Ctrl+space bar

IntelliSense hover stuck at "Loading..."

![image](https://user-images.githubusercontent.com/12818376/96904030-6edcd100-144b-11eb-8da7-30fd8dae40ba.png)

Does not reproduce without the GHPR extension installed.

**Comment by gregvanl** [comment]
One workaround is to add a space to the line and then IntelliSense and snippets are displayed.
Seems to be an issue only if the cursor is at the beginning of a line

**Comment by alexr00** [comment]
Looks like something has fixed this in the mean time.
