### ISSUE TITLE
Show issue discussion similar to PR discussion

### ISSUE THREAD

**Issue by nopeslide** [microsoft/vscode-pull-request-github#2229]
The `Description` view for PRs is great, but I'm missing the same feature for issues.
Issues may shift in content with the ongoing discussion and just seeing the initial post is insufficient.
Furthermore, being able to assign tags, persons, ... would not force everyone to open github again.

**Comment by alexr00** [comment]
Closing as we have no plans to support this at this time!

**Comment by jhpratt** [comment]
@alexr00 Out of curiosity, is there any particular reason why not? I would find it quite useful.

**Comment by alexr00** [comment]
Copying the GitHub UI in a webview in this extension is an endless game of catch up: we're never going to have feature parity with github.com. We wanted to bring the "most useful for coding" part of of issues into the editor, and showing an issue overview page just doesn't make the cut!
