### ISSUE TITLE
User alias autocomplete in file comments

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode-pull-request-github#223]
As title, I found this pretty annoying when writing comments in description page, without autocomplete, I'm not sure if I'm writing the user alias.

**Comment by rebornix** [comment]
@shana do you know if we have API for this feature? On GitHub website, when we type in a comment box, we can get proper username suggestions related to this project/issue/org.

**Comment by RMacfarlane** [comment]
Done with https://github.com/Microsoft/vscode-pull-request-github/commit/9efc362b865dc7767d9a5bec75e4e5c335d615c0#diff-4c377281588b3e01e164412d5a23724a
