### ISSUE TITLE
Failing to activate extension

### ISSUE THREAD

**Issue by GrayJack** [microsoft/vscode-pull-request-github#2231]
- Extension version: 0.20.0
- VSCode Version: 1.50.1
- OS: Linux 5.9.X x86_64

Steps to Reproduce:

1. Open the VSCode
2. Open developer tools
3. Get a error with message `'GitHub.vscode-pull-request-github' failed: t.onDidChange is not a function.`

**Comment by RMacfarlane** [comment]
@GrayJack Are you able to update to extension version 0.20.1? This should fix this problem.

The issue is that this extension uses some of the proposed APIs from VSCode, which are subject to change. Parts of the file decoration API were renamed in VSCode 1.50.1, which was a breaking change

**Comment by GrayJack** [comment]
My VSCode is not showing a update version 0.20.1. Should I install from git?

**Comment by ChaDonSom** [comment]
Huh, I seem to be having this same issue using `cdr/code-server@3.6.1` which uses vscode `1.50.0` and my Github pull requests extension is version `0.20.0`.

However, I do have vscode `1.50.1` installed alongside code-server on the machine code-server runs on, and I also have `1.50.1` installed on the machine I access code-server on.

**Comment by ChaDonSom** [comment]
Manually updating my extension to `0.20.1` fixed it :+1:

**Comment by GrayJack** [comment]
Hi, I never had to do a manual update with VSCode, how do I do that?

**Comment by RMacfarlane** [comment]
I'm not sure why it wouldn't be automatically updating, can you check your "Extensions: Auto Check Updates" and "Extensions: Auto Update" settings? If you go to the extensions view, do you see an update button for it?
<img width="400" alt="Screen Shot 2020-10-28 at 9 02 32 AM" src="https://user-images.githubusercontent.com/3672607/97463022-8e1ca800-18fc-11eb-80f1-5c7ffac5c132.png">

If not, another option is to download the extension from https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github and then run "Extension: Install from VSIX..." in VSCode.

**Comment by ChaDonSom** [comment]
I went to [the extension's page on Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github) and hit the 'Download Extension' link,

Then, from inside VS Code, I opened my extensions panel, hit the 3-dot menu in the top right, and clicked 'Install from VSIX...'

Yes, what @RMacfarlane said.

With `cdr/code-server`, they maintain their own extension store that just scrapes Marketplace. Could be their crawler hasn't found the update yet.

**Comment by GrayJack** [comment]
> I'm not sure why it wouldn't be automatically updating, can you check your "Extensions: Auto Check Updates" and "Extensions: Auto Update" settings? If you go to the extensions view, do you see an update button for it?
> <img alt="Screen Shot 2020-10-28 at 9 02 32 AM" width="400" src="https://user-images.githubusercontent.com/3672607/97463022-8e1ca800-18fc-11eb-80f1-5c7ffac5c132.png">
> 
> If not, another option is to download the extension from https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github and then run "Extension: Install from VSIX..." in VSCode.

It is set to check for updates automatically, and I also tried to manually request for updates, and it just says that all extension are up-to-date =/

But thanks, will do that way

**Comment by GrayJack** [comment]
Yeah, manually updating worked out, not sure why it didn't show up though

Thanks a bunch, I think this issue can be closed now
