### ISSUE TITLE
"Open" should be the default PR query

### ISSUE THREAD

**Issue by burkeholland** [microsoft/vscode-pull-request-github#2233]
Found in https://github.com/microsoft/vssaas-planning/issues/1529 -> https://github.com/microsoft/vssaas-planning/issues/2176

Currently, there is no default query for "Open" PR's. Given that is the default in GitHub, it should be a default query as well. Otherwise "All" is the only view that lets you see PR's and non-power users won't know to adjust the query.

**Comment by RMacfarlane** [comment]
Currently, the "All" category does actually filter to only open PRs. Perhaps we should just rename it to "All Open"?

**Comment by RMacfarlane** [comment]
Related https://github.com/microsoft/vscode-pull-request-github/issues/1777

**Comment by RMacfarlane** [comment]
@burkeholland I renamed the category, let me know if you see any issues with it showing stale closed or merged PRs. Thanks!
