### ISSUE TITLE
Cannot use extension for web anymore due to auth issues

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-pull-request-github#2234]
I am using the GH PR nightly extension in web (locally) and it worked fine up until last week I think. There are really 2 bugs here:

**Wrong Scopes**
I see the following error for a token I was using just fine before:

```
Sign in failed: Error: The provided token is does not match the requested scopes: read:user repo user:email
```

This is a token that has full `user` and `repo` rights. I can only get away with this error if I specifically only pick those scopes asked but not the parent ones. Something is wrong with checking the scopes I think.

**Failed to show PRs**
Even when I pick the right access token, I am eventually greeted with this error trying to show the PRs assigned to me:

```
Fetching pull requests failed: The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them.
```

I have to use VSCode desktop to get around this.

**Comment by alexr00** [comment]
@RMacfarlane I took a look at this, and its coming from the auth extension. Since I figured out what's going on, I'll just make a PR for you :)

**Comment by bpasero** [comment]
@alexr00 will this also fix the issue that I cannot see PRs anymore in web? I am not entirely sure the scope fix fixes the other too.

**Comment by alexr00** [comment]
No, I am looking into that part now.

**Comment by alexr00** [comment]
@bpasero, for not seeing PRs assigned to you when you use a personal access token you must enable SSO for you token. This can be done from the GitHub personal access token settings page.

**Comment by bpasero** [comment]
@alexr00 wow that's it! I guess we cannot help the user here?

**Comment by alexr00** [comment]
I will have to defer to @RMacfarlane for whether we can do anything else. We can certainly display a more helpful message.

**Comment by RMacfarlane** [comment]
I think there may be a header we get on a 401 that will tell us if SSO is missing. Will look into this more next month
