### ISSUE TITLE
Sign in popup never showed up - Unable to push code "Invalid username or password."

### ISSUE THREAD

**Issue by UltimatePro-Grammer** [microsoft/vscode-pull-request-github#2236]
I was having issues with pushing branches with workflow changes in them so tried to revoke access to this extension through GitHub and then delete and re-install the extension.

However, this seems to have irreversibly broke it and I have tried every other solution suggested for similar problems. Every time I try to do one of the fixes the sign in notification never shows up.
Note that I am in a git repository and see two empty boxes when I go to the extension's viewlet:
![Screen Shot 2020-10-27 at 7 32 09 PM](https://user-images.githubusercontent.com/63370104/97372976-372aba80-188b-11eb-911a-c272398263ea.png)

The exact error I am getting from git when trying to push my code is
```
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/UltimatePro-Grammer/JSQL.git/'
```
Is there a way to force authenticate? I have seen suggestions to use the `Github Pull Requests: Sign in to GitHub` command, though that does not show up in my command palette.

Extension version: 0.20.1
VSCode version: 1.50.1
Operating System: MacOS

Any help would be ***greatly*** appreciated as I have been stuck on this for quite some time.

Note also that I don't get any errors from anything until I try to push my code.

**Comment by RMacfarlane** [comment]
There should be an option to sign out of an account at the bottom of the activity bar, are you still signed in there?
<img width="589" alt="Screen Shot 2020-10-27 at 4 44 57 PM" src="https://user-images.githubusercontent.com/3672607/97373725-d6dc4e80-1873-11eb-8cb1-ee71db045850.png">

**Comment by UltimatePro-Grammer** [comment]
@RMacfarlane Yes, I am. Should I sign out?
![Screen Shot 2020-10-27 at 8 06 35 PM](https://user-images.githubusercontent.com/63370104/97374952-f2ede900-188f-11eb-8a23-72fe3e8281c5.png)

**Comment by RMacfarlane** [comment]
Yeah, can you try signing out? The option to sign in should appear again, which should prompt you to reauthorize

**Comment by UltimatePro-Grammer** [comment]
Okay, I signed out. All that popped up was a notification that said "Successfully signed out." What should I do now? Additionally, when I click on the account button it still says I am signed in.

**Comment by UltimatePro-Grammer** [comment]
**Update:**
I fixed it! Here's what I did for anybody in the future,
1. Click on the profile button on the bottom left and select "Sign Out" on the one that says `[your GitHub username] (GitHub)`
2. Once signed out, uninstall and reinstall the extension.
3. You should see a notification pop up on the profile button after downloading. Click on the profile button and choose "Sign in"
After these steps I am no longer having the issue!
