### ISSUE TITLE
Insiders: Error on startup

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-pull-request-github#2242]
![image](https://user-images.githubusercontent.com/22350/97581020-5c870800-19f4-11eb-8f3a-299cae1d70d2.png)

**Comment by alexr00** [comment]
@joaomoreno does this happen every time? @RMacfarlane I don't know what this could be coming from. Does it ring any bells for you?

**Comment by RMacfarlane** [comment]
This is very mysterious to me! From searching, it seems that the html page in this error is from some HTTP web proxy software. Do you have something like that running? Does the stable version of the extension also do this?

**Comment by joaomoreno** [comment]
OK That's embarrassing 😆 I had been testing proxy stuff... 🤦‍♂️
