### ISSUE TITLE
Error: unknown handler on attempting to checkout a PR

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-pull-request-github#2246]
The steps I used:
1. clone vscode
2. build
3. zip
4. extract
5. open extracted
6. checkout -> error
7. run `git fetch origin`
5. checkout -> error

![image](https://user-images.githubusercontent.com/8586769/97747646-877f6380-1aa9-11eb-8419-0be0dabf0dc8.png)

**Comment by alexr00** [comment]
duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/1594
