### ISSUE TITLE
"Delete branch" offers to delete on upstream, not origin

### ISSUE THREAD

**Issue by philipstarkey** [microsoft/vscode-pull-request-github#2247]
I think the wrong branch is offered for deletion once the PR is merged from a branch in a fork. The prompt offers to delete `upstream/branchname` which doesn't seem to exist after the PR is merged anyway. But `origin/branchname` does.

Version information:

- Extension version: 0.20.1
- VSCode Version: 1.50.0
- OS: Windows 10

Steps to Reproduce:

1. Fork repository.
2. Checkout fork as origin, add original repo as upstream.
2. Commit to new branch.
3. Make a PR from within VS Code using this extension. Push new change to origin, send PR to upstream.
4. Merge the PR
5. Refresh the PR in VS Code
6. See that it suggests deleting the branch. Click it.
7. It prompts you to delete the remote branch on **upstream** and the local branch.

I then have to manually delete `origin/branchname`.

From what I can tell, this extensions should be offering to delete `origin/branchname` instead of `upstream/branchname`.

**Comment by alexr00** [comment]
The label is incorrect in the picker, the right branch is actually deleted if you select that option.
