### ISSUE TITLE
Give hint to install GHPR in the remote if it's only installed on the UI

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#2248]
I saw this and was stumped for a little bit. Could we give a hint to the user here to install in the remote if the workspace is WSL and GHPR is activated as a UI extension?

![image](https://user-images.githubusercontent.com/2193314/97872637-351d8d00-1ccb-11eb-88fd-de72333ebc55.png)

**Comment by alexr00** [comment]
Not sure how you got into this state, since this is what happens to me:

![image](https://user-images.githubusercontent.com/38270282/142609547-c47fc067-4a96-4423-be93-c6a7e5617069.png)
