### ISSUE TITLE
PR and issues seems to use different logic to pick up the parent repo

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#2249]
I was in a situation where issues were getting picked up, but not PRs:

![image](https://user-images.githubusercontent.com/2193314/97873573-b0cc0980-1ccc-11eb-8476-f4eb06b196a2.png)

Log:

```
[Info] Review> Validating state...
[Info] No remote with name 'ups' found. Please update your 'githubPullRequests.remotes' setting.
[Info] Found GitHub remote
[Info] Review> no matching pull request metadata found for current branch master
[Info] Review> no matching pull request metadata found on GitHub for current branch master
```

This fixed it: `git remote add ups https://github.com/xtermjs/xterm.js`

**Comment by alexr00** [comment]
We need to make sure we're using the same logic for finding the "most parent"/"most upstream" repo to look for PRs and issues in.

**Comment by alexr00** [comment]
A lot has changed since 2020, and I know I've made changes to the upstream detection. Closing as we can always reopen if it happens again.
