### ISSUE TITLE
Close pull request in PR tree view context menu is ambiguous

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode-pull-request-github#225]
I wanted to exit review mode when the description page of the pull request is not open, then I went to the Pull Requests tree view, right click on that PR, clicked "Close Pull Request", which literally closed that pull request but didn't switch branches.

**Comment by rebornix** [comment]
We can probably add "Exit Review Mode"

**Comment by RMacfarlane** [comment]
Closing since we've already removed the "Close" context menu option
