### ISSUE TITLE
Github Enterprise Support

### ISSUE THREAD

**Issue by noambloom** [microsoft/vscode-pull-request-github#2251]
Support for Github Enterprise has been dropped since 0.16 but now that GH Cli is out and seems to support it (https://cli.github.com/manual/#github-enterprise-server) would it be possible to leverage their support and use the github cli as the backend for this extension?

**Comment by lupalby** [comment]
I would be happy with beta support and actively help to test it. I would love for GHE support to be back!

**Comment by RMacfarlane** [comment]
Closing as a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/1793
