### ISSUE TITLE
Use colored icons in the Issues view

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-pull-request-github#2252]
Leverage the new support for colored icons to make the issues icons easier to differentiate

![image](https://user-images.githubusercontent.com/172399/98100595-621b9c80-1e91-11eb-800d-59947e1bfcad.png)

**Comment by alexr00** [comment]
Fixed by https://github.com/microsoft/vscode-pull-request-github/commit/568bd1f105a3703d803cac343c69b9978ca009e2

**Comment by bpasero** [comment]
This may not work in all themes, but given our file icons by default also use color (Seti) I guess we are consistent.
