### ISSUE TITLE
Minor release 0.20.1 available from Marketplace has no github release

### ISSUE THREAD

**Issue by coroa** [microsoft/vscode-pull-request-github#2255]
It seems there was no github release produced for minor release 0.20.1,

ie. the [commits](https://github.com/microsoft/vscode-pull-request-github/compare/0.20.0...release/0.20) on the release-0.20 branch since the 0.20.0 tag have not been tagged as a new release, thus there is no publishing of a 0.20.1 release here on github and is only available from the marketplace https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github .

Probably that's why openvsx has not picked it up ~and is still keeping #2206  open~.

**Comment by RMacfarlane** [comment]
Thank you! I've published the release.
