### ISSUE TITLE
Fetching pull requests for remote 'origin' failed, please check if the url git@git.xxxx.com:xxx/xxx.git is valid.

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode-pull-request-github#2256]
```
Version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T14:53:05.704Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
```

Steps to Reproduce:

1. open a repository which is hosted by Github Enterprise
2. enable this extension，every time I reload vscode will notify this

**Comment by lupalby** [comment]
Unfortunately this extension dropped support for Github Enterprise earlier this year. Such a sad news! Look for other issues asking to bring GHE support back and add your support

**Comment by RMacfarlane** [comment]
Yes. this is unfortunately the case. Since there are other issues open requesting GHE support, I'm going to go ahead and close this as a duplicate. Thanks!
