### ISSUE TITLE
Issue numbers no longer appearing as links

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-pull-request-github#2258]
I recall seeing issue numbers linkified in comments, but I don't seem to see it happening anymore. This is a standard ts file in microsoft/vscode:

![image](https://user-images.githubusercontent.com/8586769/98406091-34199200-2022-11eb-9f3e-eb9a7f3f572b.png)

**Comment by alexr00** [comment]
We have had issue links turned off for months since we determined that they too often show up in unwanted places (outside of comments). For now, we will keep them disabled.
