### ISSUE TITLE
issueBranchTitle not Working as Expected

### ISSUE THREAD

**Issue by GLStephen** [microsoft/vscode-pull-request-github#2259]
No matter what I do I cannot get this pluging to accept and use this formatting in the devcontainer.json (and all other settings.json) **if the branch was previously created with the default format**

"githubIssues.issueBranchTitle": "${user}-issue${issueNumber}",

The branch is always created in the default format. Even if I delete the "bad" branch. Is there metadata for this and how do I delete it?

It seems like once you've created a branch with any name then the new settings are impossible to take effect on a branch that was previously created. It seems like some metadata is stored somewhere? Is that deletable?

**Comment by jamietdavidson** [comment]
Reup. I am experiencing this as well.

**Comment by adedayojs** [comment]
Please any update on this??? I'm experience this and it sucks!

**Comment by alexr00** [comment]
I think an ideal fix here would be the following:

1. User starts working on an issue.
2. User stops working on that issue.
3. User changes `githubIssues.issueBranchTitle` at some point.
4. User starts working on the same issue from 1 again.
5. We show a modal dialog offering to rename the branch.

**Comment by burkeholland** [comment]
@alexr00 Tried to implement the rename, but didn't see a clean way to do it.

- It doesn't look like we expose renameBranch from the Git extension
- Executing the command doesn't provide a mechanism to prefill the branch name. So we would have to ask them if they want to rename and then they would have to manually rename.

In the absence of a cleaner way to rename, I implemented the above request which is to check to see if the branch has been deleted but is still in the state and update the name to the new value.

So 2 questions...

@GLStephen - is this an adequate fix?
@alexr00 - is there a way to rename and I just missed it?

**Comment by alexr00** [comment]
@burkeholland, for rename could we do a `createBranch` to make the branch with the new name then do a `deleteBranch` on the old one?

If the branch has been deleted, I do think it's good to update the state to use the new value though.

**Comment by burkeholland** [comment]
I think the current change will provide the most expected experience. I worry that creating the branch will run into cases where that branch already exists and isn't related to this issue at all.

**Comment by alexr00** [comment]
I think if we show a modal dialog as suggested before we start doing any branch creating/renaming then there won't be any unexpected behavior. That said, I'm still supportive of the change you're currently working on!
