### ISSUE TITLE
There is no more `GitHub Pull Requests: Manually Provide Authentication Response`. Isn't it? What is alternatives?

### ISSUE THREAD

**Issue by seriousran** [microsoft/vscode-pull-request-github#2260]
There is no more `GitHub Pull Requests: Manually Provide Authentication Response`. Isn't it? What is alternatives?

_Originally posted by @seriousran in https://github.com/microsoft/vscode-pull-request-github/issues/1067#issuecomment-723696585_

**Comment by RMacfarlane** [comment]
After you start the sign in process, you can click on the "Signing into GitHub..." status bar item to enter a token:
<img width="187" alt="Screen Shot 2020-11-09 at 10 14 07 AM" src="https://user-images.githubusercontent.com/3672607/98580130-615d7e80-2274-11eb-8cb5-10087ca16584.png">

**Comment by tukusejssirs** [comment]
> After you start the sign in process, you can click on the "Signing into GitHub..." status bar item to enter a token:
> <img alt="Screen Shot 2020-11-09 at 10 14 07 AM" width="187" src="https://user-images.githubusercontent.com/3672607/98580130-615d7e80-2274-11eb-8cb5-10087ca16584.png">

That, however, does not work for me (no URL is open in my browser). We definitely should have an option to copy the URL (everywhere in VS Code, not just here).
