### ISSUE TITLE
Create pull request command missing from command palette

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode-pull-request-github#2264]

**Comment by RMacfarlane** [comment]
I'm having trouble reproducing this, could you grab the logs in the output channel if you see this again? The conditions for showing the '+' on the view versus the command in the command palette are slightly different, but it should still show up in the command palette if you're logged in. I'm wondering if there was just a delay in setting the context key for this on startup or if there's some other issue with that key being set
