### ISSUE TITLE
Offer to create a PR after publishing a branch

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode-pull-request-github#2265]
We should detect when I publish a new branch (basically remember the "unpublished" branches at the start and then anytime branches change, check if there was an unpublished branch that now has a remote) and show a notification to open a PR (assuming there hasn't already been a PR associated with that branch)

**Comment by RMacfarlane** [comment]
Completed with https://github.com/microsoft/vscode-pull-request-github/pull/2362 🎉
