### ISSUE TITLE
When creating a PR, the branch picker is auto-completed to the current branch, but it make it look like that is the only option

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode-pull-request-github#2268]
Maybe we should just pick the current branch, but not put the name in the input?

![image](https://user-images.githubusercontent.com/641685/98600395-7acded00-22ab-11eb-8ffa-f0a70decf00d.png)

**Comment by RMacfarlane** [comment]
I think this is actually useful as is, especially in the case where the target repo has many branches. That way if the default branch is far down in the list, it's obvious that it is currently selected
