### ISSUE TITLE
Some buttons not themed

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-pull-request-github#2277]
![image](https://user-images.githubusercontent.com/323878/98713402-6e45a500-233c-11eb-8b52-196983531b88.png)

![image](https://user-images.githubusercontent.com/323878/98713454-80274800-233c-11eb-9ff0-a6569dc1b385.png)

On the description page, it looks like the 3 buttons on the bottom besides Comment are the same color in all themes. Is that on purpose?

**Comment by RMacfarlane** [comment]
Yeah, these are actually using a theme color - button.secondaryBackground. It looks like that color is almost identical between light and dark themes
