### ISSUE TITLE
Telemetry and metrics for preview release

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode-pull-request-github#228]
We'd like to have a set of basic telemetry in place to measure the success and usage of the extension:

Top of mind:

**Metrics:**
Comments:
- [ ] How many comments are being added from the editor?
- [ ] How many comments are being added from the description page?

Authentication
- [ ] What's the success rate of authentication?  How many people stall?
- [ ] What's the most commons errors we get from Github? Scope issues? 

PR treeview
- [x] What PR categories are used the most? (used = expanding the tree to see PRs)
- [ ] How many times does a PR get checked out from the context menu?

Overview page
- [ ] How often is the overview page opened?
- [ ] How many times does a PR get approved?
- [ ] How many times does a PR get checked out?
- [ ] How many times does a PR get changed requested?
 
Please add more.

**Comment by auchenberg** [comment]
@shana What options do we have to land this with Github tech?

**Comment by RMacfarlane** [comment]
Some other possible metrics:

- [ ] How often is "Open Pull Request in GitHub" used?
- [ ] How often is the action for deleting a local pull request branch used?


- [ ] What errors do users see when trying to check out a pull request?
- [ ] What errors do users see when trying to create or reply to a comment?

**Comment by shana** [comment]
We have infrastructure for submitting metrics from editor extensions and desktop apps, so we can add vscode to that. There's also a telemetry package for this purpose on atom (https://github.com/atom/telemetry) which we probably can leverage here.

**Comment by auchenberg** [comment]
@shana When time allows. How many of these metrics did we get into place?

**Comment by shana** [comment]
@auchenberg As of now, the following metrics are being tracked:

- PR openInGitHub
- PR open description
- PR checkout from context menu
- PR checkout from description
- PR local branch delete
- PR close
- PR request changes
- PR approve
- PR List Expand: Local, Assigned, Review Requested, Mine, All
- Authentication started (user clicked on signin to start the auth process)
- Authentication failed
- Authentication success
- Authentication cancel (user dismissed the signin info box)

These are in master but not all included in 0.22.

We can also track exceptions/errors, but those use a different endpoint/backend so they aren't included right now (but we can track that as well)

**Comment by auchenberg** [comment]
Cool, I think this is a good start.
