### ISSUE TITLE
Replace Icon on the Activity Bar by an Octocat (or anything different to built-in Source Control)

### ISSUE THREAD

**Issue by manutero** [microsoft/vscode-pull-request-github#2280]
> Searched for duplicated issues, didn't find any

**Situation**: Current Icon for the Activity Bar is extremely similar to already existing menu "Source Control" (check the image)

![Captura de pantalla 2020-11-11 a las 11 46 12](https://user-images.githubusercontent.com/2211052/98807595-2ea1ba80-241b-11eb-9e6e-099cd9b5c32d.png)

**Request**: Change the Activity Bar icon of this extension.
**Suggestion**: I'd go for an Octocat; `Octocat === Github` , besides the icon is already in the repo (https://github.com/microsoft/vscode-pull-request-github/blob/master/resources/icons/github_logo.png)

![github_logo](https://user-images.githubusercontent.com/2211052/98807855-935d1500-241b-11eb-9f38-a9e17e9bd1b0.png)

**Comment by KaiSforza** [comment]
I made it the svg logo they have in `resources/icons/dark`, it fits the monotone theme a bit better.
