### ISSUE TITLE
Autofill @usernames in comments

### ISSUE THREAD

**Issue by brianjmurrell** [microsoft/vscode-pull-request-github#2284]
When adding a comment to a PR, typing an `@` followed by some letters should populate a list of relevant users like the GH UI does.

**Comment by RMacfarlane** [comment]
I think this is a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/1206, unless you're seeing that there are no completions within comments in a file

**Comment by brianjmurrell** [comment]
Yeah, I tend to agree.

**Comment by RMacfarlane** [comment]
Thanks, I will go ahead and close this in favor of #1206
