### ISSUE TITLE
Pull new changes in PR branch when checking it out

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-pull-request-github#229]
- Check out a PR
- Check out master
- Some time later the PR gets more changes
- Check out the PR again
- I don't have the latest changes, but they do show up in "Changes in Pull Request"

I think it should just `git pull` when I check out a PR for the second time?

**Comment by RMacfarlane** [comment]
Already fixed via https://github.com/Microsoft/vscode-pull-request-github/commit/49aa57d9f4f13599a44e78bc783607c248d2b2de
