### ISSUE TITLE
Please provide the Product Management view on GitHub Enterprise support

### ISSUE THREAD

**Issue by cfiderer** [microsoft/vscode-pull-request-github#2290]
I understand that support for GitHub Enterprise was dropped from this extension with 0.16.0.

With the takeover of GitHub by Microsoft, all relevant components (VSCode, the VSCode Pull Request extension, and GitHub Enterprise) are owned by the same company, and all customers using GitHub Enterprise are left hanging out in the cold.

Please provide the Product Management point of view on this deficiency.
Wouldn't it be possible to allocate the necessary resources from the GitHub Enterprise customer support area?

**Comment by Ygilany** [comment]
Can we bring back GitHub enterprise please?!!

**Comment by cfiderer** [comment]
The latest versions (VSCode 1.57.0, GitHub Pull Requests and Issues v0.27.0)  have some support for GitHub Enterprise. 
Refer to the change log of the extension for details.

**Comment by alexr00** [comment]
GitHub Enterprise is now fully supported! If you find problems with it, please open issues.
