### ISSUE TITLE
Diff from PR's file gets erroneously opened when working on the PR's branch

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-pull-request-github#2295]
I've had `jackson/proposed-api-management-command` checked out for a while, which has a PR up for it but I haven't been actively using the GHPR extension. However, I still see that a diff for `main.js` keeps opening at strange times

1. Checkout `Microsoft/vscode@jackson/proposed-api-management-command`
2. Close all editors
2. Reload
2. Wait a bit
3. This pops up:
![image](https://user-images.githubusercontent.com/8586769/99279986-b3a71e00-27e5-11eb-9b00-1c7c7208b8c3.png)

reproduces in github.vscode-pull-request-github@0.21.0 and the latest nightly

**Comment by JacksonKearl** [comment]
I'm consistently running into this many times a day when working on any branches that have associated PR's, even if I'm not actively using the GHPRI extension. Is there any thing I can do to help debug this?

**Comment by RMacfarlane** [comment]
This is actually something we intentionally added (at least I think this is behaving as expected, @alexr00 can correct me), but when the extension has "focused mode" enabled, we automatically open the first diff on checkout. The idea was that this would be where you would want to start a review, particularly if you're navigating from a codespace. I can see this being rather disruptive, though, so maybe we should try to scope this to the codespace case

**Comment by alexr00** [comment]
The diff popping up after reload and when you change branches is actually expected as Rachel said. I'll look at scoping it further.

**Comment by JacksonKearl** [comment]
It also pops up any time I make a commit onto the branch, which is probably the most annoying. I don't think I'd really ever want this, but I do like focused mode. Could it be separately toggleable?

**Comment by JacksonKearl** [comment]
It appears less often now (not on push), which is great. But I'd still really love for this to not happen at all. I probably reload vscode more than most users, but it's getting really quite annoying for an editor to pop up and steal my focus ~5s after I reload and I'm in the middle of something else. Would you consider an option to disable this entirely?

**Comment by RMacfarlane** [comment]
This also seems to be happening when the window is reloaded or when a PR is first created, can we try to scope this down further?

**Comment by Donna3344** [comment]
You guys amazing at this!!

**Comment by Donna3344** [comment]
I can learn so much from the community. Thanks 🙏

**Comment by JacksonKearl** [comment]
I've disabled Focus Mode even though I do like the views because of how often the review editor pops up. 

In my experience I never want them because I often have a separate branch up that isn't really intended to be reviewed by me or really anyone; a checkbox disabling it entirely would make me happy.

**Comment by JacksonKearl** [comment]
It's beautiful 🙏
