### ISSUE TITLE
0.21.1 breaks issue and pull request views

### ISSUE THREAD

**Issue by RamonMeffert** [microsoft/vscode-pull-request-github#2297]
- Extension version: 0.21.1
- VSCode Version: 1.51.1
- OS: macOS 11.0.1 (intel)

Steps to Reproduce:

1. Open the GitHub view from the Activity Bar
2. See that the issue and pull request views show nothing

When trying to refresh the views or executing one of the commands from the cmd+shift+p menu, a red error popup appears saying that <action x> is not available. This was the case for every action I have tried (but I have not tried all actions).

I've tried refreshing the views, reinstalling the plugin, restarting vs code, even rebooting my system – nothing worked. I have reinstalled 0.21.0 again, and everything seems to be working fine again.

**Comment by RMacfarlane** [comment]
Thanks, I've published 0.21.2 that reverts these changes.

**Comment by daxmc99** [comment]
🤯 
Amazing job! That was quick!

**Comment by RamonMeffert** [comment]
Thanks so much! That was incredibly quick indeed.
