### ISSUE TITLE
Edit PR title, does not (auto) update title of PR in treeview (PR in list on left side)

### ISSUE THREAD

**Issue by ranavale** [microsoft/vscode-pull-request-github#2299]
- Extension version:v0.21.2
- VSCode Version:1.51
- OS:Windows

Steps to Reproduce:
1. Open Pull request
2. Go to PR description.
3. Edit title of pr.
4. Wait for sync? nothing happens
5. Refresh PR: still the PR in list has old title.
6. Solution: Refresh the PR list from its treeview control. (I would expect it to happen when title is edited automatically)

**Comment by sumitani** [comment]
Can I work on it? @RMacfarlane

**Comment by alexr00** [comment]
Turns out this isn't a good first issue since there is some refactoring work that will need to be done to expose a nice way to refresh the list.

**Comment by alexr00** [comment]
Found a not bad way to do this, and also ensured the title is updated in other places.

**Comment by tanhakabir** [comment]
There's a little bit of lag but verified
