### ISSUE TITLE
Webview is disposed

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-pull-request-github#230]
I don't know how I got into this state but I have about 900 of these errors in the devtools console:

![image](https://user-images.githubusercontent.com/323878/44311986-0646c500-a3a6-11e8-95b0-41397c0ab861.png)

**Comment by rebornix** [comment]
Thanks, we forgot to dispose some listeners for webview.

**Comment by ronjouch** [comment]
@rebornix I got this error again today with an in-vscode notification, using 0.4.0.

VSCode Version: 1.32.0-insider
Commit: aeaef41d51201e555735f5e8d2f38a9d0ddb9026
Date: 2019-02-20T06:13:19.816Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.20.11-042011-generic
