### ISSUE TITLE
Extension stopped working in 1.52.0-insider

### ISSUE THREAD

**Issue by 454de6e** [microsoft/vscode-pull-request-github#2303]
Extension stopped working in

Version: 1.52.0-insider
Commit: bf21395291146c014220eb70b54fdfc0a15956b5
Date: 2020-12-01T09:20:33.868Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.1.0

See screenshot. Does not load pull requests or issues.

<img width="321" alt="Screen Shot 2020-12-01 at 11 16 42 AM" src="https://user-images.githubusercontent.com/1482402/100766643-dc730a00-33c6-11eb-9491-cf7515fb0ee9.png">

- Extension version: 0.21.3
- VSCode Version: see further up
- OS: see further up

Steps to Reproduce: Open any project cloned from GitHub and click on extension's GitHub icon.

**Comment by RMacfarlane** [comment]
Thank for catching this! I just published 0.21.4, which fixes this.

**Comment by 454de6e** [comment]
@RMacfarlane It works thank you!
