### ISSUE TITLE
Extension does not load inside Codespaces

### ISSUE THREAD

**Issue by 454de6e** [microsoft/vscode-pull-request-github#2304]
This extension is installed by default in GitHub Codespaces. I using the latest stable VSCode

Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-11T01:11:34.018Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.1.0

and when running a Codespace with the `github.codespaces` extension, the `github.vscode-pull-request-github` extension does not load. It's icon does not show up on the left hand side. When I look at installed extensions I see this:

<img width="319" alt="Screen Shot 2020-12-01 at 11 34 31 AM" src="https://user-images.githubusercontent.com/1482402/100768716-3379de80-33c9-11eb-9bac-40089b5fe7ac.png">

v0.21.2 shows up as locally installed (I actually have 0.21.3 locally installed) and there is a reload prompt. Pressing the reload prompt reloads VSCode but it does not change the status of the `github.vscode-pull-request-github` extension.

This extension loads fine in 1.52.0-insiders, but on insiders there is another, presumably non-related, problem with this extension, see https://github.com/microsoft/vscode-pull-request-github/issues/2303.

Steps to Reproduce: Happens for me with any Codespace opened on a local installation of above mentioned stable VSCode via the `github.codespaces` extension.

**Comment by RMacfarlane** [comment]
Sorry I missed replying to this earlier - I believe this has already been fixed.

As for why it keeps showing as disabled in this list, I suspect what's happening is that you also have a copy of the extension on the Codespace which is taking precedence.

**Comment by 454de6e** [comment]
This is fixed in VSCode 1.52.
