### ISSUE TITLE
Get permalink of current line/selection

### ISSUE THREAD

**Issue by marvinhagemeister** [microsoft/vscode-pull-request-github#2305]
One of the most frequent workflows I have is that I browse code in vscode and quickly want to send a link of the current line or selection to someone else. Currently I manually go to the repo on github and search for the same file, but that's a lot of manual steps. Would be far easier if there is a command for that.

**Comment by ianmacartney** [comment]
If you open the command palette, there's a command called "Copy GitHub permalink". isn't that exactly what you're asking for?

**Comment by marvinhagemeister** [comment]
Ohh I totally missed that 🙈 That works!
