### ISSUE TITLE
Codespaces workspace shows no PRs

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode-pull-request-github#2307]
re https://github.com/microsoft/vscode-internalbacklog/issues/1660 -> https://github.com/microsoft/vssaas-planning/issues/2176

* create codespace for vscode-repo
* in browser, open Github view and see PRs
* also open codespace in desktop
* :bug: Github view stays empty

<img width="1372" alt="Screenshot 2020-12-02 at 14 16 01" src="https://user-images.githubusercontent.com/1794099/100877411-0866bc00-34a9-11eb-8025-c9b6c1d69b1c.png">

<img width="1136" alt="Screenshot 2020-12-02 at 14 15 57" src="https://user-images.githubusercontent.com/1794099/100877405-056bcb80-34a9-11eb-9f3b-6613250b2982.png">

**Comment by RMacfarlane** [comment]
I haven't been able to repro this while testing recently. Since Eric has made changes to add a "Loading..." welcome view to these trees that gets shown immediately, the view should no longer show up as blank.

**Comment by klausbadelt** [comment]
We still experience this issue, but on Gitpod. v0.27.1
<img width="1743" alt="Screen Shot 2021-07-26 at 3 51 18 PM" src="https://user-images.githubusercontent.com/5615403/127069338-e15823d0-84f5-4509-89cf-df42b65923cc.png">
