### ISSUE TITLE
Description is not shown

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode-pull-request-github#231]
- Opened All (node)
- Expanded a PR in that
- Clicked on description 

🐛 A blank screen is shown

![image](https://user-images.githubusercontent.com/10746682/44329778-a7488500-a465-11e8-9f13-933d452d7506.png)

**Comment by RMacfarlane** [comment]
Fixed by https://github.com/Microsoft/vscode-pull-request-github/commit/ec53fb62e62e98371d90193923fc33f0f2a2a581
