### ISSUE TITLE
Unexpected progress when creating PR from extension

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode-pull-request-github#2311]
* create a new PR from the GH extension
* you are guided through the process, a progress notification shows
* 😕 at one point progress depends on me making a selection in quick pick which is very unexpected. It seems like progress is used to indicate my steps through this and not representing some long running operation

<img width="1039" alt="Screenshot 2020-12-02 at 17 26 54" src="https://user-images.githubusercontent.com/1794099/100903528-4e7e4880-34c6-11eb-82d1-ef9c5fdcc1c1.png">

**Comment by RMacfarlane** [comment]
With the change to use a webview view for create (https://github.com/microsoft/vscode-pull-request-github/pull/2335), this progress indicator is no longer shown
