### ISSUE TITLE
Cannot open image diffs of PR

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-pull-request-github#2316]
Checkout https://github.com/microsoft/vscode/pull/111840, attempt to open diffs in media folder

![image](https://user-images.githubusercontent.com/8586769/101208554-3540dd80-3627-11eb-9af3-993fc2a767ca.png)

**Comment by alexr00** [comment]
The PR branch for the original PR has been deleted, so I can't open it, but I haven't reproed the bug with other image diffs.
