### ISSUE TITLE
Use when clauses to hide the extension's activity bar view

### ISSUE THREAD

**Issue by tristan957** [microsoft/vscode-pull-request-github#2317]
Often times I am working in projects whose remotes aren't on GitHub for instance. Take my day job for example. I am largely working within Bitbucket (unfotunately).

The Activity Bar is fairly precious space in my opinion. It isn't super large, and if too many extensions take up real estate on it, the Activity Bar will overflow with a scrollbar I think.

A contributed `viewContainer` is hidden when all of the views within it have `when` clauses which evaluate to false.

I want to propose that this project take advantage of `when` clauses that follow all or some of the following criteria:

* One of the remotes includes `github.com` (not sure if this extension supports GitHub Enterprise or not)
* A `.github` folder exists at the root of the $workspaceFolder
* A user runs a command provided by this extension

A similar issue exists for the GitLab Workflow extension here: https://gitlab.com/gitlab-org/gitlab-vscode-extension/-/issues/71

**Comment by RMacfarlane** [comment]
I'm worried this will cause a lot of confusion for users, particularly when first installing the extension and opening an empty folder. I could see having a setting to opt-into this behavior, but I don't think we should do this by default.

**Comment by tristan957** [comment]
Even something like an opt-in would be greatly appreciated.

**Comment by alexr00** [comment]
You can now accomplish this using VS Code's profiles feature!

**Comment by tristan957** [comment]
Hmm. I don't use that feature. Oh well. I just keep all extensions installed all the time.

**Comment by alexr00** [comment]
Profiles is a nice feature and very easy to use if you're interested: https://code.visualstudio.com/docs/editor/profiles
