### ISSUE TITLE
Allow creating a commit comment from vs code

### ISSUE THREAD

**Issue by twitu** [microsoft/vscode-pull-request-github#2319]
I could not find such a feature mentioned here.

It will be great to have a way to create commit comments either from vs code editor pane or integrated terminal. GitHub provides an [api](https://developer.github.com/v3/repos/comments/#create-a-commit-comment) for it.

This will also need a way to view existing comments on a file to file basis.

The main utility of this feature would be to annotate code with logic, thoughts or other stuff that do not necessarily belong in the code documentation section. Moreover it would allow such annotations to be permalinked and always be accessible.

**Comment by phil-blain** [comment]
In the same spirit, it would be great if commit messages could be read in the UI of the extension. Right now only the title of the commit message is visible in the "Changes in Pull Request section" or the "Pull Request #n" editor.

**Comment by alexr00** [comment]
This sounds like a cool feature idea, but since it's not pull request specific, I'm not sure it belongs in this extension. Closing as we have not plans to address this feature request.
