### ISSUE TITLE
Can't update past 0.21.2

### ISSUE THREAD

**Issue by EppO** [microsoft/vscode-pull-request-github#2320]
- Extension version: 0.21.2
- VSCode Version: 1.51.1
- OS: Mac

Steps to Reproduce:

1. Install version 0.21.2 on Mac
2. Extension doesn't get updated when clicking 'Check for Extension Updates' although 0.21.4 is the latest released version
3. Installing manually the 0.21.4 version (using the .vsix) is impossible (see screenshot): 
> Unable to install extension 'github.vscode-pull-request-github' as it is not compatible with VS Code '1.51.1'.

<img width="1298" alt="Screen Shot 2020-12-07 at 20 57 57" src="https://user-images.githubusercontent.com/6111/101428651-27ad8100-38cf-11eb-8f9c-8f6f0bc9a985.png">

4. Extension page shows v0.21.2 as latest

**Comment by RMacfarlane** [comment]
This is actually working as expected. Versions 0.21.3 and higher require VSCode version 1.52 (which is the current VSCode insider's version) because of an API change. This should be released to as the stable version of VSCode this week.

**Comment by EppO** [comment]
Ok I see. It's not obvious when you look at the Git repository or the [Marketplace](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github) what version of VSCode the extension requires. I'll wait for the next stable version then, thanks for letting me know.
