### ISSUE TITLE
Jupyter notebook diff experience

### ISSUE THREAD

**Issue by ankitbko** [microsoft/vscode-pull-request-github#2323]
VSCode insider has updated Jupyter notebook experience with ability to show diff in more readable format (rather than diff of json). This experience does not work with PR yet. Any plans of integrating with that?
https://code.visualstudio.com/updates/v1_49#_notebooks

![image](https://user-images.githubusercontent.com/3169316/101884567-ecf16480-3bbe-11eb-925b-3f02785df524.png)

**Comment by RMacfarlane** [comment]
This would be cool!

cc @rebornix do you have a sense of how difficult this would be?

**Comment by rebornix** [comment]
@RMacfarlane As long as the notebook content provider uses the workspace fs api to resolve file content, it will work out of the box. We can meet and evaluate GitHub Issue Notebook together.

**Comment by jucor** [comment]
This would be *awesome*. I can't get it to work: I get an error "No file system provider found for resource":
![image](https://user-images.githubusercontent.com/660037/133898092-88d05e19-9762-4d6e-97a9-ad5bb7e1c15a.png)

**Comment by IceTDrinker** [comment]
What would it take to get the notebook diff view?

Apparently diffs/changes for ipynb files are generated as `RemoteFileChangeNode` which triggers the notification and the "open in browser" thing but it's not clear to me why it's not generated as a `GitFileChangeNode`.

I'm definitely not a TypeScript dev (and certainly not a vscode dev either) so it would probably be hard to contribute but that functionnality would be extremely useful (one better on GitHub even!) so I'm willing to contribute whatever help I can!

Cheers

**Comment by janosh** [comment]
Is there an equivalent issue somewhere about adding this to GitHub's web interface?

**Comment by lgonzalezsa** [comment]
This will be awesome, if I can suggest as well to include the navigation minimap to identify where the code was changed.

**Comment by alexr00** [comment]
This has been fixed in the mean time.
