### ISSUE TITLE
Opening a gist repository gives a fetch error

### ISSUE THREAD

**Issue by mcornella** [microsoft/vscode-pull-request-github#2324]
Issue Type: <b>Bug</b>

1) Clone a wiki (adding `.wiki.git` to a main repository URL) or gist repository
2) Open the cloned repository with VS Code with the extension enabled
3) See error: `Fetching pull requests for remote 'origin' failed, please check if the url <URL> is valid.`

Wiki repository:
![image](https://user-images.githubusercontent.com/1441704/102021379-ac8d1480-3d7f-11eb-8fce-dc196942da94.png)

Gist repository:
![image](https://user-images.githubusercontent.com/1441704/102021397-d5150e80-3d7f-11eb-9ec1-7dcd9bb7c93f.png)

Extension version: 0.22.0
VS Code version: Code - Insiders 1.52.0-insider (bc13785d3dd99b4b0e9da9aed17bb79809a50804, 2020-12-07T14:46:48.305Z)
OS version: Windows_NT x64 10.0.20262
Remote OS version: Linux x64 4.19.128-microsoft-standard
Remote OS version: Linux x64 4.19.128-microsoft-standard
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5 CPU       M 520  @ 2.40GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|7.92GB (1.69GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/marc/code/refined-github --remote=wsl+Ubuntu --crash-reporter-id b50261c5-4e04-48dd-9f0a-6d441b513f94|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i5 CPU       M 520  @ 2.40GHz (4 x 2393)|
|Memory (System)|3.80GB (1.30GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i5 CPU       M 520  @ 2.40GHz (4 x 2393)|
|Memory (System)|3.80GB (1.30GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i5 CPU       M 520  @ 2.40GHz (4 x 2393)|
|Memory (System)|3.80GB (1.30GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221882
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30208929
wsl2promptcf:30219163
vstry914:30230485
pythonvsdeb440:30224570
unusedpromptcf:30219165
folderexplorercf:30219167
openfilemenu:30219168
pythonvsded773:30223139
pythonvspyt600cf:30228412
core-portspanelcf:30233468

```

</details>

**Comment by hoteit** [comment]
issue is still there... any tricks around it?

**Comment by mcornella** [comment]
This doesn't happen to me anymore on 0.26.0, can you check if upgrading works?

**Comment by alexr00** [comment]
Should be fixed for wiki, but I haven't made any changes for gists.

**Comment by mcornella** [comment]
Yeah that's true, I hadn't checked on gists. I'll update the title.

**Comment by burkeholland** [comment]
OK! So this turned out to be harder than I thought. Gists can be cloned in two different ways so the remote might look different.

1. Clone via `gist.github.com` (i.e. `https://gist.github.com/burkeholland/efcf2bc7fd9a3d84ecd9756f83f97551`)
2. Clone via github.com (i.e. `git@github.com:c8456e08df200c7fd718dac69bbfc5a0.git`)

 #1 is easy enough to account for. #2 is a bit harder as I'm not sure if gist id's follow a certain pattern.

**Comment by mcornella** [comment]
> 2\. Clone via github.com (i.e. `git@github.com:c8456e08df200c7fd718dac69bbfc5a0.git`)

[In my example](https://github.com/microsoft/vscode-pull-request-github/issues/2324#issue-765605605) the SSH remote uses `gist.github.com`, and so it does when using the Clone via SSH button:
![Captura de pantalla de 2021-08-20 22-40-47](https://user-images.githubusercontent.com/1441704/130291209-0fbac401-3c5d-4c57-a42b-a98969afc358.png)

**Comment by alexr00** [comment]
Let's solve for the the simple case and take the incremental improvement. I agree that I don't see a clear solution for (2) above.

**Comment by burkeholland** [comment]
Does a match for gist[.]github[.]com. If you clone from github.com, YMMV.

**Comment by roblourens** [comment]
I don't get an error. Should I see this when I cloned a wiki?

![image](https://user-images.githubusercontent.com/323878/144308631-8f3b06fe-5f68-41ac-8f92-e3af31bd9457.png)

**Comment by alexr00** [comment]
What you're seeing is correct. We don't provide GitHub support when you open a wiki or gist, and I think most people don't expect there to be support for these.
