### ISSUE TITLE
PR sidebar view not activated

### ISSUE THREAD

**Issue by burkeholland** [microsoft/vscode-pull-request-github#2325]
When opening a PR in Codespaces (Web), the PR view isn't activated in the sidebar.

Extension version: v2020.12.19262 

## How to replicate

Open a PR in a Codespace (Web)

## What happens

The first file with changes is opened in the diff view, but the PR view is not activated in the sidebar.

## What should happen

The first file with changes should be opened in diff view, the PR view should be activated in the sidebar with the currently opened file selected.

**Comment by RMacfarlane** [comment]
Oops, I duplicated this issue myself: https://github.com/microsoft/vscode-pull-request-github/issues/2360.

Checked in a fix for it with https://github.com/microsoft/vscode-pull-request-github/commit/a418bd650bf24bd12baf552e8c201fad01382fb5, which will be available in tomorrow's insider's
