### ISSUE TITLE
[QUESTION]: Hide discussion in modified files

### ISSUE THREAD

**Issue by robence** [microsoft/vscode-pull-request-github#2327]
Hi! I've been using this extension and it's awesome! It really speeds things up without leaving my VSCode. 

Is there an option to hide discussion column presented below? I've looked into the settings parameters, but couldn't find it on my own, can you guys help me out?

![image](https://user-images.githubusercontent.com/20738129/102626370-0195a580-4147-11eb-8551-6624f8cdc166.png)

**Comment by RMacfarlane** [comment]
Hi @robence, there isn't a setting to hide this right now, unfortunately.

I'm curious in what situations you want to hide it, possibly similar to https://github.com/microsoft/vscode-pull-request-github/issues/408

**Comment by robence** [comment]
> Hi @robence, there isn't a setting to hide this right now, unfortunately.
> 
> I'm curious in what situations you want to hide it, possibly similar to #408

Hi! Thank you for your fast reply. I personally do not find it super useful, so if possible would like to see only changes to previous commit (usual vscode diff markers). I find it interferes with other diffs and is more difficult to see what changes am I about to make. It might work for others, which I'm glad for, although I'd like to switch off white labels in every situation.

**Comment by guigagb** [comment]
I don't need use the feature, i want disable the bar too.

**Comment by Donna3344** [comment]
On Jan 22, 2021 1:27 PM, Guilherme Trindade <notifications@github.com> wrote:
I don't need use the feature, i want disable the bar too.

**Comment by tgreen7** [comment]
Please add an option. The bar is so distracting.

**Comment by Greenek** [comment]
You can "hide" it by overwriting the bar color with the background color of your theme in the `settings.json`, for example:

```
"workbench.colorCustomizations": {
    "editorGutter.commentRangeForeground": "#292c34"
}
```

But yeah, it would be nice to have an option to disable it.

**Comment by jeffreyscottfrench** [comment]
Looks like you can click "exit review mode" from the PR overview page and it closes it out.

**Comment by robence** [comment]
I haven't used the extension in a while, to me this doesn't seem relevant. If you feel the need you can create a new issue based on this one.
