### ISSUE TITLE
Adopt vscode.diff and vscode.open for tree commands

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#2333]
With the recent work in VS Code to make the `diff` and `open` command like the commands do from the file explorer and SCM view, we should take advantage of that work in this extension.

**Comment by RMacfarlane** [comment]
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/2288?

**Comment by alexr00** [comment]
Yes!
