### ISSUE TITLE
Prevent text wrap in commits list (description view)

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/vscode-pull-request-github#2339]
Issue Type: <b>Feature Request</b>

Would you accept PR that prevents text wrap for timestamp in commits list?

In my case it looks like this:
![image](https://user-images.githubusercontent.com/1312662/103556697-d509b980-4eba-11eb-85b6-6380999df403.png)

Which will look much better if displayed in one line
![image](https://user-images.githubusercontent.com/1312662/103557662-32523a80-4ebc-11eb-8a3a-aeb49547581e.png)

If yes - can it be applied to all timestamps on description view (comment header etc.) or only commits list?

Extension version: 2021.1.4862
VS Code version: Code - Insiders 1.53.0-insider (98106c48a07d4d07f0f71b4db9b3ff156f223339, 2021-01-01T05:22:15.141Z)
OS version: Windows_NT x64 10.0.19041

**Comment by RMacfarlane** [comment]
Yes, would definitely accept a PR to fix this!

I think it would make sense to also apply this everywhere, but perhaps have some additional stying on the comment header to hide overflow.
