### ISSUE TITLE
Exclude more files from package

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#2341]
The nightly build has failed because we can only have 25 file in our package (since we also package for web): https://rebornix.visualstudio.com/Pull%20Request/_build/results?buildId=2090&view=logs&j=3bd52376-4866-57aa-dfdb-d04952b84d8d&t=14bd693e-34d1-5172-806f-7299de473e6e

We should see if more files can be excluded so we can be below the max.

**Comment by RMacfarlane** [comment]
From running `vsce ls`, looks like what we include is:
```
base.webpack.config.js
browser.webpack.config.js
CHANGELOG.md
dist/browser/extension.js
LICENSE
media/activityBar-webviewIndex.js
media/createPR-webviewIndex.js
media/extension.js
media/webviewIndex.js
package.json
package.nls.json
README.md
resources/icons/github_logo.png
resources/icons/issues.png
resources/icons/pull-request.png
resources/icons/reactions/confused.png
resources/icons/reactions/eyes.png
resources/icons/reactions/heart.png
resources/icons/reactions/hooray.png
resources/icons/reactions/laugh.png
resources/icons/reactions/rocket.png
resources/icons/reactions/thumbs_down.png
resources/icons/reactions/thumbs_up.png
ThirdPartyNotices.txt
```

Though I'm not sure why this list is only 24 files long 🤔 We should be able to safely get rid of the webpack configs.
