### ISSUE TITLE
PR description title hover icons shift the title

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#2350]
If going with this show on hover style, maybe show the buttons as an overlay with opaque background on top of the title title, instead of causing the reflow:

![recording (24)](https://user-images.githubusercontent.com/2193314/104222197-ceb59900-53f6-11eb-819c-dfaa1e2b4981.gif)

**Comment by pnavarrc** [comment]
I encountered this bug today, maybe moving the issue number to the left would work too. The problem is that is impossible to click on the PR number as it will move up and down depending on what the user is hovering!

**Comment by burkeholland** [comment]
I'm not seeing this behavior in  0.29.0....


https://user-images.githubusercontent.com/686963/129456222-5cd7298e-ba75-4692-8946-e3369aa0c0e3.mp4
