### ISSUE TITLE
Keyboard focus lost when expanding a branch node in the Pull Requests section

### ISSUE THREAD

**Issue by MarcoZehe** [microsoft/vscode-pull-request-github#2351]
Issue Type: <b>Bug</b>

1. Create a local branch with some commits.
2. In the side bar, switch to the Github tab, and expand the Pull Requests section.
3. Using the keyboard, tab into the tree view and move up and down. Focus the Local Branches section and press Right Arrow to expand.
4. Move to your branch with up and down arrows to focus the branch you created in step 1, then press RightArrow again.

Expected: The tree node expands, but focus stays there and allows further navigation into the contents. Just like when opening a folder in the File Explorer view.
Actual: Focus jumps to the next top level node, then the branch contents gets inserted above, requiring you to move up through the files and other information that is contained within your branch. If you have a lot of files in a branch commit series, that could mean a huge loss of focus context, requiring several keystrokes to get back to the top of that branch to do things like create a pull request from it, etc.

Extension version: 0.22.0
VS Code version: Code - Insiders 1.53.0-insider (6dc779565e1e4a26104002fde340b68c157c3bc5, 2021-01-12T06:46:39.069Z)
OS version: Darwin arm64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|undefined|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id 4ea43554-4a6d-4f7c-b2fb-6de1a3610d98|
|Screen Reader|yes|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221882
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30208930
wsl2promptcf:30219163
vstry244:30230484
pythonvsdeb440:30224570
unusedprompt:30219164
folderexplorer:30219166
openfilemenucf:30219169
pythonvsded773:30223139
pythonvspyt600cf:30241728
core-portspanel:30233467

```

</details>

**Comment by alexr00** [comment]
I'm not able to reproduce this issue now, but please comment if you're still seeing it!
