### ISSUE TITLE
Feature Request: Add tags when creating issues from anywhere

### ISSUE THREAD

**Issue by DavidMtbg** [microsoft/vscode-pull-request-github#2352]
It would be a great note-taking to action item feature/workflow if one could add tags to the issue that is created from the editor via // TODO, etc.

Example:
`// TODO Add tags when creating issues from anywhere #feature-request`

N.B. Enjoying this extension - thanks!

**Comment by alexr00** [comment]
You can add labels in the issue editor, which can be found by using the button on the input box when you enter the issue title.
