### ISSUE TITLE
Focused mode draft pull request styling issues

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode-pull-request-github#2354]
![Screenshot 2021-01-13 at 17 22 39](https://user-images.githubusercontent.com/3672607/104485769-c2a91300-557f-11eb-8ca3-275a8a1053ba.png)
"Ready for review" should take up the whole line, and the warning icon should be inline with text

**Comment by JacksonKearl** [comment]
Looks good. No more warning icon but that's prob intentional :)
![image](https://user-images.githubusercontent.com/8586769/106213552-cf358a00-6181-11eb-8e5c-66b548bfe47a.png)
![image](https://user-images.githubusercontent.com/8586769/106213700-1ae83380-6182-11eb-9ce6-dad3b365b236.png)
