### ISSUE TITLE
There are updates available for this pull request while master branch is checked out

### ISSUE THREAD

**Issue by AlCalzone** [microsoft/vscode-pull-request-github#2356]
Extension version: 0.22.0
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Check out master branch
2. Have remote changes that are not pulled
3. ![grafik](https://user-images.githubusercontent.com/17641229/104587198-dd09ec00-5666-11eb-94ba-24b9148c6710.png)

Edit: This might be related to the following info I found in the log:
```
[Info] Review> current branch master is associated with pull request #1335
[Info] Review> Resolving pull request
[Info] Review> Fetching pull request data
[Info] Review> register comments provider
[Info] Review> display pull request status bar indicator and refresh pull request tree view.
```
If I try to open it from the status bar ![grafik](https://user-images.githubusercontent.com/17641229/104590241-54417f00-566b-11eb-83f8-6b507f8a4b36.png), I'm getting the error `Cannot read property 'commit' of undefined`

**Comment by AlCalzone** [comment]
Upon further investigation: This is the mentioned PR: https://github.com/zwave-js/node-zwave-js/pull/1335

I'm not sure what went wrong, but Github says that it was merged into master without any commits:
![grafik](https://user-images.githubusercontent.com/17641229/106754437-4610ce00-662d-11eb-9174-d2594fe3cddf.png)

**Comment by AlCalzone** [comment]
I would help fix this (since this is really annoying), but I have no clue where to even start.

**Comment by AlCalzone** [comment]
Ping - How can I help get this fixed?

**Comment by AlCalzone** [comment]
So, I figured this out. At some point this extension has associated the master branch with the broken PR under the key `github-pr-owner-number` in the local `.git/config`. Since that entry never got cleaned up, it kept showing that the master branch was associated with the PR.

I removed the entry manually and the problem is resolved.

**Comment by ryanaklein** [comment]
Good find! That sort of worked for me. I had to manually change the record in `.config` then switch branches then back to the branch my PR was open on. I wonder if it has anything to do with protected branches? Perhaps the plug-in is expecting the branch to be deleted?

**Comment by bessx** [comment]
> So, I figured this out. At some point this extension has associated the master branch with the broken PR under the key `github-pr-owner-number` in the local `.git/config`. Since that entry never got cleaned up, it kept showing that the master branch was associated with the PR.
> 
> ```
> [branch "master"]
> 	remote = origin
> 	merge = refs/heads/master
> 	github-pr-owner-number = "zwave-js#node-zwave-js#1335"
> ```
> 
> I removed the entry manually and the problem is resolved.

I'm having the same issue, but deleting the entry manually didn't seem to help.  I even tried to delete the entire repo and re-clone it, but the pull request still came back. Any hints?
