### ISSUE TITLE
Use more specific "when" clauses for commands contributed to views

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode-pull-request-github#2357]
For some context commands on views, we have "when" clauses that look like "view =~ /pr:/". Since this isn't a very specific regex, it can easily match views contributed from other extensions. We can use a direct match, "view == pr:github", instead.

**Comment by ankitbko** [comment]
@RMacfarlane  Unsure but will this also cause any issue - `"when": "commentController =~ /^(browse|review)/"`?

**Comment by ankitbko** [comment]
I checked and comment context also needs to be updated

![image](https://user-images.githubusercontent.com/3169316/104706863-a81e9780-5741-11eb-96ca-992a7d5eb973.png)

**Comment by ankitbko** [comment]
@RMacfarlane Also I am not sure if this is related but the File Decoration is also duplicating. Will it always show on any URI that has query parameter set?

![image](https://user-images.githubusercontent.com/3169316/104767179-c01e0780-5791-11eb-8204-05cf5190cbe1.png)

**Comment by RMacfarlane** [comment]
Yes, currently the decorator is only checking if the uri has `status` in the query parameters. I can scope it to check the uri scheme as well.

**Comment by RMacfarlane** [comment]
Steps to verify this is fixed:

1. Create a test extension and add a view that starts with "pr", like
```
    "views": {
      "explorer": [
        {
          "id": "pr-not-github",
          "name": "Test"
        }
      ],
```
2. Confirm no actions from the GHPRI extension show up on it.

**Comment by aeschli** [comment]
Verified in code.

Note, the regex could also be made more specific: 

`view =~ /(pr|prStatus):github/`  -> `view =~ /^(pr|prStatus):github$/`
