### ISSUE TITLE
Right click to get a link to file or line in GitHub

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode-pull-request-github#2359]
Suggestion: Add ability to right click in various locations to get link(s) to the location *on GitHub*.

- Right click on a file in the Explorer
- Right click on a line of code in an editor

Of course, a challenge is if the file and/or line of code do not yet exist in GitHub :)

**Comment by alexr00** [comment]
We have this with the Open and Copy Permalink commands.
