### ISSUE TITLE
Unable to submit a review with one comment

### ISSUE THREAD

**Issue by burkeholland** [microsoft/vscode-pull-request-github#2367]
- Extension version: v2021.1.26474
- VSCode Version: 1.53.0-insider
- OS: Windows 10

Steps to Reproduce:

1. Start a review and add a comment
2. There is no way to submit the review without leaving a second comment

https://user-images.githubusercontent.com/686963/105080342-4a968d80-5a56-11eb-8f14-ade531669aa9.mp4

Linking https://github.com/microsoft/vssaas-planning/issues/2176

**Comment by RMacfarlane** [comment]
Yeah, this is confusing. The "Finish Review" button also isn't clear as to whether it's "comment", "approve", or "request changes". You can actually submit the review from the Description page, which is clearer:
<img width="1434" alt="Screen Shot 2021-01-19 at 11 25 07 AM" src="https://user-images.githubusercontent.com/3672607/105082959-24b6bc00-5a49-11eb-8ac9-6d4714cdfa02.png">

I wonder if we should do something more radical and get rid of the "Finish Review" and "Delete Review" buttons and instead have an "Open Review" button which would go to the description page - what do you think? Or just enable "Finish Review" in this case? @alexr00 do you have any opinions about this? I think I exclusively use the description page to submit reviews

**Comment by alexr00** [comment]
I'm with you @RMacfarlane, I also exclusively use the description page to submit reviews. I'd be perfectly happy without "Finish Review" and "Delete Review".

**Comment by sbatten** [comment]
@RMacfarlane The solution is sufficient, but I find the wording confusing. `Open Review` to me sounds the same as `Start Review` which I just did. It also sounds like `Checkout Pull Request`. I would not guess that it takes me to the description page. `Go to Review` sounds more like it will navigate me somewhere. Or `Open PR Description` if that verb is preferred.

**Comment by RMacfarlane** [comment]
`Go to Review` sounds good to me, will update to that

**Comment by Donna3344** [comment]
I would have to agree it was confusing. There's a few of us that were uncertain.
