### ISSUE TITLE
Comments on deleted files can not be revealed 

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode-pull-request-github#237]
When we checkout to pull request https://github.com/auchenberg/pullrequest-demo/pull/7, we have comments on `app.js` but the file is deleted already, so clicking on comments on comments panel will fail.

**Comment by roblourens** [comment]
I can't see the comments in the editor https://github.com/Microsoft/vscode-pull-request-github/issues/343 - but clicking them in the panel does open the editor so I think it's a new issue.
