### ISSUE TITLE
Separate view containers for PR and issues list and the active pull request

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode-pull-request-github#2371]
Right now all views are contributed into the same "GitHub" view container which uses the pull request icon. As we add additional views for "focused mode" and creating a pull request, the management of this view container becomes more of a hassle.

Having a separate viewlet for the currently active pull request makes it easy to go back and reference the pull request or issues list. To do this, we would change the existing view container to use the old GitHub icon (which [has already been requested by users](https://github.com/microsoft/vscode-pull-request-github/issues/2280)), and use the PR icon for the new container.

![separate_viewlets](https://user-images.githubusercontent.com/3672607/105089244-b6c2c280-5a51-11eb-89da-26b38f249a69.gif)

**Comment by mkwng** [comment]
Is there precedent for extensions using two icons on the sidebar like this? i understand the utility, but i wonder if there's a better way of allowing more focus here.

@misolori are there extension patterns that allow for nesting or moving deeper that can be borrowed here?

**Comment by misolori** [comment]
@mkwng we don't have any patterns that extensions can use, in the remote explorer we use a dropdown to switch between views (which has also been requested from extension authors) but that is not part of the extension api. This is a little similar pattern to our References view where a dynamic view appears only when invoked via a command:

![image](https://user-images.githubusercontent.com/35271042/105419256-40f65c80-5bf3-11eb-9369-5dd8de6dafd4.png)

We also have a concept of moving views around so the user can take any view from an extension and pull it out into it's own view, so this isn't too far from that as well. In the example below, I've taken the "TODO" view and have moved it into the remote explorer view:

![image](https://user-images.githubusercontent.com/35271042/105419525-b7935a00-5bf3-11eb-8ffd-799f51bc40c7.png)

**Comment by RMacfarlane** [comment]
To verify:

Using the nightly version of the extension
- start creating a PR, should go to the new pull request viewlet
- checkout a pull request, should also go the new viewlet
