### ISSUE TITLE
unclear FAQ

### ISSUE THREAD

**Issue by hannamtt** [microsoft/vscode-pull-request-github#2373]
- Extension version: v0.21.0
- VSCode Version: v1.51.1
- OS: ubuntu 18.04

Steps to Reproduce:

1. press sign-in in the vscode github pull request extension

The integrated sign in feature mentioned in the FAQ fails to mention if it is compatible with self hosted git hub enterprise instances, I'm using GitHub Enterprise Server 2.22.5 but regardless of the version I don't see any place to enter my servers url.

**Comment by KaiSforza** [comment]
Could we get some clarification on whether it's just versions 2.15.x and below or how exactly to get this working with GHE? It doesn't seem to work at all.


> #### Integrated sign in
> If your GitHub Enterprise is version 2.14.5 and above, you can authenticate in the same way as you would on GitHub, by clicking on the Sign In button when the dialog asking you to sign in shows up on the bottom right corner.

I've also tried editing  `"githubPullRequests.hosts": []` to no avail.

**Comment by RMacfarlane** [comment]
GHE is currently not supported, I missed updating that section of the wiki, sorry.

The last version of the extension that worked with GHE is 0.15, so it is possible to install an older version of the extension. However, there was a breaking change the proposed VSCode file decorator API that this extension uses in I believe VSCode 1.50, so using that version of the extension also requires downgrading VSCode
