### ISSUE TITLE
Aborting "Create new PR" leaves hanging task in vscode

### ISSUE THREAD

**Issue by pdreker** [microsoft/vscode-pull-request-github#2375]
- Extension version: 0.22.0
- VSCode Version: 1.52.1
- OS: macOS 10.15

Steps to Reproduce:

1. Create branch, but do not publish to GH
2. make changes
3. Go to GH Extension, click "Create new PR"
4. Receive warning about branch not being published
5. Hit ESC.
6. At this point the dialog closes, but the "Task" or progress indicator in the bottom right stays (see image)
![Progress indicator](https://user-images.githubusercontent.com/9774687/105156544-488f0600-5b0c-11eb-9688-56e2a68e3def.png)

I have not found a way to get rid of the indicator or of the corresponding status bar message other than restarting VScode.

If I *can* abort the workflow, it should be terminated cleanly.

**Comment by RMacfarlane** [comment]
We've recently reworked the create PR experience and it now no longer uses this indicator at all, and should handle cancelling branch publish properly. The next stable version will be released next week. Thanks!
