### ISSUE TITLE
Enable assigning PR to user (assign to yourself) from plugin

### ISSUE THREAD

**Issue by lachaib** [microsoft/vscode-pull-request-github#2377]
Hello,

With respect to my current company's practices, I have to assign the PR to myself when it is created and unfortunately this is not feasible from VS Code plugin and it requires me to open github's website just for this one click, so it's a time waste, adding this button in VS Code plugin would be of great help (I believe not only to me).

Would it be possible to get it?
Thanks

**Comment by RMacfarlane** [comment]
Hey @lachaib, there is an existing feature request for this (https://github.com/microsoft/vscode-pull-request-github/issues/1063), so I'm going to go ahead and close this as a duplicate.

**Comment by lachaib** [comment]
My bad I didn't find it despite my prior search.
Thanks @RMacfarlane for your quick answer.
