### ISSUE TITLE
Create PR title shows stale commit sometimes

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode-pull-request-github#2383]
Issue Type: <b>Bug</b>

1. Create a new branch in a repo
2. Create a new commit using the SCM view
3. Immediately click the "Create Pull Request" (+) action on the SCM view

The title is pre-populated with the previous commit message instead of the new one. The git state probably hasn't updated by then so we send old data to the webview. We should listen to changes in git state and update the view accordingly.

Extension version: 2021.1.27902
VS Code version: Code - Insiders 1.53.0-insider (5717c0396ad20e002edebdc23f4c23cba44fb3cc, 2021-01-20T19:59:51.303Z)
OS version: Darwin x64 19.6.0

**Comment by RMacfarlane** [comment]
was fixed as part of https://github.com/microsoft/vscode-pull-request-github/commit/27a17d80221db7f1af4403679d2621f8d92838fe

**Comment by aeschli** [comment]
Now I see the name of branch in the title (not the last commit).

**Comment by RMacfarlane** [comment]
GitHub's logic for the default title is, if there is more than one commit between the two branches, use the branch name, otherwise use the last commit. For unpublished branches I'm not sure how many commits there are and am defaulting to the branch name, maybe using the commit is better?

**Comment by aeschli** [comment]
From me, the first commit message it likelier to be a good title, and the branch name never as I use a notation like `user/issueId`. Buts its always a guess and I'm likely have to edit it anyways
