### ISSUE TITLE
Do not show log in model dialog as soon as extension got installed

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-pull-request-github#2387]
Machine 1:

- Turn on settings sync and sync up pull request extension

Machine 2:

- Turn on Settings Sync
- This installs  pull request extension 
🐛  I see following dialog immediately

![image](https://user-images.githubusercontent.com/10746682/105463140-ec54ef00-5c8f-11eb-95c5-663ba78728dd.png)

This also happens when I install the extension manually. IMO showing the dialog immediately after activating the extension might not be good idea. It shall be driven by an explicit user action to use this extension, for eg: when I open pull request view.

**Comment by RMacfarlane** [comment]
Related https://github.com/microsoft/vscode/issues/111529

**Comment by RMacfarlane** [comment]
Closing as microsoft/vscode#111529 has been fixed, a badge should appear on the accounts activity bar icon instead
