### ISSUE TITLE
Diff hunk parsing fails when the head is @ -0,0 +1 @

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode-pull-request-github#239]
For content which is addition, the diff hunk header will be like 

```
@ -0,0 +1 @
```

In this case, the line count for the added content is omitted.

**Comment by roblourens** [comment]
Verification steps?

**Comment by rebornix** [comment]
@roblourens this pr is a good one https://github.com/roblourens/test-pr-repo/pull/3 and I'm sure it works ;)
