### ISSUE TITLE
Creating pull requests failed: HttpError: Validation Failed: {"resource":"PullRequest","code":"custom","message":"not all refs are readable"}

### ISSUE THREAD

**Issue by starkpsmichael** [microsoft/vscode-pull-request-github#2391]
- Extension version: v0.22.0
- VSCode Version: GitHub Codespace Insiders
- OS: Ubuntu 20

Trying to use this extension with GitHub Codespaces (Insiders), gives the following Error when trying to create a pull request for a _private_ repo: `Creating pull requests failed: HttpError: Validation Failed: {"resource":"PullRequest","code":"custom","message":"not all refs are readable"}`

Creating a pull request for a public repo works fine.

**Comment by alexr00** [comment]
There have been auth changes around private repo in Codespaces. Please comment if you're still seeing this issue!
