### ISSUE TITLE
GH PR: picker for repository could provide help text and should stay open on focus lost

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-pull-request-github#2394]
Testing microsoft/vscode#114967

When I click on the "+" I think the picker could show a description in the input field what I have to do (pick a repository to create pr in):

![image](https://user-images.githubusercontent.com/900690/105830091-5e497300-5fc5-11eb-86f0-5d786380aa7b.png)

It should also not close when I focus out to another window.

Example of how it works better:

![image](https://user-images.githubusercontent.com/900690/105830197-7de09b80-5fc5-11eb-94d4-a4939cad73c7.png)

**Comment by RMacfarlane** [comment]
This looks like the old flow using the stable version of the extension, right? Going to go ahead and close since I don't think this applies anymore

**Comment by bpasero** [comment]
![recording (2)](https://user-images.githubusercontent.com/900690/105953653-ceaecd80-6073-11eb-9fc8-46044f678b7b.gif)
