### ISSUE TITLE
Unable to find GitHub repository matching 'undefined'.

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-pull-request-github#2395]
Testing microsoft/vscode#114967

![image](https://user-images.githubusercontent.com/900690/105830991-78d01c00-5fc6-11eb-97ca-0a5e18452fad.png)

**Comment by isidorn** [comment]
I also see this

**Comment by RMacfarlane** [comment]
Fixed with https://github.com/microsoft/vscode-pull-request-github/pull/2418

**Comment by mhmo91** [comment]
Started happening again for me

**Comment by hoducha** [comment]
@mhmo91 I got the same issue, and it was solved when I set the up-stream.

**Comment by bhack** [comment]
Same to me
