### ISSUE TITLE
GH PR: remove notifications asking to create PR

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-pull-request-github#2398]
Testing microsoft/vscode#114967

Now that we have prominent actions to start the GH PR flow I would suggest to remove this notification:

![image](https://user-images.githubusercontent.com/900690/105832496-517a4e80-5fc8-11eb-8528-e22af3a2c321.png)

**Comment by RMacfarlane** [comment]
@bpasero Was there something that triggered the notification, like publishing a branch?

**Comment by JacksonKearl** [comment]
I saw it when I published a branch. I see there also isn't a way to never show again.
![image](https://user-images.githubusercontent.com/8586769/105916178-6d401d80-5fe5-11eb-94fb-1809ffe063b7.png)

**Comment by bpasero** [comment]
Yes, when publishing a branch I think.

**Comment by eamodio** [comment]
It is a bug that there is no _Don't Show Again_ button. That will be fixed in the next insiders.
