### ISSUE TITLE
Misc UX: Pull Request Description page

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode-pull-request-github#24]
Header left-alignment is very strange... There seems to be none.

![image](https://user-images.githubusercontent.com/22350/41915495-27a75464-7956-11e8-820d-6ccd813a0056.png)

---

The white decorations don't work well in light themes:

![image](https://user-images.githubusercontent.com/22350/41915352-cad34400-7955-11e8-87f7-0054df8837a8.png)

---

The _row_ separators are omitted in most themes:

![image](https://user-images.githubusercontent.com/22350/41915380-df97cd52-7955-11e8-8672-125c04b12424.png)

---

Code snippets use non-monospace font:

![image](https://user-images.githubusercontent.com/22350/41915411-edddeeaa-7955-11e8-8c3b-baf1a05edd17.png)

---

Multiple reviews in the same file are strangely rendered:

![image](https://user-images.githubusercontent.com/22350/41915471-1827331a-7956-11e8-84e9-b77570306529.png)

---

Commit rows could be aligned with the comment rows. Right now they look like:

![image](https://user-images.githubusercontent.com/22350/41915853-fdbd90ae-7956-11e8-8c30-50cf076e6775.png)

They could probably look much more aligned with github's:

![image](https://user-images.githubusercontent.com/22350/41915873-0914396c-7957-11e8-8c28-0aa7a7ffdfa7.png)

That way every row would start with an avatar, which is good alignment.

---

There's a strange crop happening on PR 47144 from vscode:

<img width="1546" alt="screen shot 2018-06-26 at 16 06 58" src="https://user-images.githubusercontent.com/22350/41917563-00a5f3de-795b-11e8-9fd3-543d4e339c3a.png">

**Comment by rebornix** [comment]
@misolori already addressed these issues.
