### ISSUE TITLE
PR flow: unable to view Compare Changes image files

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-pull-request-github#2400]
Refs: https://github.com/microsoft/vscode/issues/114967

Have a .png file in the GH PR  flow. Click on compare changes -> error in console, can not show image in Diff View
Works fine for textual files.

```
ERR No file system provider found for resource 'github:/2020/Fiki.png?%7B%22fileName%22%3A%222020%2FFiki.png%22%2C%22branch%22%3A%22isidorn%2Fupdate%22%7D': Unavailable (FileSystemError): No file system provider found for resource 'github:/2020/Fiki.png?%7B%22fileName%22%3A%222020%2FFiki.png%22%2C%22branch%22%3A%22isidorn%2Fupdate%22%7D'
	at _handleError (/snap/code-insiders/615/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:135997)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by jucor** [comment]
That would be very, very helpful indeed. https://www.reviewnb.com/ does it integrated in Github, but it's somewhat hacky. This plugin would be the perfect place to do it smoothly!
Thanks @kieferrm @RMacfarlane  for any ideas about what it would take!

**Comment by alexr00** [comment]
Images should be fixed now.
