### ISSUE TITLE
PR flow: description field should be saved if canceled and started again

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-pull-request-github#2403]
Refs: microsoft/vscode#114967

1. Start a PR flow, write a title and a description
2. Cancel it
3. Start it again -> notice how the Title is nicely restored, while the description is empty 🐛 

We should also store the description

**Comment by RMacfarlane** [comment]
This is as designed - when you cancel we clear the state associated with the pull request. Starting it again will re-populate the title and description fields with some defaults. If you edited the title to something else and that is restored, that's a bug.

The thought is that "Cancel" is basically a discard, so you do not want to preserve any state

**Comment by isidorn** [comment]
Okey, thanks for explaining. Feel free to close this then.
