### ISSUE TITLE
Esc should exit the PR flow

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-pull-request-github#2404]
Refs: microsoft/vscode#114967

Currently you can only exit the PR flow if you press on the `Cancel` button. While this makes sense I suggest that the `ESC` also exits the PR flow. This will also make it better with regards to accessibility

I am not worried about users accidently clicking this since you nicely remember the Title, but you should also remember the description https://github.com/microsoft/vscode-pull-request-github/issues/2403

**Comment by RMacfarlane** [comment]
Since changes are discarded on cancel, I'm a bit worried about adding this. Do you think it would be confusing if it only worked when you hadn't made changes to the default title/description/branch? Or if it showed a confirmation if so?

**Comment by isidorn** [comment]
A confirmation dialog if there is some content makes sense.
If all is empty than no confirmation.

That would be a nice experience imho
