### ISSUE TITLE
Error message refers to 'undefined' when there in no published branch

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-pull-request-github#2406]
Testing microsoft/vscode#114967

Please see the screenshot below:

![image](https://user-images.githubusercontent.com/172399/105854151-cf4d5280-5fe6-11eb-8743-9fadaa78a4fd.png)

**Comment by isidorn** [comment]
Kind of dup of https://github.com/microsoft/vscode-pull-request-github/issues/2395

**Comment by RMacfarlane** [comment]
Yeah, this is a dup of #2395
