### ISSUE TITLE
Description box can be resized

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-pull-request-github#2408]
https://github.com/microsoft/vscode/issues/114967

PR flow, the descripiton box can be manually resized.
While I personally believe it would be nicer if it behaves just like the SCM commit input box (no manual resize, shift + enter for more lines) but just that it stars with two lines.

However if you prefer to keep the current manualy resize behavior I suggest that you introduce a min limit. Since currently I can resize it to be smaller than 1 line and than it looks very broken.

**Comment by TylerLeonhardt** [comment]
The problem with "no manual resize" is that pull request templates can be very long, like PowerShell's: https://github.com/PowerShell/PowerShell/blob/master/.github/PULL_REQUEST_TEMPLATE.md

so I think we still want the manual resize. but I totally agree on it needing to not resize smaller than one line.
