### ISSUE TITLE
Decorate branch name with some detail so they become distinguishable

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-pull-request-github#2409]
Refs: https://github.com/microsoft/vscode/issues/114967

Notice how in the following screenshot `isidorn/update` blends in with the rest of the text and it is very easy to miss it both in Create PR view and Compare Changes view.

![Screenshot 2021-01-26 at 15 09 50](https://user-images.githubusercontent.com/1926584/105855640-97470f00-5fe8-11eb-9f5d-2775ef93cab5.png)

Notice how GH shows branch names

![Screenshot 2021-01-26 at 15 11 29](https://user-images.githubusercontent.com/1926584/105855809-c8274400-5fe8-11eb-81b6-a91968dd5279.png)

Due to that I think we should try to decorate branch names with some details so they stand out. At least by being bold.

**Comment by RMacfarlane** [comment]
I made the branch bold in the first view, but there isn't a way to change it in the "Compare Changes" tree. Right now that's set with the tree's message property, which is just a string, and the welcome view markdown doesn't support anything besides links

**Comment by isidorn** [comment]
@RMacfarlane thanks! 
@joaomoreno maybe we should consider to make the welcome view text a bit more powerfull to support bold text at least.

**Comment by isidorn** [comment]
Looks nicer -> verified

![Screenshot 2021-01-28 at 18 22 44](https://user-images.githubusercontent.com/1926584/106174950-d5356600-6195-11eb-9915-b680710915cf.png)
