### ISSUE TITLE
`githubPullRequests.pullRequestTitle: ask` acts like "commit" or "branch"

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-pull-request-github#2410]
Testing Microsoft/vscode#114967

the default value for `githubPullRequests.pullRequestTitle:` is `ask`, but when I try to create a PR it uses the latest commit message instead, or sometimes the branch name.

**Comment by RMacfarlane** [comment]
Yeah, I'm thinking of removing these settings as suggested here: https://github.com/microsoft/vscode-pull-request-github/issues/2407

This is currently expected behavior, "ask" is now mimicking what GitHub does, but that no longer matches the enum description

**Comment by RMacfarlane** [comment]
I just deprecated this setting, so hopefully it should be clearer that this is expected behavior
