### ISSUE TITLE
Unable to find GitHub repository matching 'undefined'

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-pull-request-github#2414]
Verifying https://github.com/microsoft/vscode-pull-request-github/issues/2348

I got into the create flow, but ended in this error when I tried to create the pull request

![](https://memes.peet.io/img/21-01-003f68f3-dbed-43c8-8277-d08027b9db6b.png)

I can fetch/push from the cli and I was able to create an issue, so it seems like the extension is aware that the remote exists.

**Comment by RMacfarlane** [comment]
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/2395
