### ISSUE TITLE
Pull request description set incorrectly for "ask" 

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode-pull-request-github#2420]
Issue Type: <b>Bug</b>

1. Change `githubPullRequests.pullRequestDescription` to "ask", which is supposed to behave as GitHub and use a PR template if available or otherwise the commit body of the last commit
2. In a repo without a PR template, create a branch, make a multiline commit message, and publish the branch
3. Start the create flow

Description appears as empty rather than the commit body

Extension version: 2021.1.36542
VS Code version: Code - Insiders 1.53.0-insider (1a9dd758530782ee4bb09a15bdc484f3dcb9b5a3, 2021-01-26T05:12:23.287Z)
OS version: Darwin x64 19.6.0

**Comment by RMacfarlane** [comment]
The `githubPullRequests.pullRequestDescription` setting is now deprecated and this is the default behavior, so steps to verify are everything after that

**Comment by TylerLeonhardt** [comment]
@RMacfarlane I don't see that setting anymore. When you say it was deprecated, do you mean it was removed?

**Comment by RMacfarlane** [comment]
Yes

**Comment by TylerLeonhardt** [comment]
> When settings are marked as deprecated, they no longer show up in the settings GUI

whoa I didn't know I could mark a setting as deprecated!

Anyway, this looks like the right behavior:

![image](https://user-images.githubusercontent.com/2644648/106310559-972d5600-6218-11eb-878a-e5714d2077e4.png)
