### ISSUE TITLE
Allow editing the right half of PR's diff editor without having to check out PR

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-pull-request-github#2422]
It'd be super nice to be able to propose changes by editing the left half of the diff editor for a PR.

**Comment by alexr00** [comment]
We now show a message prompting you do check out the PR if you want to make changes. We also support GitHub's "make a suggestion" flow.

**Comment by alexr00** [comment]
Closing as we don't plan to address this.
