### ISSUE TITLE
Creating PR pulls in wrong title as a default

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode-pull-request-github#2435]
- Extension version: v2021.1.39421
- VSCode Version:
Version: 1.53.0-insider
Commit: 2ce26643d85bf985d3d3ce6ce0ff5d78866f9b5f
Date: 2021-01-28T13:51:17.482Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 19.6.0
- OS: macOS 10.15.6

Clicked on this notification and then was taken to the PR sidebar that had wrong text in title field. 

![image](https://user-images.githubusercontent.com/35271042/106209165-6518e700-6179-11eb-9a2b-41eacfffe914.png)

Unsure if this was something I maybe added in a previous PR that was never submitted, but thought it was odd as the commit message in the branch didn't mention this.

![image](https://user-images.githubusercontent.com/35271042/106209243-8679d300-6179-11eb-9fa2-f9e2cd176736.png)

Steps to Reproduce:

1. Publish a branch
2. Click on notification to create PR
3. 🐛  See title that uses wrong default text

**Comment by RMacfarlane** [comment]
Does this text look like a commit message from a branch you were previously on?

**Comment by misolori** [comment]
It was from [one of my commits](https://github.com/microsoft/vscode-docs/commit/394271ab757f85bc7d7a60e94e9e2dc64283ecc6) in the repo but not from a branch

**Comment by RMacfarlane** [comment]
I think you're right with 
> Unsure if this was something I maybe added in a previous PR that was never submitted

I'm able to repro this if I 
1. Start create by running "Create Pull Request"
2. Reload the window or restart VS Code
3. Switch branches
4. Start create again

We shouldn't preserve state then

**Comment by rebornix** [comment]
Unassign myself for verification as seems I'm not able to trigger the notification.

**Comment by TylerLeonhardt** [comment]
following these steps: https://github.com/microsoft/vscode-pull-request-github/issues/2435#issuecomment-769518005

The issue appears to be fixed. Like @rebornix, I can't seem to figure out how to trigger this notification. If the steps above are sufficient, mark as verified or let us know how to trigger this notification.

**Comment by RMacfarlane** [comment]
Those steps are sufficient, going through the notification or not doesn't matter. (But to get it to appear, use the `Git: Publish Branch...` command.) Thanks for verifying!
