### ISSUE TITLE
Create PR view: Rename the 'Cancel' button to 'Close'?

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-pull-request-github#2438]
Testing microsoft/vscode#114967

Since the button closes the view should it be called 'Close' and not 'Cancel' (I don't know why but I was also surprised to see 'Cancel' shown in a view).

If it is a close action I wonder whether the button could be removed in favor is of some close 'x' in the view's header.

![image](https://user-images.githubusercontent.com/172399/106254927-9517c700-6219-11eb-8235-1d3186d4e41f.png)

**Comment by misolori** [comment]
I agree with @RMacfarlane that cancel is more appropriate here. We do a similar thing in settings sync when conflict appear and after clicking cancel/sync the view goes away:

![image](https://user-images.githubusercontent.com/35271042/106305021-0010d000-6211-11eb-8a0c-ecf977d96a5a.png)

**Comment by egamma** [comment]
Closing the arguments make sense to me.
