### ISSUE TITLE
Make synchronization in the background optional

### ISSUE THREAD

**Issue by djc** [microsoft/vscode-pull-request-github#2440]
I really like using this extension to checkout pull requests. However, because I use interactive authentication for my SSH key, it is quite annoying when this extension (presumably) syncs some amount of state in the background (and background sync isn't very important for my use case). It would be nice if background sync frequency was configurable, or, even better, could be turned off completely.

**Comment by alexr00** [comment]
Fixed as a part of https://github.com/microsoft/vscode-pull-request-github/issues/4202
