### ISSUE TITLE
<!-- Please search existing issues to avoid creating duplicates. -->

### ISSUE THREAD

**Issue by Donna3344** [microsoft/vscode-pull-request-github#2442]
- - [ ] - 

Found in https://GitHub.com/microsoft/vssaas-planning/issues/1529 -> https://github.com/microsoft/vssaas-planning/issues/2176

Currently, there is no default query for "Open" PR's. Given that is the default in GitHub, it should be a default query as well. Otherwise "All" is the only view that lets you see PR's and non-power users won't know to adjust the query.

__Originally posted by @burkeholland in https://github.com/microsoft/vscode-pull-request-github/issues/2233__

**Comment by RMacfarlane** [comment]
Closing this since I think this was created by mistake
