### ISSUE TITLE
Locally deleted file that was added in PR will throw error when trying to open changes

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#2443]
Issue Type: <b>Bug</b>

Repro:

1. Checkout a PR that adds a file
2. Delete the file being added
3. Click on the file to view changes in the PR

Extension version: 2021.2.542
VS Code version: Code - Insiders 1.53.0-insider (dcda88e5a69a52b3a9e141af73b68caae08cb2bf, 2021-01-25T08:41:30.565Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 5, 4|
|Memory (System)|16.00GB (2.00GB free)|
|Process Argv|-psn_0_1270070 --crash-reporter-id b16ce66d-dd99-4888-ad6f-60ec3335d2e7|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221882
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30208930
wsl2promptcf:30219163
pythonvsdeb440:30224570
unusedpromptcf:30219165
folderexplorer:30219166
openfilemenucf:30219169
pythonvsded773:30223139
vstes627:30244334
pythonvspyt600cf:30251589
core-portspanel:30233467
coreuntitledfile:30249963

```

</details>

**Comment by Tyriar** [comment]
Clicking here:

<img width="288" alt="Screen Shot 2021-02-01 at 9 31 37 AM" src="https://user-images.githubusercontent.com/2193314/106495278-516aca80-6470-11eb-9f9a-c8e0eea41b68.png">

Causes this:

<img width="461" alt="Screen Shot 2021-02-01 at 9 29 52 AM" src="https://user-images.githubusercontent.com/2193314/106495231-444ddb80-6470-11eb-82ba-fd9b54f573e3.png">

**Comment by burkeholland** [comment]
I think expected behavior here is that if you delete the file added in the pull request, you get an error when you try and click on the file saying that it's been deleted.

Does that sound right?

**Comment by Tyriar** [comment]
Maybe bring up a readonly diff of the previous state?

**Comment by alexr00** [comment]
We can make sure we take into account whether the local file is deleted when we set the command for the tree item. However, I don't think it's worth listening for file events and updating the tree. 

Changes for this are needed here:
https://github.com/microsoft/vscode-pull-request-github/blob/a3040499b41ea55fcab3500bf599b7f0c5e7a98e/src/view/treeNodes/fileChangeNode.ts#L40-L64
If the `parentURI` file doesn't exist, we should use the command to open a file instead.
