### ISSUE TITLE
"Webview is disposed" error notification on switching to a branch

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-pull-request-github#2444]
When I switched to a branch with an active PR up (but I haven't interacted with GHPR extension), I got:
![image](https://user-images.githubusercontent.com/8586769/106524380-57c06d00-6497-11eb-90a1-cd3a196f9e63.png)

**Comment by alexr00** [comment]
Found a reliable way to repro:
1. Checkout a PR
2. Open the PR overview
3. Change branches from command line
4. Change branches back to the PR branch from the command line.

Error comes from here:
https://github.com/microsoft/vscode-pull-request-github/blob/2384341c9a49da7ba550847e1399c3bb0c819c12/src/github/pullRequestOverview.ts#L237-L238

**Comment by frankpeleato** [comment]
@alexr00 still experiencing this issue in v0.28.0.

**Comment by alexr00** [comment]
The fix has not been released yet and will be in 0.29.0

**Comment by frankpeleato** [comment]
> The fix has not been released yet and will be in 0.29.0

Thanks!

**Comment by connor4312** [comment]
Not able to verify due to https://github.com/microsoft/vscode-pull-request-github/issues/2860

**Comment by stuartleeks** [comment]
Verified on `v2021.7.42360`

**Comment by lmapii** [comment]
I know this issue is closed, but I'm seeing this *a lot* still.

<img width="549" alt="image" src="https://user-images.githubusercontent.com/7037131/218469924-fb9dffe2-85bc-4513-852d-1d55f29df51d.png">

Version: 1.75.0 (Universal)
Commit: e2816fe719a4026ffa1ee0189dc89bdfdbafb164

**Comment by ramonli** [comment]
![image](https://github.com/microsoft/vscode-pull-request-github/assets/1152328/ade0c872-ef85-4c99-a215-561d2ef27c87)
when I tried to paste some words to vscode, the error popped up, and many times. I have to restart vscode.

**Comment by PeterAdam2015** [comment]
Same error when copy then paste:

![image](https://github.com/microsoft/vscode-pull-request-github/assets/12378829/6aed4084-3f96-4a5c-8307-8b668d9b4301)

- system-info:
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial
- vscode-info: 
1.84.0
d037ac076cee195194f93ce6fe2bdfe2969cc82d
x64

**Comment by alexr00** [comment]
> Same error when copy then paste in plantuml extension supported file

Sounds like this is a different extension.
