### ISSUE TITLE
Error: Comment position cannot be negative?

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-pull-request-github#2446]
I made some edits to the file, the reverted them, thaat may have had something to do with it.
![image](https://user-images.githubusercontent.com/8586769/106578031-ef53a900-64f3-11eb-97c9-017c06740ea0.png)

**Comment by RMacfarlane** [comment]
Do you remember if the comment widget was open while you were making the file edits?

**Comment by JacksonKearl** [comment]
No, I believe I had undone them all before commenting. Though I did have an existing comment in the section I was editing.

**Comment by RMacfarlane** [comment]
Should be fixed with https://github.com/microsoft/vscode-pull-request-github/pull/2626
]
