### ISSUE TITLE
Comment's in tree duplicated after replying to a comment?

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-pull-request-github#2448]
After I submitted the reply to the package.json comment, the index.ts tree item duplicated?

![image](https://user-images.githubusercontent.com/8586769/106637314-60688000-6537-11eb-86f0-a47a302d8b98.png)

**Comment by JacksonKearl** [comment]
Keeps on growing

![image](https://user-images.githubusercontent.com/8586769/106639492-dcfc5e00-6539-11eb-91a8-1c35803630ab.png)

**Comment by RMacfarlane** [comment]
Closing as a duplicate, this should be fixed by recent comments refactoring + https://github.com/microsoft/vscode-pull-request-github/pull/2649
