### ISSUE TITLE
Cmd+Enter to submit review in focus mode

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-pull-request-github#2449]
In the focus mode review view, it'd be nice if cmd+enter sumbitted the review/comment, as it does on github.com.

**Comment by alexr00** [comment]
Similar to https://github.com/microsoft/vscode-pull-request-github/issues/2241

**Comment by jennyxing** [comment]
I believe hitting "cmd+enter" or "ctrl+enter" used to submit the review/comment, but it stopped working for me a few months ago.

**Comment by alexr00** [comment]
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/2241
