### ISSUE TITLE
Rendering of changed files is difficult to use

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode-pull-request-github#245]
* in the section changes in PR
* I find much more usable the showing of the filename and the path as something smaller (like the git scm does it)

I need to scroll a lot to keep track of which files I still need to review (the filename is cut by ... and only the path is visible, which is not helpful):

<img src="https://user-images.githubusercontent.com/5047891/44454764-adbd3500-a5fc-11e8-9edb-8013abede47c.png" width="200" />

**Comment by RMacfarlane** [comment]
This was fixed by https://github.com/Microsoft/vscode-pull-request-github/pull/737
