### ISSUE TITLE
"Delete branch" flow and buttons in focused mode

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode-pull-request-github#2460]
- "Delete branch" should be renamed to "Clean up..." to indicate that there are multiple resources to delete and that clicking it will not immediately delete anything
- In codespaces, this should also have a suspend codespace option

There should also be two additional buttons
- "Close", which closes the PR on GitHub
- Something like "Exit Review Mode", which like the button the description page, will switch off of the current branch. This can also offer to clean up local resources

**Comment by RMacfarlane** [comment]
Decided to not include the "Close" button since I don't think this is a common action for a checked out pull request. Also changing the "Delete branch" button to just "Delete branch..." so that it still implies the action isn't immediate, but matches GitHub.com

**Comment by alexr00** [comment]
> Something like "Exit Review Mode", which like the button the description page, will switch off of the current branch. This can also offer to clean up local resources

Using the "Exit Review Mode" from the focus view didn't offer to clean up any local resources as far as I could see. Expected?

**Comment by RMacfarlane** [comment]
Yeah, that's correct, it should just switch to the default branch
