### ISSUE TITLE
Remove "Create PR" Icon when there is a PR already 

### ISSUE THREAD

**Issue by davidbernegger** [microsoft/vscode-pull-request-github#2462]
![image](https://user-images.githubusercontent.com/16232537/107036336-c5330d00-67b9-11eb-8209-7cfb8114e9ab.png)

I want to deactivate the "Create PR Icon" when there is already a pull request available for that branch. A feature flag for completely removing it would also be nice but imho not a necessity.

**Comment by RMacfarlane** [comment]
https://github.com/microsoft/vscode-pull-request-github/pull/2457 will update this to a sharper image, but I think removing this when your branch already has a PR is reasonable

**Comment by davidbernegger** [comment]
Thanks for the fast reply! Changed title and description of the ticket to align it more to your comment.
