### ISSUE TITLE
Comment box blocked in PR review window

### ISSUE THREAD

**Issue by nschonni** [microsoft/vscode-pull-request-github#2477]
- Extension version: v0.23.0
- VSCode Version:
1.53.0 (user setup)
Commit: 8490d3dde47c57ba65ec40dd192d014fd2113496
Date: 2021-02-03T20:36:38.611Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042
- OS: Windows 10

Steps to Reproduce:

1. Open PR with review comments
2. Click on particular link with file view to see comment

![image](https://user-images.githubusercontent.com/1297909/107259021-7f20b800-6a0a-11eb-9c0f-e066b84e049f.png)

This is with the High Contrast theme

**Comment by RMacfarlane** [comment]
Closing as a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/160

**Comment by nschonni** [comment]
I think their related, but it looks like here the commend box isn't rendering at all, rather than just the overlapping issue on the other one
