### ISSUE TITLE
PR view should be expanded by default

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-pull-request-github#248]
1. Install PR extension, start vscode on a brand new --user-data-dir
2. Notice the PR view is collapsed by default and at the bottom of the GIT view

This makes it very hard to notice it.

Also the view has a very good default size (just give it enough that the 5 options are all visibe Created by Me, All...).

Due to that my recommendation is that this view should be exapnded by default - the user just installed the extension he should see the change easily.

**Comment by JeffreyCA** [comment]
I agree, it's very hard to notice if not expanded. I always have to look toward the bottom of my screen.

**Comment by RMacfarlane** [comment]
Since we now have a separate view for the extension that gets shown by default when first creating the extension, I think this should now be much more discoverable. So, closing this issue
