### ISSUE TITLE
Low-resolution "Create PR" icon in the Source Control panel.

### ISSUE THREAD

**Issue by rafegoldberg** [microsoft/vscode-pull-request-github#2480]
- Extension version: v0.23.0
- VSCode Version: 1.53.0
- OS: macOS (v11.2)

### Steps to Reproduce:

1. Checkout a branch with no corresponding PR.
2. Navigate to the source control panel and hover over the top bar.

Note the blurry icon at higher zoom levels.

<p align=center><img width=auto src=https://user-images.githubusercontent.com/886627/107291970-e431d900-6a1d-11eb-9d85-dbf5975b24c4.png>

**Comment by RMacfarlane** [comment]
We've checked in a fix for this (https://github.com/microsoft/vscode-pull-request-github/pull/2457), but it requires an update on the VS Code side to add the new codicon. Should be released this week

**Comment by RMacfarlane** [comment]
This change has been released in the latest version, 0.23.1
