### ISSUE TITLE
File decorator does not show up when connecting to remote

### ISSUE THREAD

**Issue by ankitbko** [microsoft/vscode-pull-request-github#2482]
- Extension version: 0.23.0
- VSCode Version: 1.54.0-insiders
- OS: Remote into Ubuntu from Windows machine

Steps to Reproduce:

1. Open repository in remote using Remote Extension

How the file decorator looks on local machine (Windows):
![image](https://user-images.githubusercontent.com/3169316/107336216-dabc7580-6ade-11eb-8d67-daf082a3f772.png)

How it looks on remote Ubuntu vm (notice no file decorator):
![image](https://user-images.githubusercontent.com/3169316/107336295-ef990900-6ade-11eb-806d-c1829b1c9d2a.png)

I have been able to repro it in all 3 remote environment - ssh, devcontainer and wsl.

cc: @RMacfarlane

**Comment by ankitbko** [comment]
Any idea on what maybe causing this?

**Comment by alexr00** [comment]
Tested with WSL, and I see the decorations show as expected. Looks like this got fixed in the meantime.
