### ISSUE TITLE
Organizations

### ISSUE THREAD

**Issue by AR-Student824** [microsoft/vscode-pull-request-github#2486]
This is a question: is there any way to connect a Github organization instead of your main account and getting access to those repos? I searched the web but couldn't find anything useful to my situation. Thanks in advance.

**Comment by alexr00** [comment]
There is community driven support for GitHub enterprise. You can search for "enterprise" in https://github.com/microsoft/vscode-pull-request-github/blob/main/CHANGELOG.md to learn more.
