### ISSUE TITLE
Prompted to create a PR after pushing to non-github repo

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-pull-request-github#2489]
- I have a repo with two remotes, one on github and one on visualstudio.com
- Create a branch, commit, and publish to the visualstudio.com repo
- Got a notification, "would you like to create a PR?"
- Clicked yes, nothing happened. But I think I shouldn't have gotten the notification

**Comment by alexr00** [comment]
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/2879
