### ISSUE TITLE
"There are no new commits" - The web GUI says otherwise. I'm confused

### ISSUE THREAD

**Issue by altjx** [microsoft/vscode-pull-request-github#2491]
- Extension version: 0.23.0
- VSCode Version: 1.53.1
- OS: Mac OS Catalina

Steps to Reproduce:

1. Modify a file in a branch other than master. In my case, I modified a script in the "dev" branch
2. Staged changes, committed changes, and then push changes to remote dev branch.
3. Selected the "master" branch from underneath GitLen's "branches" list and selected "Create Pull Request"
4. Once inside of the GitHub Pull Requests extension, I select the "dev" branch
5. Error: There are no new commits between the base "dev" branch and the comparing "master" branch
6. Checked the web interface and was able to create a pull request, showing changes.

This is what the extension says:
![Screen Shot 2021-02-12 at 10 03 11 PM](https://user-images.githubusercontent.com/4023423/107840119-23458e80-6d7e-11eb-9f84-924f001505fd.png)

This is what the web interface says:
<img width="1210" alt="Screen Shot 2021-02-12 at 10 05 10 PM" src="https://user-images.githubusercontent.com/4023423/107840147-60aa1c00-6d7e-11eb-9d88-075b9b9af55d.png">

I feel like I have to be using the extension incorrectly, but I'm not sure what that is. Is this a bug or what am I doing wrong?

**Comment by altjx** [comment]
Anyone??

**Comment by RMacfarlane** [comment]
Ah, instead of switching to the `master` branch and changing the dropdown to `dev`, can you try the opposite? The dropdown is meant to be the base branch and the current branch is the "compare" branch

**Comment by altjx** [comment]
Sorry for the delay. Thanks for the suggestion, @RMacfarlane. Didn't receive notification for some reason.

Haven't had any issues since then, so it could have just been a one-time fluke.

Thanks!!
