### ISSUE TITLE
vscode url redirect for github plugin

### ISSUE THREAD

**Issue by Darklight-user** [microsoft/vscode-pull-request-github#2497]
Extension Version: 0.23.1
Version: 1.53.2
OS: Linux x64 4.19.0-14-amd64 snap

Steps to Reproduce:
1. in Debian 10, install vscode using snap, install github plugin
2. When logging in to Github, I am redirected to the github authentication page. after authentication I am asked to choose a url handler for VScode. I am not sure where the handler is located in the /snap/code/ folder. I cancel the redirect to vscode and copy the token and click "signing into github" and paste the token and press enter but then I am not logged in, even after that. I tried to redo the authentication, problem persists.
I get no error and it just stays the same.

**Comment by RMacfarlane** [comment]
@Darklight-user Can you open the output panel and select "GitHub Authentication" from the output there? Is anything logged when you paste the token?
