### ISSUE TITLE
Don't show hover cards for @-mentioned users when related to JSDoc

### ISSUE THREAD

**Issue by Thomas1664** [microsoft/vscode-pull-request-github#2498]
- Extension version: 0.23.1
- VSCode Version: 1.53.2
- OS: Windows 10

Steps to Reproduce:

Write a JSDoc-comment for a symbol:
```javascript
/**
 * test
 * @param {string} e this line works
 * @returns {number | false} this does not work
 * @var does not work
*/
```
Notice that a GitHub user card appears on hovering over `@returns` or `@var`.
For `@param` it works

**Comment by micnic** [comment]
I also bumped into this issue, screenshot:
<img width="413" alt="image" src="https://user-images.githubusercontent.com/1449826/110297748-7e287980-7ffc-11eb-9c99-37dd3e5af208.png">

**Comment by kyori19** [comment]
Any updates on this issue?
I'm faced this issue with PHPDoc.

**Comment by hildjj** [comment]
Try it with `@ignore` for a quick scare.

**Comment by veritablequandary** [comment]
Would really love to see an update on this one. Had me very confused for a minute when @requires panda icon started flashing every so often :)

![Capture](https://user-images.githubusercontent.com/12649481/134100241-10d422c9-3938-4e18-9448-1a164253c136.PNG)

**Comment by hackssert** [comment]
This fix doesn't work with Svelte <script> tag.
