### ISSUE TITLE
Comments panel very aggressive

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-pull-request-github#250]
1. Checkout a PR notice how the panel agressivly opens beneath
2. Context menu in the panel title area -> hide comments panel
3. Start a PR review and notice how the comments panel is visible again

There is absolutely no option to hide the comments panel which is unhappy since it takes a large portion of the screen real estate.
My suggestion: open the comments panle only on the very first PR checkout so the user can discover it but never do it again.

I am not a fan of the comments panel but I can takle that in a seperate issue.

**Comment by Tyriar** [comment]
Related: https://github.com/Microsoft/vscode-pull-request-github/issues/70

**Comment by RMacfarlane** [comment]
Closing this as the comments panel is no longer automatically opened when a PR is checked out
