### ISSUE TITLE
Copy Link in Command Palette

### ISSUE THREAD

**Issue by mfulton26** [microsoft/vscode-pull-request-github#2501]
I did not notice at first that after creating a Pull Request in VSCode that there is a "Copy URL" button when hovering over the Pull Request name. I searched in the Command Palette and it wasn't there. I prefer to do most action via the keyboard. It would be nice to have this added to the Command Palette. Thank you.

**Comment by alexr00** [comment]
Closing as we have no plans to address this feature request.
