### ISSUE TITLE
Branches persist after selecting to delete after merging PR

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode-pull-request-github#2504]
- **Extension version:** Nightly build, v2021.2.241
- **VSCode Version:** In GitHub Codespaces in the web
Version: 1.54.0-insider
Commit: 3f0d8a14759cddea93f0dbddc12a4ef1e5586e86
Date: 2021-02-17T07:37:22.767Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36

**Steps to Reproduce:**

**Testing** https://github.com/microsoft/vssaas-planning/issues/2176

1. Merge a PR using GHPRI Nightly
2. Choose to delete the local and remote branches (leave the default options checked after merging)
3. If I go to the repo on the GitHub website (i.e. https://github.com/chrisdias/gh-static-e2e), the branch has been deleted. But in my Codespace, I still see the `branch` and `origin/branch` that should've been deleted. 
     - When I click on them, they populate with changes, which is then when I realize the change didn't populate in my repo's main branch, and I needed to do a pull to sync changes.
4. Even after the pull, although my main branch pulls in the changes from the merged PR, the branches that I thought should've been deleted are still visible. 

See ~16 minute mark of video in https://github.com/microsoft/vssaas-planning/issues/2176#issuecomment-771141071 for this behavior in action. I believe this also happened during @Burkeholland's run last week.

**Comment by RMacfarlane** [comment]
It looks like what happens is the remote branch does get deleted from GitHub, but we don't clean up the local ref to the remote branch. As in, we don't have a copy of the branch locally, but think it still exists on the remote. @eamodio The two ways I can think to do this are running `fetch` with the prune flag, or running deleteRef with something like `refs/remote/<remote name>/<branch name>`. Neither of those are exposed in the git extension API right now, I can go ahead and add one of them. Does deleteRef make the most sense here?

**Comment by bamurtaugh** [comment]
Hey @RMacfarlane - should I see this change live in the latest GHPRI nightly? I just tested the Golden Scenario, and after merging a PR and choosing to select the local and remote branches, I still see the branch "GoldenRun3-10" in my Codespace:

![image](https://user-images.githubusercontent.com/25310137/110725748-f04fb880-81cc-11eb-98ec-3917fa3902ec.png)

It was deleted from https://github.com/chrisdias/gh-static-e2e when I view it in the browser.

**Comment by RMacfarlane** [comment]
Hmm, I just gave this a try and did see the remote branch removed. I'm wondering if maybe Codespaces was behind a bit on what VS Code Insider's version it was using when you tested? If you see this again, can you check the git output channel to see if it's running `get fetch --prune`?

**Comment by bamurtaugh** [comment]
Thanks for checking into this. I just tried again, and I'm still seeing the branch I created "Testing3-12" (please let me know if I'm doing anything wrong, i.e. if I needed to take another/different step):

![image](https://user-images.githubusercontent.com/25310137/110973289-eaafbb00-8311-11eb-8878-d1dadf287693.png)

![image](https://user-images.githubusercontent.com/25310137/110973375-087d2000-8312-11eb-9c16-cdb557f87753.png)

When looking at the Git output, I don't see any `prune`.

[GitOutput3-12.txt](https://github.com/microsoft/vscode-pull-request-github/files/6131721/GitOutput3-12.txt)

The version information is:
Version: 1.55.0-insider
Commit: 06b54543d660353a04cdab6554d1f27266a537fd
Date: 2021-03-12T05:17:36.194Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36

**Comment by RMacfarlane** [comment]
I'm not able to reproduce still, can you double check that the version of the extension is `v2021.3.14943`?

**Comment by bamurtaugh** [comment]
Yes, I'm using the Nightly version of the extension `v2021.3.14943`.

![image](https://user-images.githubusercontent.com/25310137/110984192-a1666800-831f-11eb-9842-85799023a560.png)

**Comment by RMacfarlane** [comment]
Sorry for giving you the run around! I've been using the button on the description page, but the one in the focused mode view in the activity bar has slightly different logic that I didn't update. Fixing now.
