### ISSUE TITLE
Resource not accessible by integration when creating PR with fork in Codespaces

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode-pull-request-github#2507]
On Codespaces:

I'm trying to create a PR from `rzhao271/build-tools:rzhao271/winbat` to `electron/build-tools:master` but I see this:

![codespace-integration-fail](https://user-images.githubusercontent.com/7199958/108425310-22ce4d00-71ef-11eb-8eb5-ca5b4a4469c9.PNG)

**Comment by RMacfarlane** [comment]
Duplicate of https://github.com/github/codespaces/issues/2243
