### ISSUE TITLE
Auto-refresh the create PR view

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode-pull-request-github#2514]
Currently doesn't update to latest SCM state of added forks, branches, etc.  Have to cancel and click on create button again which is confusing and unintuitive. Users in study thought it was broken.

This view: 
![image](https://user-images.githubusercontent.com/12758612/108552796-a5661380-72a6-11eb-8047-fa2f2fd93c01.png)

**Comment by alexr00** [comment]
This view updates more frequently now.
