### ISSUE TITLE
Make edit and copy buttons beside the PR name always visible

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode-pull-request-github#2515]
These buttons only show on however and aren't discoverable outside of hover. I'm not sure how intuitive it is to hover over that area to discover the buttons.

On hover buttons: 
![image](https://user-images.githubusercontent.com/12758612/108553635-d72baa00-72a7-11eb-813a-08feb695c23d.png)

Regular:
![image](https://user-images.githubusercontent.com/12758612/108553621-ced36f00-72a7-11eb-9531-79febc790269.png)

**Comment by RMacfarlane** [comment]
related https://github.com/microsoft/vscode-pull-request-github/issues/2350
