### ISSUE TITLE
Make it visibly easier to see what files were changed in part of a PR

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode-pull-request-github#2517]
This part to show which changed files are in the PR isn't visibly obvious to users:
![image](https://user-images.githubusercontent.com/12758612/108559273-fc241b00-72af-11eb-84e9-9ed1e1452673.png)

After checking out a PR, it's not clear in the Explorer what files are part of the PR:
![recording (8)](https://user-images.githubusercontent.com/12758612/108559482-3d1c2f80-72b0-11eb-835e-3d6446c58f28.gif)

Users in the study were confused about the state of their local files once checking out a PR.

**Comment by alexr00** [comment]
@tanhakabir when a PR is checked out we switch to the "Changes in PR" view. Is there something else we could do to that view to make it more clear that these are PR changes?

![image](https://user-images.githubusercontent.com/38270282/142647718-ce2878c4-6f57-4759-9de6-33731f3decb1.png)

**Comment by tanhakabir** [comment]
I think this is an improvement from before! I'm happy with this now and we can see if we hear more feedback otherwise
