### ISSUE TITLE
Extension is unable to find my remote `fork`

### ISSUE THREAD

**Issue by brettcannon** [microsoft/vscode-pull-request-github#2520]
- Extension version: 0.23.1
- VSCode Version: 1.53.2
- OS:

Steps to Reproduce:

1.Try to create a PR with a remote named `fork`
2. Notice how the extension says it can't figure out where [my `fork`](https://github.com/brettcannon/cpython) is:

<img width="784" alt="Screen_Shot_2021-02-19_at_15 24 17" src="https://user-images.githubusercontent.com/54418/108761219-6da7d780-7503-11eb-8157-a70ff73dcec7.png">

**Comment by RMacfarlane** [comment]
As a workaround, I think adding `fork` to the `githubPullRequests.remotes` should fix this

**Comment by alexr00** [comment]
> As a workaround, I think adding `fork` to the `githubPullRequests.remotes` setting should fix this

Closing as this is intentional.
