### ISSUE TITLE
Cannot create issues.

### ISSUE THREAD

**Issue by jhujasonw** [microsoft/vscode-pull-request-github#2521]
- Extension version: 0.23.1
- VSCode Version: 1.53.2
- OS: Ubuntu 20.10

Steps to Reproduce:

1. Open a repository
2. Try to create an issue.
3. Save the issue, it should create the issue, but instead the window with the issue text stays open, the modified dot goes away and no issue is created.

I should note, there is nothing in the logs, and nothing in the dev console.  I am not sure where else to look to see what the issue could be.  This has been a problem for at least the last 2 versions of the extension, and I have tried to work through it to no avail.

**Comment by jhujasonw** [comment]
I can also see issues that are created, I can create PRs no problem, and I can do all the other actions within the extension except create issues.

**Comment by jhujasonw** [comment]
I *just* noticed this pop up in the console as I was trying to troubleshoot it further, but it has scope so I don't know if it's applicable:

`[Violation] Forced reflow while executing JavaScript took 31ms`

**Comment by jhujasonw** [comment]
I just tried this in vscode, same version of the extension and main app, running in WSL on a Windows 10 machine.  WSL is Ubuntu 20.04.  It seems to work there, but not on my main linux machine.  Very odd.

On a lark, I opened a remote session from the windows 10 machine to the Linux host via SSH, opened the same repository as I was trying to do this with on the linux machine, and created an issue with no problem.  This looks like it might be related to vscode on Linux itself.

**Comment by alexr00** [comment]
Do you have auto save turned off? We only do ctrl+s to create the issue when you have autosave on (when the settings is NOT `"files.autoSave": "off"`).

**Comment by jhujasonw** [comment]
Sorry I didn't see your reply until today.  Autosave is set to "onFocusChange" at the moment.   

There have been updates to vscode and the extension since I opened this, and indeed, it's still not working.

Current versions: 
Github Pull Requests and Issues: 0.25.0
VScode: 1.55.0
Linux: Ubuntu 20.10

An added oddity that I just noticed is the autocomplete stuff for the Assignees and Lables fields also doesn't work.  I wonder if it's related....

**Comment by alexr00** [comment]
I suspect your keyboard shortcuts are somehow messed up. Can you run the command "Developer: Toggle Keyboard Shortcuts Troubleshooting"? It will open a log. Try to repro your issue then share the log here and we'll see what's up.

**Comment by jhujasonw** [comment]
Here is a snippet of the log from a Ctrl-S in a new issue window (I closed and reopened a new one.)

```[2021-04-07 09:46:04.512] [renderer5] [info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl], code: KeyS, keyCode: 83, key: s
[2021-04-07 09:46:04.513] [renderer5] [info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl], code: KeyS, keyCode: 49 ('S')
[2021-04-07 09:46:04.514] [renderer5] [info] [KeybindingService]: | Resolving ctrl+[KeyS]
[2021-04-07 09:46:04.515] [renderer5] [info] [KeybindingService]: \ From 2 keybinding entries, matched issue.createIssueFromFile, when: resourceScheme == 'newIssue' && config.files.autoSave != 'off', source: user extension GitHub.vscode-pull-request-github.
[2021-04-07 09:46:04.839] [renderer5] [info] [KeybindingService]: + Storing single modifier for possible chord ctrl.```

**Comment by jhujasonw** [comment]
The issue is also not created if I click the checkmark icon at the top of the editor window, so it may be more than just a key mapping issue.

**Comment by alexr00** [comment]
Yep, seems like it isn't the keybinding. Are there any other errors in the developer console?

Can you share the contents of the new issue file you are trying to use to create an issue?

**Comment by jhujasonw** [comment]
There are no other errors in the dev console, sadly.  

Here are the contents of the editor window: 
```
instance_type not being respected

Assignees: jhujasonw
Labels: 
The name of the variable changed as well as it's type, it's now a list called instance_types 


<!-- Edit the body of your new issue then click the ✓ "Create Issue" button in the top right of the editor. The first line will be the issue title. Assignees and Labels follow after a blank line. Leave an empty line before beginning the body of the issue. -->
````

As a point, this seems to work fine in Windows vscode... which is what is bugging me.  I am not well versed in debugging vscode extensions, so my attempts to try to debug what's going on have unfortunately failed.  If you have suggestions on how to give it a go to step-wise debug it, I would give it a shot.

I've tried logging out and back in to github via the extension as well, but that doesn't effect it.

**Comment by alexr00** [comment]
I tested with on Ubuntu, but I'm still unable to repro.

Can you try leaving a blank line between the "Labels:" line and the issue body? I still saw the issue get created without leaving a blank line when I tested, but the format is such that the blank line mentioned in the comment is supposed to be there.

**Comment by jhujasonw** [comment]
Hi @alexr00,

Sorry for the delay.  I just tried it again today and... well... now it's working.  I have no idea what has changed or what is causing it to work now.  I guess my only remaining question is, if I run into it again, and nothing shows up in the logs, what is the best way to debug this?  Short of the answer to that question, which may be a separate issue, this can probably close as it's clearly an issue on my machine, for some reason....

**Comment by jhujasonw** [comment]
I JUST HAD AN EPIPHANY!  Here is some more information about this that may be helpful for you to recreate.  I have a git submodule in the project I am working on.  If I have another file open in the editor, the NewIssue.md window opens up without asking me what repo to add the issue to.  If I close all open editors, and click the add issue button, it asks me what repo to add it to and then it works.  I think this starts to pinpoint what is going on here.

**Comment by alexr00** [comment]
Closing since I was never able to repro. @jhujasonw if you're still seeing it we can keep trying to diagnose the problem.
