### ISSUE TITLE
Cramped PR title in pull request review mode

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-pull-request-github#2528]
Issue Type: <b>Bug</b>

Possibly #2459

1. Check out a PR for review

**Bug**
The title on the pull request page ends up being cramped over on the left side of the editor, making it difficult to read 

<img width="1309" alt="Screen Shot 2021-02-24 at 10 22 44 PM" src="https://user-images.githubusercontent.com/12821956/109112211-1b2b0e80-76ef-11eb-84d7-869e7975fd6b.png">

Extension version: 2021.2.34443
VS Code version: Code - Insiders 1.54.0-insider (c47da720f351455681978a48edc4d9a0d095ea0e, 2021-02-24T12:22:35.736Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (0.43GB free)|
|Process Argv|--crash-reporter-id cc7f0c9b-aa2b-4a45-8baa-81ffda32679e|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by alexr00** [comment]
This has since been fixed.
