### ISSUE TITLE
Pending checks aren't being labelled

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#2535]
Repro

- Create a PR
- Click show pending checks

![image](https://user-images.githubusercontent.com/2193314/109301128-54957400-77ec-11eb-9fc3-61f2c0069ea5.png)

Ext v2021.2.36004

Version: 1.54.0-insider (user setup)
Commit: 3290f9a73ba6fc3b1063ea32476067434ee91b1d
Date: 2021-02-26T05:13:29.656Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by alexr00** [comment]
This has since been fixed.
