### ISSUE TITLE
Milestone label not being filled

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#2536]
Repro:

1. Create a PR
2. Go to PR on .com
3. Set a milestone

![image](https://user-images.githubusercontent.com/2193314/109301184-7131ac00-77ec-11eb-80d3-88c4fe1871e7.png)

Ext v2021.2.36004

Version: 1.54.0-insider (user setup)
Commit: 3290f9a73ba6fc3b1063ea32476067434ee91b1d
Date: 2021-02-26T05:13:29.656Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by RMacfarlane** [comment]
We were rendering a div with a background even in the case where there is no milestone set, so I think the data you're seeing here is stale.

To verify:
- Use nightly version of extension
- Open a description page of a PR with no assigned milestone, check nothing is rendered under "Milestone"
