### ISSUE TITLE
Show progress when fetching labels in PR detail

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#2538]
It takes several seconds to load in microsoft/vscode's labels and show the quick pick, we should fetch them in the background, maybe when opening the PR detail so it's instantaneous.

![recording (11)](https://user-images.githubusercontent.com/2193314/109301677-206e8300-77ed-11eb-8807-ed4620d69229.gif)

Related: https://github.com/microsoft/vscode-pull-request-github/issues/2537

Ext v2021.2.36004

Version: 1.54.0-insider (user setup)
Commit: 3290f9a73ba6fc3b1063ea32476067434ee91b1d
Date: 2021-02-26T05:13:29.656Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by alexr00** [comment]
I would rather we show progress than pre-fetch the labels since we're not sure the user will want them. Repurposing the issue for showing progress.

**Comment by alexr00** [comment]
Looks like we already show progress.
