### ISSUE TITLE
Getting: Adding a comment failed....

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode-pull-request-github#255]
I am constantly getting this

<img width="569" alt="capture" src="https://user-images.githubusercontent.com/1931590/44458726-67210800-a607-11e8-9f1b-254dda5a52d9.png">

with no help how to get out of this.

**Comment by RMacfarlane** [comment]
This error is returned from GitHub when there's already a pending review for the PR open on GitHub. We should return a better, custom error message for this case
