### ISSUE TITLE
"Create Pull Request" didn't work

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-pull-request-github#2551]
- Publish a branch to github
- Notification to create a PR pops up, click the button to create
- I just have an empty view

![image](https://user-images.githubusercontent.com/323878/109696734-37410c80-7b42-11eb-9ee8-a38e30166e01.png)

From the github PR output channel

```
[Info] Review> no matching pull request metadata found for current branch roblou/settingsOpenEditor
[Info] Review> no matching pull request metadata found on GitHub for current branch roblou/settingsOpenEditor
[Info] Review> Queuing additional validate state
[Info] Review> Validating state...
[Info] Found GitHub remote
[Info] Review> no matching pull request metadata found for current branch roblou/settingsOpenEditor
[Info] Review> no matching pull request metadata found on GitHub for current branch roblou/settingsOpenEditor
[Info] Review> Queuing additional validate state
[Info] Review> Validating state...
[Info] Found GitHub remote
[Info] Review> no matching pull request metadata found for current branch roblou/settingsOpenEditor
[Info] Review> no matching pull request metadata found on GitHub for current branch roblou/settingsOpenEditor
```

**Comment by RMacfarlane** [comment]
Can you open the webview developer tools and see if there's anything in the console?

**Comment by roblourens** [comment]
I did check and there wasn't anything relevant

**Comment by RMacfarlane** [comment]
Same for the normal developer tools?

**Comment by roblourens** [comment]
Sorry I didn't check the webview developer tools. Just the normal ones. Let me see if I can repro it again

**Comment by roblourens** [comment]
This is in a remote window btw, maybe that's relevant. I get this error in webview devtools

![image](https://user-images.githubusercontent.com/323878/109726533-c01e6f00-7b67-11eb-8fd4-de6b1011c232.png)

**Comment by RMacfarlane** [comment]
I think this is https://github.com/microsoft/vscode/issues/112641
cc @mjbvz

**Comment by dantman** [comment]
I get this issue all the time and have to collapse then uncollapse the create PR view to see the UI.

**Comment by MaikoTan** [comment]
> I get this issue all the time and have to collapse then uncollapse the create PR view to see the UI.

I got this bug on Remote Container (Docker Desktop on Windows 10), too.
To collapse and uncollapse would solve it, but it is painful to do every time.

### My Environment
Version: 1.54.3 (user setup)
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-15T10:55:45.459Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by RMacfarlane** [comment]
The issue has been fixed upstream in VSCode, so going to go ahead and close this
