### ISSUE TITLE
don't require all scopes immediately

### ISSUE THREAD

**Issue by akosyakov** [microsoft/vscode-pull-request-github#2555]
It would be nice if the extension does not try to get access to public/private repos immediately but on demand. i.e. it can start with user email and name scopes and when someone tries to review private repository or comment on public it will show a notification with a question to grant permissions which will upgrade the current session.

**Comment by akosyakov** [comment]
Also wonder whether such notification should rather use a new VS Code extension authentication API to upgrade the session instead of showing a generic notification as for now with an instruction to check GitHub tokens. Some tokens maybe be controlled by a user, i.e. if it is generated by GitHub app as far as I know.

**Comment by alexr00** [comment]
Thank you for the suggestion! However, we have no plans to address this suggestion in the future.
