### ISSUE TITLE
New PR terminal link notification still shows up when an option is selected

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#2558]
- Extension version: 2021.3.10623

Version: 1.55.0-insider (user setup)
Commit: 5d80c30e5b6ce8b2f5336ed55ad043490b0b818f
Date: 2021-03-08T05:13:14.184Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Click a link like https://github.com/microsoft/vscode/pull/new/tyriar/1_54_118321 in the terminal
2. Select no, continue to github.com
3. Click another link like in step 1
4. The browser will open github.com as well as show the notification again

I guess we're not correctly disposing the terminal link provider when no is selected?

**Comment by alexr00** [comment]
Looks like this is no longer reproducible. Each time I click the link I get a notification. The browser is only opened when I choose the option in the notification.
