### ISSUE TITLE
How to be kept signed in? Remembering authorization.

### ISSUE THREAD

**Issue by allanleal** [microsoft/vscode-pull-request-github#2562]
Is it possible to remember the authorization so that whenever I open vscode again I do not need to perform a new sign-in operation?

I want to avoid clicking on the `Sign in to use GitHub Pull Requests and Issues` (at every new vscode session):

![image](https://user-images.githubusercontent.com/5825588/110598175-be653480-8181-11eb-9ff1-6393cc28fa67.png)

and then authorize the connection:

![image](https://user-images.githubusercontent.com/5825588/110598302-e2287a80-8181-11eb-8b32-cf103c92a10b.png)

**Comment by allanleal** [comment]
I'm on Linux (Neon KDE 20.04). I went through the whole process of authenticating and there was no output in the Output pane.

**Comment by RMacfarlane** [comment]
Do you have `gnome-keyring` installed?

https://github.com/atom/node-keytar/issues/74

**Comment by allanleal** [comment]
I don't have `gnome-keyring` installed? Should I install it? If so, are there additional steps to try?

**Comment by RMacfarlane** [comment]
Yeah, could you try installing it and signing in again, and see if sign in is remembered?

**Comment by allanleal** [comment]
@RMacfarlane Excellent - installing `gnome-keyring` resolved the issue. I can now exit vscode and come back to it without reconnecting manually to GitHub. Thank you so much.
