### ISSUE TITLE
Change repo/branch name to links in Create Pull Request view

### ISSUE THREAD

**Issue by burkeholland** [microsoft/vscode-pull-request-github#2563]
Make it easier for people to jump to GitHub from the Create Pull Request View by changing the repository/branch name to links

Via @egamma...

"My suggestion [...] is to change the repository/branch name into links:"
 
![image](https://user-images.githubusercontent.com/686963/110705598-41a37c00-81bc-11eb-972d-0f7947d95a62.png)

"This can be done by having a drop down only in front of the repo and branch name and by showing the currently selected repo/branch as a link label (that is not part of the drop down). In ASCII…:"

| v |  burkeholland/cloud-developer
| v |  master

**Comment by RMacfarlane** [comment]
@burkeholland I'm trying to understand the use case for this - are you just trying to continue the create on GitHub, or do you actually need to get to those repos?

I think it would be clearer to have an action in the header that just says "Create on GitHub" or something like that that could copy whatever data you've entered and open GitHub

**Comment by burkeholland** [comment]
I think it's just to make it easier for me to jump between Codespaces and GitHub. I might want to do that because I want to open the PR on GitHub, or perhaps I go to GitHub to check something - like a secret. The overall idea is to just make it easier for people to move between Codespaces and GitHub if they want to.
