### ISSUE TITLE
Can't work properly if origin don't have a branch named master/main

### ISSUE THREAD

**Issue by lychichem** [microsoft/vscode-pull-request-github#2566]
- Extension version:0.24.0
- VSCode Version:1.54.1
- OS:10.0.19043.867

Steps to Reproduce:

1.Clone a repo and delete/rename the master branch
2.Try to make PR via VSCode

**Comment by RMacfarlane** [comment]
@lychichem Do you mean you deleted/renamed the branch locally in git? What happens when you try to create the pull request?

**Comment by lychichem** [comment]
For example, first I fork your repo on github:
![image](https://user-images.githubusercontent.com/9316590/114251230-e0e1ac00-99d2-11eb-9d3f-9bdadb2680b9.png)
Then I rename the main branch to RMac:
![image](https://user-images.githubusercontent.com/9316590/114251303-230aed80-99d3-11eb-9192-d8614521cac0.png)
Then I clone it:
![image](https://user-images.githubusercontent.com/9316590/114251378-5b123080-99d3-11eb-83d4-216753f1fc67.png)
Then I made some changes and push them to RMac branch:
![image](https://user-images.githubusercontent.com/9316590/114251457-ae847e80-99d3-11eb-9422-779229039a44.png)
![image](https://user-images.githubusercontent.com/9316590/114251511-dc69c300-99d3-11eb-9c64-9befadc64ca8.png)
Then I try to make a pr via VSCode, and I can't select branch,both source branch and target branch:
![image](https://user-images.githubusercontent.com/9316590/114251559-0ae79e00-99d4-11eb-8a95-9908076fbb2e.png)
Now I rename the RMac branch both locally and on remote, this time it works:
![image](https://user-images.githubusercontent.com/9316590/114252245-d0333500-99d6-11eb-9cad-11a62b48255d.png)

The issue 100% happens on a repo with a renamed default branch.

**Comment by lychichem** [comment]
Confirmed fixed by 16aed4cee0c037c01ec0b2edb2619f8c021870f8 in extension v0.26.0. Closing.
