### ISSUE TITLE
Option to hide auto-generated files 

### ISSUE THREAD

**Issue by lendup-erikschlegel** [microsoft/vscode-pull-request-github#2567]
Some changes create a wake of auto-generated files which distract from the review process. The impact is mitigated in github by the addition of a .gitattributes file with lines like `*.snap linguist-generated`, or by filtering out these files. I see no such ability in the current version of this extension. 

It would be great to have an option whereby we can hide these files in the Pull Request explorer pane. It would be great if this extension could respect either the .gitattributes file or VSCode's File: exclude setting. 

In the below screenshot, a simple change to Colors.js created this autogenerated file tree (1 actual change, 68 generated files).
![image](https://user-images.githubusercontent.com/48072118/110817436-2595ee00-8241-11eb-81dd-41b8de35fa7d.png)

**Comment by alexr00** [comment]
Closing as we have no plans to address this.
