### ISSUE TITLE
Allow disable of PR pop up message

### ISSUE THREAD

**Issue by sirmspencer** [microsoft/vscode-pull-request-github#2571]
To reproduce
1. Push a new branch to githhub
2. Click on link to crate pull request
3. Message box shows for every click

![image](https://user-images.githubusercontent.com/33734037/110996982-974d6500-8331-11eb-81bb-e31013e3e7c0.png)

I do not want to use this feature ever.  Please let me disable the message box completely.

**Comment by RMacfarlane** [comment]
A new `githubPullRequests.terminalLinksHandler` setting was added with https://github.com/microsoft/vscode-pull-request-github/pull/2530 which allows configuring the terminal link handler so this notification will not be shown. Will be released in the next stable build next month

**Comment by dharmveerjakhar** [comment]
Is it resolved?
