### ISSUE TITLE
"Pull Requests" and "Issues" have been showing "loading..." for hours

### ISSUE THREAD

**Issue by labo28** [microsoft/vscode-pull-request-github#2572]
- VS Code Version: 1.54.2
- OS Version: 10.0.19042 Build 19042

Steps to Reproduce:

1. Install GitHub Pull Requests and Issues in VSCode
2. Authorize with Github
3. Go to the Github Section with the tab on the left side
4. Pull Requests and Issues have been showing "loading..." for hours

Does this issue occur when all extensions are disabled?: No

**Comment by saitozturk** [comment]
I have the same issue and see the 2 warnings and 2 errors below in the Developer console:

workbench.desktop.main.js:62 [Extension Host] rejected promise not handled within 1 second: Error: Git model not found
v @ workbench.desktop.main.js:62

workbench.desktop.main.js:62 [Extension Host] stack trace: Error: Git model not found	at a.getAPI (c:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\main.js:54:45368)	at new Da (c:\Users\User\.vscode\extensions\github.vscode-pull-request-github-0.24.0\dist\extension.js:1008:18628)	at Function.createProvider (c:\Users\User\.vscode\extensions\github.vscode-pull-request-github-0.24.0\dist\extension.js:1008:19195)	at Dp (c:\Users\User\.vscode\extensions\github.vscode-pull-request-github-0.24.0\dist\extension.js:1008:25145)	at Eg (c:\Users\User\.vscode\extensions\github.vscode-pull-request-github-0.24.0\dist\extension.js:1020:23211)	at processTicksAndRejections (internal/process/task_queues.js:97:5)
v @ workbench.desktop.main.js:62

workbench.desktop.main.js:2084 [[object Object]]Git model not found
$onExtensionRuntimeError @ workbench.desktop.main.js:2084

workbench.desktop.main.js:2084 Error: Git model not found
	at a.getAPI (c:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\main.js:54:45368)
	at new Da (c:\Users\User\.vscode\extensions\github.vscode-pull-request-github-0.24.0\dist\extension.js:1008:18628)
	at Function.createProvider (c:\Users\User\.vscode\extensions\github.vscode-pull-request-github-0.24.0\dist\extension.js:1008:19195)
	at Dp (c:\Users\User\.vscode\extensions\github.vscode-pull-request-github-0.24.0\dist\extension.js:1008:25145)
	at Eg (c:\Users\User\.vscode\extensions\github.vscode-pull-request-github-0.24.0\dist\extension.js:1020:23211)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
$onExtensionRuntimeError @ workbench.desktop.main.js:2084

**Comment by andrejsharapov** [comment]
I have been observing the same problem for 2 days :eyes:

<details>
<summary>screen</summary>

![image](https://user-images.githubusercontent.com/44722574/112190519-2140dc00-8c16-11eb-9d9c-12fc5224fcf8.png)


</details>

**Comment by BobcatProgrammer** [comment]
I have the same issue. Logs are mostly the same as for @saitozturk 
![image](https://user-images.githubusercontent.com/22432834/114180573-a3ccd980-9940-11eb-9133-b01cb8b5ef40.png)

**Comment by BobcatProgrammer** [comment]
I just noticed its working in another repo with a different set of extensions activated. After testing this I have verified it has to do with the `sonarsource.sonarlint-vscode` extension. When the extension is enabled Github Pull Request Extension doesn't load with above error. If I deactivate sonarlint it works without problems.

Is this caused by SonarLint or Github PR? Should I open an issue with SonarLint as well?

**Comment by lucasrodes** [comment]
Same error to me 

<img width="702" alt="image" src="https://user-images.githubusercontent.com/18101289/116392649-95bff980-a818-11eb-84ee-e6291bf774ba.png">

**Comment by lucasrodes** [comment]
UPDATE
---------

Apparently the fetch field in "origin" section in `.git/config` file was wrongly set. It should look like:

```config
[remote "origin"]
	url = https://github.com/[user]/[project].git
	fetch = +refs/heads/*:refs/remotes/origin/*
```

Previously I had:

❌❌
```config
[remote "origin"]
	url = https://github.com/[user]/[project].git
	fetch = +refs/heads/master:refs/remotes/origin/master
```

**Comment by BobcatProgrammer** [comment]
the fix proposed by @lucasrodes does not work for me unfortunately...
Also disabling other Extensions above seems to have been a race condition... Its now back to not working at all.

**Comment by Gabri3l09** [comment]
Any solutions. I got the same problem. Endless loading......

**Comment by BobcatProgrammer** [comment]
I might have found the root cause for this. The Extensions depends on the `vscode.git` extension but it never declares that anywhere. And therefore sometimes fails if the Git extensions is not loaded in time. This also explains my race condition above that removing extension "fixed" it. This changed the startup order enough to have `vscode.git` ready before the github extension loaded.
Based on the [Extension Docs](https://code.visualstudio.com/api/references/extension-manifest) I added following snippet to the `package.json` of the extension in my local `.vscode/extensions` folder

```jsonc
{
// ....
	"extensionDependencies": [
		"vscode.git"
	],
// ....
}
```
This seems to have fixed the issue for me... will keep on testing. Can anybody confirm this?

Also happy to do a PR for this. (shouldn't be too hard adding all of 3 lines 😄 )

**Comment by RMacfarlane** [comment]
It looks like there are two separate issues here:
1. If Git is not installed, the git extension throws an error when we try to access the API and we don't gracefully handle this
2. The git extension is not activating at some times

Adding the `vscode.git` extension as an extension dependency doesn't actually make VS Code try to activate it before this extension, I think we need to make an explicit call to activate

**Comment by wavypng** [comment]
So how do you fix it ?

**Comment by bhaveshpandey29** [comment]
I fixed this loading issue by removing and re-adding the repo in the vs code. Try to remove the local copy from your system and clone again.

**Comment by justincjohnson** [comment]
In case this helps anyone else, for me the following fixed this issue.

1. Quite vscode
2. `rm -rf ~/.vscode/extensions/github.vscode-pull-request-github-*`
3. Start vscode
4. Reinstall the extension, and reauth to GitHub in browser

**Comment by JoaoPedroAlex** [comment]
Hello, I am suffering from this situation and I do not see any error. How can I debug this?

**Comment by milunova** [comment]
> Hello, I am suffering from this situation and I do not see any error. How can I debug this?

I was having the same issue and after much digging I was able to find the problem. What did you name your remote repo in vscode? Run the following command in the terminal in the same location as the git folder:

`git remote -v`

You should see the name on the left hand side. If it is not named origin/upstream the extension will not work. Looking at the extension settings, you can see that is what it is looking for:

![image](https://user-images.githubusercontent.com/99946963/155196681-c02b80e3-b3fd-493d-b5b5-8525f638bff0.png)

To fix the issue, you have to add origin

`git remote add origin https://github.com/<account>/<repo>`

Alternatively, in the extension settings, you can add the name of your remote so that it knows to also look for the remote repo that came up when the above command was sent.

**Comment by wlgrd** [comment]
I don't know why @milunova's comment is marked as outdated, but this fixed it for me. I had named my new remote "github" and not "origin", and then this happened without me thinking about it. I just added `github` to the list of PR: Remotes and it worked straight away.

**Comment by Ochirsuh** [comment]
Is there someone who fixed this problem? pls help me.

**Comment by wlgrd** [comment]
> Is there someone who fixed this problem? pls help me.

As I mentioned, the below reply worked for me. 

> > Hello, I am suffering from this situation and I do not see any error. How can I debug this?
> 
> I was having the same issue and after much digging I was able to find the problem. What did you name your remote repo in vscode? Run the following command in the terminal in the same location as the git folder:
> 
> `git remote -v`
> 
> You should see the name on the left hand side. If it is not named origin/upstream the extension will not work. Looking at the extension settings, you can see that is what it is looking for:
> 
> ![image](https://user-images.githubusercontent.com/99946963/155196681-c02b80e3-b3fd-493d-b5b5-8525f638bff0.png)
> 
> To fix the issue, you have to add origin
> 
> `git remote add origin https://github.com/<account>/<repo>`
> 
> Alternatively, in the extension settings, you can add the name of your remote so that it knows to also look for the remote repo that came up when the above command was sent.

**Comment by abdulmoizniazi** [comment]
> 

hy ...I am facing same issue , please help

**Comment by wlgrd** [comment]
@abdulmoizniazi did you try looking at the solutions?

**Comment by fseminario** [comment]
I'm having this issue too but none of the solutions have worked. I'm on SSO enterprise

**Comment by JohnK1987** [comment]
Hello,

I facing same behavior as was described above, the extension is still loading. 

I can recommend to type the command below into Terminal of VScode
>git remote --v
Then you will see the list of active remotes, for example:
```
C:\Users\user\MbedCE_Test\build>git remote --v 
MyRemote https://github.com/SomeOrg/SomeRepo.git (fetch)
MyRemote https://github.com/SomeOrg/SomeRepo..git (push)
origin  https://github.com/SomeOrg/SomeRepo. (fetch)
origin  https://github.com/SomeOrg/SomeRepo. (push)
```
If the remote with your URL is not there
> ![image](https://user-images.githubusercontent.com/99946963/155196681-c02b80e3-b3fd-493d-b5b5-8525f638bff0.png)
 
then you need to add it manually via 

> git remote add NAME_OF_REMOTE `https://github.com/<account>/<repo>`

for example `git remote add origin  https://github.com/SomeOrg/SomeRepo`

BR, Jan

**Comment by fseminario** [comment]
> Hello,
> 
> I facing same behavior as was described above, the extension is still loading.
> 
> I can recommend to type the command below into Terminal of VScode
> 
> > git remote --v
> 
> Then you will see the list of active remotes, for example:
> 
> ```
> C:\Users\User\ProjectName\build>git remote --v 
> MyRemote https://github.com/SomeOrg/SomeRepo.git (fetch)
> MyRemote https://github.com/SomeOrg/SomeRepo..git (push)
> origin  https://github.com/SomeOrg/SomeRepo. (fetch)
> origin  https://github.com/SomeOrg/SomeRepo. (push)
> ```
> 
> If your repository is not on the list you have to add it via
> 
> > git remote add NAME_OF_REMOTE `https://github.com/<account>/<repo>`
> 
> for example `git remote add origin https://github.com/SomeOrg/SomeRepo`
> 
> /*************************************************************************************/
> 
> If the remote is not there
> 
> > ![image](https://user-images.githubusercontent.com/99946963/155196681-c02b80e3-b3fd-493d-b5b5-8525f638bff0.png)
> 
> then you need to add it manually via **Add item** button
> 
> BR, Jan

Thanks for sharing. I did what you mentioned but my remotes were already there and still getting the same errors. 

Also not sure if this makes a difference but I have to be on VPN, which I have been connected to access my remotes. Is it possible that can be causing an issue?

**Comment by JohnK1987** [comment]
@fseminario  I have no Idea sorry.

**Comment by shizukann** [comment]
> `git remote -v`
> 
> You should see the name on the left hand side. If it is not named origin/upstream the extension will not work. Looking at the extension settings, you can see that is what it is looking for:
> 
> ![image](https://user-images.githubusercontent.com/99946963/155196681-c02b80e3-b3fd-493d-b5b5-8525f638bff0.png)
> 
> To fix the issue, you have to add origin
> 
> `git remote add origin https://github.com/<account>/<repo>`
> 

Just like @wlgrd, @milunova 's solution helped me, don't know why it's marked outdated.

**Comment by hiresh-verma** [comment]
I reinstalled the extension, and it fixed the issue for me.

**Comment by Twomoon-Github** [comment]
if all else failed: i got the same issue with "git failed to load" so i moved to my master branch and did

git fetch upstream
git checkout master
git branch -u upstream/master

pretty sure i have done it before, but once i did it again it worked
