### ISSUE TITLE
Improvements to start work

### ISSUE THREAD

**Issue by jahead** [microsoft/vscode-pull-request-github#2573]
Hey I tired searching first and I couldn't find it. 

We have just moved from the atlassian extension (moved from atlassian to github) to this one.  
We make use of of topic branches such as `feature/*`, `release/*`, `bugfix/*`... etc 
I found that this product couldn't easily do the same. 

My proposal is to allow us to have `${prefix}` for the branch creation, which can be picked from a list when you click "start work". The list could be filled out in the settings pane. 

Are you guys open to the idea? I may be able to find some time to help?

**Comment by sergey-s-betke** [comment]
I have the same problems. I think, it is possible to detect branch type and from issue label (bug, …). Please, add label->feature name template to settings. And base branch...

**Comment by alexr00** [comment]
There is a setting that will prompt you for the branch name each time: `"githubIssues.useBranchForIssues": "prompt"`
