### ISSUE TITLE
Add OAuth support for login in VsCodium

### ISSUE THREAD

**Issue by pmahend1** [microsoft/vscode-pull-request-github#2576]
Since the extension is available for VSCodium as well, please support Github authentication/authorization to use the extension effectively. Unless this is done ,the extension doesnt work on VSCodium.

[You may add VSCodium as registered OAuth app.](https://docs.github.com/en/developers/apps/creating-an-oauth-app)

Copy of https://github.com/microsoft/vscode-pull-request-github/issues/1778

**Comment by flotwig** [comment]
Workaround: https://github.com/microsoft/vscode-pull-request-github/issues/1778#issuecomment-625986692

**Comment by alexr00** [comment]
This extension just uses VS Code's built in GitHub Authentication extension. This support would need to be added upstream in the VS Code repo.
