### ISSUE TITLE
Skipped status check is shown as pending

### ISSUE THREAD

**Issue by anantakrishna** [microsoft/vscode-pull-request-github#2580]
- Extension version: v0.24.0
- VSCode Version: 1.54.3
- OS: Windows 10

Steps to Reproduce:

1. Configure status checks for pull requests so that one of them would be skipped. For example, using the GitHub Actions and [`jobs.<job_id>.if'](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idif).
1. Create a PR.
1. Wait for the checks to be executed.
1. Make sure that one of the checks was skipped: 
![image](https://user-images.githubusercontent.com/6065071/111617964-65973b00-8816-11eb-8e3e-999bc85e51d9.png)
1. Open the same PR in VS Code and see that the same check is in the pending state: 
![image](https://user-images.githubusercontent.com/6065071/111618079-8790bd80-8816-11eb-9455-6ca450675734.png)

**Comment by anantakrishna** [comment]
Moreover, while one of the checks is really in pending state, I've caught the following strange situation:
![image](https://user-images.githubusercontent.com/6065071/111647456-16acce00-8835-11eb-8cd7-17a25ee73dcb.png)

**Comment by drewda** [comment]
This same issue is happening to me (VS Code says "1 successful check and 1 pending check" while github.com says "1 successful and 1 skipped checks")

**Comment by burkeholland** [comment]
The issue is that GitHub is returning a "NEUTRAL" status for these items. It should be "SKIPPED". For now, I've implemented a fix to treat NEUTRAL as SKIPPED, but I'm not sure what the edge cases of doing this might be.

I see the missing text as well. @anantakrishna can you open another issue for that?

**Comment by anantakrishna** [comment]
Sure, I will.
