### ISSUE TITLE
Issues are "Loading..." forever when you don't have a folder opened

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#2581]
Seems the case where no git repo exists isn't handled, the issues view doesn't handle it nicely like the PR view
<img width="346" alt="Screen Shot 2021-03-18 at 7 28 24 AM" src="https://user-images.githubusercontent.com/2193314/111642677-87170900-87bb-11eb-839a-a95cd19ce8c7.png">

**Comment by aeschli** [comment]
I first thought there's an authentication issue, then looking for error messages, trust issues...

Should show the same message as with Pull requests, or, even better, work without any folder open.
