### ISSUE TITLE
Confusing on how to get out of a PR when you've checked out a PR

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode-pull-request-github#2586]
UI wise it's not clear you need to find the PR page again to get out and back to the branch you were on. We saw in GHPRI study users were confused about what state they were in after checking out a PR so they might be confused on how to get out from this flow since they might not release they can just checkout the branch they were on before

![recording (19)](https://user-images.githubusercontent.com/12758612/111689734-a462cc00-87e9-11eb-9968-515f63811c20.gif)

**Comment by tanhakabir** [comment]
I think having more clarity about what state you're in once checking out a PR could help. Or a clear button in the extension to exit the PR

**Comment by alexr00** [comment]
We do now have a clear "Exit" button in the sidebar:

![image](https://user-images.githubusercontent.com/38270282/142658296-393b1868-8a64-4ba0-80fd-6ac9d7a2460f.png)
