### ISSUE TITLE
Have sections of the TreeView open on load at the beginning

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode-pull-request-github#2587]
In GHPRI studies I saw a user struggle to find PRs. I think having the dropdowns open by default at the beginning would explain what the extension has/can do quickly. As well as find PRs quickly.

To look like this: 
![image](https://user-images.githubusercontent.com/12758612/111696075-14c11b80-87f1-11eb-8e37-01a480f451d8.png)

Instead of:
![image](https://user-images.githubusercontent.com/12758612/111696117-230f3780-87f1-11eb-9634-d5e14c663e68.png)

**Comment by bpasero** [comment]
I am actually not a big fan of this change because the list of all opened PRs is never relevant to me.

//cc @alexr00

**Comment by alexr00** [comment]
Maybe the "all" should be added as a query to to `queries` setting? That way people who don't want it at all can remove it.

**Comment by bpasero** [comment]
I wouldn't mind getting the node expanded that lists the PRs I need to review 👍
