### ISSUE TITLE
The comment icon in the TreeView is unclear and tiny

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode-pull-request-github#2589]
In the treeview, the comment icon with a diamond is unclear that there are comments and quite tiny. Maybe a an icon like this would be better?
![image](https://user-images.githubusercontent.com/12758612/111698305-e8f36500-87f3-11eb-8424-569a77446faa.png)

What it looks like currently:
![image](https://user-images.githubusercontent.com/12758612/111698269-de38d000-87f3-11eb-8797-33c720e054f0.png)

**Comment by alexr00** [comment]
Seems like there's a Unicode character for a speech bubble, maybe we can use that: U+1F5E8

**Comment by RMacfarlane** [comment]
Maybe 💬? U+1F5E8 is a little hard to see on a dark themes, but 💬 is also a bit hard on light themes.
<img width="363" alt="Screen Shot 2021-04-09 at 2 55 52 PM" src="https://user-images.githubusercontent.com/3672607/114244650-b5fc4700-9943-11eb-9ded-1007d68210d9.png">
<img width="365" alt="Screen Shot 2021-04-09 at 2 55 43 PM" src="https://user-images.githubusercontent.com/3672607/114244662-b85ea100-9943-11eb-903d-5fe8cf4d6aae.png">


<img width="364" alt="Screen Shot 2021-04-09 at 2 53 59 PM" src="https://user-images.githubusercontent.com/3672607/114244512-7c2b4080-9943-11eb-8ea3-df285756e0e7.png">
<img width="365" alt="Screen Shot 2021-04-09 at 2 53 11 PM" src="https://user-images.githubusercontent.com/3672607/114244665-bb599180-9943-11eb-9852-1bb3bdfc7cf0.png">

**Comment by alexr00** [comment]
It is a bit hard to see. I like the one in your second set of screenshots more.

**Comment by tanhakabir** [comment]
Hmm I do like the second set with the lighter icon but it is difficult to see/notice on light theme. Hm how does it look on windows?

**Comment by tanhakabir** [comment]
I see this but not sure what the dark mode looks like: 
![image](https://user-images.githubusercontent.com/12758612/114419679-7d898280-9b68-11eb-8320-3231812fba68.png)

I think for windows it's fine but not so sure about the visibility on mac. We could try it for now and see if we get complaints in future studies or feedback?

**Comment by meganrogge** [comment]
I'm still seeing the diamond shape, no speech bubble.

![comment](https://user-images.githubusercontent.com/29464607/116613628-c1f97a00-a8ed-11eb-870e-81416a204576.PNG)

**Comment by meganrogge** [comment]
This is using v0.25.1 of GHPR

**Comment by RMacfarlane** [comment]
@meganrogge are you using the [nightly](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github-insiders) version of the extension? note you have to disable or uninstall the stable one, they conflict when installed side-by-side

**Comment by meganrogge** [comment]
I do not have the nightly version installed.

**Comment by meganrogge** [comment]
![extension](https://user-images.githubusercontent.com/29464607/116614054-477d2a00-a8ee-11eb-833b-e250aa394b4d.PNG)

**Comment by RMacfarlane** [comment]
Ok, cool, can you use that one to test with? The changes for this iteration haven't been published to stable yet, so will only show up in nightly

**Comment by meganrogge** [comment]
Oh ok yep I'll try that

**Comment by meganrogge** [comment]
looks great 😄
