### ISSUE TITLE
View Changes from each commit in the pull request

### ISSUE THREAD

**Issue by akshayy-narayanaram** [microsoft/vscode-pull-request-github#2594]
Having multiple commits in the PR, it would be easier to see the changes from each commit in the PR or a range of commits in the PR instead of only the squashed content of all the commits

**Comment by RMacfarlane** [comment]
A list of commits and all of the files changes within them is available if you check out the pull request:
<img width="339" alt="Screen Shot 2021-03-19 at 7 52 19 AM" src="https://user-images.githubusercontent.com/3672607/111799274-18ec4800-8888-11eb-9ae9-a67ddb808f6f.png">

There's an existing feature request to also make this visible without checkout out the PR: https://github.com/microsoft/vscode-pull-request-github/issues/2201

I'm going to close this as a duplicate, thanks!
