### ISSUE TITLE
Improve comment icons UX

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode-pull-request-github#26]
Instead of telling the user what he can't do:

![image](https://user-images.githubusercontent.com/22350/41916204-d55c7016-7957-11e8-88fe-4b0812715431.png)

We should prevent him from attempting to do it at all.

Also the icon is very bad in certain scenarios:

![image](https://user-images.githubusercontent.com/22350/41916384-384388f4-7958-11e8-94b0-01edefd36284.png)

**Comment by rebornix** [comment]
We no longer use the comment icon.
