### ISSUE TITLE
Indentation off in comments

### ISSUE THREAD

**Issue by backerman** [microsoft/vscode-pull-request-github#2603]
Issue Type: <b>Bug</b>

Open PR paulomarquesc/AzureRmStorageTable#60 in the GitHub extension PR viewer.
View the first comment.
Expected result: Indentation of sample code is as on GitHub.
Actual result: Indentation of opening braces is not correct.

Expected:
![image](https://user-images.githubusercontent.com/115895/112085337-9396bb00-8b47-11eb-8bff-5681a962ac2b.png)

Actual:
![image](https://user-images.githubusercontent.com/115895/112085361-9c878c80-8b47-11eb-83ff-0aaf551b147b.png)

Extension version: 0.24.0
VS Code version: Code - Insiders 1.54.0-insider (192c817fd350bcbf3caecae22a45ec39bae78516, 2021-02-19T05:14:28.632Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.75GB (17.57GB free)|
|Process Argv|. --crash-reporter-id 874023d1-7365-4731-bee1-50b9f3866079|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30263608
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
vstry914:30244316
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
pythonvsnew554:30265444
pythontb:30258533
pythonvspyt943:30277000
openwslfolder:30278404
vscoresta800cf:30265948
vsc_aacf:30263846
vspre833:30267464
vsfjg287:30275553
vshan820cf:30276953

```

</details>

**Comment by alexr00** [comment]
Looks like the comment mixes tabs and spaces.
