### ISSUE TITLE
"Would you like to create PR" popups after publish my repo, but there is only one branch!

### ISSUE THREAD

**Issue by codehz** [microsoft/vscode-pull-request-github#2604]
- Extension version: 0.24.0
- VSCode Version: 1.54.3
- OS: Windows_NT x64 10.0.21332

Steps to Reproduce:

1. Create a local repo (with emoji as default branch name)
2. Open it in vscode
3. Write random thing into it
4. Publish it by github.publish command
5. Waiting publish success
6. Now you got two notifications
![image](https://user-images.githubusercontent.com/13158903/112197917-8bbe4000-8c47-11eb-9e81-7dec623d1e18.png)
7. click the create PR button
![image](https://user-images.githubusercontent.com/13158903/112198119-c1632900-8c47-11eb-97e5-e4c29f78800c.png)
8. And in github web ui
![image](https://user-images.githubusercontent.com/13158903/112198221-da6bda00-8c47-11eb-854c-245624235115.png)

**Comment by tanhakabir** [comment]
![image](https://user-images.githubusercontent.com/12758612/144353775-51140138-a067-4762-9d39-0d4b731f8e5d.png)

![image](https://user-images.githubusercontent.com/12758612/144353807-fcfedba8-3ed5-411f-9a5b-41c60eabd8fe.png)

Still seeing the notification to create a PR with empty branch that has emoji in name using the Pre-release version of GHPRI

**Comment by alexr00** [comment]
This appears to be an issue with GitHub. Initially, when the GitHub repo is created, the default branch is set to `main`, even though if you look on the web UI it shows the expected 💥 branch name. A few moments later, the same REST API call returns the correct 💥 branch as the default branch.

**Comment by alexr00** [comment]
Closing as upstream.
