### ISSUE TITLE
Allow disabling the "Do you want to create a pull request..." message from the terminal.

### ISSUE THREAD

**Issue by mckalexee** [microsoft/vscode-pull-request-github#2605]
In my workflow I generally click the `Create a pull request for ...` link in the terminal to create a pull request after pushing a branch.

Since #2348 it appears this is intercepted and I have to click "No, continue to github.com"
![image](https://user-images.githubusercontent.com/6014098/112204035-94802900-8be9-11eb-9e8e-aac80b519a77.png)

I prefer creating pull requests outside of VS Code. I would like this extension to allow me to disable this popup or to have an option saying "No, don't ask again". 

I apologize if this functionality exists, but I cannot seem to find it in the settings or by searching.

It's small this, but it's a bit annoying that I have click through twice.

**Comment by frenck** [comment]
![image](https://user-images.githubusercontent.com/195327/113518326-f6e00e80-9585-11eb-902e-5c3dfedaf64d.png)

Please, for the love of god, stop annoying people. That will make them stop using the extension.

This extension does not respect pull request templates from upstream, I don't want to use this provided / suggestion ever. Yet, I'm annoyed by it constantly. For someone like me, making around 300 PRs a month, that is just shitty.

**Comment by frenck** [comment]
@RMacfarlane Hero! ❤️

**Comment by alexr00** [comment]
Would be nice to have a third button on there to configure the setting!

**Comment by aberonni** [comment]
If I understand this correctly, this should've enabled a setting for me to configure this? Yet I can't see it anywhere:
![image](https://user-images.githubusercontent.com/1260402/117119040-d2986d00-ad91-11eb-8f8e-19cb4cfaa83d.png)

Am I missing something? Using extension v0.25.1

**Comment by RMacfarlane** [comment]
@aberonni This change hasn't been released yet, we should release version 0.26.0 by the end of the week
