### ISSUE TITLE
Show a message when there are no milestones defined

### ISSUE THREAD

**Issue by stevencl** [microsoft/vscode-pull-request-github#2606]
Testing microsoft/vscode#119507

In a repo with no milestones created, clicking assign milestone should show a message, perhaps something like: "No milestones created for this repo. Go to https://github.com/"insert repo url here"/milestones/new to create a new milestone

![image](https://user-images.githubusercontent.com/1704059/112127307-36d5e780-8bbd-11eb-947a-c8ef6d97e845.png)

**Comment by mjbvz** [comment]
Tried with `2021.3.35542` but looks like we may need a new build for this

**Comment by rebornix** [comment]
@RMacfarlane do we have a new build for verifying issues?

**Comment by RMacfarlane** [comment]
Oh oops, I apparently just read the title and interpreted it as something else - I added placeholders in the sidebar for when milestones, reviewers, etc have not been assigned yet. Will fix this in next iteration.
