### ISSUE TITLE
do not auto select a default branch if current branch doesn't have a remote  

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode-pull-request-github#2608]
Testing microsoft/vscode#119527

- create a new branch without pushing it to a remote (e.g. "aweinand/foo")
- make sure to be on that branch (shown in the status bar)
- in the "Create Pull Request" view create a new pull request

Observe: In the "Merge Change From" section the branch selector shows the first branch of the list of all branches ("TylerLeonhard/ignore-this") which is totally unrelated to the currently selected branch shown in the status bar.

<img width="491" alt="2021-03-23_15-28-55" src="https://user-images.githubusercontent.com/1898161/112162695-94355d00-8bec-11eb-88cf-0d2546cea7c3.png">

This choice is confusing.

I suggest in this case to not select a branch in the branch selector and explain somewhere (e.g. as the placeholder text) that the current branch has not yet pushed to a remote.

**Comment by RMacfarlane** [comment]
To verify:
1. Use nightly version of the GHPRI extension
2. Create a new branch but do not publish it
3. Start creating a PR

The unpublished branch name should show up in the dropdown and be selected by default. Trying to create the PR will result in a dialog asking if you want to publish the branch.
