### ISSUE TITLE
Lost my comment: comment suddenly disappears

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode-pull-request-github#261]
Version: 0.14

I typed a long comment and suddenly the comment editor closed without notice and my comment was gone. I can reproduce this if I:
* write a comment
* refresh the PR view

However in this case I am quite sure I did not refresh the PR view, but maybe you do this automatically in the background.

**Comment by roblourens** [comment]
Stil reproes, assuming this is the scenario:

- Open description page
- Type in "Leave a comment" and don't submit
- Click refresh in "Changes in Pull Request"
- Comment text disappears

**Comment by RMacfarlane** [comment]
@roblourens I think this fix is for comments within the editor when doing any kind of refresh action

The comment on the description page os currently only persisted when navigating away from the page and back, but get reset when the webview itself is refreshed, either on when looking at a description page of a different PR or clicking refresh in "Changes in Pull Request"

**Comment by dalvallana** [comment]
It also happens that when I'm writing an inline comment, I still want to check other files to remember any variable or method name I want to mention in the comment. I noticed that **when going to another tab to see another modified or added file, and then coming back to the file I'm commenting on, all what I had written disappeared**. This doesn't happen when commenting on the Description; I can move across tabs and my in-progress comment is still there when I come back.

**Comment by RMacfarlane** [comment]
@rebornix has fixed this, inline comments are persisted when using VSCode version 1.29.
