### ISSUE TITLE
Create button is not visible in default layout

### ISSUE THREAD

**Issue by stevencl** [microsoft/vscode-pull-request-github#2610]
Testing microsoft/vscode#119507

The default layout for the extension seems to hide most of the create button:
![image](https://user-images.githubusercontent.com/1704059/112123421-27ed3600-8bb9-11eb-8c50-292ba34acfa9.png)

**Comment by alexr00** [comment]
We can't control the size of the views here. Ideally Compare Changes would be smaller, but the best we can do is collapse it all the way. If we collapse it, then I don't think anyone will find it.
