### ISSUE TITLE
Slightly confusing view in create new pull request UX

### ISSUE THREAD

**Issue by stevencl** [microsoft/vscode-pull-request-github#2611]
Testing microsoft/vscode#119527

When creating a new pull request, I still see details of earlier pull requests. I think it might make more sense when in the middle of creating a new pull request that the view only shows the details of the new pull request being created. It's slightly confusing for example seeing a message in the top half of the view saying that there are no commits between these two branches I want to merge but the bottom half of the view has an affordance that lets me view changes in another pull request. For a second I thought the changes it was letting me review were in this new pull request I was trying to create.

![image](https://user-images.githubusercontent.com/1704059/112128890-c4fe9d80-8bbe-11eb-8e4f-a0ee09bd76f0.png)

**Comment by alexr00** [comment]
This is happening because we use the last commit to add  the title and message. If the from and into branches are the same we could remove that though.
