### ISSUE TITLE
Dangerous `Delete Review` button in comment view

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-pull-request-github#2613]
Isn't this button really dangerous to have right there? Won't it delete all comments I've done so far?

![image](https://user-images.githubusercontent.com/22350/112292065-f4102000-8c4d-11eb-91ea-17538fd07f31.png)

I only expected two buttons:

- Finish Review
- Add Comment
- Cancel Comment

**Comment by RMacfarlane** [comment]
There should be a modal dialog asking for confirmation when this is run

**Comment by joaomoreno** [comment]
That helps yeah. But is it really useful to have that button over there at all?

**Comment by mefcorvi** [comment]
I agree with @joaomoreno. I've never needed to delete review, although it's very common when I want to cancel comment. I don't know how to cancel comment so I usually end up with several empty forms floating around, it's fine but a bit annoying. BTW I'm not sure that "Delete Review" button exists on GitHub, at least I've never seen it.
