### ISSUE TITLE
Issues section stuck in 'Loading...' in an empty workspace

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-pull-request-github#2614]
Open the GHPRI view container in an empty workspace.
The Issues section is stuck in the 'Loading...' state, see below

![image](https://user-images.githubusercontent.com/172399/112340112-8cdf8380-8cc0-11eb-9280-92795434c9d2.png)

**Comment by RMacfarlane** [comment]
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/2581
