### ISSUE TITLE
"no upstream branch" for a pushed branch without a remote tracking branch

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-pull-request-github#2622]
1. Create a branch on the CLI, commit, and `git push` it
    - I use `[push]\ndefault=current` in my gitconfig, so I can just `gp` without needing `-u origin <branch>`
2. Click the pull request link and enter the flow in the extension
3. Submit the pull request and get this warning:

![](https://memes.peet.io/img/21-03-295dcb9e-6af9-45f6-8e01-fd15adaf7afc.png)

Clicking "Publish" made it go through, but I was confused why it's needed since the branch was already pushed to Github. I realized writing this issue that it was probably because I had pushed the branch but didn't have a remote tracking branch.

Maybe the extension should do some inference here -- seeing that I'm PRing the branch which already exists locally and remotely even though there's no explicit tracking set up?

**Comment by alexr00** [comment]
Closing as the the image with warning has expired.
