### ISSUE TITLE
Can't create issues - "Creating issue failed: Issues are disabled for this repo" although enabled

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode-pull-request-github#2627]
- Extension version: GHPRI Nightly, v2021.3.42303
- VSCode Version: Codespaces
Version: 1.55.0-insider
Commit: c185983a683d14c396952dd432459097bc7f757f
Date: 2021-03-30T12:43:45.267Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36
- OS: Windows 10, Chrome browser

Steps to Reproduce:

1. Create a Codespace on https://github.com/bamurtaugh/communication-services-web-calling-hero
2. Attempt to create an issue 
3. Fails with "Creating issue failed: Issues are disabled for this repo" 
![image](https://user-images.githubusercontent.com/25310137/113073937-f1965480-917e-11eb-9081-ea48c8043b43.png)

4. Check my repo, issues are enabled. However, I noticed they're disabled for the upstream from which I forked https://github.com/burkeholland/communication-services-web-calling-hero (although issues are enabled for the upstream from which Burke forked, https://github.com/Azure-Samples/communication-services-web-calling-hero)

Here are my remotes when using `git remote -v`:

![image](https://user-images.githubusercontent.com/25310137/113073853-c449a680-917e-11eb-88c5-7ce65236f196.png)

I ran into this as the "owner" of the fork, and a collaborator I added to the fork also experienced this same behavior. 

I saw https://github.com/microsoft/vscode-pull-request-github/issues/1517, which seems to be related here.

**Comment by alexr00** [comment]
We try to be smart and when a repo is a fork, we figure that you are most likely to want to create an issue on the upstream.

Looks like we should fallback to the fork for creating the issue if we encounter this error.

**Comment by nathansegers** [comment]
@alexr00 What if we want to edit issues onto the fork/origin repo? Can we configure that somewhere? My Fork is the continuation of a disbanded project.

**Comment by alexr00** [comment]
@nathansegers we should also add a way for you do that :)

**Comment by PostmanSpat** [comment]
I have a similar issue, but slightly different symptom. Issues are enabled on the origin repo, I forked that repo and enabled issues on my own fork. If I add an issue to my fork via GitHub it does not appear in VSCode. If I add an issue via VSCode it logs under the origin, not my fork.

**Comment by asecurityguru** [comment]
@alexr00 Did we fix this issue?

**Comment by mipskevin** [comment]
Did anything come of this?  My fork will stay independent of the upstream and I want my issues create in my fork (origin), not in upstream.

**Comment by alexr00** [comment]
If your fork is always going to remain independent of the upstream, then you can remove `upstream` from the setting `githubPullRequests.remotes` to solve this.

**Comment by lup9304** [comment]
> If your fork is always going to remain independent of the upstream, then you can remove `upstream` from the setting `githubPullRequests.remotes` to solve this.

How to solve it in github web page?

**Comment by scalewithlee** [comment]
> > If your fork is always going to remain independent of the upstream, then you can remove `upstream` from the setting `githubPullRequests.remotes` to solve this.
> 
> How to solve it in github web page?

Just make sure "Issues" is select on the Settings -> Features section:

<img width="1073" alt="Image" src="https://github.com/user-attachments/assets/3a68683c-de59-4b71-99f0-b21dc2acf280" />
