### ISSUE TITLE
Suggests creating a PR when pushing to a non-GitHub remote

### ISSUE THREAD

**Issue by deadlydog** [microsoft/vscode-pull-request-github#2629]
- Extension version: 0.24.0
- VSCode Version: 1.54.3
- OS: Windows 10

Steps to Reproduce:

1. Clone a non-GitHub repository (e.g. an Azure DevOps repository)
2. Create a branch
3. Make a change and commit it
4. Push the branch to the remote (e.g. Azure DevOps)
5. The extension pops up asking if we want to create a Pull Request, even though the branch wasn't pushed to GitHub, and the extension cannot create Pull Requests on Azure DevOps.

I assume the problem exists when using other hosting providers as well (BitBucket, GitLabs, etc), but I haven't confirmed.

I would expect the extension to only prompt me to perform GitHub operations when I'm pushing changes to GitHub.

**Comment by ahmed2m** [comment]
I experience this so often, that it starting to become a little annoying

**Comment by alexr00** [comment]
Should be fixed now, please ping this issue if you're still seeing in the latest version!
