### ISSUE TITLE
No indication on sidebar where comments are 

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode-pull-request-github#263]
![image](https://user-images.githubusercontent.com/4033249/44539860-11f1fe80-a6ba-11e8-8edf-2c205d50384a.png)

I have to scroll through the whole document to find where the comments are.

**Comment by RMacfarlane** [comment]
Fixed by https://github.com/Microsoft/vscode/commit/b50bc73a242b2e2ea786640f8b90cafc658bd0f0
