### ISSUE TITLE
Emoji menu doesn't open in comment / review summary field

### ISSUE THREAD

**Issue by drzamich** [microsoft/vscode-pull-request-github#2631]
- Extension version: 0.24.0
- VSCode Version: 1.54.3
- OS: macOS Catalina 10.15.7

When doing code review, I have no problems opening emoji menu (`⌃` + `⌘` + `Space`) when making a comment about a particular line of code.
![emoji1](https://user-images.githubusercontent.com/26330688/113276623-4bfaf680-92e0-11eb-8d22-65ab69d4c89d.gif)

Yet on PR description page, when I want to summarise my review, the emoji menu does not open when I press the key combination. Same applies to the comment field at the very bottom.
Emojis are very important to providing a friendly atmosphere so having this working would be great.

![emoji2](https://user-images.githubusercontent.com/26330688/113277247-d2173d00-92e0-11eb-9bb4-742093f3a4d2.gif)

Steps to Reproduce:

1. Open a description of some pull request.
2. Scroll down to the "Leave a comment" field.
3. Focus the field and try to open emoji menu with `⌃` + `⌘` + `Space`

**Comment by alexr00** [comment]
@drzamich I'm not able to reproduce this issue on Windows. If you're still seeing it on mac, please comment and I'll reopen!
