### ISSUE TITLE
Automatic PR branch detection criteria are unclear

### ISSUE THREAD

**Issue by TBBle** [microsoft/vscode-pull-request-github#2638]
Issue Type: <b>Bug</b>

----

I see that #2158 has introduced automatic recognition of branches for PRs, but I can't understand how it's supposed to work.

I have the following in my .git/config:
```
[core]
	repositoryformatversion = 0
	filemode = false
	bare = false
	logallrefupdates = true
	ignorecase = true
[remote "origin"]
	url = https://github.com/containerd/containerd.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
	merge = refs/heads/master
[remote "tbble"]
	url = git@github.com:TBBle/containerd.git
	fetch = +refs/heads/*:refs/remotes/tbble/*
[user]
	name = Paul \"TBBle\" Hampson
	email = Paul.Hampson@Pobox.com
[branch "wcow_mount_layers"]
	remote = tbble
	merge = refs/heads/wcow_mount_layers
[branch "wcow_commit_layers"]
	remote = tbble
	merge = refs/heads/wcow_commit_layers
	github-pr-owner-number = "containerd#containerd#4415"
[branch "wcow_compare_layers_to_tar"]
	remote = tbble
	merge = refs/heads/wcow_compare_layers_to_tar
	github-pr-owner-number = "containerd#containerd#4399"
```

I added the `github-pr-owner-number` to those two branches by hand, to confirm that the non-auto-detection part works.

I have tried renaming 'origin' as 'upstream' and 'tbble' as 'origin', without any effect, using `git remote rename`.

The Debug logs from the GitHub PR extension aren't helpful, except indicating that apparently nothing is found, or something is null?

This is what I get 

```
[Debug 1617598078.378s] GitHubRepository> Fetch metadata containerd/containerd - done
[Debug 1617598078.482s] Review> no matching pull request metadata found for current branch wcow_mount_layers
[Debug 1617598078.482s] Review> no matching pull request metadata found on GitHub for current branch wcow_mount_layers
[Debug 1617598078.546s] PullRequestOverviewPanel> initialized with PR
```

The only relevant config changes for VSCode are
```
"githubPullRequests.defaultMergeMethod": "rebase"
"githubPullRequests.logLevel": "debug"
```

The PR in question looks like it should match:
![image](https://user-images.githubusercontent.com/138397/113538804-7ff75400-961f-11eb-8207-864d96d4b3dc.png)

Is there something I'm doing wrong here? Some overlooked setting? I'm not aware of an option to control this detection, and #2186 appears to concur.

Otherwise, perhaps there's a bug? I can't think what it could be, but is there any chance it is suffering a case-mismatch because my remote's name is 'tbble', but the repo on GitHub is 'TBBle'? The remote's URL is correctly cased, anyway.

----

Extension version: 0.25.0
VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:55.261Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4800U with Radeon Graphics          (16 x 1797)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.42GB (1.98GB free)|
|Process Argv|--folder-uri file:///c%3A/Projects/containerd/containerd --crash-reporter-id 4aee09a7-4800-4deb-b44b-96dc2415a455|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554cf:30281909
pythontb:30283811
pythonvspyt943cf:30280190
wslfolderdoc:30282074
vspre833:30267464
pythonptprofiler:30281270
vshan820cf:30276953
pythondataviewer:30283453

```

</details>

**Comment by alexr00** [comment]
@TBBle we use GitHub API to see if the current branch is associated with a PR. Do you still see this issue?

**Comment by TBBle** [comment]
Yup, the problem still replicates, with
```
git clone https://github.com/containerd/containerd.git
cd .\containerd
git remote add tbble git@github.com:TBBle/containerd.git
git remote update --prune
git checkout -b wcow_mount_layers tbble/wcow_mount_layers
```

producing `.git/config`
```
[core]
	repositoryformatversion = 0
	filemode = false
	bare = false
	logallrefupdates = true
	ignorecase = true
[remote "origin"]
	url = https://github.com/containerd/containerd.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "main"]
	remote = origin
	merge = refs/heads/main
[remote "tbble"]
	url = git@github.com:TBBle/containerd.git
	fetch = +refs/heads/*:refs/remotes/tbble/*
[branch "wcow_mount_layers"]
	remote = tbble
	merge = refs/heads/wcow_mount_layers
```

Adding
```
	github-pr-owner-number = "containerd#containerd#4419"
```
to the end causes the branch to appear in Local Pull Request Branches as expected.

I tried enabling `"githubPullRequests.logLevel": "debug",`, but cannot see anything specific in the output that looks like a request for PRs. Specifically, ["Fetch pull requests for branch - enter" from `getPullRequestForBranch`](https://github.com/microsoft/vscode-pull-request-github/blob/v0.32.0/src/github/githubRepository.ts#L352) doesn't appear in the log output.

I do see the following messages,
```
[Debug 1637589398.927s] Review> no matching pull request metadata found for current branch wcow_mount_layers
[Debug 1637589398.927s] Review> no matching pull request metadata found on GitHub for current branch wcow_mount_layers
```
so it must be hitting [this code](https://github.com/microsoft/vscode-pull-request-github/blob/v0.32.0/src/view/reviewManager.ts#L262-L281) and hence _calling_ [`getMatchingPullRequestMetadataFromGitHub`](https://github.com/microsoft/vscode-pull-request-github/blob/v0.32.0/src/github/folderRepositoryManager.ts#L1761-L1791), but one of the conditions in that function fails, so [`getPullRequestForBranch`](https://github.com/microsoft/vscode-pull-request-github/blob/v0.32.0/src/github/githubRepository.ts#L350-L383) is never called.

Since adding the annotation works manually, [`getMatchingPullRequestMetadataForBranch`](https://github.com/microsoft/vscode-pull-request-github/blob/v0.32.0/src/github/folderRepositoryManager.ts#L1749-L1759) works, so `this.repository`, `this.repository.state.HEAD` and `this.repository.state.HEAD.name` are all valid.

So either `this.repository.state.HEAD.upstream` is `false`-ish, `this.gitHubRepositories` is empty, or `repo.remote.remoteName === this.repository.state.HEAD.upstream.remote` never matches.

This is with GitHub Pull Requests and Issues 0.32.0 (Preview).

**Comment by alexr00** [comment]
@TBBle thank you for all the details! Two things:
1. There is a bug, which I am pushing a fix for. 
2. Make sure you add your `tbble` remote to `githubPullRequests.remotes`. PR branch detection will still not work due to the bug, but that's also needed.

**Comment by TBBle** [comment]
Hmm. The documentation might need updating as well, as the README says
> As mentioned above, `githubPullRequests.remotes` is used to specify what remotes the extension should try to fetch pull requests from.

but you're saying I need to add remotes where the _branch_ lives, not the PR? I don't understand why this wouldn't just process any branch's upstream remote by default.

**Comment by roblourens** [comment]
I followed the steps in https://github.com/microsoft/vscode-pull-request-github/issues/2638#issuecomment-975574277 and added tbble to `githubPullRequests.remotes`, but `Local Pull Request Branches` is empty

**Comment by alexr00** [comment]
We don't detect PRs for all your local branches, only the one you have checked out. Once you've checked out a branch that a PR is associated with, then it will show up in `Local Pull RequestBranches`. @roblourens did you check out a branch with a PR associated with it?

**Comment by TBBle** [comment]
I have repeated my reproduction steps in https://github.com/microsoft/vscode-pull-request-github/issues/2638#issuecomment-975574277, and installed the nightly build `GitHub Pull Request Nightly Build
v2021.11.14945` (`github.vscode-pull-request-github-insiders`) which I assume is recent-enough to have the given fix.

Even after adding `tbble` to the list of remotes to fetch pull requests from, it doesn't recognise my currently-checked-out branch as a local pull request.

![image](https://user-images.githubusercontent.com/138397/144606982-a02e9d56-c76e-4714-9cff-7bb3f1048130.png)

![image](https://user-images.githubusercontent.com/138397/144607085-2b15c178-1775-49e5-9c25-cf286a372de5.png)

So I'd like to reopen this ticket, but I don't see how.

----

I did notice that if I didn't have `tbble` (_my_ fork) in `githubPullRequests.remotes`. then the "Created by me" list can't see the pull request that actually lives in the `origin` repo, and which remains present in the 'All Open' list.

So I want to highlight again that
> List of remotes, by name, to fetch pull requests from.
needs to be changed to indicate that it is in reality
> List of remotes, by name, where might contain branches which are the underlying branches of pull requests elsewhere.

The current description is clearly wrong because if I _only_ list `tbble`, i.e. removing `origin` and `upstream`, it's still showing me PRs in `origin`. (There are [_no_ PRs in `tbble`](https://github.com/TBBle/containerd/pulls?q=is%3Apr), that's my fork and has only branches for [PRs to `origin`](https://github.com/containerd/containerd/pulls?q=is%3Apr+author%3ATBBle)).

And maybe remove `upstream` from the defaults, 'cause I can't see why I would check out a fork in which I have branches for PRs into other repos named `upstream`, and it hence sets the wrong expectation for what this setting is for.

If I invert my workflow and clone _my_ fork (as `origin` by default) and then add the upstream repo as `upstream`, then I still only need to list `origin` here, because it seems the extension doesn't actually _need_ a remote for the place where the PRs live, it finds them by... magic? I guess it searches repo from which the named remote is forked? But _not_ the named remote's own repo. But only for the 'Created by me' list.

**Comment by alexr00** [comment]
@TBBle thank you for trying it out! Unfortunately, `v2021.11.14945` is not new enough to have the changes that I made to address this issue. The latest versions of the nightly/pre-release build are only available with VS Code insiders as there were some other changes that required me to bump the required VS Code version.

The good news is that in VS Code insiders this extension now supports the VS Code "pre-release extension" feature. If you are able to try out your scenario in VS Code insiders, you don't need to install the nightly build. Instead, from the Extensions view, you can choose to install the pre-release version of GitHub Pull Requests and Issues.

**Comment by roblourens** [comment]
Yeah, the steps in https://github.com/microsoft/vscode-pull-request-github/issues/2638#issuecomment-975574277 include `git checkout -b wcow_mount_layers tbble/wcow_mount_layers`, and that remote branch has this PR: https://github.com/containerd/containerd/pull/4419. If I check out the remote branch directly `git checkout  tbble/wcow_mount_layers`, same result.

**Comment by roblourens** [comment]
I am probably doing something wrong, but will reopen it since I can't verify it right now.

**Comment by TBBle** [comment]
So new VS Code version, and now I have the "Pre-Release" version `v0.35.2021120909`. Behaviour seems unchanged compared to https://github.com/microsoft/vscode-pull-request-github/issues/2638#issuecomment-985514638' for both "Local Pull Request Branches" and "Created By Me".

If that's not a new-enough build of the extension, what version should I be targeting/waiting for?

**Comment by alexr00** [comment]
@TBBle that is the correct version. The issue has been reopened in response to the fix being insufficient (https://github.com/microsoft/vscode-pull-request-github/issues/2638#issuecomment-985714707)

I am looking into a better fix. Thank you for your patience and willingness to try it out!

**Comment by TBBle** [comment]
Ah, thank you. I misunderstood that comment as merely being unable to reproduce the issue, rather than confirmation that it was not yet fixed.

**Comment by rzhao271** [comment]
@TBBle does the newest pre-release version work for you?
