### ISSUE TITLE
 How can I modify the content in the newIssue.md file to specify that the current issue belongs to an existing Milestone?  

### ISSUE THREAD

**Issue by cool-delete** [microsoft/vscode-pull-request-github#2639]
I have already seen the closed issue #2197
So I think you should have realized this function

- Extension version:0.25.0
- VSCode Version:1.55
- OS:win10 20h2 wsl2 Ubuntu20.04

Steps to Reproduce:

1.
I tried to typed this, but it didn't work
![image](https://user-images.githubusercontent.com/13638610/113590775-a213c500-9665-11eb-8852-00bee6b598f1.png)

2.The Extension  will add a "no Milestone" Milestone and this issue will belongs to  "no Milestone"

**Comment by chenxizhang** [comment]
same suggestion here, add the milestone into the template or let us to customize the template, please

**Comment by tomkivlin** [comment]
I would add my voice to this, please.

**Comment by mitch1009** [comment]
Am interested in this issue. i got caught up in this loop today trying to add an issue to a milestone. i did not find any solution but to go to GitHub web and implement it there. this will be a good feature to ease navigation back and forth

**Comment by mpaulosky** [comment]
I want to add my vote for this feature to be added! It would also be nice to have the ability to include the project that you would like the issue assigned to.

**Comment by JorgePinetta** [comment]
I want to add my vote for this feature to be added!

**Comment by mitch1009** [comment]
> I want to add my vote for this feature to be added!

I strongly vote for this feature

**Comment by AliSajid** [comment]
I ran into this as well. Please add.
