### ISSUE TITLE
Sign in troubles

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-pull-request-github#264]
On Windows, when I click on the tree I see this pop up:

![image](https://user-images.githubusercontent.com/2193314/44541758-ccd0cb00-a6bf-11e8-8435-d6bc8dbd4159.png)

This doesn't appear to work at all when I put in my credentials. I tried multiple times before discovering that the _notification_ send me to the oauth page. When I tried to use that I hit this after clicking authorize:

![image](https://user-images.githubusercontent.com/2193314/44541840-0d304900-a6c0-11e8-87b8-7ea1574c62d3.png)

Oauth ended up working after reloading the window and trying again.

**Comment by auchenberg** [comment]
Ping @shana  ;)

**Comment by shana** [comment]
Yup, poking the system git for credentials is causing this. I think I'm going to take out that check/do it differently so it doesn't pop up the GCM (which is popping up this dialog). GCM can't get tokens that work, so this is definitely annoying.

**Comment by shana** [comment]
This is fixed in https://github.com/Microsoft/vscode-pull-request-github/commit/90d078a1aa16abd32fdba36e0ec7792cdd9ddf27
