### ISSUE TITLE
Visuals on the PR overview page

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-pull-request-github#2648]
Pls see

![image](https://user-images.githubusercontent.com/4674940/114207880-b380f980-9911-11eb-9b78-7e9292488e47.png)

A) propose to increase the vertical space between the button row and the title/date of the PR
B) While "Reviewers" is a title "None yet" is a value. Proposal to visually show that difference by color, font, or borders
C) Missing alignment
D) Propose to increate the vertical space between the check list and the button; increase the horizontal space between "using method" and the drop down

**Comment by alexr00** [comment]
A) The buttons are currently intended to be aligned with the title, however they are currently a little too low. I've moved them to line up better with the title. If instead you were proposing that we move the buttons up above the title (still right aligned), then I will try that out.
B) Has already been addressed with bold and italics.
C) Looks like this one has already been addressed too.
D) Increased the vertical space by 4px. Fixed the missing space before the drop down.

![image](https://user-images.githubusercontent.com/38270282/123115439-660c2700-d440-11eb-9275-65a360049311.png)
