### ISSUE TITLE
Double spaces on pull request header

### ISSUE THREAD

**Issue by MicaelJarniac** [microsoft/vscode-pull-request-github#2651]
Issue Type: <b>Bug</b>

Open a pull request from the extension, then look at its header and notice that there are double spaces in several places.

![Screenshot](https://i.imgur.com/E0Bd8PN.png)
```
MicaelJarniac wants to merge changes  into  example:main from  example:develop
```
```
MicaelJarniac wants to merge changes [double spaces here] into [double spaces here] example:main from [double spaces here] example:develop
```

Extension version: 0.25.1
VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 2200G with Radeon Vega Graphics     (4 x 3493)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.95GB (0.60GB free)|
|Process Argv|--folder-uri vscode-remote://wsl%2Bubuntu/home/micael/projects --crash-reporter-id c1c5a056-2d00-4ffe-bd74-762397c34297|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 3 2200G with Radeon Vega Graphics (4 x 3493)|
|Memory (System)|6.16GB (3.37GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 3 2200G with Radeon Vega Graphics (4 x 3493)|
|Memory (System)|6.16GB (3.37GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554cf:30281909
pythontb:30283811
wslfolderdoc:30282074
vspre833:30267464
pythonptprofiler:30281270
vscnewfilehidden:30288034
vshan820cf:30276953
vscorecescf:30285484
pythondataviewer:30285071
vscus158:30286553

```

</details>

**Comment by Donna3344** [comment]
No wonder

**Comment by rzhao271** [comment]
There's still a double space between "changes" and "into".
