### ISSUE TITLE
Disable auto-opening when starting up

### ISSUE THREAD

**Issue by fungiboletus** [microsoft/vscode-pull-request-github#2654]
Whenever I open VS Code, vscode-pull-request-github will open itself on the side panel and open the first file diff. I close it every time. How can I stop vscode-pull-request-github to open itself when I start VS Code, without removing the extension of course ?

**Comment by RMacfarlane** [comment]
Is this when using GitHub Codespaces? If not, then this behavior should have already been removed in the latest version of the extension: https://github.com/microsoft/vscode-pull-request-github/issues/2295

**Comment by fungiboletus** [comment]
Sorry for the late answer. Yes it's in GitHub Codespaces.

I can see [https://github.com/microsoft/vscode-pull-request-github/pull/2601/files](in the diff) that Github Codespaces is a specific case. I guess a lot of users of Github Codespaces will do one pull request and move on, but it would be nice if it's possible to disable this behaviour. I'm not familiar with VsCode extension development so I can't do a good pull request to have the option. Thanks for your work 🙂

**Comment by alexr00** [comment]
Not auto opening is now the default in codespaces.
