### ISSUE TITLE
Pull Request tab not loading

### ISSUE THREAD

**Issue by vedantkaul0809** [microsoft/vscode-pull-request-github#2659]
Issue Type: <b>Bug</b>

The pull request tab is not loading. It's just showing 'No remotes match the current setting and 'configure remotes' option under it.  Whereas it should show all sub tabs as 'local pull request branches','waiting for my review','assigned to me ' etc. Can you please help to resolve the issue.

Extension version: 0.25.1
VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz (4 x 1995)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.42GB (1.19GB free)|
|Process Argv|--crash-reporter-id 30ec22f3-0372-40e5-8e5f-25936cb0fc17|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554:30281908
pythontb:30283811
openwsldoc:30282072
vspre833:30267464
pythonptprofiler:30281270
vshan820:30276952
pythondataviewer:30285071
vscus158cf:30286554

```

</details>

**Comment by vedantkaul0809** [comment]
![image](https://user-images.githubusercontent.com/79090043/115124092-0297f000-9fde-11eb-8768-b2a1e249cbff.png)
Here is the screenshot attached.

**Comment by RMacfarlane** [comment]
What's the output in the terminal when you run `git remote -v`?

**Comment by Donna3344** [comment]
Amazing
