### ISSUE TITLE
Not Permitted to push to github through vscode, tried pull request same

### ISSUE THREAD

**Issue by LeoTheUXBro** [microsoft/vscode-pull-request-github#2660]
![image](https://user-images.githubusercontent.com/47278525/115140338-ae692c00-a02e-11eb-8f34-e33d1bd380b5.png)

I haven't been able to push

**Comment by RMacfarlane** [comment]
Hey @LeoTheUXBro, this may be expected - have you been added as a contributor to the "DrakeinRaven/Binance_MC_Gr26" repository? If not, you won't have permissions to make changes to it directly and will instead have to make a fork of the repository: https://docs.github.com/en/github/getting-started-with-github/fork-a-repo

**Comment by LeoTheUXBro** [comment]
Hi @RMacfarlane, I am one of the contributors, but I guess the issue developed due to the change of my github username. If the repo owner re-adds me, will that solve the problem?
