### ISSUE TITLE
I am stuck in a PR that I am not on

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-pull-request-github#2662]
My setup:
- multi root workspace
- first folder: vscode
- second folder: vscode-docs (checked out to `vnext`)

![image](https://user-images.githubusercontent.com/900690/115266823-d2b12f80-a138-11eb-8abf-c783adef7894.png)

From https://github.com/microsoft/vscode-docs/pull/4423

**Comment by ryanaklein** [comment]
Similar experience for me. 
![Screen Shot 2021-04-21 at 8 57 38 AM](https://user-images.githubusercontent.com/3856027/115557626-e1562e80-a27f-11eb-9d88-da87ab9b0902.png)

In the below screen shot, the pr that I'm "stuck" on is closed. It's merging from one protected branch into another.
![Screen Shot 2021-04-21 at 8 58 46 AM](https://user-images.githubusercontent.com/3856027/115557628-e1eec500-a27f-11eb-8a31-12149789f99c.png)

**Comment by AlCalzone** [comment]
This might be the same I was experiencing here: https://github.com/microsoft/vscode-pull-request-github/issues/2356

**Comment by alexr00** [comment]
Because the branch `vnext` is associated with a pull request we show the pull request view. We now have https://github.com/microsoft/vscode-pull-request-github/issues/3009, which will not use the associated PR if the PR is closed (not merged, just closed).
