### ISSUE TITLE
Cannot fetch Pull Requests after downloading extension

### ISSUE THREAD

**Issue by jdgreenberger** [microsoft/vscode-pull-request-github#2667]
I just downloaded the extension and am unable to view the extension in the visibility bar or in the source control section of VSCode.  I'm getting the log messages:
```
[Info] Found GitHub remote
[Info] Review> no matching pull request metadata found for current branch master
[Info] Review> no matching pull request metadata found on GitHub for current branch master
```
I've searched through all the issues and saw a similar [potentially related](https://github.com/Microsoft/vscode-pull-request-github/issues/1014) message but it suggests using a different remote which does not seem to be my problem given that one of the logs said "Found Github remote". I've seen another issue about workspaces with multiple roots but I'm not sure whether that applies to me. I've got a single repository with multiple folders opened at the root.

Specs:
- Extension version: 0.25.1
- VSCode Version: 1.55.2
- OS: Mac OSX 11.2.1

**Comment by RMacfarlane** [comment]
Hey @jdgreenberger, you mean that you don't see the GitHub icon on the activity bar at all? Or that pull requests aren't showing up in the tree?

**Comment by jdgreenberger** [comment]
Neither one seems to be showing up for me. 
![Screen Shot 2021-04-21 at 5 12 54 PM](https://user-images.githubusercontent.com/2753924/115627539-d1ad0900-a2c4-11eb-8f7c-32ee9bc976e4.png)
![Screen Shot 2021-04-21 at 5 12 48 PM](https://user-images.githubusercontent.com/2753924/115627555-d8d41700-a2c4-11eb-81ba-c094a37dedf0.png)

**Comment by RMacfarlane** [comment]
@jdgreenberger what does your activity bar look like?
<img width="57" alt="Screen Shot 2021-04-22 at 3 03 00 PM" src="https://user-images.githubusercontent.com/3672607/115790635-df719580-a37b-11eb-9af2-ae8cadd8eed0.png">

**Comment by jdgreenberger** [comment]
Oh wow, I didn't realize it would be under the Github icon. It's showing up now, sorry about the confusion. It may be helpful to add that screenshot to the Readme to guide simpletons like me 😃
