### ISSUE TITLE
Use status bar entry for creating pull request

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-pull-request-github#2675]
As is, any time I push a new branch I get a notification asking me if I want to make a PR, this is sometimes helpful but sometimes annoying. I can choose to not see it again, but then I don't get it in the cases where I actually do want to make a PR. 

I propose using the status bar to show a "Create Pull Request" message, in place of where the "Pull request #11111" message is now for branches that *do* have an associated PR:
![image](https://user-images.githubusercontent.com/8586769/115928034-52d9dc80-a43a-11eb-9b99-86828d8f4505.png)

**Comment by alexr00** [comment]
We have several other places we show a "create" button: in the PR view, in the SCM view, and in the command palette. Since the buttons are more contextual that the status bar, they seem like a better place.
