### ISSUE TITLE
Linked pull requests

### ISSUE THREAD

**Issue by KristofMerey** [microsoft/vscode-pull-request-github#2676]
If I create a pull request working on an issue branch, I expect that the new pull request is automatically linked to the issue in its section "Linked pull requests".

**Comment by alexr00** [comment]
The GitHub API doesn't have a way to do this directly. The only way is to have a "Fixes #XYZ" type string in the PR description.

**Comment by alexr00** [comment]
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/5824
