### ISSUE TITLE
Clicking on the icon right on the PR title does nothing

### ISSUE THREAD

**Issue by jonathanvila** [microsoft/vscode-pull-request-github#2677]
- Extension version: 0.25.1
- VSCode Version: 1.55.2
- OS: Fedora 33

Steps to Reproduce:

1. click on icon for Pull Requests
2. click on the icon right on the pr title
3. nothing happens
4. expected : show the PR description

**Comment by alexr00** [comment]
> click on the icon right on the pr title

Can you share a screenshot of this so I can better understand what you're clicking on?
