### ISSUE TITLE
Show no PRs ( in any query ) for a given project, but there are

### ISSUE THREAD

**Issue by jonathanvila** [microsoft/vscode-pull-request-github#2678]
- Extension version: 0.25.1
- VSCode Version: 1.55.2
- OS: Fedora 33

Steps to Reproduce:

1.Clcik on source control
2. go to github pull requests
3. on the list of projects drill down on the first one
4. no categoy shows a pull request, even clicking on the refresh icon 
5. it shows pull requests for other projects

Seems like it is showing PRs done against my fork, but not for the upstream remote ( which is the one I'm interested on )

**Comment by RMacfarlane** [comment]
Hey @jonathanvila, can you check the value of the `githubPullRequests.remotes` setting and share what your remotes are? (`git remote -v`)

**Comment by jonathanvila** [comment]
Hi Rachel

Yes, I do that often when I see that error .
upstream , origin

**Comment by alexr00** [comment]
@jonathanvila are the values of `githubPullRequests.remotes` and `git remote -v` both the same (upstream and origin)?
