### ISSUE TITLE
Can't resolve conversation from description page

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-pull-request-github#2685]
Testing https://github.com/microsoft/vscode/issues/122243

Can resolve through gh.com

![image](https://user-images.githubusercontent.com/323878/116324583-41b00900-a775-11eb-9fec-a5c5425f5568.png)

No resolve button:

![image](https://user-images.githubusercontent.com/323878/116324564-39f06480-a775-11eb-85a1-fed1fd969883.png)

**Comment by ednl** [comment]
Yes, please! Adding the ability to resolve conversations would be very helpful. Thanks.

**Comment by ednl** [comment]
(Also, don't bother actually going to that url Rob mentioned, it's a parked domain in China.)

**Comment by roblourens** [comment]
To be clear, you can resolve conversations, just not on the description page. And I mean github.com...

**Comment by LyleGuay** [comment]
I would like to see this feature as well!

Currently, once a conversation has the label "Outdated", you can't "Resolve Conversation" from within VSCode. You need to switch back to the Github.com PR page to resolve the conversation.

**Comment by alexr00** [comment]
This has since been added.
