### ISSUE TITLE
Inconsistent comment/conversation state

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-pull-request-github#2687]
Testing https://github.com/microsoft/vscode/issues/122243

1) I created a PR through VS Code
2) Once the PR was in review mode I opened one file and added a comment
3) I replied to the comment
4) I pressed start review
5) I replied again

-> There are 3 comments on the PR as you can see in the overview page
-> Only the last comment is show in the editor and the comments panel

![image](https://user-images.githubusercontent.com/4674940/116432272-59cb6b00-a7fd-11eb-93db-05433b61aaaa.png)

**Comment by kieferrm** [comment]
I exited review mode by switching the branch to `main` and then back to `kieferrm/pr1`.

The comments now show up correctly, but I also got the webview disposed error notification.

![image](https://user-images.githubusercontent.com/4674940/116433094-086fab80-a7fe-11eb-9ed3-fddfc8de55bf.png)

**Comment by kieferrm** [comment]
Also see https://github.com/microsoft/vscode-pull-request-github/issues/2689

**Comment by RMacfarlane** [comment]
Starting a review in reply to something should not create a new thread on the same line, but a reply

https://github.com/microsoft/vscode-pull-request-github/pull/2700

**Comment by rzhao271** [comment]
It says it's pending so I'm unable to reply to the comment.

![pend](https://user-images.githubusercontent.com/7199958/116758628-5387eb00-a9c5-11eb-9cf3-7f833291705a.PNG)

**Comment by RMacfarlane** [comment]
To verify:

1. Open a pull request and use the "Add comment" button to create a comment
2. Then, reply to that comment using the "Start Review" button

The two comments should appear in the same thread, they should not be independently added to the same line. The "Pending" label you see indicates that the review hasn't yet been submitted, so is expected
