### ISSUE TITLE
Losing presentation of comments after resolving a conversation

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-pull-request-github#2689]
Testing https://github.com/microsoft/vscode/issues/122243

I had the following conversation.

![image](https://user-images.githubusercontent.com/4674940/116433949-d4e15100-a7fe-11eb-956c-f9dba4da04af.png)

I added yet a comment and resolved the conversation. At this moment the resolved conversation disappeared.  Clicking the black diamond toggled through the conversations. Closing the editor and reopening it I got back into a normal state. 

I speculate that this is because I have two conversations on the same line.

![image](https://user-images.githubusercontent.com/4674940/116434802-96986180-a7ff-11eb-93b7-fc5dbd1b54fa.png)

**Comment by RMacfarlane** [comment]
Upstream: https://github.com/microsoft/vscode/issues/77155

**Comment by alexr00** [comment]
Upstream issue is fixed.
