### ISSUE TITLE
The comments panel should indicate if a conversation is resolved

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-pull-request-github#2691]
Testing https://github.com/microsoft/vscode/issues/122243

Currently I don't see if a conversation has been resolved:

![image](https://user-images.githubusercontent.com/4674940/116435300-10304f80-a800-11eb-8843-f7369c629924.png)

We should annotate the conversation and collapse it by default. We should also think about having a filter on the comments panel.

**Comment by alexr00** [comment]
This has been done.
