### ISSUE TITLE
Overview page shows the same comment in two conversations at the same time and confuses the resolved state

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-pull-request-github#2693]
Testing https://github.com/microsoft/vscode/issues/122243

The 'will change back' comment only belongs into the first conversation which has been resolved.

The second conversation was not resolved but the show/hide button shows up. I'm guessing this is because it "contains" the also the 'will change back' comment.

![image](https://user-images.githubusercontent.com/4674940/116436358-30acd980-a801-11eb-8d7e-1c9e0b1b2b47.png)

**Comment by kieferrm** [comment]
The overview page on GH also seems to be confused. The files page shows almost the right info: https://github.com/kieferrm/gatsby-1/pull/6/files. Only the pending label on 'will change back' is confusing.

**Comment by alexr00** [comment]
Closing as part of issue clean up as there haven't been more reports of this.
