### ISSUE TITLE
"Greyed out text" in the input box

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-pull-request-github#2695]
Testing microsoft/vscode#122243

The text in the input box for the PR title looks like it's greyed out. This mislead me for example to assume that the pre-filled in title is a placeholder and not an actual string. 

![image](https://user-images.githubusercontent.com/4674940/116430642-e1b07580-a7fb-11eb-8095-432c27a1f2b5.png)

**Comment by RMacfarlane** [comment]
Interestingly, these inputs are already using `var(--vscode-input-foreground)` as the color which matches other inputs in VS Code. The `vscode-dropdown-foreground` color which the selects are using appears to be a bit different and higher contrast. @misolori do you think we should align these colors?

**Comment by misolori** [comment]
I think this just varies by theme, for example the GH Light theme shows both text as the same colors, though it looks like the placeholder text is not using any color token?

![image](https://user-images.githubusercontent.com/35271042/116471908-10dddb80-a82a-11eb-8ac5-36815e2c5b8d.png)

![image](https://user-images.githubusercontent.com/35271042/116472005-2ce17d00-a82a-11eb-8494-d48768c6a876.png)

**Comment by RMacfarlane** [comment]
Updated the placeholder text color to use the vscode theme token for it
