### ISSUE TITLE
Make this extension universal

### ISSUE THREAD

**Issue by jens1o** [Microsoft/vscode-pull-request-github#270]
I don't want to bind me to a monopol, so please make this working with other providers, too. At least make it generic enough for adding multiply providers.

**Comment by auchenberg** [comment]
@jens1o This extension includes the GitHub specific integration for Pull Requests in VS Code, and is using a set of new generic VS Code extension APIs to enable commenting, etc, that can be used by any provider. 

We are planning on releasing multiple of these providers, and this Github specific provider is just one.

**Comment by jens1o** [comment]
> We are planning on releasing multiple of these providers

Where is the issue for that to subscribe to it?
