### ISSUE TITLE
Cannot reply to temporary 

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-pull-request-github#2702]
1. Make a comment on a PR
2. Create a separate comment and hit "start a review"
3. Get an error 

![](https://memes.peet.io/img/21-04-edce6e05-cccb-4dbc-a5c2-0e98359a6619.png)

Errors in console:

![](https://memes.peet.io/img/21-04-c1749496-c11c-4afb-bb28-e31962dade35.png)

**Comment by RMacfarlane** [comment]
Ah, we immediately create a "temporary comment" under the assumption that the create will succeed so that the UI updates quickly and then replace it with the real comment. We should queue additional actions when something is still in progress

**Comment by alexr00** [comment]
@connor4312 I'm not able to repro this. Does it happen every time for you?

**Comment by connor4312** [comment]
I no longer repro
