### ISSUE TITLE
Hide 'Open Permalink on GitHub' command if the workspace is a RemoteHub

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode-pull-request-github#2703]
![image](https://user-images.githubusercontent.com/2644648/116734726-77860500-a9a2-11eb-8a9a-8878af60636f.png)

Version: 1.56.0-insider
Commit: 6449b6b7253b5808e2278903c82da8d59a230383
Date: 2021-04-30T09:28:57.754Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin x64 20.4.0

Steps to Reproduce:

1. Select some code in a RemoteHub workspace
2. Run the `Open Permalink on GitHub` command

@eamodio mentioned we should just hide this command and he will provide a similar command in RemoteHub

**Comment by alexr00** [comment]
@eamodio instead of providing a similar command in RemoteHub, let's see if we can add this command in a place where it is always available.

**Comment by alexr00** [comment]
The command works now. Will still investigate adding to a built in extension.
