### ISSUE TITLE
Extension interferes with editing of upstream remote

### ISSUE THREAD

**Issue by burkeholland** [microsoft/vscode-pull-request-github#2705]
- Extension version: v2021.4.42844
- VSCode Version: 1.55
- OS: Linux x64 5.4.72-microsoft-standard-WSL2

Steps to Reproduce:

1. Add a fork origin
2. Check that the upstream is added automatically
3. Remove the upstream from the terminal
4. Check that it is added back almost immediately

https://user-images.githubusercontent.com/686963/116754484-6c48ce80-a9ce-11eb-982a-8e5bb60bc481.mp4

Maybe it could only change the upstream when you try to create the PR. As is, it seems to have a listener that prevents manual changing of the upstream.

**Comment by alexr00** [comment]
@burkeholland can you try changing the setting `githubPullRequests.remotes` to not include `upstream`? I think that's why we're adding it back, because we need that remote (even when you are not creating a PR) if it's listed there.
