### ISSUE TITLE
Cannot find the commits in an open PR to a private repo

### ISSUE THREAD

**Issue by naiteeks** [microsoft/vscode-pull-request-github#2716]
- Extension version:
- VSCode Version: 1.56.0
- OS: Windows

Steps to Reproduce:

1. Goto the extension
2. Click on the All Open option to open all the open PRs
3. Click on the expand/collapse button
4. All commits should show up, but its empty
![image](https://user-images.githubusercontent.com/42254991/117215804-9d9d1200-adb3-11eb-8c04-18f0077881fd.png)

**Comment by RMacfarlane** [comment]
Currently the commits do not show up in the tree until you have checked out the pull request. There's an existing feature request to add the commits here as well (https://github.com/microsoft/vscode-pull-request-github/issues/2201), so I'm going to close this as a duplicate. Thanks!
