### ISSUE TITLE
Option to hide the Create Pull Request button

### ISSUE THREAD

**Issue by deepnight** [microsoft/vscode-pull-request-github#2717]
Is it possible to add a small option to hide the "*Create Pull Request*" button in the SCM panel please?

Many extensions tend to add stuff there and it becomes *really* cluttered (see screen), hiding important informations.

![image](https://user-images.githubusercontent.com/1671695/117263830-f4a5f400-ae52-11eb-8fae-0ba448bbc1b8.png)

**Comment by alexr00** [comment]
I think ideally this would be solved at the VS Code level. That way, uses could choose which buttons from which extension get shown for all extensions, not just this one.
