### ISSUE TITLE
Auto Refresh PR when in Review Mode

### ISSUE THREAD

**Issue by jkworth** [microsoft/vscode-pull-request-github#2719]
Would be nice to have an option when in review mode of a PR that I don't have to keep hitting refresh. 

A configureable value in in the settings would be good so that I can tell it how often to refresh.

Note: To limit the updates this might be something that is auto refreshing only with the Pull Request tab is loaded. It does not need to be the active tab.

**Comment by alexr00** [comment]
We refresh every 2 minutes.
