### ISSUE TITLE
Support virtual workspaces

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode-pull-request-github#2722]
👋 Hi there, Martin here, from the VS Code team.

Recently we've announced the [Remote Repository feature](https://code.visualstudio.com/updates/v1_56#_remote-repositories-remotehub) that lets you browse and edit files and folders directly on GitHub.

`Open Remote Repository...` opens VSCode on a folder or workspace located on a virtual file system. We call this a **virtual workspace**. We observed that not all extension support this well, either because they can not, or they haven't thought about it.

It would be fantastic if you could test whether your extension can handle virtual workspaces:

Check out the [Virtual Workspaces Extension Author Guide](https://github.com/microsoft/vscode/wiki/Virtual-Workspaces) on how to do that.

When done, set the new `virtualWorkspaces` capability in your 'package.json'.

```
{
  "capabilities": {
    "virtualWorkspaces": true | false
  }
}
```

- Use `"virtualWorkspaces": true` if your extension is prepared for virtual workspaces
- Use `"virtualWorkspaces": false` if your extension should be disabled when a virtual workspace is opened

For questions and comments please use the [Virtual Workspaces Tracking Issue](https://github.com/microsoft/vscode/issues/123115).

Thanks for the support and the great work! ❤️

**Comment by alexr00** [comment]
Not everything is supported yet, so there's no need to test exhaustively since I already know some things are not yet working, but you should be able to:
- View and comment on a not-checked out PR
- View and comment on a checked out PR
- Start working on an issue from the issues view.

**Comment by connor4312** [comment]
Unable to verify due to https://github.com/microsoft/vscode-remotehub/issues/40, someone else may have better luck

**Comment by TylerLeonhardt** [comment]
My understanding is that you need the virtual workspace of the repo opened. So have `main` branch opened of `Microsoft/vscode`.

Then it's like:
* View and comment on a not-checked out PR - totally using the PR view
* View and comment on a checked out PR - using the PR view and looking through the actual source
* Start working on an issue from the issues view - make sure checking out an issue from a remote workspace works

**Comment by TylerLeonhardt** [comment]
@alexr00 the comments don't appear in the file when I check out a PR:
![image](https://user-images.githubusercontent.com/2644648/124033716-28168200-d9af-11eb-92f7-f96d5f66ae6c.png)

On the left is the editor from the GHPR extension. On the right is the normal Remote Repositories editor

**Comment by TylerLeonhardt** [comment]
The other scenarios seem to work well.

**Comment by alexr00** [comment]
@TylerLeonhardt thanks for testing this! I'm not able to repro what you're seeing. Are you using the nightly/insiders version of GHPRI?

**Comment by TylerLeonhardt** [comment]
unfortunately, this still repros for me
![image](https://user-images.githubusercontent.com/2644648/124162668-901ea400-da53-11eb-8ada-1d8d2180496f.png)

![image](https://user-images.githubusercontent.com/2644648/124162735-a62c6480-da53-11eb-8cd8-3abfea4b2844.png)
![image](https://user-images.githubusercontent.com/2644648/124162808-be03e880-da53-11eb-87d2-581b29fb3937.png)

**Comment by stuartleeks** [comment]
Comments are showing inline in the source for me with Remote-Repositories and the PR checked out (Nightly build v2021.7.39424):

![image](https://user-images.githubusercontent.com/1824461/127342945-1155d6ce-458a-40cb-86a9-b039d7ddc417.png)

Successfully viewed and commented on both checked out and non-checked out PRs.
Also checked out an issue from the issues view.
