### ISSUE TITLE
GitHub not loading

### ISSUE THREAD

**Issue by NathanBrianRoberts** [microsoft/vscode-pull-request-github#2724]
- Extension version: 0.26.0
- VSCode Version: 1.56.0
- OS: 10 Dev (Build 21376.1)

Steps to Reproduce:

1. Install GitHub
2.Wait for the thing to load

The extension will not load, to finish setting up the extension and connecting with my GitHub respirometry's . It just sits there saying it is loading.

**Comment by RMacfarlane** [comment]
Closing as a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/2572
