### ISSUE TITLE
Error when trying to check out a pr from viewlet

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-pull-request-github#2727]
After clicking the checkout action, I get this error:
![image](https://user-images.githubusercontent.com/8586769/117904418-30432280-b286-11eb-9ac5-5cb4f231635a.png)

**Comment by alexr00** [comment]
@JacksonKearl just to make sure I understand:
1. You tried to run the "checkout PR" action.
2. The PR branch was not checked out and you got this error.

In that case, yes we should be able to have a better message.

**Comment by JacksonKearl** [comment]
Yes, I believe the source if the error was that I had a file in "conflict" state still in my working directory from when I was doing some previous git stuff.

**Comment by alexr00** [comment]
Fixed by https://github.com/microsoft/vscode-pull-request-github/commit/63eb31ce9f5952c924848a71df23174ae8e597d0
