### ISSUE TITLE
Clicking Extension Icon Gives Create PR Screen Instead PRs and Issues

### ISSUE THREAD

**Issue by conradwt** [microsoft/vscode-pull-request-github#2733]
When clicking the icon, I see a create PR and it's unclear as to how to get listing for the following

v PULL REQUESTS
   ...
   ...
   ...

v ISSUES
  ...
  ...

and so on.  The extension icon puts the user in an unclear state.

- Extension version: 0.26.0
- VSCode Version: 1.57.0-insider
- OS: macOS 11.3.1

Steps to Reproduce:

1.  Click the extension icon
2. Unable to view/list PULL REQUESTS and ISSUES

**Comment by alexr00** [comment]
There are two activity bar icons associated with this extension:
![image](https://user-images.githubusercontent.com/38270282/118488493-12f5d480-b71c-11eb-8aa1-fc9a30a5040b.png)

The top one is the "create PR" icon, and the bottom is the PRs and Issues tree views.

**Comment by conradwt** [comment]
@alexr00 Great and thanks for the clarification.
