### ISSUE TITLE
Go to review should not be on the same level as add comment

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-pull-request-github#2736]
![image](https://user-images.githubusercontent.com/900690/118677858-dea61500-b7fc-11eb-8ed2-58c02454193b.png)

I find the 2 buttons do not really have anything in common. I clicked the "Go to review" button and lost my comment I typed.

**Comment by alexr00** [comment]
A common user flow is to leave some comments then open the review description and approve/request-changes. This button is there to facilitate that flow, especially since we've found that some users have trouble finding their way to the review description.
