### ISSUE TITLE
Extension does not respect remote link type for upstream

### ISSUE THREAD

**Issue by lychichem** [microsoft/vscode-pull-request-github#2740]
- Extension version:0.26.0
- VSCode Version:1.56.2 x64 system install
- OS:10.0.19043.1021 x64 pro zh-CN

Steps to Reproduce:

1.Clone https://github.com/lychichem/winget-pkgs, which is forked from microsoft/winget-pkgs, by using ssh url, with this extension in VSCode
2.The upstream automatically added uses https but not ssh

This may be a small issue for developers outside mainland China, but it's a severe issue for developers in mainland China, as Github/Gitlab is not so robust under https (They suffer from TLS RST attack, especially when it is near June 4th). So developers in mainland China usually cannot use git with an https remote.

**Comment by burkeholland** [comment]
+ @alexr00 

The only catch here is that a person might have multiple remotes with differing protocols. In which case we have no idea what they want for their upstream. This PR looks at the first one and uses whatever protocol that one is.

**Comment by alexr00** [comment]
Looking at the first one is a better default then we currently have.
