### ISSUE TITLE
Disable decorations when in review mode

### ISSUE THREAD

**Issue by mil-ad** [microsoft/vscode-pull-request-github#2743]
Is it possible to disable decorations when I have an active PR? Sometimes I want to carry on working on my PR branch while it's being reviewed and there far too many decorations from this extension in the editor view.

**Comment by alexr00** [comment]
I think what you want is to disable "review mode" even when on the PR branch. Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/408
