### ISSUE TITLE
Errors when working in .wiki repos

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-pull-request-github#2749]
See this a lot when working in https://github.com/microsoft/vscode.wiki.git
![image](https://user-images.githubusercontent.com/8586769/119598389-b76cbc00-bd97-11eb-8aac-df0526e21bef.png)

**Comment by alexr00** [comment]
@JacksonKearl how did you clone this repo?

**Comment by JacksonKearl** [comment]
Just `git clone git@github.com:microsoft/vscode.wiki.git`

**Comment by alexr00** [comment]
.wiki repos don't support PRs, so I've just disabled them. GHPRI will not show anything for them, and you will no longer get these errors.
