### ISSUE TITLE
Check out vs checkout

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-pull-request-github#275]
Right now "check out" is used throughout but I think we should be using "checkout" as that's the underlying git operation used and it's referred to as "the checkout operation" in the docs https://git-scm.com/docs/git-checkout

![image](https://user-images.githubusercontent.com/2193314/44666449-4e30a200-a9cd-11e8-912e-7506c6be8b1d.png)

![image](https://user-images.githubusercontent.com/2193314/44666455-52f55600-a9cd-11e8-88f0-c54fd2f323ea.png)

**Comment by rebornix** [comment]
Interesting, https://github.com/Microsoft/vscode-pull-request-github/issues/177 . `checkout` is used when we are referring to the operation/command while we use `Check Out` as a verb.

cc @shana

**Comment by auchenberg** [comment]
Could we name the button `Checkout Pull Request` or `Checkout PR` to it use a "command" and not a verb?

**Comment by Tyriar** [comment]
From https://github.com/Microsoft/vscode-pull-request-github/issues/177#issuecomment-412611563

> So on GitHub we use "check out" as a verb, and only use "checkout" when talking about the command or if talking about a specific feature with that name (like if we named a feature "the checkout button"). I don't know if the VS docs team has different guidelines for that usage tbh.

@shana where on GH is "check out" used? This is all I could find:

<img width="370" alt="screen shot 2018-08-28 at 10 48 49 am" src="https://user-images.githubusercontent.com/2193314/44740693-f9b22300-aaaf-11e8-8596-a2a445d00140.png">

GH desktop, https://desktop.github.com/:

<img width="860" alt="screen shot 2018-08-28 at 10 50 40 am" src="https://user-images.githubusercontent.com/2193314/44740822-3b42ce00-aab0-11e8-99d4-27d017efd835.png">

https://help.github.com/articles/checking-out-pull-requests-locally/

<img width="557" alt="screen shot 2018-08-28 at 10 53 12 am" src="https://user-images.githubusercontent.com/2193314/44740953-9674c080-aab0-11e8-9c5d-1ff83a404d67.png">

**Comment by auchenberg** [comment]
We have decided to use "checkout". Fixed in https://github.com/Microsoft/vscode-pull-request-github/commit/fc5e2ce048698d26d6aa28d93f0f90bdb460c6b9 + https://github.com/Microsoft/vscode-pull-request-github/commit/79e19a1e598fbc5680351c2a618b85617267961f

**Comment by auchenberg** [comment]
@roblourens What's the specific concern and proposal? We have updated the wording, so it looks like:

<img width="278" alt="screen shot 2018-08-30 at 11 17 29 pm" src="https://user-images.githubusercontent.com/173559/44895828-ecad5380-acaa-11e8-8563-f05161d6d210.png">

<img width="421" alt="screen shot 2018-08-30 at 11 16 37 pm" src="https://user-images.githubusercontent.com/173559/44895831-f1720780-acaa-11e8-84ed-3330e7664154.png">

<img width="296" alt="screen shot 2018-08-30 at 11 16 28 pm" src="https://user-images.githubusercontent.com/173559/44895832-f46cf800-acaa-11e8-9027-bb6763b97c84.png">

**Comment by Tyriar** [comment]
The screenshots look right to me.

**Comment by roblourens** [comment]
My proposal is still to use "Check out" instead of "Checkout"

**Comment by auchenberg** [comment]
Let's have a vote:`Checkout` vs `check out` vote with reactions.  Closing today day 5pm PST.
