### ISSUE TITLE
Only one permalink creation command available

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-pull-request-github#2750]
Seen on v0.26.0. Also on insiders v2021.5.35103

I am missing the other usual Permalink creation commands, now I can only copy the markdown formatted link:

![image](https://user-images.githubusercontent.com/22350/119625992-9f109780-bdbf-11eb-901d-d7390884da4e.png)

**Comment by alexr00** [comment]
This is going to have the same root cause as https://github.com/microsoft/vscode-pull-request-github/issues/2751, since we (wrongly) require sign in for that command.

**Comment by Tyriar** [comment]
To fix the sign in requirement: https://github.com/microsoft/vscode-pull-request-github/issues/2761
