### ISSUE TITLE
Always asks for auth

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-pull-request-github#2751]
Seen on v0.26.0. Also on insiders v2021.5.35103

This notification never goes away. When I click it, I follow the usual GH auth flow successfully. But at the end, the notification just stays.

![image](https://user-images.githubusercontent.com/22350/119626178-c8c9be80-bdbf-11eb-86b6-dbcc18601169.png)

**Comment by TylerLeonhardt** [comment]
I was suspicious of https://github.com/microsoft/vscode/pull/124640

But I reverted my change and the issue still exists so it's not that.

**Comment by TylerLeonhardt** [comment]
Interestingly, then menu item puts you into this loop that @joaomoreno describes, but going through the modal flow (using the `Sign in` button in the `GitHub: Login` view, will get you to a logged in state...

but then reloading the window puts you back in the logged out state.

**Comment by JustinGrote** [comment]
@TylerLeonhardt FYI certain actions also seem broken. For instance, creating a pull request:

https://user-images.githubusercontent.com/15258962/119751207-949dde80-be4f-11eb-88ac-972a3d46a453.mp4

**Comment by rami3l** [comment]
@TylerLeonhardt I can confirm this bug on my machine. Using the command palette gives a correct login (using the popup does not), but the login state is lost when I quit and restart VSCode.

**Comment by alexr00** [comment]
Here's what I'm seeing:
1. User tries to sign in from the Accounts activity bar icon and completes the sign in flow.
2. GHPRI's `vscode.authentication.onDidChangeSessions` handler gets called.
3. GHPRI calls `vscode.authentication.getSession` with `github` as the auth provider ID, it's usual scopes, and `createIfNone` set to false.
4. Step 3 returns undefined. 

I don't think step 4 is expected. @TylerLeonhardt maybe you can confirm this?

**Comment by TylerLeonhardt** [comment]
Turns out, the support for GitHub Enterprise slipped in a change that sorted scopes which I don't think we wanted. I've reverted back to not sorting scopes and it seems to be working for me.

**Comment by Tyriar** [comment]
I'm still hitting https://github.com/microsoft/vscode-pull-request-github/issues/2750, is this not released yet in nightly v2021.6.1983?

**Comment by benblo** [comment]
I have this issue as well... if I open several VsCode window, I get the login popup each time.

**Comment by jgile** [comment]
same problem
