### ISSUE TITLE
Cannot view pull request from a fork

### ISSUE THREAD

**Issue by FairlySadPanda** [microsoft/vscode-pull-request-github#2756]
I am the owner of my repository and am fully signed in.

I am trying to use this extension to review this PR: https://github.com/FairlySadPanda/vrcbce/pull/21
I am able to see and review this PR: https://github.com/FairlySadPanda/vrcbce/pull/12

I cannot see PR 21 in the extension:
![image](https://user-images.githubusercontent.com/732532/120116558-9681dd80-c180-11eb-8a2a-1596cf96d8ed.png)

It should not require further configuration than the obvious to view a pull request that is listed in my own repository, even if the origin is a fork. If this requires further setup, there should be documentation for this that is readily searchable for and a helper script built in to set this up.

**Comment by alexr00** [comment]
@FairlySadPanda looking at the the two PRs, I can see that the from repo:branch of 21 is `esnya:feature/ui`. It seems that the `esnya` repo has been deleted. We don't show PRs for deleted repos. Do you know if that repo was deleted at the time that you were trying to view the PR in this extension?

**Comment by FairlySadPanda** [comment]
Hey, the repo wasn't deleted at the time.

The confusing thing here is that a later PR that used the same workflow appeared. But no matter what I tried on my end, PR 21 did not. I ended up having to delete PR 21 and create 22 myself, which showed up.

I appreciate this could be a weird one-off, but it'd be good to know how to diagnose and fix this if it comes up again.

**Comment by alexr00** [comment]
@FairlySadPanda let's leave this issue open for a bit then, and if you see the issue again can you do the following:
- Open the Output panel and copy the output from "GitHub Pull Request" into this issue.
- Open the dev tools (command Developer: Toggle Developer tools) and copy the contents of the console into this issue.

**Comment by alexr00** [comment]
No updates in a while, closing.
