### ISSUE TITLE
Copy/paste images in PR description

### ISSUE THREAD

**Issue by BenjaVR** [microsoft/vscode-pull-request-github#2760]
If we make a PR on the Github website, we can paste an image in the text editor and it will automatically upload the image and put it inline.

It would be nice if we could do the same from the vscode plugin. Now I have to leave placeholders and open the PR in the browser after creation, just to add the images.

**Comment by alexr00** [comment]
duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/320
