### ISSUE TITLE
Fetch URL not valid

### ISSUE THREAD

**Issue by Blfrg** [microsoft/vscode-pull-request-github#2768]
Note: The error message is the same as #1941 however the cause is unrelated.

- Extension version: v0.27.0
- VSCode Version: Version: 1.57.0
- OS: Linux x64 5.4.0-74-generic

![2021-06-10_20-20](https://user-images.githubusercontent.com/3829034/121624032-00766e80-ca2e-11eb-98c4-b580e7b5415d.png)

Steps to Reproduce:
1. Open workspace which has git repos which are not hosted on github.com
2. Commit/Push/Pull and the error will be displayed.

Since this extension is intended only for github.com repos,
it should not try to interact with repos on other domains.
The extension should limit itself to repos hosted on github.com.

If custom domains or other providers are permitted,
a configuration option for a list of additional domains to allow/block would be helpful.

**Comment by bgelens** [comment]
I experience the same for Azure DevOps urls

**Comment by TylerLeonhardt** [comment]
@bgelens @Blfrg using the [GitHub PR nightly build](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github-insiders) do you still see this?

**Comment by bgelens** [comment]
@TylerLeonhardt I don't see it on the nightly build 🥳
