### ISSUE TITLE
Demo links on the Marketplace are broken

### ISSUE THREAD

**Issue by cfiderer** [microsoft/vscode-pull-request-github#2769]
The links to the demos (PR demo, Issue demo) on the [Marketplace page](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github) are broken, the demos are not accessible.
![2021-06-11_10-22-51 GHPR Marketplace](https://user-images.githubusercontent.com/40199723/121655943-4881a980-ca9f-11eb-815a-cba6ceb27c6b.png)

**Comment by plus-** [comment]
they point to `master` instead of `main`
