### ISSUE TITLE
Exception when checking out checked out branch

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-pull-request-github#277]
This is difficult to reproduce but I believe this was the repro:

1. Checkout a branch for review
2. Reload window
3. Swiftly open the PR explorer and checkout the same branch before the extension realizes that it's already checked out

![image](https://user-images.githubusercontent.com/2193314/44674260-d0c35c80-a9e1-11e8-8ba2-ae62b601b25a.png)

**Comment by rebornix** [comment]
@Tyriar do you have detailed call stack when you ran into this issue?
