### ISSUE TITLE
i am unable to run program

### ISSUE THREAD

**Issue by Ruthwick1504** [microsoft/vscode-pull-request-github#2774]
Issue Type: <b>Bug</b>

i am facing problem in running program it is showing popup about pull up request.

Extension version: 0.27.0
VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (4.45GB free)|
|Process Argv|--crash-reporter-id dab6a96a-8dff-425d-ab37-38a961f2e30d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
pythonvsuse255cf:30319632
vscgsv2:30307504
vscorehov:30309549
vscod805cf:30301675
binariesv517cf:30312826

```

</details>

**Comment by alexr00** [comment]
Can you please share a screen shot and detailed steps to reproduce the issue?

**Comment by Ruthwick1504** [comment]
> Can you please share a screen shot and detailed steps to reproduce the issue?

![image](https://user-images.githubusercontent.com/81862163/122001545-19847400-cdce-11eb-98b5-2517ee593e1d.png)

**Comment by Ruthwick1504** [comment]
please tell me how do i resolve this

**Comment by alexr00** [comment]
Can you open the developer tools (command "Developer: Toggle developer tools"), reproduce the issue, then share the contents of the console from the developer tools?
