### ISSUE TITLE
No Commits view for Pull Request

### ISSUE THREAD

**Issue by wcerfgba** [microsoft/vscode-pull-request-github#2776]
Issue Type: <b>Bug</b>

1. `git checkout <branch>` 
2. Open GitHub Pull Requests in sidebar
3. Unfold relevant ticked PR
4. Observe no Commits tree

![image](https://user-images.githubusercontent.com/1129959/121875135-04411400-cd00-11eb-85a2-eb1b62793541.png)

Extension version: 0.27.0
VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.895Z)
OS version: Linux x64 5.12.0-pf5
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.56GB (0.48GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 0e53faab-c6a1-4e2b-a6a4-18c06abdc23b|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|i3|
|XDG_CURRENT_DESKTOP|i3|
|XDG_SESSION_DESKTOP|i3|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
pythonvsuse255:30319631
vscgsv2:30307504
vscorehov:30309549
vscod805:30301674
binariesv517cf:30312826

```

</details>

**Comment by alexr00** [comment]
The commits tree only shows in the active PR view, which is the view with a rectangle around it:

![image](https://user-images.githubusercontent.com/38270282/121909292-1043ca80-cd2e-11eb-8dca-3c1dcd533bb4.png)
