### ISSUE TITLE
Fetching failed if origin is on visualstudio.com

### ISSUE THREAD

**Issue by carlocardella** [microsoft/vscode-pull-request-github#2781]
- Extension version: v0.27.0
- VSCode version:
```
Version: 1.57.0 (user setup)
Commit: b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
Date: 2021-06-09T17:18:42.354Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043
```

Steps to Reproduce:

I am not sure if this extension is supposed to work with `visualstudio.com` (I thought it was only GitHub?), anyway this started happening with v0.27, if I downgrade to v0.26 I can no longer repro the error

1. Open a git repo cloned from `visualstudio.com`
2. Sync with the remote

![image](https://user-images.githubusercontent.com/5784415/121971006-a4ad2d80-cd2c-11eb-9a51-0e8a8d114e9d.png)

**Comment by papey** [comment]
Same here with all my repos that are not github.com related.

**Comment by nerdmax** [comment]
Same here, my repo's origin is bitbucket.

**Comment by alexr00** [comment]
This should already be fixed in the nightly build of the extension (and the fix will be in the next release). If you still see the issue there please ping this issue!
