### ISSUE TITLE
Unable to fetch PR for remote

### ISSUE THREAD

**Issue by coder2000** [microsoft/vscode-pull-request-github#2783]
- Extension version: 0.27.0
- VSCode Version: 1.57.0
- OS: Arch Linux

AFAIK the extension is supposed to only work with GitHub and I keep getting an error that it cannot fetch the pull requests for origin when the origin is a different service like BitBucket.

Steps to Reproduce:
1. Define an origin that is different from GitHub
2. Push commits

**Comment by nerdmax** [comment]
Anything we can do to prevent this extension from automatically fetching pull requests from the origin that is not GitHub related?

**Comment by alexr00** [comment]
This should already be fixed in the nightly build of the this extension (and should be fixed in the next release). If you still see the issue in either of those then please ping this issue!

**Comment by coder2000** [comment]
It still happens with 0.27.1 or were you talking about 0.28?

**Comment by alexr00** [comment]
0.28.0 (not yet released) and the [nightly build](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github-insiders) have it.
