### ISSUE TITLE
Description of PRs doesn't get updated when forcing a refresh

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode-pull-request-github#279]
Description of PRs doesn't get updated when forcing a refresh.

1. View PR description page. Notice the description
2. Go to GitHub, update description
3. Go back to VS Code, right click as select "Refresh PR"
4. Description isn't updated.

**Comment by rebornix** [comment]
* Run refresh action from PR node's context menu doesn't work, closing and reopening the PR description page but it's still the old one
* The description page is not updated when run the global refresh command (refresh the whole tree).

We don't necessarily need to fix the second issue in August IMO.

**Comment by msorens** [comment]
Another aspect to the same issue:
New comments added from GitHub also do not show up on the Description page, though you can see them when viewing individual files.

**Comment by RMacfarlane** [comment]
Fixed with https://github.com/Microsoft/vscode-pull-request-github/commit/7ac61967a61be128d5bfcbfa33976385e85c5132
