### ISSUE TITLE
False positive "This branch has conflicts that must be resolved."

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode-pull-request-github#2792]
- Extension version: Nightly v2021.6.30916
- VS Code and OS info:
Version : 1.58.0-insider (user setup)
Commit : d54f7e1f6c1290fe27e2397eca509d0e0728272e
Date : 2021-06-22T07:15:24.214Z
Electron : 12.0.11
Chrome : 89.0.4389.128
Node.js : 14.16.0
V8 : 8.9.255.25-electron.0
OS : Windows_NT x64 10.0.19043

Steps to Reproduce:

1. I created a new PR.
2. I scrolled down and saw that there was a message warning about a conflict, but there is none.

![An example screenshot showing that there is a merge conflict in GHPRI but not on GitHub for the same PR](https://user-images.githubusercontent.com/7199958/123013145-840e5480-d378-11eb-9781-1406deeef4a4.png)

**Comment by alexr00** [comment]
@rzhao271 does this happen every time for you? Does it happen consistently for specific PRs?

**Comment by rzhao271** [comment]
I'm unable to reproduce this issue by checking out PRs I currently have open.
I'll have to see if it shows up only during creation of new PRs.

**Comment by rzhao271** [comment]
Closing for now.
