### ISSUE TITLE
Pull request view + first diff should be opened less agressively

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#2794]
The pull request view + the first diff should only be opened automatically when:
- The user has just created the PR
- The user opened the PR through the PR UI 

Some examples of times when the PR view + first diff should not be opened:
- When the user changes branches with git or with the git UI
- When the user opens a folder and that folder just happens to be on a branch with a PR

**Comment by alexr00** [comment]
@bamurtaugh and @tanhakabir FYI.

**Comment by connor4312** [comment]
I'm not really sure how to verify this, when I checkout a PR and switch folders on stable I don't get the view re-opened

**Comment by alexr00** [comment]
Things to verify:
- Checkout a PR from the PRs view. Verify that the view is opened.
- Switch branches using the command line. Verify that the view is _not_ opened.
- Create a PR. Verify that the view is opened.
- Checkout a PR from the PRs view. Close that folder. Open that folder. Verify that the view is _not_ opened.

**Comment by chrmarti** [comment]
Verified assuming this is only about this view (not the editor):
![image](https://user-images.githubusercontent.com/9205389/124445064-819bf980-dd7f-11eb-9a4e-d49110e5162e.png)
