### ISSUE TITLE
Better support for non-GitHub remotes

### ISSUE THREAD

**Issue by acdha** [microsoft/vscode-pull-request-github#2797]
- Extension version: 0.27.1
- VSCode Version: 1.57.1
- OS: macOS Big Sur

Steps to Reproduce:

1. Open a Git repo which uses a non-GitHub remote

This will get an error like this on every project you open:
```
Fetching pull requests for remote 'origin' failed, please check if the url ssh://git@gitlab.example.org:7999/… is valid.
```

Now, I can disable the extension in workspaces which aren't for GitHub projects but it would be nice if this either happened automatically based on the hostname and/or a probe saved after the first request so I didn't get an error from anything which isn't github.com or a server which appears to support the GitHub Enterprise API.

**Comment by alexr00** [comment]
This should already be fixed in the nightly build of the extension (and the fix will be in the next release). If you still see the issue there please ping this issue!
