### ISSUE TITLE
Clicking a change of a PR which is currently checked out should use the actual file on disk

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-pull-request-github#28]
Currently, when clicking on such a change, we still use a temp file, as mentioned in #27.

**Comment by kieferrm** [comment]
@joaomoreno you talk about the "Changes in Pull Request" files? The question here is what should happen when I have changes on top of the PR. This is somehow similar to the git extension, when you have changes staged. When you click the staged file you see the version that's staged, not the one your workspace contains.

**Comment by joaomoreno** [comment]
That's a great point. We should be a bit more clear as to what the difference between the two trees actually is.

**Comment by RMacfarlane** [comment]
This has already been completed, the "Change in Pull Request" tree should diff with the actual file on disk and should allow opening it directly
