### ISSUE TITLE
Tests do not run

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode-pull-request-github#280]
The test script is `node ./node_modules/mocha/bin/_mocha --timeout 1000 --colors ./out/test/**/*.js`, but everything is now bundled into `media` as a single file

**Comment by rebornix** [comment]
Brought back testing and found that we have one failing test …

**Comment by rebornix** [comment]
Fixed via https://github.com/Microsoft/vscode-pull-request-github/commit/92bea3d66296db784e1806d9e3e838416662f375
