### ISSUE TITLE
Publish to GitHub stuck with GitHub Pull Requests Extension

### ISSUE THREAD

**Issue by albertkao** [microsoft/vscode-pull-request-github#2802]
Issue Type: <b>Bug</b>

Publish to GitHub stuck with the GitHub Pull Requests and Issues Extension.
How to fix or debug this issue?
I edited and committed one small file with one line change, which is very fast as expected.
However, publish to GitHub for that commit is stuck in the two revolving circles at the status bar, even after one hour.
Authentication is fast with the GitHub Pull Requests and Issues Extension.

As a comparison, adding files, etc, at https://github.com with a browser, which is very fast as expected.

My Visual Studio Code has only one Extension:
GitHub Pull Requests v0.27.1

Visual Studio Code info:
Version: 1.57.1 (user setup)
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:28:07.755Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19042

Extension version: 0.27.1
VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz (4 x 2395)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|5.86GB (0.72GB free)|
|Process Argv|--crash-reporter-id c894de1e-c7a8-472c-884b-527c2abe550a|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805cf:30301675
pythonvspyt200:30329803
vscextlangct:30322307
binariesv615:30325510

```

</details>

**Comment by alexr00** [comment]
Can you share the output from GitHub Pull Request?

**Comment by albertkao** [comment]
This issue disappears.   
Publish to GitHub works as expected.
The output from GitHub Pull Request is blank.
