### ISSUE TITLE
Element already registered

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-pull-request-github#2803]
![image](https://user-images.githubusercontent.com/323878/123479708-30894a00-d5b6-11eb-9740-7bd6c1ba075c.png)

```
Element with id Local Pull Request Brancheshttps://github.com/microsoft/vscode/pull/60058 is already registered
```

I just reloaded the window, expanded all the nodes, and got that

**Comment by alexr00** [comment]
@roblourens can you share the output from GitHub Pull Request when this occurs? I can't repro it, but there's logging around this that might provide a clue.
