### ISSUE TITLE
Hover card fails to appear when hovering over issue number

### ISSUE THREAD

**Issue by melink14** [microsoft/vscode-pull-request-github#2804]
- Extension version: 0.27.1
- VSCode Version: 1.57.1
- OS: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Hover over an issue number like `// See issue #366 for an example where it breaks look ups.`
2. Notice that issue hover card fails to appear.

In output logs I see recurring logs appear each time as follows:

```
[Info] GithubRepository> Unable to fetch PR: TypeError: Cannot read property 'owner' of undefined
[Info] GithubRepository> Unable to fetch PR: Error: GraphQL error: Could not resolve to a PullRequest with the number of 366.
```

**Comment by alexr00** [comment]
This should already be fixed in the nightly build of the extension, and will be fixed in the next stable release of the extension too.
