### ISSUE TITLE
Always prompt to fork Repository

### ISSUE THREAD

**Issue by binsee** [microsoft/vscode-pull-request-github#2805]
- Extension version: 0.27.1
- VSCode Version: 1.57.1 (user setup)
- OS: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Choose an issue
2. click `Start Working on Issue and Checkout Topic Branch`
3. A prompt pops up to fork
4. Select fork and wait for the fork to complete
5. Choose another issue
6. click `Start Working on Issue and Checkout Topic Branch`
7. The fork still pops up

This problem occurs when working in a repository from a fork.
I checked the project code and debug log and found that there was a problem with the code, which caused this problem to be repeated.
I fixed the code and submit pr later, please review it.

My native language is not English, please forgive my grammatical error.

**Comment by stuartleeks** [comment]
I'm not seeing the prompts to create a fork in the latest nightly build (`v2021.7.39424`), but I'm also not getting it with the `0.28` release (which I don't think has this fix in?), so I'm not sure whether I'm testing the wrong thing or have a different configuration?

**Comment by alexr00** [comment]
To verify using the nightly build (an older one is ok):
1. Clone a repo that you don't have a fork of and that you don't have permission to push to.
2. Using the Issues view, Start Working on an issue.
3. Verify that you're prompted to fork.
4. Follow the fork flow.
5. Using the Issues, view, Stop Working on the issue.
6. Start working on an issue again.
7. Verify that you don't get another fork prompt.

**Comment by stuartleeks** [comment]
Thanks @alexr00. Following those steps, I can repro with `0.28` and confirm that I no longer see the issue on the nightly build 😄
