### ISSUE TITLE
Close pull request action should...

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode-pull-request-github#281]
Testing https://github.com/Microsoft/vscode/issues/57301

- use a modal dialog for confirmation. The notification in the lower right corner can easily be overlooked.
- allow me to add a final close comment

**Comment by rishab-pdx** [comment]
I would like to take it if no one is taking it.

I see we have to use ```modal``` in

https://github.com/microsoft/vscode-pull-request-github/blob/master/src/commands.ts#L318

I am not clear on the second bullet point. Are we supposed to prompt the user for a final comment  again with a ```inputBox``` as we already have the comment box in PR overview panel.
