### ISSUE TITLE
Unable to checkout PR from overview page

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#2812]
From @misolori (https://github.com/microsoft/vscode-pull-request-github/issues/2688#issuecomment-871488680):

I'm seeing a couple of issues. When trying to check out the PR from the overview page, I get a "branch not found" error. Then when I manually change to the branch and attempt to open the commit file, I get a "couldn't find commit"

<img width="1024" alt="CleanShot 2021-06-30 at 08 06 16@2x" src="https://user-images.githubusercontent.com/35271042/123985367-457d2900-d97a-11eb-8a83-cd659006da52.png">

GHPR: v2021.6.42304
Version: 1.58.0-insider (Universal)
Commit: 57930758db9e2c83f59b9ee1851400bd16192d32
Date: 2021-06-30T05:13:11.659Z
Electron: 12.0.12
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin arm64 20.5.0

<hr>

**Comment by alexr00** [comment]
@misolori is the PR you're seeing this with in a public repo and if so can you share a link? I'd like to try to repro with the same PR.

**Comment by misolori** [comment]
Yes, it's https://github.com/misolori/create-react-app/pull/6

**Comment by alexr00** [comment]
Thanks! I can repro!
