### ISSUE TITLE
Show amount of 'marked' files

### ISSUE THREAD

**Issue by BenjaVR** [microsoft/vscode-pull-request-github#2813]
In the pull request window you can mark files as 'viewed', but when reviewing a lot of files I have a hard time verifying if I did not miss any file.

I think a simple counter somewhere (e.g. `✔️ 24/25`) could make this easier.

Another solution would be to filter the list of files based on the 'marked' state.

**Comment by selrond** [comment]
I wanted something to better differentiate between viewed and not viewed files for so long.
The best (and probably the easiest to implement) way I think would be dimming the file names that are marked as viewed

**Comment by alexr00** [comment]
This is now done via checkboxes.
