### ISSUE TITLE
vs code

### ISSUE THREAD

**Issue by VVAgw** [microsoft/vscode-pull-request-github#2814]
"githubPullRequests.queries": [
    {
        "label": "Waiting For My Review",
        "query": "is:open review-requested:${user}"
    },
    {
        "label": "Assigned To Me",
        "query": "is:open assignee:${user}"
    },
    {
        "label": "Created By Me",
        "query": "is:open author:${user}"
    },
    {
        "label": "Mentioned Me",
        "query": "is:open mentions:${user}"
    }
]

**Comment by Donna3344** [comment]
Thank you so much.

**Comment by Donna3344** [comment]
Thanks to VVAgw awesomeness
