### ISSUE TITLE
Spurious error message popped up on non-Github repositories

### ISSUE THREAD

**Issue by jaens** [microsoft/vscode-pull-request-github#2816]
- Extension version: v0.27.1
- VSCode Version: 1.57.1
- OS: Linux x64 5.10.0-6-amd64

Steps to Reproduce:

1. Open a repository that has a non-Github main remote configured.

Expected:
* Nothing happens.

Actual:
* Error message pops up in a notification every time:  
 "Fetching pull requests for remote 'origin' failed, please check if the url git@bitbucket.org:my_user/my_repo is valid."

**Comment by alexr00** [comment]
Already fixed for 0.28.0 and in the nightly build.

**Comment by jaens** [comment]
@alexr00 Nice that it's fixed, but 0.28.0 has not been released yet?

**Comment by alexr00** [comment]
0.28.0 was released last Thursday.
