### ISSUE TITLE
Support autolinked references (issue, PR, commit shorthands)

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-pull-request-github#2817]
They're all listed in the Github documentation [here](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/autolinked-references-and-urls)

**Comment by alexr00** [comment]
Where do you want these to be supported (code editor, comments, review overview)?

**Comment by 4086606** [comment]
All three! But it occurs to me that code editor support could produce false positives, so that should have a user setting

**Comment by alexr00** [comment]
We used to support issues and PRs links in the editor, but it was to slow so we removed it.
Issue and PR links are already supported in the overview.

**Comment by texastoland** [comment]
Do hovers still exist? I can't make them appear, see relevant settings, or find associated documentation 😓

**Comment by alexr00** [comment]
Documentation is here: https://github.com/microsoft/vscode-pull-request-github/blob/main/documentation/IssueFeatures.md

It's a little out of date. I will try to update it soon!

**Comment by texastoland** [comment]
Thanks for the reference 🙏🏼 From that list I don't get the code action to create an issue or completions or hovers for issues. I'm authenticated and working on my forked `origin` with issues disable and the `upstream` original repo properly configured. Am I missing something? Are you aware of a related issue already?

**Comment by alexr00** [comment]
@texastoland those are all still working well for me. Can you please open a new issue for these and add some screenshots or gifs of things that you are not seeing work?

**Comment by texastoland** [comment]
I can! A video of them ... not appearing? Should the file type (ex. F#) matter?

**Comment by alexr00** [comment]
We pay attention to file type for some features, but it shouldn't matter for any of the features that you've listed.

**Comment by SNDST00M** [comment]
* microsoft/vscode-pull-request-github#1858
* microsoft/vscode#99356

**Comment by texastoland** [comment]
Sorry to spam this issue! I'd also like to propose a different default query for autocomplete. Otherwise it isn't discoverable in typical open source workflows where no one is ever assigned. Is that worth a separate ticket or already discussed and decided?

**Comment by alexr00** [comment]
We now have more things linkified in comments.
