### ISSUE TITLE
PR Reviews: Differentiate between adding comments and review comments

### ISSUE THREAD

**Issue by mymindstorm** [microsoft/vscode-pull-request-github#2818]
Issue Type: <b>Bug</b>

In a pull request, there is a difference between "single" comments and comments associated with a code review. The latter are hidden until the review is complete. The current commenting UI does not differentiate between a "review comment" and a "single comment," which is very confusing. I should be able to tell which type of comment is about to be made before clicking the "Add Comment" button.

Extension version: 0.27.1
VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:26:56.255Z)
OS version: Linux x64 5.12.13-300.fc34.x86_64
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3788)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|15.59GB (2.53GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id c51d7420-a9e9-497a-b40a-40606b86db8e|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome-xorg|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome-xorg|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by alexr00** [comment]
We do sort of show whether a comment is going to be a single comment or part of a review. 
- On your first comment, and ever subsequent comment unless you start a review, the comment buttons are "Start a Review" and "Add a Comment". I think this one is pretty clear.
- Once you've used the "Start a Review" button, all subsequent comments are part of your review.
- A comment that's part of an incomplete review will say "Pending", whereas a single comment will not.
![image](https://user-images.githubusercontent.com/38270282/124584742-e37a6300-de54-11eb-9339-d1baf4e8fbca.png)

**Comment by mymindstorm** [comment]
Thanks for the info. I encountered this by going to the PR and then entering review mode with a partial review already open. Due to that, I never saw the "Start Review" button, which caused me a bit of confusion.

I think that the clarity of the review comment UI (before creating the comment) would be improved by changing the string to "Add review comment".

**Comment by alexr00** [comment]
To verify:

1. Install the pre-release version of the extension
2. Open a folder that contains a clone of a GitHub repo
3. Open the comments widget by clicking on the + in the comments bar.
4. Verify that if you haven't started a review you see buttons to "Start Review" and "Add Comment" when you open the comments widget.
5. Start a review.
6. Open the comments widget by clicking on the + in the comments bar.
7. Verify that you no longer see "Start Review" and "Add Comment" but instead see "Add Review Comment".
