### ISSUE TITLE
Webview is disposed

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-pull-request-github#2819]
Found verifying #2794 using the nightly build v2021.7.2002.

I previously entered and exited review mode for https://github.com/chrmarti/vscode-regex/pull/47. Then I did `git checkout pr/dagrooms52/47` in the terminal and the below error was shown.

![image](https://user-images.githubusercontent.com/9205389/124443637-23bae200-dd7e-11eb-91e7-a7b5ed5ffccc.png)

Rest of the console:

![image](https://user-images.githubusercontent.com/9205389/124444100-8d3af080-dd7e-11eb-8439-57237ef03cc8.png)

**Comment by alexr00** [comment]
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/2444
