### ISSUE TITLE
Error when handling outdated comments

### ISSUE THREAD

**Issue by sfc-gh-sgiesecke** [microsoft/vscode-pull-request-github#2831]
- Extension version: 0.26.0
- VSCode Version: 1.56.2
- OS: CentOS / Linux

Steps to Reproduce:

1. Open a PR and file with outdated comments

Expected behaviour:

Outdated comments are somehow visible

Actual behaviour:

Errors in log like
```
[Info] Failed to parse patch for outdated comments: Failed to execute git {
  "exitCode": 128,
  "gitCommand": "diff",
  "stdout": "",
  "stderr": "fatal: Invalid symmetric difference expression 493338c5e5666ea78107a7397a739cb6326dbf22...38a6634c3392755b47f24b4867d32916fc6310bd\n"
}
```

**Comment by alexr00** [comment]
@sfc-gh-sgiesecke do you have a PR in a public repo that you can share a link to?

**Comment by sfc-gh-sgiesecke** [comment]
Unfortunately not, I have used the extension only with a private repo so far.

**Comment by 0xabu** [comment]
I think I'm seeing this on https://github.com/pdfminer/pdfminer.six/pull/661 (which I just opened for the first time to try out this extension). The only two comment I see in the extension are the non-outdated ones; outdated but unresolved comments don't appear anywhere.

There are no obvious errors in the log, but I do see this which suggests that the extension is seeing something about the missing comments:
```
[Info] PullRequestCommentController> Thread with ID pdfminer/high_level.py-modified is no longer in cache
[Info] PullRequestCommentController> Thread with ID pdfminer/arcfour.py-modified is no longer in cache
[Info] PullRequestCommentController> Thread with ID pdfminer/ccitt.py-modified is no longer in cache
[Info] PullRequestCommentController> Thread with ID pdfminer/ccitt.py-modified is no longer in cache
[Info] PullRequestCommentController> Thread with ID pdfminer/ccitt.py-modified is no longer in cache
[Info] PullRequestCommentController> Thread with ID pdfminer/encodingdb.py-modified is no longer in cache
[Info] PullRequestCommentController> Thread with ID setup.py-modified is no longer in cache
[Info] PullRequestCommentController> Thread with ID tools/dumppdf.py-modified is no longer in cache
[Info] PullRequestCommentController> Thread with ID tools/pdf2txt.py-modified is no longer in cache
```

Extension 0.30.0, VSCode 1.60.0

**Comment by alexr00** [comment]
I haven't been able to reproduce this issue and there have been no further reports. If it happens again I will investigate further!
