### ISSUE TITLE
Right Click + Checkout PR doesn't work

### ISSUE THREAD

**Issue by gsquared94** [microsoft/vscode-pull-request-github#2834]
Issue Type: <b>Bug</b>

Open [this](https://github.com/gsquared94/skaffold) fork in VSCode. Tried to checkout [this](https://github.com/GoogleContainerTools/skaffold/pull/6194) PR from [upstream](https://github.com/GoogleContainerTools/skaffold) 

Get the prompt without going into `Review Mode`
```
X Error
```

It works for PRs on the upstream from other forks but doesn't work for checking out any PRs originating from [this](https://github.com/tejal29/skaffold) fork.
Extension version: 0.26.0
VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:32.912Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.15GB free)|
|Process Argv|--crash-reporter-id a5bc59e0-dfc3-44bf-970b-d30be94a5ece|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by gsquared94** [comment]
Another issue I've encountered:
- I've checked out a PR branch, and exit the review mode and switch the branch.
- There's a force push on the PR branch
- I try to check out the same PR again, it fails. IMO if the target branch already exists locally it should prompt for a reset in case of conflicts.

**Comment by gsquared94** [comment]
I've been trying with the Nightly build and instead of just `X Error` it now produces the error:
```
hint: Pulling without specifying how to reconcile divergent branches is hint: discouraged. You can squelch this message by running one of the following hint: commands sometime before your next pull: hint: hint: git config pull.rebase false # merge (the default strategy) hint: git config pull.rebase true # rebase hint: git config pull.ff only # fast-forward only hint: hint: You can replace "git config" with "git config --global" to set a default hint: preference for all repositories. You can also pass --rebase, --no-rebase, hint: or --ff-only on the command line to override the configured default per hint: invocation. From github.com:tejal29/skaffold 4fe68b28a..2a72a462a add_aborted -> tejal29/add_aborted c533e7ca1..083292092 add_sk_logs_for_pod -> tejal29/add_sk_logs_for_pod ! [rejected] v1.11.0 -> v1.11.0 (would clobber existing tag) . Please check git output for more details
```

**Comment by alexr00** [comment]
@gsquared94 thanks for trying the nightly build! I think the error message now gives you enough information to resolve the issue on your system. Since the error you're seeing is uncommon and results from a setup that needs to be fixed (i.e., if you checked out the branch manually you'd see the same problem) I will leave this as is.
