### ISSUE TITLE
Save Actions slowed/blocked in large workspaces

### ISSUE THREAD

**Issue by jsg2021** [microsoft/vscode-pull-request-github#2835]
I would love to use this extension, but I currently can't with my workflow. I have an application spread across ~50+ modules (all active on my .code-workspace) When I install this module, save actions frequently take several seconds to complete. Without this extension no perceivable delay. I know my scenario is probably pushing the limits, but I'm on a very beefy machine that should be able to push through... I think the slowness is something blocking on a request/per-repo.

- Extension version: 0.28.0
- VSCode Version: 1.58.1
- OS: Fedora 34

Steps to Reproduce:

1. Add 50+ git repos to your workspace (not sure if size of repo matters or not, all mine are non-trivial)
2. Make edits in some code... most noticible with eslint/prettier enabled and you type something it will fix... 
3. save
4. notice the save actions take significant time.
5. disable this extension, repeat... no significant delay.

Can whatever this is doing in a Save Action be made async or fired off in the background?

**Comment by alexr00** [comment]
@jsg2021 this extension doesn't register for either `onWillSaveTextDocument` or `onDidSaveTextDocument`, so there are no save actions in GitHub Pull Requests and Issues.

**Comment by jsg2021** [comment]
I didn't think it had, but at the time of writing the initial issue, it was the only variable changing. (to my knowledge.) Slow with it on, and performance was fine with it disabled.

**Comment by alexr00** [comment]
This extension does a lot of work based on some git events. Were you changing branches or making commits at the time of the slowness?

**Comment by jsg2021** [comment]
No, just normal editing. Maybe file watchers or git status checks were triggered on save? It's entirely possible that my workspace is too large for this extension. 😕 (tho, vs code seems fine otherwise.) -- 50-60 github repos with in a workspace.

**Comment by alexr00** [comment]
If you set `githubPullRequests.logLevel` to `debug` and then share the Output from GitHub Pull Request next time you see the slowness I can see if there's anything suspicious in the logs.
