### ISSUE TITLE
Extension should have a node for closed PRs

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode-pull-request-github#284]
Testing https://github.com/Microsoft/vscode/issues/57301

**Comment by akshita31** [comment]
Any updates here ? Sometimes it is useful to go back and read through old pr's to understand a concept.

**Comment by RMacfarlane** [comment]
This can now be accomplished by adding a custom category to the GitHub Pull Requests tree. More info here: https://github.com/microsoft/vscode-pull-request-github#configuring-the-extension

An example would be
```
"githubPullRequests.queries": [
	{
		"label": "Waiting For My Review",
		"query": "is:open review-requested:${user}"
	},
	{
		"label": "Assigned To Me",
		"query": "is:open assignee:${user}"
	},
	{
		"label": "Created By Me",
		"query": "is:open author:${user}"
	},
	{
		"label": "Closed”,
		"query": "is:closed"
	}
]
```
