### ISSUE TITLE
Could not resolve conversation on old PR

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#2857]
I tried to resolve this comment via the extension: https://github.com/xtermjs/xterm.js/pull/3212#discussion_r555103406, the reaction icon also wasn't showing:

![image](https://user-images.githubusercontent.com/2193314/126714506-3a468527-ee44-4f11-a805-bf5d7ce56d1d.png)

ext: v2021.7.30987
Version: 1.59.0-insider (user setup)
Commit: e8a59bc6f920e731b47f0bc72263e82aba8b796e
Date: 2021-07-22T05:14:01.507Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by alexr00** [comment]
Reaction not showing is https://github.com/microsoft/vscode/issues/128770.

**Comment by alexr00** [comment]
I think we need https://github.com/microsoft/vscode/issues/130107 in order to solve this without a hack.

**Comment by eladcandroid** [comment]
I experienced it now... is there anything new? 
Can you merge the last commits?
