### ISSUE TITLE
Multiline string settings are now supported in the settings editor

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode-pull-request-github#2859]
Hi! Just a note that you can now add the `"editPresentation": "multilineText"` key-value pair to any string setting that can take multiple lines (such as `githubIssues.workingIssueFormatScm`). In the settings editor, the setting will then display a textarea rather than a single-line inputbox. The feature is currently available in the Insiders edition of VS Code, and will be released to Stable in around two weeks.

**Comment by alexr00** [comment]
To verify:
- Install the Nightly version of the extension and disable the stable version if you have it installed
- Open the settings editor and edit the setting `githubIssues.workingIssueFormatScm`.
- Verify that it uses the multiline input box.
