### ISSUE TITLE
Try to use something else than '+' for add comment button 

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode-pull-request-github#286]
Testing https://github.com/Microsoft/vscode/issues/57301

There is a bit too much overload, especially in the context of a diff:

![screenshot from 2018-08-28 06-48-34](https://user-images.githubusercontent.com/5047891/44727238-6ddbcf00-aa8e-11e8-9f25-8ae7a57522b5.png)

Perhaps you can use a different character, like the "speech balloon" -  💬  -  https://www.fileformat.info/info/unicode/char/1f4ac/index.htm

**Comment by alexr00** [comment]
@RMacfarlane I like this one. Is this something that can be changed in microsoft/vscode?

**Comment by alexr00** [comment]
This has been done!
