### ISSUE TITLE
PRs and issues aren't loading

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode-pull-request-github#2860]
![recording (38)](https://user-images.githubusercontent.com/29464607/126838601-5d61e56f-f0a9-4bc1-b756-876268b13b18.gif)
Issue Type: <b>Bug</b>

**The output channel says:**
`[Info] Registering git provider`

**Dev tools says:**
`rejected promise not handled within 1 second: Failed to execute git {  "exitCode": 128,  "gitCommand": "fetch",  "stdout": "",  "stderr": "fatal: couldn't find remote ref merogge/default2\n"} (at c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:104:30466)`

I tried:
- restarting the extension host
- disabling the extension, reloading the window, enabling the extension 
- switching branches

Extension version: 2021.7.30987
VS Code version: Code - Insiders 1.59.0-insider (e8a59bc6f920e731b47f0bc72263e82aba8b796e, 2021-07-22T05:14:01.507Z)
OS version: Windows_NT x64 10.0.21376
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.59GB (10.99GB free)|
|Process Argv|--crash-reporter-id 3420d46c-96c2-459d-a2a6-a3ea05795ead|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vspre833:30321513
vsdfh931:30280409
vshan820:30294714
vscus158:30321503
vscod805:30301674
bridge0708:30335490

```

</details>

**Comment by meganrogge** [comment]
more info in the output channel:
```
[Info] Registering git provider
[Info] Registering git provider
[Info] Looking for git repository
[Info] Found 1 repositories during activation
[Info] Git repository found, initializing review manager and pr tree view.
[Info] Review> Validate state in progress
[Info] Review> Validating state...
[Info] Cannot updates repositories as git is uninitialized
[Info] Review> no matching pull request metadata found for current branch main
[Info] Review> no matching pull request metadata found on GitHub for current branch main
[Info] Review> Queuing additional validate state
[Info] Review> Validating state...
[Info] Cannot updates repositories as git is uninitialized
[Info] Review> no matching pull request metadata found for current branch main
[Info] Review> no matching pull request metadata found on GitHub for current branch main
```

**Comment by misolori** [comment]
Also running into the same issue on the nightly version v2021.7.36543

<img width="349" alt="CleanShot 2021-07-26 at 13 44 18@2x" src="https://user-images.githubusercontent.com/35271042/127056566-f50e4a69-2041-4de9-b87a-2d5348bb6faf.png">

**Comment by alexr00** [comment]
Is the Git SCM view loaded? The logs indicate that we're still waiting for the git extension to say that it's ready.

**Comment by misolori** [comment]
Git is working and loaded, I've been able to commit + push. This happens on any repo I open up, and in a blank workspace the Issues view gets stuck in "loading"

<img width="547" alt="CleanShot 2021-07-27 at 08 26 15@2x" src="https://user-images.githubusercontent.com/35271042/127182029-88075772-8fef-4e69-b981-b50f959b73de.png">

However, it appears that in remote repositories it does load:

<img width="431" alt="CleanShot 2021-07-27 at 08 26 57@2x" src="https://user-images.githubusercontent.com/35271042/127182152-982d4b10-c8bf-4204-878c-a01526c074a6.png">

**Comment by alexr00** [comment]
Do you have `extensions.webWorker` set? If yes, that could be the culprit.

**Comment by misolori** [comment]
I actually do not. 

I just tried one more thing: I opened vscode in a new user data directory, had to re-authenticate, and that was able to bring up the views. So wonder if something is in the cache that is broken? I tried re-authenticating with my current vscode and that didn't do anything.

**Comment by meganrogge** [comment]
This is happening for me on both my mac and surface-book. It started happening ~4/5 days ago - did something change around then?

**Comment by misolori** [comment]
Also seeing this in the console logs:

```log
[Extension Host] Failed to connect to provider "No token found for host github.com" (at console.e.<computed> [as log] (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/microsoft-authentication/dist/extension.js:1:170797))
```

<img width="1007" alt="CleanShot 2021-07-28 at 14 20 01@2x" src="https://user-images.githubusercontent.com/35271042/127397569-699deccd-e75f-4135-aa54-9ff84c454011.png">

**Comment by alexr00** [comment]
@TylerLeonhardt does the log line here indicate some specific issue to you? https://github.com/microsoft/vscode-pull-request-github/issues/2860#issuecomment-888629406

**Comment by TylerLeonhardt** [comment]
> No token found for host github.com

> Microsoft authentication extension

how odd...

Let me ask this question, when you log out of your accounts and it shows the notification "successfully signed out", if you go into the account menu again does it say you're signed in still?

**Comment by connor4312** [comment]
I'm hitting this as well, though not seeing the token error Miguel is reporting. Let me know if there's any more info you need.

GHPR output:

```
[Info] Registering git provider
[Info] Registering git provider
[Info] Looking for git repository
[Info] Found 1 repositories during activation
[Info] Git repository found, initializing review manager and pr tree view.
[Info] Review> Validate state in progress
[Info] Review> Validating state...
[Info] Cannot updates repositories as git is uninitialized
[Info] Review> no matching pull request metadata found for current branch master
[Info] Review> no matching pull request metadata found on GitHub for current branch master
```

Git output:

```
Validating found git in: /usr/bin/git
Using git 2.30.1 (Apple Git-130) from /usr/bin/git
> git rev-parse --git-dir
Open repository: /Users/connor/Github/mopidy-azure
> git status -z -u
> git symbolic-ref --short HEAD
> git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track) refs/heads/master refs/remotes/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
Warning: Failed to watch ref '/Users/connor/Github/mopidy-azure/.git/refs/remotes/origin/master', is most likely packed.
> git config --get commit.template
> git config --local branch.master.github-pr-owner-number
> git status -z -u
> git symbolic-ref --short HEAD
> git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track) refs/heads/master refs/remotes/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
Warning: Failed to watch ref '/Users/connor/Github/mopidy-azure/.git/refs/remotes/origin/master', is most likely packed.
> git config --get commit.template
> git status -z -u
> git symbolic-ref --short HEAD
> git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track) refs/heads/master refs/remotes/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
Warning: Failed to watch ref '/Users/connor/Github/mopidy-azure/.git/refs/remotes/origin/master', is most likely packed.
> git config --get commit.template
```

**Comment by TylerLeonhardt** [comment]
Another question, are you all using Remote Repositories/GHPR a bit in other distributions of VS Code. Stable... Web... My other suspicion is that the SAML might have expired... but also GHPR implemented my new "reauth" API so I'm doubtful.

**Comment by TylerLeonhardt** [comment]
I was able to repro this... looks like RemoteHub works ok with GHPR:
![image](https://user-images.githubusercontent.com/2644648/127544106-f789f2a0-32fb-4bde-88e8-34ff9ab5b2bd.png)

but then if I do it with my local repo it doesn't work:
![image](https://user-images.githubusercontent.com/2644648/127544234-ce290afd-6263-4e50-9722-d142e95ce2d8.png)

**Comment by TylerLeonhardt** [comment]
Same behavior as GHPR stable extension too... suspicious...

**Comment by alexr00** [comment]
Between all the logs and screen shots I see a possible explanation.

This log line appearing twice is extremely suspicious:

```
[Info] Registering git provider
[Info] Registering git provider
```

It means that both the git extension and the Remote Repositories extension are registering as git providers in a "local" (not Remote Repository) setup. This shouldn't be happening.  Because Remote Repositories is registering, we wait for it to say that git is initialized, but it never is.

Thank you all for trying this so many times and collecting so many logs 🙏 I think I have enough to figure out how to solve this.

**Comment by baraBlz** [comment]
Please let me know how I can help. I feel like my dumbness is slowing you down so much. Is there any way we can communicate by talking?
I want to get there with you, but life is so distracting that it is really hard to remember the sequence of events I need to do.
Please, please let me help by reaching me on my phone somehow +353871717461

Domagoj ***@***.***>    Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by alexr00** [comment]
For folks who want to work around this for now you can disable RemoteHub.

**Comment by baraBlz** [comment]
No, no, workarounds. I want to help you help me. It feels really bad that you have to do all the work for me. I am just so overwhelmed with tabs due to one screen and IRL Tabs – but that is not excuse to let you do it alone. Just tell me how. What am I not seeing.

Domagoj ***@***.***>    Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by misolori** [comment]
Disabling RemoteHub fixed the issue 👏

**Comment by baraBlz** [comment]
I am not a programmer like you good folks, but I believe trying can get anything done.
Perhaps the problem was in the fact that E Mail accounts weren`t linked together in Windows mail.

**Comment by meganrogge** [comment]
yep worked for me too 👍🏼

**Comment by alexr00** [comment]
This has been fixed by https://github.com/microsoft/vscode-remote-repositories-github/issues/45 in RemoteHub, so I won't make a work around change here.
