### ISSUE TITLE
Issues window is empty

### ISSUE THREAD

**Issue by Zidras** [microsoft/vscode-pull-request-github#2861]
- Extension version: v0.28.0
- VSCode Version: 1.58.2
- OS: Win10 21H1

Steps to Reproduce:

1. Open GitHub extension
![image](https://user-images.githubusercontent.com/10605951/126916034-6bd0fb83-a024-4282-b7a6-e1908f3c8bc4.png)

should show open issues:
![image](https://user-images.githubusercontent.com/10605951/126916087-9a7ea0cb-b831-4474-b362-138c3f8bb465.png)

Additional information:
- Console did not fire any error.
- PRs load just fine.

**Comment by alexr00** [comment]
@Zidras the default queries show issues assigned to you and issues you created. Did you create any issues in that repo? Are any assigned to you?

**Comment by Zidras** [comment]
Hi Alex, all the issues are created by others and none are assigned to me. I can check at home later if assigning changes the behaviour in vsc.
It seemed strange not having a predefined issue query that would catch all the issues though, like the PRs.

**Comment by alexr00** [comment]
You can modify the queries using `"githubIssues.queries"`. The queries have been the same for over a year and I haven't noticed any other feedback where folks say that the defaults are bad, so I'm inclined toward them being pretty good defaults. 

I'll leave this issue open for a few months, and we'll see if we get any other users with the same feedback. I'm biased, I don't like the "all PRs" query that much.

**Comment by Zidras** [comment]
Confirmed: works as you described. 
IAC, I managed to create my own query using your suggestion (I had some trouble because the repo variables ${owner}/${repository} did not point to me nor my repo - because it is a fork?), so thanks.

**Comment by alexr00** [comment]
We now have a "recent issues" default query.
