### ISSUE TITLE
Test working on an issue in a different repo

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#2862]
Refs: https://github.com/microsoft/vscode-pull-request-github/issues/2820

- [x] anyOS @Tyriar
- [x] anyOS @stuartleeks (windows)

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode-pull-request-github/issues/new?body=Testing+%232862%0A%0A&assignees=alexr00)

---

There are no restrictions in the "Issues" view that require that your queries only include the repo you currently have open. For example, my queries are the following:

```json
{
	"githubIssues.queries": [
		{
			"label": "Recovery",
			"query": "assignee:alexr00 is:open repo:microsoft/vscode repo:microsoft/vscode-remote-release  repo:microsoft/vscode-pull-request-github sort:updated-desc label:candidate"
		},
		{
			"label": "Remote",
			"query": "assignee:alexr00 is:open repo:microsoft/vscode-remote-release sort:updated-desc milestone:\"July 2021\""
		},
		{
			"label": "Code",
			"query": "assignee:alexr00 is:open repo:microsoft/vscode sort:updated-desc milestone:\"July 2021\""
		},
		{
			"label": "Issues",
			"query": "assignee:alexr00 is:open repo:microsoft/vscode-pull-request-github sort:updated-desc milestone:\"July 2021\""
		},
	],
}
```

Previously, if I had Microsoft/vscode open, but wanted to start working on an issue from my "Remote" query above, I would get a modal dialog saying that there isn't a matching repo so I couldn't start working on the issue. Now, this should just work. 

Setup:
- Install the Nightly build of GitHub Pull Requests and Issues. Disable the stable build of the extension if you have it.
- Set your issues queries setting to some queries that return issues that are outside of the folder you have open.
- To start working on an issue, open the "Issues" view and use the "Start working" action on an issue.

Verify:
- That you can start working on an issue that isn't in the repo you have open when you only have one folder open.
- That you can start working on an issue that isn't in the repo you have open when you have a multiroot workspace with multiple repos. Verify that you get prompted to pick a repo.

**Comment by stuartleeks** [comment]
With `v2021.7.37984` of the Github Pull Request Nightly extension, I created this query:

```json
        {
            "label": "Devcontainer CLI (unofficial)",
            "query": "state:open repo:stuartleeks/devcontainer-cli sort:created-desc"
        },
```

And then with a folder open for a different repo I right-clicked an issue in the list from the above query and selected "Start working on item" and got this error:

![image](https://user-images.githubusercontent.com/1824461/127129894-979746b2-6b6e-47cb-a85d-3946b910d694.png)

**Comment by stuartleeks** [comment]
Temporarily set `githubIssues.assignWhenWorking` to `false` to workaround the above issue and can confirm that I am prompted to select a repo when working in a multiroot workspace

**Comment by Tyriar** [comment]
I also saw the above, I was using 2 private repos fwiw. So I couldn't really test this yet.

**Comment by alexr00** [comment]
I have released a new nightly build so this should be good to test now.

**Comment by baraBlz** [comment]
sorry guys, im all over the place. working and playing with github half
brained.
If i am stalling or preventing somebody from doing their work +353871717461
feel free to WhatsApp or ring. Im doing everything just to learn. Thats why
I kinda ignore most suggestions. Im the head through wall type of guy, hh
apologies in advance.

**Comment by stuartleeks** [comment]
Working for me on `v2021.7.37985` 😄
