### ISSUE TITLE
Duplicate issues for org-level query

### ISSUE THREAD

**Issue by stuartleeks** [microsoft/vscode-pull-request-github#2864]
- Extension version: v2021.7.36543 (nightly)
- VSCode Version: 1.59.0-insider (user setup)
- OS: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Add an org-level query, e.g.

```json
        {
            "label": "microsoft org assigned to me (all)",
            "query": "assignee:${user} org:microsoft"
        },

```
2. Check the issues panel:

![image](https://user-images.githubusercontent.com/1824461/127123700-636b789d-9ebe-49d7-948d-d875131d5fe6.png)

Note the duplicate issues displayed

**Comment by stuartleeks** [comment]
Found during testing #2862

**Comment by alexr00** [comment]
@stuartleeks do you see this every time? I'm not able to repro it.

**Comment by stuartleeks** [comment]
no - I noticed that I was no longer seeing this after getting an updated nightly build when verifying another issue for the extension!

**Comment by baraBlz** [comment]
Hey I'm home soon I'll be in touch

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by stuartleeks** [comment]
(i.e. it was consistently giving duplicates and now isn't)

**Comment by alexr00** [comment]
That makes me suspect that GitHub was returning duplicates. Closing, and we can re-open if it keeps happening.

**Comment by baraBlz** [comment]
I m almost done can't read atm

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
