### ISSUE TITLE
Error assigning issue outside of current repo

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#2865]
Testing #2862

From @stuartleeks:

With `v2021.7.37984` of the Github Pull Request Nightly extension, I created this query:

```json
        {
            "label": "Devcontainer CLI (unofficial)",
            "query": "state:open repo:stuartleeks/devcontainer-cli sort:created-desc"
        },
```

And then with a folder open for a different repo I right-clicked an issue in the list from the above query and selected "Start working on item" and got this error:

![image](https://user-images.githubusercontent.com/1824461/127129894-979746b2-6b6e-47cb-a85d-3946b910d694.png)

**Comment by stuartleeks** [comment]
Verified that I no longer get this error with nightly release `v2021.7.40864`
