### ISSUE TITLE
Add entries to the Remote Repositories Pull Request menu

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#2867]
The Remote Repositories extension has a Pull Request submenu. We should contribute a "create PR" command to this submenu.

**Comment by alexr00** [comment]
This cannot be verified until a new version of Remote Hub insiders has been released.

**Comment by rzhao271** [comment]
CC @eamodio

**Comment by eamodio** [comment]
It's been published.
