### ISSUE TITLE
Cannot create pull request

### ISSUE THREAD

**Issue by MRZMUH001** [microsoft/vscode-pull-request-github#2870]
Issue: Struggling to create a pull request. It used to work a few months back.

Extension version: v0.28.0
VSCode Version: 1.58.2 
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043 (WSL2)

Steps to Reproduce:

1. Go to branch, and click create a pull request (or go directly to create pull request view)
2. Nothing happens (empty view) with console errors.

See attached extension view, output, and console logs.

![image](https://user-images.githubusercontent.com/5204414/127452864-3c03812b-5198-45f4-8330-b28dde68c1c7.png)

**Comment by alexr00** [comment]
Is the repo you're using public? If so, can you share the branch that you're trying to create a PR from?

**Comment by MRZMUH001** [comment]
Hi @alexr00 - Unfortunately not, this is a private repo.
 
 Inspired by your comment, I just tried the following:
- on a public repo with the same user for a different organisation, and it seems to work.
- on a private repo with the same user for a different organisation, and it seems to work.
- on a private repo with the same user for the same organisation (as in the original issue), and it seems to work.

So clearly something is wrong something specific to the private repo (in question). Any guesses?

I have double-checked .git/config, and project-specific settings, nothing different from a skim around.

I had also tried below few months back which fixed it, but the problem reverted: 
```
{
    // Allow Github Pull Request to work
    "enable-proposed-api": [
        "GitHub.vscode-pull-request-github"
    ]
}
```

**Comment by alexr00** [comment]
@MRZMUH001 thanks for trying all those scenarios!

Following the link in your screenshot, here's the error: https://reactjs.org/docs/error-decoder.html/?invariant=31&args[]=object%20with%20keys%20%7B%7D&args[]=

It's pretty clearly a bug in the create PR view that we show when you try to create a PR, but I can't tell where. 

If you're willing to try it out, here's an unminified build of the extension, which should help narrow down where the issues is. It says it's version 0.28.0, but it's build off of the main branch, where all the work for 0.29.0 is. Just change the file extension to `.vsix` and drag it into the extensions view. 
[vscode-pull-request-github-0.28.0.zip](https://github.com/microsoft/vscode-pull-request-github/files/6915576/vscode-pull-request-github-0.28.0.zip)
Alternatively, if you're feeling more adventurous you could clone the repo and build it yourself :).

**Comment by MRZMUH001** [comment]
Hi @alexr00,

Thanks for above. As recommended:

```
webview-create-pr-view.js:1006 Warning: Unknown ARIA attribute `aria-describedBy`. Did you mean `aria-describedby`?
    in input (created by Root)
    in div (created by Root)
    in div (created by Root)
    in Root
```

```
Uncaught Error: Objects are not valid as a React child (found: object with keys {}). If you meant to render a collection of children, use an array instead.
    in div (created by Root)
    in div (created by Root)
    in Root
    at throwOnInvalidObjectType (webview-create-pr-view.js:14331)
    at reconcileChildFibers (webview-create-pr-view.js:15231)
    at reconcileChildren (webview-create-pr-view.js:17680)
    at updateHostComponent (webview-create-pr-view.js:18220)
    at beginWork (webview-create-pr-view.js:19545)
    at HTMLUnknownElement.callCallback (webview-create-pr-view.js:1106)
    at Object.invokeGuardedCallbackDev (webview-create-pr-view.js:1155)
    at invokeGuardedCallback (webview-create-pr-view.js:1210)
    at beginWork$1 (webview-create-pr-view.js:24121)
    at performUnitOfWork (webview-create-pr-view.js:23075)
```

```
Warning: Failed prop type: You provided a `checked` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultChecked`. Otherwise, set either `onChange` or `readOnly`.
    in input (created by Root)
    in div (created by Root)
    in div (created by Root)
    in Root
```

```
The above error occurred in the <div> component:
    in div (created by Root)
    in div (created by Root)
    in Root

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
```

```
webview-create-pr-view.js:14331 Uncaught Error: Objects are not valid as a React child (found: object with keys {}). If you meant to render a collection of children, use an array instead.
    in div (created by Root)
    in div (created by Root)
    in Root
    at throwOnInvalidObjectType (webview-create-pr-view.js:14331)
    at reconcileChildFibers (webview-create-pr-view.js:15231)
    at reconcileChildren (webview-create-pr-view.js:17680)
    at updateHostComponent (webview-create-pr-view.js:18220)
    at beginWork (webview-create-pr-view.js:19545)
    at HTMLUnknownElement.callCallback (webview-create-pr-view.js:1106)
    at Object.invokeGuardedCallbackDev (webview-create-pr-view.js:1155)
    at invokeGuardedCallback (webview-create-pr-view.js:1210)
    at beginWork$1 (webview-create-pr-view.js:24121)
    at performUnitOfWork (webview-create-pr-view.js:23075)
```
    
Hope this helps!

**Comment by alexr00** [comment]
Thanks @MRZMUH001 that gave me a bit more info. I have a change that I will merge next week. Once the change is available in the marketplace I'll add a comment here to let you know it's available.

**Comment by MRZMUH001** [comment]
That was quick! Thank you for helping out and resolving it soon.

**Comment by MRZMUH001** [comment]
Hi @alexr00 , any news on the release of https://github.com/microsoft/vscode-pull-request-github/pull/2877?

**Comment by alexr00** [comment]
@MRZMUH001 thanks for checking in! You can download the nightly build of the extension if you want to try out the fix now. I just added a new FAQ for this too too: https://github.com/microsoft/vscode-pull-request-github/wiki#4-when-will-the-next-release-occur

**Comment by alexr00** [comment]
No one else has been able to reproduce this, but @MRZMUH001 took a look at the PR. I'm going to call this verified by code review.
