### ISSUE TITLE
Create request suggests wrong branch

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode-pull-request-github#2871]
Testing #2867

On Remotehub:

1. Switch to a new branch and add a commit
2. Run the create a PR command
3. Close the PR viewlet
4. Run the create a PR command again
5. 🐛 The wrong "merge changes from" branch is suggested after a while

Creating a separate issue rather than marking original issue as verification-found, because this seems a bit more like an edge case.

![Screencap](https://user-images.githubusercontent.com/7199958/127562087-b43a59ac-eb0d-4983-9833-e8d111c972ab.gif)

**Comment by stuartleeks** [comment]
Tested GHPR extension nightly build `v2021.7.42360`

```
Version: 1.59.0-insider (user setup)
Commit: 0f22f2d343e33b03e8033d1083513072f58ece21
Date: 2021-07-29T05:13:10.735Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19043
```

There's a very brief flicker onto the wrong branch, but it then reverts back to the correct one.  

![test2871](https://user-images.githubusercontent.com/1824461/127654810-b3906716-df47-4858-9709-75d116e28a1a.gif)
