### ISSUE TITLE
Permalink commands don't support GitHub Enterprise

### ISSUE THREAD

**Issue by kamaln7** [microsoft/vscode-pull-request-github#2872]
Hello!

First off I'm really excited to see that this extension has brought back support for GHE 🎉

I noticed that the permalink commands generate `github.com` URLs even if within a GHE context.

- Extension version: 0.28.0
- VSCode Version: 1.58.2
- OS: Linux x64 5.4.99

There are many hardcoded references to `github.com` in [src/issues/util.ts](https://github.com/microsoft/vscode-pull-request-github/blob/ef2f9f9a03b2fc42335b9b6af91121bc243f040a/src/issues/util.ts#L427) but it seems like this issue is coming from `createGithubPermalink`:

https://github.com/microsoft/vscode-pull-request-github/blob/ef2f9f9a03b2fc42335b9b6af91121bc243f040a/src/issues/util.ts#L494

Steps to Reproduce:

Assuming the GitHub Enterprise integration is set up properly (per [these instructions](https://github.com/microsoft/vscode/pull/115940#issuecomment-838838680)).

1. Open a workspace that uses a repo with a GitHub Enterprise remote
2. Run the `GitHub Issues: Copy GitHub Permalink` command
3. The generated URL references `https://github.com/` instead of the GHE server's endpoint.

**Comment by alexr00** [comment]
This has since been fixed!
