### ISSUE TITLE
Diff from fork point state to current file state

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode-pull-request-github#288]
Testing Microsoft/vscode#57301

I've been wanting to file this one for a few days already. I would prefer if, once I checked out a PR, that the "Changes in Pull Request view" would open on the left hand side the fork point (as it does today) and on the right hand side the file, as it is on disk.

Today, the Changes in PR view opens on the right hand-side a read-only file where I cannot edit and it is super annoying, I need to press a button to get to the file if I want to remove like a newline. Once I remove a newline, the Git viewlet shows me the diff of removing the line, but I want to see the final diff of the PR i.e. (fork point <-> current file state).

I know this is quite a change, but IMHO that would make it a lot more useful for me... I always think of a PR in terms of fork point <-> final PR state and I want the diffs to be as small as possible...

**Comment by rebornix** [comment]
We can make this closer to the Git SCM experience and leverage the `git` schemes.

* For the left side, use the content from the file of that specific commit, and we can re-use the `git` scheme https://github.com/microsoft/vscode/blob/master/extensions/git/src/commands.ts#L240-L277
* For the right side, use the `file` scheme and then we can see the latest content of the file on the local disk

@joaomoreno do you think it's a good idea to depend on how Git extension generates the document Uri?

**Comment by joaomoreno** [comment]
@rebornix Absolutely. I'm even considering making it git extension API: https://github.com/Microsoft/vscode/issues/55110

**Comment by RMacfarlane** [comment]
Completed with https://github.com/Microsoft/vscode-pull-request-github/pull/828

**Comment by alexandrudima** [comment]
This is great! Thank you!
