### ISSUE TITLE
Lost github icon in activity bar

### ISSUE THREAD

**Issue by Yajo** [microsoft/vscode-pull-request-github#2880]
Issue Type: <b>Bug</b>

At some point I was rearranging the panels, and I lost the github octocat icon. Instead, it became a "pull request" icon, which is not that different from the VCS panel icon and it gets confusing.

Is there any way to restore the original panel layout/icon?

Extension version: 0.28.0
VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:30:16.440Z)
OS version: Linux x64 5.13.6-200.fc34.x86_64
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.46GB (0.80GB free)|
|Process Argv|--unity-launch --crash-reporter-id 1b07b1f6-f187-42fc-aa9e-516fd1a4c83e|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
vstre464cf:30346473

```

</details>

**Comment by Yajo** [comment]
This is how that icon looks now 😞 

![imagen](https://user-images.githubusercontent.com/973709/128148780-edb82752-3a8c-43ac-b535-0e058522688e.png)

**Comment by alexr00** [comment]
To reset views to their original state you can open the command palette and run the command View: Reset View Locations. Note that this will reset all your view locations but it's the only way to get everything back.
