### ISSUE TITLE
When creating a PR from the pop-up after pushing a new branch it should not ask about repo

### ISSUE THREAD

**Issue by Hades32** [microsoft/vscode-pull-request-github#2882]
Issue Type: <b>Bug</b>

I have a workspace with ~20 repos. When I push a fresh branch to one of them I get asked if I want to create a PR - I click yes - and then I get asked which repo/project this new PR is about...
Clearly the extensions should know this information, as the popup had the context.

Extension version: 0.28.0
VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.10.43.3-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.75GB (5.48GB free)|
|Process Argv|--folder-uri vscode-remote://wsl%2Bubuntu/home/mj/dev/product-os/product-os --crash-reporter-id 03d1d847-7d95-4a8b-9acf-a6c2e77c0f20|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.43.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz (16 x 2304)|
|Memory (System)|15.51GB (4.13GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490
vstre464:30346472

```

</details>

**Comment by alexr00** [comment]
@Hades32 can you share a screen shot of "and then I get asked which repo/project this new PR is about..."?

**Comment by Hades32** [comment]
Sure @alexr00 
![image](https://user-images.githubusercontent.com/167847/129007869-91fc7239-7a76-455d-9f75-01aaadc3279b.png)

**Comment by Hades32** [comment]
Awesome! That was fast! Thank you @alexr00 😊

**Comment by alexr00** [comment]
If you want, you can try out the change using the latest [nightly build](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github-insiders) of the extension. If you do try it out, it would be helpful if you could comment here saying whether the issue is fixed for you!

**Comment by Hades32** [comment]
Everything working as expected with GitHub Pull Request Nightly Build
v2021.8.16387

Am Do., 12. Aug. 2021 um 11:22 Uhr schrieb Alex Ross <
***@***.***>:

**Comment by alexr00** [comment]
Thank you for verifying!
