### ISSUE TITLE
Creating a PR when working on issue does not link 

### ISSUE THREAD

**Issue by silveiralsv** [microsoft/vscode-pull-request-github#2888]
- Extension version: v0.29.0
- VSCode Version: 1.59.0
- OS: Linux x64 5.11.0-25-generic snap

Steps to Reproduce:

1. create an Issue, and starting work on it
2. create a PR from working issue

**Comment by alexr00** [comment]
duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/2676
