### ISSUE TITLE
Changing GitHub Personal Access Token 

### ISSUE THREAD

**Issue by wifinigel** [microsoft/vscode-pull-request-github#2889]
When I started using the plugin, the personal access token I assigned did not have correct privileges.  This was reported by the plugin when I tried to perform any actions with the plugin such as accessing PRs. The error messages did not report any way to ix the credential issue and I could not find any fields in the plugin settings to set or update the PAT.

My fix was to remove and re-install the plugin to get prompted for my GitHub credentials. When my credentials expire in a few weeks, I'm not sure how I can avoid another remove/re-install cycle - a plugin option to do this would be great. 

Thanks for this super useful plugin! :)

- Extension version:
- VSCode Version: v0.28.0
- OS: Windows

Steps to Reproduce:

1. Create PAT with basic repo-only access permissions
2. Install plugin and use that token as your credential
3. Try to perform any operations and view errors messages about lack of access to read email settings etc.

**Comment by alexr00** [comment]
You should be able to logout using the account icon

![image](https://user-images.githubusercontent.com/38270282/129006837-41fef900-da00-41c3-843c-856e94e70d07.png)
