### ISSUE TITLE
Description field is too wide

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-pull-request-github#289]
https://github.com/Microsoft/vscode/issues/57301

https://baymard.com/blog/line-length-readability suggests the optimal reading width is 50-75 characters, right now the description page is around 160:

<img width="1068" alt="screen shot 2018-08-28 at 10 57 14 am" src="https://user-images.githubusercontent.com/2193314/44741157-24e94200-aab1-11e8-9163-6b62ebdf3d95.png">

It's a far more pleasant experience reading it on GitHub:

<img width="845" alt="screen shot 2018-08-28 at 10 57 58 am" src="https://user-images.githubusercontent.com/2193314/44741210-46e2c480-aab1-11e8-8097-67c072189d64.png">

We should bump the font size and make the wrapping div around 20-30% more narrow imo

**Comment by RMacfarlane** [comment]
As part of https://github.com/Microsoft/vscode-pull-request-github/pull/951, the content on the description page now has a max width of 900px which should more closely match GitHub
