### ISSUE TITLE
GHPRI: Iteration Plan for August 2021

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-pull-request-github#2890]
This plan captures our work in **August**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/130368). Although we plan for a whole iteration, we may not only ship at the end of an iteration but throughout.

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

### Fundamentals
- [ ] :runner: Issues [query](https://github.com/microsoft/vscode-pull-request-github/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22August+2021%22) @alexr00

### Features
- [x] Support to collapse all comments [vscode-pull-request-github#665](https://github.com/microsoft/vscode-pull-request-github/issues/665) @alexr00

### Deferred
- [ ] Investigate performance issues/improvements for branch PR detection [vscode-pull-request-github#2487](https://github.com/microsoft/vscode-pull-request-github/issues/2487) @eamodio

**Comment by Donna3344** [comment]
Awesome

**Comment by Donna3344** [comment]
Too crazy
