### ISSUE TITLE
Remotes with multiple push urls are not detected

### ISSUE THREAD

**Issue by gaelhameon** [microsoft/vscode-pull-request-github#2891]
Issue Type: <b>Bug</b>

I have a repo with the following remotes:
```
github  https://github.com/gaelhameon/ookpik-apollo.git (fetch)
github  https://github.com/gaelhameon/ookpik-apollo.git (push)
github  file:///C:\Users\gaelh\OneDrive - SNCF\git-repositories\ookpik-apollo (push)
onedrive        file:///C:\Users\gaelh\OneDrive - SNCF\git-repositories\ookpik-apollo.git (fetch)
onedrive        file:///C:\Users\gaelh\OneDrive - SNCF\git-repositories\ookpik-apollo.git (push)
```

And here are my settings:
```
    "githubPullRequests.remotes": [
        "origin",
        "upstream",
        "github"
    ],
```
 
My github remote should be recognized, but the extension says that "No remotes match the current settings".

If I change my repo's remote to get this:
```
github  https://github.com/gaelhameon/ookpik-apollo.git (fetch)
github  https://github.com/gaelhameon/ookpik-apollo.git (push)
onedrive        file:///C:\Users\gaelh\OneDrive - SNCF\git-repositories\ookpik-apollo.git (fetch)
onedrive        file:///C:\Users\gaelh\OneDrive - SNCF\git-repositories\ookpik-apollo.git (push)
```

Then the extension works fine.

But I'm sad, because now I have to do two commands to push to both urls :-(

Would it be possible to support this case ?

Extension version: 0.29.0
VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.82GB (1.32GB free)|
|Process Argv|--crash-reporter-id 3b8c121b-da03-4aa8-b03c-49f926fb37c8|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
vstre464cf:30346473

```

</details>

**Comment by alexr00** [comment]
We should be able to ignore the second push url.

**Comment by gaelhameon** [comment]
@JacksonKearl  it's not really solved for me. 

Here is with v0.29.2
![image](https://user-images.githubusercontent.com/17253950/131235682-539686ea-24a8-4b4f-9524-e47a41b1c48f.png)

I have a workspace with 3 repos. And you can see that with the config I have above, it works only for the "ookpik-apollo" repo, which is the only one that has a "github-for-pr" remote that has only one push url.
This image gives the impression that it works for the other repos, but it doesn't: I have pull requests open in all 3 repos and it doesn't find them.
![image](https://user-images.githubusercontent.com/17253950/131235830-54047c84-f95c-4e19-b123-864f095fe6eb.png)


If I remove "github-for-pr" from my config, I get this:
![image](https://user-images.githubusercontent.com/17253950/131235723-a8d75e84-cee6-4a4b-8d41-51bdaad0e85a.png)

On this one, it's event clearer that it doesn't work.

I also tried with the nightly build and it gets weird:
![image](https://user-images.githubusercontent.com/17253950/131235810-c984b9a4-df57-4bb0-ab1c-e6fceefb2279.png)

It works for the "lauritz" repo, which is good, but doesn't work for the other 2.

For "private", maybe it's because my fetch is in SSH and my push in https. I'll try to change that next.
For "apollo", there are two differences with "lauritz":
- an additional remote that uses the same url as the "github" remote
- the fact that the github push url is listed before the onedrive url

One more test: when I reintroduce the "githup-for-pr" remote in the config, I get the pr for the apollo repo

![image](https://user-images.githubusercontent.com/17253950/131235886-1e6e0e22-cad9-48ec-9635-260f077b6f5b.png)

**Comment by gaelhameon** [comment]
The order in which the remotes are listed seems to matter.

I did this: 
```
git remote add github git@github.com:gaelhameon/ookpik-private.git 
```
And saw my pr appear after this step.
Then 
```
git remote set-url --add github "file:///C:\Users\gaelh\OneDrive - SNCF\git-repositories\ookpik-private"
```
made it disappear

Then 
```
git remote set-url --add github git@github.com:gaelhameon/ookpik-private.git
```
gives me this situation
```
github  git@github.com:gaelhameon/ookpik-private.git (fetch)
github  git@github.com:gaelhameon/ookpik-private.git (push)
github  file:///C:\Users\gaelh\OneDrive - SNCF\git-repositories\ookpik-private (push)
github  git@github.com:gaelhameon/ookpik-private.git (push)
onedrive        file:///C:\Users\gaelh\OneDrive - SNCF\git-repositories\ookpik-private (fetch)
onedrive        file:///C:\Users\gaelh\OneDrive - SNCF\git-repositories\ookpik-private (push)
```

and now my PR appears

**Comment by alexr00** [comment]
Looks like this is an upstream issue: https://github.com/microsoft/vscode/issues/133727
