### ISSUE TITLE
Add caching for mentionable users

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#2897]
See discussion in https://github.com/microsoft/vscode-pull-request-github/issues/2892

**Comment by alexr00** [comment]
The new caching works as follows:

1. Mentionable users are only preloaded from GitHub when a PR branch is checked out and they have not been fetched from GitHub in the last 30 days. 
2. If mentionable users for a repository have been fetched before, then they will not be preloaded from GitHub and will instead be restored from a local cache.
3. When a user triggers an `@` completion in a PR comment for the first time in a session, the cached mentionable users will be refreshed from GitHub in the background and the existing cache will be shown the user.
4. The cache for a repository is wiped after 30 days.
5. The cache is not synced between "platforms" (desktop/codespaces web/other browsers/other computers/etc.) as the amount of data to sync is too much. 


cc @mislav since you were interested in this

**Comment by mislav** [comment]
This is fantastic. Thanks for the clever solution and summarizing it here!
