### ISSUE TITLE
github.dev Copy as Permalink doesn't put anything on clipboard

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode-pull-request-github#2903]
Open a repo: https://github.dev/microsoft/vscode
Right click on a file in the explorer, choose `Copy GitHub Permalink`
Try to paste the link ...

Result: Nothing on clipboard

**Comment by alexr00** [comment]
I'm seeing this error: "Could not resolve external URI: vscode-vfs://github/microsoft/vscode/CONTRIBUTING.md"

There's a secondary issue where there's an extra `"github"` getting added to the path too.

**Comment by alexr00** [comment]
The "Could not resolve" error is occurring because github.dev doesn't currently support the extension API `asExternalUri`. Until that's supported, we can just catch the error and not provide a contextualized permalink for github.dev.

**Comment by alexr00** [comment]
To verify:

1. Open a repo: https://github.dev/microsoft/vscode
2. Go to built in extensions and disable GitHub Pull Requests and Issues
3. Install the extension GitHub Pull Requests Nightly
4. Reload
5. Right click on a file in the explorer, choose Copy GitHub Permalink
6. Paste the link somewhere and verify it is a valid github.com link (yes, it should be github.dev, but there is a fix needed on their side for that).

**Comment by hediet** [comment]
> Go to built in extensions and disable GitHub Pull Requests and Issues

GitHub Pull Requests does not seem to be built in ;)

> Paste the link somewhere and verify it is a valid github.com link

That is the link:

https://github.com/microsoft/vscode/blob/7ec64f0dad5dbf5fbc4fe2b1f9383844c29095b7/src/vs/editor/contrib/inlineCompletions/ghostTextController.ts

**Comment by hediet** [comment]
Now I'm getting this:

![image](https://user-images.githubusercontent.com/2931520/129343452-842b8b1e-21c1-4de0-b20c-0abc7ed4d370.png)

**Comment by hediet** [comment]
I can verify, it did not work before, but in nightly, it works.

Also, github.dev has this extension built-in. I misread the github.dev link.
