### ISSUE TITLE
`remoteHub/pullRequest` is not a valid menu identifier

### ISSUE THREAD

**Issue by kathenas** [microsoft/vscode-pull-request-github#2908]
Issue Type: <b>Bug</b>

Activation time (Startup) : 14ms
Messages (1)
`remoteHub/pullRequest` is not a valid menu identifier

Extension version: 0.29.2
VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:20.182Z)
OS version: Linux x64 4.18.0-305.12.1.el8_4.x86_64
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 3307)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|30.92GB (21.21GB free)|
|Process Argv|--unity-launch --crash-reporter-id d4183a8a-8990-4b53-ba92-9008841a16d1|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome-xorg|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome-xorg|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by spindensity** [comment]
The same problem here.

**Comment by RishabhKothaari** [comment]
This is not a bug. The extension tries to contribute to [GitHub Repositories](https://marketplace.visualstudio.com/items?itemName=GitHub.remotehub) extension which might be not installed as a result you get this warning. You can suppress the warnings or install Remotehub.

**Comment by kathenas** [comment]
> This is not a bug. The extension tries to contribute to [GitHub Repositories](https://marketplace.visualstudio.com/items?itemName=GitHub.remotehub) extension which might be not installed as a result you get this warning. You can suppress the warnings or install Remotehub.

Ah... I have installed the extension named and all good. Thanks.

**Comment by ches** [comment]
Perhaps that spurious warning could be avoided if the GitHub Repositories extension would [set a context key](https://github.com/microsoft/vscode/issues/132539) that the Pull Requests extension's menu contribution could check in a `when` clause.

Maybe that would have a race condition on extension load order though. I dunno, I'm not familiar with VS Code extension development, but this seems like something that is likely to be a solved problem.

**Comment by ches** [comment]
Ah, as per https://github.com/microsoft/vscode-pull-request-github/issues/3073#issuecomment-956286288 it is perhaps not a solved problem: microsoft/vscode#136222
