### ISSUE TITLE
Description code blocks aren't rendered with a monospace font

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-pull-request-github#291]
https://github.com/Microsoft/vscode/issues/57301

<img width="541" alt="screen shot 2018-08-28 at 11 00 42 am" src="https://user-images.githubusercontent.com/2193314/44741358-a80a9800-aab1-11e8-8fae-7dc8106311dc.png">

**Comment by unimatrixZxero** [comment]
Would appreciate a fix for this 🙏
