### ISSUE TITLE
Collapse comments on startup

### ISSUE THREAD

**Issue by Mystic8b** [microsoft/vscode-pull-request-github#2912]
Hello. I could not find in the settings how to make the comments collapse when opening the project. It upsets me very much that I have to fold them manually every time.
![image](https://user-images.githubusercontent.com/35394377/129710807-2d3f14b4-5d91-4b86-8667-37b26aa045db.png)

**Comment by alexr00** [comment]
duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/665
