### ISSUE TITLE
Old image version is not shown when viewing a pull request change for an image

### ISSUE THREAD

**Issue by Artur-** [microsoft/vscode-pull-request-github#2914]
- Extension version: v0.29.2
- VSCode Version: 1.59.0
- OS: GitHub editor

Steps to Reproduce:

1. Open https://github.dev/Artur-/screenshot-public/pull/1
2. Click "image.png"

Expected outcome:
The image currently in the repository is shown on the left side, the image included in the PR is shown on the right side

Actual outcome:
The left side always shows "An error occurred while loading the image". The right side correctly shows the image in the PR

**Comment by alexr00** [comment]
Thanks for filing this! Looks like it's an upstream issue: https://github.com/microsoft/vscode/issues/131079

**Comment by alexr00** [comment]
The VS Code regression is not going to be fixed anytime soon. I have added a temporary storage for images that gets wiped on extension activation which improves the situation for now: https://github.com/microsoft/vscode-pull-request-github/pull/2925

**Comment by alexr00** [comment]
That is as-designed for now. Thanks for verifying!
