### ISSUE TITLE
Lowercase branch names

### ISSUE THREAD

**Issue by ramiel** [microsoft/vscode-pull-request-github#2935]
I'd like to have branch name totally lowercase. This way it would be more friendly on cli tools.

**Comment by ramiel** [comment]
Sorry, I should have been more clear. When a branch is created form an issue, the `Github Issues: Issue Branch Title` setting is used to determine the branch name. I noticed that `${sanitizedIssueTitle}` produces uppercase letters, but I'd like to have an option to have only lowercase characters

**Comment by ramiel** [comment]
I also noticed someone proposed a PR with the very same goal: https://github.com/microsoft/vscode-pull-request-github/pull/2364

**Comment by alexr00** [comment]
I find the branch name hard to read if the issue title is uses with only lowercase. Instead of always using lowercase, I propose we have a new variable `${sanitiazedLowercaseIssueTitle}`. It's a bit verbose, so other name suggestions are welcome!

**Comment by ramiel** [comment]
This sounds good

**Comment by alexr00** [comment]
@burkeholland, another one for you if you're interested.

**Comment by alexr00** [comment]
To verify:
1. Open a folder with a GitHub repo.
2. Make sure you have the nightly build of this extension installed and the stable version disabled/uninstalled.
3. Open the Issues view. If you don't have any issues in the view, you will need to modify the queries in settings to get some to show.
4. Set this setting: `"githubIssues.issueBranchTitle": "${sanitizedLowercaseIssueTitle}"`
5. "Start working" on one of the issues (inline command on an issue or context menu).
6. Verify that a new branch is created and checked out and that the name of the branch is the issue title with all letters lowercased and illegal characters removed. Removal of illegal characters has already been tested, so no need to thoroughly test that part if you don't want to.
