### ISSUE TITLE
Hiding of all comments behaves strange when one PR is checked out and one not

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode-pull-request-github#2936]
Testing #2931

See screen cast

![cast](https://user-images.githubusercontent.com/1931590/130618085-9dabeff7-c15d-4999-844f-a9387efd02d1.gif)

**Comment by dbaeumer** [comment]
Observe that pressing the toggle button doesn't toggle the comment I am clicking in. This is different when only one PR is open.

**Comment by alexr00** [comment]
This would have been caused by registering too many comment controllers. With 62ad77ddfa1bc561d2248ef0d33a96cb3e8554d5, the last place this could happen has been removed.
