### ISSUE TITLE
Pull request editors not restored

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode-pull-request-github#2938]
Testing #2931

- Open to pull request file editors (the once showing comments) side by side
- reload the window
- you get

<img width="1342" alt="capture" src="https://user-images.githubusercontent.com/1931590/130619095-699838dd-21f7-4f05-8e16-b741caee0414.png">

I expected the editors to be restored.

**Comment by joyceerhl** [comment]
I don't get put back into focused PR view after a reload, is that expected?
