### ISSUE TITLE
No githubPullRequests.commentExpandState setting

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode-pull-request-github#2939]
Testing #2931

<img width="468" alt="capture" src="https://user-images.githubusercontent.com/1931590/130619584-4cc67e73-091d-4296-9794-e23e187f499d.png">

Above screen shot is from workspace setting file.

**Comment by alexr00** [comment]
I made it a user only setting since there are also buttons in the UI that change it. However, I was modelling after the Auto Save feature, and that is not a user only setting. I will update it to allow it to be set in the workspace too.
