### ISSUE TITLE
I would not have expected that toggle the comment state will change the setting file

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode-pull-request-github#2940]
Testing #2931

- collapse all comments
- observe: the user setting for `githubPullRequests.commentExpandState` changes to `collapseAll`

**Comment by dbaeumer** [comment]
IMO the button should behave more like expand / collapse all in the explorer than auto save. I would have never expected that pressing the button changes a setting and makes this 'survive' a reload. IMO the setting should be used when we open VS Code but then for example collapsing all should not be remembered. But this is my take.

**Comment by alexr00** [comment]
I can see how it would be confusing. I will update it to not write the setting.

**Comment by alexr00** [comment]
I've been thinking about this some more, and I'm again leaning towards keeping the current behavior where the setting is changed. We persist UI state across reloads in many places (open editors, collapsed views, panel state, etc.), and this is just another UI state that will be persisted.

**Comment by dbaeumer** [comment]
I am not arguing against persisting the UI state across reloads but to my knowledge the UI state is persisted per workspace. This setting is a user setting and might be synced to even other machines. So clicking a minus button in the UI has a far higher impact than I would have expected.

**Comment by alexr00** [comment]
Here's what I landed on:
- The Toggle command has been removed in favor of a Collapse command and an Expand command
- The setting is no longer changed when you run the Expand/Collapse commands or the use the action on the comment widget.
- The action on the comment widget is always "Collapse All Comments".
