### ISSUE TITLE
insufficient permissio for adding an object to repository database .git/objects

### ISSUE THREAD

**Issue by mtyeager** [microsoft/vscode-pull-request-github#2942]
- Extension version: .26
- VSCode Version: 1.56.2
- OS: Debian 10 Buster

Steps to Reproduce:

1. Click on Commit in the project
2.Get error message insufficient permissions for adding an object to repository database .git/objects
Have checked all the files, all have the correct user and group assigned
Have been using git from vscode for months now from the terminal in vscode without issue, same file permissions
With authentication change on GitHub requiring a personal access token I decided to install the GitHub Pull Requests and Issues extension and see if that would automate the personal access token process
Have looked through numerous online discussions regarding this error, but all old, and not regarding this extension
But funny work around. I can add and commit using terminal, and then push using the extension.

**Comment by mtyeager** [comment]
The work around mentioned above worked only once. Not sure why it worked at all. I have gone back to using terminal with personal access token.

**Comment by alexr00** [comment]
@mtyeager can you share a screenshot of where you "click on commit in the project"?
