### ISSUE TITLE
Toggle comment expansion does not toggle when comment has just been manually opened and closed

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-pull-request-github#2943]
Testing #2931

Repro Steps:
1. From a comment close it using the - UI button on the comment
2. From the editor gutter expand the comment back out
3. Use the Toggle Comment Expansion command

Expected: Command toggles to hidden
Actual: Nothing happens

Gif below.
![ToggleComment](https://user-images.githubusercontent.com/812783/130658313-e655a108-ff77-41a1-86a1-0ed7fbd1d158.gif)

Note: After the first command run, it will then toggle correctly on the second run of the command.

**Comment by IanMatthewHuff** [comment]
Looking more closely now I believe that this behavior is intentional. But leaving the bug open just to mention that I think that the UI paradigm is a bit confusing. I would just say that the space on the top of the toolbar feels very "comment specific" so controlling a global setting from that location felt very odd to me kinda per #2940 . I get now that it's just swapping the setting, but I honestly didn't notice the + / - change on the icon so my GIF above felt wrong. Especially as I would consider that a Toggle command would always do something. Having a command "Expand All PR Comments" and another command "Collapse All PR Comments" would match the behavior more to me.

**Comment by alexr00** [comment]
👍 two commands makes sense, I will add that.

**Comment by alexr00** [comment]
Here's what I landed on:
- The Toggle command has been removed in favor of a Collapse command and an Expand command
- The setting is no longer changed when you run the Expand/Collapse commands or the use the action on the comment widget.
- The action on the comment widget is always "Collapse All Comments".
