### ISSUE TITLE
Should comment collapsing/expansion be an editor action?

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-pull-request-github#2945]
Testing #2931

It feels weird that clicking expand/collapse on a single comments' actions causes the state of other comments to change. It would make more sense to be if the collapse/expand button was an editor action instead. cc @misolori

**Comment by alexr00** [comment]
Making the expand/collapse action an editor action was one of the original proposals. My concern with making it an editor action is discoverability. I want the action to be close to comments so that comments users can find it easily.
