### ISSUE TITLE
Are there options for theme authors to theme the PR description?

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#295]
https://github.com/Microsoft/vscode/issues/57301

It's not clear where this grey is coming from which looks very out of place in my theme:

<img width="427" alt="screen shot 2018-08-28 at 11 08 26 am" src="https://user-images.githubusercontent.com/2193314/44741694-b4dbbb80-aab2-11e8-8459-0cbce4965751.png">
<img width="80" alt="screen shot 2018-08-28 at 11 08 29 am" src="https://user-images.githubusercontent.com/2193314/44741696-b60ce880-aab2-11e8-8ea7-2215a8b74a1c.png">

Can this be documented if we can theme?

**Comment by ahmadawais** [comment]
I came here to create a similar thread. @Tyriar is always ahead 🙌🤣

Anywho, as a [theme (SOP)](https://marketplace.visualstudio.com/items?itemName=ahmadawais.shades-of-purple) author I'd love to be able to style several elements of the interface.

## [ ] GitHub PR Status 

Normally the button styles are picked up from the theme but the PR Status is badge/shield is all messed up. GIF ↓

![image](https://on.ahmda.ws/7b99b647f77b/c)
![image](https://on.ahmda.ws/7f860f55ce96/c)

## [ ] DP Missing + No Syntax Highlighting

The display image and syntax highlighting are missing in places — not sure if a theme should control these but my 🦄Shades of Purple VSCode theme handles styling of different languages inside the markdown very well. That'd be good too (Happy to recreate a separate issue for this)

Peace! ✌️

**Comment by misolori** [comment]
@ahmadawais for the status text color see #399
