### ISSUE TITLE
Tick SVG doesn't look right

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#2950]
![image](https://user-images.githubusercontent.com/2193314/130789802-ef9d16c5-d269-44cf-a522-57eb56abcf60.png)

Using the actual SVG from github.com looks nicer:

![image](https://user-images.githubusercontent.com/2193314/130790291-aabcf645-6508-49be-88f8-29eda7e7715b.png)

cc @misolori 

Ext: v2021.8.35110

**Comment by Tyriar** [comment]
It also doesn't align with the codicon:

![image](https://user-images.githubusercontent.com/2193314/130793198-2f90e4df-3abb-4c8c-bee9-c458e50c61c5.png)

**Comment by alexr00** [comment]
@burkeholland FYI in case you want to take this one.

**Comment by Tyriar** [comment]
Can fix that in https://github.com/microsoft/vscode-pull-request-github/issues/2951
