### ISSUE TITLE
Pending check circle should be horizontally aligned with no conflicts tick

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#2951]
Current:

![image](https://user-images.githubusercontent.com/2193314/130790463-96fbcade-a6bd-4e4d-9878-2e4ff242d1f6.png)

Proposed:

![image](https://user-images.githubusercontent.com/2193314/130790527-d10b3ec9-c859-45ab-83c0-16bb8d69f535.png)

Ext: v2021.8.35110

**Comment by alexr00** [comment]
@burkeholland FYI in case you want to take this one.

**Comment by burkeholland** [comment]
Modified the dot to match the official octicon "dot-16" which is horizontally aligned. Now the dots are not vertically aligned in details...

![image](https://user-images.githubusercontent.com/686963/131365932-d9e56bfb-fee1-4cc8-8965-ffabafbab82f.png)

Maybe we already have an issue opened. If not, I'll open one.

**Comment by burkeholland** [comment]
Moved fix to #2971
