### ISSUE TITLE
PR created x minutes ago is cut off in small tabs

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#2952]
![image](https://user-images.githubusercontent.com/2193314/130790692-11186a45-2102-47ad-ba29-dc28069d6d20.png)

Ext: v2021.8.35110

**Comment by alexr00** [comment]
Thanks for all the great issues @Tyriar!

@burkeholland FYI in case you want to take this one.

**Comment by connor4312** [comment]
This is better, I think there's still some opportunity for improvement at very small sizes though (around 400px)
