### ISSUE TITLE
Focus border is used on assignees when it's not focused

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#2956]
I thought this was focused:

![image](https://user-images.githubusercontent.com/2193314/130791639-bbe95df0-6900-4572-a4c3-52b9f56b868f.png)

This results in this weird state:

![image](https://user-images.githubusercontent.com/2193314/130791725-34072d3e-5de3-42c4-b3cc-9593a1b0e9ce.png)

Normally this doesn't show in the UI as focused can only be on one item, for example:

![image](https://user-images.githubusercontent.com/2193314/130791838-5935f17b-5c21-4502-a6c4-207c893bbb84.png)

Ext: v2021.8.35110

**Comment by alexr00** [comment]
@burkeholland FYI in case you want to take this one.
