### ISSUE TITLE
Unable to install extension on Linux system

### ISSUE THREAD

**Issue by rohit04saluja** [microsoft/vscode-pull-request-github#2981]
- Extension version: v0.30.0
- VSCode Version: 1.59.1
- OS: RHEL 7.9

Steps: Install extension from VSCode Extensions View.

Following error is seen:
`Unable to install extension 'github.vscode-pull-request-github' as it is not compatible with VS Code '1.59.1'`

**Comment by alexr00** [comment]
@rohit04saluja sorry for the difficulty! This should now be resolved as we have released version 1.60 of VS Code.
