### ISSUE TITLE
Is it possible to have the old view ?

### ISSUE THREAD

**Issue by ExtremeGTX** [microsoft/vscode-pull-request-github#2983]
As you can see in the screenshot (from introduction video) below 
<img width="1552" alt="github_pr_overview 1" src="https://user-images.githubusercontent.com/6371120/131918178-a826da7e-9127-471e-babe-0f7004f1d8a8.png">

The changes done in the PR is in a different panel "CHANGES IN PULL REQUEST" from the other one which lists all PRs "GITHUB PULL REQUESTS".

I tried to get this on VSCode v1.59.1 but couldn't able to find a way to do it.

**Comment by alexr00** [comment]
@ExtremeGTX I'm not 100% sure which of these you're asking for, so here's both of them:

If you want to put the "Changes in Pull Request" view in it's own view container so it doesn't share with the "Pull Requests" view:
1. Run the command "View: Reset View Locations". **Note** that this will reset _all_ your view locations, so you'll have to move views around again to put them where you want them.

If you want to move the "Changes in Pull Request" view into the same view container as "Pull Requests" view:
1. You can click and drag on the view title to drag into the view container you want.

**Comment by ExtremeGTX** [comment]
I tried the suggested solutions but didn't work, please check the screenshot below for a better explanation.
![2021_09_04_00_16_47_gui_runner c_mgba_Visual_Studio_Code](https://user-images.githubusercontent.com/6371120/132070748-f3f86c2b-fc06-4c15-86f7-621d8e79a403.jpg)

**Comment by alexr00** [comment]
If you want to move the "Changes in Pull Request" view into the same view container as "Pull Requests" view, you can click and drag on the view title to drag into the view container you want.
