### ISSUE TITLE
Review> current branch pr/xxxxx/12345 hasn't setup remote yet

### ISSUE THREAD

**Issue by diablodale** [microsoft/vscode-pull-request-github#2984]
Attempts to checkout a PR so I can compile and validate it fail. The files are not checked out. And the output window for "github pull request" reports...

```
...
[Info] Review> current branch pr/xxxxx/12345 hasn't setup remote yet
...
[Info] Review> current branch pr/xxxxx/12345 hasn't setup remote yet
...
[Info] Review> current branch pr/xxxxx/12345 hasn't setup remote yet
...
```

I suspect this is related to an incompatible naming of the remote. Perhaps this extension is assuming it will have full domain of all remote names. But it doesn't. And it can't use a remote name that is already used, or needs to be used. It needs to create a unique remote name in its own private domain.

### Setup

* Microsoft Windows [Version 10.0.19043.1165]
* Version: 1.60.0 (system setup)
* Commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
* Date: 2021-09-01T10:41:52.311Z
* Electron: 13.1.8
* Chrome: 91.0.4472.164
* Node.js: 14.16.0
* V8: 9.1.269.39-electron.0
* OS: Windows_NT x64 10.0.19043
* Extension version: v0.30.0
* git v2.33.0

Steps to Reproduce:

1. install setup as above
2. Have a git repo with origin, upstream, branches, and a variety of remotes including remotes having the same name as some username. For example, have a repo remote named "daledemo" that points to a fork of the associated repo.
3. Have a git repo on github.
4. Have a github user named "daledemo" create a PR for the associated git repo
5. Attempt to checkout this PR using this extension.
6. Examine and watch that the files of the PR are actually on the hard drive (not virtual) so that the PR's files can be compiled

### Result

The PR's files are not on the hard drive. Errors appear in this extensions output tab window
```
[Info] Review> current branch pr/daledemo/12345 hasn't setup remote yet
```

### Expected

Files on drive. Ready to compile.

### Notes

I suspect this is related to the existing remote "daledemo" that was setup prior to the attempted PR checkout.
And then this extension assumed that it can create a remote called "daledemo" for its use on the PR.
But it can't.  That "daledemo" remote is already in use to point to the fork.

**Comment by alexr00** [comment]
Thanks for the note, that does seem like it could be the culprit.

**Comment by alexr00** [comment]
I can only reproduce this issue when I have checked out a PR from fork xxxxx before and then I later change the remote named xxxxx to something else. This is expected in this case.

**Comment by diablodale** [comment]
I no longer use the github extension as it was unreliable.
I can neither confirm or deny as the error was reproduced using my repro steps above. Perhaps in the last two months bugs were fixed somewhere.
Good luck
