### ISSUE TITLE
Use colour to differentiate between resolved and unresolved discussions

### ISSUE THREAD

**Issue by rhystedstone** [microsoft/vscode-pull-request-github#2987]
The discussion bar will show boxes with a diamond wherever a discussion is collapsed, however, there is no obvious difference between resolved and unresolved discussions:
![The top discussion is resolved, while the other is not.](https://user-images.githubusercontent.com/12123847/132106336-904bbc11-f550-4a30-bcfb-e83fbafb8309.png)
*The top discussion is resolved, while the other is not.*

I'm suggesting that the buttons have a separate colour when marked as "resolved". Resolved issues could be greyed out.

**Comment by a-stewart** [comment]
We created a similar request for something something similar to this to be added to the comments api in upstream vscode.
https://github.com/microsoft/vscode/issues/127473

**Comment by alexr00** [comment]
We use a different icon for resolved vs. unresolved now.
