### ISSUE TITLE
Permanent Authentication request 

### ISSUE THREAD

**Issue by marcelkmfst** [microsoft/vscode-pull-request-github#2989]
Hi,

the extension suddenly stopped working. I get permanent popups that authentication is required. The authentication itself works but the extension is asking again. Tried PAT as well, same behavior. Disabling and enabling as well as uninstalling the extension didn´t help Any idea? 

- Extension version: 0.29.2
- VSCode Version: 1.59.1
- OS: W1021H1

**Comment by thegiantbeast** [comment]
Same problem here. Even just by reloading the window will trigger this behaviour.

It seems the credentials are not being stored between sessions.

**Comment by alexr00** [comment]
Can you open the Output panel and share the output from "GitHub Pull Request" and "GitHub Authentication"?
