### ISSUE TITLE
Commenting on review creates a new pending review. 

### ISSUE THREAD

**Issue by einsiol** [microsoft/vscode-pull-request-github#2990]
- Extension version: 0.30.0
- VS Code Version: 1.60.0
- OS Version: macOS 11.5.2

I've noticed an issue where I commented(answered) on a review comment on my PR from Visual Studio code. My answer was added as expected under the comment I was answering too, but it also appears as a pending comment for a review at the bottom of the PR.

The review cannot be removed after, there is no option to dismiss it. If I check the `files` section, I can't find the review comment anywhere, it is only visible in the `conversation` section

I am also the author of the PR.

Steps to Reproduce:

1. Comment on a code review comment inside VScode, inside the file the comment relates to.
2. Check PR, this comment has been added as a pending review comment, as well as a normal respond to the comment.

**Comment by alexr00** [comment]
@einsiol did you use the "Start review" button instead of the "Add comment" button?
