### ISSUE TITLE
Post install the viewlet doesn't show the sign in button

### ISSUE THREAD

**Issue by nevasha27** [microsoft/vscode-pull-request-github#2994]
- Extension version: 0.30
- VSCode Version:  1.60.0 (Universal)
- OS: Mac OS 11.5.2

Steps to Reproduce: 

1. Install "GitHub Pull Requests and Issues" from marketplace
2. Navigate to the viewlet
3.
![image](https://user-images.githubusercontent.com/48847088/132954516-bd655f4c-cf09-4d5e-989a-ddf7b2b8d811.png)

**Comment by alexr00** [comment]
I'm not able to reproduce this issue. Can you open the Output panel and share the output from "GitHub Pull Request" and "GitHub Authentication"?
