### ISSUE TITLE
Error: You can’t perform that action at this time.

### ISSUE THREAD

**Issue by dkowalec** [microsoft/vscode-pull-request-github#2996]
# Error: You can’t perform that action at this time.

- Extension version: `N/A`
- VSCode Version: `N/A`
- OS: `MacOSx / Catalina 10.15.7`
- Chrome: `Version 93.0.4577.63 (Official Build) (x86_64)`

## Steps to Reproduce:
1. Go to Github repo PR
2. Feedback on PR
3. Received reply on feedback
4. Thumbs up emoji
5. Attempt to resolve comment
6. Error: Can't resolve comment using Chrome, Firefox, or Safari or on mobile Chrome (iOS)

PR Reply: https://github.com/mdvip/mdvipconnect/pull/1257/files#r708484672
> I tested this on several browsers and the issue started happening randomly about 2-3 weeks ago. I had this on my mobile phone and now my desktop. This isn't a cache issue as I launched a brand new browser uncached and save issue. I am the enterprise admin and admin on the repos as well. The PR was not opened by me but a developer so it can't be a permission issue.

## Error Screenshot
![image](https://user-images.githubusercontent.com/45953408/133514912-6bdd47d7-910e-466b-9dc9-fe6d4aae4089.png)

## HTML Error Markup
````
<div id="ajax-error-message" class="ajax-error-message flash flash-error">
    <svg aria-hidden="true" height="16" viewBox="0 0 16 16" version="1.1" width="16" data-view-component="true" class="octicon octicon-alert">
    <path fill-rule="evenodd" d="M8.22 1.754a.25.25 0 00-.44 0L1.698 13.132a.25.25 0 00.22.368h12.164a.25.25 0 00.22-.368L8.22 1.754zm-1.763-.707c.659-1.234 2.427-1.234 3.086 0l6.082 11.378A1.75 1.75 0 0114.082 15H1.918a1.75 1.75 0 01-1.543-2.575L6.457 1.047zM9 11a1 1 0 11-2 0 1 1 0 012 0zm-.25-5.25a.75.75 0 00-1.5 0v2.5a.75.75 0 001.5 0v-2.5z"></path>
</svg>
    <button type="button" class="flash-close js-ajax-error-dismiss" aria-label="Dismiss error">
      <svg aria-hidden="true" height="16" viewBox="0 0 16 16" version="1.1" width="16" data-view-component="true" class="octicon octicon-x">
    <path fill-rule="evenodd" d="M3.72 3.72a.75.75 0 011.06 0L8 6.94l3.22-3.22a.75.75 0 111.06 1.06L9.06 8l3.22 3.22a.75.75 0 11-1.06 1.06L8 9.06l-3.22 3.22a.75.75 0 01-1.06-1.06L6.94 8 3.72 4.78a.75.75 0 010-1.06z"></path>
</svg>
    </button>
    You can’t perform that action at this time.
  </div>
````

**Comment by alexr00** [comment]
This is coming from github.com, not this VS Code extension.
