### ISSUE TITLE
outdated comments do not appear

### ISSUE THREAD

**Issue by 0xabu** [microsoft/vscode-pull-request-github#2997]
My first time trying this extension, I opened https://github.com/pdfminer/pdfminer.six/pull/661 and wondered where all the open/unresolved comments are. The only two comments I see in the extension are the non-outdated ones; outdated but unresolved comments don't appear anywhere. Is that expected?

There are no obvious errors in the log, but I do see this which suggests that the extension is seeing something about the missing comments:
```
[Info] PullRequestCommentController> Thread with ID pdfminer/high_level.py-modified is no longer in cache
[Info] PullRequestCommentController> Thread with ID pdfminer/arcfour.py-modified is no longer in cache
[Info] PullRequestCommentController> Thread with ID pdfminer/ccitt.py-modified is no longer in cache
[Info] PullRequestCommentController> Thread with ID pdfminer/ccitt.py-modified is no longer in cache
[Info] PullRequestCommentController> Thread with ID pdfminer/ccitt.py-modified is no longer in cache
[Info] PullRequestCommentController> Thread with ID pdfminer/encodingdb.py-modified is no longer in cache
[Info] PullRequestCommentController> Thread with ID setup.py-modified is no longer in cache
[Info] PullRequestCommentController> Thread with ID tools/dumppdf.py-modified is no longer in cache
[Info] PullRequestCommentController> Thread with ID tools/pdf2txt.py-modified is no longer in cache
```

Extension 0.30.0, VSCode 1.60.1

_Originally posted by @0xabu in https://github.com/microsoft/vscode-pull-request-github/issues/2831#issuecomment-917231967_

**Comment by alexr00** [comment]
Are the comments visible in the "Comments" panel?
