### ISSUE TITLE
github.dev PR reviews don't allow commenting in renamed files

### ISSUE THREAD

**Issue by AArnott** [microsoft/vscode-pull-request-github#2999]
Looking at https://github.dev/microsoft/CsWin32/pull/355

I cannot seem to leave comments in files that were renamed as part of the PR. Even on lines that changed.

**Comment by roblourens** [comment]
Seems like I still can't add comments to this renamed file

![image](https://user-images.githubusercontent.com/323878/144304748-57a74bb6-22d6-428d-837c-e611f85655da.png)

**Comment by alexr00** [comment]
@roblourens I'm not able to reproduce this. Do you have changed lines in the file? Commenting is still only allowed on changed lines.

**Comment by fsevenm** [comment]
In my case, still cannot add comment for renamed file. The left bar is not clickable.

https://user-images.githubusercontent.com/29963765/175227837-0b1c9ae5-80ab-4c41-981a-de6e694793e6.mp4

**Comment by fsevenm** [comment]
The file was renamed + changed at the same time. Not sure if I should create a new issue for this.

**Comment by fsevenm** [comment]
@alexr00 desktop VS Code

**Comment by fsevenm** [comment]
I just open it normally. Opening PR sidebar, the select the updated file.
![image](https://user-images.githubusercontent.com/29963765/176628520-c63f5984-c20f-4700-8b3d-c82738713eb8.png)

**Comment by fsevenm** [comment]
@alexr00  I added the comment from github directly and this is how it looks like.
![image](https://user-images.githubusercontent.com/29963765/176800535-04065e64-3062-49a1-9028-94fe4f066e7b.png)

**Comment by alexr00** [comment]
Thank you @fsevenm. I can reproduce the issue.
