### ISSUE TITLE
Contributed panels do not appear focused on startup

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode-pull-request-github#30]
1. Open the Comments panel
2. Reload the window

<img width="916" alt="screen shot 2018-06-26 at 15 57 41" src="https://user-images.githubusercontent.com/22350/41917012-b0a1325a-7959-11e8-85b1-32649a174844.png">

**Comment by RMacfarlane** [comment]
Fixed in https://github.com/Microsoft/vscode/commit/9eeae44f76145b0bffd48919228b14ded5afbda6
