### ISSUE TITLE
Clear authentication

### ISSUE THREAD

**Issue by jrschumacher** [microsoft/vscode-pull-request-github#3000]
Provide way to clear the Github authentication data.

Currently, I have a token stored, but it's invalid, and I'm not being prompted to provide a new one. I've removed the extension, but this doesn't clear the session data.

**Comment by alexr00** [comment]
You can clear it by signing out:
![Uploading recording (68).gif…]()

**Comment by jrschumacher** [comment]
I'm not seeing the account management icon. 
![CleanShot 2021-09-22 at 07 54 55](https://user-images.githubusercontent.com/46549/134347437-73fbdaa5-cf3c-4a1d-98da-ec2f8edc4ccb.png)
![CleanShot 2021-09-22 at 07 56 03](https://user-images.githubusercontent.com/46549/134347489-9a84e4d0-79d2-4b16-b480-9a6cbed6131d.png)

**Comment by alexr00** [comment]
It's this one: 
![image](https://user-images.githubusercontent.com/38270282/134350670-e1ccf6a9-3b45-43cb-bde7-1cfcad3086e3.png)

**Comment by jrschumacher** [comment]
Ah! Thanks!!
