### ISSUE TITLE
Cannot modify PR from fork using . interface

### ISSUE THREAD

**Issue by pllim** [microsoft/vscode-pull-request-github#3001]
Similar to #2557 but that one sounds like a feature request, while mine is more like a bug report. I first submitted this to GitHub Help Desk but after a month or so of silence, they asked me to open issue here.

- Extension version: (Not sure what this is)
- VSCode Version: (Not sure how to check)
- OS: Windows 10

Steps to Reproduce:

I tried this `.` trick to try to fix someone else's PR from a fork to a repo I help maintain, but the commit failed with permission error. That wasted 30 minutes of my time, when I could have done it locally via normal `git` commands.

Reproduction Steps

1. Go to an active PR on a repo you have write access to, and the maintainer is allowed to push commits to it.
2. Click on the link that takes you to the PR branch on the author's fork.
3. Use the magical `.` key to pop up VS Code interface.
4. Do some edits across several files on that branch.
5. Attempt to commit the changes. See errors about unable to commit due to permission issues.
6. Abandon ship.

**Comment by alexr00** [comment]
@pllim a few questions for you:

1. Can you do your repro then open the Output panel in your VS Code tab? Choose "GitHub Authentication" from the Output panel's dropdown. Can you share the contents of that output here?
2. Also from the Output panel, choose "GitHub Pull Request" from the dropdown. Can you share that output here too?
3. Finally, can you share the exact error you're seeing about being unable to commit?

**Comment by pllim** [comment]
@alexr00 , thanks for the reply, but I don't understand what you mean by "Output panel in your VS Code tab". Do you have screenshots that I can follow? This is what I am looking at:

![Screenshot 2021-09-21 131827](https://user-images.githubusercontent.com/2090236/134217518-199930b6-2a2b-4b54-96f7-8229be2ebeb9.jpg)

**Comment by alexr00** [comment]
![recording (68)](https://user-images.githubusercontent.com/38270282/134689647-84d8091b-5d86-498c-b0e2-dd9092b82d0b.gif)

**Comment by pllim** [comment]
Also, the PR author confirmed that he checked the `Allow edits and access to secrets by maintainers` option, and I am a maintainer for the repo that PR is opened at.

**Comment by alexr00** [comment]
Thanks @pllim that's exactly what I was looking for.

@eamodio I think that error is coming the GitHub Repositories extension. Do you know anything about this issue?

**Comment by eamodio** [comment]
Yeah, unfortunately there is a current issue with the GitHub apis for this scenario which is blocking us from being able to commit properly. We are currently switching to use a new set of GitHub apis for committing (via GraphQL) which should resolve this issue. 

Additionally, just know for the future you can export a Git patch file from github.dev:
![image](https://user-images.githubusercontent.com/641685/135385284-f025e5e6-b266-4ea5-8f1c-d43fb04c3042.png)

Which you can then import and apply locally using `git apply <patch-filename>`.

**Comment by alexr00** [comment]
Thanks for the details @eamodio!

Closing as upstream.
