### ISSUE TITLE
Activating the Pull Requests

### ISSUE THREAD

**Issue by ViNi0708** [microsoft/vscode-pull-request-github#3004]
Activating the Pull Requests and Issues extension failed. Please make sure you have git installed.

**Comment by alexr00** [comment]
Can you please reproduce the issue then share the following:

- Output from "GitHub Pull Request"
- The exact steps (with screenshots if possible) or what you were doing when the error occurred. If your repo is public, a link to the PR or branch you were using is also helpful.

Output can be found by running the command "Output: Focus on Output View"

**Comment by jbanahan** [comment]
Just ran into this in VS Code when I upgraded my M1 to Monterey.

Running `git` in the terminal got me the following error:
```
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
```

To fix: `xcode-select --install`

**Comment by Rogersurf** [comment]
> 1. GitHub Repository Manger extension

I just have done the 3rs step and it worked. Thank you so much!

**Comment by ejm554** [comment]
> 1. Make sure that you are signed into the GitHub Repository Manger extension (separate extension)

I don't see this extension in the VS Code Marketplace. Can you provide a direct link?

**Comment by Suncatcher** [comment]
> I don't see this extension in the VS Code Marketplace. Can you provide a direct link?

the same. There is some from Henrique Bruno, which doesn't look like official
https://marketplace.visualstudio.com/items?itemName=henriqueBruno.github-repository-manager
