### ISSUE TITLE
Failed to execute git

### ISSUE THREAD

**Issue by sina-yeganeh** [microsoft/vscode-pull-request-github#3006]
- Extension version: v0.30.0
- VSCode Version: Latest Version
- OS: Linux

Hi! When I want to pull request to my repo, I got this error. do you know why? please help.

**Comment by alexr00** [comment]
Can you please share the following:

- Output from "GitHub Authentication"
- Output from "GitHub Pull Request"
- The exact steps (with screenshots if possible) or what you were doing when the error occurred. If your repo is public, a link to the PR or branch you were using is also helpful.

Output can be found by running the command "Output: Focus on Output View"

**Comment by sina-yeganeh** [comment]
Problem fixed, thank for your atation
