### ISSUE TITLE
Fetching pull requests for remote 'origin' failed

### ISSUE THREAD

**Issue by ghstridr** [microsoft/vscode-pull-request-github#3012]
When opening a project or just starting VSCode, I am getting a issue of not being able to pull notifications from github for pr's and issues.
`Version: 1.60.2
Commit: 7f6ab5485bbc008386c4386d08766667e155244e
Date: 2021-09-22T11:59:27.195Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 19.6.0`
![Screenshot- 2021-09-28 at 3 44 53 PM](https://user-images.githubusercontent.com/296345/135397612-4213b900-0af0-4fe3-9d2b-e7a3f5592590.png)

**Comment by alexr00** [comment]
Can you please reproduce the issue then share the Output from "GitHub Pull Request"?  There should be a more detailed error.

**Comment by ghstridr** [comment]
For some reason, the problem seems to have disappeared. I started vscode today without any error messages. I'll close this. Thank you.
