### ISSUE TITLE
No issue completions with default query

### ISSUE THREAD

**Issue by texastoland** [microsoft/vscode-pull-request-github#3014]
- **Extension version**: v0.30.0
- **VSCode Version:** 1.60.2 (NOT Insiders)
  **Commit:** 7f6ab5485bbc008386c4386d08766667e155244e
  **Date:** 2021-09-22T11:59:27.195Z (1 wk ago)
- **OS:** macOS 11.6 (20G165)

Issue autocompletion is provided by the `githubIssues.queries` setting. By default it's limited to your assigned (with a milestone?) and created issues. Contributions to open source projects are rarely assigned. This limits discoverability of issue autocompletion (I was specifically searching for it).

I propose an additional default **Open Issues** query corresponding to **All Open** pull requests.

**Comment by alexr00** [comment]
@texastoland this is an excellent point. I'm thinking a "Recent Issues" query might be good to have, where it returns recently modified issues.

**Comment by alexr00** [comment]
Leaving this here for when I update the query: https://docs.github.com/en/search-github/searching-on-github/searching-issues-and-pull-requests#search-by-when-an-issue-or-pull-request-was-created-or-last-updated

**Comment by texastoland** [comment]
I like that! It would resolve the discovery issue for repos (like Microsoft's) where all open issues might incur a performance penalty. If it were architecturally feasible in the future paging open issues could be preferable.
