### ISSUE TITLE
Copy GitHub Permalink slow on large repos

### ISSUE THREAD

**Issue by geramirez** [microsoft/vscode-pull-request-github#3016]
some related issues, but not the same one

- Extension version: 0.30.0
- VSCode Version:   1.60.2
- OS: mac os

Steps to Reproduce:
1. Open a repo like github/github 
2. copy a line and quickly paste the result
3. nothing will be copied 

However you you wait a second or two on the window. The copy will work.

This only seems to happen on large repos.

**Comment by alexr00** [comment]
The slowness is tied to the number of branches you have locally: https://github.com/microsoft/vscode-pull-request-github/issues/1884

There is a two second timeout for using a fallback. I'll try reducing that and we'll see if anyone notices that the fallback is less accurate.
