### ISSUE TITLE
"Unable to create a GitHub permalink for the selection. There is no suitable remote."

### ISSUE THREAD

**Issue by daniellepintz** [microsoft/vscode-pull-request-github#3019]
Hi, I am getting the error "Unable to create a GitHub permalink for the selection. There is no suitable remote."
when trying to "Copy GitHub permalink" via this extension (via command shift p in VSCode).

<img width="559" alt="Screen Shot 2021-09-30 at 8 48 00 PM" src="https://user-images.githubusercontent.com/38207072/135562285-2340fa19-bafb-4229-88f0-db35879a4d35.png">

### Debug info: 

the output of `git remote -v` is:
```
origin	git@github.com:daniellepintz/pytorch-lightning.git (fetch)
origin	git@github.com:daniellepintz/pytorch-lightning.git (push)
upstream	https://github.com/PyTorchLightning/pytorch-lightning.git (fetch)
upstream	https://github.com/PyTorchLightning/pytorch-lightning.git (push)
```

I have `githubPullRequests.remotes` set correctly:
<img width="901" alt="Screen Shot 2021-09-30 at 8 49 41 PM" src="https://user-images.githubusercontent.com/38207072/135562383-e1a26673-187c-465f-9a47-bf621d48fa19.png">

and I am on a local branch that has a remote counterpart (in origin)

Does anyone know how to fix this? TIA

- Extension version: 0.29.2
- VSCode Version: 1.59.1
- OS: Mac 11.6

**Comment by daniellepintz** [comment]
Hi, is it possible to get some help on this?

**Comment by mmcloughlin** [comment]
FWIW when this happened to me, it was because the local version didn't exist on the remote. @alexr00 I assume that's what you're getting at with your question?

If that's the underlying reason it makes perfect sense but the error message could be clearer.

**Comment by alexr00** [comment]
@mmcloughlin yes, that's where I was going with the question. I'll update the message 👍.

**Comment by mmcloughlin** [comment]
@alexr00 Thanks!
