### ISSUE TITLE
Show commit descriptions in an overflow

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#302]
https://github.com/Microsoft/vscode/issues/57301

Right now it looks like the title+description string is just added:

<img width="417" alt="screen shot 2018-08-28 at 11 28 48 am" src="https://user-images.githubusercontent.com/2193314/44742800-a04cf280-aab5-11e8-8527-436cb488ddbd.png">

<img width="445" alt="screen shot 2018-08-28 at 11 33 00 am" src="https://user-images.githubusercontent.com/2193314/44743014-25380c00-aab6-11e8-98b4-803d9e461f52.png">

This would look terrible if the description contains a paragraph of text which I will sometimes do on particularly complex bug fixes.

**Comment by Tyriar** [comment]
@RMacfarlane I suspect the message you get back has `\n` chars in it and they're just converted to whitespace when in HTML. The first line is the title of the commit, the rest is the description.

**Comment by alexr00** [comment]
Overflow already happens when the message to sufficiently long:

![image](https://user-images.githubusercontent.com/38270282/142017664-f7be0ac7-1f0c-4bd9-8ce2-4bc1c9857f3b.png)
