### ISSUE TITLE
Option to filter PR under the All Open tree

### ISSUE THREAD

**Issue by jmredfern** [microsoft/vscode-pull-request-github#3025]
I work on a large Monorepo, which means there's huge number of open PRs under the All Open tree. This means that it's difficult to find a specific open PR (the workaround I've been using is to assign myself to that PR in GitHub). It would be really useful if there was a filter so that I could type in the PR id number to find a specific open PR.

Thanks!

**Comment by alexr00** [comment]
In most VS Code trees you can start typing when the focus is in the tree and then elements that match what you typed will either select or filter (you can toggle between those options). Of course, this only works if the element is in one of the subtrees you have open. 

![recording (69)](https://user-images.githubusercontent.com/38270282/137517926-b0b6fd05-5ac9-4b6f-a2f9-4e9ae1285adf.gif)

@jmredfern does that do what you need? You can also add new queries to the PRs tree.
