### ISSUE TITLE
Allow configuration of default branch in pull requests

### ISSUE THREAD

**Issue by hoersamu** [microsoft/vscode-pull-request-github#3028]
It would be great if there was a setting to select the default branch to merge into when opening PRs.

**Comment by odil-io** [comment]
I would love to overrule the Default Branch setting from GitHub (or other VCS) to avoid conflicts. As I'm not always able (or permitted) to edit a Repo's settings.

**Comment by hannanelson** [comment]
It would be nice if the default branch to merge was the source branch (the branch you branched from).

**Comment by odil-io** [comment]
> It would be nice if the default branch to merge was the source branch (the branch you branched from).

Exactly what I meant

**Comment by alexr00** [comment]
There is the setting `githubPullRequests.overrideDefaultBranch`, which lets you override the default branch for the repo.

**Comment by alexr00** [comment]
We also now guess which branch should be the base branch by looking at where you branched off from.

**Comment by jaunito76** [comment]
This guessing seems to default to the same branch that you are working on, can you still use the ```githubPullRequests.overrideDefaultBranch```?

**Comment by alexr00** [comment]
> This guessing seems to default to the same branch that you are working on

If you're using the pre-release version with VS Code insiders this should now be fixed. 

If not, then you can use `githubPullRequests.createDefaultBaseBranch`.
