### ISSUE TITLE
PR approvals aren't very obvious 

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-pull-request-github#303]
https://github.com/Microsoft/vscode/issues/57301

Also note there are two types, collaborator/owner approvals and contributor/external approvals.

<img width="365" alt="screen shot 2018-08-28 at 11 35 12 am" src="https://user-images.githubusercontent.com/2193314/44743123-7811c380-aab6-11e8-821b-2e7b18f1f7cc.png">

**Comment by RMacfarlane** [comment]
Completed by https://github.com/Microsoft/vscode-pull-request-github/pull/831
