### ISSUE TITLE
Duplicate comments showing up in pull request

### ISSUE THREAD

**Issue by bdwain** [microsoft/vscode-pull-request-github#3037]
Issue Type: <b>Bug</b>

I commented on a pull request via the VSCode Extension (I can't share the PR as it's part of my organization) and I am seeing each comment appears three times in the extension's diff view (but only once in the web PR interface).

This is a pull request I opened (and I have it checked out locally as well, though I commented in the diff view, not "review mode")

It also seems limited to comments I made, not comments other people made.

Extension version: 0.31.0
VS Code version: Code 1.61.0 (ee8c7def80afc00dd6e593ef12f37756d8f504ea, 2021-10-07T18:11:58.853Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 2|
|Memory (System)|32.00GB (6.89GB free)|
|Process Argv|--crash-reporter-id a9129995-196a-46ef-bc1b-19ca01449137|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30378365
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30364666
pythonvspyt187:30373474
vsqsis300:30381676
vsaa593:30376534
vssld246cf:30379912

```

</details>

**Comment by bdwain** [comment]
<img width="1352" alt="Screen Shot 2021-10-14 at 1 00 25 PM" src="https://user-images.githubusercontent.com/3982094/137374230-4ec016c5-ed37-4331-b506-c981f071fb2d.png">

**Comment by alexr00** [comment]
Thanks @bdwain, [this](https://github.com/microsoft/vscode-pull-request-github/issues/3037#issuecomment-944040188) helps. 

I'm not able to repro the issue. However, I see a place where this could happen. I've pushed a change, and it will be available in the pre-release version of the extension on Monday.

**Comment by alexr00** [comment]
@bdwain are you able to try out the [pre-release](https://github.com/microsoft/vscode-pull-request-github/wiki/Pre-release-Build) version of the extension to check if the issue is fixed there?

**Comment by bdwain** [comment]
@alexr00 i haven't seen the issue occur in a while, so I can't say for sure anymore if this changed anything.

**Comment by alexr00** [comment]
Ok, thanks @bdwain. We'll leave this one unverified then.
