### ISSUE TITLE
Mousing over external links in PR description should show where they go

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#304]
https://github.com/Microsoft/vscode/issues/57301

I tried to check the domain on the download links in https://github.com/Microsoft/vscode/pull/56149

**Comment by connorshea** [comment]
I would also appreciate this, the default Markdown renderer handles this well by showing the URL on hover, presumably with an `alt` attribute?

<img width="493" alt="screen shot 2018-09-13 at 12 47 05 pm" src="https://user-images.githubusercontent.com/2977353/45508975-823cee80-b753-11e8-93db-7d37456b0df9.png">

**Comment by rzhao271** [comment]
I do see more hovers show up, but still none for the description area of the PR:
![Description area of the PR](https://user-images.githubusercontent.com/7199958/144115803-a472fbb7-b499-46b4-a77b-d80d6b2db72d.PNG)

**Comment by alexr00** [comment]
I can't find a way to cause the target of a link to be used as the title of an element for all links. Since we just render the html from GitHub, and that html doesn't have titles set for any of the link, I'm calling target hovers in GitHub provided content wont-fix.
