### ISSUE TITLE
Feature Request: View All Changes In PR

### ISSUE THREAD

**Issue by nodeselector** [microsoft/vscode-pull-request-github#3047]
I would find a command that allows me to open all changes in a pull request really valuable. Currently I open each file's diff from the PR Changes view. This is fine, but gets a bit tedious with larger pull request (O(N) in terms of my input). If I'm wanting to compare changes to the working tree GitLens has a `Open All Changes (difftool)` (O(1) in terms of my input) command. Which is fantastic as I can open each diff as a tab and work through the changes in the commit, closing tabs as I'm satisfied with the changes.

I would like to be able to be able to do something similar for my PR review process:
- Close All Editors
- Open All Changes in PR
- Review each file, adding comments, marking as reviewed, and finally closing that file when I'm satisfied.

I hope this isn't a duplicate. I see that the folks working on GitLens received a similar request, however, they see this project as more in scope for implementation. See https://github.com/Axosoft/vscode-gitlens/issues/1020

**Comment by joshuaobrien** [comment]
I'd like this feature too. @alexr00, is it okay with you if I work on it?

**Comment by alexr00** [comment]
@joshuaobrien yes, go for it! Do you need any code pointers?

**Comment by joshuaobrien** [comment]
Thanks @alexr00! I'll have an attempt at implementing the feature and reach out here if I run into issues

**Comment by joshuaobrien** [comment]
The initial approach that I've taken is to register a new command and pass `reviewManagers` to it. I then select the first review manager and use that to grab the local files that have changed. I can potentially see a couple problems with this though:

- There could be multiple review managers, so we can't just grab the first one
- Using `ReviewManager` feels a little convoluted. Perhaps I should grab the active  `PullRequestModel` and collate the files associated with its commits instead

Could I please get some advice here, @alexr00? Which direction would you recommend I explore? You can see a draft of my changes here: https://github.com/joshuaobrien/vscode-pull-request-github/pull/2

**Comment by joshuaobrien** [comment]
Also @alexr00, as a follow on from the addition of this command, would there be scope for adding a button for this to the UI? I know I'd use that quite a bit myself. I'm happy to have a go at implementing it!

**Comment by alexr00** [comment]
@joshuaobrien I took a quick look at your draft, thanks for working on this. A few notes:
- I don't want to have a super visible button as I'm not sure how popular this will end up being, but having the command in the context menu for the PR in the "Changes in Pull Request" view might be nice.
- Instead of choosing a `ReviewManager`, you can choose a `PullRequestModel`. There's a little choose utility you can use. ex:
https://github.com/microsoft/vscode-pull-request-github/blob/96dc89953372ef579902248473fb7f9a18923e7e/src/commands.ts#L487-L494

**Comment by alexr00** [comment]
To verify: 
1. Open a PR using the pre-release version of the extension
2. Try the new "Open All Diffs" command.
3. Verify that all diffs are opened.
