### ISSUE TITLE
No PR data available when using GHE with http URI

### ISSUE THREAD

**Issue by lzrf0cuz** [microsoft/vscode-pull-request-github#3050]
Issue Type: <b>Bug</b>

When using GHE, all opened pull request are listed, but when a PR is clicked, no info is available. It works fine when using github.com, the issue is only with GH Enterprise.

Extension version: 0.31.1
VS Code version: Code 1.61.2 (Universal) (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T15:49:28.381Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30364666
pythonvspyt187:30373474
vsqsis400:30381677
vsaa593:30376534
vssld246:30379911

```

</details>

**Comment by sheenjustin** [comment]
Hey @akhi4u is your GHE server using http? I'm getting a similar response and this looks to be the culprit:

[Info] Review> Validating state...
[Info] GitHubServer> No response from host **https://<Domain>**/<Repo>: request to https://<Domain>/api/v3/rate_limit failed, reason: connect ECONNREFUSED <IP-Address>:443
[Info] No remotes found. The following remotes are missing: origin
[Info] No GitHub remotes found
[Info] Review> no matching pull request metadata found for current branch staging
[Info] Review> no matching pull request metadata found on GitHub for current branch staging

But the GHE URI in my settings.json is **http://<Domain>** so somewhere along the line it's trying to upgrade to https and doesn't fallback to http

**Comment by alexr00** [comment]
@sheenjustin thanks for the investigation. I can reproduce the http/https mismatch.

**Comment by alexr00** [comment]
It looks like `https` is required for some of the GitHub API calls we make. The fix is to automatically always use `https`.
