### ISSUE TITLE
Fails to load pull requests when using ssh.github.com for ssh over https

### ISSUE THREAD

**Issue by kevindurb** [microsoft/vscode-pull-request-github#3052]
- Extension version: 0.31.1
- VSCode Version: 1.61.2
- OS: macos 11.3.1

Steps to Reproduce:

1. follow steps to add ssh.github.com to ssh config from github docs https://docs.github.com/en/authentication/troubleshooting-ssh/using-ssh-over-the-https-port
2. install extension
3. extension stuck on "No remotes match current setting"

Output:
```
[Info] Registering git provider
[Info] Looking for git repository
[Info] Found 1 repositories during activation
[Info] Git repository found, initializing review manager and pr tree view.
[Info] Review> Validate state in progress
[Info] Review> Validating state...
[Info] Cannot updates repositories as git is uninitialized
[Info] Review> Queuing additional validate state
[Info] Review> Validating state...
[Info] Cannot updates repositories as git is uninitialized
[Info] Review> no matching pull request metadata found for current branch main
[Info] Review> no matching pull request metadata found on GitHub for current branch main
[Info] Git initialization state changed: state=initialized
[Info] Review> Queuing additional validate state
[Info] Review> Validating state...
[Info] GitHubServer> No response from host https://ssh.github.com/****/****: request to https://ssh.github.com/api/v3/rate_limit failed, reason: write EPROTO 140596883097400:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:

[Info] No remote with name 'origin' found.
[Info] No remote with name 'upstream' found.
[Info] No GitHub remotes found
[Info] Review> no matching pull request metadata found for current branch main
[Info] Review> no matching pull request metadata found on GitHub for current branch main
```

**Comment by ghills** [comment]
I'm also facing this issue as I have my ssh configuration for github setup to operate over the HTTPS port

**Comment by alexr00** [comment]
@ghills or @kevindurb there will be a [nightly/insiders build](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github-insiders )of this extension with the fix available starting tomorrow. If you could try it out sometime in the next week or so and reply indicating whether the issue is fixed that would help us out with our verification process! (Note that you will have to disable or uninstall the stable build of the extension first).

**Comment by ghills** [comment]
> @ghills or @kevindurb there will be a [nightly/insiders build](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github-insiders) of this extension with the fix available starting tomorrow. If you could try it out sometime in the next week or so and reply indicating whether the issue is fixed that would help us out with our verification process! (Note that you will have to disable or uninstall the stable build of the extension first).

Hi @alexr00 -

I gave the nightly build a try (v2021.11.14945) and it still is not loading issues/PRs. Here are the contents of the output pane:

```
[Info] Registering git provider
[Info] Looking for git repository
[Info] Found 1 repositories during activation
[Info] Git repository found, initializing review manager and pr tree view.
[Info] Review> Validate state in progress
[Info] Review> Validating state...
[Info] GitHubServer> No response from host https://ssh.github.com/redacted/redacted: request to https://ssh.github.com/api/v3/rate_limit failed, reason: Client network socket disconnected before secure TLS connection was established
[Info] GitHubServer> No response from host https://ssh.github.com/ghills/redacted: request to https://ssh.github.com/api/v3/rate_limit failed, reason: Client network socket disconnected before secure TLS connection was established
[Info] No remote with name 'origin' found.
[Info] No remote with name 'upstream' found.
[Info] No remote with name 'redacted' found.
[Info] No GitHub remotes found
[Info] Review> no matching pull request metadata found for current branch fixup/cleanups
[Info] Review> no matching pull request metadata found on GitHub for current branch fixup/cleanups
```

Thanks for following up on this issue!

**Comment by alexr00** [comment]
@ghills I'm not able to reproduce what you're seeing. Can you share the output of `git remote -v` (redacted as you have been doing is still useful)?

**Comment by ghills** [comment]
> @ghills I'm not able to reproduce what you're seeing. Can you share the output of `git remote -v` (redacted as you have been doing is still useful)?

@alexr00 sure thing-

`git remote -v`:
```
foo        git@github.com:redacted/redacted.git (fetch)
foo        git@github.com:redacted/redacted.git (push)
origin  git@github.com:ghills/redacted.git (fetch)
origin  git@github.com:ghills/redacted.git (push)
```

Here are the contents of `~\.ssh\config`:
```
Host github.com
  Hostname ssh.github.com
  Port 443
  User git
```

Testing the authentication to GitHub:
```
> ssh -T git@github.com
warning: agent returned different signature type ssh-rsa (expected rsa-sha2-512)
Hi ghills! You've successfully authenticated, but GitHub does not provide shell access.
```

In my case I am running on Windows.

**Comment by alexr00** [comment]
@ghills thank you for being so thorough. This is suspicious:
```
warning: agent returned different signature type ssh-rsa (expected rsa-sha2-512)
```

That's the only difference between our setups. I think GitHub is rejecting further requests because of the differing signature types (This says that the remote can choose to reject connections where this happens: https://stackoverflow.com/questions/57223333/agent-key-rsa-sha256-returned-incorrect-signature-type#:~:text=There%20are%20two%20issues%20here%2C%20which%20are%20separate,of%20several%20hash%20algorithms%3A%20SHA-1%2C%20SHA-256%2C%20or%20SHA-512.)

If you're still seeing the issue after resolving the differing signatures I can take another look!

**Comment by ghills** [comment]
@alexr00 I got rid of that warning by updating Windows' OpenSSL to 8.1.0.1.

```
> ssh -T git@github.com
.Hi ghills! You've successfully authenticated, but GitHub does not provide shell access.
>
```

Unfortunately now I am getting a different error from the extension:

```
[Info] Registering git provider
[Info] Looking for git repository
[Info] Found 1 repositories during activation
[Info] Git repository found, initializing review manager and pr tree view.
[Info] Review> Validate state in progress
[Info] Review> Validating state...
[Info] GitHubServer> No response from host https://ssh.github.com/ghills/redacted: request to https://ssh.github.com/api/v3/rate_limit failed, reason: write EPROTO 9594760:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:

[Info] GitHubServer> No response from host https://ssh.github.com/redacted/redacted: request to https://ssh.github.com/api/v3/rate_limit failed, reason: Client network socket disconnected before secure TLS connection was established
[Info] No remote with name 'origin' found.
[Info] No remote with name 'upstream' found.
[Info] No remote with name 'redacted' found.
[Info] No GitHub remotes found
[Info] Review> no matching pull request metadata found for current branch fixup/cleanups
[Info] Review> no matching pull request metadata found on GitHub for current branch fixup/cleanups
```

For the repository I am testing with I am able to authenticate and work with remotes from Powershell, cmd, and the source control pane of VSCode (which I assume is just using the git cli under the hood).

From what I can see, it is trying to do an `OPTIONS https://ssh.github.com/api/v3/rate_limit` request which I am wondering is incorrect if `ssh.github.com` is not supposed to be the API endpoint.

Perhaps related to this code for host selection?
https://github.com/microsoft/vscode-pull-request-github/blob/be0fbc62714d3502b84f14d52e689d7094c7ea37/src/authentication/configuration.ts#L29-L34

called from
https://github.com/microsoft/vscode-pull-request-github/blob/be0fbc62714d3502b84f14d52e689d7094c7ea37/src/authentication/githubServer.ts#L24

**Comment by alexr00** [comment]
@ghills that is the code that I would expect to cause this, but we shouldn't actually get that far as there's a check for `ssh.github.com` that bails out before making the `GitHubManager.getOptions` call:

https://github.com/microsoft/vscode-pull-request-github/blob/f837b766033fd48ef28b16abcfc3f85303992f90/src/authentication/githubServer.ts#L8-L22

**Comment by ghills** [comment]
@alexr00 that worked - with that build it appears to be operating normally.

Thanks!

**Comment by TylerLeonhardt** [comment]
verifying based on @ghills's comment.
