### ISSUE TITLE
Extension not responsive issue

### ISSUE THREAD

**Issue by PranavGPR** [microsoft/vscode-pull-request-github#3053]
Hello I've been using this issue for a longer time now. But sometimes the extension is not starting itself and becomes unresponsive for several minutes. If you can kindly check what's happening here, it would be really helpful.

- Issue Type: `Bug`
- Extension Name: `vscode-pull-request-github`
- Extension Version: `0.31.1`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.61.2`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 53,
		"activateCallTime": 0,
		"activateResolvedTime": 6997,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "GitHub.vscode-pull-request-github",
				"_lower": "github.vscode-pull-request-github"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": [],
	"runningLocation": 1
}
```

**Comment by alexr00** [comment]
@PranavGPR is there some specific action you are doing when the slowdown occurs? If yes, can you try collecting a profile of the extension? https://github.com/microsoft/vscode/wiki/Performance-Issues#profile-the-running-extensions

**Comment by PranavGPR** [comment]
> @PranavGPR is there some specific action you are doing when the slowdown occurs? If yes, can you try collecting a profile of the extension? https://github.com/microsoft/vscode/wiki/Performance-Issues#profile-the-running-extensions

No, I was just trying to open a PR in my local machine's VSCode.

**Comment by alexr00** [comment]
Closing as not actionable for now, but if you're able to collect a profile please comment and I will investigate!
