### ISSUE TITLE
Comment icon in PR tree has black outline

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#3054]
Repro:

Make a comment and view the PR tree

![image](https://user-images.githubusercontent.com/2193314/138288677-e5b70ccf-7276-4c22-8863-b8cb5a4ad530.png)

cc @misolori

**Comment by misolori** [comment]
Couldn't find one so created https://github.com/microsoft/vscode/issues/135591

**Comment by alexr00** [comment]
I'll switch over to the proposed codicon support, though that means we'll only show one decoration.

**Comment by alexr00** [comment]
To verify:
- Install the latest pre-release version of GitHub Pull Requests
- Open your local clone of a GitHub repo in VS Code.
- Open the "Pull Requests" view
- Expand a PR that has comments, or add a comment to a PR.
- Verify that you see a nice comment codicon as the decoration for the file with the comment in the "Pull Requests" view. It is a known limitation that you will only see one decoration.
