### ISSUE TITLE
Can't connect to GHE by 0.31.1 when upgrade vscode from 1.61.1 to v1.61.2

### ISSUE THREAD

**Issue by think120** [microsoft/vscode-pull-request-github#3056]
- Extension version: 0.31.1
- VSCode Version: 1.61.2
- OS: WIN 10

In vscode 1.6.1.2, can't login to GitHub Enterprise.  

The extension asked me to sign in
![image](https://user-images.githubusercontent.com/78618719/138354584-5bddfef8-7b72-4490-bf72-b6c17fa70a3c.png)

But I've already signed in.

![image](https://user-images.githubusercontent.com/78618719/138354537-dfce97b9-2141-4df8-9e68-a83281c45d3d.png)

![image](https://user-images.githubusercontent.com/78618719/138354350-0cec821d-ee8c-4e43-bde8-8c854e41cb35.png)

When **downgrade to v1.61.1,**  it works again!!

Or if downgrade extension to 0.31, then it works with vscode 1.61.2

**Comment by slietzau** [comment]
@alexr00 The issue persists with with vscode 1.62.2 and extension version 0.32.0.

Downgrading to 0.31.0 is still the only solution for us.

The whole prompt to sign in for GitHub/ GitHub Enterprise is missing:
![image](https://user-images.githubusercontent.com/17597022/141455054-0c7b0673-aa90-4475-a86e-2e36932ecbe5.png)

Same picture with 0.31.0:
![image](https://user-images.githubusercontent.com/17597022/141455167-200d9f50-1448-4ec5-9281-20f97109bea6.png)

**Comment by stoinov** [comment]
I am seeing the opposite: 1.62.2 works with 0.32 for me.
I haven't done any changes to config - just updated VSCode. It was working with 1.62.0 too.

**Comment by slietzau** [comment]
I had to sign out of my github.com account to be able to reproduce the issue.

**Comment by alexr00** [comment]
@slietzau we no longer show the sign in prompt on the Accounts icon/menu until you have opened the GitHub view.
