### ISSUE TITLE
Unable to open PR from the web environment

### ISSUE THREAD

**Issue by vreynolds** [microsoft/vscode-pull-request-github#3068]
All the drop downs in "merge changes from" and "merge changes into" are blank, can't select anything, therefore can't submit a PR. 😿 

![image](https://user-images.githubusercontent.com/6738917/138492684-7fa64cf6-7825-41b3-ad4c-7edf3b54645e.png)

Version: 1.61.2
Commit: 6cba118ac49a1b88332f312a8f67186f7f3c1643
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:93.0) Gecko/20100101 Firefox/93.0
Embedder: github.dev

**Comment by dufferzafar** [comment]
I was facing this on Firefox as well. But not on Chrome. Let me know if you need any logs etc.

**Comment by dufferzafar** [comment]
This only seems to be occurring on http://vscode.dev / http://github.dev and not on GitHub CodeSpaces.

This screenshot is from the same firefox, but running codespaces:

![image](https://user-images.githubusercontent.com/1449512/140540473-651d0897-bc3d-467b-ab32-73f4a45ba94c.png)

**Comment by alexr00** [comment]
I'm no longer seeing this occur in Firefox.
