### ISSUE TITLE
VS Code Extensions Causing CPU to Overload

### ISSUE THREAD

**Issue by lynstanford** [microsoft/vscode-pull-request-github#3072]
- Extension version: Cloud Code v=1.15.1 - (Google Cloud Code SDK)
- VSCode Version: 1.61.2
- OS: Windows 10 Pro Version=10.0.19042 Build 19042

Steps to Reproduce:

1. Open VS Code
2. Load Google 'Cloud Code' Extension
3. Reload

**Comment by lynstanford** [comment]
Discovered incredibly slow loading time for this extension causing the VS Code program to crash.

**Comment by alexr00** [comment]
It sounds like you're having an issue with the Cloud Code extension. I suggest you file an issue with that extensions repository.

**Comment by lynstanford** [comment]
Many thanks alexr00, will do!
