### ISSUE TITLE
Add PR's fork as remote handle

### ISSUE THREAD

**Issue by janosh** [microsoft/vscode-pull-request-github#3075]
When right-clicking a PR, would be nice if besides the current "Checkout PR" option, there was another to add to PR's origin repo as a remote handle.

![Screen Shot 2021-11-02 at 07 00 42](https://user-images.githubusercontent.com/30958850/139800612-6bbf4d62-6e31-42fe-9fdd-a60cba4832c7.png)

I.e. if the PR comes from `https://github.com/someone-else/fork`, run

```sh
git remote add someone-else https://github.com/someone-else/fork
```

Reasoning: The current checkout option does not allow to push edits to PRs. If you're unaware of that, using this option to make changes and then being unable to add them to the PR can come as a bad surprise.

**Comment by alexr00** [comment]
So long as the author of the PR hasn't disabled it, you should be able to push changes to checked out PRs. If you're still unable to, please ping this issue and I will investigate!
