### ISSUE TITLE
Support auto merge

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#3085]
ext:

![image](https://user-images.githubusercontent.com/2193314/140540014-e3bb6e3c-f010-44ae-b737-a84a7f8f261d.png)

.com:

![image](https://user-images.githubusercontent.com/2193314/140540114-8039ae10-c214-4fd0-a779-d4517bdf7270.png)

**Comment by emtei** [comment]
That's a great feature! I could work on it, but does Github REST API support auto merge?
There is `enablePullRequestAutoMerge` mutation in GraphQL API but not in REST API.

I could use `octokit.graphql` like here: https://github.com/peter-evans/enable-pull-request-automerge/blob/main/src/github-helper.ts#L40 will this be fine for you? @alexr00 @Tyriar

**Comment by alexr00** [comment]
When possible and when it doesn't involve too much refactoring we try to us the GraphQL API, so this could work. There are several work chunks here:
- Check if the repo supports auto merge
- Add UX to turn on auto merge
- Do the auto merge

@emtei let me know if you want some code pointers!

**Comment by alexr00** [comment]
Here's what it looks like so far:
![image](https://user-images.githubusercontent.com/38270282/167104770-5c2233d4-73e2-42ae-b2ba-434556066e51.png)

I still need to show it in the PR overview webviews too.

**Comment by robinmanuelthiel** [comment]
Looks nice! Will there be an option to automatically delete the local branch as well, once the PR got merged?

**Comment by alexr00** [comment]
Will finish in June.
