### ISSUE TITLE
Documentation - Issue Variables

### ISSUE THREAD

**Issue by captainrdubb** [microsoft/vscode-pull-request-github#3087]
I am trying to change the format of the new branch created when i click `Start working on issue and checkout topic branch` button. I _discovered_ that there is a user setting for this. However, I am not sure about the available variables. I think that I found them [here](https://github.com/microsoft/vscode-pull-request-github/blob/5dc01ecf4f68d32f314a7e292026fefc68bd71b2/src/issues/util.ts#L520). It would be awesome to have this documented.

**Comment by alexr00** [comment]
Many of the variables are documented in the settings themselves:
![image](https://user-images.githubusercontent.com/38270282/140770463-7ea47264-16ad-4f78-a416-69237972d96f.png)

Just added this: https://github.com/microsoft/vscode-pull-request-github/blob/main/documentation/IssueFeatures.md#github-variables
