### ISSUE TITLE
SCM completion should have a setting to just insert the `#NUMBER` pattern

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-pull-request-github#3088]
Currently, accepting an issue suggestion in the SCM input will insert the issue's title as well as the `#NUMBER` pattern. It would be great to just get the `#NUMBER`.

**Comment by alexr00** [comment]
There's a setting for that :):
```
"githubIssues.issueCompletionFormatScm": "${issueNumberLabel}"
```
