### ISSUE TITLE
Issue Filter - Exclusion

### ISSUE THREAD

**Issue by captainrdubb** [microsoft/vscode-pull-request-github#3089]
Issue Type: <b>Bug</b>

In user settings, cannot use either of the following:

In GitHub I can use "-assignee:USERNAME", so that I can exclude issues assigned to user.
```
"githubIssues.queries":[
        {
            "label": "Not Assigned To Me",
            "query": "-assignee:${user}"
        },
]
```

In GitHub I can use "no:assignee", so that I can exclude all assigned issues.
```
"githubIssues.queries":[
        {
            "label": "Unassigned Issues",
            "query": "no:assignee"
        },
]
```

Extension version: 0.32.0
VS Code version: Code 1.62.0 (b3318bc0524af3d74034b8bb8a64df0ccf35549a, 2021-11-03T15:24:41.297Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 2|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv|--crash-reporter-id ccfae832-c142-4834-aaef-4a65f23b45dd|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200cf:30386380
vsaa593cf:30376535
vssld246cf:30386378

```

</details>

**Comment by alexr00** [comment]
Both of your examples work for me. Can you provide any other details about your setup? If it's a public repo, can you share the repo?
