### ISSUE TITLE
new APIs request: getCurrentPullRequestInfo and openDiff

### ISSUE THREAD

**Issue by LizardEatsFlies** [microsoft/vscode-pull-request-github#3093]
I would like to propose two new api calls so that other VS Code extensions can interact with this extension. 

They would look something like this:

`getCurrentPullRequestInfo(uri: string)` 
Given the URI of a file or diff view, return the PR number and repository that corresponds to that URI (or null if the URI isn’t for a file or diff).

`openDiff(filePath: string, pr: number, repoRootUri: Uri)` 
Open the diff view of a desired file based on its path, the PR number, and the repository. This would function the same as clicking on that fileChangeNode in the pull requests TreeView.

**Question**: is the repository rootUri the right way to refer to a repo in this extension?

### The reasoning behind these two calls:
We are currently developing an extension that allows users to explore the pull request in a diagram. We want to:
1. Allow a user, while doing a code review using the github pr extension, to view the associated diagram. For this, we need to know what the “active” pull request is that’s being reviewed, and we’re thinking the best way to do that is based on the URI of the active editor. Very open to other ideas, though!
2. Allow a user to click in our diagram to open the diff view of any file in the pull request. For this, we need a way to open the correct diff view for each file, just as it would be opened by the github pr extension.

We see two scenarios for how a user might interact with our extension and the github pr extension

1) Checking out a review branch

- User checks out the branch they want to review
- User opens our Review Map diagram
  - We look at the local branch information and determine the PR we are on and all the information we need to display the diagram
- User double clicks on a file in the diagram to open the diff for that file
  - We get the file path they clicked on and call the proposed `openDiff()` api with the filepath, pr number, and repo rootUri
- The user is now in github pr extension land and can review the file like normal

2) User is exploring remote pull requests and opening the diffs from the github pr extension

- User opens up the github PR extensions's pull requests TreeView, expands the PR they want to review, and clicks on a fileChangeNode to open a file diff view
- while viewing that file, they want to view it in our diagram
  - user does a cmd shift P and choses to open our diagram 
  - we call the proposed `getCurrentPullRequestInfo()` api to get the repository and PR number
  - we use this information to display our diagram
- User clicks in our diagram to open a different file's diff
  - We grab the filepath of what they clicked on, combine it with the repository/pr that we have from the last step and call `openDiff()` 

Thank you for considering our proposal!

**Comment by deammer** [comment]
@LizardEatsFlies and I have made some progress on our extension.

We figured out how to glean some pull request information by accessing `editor.document.uri.scheme`. If that scheme is `"pr"`, we can parse a lot of context information:
```ts
const editor = vscode.window.activeTextEditor;
const {
  headCommit,
  baseCommit,
  prNumber,
  remoteName
} = JSON.parse(editor.document.uri.query);
```

This allowed us to make progress without the `getCurrentPullRequestInfo()` method we proposed.

To get around the lack of `openDiff()` method, we constructed some URIs manually and called the `vscode.diff` command:

```ts
const schemeParams = {
  headCommit,
  baseCommit,
  prNumber,
  remoteName,
  fileName,
  isBase: true,
  status: 3,
};

const baseURI = vscode.Uri.file(absoluteFilePath).with({
  scheme: "pr",
  path: absoluteFilePath,
  query: JSON.stringify(schemeParams),
});

schemeParams.isBase = false;
const headURI = vscode.Uri.file(absoluteFilePath).with({
  scheme: "pr",
  path: absoluteFilePath,
  query: JSON.stringify(schemeParams),
});

const shortFileName = path.basename(relativeFilePath);

// Open a diff view based on a PR selected in the GitHub extension panel
vscode.commands.executeCommand(
  "vscode.diff",
  baseURI,
  headURI,
  `${shortFileName} (Pull Request)`
);
```

**Comment by alexr00** [comment]
> `getCurrentPullRequestInfo(uri: string)`
I'm definitely amenable to this API, but I don't have time to work on it at the moment. This should probably return the following:
```
{
prNumber: number,
owner: string, // for this repo that would be "microsoft"
repository: string // for this repo that would be vscode-pull-request-github
{
``` 

`openDiff(filePath: string, pr: number, repoRootUri: Uri)`
I'm less sure of this API. What if the pr isn't a currently open pr?

**Comment by alexr00** [comment]
We don't plan to add this in the near future, so closing as out of scope!
