### ISSUE TITLE
Improve error message "Unable to find GitHub repository matching 'anka-213'"

### ISSUE THREAD

**Issue by anka-213** [microsoft/vscode-pull-request-github#3094]
Issue Type: <b>Bug</b>

## Steps to reproduce

1. Create a new branch on a fork and push the "publish branch" button in vs-code
2. Click yes on "do you want to create a pull request"
3. Fill in the details and press "Create"

## Results

I get the error message
```
Unable to find GitHub repository matching 'anka-213'.
```
(Or whatever your github user name is)

Additionally, in the UI for creating a pull request, the "Merge changes from" box only allows choosing the upstream. My fork is not an option, despite it existing on github and in the list of remotes.

## More info:
```
$ git remote -v
anka-213        git://github.com/anka-213/gf-ud.git (fetch)
anka-213        git://github.com/anka-213/gf-ud.git (push)
origin  git://github.com/GrammaticalFramework/gf-ud.git (fetch)
origin  git://github.com/GrammaticalFramework/gf-ud.git (push)
```

Extension version: 0.32.0
VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T15:49:28.381Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 4|
|Memory (System)|64.00GB (0.16GB free)|
|Process Argv|--crash-reporter-id 391e5f07-6e2a-42f9-a25c-b064ccd04680|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis300:30386381
vsaa593:30376534
vssld246:30386377

```

</details>

**Comment by alexr00** [comment]
By default, we only pay attention to remotes called `upstream` and `origin`. You can add additional remote using this setting:
```
"githubPullRequests.remotes": [
  "origin",
  "anka-213"
]
```

**Comment by anka-213** [comment]
Maybe we can resolve this issue by improving the error message to include how to fix it?

**Comment by alexr00** [comment]
@anka-213 fair request!

**Comment by anka-213** [comment]
Many thanks!

**Comment by Ark-kun** [comment]
> By default, we only pay attention to remotes called `upstream` and `origin`. You can add additional remote using this setting:
> 
> ```
> "githubPullRequests.remotes": [
>   "origin",
>   "anka-213"
> ]
> ```

What is the reasoning behind this behavior?
Why do you need an explicit list of remotes when the current branch already tracks a remote branch?

Why can't the extension just use the current remote branch?
