### ISSUE TITLE
Login not appearing

### ISSUE THREAD

**Issue by kingma-sbw** [microsoft/vscode-pull-request-github#3097]
Issue Type: <b>Bug</b>

Install Github pull request and issues, allow vscode to start
Open a folder and click the GitHub tool.

PULL REQUEST show "No git repositories found." / ISSUES shows "Loading..."

Extension version: 0.32.0
VS Code version: Code 1.62.1 (f4af3cbf5a99787542e2a30fe1fd37cd644cc31f, 2021-11-05T10:57:55.946Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (4.93GB free)|
|Process Argv|--open-url --crash-reporter-id 5ccd64c1-f953-4adb-8583-a4619d21d2b5 -- vscode:extension/GitHub.vscode-pull-request-github|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200:30386379
vsaa593cf:30376535
vssld246cf:30386378

```

</details>

**Comment by ESKYoung** [comment]
@kingma-sbw - [not sure if this is similar, but Git on my remote instances kept hanging](https://github.com/microsoft/vscode-pull-request-github/issues/3098#issuecomment-966884912). Turns out it's a bug in VS Code 1.62.1.
