### ISSUE TITLE
ssh ignores current users .ssh folder

### ISSUE THREAD

**Issue by theking2** [microsoft/vscode-pull-request-github#3099]
To keep track of multiple accounts a custom ssh configuration is uesd with 
sample
```
Host github.com
	HostName github.com
	User git
	IdentityFile ~/.ssh/id_ed25519_normal

Host github-special.com
	HostName github.com
	User git
	IdentityFile ~/.ssh/id_ed25519_special
```

pull-request-github complaints about connection git@github-special.com;user/repo.git

**Comment by alexr00** [comment]
Can you give an example of the complaint?

**Comment by theking2** [comment]
Login not possible

**Comment by alexr00** [comment]
I don't see the error "Login not possible" anywhere in this extension code base or microsoft/vscode. Can you share a screenshot?

**Comment by theking2** [comment]
the complete text:
`Fetching pull requests for remote 'origin' failed, please check if the url git@github-theking2.com:theking2/dwh_php7.git is valid.` 

Integrated source control has no problem.
```
git remote --verbose
dwh-php7        https://github.com/theking2/dwh_php7.git (fetch)
dwh-php7        https://github.com/theking2/dwh_php7.git (push)
origin  git@github-theking2.com:theking2/dwh_php7.git (fetch)
origin  git@github-theking2.com:theking2/dwh_php7.git (push)
```

**Comment by theking2** [comment]
config in (-join($Env:USERPROFILE)) /.ssh

# theking2 account git@github-theking2.com:theking2/repo-name
```
Host github-theking2.com
        HostName github.com
        User git
        IdentityFile ~/.ssh/id_ed25519
```

**Comment by DirtySoc** [comment]
I'm not sure this is the exact same issue, but may be in a similar vein...

I have multiple GitHub accounts I use (Personal & Work). When logged in to the extension with my personal GH account and try to access a work repo I get the error: `Fetching pull requests for remote 'origin' failed, please check if the url git@my-org/work-repo.git is valid.`

Is there a way to login to GitHub PR Extension with more than one GitHub account? Or configure it to accept different credentials for different repos?

**Comment by theking2** [comment]
@DirtySoc it is possible to work with mulitple github accounts exactly in the way I described. If I clone from my 'normal' account I use:
`git clone git@github.com:user1/proj1.git`

if I clone from my special account I use:
`git@github-special.com:user2/proj2.git`


This works in `Source Control`in vscode as:
```
git remote --verbose
origin  git@github-special.com:user2/proj2.git (fetch)
origin  git@github-special.com:user2/proj2.git (push)

```
Unfortunately Pull Requests ignores the settins in .ssh/config and always uses a fixed github.com (git@github.com:user2/proj2.git).

**Comment by roisafirorichard** [comment]
I also have the same issue, I use multiple accounts one personal and another one for work, I clone using my personal. account by adding `-personal` to `git@github.com:xxxx/xxxx.git` and it becomes `git@github-personal.com:xxxx/xxxx.git`. 

apparently the extension doesn't support that and as a result I get the same error message 

```
Fetching pull requests for remote 'origin' failed, please check if the url git@github-personal.com:xxxx/xxxxx.git is valid.
```

please have a look at this.
