### ISSUE TITLE
Comments panel is flaky

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-pull-request-github#31]
I don't really understand when the comments panel is supposed to show comments.

It doesn't show when I open a PR's description, which definitely has comments:

<img width="1796" alt="screen shot 2018-06-26 at 16 02 42" src="https://user-images.githubusercontent.com/22350/41917307-5e9bd266-795a-11e8-81c0-333087e3ce48.png">

It also doesn't seem to show them when I open a change:

<img width="1796" alt="screen shot 2018-06-26 at 16 02 31" src="https://user-images.githubusercontent.com/22350/41917299-571b0d2c-795a-11e8-9671-952d230b7ae2.png">

**Comment by joaomoreno** [comment]
Got it, it showed comments once I checked out the PR...

**Comment by kieferrm** [comment]
Correct. It shows the comments on whatever is in your workspace. Need to make this more clear.

**Comment by RMacfarlane** [comment]
Closing out some old issues, I think we are unlikely to change this behavior
