### ISSUE TITLE
Pull request comment segment stuck on old branch

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode-pull-request-github#3100]
Reporting from a stable GitHub Codespace.

Steps to Reproduce:

1. Opened a pull request (_447_) in a codespace
2. Did another fix that I didn't want in my pull request, so I stashed it and put it on a new branch.
3. Created a pull request (_459_) for the new branch.

Results: Some of the UI state is stuck with the old pull request (lower left panel), while others show the new pull request.

![image](https://user-images.githubusercontent.com/8599/141510772-74c2420a-ac1f-48f6-9d77-3a338b8b9dbc.png)

**Comment by alexr00** [comment]
To verify: 
- Checkout a branch with a PR
- Checkout your repos main branch
- From the command line or from git, but _not_ through the PR UI, checkout a different branch with a PR
- Verify that the PR focus view shows the correct title.
