### ISSUE TITLE
Multi-line comments cut off in overview

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode-pull-request-github#3101]
Not sure if this is the same underlying request as https://github.com/microsoft/vscode-pull-request-github/issues/1376, so please feel free to close if so.

I received user feedback that it'd be great if multi-line comments appeared for the full set of lines, rather than a subset, in case there is important context in earlier lines.

- I left a multi-line comment across lines 2-8 in this PR: https://github.com/ataridotcom/gh-static-e2e/pull/13
- When I opened the PR in [github.dev](https://github.dev/ataridotcom/gh-static-e2e/tree/Test11-12), it only appears for the last few lines (5-8)

Comment in gh.com, fully lines 2-8:
![image](https://user-images.githubusercontent.com/25310137/141512124-8f530c39-ac8a-4b33-b5e0-05425d00bff9.png)

Comment on GHPRI overview page, only appears for lines 5-8:
![image](https://user-images.githubusercontent.com/25310137/141512152-d0d4d96f-f386-4efc-96cb-a17524b3c0f4.png)

**Comment by alexr00** [comment]
Since this issue is about the way the comments show on the overview page, it is not the same as #1376.

**Comment by alexr00** [comment]
Looks like the max number of lines we show was 4. I've increased it to 8.
