### ISSUE TITLE
remote: Repository not found (only on VSCode)

### ISSUE THREAD

**Issue by begueradj** [microsoft/vscode-pull-request-github#3109]
Steps to Reproduce:

1. Create a private repository on Github 
2. Clone it
3. Commit any change and push it
4. I always get this error message: 
remote: Repository not found.
fatal: Authentication failed for 'https://github.com/begueradj/my_repository/'

Note:

This happens ONLY through VScode, i.e. I do not face this problem through the Ubuntu Terminal tool, for example

Environment:

Version: 1.62.2
Commit: 3a6960b964327f0e3882ce18fcebd07ed191b316
Date: 2021-11-11T20:51:30.084Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.4.0-90-generic snap

**Comment by BrianT71** [comment]
Confirming I have the same issue. Also on Ubuntu.

**Comment by pgroyal22** [comment]
Also having a similar issue, on Manjaro

**Comment by Hamburglar0650** [comment]
I'm having the same issue. I had to start using Github Desktop to Push/Pull.

**Comment by alexr00** [comment]
@begueradj can you share the following:
- a screen shot of the error
- the log output from "GitHub Pull Request"
- the log output from "Git"
- the log output from "GitHub Authentication"

**Comment by neelesh-dss** [comment]
I am also facing this issue on Windows 10 with vscode

**Comment by KirinyetBrian** [comment]
i am facing the same issue in Linux mint.It only happens on vs code

**Comment by luong-komorebi** [comment]
On my machine the error is close to this, where it also shows no remotes configured 
One error that I was able to find in the log but did not know what to do with it is `No response from host https://ssh.github.com/REDACTED/REDACTED: request to https://ssh.github.com/api/v3/rate_limit failed, reason: Client network socket disconnected before secure TLS connection was established` 


Github log (redact repository and org name)
```
[Info] Registering git provider
[Info] Looking for git repository
[Info] Found 1 repositories during activation
[Info] Git repository found, initializing review manager and pr tree view.
[Info] Review> Validate state in progress
[Info] Review> Validating state...
[Info] GitHubServer> No response from host https://ssh.github.com/REDACTED/REDACTED: request to https://ssh.github.com/api/v3/rate_limit failed, reason: Client network socket disconnected before secure TLS connection was established
[Info] No remote with name 'origin' found.
[Info] No remote with name 'upstream' found.
[Info] No GitHub remotes found
[Info] Review> no matching pull request metadata found for current branch development
[Info] Review> no matching pull request metadata found on GitHub for current branch development
[Info] Review> Queuing additional validate state
[Info] Review> Validating state...
[Info] No remote with name 'origin' found.
[Info] No remote with name 'upstream' found.
[Info] No GitHub remotes found
[Info] Review> no matching pull request metadata found for current branch development
[Info] Review> no matching pull request metadata found on GitHub for current branch development
```

Git log 
```
Validating found git in: /usr/local/bin/git
Using git 2.34.0 from /usr/local/bin/git
> git rev-parse --git-dir
Open repository: /Users/REDACTED/REDACTED/REDACTED-REDACTED
> git fetch
> git status -z -u
> git symbolic-ref --short HEAD
> git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track) refs/heads/development refs/remotes/development
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git check-ignore -v -z --stdin
> git config --get commit.template
> git config --global user.email
> git config --global user.name
> git status -z -u
> git symbolic-ref --short HEAD
> git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track) refs/heads/development refs/remotes/development
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git show -s --format=%an <%ae> [%ai] c8ad8107a293d0e0ad56d4874c491335c3b948dc
> git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%B -z c8ad8107a293d0e0ad56d4874c491335c3b948dc
> git show -s --format=%an <%ae> [%ai] 82ca97e2f2d6d5a669f29010b10c712498eaa728
> git show -s --format=%an <%ae> [%ai] 7e1d16c22a29152bcef6b04c08f892b59f8015d4
> git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%B -z 82ca97e2f2d6d5a669f29010b10c712498eaa728
> git show -s --format=%an <%ae> [%ai] 37b5bd1782a3ccf4528611237bbedf9477c0913b
> git show -s --format=%an <%ae> [%ai] 3d5a4f90055dbd1a6d52af1ac15f85ae0a77755e
> git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%B -z 7e1d16c22a29152bcef6b04c08f892b59f8015d4
> git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%B -z 37b5bd1782a3ccf4528611237bbedf9477c0913b
> git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%B -z 3d5a4f90055dbd1a6d52af1ac15f85ae0a77755e
> git show -s --format=%an <%ae> [%ai] 95b037f1f2550315796650b378c97a911061efdf
> git show -s --format=%an <%ae> [%ai] 8ce38e191bbcf187ea6f211ebb1c5fb107b536dc
> git show -s --format=%an <%ae> [%ai] 8b3fe94f8835f3c24773acc952b8f8b17b222c3f
> git show -s --format=%an <%ae> [%ai] 34acf369deac5aef91bb231300c370e873c13954
> git show -s --format=%an <%ae> [%ai] e0404c5b3ea5be29b2d565baf121c72a88312773
> git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%B -z 8ce38e191bbcf187ea6f211ebb1c5fb107b536dc
> git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%B -z 8b3fe94f8835f3c24773acc952b8f8b17b222c3f
> git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%B -z 95b037f1f2550315796650b378c97a911061efdf
> git show -s --format=%an <%ae> [%ai] 7f37374cd05a33c565e2458ae381cf5e6024a109
> git show -s --format=%an <%ae> [%ai] d7b98883301e585c18ef5464bb7d5fdf666da7ce
> git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%B -z e0404c5b3ea5be29b2d565baf121c72a88312773
> git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%B -z 7f37374cd05a33c565e2458ae381cf5e6024a109
> git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%B -z 34acf369deac5aef91bb231300c370e873c13954
> git show -s --format=%an <%ae> [%ai] 88ee204ed0da40be30ac2b8a9b4dbaeea14bcc40
> git show -s --format=%an <%ae> [%ai] d86fa66b1ebd17651495b4f3a9d2f539e66e9998
> git show -s --format=%an <%ae> [%ai] f6817d131728d4ce9954e52551b15a279c387318
> git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%B -z d7b98883301e585c18ef5464bb7d5fdf666da7ce
> git show -s --format=%an <%ae> [%ai] 34acf369deac5aef91bb231300c370e873c13954
> git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%B -z d86fa66b1ebd17651495b4f3a9d2f539e66e9998
> git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%B -z f6817d131728d4ce9954e52551b15a279c387318
> git show -s --format=%an <%ae> [%ai] 5592d73738f9f4ce138f88ebab0d99a2e60364ec
> git show -s --format=%an <%ae> [%ai] ff983fae69b33ee752c932083cc5a3f907ea51d5
> git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%B -z 88ee204ed0da40be30ac2b8a9b4dbaeea14bcc40
> git show -s --format=%an <%ae> [%ai] 3922eb125b04c3af31e407058bea35a40cf55f09
> git show -s --format=%an <%ae> [%ai] 265e4c9393cf6790dcd7871fcf6cb13700e04c66
> git show -s --format=%an <%ae> [%ai] ee4257a5a3dacdec89633653ddc4654fcf4b4cdd
> git show -s --format=%an <%ae> [%ai] a77ea67dcd828939c252e6b36148d389902848da
> git show -s --format=%an <%ae> [%ai] 88ee204ed0da40be30ac2b8a9b4dbaeea14bcc40
> git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%B -z 5592d73738f9f4ce138f88ebab0d99a2e60364ec
> git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%B -z 34acf369deac5aef91bb231300c370e873c13954
> git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%B -z ee4257a5a3dacdec89633653ddc4654fcf4b4cdd
> git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%B -z 265e4c9393cf6790dcd7871fcf6cb13700e04c66
> git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%B -z 3922eb125b04c3af31e407058bea35a40cf55f09
> git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%B -z ff983fae69b33ee752c932083cc5a3f907ea51d5
> git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%B -z a77ea67dcd828939c252e6b36148d389902848da
> git show -s --format=%an <%ae> [%ai] c6155e104a8526c0526930b7631b216ffbc9ada5
> git show -s --format=%an <%ae> [%ai] 7e1daf019c3d1febf400e98189d6584fa36d3a3c
> git show -s --format=%an <%ae> [%ai] ff983fae69b33ee752c932083cc5a3f907ea51d5
> git show -s --format=%an <%ae> [%ai] ad1ecd4c97fc3ceb80f3d81d0265c5b4295d2de9
> git show -s --format=%an <%ae> [%ai] 16db38c90e1f0a81de4f2c66680ede44181724e8
> git show -s --format=%an <%ae> [%ai] 18cbc37a3823ad95ab68668f83500d5b7a9e5f39
> git show -s --format=%an <%ae> [%ai] ff983fae69b33ee752c932083cc5a3f907ea51d5
> git show -s --format=%an <%ae> [%ai] f2a46292e6b8db20b2196c0718ef6dcb7fbed4bb
> git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%B -z 88ee204ed0da40be30ac2b8a9b4dbaeea14bcc40
> git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%B -z c6155e104a8526c0526930b7631b216ffbc9ada5
> git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%B -z 7e1daf019c3d1febf400e98189d6584fa36d3a3c
> git show -s --format=%an <%ae> [%ai] 512dd99cdde64bd79cb83acb6f895bcb3efcf0ee
> git show -s --format=%an <%ae> [%ai] 45e0018d81e726b451aef62765accd14b70ae3ff
> git show -s --format=%an <%ae> [%ai] 5592d73738f9f4ce138f88ebab0d99a2e60364ec
> git show -s --format=%an <%ae> [%ai] ff983fae69b33ee752c932083cc5a3f907ea51d5
> git show -s --format=%an <%ae> [%ai] a6d8e746030d7baf94621b01af5e81a69906ed99
> git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%B -z 18cbc37a3823ad95ab68668f83500d5b7a9e5f39
> git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%B -z ff983fae69b33ee752c932083cc5a3f907ea51d5
> git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%B -z 16db38c90e1f0a81de4f2c66680ede44181724e8
> git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%B -z ad1ecd4c97fc3ceb80f3d81d0265c5b4295d2de9
> git show -s --format=%an <%ae> [%ai] 40a3bbfd0a6210ba794ef7936399f08d49eb4d3b
> git show -s --format=%an <%ae> [%ai] f4eddd89aed7e8af511a57db6f91493b36f47bdc
> git show -s --format=%an <%ae> [%ai] 8565722f54d34518caccf5e960ec482478830824
> git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%B -z ff983fae69b33ee752c932083cc5a3f907ea51d5
> git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%B -z f2a46292e6b8db20b2196c0718ef6dcb7fbed4bb
> git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%B -z ff983fae69b33ee752c932083cc5a3f907ea51d5
> git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%B -z 512dd99cdde64bd79cb83acb6f895bcb3efcf0ee
> git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%B -z 45e0018d81e726b451aef62765accd14b70ae3ff
> git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%B -z a6d8e746030d7baf94621b01af5e81a69906ed99
> git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%B -z 5592d73738f9f4ce138f88ebab0d99a2e60364ec
> git show -s --format=%an <%ae> [%ai] c6155e104a8526c0526930b7631b216ffbc9ada5
> git show -s --format=%an <%ae> [%ai] 7e1daf019c3d1febf400e98189d6584fa36d3a3c
> git show -s --format=%an <%ae> [%ai] 512dd99cdde64bd79cb83acb6f895bcb3efcf0ee
> git show -s --format=%an <%ae> [%ai] 45e0018d81e726b451aef62765accd14b70ae3ff
> git show -s --format=%an <%ae> [%ai] 3671588804f57d303e2e6ed98b968b2f8020c6c4
> git show -s --format=%an <%ae> [%ai] 30601eb7a88d2a3be529b7d97f24491c68a6968c
> git show -s --format=%an <%ae> [%ai] 69cbf4f47dda08358aebdfd2d08c318fe420308d
> git show -s --format=%an <%ae> [%ai] 05f8378fe58eab37ff2c1ecd77ebd398af3f0ead
> git show -s --format=%an <%ae> [%ai] 193b02603757f4550ce8945cbb8102f292c5ac49
> git show -s --format=%an <%ae> [%ai] 512dd99cdde64bd79cb83acb6f895bcb3efcf0ee
> git show -s --format=%an <%ae> [%ai] 45e0018d81e726b451aef62765accd14b70ae3ff
> git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%B -z 8565722f54d34518caccf5e960ec482478830824
> git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%B -z f4eddd89aed7e8af511a57db6f91493b36f47bdc
> git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%B -z 40a3bbfd0a6210ba794ef7936399f08d49eb4d3b
> git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%B -z 3671588804f57d303e2e6ed98b968b2f8020c6c4
> git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%B -z c6155e104a8526c0526930b7631b216ffbc9ada5
> git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%B -z 7e1daf019c3d1febf400e98189d6584fa36d3a3c
> git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%B -z 193b02603757f4550ce8945cbb8102f292c5ac49
> git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%B -z 05f8378fe58eab37ff2c1ecd77ebd398af3f0ead
> git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%B -z 512dd99cdde64bd79cb83acb6f895bcb3efcf0ee
> git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%B -z 30601eb7a88d2a3be529b7d97f24491c68a6968c
> git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%B -z 45e0018d81e726b451aef62765accd14b70ae3ff
> git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%B -z 69cbf4f47dda08358aebdfd2d08c318fe420308d
> git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%B -z 512dd99cdde64bd79cb83acb6f895bcb3efcf0ee
> git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%B -z 45e0018d81e726b451aef62765accd14b70ae3ff
> git config --local branch.development.github-pr-owner-number
> git status -z -u
> git symbolic-ref --short HEAD
> git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track) refs/heads/development refs/remotes/development
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git status -z -u
> git symbolic-ref --short HEAD
> git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track) refs/heads/development refs/remotes/development
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git show --textconv :app/models/tableless.rb
> git ls-files --stage -- /Users/REDACTED/REDACTED/REDACTED-REDACTED/REDACTED/REDACTED/tableless.rb
> git check-ignore -v -z --stdin
> git cat-file -s cc19faf6f88ec03f1cab5f89654c5157ad287ea0
> git status -z -u
> git symbolic-ref --short HEAD
> git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track) refs/heads/development refs/remotes/development
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git fetch
From github.com:REDACTED/REDACTED
 - [deleted]                 (none)     -> origin/chore/REDACTED-45
   de5579686fd..616211d02a8  development -> origin/development
> git status -z -u
> git symbolic-ref --short HEAD
> git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track) refs/heads/development refs/remotes/development
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git config --local branch.development.github-pr-owner-number
```

Github authentication log 
```
[Info  - 03:21:09.764] Reading sessions from keychain...
[Info  - 03:21:09.941] Getting sessions for all scopes...
[Info  - 03:21:09.941] Getting sessions for all scopes...
[Trace  - 03:21:09.941] Token acquired from secret storage.
[Info  - 03:21:09.941] Got stored sessions!
[Trace  - 03:21:09.941] Read the following session from the keychain with the following scopes: user:email
[Trace  - 03:21:09.941] Read the following session from the keychain with the following scopes: repo
[Trace  - 03:21:09.941] Read the following session from the keychain with the following scopes: read:user,user:email,repo
[Trace  - 03:21:09.941] Read the following session from the keychain with the following scopes: read:user,user:email
[Trace  - 03:21:09.941] Read the following session from the keychain with the following scopes: repo,workflow
[Info  - 03:21:09.943] Got 5 verified sessions.
[Info  - 03:21:09.943] Got 5 sessions for all scopes...
[Info  - 03:21:09.943] Got 5 sessions for all scopes...
[Info  - 03:21:10.458] Getting sessions for read:user,user:email,repo...
[Info  - 03:21:10.458] Got 1 sessions for read:user,repo,user:email...
[Info  - 03:21:10.465] Getting sessions for read:user,user:email,repo...
[Info  - 03:21:10.465] Got 1 sessions for read:user,repo,user:email...
[Info  - 03:21:10.720] Getting sessions for read:user,user:email...
[Info  - 03:21:10.720] Got 1 sessions for read:user,user:email...
[Info  - 03:21:11.59] Getting sessions for repo...
[Info  - 03:21:11.65] Got 1 sessions for repo...
```

**Comment by alexr00** [comment]
@luong-komorebi what were you doing when you saw the error notification? What was the exact text of the error notification?

**Comment by luong-komorebi** [comment]
@alexr00 thanks for the prompt response. I was clicking on the github icon. My intention was to review pull requests 
![image](https://user-images.githubusercontent.com/15828926/143223209-4239a1cf-4436-44e7-96c6-7f2f0697d1ff.png)
The exact error message is `no remotes match the current setting`. Not sure if it falls under this issue or I should create a new one.

**Comment by alexr00** [comment]
@luong-komorebi this is a different issue; however, it looks like you might just need to add your remotes to `githubPullRequests.remotes`.

**Comment by Vasu-Vijay** [comment]
Same issue, anyone got any solutions?

**Comment by sylar123abc** [comment]
Hi everyone got the same problem and solved it out, 

- First you have to create a personal access token (settings > developper settings > personal access token)
- Then you have to update the url of your local config to put your token : 
```
cd /path/to/your/repo
nano .git/config
```

then you'll have an url under the origin section (looks like this)

```
[remote "origin"]
	url = https://github.com/username/repo.git
```

here just change the url by : 
```
[remote "origin"]
	url = https://<username>:<personalToken>@github.com/username/repo.git
```

Then it should work :) hope it helped

NB: make sure to use https

**Comment by RoyceOnRolls** [comment]
@sylar123abc  Thanks you so much! This solved the issue :+1:

**Comment by zack-dev-cm** [comment]
works for me without <username>:
[remote "origin"]
	url = https://<personalToken>@github.com/username/repo.git

**Comment by vergil250493** [comment]
> https://<username>:<personalToken>@github.com/username/repo.git

Thank this was usefull solved my problem before was working fine but just random stop following this method worked.

**Comment by JoshWhite** [comment]
> works for me without `<username>` in the beginning:
> 
> ```
> [remote "origin"]
> 	url = https://<personalToken>@github.com/username/repo.git
> ```

This works well on a repo per repo basis, but if your organisation has loads of repos it can get quite tiresome. 

If you install [Github CLI](https://cli.github.com/), run `gh auth login` and sign in via the browser, you should be able to access all your repos 👍

**Comment by samleemc** [comment]
the trick worked. But what has changed? My VSC worked perfectly previously, but why suddenly we need to manually change the config file for it to work? Can we fix it at the extension/VSC level so that we don't need to update every repo config?

**Comment by eugeneniemand** [comment]
I installed GH CLI and still authenticated from a terminal on Windows. Restarted VS Code and tried to push and received the same error. Next I tried running GH CLI on PS & CMD terminal in VS Code and it just says `gh: The term 'gh' is not recognized as a name of a cmdlet....` eventually I changed the .git/config as suggested above and that solved the error and now it works.

**Comment by durayakar** [comment]
Version: 1.75.1 (system setup)
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:32:34.589Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

I am here, because after a few VS Code updates, the The GitHub repo that I cloned with VS Code and updated several times started to fail with this same error today. It has been a few months since I updated this repo. I regularly update VS Code, so I do not have the version number that worked. 
I used https, not ssh. Therefore, I did not have to deal with PAT. 

1. I cloned the repo using VS Code. Why would I need to manually change the remote origin url? 
2. If the remote origin url was wrong to begin with, how did VS code authenticate and pull my repo in the first place?
3. I am able to create a pull request and an issue via the GitHub extension, so my GitHub credentials are recognized. 
4. GitHub Desktop works. If I open side by side VS Code and GitHub Desktop, I can work in VS Code, and then manage the repo in GitHub Desktop - sub-par experience, isn't it?   
5. I also have CoPilot, using it with the same GitHub account inside VS Code. That started to take too long to log me in and offer "another way" to log in. 
6. Can you please fix this VS Code bug?

**Comment by durayakar** [comment]
> > works for me without `<username>` in the beginning:
> > ```
> > [remote "origin"]
> > 	url = https://<personalToken>@github.com/username/repo.git
> > ```
> 
> This works well on a repo per repo basis, but if your organisation has loads of repos it can get quite tiresome.
> 
> If you install [Github CLI](https://cli.github.com/), run `gh auth login` and sign in via the browser, you should be able to access all your repos 👍

That works for me as well. So, is GitHub CLI (gh) a requirement to use GitHub repos with VS Code now?

**Comment by alexr00** [comment]
@durayakar GitHub CLI is not a requirement!

I would guess that your auth token has lost some permissions in the time since you last opened the repo. Could you share the output from "GitHub Pull Request". And then, can you try signing out of VS Code with your GitHub account then signing in again?

**Comment by miguelgargallo** [comment]
> > > works for me without `<username>` in the beginning:
> > > ```
> > > [remote "origin"]
> > > 	url = https://<personalToken>@github.com/username/repo.git
> > > ```
> > 
> > 
> > This works well on a repo per repo basis, but if your organisation has loads of repos it can get quite tiresome.
> > If you install [Github CLI](https://cli.github.com/), run `gh auth login` and sign in via the browser, you should be able to access all your repos +1
> 
> That works for me as well. So, is GitHub CLI (gh) a requirement to use GitHub repos with VS Code now?

thanks

**Comment by Alok5102S** [comment]
@samleemc Thanks it's really helpful

**Comment by qoodanny** [comment]
same issue

**Comment by alboteanud** [comment]
just to make it clear, the config looks like this:
[remote "origin"]
	url = https://ghp_IUIU64e9CjVTBkTgWPQ...K07A5yz@github.com/alboteanud/myTestRepo.git

**Comment by wsp-backis** [comment]
I can confirm that the trick with PAT in the config file works, but I found that the config file is world readable in Ubuntu 20.04 and WSL2. This is a issue with the PAT since it could be quite powerful and access most things in your Github repo. The solution is simple: use chmod to restrict access
`chmod 0600 config` 
It seems to work in both VS Code as well as bash prompt.

**Comment by ianvinkWD** [comment]
2024 update:

install the GitHub CLI from https://cli.github.com/ , reboot, and then open VS Code.

Run this in the terminal in VS Code

**gh auth login**

then follow the default prompts

You should be then good to go @maruarcus

**Comment by Charlesbasis** [comment]
using Github cli in vscode, worked for me

**Comment by IdealistCat** [comment]
> Hi everyone got the same problem and solved it out,
> 
> * First you have to create a personal access token (settings > developper settings > personal access token)
> * Then you have to update the url of your local config to put your token :
> 
> ```
> cd /path/to/your/repo
> nano .git/config
> ```
> 
> then you'll have an url under the origin section (looks like this)
> 
> ```
> [remote "origin"]
> 	url = https://github.com/username/repo.git
> ```
> 
> here just change the url by :
> 
> ```
> [remote "origin"]
> 	url = https://<username>:<personalToken>@github.com/username/repo.git
> ```
> 
> Then it should work :) hope it helped
> 
> NB: make sure to use https

how do i do that.

**Comment by IdealistCat** [comment]
> > Hi everyone got the same problem and solved it out,
> > 
> > * First you have to create a personal access token (settings > developper settings > personal access token)
> > * Then you have to update the url of your local config to put your token :
> > 
> > ```
> > cd /path/to/your/repo
> > nano .git/config
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > then you'll have an url under the origin section (looks like this)
> > ```
> > [remote "origin"]
> > 	url = https://github.com/username/repo.git
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > here just change the url by :
> > ```
> > [remote "origin"]
> > 	url = https://<username>:<personalToken>@github.com/username/repo.git
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then it should work :) hope it helped
> > NB: make sure to use https
> 
> how do i do that. how do i make a personal access token

nevermind

**Comment by dzalf** [comment]
> Hi everyone got the same problem and solved it out,
> 
> * First you have to create a personal access token (settings > developper settings > personal access token)
> * Then you have to update the url of your local config to put your token :
> 
> ```
> cd /path/to/your/repo
> nano .git/config
> ```
> 
> then you'll have an url under the origin section (looks like this)
> 
> ```
> [remote "origin"]
> 	url = https://github.com/username/repo.git
> ```
> 
> here just change the url by :
> 
> ```
> [remote "origin"]
> 	url = https://<username>:<personalToken>@github.com/username/repo.git
> ```
> 
> Then it should work :) hope it helped
> 
> NB: make sure to use https

For those still struggling despite this detailed solution, please note that if you are trying to sync a repository from an organization you own, fine-grained tokens might not work.

In my case, I solved it by creating a _classic token_ assigning it to the organization then replacing the `<username>` and `<personalToken>` as mentioned and the last part of the link (`@github.com/username/repo.git`) must be the link to the repo from your organization.

I hope this helps

**Comment by kissme666** [comment]
> 2024 update:
> 
> install the GitHub CLI from https://cli.github.com/ , reboot, and then open VS Code.
> 
> Run this in the terminal in VS Code
> 
> **gh auth login**
> 
> then follow the default prompts
> 
> You should be then good to go [@maruarcus](https://github.com/maruarcus)

It's userful for me.
Thanks.

**Comment by kusallivezen** [comment]
> > Hi everyone got the same problem and solved it out,
> > 
> > * First you have to create a personal access token (settings > developper settings > personal access token)
> > * Then you have to update the url of your local config to put your token :
> > 
> > ```
> > cd /path/to/your/repo
> > nano .git/config
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > then you'll have an url under the origin section (looks like this)
> > ```
> > [remote "origin"]
> > 	url = https://github.com/username/repo.git
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > here just change the url by :
> > ```
> > [remote "origin"]
> > 	url = https://<username>:<personalToken>@github.com/username/repo.git
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then it should work :) hope it helped
> > NB: make sure to use https
> 
> how do i do that. how do i make a personal access token

This worked for me also.
Thank you

**Comment by progmars** [comment]
Using PAT in the URL is not a solution but a workaround - it's not a good practice to keep PATs in the URL.
So, it should be solved somehow properly.
I have the same issue - a repo that has been working just fine suddenly stopped working after a VSCode update.

```
> git push -u origin main [766ms]
remote: Repository not found.
fatal: repository 'https://github.com/myuser/myrepo.git/' not found
```

I have no idea what the problem is. That / after .git looks suspicious though, should it really be there?

I have tried logging out and in through VSCode, and it worked. When I use Remote - Add remote menu command, it can find the remote repository just fine. So why suddenly can't it push to it?
