### ISSUE TITLE
Marked file as viewed failed: TypeError: Cannot read properties of undefined (reading 'pullRequest')

### ISSUE THREAD

**Issue by dtinth** [microsoft/vscode-pull-request-github#3129]
When triggering the **GitHub Pull Requests: Mark File As Viewed** from the command palette, the extension shows an error message.

- Extension version: v0.32.0
- VSCode Version: 1.62.3
- OS: Web

Steps to Reproduce:

1. Open **Command Palette** 
2. Run **GitHub Pull Requests: Mark File As Viewed**

Expected Result: The currently reviewing file is marked as viewed.

Actual Result:
![image](https://user-images.githubusercontent.com/193136/142978828-aa349eb7-2437-421c-859b-f0a923c1ad40.png)

**Comment by alexr00** [comment]
That command shouldn't be available in the command palette. It's only intended to be used in the "Changes in PR" view.

**Comment by ConstNW** [comment]
> That command shouldn't be available in the command palette. It's only intended to be used in the "Changes in PR" view.

It's not even worked in the "Changes in PR" view.

![image](https://user-images.githubusercontent.com/470927/200884936-2a17124f-cfd3-4d17-9b51-9b1ea28f8464.png)

![image](https://user-images.githubusercontent.com/470927/200884963-c38e2bc7-f263-484d-ba5c-0f8176d953e9.png)

**Comment by alexr00** [comment]
This is an upstream issue in VS Code, where keyboard shortcuts don't really work on extension provided tree items: https://github.com/microsoft/vscode/issues/72442
