### ISSUE TITLE
Making a comment and switch editor to another and back will hide the comment and break the gutter

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-pull-request-github#313]
Repro:

1. Write out a comment (don't press the comment button)
2. ctrl+tab
3. ctrl+tab

The comment is hidden, unpublished and clicking on the gutter does nothing:

![image](https://user-images.githubusercontent.com/2193314/44753382-b026ff80-aad2-11e8-9f1a-04a81166e509.png)

**Comment by RMacfarlane** [comment]
Since the gutter issue has been mitigated, let's track this in https://github.com/Microsoft/vscode-pull-request-github/issues/215
