### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Im1Bear** [microsoft/vscode-pull-request-github#3137]
- Issue Type: `Bug`
- Extension Name: `vscode-pull-request-github`
- Extension Version: `0.32.0`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.62.3`

:warning: We have written the needed data into your clipboard. Please paste!
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 185,
		"activateCallTime": 1,
		"activateResolvedTime": 4465,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "GitHub.vscode-pull-request-github",
				"_lower": "github.vscode-pull-request-github"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": [],
	"runningLocation": 1
}
```
 :warning:

**Comment by alexr00** [comment]
@Im1Bear can you please describe the issue you were seeing?

**Comment by Im1Bear** [comment]
> @Im1Bear can you please describe the issue you were seeing?

I don't know it anymore so you can close the Issue.
