### ISSUE TITLE
Collapse All Comments command shows up for every extension's comments

### ISSUE THREAD

**Issue by SanderRonde** [microsoft/vscode-pull-request-github#3140]
- Extension version: 0.32.0
- VSCode Version: 1.62.3
- OS: Windows 10

Steps to Reproduce:

1. Use any other extension that makes use of the VSCode comments API
2. See this extension's "Collapse All Comments" button show up.

The issue is that this command which the extension contributes isn't restricted to comment threads that are controlled by just this extension. Instead, it shows up on every comment thread. This makes this button (controlled by the GH extension) a no-op (since it only controls GH threads) and possibly a duplicate (since other extensions tend to implement something similar as well). The issue is around this line: https://github.com/microsoft/vscode-pull-request-github/blob/d5457f92f2903802b17ee5811432e745ecf7169a/package.json#L1405 Other commands have `"when": "commentController =~ /^github-(browse|review)/"` but this one does not.

If you'd like I can make the PR myself since it's such an easy fix. Let me know.

**Comment by alexr00** [comment]
Thanks for reporting this!
