### ISSUE TITLE
Pre-release flow issues

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#3145]
Opened VS Code just now and saw this:

![image](https://user-images.githubusercontent.com/2193314/143971328-5543510e-46bc-469c-98ab-41470f5387c1.png)

Clicked the button and got:

![image](https://user-images.githubusercontent.com/2193314/143971364-d08a09a8-1635-416c-b2d5-3c1bf496483d.png)

Version:

![image](https://user-images.githubusercontent.com/2193314/143971391-747f8257-dd7f-4ccb-afb9-d3659598d029.png)

Messages:

![image](https://user-images.githubusercontent.com/2193314/143971405-459f1d1a-cafc-4898-ad4f-6d680502a6b2.png)

Nightly is activated, disabled and needs a reload:

![image](https://user-images.githubusercontent.com/2193314/143971429-17699deb-b593-49d5-9f0b-84620f1fa496.png)

**Comment by IllusionMH** [comment]
Had same problem, but in my case GHPRaI is was not installed at all and my expectation was that installation will be triggered or, maybe better, action in message should guide me to extension details page so I can install install it without search.

**Comment by Tyriar** [comment]
This was a problem in yesterday's build apparently
