### ISSUE TITLE
Invalid PR should not cause a notification

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-pull-request-github#3152]
Testing #3144

![image](https://user-images.githubusercontent.com/900690/144210807-828be050-4b55-4ebb-a62e-dd0796aee189.png)

I would have expected a modal dialog or better, to indicate the PR is not available from the picker.

**Comment by bpasero** [comment]
I typed in a string ("kasdkasjdkj") but the dialog shows "0":

![image](https://user-images.githubusercontent.com/900690/144594841-f38ea5d6-4fd1-475c-b31b-1c94ba399fbf.png)

**Comment by alexr00** [comment]
I broke the validation regex. Fix will be available Monday.

**Comment by alexr00** [comment]
@rzhao271 are you sure you were on the latest pre-release version? You should be unable to choose a PR if you just enter letters.

![image](https://user-images.githubusercontent.com/38270282/144996189-dcf81391-8656-4261-a8fa-76d0bd18677c.png)

**Comment by rzhao271** [comment]
Got it this time
