### ISSUE TITLE
Expected PR number to ignore hash

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode-pull-request-github#3156]
Testing #3144

I copied a number from the web and pasted it, expecting for it to be "smart" and ignore the #. This would be a nice "delighter" and save extra steps even though overtime you would learn that you can't use the #.

![image](https://user-images.githubusercontent.com/35271042/144278618-c827c6ff-3dfe-4218-a489-ecdadb5ea229.png)

**Comment by joyceerhl** [comment]
Still repros, guessing the fix hasn't shipped yet? 
![image](https://user-images.githubusercontent.com/30305945/144515875-70685813-6986-42a2-84ce-9c459bf42869.png)

**Comment by alexr00** [comment]
Correct, the daily pre-release build occurs around 10am CET.
