### ISSUE TITLE
Prompt user to sign in when logged out and running command

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode-pull-request-github#3157]
Testing #3144

<img width="643" alt="CleanShot 2021-12-01 at 09 14 10@2x" src="https://user-images.githubusercontent.com/35271042/144281530-efdc8937-49da-4ca4-83b6-4d2896cec61d.png">

When you sign out of the extension and run the "Check Out" command, the quick pick is in an odd state where it's asking what repository I want to use. I would've expected for the extension to prompt me to sign in and then show the quick pick to select the pr.

**Comment by alexr00** [comment]
The command should be hidden in this case.
