### ISSUE TITLE
t is not iterable for assignee + button

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode-pull-request-github#3161]
Testing https://github.com/microsoft/vscode-pull-request-github/issues/3132

Steps:
Same as https://github.com/microsoft/vscode-pull-request-github/issues/3132#issuecomment-977986006, but use the + to try and add an assignee.

**Comment by joyceerhl** [comment]
Still seeing this in insiders.vscode.dev, will wait for nightly GHPRI
![image](https://user-images.githubusercontent.com/30305945/144659528-c8cea1d6-ee2c-4fde-adcd-22704ae3951e.png)
