### ISSUE TITLE
[Feature] Auto-create remote when attempting to check out a PR from a fork

### ISSUE THREAD

**Issue by lougreenwood** [microsoft/vscode-pull-request-github#3162]
## Context

Our repo setup requires contributors to fork the base repo and work in branches on their fork. Contributors then create a PR from fork branches against the base repo master branch.

### Problem

This means that a user of this addon who is also using the workflow described above needs to manually manage remotes for all contributors - otherwise, when trying to checkout a branch, the user sees an error that they need to create a remote for the fork (this is quite a cryptic error too, since it's only in the logs, and the logs quickly fill with junk leaving the message scrolled out of the console buffer).

### Solution

Ideally this addon would prompt a user that a remote does not exist which corresponds to this PR and would the user like to create that remote. If the user answers yes, the remote is added to the git config.

### Benefits

This will help to create a more seamless workflow. I imagine it would be especially useful for open source repos where a list of contributors is not known ahead of time, or for large organisations where manually creating a list of remotes for every contributor is not feasible.

### Notes

Perhaps the addon could also remove the auto-generated remote after completing the PR review to keep the user's git config clean.

**Comment by alexr00** [comment]
Remotes should automatically be added when you checkout a PR from the "Pull Requests" view. If you're not seeing that happen then please ping the issue and I will investigate!
