### ISSUE TITLE
Every time I open a new instance of vscode I'm being prompted to sign in to GitHub

### ISSUE THREAD

**Issue by ryan-efendy** [microsoft/vscode-pull-request-github#3165]
- Extension version: v0.33.2021120309
- VSCode Version: 1.63.0-insider Commit: cca3e817a2608225d4ae8715308195c91 1765bad
- OS: macOS Big Sur Version 11.5.2

every time I open a new instance of vscode (insider) I'm being prompted to sign in to GitHub:
![image](https://user-images.githubusercontent.com/12979345/144631592-f8a32171-d2bc-4c08-b430-1535fa0a2f23.png)

**Comment by alexr00** [comment]
@ryan-efendy are you signed in?

**Comment by ryan-efendy** [comment]
@alexr00 yes I'm signed in. +1 on what @jhpratt said, every time I reload windows or open a new instance of vscode it prompts me to sign in.

![image](https://user-images.githubusercontent.com/12979345/145508098-7eaca0a6-f56b-408d-a4f9-b2409a22498b.png)

**Comment by alexr00** [comment]
@ryan-efendy and @jhpratt I can't repro the issue, but I pushed a change that could fix it. Pre-release version 0.35.2021121009 has the change. Would you be able to try it out and reply back with whether you stop getting the prompt like that?

**Comment by jhpratt** [comment]
Quick check amounting to "upgrade to prerelease" and "reload" still results in the prompt.

Are there any logs that may be of use? I'd need instructions, but I'm fine sharing them if they're helpful.

**Comment by alexr00** [comment]
Thanks for trying it out. To get logs:

1. Set this setting to expand the log level: `"githubPullRequests.logLevel": "debug"`
2. Do your repro of the issue.
3. Run the command "Output: Focus on Output View"
4. In the Output dropdown, choose GitHub Pull Requests.
5. Share the entire contents of that output.

**Comment by baraBlz** [comment]
Hey what’s the issue. No one know I was supposed to be in the witness
protection programme and now all smart assholes compromised me 100%
again??? Please call +353 87 387 5677

**Comment by baraBlz** [comment]
The ur gonna love hearing how I protect myself since I was a kid much less
this whatever it was…

**Comment by baraBlz** [comment]
I first wouldn’t allow myself to pretend hacker on any fucking corner of
the world if I copy pasted some code. Much less a developer or hard earned
scholar… I dunno kids need to learn their place from me I guess. +353 87
387 5677

**Comment by ryan-efendy** [comment]
@alexr00 I'm on v0.35.2021121012 (pre-release) and I'm still being prompted to sign in on reload window etc
![image](https://user-images.githubusercontent.com/12979345/145619116-2bff9997-2db8-4ff6-9cbc-067d69cf600e.png)

**Comment by jhpratt** [comment]
Well…it's a lot but here is the full output. I _did not_ click "sign in". Looks like the overwhelming majority of the output is GraphQL requests and responses.

https://gist.github.com/jhpratt/ea32a8cfa7862badbf3eceb9ddd5e6c7

I'd have included it inline but it's >10x the maximum length of a comment.

**Comment by jhpratt** [comment]
Thanks @alexr00! I haven't checked the latest one-line patch but it is certainly plausible that failing to return is in fact the cause.

**Comment by alexr00** [comment]
I'm pretty sure that was the problem. The new pre-release build should be available in an hour or so. I will also be making a new stable build with this patch release tomorrow.

**Comment by alexr00** [comment]
Re-opening to track for the stable build too.

**Comment by alexr00** [comment]
@jhpratt or @ryan-efendy any luck with the latest pre-release version?

**Comment by ryan-efendy** [comment]
I haven't been prompted to sign in all day today (opening new instance and reloading window) 👍🏼  I'm on **v0.35.2021121309**.

**Comment by alexr00** [comment]
Thank you for verifying @ryan-efendy!

**Comment by baraBlz** [comment]
Hello,

My name is Domagoj Barisic, is there anything I could do to get a bed and a
safe roof to finish what I started please? I am a nervous wreck from all
the stress thrown @ me.
+353873875677

Yours Sincerely,

Domagoj Barisic
