### ISSUE TITLE
Allow "Don't Show Again" and/or configurability of opening PR

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode-pull-request-github#3167]
As described by user in [Twitter thread](https://twitter.com/choldgraf/status/1467929832176513024?s=20):

> The issue is when ctrl+clicking a link in the VSCode terminal. I want it to open a browser directly, and instead it gives a pop-up. 
> 
> Most pop-ups have a little checkbox like "don't show this pop-up again" and I am looking for the vscode version of this!

Would we consider adding "Don't Show Again," or a setting to configure this in GHPRI so that users can choose a default and avoid seeing this popup moving forward?

**Comment by choldgraf** [comment]
Just a note that it would also be fine if there were an obvious place in the settings to disable this check. When I `ctrl+click` on a github URL within VSCode, I just want it to open a browser window directly and not ask me whether I want to take the action in vscode.

**Comment by alexr00** [comment]
There was already a setting(`"githubPullRequests.terminalLinksHandler": "github"`), but I added a button to the notification that sets the setting. 

![image](https://user-images.githubusercontent.com/38270282/145386809-287105e3-a8b3-4399-a9f1-1b3e15cdb852.png)

**Comment by choldgraf** [comment]
having that box is a nice UX, thanks very much for listening and for the addition :-)

**Comment by IanMatthewHuff** [comment]
Looks good. Verified.

![image](https://user-images.githubusercontent.com/812783/151224296-a69e2813-dae0-478e-b558-3901981d9bbe.png)

**Comment by IanMatthewHuff** [comment]
Sorry had the process wrong (I had removed verification-needed after verifying) added it back in along with verified.
