### ISSUE TITLE
Times do not auto-update

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode-pull-request-github#318]
Testing https://github.com/Microsoft/vscode/issues/57301

Click the Approve button repeatedly, wait a couple of minutes between presses

All of them are rendered with "a few seconds ago"

![screenshot from 2018-08-29 11-06-14](https://user-images.githubusercontent.com/5047891/44777747-a9a09280-ab7b-11e8-8aef-f0e920446760.png)

The GitHub UI shows that there are a couple minutes between them:

![screenshot from 2018-08-29 11-07-39](https://user-images.githubusercontent.com/5047891/44777795-c5a43400-ab7b-11e8-96a6-b1b72c98b89c.png)

**Comment by alexr00** [comment]
We no longer allow multiple approvals like this.
