### ISSUE TITLE
Recent Change has stopped my Language Server (Intellisense) from working

### ISSUE THREAD

**Issue by klueless-io** [microsoft/vscode-pull-request-github#3180]
I posted details of my issue as a bug against VSCode, you can see it here

[VSCode Issue](https://github.com/microsoft/vscode/issues/138923)
and
[YouTube walkthrough](https://youtu.be/pNqHHghTRgY)

I was able to get intellisense working by disabling your extension

**Comment by alexr00** [comment]
If this is this is still happening please ping this issue and I will investigate!
