### ISSUE TITLE
Issue completions not showing in comments github.dev

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#3182]
From https://github.com/microsoft/vscode-pull-request-github/issues/2401#issuecomment-991129937

I do see issues and PRs in the GHPRI view on the left, but typing `#` in a comment does not suggest them (even if I start typing numbers after the `#` too):

![image](https://user-images.githubusercontent.com/25310137/145610606-16dfee50-12c0-432c-90d6-816282dbcc42.png)

I can successfully hover over the issues to get more info:

![image](https://user-images.githubusercontent.com/25310137/145610777-8d114776-28d8-4965-b03a-a2198d1e5364.png)

I tested with https://github.dev/bamurtaugh/ExpressApp/pull/5.

**Comment by bamurtaugh** [comment]
Looks like it works great for me now, thanks so much!

**Comment by alexr00** [comment]
Thanks for helping narrow it down!
