### ISSUE TITLE
Sync pull for PR with updates notification

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#3188]
Just got his on my new PC:

![image](https://user-images.githubusercontent.com/2193314/145911093-0808b9b3-6cf4-49fd-9f07-672457b63b8d.png)

We should sync whether to show this notification via settings sync.

**Comment by alexr00** [comment]
This was already done as part of https://github.com/microsoft/vscode-pull-request-github/issues/2628

**Comment by sedghi** [comment]
@alexr00 Hi, I have similar issue (an already reviewed PR that has been updated with more commits), but the notification is not showing up for me. How can i update the PR with new changes? `git pull` doesn't work

![image](https://user-images.githubusercontent.com/7490180/147262274-6f168e63-81fd-4eb3-b602-8e2609c014e0.png)

**Comment by sedghi** [comment]
@alexr00 appreciate your comment on my above issue
