### ISSUE TITLE
Bug: Slow to mark files as viewed

### ISSUE THREAD

**Issue by lagerholm** [microsoft/vscode-pull-request-github#3191]
Issue Type: <b>Bug</b>

When marking files as viewed it's very slow. Takes more than 1 second on my pretty fast machine. This is frustrating when you have a big PR with many files with few changes. I still want to mark all files as viewed to keep track of the progress if I'm interrupted and to make sure I look at everything. 

Extension version: 0.34.0
VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T06:26:56.179Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz (16 x 3792)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.71GB (16.38GB free)|
|Process Argv|--crash-reporter-id 009e0e6a-4a53-4bdb-9f46-6e92241da487|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.60.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz (16 x 3792)|
|Memory (System)|15.63GB (12.09GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.60.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz (16 x 3792)|
|Memory (System)|15.63GB (12.09GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593cf:30376535
pythonvs932:30410667
vscop804:30404766
vs360cf:30404996
vsrem710:30405998
vscexrecpromp3c:30407761

```

</details>

**Comment by lagerholm** [comment]
Tested some more on a smaller PR with only one changed file at it was still slow.

**Comment by alexr00** [comment]
I'm seeing ~350ms for marking a file as viewed, and basically all that time is spent doing the GitHub API call. We can't shorten that. UX may be improved with https://github.com/microsoft/vscode-pull-request-github/issues/3201.
