### ISSUE TITLE
Being on a branch with a PR replaces my active editor

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-pull-request-github#3194]
Steps to Reproduce:

1. be on a branch that maps to a opened PR
2. reload window
3. open some editors to look at

=> 🐛  out of random my active editor changes to the PR

![recording](https://user-images.githubusercontent.com/900690/146012802-5c832111-9051-452b-a4f8-f51bbaf7c62e.gif)

**Comment by alexr00** [comment]
@bpasero what version of GHPRI are you using?

**Comment by bpasero** [comment]
@alexr00  github.vscode-pull-request-github
