### ISSUE TITLE
Can't comment in pull request via github.dev

### ISSUE THREAD

**Issue by RikkiGibson** [microsoft/vscode-pull-request-github#3197]
- Extension version: Not obvious how to check this. It doesn't show in the extensions tab from github.dev.
- VSCode Version: 1.63.0
- OS: macOS. Using Edge browser.

Steps to Reproduce:

1. Open PR https://github.dev/dotnet/roslyn/pull/57780
2. Navigate to NullableWalker.cs in the GitHub Pull Request tab
3. Try to leave a comment on a changed line

Expected behavior:
The "new comment" glyph shows up and you can leave a comment

Actual behavior:
No "new comment" glyph shows up

**Comment by alexr00** [comment]
I suspect you were hitting https://github.com/microsoft/vscode-pull-request-github/issues/3173, which should be fixed in version 0.34.1 of the extension.
