### ISSUE TITLE
PR description view sometimes shows up empty

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-pull-request-github#3199]
- Extension version: v0.35.2021121509
- VSCode Version: 1.64-insider (vscode.dev)
- OS: Windows 11

Steps to Reproduce:

1. Open https://insiders.vscode.dev/github/microsoft/vscode/pull/139243
2. The view with the reviewer info and comment box sometimes shows up empty
![image](https://user-images.githubusercontent.com/30305945/146277401-7a6c9dba-d25b-426f-884a-99b499f428a9.png)
3. Collapsing and expanding the view is usually enough to get it to show up, but not always, possibly a timing issue?
![image](https://user-images.githubusercontent.com/30305945/146277513-f8485e3e-2786-4f70-ab61-ae8d37db1ce5.png)

**Comment by alexr00** [comment]
Looks like an upstream issue: https://github.com/microsoft/vscode/issues/139638
