### ISSUE TITLE
Fetching pull requests failed: TypeError: Cannot read property 'link' of undefined

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode-pull-request-github#32]
I'm just trying to look at PRs assigned to me, but they don't come up. It is weird, because this worked for me on the mac with an older version of the extension...

![image](https://user-images.githubusercontent.com/5047891/41917411-955f3cca-795a-11e8-8914-2a8fd9da6f3a.png)

**Comment by rebornix** [comment]
@RMacfarlane this is where we access `link` https://github.com/Microsoft/vscode-pull-request-github/blob/master/src/github/githubRepository.ts#L36 , is it possible that `headers` is undefined?

**Comment by RMacfarlane** [comment]
@alexandrudima I think different versions of the @octokit/rest package are being installed based on using npm vs yarn. When using yarn, `"^15.2.6"` is resolving to that exact version on my machine, and using npm results in `15.8.1` being installed. Between those versions, the property "meta" was renamed to "headers" on the response object. So there should always be a headers property if the request succeeded.

I'll bump the version in the `package.json` to 15.8.0, the version that introduced the rename
