### ISSUE TITLE
Losing focus/switching tabs while a comment entered (but not submitted) loses comment

### ISSUE THREAD

**Issue by catskul** [microsoft/vscode-pull-request-github#3200]
- Extension version: v0.35.2021121609
- VSCode Version:Version: 1.64.0-insider
- Commit: f67a8b753f55e452f38b61497662839c4691fb12
- Date: 2021-12-16T05:15:28.698Z
- Electron: 13.5.2
- Chromium: 91.0.4472.164
- Node.js: 14.16.0
- V8: 9.1.269.39-electron.0
- OS: Linux x64 5.4.0-91-generic

Steps to Reproduce:

1. starting editing a reply to a review comment.
2. switch to a different tab
3. return to tab with comment box
4. work is gone

**Comment by alexr00** [comment]
I've added a small cache for comments in non-visible files in a PR. However, the cache will only preserve 1 diffs worth of comments. This means that if you click switch tabs once while writing a reply, your reply won't be lost. But if you switch tabs twice while writing a reply it will be lost. If we find that this cache is too limited, we can expand it, but any expansion will come at the cost of minor perf losses.
