### ISSUE TITLE
Confusing "Go to review button" that also discards the comment.

### ISSUE THREAD

**Issue by danielo515** [microsoft/vscode-pull-request-github#3202]
Hello,

this is both a bug report and a confusing UX report. When you are in the middle of a review the UI to add a comment shows two buttons: `Go to review` and `Add comment`. This is confusing because:

- What is the purpose of the Go to review button? Why do I need it on a comment?
- The layout resembles the Github UI, where one button adds a comment to the review while the other just adds the comment as is.

Here is the UI

![image](https://user-images.githubusercontent.com/2270425/146764565-871f14ed-ece6-45ee-82be-6e41d432ead0.png)

This is even worse because, if you click the Go to review button (because you think it will add the comment to the review) the comment is lost, vanished, bye bye.

- Extension version:
- VSCode Version: 1.63.2
- OS: MacOS

Steps to Reproduce:

1. Start a review
2. Add a comment and then click the Go to review button.

**Comment by alexr00** [comment]
The "Go to Review" button was supposed to make the PR overview page more discoverable, but it is confusing. We could move it into an action icon at the top of the comment thread instead. @misolori what do you think? We could use the `go-to-file` codicon.
