### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by nelrafa103** [microsoft/vscode-pull-request-github#3204]
- Issue Type: `Bug`
- Extension Name: `vscode-pull-request-github`
- Extension Version: `0.32.0`
- OS Version: `Linux x64 5.15.8-76051508-generic`
- VS Code version: `1.60.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:```json 
{
	"messages": [
		{
			"type": 2,
			"message": "`remoteHub/pullRequest` is not a valid menu identifier",
			"extensionId": {
				"value": "GitHub.vscode-pull-request-github",
				"_lower": "github.vscode-pull-request-github"
			},
			"extensionPointId": "menus"
		}
	],
	"activationTimes": {
		"codeLoadingTime": 187,
		"activateCallTime": 0,
		"activateResolvedTime": 10805,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "GitHub.vscode-pull-request-github",
				"_lower": "github.vscode-pull-request-github"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": [],
	"runningLocation": 1
}
```

**Comment by alexr00** [comment]
This error is by design (https://github.com/microsoft/vscode/issues/136222). @joaomoreno in case you would reconsider this.
