### ISSUE TITLE
GraphQL error when making a PR comment in Codespaces

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#3206]
Saw this GraphQL error when making a comment in Codespaces:

![image](https://user-images.githubusercontent.com/2193314/146968697-8e134927-9206-4925-b14f-ebe42adb4a42.png)

Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:36:48.576Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4741.0 Safari/537.36 Edg/98.0.1100.3

ext version v0.34.2

**Comment by Tyriar** [comment]
The comment seems to have been made as it's visible on .com

Log:

```
[Info] /root/.ssh/config: ENOENT: no such file or directory, open '/root/.ssh/config'
[Info] Registering git provider
[Info] Looking for git repository
[Info] Found 1 repositories during activation
[Info] Git repository found, initializing review manager and pr tree view.
[Info] Review> Validate state in progress
[Info] Review> Validating state...
[Info] Found GitHub remote
[Info] Review> current branch pr/silamon/3546 is associated with pull request #3546
[Info] Review> Resolving pull request
[Info] Review> Fetching pull request data
[Info] Review> register comments provider
[Info] Review> display pull request status bar indicator and refresh pull request tree view.
[Info] Review> using focus mode = true.
[Info] Review> state validation silent = true.
[Info] Review> PR show should show = false.
```

**Comment by alexr00** [comment]
I can't repro on a private non-org owned repo. 
- What is the repository this is happening in (is it org owned?)?
- Is the PR coming from a fork?
- Is the repo public?

@TylerLeonhardt FYI as this sounds like a scopes issue.

**Comment by Tyriar** [comment]
Here's the PR (yes, yes, yes) https://github.com/xtermjs/xterm.js/pull/3546

**Comment by alexr00** [comment]
I can repro in that PR when I try to add a single comment. (Sorry about the spam in the PR!)

It seems to be related to the the `SubmitReview` mutation we do (https://github.com/microsoft/vscode-pull-request-github/blob/690e871223e56bbd74f82755b6db4a8dd8c00446/src/github/queries.gql#L565-L576)

**Comment by alexr00** [comment]
Looks like an upstream issue since it works fine outside of Codespaces.

**Comment by TylerLeonhardt** [comment]
Probably wanna bring @jkeech into this? Maybe there's an issue tracked there?

**Comment by alexr00** [comment]
The upstream Codespaces issue has been closed without a fix. Closing in favor of the upstream issue.
