### ISSUE TITLE
Unable to find source repository

### ISSUE THREAD

**Issue by rbtcollins** [microsoft/vscode-pull-request-github#3207]
I found closed bugs for this issue, but I am still puzzled by it. 

I fully understand being able to configure the repository the PRs are made against. But for choosing the *source* of a PR, surely the only things that matter are that the source repository is on GitHub. And querying the source repository for PRs is wasteful - theres no point doing that at all.

- Extension version: Last updated 22/12/2021, 10:09:20
- VSCode Version: 1.63.2
- OS: Windows

Steps to Reproduce:

1. Have 2 remotes, one called 'origin' and one called 'myname'
2. Create a new branch 'foo' and push to github/myname using the vscode sync button
3. click on create a PR and watch it fail.

**Comment by alexr00** [comment]
@rbtcollins I'm trying to follow your repro steps, but I still see PR creating succeed. Can you share screen shots of how you see it fail to create a PR?

**Comment by rbtcollins** [comment]
Before syncing
![image](https://user-images.githubusercontent.com/499678/147361655-a778f114-fbb5-477e-a0c5-d523e6f853a4.png)
Select my repo to sync to
![image](https://user-images.githubusercontent.com/499678/147361669-2d74c0ed-d7b5-4069-a9bd-67073f23b543.png)
My repo isn't visible in the create PR dialog 'From' box
![image](https://user-images.githubusercontent.com/499678/147361693-8a547610-d6cc-446a-b971-444090bcb023.png)
old remotes setting:
![image](https://user-images.githubusercontent.com/499678/147361720-3a2a4db0-2428-4e17-b549-b844ef752549.png)

then 
1. add my source repo (which will never have pull requests on it ...)
2. cancel the PR creation
3. Initiate PR creation again
4. now the from box lists my repo

![image](https://user-images.githubusercontent.com/499678/147361815-2fbbe804-6837-43ab-ae79-45525048ef84.png)

**Comment by alexr00** [comment]
Thanks @rbtcollins, I see the confusion now.

**Comment by JacksonKearl** [comment]
Works well when the two origins have different owners, ran into #3278 when they're both the same owner.
