### ISSUE TITLE
can't comment on a line with existing comment

### ISSUE THREAD

**Issue by itaysk** [microsoft/vscode-pull-request-github#3208]
- Extension version: 0.34.2
- VSCode Version: 1.63.0
- OS: Ubuntu Hirsute (via remote ssh from MacOS Monterey)

Steps to Reproduce:

1. Open a PR with existing review
2. Find an existing comment
3. Try to add another comment on the same line
4. Gutter button is disabled (not plus sign)

**Comment by joshuaobrien** [comment]
👋 I'm happy to work on this one
