### ISSUE TITLE
How to create a PR using the extension?

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode-pull-request-github#321]
Testing https://github.com/Microsoft/vscode/issues/57301

Maybe I missed it, but if I am a user getting started with github and with a certain project, what steps can I do to create a PR using the extension? It seems imbalanced in showing only existing PRs.

**Comment by lhutz** [comment]
I think it is not yet available in this extension, like it's mentioned in #283

**Comment by RMacfarlane** [comment]
Closing as a duplicate of https://github.com/Microsoft/vscode-pull-request-github/issues/283
