### ISSUE TITLE
Big List of Naughty Strings breaks the rendering of a PR

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode-pull-request-github#322]
Testing https://github.com/Microsoft/vscode/issues/57301

Attempt to open the description for https://github.com/auchenberg/pullrequest-demo/pull/6 
ref> https://raw.githubusercontent.com/minimaxir/big-list-of-naughty-strings/master/blns.txt

Observe strings are not escaped properly:

![image](https://user-images.githubusercontent.com/5047891/44778792-2e8cab80-ab7e-11e8-93bc-55330384fad9.png)

I sometimes reproduced only when clicking between two different descriptions. i.e. first show the description for PR 6 and then click on the checked out description for PR 3

**Comment by alexandrudima** [comment]
@kieferrm @mjbvz I remember you testing the markdown preview webview and devising some good practices to avoid JS execution or other attacks. Perhaps you can talk and share the learnings.

**Comment by mjbvz** [comment]
For content inside a webview, the PR extension already uses a content security policy which should prevent script execution. Two limitations:

- This means we rely entirely on the content security policy to work. The csp should work since this is a core piece of web security, but we can't guarantee that it will
- It doesn't prevent someone from injecting bad html content that can ruin how the editor looks

Compared with the markdown preview, we probably want additional sanitization for user content in the PR extension because the content is coming from an external, online source instead of from files in the user's workspace

**Comment by alexandrudima** [comment]
:+1: Thanks for clarifying that it is just a rendering issue.

**Comment by connorshea** [comment]
I don't know if I should open a separate issue for my problem, but I ran into the same kind of issue with a PR I was looking at.

Essentially, the file being commented on is a JSON file with the following contents:

```json
"firefox": [
  {
    "version_added": "47",
    "notes": "Before Firefox 44, Firefox incorrectly allowed elements inside a <code><frame></code> or an <code><object></code> to request, and to be granted, fullscreen. In Firefox 44 and onwards this has been fixed: only elements in the top-level document or in an <code><iframe></code> with the <code>allowfullscreen</code> attribute can be displayed fullscreen."
  }
]
```

<img width="953" alt="screen shot 2018-09-10 at 1 01 29 pm" src="https://user-images.githubusercontent.com/2977353/45318338-df3d6800-b4f9-11e8-8019-3eb739fb0eb6.png">

It seems the `iframe` element is being rendered in the editor, and the `object` and `frame` elements also cause weird problems.

[Link to GitHub comment](https://github.com/mdn/browser-compat-data/pull/2770#discussion_r216065017)

**Comment by alexr00** [comment]
@mjbvz is there somewhere in the built in markdown renderer where there is a list of strings I should escape that you can point me to?

**Comment by mjbvz** [comment]
@alexr00 For markdown, we use this regular expression: https://github.com/microsoft/vscode/blob/d33c0621bc049594f93830b20bf0d8e2ff2f6a40/src/vs/base/common/htmlContent.ts#L105-L106

Not sure if it would handle these edge cases though

**Comment by alexr00** [comment]
Thanks!

I can't reproduce the original issue, but I'll add the escape just to be thorough.
