### ISSUE TITLE
Feature: Add link "Open in GitHub"  in PR Tab

### ISSUE THREAD

**Issue by Nevin1901** [microsoft/vscode-pull-request-github#3220]
I was creating a pull request through vscode.dev, and I thought this extension was missing a feature. In my opinion, there should be a link somewhere on this tab allowing someone to open the pull request or issue in GitHub (I would think it would be under the "Exit Review Mode" button).
<img width="296" alt="image" src="https://user-images.githubusercontent.com/39220032/147865107-d694033b-6ebf-44ac-ba5c-213180308f69.png">

I'm curious as to what everyone's opinions are. I can try and start working on this one of these days.

**Comment by alexr00** [comment]
We already have that action in the title of the view:

![image](https://user-images.githubusercontent.com/38270282/147923541-64eb2fe3-b660-4d56-95c7-19dc15e48c09.png)

I'm inclined to leave it in the title since that's the VS Code convention for where to put actions.
