### ISSUE TITLE
File tree mostly covered by comment pane by default

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode-pull-request-github#3227]
Filing based on meeting from a few weeks ago: The file tree in the GHPRI view was mostly covered by "Comment and Submit" pane by default. This can be moved, but it was confusing/frustrating to start like this by default.

Upon reviewing the experience, I'm thinking this must have been the below:

![image](https://user-images.githubusercontent.com/25310137/147985231-6799acf9-bdf9-4115-9c04-2e1281130ae7.png)

Should the bottom comment pane start at a lower point by default, and only be moved/default to higher if the user has previously moved it (i.e. always default to below the last expanded item in the above section's tree)? Or is that already the case / not feasible / not in line with other UI practices? 

As it's been a few weeks since we observed this, if I'm misremembering anything from this experience, please also let me know.

**Comment by alexr00** [comment]
The initial height of the webview should be 50% of the total height, which would already be an improvement over the current situation. Bug for that: https://github.com/microsoft/vscode/issues/106585.

This would be even better, but probably more work than fixing the bug: https://github.com/microsoft/vscode/issues/123715

**Comment by bamurtaugh** [comment]
Thanks for linking these issues @alexr00! As there are already two issues that seem to cover this, would it make sense to close this one? Or is it helpful to have something here tracking the experience on the GHPRI side?

**Comment by alexr00** [comment]
👍 closing as upstream!
