### ISSUE TITLE
VSCode thinks extension provides code actions

### ISSUE THREAD

**Issue by aaronadamsCA** [microsoft/vscode-pull-request-github#3229]
Issue Type: <b>Bug</b>

Sometimes when I save a file, VS Code says it's fetching code actions from this extension.

My `settings.json` tells VS Code which code actions to run, and this extension isn't included in my config:

```jsonc
{
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": true
  },
  // Rest of settings
}
```

So as far as I'm concerned, there's no reason VS Code should be fetching these code actions. But since it takes a surprisingly long time, I see it in the IDE.

I'm guessing this might have to do with this extension listing `*` as one of its activation events?

Extension version: 0.34.2
VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.56GB (13.28GB free)|
|Process Argv|--folder-uri vscode-remote://dev-container%2B7b227265706f7369746f727950617468223a2268747470733a2f2f6769746875622e636f6d2f73686f706e697368652f6e697368652d7765622d617070732e6769742f747265652f6d61696e222c22766f6c756d654e616d65223a226e697368652d7765622d617070732d6d61696e2d3166636431626661626462616365306665303266663130623861663364313531222c22666f6c646572223a226e697368652d7765622d61707073222c22696e7370656374566f6c756d65223a66616c73657d/workspaces/nishe-web-apps --crash-reporter-id a9305738-51b5-4cca-ac9d-97e8b1880520|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Nishe Web Apps|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|Memory (System)|15.42GB (7.61GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30384386
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscop804:30404766
vs360:30404995
vsrem710cf:30416617
vscexrecpromp3t1:30407762

```

</details>

**Comment by alexr00** [comment]
@aaronadamsCA can you share a screenshot of what you're seeing?

**Comment by aaronadamsCA** [comment]
Sorry @alexr00, I meant to include this but forgot:

![image](https://user-images.githubusercontent.com/1505561/148622742-f94f4377-b3e5-426d-8a28-35908ba99d12.png)

**Comment by jrieken** [comment]
We first need to ask the code action provider for the potential actions and can only than pick/select some. Therefore we ask all providers. Tho, using `CodeActionProviderMetadata#providedCodeActionKinds` allows you to specify what kind of code action kinds your provider would ever return. I believe during save we are only interested in "SourceFixAll"-kinds

**Comment by alexr00** [comment]
Thanks @jrieken that was the problem!
