### ISSUE TITLE
Comments appear being pending instead of submitted

### ISSUE THREAD

**Issue by shiyao-afterpay** [microsoft/vscode-pull-request-github#3232]
After I started a review, and added some comments, then finally when I submit the review in this panel (the bottom left one in VSC).
![image](https://user-images.githubusercontent.com/76024153/148340058-b8713992-4703-4493-9131-23d4c36f7f3b.png)

The comments are pending instead of submitted.

**Comment by alexr00** [comment]
Thanks for filing this bug!
