### ISSUE TITLE
"We couldn't find an open repository for..."

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-pull-request-github#3242]
![image](https://user-images.githubusercontent.com/323878/148816980-c58d5ddb-1a11-4cd4-9c62-43c3aca67d5c.png)

- Open https://github.com/microsoft/vscode-remote-ssh/pull/183, press `.`
- The first time I opened this PR, it loaded all the content but I couldn't add comments
- The second and third time, I got this error message and when I click a diff, the left side is empty
[ghpr.txt](https://github.com/microsoft/vscode-pull-request-github/files/7841041/ghpr.txt)

**Comment by alexr00** [comment]
@roblourens what version of the extension was this?

**Comment by roblourens** [comment]
Still happens today on https://github.dev/microsoft/vscode-remote-ssh/pull/185/files. Looks like I have `v0.35.2022011315`

![image](https://user-images.githubusercontent.com/323878/149571770-7a72e3eb-8b99-4e77-8f65-687a0af38238.png)

**Comment by alexr00** [comment]
This issue is fixed in the latest pre-release build.

Commenting should be fixed by https://github.com/microsoft/vscode-pull-request-github/issues/3306, which went out in 0.36.1 yesterday.

**Comment by alexr00** [comment]
@nwhitaker can you share the output from GitHub Pull Request?
