### ISSUE TITLE
Show changes like the SCM view

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-pull-request-github#3249]
See how changes in the SCM view appear with their parent directory path:

![image](https://user-images.githubusercontent.com/900690/149461780-819ac6ea-b139-4dbb-ab4e-1ffc5e04d439.png)

And now compare to a PR changes view:

![image](https://user-images.githubusercontent.com/900690/149461795-b0d94ae0-ee69-40c3-a0fb-2a02f7b0610b.png)

This makes it very hard to tell apart files with the same name.

@alexr00 is that possible?

**Comment by alexr00** [comment]
The default is the tree layout. There's a "Toggle View Mode" button in the view that you probably hit at some point:

![image](https://user-images.githubusercontent.com/38270282/149491027-99d986c4-cd93-43bc-91fa-89c51334c31a.png)

It's also a setting: `githubPullRequests.fileListLayout`.

**Comment by bpasero** [comment]
@alexr00 yeah I am aware of that and the SCM view has that as well but I really prefer the flat view. That doesn't mean we cannot show the paths right?

**Comment by alexr00** [comment]
Ah I misunderstood!

**Comment by alexr00** [comment]
Looks like it was actually a bug, as the original intent appears to be that the dirname is shown in the description.

**Comment by bpasero** [comment]
👏

**Comment by bpasero** [comment]
I think this is good, but in the multi-root case the display is still different:

**SCM Changes View**

![image](https://user-images.githubusercontent.com/900690/151118878-13c1914b-5c93-4cdd-a426-299d83e2bd84.png)

**PR Extension**

![image](https://user-images.githubusercontent.com/900690/151118916-b185913a-2c21-4815-b288-e6f914b5ef73.png)

Specifically the `monaco *` indicator seems to be missing.

**Comment by alexr00** [comment]
@bpasero where does the "monaco" come from? Is it a label set in the workspace file? If so, I would keep as is since we already group files by pull request, which seems like the logical way to do it in this extension.

**Comment by bpasero** [comment]
@alexr00 there is nothing you have to do other than passing the `Uri` into the `ILabelService`:

```
labelService.getUriLabel(editorFolderResource, { relative: true })
```

That will take care of everything. Maybe take a look how the "Open Editors" view in the explorer does it.

**Comment by alexr00** [comment]
@bpasero I had made the `description` change in the extension, but it looks like we have a mechanism form automatically doing `labelService.getUriLabel(resource, { relative: true })` for the description in VS Code. However, it adds some ugly slashes and doesn't seem to include the root.

New issue with all the details: https://github.com/microsoft/vscode/issues/141634
