### ISSUE TITLE
Not able to mention people in my code.

### ISSUE THREAD

**Issue by ivan-rybachok** [microsoft/vscode-pull-request-github#3251]
@ won't show the name of the other people that have access to the project
![image](https://user-images.githubusercontent.com/92591041/149580241-cd72d317-de02-42fe-b907-1885188bd22b.png)

**Comment by AdrianFahrbach** [comment]
Are you sure that this is fixed?

We were talking about how to mention people in a TODO comment and suddenly got suggestions popup when typing this in a scss file:
```
// TODO: @
```

This was the first time that I have seen this (although I have been using the `@` character in comments before). It was only working in that repository, not in others and it wasn't working on my colleagues computers. After restarting VSCode it isn't working in that repository either. So no mention suggestions at all.

MacOS: v12.2
VSCode: v1.70.2
GitHub Pull Requests and Issues: v0.48.1

**Comment by alexr00** [comment]
@AdrianFahrbach what is the language of the file you're doing this in?

**Comment by AdrianFahrbach** [comment]
It's not working on `tsx` and in `html`, other than that it is working now.

My colleague and I removed some deprecated extensions, maybe that has something to do with it, but I guess not. We will check this on monday with another colleague.

My guess is that it wasn't working on our devices for different reasons that made it seem like it wasn't working at all. The individual reasons could be:
* We were testing it in `.tsx` or html inside `.php`
* The user wasn't logged in to GitHub
* In `.yml` it shows the mention suggestion immediately and in other file types I have to "trigger suggest" to see the mentions at the bottom of my suggestion list. The reason for that may be that the mentions are the only suggestions I get in '.yml'.

**Comment by alexr00** [comment]
> The reason for that may be that the mentions are the only suggestions I get in '.yml'.

This is the most likely culprit. If there are other suggestions they may take precedence over the user suggestions. 

I tested with `tsx` and it works if I trigger suggestions. For `html`, it works without triggering. Are these files in your GitHub repo?

**Comment by AdrianFahrbach** [comment]
It does work in html, only the issues are not working in html. Sorry for the confusion, my bad.

`tsx`: Issues and mentions not working
`html`: Issues not working
`yml`: Issues not working

![Bildschirmfoto 2022-08-19 um 10 42 48](https://user-images.githubusercontent.com/45072099/185581549-bc22d1d8-6059-487f-b661-d5b03ae956d5.png)
![Bildschirmfoto 2022-08-19 um 10 28 59](https://user-images.githubusercontent.com/45072099/185581554-a7cef1d3-6ec1-4ce6-887d-3c1f1d3ec167.png)


All of the files are inside the repository. No symlinks or submodules or whatsoever.

**Comment by alexr00** [comment]
@AdrianFahrbach opened https://github.com/microsoft/vscode-pull-request-github/issues/3874
