### ISSUE TITLE
Ability to auto-assign when creating a Pull request from an Issue

### ISSUE THREAD

**Issue by JotaRata** [microsoft/vscode-pull-request-github#3253]
It would be neat to have an option to auto-assign a person when creates a pull request from an issue (clicking in the issue name in the bottom bar).

Also it could link the current working issue to that new pull request, so it closes automagically.

**Comment by alexr00** [comment]
Linking a PR automatically is tracked by https://github.com/microsoft/vscode-pull-request-github/issues/2676

Who would you expect the PR be auto assigned to? The same person as is assigned to the issue?

**Comment by alexr00** [comment]
We have a setting for who to assign PRs to:` "githubPullRequests.assignCreated": "${user}"`
