### ISSUE TITLE
Markdown content escaped when editing comments

### ISSUE THREAD

**Issue by diminutivesloop** [microsoft/vscode-pull-request-github#3254]
Issue Type: <b>Bug</b>

When editing a PR comment any Markdown content is backslash escaped which removes the formatting when the comment is saved. For example the following markdown text:
```
- a list
- of things
- that aren't important
```
is converted to this:
```
\- a list
\- of things
\- that aren't important
```

Extension version: 0.34.3
VS Code version: Code 1.63.2 (Universal) (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (0.12GB free)|
|Process Argv|--crash-reporter-id ed50f89e-497f-43cd-86f3-a73119f730ed|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30384385
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dsc:30421290
pythonvs932:30410667
vscop804cf:30404767
vs360cf:30404996
vsrem710:30416614
vsccppwtstudy:30421978

```

</details>

**Comment by MilesCranmer** [comment]
This bug makes editing comments on PRs broken. I see the same issue, and I note that it is particularly bad because backslashes will also be backslashed on repeated save. Which means that after a few edits of a PR comment, you are left with something like:
```
This is a call to \\\`subprocess\\\`, which then does other thing\\\!
```
(yes it also backslashes an exclamation mark). It does the same for code blocks, which ends up removing the code block formatting.

**Comment by alexr00** [comment]
Is this a new issue, or has this been going on for a while?

**Comment by diminutivesloop** [comment]
I only noticed it recently and I'm pretty sure I've edited Markdown comments before without issue, so yes I think it's new.

**Comment by alexr00** [comment]
@diminutivesloop could you make a gif/screen capture of what you're seeing? I haven't been able to reproduce it. (https://gifcap.dev/ is made by another member of the VS Code team if you need a way to capture).

**Comment by MilesCranmer** [comment]
@alexr00 here is my recording, which presumably is the same issue @diminutivesloop is seeing

https://user-images.githubusercontent.com/7593028/150583048-be9a248d-69af-4812-a7fd-f79be5db0a94.mov

.

**Comment by MilesCranmer** [comment]
@alexr00 I also noticed that if I create the comment from the extension, it doesn't have this issue, which might be why you couldn't reproduce it(?). It's only when I edit a comment that already exists (that has such characters as above) will the backslashes appear.

**Comment by diminutivesloop** [comment]
@MilesCranmer Yeah your screen capture reflects what I'm seeing.

**Comment by MilesCranmer** [comment]
Thanks @alexr00!
