### ISSUE TITLE
Many spurious user mentions inserted in text

### ISSUE THREAD

**Issue by pokey** [microsoft/vscode-pull-request-github#3257]
Issue Type: <b>Bug</b>

When editing a new GitHub issue from within VSCode, I'll get lots of spurious insertions of user names as I type, meaning I'm often cleaning up after this extension.  Here is an example:

![ezgif com-gif-maker](https://user-images.githubusercontent.com/755842/149932607-759a3709-38d4-4a9f-b930-db27db223cce.gif)

Notice how I'm just typing normally, no `@` or `<tab>`, but a random name comes out of nowhere.  In case helpful, I did it again, this time slowing down long enough for the pop-up to appear:

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/755842/149932795-3df1b87f-774b-4c33-a193-a742d7eab41d.gif)

I believe the issue is that the suggestions are quite lenient, and hitting `<space>` accepts the completion.  A couple solutions I could think of:

- Only make suggestions if the token starts with `@` (or if not desired to have this be default behaviour, at least adding a setting where I can force this)
- Have a setting to disable `<space>` to accept suggestion

Extension version: 0.34.3
VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin x64 21.2.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id 99d35f96-61a9-461b-a60d-f915d32f3eee|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804cf:30404767
vscop453:30404998
vsrem710cf:30416617
vsccppwtstudy:30421978

```

</details>

**Comment by alexr00** [comment]
Do you have the setting `"editor.quickSuggestions": true`?

**Comment by pokey** [comment]
> Do you have the setting `"editor.quickSuggestions": true`?

It appears that I do:

```json
    "editor.quickSuggestions": {
        "other": true,
        "comments": true,
        "strings": true
    },
```

I believe I turned them on at the [advice](https://github.com/atishay/vscode-allautocomplete#suggestions-in-commentsstrings) of the [All Autocomplete extension](https://marketplace.visualstudio.com/items?itemName=Atishay-Jain.All-Autocomplete)

**Comment by alexr00** [comment]
I've pushed a change that will only include users in the quick suggest when on the Assignees line of the new issue file.

**Comment by pokey** [comment]
Ah right yeah that seems like a nice fix thank you!
