### ISSUE TITLE
Update a PR that has force pushes

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#3258]
@alexr00 Hi, I have similar issue (an already reviewed PR that has been updated rebased pushed with more commits), but the notification is not showing up for me. How can i update the PR with new changes? `git pull` doesn't work (which makes sense), how can i reset it to the head?

![image](https://user-images.githubusercontent.com/7490180/147262274-6f168e63-81fd-4eb3-b602-8e2609c014e0.png)

_Originally posted by @sedghi in https://github.com/microsoft/vscode-pull-request-github/issues/3188#issuecomment-1000383916_

**Comment by alexr00** [comment]
@sedghi did you try the refresh button? 
![image](https://user-images.githubusercontent.com/38270282/149951214-54e100e0-78d4-4175-87e4-804ecbc70ad5.png)

**Comment by sedghi** [comment]
I don't have that refresh button hmmm

```
Version: 1.63.2 (Universal)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:37:28.172Z (1 mo ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 19.6.0
```

**Comment by alexr00** [comment]
Can you please share a screenshot?

**Comment by alexr00** [comment]
Closing due to missing info.

**Comment by vladimir-bukreev** [comment]
I have the same question. In our company we force-push updates to PRs. I have refresh button on the 'changes in pull request #..." header row, but it does nothing. 
I think I can reset current branch (pr/<username>/<pr-id>) to the latest commit I've fetched, but this is a manual way, I don't like it. 
Is there a proper way of refreshing force-pushed PR?

**Comment by alexr00** [comment]
>  I have refresh button on the 'changes in pull request #..." header row, but it does nothing.

Can you check the PR branch that you have checked out and see what commit the head is at?

**Comment by vladimir-bukreev** [comment]
@alexr00 , please help me to understand, are you going to re-open this bug? Or should I create a new one?

**Comment by Angie20182** [comment]
I am probably going to yes I'm just trying to make some type of money I've
been trying to learn all of it and I still haven't made a dollar I'm single
mom trying to figure it out

**Comment by alexr00** [comment]
Meant to reopen this when I added it to the September Milestone.

**Comment by alexr00** [comment]
I cannot reproduce this issue. Even when there has been a force push to the repo the PR branch, the refresh button works. 

Next time you see this error can you share the output from "GitHub Pull Request"?

**Comment by vladimir-bukreev** [comment]
Du I have to manually fetch changes from remote before clicking refresh button? Anyway, it does nothing in both cases - when local repo is obsolete or up-to-date. 
Here is another screenshot, I see nothing interesting in extension output. 
And I've created repro repository on Github, but again, there is nothing special - https://github.com/vladimir-bukreev/vscode-pr-forcepush
![image](https://github.com/microsoft/vscode-pull-request-github/assets/137898245/32a03782-58e8-461e-b879-b6912ddf2bbf)

Environment info:
VSCode 1.83.1
OS; Windows 10
git: 2.42.0.windows.2
GitHub Pull Requests and Issues extension version: 0.74.0

STR:
0) Create PR branch with a single commit.
1) Open PR in one instance of VSCode in one working copy of the repo. 
2) Open PR branch in another instance of VSCode, in another working copy of the same repo.
3) Make any change in PR branch and amend last commit. 
4) Force-push amended commit
5) Switch to the 1st VSCode instance, open Github Pull Request tab, click refresh button

Observed behavior: nothing is changed, nothing is updated, PR shows old (original) changes. 
After several seconds VSCode will fetch changes from the server automatically, new commit with origin/branch will become visible in Commit Graph, but GH PR tab behavior will not change, refresh button still will not update the PR.
