### ISSUE TITLE
Links are rendered different in Web UI or description editor

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode-pull-request-github#326]
Testing https://github.com/Microsoft/vscode/issues/57301

See the two screen shots and the links in the second comment

<img width="774" alt="capture" src="https://user-images.githubusercontent.com/1931590/44790716-4b39db00-aba0-11e8-85ea-4d1a8c7470f6.png">

<img width="801" alt="capture" src="https://user-images.githubusercontent.com/1931590/44790745-57259d00-aba0-11e8-9399-43562815490f.png">

**Comment by RMacfarlane** [comment]
Closing as a duplicate of https://github.com/Microsoft/vscode-pull-request-github/issues/74
