### ISSUE TITLE
PR shows completely different changes in GitHub view vs Pull Request view

### ISSUE THREAD

**Issue by RikkiGibson** [microsoft/vscode-pull-request-github#3260]
- Extension version (web): v0.34.3
- VSCode Version (web): 1.63.2
- Browser: Microsoft Edge Version 97.0.1072.62

Steps to Reproduce:

1. Open https://github.dev/dotnet/roslyn/pull/57667
2. Observe changes in CSharpCompilation.cs in "GitHub Pull Request" tab
3. Open the same PR in the "GitHub" tab and find the changes in CSharpCompilation.cs

**Expected behavior**: equivalent file changes shown in both places
**Actual behavior**: different file changes are shown in each place

Note that the changes in "GitHub" are *correct* while the changes in "GitHub Pull Request" are *incorrect*.

GitHub view:
![image](https://user-images.githubusercontent.com/5833655/150029825-b2c155d2-f968-4dd9-82b1-bf1e2962076c.png)

GitHub Pull Request view:
![image](https://user-images.githubusercontent.com/5833655/150029859-433d28f6-f024-46f4-aa60-7ba322a2bca8.png)

**Comment by alexr00** [comment]
@RikkiGibson Does this happen every time you open that PR? I'm not able to repro the issue.

If it does happen every time, would you be willing to try the[ pre-release version](https://github.com/microsoft/vscode-pull-request-github/wiki/Pre-release-Build) of the extension and see if it also reproduces there?

**Comment by RikkiGibson** [comment]
I looked again and the "GitHub Pull Request" view is still wrong, but wrong in a new way :)

![image](https://user-images.githubusercontent.com/5833655/151046457-61095024-e566-4be5-a4e5-89e537a2c530.png)

Switching to pre-release actually fixes the issue. Thanks for the tip!

I wonder if a specific issue was fixed between stable and pre-release? Did you use the version from the issue description when attempting to repro?

**Comment by alexr00** [comment]
I tried both stable and pre-release when trying to repro, but no luck on either. There are some significant refactors to improve performance in pre-release, so something could have fixed it.

**Comment by RikkiGibson** [comment]
I think dotnet/roslyn#57667 still shows some bad behavior in my Edge, but other pull requests seem to work fine. I wonder if some local cache got into a bad state specifically for that pull request.

**Comment by alexr00** [comment]
> I wonder if some local cache got into a bad state specifically for that pull request.

That could be it. Could you try going to https://vscode.dev/github/dotnet/roslyn/pull/57667 and seeing if it repros there?

**Comment by RikkiGibson** [comment]
Fascinating. Right now I get the gray bars indicating I can leave a comment, but no actual content diffs in github.dev:

![image](https://user-images.githubusercontent.com/5833655/155346784-0b950d59-211a-4fde-b32b-89bc7cac5ef7.png)

In vscode.dev/github I get the proper content diffs:

![image](https://user-images.githubusercontent.com/5833655/155346919-9f2df841-7832-4f90-8c98-1ca714f6ae41.png)

**Comment by alexr00** [comment]
The no diffs is caused by https://github.com/microsoft/vscode-remote-repositories-github/issues/121 We're still trying to get to the bottom of that one.

I think it's safe to say that the original issue was caused by caching though if you can't repro it on vscode.dev. If you see the incorrect diffs (not the no diffs) again, lets reopen for further investigation since we shouldn't end up with a bad cache. 

Thank you for trying this out!
