### ISSUE TITLE
Issue Hover Card fails for external repository issue reference surrounded by parentheses

### ISSUE THREAD

**Issue by melink14** [microsoft/vscode-pull-request-github#3268]
Issue Type: <b>Bug</b>

Steps to Reproduce:

1. Make a TODO with issue in another repository using paren formatting:
```js
// TODO(trygve-lie/esbuild-plugin-import-map#25): Remove when official definition is added.
```
2. Hover over it and confirm error message in logs:
```
[Info] GithubRepository> Unable to fetch PR: Error: GraphQL error: Could not resolve to a Repository with the name 'TODO(trygve-lie/esbuild-plugin-import-map'.
```

It works if I put spaces around the issue number but it's a bit unwieldy considering same repo refs work differently.

Extension version: 0.34.3
VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5950X 16-Core Processor             (32 x 3400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (1.91GB free)|
|Process Argv|--crash-reporter-id 56cd355b-45cd-41ef-9aa0-32e251f0fac2|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Pengwin|
|OS|Linux x64 5.10.60.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 9 5950X 16-Core Processor (32 x 3399)|
|Memory (System)|7.76GB (0.88GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30424896
pythonvs932:30410667
vscop804:30404766
vscop341:30404997
vsrem710:30416614
vsbas813:30426126
vsic-wlc-tsjs:30426436

```

</details>

**Comment by roblourens** [comment]
Works great but I noticed the highlight is includes the opening paren but not the closing paren

<img width="362" alt="image" src="https://user-images.githubusercontent.com/323878/155600047-ba84d910-90cd-4fad-91d0-48ac0b54153e.png">
