### ISSUE TITLE
Stuck creating PR

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-pull-request-github#3269]
v0.35.2022012509

It somehow doesn't get out of the "no commits between" state. That was true when I first forgot to create a commit, but I then added that locally and later pushed to the remote. The view somehow doesn't recover.

<img width="490" alt="image" src="https://user-images.githubusercontent.com/9205389/151120421-8d2031b9-ef85-49aa-9d3d-e02da2f1a998.png">

I see a few of the following in the console:
```
workbench.desktop.main.js:sourcemap:578 DEBUG Webview(webviewview-github-createpullrequest): will update content
workbench.desktop.main.js:sourcemap:578 DEBUG Webview(webviewview-github-createpullrequest): webview ready
workbench.desktop.main.js:sourcemap:578 DEBUG loadLocalResource - begin. requestUri=file:///Users/chrmarti/.vscode-insiders/extensions/github.vscode-pull-request-github-0.35.2022012509/dist/webview-create-pr-view.js
workbench.desktop.main.js:sourcemap:578 DEBUG loadLocalResource - found resource to load. requestUri=file:///Users/chrmarti/.vscode-insiders/extensions/github.vscode-pull-request-github-0.35.2022012509/dist/webview-create-pr-view.js, resourceToLoad=file:///Users/chrmarti/.vscode-insiders/extensions/github.vscode-pull-request-github-0.35.2022012509/dist/webview-create-pr-view.js
```

Version: 1.64.0-insider
Commit: f93c69659de1a1466bd15e0f1c9f790e73be9208
Date: 2022-01-25T08:42:38.986Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0

**Comment by chrmarti** [comment]
Reloaded the window, but now I'm stuck here:
<img width="575" alt="image" src="https://user-images.githubusercontent.com/9205389/151123113-78f88620-f55d-4bc8-b579-4d220805b0a6.png">

**Comment by roblourens** [comment]
I was also stuck here, after creating commits and pushing them:

<img width="431" alt="image" src="https://user-images.githubusercontent.com/323878/155799035-1a4cc8e1-48ca-4780-8aa1-e64f8b62e736.png">

until I reloaded the window

**Comment by alexr00** [comment]
@roblourens what version of the extension did you have?

**Comment by roblourens** [comment]
I assume the latest at that point. I tried again and it seems to work, but I'm not exactly sure what the repro steps are. Something like, publish a branch that is equal to the upstream branch, start creating a PR, then create a commit and push it? This time I saw the Create PR panel refresh like I expect when I pushed the commit

**Comment by alexr00** [comment]
@roblourens if you were on the latest stable version of the extension then there was a bug that could have caused this. The pre-release from Feb 23 or later would have the fix though. Closing, since you did see it work this time.
