### ISSUE TITLE
Sometimes the diff viewer gets stuck

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode-pull-request-github#327]
Testing Microsoft/vscode#57301

See screen short:

<img width="1125" alt="capture" src="https://user-images.githubusercontent.com/1931590/44791820-d1efb780-aba2-11e8-91f6-9b24f40f4ca7.png">

Closing and reopening then mostly works and shows in the above example:

<img width="1134" alt="capture" src="https://user-images.githubusercontent.com/1931590/44791851-e764e180-aba2-11e8-95e8-d5fb1624f965.png">

**Comment by alexr00** [comment]
I haven't seen this in at least a year.
