### ISSUE TITLE
useReviewMode: misleading description

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode-pull-request-github#3270]
Testing #3267

The description says the open PRs will always end in review mode
<img width="498" alt="capture" src="https://user-images.githubusercontent.com/1931590/151146515-04337e64-e630-496e-a1af-c1db66e216e7.png">

However there seems to be a setting that I can turn to false. Is this ignored?

**Comment by alexr00** [comment]
It is ignored. I will remove the `open` option.
