### ISSUE TITLE
Review mode not entered for merged PRs

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode-pull-request-github#3271]
Testing #3267

- I checked out a merged PR
- settings
```
"githubPullRequests.useReviewMode": {
		"open": false,
		"merged": true,
		"closed": true
	}
```
- reload the Window

Review mode not entered. I would have expected the Review mode being entered.

**Comment by alexr00** [comment]
@dbaeumer I'm not able to repro this. Did you change the setting before or after checking out the PR  branch?

**Comment by dbaeumer** [comment]
The PR was actually merged not closed. But the result should have been the same.

**Comment by dbaeumer** [comment]
@alexr00  I couldn't reproduce but I guess that the closed PR was merged. Since makes it hard to decide which flag is taken. I opened https://github.com/microsoft/vscode-pull-request-github/issues/3273 to make this clearer. And may be the flag should be named `closedAndNotMerge` otherwise there is a big overlap between closed and merged. Does that make sense?

**Comment by alexr00** [comment]
I see. I find that `closed` and `merged` are distinct enough since they are different PR states, but it is true that when you search for "closed" PRs you can also see merged PRs so I can understand the confusion. I would still call the settings `closed` and `merged`, but I would improve the setting description.

**Comment by dbaeumer** [comment]
Makes sense. But what is missing is a easy way to query for `closed but not merged`.

**Comment by alexr00** [comment]
@dbaeumer "closed but not merged" is what `closed` would be for.

**Comment by dbaeumer** [comment]
@alexr00 I was referring to adding a query to the GitHub viewlet that only shows `closed not merged PRs`. Something like this

```
	"githubPullRequests.queries": [
		{
			"label": "Closed not merged",
			"query": "is:closed && !is:merged"
		}
	]

``` 

Or is that possible?

**Comment by alexr00** [comment]
I have updated the description of "closed" to try to clarify closed vs. merged.

**Comment by dbaeumer** [comment]
Thanks for the tip. Will verify tomorrow.
