### ISSUE TITLE
it requires frequent window reload

### ISSUE THREAD

**Issue by krsinghshubham** [microsoft/vscode-pull-request-github#3275]
- Extension version: latest
- VSCode Version: latest
- OS: Macos BigSur

Steps to Reproduce:

1. Have a large project somewhere with 6k files with SSO enabled.
2. Work on a file having no pr history, and get back to other file and all the features will stop working.

**Comment by alexr00** [comment]
@krsinghshubham can you list one or two of the features that stop working?

**Comment by krsinghshubham** [comment]
1. Open Changes icon does not work
2.  Commit details for specific lines does not show up

**Comment by alexr00** [comment]
@krsinghshubham are you maybe referring to features provided by the GitLens extension? The GitHub Pull Requests and Issues extension doesn't show commit details for specific lines and we don't have an "Open Changes" icon.

**Comment by krsinghshubham** [comment]
@alexr00 ohh, i didn't knew. Thanks for informing.
