### ISSUE TITLE
Wording improvment for useReviewMode setting

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-pull-request-github#3276]
Testing #3267

Wording is subjective so feel free to discard any and all suggestions here :). But I did find some of the wording confusing here.

First there is a plural on `pull requests states` that is unneeded. The plural is that multiple states are controlled by the setting not multiple pull requests. Also the `Controls which` term feels redundant for a setting (unless this wording is a VS Code standard) as well as `cause the extension` as it's clear that it's the extension controlling the setting and not something that the user would care about. My suggestion on wording would be like so:

Before:
```
Controls which pull requests states cause the extension to go into review mode.
```

After:
```
Choose which pull request states will open in review mode.
```

The second sentence of the setting description was also confusing to me. If  `Open pull requests will always use review mode.` then what does the `open` `Whether review mode will be used for open pull requests` setting control?

**Comment by IanMatthewHuff** [comment]
I'm not sure if this is a separate issue or simply relating to the wording issue, but per the second sentence regardless of if I set "open" to true or false open pull requests always open for me in review mode. This would match up with the wording of the main setting, but if that is the case I don't see why "open" is an option for the modes.

**Comment by alexr00** [comment]
Great wording suggestion. I have made a small tweak because "open" is  a bit overloaded here and I want to avoid using "open" unless referring to the state of the PR:
```
Choose which pull request states will use review mode. "Open" pull requests will always use review mode.
```

I've also updated the description of merged and closed to use similar language:
```
Use review mode for merged pull requests.
Use review mode for closed pull requests. Merged pull requests are not considered "closed".
```

And finally, I have removed the `open` option as it is confusing and doesn't do anything.
