### ISSUE TITLE
Cannot read property 'owner' of undefined after "create pull request" and opening the view

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-pull-request-github#3278]
![image](https://user-images.githubusercontent.com/8586769/151627250-437ece16-49dc-4fe8-80f3-c4b0ad74fa9d.png)

found while verifying https://github.com/microsoft/vscode-pull-request-github/issues/3207, the branch had just been published to a second origin repo under my same account (JacksonKearl/CAHours2 versus the cloned JacksonKearl/CAHours)

also repros in Insiders/Nightly

**Comment by alexr00** [comment]
I'm no longer able to repro this.
