### ISSUE TITLE
Does useReviewMode setting take in additional properties?

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode-pull-request-github#3279]
Verifying https://github.com/microsoft/vscode-pull-request-github/issues/3276

I noticed in the Settings UI that the `githubPullRequests.useReviewMode` setting currently points the user to the JSON file.
If the only keys the user can configure are closed and merged, then setting `"additionalProperties": false` in the schema should allow for the Settings UI to render the setting properly.

**Comment by alexr00** [comment]
Great tip, thank you!
