### ISSUE TITLE
Avoid suggesting Issue and PR numbers immediately after comment hash

### ISSUE THREAD

**Issue by tboddyspargo** [microsoft/vscode-pull-request-github#3281]
_I didn't find any issues relating to this specific behavior. I hope I didn't miss anything..._
# Summary
It would be really nice if the Issue and Pull Request auto-complete suggestion feature was not triggered by the hash symbol that indicates a comment.

When I am writing commends have have a blank comment line, my instinct is to type `[Enter]`, `#`, `[Enter]` to achieve this. However, this results (undesirably) in me inadvertently inserting the first auto-complete suggested Issue or PR number (e.g. #1536).

# Current behavior
_In documents where "#" indicates the start of a comment on that line._
1. Hit `[Enter]` (to move to a new line)
2. Type `#`
3. Hit `[Enter]`

**Example Result**
```sh
#1532
```

# Desired behavior
_In documents where "#" indicates the start of a comment on that line._
1. Hit `[Enter]` (to move to a new line)
2. Type `#`
3. Hit `[Enter]`

**Example Result**
```sh
#

```

# Work-around
I can work around this by disabling `"githubIssues.issueCompletions.enabled"`, but there are certainly moments when I would love to take advantage of this easy way to do issue discovery and referencing.

**Comment by alexr00** [comment]
There's a setting for this. I've added all the languages that VS Code has built-in that say `#` is a line comment to the default value of the this setting:

https://github.com/microsoft/vscode-pull-request-github/blob/5577f6cde9f38aeace63f45ce39ff8d5e097e722/package.json#L292-L310
