### ISSUE TITLE
PHP DocBlock - don't show hover cards for @-mentioned users

### ISSUE THREAD

**Issue by runthis** [microsoft/vscode-pull-request-github#3286]
Issue Type: <b>Bug</b>

Create a PHP docblock with `@return` or `@todo` and hover it.

```
/**
 * test
 * @todo fix that thing
 * @return something
*/
```

Good list of tags
https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc-tags.md

Related: #2498 & #3122

Extension version: 0.32.0
VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

**Comment by alexr00** [comment]
To verify:

1. Install the pre-release version of the extension.
2. Open a folder that contains a clone of a GitHub repo.
3. Create a PHP file
4. Add the doc block from the original issue.
5. Hover over `@return` and `@todo` and verify that no GitHub user hover is shown.
