### ISSUE TITLE
Improve the interaction for 'viewed files' in the Changes View

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-pull-request-github#3287]
Toggling the viewed state for a file in the Changes view is not intuitive:

![image](https://user-images.githubusercontent.com/172399/152242314-66f23f8f-aa96-4c65-86ff-2ac1999309f7.png)

After clicking the 'checked' inline action, the toggle action moves around and is replaced with very different icon.
![image](https://user-images.githubusercontent.com/172399/152242354-b1716b93-1287-47d4-a30e-d4e26cccee3b.png)

**Comment by misolori** [comment]
Also worth pointing out that we use a mixture of checks, would be nice to consolidate/make it a bit more consistent:

<img width="300" src="https://user-images.githubusercontent.com/35271042/152256740-7dbb5fa8-bd56-4a62-b1af-ffa49ba65ad6.png">

**Comment by misolori** [comment]
Love how clear the checks are, it would be nice if the position of the icons could stay the same so it could be an easy "toggle" which makes me wonder if we can find a decorator for "not yet reviewed" so the position stays consistent?

**Comment by alexr00** [comment]
What if we swap the "git" decoration (M, D, A, etc.) for the check?
![Recording 2022-02-16 at 12 48 06](https://user-images.githubusercontent.com/38270282/154258853-958bbd69-2ac1-4f6b-a6e4-6f195f04c072.gif)

**Comment by lychung7** [comment]
@misolori we had also explored an indicator next to the file name for when the file hasn't been marked as viewed yet. Although the dot is used in other scenarios in list views. I think what @alexr00 suggested for swapping could also be a good idea! Users might not need to see the git decorations after they mark them as viewed.

https://user-images.githubusercontent.com/60596156/154302890-912387d6-bebf-42bd-856b-5d35adb8c615.mov
