### ISSUE TITLE
After making a change to a PR that was made on a fork the "Files" tree is empty

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#3294]
![image](https://user-images.githubusercontent.com/38270282/152561959-8fdf51d8-02da-4916-b108-988129246175.png)

Refreshing the tree doesn't bring the files back.

**Comment by alexr00** [comment]
To verify (you MUST use VS Code desktop for part of this, but it's ok to start in vscode.dev or github.dev if you want):
1. Find a repository that you don't own that you have commit rights too. We'll call this upstream.
2. Make a fork of upstream. We'll call this fork.
3. Make a PR from fork into upstream. The change should include 3+ files.
**From here on out, you must use VS Code desktop**
4. Open the upstream repo in VS Code.
5. Make sure you have the pre-release version of GHPRI.
6. From the "Pull Requests" view, checkout the PR you made in step 3.
7. Make a change to all of the files in the PR. Commit and push the change to the PR.
8. Open the "Change in Pull Request" view. Verify that the "Files" subtree has the correct children.

**Comment by aeschli** [comment]
Verified with PR extension running on resources from Github Repositories.
