### ISSUE TITLE
Add "today" as query option

### ISSUE THREAD

**Issue by tyler36** [microsoft/vscode-pull-request-github#3298]
I want to add 2 queries:
- show new issues
- show issues closed today

Somethign similar to:

```json
        {
            "label": "New Issues",
            "query": "state:open repo:${owner}/${repository} sort:created-desc closed:>=${yesterday}"
        },
        {
            "label": "Closed Issues",
            "query": "state:closed repo:${owner}/${repository} sort:created-desc closed:>=${today}"
        }
```

However, all the Github [search documentation](https://docs.github.com/en/search-github/searching-on-github/searching-issues-and-pull-requests) relates to setting a specific date.

Is something like this already available?  I feel like this would be a variable handled by the extension. 

Ideally, something like the below (php) psuedo code:

- `${today}` => `now()->format('Y-m-d')`
- `${yesterday}` => `now()->subDay()->format('Y-m-d')`

I would love to be able to do something like `created:>=${yesderay}T18:00:00` => issues that were created after I left work.

**Comment by alexr00** [comment]
Since we're just using GitHub's query language for this I'm going to call this an upstream issue and close this.

**Comment by tyler36** [comment]
This feature was added in [`0.104.0`](https://github.com/microsoft/vscode-pull-request-github/blob/main/CHANGELOG.md#01040)
