### ISSUE TITLE
Failed to read outdated comments

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode-pull-request-github#33]
I opened a PR which had outdated comments (changes were added on top of other changes which had comments):

One of the comments seems to appear nicely (_use lower-case `uri` for consistency_)... The other gets the `Commenting is not supported outside of diff hunk areas.` warning when clicked, even though I just want to read it, not comment on it:

<img width="1796" alt="screen shot 2018-06-26 at 16 04 49" src="https://user-images.githubusercontent.com/22350/41917441-a94dc54e-795a-11e8-8122-6968aaa37f93.png">

**Comment by rebornix** [comment]
I no longer see this issue happening. When a file which contains an outdated comment, the comment is displayed and a comment affordance is displayed near the line number, clicking on it doesn't trigger any warning popup. I'd like to close this one first, if you run into this issue again, feel free to reopen it.

**Comment by rebornix** [comment]
We still have UX issues with how to show outdated comments but we don't track it here.
