### ISSUE TITLE
Display comment bubbles different colors based on participant

### ISSUE THREAD

**Issue by marvin1up** [microsoft/vscode-pull-request-github#3302]
The comment bubbles provide a great place to quickly show where comments are in the code, but the current user, the original author, and other reviewers are all shown with a "white" comment bubble (and white indicator in the file gutter).

It would be great if the different participants added different colors.  For simplicity maybe any reviewer comments are a shade of blue, and the PR author comments a shade of yellow, and files with comments from reviewers and the author a shade of green.  The same (configurable) colors would be used in the file gutter for individual comments.

BTW, very useful extension.  👍🏾

**Comment by alexr00** [comment]
@marvin1up we're about to use color to indicate resolved/unresolved, so we won't be able to use it for the user. I do like the idea of differentiating self comments vs. other's comments in some way though.

Thanks for using the extension!

**Comment by alexr00** [comment]
I don't expect that we're going to make a change in this direction, especially since a comment thread can have replies in it from multiple users. The Comments view lets you filter comments (just in the view though, not in the editor) and you can search by user in there.
