### ISSUE TITLE
New pull requests on branches off master try to merge into a wrong branch

### ISSUE THREAD

**Issue by janakjjp** [microsoft/vscode-pull-request-github#3303]
- Extension version: v0.36.0
- VSCode Version: 1.64.1 (Universal)
- OS: macOS Monterey (12.2)

Steps to Reproduce:

1. Stage, commit and push a branch off `master` onto a GitHub Enterprise instance;
2. Issue the Pull Request command, and observe the fields in the Create Pull Request dialog in VS Code.

Expected behavior:
- "INTO" shows the repo in question and the "master" branch. (The repo is large, with hundreds of branches, or more. With a smaller repo, I do see this expected behavior.)

Actual behavior:
- "INTO" selects the very first branch available.
- Expanding the drop-down and scrolling ends at "j", so I can't choose "master."
- This means I can't properly create the PR for my commits.

Let me know if I can provide additional debugging information. Thank you!

**Comment by rchiodo** [comment]
/verified

Always show 'main' for me no matter how many branches
![image](https://user-images.githubusercontent.com/19672699/155776570-27018945-bb19-4959-8f4f-503748ac5f8f.png)
