### ISSUE TITLE
"The current repository does not have a push remote for..." when trying to create a PR from github.dev

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#3309]
1. Open a repo with github.dev.
2. Create a branch withing github.dev.
3. Try to create a PR. The "there is no upstream, do you want to publish" dialog will show.
4. "The current repository does not have a push remote for..." error shows in the "create PR" webview.

**Comment by alexr00** [comment]
This is happening in github.dev and vscode.dev because the GitHub Repositories extension's `Repository.getBranch` is returning a `Branch` that has no `upstream` set.

Interestingly, `repository.state.HEAD` _does_ have the `upstream` set. 

@joyceerhl ideally this would be fixed in GitHub Repositories since there are other places we expect there to be an `upstream` too. Note: I don't think this is a new issue in GitHub Repositories, it's just more visible now because I added proper upstream checking in the "create a PR" flow recently.

**Comment by alexr00** [comment]
Added an easy work around for this case!

**Comment by alexr00** [comment]
It expects `upstream.remote` to be `origin`, since that's what it is on `repository.state.HEAD`.

**Comment by johnpapa** [comment]
Thanks for working on this. It is an issue for our microsoft learn student ambassadors who are teaching a workshop on how to use github.dev to create branches, commit, push, make a PR, and merge. 

Thanks again!

**Comment by joyceerhl** [comment]
@alexr00 Made that change--I also noticed that RemoteHub never sets `remote` in the result of `Repository.getBranches`. Could this be a problem for https://github.com/microsoft/vscode-pull-request-github/blob/49489d66d3988c61bec54ea2b55c0d64b3b22504/src/issues/util.ts#L408-L415?

**Comment by alexr00** [comment]
👍 thanks for pointing that out! I'll make the same workaround change for the recovery release there.

**Comment by jablagH** [comment]
Thanks for try to fix this issue! This affects an important part of end-of-degree project.
