### ISSUE TITLE
Let me make comments on reviews in the PR desription

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#331]
<img width="489" alt="screen shot 2018-08-29 at 5 06 02 pm" src="https://user-images.githubusercontent.com/2193314/44822088-dbcae800-abad-11e8-81cc-62c1c66aae5d.png">

I have to go to it via the comments panel currently.

**Comment by RMacfarlane** [comment]
Closing as a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/601
