### ISSUE TITLE
Do you want to create a pull request notification stopped working

### ISSUE THREAD

**Issue by bzlom** [microsoft/vscode-pull-request-github#3310]
Might be a simple fix, but I could't find it mentioned anywhere. With the latest release of the plugin a feature was added: `Added a "Don't show again" button to the "Do you want to create a pull request" notification to better surface the associated setting.` .

I believe I pressed on the `Don't show again` button and now I don't get the popup any longer, which is expected - but I would like to re-enable it back. I tried fully reinstalling VS Code and removing all the associated folders - that didn't fix my issue. I also tried removing all of the associated folders with VS Code:
Users\<USER>\AppData\Roaming\Code
Users\<USER>\.vscode
Which got the popup window to appear once afterwards and it stopped appearing afterwards again. Is there a simple setting that re-enables the popup?

- Extension version: v0.36.0
- VSCode Version: 1.64.1
- OS: Windows 10

Steps to Reproduce:

1. Accidentally click on `Don't show again` button
2. Pull your hair out

**Comment by alexr00** [comment]
@bzlom the `Don't show again` button sets this setting: `githubPullRequests.terminalLinksHandler`. To get the notification back you can set it to `ask`, or if you always want to use the extension to create PRs you can set it to `vscode`.

**Comment by mikebronner** [comment]
@alexr00 This has stopped working for me for about a week now. I followed your advice above, the setting was set to `ask`, and I changed it to `vscode`, but PRs are not being prompted or created when clicking the Publish button on a new branch. Is this a different issue?

**Comment by alexr00** [comment]
@mikebronner it is a different, but related issue. I have opened https://github.com/microsoft/vscode-pull-request-github/issues/3347 to track adding a setting.
