### ISSUE TITLE
Avoid inserting issue titles in commit message suggestion

### ISSUE THREAD

**Issue by BlueGlassBlock** [microsoft/vscode-pull-request-github#3314]
_I  searched and didn't find any issues relating to this... Hope that I didn't miss anything..._

# Summary

Currently commit message completion also adds the title of the issue,

which makes it hard to trigger `close #1` or `fix #1` to make GitHub automatically close the certain issue.

### Current Behavior

_In commit message_

Assuming that the repo has a `#1: Example issue`

1. type `close #`
2. navigate to the issue index and hit `Enter`

**Result:**

`close Example issue #1`

GitHub doesn't close `#1` on push.

### Expected Behavior

Assuming that the repo has a `#1: Example issue`

1. type `close #`
2. navigate to the issue index and hit `Enter`

**Result:**

`close #1`

GitHub closes `#1` on push.

**Comment by alexr00** [comment]
@BlueGlassBlock checkout the setting `githubIssues.issueCompletionFormatScm`. You can change how the suggestion is formatted using that setting.
