### ISSUE TITLE
Extensions are not working in codespaces

### ISSUE THREAD

**Issue by Venkat-Swaraj** [microsoft/vscode-pull-request-github#3319]
- Extension version: 1.5.2
- VSCode Version: 1.64
- OS: Windows 11

Steps to Reproduce:
C++ intellisense extension,tabnine any extension is not working. While I type code it doesn't give any suggestions which is intended behaviuor of C++ intellisense.I tried reset intellisense database. But still the problem persists.

**Comment by alexr00** [comment]
Sounds like an issue with the C++ extension, not with the GitHub Pull Requests and Issues extension.
