### ISSUE TITLE
How to have enterprise github URL in Copy as Permalink feature ?

### ISSUE THREAD

**Issue by utkarsh22garg** [microsoft/vscode-pull-request-github#3324]
When I try to do copy as permalink, it copies URL with github.com/.... but I would like to have github enterprise URL instead when copying. 

Is there a way to achieve so ?

- Extension version: 0.36.1
- VSCode Version: 1.64.1 (system setup)
- OS: Windows_NT x64 10.0.19042

**Comment by alexr00** [comment]
Fixed by https://github.com/microsoft/vscode-pull-request-github/pull/3460
