### ISSUE TITLE
PR Description Not Loading in Firefox on github.dev

### ISSUE THREAD

**Issue by diminutivesloop** [microsoft/vscode-pull-request-github#3331]
- Extension version: 0.36.2
- VSCode Version: 1.64.2
- User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:97.0) Gecko/20100101 Firefox/97.0
- Embedder: github.dev

Steps to Reproduce:

1. Open a PR on github.dev in Firefox.
2. Open the PR description from the sidebar.

A new tab loads but its contents never load. The following error is logged to the console:
```
Content Security Policy: The page’s settings blocked the loading of a resource at https://github.vscode-unpkg.net/GitHub/vscode-pull-request-github/0.36.2/extension/dist/webview-pr-description.js (“script-src”). [main.js:861:20](https://ticino.blob.core.windows.net/sourcemaps/f80445acd5a3dadef24aa209168452a3d97cc326/core/vs/workbench/contrib/webview/browser/pre/out-vscode/vs/workbench/contrib/webview/browser/pre/main.js)
```

This issue persists even after clearing cookies and site data. I've also made sure to disable Enhanced Tracking Protection as that was causing issues with github.dev in the past.

**Comment by alexr00** [comment]
@diminutivesloop this seems to be fixed in VS Code insiders. Switching to insiders is very easy if you want to get PR description back right now:

![image](https://user-images.githubusercontent.com/38270282/155168237-46f63fa6-d2f8-4be9-a173-4496847be60a.png)
