### ISSUE TITLE
Test mark as viewed

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#3332]
Refs: https://github.com/microsoft/vscode-pull-request-github/issues/3287

- [x] anyOS @rzhao271
- [x] anyOS @mjbvz

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode-pull-request-github/issues/new?body=Testing+%233332%0A%0A&assignees=alexr00)

---

The old UX for marking a file in a PR as viewed caused some button jumping and used icons that were hard to understand. Within the limitations of the tree view, we've tried to improve upon this.

1. Install the pre-release version of GitHub Pull Requests and Issues (instructions: https://github.com/microsoft/vscode-pull-request-github/wiki/Pre-release-Build). Browser is fine if you want.
2. Open a PR that you don't mind marking files as viewed in (You can open a PR from the "Pull Requests" view).
3. Figure out how to mark a file as viewed. Verify that the icons representing "mark as viewed" and "mark as unviewed" make sense.
4. Verify that when a file has been marked as viewed that it has no color and the git file decoration changes into a check.
5. Verify that that when you mark a file as unviewed it regains it's color and file decoration.

**Comment by mjbvz** [comment]
Test on MacOS and seems to work well

To improve discoverability, could there also be a button in the editor tool bar that shows in diffs from a PR?
