### ISSUE TITLE
Disable auto-opening PR comments/discussions

### ISSUE THREAD

**Issue by ryan-efendy** [microsoft/vscode-pull-request-github#3335]
As a user, I want to have an option/setting to disable auto-opening GitHub comments/discussion when I navigate to a file.

**Comment by alexr00** [comment]
Checkout the setting `githubPullRequests.commentExpandState`.

**Comment by otech47** [comment]
this doesn't seem to work when set to `collapseAll`. the comment still shows expanded when navigating to the file with the comment... tried collapsing before navigating away and it is still not respected

**Comment by alexr00** [comment]
@otech47 are you navigating to the file by clicking on the comment in the Comments view? If you click on a comment in the Comments view then the comment will expand.

**Comment by MiguelNiblock** [comment]
@alexr00  this doesn't work. I've set comment expand state as you suggested, and when i open the file the comments reopen.

**Comment by alexr00** [comment]
@MiguelNiblock I'm seeing this work:
1. Set `"githubPullRequests.commentExpandState": "collapseAll"`
2. Open a file with a PR comment from the "Pull Requests" view. The comment is collapsed.

Is it possible that you're opening the file and seeing the expanded comment, and only after seeing the comment you change the setting? In this case, we cannot collapse the comment. You can use the "Collapse all action" for this one time issue when you have freshly changed the setting:
![image](https://github.com/microsoft/vscode-pull-request-github/assets/38270282/ac87018e-2804-41f4-a813-0fd9a7a260ac)

**Comment by jverce** [comment]
Same here, this line has no effect:
```json
{
  "githubPullRequests.commentExpandState": "collapseAll"
}
```

All PR comments still appear in files every time I reopen them. I have to click on the **Collapse All Comments** button myself every time I open a file. If I reopen the file, the comments are showing up again.

**Comment by alexr00** [comment]
@jverce Is it possible that you're opening the file and seeing the expanded comment, and only after seeing the comment you change the setting? The setting only applies to comments that have not set been set, so you'll need to reload for the setting to take effect if there are already comments.

**Comment by myonov** [comment]
As far as I understand it, there are 2 things that happen when you open a file with comments:

* The comments are shown directly in the editor (the setting `"githubPullRequests.commentExpandState": "collapseAll"` will actually affect that behavior and the comments will be collapsed).
* The panel below the editor will be opened and the comments section will be focused. This behavior is not affected by `githubPullRequests.commentExpandState` and it is kind of annoying.

**Comment by alexr00** [comment]
For the second one, we have `comments.openView`.

**Comment by myonov** [comment]
Thanks, Alex! That was super quick :)
That option was what I needed.
