### ISSUE TITLE
No GitHub Pull Requests and Issues in the sidebar, issues autocompletion and hover not working

### ISSUE THREAD

**Issue by ilyakochik** [microsoft/vscode-pull-request-github#3336]
- Extension version: `v0.36.2`
- VSCode Version: `1.64.2 (Universal)`
- OS: `macOS Monterey 12.1`

I have Node.js project, GitHub repo, and a local VSCode with following plugins: ESLint, GitHub Codespaces, GitHub Pull Requests and Issues.

Problems:
- There is no GitHub Pull Requests and Issues in the sidebar
- When I start typing `// #` issues lookup is not triggered
- There is no hover over issues in comment i.e. `// TODO #7`

Output from GitHub Pull Request:
```
[Info] /Users/xxxxxxx/.ssh/config: ENOENT: no such file or directory, open '/Users/xxxxxxx/.ssh/config'
[Info] Registering git provider
[Info] Looking for git repository
[Info] Found 0 repositories during activation
[Info] Git repository found, initializing review manager and pr tree view.
[Info] Repository file:///Users/xxxxxxx/Code/prototype has been opened
[Info] Review> Validate state in progress
[Info] Review> Validating state...
[Info] Cannot updates repositories as git is uninitialized
[Info] Git initialization state changed: state=initialized
[Info] Review> Queuing additional validate state
[Info] Review> Validating state...
[Info] No remotes found. The following remotes are missing: origin, upstream
[Info] No GitHub remotes found
[Info] Review> Queuing additional validate state
[Info] Repo state for file:///Users/xxxxxxx/Code/prototype changed.
[Info] Repo file:///Users/xxxxxxx/Code/prototype has already been setup.
[Info] Review> Validating state...
[Info] Found GitHub remote
[Info] Review> no matching pull request metadata found for current branch testing-xxxxxxx
[Info] Review> no matching pull request metadata found on GitHub for current branch testing-xxxxxxx
```

Structure of the repo:
```
% git remote -v
origin  https://github.com/xxxxxxxxxx/prototype.git (fetch)
origin  https://github.com/xxxxxxxxxx/prototype.git (push)

% git branch   
  main
  testing-xxx
* testing-xxxxxxxxx
```

**Comment by alexr00** [comment]
@ilyakochik can you set the settign `githubPullRequests.logLevel` then reload your VS Code window and share the Output from GitHub Pull Request again?

**Comment by alexr00** [comment]
You could also try signing out and signing in again in VS Code.

**Comment by ilyakochik** [comment]
@alexr00 , sorry it took me a while. below are the additional details.

### You could also try signing out and signing in again in VS Code.

Didn't help.

### Set the setting `githubPullRequests.logLevel` then reload your VS Code window and share the Output from GitHub Pull Request again?

See attached [logs.txt](https://github.com/microsoft/vscode-pull-request-github/files/8257152/logs.txt)

**Comment by alexr00** [comment]
Thanks @ilyakochik. Everything looks normal in the logs. We're finding your `origin` remote and able to fetch issues. 

Can you share a screen shot of "no GitHub Pull Requests and Issues in the sidebar"?

**Comment by ilyakochik** [comment]
You see plugin is installed, but there is nothing in the sidebar and nothing happens when I click on `GitHub Pull Requests: Sign in to GitHub`

<img width="729" alt="image" src="https://user-images.githubusercontent.com/45572664/158679877-146fea7c-bf21-4efb-a544-a6183f689e3c.png">

**Comment by alexr00** [comment]
Thanks @ilyakochik. Can you click on the "GitHub" activity bar icon and share a screen shot of that? The current screen shot shows the "Source Control" sidebar.

**Comment by ilyakochik** [comment]
That tab seems to fetch issues successfully:
<img width="223" alt="image" src="https://user-images.githubusercontent.com/45572664/158791088-b0956755-b294-4ac0-8157-6ae088238ee0.png">

However, when I type `// #` there is no issue lookup pop-up:
<img width="197" alt="image" src="https://user-images.githubusercontent.com/45572664/158791283-3609b210-a0c6-4f5c-930e-a81fbb4951ac.png">

**Comment by ilyakochik** [comment]
@alexr00 , is there any further information you might need?

**Comment by alexr00** [comment]
Can you also check that the value of the setting `githubIssues.ignoreCompletionTrigger` hasn't been modified? There are some languages that we don't to the `#` suggest for, and they are set in `githubIssues.ignoreCompletionTrigger`. It looks like you're using javascript, which by default **should** have the `#` suggest (and therefore should not be listed in that setting).

**Comment by ilyakochik** [comment]
Here is what I've got for `githubIssues.ignoreCompletionTrigger`
<img width="629" alt="image" src="https://user-images.githubusercontent.com/45572664/165086636-7912a6f3-aafd-4d12-9339-88a5ec0d0932.png">

**Comment by ilyakochik** [comment]
`editor.quickSuggestions` was the root cause. Once I changed it to `"editor.quickSuggestions": {"comments": "on",...}` all started working fine.

Thanks a lot!

By the way, it is very hard to find this setting—it is editable only via settings.json (see screenshot, there is no UI for it). Is it on purpose?
<img width="531" alt="image" src="https://user-images.githubusercontent.com/45572664/165124852-12a2d92e-f6fc-409b-8389-d39211ee88f4.png">

**Comment by alexr00** [comment]
> By the way, it is very hard to find this setting—it is editable only via settings.json (see screenshot, there is no UI for it). Is it on purpose?

@jrieken for the `editor.quickSuggestions` question.

**Comment by jrieken** [comment]
> @jrieken for the editor.quickSuggestions question.

@rzhao271 @roblourens

**Comment by roblourens** [comment]
The type of that setting is boolean or object. So it can't be rendered in the UI
