### ISSUE TITLE
'Mark file as not viewed' triggered exception 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-pull-request-github#3337]
Testing #3332

1. Browse a pull request (don't actually check it out)
2. Click on one of the files to view a diff
3. In the command palette, run: mark file as not viewed

**bug**
I see an exception: 

```
workbench.desktop.main.js:787 Marked file as not viewed failed: TypeError: Cannot read properties of undefined (reading 'pullRequest')
```

**Comment by alexr00** [comment]
That command should not be available from the command palette.
