### ISSUE TITLE
'Mark file as not viewed' always shows up in the command palette

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-pull-request-github#3338]
Testing #3332

1. Open a random file in a repo
1. Open the command palette and search `mark`

**Bug**
The `Mark file as not viewed` command always seems to be present. Instead I think it should only show when the current file is part of a PR

**Comment by alexr00** [comment]
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/3337, that command should never be in the command palette.
