### ISSUE TITLE
There is a `mark as not viewed` command but no `mark as viewed` command?

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-pull-request-github#3339]
Testing #3332

1. Open the command palette and search `mark`

**Bug**
There is a `Mark file as not viewed` command but not a `mark file as viewed ` command. I think both should either be present or both should be hidden

**Comment by rzhao271** [comment]
I'm on Windows and don't seem to see it.
I opened a PR and tried opening the diff of the file, the file itself, and the description view, before opening the command palette in each case.
v0.37.20220

![Command prompt not showing mark commands](https://user-images.githubusercontent.com/7199958/155584118-08b96ab9-2c02-4e6c-8fa1-2e141b39bbb9.PNG)

**Comment by alexr00** [comment]
Neither should show. Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/3337
