### ISSUE TITLE
 Resolving thread failed

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-pull-request-github#3348]
Testing microsoft/vscode#143545

- Check out this PR and click resolve on this thread: https://github.com/roblourens/testrepo/pull/5#discussion_r813191803
- I got this error popup:

`Resolving conversation failed: Error: GraphQL error: Variable $input of type ResolveReviewThreadInput! was provided invalid value for threadId (Expected value to not be null)`

Log:
[ghpr.log](https://github.com/microsoft/vscode/files/8127065/ghpr.log)

**Comment by alexr00** [comment]
This is a result of the hack used to work around https://github.com/microsoft/vscode/issues/130107.

For March, I'll add the API proposal in VS Code and adopt it here.

**Comment by alexr00** [comment]
Fixed with https://github.com/microsoft/vscode-pull-request-github/commit/735e70739f45bd66c268787bb75ee5ba642ba910 and https://github.com/microsoft/vscode/commit/4ce5585b4ce4ef3ffa59d617336eaec2fc31d160
