### ISSUE TITLE
Comments panel - comment appears twice

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode-pull-request-github#3349]
Testing microsoft/vscode#143545

1. Open a file from the pull request in the diff editor
2. Add a comment for the file

Comment appears twice in the comments panel.
It looks like the comment is added both to the file, as well as the "read only" resource.
![image](https://user-images.githubusercontent.com/3372902/155531027-134d3ddd-457e-484b-8673-eb28e97a2881.png)

**Comment by alexr00** [comment]
This has to do with how we handle comments from the "Pull Requests" view and the "Changes in Pull Request" view. Not a new issue, so I will fix for March.
