### ISSUE TITLE
No prompt to log in and PR view is just blank

### ISSUE THREAD

**Issue by pweiss-mri** [microsoft/vscode-pull-request-github#3351]
- Extension version: v0.36.2
- VSCode Version: 1.64.2 (user setup)
- OS: Windows_NT x64 10.0.19044

Full VS Code "About" info:
Version: 1.64.2 (user setup)
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:02:28.252Z (2 wks ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044

Steps to Reproduce:

1. Install extension
2. Reload
3. Error (only in dev tools)

I have been trying to get the github pull requests to show up and haven't had any luck.  I've seen several issues with similar symptoms but reading the full history on the issue shows mine is different.

I think the root of the issue is a timeout related to attempting to authenticate.  I see this error in the dev tools:
>Activating extension 'GitHub.vscode-pull-request-github' failed: Timed out waiting for authentication provider to register.

In the extension output I see:
>[Info] C:\Users\\[username]\\.ssh\config: ENOENT: no such file or directory, open 'C:\Users\\[username]\\.ssh\config'

I've tried manually running the **GitHub Pull Requests: Configure...** command and get the following error message:
>Command 'GitHub Pull Requests: Configure...' resulted in an error (command 'pr.configurePRViewlet' not found)

I've tried downgrading the extension to 0.34.3 as well as upgrade to the pre-release version but got the exact same symptoms/errors with those.  (the timeout error was worded slightly differently in 0.34.3 but it still still a timeout error around authentication)

**Comment by alexr00** [comment]
@pweiss-mri this indicates the the built-in GitHub Authentication extension has failed to activate. Do you have the built-in GitHub Authentication extension enabled?

**Comment by pweiss-mri** [comment]
I had apparently disabled the built in github authentication extension sometime in the past and forgot about it.  This is working for me after I re-enabled that extension.

**Comment by alexr00** [comment]
I can add GitHub Authentication as required dependency of this extension, which should result in a more obvious error. I don't think this will cause an issue for enterprise users.

**Comment by thomaspeugeot** [comment]
Hello, I have met the same issue. 
Question : how do you enable " the built in github authentication extension" ?
thks
