### ISSUE TITLE
pr.exit undefined error

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode-pull-request-github#3352]
- Extension version: v0.37.20220224
- VSCode Version:
Version : 1.65.0-insider (user setup)
Validation : 3112460dc48ce7e557ea9feeaae04b912164b48b
Date : 2022-02-24T05:15:20.989Z
Electron : 16.0.9
Chromium: 96.0.4664.174
Node.js : 16.9.1
V8 : 9.6.180.23-electron.0
- OS: Windows 10

Steps to Reproduce:

1. Check out a PR
2. Go back to the view that lists all the PRs
3. In the status bar branch selector, switch back to main
4. Quickly go to the PR in the PR list view, right click, exit review mode
5. :bug: error notification

If I wait long enough between steps 3 and 4, though, I notice that an info dialog pops up as well saying "The default branch is already checked out."

![A screenshot showing the error](https://user-images.githubusercontent.com/7199958/155586604-be625fd7-fc3f-4a9a-981f-3aeca7966d98.PNG)

**Comment by alexr00** [comment]
I'm not able to reproduce the error. 

The info notification "The default branch is already checked out." is by design.
