### ISSUE TITLE
Create PR view should refresh itself somehow

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode-pull-request-github#3357]
I was testing #2988 which worked but just to test it further, I wanted to add a 2nd commit and attempt to create a PR to see what the placeholder is then. I never "cancelled" the previous "Create Pull Request" view and as a result, after I pushed a 2nd commit to my branch and went into the "Pull Request" view (note, not Create Pull Request view) to click the button to create a pull request it simply focused on the existing Create Pull Request view and didn't update the details (in other words it was stale). 

- Extension version: v0.37.2022022414
Version: 1.65.0-insider (user setup)
Commit: 8440b8f47231147823ba9696913d642e5f2d9d58
Date: 2022-02-25T05:17:33.544Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

Steps to Reproduce:

1. Create a branch
2. add a commit
3. push it
4. go to Pull Requests view and click the create PR button
5. (don't do anything with the now open Create PR view. Leave it be)
6. now add another commit and push
7. Go to the Pull Request view and click the create PR button again
8. Now you are looking at the Create PR view

Expected:

The info is updated with the new placeholder and commits

Actual:

The info is stale and doesn't take into account the commit I just committed.

Proposal:

* Automatically refresh when it makes sense
* Have a refresh button on the Create PR view
* ^^ both?

**Comment by alexr00** [comment]
I'm not seeing the staleness in the "Create Pull Request" view. The title stays the same because we only look at the first commit or else we use the branch name and the diffs in the "Compare Changes" view update. What info was stale?

**Comment by TylerLeonhardt** [comment]
So I think before I was seeing staleness in the changed files but I don't see it anymore so that's good.

With that said, I still see staleness with the title. 

1. Create a branch
1. add a commit
1. push it
1. go to Pull Requests view and click the create PR button (don't do anything with the now open Create PR view. Leave it be)
1. now add another commit and push
1. Go to the Pull Request view and click the create PR button again
1. Now you are looking at the Create PR view

> otherwise we use the branch name when there are several commits

When I follow these steps, the title doesn't get updated to be the branch name. It stays as the first commit.

**Comment by TylerLeonhardt** [comment]
This is verified, but I did see slowness in the title & description updating but I have seen that outside of the context of this issue as well (like when creating a new PR)
