### ISSUE TITLE
Unable to edit PR from forked repository via github.dev

### ISSUE THREAD

**Issue by LinqLover** [microsoft/vscode-pull-request-github#3358]
- Extension version: v0.36.2
- VSCode Version: 1.64.2
- OS: github.dev

Steps to Reproduce:

1. Fork a repository that you do not have write access to
2. Create a new patch branch, make a commit, and push it to your fork
3. Create a PR to merge your patch branch into the upstream repo
4. On the PR page, press <kbd>.</kbd> to open github.dev
5. Edit a file
6. Go to source code control and try to commit your changes

Expected behavior:

A new commit is added and pushed to the fork branch.

Actual behavior:

I am asked to "enter the title for a new pull request", but I should already be editing a PR!

![image](https://user-images.githubusercontent.com/38782922/155860604-e94a01e7-03fc-4c8a-80fb-0c242328cb17.png)

**Comment by alexr00** [comment]
Moved to https://github.com/microsoft/vscode-remote-repositories-github/issues/140 since that's where support for the commit action from the source control view comes from.
