### ISSUE TITLE
Compatible issue with Code

### ISSUE THREAD

**Issue by etionsun** [Microsoft/vscode-pull-request-github#336]
version: vscode-pull-request-github-0.0.19.vsix
vscode:1.26.1 (1.26.1)
Error message below when installing via VSIX.
Unable to install Extension 'microsoft.vscode-pull-request-github-0.0.18' as it is not compatible with Code '1.26.1'.

**Comment by rebornix** [comment]
@etionsun to install this extension, you need to use VSCode Insider https://code.visualstudio.com/insiders/ or our next Stable version 1.27.
