### ISSUE TITLE
Comments go away i PR description page when switching to another tab and back

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-pull-request-github#337]
Related: https://github.com/Microsoft/vscode-pull-request-github/issues/313

I just lost a comment, and then did it again immediately after 😢. I think webviews can save and restore state now?

**Comment by RMacfarlane** [comment]
Should be fixed in 0.0.19: https://github.com/Microsoft/vscode-pull-request-github/issues/329

**Comment by Tyriar** [comment]
@RMacfarlane could focus and scroll position also be restored?
