### ISSUE TITLE
Strange rendering when comment location has been deleted

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-pull-request-github#3373]
<img width="1697" alt="image" src="https://user-images.githubusercontent.com/8586769/156820679-cf593bb7-a224-4d1b-bc29-510c12da58b5.png">

When I went to the diff view I see:
<img width="1253" alt="image" src="https://user-images.githubusercontent.com/8586769/156820787-7d484e44-dd35-4d79-8e7d-5b94e2d8d4ef.png">

which seems better

**Comment by JacksonKearl** [comment]
Source: https://github.com/microsoft/vscode/pull/144352

**Comment by JacksonKearl** [comment]
<img width="1047" alt="image" src="https://user-images.githubusercontent.com/8586769/156831837-87b0c66d-9f65-40d9-8d15-7c844ed131ff.png">

**Comment by JacksonKearl** [comment]
now the diff editor is broken too

**Comment by alexr00** [comment]
There have been a lot of changes to the comments bar recently. We can re-open if it's still happening.
