### ISSUE TITLE
Backspace, arrows keys, etc. not working in diff comment box

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#338]
I tried to make a comment on src/TerminalLine.ts (A) in xterm.js PR 1632, I can type out text fine but backspace and arrows don't work. Enter, space, alpha, number keys work.

<img width="594" alt="screen shot 2018-08-30 at 7 43 57 am" src="https://user-images.githubusercontent.com/2193314/44859202-854ebf80-ac28-11e8-9503-998051eb5613.png">

Closing the comment box and trying again yields the same result. Closing the file and opening again also doesn't fix it. Reloading the window fixed it.

**Comment by Tyriar** [comment]
This was using v0.0.18

**Comment by Tyriar** [comment]
There weren't any errors in devtools.

**Comment by RMacfarlane** [comment]
Possibly related: https://github.com/Microsoft/vscode/issues/23687

Are you able to consistently repro this? I haven't been able to yet on my machine

**Comment by Tyriar** [comment]
I only saw it that one time, fixed after reloading.

**Comment by RMacfarlane** [comment]
Closing this issue since there have been no further reports of this and I haven't been able to repro it
