### ISSUE TITLE
Allow a review to sort by viewed/unviewed files

### ISSUE THREAD

**Issue by jmarolf** [microsoft/vscode-pull-request-github#3380]
Today we have three buttons at the top that affect the list of files to review: 
<img width="102" alt="image" src="https://user-images.githubusercontent.com/9797472/157104747-d1d9080d-7d5c-4ee6-9834-1e016e8f118d.png">

- Toggle View Mode
- Refresh
- Collapse All

I would like there to be a fourth option "Filter" that allows me to filter the set of files shown in the list.

Something ~ like this:

<img width="45" alt="image" src="https://user-images.githubusercontent.com/9797472/157105637-881604c0-d31a-415b-acb4-f4aee7f43bab.png#gh-light-mode-only">
<img width="45" alt="image" src="https://user-images.githubusercontent.com/9797472/157105775-4452311c-7ac8-410e-b66d-e46681b64d39.png#gh-dark-mode-only">

- [ ] Files marked as "Viewed"
- [ ] Files not marked as "Viewed"
- [ ] Files with comments
- [ ] Files with no comments

**Comment by jmarolf** [comment]
oh that is useful. Why is that hidden in a panel instead of being part of the "Github Pull Requests" sidebar?

**Comment by alexr00** [comment]
It's part of VS Code's UI, not part of this extension. We are working on making the "Comments' view easier to find. In the insiders version of VS Code and the pre-release version of this extension the "Comments" view opens:
- when you check out a PR at the same time that the "Pull Request" view opens.
- wen you open a file with comments.

**Comment by alexr00** [comment]
Between the Comments view and the new checkboxes in the PR view, I think the scan-ability needs of this feature request have been met without adding an additional filter.
