### ISSUE TITLE
Enable extensions (eg. lint, typescript) inside the readonly mode

### ISSUE THREAD

**Issue by JoachimKoenigslieb** [microsoft/vscode-pull-request-github#3381]
Hi, 

I've tried to use this amazing extension to review code changes. The only issues I've encountered is that my linter and typescript support is not active in the pull requests view. I would love to get help to spot issues in the files I'm reviewing using my usual extension tools. 

Is this possible to implement? 

Joachim

**Comment by alexr00** [comment]
Checking out the PR should get you the extension support you want. 

Extensions would have to opt in to supporting our PR diff file type, which I don't think they would do.
