### ISSUE TITLE
PR view should emphasize assigning to yourself like on .com

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#3382]
Assigning in extension requires filtering/scrolling:

![image](https://user-images.githubusercontent.com/2193314/157268585-b82af13f-4d8d-4d7a-b619-f9f7ce65001e.png)

Assigning via .com doesn't:

![image](https://user-images.githubusercontent.com/2193314/157268714-015417dc-1e87-4ec9-949c-e5d6f75f81d6.png)

**Comment by alexr00** [comment]
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/3627
