### ISSUE TITLE
Assigning reviewers and assignees should use simple quick open

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-pull-request-github#3385]
It's very tricky to get a fast keyboard flow to assign people as a PR reviewer or assignee, due to the fact that we use the multiple choice quick input interface. When that comes up, typing a name and hitting Enter won't actually select the person.

![image](https://user-images.githubusercontent.com/22350/157449341-847685f3-ae91-4023-a260-ee78b18bcaaa.png)

Suggestion:

- Switch the default experience to use single quick input, for fast input
- Have the first option be `Pick multiple people`, which toggles the quick input mode to multiple selection

**Comment by alexr00** [comment]
It would also be nice if the multi select quick pick was more keyboard friendly...

**Comment by alexr00** [comment]
We're actually switching more fully to the multiselect quick pick instead. Hitting Space will select the person.
