### ISSUE TITLE
When `Create Issue` is executed, "ASCII code `0xdf`" will be entered.

### ISSUE THREAD

**Issue by ShortArrow** [microsoft/vscode-pull-request-github#3388]
Issue Type: <b>Bug</b>

`ctrl`+`s` has conflict with `normal file save command` on windows.

1. change shortcut to `ctrl`+`alt`+ `s`
1. press `create an issue` button
1. edit `newissue.md`
1.  `ctrl`+`alt`+ `s` 
1. appear "Mysterious character"  on `newissue.md`: that has ascii code `0xdf`

If click the UI button without using the shortcut key, it will work as expected.

I don't know if it's related, 

```
GitHub.vscode-pull-request-github]: `remoteHub/pullRequest` is not a valid menu identifier
_logMessageInConsole @ workbench.desktop.main.js:3036
```

Extension version: 0.37.2022021515
VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4150 CPU @ 3.50GHz (4 x 3492)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (2.38GB free)|
|Process Argv|--crash-reporter-id 5beae045-4e82-45fa-a01a-426c34e588f3|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc008:30440022
pythonvsnew555:30450902
vsbas813:30436447
vscscmwlcmc:30438804
vscgsvid1:30447480
helix:30440343
dockersurvey3:30446832
pynewfile477:30450038

```

</details>

**Comment by ShortArrow** [comment]
Thank you for your reply!
I misunderstood that autosave had to be turned off.

Even if autosave is off, I think it's better to can work with non-collision shortcut keys. Because not everyone likes auto-save. As a proof, by default vscode, autosave is disabled.

If you like this idea, I would be grateful if you could adopt it.
If necessary, let me know and I will create a new Issue.

**Comment by alexr00** [comment]
It is too late to change the default keybinding for this, as many users will have gotten used to the current keybinding. 

The ctrl+s keybinding to create the issue was also a user request, so while I agree that not every user has the same keybinding preferences, I will not be able to make both happy with the default even if I do change it.

I think this is a good example of why we let you configure the keybindings yourself if you want to :). If you have not modified keyboard shortcuts before, you can see how to do so here: https://code.visualstudio.com/docs/getstarted/keybindings?msclkid=d6df428da9f111eca4f91c5cfc10415f#_keyboard-shortcuts-editor

**Comment by ShortArrow** [comment]
@alexr00 keybind is not working for me. on "autosave off". why😢?

This is so stressful while npm watch command are runnning. For example, on project using react or flutter and others.

> https://github.com/microsoft/vscode-pull-request-github/issues/2556#issuecomment-1061906127
> You can add your own keyboard shortcut for this if you want it though. The command is issue.createIssueFromFile.
