### ISSUE TITLE
Clicking on a change from a commit opens change from all commits

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-pull-request-github#3389]
Steps to Reproduce:

1. have a change with many commits
2. expand one commit
3. click into a file for a change

=> 🐛 the file from the main change is expanded

![Recording 2022-03-10 at 10 04 48](https://user-images.githubusercontent.com/900690/157627957-d00729dc-b6c9-4ebe-af0a-1f28be3334ff.gif)

**Comment by alexr00** [comment]
We follow which file you open, and if it exists in the "Files" subtree, we reveal it. For the most recent commit, the file that you open is the same file that is on your branch's head, so it also exists in the "Files" subtree. This will not happen for earlier commits.

There is no information in the `vscode.window.onDidChangeActiveTextEditor` event that lets me see where the file was opened from. 

I think the best approach here is to respect the `explorer.autoReveal` setting in the "Changes in Pull Request" view.
