### ISSUE TITLE
Support resolving conversations

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#339]
<img width="789" alt="screen shot 2018-08-30 at 9 55 03 am" src="https://user-images.githubusercontent.com/2193314/44866689-c9e35680-ac3a-11e8-9211-735d7c88c1bb.png">

Needs support for deemphasizing outdated/resolved comments https://github.com/Microsoft/vscode-pull-request-github/issues/89

**Comment by aoberoi** [comment]
I would like to add that I don't necessarily want "outdated" comments hidden, but i would like "resolved" comments hidden. I hope that the resolve button is available and that these two properties can be filtered separately.

**Comment by myartsev** [comment]
+1 just tried out the extension and can see myself using it regularly if resolving conversations directly from VSCode was possible, otherwise, there's too much noise and I end up going directly to the GitHub website.

**Comment by stgarf** [comment]
Same as the last two comments -- If in the Github PR UI the `resolved comments` and `outdated comments` are hidden when appropriate (e.g. resolved and/or outdated) but I also can click a small icon to reveal them to take a second-glance, this would be the icing on the cake for this extension. I basically don't need to leave VSCode... :)

**Comment by JaimieMurdock** [comment]
I would also really like to see this feature. I'm still reviewing PRs through the website instead of VSCode because of it. As @dylmye pointed out, it is exposed by the API. Would anyone have a pointer on what files need to be edited to add this support? I might be willing to work on this, but would need some mentorship.

**Comment by liang2zhu1** [comment]
The extension is awesome but this features is really blocking me from using that day-to-day

**Comment by ghs180** [comment]
This extension would be perfect if it had this feature :).

**Comment by judy** [comment]
Throwing my hat in here too. This extension is unusable to me until I can hide resolved comments/see only unresolved comments.

**Comment by MrMage** [comment]
+1. It would be great if resolved comments could at least be indicated _somehow_ in the UI, or if the extension could remember the "collapsed" state across closing and re-opening a particular diff.

**Comment by hasbro17** [comment]
+1 for remembering that a comment is resolved. Or at least remember if we've collapsed the comment locally within a review session.
Great extension overall except for some rough edges like this which break your focus while reviewing and force you back to the browser to see what comments are outdated.

**Comment by MrMage** [comment]
FYI, I have switched my code reviews to [Reviewable.io](https://reviewable.io/) now. That lets me hide resolved comments and quickly go through all my previous comments, to ensure that all my comments have been addressed. Overall, it has really helped me keep track of reviews for large PRs.

I am not affiliated with Reviewable, just a very happy customer.

**Comment by JacksonKearl** [comment]
cc @RMacfarlane @alexr00 I self-assigned this forever ago but I'm not doing much GHPR anymore.

**Comment by Perh0rd** [comment]
Totally agree, it's very noisy and make PR review unusable.

**Comment by bamurtaugh** [comment]
Linking https://github.com/microsoft/vssaas-planning/issues/2176

**Comment by Perh0rd** [comment]
> Linking https://github.com/microsoft/vssaas-planning/issues/2176

Link broken
