### ISSUE TITLE
The extension got extremely large with v0.38.0

### ISSUE THREAD

**Issue by filiptronicek** [microsoft/vscode-pull-request-github#3392]
Hi there 👋!
We noticed today that the extension got 81x bigger with the latest update, https://github.com/microsoft/vscode-pull-request-github/releases/tag/v0.38.0. This is because now a `beats-internal.tar.gz` file is included, which includes 3 very big binaries. In our team we were wondering whether this is an intentional change or something unintentional. 

cc @alexr00, this looks like something potentially problematic for many users with slower connections.

**Comment by alexr00** [comment]
Thank you @filiptronicek for reporting this!

**Comment by filiptronicek** [comment]
I'm blown away by the speed of this being closed 😄, kudos!

**Comment by alexr00** [comment]
Better to make a recovery release now than on Monday :)
