### ISSUE TITLE
VSCode is asking to sign into github every time I open VSCode

### ISSUE THREAD

**Issue by hartra344** [Microsoft/vscode-pull-request-github#340]
Using latest version of VSCode-Insiders and version 0.0.18 of the extension
![screen shot 2018-08-30 at 12 55 04 pm](https://user-images.githubusercontent.com/13208452/44875937-67974f80-ac54-11e8-81e8-a7628bcb1d75.png)
![screen shot 2018-08-30 at 12 58 50 pm](https://user-images.githubusercontent.com/13208452/44875964-7978f280-ac54-11e8-88e2-f6056f303920.png)

**Comment by shana** [comment]
@hartra344 Do you sign in or do you dismiss the notification?

**Comment by hartra344** [comment]
I sign in every time, doesn’t work at all if I don’t

**Comment by shana** [comment]
@hartra344 Does your user settings have an entry like this:

```
    "github.hosts": [
        {
            "host": "https://github.com",
            "username": "oauth",
            "token": "system"
        }
    ],
```

and does your keychain have an entry with name `vscode-pull-request-github` with a token?
