### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by DameonWebb** [microsoft/vscode-pull-request-github#3413]
- Issue Type: `Performance`
- Extension Name: `vscode-pull-request-github`
- Extension Version: `0.32.0`
- OS Version: `Darwin x64 18.7.0`
- VS Code version: `1.62.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/var/folders/xp/c47hgstn61xdxny441td81200000gn/T/GitHub.vscode-pull-request-github-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by alexr00** [comment]
Closing due to missing info.
