### ISSUE TITLE
PR doesn't support templates on .github repository

### ISSUE THREAD

**Issue by GuillermoMarcel** [microsoft/vscode-pull-request-github#3414]
Current version work fine with PR templates in the same repository.

Many Companies work with unified templates on the ".github" repository located commonly at `https://github.com/<username>/.github`

I can see this working as detecting that repository if no template is located in current repository. Or as a configuration where the user can define the path to the PR template file

settings sample:
```json
{
  "pr_template_url": "https://github.com/GuillermoMarcel/.github/blob/main/PULL_REQUEST_TEMPLATE.md"
}
```

**Comment by cl-christschantz** [comment]
I would also like to see this implemented.
