### ISSUE TITLE
Not show editor info when preview pull request

### ISSUE THREAD

**Issue by ZTjack** [microsoft/vscode-pull-request-github#3416]
- Extension version: v0.38.1
- VSCode Version: 1.65
- OS: Mac

Steps to Reproduce:

This is an awesome plugin and I have use this for about half an year. But several weeks ago, I found that I cannot see the editor info when preview my member's pull request.

Before, it was looked as this:
<img width="1352" alt="image" src="https://user-images.githubusercontent.com/20082885/159157273-37d3f9a7-3977-4e3b-921d-a6eb98ac1181.png">

But now it looks like this without editor info shown:
<img width="1345" alt="image" src="https://user-images.githubusercontent.com/20082885/159157316-16cc9937-f741-4519-9bc9-484a1e4327f4.png">

**Comment by alexr00** [comment]
Glad to hear you like the extension!

The info you have outlined is coming from another extension (maybe Gitlens?), as we don't provide that feature. I would recommend filing an issue with that extension.
