### ISSUE TITLE
Can't merge PR branch with master branch

### ISSUE THREAD

**Issue by lucasrodes** [microsoft/vscode-pull-request-github#3419]
## System details

- Extension version: v0.38.1
- VSCode Version: 1.65.2
- OS: Linux 5.10.93-1-MANJARO

## Steps to Reproduce:
After https://github.com/microsoft/vscode-pull-request-github/issues/3383 (and https://github.com/microsoft/vscode/issues/144205) has been solved, I can now checkout and pull/push to/from PR branches correctly.

However, I can no longer merge the PR branch with any project branch.

1. Working on the project https://github.com/owid/covid-19-data I checkout to a PR using the UI. E.g. to branch https://github.com/owid/covid-19-data/pull/2565, where conflicts are to be resolved.
2. Then I type `git merge master` in the terminal but I get the following error
    ```
    $ git merge master
    fatal: refusing to merge unrelated histories
    ```

This did not happen a month ago, so I am unsure whether it can be related to the last updates?

**Comment by alexr00** [comment]
Closing due to missing info.
