### ISSUE TITLE
Changes in commit appear without folder info

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-pull-request-github#3424]
I would have expected either to see the folder as description or a tree structure:

![image](https://user-images.githubusercontent.com/900690/159476292-1a4ad6f5-1daa-425b-b961-68fad473a206.png)

**Comment by alexr00** [comment]
I've added a directory tree for commits nodes when `githubPullRequests.fileListLayout` is `tree`. 

For folder info when it's `flat`, here's what we get now:
![image](https://user-images.githubusercontent.com/38270282/165099938-0625d6d3-51c6-49e8-9e8a-56be4cda6047.png)

I think I can add a `resourceLabelFormatters` if you wouldn't expect to see the commit in the path like that.
