### ISSUE TITLE
color contribution issues.newIssueDecoration does not provide color 'defaults.highContrastLight'

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-pull-request-github#3425]
```
abstractExtensionService.ts:1245 [GitHub.vscode-pull-request-github]: color contribution issues.newIssueDecoration does not provide color 'defaults.highContrastLight'. Using color for `light` instead (#00000048).
_logMessageInConsole @ abstractExtensionService.ts:1245
abstractExtensionService.ts:1245 [GitHub.vscode-pull-request-github]: color contribution issues.open does not provide color 'defaults.highContrastLight'. Using color for `light` instead (#22863a).
_logMessageInConsole @ abstractExtensionService.ts:1245
abstractExtensionService.ts:1245 [GitHub.vscode-pull-request-github]: color contribution issues.closed does not provide color 'defaults.highContrastLight'. Using color for `light` instead (#cb2431).
```

**Comment by rchiodo** [comment]
@alexr00 should the latest github pr extension have fixed this? I'm still getting the console output:

![image](https://user-images.githubusercontent.com/19672699/159761195-a7b86552-ee13-49f4-8c51-060fe8ba0eb8.png)

My github pr extension is:

Name: GitHub Pull Requests and Issues
Id: GitHub.vscode-pull-request-github
Description: Pull Request and Issue Provider for GitHub
Version: 0.39.2022032309
Publisher: GitHub
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github

**Comment by rchiodo** [comment]
Sorry my bad, wrong extension output. That's from github remotehub.

**Comment by aeschli** [comment]
I have now removed the warning/info. I now think it's ok to not define a `highContrastLight` value. In that case the `light` value (which is mandatory) will be taken. That's probably what most implementers do anyways.
Same for the already existing `highContrast`. It is no longer required, and will default to `dark`.
