### ISSUE TITLE
Can't see comments on deleted files

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-pull-request-github#343]
- Checkout https://github.com/auchenberg/pullrequest-demo/pull/7
- See app.js
- Comments sort of appear in margin

![image](https://user-images.githubusercontent.com/323878/44885875-3892d500-ac78-11e8-8ed5-ddfb7d09d528.png)

**Comment by rebornix** [comment]
Duplicates of https://github.com/Microsoft/vscode-pull-request-github/issues/170
