### ISSUE TITLE
Active pull request doesn't match active pr panel

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-pull-request-github#3431]
I have this PR open:

And the screen shows this:
![image](https://user-images.githubusercontent.com/19672699/159788383-0c5b99ee-dc06-4d6b-a00f-8d7ad41a6d09.png)

The active pr panel is from another PR.

Attached the log output:
[ghpri.txt](https://github.com/microsoft/vscode-pull-request-github/files/8336318/ghpri.txt)

**Comment by rchiodo** [comment]
GH PR Extension version:
Name: GitHub Pull Requests and Issues
Id: GitHub.vscode-pull-request-github
Description: Pull Request and Issue Provider for GitHub
Version: 0.39.2022032309
Publisher: GitHub
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github

**Comment by alexr00** [comment]
The Comments view will show comments from your currently open PR and from any PRs you've recently browsed but not checked out. Is that what you're seeeing?

**Comment by rchiodo** [comment]
Sorry I named it the wrong thing. The bottom panel on the current PR showed the wrong PR data.

![image](https://user-images.githubusercontent.com/19672699/159967803-0361e2d2-61e9-4906-bcdd-506084bf3977.png)

I thought this (at first) was where comments would show up because you can comment there, but it's not the comments panel (that shows up in the output tab).

It's the 'Active Pull Request' panel. It doesn't match the active pull request.

I just had it repro again:
![image](https://user-images.githubusercontent.com/19672699/159968136-aab902e6-0beb-4a40-8978-eee06595e0a2.png)

You can tell because the PR numbers don't match.

**Comment by alexr00** [comment]
Steps to repro:
1. Have a PR checked out.
2. Reload
3. Use the "Exit Review Mode" button to change branches
4. Checkout a different PR from the PRs view and _do not click on the GitHub Pull Request view, let it open on its own_.
