### ISSUE TITLE
Don't make potentially expensive `getObjectDetails` and `detectObjectType` calls for known file extensions

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#3446]
From @bpasero:

![Recording 2022-03-31 at 07 25 08](https://user-images.githubusercontent.com/900690/160982691-a22b2a16-0b8e-4c14-b0dd-a9a9a0b99b9d.gif)

Notice how often a click on an entry takes seconds to cause any update in the editor, almost as if the open editor call only comes after a delay. I would suggest to turn this around and make the click instant but do the resolving in the editor.

**Comment by bpasero** [comment]
I would turn it around and have a set of well known image file extensions where you do these operations instead of doing it for everything that does not seem to have a text extension.

**Comment by alexr00** [comment]
I think that would guess incorrectly more often and we would show no diff for those files. It seems better to be correct more often with a chance of slowness in the browser.

**Comment by bpasero** [comment]
For reference, we have a list of seemingly media types here in core: https://github.com/microsoft/vscode/blob/a64e8e5673a44e5b9c2d493666bde684bd5a135c/src/vs/base/common/mime.ts#L33-L84

**Comment by alexr00** [comment]
That's perfect, thank you. I will switch over to use that list.

**Comment by connor4312** [comment]
Verified that only two calls are made to `https://api.github.com/repos/microsoft/vscode/git/blobs/...` to open a diff on a .ts file. I still see some loading time that looks like the gif in the original issue, but I think the extra calls are correctly removed
