### ISSUE TITLE
This extension caused an Error : Extension host terminated unexpectedly

### ISSUE THREAD

**Issue by Medeon** [microsoft/vscode-pull-request-github#3449]
ADD ISSUE DESCRIPTION HERE

Version: 1.66.0
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36
Embedder: codespaces

Extension version: 0.40.0

**Comment by alexr00** [comment]
Was there any additional error info in the developer tools?

**Comment by Medeon** [comment]
Thanks for your reply. The error disappeared after closing the terminal and opening a new terminal.
________________________________
Van: Alex Ross ***@***.***>
Verzonden: woensdag 6 april 2022 17:43
Aan: microsoft/vscode-pull-request-github ***@***.***>
CC: Medeon ***@***.***>; Author ***@***.***>
Onderwerp: Re: [microsoft/vscode-pull-request-github] This extension caused an Error : Extension host terminated unexpectedly (Issue #3449)


Was there any additional error info in the developer tools?

**Comment by alexr00** [comment]
Hmm. The only terminal API that this extension uses is the terminal link handler API. 

Without additional error information there's nothing I can do to investigate the issue. If you see the issue again, can you please open the developer tools and see if there's any error information in the console that you can share?

**Comment by Medeon** [comment]
Sure, thanks for the effort.

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________
