### ISSUE TITLE
Use editor font for code blocks in comments in comments panel

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-pull-request-github#345]
From https://github.com/Microsoft/vscode-pull-request-github/issues/168 the editor font is used for code blocks in comments in the inline comments thing, but it should also be used in the comments panel.

![image](https://user-images.githubusercontent.com/323878/44886311-75f86200-ac7a-11e8-8e70-85c2acbcf07a.png)

**Comment by RMacfarlane** [comment]
Was fixed with https://github.com/microsoft/vscode/commit/aa497deb2d47dad97229ff19069a93d97ac7df32
