### ISSUE TITLE
Do not automatically expand comments from me

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-pull-request-github#3452]
Today I was on a branch with associated PR from me:
* not in review mode
* with a single comment from me pinging someone else from the team

Working on this branch:
* the comments panel appeared in my face directly
* my own comment was always expanded in the editor

Neither nor should apply, independent of settings. Esp. when not in review mode and when I am the only commenter.

**Comment by alexr00** [comment]
> my own comment was always expanded in the editor

Agree! We should collapse comments where you are the most recent commenter in a thread.

> the comments panel appeared in my face directly

The Comments view doesn't know that you are the one who left the comment. It will open when a file with a comment is opened depending on the value of `comments.openView`. This could be changed to only open if there are _expanded_ comments in the current file which may improve the behavior for you.

**Comment by saifahn** [comment]
> t will open when a file with a comment is opened depending on the value of comments.openView

Thanks for this information, I missed this in the updates from the March release of VSCode. For anyone else who is having the same issue: [here is the relevant section.](https://code.visualstudio.com/updates/v1_66#_comments-view-discoverability)

I do want to add a +1 to this - it has been jarring over the last couple days and has interrupted my workflow a bit, switching panels every time I switch to a file with comments! Is this repo the best place to share this opinion?

Thanks for the work on the extension, it's been generally really great :)

**Comment by sandy081** [comment]
This auto expanding comments view is annoying. While developing in the PR branch this view keeps coming up when I switch between files even though I hide the view every time.

**Comment by DanRowe** [comment]
Thanks for pointing to that section @saifahn! For anyone doing some quick searching, the below setting will disable the comments panel coming up when you switch files.

```
"comments.openView": "never",
```

I found this comments panel constantly interrupted me when switching between files, especially with a split view and 
 I constantly closed it. However, I usually have the GitHub Pull Request sidebar open if I'm wanting to view comments. I could see the comments move to being a tab in that menu. Great extension either way, thanks for adding the ability to customize this with that setting.

**Comment by alexr00** [comment]
> I could see the comments move to being a tab in that menu

Most of VS Code's views are draggable, so if you like the Comments view in the GitHub Pull Request view container you can drag it there!
