### ISSUE TITLE
Web: Broken state for deleting branch in repo that deletes on merge

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode-pull-request-github#3453]
- VSCode Version: github.dev

Steps to Reproduce:

1. I reviewed a PR https://github.dev/microsoft/vscode/pull/146789
2. Merged the PR and picked to delete the branch.

AR: Delete Branch is still shown, with a note that I can exit without deleting the branch. _Is it deleted or not?_
ER: When the branch is deleted, the UI sets to a welcome state where I can't commit or delete branches that don't exist.

<img width="328" alt="image" src="https://user-images.githubusercontent.com/8599/161798373-5fb2a976-669e-4c2f-a642-8705aceff8ab.png">

A quick pick showed up a minute later  to delete the branch, but clicking it just caused an error in the output:

```
[Info] PullRequestChangesTreeDataProvider> Error: Cannot resolve tree item for element 0/0:treeView.ts
[Info] GithubRepository> Unable to delete branch: HttpError: Reference does not exist
```

But even then the UI didn't change.

<hr>

Refreshing still offers to exit without deleting the branch, but doesn't have a delete branch button anymore:

<img width="939" alt="image" src="https://user-images.githubusercontent.com/8599/161799432-c7785670-9aaa-473b-9113-184d6f665f98.png">

**Comment by alexr00** [comment]
> Delete Branch is still shown, with a note that I can exit without deleting the branch. Is it deleted or not?

I took a closer look at what's the disabled buttons mean: They are disabled while we try to delete the branch. Disabled does not indicate that the branch has been deleted, rather that the operation is still happening and we don't want to you click additional buttons while we work on it.

I see that this is happening with GitHub Repositories. I think the microsoft/vscode repo has a setting on it that causes PR branches to be deleted when the PR is merged. So, what it looks like is happening here is that the branch got deleted out from under you right after merging.

This is a poor experience. I'll see what we can do to improve it.

**Comment by alexr00** [comment]
The new behavior follows the same pattern as in non remote-repository workspaces: after the branch is deleted you will see the default branch for the repo get checked out. In web, this means there will be a realod.
