### ISSUE TITLE
Stop Auto Switching to GitHub Panel View

### ISSUE THREAD

**Issue by noahschumacher** [microsoft/vscode-pull-request-github#3459]
I am not sure what changed but now everytime I open a file that has unresolved comments on it, I get autoswitched from explorer or whatever other sidebar view I was on to the Github review view. Personally I find this incredibly annoying and actually makes the otherwise great extension unusable.

It seems this is by design but I could not find a setting to turn it off. 

Version v0.40.0.

**Comment by alexr00** [comment]
The setting to turn this off is `"comments.openView": "never"`.

**Comment by alexr00** [comment]
In light of all the feedback I've gotten about this setting, I've added a new default value `'firstFile'`: https://github.com/microsoft/vscode/issues/147365

In the mean time, you can set the setting to `'never'` to prevent this behavior.
