### ISSUE TITLE
Exit review mode -> close branch picker -> trapped

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-pull-request-github#346]
- Check out PR
- Check out a second PR
- Click Exit Review Mode
- Get branch quickpick, press esc
- Now "Exit Review Mode" is grayed out and I can't exit review mode

**Comment by rebornix** [comment]
We call git extension command `git.checkout`, which has no return results. This can be easily fixed if we add responses for the git command or we check the local branch to see if the checkout succeeds or not.
