### ISSUE TITLE
Fails to activate with "Timed out waiting for authentication provider to register"

### ISSUE THREAD

**Issue by DavidS-cloud** [microsoft/vscode-pull-request-github#3469]
Issue Type: <b>Bug</b>

Reinstalled the extension, still getting no activation, only these log entries:
```
[2022-04-14 14:54:12.044] [exthost] [error] Activating extension GitHub.vscode-pull-request-github failed due to an error:
[2022-04-14 14:54:12.044] [exthost] [error] Timed out waiting for authentication provider to register
```

Extension version: 0.40.0
VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:41.156Z)
OS version: Linux x64 5.16.0-6-amd64
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2468)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.36GB (1.31GB free)|
|Process Argv|--crash-reporter-id 34a5434f-86d5-49a8-9da7-aae53149b098|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|i3|
|XDG_CURRENT_DESKTOP|i3|
|XDG_SESSION_DESKTOP|i3|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30466690

```

</details>

**Comment by alexr00** [comment]
Do you have the built in GitHub Authentication extension enabled?

**Comment by DavidS-cloud** [comment]
This is all extensions I've installed:
![2022-04-25_08MS+0100_756x1196](https://user-images.githubusercontent.com/88319323/165045806-9787ea95-0cbc-4859-9280-611335267a21.png)

I didn't find a "GitHub Authentication" extension, but I did find these settings:

![2022-04-25_09MS+0100_1190x564](https://user-images.githubusercontent.com/88319323/165045815-6b0853d7-4f3b-460b-b9c6-1ceebe83fcbb.png)

**Comment by alexr00** [comment]
@DavidS-cloud GitHub Authentication is a built-in extension.

**Comment by DavidS-cloud** [comment]
Thanks to the documentation in https://marketplace.visualstudio.com/items?itemName=L13RARY.l13-built-in-extensions I found that `@builtins` in the Extensions search lists built-in extensions and, indeed, GitHub Authentication was disabled. After enabling it and reloading VSCode the pull request extension is loading again.

**Comment by alexr00** [comment]
Let's make this extension directly depend on GitHub Authentication.

**Comment by JacksonKearl** [comment]
When I disable GHPRI, sign out of github, disable the GitHub Authentication extension, then enable GHPR I still end up in this state:

<img width="795" alt="image" src="https://user-images.githubusercontent.com/8586769/166063858-0e34c907-e4d7-48f8-8f4c-fef0360d6cfd.png">

Using latest prerelease og GHPRI

**Comment by JacksonKearl** [comment]
The view is completely empty in this case, upon reenabling GitHub Authentication I get a proper signed out view:
<img width="628" alt="image" src="https://user-images.githubusercontent.com/8586769/166064120-1ee55cc7-eeb8-408b-824b-3e28e723d1bc.png">

**Comment by jmcneil86043** [comment]
Wow!!!!! I've been trying to get Copilot to login for months. My GitHub Authentication was disabled Thanks!!!

**Comment by Ishaan-Shaikh** [comment]
> Do you have the built in GitHub Authentication extension enabled?

Thank you! I had the same problem but now it's solved.

**Comment by Bhartendu-Kumar** [comment]
Same issue, solved by :

[Clean uninstall](https://code.visualstudio.com/docs/setup/uninstall#_clean-uninstall)

If you want to remove all user data after uninstalling VS Code, you can delete the user data folders Code and .vscode. This will return you to the state before you installed VS Code. This can also be used to reset all settings if you don't want to uninstall VS Code.

The folder locations will vary depending on your platform:

Windows - Delete %APPDATA%\Code and %USERPROFILE%\.vscode.
macOS - Delete $HOME/Library/Application Support/Code and ~/.vscode.
Linux - Delete $HOME/.config/Code and ~/.vscode.

This works for insider too. Just replace by vscode-insiders
