### ISSUE TITLE
Add option to disable autofocus of comment view

### ISSUE THREAD

**Issue by lforst** [microsoft/vscode-pull-request-github#3470]
When pressing a file in the 'changes' view, if that file has comments, the comment view will automatically show. Because this view is quite large, I find it a bit annoying when it shows up. I think an option to control this behaviour would be pretty nice.

**Comment by Gilad-Gur-Andelman** [comment]
@lforst 
Try this in your `settings.json`:    
```
{
    "comments.openView": "never",
}
```

**Comment by lforst** [comment]
> @lforst Try this in your `settings.json`:
> 
> ```
> {
>     "comments.openView": "never",
> }
> ```

Awesome, thank you!
