### ISSUE TITLE
Recent update breaks sign in using Github if signed in organization using Microsoft.

### ISSUE THREAD

**Issue by denist-huma** [microsoft/vscode-pull-request-github#3471]
- Extension version: v0.40.0
- VSCode Version: 1.66.2
- OS: Linux x64 5.11.0-37-generic snap
- 
Version: 1.66.2
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:49:24.808Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Linux x64 5.11.0-37-generic snap

Steps to Reproduce:

1. I login to my organization using Microsoft SSO
2. Install extension
3. click under user menu "Sign in using Github to use GitHub Pull Requests and Issues"
4. I see an empty tab in Chromium Version 100.0.4896.127 (Official Build) snap (64-bit) with a link starting from "https://github.com/login/oauth/authorize?client_id="
5. I cannot log in
6. It was working in the previous version I don't pin
7. LiveShare Ext is able to login, so I belive there is no problem on my side

**Comment by alexr00** [comment]
Can you share the output from GitHub Authentication and GitHub Pull Request?

**Comment by alexr00** [comment]
Closing due to missing info.
