### ISSUE TITLE
Option to hide all resolved comments 

### ISSUE THREAD

**Issue by lukepighetti** [microsoft/vscode-pull-request-github#3476]
I would like an extension option to hide all resolved comments from the entire extension experience. That includes inline comments and in the comments pane.

**Comment by pokey** [comment]
I would argue that hiding resolved comments should be the default behaviour, and that the setting would allow users to turn them on if they'd like to see them.  Could also have a command to toggle, rather than just a setting

**Comment by mogelbrod** [comment]
Being able to toggle hiding all resolved comments from the comments panel etc. would be super helpful!

**Comment by alexr00** [comment]
The current behavior is that resolved comments are collapsed by default. 
The Comments view now lets you filter out resolved comments.

Between these two things you should be all set!
