### ISSUE TITLE
Invalid arguments when attempting to view first commit in a PR

### ISSUE THREAD

**Issue by samholmes** [microsoft/vscode-pull-request-github#3478]
- Extension version: v0.40.0
- VSCode Version: 1.66.2
- OS: macOS 12.3 (21E230)

Steps to Reproduce:

1. Checkout PR
2. Go to Github Pull Request extension tab
3. Expand "Commits" accordion
4. Expand first commit

Result: An error message in the bottom right displays "Invalid arguments"

Expected: The commit accordion expands showing all of the file changes for the commit.

**Comment by alexr00** [comment]
@samholmes is there a public PR that you see this with so that I can try it out? I tried with a couple PRs but I haven't been able to reproduce the issue.

If you can't share the PR, can you share the output from "GitHub Pull Request"?

**Comment by samholmes** [comment]
I can't seem to replicate it anymore.

**Comment by javsalgar** [comment]
I was able to reproduce it with this PR https://github.com/bitnami/charts/pull/10652

Output from vscode:

```
[Info] PullRequestTree> Adding PR #10652 to tree
[Info] Review> register comments provider
[Info] Review> display pull request status bar indicator and refresh pull request tree view.
[Info] Review> using focus mode = true.
[Info] Review> state validation silent = true.
[Info] Review> PR show should show = false.
[Info] Error: Invalid arguments

```

**Comment by alexr00** [comment]
@javsalgar thank you for posting this! I've found the bug and have fix.
