### ISSUE TITLE
Prompted about updates to PR after pushing to the PR branch

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-pull-request-github#3479]
- Extension version: v0.41.2022041309
- VSCode Version: 1.67-insider
- OS: Windows 11

Steps to Reproduce:

1. Push updates to a PR branch
2. :bug: get notified about updates to the PR a few seconds later (but these were the updates I just pushed). Pulling is a no-op
![image](https://user-images.githubusercontent.com/30305945/164303865-ad09c058-2c7b-467c-b822-ef6b72ac9171.png)

**Comment by roblourens** [comment]
I got this too. Got the notification twice in a row after pushing

**Comment by alexr00** [comment]
I think this is related to the git extension API not signaling there is a change immediately. Should be fixable by not looking at a cached commit sha and instead only looking at whether the branch is behind.
