### ISSUE TITLE
The close arrow on the inline comment thing should be an X

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-pull-request-github#348]
It's an X for the inline find-all-references widget, and the panel.

**Comment by RMacfarlane** [comment]
Fixed by https://github.com/Microsoft/vscode/commit/70df226af0a243181edc7c7682aa71a548767996

**Comment by ramya-rao-a** [comment]
@roblourens I clicked on the X expecting it to delete the comment

The collapse icon makes more sense here

In case of peek widgets there is nothing to delete, so X would mean close not delete

@misolori

**Comment by roblourens** [comment]
We use x in several places to close things, I don't think we use it to mean 'delete'. Right or wrong, I think the consistency is good.

**Comment by ramya-rao-a** [comment]
We (@RMacfarlane, @misolori and I) just had a discussion about the same.

I had added a comment, wanted to delete it, and even before I formed a coherent thought in my mind, I ended up clicking the X expecting it to delete the comment.

Once we do support the edit and delete features, we can have the trash can icon for delete just like we do for terminals. Then it wouldnt be so confusing.
