### ISSUE TITLE
the Terminal comments window opens automatically in an infinite loop each time I open the file.

### ISSUE THREAD

**Issue by khitermedachraf** [microsoft/vscode-pull-request-github#3483]
- Extension version: the output of the comments (Reviews...) from GitHub in VS Code Terminal.
- VSCode Version: 1.66.2 (user setup).
- OS: Windows_NT x64 10.0.19043.

Steps to Reproduce:

1. the Terminal comments window **opens automatically and in an infinite loop each time I select the file** which contains the Github comments after a PR.
2. And if I delete the comments from VS Code **to prevent the comments window from showing on**, The comments will be deleted from the PR on GitHub which is not good.

<img width="960" alt="2022-04-22_031554" src="https://user-images.githubusercontent.com/38400387/164583871-ebed5a75-b356-4a2b-ab4b-dda53310ab90.png">

**Comment by alexr00** [comment]
This is controlled by the setting `comments.openView`. You can change that setting to prevent the comments view from opening. The default value of that setting has also been changed to `firstFile` in version 1.67 of VS Code, which will only open the comments the first time a file with comments is opened per session.

**Comment by emilygdavis** [comment]
Thank you @alexr00 I was running into this issue too and could not find a fix anywhere!

**Comment by khitermedachraf** [comment]
Thank you @alexr00, I wish I'll work at Microsoft one day 😍🔥.
