### ISSUE TITLE
Text suggestions load forever on first column

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-pull-request-github#3485]
![Recording 2022-04-22 at 06 47 52](https://user-images.githubusercontent.com/22350/164605150-2590b6d5-eaad-41fe-85c0-493373d28fd1.gif)

**Comment by alexr00** [comment]
Required setup to repro:
1. Install GHRPI
2. Sign in with GHPRI
3. Open a folder without a git repo.

**Comment by rchiodo** [comment]
@alexr00 I can't repro the initial problem (using this version of GHPRI and stable VS code):

Name: GitHub Pull Requests and Issues
Id: GitHub.vscode-pull-request-github
Description: Pull Request and Issue Provider for GitHub
Version: 0.40.0
Publisher: GitHub
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github

Do I need a specific version to repro?

**Comment by joaomoreno** [comment]
Fixed it for me!
