### ISSUE TITLE
Comment panel loses comments and throws errors

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-pull-request-github#349]
- Clone https://github.com/roblourens/test-pr-repo
- Checkout https://github.com/roblourens/test-pr-repo/pull/2
- Switch between that PR and other PRs in the repo a bit
- At some point, get an error like `Assertion failed (item already registered: file:///Users/roblou/Documents/test-pr-repo/README.md): Error: Assertion failed (item already registered: file:///Users/roblou/Documents/test-pr-repo/README.md)` and the comments panel is missing comments or showing comments from the wrong PR

Looked at it with @RMacfarlane

**Comment by RMacfarlane** [comment]
Repro steps:

- Checkout a PR that already has some comments on it
- Open a diff view of a file with comments
- Reply to one of these existing comments

:bug: Comments panel isn't updated

The extension sends an update event to the workspace comments provider with the thread from the diff editor. This thread's `resource` is the file it's on - in the case of the diff editor, this is content being served from the extension with a `pr` scheme. The comment's panel is expecting to update a thread on an actual file.

**Comment by RMacfarlane** [comment]
Checked in a quick fix for this but we should still

- check behavior of update events triggered from polling
- make comments panel more resilient to this in core

**Comment by RMacfarlane** [comment]
Closing, as I'm no longer able to repro, and since there have been various refactoring to VSCode core for commenting since this
