### ISSUE TITLE
Changes in commits should support tree structure

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-pull-request-github#3491]
Testing #3488

When I expand a commit I would have expected to see a tree structure, given my setting `githubPullRequests.fileListLayout` is `tree`:

![image](https://user-images.githubusercontent.com/900690/165236890-7e23c2ed-4f4c-4408-8987-8f53e00f5ab7.png)

**Comment by bpasero** [comment]
Alternatively I would have expected to see the path as description segment next to the label, independent of that setting.

**Comment by bpasero** [comment]
Hm, it looks like I was maybe using the non-pre-release version...

**Comment by bpasero** [comment]
No, I see no tree structure using `v0.41.2022042509`

**Comment by alexr00** [comment]
The new build with the change wasn't out yet. After you update to `v0.41.20220426*` do you see the tree structure?
