### ISSUE TITLE
Path description needs a label formatter

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-pull-request-github#3492]
Testing #3488

The path should be presented as it is in the above part of the picture:

![image](https://user-images.githubusercontent.com/900690/165237171-b67495b5-d392-4358-854e-30a9058b2715.png)

**Comment by alexr00** [comment]
Interesting. When I ran it I didn't see the review prefix and I kind of liked having the commit ID in there.

**Comment by bpasero** [comment]
That information is quite redundant though, no? If at all I would show it next to the commit label as description.

Btw I was pushing changes to the label formatter yesterday when there is no formatter registered, so it is possible I caused an issue here, but nevertheless a label formatter makes sense here imho.
