### ISSUE TITLE
Reloading the workbench when a file with comments is open breaks the GHPR tree

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-pull-request-github#3495]
Testing microsoft/vscode#148048

Very strange:

![Recording 2022-04-27 at 16 52 33](https://user-images.githubusercontent.com/22350/165547139-7016ae71-987e-4346-9f9a-00ef43b997d6.gif)

I can't repro if the file which is open has no comments.

**Comment by alexr00** [comment]
Same root cause as https://github.com/microsoft/vscode-pull-request-github/issues/2938, and should not be fixed for April.

**Comment by sandy081** [comment]
I can still repro it

**Comment by alexr00** [comment]
@sandy081 I can't repro it. Can you share the version number of GHPRI?
