### ISSUE TITLE
Comments window displayed and focused even when explicitly disabled

### ISSUE THREAD

**Issue by marvin1up** [microsoft/vscode-pull-request-github#3498]
Issue Type: <b>Bug</b>

<img width="409" alt="image" src="https://user-images.githubusercontent.com/60975671/165799747-d65e9413-cdc9-4061-8fa1-bc13d8bfa4ec.png">

Even when the comments windows has been explicitly disabled, it is still displayed and focused when a file diff, that has comments, is selected in the navigation window.

# Steps to reproduce
* Open a PR
* Select a file with comments
* In the panel, uncheck the `Comments` pane or hide he `Comments` pane
* Select a different file with comments - the comments pane is re-displayed and given focus.

Extension version: 0.40.0
VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:49:20.994Z)
OS version: Darwin x64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|32.00GB (15.59GB free)|
|Process Argv|--crash-reporter-id 8928b6b8-3b05-4f1d-9894-d8f6ca1d282a|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by alexr00** [comment]
There's a setting to control this: https://github.com/microsoft/vscode-docs/blob/main/release-notes/v1_66.md#comments-view-discoverability
In 1.67 of VS Code, the setting value will change too: https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_67.md#commentsopenview-default-value
