### ISSUE TITLE
Enable "delete branch" after close or merge

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-pull-request-github#350]
I like to delete the PR branch after closing a PR, it would be nice if that was possible through the extension

![image](https://user-images.githubusercontent.com/323878/44887231-f7062800-ac7f-11e8-9879-ccd49ba8e452.png)

**Comment by satoyan** [comment]
So do I.

**Comment by rebornix** [comment]
Usually after I merged a PR branch I just switch to master, until one day I realized that I have so many local branches which are bind to some PRs but those PRs are already merged. Cleaning them one by one locally is such a pain.

**Comment by Juberstine** [comment]
I'd love to see this as well, so in for the +1

**Comment by samgabriel** [comment]
+1

**Comment by TheCrimsonSage** [comment]
Please add this, this is basic functionality that most similar systems already have, i.e. VSTS

**Comment by kainbacher** [comment]
+1

**Comment by benc-uk** [comment]
Being able to delete BOTH the local and remote branch would be 👌

**Comment by rebornix** [comment]
It's already shipped in Nightly.

**Comment by cybairfly** [comment]
Is this feature available? Can't find any way to delete remote branch in VSCode
