### ISSUE TITLE
Fallback logic of getSessions calls could be improved

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode-pull-request-github#3500]
See this log:
```
[Info  - 21:39:12.882] Getting sessions for read:user,repo,user:email,workflow...
[Info  - 21:39:12.882] Got 0 sessions for read:user,repo,user:email,workflow...
[Info  - 21:39:12.928] Getting sessions for read:user,repo,user:email...
[Info  - 21:39:12.929] Got 0 sessions for read:user,repo,user:email...
[Info  - 21:39:23.342] Logging in for the following scopes: read:user repo user:email
```

It’s asking for the new scopes, and then the old scopes with `createIfNone:true` when really it should ask for the new ones silently, then the old ones silently and then ask for the new ones with `createIfNone:true`

**Comment by rzhao271** [comment]
What are some verification steps and/or the expected output for this issue?

**Comment by TylerLeonhardt** [comment]
verification steps:

* Log out of GitHub in VS Code
* Install latest prerelease of GitHub Repositories
* Install latest prerelease of GHPRI (don't think the fix has been released yet though... might need to wait for Monday)
* Reload the window to be sure
* Log in to GHPRI
* Log in to GitHub Repositories

You should only see one auth prompt.

Also please be wary of: https://github.com/microsoft/vscode/issues/148310 ... just select "Open a Pull Request" in the remote picker to be sure you're using GitHub Repositories and not the built-in GitHub extension that doesn't use the same scopes.
