### ISSUE TITLE
Wrong PR name displayed in PR panel

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode-pull-request-github#3501]
I have 2 PRs open at the moment
![Screen Shot 2022-04-28 at 11 31 09 AM](https://user-images.githubusercontent.com/29464607/165822356-e6d94048-2e62-46c0-9ae2-31f1fb9df86e.png)

In the GHPR view, I checked out the first 1.

In the GHPR view just above the text box, I see the name of PR 2 with no spaces between parts of the text

![Screen Shot 2022-04-28 at 11 30 18 AM](https://user-images.githubusercontent.com/29464607/165822471-fcb7bc0c-8ce0-493e-86c7-de74c8583b68.png)

**Comment by alexr00** [comment]
Closing as this should have been fixed with https://github.com/microsoft/vscode-pull-request-github/issues/3431#issuecomment-1091421594.
