### ISSUE TITLE
Unable to add comments to existing/new lines

### ISSUE THREAD

**Issue by martijnkriebel** [microsoft/vscode-pull-request-github#3502]
While reviewing a PR I can only add comments to deleted lines of code (left panel in figure, line 1), while I cannot do this for existing/new lines.

- Extension version: 5.814.597
- VSCode Version: 1.66.2
- OS: Windows 10 Enterprise build 19044.1586

![image](https://user-images.githubusercontent.com/62608156/165927245-fe380916-9e4d-4d20-b935-967210f9a860.png)

**Comment by alexr00** [comment]
@martijnkriebel I haven't been able to reproduce this issue. Does this happen every time for you?

**Comment by martijnkriebel** [comment]
@alexr00 I tried it for a new PR, and for some reason the extension does work as expected here!. Unsure why I had troubles with the other PR though, as it worked fine for my colleague (who is using the same version of the extension and VS Code as me).

**Comment by alexr00** [comment]
Hmm. There have been some changes in this area. I'll investigate further.

**Comment by aaronadamsCA** [comment]
I've got the same thing happening right now in Codespaces, VS Code v1.67.0, extension v0.42.0.

I'm in review mode for a pull request, and I can only open comments in the left pane:

![image](https://user-images.githubusercontent.com/1505561/167090716-9e6512c4-ab8e-44fd-9f25-4b1b78d87075.png)

No amount of clicking will let me do the same thing in the right pane.

Let me know if there's anything I can do to help debug this; I checked the extension output and there's nothing noteworthy.

**Comment by alexr00** [comment]
@aaronadamsCA does this happen every time? And, if the PR is in a public repo can you share it?

I haven't been able to reproduce the issue yet.

**Comment by aaronadamsCA** [comment]
I've tried several times today and I can't seem to reproduce the issue again. I don't know what changed!

**Comment by alexr00** [comment]
Thanks for the update! Closing, we can re-open create a new issue if we see it again.

**Comment by alexr00** [comment]
Think I found what was going on: https://github.com/microsoft/vscode-pull-request-github/issues/3556#issuecomment-1126038772
