### ISSUE TITLE
Custom branch naming for "Topic branch"

### ISSUE THREAD

**Issue by florius0** [microsoft/vscode-pull-request-github#3506]
Allow users to set naming strategy for branches when using `Start working on issue and checkout topic branch`.

**Comment by florius0** [comment]
Turns out this is already possible

**Comment by airtonix** [comment]
> Turns out this is already possible

how?

**Comment by florius0** [comment]
In the settings there is an option "Github Issues: Issue branch title"
<img width="2032" alt="image" src="https://user-images.githubusercontent.com/18403735/184512654-a996cbc0-e635-4763-bab5-08f2f1684cb7.png">
