### ISSUE TITLE
In review mode, the "Active Pull Request" panel contains another Pull Request

### ISSUE THREAD

**Issue by faustnord** [microsoft/vscode-pull-request-github#3508]
- Extension version: v0.40.0
- VSCode Version: 1.66.2 (Universal)
- OS: macOS Monterey 12.3.1

Steps to Reproduce:

1. 
<img width="375" alt="Снимок экрана 2022-04-27 в 17 25 25" src="https://user-images.githubusercontent.com/33550676/165548504-537bc355-ebdd-47b6-bd55-192b0972aee5.png">

2. 
<img width="375" alt="Снимок экрана 2022-04-27 в 17 30 19" src="https://user-images.githubusercontent.com/33550676/165548652-8c39d9a3-322f-4f95-8049-f1214b71649b.png">

3. 
<img width="375" alt="Снимок экрана 2022-04-27 в 17 33 47" src="https://user-images.githubusercontent.com/33550676/165548785-24ed159f-70d8-4743-be62-588bc160cb9e.png">

4. 
<img width="375" alt="Снимок экрана 2022-04-27 в 17 35 20" src="https://user-images.githubusercontent.com/33550676/165548842-af4b65db-1822-4e9f-891d-833503e56359.png">

5. 
<img width="375" alt="Снимок экрана 2022-04-27 в 17 39 40" src="https://user-images.githubusercontent.com/33550676/165548905-54dd36a1-ffdf-4fe8-a0ab-d8a2ce810675.png">

6.
<img width="375" alt="Снимок экрана 2022-04-27 в 19 41 23" src="https://user-images.githubusercontent.com/33550676/165579727-ea94f15f-fe0a-4138-a800-021095a543f0.png">

7.
<img width="924" alt="Снимок экрана 2022-04-27 в 19 43 57" src="https://user-images.githubusercontent.com/33550676/165579250-1010cb38-2fe5-45c7-8cfa-593f8d7836d0.png">

Such non-obvious behavior leads to bad consequences. You think you're approving, commenting, or merging one branch (which you switched to), when in fact you're doing these actions on a completely different branch that you were working on before.

We've already gotten into trouble with this bug and accidentally merged a completely different branch that hasn't been finalized yet.

**Comment by dslatkin** [comment]
> Such non-obvious behavior leads to bad consequences. You think you're approving, commenting, or merging one branch (which you switched to), when in fact you're doing these actions on a completely different branch that you were working on before.
>
> We've already gotten into trouble with this bug and accidentally merged a completely different branch that hasn't been finalized yet.

Not sure if it's related, but there's a similar issue we've been bitten by in #3490 where there's a mismatch in the PRs displayed in the "Changes in pull request" and "Active pull request" panels. We've also been bitten with comments and approvals going to the wrong PRs. 🙁

**Comment by alexr00** [comment]
Thank you for the very clear repro steps! This looks like https://github.com/microsoft/vscode-pull-request-github/issues/3431.

I tried the steps with the current pre-release build of the extension (which as the fix for https://github.com/microsoft/vscode-pull-request-github/issues/3431), and wasn't able to reproduce the issue. If you're willing to try it out, instructions for using the pre-release build are very simple and are here: https://github.com/microsoft/vscode-pull-request-github/wiki/Pre-release-Build

**Comment by faustnord** [comment]
I checked it.
This now works correctly in VS Code 1.67.0 and extension version v0.42.0

**Comment by alexr00** [comment]
Thank you for testing this @faustnord!
