### ISSUE TITLE
Pull requests created from a fork on a topic branch aren't discovered.

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#3511]
1. Create a fork of a repo
2. Clone your fork. Configure your remotes so that your fork is `origin` and the upstream repo is `upstream`.
3. Checkout a topic branch in your fork
4. Commit some changes
5. Make a pull request back to the original repo that you forked from. (if the upstream repo doesn't show in the PR view, make sure that you have `githubPullRequest.remotes` configured correctly).
6. Remove GHPRI's knowledge of your PR (can delete the `github-pr-owner-number` from your git config and reload or create a Codespace from the PR). 
7. 🐛 The "Pull Request" view will not show. GHPRI is not able to tell that the current branch is associated with a PR.

**Comment by aeschli** [comment]
Testing with 
github.vscode-pull-request-github@v0.43.2022053009

After I deleted the the key from `git config` I reloaded the Window.

The status bar would only show the branch name, but not the PR number. Is that expected or is that what should have been fixed? @alexr00

**Comment by alexr00** [comment]
That's what should have been fixed. The PR is still open?

**Comment by aeschli** [comment]
I've closed the PR in the meantime as it was in a public repo and I didn't want to confuse.
Let me know if I should set it up again.

**Comment by alexr00** [comment]
I can repro, no need to set it up again yet.
