### ISSUE TITLE
Mark as viewed close file option

### ISSUE THREAD

**Issue by brucejo75** [microsoft/vscode-pull-request-github#3513]
Hi All,  Thanks for this fantastic extension!

I am in the process of reviewing a change to over 200 files. (yes, I know...)

I run VSCode with `"workbench.editor.enablePreview": false` (yes, I know.. I am a tab binger)

While reviewing the code I would like the file to close after each review is complete. Which does not happen if `"workbench.editor.enablePreview": false`.

Pardon me if this feature exists, I could not find it.

What I think would be valid options:
1. Close the window when I select Mark as Viewed &/or close the file under review when I select another file for review.
2. New options setting `githubpullrequest.editor.enablePreview` (Default: `true`)
3. Put the editor into `enablePreview` mode during any github pull request review with no user option to change.

For a user like me #1 seems optimal.  As I may have other windows open other than the review window.

But I think any of the solutions would be a big improvement for my scenario.

### Workaround
Just review a batch of files then close all in the window. (but this gets rid of some other windows I have open, no big deal really)

Thanks!

**Comment by brucejo75** [comment]
Wow, look forward to trying it!

**Comment by alexr00** [comment]
When you mark a file as viewed through the active editor menu bar or through a keybinding, the file will close. When you mark it as viewed through the tree view then it will not close. If a setting is needed I'll add one, but my hope is that this behavior is better for almost everyone.

**Comment by brucejo75** [comment]
Thanks @alexr00!

**Comment by alexr00** [comment]
To verify:

- Open a pull request in VS Code
- Open a file that's included in the pull request
- Mark the file as viewed from the active PR tree view. Verify that the file is not closed.
- Open a file that's included in the pull request.
- Mark the file as viewed using either a keyboard shortcut that you've configured or the editor toolbar action. Verify that the file **is** closed.
