### ISSUE TITLE
Please add a link to a video on how to use this plugin 

### ISSUE THREAD

**Issue by ketkarameya** [microsoft/vscode-pull-request-github#3522]
Thank you for developing this plugin, I have thoroughly enjoyed using it. 
However, it was very difficult to explore the various features in this plugin just by reading the documentation. 
I found this video very useful - [Introducing GitHub pull requests for Visual Studio Code](https://www.youtube.com/watch?v=pa5xHTUXOxQ&t=412s). I would recommend adding a link to this (or any other video) on the homepage and [here](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github). I think it will help users get started with this plugin quickly (without having to read a lot or tinker).

**Comment by alexr00** [comment]
Added with https://github.com/microsoft/vscode-pull-request-github/pull/4337
