### ISSUE TITLE
Cannot exit review mode when default branch has same name as head branch of a PR

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#3525]
For example, the microsoft/vscode repository has a pull request associated with it's main branch:
1. Checkout a PR
2. "Exit review mode"
3. The Changes in PR view never closes.

**Comment by roblourens** [comment]
I created https://github.com/roblourens/testrepo/pull/8 which is a PR from the default branch to some other branch. I check out that PR, then click "Exit review mode", and just get a notification that says "Default branch is already checked out" but I still see the status bar item that says I am in review mode. Am I doing it right?

**Comment by dnut** [comment]
The root cause of this problem is a much more general problem with the way this extension is implemented. #3590

**Comment by alexr00** [comment]
A couple things have changed to (I hope) improve this:
- "Exit Review mode" has been changed to "Checkout 'main'" branch, where 'main' is the name of your default branch.
- If you're on your default branch already, you'll see a notification asking if you want to ignore the PR when we detect a PR associated with the branch.

**Comment by connor4312** [comment]
I verified that the button is changed, but I'm not sure how to exit "review mode". Maybe this should be easier to do?

<img width="1688" alt="image" src="https://user-images.githubusercontent.com/2230985/176933498-5e6c7e08-cc4b-4177-b6f0-6569f1a5a1e6.png">
