### ISSUE TITLE
Unable to create PR in web

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-pull-request-github#3528]
- Extension version: latest prerelease
- VSCode Version: 1.67-insider
- OS: Windows 11

Steps to Reproduce:

1. Create a branch in insiders.vscode.dev/github/microsoft/vscode
2. Create a PR using GHPRI
3. :bug: origin and branch info not populated 
![image](https://user-images.githubusercontent.com/30305945/167182264-9f17e26f-8bae-446b-bd1b-309afa7dfe5e.png)

**Comment by meganrogge** [comment]
This is not working for me 
![Screen Shot 2022-06-02 at 11 51 42 AM](https://user-images.githubusercontent.com/29464607/171706895-72fa91b9-6566-4666-8399-9f64393dd4e6.png)

**Comment by lychichem** [comment]
> This is not working for me ![Screen Shot 2022-06-02 at 11 51 42 AM](https://user-images.githubusercontent.com/29464607/171706895-72fa91b9-6566-4666-8399-9f64393dd4e6.png)

Same for me. Maybe github.dev haven't deploy the latest version yet.

**Comment by alexr00** [comment]
@meganrogge and @lychichem can you share what version of GitHub Pull Requests and Issues you have installed there? I just checked again with `v0.43.2022060209` and I see it working.

**Comment by lychichem** [comment]
> @meganrogge and @lychichem can you share what version of GitHub Pull Requests and Issues you have installed there? I just checked again with `v0.43.2022060209` and I see it working.

![image](https://user-images.githubusercontent.com/9316590/171831796-6d0f0835-93c0-4f18-8fde-1774c0316551.png)
github.dev runs `v0.42.0` web worker
