### ISSUE TITLE
Duplicates of comment decorations after mutiple code changes

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-pull-request-github#353]
<img width="658" alt="image" src="https://user-images.githubusercontent.com/876920/44925812-4a21be80-ad04-11e8-92aa-c752622e9757.png">

There used to be one comment around `const editor = new SourceEditor({`, I did quite a few code additions, cut the whole `SourceEditor` creation and paste to another paste, and finally decided to undo the whole code change by `Cmd + Z`. The final state of the decorations look frightening.

**Comment by RMacfarlane** [comment]
I'm not able to reproduce this, I believe we've already fixed this upstream
