### ISSUE TITLE
shows duplicate review comments that don't actually exist

### ISSUE THREAD

**Issue by diminutivesloop** [microsoft/vscode-pull-request-github#3530]
Issue Type: <b>Bug</b>

After submitting a review with comments both the Comments view and the file changes view shows an extra comment thread with duplicates of each of the other comments in the review. This thread doesn't exist when I load the PR in the web interface but it did cause me to delete a bunch of comments from a PR I submitted because I thought they were actual duplicates. 

<img width="651" alt="Screen Shot 2022-05-06 at 3 44 52 PM" src="https://user-images.githubusercontent.com/667716/167207692-a3a75390-4c07-4214-a2df-88c78294a1aa.png">

Extension version: 0.42.0
VS Code version: Code 1.67.0 (Universal) (57fd6d0195bb9b9d1b49f6da5db789060795de47, 2022-05-04T12:14:47.100Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|32.00GB (0.21GB free)|
|Process Argv|--crash-reporter-id ed50f89e-497f-43cd-86f3-a73119f730ed|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
testflight:30433670
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217
vscaac:30438847

```

</details>

**Comment by alexr00** [comment]
I think this should be fixed now. If you're still seeing it please ping this issue!
