### ISSUE TITLE
Investigate performance of "Create" view

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#3531]
The "Create PR" view is slow to load and slow to create a PR. We should see if there are opportunities to improve the load performance and the create performance.

**Comment by alexr00** [comment]
Improvements have been made in the load performance, but there may still be opportunities to improve the create performance.

**Comment by alexr00** [comment]
Took a look at the performance of the "create" button, there are three chunks where most of the time is spent:

Pushing the branch: ~2.4 seconds 
@lszomoru, it's a long shot, but any chance there's a place for performance improvements in the git extension API `Repository.push`?

Creating the PR using GitHub API: ~1 second
This currently uses the rest API. I'll see if the GraphQL API is any faster.

Writing some metadata to the git config: ~.6 seconds
Not much to be done here.

**Comment by lszomoru** [comment]
@alexr00, took a look and from what I can tell, there is not much code being executed other that invoking `git push`. Do you have an idea of how much time it currently takes for pushing the branch? How does that compare with the duration of the `git push` command logged in the git output window?

**Comment by alexr00** [comment]
I didn't see an end time of `push` in the git extension output, but I tested it from the command line with `git push --set-upstream origin alexr00/createPerf` and it's **~2.3 seconds**:

```
PS D:\repos\alexr00\playground> Measure-Command { git push --set-upstream origin alexr00/createPerf | Out-Default }
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 12 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 1005 bytes | 1005.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
remote:
remote: Create a pull request for 'alexr00/createPerf' on GitHub by visiting:
remote:      https://github.com/alexr00/playground/pull/new/alexr00/createPerf
remote:
To https://github.com/alexr00/playground.git
 * [new branch]      alexr00/createPerf -> alexr00/createPerf
Branch 'alexr00/createPerf' set up to track remote branch 'alexr00/createPerf' from 'origin'.

←[32;1mDays              : ←[0m0
←[32;1mHours             : ←[0m0
←[32;1mMinutes           : ←[0m0
←[32;1mSeconds           : ←[0m2
←[32;1mMilliseconds      : ←[0m320
←[32;1mTicks             : ←[0m23207875
←[32;1mTotalDays         : ←[0m2.68609664351852E-05
←[32;1mTotalHours        : ←[0m0.000644663194444444
←[32;1mTotalMinutes      : ←[0m0.0386797916666667
←[32;1mTotalSeconds      : ←[0m2.3207875
←[32;1mTotalMilliseconds : ←[0m2320.7875
```

I don't think there's any opportunity for speed up there.

**Comment by alexr00** [comment]
The GraphQL API seems to be slight faster than the REST API. I've swapped them out. 

We already show a spinner in the status bar, but maybe we can boost perceived performance by showing a progress notification.
