### ISSUE TITLE
Getting random title in "Create PR" view

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-pull-request-github#3536]
I created a branch manually, made a commit, ran "Create Pull Request", and I get the view with this title

<img width="405" alt="image" src="https://user-images.githubusercontent.com/323878/167473565-7197846b-66bf-48b2-8912-b2425a80e0ec.png">

That's a PR from Tyler, I have never checked it out

**Comment by alexr00** [comment]
Weird. The title should come from the most recent commit on the from branch. Can you turn on debug logging for GHPRI and then share the log next time this happens?

**Comment by roblourens** [comment]
This happens often. I thought that maybe I wasn't waiting until the precommit hook was done before running "Create pull request" so this time I was sure to wait. This part doesn't always happen, but in this case, the wrong branch was selected, and the current branch didn't even show up in the dropdown until I reloaded the window. The branch and title fields were set to the last PR that I sent. I'd reloaded the window since that PR.
[log.txt](https://github.com/microsoft/vscode-pull-request-github/files/8718609/log.txt)

**Comment by roblourens** [comment]
Also, the view is often just really slow to update - it shows some old data for a while, then updates. Sometimes when I think I saw this issue, it's just that I didn't wait long enough. Not the case in the one above though, it was open for a long time and never updated.

**Comment by roblourens** [comment]
I don't think so!
