### ISSUE TITLE
Provide a way to select only code

### ISSUE THREAD

**Issue by NavyAdmiral** [microsoft/vscode-pull-request-github#354]
![image](https://user-images.githubusercontent.com/40662484/44951484-da165400-ae3b-11e8-9fa9-40a8efe20807.png)

Much like how GitHub is already doing it. The `-`, `+` and `line number` views in the `PR Description` page should be isolated from the code selection.

**Comment by NavyAdmiral** [comment]
@rebornix why isn't this view using the same view from the default vscode diff view?

**Comment by rebornix** [comment]
@NavyAdmiral the description page is a pure web app in a webview and it's contributed by the extension, which means it can't use vscode's own diff view.

We can probably use Monaco editor for this case.
