### ISSUE TITLE
Add "Exit Review Mode" command

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode-pull-request-github#3541]
![image](https://user-images.githubusercontent.com/35271042/167765237-56856e65-303a-4a3f-a110-c3e35ced5b7c.png)

I didn't have the PR overview page and wanted to exit the review mode so I could get the list of PRs back and didn't see this there but it does exist in the over page. Maybe we should add the command to the command palette?

**Comment by alexr00** [comment]
The language of "Exit Review Mode" has change to " Checkout <default> Branch", so I've added the command with the new language.
