### ISSUE TITLE
Hover cards for owner/repo#123 don't show if the issue number is large

### ISSUE THREAD

**Issue by michaeloliverx** [microsoft/vscode-pull-request-github#3543]
- Extension version: `v0.42.0`
- VSCode Version: `1.67.1`
- OS: Windows 10

I have noticed hover cards only show for me when the number is below something like 1100ish? 

Steps to Reproduce:

1. Try hover with `python/cpython#1000` and the card displays: 
![image](https://user-images.githubusercontent.com/55017335/167813942-b69d43b5-1bb1-47c7-9c52-1d37adb8bfb0.png)

2. Try hover with `python/cpython#83413` and the card **doesn't** display: 
![image](https://user-images.githubusercontent.com/55017335/167814905-86e3b48b-26a7-447e-a988-d25df541ce8f.png)

**Comment by alexr00** [comment]
@michaeloliverx do you have the python/cpython repo open in the VS Code window that you're doing the hovering in? My guess is that the answer is no, and that you have a different repo open where the largest issue number is <1100ish. 

We use the max issue number of the repo you have open to avoid incorrect hovers, but we shouldn't do that when the format of the hover is `<owner>/<rep>#<number>`, and only when the format is just `#<number>`

**Comment by michaeloliverx** [comment]
@
