### ISSUE TITLE
Close Pull Request should not be in the context menu of a PR

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode-pull-request-github#355]
I very often confuse "Close Pull Request" with a way to get back to my previous branch (master) when I checked out a PR. I suggest to move the action especially since it triggers a confirmation as notification in the lower right corner which is bad too. If any, the confirmation should be modal.

![image](https://user-images.githubusercontent.com/900690/44990491-7605a400-af91-11e8-9a58-4511f24153cd.png)

![image](https://user-images.githubusercontent.com/900690/44990502-7aca5800-af91-11e8-9ff1-281fdd6eefe3.png)

Anyhow, lets remove it and let people do this through the full UI where they can also comment.

**Comment by rebornix** [comment]
I ran into this issue once before and I somehow thought "Close Pull Request" is exiting the review mode. Now seems I'm not the only one who has this confusion ;)
