### ISSUE TITLE
Failed to execute git

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-pull-request-github#3550]
- "Start Working on Issue"
- Make a commit
- "Create Pull Request"
- I click the "Create" button, get prompted to publish the branch, confirm that, and get an error popup, "Failed to execute git"

When I click Create, this is printed in the Git output channel

```
[2022-05-12T00:43:14.225Z] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/roblourens/issue149242 refs/remotes/roblourens/issue149242 [39ms]
[2022-05-12T00:43:19.525Z] > git push -u origin main [3150ms]
[2022-05-12T00:43:19.525Z] To github.com:microsoft/vscode.git
 ! [rejected]                main -> main (non-fast-forward)
error: failed to push some refs to 'github.com:microsoft/vscode.git'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. Check out this branch and integrate the remote changes
hint: (e.g. 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

That looks like it's trying to push to `main`? That's not the branch I have checked out. I ran "Publish Branch" manually and it printed `[2022-05-12T00:45:02.546Z] > git push -u origin roblourens/issue149283 [4023ms]` and that worked

**Comment by alexr00** [comment]
@roblourens have you seen this again? I haven't been able to reproduce it, so I'm adding some more logging.
