### ISSUE TITLE
Switching to a diff of a file with comments always open comments pane.

### ISSUE THREAD

**Issue by luqmana** [microsoft/vscode-pull-request-github#3551]
- Extension version: 0.40.0
- VSCode Version: 1.66.1 (8dfae7a5cd50421d10cd99cb873990460525a898)
- OS: Darwin arm64 20.6.0

Steps to Reproduce:

1. Navigate to PR w/ file-comments.
2. Open one such file. 'Comments' tab opens up in the bottom pane.
3. Close 'Comments' pane and navigate to different tab.
4. Go back to file-with-comments. 'Comments' tab opens up again.

It'd be nice if the Comments pane wouldn't pop up everytime I go back to the diff view or at least have an option to disable that behaviour.

**Comment by alexr00** [comment]
You can disable this with the setting `comments.openView`. With VS Code 1.67 this has already been changed to be less aggressive and only open on the first file with comments.
