### ISSUE TITLE
Can't add comments on added lines

### ISSUE THREAD

**Issue by fepegar** [microsoft/vscode-pull-request-github#3556]
Hello. I am trying to add comments on added lines in a PR using the extension. I expect the white widget to show up in both sides, like this:

![MicrosoftTeams-image](https://user-images.githubusercontent.com/12688084/168261647-04aa4f1f-2248-48b0-ac5a-efe5c3872a1f.png)

But it does not:

<img width="900" alt="Capture2" src="https://user-images.githubusercontent.com/12688084/168262336-5cdc3de8-5c6e-498a-962e-cb5c0a7e3b74.PNG">

The blue circle shows the position of my cursor, which is not captured by my screenshots software.

It does work for the removed lines:

<img width="900" alt="Capture1" src="https://user-images.githubusercontent.com/12688084/168262440-f4c62a4b-4ef7-426e-a62d-9a0989c24b29.PNG">

Possibly related to:

- #1339
- #1374

System info:

- Extension version: `v0.42.0`
- VSCode Version: `1.67.1`
- OS: Windows 10 (WSL 2)

Steps to Reproduce:

1. Show a PR in the extension
2. Hover over added (green lines)

The white widget doesn't show up.

**Comment by alexr00** [comment]
@fepegar is your repository public and if so can you share a link to the pull request that you see this with?

**Comment by alexr00** [comment]
I can repro when I use WSL.

**Comment by fepegar** [comment]
Sure, here it is: https://github.com/microsoft/hi-ml/pull/337

**Comment by alexr00** [comment]
Correction: It's not that I can repro with WSL, it's that I can repro when the file from the PR is not contained in folder I currently have open.

**Comment by fepegar** [comment]
That reminds me of https://github.com/microsoft/vscode-pull-request-github/issues/1374#issuecomment-541179078

**Comment by fepegar** [comment]
Thanks, @alexr00!
