### ISSUE TITLE
Support Gitlab

### ISSUE THREAD

**Issue by delold** [Microsoft/vscode-pull-request-github#356]
It would be amazing if this extension would support Gitlab too.

**Comment by svipben** [comment]
I totally agree with this! It's so powerful extension we definitely need support for GitLab!

**Comment by RMacfarlane** [comment]
@delold @svipben I'm happy you're excited about this!

To build this extension, we introduced a new proposed api for adding comments that is meant to be generic (in the release notes here: https://code.visualstudio.com/updates/v1_27#_comment-providers). This extension is meant only to add support for GitHub pull requests - trying to make it integrate with other git providers would make it bloated. Instead, we plan to create a separate extension for each git provider.

**Comment by svipben** [comment]
Omg, thank you very much!🔥

**Comment by swiffer** [comment]
@RMacfarlane don't know about your planning Progress - Just wanted to point to GitLab Workflow, created by Fatih Acet over at GitLab. Perhaps its worth talking with him.

**Comment by fatihacet** [comment]
I have created a VSCode extension for GitLab called GitLab Workflow. It supports creating MRs, issues and pipelines directly from VSCode. You can also see pipeline status, MR link and closing issue link on the VSCode status bar. Feel free to take a look at it https://marketplace.visualstudio.com/items?itemName=fatihacet.gitlab-workflow

**Comment by sandeepp-cuelogic** [comment]
@fatihacet GitLab Workflow is truly awesome for gitlab users! It would be great if we can add review comments within VSCode `GitLab Workflow` as well, it should definitely help large developer base. Kudos `Github Pull Request` provider team!!!

**Comment by RMacfarlane** [comment]
Hi @fatihacet 👋 Awesome extension! The comment provider API is still being stabilized and there are a lot of things I would like to add to it. Would welcome your feedback here: https://github.com/Microsoft/vscode/issues/53598

**Comment by goloveychuk** [comment]
Can't we have a `Provider` interface layer, with functions like `getAllPrs`, `getCommentsForPr` and have support for all git providers?

**Comment by le91688** [comment]
Have any other git providers implemented anything using comments yet? Anything in the works?

**Comment by smmofidulislam06-spec** [comment]
## Men’s Charcoal Black Denim Jeans – Stylish Stone Washed Streetwear Jeans | Product Highlights

Upgrade your everyday style with these **Men’s Charcoal Black Denim Jeans**, designed for modern fashion lovers who prefer comfort, durability, and a trendy streetwear look. Featuring a stylish stone-washed charcoal black finish, these jeans offer a perfect blend of casual style and everyday practicality.

### 🔥 Premium Denim Fabric

* Made from a **high-quality cotton blend denim fabric** for comfort and long-lasting use.
* Soft, breathable, and skin-friendly material suitable for daily wear.
* Strong denim construction provides durability while maintaining flexibility.
* Fabric quality designed to handle regular use and repeated washes.

### 👖 Modern Slim Straight Fit Design

* Trendy **slim straight fit** gives a stylish and confident appearance.
* Designed to provide a comfortable body-fit look without restricting movement.
* Straight leg style makes it easy to pair with sneakers, boots, shirts, hoodies, and T-shirts.
* Perfect choice for men who prefer a modern streetwear-inspired outfit.

### 🖤 Trendy Charcoal Black Stone Wash Look

* Attractive charcoal black colour adds a premium and fashionable touch.
* Stone washed finish creates a stylish rugged denim appearance.
* Ideal for casual outings, travel, parties, college, and daily activities.
* A versatile colour that matches easily with different outfits.

### ⚙️ Durable Stitching & Strong Details

* Features strong reinforced stitching for improved durability.
* Heavy-duty zipper and button closure ensure reliable everyday performance.
* Quality hardware adds strength and a premium denim feel.
* Built for comfort and long-term wear.

### 👜 Functional Multi-Pocket Design

* Designed with practical pockets for everyday convenience.
* Deep pockets provide space for carrying essentials like phone, wallet, and keys.
* Combines fashion with functionality.
* Suitable for travel, casual wear, and outdoor activities.

### ✨ Perfect Casual Wear Jeans

* Great for:

  * Daily wear
  * Streetwear fashion
  * Travel outfits
  * Casual meetings
  * Parties
  * Weekend looks
* Easily styles with:

  * T-shirts
  * Shirts
  * Hoodies
  * Jackets
  * Sneakers

### 👔 Comfortable Everyday Fit

* Comfortable straight fit allows easy movement throughout the day.
* Designed for all-day wear with a balance of style and comfort.
* Suitable for adult men looking for fashionable and practical denim.

### Product Specifications:

* **Product Type:** Men’s Jeans
* **Colour:** Charcoal Black
* **Pattern:** Solid
* **Style:** Modern
* **Fit Type:** Straight Fit
* **Leg Style:** Straight
* **Rise Style:** Low Rise
* **Closure:** Button Closure
* **Fabric:** Cotton Blend Denim
* **Occasion:** Casual Wear
* **Season:** All Season
* **Country of Origin:** India
* **Net Quantity:** 1 Jeans

### Why Choose These Jeans?

✔ Stylish stone washed streetwear design
✔ Comfortable cotton blend fabric
✔ Durable stitching and strong construction
✔ Modern slim straight fit
✔ Easy matching with casual outfits
✔ Perfect for everyday fashion

**A must-have pair of charcoal black jeans for men who want a combination of style, comfort, and durability in their wardrobe.**
