### ISSUE TITLE
bug: the `Copy GitHub Permalink` command copies wrong commit hash

### ISSUE THREAD

**Issue by nikitastupin** [microsoft/vscode-pull-request-github#3566]
Hey 👋

- Extension version: Name: 0.42.0
- VSCode Version: 1.67.2
- OS: macOS Monterey 12.4

Steps to Reproduce:

1. `git clone https://github.com/microsoft/vscode-pull-request-github`
1. `git checkout f80b0868f527836658735b610defde4720066bcd`
1. Run the he `Copy GitHub Permalink` command on 5th line of the `README.md`.
1. The `https://github.com/microsoft/vscode-pull-request-github/blob/6b9d9c0d28c62329753a4769a03b48278b6ef51a/README.md#L5` permalink is copied.

Expected:

The `https://github.com/microsoft/vscode-pull-request-github/blob/f80b0868f527836658735b610defde4720066bcd/README.md#L5` permalink is copied.

**Comment by nikitastupin** [comment]
Hey @alexr00,

Here is the example of an issue: I conduct security audit of a GitHub repo at a particular commit. When I write a report I put references as GitHub permalinks for client's convenience. If a permalink points to a different commit it might be hard to tell wether I audited the right thing.

Furthermore, current behavior differs from how GitHub's copy permalink feature works. In GitHub it copies permalink of the commit you're currently at.

Also, the extension's copy permalink feature worked the same as GitHub's one but at some of the latest updates it changed for unknown reason 🤷

**Comment by alexr00** [comment]
Thanks for the explanation! I agree that we should instead use the head commit and will make that change.

**Comment by nikitastupin** [comment]
I've checked in 0.46.0 and it works! Thanks!
