### ISSUE TITLE
Extension making Vscode hang

### ISSUE THREAD

**Issue by rahmathu** [microsoft/vscode-pull-request-github#3570]
Summary: 
I often notice that Vscode hangs for couple of seconds while typing or switching windows. Here is the debug data below. In case more info is needed please let me know 

- Issue Type: `Bug`
- Extension Name: `vscode-pull-request-github`
- Extension Version: `0.40.0`
- OS Version: `Darwin x64 20.6.0`
- VS Code version: `1.67.0`

```json 
{
	"messages": [
		{
			"type": 1,
			"message": "`remoteHub/pullRequest` is not a valid menu identifier",
			"extensionId": {
				"value": "GitHub.vscode-pull-request-github",
				"_lower": "github.vscode-pull-request-github"
			},
			"extensionPointId": "menus"
		}
	],
	"activationTimes": {
		"codeLoadingTime": 73,
		"activateCallTime": 0,
		"activateResolvedTime": 2321,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "GitHub.vscode-pull-request-github",
				"_lower": "github.vscode-pull-request-github"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": [
		{
			"name": "TypeError",
			"message": "Cannot read properties of undefined (reading 'findIndex')"
		},
		{
			"name": "TypeError",
			"message": "Cannot read properties of undefined (reading 'findIndex')"
		},
		{
			"name": "TypeError",
			"message": "Cannot read properties of undefined (reading 'findIndex')"
		}
	],
	"runningLocation": {
		"affinity": 0,
		"kind": 1
	}
}
```

**Comment by alexr00** [comment]
@rahmathu next time you see this would you be able to take a CPU profile? https://github.com/microsoft/vscode/wiki/Performance-Issues#profile-the-running-extensions

**Comment by rahmathu** [comment]
@alexr00 : Thanks, let me do this and get back with the requested information

**Comment by alexr00** [comment]
Also, do you by chance have the vim extension installed? Maybe related: https://github.com/microsoft/vscode-pull-request-github/issues/3562

**Comment by rahmathu** [comment]
@alexr00 : I will share the info you have requested. I dont have the vim extension installed as i don't use vim at all.

**Comment by rahmathu** [comment]
@alexr00 : I think this Pull requests extension is not working good for me. All my queries are failing and i see this error below "`remoteHub/pullRequest` is not a valid menu identifier". I am not sure if it's related to this one or different. Can you please let me know what this error means and why my queries wont work ?

Here are the Non working queries from the extension but work on the github UI 

```json 
    "githubIssues.queries": [
        {
            "label": "My Issues",
            "query": "default"
        },
        {
            "label": "Created Issues",
            "query": "author:rahmathu state:open repo:${owner}/${repository} sort:created-desc"
        },
        {
            "label": "Recent Issues",
            "query": "state:open repo:${owner}/${repository} sort:updated-desc"
        }
    ],
    "githubPullRequests.queries": [
        {
            "label": "Waiting For My Review",
            "query": "is:open review-requested:rahmathu"
        },
        {
            "label": "Assigned To Me",
            "query": "is:open assignee:rahmathu"
        },
        {
            "label": "Created By Me",
            "query": "is:open author:rahmathu"
        },
        {
            "label": "Mentions Me",
            "query": "is:open mentions:rahmathu archived:false "
        }
    ],
```

Error dump from the extension 

```json 
{
	"messages": [
		{
			"type": 1,
			"message": "`remoteHub/pullRequest` is not a valid menu identifier",
			"extensionId": {
				"value": "GitHub.vscode-pull-request-github",
				"_lower": "github.vscode-pull-request-github"
			},
			"extensionPointId": "menus"
		}
	],
	"activationTimes": {
		"codeLoadingTime": 25,
		"activateCallTime": 0,
		"activateResolvedTime": 1851,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "GitHub.vscode-pull-request-github",
				"_lower": "github.vscode-pull-request-github"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": [],
	"runningLocation": {
		"affinity": 0,
		"kind": 1
	}
}
```
Screenshot of the extension error 
![image](https://user-images.githubusercontent.com/95310567/171917474-7edddcea-ce6e-4144-8409-36e9281d7b91.png)

**Comment by alexr00** [comment]
When you see it again, can you also share the output from the developer console (command: Developer: Toggle Developer Tools) and from GitHub Pull Request in the Output panel?

**Comment by rahmathu** [comment]
@alexr00 : Here you go after a reload of the developer window 
![image](https://user-images.githubusercontent.com/95310567/173114070-b0d9406e-c133-457e-b137-5bee6dbab600.png)

Here is the developer console view in detail 

![image](https://user-images.githubusercontent.com/95310567/173114129-69a9cecc-0d93-477f-bebe-33bdde0ca78b.png)

In case this is not helpful and font is too small please let me know step by step on how to take logs for each window

**Comment by alexr00** [comment]
Thanks! There's nothing very suspicious there either. What is leading you to think that this extension is causing VS Code to hang?

Can you set the setting `"githubPullRequests.logLevel": "debug"`, then when you next see the hang can you share the "GitHub Pull Request" output again?

**Comment by rahmathu** [comment]
@alexr00 : I turned all extensions off and started turning on one by one, then what i noticed that this github pull loads the slowest and also during vscode hangs the extension is pulling updates . That made my suspicious about this. Let me make the log level debug and get back to you

**Comment by rahmathu** [comment]
@alexr00 : I am not able to see the problem any more, not sure what helped. After an update things are working good. Closing this issue. Thanks a lot for your help

**Comment by alexr00** [comment]
@rahmathu thanks for the update! If you see it again we can always take another look.
