### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by JoshuaPeddle** [microsoft/vscode-pull-request-github#3574]
- Issue Type: `Bug`
- Extension Name: `vscode-pull-request-github`
- Extension Version: `0.42.0`
- OS Version: `Windows_NT x64 10.0.22616`
- VS Code version: `1.67.2`

```json 
{
	"messages": [
		{
			"type": 1,
			"message": "`remoteHub/pullRequest` is not a valid menu identifier",
			"extensionId": {
				"value": "GitHub.vscode-pull-request-github",
				"_lower": "github.vscode-pull-request-github"
			},
			"extensionPointId": "menus"
		}
	],
	"activationTimes": {
		"codeLoadingTime": 59,
		"activateCallTime": 0,
		"activateResolvedTime": 2040,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "GitHub.vscode-pull-request-github",
				"_lower": "github.vscode-pull-request-github"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": [],
	"runningLocation": {
		"affinity": 0,
		"kind": 1
	}
}
```

**Comment by alexr00** [comment]
I assume its the "`remoteHub/pullRequest` is not a valid menu identifier" message that's the issue?

Unfortunately there's no way to suppress that message. Is the message popping up in a notification anywhere, or is this just in the Show Running Extensions view?

**Comment by rahmathu** [comment]
@alexr00 : I am also seeing this problem in #3570 . This is causing the problem where the queries are not working and they never update new values. Can you please let me know how to proceed ?

**Comment by alexr00** [comment]
`"remoteHub/pullRequest is not a valid menu identifier"` is a harmless warning message and is not the cause of any issue (other than the annoying message that shows in the Running Extensions view.
