### ISSUE TITLE
Linkify GitHub handles in comments 

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-pull-request-github#3586]
![image](https://user-images.githubusercontent.com/30305945/171506495-2d972dae-d94a-4774-bf57-dfbb3ebc544f.png)

Would love to be able to 1. visually distinguish handles in comment text, and 2. click on the handle, just like on GitHub.com.

**Comment by alexr00** [comment]
Found a bug that prevents this: https://github.com/microsoft/vscode/pull/168605

Once that's in I can add the links.
