### ISSUE TITLE
Cannot exit review mode - only switches branches

### ISSUE THREAD

**Issue by dnut** [microsoft/vscode-pull-request-github#3590]
The "Exit Review Mode" button is broken. It doesn't actually toggle a review mode. It only switches branches.

Here's how this extension works:
- If there are any PRs from the current branch, you see all the data from that PR mixed in with your code.
- clicking "exit review mode" doesn't do anything except `git checkout master`, with the assumption there are no PRs from master.

The only way to exit review mode is by disabling the extension, which is usually what I do. This is annoying.

Personally I never want to be in review mode for my own PRs, only for other people's PRs. I prefer to respond to comments where they are all in one place in the PR Conversation web page. I don't need to see the code context because I know the code - I wrote it... Also, I need to edit the code without clutter everywhere.

Fixing this would also solve #3525.

**Comment by alexr00** [comment]
@dnut the purpose of the "Exit Review Mode" button is to checkout the default branch for the repo, but I can see why you would want to disable commenting when you're on the default branch. 

For most users, checking out the default branch as a way to exit a pull request is good workflow. I think what's needed here is a notification that shows when we notice that you've checked out the default branch and there's a PR associated with it. From that notification, we can set a setting that excludes your default branch from ever entering review mode.

I also plan on adding a way to just toggle whether commenting more generally.

**Comment by jmg-duarte** [comment]
> I also plan on adding a way to just toggle whether commenting more generally.

Hey @alexr00! Was this ever added? What happens to me is: I'm done with answering comments on my PR and want to keep working without them showing up unannounced and the `+` on the left side

**Comment by alexr00** [comment]
Yep, the command is Toggle Editor Commenting.
