### ISSUE TITLE
Add a setting to not open PR after creation

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-pull-request-github#3593]
I do not need to see the GH PR open automatically after having it created, in fact I was already putting all the relevant information in from the view, so I wonder why we even open it by default?

**Comment by alexr00** [comment]
I sometimes add a milestone after opening, so I find it useful for that since. 

A setting makes sense.

**Comment by bpasero** [comment]
Maybe the milestone should be something I can set from the view when creating the PR then?

**Comment by alexr00** [comment]
Maybe, but we have very limited space in the "Create" webview, so I would want to make sure that anything we add there is very valuable. We have a bot to add milestone in microsoft/vscode now, so I don't really need it anymore. 

I am sure I will get many issues asking where the overview page has gone if I just stop opening it. A setting makes the most sense to me.

**Comment by alexr00** [comment]
New setting: `githubPullRequests.postCreate`.
