### ISSUE TITLE
Support multiple GitHub accounts

### ISSUE THREAD

**Issue by skorpions2000** [microsoft/vscode-pull-request-github#3595]
Possibly related to closed issue https://github.com/microsoft/vscode-pull-request-github/issues/1941 but am reporting again as instructed at the bottom of the thread on that issue.

    Extension version: v0.42.0
    VSCode Version: 1.67.2
    OS: Windows 10

![изображение](https://user-images.githubusercontent.com/11683786/172327422-b39c3dc7-243c-4cf4-a553-136eb062d393.png)

**Comment by alexr00** [comment]
@skorpions2000 thanks for making a new bug! Are you using GitHub enterprise?

Can you also please share the output from "GitHub Pull Requests"?

**Comment by jasonmacallister** [comment]
Also using GitHub Enterprise Server.  From Output: 

[Info] GitHubRepository> Fetching pull requests for branch failed: HttpError: Not Found
[Info] GithubRepository> Unable to fetch issues without milestone: Error: GraphQL error: Could not resolve to a Repository with the name '_org/repo_'
[Info] GithubRepository> Unable to fetch issues with query: Error: GraphQL error: Could not resolve to a Repository with the name '_org/repo_'

**Comment by alexr00** [comment]
There has been _a lot_ of work done in August and September to support GitHub Enterprise better. Could you try again with the latest version of the extension?

**Comment by CombeeMike** [comment]
I'm seeing this same issue with the same log output as shown by @jasonmacallister [above](https://github.com/microsoft/vscode-pull-request-github/issues/3595#issuecomment-1150071248) with the latest `v0.56.0`.

I'm not using GitHub enterprise. At least I don't think so. Is there a place where I can verify this?

ATM I'm not able to use the extension at all due to this error...

**Comment by alexr00** [comment]
> I'm not using GitHub enterprise. At least I don't think so. Is there a place where I can verify this?

If your clone url is github.com then you are not using GitHub Enterprise. Is it a github.com url?

**Comment by CombeeMike** [comment]
> > I'm not using GitHub enterprise. At least I don't think so. Is there a place where I can verify this?
> 
> If your clone url is github.com then you are not using GitHub Enterprise. Is it a github.com url?

Ok, then I'm not using enterprise. The url is `git@github.com:abc/xyz.git`.

**Comment by alexr00** [comment]
@CombeeMike in that case can you please do the following:
- Set `"githubPullRequests.logLevel": "debug"`
- Reload the window
- Share the output from GitHub Pull Request. If you don't want to share it here (as it may contain data about your repository), you can send it to the email in my profile.

**Comment by CombeeMike** [comment]
@alexr00 I just realized that this was my own fault. I had 2 GitHub accounts connected to VSCode where 1 is a private and the other a work account. I'm using the PR extension exclusively with my work account and the repo I'm using it with is a private one. After completely removing the private account from VSCode, the PR extensions asked me to sign in, which I then did with the work account.

This solved the issue for me, so it seems like the PR extension was somehow erroneously connected/signed in with my private account which does not have access to the repo I was having troubles with.

Sorry for wasting your time with this, I could have also figured this out before asking for help here 🙈

**Comment by matt-unosquare** [comment]
I im in a similiar situation, where i have 2 githubs, 1 work, 1 personal, and the extension appears to be setup with the personal, but i see no way to telling it to use the work one instead

**Comment by alexr00** [comment]
The only option until we have https://github.com/microsoft/vscode/issues/127967 is to sign out of the account you don't want to use. 

As suggested [here](https://github.com/microsoft/vscode/issues/127967#issuecomment-2065442516) you could use VS Code Insiders for one account and VS Code stable for another.

**Comment by vvoldi** [comment]
fixed in the latest versions of VS code, they added multiple account support

**Solution:** 

1. right-click on the extension 
2. click Account Preferences
3. select the necessary account (or add a new one here)
4. restart vs code

![Image](https://github.com/user-attachments/assets/0dc7d9ef-0b1a-403a-b1e6-6309bd137e5c)

**Comment by alexr00** [comment]
Thanks for commenting here @vvoldi!
