### ISSUE TITLE
Duplicate entries in PR tree

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode-pull-request-github#36]
Not sure how I got into this state...

![image](https://user-images.githubusercontent.com/22350/41918504-c4e99d30-795c-11e8-990c-5345c6f2097d.png)

**Comment by rebornix** [comment]
Not sure how this happened, we are returning an array for `getChildren()`

```
[
  new DescriptionNode(),
  ...fileChanges
]
```

I'll see if there is any retry logic in tree view caller.

**Comment by rebornix** [comment]
@sandy081 may I have your expertise on this? I ran into this issue once as well with bad network connection. The behavior makes me think if it has something with tree view API implementation.

Firstly, when I ran into the issue and see duplicates, the UI was like

```
- Update gulpfile balablaba  
  - Description
  - Description
  - gulpfile.js
  - gulpfile.js
```

`Update gulfile balabal` was the PR node which contains a list of tree items representing file changes. Then I click it to collapse the tree, what I got finally was

```
- Update gulpfile balablaba  
  - Description
  - gulpfile.js
```

The tree was already collapsed and I still saw two file change nodes. These two tree nodes are zombie nodes now. @sandy081  Do you have any idea of which part goes wrong in this case?

**Comment by sandy081** [comment]
@rebornix Are you aware of the operations you were performing on the tree view api before coming into this state?

**Comment by rebornix** [comment]
@sandy081 my suspicion is two long running `refresh` actions lead to this bug. In my case above

1. Expand PR node, which attempts to fetch all changed files information from GitHub
2. Step 1 takes tens of seconds (sometimes even timeout)
3. Some internal code triggers tree refresh

Step 3 probably triggers another `treeItem.getChildren()`, which is a long running task as well. Is it possible that we don't cancel the first one and both tasks return results at almost the same time and all results get injected into the tree?

**Comment by joaomoreno** [comment]
Definitely a tree issue.

**Comment by joaomoreno** [comment]
Fixed by https://github.com/Microsoft/vscode/issues/56665
