### ISSUE TITLE
Lines falsely shown as removed in diff editor

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-pull-request-github#361]
Issue Type: <b>Bug</b>

![image](https://user-images.githubusercontent.com/9205389/45032394-fd1a5100-b051-11e8-909a-ad20052f8412.png)

The `const options` and `onDidChangeSelection` lines are not actually removed:

![image](https://user-images.githubusercontent.com/9205389/45032441-1cb17980-b052-11e8-8271-55b96a7c98ec.png)

The PR: https://github.com/Microsoft/vscode-extension-samples/pull/89

Extension version: 0.0.22
VS Code version: Code - Insiders 1.27.0-insider (7b9afc4196bda60b0facdf62cfc02815509b23d6, 2018-09-03T09:07:33.052Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.53GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by roblourens** [comment]
Seeing a similar issue here, maybe the same thing: https://github.com/Microsoft/vscode/pull/57957/files

![image](https://user-images.githubusercontent.com/323878/45124254-71222b00-b11e-11e8-87fe-4b704913c04a.png)

In extHostSearch.test.ts, the `catch` line is not actually removed.
