### ISSUE TITLE
Checking out a pr provides inaccurate blame info

### ISSUE THREAD

**Issue by lukeingalls** [microsoft/vscode-pull-request-github#3612]
Issue Type: <b>Bug</b>

I'm not sure which extension this should be filed under so I'm starting here.

The steps I'm taking are 
1. Select a pr from 'waiting for my review'
1. Next to description click the checkout button
1. Select any file
1. Select any line on that file and the blame info shown by gitlens will all be attributed to that pr regardless on if it was touched. If I try to go back versions of the file it indicates it was just created even though the diff is correct.

I'm also unable to start a review or leave comments at the moment which I was definitely able to do previously.

edit: issue persists after restarting vscode

Extension version: 0.44.0
VS Code version: Code 1.68.0 (Universal) (4af164ea3a06f701fe3e89a2bcbb421d2026b68f, 2022-06-08T11:44:00.250Z)
OS version: Darwin x64 21.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv|--crash-reporter-id 6c90f615-19ef-40da-81b1-688a0f70a370|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vscaat:30438848
vsclangdc:30486549

```

</details>

**Comment by lukeingalls** [comment]
got this error trying to checkout a pr 
`Error running command pr.pick: Cannot read properties of undefined (reading 'number'). This is likely caused by the extension that contributes pr.pick.`

**Comment by alexr00** [comment]
> I'm also unable to start a review or leave comments at the moment which I was definitely able to do previously.

> got this error trying to checkout a pr
Error running command pr.pick: Cannot read properties of undefined (reading 'number'). This is likely caused by the extension that contributes pr.pick.

Both of these would be issues with this extension (GitHub Pull Requests and Issues)

The Gitlens blame issue should be reported in that extension's repo :).

For the commenting and checkout issues: 
- Next time you see the issue can you share the "GitHub Pull Request" output?
- Can you also share the output of `git remote -v`?
- And finally, is your repo a public repo? If so, can you share a link to it so I can see if I can reproduce the issues?
