### ISSUE TITLE
Empty files cannot be opened or marked as read

### ISSUE THREAD

**Issue by TIS-Julien-Wolf** [microsoft/vscode-pull-request-github#3618]
- Extension version: v0.44.0
- VSCode Version: 1.68.0
- OS: WSL Ubuntu-20.04

Steps to Reproduce:

1. create a PR with an empty `.py` file
2. open extension in VSCode
3. select the file for viewing
4. mark as viewed

When I try to open an empty file, I get a notification that I need to open the file on GitHub:
```
geoff-deforestation/geoff/carbon.py can't be opened locally. Do you want to open it on GitHub?
```

Having checked on GitHub that the file is indeed empty, I tried to review it, which caused an error:
```
Marked file as viewed failed: TypeError: Cannot read properties of undefined (reading 'substring')
```

The file in question was a Python file with a `.py` extension, if that matters.

**Comment by Christopher-C-Robinson** [comment]
I'm getting this error when trying to mark a file as reviewed:
`Marked file as viewed failed: TypeError: Cannot read properties of undefined (reading 'substring')`

![Image](https://github.com/user-attachments/assets/edeeac11-b932-4262-ab5e-f6b343ae1f4d)

This is an azure devops PR not a GitHub PR.

**Comment by alexr00** [comment]
This extension is just for GitHub PRs! You'll need to file an issue with whatever extension you're using for Azure Devops PRs.
