### ISSUE TITLE
GitHub Enterprise Personal Access Token fails

### ISSUE THREAD

**Issue by keaedwar** [microsoft/vscode-pull-request-github#3619]
Issue Type: <b>Bug</b>

When I start up vscode, I'm prompted with a popup that says "The extension. 'GitHub Pull Requsts and Issues' wants to sign in using GitHub Enterprise. When I press the Allow button, I'm prompted to enter my "GitHub Personal Access Token (Press 'Enter' to confirm or 'Escape' to cancel)" After entering my personal access token and pressing 'Enter' I get the error "Sign in failed: Error: The provided token does not match the requested..."

I've tried creating another personal access token on our enterprise github, but it still doesn't work. I can still access our enterprise github from other tools: git, GitHub Desktop, Visual Studio 2022, but not vscode.

Extension version: 0.44.0
VS Code version: Code 1.68.0 (4af164ea3a06f701fe3e89a2bcbb421d2026b68f, 2022-06-08T11:44:16.822Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.20GB (41.44GB free)|
|Process Argv|--crash-reporter-id dd49e5cf-961c-4496-a33b-7a15974749cb|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdf:30486550

```

</details>

<!-- generated by issue reporter --
![2022-06-10 09_57_12-Window](https://user-images.githubusercontent.com/61704744/173579972-e5c46e73-a9e8-45d3-8760-20e694f65b32.png)
![2022-06-10 10_00_10-Window](https://user-images.githubusercontent.com/61704744/173579995-c01d4b6f-69fa-4a1a-a78c-f767dbefdd42.png)
![2022-06-10 10_14_34-Window](https://user-images.githubusercontent.com/61704744/173580012-46d0e789-4665-4527-accc-f70f8b3a1a10.png)
>

**Comment by kittydoor** [comment]
https://github.com/microsoft/vscode-pull-request-github/wiki#2-is-github-enterprise-supported

You need to add the scopes described in the wiki... and also "workflow". It seems that started being required at some point but isn't updated in the wiki.
