### ISSUE TITLE
Allow keyboard shortcut for Open File

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/vscode-pull-request-github#3624]
(I searched existing issues).

The workflow of of this extension is a bit broken when you want to make any edit for a file you're viewing in a PR. Or even if you just want to read the file without the green diff colour over it.

Clicking on the side bar you end up in a view like below:
<img width="1695" alt="image" src="https://user-images.githubusercontent.com/936006/173693132-00e9e1c5-dad0-473a-837e-2f5d7b85bafc.png">

I want to switch to this view:
<img width="1701" alt="image" src="https://user-images.githubusercontent.com/936006/173693274-7ff30c82-50ff-47eb-b9bd-05e6b9989e29.png">

I want to make edits to this file or see it in action, how can I switch to opening it normally? I can't find any option of doing this. Right clicking on the tree view only offers me "open in Github". It would be really nice if there's a keybinding to this, similar to Gitlens for VSCode which allows you to toggle from diff view to opening the file.

Gitlens offers this (as well as Git too)
<img width="1695" alt="image" src="https://user-images.githubusercontent.com/936006/173694103-2f2ec6db-c21f-41dc-bb8b-f2653c44159d.png">

Similar issue: https://github.com/microsoft/vscode-pull-request-github/issues/868 (although this is more editing, which I think is possible)

**Comment by jasonwilliams** [comment]
Looks like this is available with no keybinding set

**Comment by alexr00** [comment]
There is an inline action (icon) in the tree for this:
![image](https://user-images.githubusercontent.com/38270282/174104691-8966badc-4cf7-401e-940d-316bc8314e50.png)

It's also in the top right editor actions when you have a diff open. 

@lszomoru the git.openFile command is used in the editor menu when in the diff editor, even when it's a PR diff (https://github.com/microsoft/vscode/blob/6e1ea79174dd791a0db49c96a9b986ae44823306/extensions/git/package.json#L1468-L1472). It looks like that command expects a uri. Would you accept a PR for it to use the active editor for the uri so that users can configure a keyboard shortcut for it?

**Comment by lszomoru** [comment]
@alexr00, apologies for not getting back to you on this. I just looked at the code, and if the `git.openFile` command is invoked without a `URI`, the command will [fallback](https://insiders.vscode.dev/github/microsoft/vscode/blob/f4d4971d75fe4ee2ee9b096f565141b9e61a2747/extensions/git/src/commands.ts#L752-L753) to the URI of the active editor document (assuming that it exists). From the looks of it everything is already in place to set up a keyboard shortcut unless I am missing something.

**Comment by jasonwilliams** [comment]
I raised an [issue](https://github.com/microsoft/vscode/issues/153786) with VSCode because I think there's a deeper underlying issue here where diff views don't always operate the same way. In other words it would be good for VSCode itself to provide some hook for extensions (such as this one) to plug into when trying to open either side split from a diff view. 

If you're a user of Git, Gitlens and Pull requests And Issues for example (like a lot of people would be), it can be confusing knowing when command/action to fire to view a diff side. Please have a look and let me know whet you think

**Comment by alexr00** [comment]
@jasonwilliams for this specific issue you can now use a keyboard shortcut to open the modified file starting with today's pre-release build (change was commit https://github.com/microsoft/vscode-pull-request-github/commit/262c85738f4f752fd0f545fe17585a971c0ff708). The command is pr.openModifiedFile.

**Comment by jasonwilliams** [comment]
Thanks @alexr00 that's appreciated. However I have been [working](https://github.com/microsoft/vscode/pull/165765) on the core VSCode to fix this because you can get this view in [many different ways](https://github.com/microsoft/vscode/issues/153786). There should be a standard interaction for anything that opens a diff view.

I think attaching this command at extension level is too jarring because gitlens, timeline and other places have the same, so as a user you need to learn a growing number of commands.

Not sure if @bpasero has any opinion on this.

**Comment by jasonwilliams** [comment]
https://github.com/microsoft/vscode/pull/165765 is now merged
