### ISSUE TITLE
Owner dropdown should list me first

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-pull-request-github#3627]
I.e. put the creator of a PR first:

![image](https://user-images.githubusercontent.com/900690/173820163-b5fb4ebb-20f4-4ea8-a59a-e79850add62f.png)

**Comment by alexr00** [comment]
@bpasero do you want the creator first or you first?

**Comment by bpasero** [comment]
@alexr00 I would mimic what GH does when I open the dropdown, I think it has a way to suggest users that fits best, I would probably put myself and creator of PR as suggestions. Maybe also reviewer.
