### ISSUE TITLE
Show changes since last review

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#363]
## GitHub.com flow

Blue line indicates there's a change:

![image](https://user-images.githubusercontent.com/2193314/45036660-f0760880-b011-11e8-9e3d-57931347a1ca.png)

Blue + indicates where I need to look from, handy link to the diff since I last looked:

![image](https://user-images.githubusercontent.com/2193314/45036676-f9ff7080-b011-11e8-9865-8d1641538914.png)

## Extension

No indication in tree (ie. I need to check notifications/email/github.com before switching back to extension):

![image](https://user-images.githubusercontent.com/2193314/45036706-0b487d00-b012-11e8-952a-9789cb9b0080.png)

No indication which commits/comments are new:

![image](https://user-images.githubusercontent.com/2193314/45036748-2a470f00-b012-11e8-8aad-5f3ed0098b7f.png)

**Comment by dmitry-timofeev** [comment]
It might be even more useful to be able to select the commits to review (because "changes since last review" sometimes does not work as expected + gets cleared once you open the changes on github).

**Comment by alexr00** [comment]
I can use this extension the first time I look at a PR, but after there are changes I can't. I don't need to re-review everything. I just need to review the changes since the last time I looked. Just being able to select which commits to use would solve this for me.

**Comment by fenollp** [comment]
To add on
> because "changes since last review" sometimes does not work as expected
> I don't need to re-review everything. I just need to review the changes since the last time I looked.

and now that there is the `Viewed` checkbox, I'd like to revisit the ask:

The files that `Changed since last view` should not show the full PR diff but only the diff since last `Viewed` of each changed file.
Right now one has no other choice than to review the changed file completely all over.

This behavior could be toggled by clicking `Changed since last view`.

**Comment by mayurdhurpate** [comment]
Hi team, would like to bump this up. Would be very useful as re-reviewing a norm while doing a PR Code Review.

**Comment by shubham-agarwal-dd** [comment]
+1

**Comment by berkeleymalagon** [comment]
+1 💙

**Comment by halouvi** [comment]
+1 please :-)

**Comment by benibenj** [comment]
@daviddossett, we are looking for two icons for switching between the ChangesSinceLastReview Mode and AllChangesOfPullRequest Mode. The icon will be placed in the panel in the top left (as in image) and when clicking it the Icon should be replaced with the second Icon, corresponding to switching into the other mode. Do you recommend using a specific icon pair or should new Icons be created for this case? 
![button](https://user-images.githubusercontent.com/44439583/178003193-37be9689-d041-40bb-b21c-de53793ee2db.png)

**Comment by alexr00** [comment]
@daviddossett it's more of a toggle. In effect, it will filter some of the files out, but also _the contents_ of the files (really the diffs) will change.

**Comment by daviddossett** [comment]
Ok, I'll see if we have any icons that work for this else I'll propose some new ones.

**Comment by daviddossett** [comment]
One possible idea. Still a bit rough but basically exploring something riffing off GH's "Files changed" icon and then a varation for pending changes that haven't yet been reviewed. 

I'm not crazy about how the pending version looks yet but using these as a starting point.

<img width="875" alt="CleanShot 2022-07-14 at 11 47 15@2x" src="https://user-images.githubusercontent.com/25163139/179059838-9a5c4768-0c72-4480-9e50-1f7d19758be5.png">

**Comment by benibenj** [comment]
@daviddossett I think these icons are a good starting point. The arrows (in pending) could possibly just be replaced with some symbol/icon which would indicate NEW changes (However all changes are 'New' just some of them are since a review).   

A totally different option could be sort of a TODO list as changes since a review will probably be in relation to comments/suggestions made in that review. (
![image](https://user-images.githubusercontent.com/44439583/179203647-49c52035-9c0f-4745-aaca-f59ac44f0a99.png)
)

I'm looking forward to your suggestions.

**Comment by daviddossett** [comment]
We could reuse `checklist` (left) and introduce a variant with unchecked items:

<img width="710" alt="CleanShot 2022-07-15 at 09 54 38@2x" src="https://user-images.githubusercontent.com/25163139/179271531-8890700d-3b93-474f-9c55-55bb57662366.png">

**Comment by alexr00** [comment]
@daviddossett I'm worried that the `checklist` and parital-`checklist` look too similar, but I like the idea of the "Files Changed" icon. What about using the dot idea similar to `comment` and `comment-unresolved`?

**Comment by daviddossett** [comment]
This could work. One concern here would be that the dot icon pattern is typically used for a state that could be cleared. E.g. clicking on an icon with a dot would reveal something and then would remove the dot.

Once reviewed, would this view still be visible? Or is it sort of temporary? This could make more sense if that's the case.

<img width="437" alt="CleanShot 2022-07-21 at 09 03 09@2x" src="https://user-images.githubusercontent.com/25163139/180260740-1240f1f8-2805-4e04-a744-86ca887e118e.png">

Another option would be to use the "Modified" icon as the nested indicator:

<img width="431" alt="CleanShot 2022-07-21 at 09 16 09@2x" src="https://user-images.githubusercontent.com/25163139/180263443-1f1063ee-a615-482c-8306-66464925322d.png">

**Comment by benibenj** [comment]
I prefer the first option as many of the other options also use a dot when there is something new and you could argue that the state will be cleared after reviewing the new changes.

**Comment by daviddossett** [comment]
Conceptually it makes sense, but how would the interaction work? Would the icon with dot appear dynamically so that users notice it and click on it to view the new changes? I'd expect the dot to go away once reviewed. But then I wouldn't know what purpose the regular `files-changed` icon would have if there aren't any unseen changes anymore.

**Comment by benibenj** [comment]
The Icon only appears when there is a change since a review, otherwise no icon appears. When there is a change since a review and a user clicks on the icon it will display only the changes since the review and the other icon (normal diff icon) appears to switch back to showing all changes.

**Comment by daviddossett** [comment]
Ok, here's an idea to work with that:

![CleanShot 2022-07-22 at 13 21 36](https://user-images.githubusercontent.com/25163139/180534334-8e47a41c-df90-4855-980d-27c2948c7ad4.gif)

- New changes are available as indicated by `files-changed-dot`
- Once viewing new changes, `go-to-files-changed` appears as an actionable icon to return to the other view.
- If the new changes were reviewed, the `files-changed-dot` icon disappears (as demonstrated in the gif). If not reviewed, it stays.

**Comment by alexr00** [comment]
These fit very well with how the interaction works. Thanks @daviddossett!
