### ISSUE TITLE
Allow me to create a new Milestone from the Milestone picker

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode-pull-request-github#3630]
Here's what I see:
![image](https://user-images.githubusercontent.com/2644648/173900528-b27460fa-25ed-49d1-a8d7-eb07bdfb4495.png)

I'd love an option when I type in this to say `Create Milestone`:
![image](https://user-images.githubusercontent.com/2644648/173900624-8087514d-9db4-4ee0-b6db-c8e73ae227f8.png)

**Comment by alexr00** [comment]
Fixed by https://github.com/microsoft/vscode-pull-request-github/pull/3686
