### ISSUE TITLE
Mentionable users API

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-pull-request-github#364]
If we can fetch `mentionable` users from github api, we can show auto complete when users type `@` in comment textarea.

**Comment by StanleyGoldman** [comment]
I was doing some research into how to get this done.
It seems this API is exposed via GraphQL.

https://developer.github.com/v4/object/repository/#mentionableusers

[Here](https://github.com/atom/github/blob/10fb0861626700eefa9b7c47229117f6a53433b7/lib/models/user-store.js#L147-L171) is how it is implemented in GitHub for Atom

**Comment by RMacfarlane** [comment]
This was implemented for comments within editors with https://github.com/microsoft/vscode-pull-request-github/pull/842
