### ISSUE TITLE
Make "rename" action more clear in review mode

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-pull-request-github#3644]
Currently, if a file is renamed, it's quite hard to tell what's going on. The entry looks like this

![image](https://user-images.githubusercontent.com/2230985/174407158-1843c31f-340c-41fd-a60e-2c3b50979495.png)

Clicking on the file opens an empty clean diff, and the tooltip on the tree view item is just its path. At minimum, the file could have a tooltip saying "Renamed [old path] to [new path]". Ideally opening the diff would be more clear, too.

**Comment by alexr00** [comment]
The diff is basically the same as what the built-in git extension does for renames. I will add a better tooltip though.

**Comment by IanMatthewHuff** [comment]
Verified. I see the new old => new tooltip now.
