### ISSUE TITLE
Hide the white vertical line 'start discussion'

### ISSUE THREAD

**Issue by xiaobaishu0097** [microsoft/vscode-pull-request-github#3645]
Hi everyone, 

I am a newcomer to this extension and want to hide the white vertical line 'start discussion' on the left side of the codespace. 

Could anyone provide me with some suggestions about how to achieve this?

Thanks!

**Comment by alexr00** [comment]
There's a new VS Code command (comes from VS Code, not from this extension) that lets you toggle editor commenting: "Comments: Toggle Editor Commenting". This command will hide the vertical line and any comments in the editor. The command is available in VS Code Insiders and will be part of the next VS Code stable release.
