### ISSUE TITLE
Can't comment on a new file (via github.dev web editor)

### ISSUE THREAD

**Issue by yoavbls** [microsoft/vscode-pull-request-github#3646]
Can't comment on a new file via github.dev web editor, the comments bar isn't shown:  
  
<img width="248" alt="image" src="https://user-images.githubusercontent.com/5693018/174592784-c312d0d8-778e-49e0-a8b4-870b3973efe4.png">

How should it be:
<img width="286" alt="image" src="https://user-images.githubusercontent.com/5693018/174592826-3c18c79a-738f-4d68-afe5-b6530b681926.png">

- Extension version: v0.44.0 (Built-in)
- VSCode Version: 1.68.1
- OS: github.dev Web editor (chrome 102)

Steps to Reproduce:

1. Create a pull request from a branch with a new file
2. Navigate to this file in the "GitHub pull request" section

**Comment by alexr00** [comment]
@joyceerhl looks like I'm getting an error from Remote Hub when trying to get the diff between the PR head commit and the base branch:

```
EntryNotFound (FileSystemError): vscode-vfs://github+7b2276223a312c22726566223a7b2274797065223a342c226964223a22616c65787230302f6e657746696c6531227d7d/alexr00/playground
    at Ll.getFileContent (https://github.vscode-unpkg.net/GitHub/remotehub/0.35.2022062201/extension/dist/browser/extension.js#vscode-extension:211:1374)
    at q0.show (https://github.vscode-unpkg.net/GitHub/remotehub/0.35.2022062201/extension/dist/browser/extension.js#vscode-extension:110:15981)
    at q0.getContent (https://github.vscode-unpkg.net/GitHub/remotehub/0.35.2022062201/extension/dist/browser/extension.js#vscode-extension:110:17981)
    at async Promise.all (index 0)
    at q0.diffBetween (https://github.vscode-unpkg.net/GitHub/remotehub/0.35.2022062201/extension/dist/browser/extension.js#vscode-extension:110:17137)
    at GitFileChangeModel.diffHunks (https://funny-towns-follow-109-202-200-78.loca.lt/dist/browser/extension.js#vscode-extension:51608:23)
    at ReviewCommentController.provideCommentingRanges (https://funny-towns-follow-109-202-200-78.loca.lt/dist/browser/extension.js#vscode-extension:53504:94)
```

The calling line is here: 
https://github.com/microsoft/vscode-pull-request-github/blob/5f9a963aae8511ebdd98ad85966acafb858b9cd9/src/view/fileChangeModel.ts#L57-L58

I've debugged and verified that all the parameters look correct and that the issue doesn't occur on desktop.

Example of what the expected output of `diffBetween` is for the following added file:
```
hello

world
```
```
diff --git a/file1.txt b/file1.txt\nnew file mode 100644\nindex 0000000..14b6b0f\n--- /dev/null\n+++ b/file1.txt\n@@ -0,0 +1,3 @@\n+hello\r\n+\r\n+world\n\\ No newline at end of file
```

**Comment by alexr00** [comment]
Debugging further and it looks like Remote Hub is looking for a file that doesn't exist. `632de960501ecebec267ba06bc238a1d715b8692` is the head commit of my PR branch.

```
EntryNotFound: Unable to read file 'vscode-userdata:/User/globalStorage/github.remotehub/tars/github/alexr00/playground/632de960501ecebec267ba06bc238a1d715b8692' (Error: Unable to resolve nonexistent file 'vscode-userdata:/User/globalStorage/github.remotehub/tars/github/alexr00/playground/632de960501ecebec267ba06bc238a1d715b8692')
    at h.doReadFileStream (https://main.vscode-cdn.net/insider/f361c5b71d6676cfc6de97cdb1cc40b08bf7d994/out/vs/workbench/workbench.web.main.js:599:18533)
    at async h.doReadFile (https://main.vscode-cdn.net/insider/f361c5b71d6676cfc6de97cdb1cc40b08bf7d994/out/vs/workbench/workbench.web.main.js:599:17489)
```

Stack trace:
```
_handleError (queryBuilder.ts:275)
readFile (queryBuilder.ts:275)
await in readFile (async)
getTarFromDisk (extension.js:103) <-- this is Remote Hub
getTarCore (extension.js:103)
await in getTarCore (async)
getCachedTar (extension.js:103)
await in getCachedTar (async)
eval (extension.js:211)
getContent (extension.js:211)
await in getContent (async)
eval (extension.js:110)
memoizedFn (extension.js:14)
getFileContent (extension.js:211)
await in getFileContent (async)
readFile (extension.js:103)
run (extension.js:102)
r.value (extension.js:102)
readFile (extension.js:39)
readFile (extension.js:47)
await in readFile (async)
run (extension.js:27)
r.value (extension.js:27)
```

**Comment by joyceerhl** [comment]
Thank you for investigating! It looks like RemoteHub's `diffBetween` implementation doesn't handle cases where one of the two diff-ed files has been deleted or added, because it expects that the file it's being asked for does exist in the specified sha. There's a super easy hacky RemoteHub fix here--just return an empty string on a `FileNotFoundError`:
![image](https://user-images.githubusercontent.com/30305945/175103976-15ae7600-5a79-4a94-bd0e-650b78a7ca48.png)

But I'm not confident that that won't cause other issues down the line, so in order to have parity with the desktop `IGit` implementation, which just shells out to git for diff generation, I think it makes sense to fake out the unidiff that you would get for a diff representing a deletion or addition.

**Comment by yoavbls** [comment]
Thank you very much for this super quick fix!
It works well on `insiders.vscode.dev/github` 🙏🏼
