### ISSUE TITLE
Truncate sanitized issue title variable to help avoid MAX_PATH

### ISSUE THREAD

**Issue by pokey** [microsoft/vscode-pull-request-github#3647]
Issue Type: <b>Bug</b>

## Steps

1. Select an issue from side bar and click on "Work on issue"

## Expected behaviour

The branch name only includes characters such as a-z (lowercase), 0-9, _, etc

## Actual behaviour

Branch name includes characters such as `<`

## Possible approach

You might consider using something like https://github.com/sindresorhus/slugify

Extension version: 0.44.0
VS Code version: Code 1.68.0 (4af164ea3a06f701fe3e89a2bcbb421d2026b68f, 2022-06-08T11:44:00.250Z)
OS version: Darwin x64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|32.00GB (0.16GB free)|
|Process Argv|--crash-reporter-id 99d35f96-61a9-461b-a60d-f915d32f3eee|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550

```

</details>

**Comment by alexr00** [comment]
We used https://git-scm.com/docs/git-check-ref-format to determine which characters to allow in branch names. It looks like `<` is an allowed character. 

Can you describe the scenario in which git's allowed characters aren't working for you?

**Comment by pokey** [comment]
Hmm strange. This is what happened on Windows:

```bash
$ git pull
error: cannot lock ref 'refs/remotes/origin/pokey/issue761-Breakpoint-<target>-puts-a-breakpoint-on-the-current-line-instead-of-the-target-line': Unable to create 'C:/Users/andre/cursorless/.git/refs/remotes/origin/pokey/issue761-Breakpoint-<target>-puts-a-breakpoint-on-the-current-line-instead-of-the-target-line.lock': Invalid argument
```

More broadly, though, I would prefer slugification, in part just for aesthetic reasons, and also to avoid any other possible problems

**Comment by alexr00** [comment]
I think you may have hit a Windows MAX_PATH issue there. I can truncate the issue title at 100 characters which should help.

**Comment by alexr00** [comment]
Ended up going with 150 instead of 100 to try to strike a balance between truncating too early and not truncating often enough.

**Comment by alexr00** [comment]
Also updated the description for the setting `githubIssues.issueBranchTitle` to include a link to the git documentation.

**Comment by pokey** [comment]
Ok, thanks for fixing.  I'd still prefer slugification, though, as `git` being happy isn't the only issue for me.  For example, when I refer to the branch on my command line, it thinks the `>` is an output redirect
