### ISSUE TITLE
Option to only view one category at a time

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-pull-request-github#365]
[Atom 1.30 adds the ability to view and check out pull requests:](http://blog.atom.io/2018/08/28/atom-1-30.html)

![image](https://user-images.githubusercontent.com/36805289/45070300-a5560700-b09e-11e8-82ef-d1d4f0c4b50a.png)

I think their design is far more fluid and it partly has to do with not nesting labels under various category titles. Aside from that, including the pull request number, check status, and date is really cool! Maybe this extension could enable something similar? :smile: 

Anyways, my ideal design would be to list all pull requests by default and then provide an option for the user to filter that list by category. This would improve the view by removing the unnecessary duplication of labels; there is no benefit in displaying the same pull request multiple times. 

Another enhancement would be the removal of the "descriptions" label. Following the example of the outline view, the label should either open the preview or expand depending on whether or not the arrow icon was pressed. Like the aforementioned suggestion, this would remove label duplication by rendering the "descriptions" label redundant.

**Comment by rebornix** [comment]
For the CI status, we can probably use file decorations like check mark with colors to indicate the status.

**Comment by alexr00** [comment]
We now have the CI status in the PRs view. You can also add your own queries to the PRs view. I'm going to close this since I think the main issues have been addressed. If that's not the case the please ping and we can re-open and continue the discussion.
