### ISSUE TITLE
Test exiting review mode when already on the default branch

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#3656]
Refs: https://github.com/microsoft/vscode-pull-request-github/issues/3590

- [x] anyOS @daviddossett
- [x] anyOS @weinand

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode-pull-request-github/issues/new?body=Testing+%233656%0A%0A&assignees=alexr00)

---

Setup:
Before testing, make sure you have the [pre-release](https://github.com/microsoft/vscode-pull-request-github/wiki/Pre-release-Build) build installed.

Testing:
1. Open a folder with a GitHub repository.
2. Create a PR from the repository's default branch (usually main or master) into another branch. 
> note: the next step should only happen once per workspace per day!
4. Verify that you get a notification offering to ignore PRs from the default branch. 
5. Verify that choosing the "Ignore Pull Request" option in the notification sets the setting `githubPullRequests.ignoredPrBranches`.
6. Verify that if you remove that setting and open the PR again that you don't get the notification again (it should only show once every 24 hours per workspace).
7. Verify that manually setting `githubPullRequests.ignoredPrBranches` works the way you'd expect.

**Comment by weinand** [comment]
@alexr00 this seems to work fine for me. 
But the one-notification-per-24-hour policy I'll have to verify tomorrow at 15:00... ;-)
(BTW, wouldn't it make more sense to have a once-per-day (midnight to midnight) policy? The I would have to wait until 15:00...)

**Comment by joaomoreno** [comment]
> @joaomoreno I still get people regularly noticing and filing issues because of the "not a valid menu identifier" message that shows in the console and in the Running Extensions editor. It makes the extension look low quality when people look in Running Extensions editor.

@alexr00 This is problematic. If we remove this message, an extension author who makes a typo in the menu id to contribute entries to will never be warned that they have a typo in there. Maybe we should show it only when running in Extension Development mode?

**Comment by alexr00** [comment]
@joaomoreno that would be perfect and I would happily owe you many beers and/or coffees for that change.

**Comment by daviddossett** [comment]
Works great, however I too can't yet verify the notification coming back. I'll report back tomorrow 😉

**Comment by joaomoreno** [comment]
> @joaomoreno that would be perfect and I would happily owe you many beers and/or coffees for that change.

The more I wait to do this, the higher the reward seems to be. _Should I wait longer...?_ 😄

**Comment by weinand** [comment]
@alexr00 I've verified that the "one-notification-per-24-hour policy" works fine: today I got another notification.

**Comment by daviddossett** [comment]
Works!
