### ISSUE TITLE
GitHub PR eventually hangs due to `git+ssh://` scheme being in a remote

### ISSUE THREAD

**Issue by errietta** [microsoft/vscode-pull-request-github#3675]
### Update

We've learned some more info in this issue... please jump to https://github.com/microsoft/vscode-pull-request-github/issues/3675#issuecomment-1171360048

---
### Original

Does this issue occur when all extensions are disabled? N/A because this is an extension bug

- VS Code Version: Version: Version: 1.68.1 (Universal)

- OS Version:  Mac os 12.3.1 (21E258)

Steps to Reproduce:

We have an enterprise account but not a custom url (we just use normal github.com)
The problem is that the extension sort of assumes you have a custom URL. You can see by the code [here](https://github.com/microsoft/vscode/blob/5a43663aed2c063b4bb0d7512f9df0d77668b9ca/extensions/github-authentication/src/githubServer.ts#L581) that it hits `${apiUri.scheme}://${apiUri.authority}/api/v3${path}`
However in normal `api.github.com` (which is what I used as my enterprise server url) there is no `/api/v3/` so it does not work.

My proposal:
* Have a different boolean setting "use github enterprise" that does the enterprise PAT dance even without a custom URL
* If the custom URL is set, use that with /api/v3/
* Else use normal `api.github.com` without custom url

Happy to give more info if needed. Also, if there's some way to develop on this extension without having to compile whole vs code, I'd be happy to implement my proposal.

Thanks!

**Comment by alexr00** [comment]
Thanks for trying that out @errietta. Do you know how you ended up with the `git+ssh` scheme in your remote? It shouldn't be a problem for this extension to handle it, but I'm curious how this state happens.

**Comment by errietta** [comment]
@alexr00 I manually typed the remote, and that's the scheme I'm used to using off by heart. It's supported by git, so I didn't think it'd be an issue

**Comment by alexr00** [comment]
@errietta makes sense! I will add support for it.

**Comment by errietta** [comment]
> @errietta the fix will be available in the pre-release build of GitHub Pull Requests and Issues by Friday. It ended up being suspiciously simple, so if you have a chance to try it out after Friday it would help to confirm that the fix is good!

Sure please ping me when it's released and I'll try out

**Comment by errietta** [comment]
Hi @alexr00 tried this today  with a git+ssh remote and looking good 👍

**Comment by alexr00** [comment]
@errietta thank you for trying it out!

**Comment by Josar** [comment]
Hello All,

i tried to log into our GHE server with "vscode-pull-request-github" but always get an Network error, after i supply the PAT.

```
[2022-07-22 15:44:30.473] [exthost] [error] Error: network error
	at _ (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\github-authentication\dist\extension.js:1:708855)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async t.GitHubEnterpriseServer.login (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\github-authentication\dist\extension.js:1:717452)
	at async t.GitHubAuthenticationProvider.createSession (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\github-authentication\dist\extension.js:1:706656)
```

Any tips to resolve that? Or guidance on how to debug this? 
@errietta you seem to know how to debug VS code plugins maybe you can help me with that?

I allready switched the plugin to preview v0.47.2022072109
VS Code 1.69.2

**Comment by alexr00** [comment]
@Josar please open a new issue with these details. This issue is just about having `git+ss://` in your git remote.
