### ISSUE TITLE
Cannot add comments in renamed+edited

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#3676]
https://github.com/microsoft/vscode-pull-request-github/issues/2999#issuecomment-1170914617

1. Checkout a topic branch
2. Make a commit that both renames a file and makes an edit in the same file
3. Create a PR.
4. You should be able to add comments in the ranges around the changes in the renamed file, but you can't.

**Comment by meganrogge** [comment]
can still reproduce the issue, but looks like the change was too recent to be tested

**Comment by alexr00** [comment]
There's a new pre-release build today that has the fix.
