### ISSUE TITLE
Automatically delete head branches isn't synced with the extension after merge/squash

### ISSUE THREAD

**Issue by bmolaga-r7** [microsoft/vscode-pull-request-github#3678]
When configuring GitHub to "Automatically delete head branches" like in here -
 
![Screen Shot 2022-07-03 at 9 13 29](https://user-images.githubusercontent.com/20521495/177027521-def548ba-1d39-4b6a-9cf9-cd2a93c00eda.png)

After every merge/squash from the extension, the head branch is deleted as expected on GitHub and on the origin of course, but the extension is not updated and does not show any indication of the deletion, the opposite - it asks me if I want to delete the branch -

![Screen Shot 2022-07-03 at 9 10 02](https://user-images.githubusercontent.com/20521495/177027578-6a3e4938-4642-4b96-8b9c-574e39305232.png)

- Extension version: v0.44.0
- VSCode Version: 1.68.1
- OS: macOS Monterey 12.4

Steps to Reproduce:

1. Go to repo settings > General > enable "Automatically delete head branches "
2. Open a PR
3. Go to vscode > GitHub Pull Requests extension > merge the PR

**Comment by alexr00** [comment]
That "Delete branch..." button lets you delete the local branch too.
