### ISSUE TITLE
exiting failed: no such branch

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode-pull-request-github#3679]
With a VSCode branch, I created a PR and then tried to exit and am seeing `exiting failed: no such branch`

https://user-images.githubusercontent.com/29464607/176953171-a92d2c16-8beb-4bf4-9ce7-33e8eeda5788.mov

**Comment by sedghi** [comment]
I'm getting this error (when I checkout a PR, it says No such branch), is there any update on the fix?

**Comment by alexr00** [comment]
@sedghi Fix is in the July 2022 milestone, which means that it will be released in the July release, which usually happens at the beginning of August. You can also get the fix earlier if you want to try out the [pre-release build](https://github.com/microsoft/vscode-pull-request-github/wiki/Pre-release-Build). 

If you're seeing this when checking out a PR it may be a different issue though. In that case, if you could try out the pre-release build and respond back if you're still seeing the issue that would be very helpful. From there, we can figure out how to fix it.
