### ISSUE TITLE
please change Icon

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode-pull-request-github#3689]
![image](https://user-images.githubusercontent.com/1876302/177439027-1cb4ae77-6550-42dd-aa8f-749ed1ee771e.png)

what is relation between right-arrow and check-out？

**Comment by alexr00** [comment]
I think we use the right arrow to indicate "open".

@daviddossett in case you think we should use a different icon. Closing, but if we decide to use a different icon I'll reopen.

**Comment by daviddossett** [comment]
I'd actually agree that the arrow doesn't really convey the check out concept. Not sure what would be the best alternative here but perhaps some variation on the PR-related icons: 

<img width="972" alt="CleanShot 2022-12-09 at 09 11 06@2x" src="https://user-images.githubusercontent.com/25163139/206756167-5603b180-1f1a-4a8c-b6e8-9c918a367133.png">

Open to ideas if you have any @heartacker

**Comment by heartacker** [comment]
git-pull-request-go-to-changes

![image](https://user-images.githubusercontent.com/1876302/206823806-a93bf339-c341-4646-b4b7-a5be9e739c5e.png)

**Comment by alexr00** [comment]
Changing to the `check` icon. The `git-pull-request-go-to-changes` is for the "go to changes since last review" command and would be too overloaded.

![image](https://user-images.githubusercontent.com/38270282/215464035-721aa1b3-1bbf-4055-a121-fbd541d3f2d0.png)

**Comment by alexr00** [comment]
I'd be happy with an icon like that.

**Comment by daviddossett** [comment]
I see that we have `desktop-download` already which could work. I'm not sure if I fully associate this with "checkout" but at least it's consistent with what people see on the GitHub.

<img width="142" alt="CleanShot 2023-01-31 at 09 49 00@2x" src="https://user-images.githubusercontent.com/25163139/215842090-248a75b5-9751-4945-89df-25d26dbeb26b.png">

**Comment by alexr00** [comment]
> I'm not sure if I fully associate this with "checkout" but at least it's consistent with what people see on the GitHub.

Actually, I agree. This doesn't look more like "checkout" than the current arrow. 

The icon has been the right arrow for quite a while now and we haven't received much feedback on it. I'm going to leave it as is since we don't have a better option and the change could be disruptive to existing users.
