### ISSUE TITLE
Not listed in marketplace

### ISSUE THREAD

**Issue by mjdease** [Microsoft/vscode-pull-request-github#370]
- Extension version: 0.1.0 is the latest release at time of report
- VSCode Version: 1.27.0
- OS: macOS 10.13.6

I was interested in trying this extension out but can't seem to find it in the marketplace. 

From the readme:
> 2. Install the extension from the marketplace

I've searched for "Github Pull Request" in the marketplace both on the web and via the editor.
I've also checked the VSCode section of the Microsoft publisher page https://marketplace.visualstudio.com/publishers/Microsoft

<img width="851" alt="screen shot 2018-09-06 at 10 20 11 am" src="https://user-images.githubusercontent.com/636957/45160987-2b6a6e80-b1c1-11e8-9ccc-cbdbb27b1a87.png">

**Comment by RMacfarlane** [comment]
@mjdease Apologies, we haven't yet published to the marketplace. We had been planning to do this on Tuesday, but the Azure outage brought the marketplace down. We're now targeting next week. I'll update the README in the meantime to make this clear
