### ISSUE TITLE
Is it possible to merge a PR from the UI, or do we need to use the terminal?

### ISSUE THREAD

**Issue by AndreaPi** [microsoft/vscode-pull-request-github#3704]
As per title: once we define the `from` and `into` branches to be merged in the UI, we write a comment and we click on "Comment and submit", does this actually merge the branch? Or do we need to open the Terminal window and execute `git merge` from there?

**Comment by alexr00** [comment]
You can merge from the overview page (2), which can be opened from the "Changes" view (1), or from the PR sidebar view (3).

![image](https://user-images.githubusercontent.com/38270282/178019734-ae95168c-fd3f-4e56-a145-7104548af40d.png)

**Comment by AndreaPi** [comment]
@alexr00 thanks for the super-fast answer!
