### ISSUE TITLE
Reconsider default PR changes view

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-pull-request-github#3714]
I find the default tree view to be much noisier

![image](https://user-images.githubusercontent.com/22350/178285428-53986456-75ff-47b6-9b5d-d46aba27dcf5.png)

than its list view counterpart:

![image](https://user-images.githubusercontent.com/22350/178285365-bd6e6128-6b9e-4333-b293-5128993c0e2a.png)

Should we default to list, similarly to how SCM does it?

**Comment by alexr00** [comment]
Would impact https://github.com/microsoft/vscode-pull-request-github/issues/3274 a bit since it's a feature that wouldn't show by default anymore.

**Comment by alexr00** [comment]
Closing given the usefulness of folder level checkboxes.
