### ISSUE TITLE
Debug yaml actions

### ISSUE THREAD

**Issue by ohhmm** [microsoft/vscode-pull-request-github#3716]
Type: <b>Feature Request</b>

Run actions locally

Extension version: 0.46.0
VS Code version: Code - Insiders 1.70.0-insider (112b2d050c8398e74360fcb2219af76ad51e8aa5, 2022-07-12T05:17:20.095Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

**Comment by alexr00** [comment]
This sounds like something that another extension could do.
