### ISSUE TITLE
Extension not showing in sidebar

### ISSUE THREAD

**Issue by steve-gentile-kr** [microsoft/vscode-pull-request-github#3720]
I've installed the plugin but its not showing up in my sidebar.

- Extension version:
- VSCode Version: 1.69.1
- OS:  OSX M1

Steps to Reproduce:

1.
2.

**Comment by alexr00** [comment]
Can you share the output of "GitHub Pull Requests"?

**Comment by sgentile** [comment]
Closing - I did not realize I needed to setup the GitHub extension first
