### ISSUE TITLE
Marking a file as "viewed" should automatically move to the next-unviewed file

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-pull-request-github#3730]
In GH, marking a file as viewed collapses it so that you get moved to the next file. In GHPR, I need to manually select the next file I want to view after marking a file as viewed. It would be handy if this happened automatically, since "viewed" files generally require no further action.

**Comment by alexr00** [comment]
We now close the file when you mark it as viewed from either a keybinding or from the editor toolbar too.
