### ISSUE TITLE
Update wiki documentation for github enterprise, add missing workflow scope

### ISSUE THREAD

**Issue by ThomasBachSap** [microsoft/vscode-pull-request-github#3731]
There is some github enterprise documentation in the wiki: https://github.com/microsoft/vscode-pull-request-github/wiki#2-is-github-enterprise-supported
However, it does not contain the correct list of scopes for the personal access token as ´workflow´ is also required. In addition, some parts seem to be a bit outdated.

I have drafted an update here: https://github.com/ThomasBachSap/vscode-pull-request-github/wiki/Home/_compare/5fe3dbb169ebf7e9b957fb80c8fd90f8dd516f9c...d4272a1a55e3f487bf5ad20d03201cc2edda7c18?diff=split

Unfortunately, I do not see an option to create a pull request for the wiki. Happy to create if somebody points me to some info how to do it. Otherwise, one just might copy&paste an edit. Consider the text released as CC0 where possible and CC-BY-4.0 otherwise.

**Comment by ThomasBachSap** [comment]
@alexr00 Can you point me the to SLA? I guess we have something from SAP side (this is my work account) in place with Microsoft or at least some internal guidance whether I can sign it or not. Happy to jump through it if the jump is short.

**Comment by grahamb** [comment]
Could someone please update the docs? If you can't take @ThomasBachSap's PR directly, surely someone can update the docs manually. I wasted a fair bit of time trying to figure out why I couldn't log in with a PAT using the documented scopes.

**Comment by grahamb** [comment]
Also: the error message displayed within VSCode doesn't note that it requires `workflow` scope. I didn't get a screenshot, but it said that needed the same scopes as in the docs (`read:user repo user:email`).

**Comment by alexr00** [comment]
@grahamb if you're willing to tolerate a little instability as I continue working on GitHub Enterprise support, I would recommend you try the pre-release version of the extension with VS Code Insiders at least until the next stable release of both. There's no need for a PAT there now and I'm actively working on GitHub Enterprise support there.

**Comment by alexr00** [comment]
@ThomasBachSap thank you for your wiki update suggestions. I don't have a good way to take your changes, especially not with CC0 where possible and CC-BY-4.0 otherwise as this repo uses the MIT license: https://github.com/microsoft/vscode-pull-request-github/blob/main/LICENSE

I have made my own updates to the wiki to include the `workflow` scope as well as some details about the pre-release changes.

**Comment by ThomasBachSap** [comment]
MIT might be an untypical choice for text, where CC seems to be the common case, but I would also have provided that or a CLA. Anyway ticket is closed and the content is updated. If everyone is happy, then I am too.
