### ISSUE TITLE
Inconsistent use of picker title

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-pull-request-github#3736]
Only the milestone picker uses a title, the others (e.g. Label) do not:

![image](https://user-images.githubusercontent.com/900690/179692574-a3582df5-744b-43b8-84a5-a12890d12962.png)

**Comment by alexr00** [comment]
@bpasero we did this because of the new "+" button in the title bar. None of the pickers used a title, but when we added the "+", we also needed to add a title otherwise it looks empty. Would you suggest that we move all pickers to use a title now?

**Comment by bpasero** [comment]
Ah ok, but I can also create a new label, no?

**Comment by alexr00** [comment]
Not from within the extension. I don't think we've ever gotten a feature request for that.

**Comment by bpasero** [comment]
Ok then nevermind 👍
