### ISSUE TITLE
Sign In actions don't work

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-pull-request-github#374]
Noticed this with https://github.com/Microsoft/vscode-pull-request-github/issues/366

- Get "Sign in" notification, dismiss it
- Click the status bar item to sign in, nothing happens
- From the command palette, run "GitHub Pull Requests: Sign In to Github", nothing happens

If I click the button in the notification, it does pop up the browser correctly.

**Comment by RMacfarlane** [comment]
@roblourens I haven't been able to reproduce this - this is with version 0.1.1 of the extension?

**Comment by roblourens** [comment]
I just upgraded to 0.1.1, seems to work now
