### ISSUE TITLE
Placeholder comment showed up after creating a PR

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-pull-request-github#3741]
- Created https://github.com/microsoft/vscode/pull/155663 as usual
- The comments panel showed up with this comment:

<img width="634" alt="image" src="https://user-images.githubusercontent.com/323878/179861738-b312d987-9c6d-46f8-8b65-750f77fcf7ee.png">

**Comment by alexr00** [comment]
@roblourens any chance you have another extension installed that did that? I don't think the string 'name' even occurs in the extension code and I can't repro it. It's also missing other values that we set on the comment, like the icon and the timestamp.

**Comment by roblourens** [comment]
I saw this once, but I create lots of PRs and have never seen it again 🤷
