### ISSUE TITLE
Temporary flickering newlines on file edit

### ISSUE THREAD

**Issue by zingmane** [microsoft/vscode-pull-request-github#3749]
- Extension version: `v0.46.0` and `v0.47.2022072109`
- VSCode Version:

```
Version: 1.69.2 (Universal)
Commit: 3b889b090b5ad5793f524b5d1d39fda662b96a2a
Date: 2022-07-18T16:12:57.074Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin x64 21.5.0
```
- OS: MacOO Monterey 12.4

Steps to Reproduce:

1. Take a file that is in version control
2. Edit that file
3. strange newlines occur but they disappear if the file got saved

Maybe the behavior only occurs in combination with other extensions. Anyway, if I disable "GitHub Pull Requests and Issues" Extension there is no such flickering.
The three dots in the temp. visual newline have no hover or additional information that could lead back to their origin.

https://user-images.githubusercontent.com/148202/180243750-53df9755-ec22-41e8-8cd3-8abc9a0361cd.mp4

**Comment by alexr00** [comment]
@zingmane this is very strange. I can't think of anything that might cause this in GitHub Pull Requests and Issues. Can you share the list of all the other extensions you have installed?

**Comment by zingmane** [comment]
Hi @alexr00.

I have tried to narrow down the reason. The problem seems to be related to the gitlens extension (`eamodio.gitlens`).

I have created a workspace with only these two extensions enabled. When I disable one of them, the flickering does not occur.

**Comment by zingmane** [comment]
Thanks for your help and sorry for bothering you.
I figured out that’s not the fault of your extension. It’s a problem of gitlens with a global git ignoreRevsFile config.
https://github.com/gitkraken/vscode-gitlens/issues/1143

Maybe I didn’t reload vscode windows correctly or I was to fast.
