### ISSUE TITLE
Can't auto-merge and draft simultaneously

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-pull-request-github#3755]
We currently show these two as independent options but they are, in fact, mutually exclusive. The user just gets an error today if they try to create a PR; and the PR is indeed created in Draft mode.

![image](https://user-images.githubusercontent.com/22350/180507186-88b80a73-a40d-498c-8154-2f0665e121f9.png)

**Comment by alexr00** [comment]
We should disable one if the other is checked.
