### ISSUE TITLE
UX is not that nice for viewing files in some repos

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#376]
This depends on the repo but for VS Code the extension is pretty bad as displaying the files. This screenshot shows that for this PR I don't know what files are and opt to click each of the files to discover what they are (hover takes too long):

<img width="397" alt="screen shot 2018-09-08 at 12 10 35 pm" src="https://user-images.githubusercontent.com/2193314/45257771-89818800-b360-11e8-955a-27fd2cb1f169.png">

Note that this is after double clicking the sash which is meant to set the viewlet to the "optimal" size.

The viewlet takes almost half the width of my macbook's monitor to show the files fully:

<img width="548" alt="screen shot 2018-09-08 at 12 13 48 pm" src="https://user-images.githubusercontent.com/2193314/45257795-b6359f80-b360-11e8-8b26-23fb08845269.png">

This is how that problem was solved for disambiguating tabs:

<img width="502" alt="screen shot 2018-09-08 at 12 16 48 pm" src="https://user-images.githubusercontent.com/2193314/45257815-16c4dc80-b361-11e8-8ff5-c57630a0ff02.png">

I'm not sure what the best way to improve this is as putting the file names at the start would degrade the experience when the PR has mostly short paths, due to the folders not being lined up.

**Comment by arjun27** [comment]
Have you considered a nested tree for the changed files? Like a subset of the explorer files tree, showing only the changed files. It would expand the list vertically, but make it easier to fit the entire thing horizontally.

I build [rubberduck](https://www.rubberduck.io), a browser extension for GitHub pull requests, and I've gotten consistent feedback that the nested view gives an instant overview of the changes ([case in point](https://twitter.com/rstankov/status/1031802679444615170)). One downside is that it needs additional clicks to expand a deeply nested file, but I've found that to be a worthwhile tradeoff (and can auto-expand multiple levels maybe?)

![tyatuw0qii](https://user-images.githubusercontent.com/284612/45257916-87a0de80-b3cb-11e8-94a1-49938360d815.gif)

**Comment by NavyAdmiral** [comment]
As an idea, what do you think about viewing the file extension icons on the left side and badges (`M for merged`) on the right side?

**Comment by Tyriar** [comment]
Thinking about this more and reading the comments we should probably try and match what we do in the explorer and search. Search for example will show the file name first and the folder slightly greyed out:

<img width="414" alt="screen shot 2018-09-08 at 1 14 05 pm" src="https://user-images.githubusercontent.com/2193314/45258251-55f72b80-b369-11e8-8fc6-450526cb0ac6.png">

The icon could be on the right could also help and then we could move the change state over the the right just like in the explorer:

<img width="400" alt="screen shot 2018-09-08 at 1 16 51 pm" src="https://user-images.githubusercontent.com/2193314/45258260-77581780-b369-11e8-9ab9-e1722f2b16f2.png">

I'm sure this would need more ext API to get right.

**Comment by RMacfarlane** [comment]
The tree items have already been changed to display the file name, and then the full path as a description after it the same way the explorer and search show.

Additionally, we just merged a PR that will add a setting for toggling between a tree and a flat view of these files - by default it's set to tree.
