### ISSUE TITLE
Test view sizes of Create and Active PR views

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#3762]
Refs: https://github.com/microsoft/vscode-pull-request-github/issues/3227

- [x] anyOS @sbatten
- [x] anyOS @karrtikr

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode-pull-request-github/issues/new?body=Testing+%233762%0A%0A&assignees=alexr00)

---

You will need the builds of VS Code and GitHub Pull Requests and Issues from 26 July or later.

1. Start VS Code with a fresh `--user-data-dir`. (from your terminal, `code-insiders --user-data-dir path_to_the_folder_you_want_to_use`).
2. Open a folder with a GitHub repository.
3. Checkout a topic branch and make a commit.
4. Run the "Create Pull Request" command.
5. A view container with 2 views will show: Create Pull Request and Compare Changes. Verify that the Create Pull Request view is two times the size of the Compare Changes view.
6. Finish creating the pull request, or checkout an existing pull request.
7. Open the "GitHub Pull Request" view container from the activity bar. There will be 2 views: a tree view on top and a webview on the bottom. Verify that the view that contains the tree takes up 2/3 of the view container and that the webview takes up 1/3 of the view container.

**Comment by karrtikr** [comment]
> Run the "Create Pull Request" command.

I don't see such a command:

![image](https://user-images.githubusercontent.com/13199757/181118688-63004e4a-3d5a-4c25-a962-7187020ebf29.png)
