### ISSUE TITLE
Test Changes Since Last Review

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode-pull-request-github#3763]
Refs:  #363 

- [ ] anyOS @mjbvz
- [x] anyOS @rchiodo

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode-pull-request-github/issues/new?body=Testing+%233763%0A%0A&assignees=benibenj)

---

This feature adds a button in the tree view of Pull Requests which have a change since the viewer himself has reviewed the PR. When switching into that mode for the PR, it will display only the new changes since the viewer's review.

1. Install the pre-release build of GitHub Pull Requests and Issues with Insiders
2. Open a folder containing a GitHub repository in VS Code
3. Review somebody else's Pull Request (with the extension or GitHub)
4. Get somebody else to commit to that Pull Request
5. Checkout the branch belonging to the PR
6. An Icon should appear on the right of the PR node in the local PR view. 
7. Press on the button. The icon of that button should change.
8. The files below the pull request should only display the files which were affected by the changes after the last review.
9. Press on the diff file. It should only display the changes since the review and not all changes.
10. Press on the icon as before (Step 7 but different Icon). The Icon should switch back and the contents of the open diff file should close and reopen with all changes from the PR (not only the ones since the review)
11. Repeat from Step 5 but checkout a different branch (not belonging to the PR) and test it on the All Pull Requests view. The button will be located on the right of the Description node of that PR.

**Comment by mjbvz** [comment]
I'm confused about step 6. Where should I see the button in the view? After checking out the branch, this is what I see


<img width="1558" alt="Screen Shot 2022-07-26 at 1 57 20 PM" src="https://user-images.githubusercontent.com/12821956/181110497-74128809-3522-44b7-a670-424084fbc98a.png">


Here's the PR I was using to test (note I'm using my two GitHub accounts so look at the names, not the images): https://github.com/mattbierner/vscode-test-pr/pull/1

**Comment by benibenj** [comment]
You should be seeing the icon on the right of the "testing"
 node when hovering over it
![Screenshot (4)](https://user-images.githubusercontent.com/44439583/181114174-ae5d9879-339a-4a71-b593-1e2792e270e1.png)

**Comment by mjbvz** [comment]
@benibenj  Ah thanks! I think the feature works as expected but had some UX feedback:

- The button is not very discoverable since it only shows on hover

- I feel there should be a clear indication of of which mode I am in (all changes vs changes since last review). Is there somewhere in the UX this could be shown besides the button?
