### ISSUE TITLE
View suggested changes

### ISSUE THREAD

**Issue by matthewvalentine** [microsoft/vscode-pull-request-github#3768]
Issue Type: <b>Bug</b>

When you are in the main file view, looking at comments, and one of them has a suggested change in it, only the first so-many characters of the change can actually be read. It displays on a single line without any wrapping, and there is no way to scroll to the right to view more of the change.

When you go to the PR description view, suggestions render correctly. So this is an issue only with the file view, and the information necessary to display it correctly is obviously already available (since it is correct in the PR view.)

I know that full support of Suggestions is a separate open ticket: https://github.com/microsoft/vscode-pull-request-github/issues/603
I believe this should be a separate ticket because it is not a request for full support, but just viewing, and it's something that is already implemented elsewhere in the extension (in the PR view but not the file view.)

Extension version: 0.46.1
VS Code version: Code 1.69.2 (Universal) (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:12:57.074Z)
OS version: Darwin x64 21.5.0
Restricted Mode: No

**Comment by alexr00** [comment]
@matthewvalentine can you share a screenshot? I don't see a way that we display suggestions in the file/editor comments. I only see the suggestion shown in the PR description view.

**Comment by alexr00** [comment]
https://github.com/microsoft/vscode-pull-request-github/issues/603 is now planned for this month (or maybe next month). Will tackle as part of that.
