### ISSUE TITLE
Description editor opens empty

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode-pull-request-github#377]
Please see the screenshot below. This happens to me whenever I click a Description node for any Pull Request.

I´m on Windows, Version: 1.28.0-insider (user setup)
Commit: a3f9f2e7240106aeec2f1d4bc03d7876bd42e2e4
Date: 2018-09-07T05:20:29.346Z

![image](https://user-images.githubusercontent.com/172399/45280237-e5b8e900-b4d3-11e8-87be-df59903224d6.png)

**Comment by RMacfarlane** [comment]
@egamma Can you check the console for errors? This is with version 0.1.1 of the extension?

**Comment by egamma** [comment]
I cannot reproduce with 0.1.2, closing.
