### ISSUE TITLE
Need better description for "Failed to create a milestone" scenarios

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode-pull-request-github#3775]
Testing #3764

Try to create an existing closed milestone such as "Backlog"

The creation will fail and there is a notification saying "Failed to create a milestone".

GitHub shows a "Title has already been taken" error message for this case

**Comment by gregvanl** [comment]
Interestingly, the title too long case does append the explanation to the notification text

**Comment by benibenj** [comment]
Validation error messages are wrongly parsed and can lead to not displaying them at all.
