### ISSUE TITLE
Branch protection is shown as failed test

### ISSUE THREAD

**Issue by cbrnr** [microsoft/vscode-pull-request-github#3777]
- Extension version: v0.46.1
- VSCode Version: 1.69.2
- OS: macOS

Steps to Reproduce:

1. Open a PR in a repository with branch protection
2. While tests are still running, branch protection is shown as a failed test

<img width="686" alt="Screen Shot 2022-07-27 at 09 39 10" src="https://user-images.githubusercontent.com/4377312/181189985-7d9a118e-8336-488d-a8d7-a80420ee3f86.png">

I think this is confusing, and because branch protection is already shown separately, it should not also show up as a failed test.

**Comment by ssoworld** [comment]
I don't know about PRs within same repo - but this is definitely true for PRs from forks.

**Comment by alexr00** [comment]
We show it in the checks because branch protection could include an approving review, which is not otherwise shown (and the GitHub API doesn't appear to have a way to tell that it's an approving review that's missing, only that there's still something missing).

**Comment by alexr00** [comment]
Tried to make it a little clearer by changing the wording and moving it to the end:

![image](https://user-images.githubusercontent.com/38270282/208707276-e3f24197-b7c3-4286-989b-4f295da42f13.png)

**Comment by cbrnr** [comment]
That's better I think, although it's the "X" status that's confusing. It looks like a failed test, and maybe it could be replaced with that slashed circle icon?
