### ISSUE TITLE
Pull request notification got permanently stuck

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-pull-request-github#3784]
Testing #3761

Mac
1. Opened an existing cloned repo.
2. There were already a few changes in it that weren't committed to master.
3. Created a new branch
4. Opened the Create Pull Request view. All dropdowns were filled correctly.
5. Pressed the Create button to create the pull request.

I was prompted along the way to publish the new branch created at step 3, then commit my changes (a couple prompts for this). Finally it gave me the Creating Pull Request notification at the bottom right, but it never completes. It's been 5 minutes.

<img width="596" alt="image" src="https://user-images.githubusercontent.com/11685408/181367627-333e0430-d03f-4b08-a300-ee2b0ceb9a5e.png">

Note that I don't believe that I was logged into github prior to trying to create the pull request. 

I've sent the log directly to you as it's rather large.

**Comment by lagamura** [comment]
I also faced the same problem. The bug occurs when you don't fill the **commit Message** description.

**Comment by joyceerhl** [comment]
Fix isn't out in latest pre-release yet (v0.47.2022072809), so I still repro:

![image](https://user-images.githubusercontent.com/30305945/181578361-11aa8539-89f0-43dd-ae14-2eff0f69fb54.png)
