### ISSUE TITLE
Unify drop-down buttons

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode-pull-request-github#3785]
The pull request extension also has a drop down button, but it works a bit different than the commit drop down button. Maybe it makes sense to unify these two ideas?

![image](https://user-images.githubusercontent.com/2931520/181295639-7acdc072-00a0-419f-b930-26e9407b9393.png)

**Comment by alexr00** [comment]
I'm fine with bringing the GHPRI button into consistency with the way this button works in VS Code core/the commit button.

**Comment by hediet** [comment]
I like about the GHPRI button that it remembers the last choice!

**Comment by lszomoru** [comment]
@hediet, it's on the plan for next milestone. Stay tuned...

**Comment by alexr00** [comment]
I will keep remembering the last choice in GHPRI, but I will also make it only 1 click to change choice as the git button is.

**Comment by daviddossett** [comment]
I'll chat w/ @hawkticehurst about the split button today. The webview toolkit is built on top of [FAST](https://github.com/microsoft/fast/) which doesn't yet provide a split button base component out of the box. Nitty gritty details aside, we'll see if there's a workaround and will report back.

**Comment by hawkticehurst** [comment]
Catching up on old issues and the quick update about split button is now that a context menu API is being finalized for use in webviews the possibility to create our own split button is really opening up.

Assuming that officially lands sooner than later I'd love to ship a split button before the end of this year.

**Comment by alexr00** [comment]
This has been fixed!
