### ISSUE TITLE
Is there any way to show build status in the PR list?

### ISSUE THREAD

**Issue by valyagolev** [microsoft/vscode-pull-request-github#3788]
It'd be great to be able to see the build status in the PR list. I'm going to try to do it with filters, but an icon next to a PR would be amazing. Perhaps I could try to contribute something like this, if it's ok and not an intentionally omitted feature.

**Comment by alexr00** [comment]
@valyagolev this seems like this feature could result in a big performance hit. It might be expensive to fetch the build status of each pr in the list.

**Comment by valyagolev** [comment]
if github API doesn’t return it with the list of PR, then yes, I suppose. In this case one might only enable it for a particular filter, e.g. for their own PRs

**Comment by alexr00** [comment]
We now show the PR checks status in the PRs list.
