### ISSUE TITLE
Allow marking of folders (i.e. all its files recursive) as viewed

### ISSUE THREAD

**Issue by CombeeMike** [microsoft/vscode-pull-request-github#3799]
I often have to review large PRs which include both, server & client code, where I'm only interested in the client code. In such situations, I always start by marking all server files as viewed which can be very tedious when there are many files involved.

-> This would be much easier if I could just mark a whole directory as viewed including all files recursively

I know that I could just collapse the folder and ignore it in the review but my overall workflow often benefits from explicitly marking those files as reviewed. E.g. I occasionally have to switch between VSCode and the GitHub PR page during PRs, where I get a better overview if the files I'm not interested in are marked as viewed etc.

This, in combination with the ability to hide viewed files (#3330) would improve my workflow tremendously.

**Comment by alexr00** [comment]
Related to https://github.com/microsoft/vscode-pull-request-github/issues/3274

**Comment by rzhao271** [comment]
Isn't this covered by https://github.com/microsoft/vscode-pull-request-github/issues/3988?

**Comment by alexr00** [comment]
yes, this is accomplished through #3988.
