### ISSUE TITLE
Pressing `Comment` button without typing anything in the comment box spits error in the console

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode-pull-request-github#38]
![image](https://user-images.githubusercontent.com/22350/41918818-68d9a200-795d-11e8-8a2c-e473f1f7e775.png)

**Comment by RMacfarlane** [comment]
Fixed with https://github.com/Microsoft/vscode/commit/3027ed94de849c13dc6488eeed988dd0eb837b31
