### ISSUE TITLE
HTML from code gets rendered in VS Code

### ISSUE THREAD

**Issue by JonnyBurger** [Microsoft/vscode-pull-request-github#380]
Above you can see how the PR looks in Github, Below you can see how it looks in VS Code..
Surprisingly, a button gets rendered 😱 

![bildschirmfoto 2018-09-10 um 17 54 23](https://user-images.githubusercontent.com/1629785/45309160-5e936180-b523-11e8-8d53-f12793e3e338.png)

The HTML in question: 
`
<button *ngIf="isEditingAllowed" class="btn btn-primary big" [disabled]="projectForm.invalid"
              (click)="save(projectForm)">Save changes</button>
`

**Comment by rebornix** [comment]
Good catch, we should add filters for markdown renderer.

**Comment by connorshea** [comment]
See also #322, I have another example of this there :)
