### ISSUE TITLE
Extension doesn't understand 	`remote = .`

### ISSUE THREAD

**Issue by seivan** [microsoft/vscode-pull-request-github#3800]
- Extension version: `v0.46.1`
- VSCode Version: `Version: 1.69.2`
- OS: `macOS 11.6.8 (Big Sur)`

Steps to Reproduce:

1. Switch to a new branch from, say,  `develop `
- `git switch -c feature/something`

2. under `.git/config` set `remote` to  `.` 
-  `cat .git/config`
```
[branch "feature/something"]
	remote = .
	merge = refs/heads/develop
```

The extension should understand valid git config options and arguments. 

Edit: I am sure some gitconfig I got is setting remote to "." which probably means current. 
** might ** be this setting 

```
[push]
  default = current
```

But not sure.

**Comment by alexr00** [comment]
Can you share the error you see from the extension?
