### ISSUE TITLE
Show PRs of original repository from private fork

### ISSUE THREAD

**Issue by GregoryLundberg** [microsoft/vscode-pull-request-github#381]
- Extension version: 0.1.1
- VSCode Version: 1.27.1
- OS: Arch Linux, Windows 10

Steps to Reproduce:

1. Install the extension

This extension makes false assumptions about the workflow. If you use a private fork it only shows the PRs on your private fork. Of course there are none because they're all on the master repository.

**Comment by RMacfarlane** [comment]
@GregoryLundberg This is by design - the extension has information about what remotes the current repository has. To view PRs of the upstream repository on the fork, please add a remote that tracks the upstream

**Comment by RMacfarlane** [comment]
Actually, I suppose a possible behavior could be for the extension to try to detect that the repo is a fork and automatically add the tracking remote. Not sure if that's invasive or expected though.

**Comment by GregoryLundberg** [comment]
I have a remote which tracks the upstream.

'master' -> github personal fork
'upstream' -> github project master repo

There are generally a few dozen PRs on the 'upstream' project. But when I ask the VSCode extension it (correctly) says my personal, private fork on github has no PRs. How do I tell it to look at 'upstream' for the PRs?

**Comment by RMacfarlane** [comment]
Is this with the latest version of the extension, 0.1.6?

The extension should automatically fetch for all of the remotes - it should fetch from each remote a page at a time until there are no more pages, and then move to the next, only making requests when you click "Load more".

Could you share what format of the 'upstream' remote looks like? I'm wondering if we're failing to parse it

**Comment by GregoryLundberg** [comment]
OK, first off, it does not appear that your extension is actually signing into  GitHub. I click the "signin" a web page appears, I confirm, and it says it was successful. But when I check VSCode it still says it wants to sign in and when I check my GH profile it says the OATH was never used. Regenerated and same result.

I don't know what you're asking for. I'll attack my .git/config but it doesn't look at all different from what I'd expect. I'm thinking it's that it cannot successfully do the OATH2 song and dance which is the real issue.

Yes, 0.1.6 on VSCode 1.27.2 on Arch Linux (updated each morning).

**Comment by GregoryLundberg** [comment]
[lundberg@lundberg-arch .git]$ cat config 
[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
[remote "origin"]
        url = https://github.com/GregoryLundberg/wesnoth                                                                          
        fetch = +refs/heads/*:refs/remotes/origin/*                                                                               
[branch "master"]                                                                                                                 
        remote = origin                                                                                                           
        merge = refs/heads/master                                                                                                 
[remote "upstream"]                                                                                                               
        url = https://github.com/wesnoth/wesnoth.git                                                                              
        fetch = +refs/heads/*:refs/remotes/upstream/*
[commit]
        gpgsign = true
[branch "1.14"]
        remote = origin
        merge = refs/heads/1.14

**Comment by GregoryLundberg** [comment]
I just built the entire repo again on a Windows 10 box and it works fine. So it's either something about my Linux box or Linux, in general. Windows 10 was able to sign in to GitHub and showed all the "upstream" PRs just fine.

**Comment by RMacfarlane** [comment]
I'm clearing out some old issue and am going to go ahead and close this. The extension should now show PRs based on the `githubPullRequests.remotes` setting, which by default will look for "origin" and "upstream" remotes
