### ISSUE TITLE
GitHub Notifications UX

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode-pull-request-github#3814]
For the GitHub notifications we need an indication of a notification belonging to a PR in addition to the highlighted color.

Here are two examples for right aligned notification badges:

![notifications1](https://user-images.githubusercontent.com/44439583/182659622-24f724c0-779b-4ae3-9346-f3736c612f54.png)
![notifications2](https://user-images.githubusercontent.com/44439583/182659624-e3bfa5cd-829a-4403-b3ec-c12cba286e83.png)

Another option is having the icon in the front (We currently also have the checkmark in the front to indicate the checked out PR):

![notifications3](https://user-images.githubusercontent.com/44439583/182662024-f76d7fcf-d34f-44ec-b3b7-172ae5bbb2a6.png)

**Comment by daviddossett** [comment]
Talked about this at the Redmond standup:

This version received positive feedback but there was some concern that it would look too similar to the git decorations.
![CleanShot 2022-08-04 at 16 32 56](https://user-images.githubusercontent.com/25163139/182972573-ab928f03-b007-4b03-a18d-c9be82c2e9a4.gif)

This one maybe feels a bit noisier inlined but it could help clarify that it isn't related to git:
![CleanShot 2022-08-04 at 16 33 09](https://user-images.githubusercontent.com/25163139/182972713-40d4d7d3-c745-4fd3-b7a0-13a5a6bab803.gif)

 Also wanted to understand if I'm interpreting the idea correctly—would we show a dot on both the PR title and the actual file with the comment? And then both would clear when the last file with a unread notification was clicked?

**Comment by daviddossett** [comment]
Oh ok, that simplifies things. Let's give that a try then!

**Comment by benibenj** [comment]
Close with #3839
