### ISSUE TITLE
Cannot save comments (error about commentsResolvedState)

### ISSUE THREAD

**Issue by twz123** [microsoft/vscode-pull-request-github#3823]
Issue Type: <b>Bug</b>

I noticed that any comments I added to Pull Requests didn't show up in GitHub. I checked the plugin details page and found this:

> Uncaught Errors (1)
Extension 'GitHub.vscode-pull-request-github' CANNOT use API proposal: commentsResolvedState. Its package.json#enabledApiProposals-property declares: tokenInformation but NOT commentsResolvedState. The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api GitHub.vscode-pull-request-github

I checked the package.json, and it looks right...

```console
❯ jq .enabledApiProposals ~/.vscode-oss/extensions/GitHub.vscode-pull-request-github/package.json
[
  "tokenInformation",
  "commentsResolvedState"
]
```

Extension version: 0.46.1
VS Code version: VSCodium 1.69.1 (b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a, 2022-07-13T00:42:29.084Z)
OS version: Linux x64 5.15.56
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 PRO 4750U with Radeon Graphics (16 x 2779)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|2, 1, 1|
|Memory (System)|14.87GB (2.05GB free)|
|Process Argv|--ms-enable-electron-run-as-node --enable-features=UseOzonePlatform --ozone-platform=wayland .|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|sway|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|wayland|
</details>

**Comment by alexr00** [comment]
@twz123 I think this is a codium specific issue. 

This extension does use proposed API so that we can test out the API proposal and take advantage of new features (in this case, special UX treatment for resolved vs. unresolved comments). In the VS Code stable and insiders builds, we allow this extension to use that proposed API. It seems that codium doesn't also do this. I would recommend that you file an issue with codium to ask them to allow this extension to use proposed API.
