### ISSUE TITLE
Support older GitHub Enterprise without workflow scope

### ISSUE THREAD

**Issue by edemaine** [microsoft/vscode-pull-request-github#3828]
My institution is running an old installation of GitHub Enterprise that doesn't have the `workflow` scope, so I can't create a Personal Access Token with this scope. Is it possible to work around this limitation?

Related issue: #3731 (documenting need for `workflow` scope)

**Comment by alexr00** [comment]
@edemaine I will do some investigation of how we can better support GitHub Enterprise later this year. I will make sure to include this scope in my investigation. Do you happen to know the version of your GitHub Enterprise installation?

**Comment by edemaine** [comment]
The docs link at the bottom is to https://docs.github.com/enterprise/3.0 so I'd guess it's 3.0, which I see was discontinued. 😕

**Comment by alexr00** [comment]
@edemaine thank you. It looks like 3.0 does have the workflow scope: https://docs.github.com/en/enterprise-server@3.0/developers/apps/building-oauth-apps/scopes-for-oauth-apps#available-scopes

Is `workflow` not available for you when you create a PAT?

It does seem like `workflow` didn't exist in 2.22 though, so maybe it isn't available in the UI for 3.0.

**Comment by edemaine** [comment]
It's definitely not a checkbox in the creation UI. Is there a way to request it anyway, like manually submitting the form?

**Comment by alexr00** [comment]
@edemaine thanks for confirming that `workflow` isn't in the UI and in general I appreciate the additional GitHub Enterprise details. I'm not aware of whether there's another way to request it, but knowing that this is a problem for some Enterprise users will help me frame my GitHub Enterprise work later this year.

**Comment by alexr00** [comment]
@edemaine would you be able to try out the latest VS Code Insiders and the latest pre-release version of this extension? With that combination there is no PAT required.

**Comment by edemaine** [comment]
Seems to work great! Much friendlier way to log in.
