### ISSUE TITLE
Fails to open PR's description or list PR's files on GitHub Enterprise

### ISSUE THREAD

**Issue by obambrough** [microsoft/vscode-pull-request-github#3829]
- Extension version: v0.48.0
- VSCode Version: v1.70.0
- OS: MacOS 12.4
- Github version: GHE 3.1

NOTE: Server is Github Enterprise 3.1
NOTE: This works with Pull Request v0.46.1, the issue started with v0.48.0

Steps to Reproduce:

1. From the 'Pull Requests' side panel expand the 'All Open' list
2. Expand any PR node, nothing is shown after expanding except for the PR that matches the branch you have checked out
3. Expand the PR matching the checked out branch
4. Only the description option is available, it doesn't show all the files from the PR
5. Click on the description to open it. It attempts to open the PR, in the main editor is shows 'Loading...'
6. The 'Github Pull Request' log contains: `[Info] Review> Error: GraphQL error: Field 'viewerLatestReview' doesn't exist on type 'PullRequest'`

**Comment by benibenj** [comment]
Thanks for bringing this up @obambrough. It looks like you are using a rather old version of GHE which does not support one of our newest features. Nevertheless, we created a fix for this case which should be available in the Pre-release version of the extension today and will be available in the released version by the end of the week.

**Comment by alexr00** [comment]
@obambrough if you are able to try out the [pre-release](https://github.com/microsoft/vscode-pull-request-github/wiki/Pre-release-Build) version (starting from version `v0.49.2022080912`) and confirm that it solves this issue that would help use get the stable version ready to release!

**Comment by obambrough** [comment]
Awesome, thank you! I installed v0.49.2022080912 and it works. I can open the description successfully and files are listed.

**Comment by alexr00** [comment]
@obambrough thank you for verifying that the fix works!
