### ISSUE TITLE
Authentication endpoint is not obviously connected to GH

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode-pull-request-github#383]
Issue Type: <b>Bug</b>

See the following screenshot. Neither the url of the auth endpoint nor the [organization](https://github.com/editor-tools) are obviously connected to GH. It would be better if the auth endpoint would be within `github.com`.  

![screen shot 2018-09-10 at 9 12 03 am](https://user-images.githubusercontent.com/4674940/45310536-5b748300-b4db-11e8-9954-ab06980be308.png)

Extension version: 0.1.1
VS Code version: Code - Insiders 1.28.0-insider (96854113091424c07b28ba84b82b75a88b8455cb, 2018-09-10T05:12:30.432Z)
OS version: Darwin x64 16.7.0

**Comment by shana** [comment]
The GitHub for VSCode oauth app has been moved to the GitHub org, so the owner will now show up as `github` and it will show `Owned and operated by GitHub` at the bottom. I can't fix the redirect url right now (working on that), but hopefully this will help.

**Comment by auchenberg** [comment]
Re-opening to keep track of the move to a Github-owned domain.

**Comment by shana** [comment]
4cf3870b656e91908c4fee8766ff6402f77664c7 switches the authentication server domain to the new github.com domain. This is the client side change needed for this fix.

The server side fix (the url being shown in the permissions page, as seen on the screenshot) will be done today, so once the client side fix is live and everyone is updated, both sides will match.

Until then, some authentication transactions might show the herokuapp.com url at some point, but hopefully things will propagate to everyone quickly enough to not be confusing to too many users.

**Comment by shana** [comment]
![auth-step2 2](https://user-images.githubusercontent.com/310137/45762186-1a444780-bc2e-11e8-9ab8-4797ce80f53c.PNG)
