### ISSUE TITLE
Unable to install extension 'github.vscode-pull-request-github' as it is not compatible with VS Code '1.69.2'

### ISSUE THREAD

**Issue by cerilawley** [microsoft/vscode-pull-request-github#3833]
- Extension version: 0.47.2022080211 & 0.49.2022080809
- VSCode Version: 1.69.2
- OS: Windows 10 Pro  21H2     build no: 19044.1826

Steps to Reproduce:

1. Download extension
2. Install from vsix

**Comment by alexr00** [comment]
This is intentional. We now rely on changes in 1.70 for the extension to work.
