### ISSUE TITLE
Pull Requests not loading

### ISSUE THREAD

**Issue by hornta** [microsoft/vscode-pull-request-github#3837]
Just came back from vacation and now my GitHub Issues & Pull Request that I used to use daily doesn't work anymore. I also get the same appearance with the pre-release version.

![image](https://user-images.githubusercontent.com/4553604/183837818-b6734f35-7d7d-4fb3-852c-06807bd3b7ed.png)

I was really dependent on this extension so I gladly take help figuring out why it is like this. I tried to re-install the extension but that don't help.

No special settings are configured for this extension neither.

- Extension version: 0.48.0
- VSCode Version: 1.70.0
- OS: Win10

**Comment by benibenj** [comment]
Are you using GitHub Enterprise @hornta? In that case the problem has been discussed in this issue #3831. It should be fixed in the pre-release version of the extension and will be in the released version by the end of the week. Plese let us know if the pre-released version works for you or not. If it still does not work, please provide us with the output of the extension.

**Comment by hornta** [comment]
We are using GitHub teams, not enterprise. It's a private repository.

**Comment by benibenj** [comment]
Could you provide us with the Output of the GitHub Pull Requests extension

**Comment by hornta** [comment]
```
[Info] Registering git provider
[Info] Looking for git repository
[Info] Found 1 repositories during activation
[Info] Git repository found, initializing review manager and pr tree view.
[Info] Review> Validate state in progress
[Info] Review> Validating state...
[Info] No remotes found. The following remotes are missing: 
[Info] No GitHub remotes found
[Info] Review> no matching pull request metadata found for current branch hornta/1728
[Info] Review> no matching pull request metadata found on GitHub for current branch hornta/1728
[Info] PullRequestTree> Removing PR #undefined from tree
```

But I do have a remote:
![image](https://user-images.githubusercontent.com/4553604/183932850-3633feed-48d6-424c-b5e1-b0dddcfd505e.png)

**Comment by alexr00** [comment]
@hornta can you share the value of the setting `githubPullRequests.remotes`?

**Comment by hornta** [comment]
@alexr00 Turns out this list was empty so I clicked the cog and chose "Reset setting" and now I got some remotes in this list sp now the extension is working again :) Thanks

![image](https://user-images.githubusercontent.com/4553604/184084512-1f0dbcc6-8e52-44b9-84be-4002dc8c141a.png)
