### ISSUE TITLE
Description empty in PR overview after creation

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode-pull-request-github#3838]
When creating a PR with a description, the topmost comment node in the PR overview should contain the description but is empty. After reloading the text appears.

![Recording 2022-08-10 at 14 23 39](https://user-images.githubusercontent.com/44439583/183900244-bb12cc47-b44c-41e9-8308-46a704b2fea2.gif)

**Comment by alexr00** [comment]
Tried to repro on 2 different machines (faster and slower) to see if it's a timing issue, but no luck. I always get the expected description after PR creation. Will try again next debt week.

**Comment by roblourens** [comment]
Something special I have to do to make sure I hit the right case?

**Comment by alexr00** [comment]
The problem occurred when the Pull Requests view refreshed around the same time that the PR was created. If the following works, then this is verified:
1. Create a PR
2. Immediately after creating, switch to the Pull Requests tree view and start refreshing it repeatedly until the PR overview shows.
3. Verify that the description in the PR overview is not empty.
