### ISSUE TITLE
Can't authenticate with GitHub, never provided prompt

### ISSUE THREAD

**Issue by dwalleck** [Microsoft/vscode-pull-request-github#384]
- Extension version: 0.1.1
- VSCode Version: 1.27.1
- OS: Windows 10 17134.228

Steps to Reproduce:

1. Open VS Code
2. Pop up appears that I need to sign in to use the Pull Requests functionality with a sign in button
3. Click the Sign In button. Another pop up immediately appears stating that an error occurred signing in to GitHub.com with a "Try Again?" button. Clicking the "Try Again?" button repeats the same flow

Trying to interact with the Pull Requests window creates more pop-ups about not being authenticated. I'm never shown a panel to provide credentials, so I'm not sure how to debug this further.

**Comment by rebornix** [comment]
@dwalleck can you please try opening Command Palette and search for `Sign in to GitHub` and see if that can work?

**Comment by dwalleck** [comment]
Thanks for the tip. I tried that and I get the same "Error signing in to github.com" pop up as well as a "Not authenticated" pop up.

**Comment by dwalleck** [comment]
Ah good, I knew there had to be output somewhere! Here's what I have in the GitHub Pull Requests log:

```
Looking for git repository
> git symbolic-ref --short HEAD
> git rev-parse task/ZAM-400
> git rev-parse --symbolic-full-name task/ZAM-400@{u}
> git rev-list --left-right task/ZAM-400...refs/remotes/origin/task/ZAM-400
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
Git repository found, initializing review manager and pr tree view.
> git config --local --get remote.origin.github-pr-remote
Error signing in to github.com: undefined
Unable to resolve remote: Error: Not authenticated.
> git config --local --get branch.task/ZAM-400.github-pr-owner-number
Review> no matching pull request metadata found for current branch task/ZAM-400
> git branch
> git config --local --get remote.origin.github-pr-remote
> git config --local --get remote.origin.github-pr-remote
> git config --local --get remote.origin.github-pr-remote
> git config --local --get remote.origin.github-pr-remote
> git config --local --get branch.feature/***.github-pr-owner-number
> git config --local --get branch.master.github-pr-owner-number
> git config --local --get branch.task/ZAM-400.github-pr-owner-number
GitHubRepository> Fetching all pull requests failed: Error: Not authenticated.
GitHubRepository> Fetching all pull requests failed: Error: Not authenticated.
GitHubRepository> Fetching all pull requests failed: Error: Not authenticated.
GitHubRepository> Fetching all pull requests failed: Error: Not authenticated.
> git config --local --get branch.task/ZAM-400.github-pr-owner-number
> git config --local --get branch.task/ZAM-400.github-pr-owner-number
Error signing in to github.com: undefined
Error signing in to github.com: undefined
Error signing in to github.com: undefined
Error signing in to github.com: undefined
Error signing in to github.com: undefined
Error signing in to github.com: undefined
> git config --local --get branch.task/ZAM-400.github-pr-owner-number
```

I'm not currently on a VPN and I don't think my firewall rules have changed beyond the Windows standard defaults (but I could always be wrong about that!) I'll try manually creating a token as you suggested.

**Comment by dwalleck** [comment]
Minor update, but manually adding my credentials did work. Thanks! I did double check my firewall settings and just to be safe, I added VS Code to the allow list but I was still seeing the same error.

**Comment by shana** [comment]
Weird. This is either the initial connection for the authentication failing, or vscode being unable to open the web browser. I don't think I have enough detailed logging in place to track this down right now unfortunately :-/
Glad to hear it's working now, let us know if it breaks.

**Comment by lumaxis** [comment]
I believe I have the same issue, here's my log output:

```
Looking for git repository
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
Git repository found, initializing review manager and pr tree view.
> git config --local --get remote.origin.github-pr-remote
Error signing in to github.com: undefined
```

Will try adding the credentials manually next!

**Comment by wesbland** [comment]
I'm seeing the same problem. I *am* behind a proxy in my office, which of course makes things more difficult to debug. I have the usual environment variables set to help (`http_proxy`, `https_proxy`, etc.), but I also have Proxifier available to make more tweaks if necessary.

Mac OS - 10.13.6
VS Code - 1.27.1
Extension Version - 0.1.1

**Comment by wesbland** [comment]
I did a little more digging for my problem with the github.com connection with Little Snitch. It looks like something in the "Code Helper" app isn't honoring the proxy settings and is connecting to `dc.services.visualstudio.com` directly. When I added a proxy rule to force this to go through my company proxy, I got a normal prompt to sign in to GitHub in Safari and everything was fine.

Seems like something needs to get fixed with how the helper process is detecting proxy settings.

**Comment by lumaxis** [comment]
@shana I believe this might be happening because our GitHub Enterprise instance does not have rate limiting enabled which makes `GET /api/v3/rate_limit` return a `404` error with this error:
```json
{
    "message": "Rate limiting is not enabled.",
    "documentation_url": "https://developer.github.com/enterprise/2.13/v3/rate_limit/#get-your-current-rate-limit-status"
}
```

That API is used to validate the provided credentials on start-up and the validation fails because of the `404`:
https://github.com/Microsoft/vscode-pull-request-github/blob/cd5f1dd04e90655409765ee973ac4db611392431/src/authentication/githubServer.ts#L210

If the credentials for the request however were actually bad, GHE would respond with a `401` error and
```json
{
    "message": "Bad credentials",
    "documentation_url": "https://developer.github.com/enterprise/2.13/v3"
}
```

I just opened https://github.com/Microsoft/vscode-pull-request-github/pull/397 with a suggested fix that locally made the extension work for me ✨

**Comment by steven-foster** [comment]
Manually adding my credentials doesn't seem to work, on version 0.1.2

As soon as I hit save, I get the original popup to sign in to github and the settings entry updates itself to just have the "host" field.

**Comment by bitfield** [comment]
Same problem here. When I click 'Sign In', I expect Code to open a web browser to authenticate to GitHub, but nothing happens, and the 'Error signing in' flash message appears immediately.

Output:
```
> git config --local --get branch.master.github-pr-owner-number
Error signing in to github.com: undefined
```

No proxies, no strange network setup, default browser is Chrome, and Code has no problem opening it when Cmd-clicking on links, for example.

**Comment by wesbland** [comment]
> @wesbland Thanks for the spelunking. It does look like your proxy is not being honored, not sure why :-/. dc.services.visualstudio.com is nothing related to the extension, that's the VSCode pinging the application insights service. That likely means that the problem with your proxy is affecting all of VSCode and not just the extension's connection.

You're right. I did end up adding a rule that just says that *everything* (that isn't to an internal site) from the "Code Helper" app should go through the proxy and I can see now that a bunch of `api.github.com` traffic is going there as well.

**Comment by masacuna** [comment]
Hi all I am stuck at the following point after following the instructions:
Make sure you have VSCode version 1.27.0 or higher
Download the extension from the marketplace
Reload VS Code after the installation (click the reload button next to the extension)

This point here I cannot see my repos.

Open your desired repo
Go to the SCM Viewlet, and you should see the GitHub Pull Request treeview.
A notification should appear asking you to sign in GitHub, follow the directions to authenticate
You should be good to go!

**Comment by RMacfarlane** [comment]
@masacuna I'm not sure what you mean by "I cannot see my repos" - are you not seeing the GitHub Pull Requests treeview? Note that on the first load, it will show up collapsed at the bottom of the viewlet. Please make sure that you have a folder open with a remote that points to GitHub. If you're still not seeing anything, what's the output of running `git remote -v` in this folder if you still see the problem?

**Comment by masacuna** [comment]
C:\Program Files\Git\cmd>git remote -v
fatal: not a git repository (or any of the parent directories): .git

**Comment by RMacfarlane** [comment]
@masacuna Let's move this conversation to a new issue since this is not related to the problem reported by this thread: https://github.com/Microsoft/vscode-pull-request-github/issues/456

**Comment by shana** [comment]
There’s a fix on master now for this, if you want to try it out.

@wesbland Looks like some extensions are shipping with old versions of the application insights package that kinda breaks http requests, and it might be causing your proxying issues too. #449 has more details, but try disabling all your extensions to see if that makes things work.

**Comment by wesbland** [comment]
@shana - It doesn't seem to have helped. I pretty much only had language extensions anyway since I just started VS Code because of this plugin.

**Comment by shana** [comment]
This issue should be fixed in release 0.1.5 as part of the fix for #449. Please reopen if you find that you still never get a prompt to sign in.

**Comment by cappslock** [comment]
Just got this error. This is the output:
```
[Info] Looking for git repository
[Info] Git repository found, initializing review manager and pr tree view.
[Info] Found GitHub remote
[Info] Error signing in to github.com: TypeError: Cannot set property 'text' of undefined
[Info] TypeError: Cannot set property 'text' of undefined
	at t.CredentialStore.willStartLogin (/Users/eric/.vscode/extensions/github.vscode-pull-request-github-0.8.0/media/extension.js:36:358635)
	at t.CredentialStore.<anonymous> (/Users/eric/.vscode/extensions/github.vscode-pull-request-github-0.8.0/media/extension.js:36:356720)
	at Generator.next (<anonymous>)
	at n (/Users/eric/.vscode/extensions/github.vscode-pull-request-github-0.8.0/media/extension.js:36:354529)
	at new Promise (<anonymous>)
	at n (/Users/eric/.vscode/extensions/github.vscode-pull-request-github-0.8.0/media/extension.js:36:354306)
	at t.CredentialStore.login (/Users/eric/.vscode/extensions/github.vscode-pull-request-github-0.8.0/media/extension.js:36:356515)
	at t.CredentialStore.<anonymous> (/Users/eric/.vscode/extensions/github.vscode-pull-request-github-0.8.0/media/extension.js:36:356396)
	at Generator.next (<anonymous>)
	at o (/Users/eric/.vscode/extensions/github.vscode-pull-request-github-0.8.0/media/extension.js:36:354362)
[Info] Error signing in to github.com: TypeError: Cannot set property 'text' of undefined
[Info] TypeError: Cannot set property 'text' of undefined
	at t.CredentialStore.willStartLogin (/Users/eric/.vscode/extensions/github.vscode-pull-request-github-0.8.0/media/extension.js:36:358635)
	at t.CredentialStore.<anonymous> (/Users/eric/.vscode/extensions/github.vscode-pull-request-github-0.8.0/media/extension.js:36:356720)
	at Generator.next (<anonymous>)
	at o (/Users/eric/.vscode/extensions/github.vscode-pull-request-github-0.8.0/media/extension.js:36:354362)
[Info] Error signing in to github.com: TypeError: Cannot set property 'text' of undefined
[Info] TypeError: Cannot set property 'text' of undefined
	at t.CredentialStore.willStartLogin (/Users/eric/.vscode/extensions/github.vscode-pull-request-github-0.8.0/media/extension.js:36:358635)
	at t.CredentialStore.<anonymous> (/Users/eric/.vscode/extensions/github.vscode-pull-request-github-0.8.0/media/extension.js:36:356720)
	at Generator.next (<anonymous>)
	at o (/Users/eric/.vscode/extensions/github.vscode-pull-request-github-0.8.0/media/extension.js:36:354362)
[Info] Error signing in to github.com: TypeError: Cannot set property 'text' of undefined
[Info] TypeError: Cannot set property 'text' of undefined
	at t.CredentialStore.willStartLogin (/Users/eric/.vscode/extensions/github.vscode-pull-request-github-0.8.0/media/extension.js:36:358635)
	at t.CredentialStore.<anonymous> (/Users/eric/.vscode/extensions/github.vscode-pull-request-github-0.8.0/media/extension.js:36:356720)
	at Generator.next (<anonymous>)
	at o (/Users/eric/.vscode/extensions/github.vscode-pull-request-github-0.8.0/media/extension.js:36:354362)
```

**Comment by harsh6768-svg** [comment]
Same issue not able to authenticate properly?

**Comment by DavraYoung** [comment]
Same issue in latest android studio(
`Failed to initiate the GitHub login process. Please try again.`

**Comment by pakchoily** [comment]
> 

`hosts` add ip for api.github.com
see https://github.com/github-community/community/discussions/16965#discussioncomment-2881851

**Comment by Zeni241** [comment]
Is it possible that authentication is not working in vscode due to "Github Desktop" app on same computer?🤪🤪

**Comment by zkldi** [comment]
For some reason, after loading this plugin today it's decided that github's url is `https://gh`. Has anyone else had this issue? There's no changes to my `settings.json`, nor any `/etc/hosts` changes.

This breaks the plugin and requires manual intervention.

```
023-03-14 10:46:35.038 [warning] GitHubServer> No response from host https://gh/repo/reponame request to https://gh/api/v3/rate_limit failed, reason: getaddrinfo ENOTFOUND gh
2023-03-14 10:46:35.038 [warning] No remotes found. The following remotes are missing: github, origin, upstream
```
