### ISSUE TITLE
Error: No view is registered with id ...

### ISSUE THREAD

**Issue by The-Plottwist** [microsoft/vscode-pull-request-github#3840]
Type: <b>Bug</b>

Hello, after updating my vscode to latest version, I have encountered with this issue (https://imgur.com/teGEuFF.png) from GitHub Pull Requests and Issues extension.

It was fine before the update.

Extension version: 0.48.0
VS Code version: Code - OSS 1.70.0 (da76f93349a72022ca4670c1b84860304616aaa2, 2022-08-05T10:46:05.991Z)
OS version: Linux x64 5.18.16-arch1-1
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7 CPU       Q 720  @ 1.60GHz (8 x 1373)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.75GB (4.53GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|xfce|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xfce|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by ohechtl** [comment]
For me, it's doing it with every extension basically.
![image](https://user-images.githubusercontent.com/42605027/184182588-aa248886-c025-4569-8781-75d3e370486b.png)
My sidebar was full of extension icons, now it's the default.
![image](https://user-images.githubusercontent.com/42605027/184182673-752d68db-ae0d-4b72-b390-534dd41557fd.png)
Also most of the extensions broke with this 1.70.0 update.

my `uname -a` output:
`Linux work 5.18.16-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Wed, 03 Aug 2022 11:25:10 +0000 x86_64 GNU/Linux`
VS Code:
```
~ $ code --version
1.70.1
6d9b74a70ca9c7733b29f0456fd8195364076dda
x64
```
Everything was working on the version before, on 1.69.x

**Comment by INeido** [comment]
I also have the same problem, even with the newest version.

```bash
➜ uname -a
Linux PC0 5.19.1-arch2-1

➜ code --version
1.70.1
6d9b74a70ca9c7733b29f0456fd8195364076dda
x64
```

Extension: v0.48.1

**Comment by alexr00** [comment]
Since you're seeing this error with all the views it looks like an upstream issue with VS Code: https://github.com/microsoft/vscode/issues/158446

There was an extension specific issue, but that only occurred with one view: https://github.com/microsoft/vscode-pull-request-github/issues/3549

**Comment by jan-san** [comment]
@The-Plottwist I had the same issue, and was able to resolve it by launching VS Code with option `--enable-proposed-api GitHub.vscode-pull-request-github`

**Comment by The-Plottwist** [comment]
Hey @jan-san , thanks for the suggestion.
Unfortunately I had other issues with the editor as well which I didn't mention.
So I switched to a different editor.

Cheers.
