### ISSUE TITLE
Sticky Scroll Scopes Decorator Functions in Python

### ISSUE THREAD

**Issue by sanjayshukla98** [microsoft/vscode-pull-request-github#3843]
I was using the experimental sticky scroll feature in Python. When there is a function decorator, the sticky scroll thinks the scope is the decorator function instead of the function itself.

<img width="227" alt="Screen Shot 2022-08-10 at 7 29 39 PM" src="https://user-images.githubusercontent.com/24563992/184055176-fe1069e1-9d4c-4259-8df2-ed3a5b64cb51.png">

**Comment by benibenj** [comment]
The sticky scroll feature is not part of the Pull Request extension, you would have to open an issue in the [microsoft/vscode](https://github.com/microsoft/vscode) repository. However, this issue has been solved with [microsoft/vscode#157180](https://github.com/microsoft/vscode/pull/157466) and is currently in vscode insiders and will be fixed for vscode in the next release.
