### ISSUE TITLE
Contribute actions for copying github.com links to share menu in github.dev and vscode.dev

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-pull-request-github#3848]
Request from @TylerLeonhardt and myself--could we have the Copy Permalink actions in the file/share and editor/context/share menus as well?

**Comment by alexr00** [comment]
Moved with https://github.com/microsoft/vscode-pull-request-github/commit/bf07a873f993b4382817ec4da3b78e6d5fb904ea

**Comment by alexr00** [comment]
For verification: The permalink commands are now in both the "Copy As" menu and the "Share" menu.
