### ISSUE TITLE
Permalink URL to Pull Request Comment

### ISSUE THREAD

**Issue by globalhuman** [microsoft/vscode-pull-request-github#3852]
No duplicates.

A permalink URL to a pull request comment made on a pull request accessible via the vscode interface. 

Currently to access a permalink to a comment the link must be generated when having the pull request open on the remote. Having access to a permalink URL from vscode will allow for easy communication with a team when referring to a specific comment.

The comments panel provided by vscode would be a great place for this functionality to exist with a right click on the comment of mention.

**Comment by globalhuman** [comment]
This PR in the vscode github repo seems to suggest something similiar

https://github.com/microsoft/vscode/issues/156885

**Comment by alexr00** [comment]
Added with https://github.com/microsoft/vscode-pull-request-github/pull/4330

**Comment by curtisgibby** [comment]
I was just looking for this issue to add it if it didn't exist. Glad to see that it'll be landing soon!
