### ISSUE TITLE
"Open File" doesn't work for an outdated comment for the whole file

### ISSUE THREAD

**Issue by TheQuantumPhysicist** [microsoft/vscode-pull-request-github#3855]
- Extension version: v0.48.1
- VSCode Version: 1.70.1
- OS: Debian 11.4

Steps to Reproduce:

1. Create a PR for some branch
2. Add a comment on some line in that PR
3. Modify the code in that line and push to that branch, now that comment is on code that's "outdated", as seen on github website
4. In the "COMMENTS" tab in the bottom panel, find that comment, and click on it, you'll see the comment, and the file name will be something like `/commit~deadbeef/somedir/somefile.rs`
6. Try to use the feature "Open File" on the top right, besides the "Close" x button. The Open File feature won't work and is a no-op.

**Comment by alexr00** [comment]
@TheQuantumPhysicist would you expect that "Open File" would open the file at the head of the branch?

**Comment by TheQuantumPhysicist** [comment]
> @TheQuantumPhysicist would you expect that "Open File" would open the file at the head of the branch?

I would expect it to open the current file in the working directory. Whatever is now present. Not necessarily the head. The advantage there is that I can choose where I wanna be, and this is usually very usful when reviewing PRs. I wanna switch to that branch, and compare and see how it looks like now.

**Comment by TheQuantumPhysicist** [comment]
Thank you. This works now, I just checked it. But can we make this go to the same line number? Or at least make it an option to do so?

**Comment by alexr00** [comment]
@TheQuantumPhysicist 👍 the next pre-release build of the extension will use the same selection when you "Open File".

**Comment by TheQuantumPhysicist** [comment]
> @TheQuantumPhysicist 👍 the next pre-release build of the extension will use the same selection when you "Open File".

Nice! Thanks!
