### ISSUE TITLE
"Pull request has been merged, do you want to create a new branch?" isn't what I want

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-pull-request-github#3856]
I get this when reopening a workspace that had a PR branch checked out, and the PR has since been merged.

<img width="567" alt="image" src="https://user-images.githubusercontent.com/323878/184938531-4b52ecdd-f275-4297-95f1-82030cd831f0.png">

This dialog isn't what I want - I want to return to main. This creates a new branch with a `_1` appended, and I'm confused because I usually won't want that.

**Comment by alexr00** [comment]
This isn't supposed to show unless you are running the "Start working on an issue" command.
