### ISSUE TITLE
Add support for multi-root workspaces

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode-pull-request-github#386]
Multi-root folder support: Investigate how the active source control provider can control what's visible in the PR viewlets

**Comment by dannyk81** [comment]
Wanted to know if what I experience is actually related to this (missing) enhancement.

VSCode 1.27.1
GitHub Pull Requests 0.1.2

1) I have an empty Workspace
2) I added a folder with a github repo ("repo1")
3) SCM tree view shows "Github Pull Requests" and I can see the PRs for "repo1"
4) I added a second folder with another github repo ("repo2") to the Workspace
5) SCM tree views only shows PRs from "repo1", nothing about "repo2"

Is that the expected result given current implementation?

My understanding of "multi-root folders" is somewhat different, and was actually expecting the above scenario to work, but perhaps I'm wrong and if so - sorry for the noise! and looking forward for this to be implemented 😄

**Comment by RMacfarlane** [comment]
@dannyk81 Yup, that is the expected result currently. A new "Selected source controls" API was recently added to VSCode (https://code.visualstudio.com/updates/v1_27#_scm-selected-source-controls) that we're planning to use to update the SCM tree view

**Comment by RMacfarlane** [comment]
Basic support for this was added in version 0.2.0 of the extension. Changing the selected repository should update the panel and all other PR related UI

![folder_select](https://user-images.githubusercontent.com/3672607/45836568-119d5100-bcc2-11e8-83bb-e009dac24c8c.gif)

Multiselecting isn't supported yet

**Comment by eamodio** [comment]
Awesome! -- Can't wait for multi-select support

**Comment by rebornix** [comment]
Thanks to @RMacfarlane and @joaomoreno we already shipped this feature in 0.2.3.
