### ISSUE TITLE
`Delete Local Branch` notification's button has odd capitalization

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode-pull-request-github#3861]
- Extension version: 0.48.1
- VSCode Version: 1.71.0-insider
- OS: Windows 11 x64

Steps to Reproduce:

1. In the Pull Requests view use the context menu on a branch that is not fully merged, and ask to "Delete Local Branch"
2. :bug: button caption has no capitalization and uses brackets.

![image](https://user-images.githubusercontent.com/6726799/185239064-c835fcfa-3e34-4740-a8fc-431a62371eb2.png)

I suggest captioning the button "Delete Unmerged Branch"

Maybe also add the word "local" to the message, and turn it into two sentences:

"The local branch 'fix-130497' is not fully merged.  Are you sure you want to delete it?"

**Comment by connor4312** [comment]
I'm actually not sure where branches are displayed in the GHPR views, any hints? Or maybe someone else can verify

**Comment by rzhao271** [comment]
The "Local Pull Request Branches" node is in the same tree as "All Open", but it was at the top and collapsed for me, whereas "All Open" is at the bottom of the tree and expanded, so that's where I was trying to search, first.
