### ISSUE TITLE
Unable to checkout a PR in GitHub Enterprise Server 3.0.22 

### ISSUE THREAD

**Issue by saurabh-c-rai** [microsoft/vscode-pull-request-github#3862]
Type: <b>Bug</b>
Since past few versions, I am not able to checkout PR in VSCode using GitHub Pull Request extension.
PR list is displayed correctly but checkout is not working.

Steps to Reproduce:
1. From the 'Pull Requests' side panel expand the 'All Open' list
2. Expand any PR node and choose to checkout the PR.

Expected Results:-
1. PR should be checked out into the PR view.

Actual Results:-
1. Error message pop-up displayed 'Failed to resolve Pull Request #<PR_NO> in <BRANCH_NAME>
2. Error in output tab :
 [Info] GithubRepository> Unable to fetch PR: Error: GraphQL error: Field 'autoMergeRequest' doesn't exist on type 'PullRequest'
GraphQL error: Field 'viewerCanEnableAutoMerge' doesn't exist on type 'PullRequest'
GraphQL error: Field 'viewerCanDisableAutoMerge' doesn't exist on type 'PullRequest'

Extension version: 0.49.2022081709
VS Code version: Code 1.70.2 (Universal) (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:36:37.829Z)
OS version: Darwin x64 21.1.0
Modes:
Remote OS version: Linux x64 3.10.0-514.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 5|
|Memory (System)|16.00GB (0.28GB free)|
|Process Argv|--crash-reporter-id 4e1a7f74-58fc-4b9a-bed4-13f7d0786d16|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: VA2 Machine-17|
|OS|Linux x64 3.10.0-514.el7.x86_64|
|CPUs|QEMU Virtual CPU version 1.5.3 (10 x 2399)|
|Memory (System)|60.79GB (1.59GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
d7fjc500:30543455
dsvsc012:30540252
azure-dev_surveyone:30548225

```

</details>

**Comment by alexr00** [comment]
@saurabh-c-rai I've tested the extension with GitHub Enterprise all the way back to 3.1, and checking out a PR works fine there. 3.0 was deprecated on 2022-02-16. Are you still on 3.0 now (I recognize that you probably don't have control over which version you're on, but I'm hoping you got updated in the last month)?

**Comment by saurabh-c-rai** [comment]
@alexr00 As luck would have it we are upgrading to GitHub Enterprise 3.4.4 by this week so I guess it won't be an issue anymore. Thanks for your support.

**Comment by alexr00** [comment]
🎉 glad to hear it! If you try out the extension after you're upgraded I recommend either waiting for the next stable release of the extension (probably in 2 weeks) or using the pre-release build. There is PAT-less auth and some general GitHub Enterprise fixes there.
