### ISSUE TITLE
Test: Pull Request Notification

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode-pull-request-github#3871]
Refs:  #1128 

- [x] anyOS @tanhakabir
- [x] anyOS @hediet

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode-pull-request-github/issues/new?body=Testing+%233871%0A%0A&assignees=benibenj)

---

Pull Request notifications can be turned on/off with the `githubPullRequests.notifications` setting. Currently, notifications are turned on by default, however, notifications will be turned off by default before release.

1. Install the pre-release build of GitHub Pull Requests and Issues.
2. Open a folder in VS Code that contains a GitHub repository.
3. Set the `githubPullRequests.notifications` setting to `PullRequests`
4. Create a GitHub notification for you on an open Pull Request of the open repository. How to do this depends on your notification settings (possibly just a comment on a PR you are watching). You'll either need a second account or a colleague for this.
5. Check if the GitHub icon shows a badge indicating a Notification. This can take up to 1 min to update.
6. Check in the All Pull Requests view if the PR with the notification is highlighted with a different font color and a notification badge to the right of its tree node.
7. Set the `githubPullRequests.notifications` setting to `off`
8. Check if all indications of a notification have disappeared (GitHub Badge and PR Tree Node)
9. Set the `githubPullRequests.notifications` setting to `PullRequests`
10. Go to the Pull Request with the notification and open the Description (PR overview). This will mark the notification as read. 
11. Check if all the indications have been removed for this PR (GitHub Badge and PR Tree Node highlighting).

This is how the notification should be displayed. The badge indicated how many PR's have a notification and the PR with the notification will be highlighted in a different font color and a round badge to the right of it.

![Screenshot 2022-08-22 132311](https://user-images.githubusercontent.com/44439583/185909840-ce976205-b420-46ea-a98a-323a1a8d32c7.png)

**Comment by hediet** [comment]
Good work!
