### ISSUE TITLE
Test: GitHub label colors

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode-pull-request-github#3872]
Refs:  #1193

- [x] anyOS @mjbvz
- [x] anyOS @alexdima

Complexity: 1

[Create Issue](https://github.com/microsoft/vscode-pull-request-github/issues/new?body=Testing+%233872%0A%0A&assignees=benibenj)

---

1. Install the pre-release build of GitHub Pull Requests and Issues.
2. Open a folder in VS Code that contains a GitHub repository.
3. Open a Pull Request which contains labels, or you can add labels to
4. The labels should have the same coloring as GitHub. The coloring is slightly different in light and dark mode. This is the same behavior as GitHub

**Comment by mjbvz** [comment]
Works well in the VS Code repo!
