### ISSUE TITLE
Plus button for adding comments is not showing

### ISSUE THREAD

**Issue by christianvari** [microsoft/vscode-pull-request-github#3882]
Type: <b>Bug</b>

Some file of the PR are not allowing adding comments as there is no way to visualize and trigger the plus button to add the comment.

It is affecting both stable and preview relase.

I've found this line in the debug console of the extension:

PullRequestChangesTreeDataProvider> Error: Cannot resolve tree item for element 0/0:abci.go

Extension version: 0.49.2022082209
VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:35:13.448Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1280P (20 x 1997)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.71GB (3.82GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/christianvari/oak/audit-elesto-dao-elesto --remote=wsl+Ubuntu --crash-reporter-id 70807638-9312-4ccc-a4ce-715fbb3e08d2|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|12th Gen Intel(R) Core(TM) i7-1280P (20 x 1996)|
|Memory (System)|7.62GB (4.14GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
d7fjc500:30543455
dsvsc012cf:30540253
azure-dev_surveyone:30548225
i497e931:30552240

```

</details>

**Comment by alexr00** [comment]
> Some file of the PR are not allowing adding comments as there is no way to visualize and trigger the plus button to add the comment.

Is the PR in a public repo, and if so, can you share the PR, file, and line number?

If the PR isn't in a public repo then can you view the PR on github.com and see if the line you want to comment on is commentable there? GitHub only allows certain lines to be commentable in PRs, and we try to match that in this extension.

**Comment by christianvari** [comment]
Unfortunately the PR is on a private repository. 
From the Github web UI I'm able to add comments. If I add them from the web UI I can see them on the code with the extension but I cannot add other comments as the plus button is not showing.

Additionally, this happens only with a subset of files of the PR.

**Comment by alexr00** [comment]
Thanks for the additional details. Is there anything different about this files? Are they all files added in the PR?

**Comment by benibenj** [comment]
I've just seen this too. For me it happened when I had a diff open when I started VSCode Insiders.

Reproduce:
1. Open a diff and it will display the gutter with the plus button
2. Either close and reopen VSCode Insiders or run the reload window command
3. Gutter with plus button is not rendered

This seems to only happen for diffs and not files which have changes.

**Comment by alexr00** [comment]
@christianvari does that line up with what you are seeing?

**Comment by christianvari** [comment]
Maybe related but not the same issue. In my case the gutter for the plus button is not rendered regardless if I reload. Also happens only in some files (added status in the PR)

**Comment by christianvari** [comment]
The issue is fixed in the latest version. Closing it
