### ISSUE TITLE
No feedback after Approve & Submit

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode-pull-request-github#3888]
Type: <b>Bug</b>

I just approved a PR in vscode. After hitting *Approve and Submit* the *Leave a comment* empties as only feedback. I was confused for a bit and had to double-check if it worked.

Should I be able to, to approve multiple times?

Maybe the description can open to show the latest comment and PR state?

Extension version: 0.49.2022082209
VS Code version: Code - Insiders 1.71.0-insider (235a92a3693176fbf9af16ec5b829c458a1d682f, 2022-08-22T05:17:16.753Z)
OS version: Darwin x64 21.6.0
Modes:
Sandboxed: No

**Comment by alexr00** [comment]
Yes, github.com allows you to approve multiple times. I'll see what I can add to the focus view to make it clearer that your approve went through.

**Comment by alexr00** [comment]
You should see your username and a checkmark after you approve and submit:

![image](https://user-images.githubusercontent.com/38270282/191021849-4caafc24-e78e-48ec-93bd-dd3519151930.png)

Do you not see this?

**Comment by digitarald** [comment]
@alexr00 sorry for the delay. I just tried this out again and it does feel very hidden. One idea would be to open (focus) the PR description, as this has a much large area for completed reviews?

Maybe there are ways that we can add to our UX toolbox to highlight subtle changes in smaller UI elements like icons (cc @daviddossett)

**Comment by alexr00** [comment]
I'd prefer to add further emphasis to the focus view rather than open the full PR description. As a user of the view myself, I don't want the whole description editor open when all I need to do is approve the PR. I'm interested in @daviddossett input on this as well!

**Comment by daviddossett** [comment]
I'll take a look at this next week—bit backed up at the moment after being OOF.

**Comment by alexr00** [comment]
No rush, I put this in the October Milestone!

**Comment by marshandrewg** [comment]
Adding on to this, currently if there's multiple reviewers on a PR it's possible your name / 'approval status' is hidden without scrolling

![Screen Shot 2022-12-12 at 10 42 32 AM](https://user-images.githubusercontent.com/24252598/207089060-a82a1c16-849c-43fa-865c-decd1f21fc20.png)

**Comment by daviddossett** [comment]
Coming back to this now, I think this is another good candidate for https://github.com/microsoft/vscode/issues/166891

In the meantime, would it make sense to match the colors used in the PR list here @alexr00? The icon would probably jump out more than it does now.

**Comment by alexr00** [comment]
👍 colors added with https://github.com/microsoft/vscode-pull-request-github/pull/4329

**Comment by alexr00** [comment]
Closing as we have colors in addition to the symbols.
