### ISSUE TITLE
After reload my PR details are no longer visible

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode-pull-request-github#3889]
Testing [#158773](https://github.com/microsoft/vscode/issues/158773)

Tested with https://github.com/microsoft/vscode/pull/158313 .

After reload my PR is no longer loaded in the PR view. It did open the checked out branch of course, but the PR is only visible after I click "Load More" in the PR tree.

The Comments view loaded correctly, but the PR view didn't have any memory of the currently loaded PR.

<img width="2131" alt="image" src="https://user-images.githubusercontent.com/8599/186326473-49dc978e-e55d-41dc-bbf5-1bb8bcc4a53c.png">

---

Extension version: 0.49.2022082209
VS Code version: Code - Insiders 1.71.0-insider (235a92a3693176fbf9af16ec5b829c458a1d682f, 2022-08-22T05:17:16.753Z)
OS version: Darwin x64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 3, 3|
|Memory (System)|64.00GB (10.03GB free)|
|Process Argv|--enable-proposed-api donjayamanne.kusto --log trace --crash-reporter-id 4cf0a6f0-aaf8-4da3-9b2b-81f6c639c12b|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by alexr00** [comment]
@digitarald a few questions:
- Did the "Changes in Pull Request" view (in the GitHub Pull Request view container) load ok?
- Was the issue just that the PR wasn't immediately visible in the "All Open" category in the "Pull Requests" view?

**Comment by digitarald** [comment]
@alexr00 
> Did the "Changes in Pull Request" view (in the GitHub Pull Request view container) load ok?
No.
> Was the issue just that the PR wasn't immediately visible in the "All Open" category in the "Pull Requests" view?
No, the PR state was lost completely, so i just assumed I need to find it again in the tree.

**Comment by alexr00** [comment]
@digitarald I can't reproduce this issue. Can you:
1. Set `"githubPullRequests.logLevel": "debug"`
2. Repro the issue
3. Share the output from "GitHub Pull Request"?
