### ISSUE TITLE
Sign In gives generic error message

### ISSUE THREAD

**Issue by billyjbryant** [microsoft/vscode-pull-request-github#3891]
I am using VSCodium and have an entirely different (but similar in nature) issue with sign-in. When I click the "Sign-in" button in the extension, I get an error dialog :

![image](https://user-images.githubusercontent.com/3013565/186501852-34b3518b-6622-468b-8835-dcafed7a76cd.png)

- Extension version: v0.48.1
- VSCode Version: (VSCodium) 1.70.2 Release: 22230
- OS: macOS Monterey Version 12.5.1

VSCodium Info
```
Version: 1.70.2
Release: 22230
Commit: 6c122d9b2d1af2c37bd55caad614321eb53b342f
Date: 2022-08-18T04:12:18.598Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin arm64 21.6.0
```

Steps to Reproduce:

1. Open the `GitHub` Tab and click `Signin`
2. Get error message

Extension Logs:
[7-GitHub Pull Request.log](https://github.com/microsoft/vscode-pull-request-github/files/9418996/7-GitHub.Pull.Request.log)

```
[Info] Error signing in to GitHub: HttpError: Bad credentials
[Info] HttpError: Bad credentials
	at /Users/billybryant/.vscode-oss/extensions/github.vscode-pull-request-github-0.48.1/dist/extension.js:1131:6173
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async S1.setCurrentUser (/Users/billybryant/.vscode-oss/extensions/github.vscode-pull-request-github-0.48.1/dist/extension.js:1148:16819)
	at async S1.createHub (/Users/billybryant/.vscode-oss/extensions/github.vscode-pull-request-github-0.48.1/dist/extension.js:1148:18000)
	at async S1.login (/Users/billybryant/.vscode-oss/extensions/github.vscode-pull-request-github-0.48.1/dist/extension.js:1148:15989)
	at async Sm.authenticate (/Users/billybryant/.vscode-oss/extensions/github.vscode-pull-request-github-0.48.1/dist/extension.js:1266:18461)
	at async /Users/billybryant/.vscode-oss/extensions/github.vscode-pull-request-github-0.48.1/dist/extension.js:1266:6905
	at async a._executeContributedCommand (/Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:63914)
```

**Comment by alexr00** [comment]
@TylerLeonhardt we also saw this with on @joaomoreno machine with VS Code. A log out and log back in solved it.

**Comment by TylerLeonhardt** [comment]
@billyjbryant can you provide the contents of the GitHub Authentication output pane:
![image](https://user-images.githubusercontent.com/2644648/128087382-c706864f-7005-4a2e-878b-662c69c4457e.png)

And also anything that shows up in Dev Tools:

* ctrl + shift + P
* "Dev Tools"

**Comment by alexr00** [comment]
I've hit this now too. The error doesn't occur when calling the auth extension API. Instead, it happens when I try to use the auth token returned from the API to use GitHub API. It seems like the token is no longer valid. 

There is nothing useful in the dev tools. 

Here's the output, cleared just before the auth call:
```
[Info  - 12:19:16.240] Getting sessions for read:user,repo,user:email,workflow...
[Info  - 12:19:16.241] Got 1 sessions for read:user,repo,user:email,workflow...
```

**Comment by TylerLeonhardt** [comment]
@cbrnr can you please share a gif/video of you logging in? you can use a tool like gifcap.dev to do this.

**Comment by cbrnr** [comment]
Thanks for the quick response! Today the extension is working again. It seems like yesterday there were some server issues, which would explain the rate limit message and failed login attempts. Maybe @billyjbryant and @alexr00 can check if the issue has resolved itself for them as well?

**Comment by cbrnr** [comment]
Today, the issue came back. First, I got that rate limit exceeded message, and after that I cannot log in:

https://user-images.githubusercontent.com/4377312/190321866-9f838997-d394-410f-af44-ec260aa3e34a.mov

**Comment by alexr00** [comment]
@cbrnr where you opening lots of windows or reloading the window a lot before you saw the rate limit error? We shouldn't be hitting that rate limit, but once it's hit you can't sign in.

**Comment by cbrnr** [comment]
I don't think so - at least not on purpose. FWIW, I never shut down my computer, so maybe some connections do not get reset? I do restart VS Code quite often though, and I tried in this case, but it didn't help. I am now signed in again, this seems to have happened automatically at some point.

**Comment by alexr00** [comment]
@cbrnr I added a lot of rate limit logging in the pre-release version of the extension. If you see the rate limit error again, could you please share the output of "GitHub Pull Request" over in https://github.com/microsoft/vscode-pull-request-github/issues/3847?

**Comment by alexr00** [comment]
The rate limit issue has been fixed. We don't have enough info continue investigating the bad credentials issue.
