### ISSUE TITLE
Focus switches to `comments` tab automatically

### ISSUE THREAD

**Issue by mntlty** [microsoft/vscode-pull-request-github#3894]
- Extension version: v0.48.1
- VSCode Version: 1.70.2 
- OS: OS X 12.5.1

Steps to Reproduce:

I'm not sure how exactly to reproduce, but I find that once I am working on code that has a pull request with comments, changing focus from my integrated terminal to the code editor will often switch to the `comments` tab. I find this to be either distracting or disruptive, as I lose sight of what I had open in the terminal and have to press keys to switch back before I can go back to the code editor.

To be helpful to me, this should be something I as the user intend to navigate to rather than having it happen automatically.

**Comment by alexr00** [comment]
@mntlty this is controlled by a setting. You can set `"comments.openView": "never"` to change this behavior.
