### ISSUE TITLE
Can't approve PR opened by myself

### ISSUE THREAD

**Issue by isaac-martin** [Microsoft/vscode-pull-request-github#390]
- Extension version:  0.1.1
- VSCode Version: 1.27.0
- OS: Mac OSX 10.13.6 

Steps to Reproduce:
1. Push some changes on feature branch
2. Open PR on Github
3. Try to approve Your own PR in VSCode

Is there a way to approve your own PR? Was mainly just testing this out and I get an error in VSCode that i can't approve PR opened by me, but I can merge and close on Github.

I understand opening and approving your own PR is kind of obsolete but there is occasions where necessary, particularly in small teams.

**Comment by RMacfarlane** [comment]
@isaac-martin Thanks for taking the time to file an issue!

No, there isn't a way - the GitHub API disallows this and the error is returned directly from there.

**Comment by davidsiers** [comment]
Is there any way for GitHub to allow this?
