### ISSUE TITLE
Buttons don't match VS Code's new style

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#3900]
Current PR view:

![image](https://user-images.githubusercontent.com/2193314/187226356-3f9ec9b4-70c1-4ac9-994e-48962414de34.png)

Expected round corners:

![image](https://user-images.githubusercontent.com/2193314/187226427-a748cb2b-92aa-45bd-a984-0635a3be38e4.png)

**Comment by alexr00** [comment]
Actually, let's take this as a candidate. Should be very low risk.
