### ISSUE TITLE
In comments, the actor's username of an emoticon is not visible as it's in github

### ISSUE THREAD

**Issue by TheQuantumPhysicist** [microsoft/vscode-pull-request-github#3908]
Extension version: v0.48.1
VSCode Version: 1.70.2
OS: Debian 11.4

Steps to Reproduce:

1. Create a PR for some branch
2. Add a comment on some line in that PR
3. Make a user add an emoticon on that comment (smile, thumbs-up, etc)
4. There's no way in VSCode to know who did this. Once has to go to github on the browser to see the actor.

While this sounds trivial, it's very useful because people often use an emoticon to approve/disapprove/vote instead of a whole comment.

**Comment by alexr00** [comment]
We have this now! ![Image](https://github.com/user-attachments/assets/a1532a40-55bb-467b-bde4-ca31a5d91386)
