### ISSUE TITLE
It would be much more useful if the gutter emphasised the lines this PR affects, not the commentable range

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#392]
I will often browse/tweak PR branches in the regular file view, I would find it so much more useful if the grey bar extended to only the lines that were changed. See this example:

<img width="466" alt="screen shot 2018-09-10 at 11 46 04 am" src="https://user-images.githubusercontent.com/2193314/45317550-2c680c80-b4ef-11e8-8101-dbc0599c1e9f.png">

I'd like it to show me these 7 lines instead:

<img width="312" alt="screen shot 2018-09-10 at 11 47 38 am" src="https://user-images.githubusercontent.com/2193314/45317616-5cafab00-b4ef-11e8-87b0-c8d11f2c20cd.png">

I propose we change the gutter so there are 4 states instead of 3:

- Uncommentable
- Commentable + not marked (only shows when the gutter is moused over, or not as bold)
- Commentable + marked
- Comment exists

**Comment by Tyriar** [comment]
Mockups:

![image](https://user-images.githubusercontent.com/2193314/45318339-7eaa2d00-b4f1-11e8-952b-a3cc16c9a977.png)

![image](https://user-images.githubusercontent.com/2193314/45318383-9da8bf00-b4f1-11e8-8a1a-eb294252fedb.png)

**Comment by Tyriar** [comment]
cc @misolori

**Comment by Tyriar** [comment]
We don't have the label in this repo, but this is definitely a papercut :drop_of_blood: for me and one of my most wanted things.

**Comment by misolori** [comment]
This was one idea I had that could improve this view a bit. The comments area could be moved to the left to have more space  and decorators could be updated to show buttons. And hovering over a line could show the "add comment" action. That way there isn't ever any collision between the general glyph areas and commenting items.

**Example**
![Kapture 2021-02-03 at 17 29 13](https://user-images.githubusercontent.com/35271042/106831935-a3b11480-6645-11eb-9a30-9ab832e6ad6d.gif)

**Comment by Tyriar** [comment]
@misolori I'm more interested in the regular file view here which is useful not only when reviewing to see exactly which lines changed but also when working on my own PRs because it will show every line I've touched across _all commits_. Right now I can trim 3 lines off the top and the bottom because I know they are definitely not part of the changes, but that doesn't work at the start/end of files, or when changes happened within 3 lines of each other.

I'm of the opinion that we don't need any decoration to indicate the line is commentable unless it's being hovered, just like GitHub:

![recording (11)](https://user-images.githubusercontent.com/2193314/106898736-68483180-66a9-11eb-9c0d-699a12ed9652.gif)

Right now it doesn't differentiate so I can't tell which lines changed from this view. Some set of lines in the red rectangle changed, but I don't know which:

![image](https://user-images.githubusercontent.com/2193314/106899411-2e2b5f80-66aa-11eb-8324-6174ababf767.png)

We're instead prioritizing information that doesn't matter much (that you can comment on lines that didn't change) over information that does (which lines changed). For GitHub users I think it's understandable that you can comment on some lines outside the diff so people would discover this. But I don't mind which mockup we go with (https://github.com/Microsoft/vscode-pull-request-github/issues/392#issuecomment-420024843), as long as it's easy to see which lines a PR changed from the regular file view.

As for moving the line to the left, one benefit now is it's right next to the git diff indicators and it's showing very similar information, especially if this issue gets resolved:

![image](https://user-images.githubusercontent.com/2193314/106899683-82ceda80-66aa-11eb-9cce-26b587fb8682.png)

**Comment by alexr00** [comment]
There must be something we can do from the extension to help with this. Will continue to investigate in November.

**Comment by alexr00** [comment]
I've tried out the options that the editor decoration API gives us, and the result isn't good enough since we can't put decorations in the gutter.

@joaomoreno suggested the [dirty diff decorator](https://github.com/microsoft/vscode/blob/cf46b990f707105d712aaa070af74ca12b6b90eb/src/vscode-dts/vscode.d.ts#L14409-L14412), but since requires a whole source control it isn't a good option as is. We'll add this to the December plan and see if we can expose the dirty diff decorator outside of the source control, since it is the idea UI for showing a diff indicator.

**Comment by joaomoreno** [comment]
> @joaomoreno suggested the [dirty diff decorator](https://github.com/microsoft/vscode/blob/cf46b990f707105d712aaa070af74ca12b6b90eb/src/vscode-dts/vscode.d.ts#L14409-L14412), but since requires a whole source control it isn't a good option as is. We'll add this to the December plan and see if we can expose the dirty diff decorator outside of the source control, since it is the idea UI for showing a diff indicator.

There are currently two blockers for this:

- It currently requires an SCM provider. This is easy to do.
- It currently has no good solution for when multiple dirty diff decorator providers provide content. It currently just picks the first one it sees. This is harder, requires some UX thought.
