### ISSUE TITLE
Comments created in the description view don't have a user icon

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#3926]
![image](https://user-images.githubusercontent.com/38270282/188898408-17fd20b8-487a-4945-aa1c-0df234a9adf8.png)

After refreshing the description webview, most icons will be correct. However, icons for code comments will still be broken.

**Comment by TylerLeonhardt** [comment]
![image](https://user-images.githubusercontent.com/2644648/193368157-e27ac90e-084b-4618-aa46-bad531161bed.png)
I think this is verified. I tried creating comments in vscode and in github.com and all the user icons give me the GH icon both in the webview and in the view.
