### ISSUE TITLE
Infinite error messages

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-pull-request-github#3928]
![Recording 2022-09-07 at 10 25 32](https://user-images.githubusercontent.com/323878/188941411-7925573f-56d0-4178-ab84-1e518c3bd98e.gif)

I don't know why this is happening. I'm on the bus but my connection is fine. I reloaded the window and it went away. I should have grabbed the log, sorry.

**Comment by alexr00** [comment]
Leaving open in case it happens again so that we can add logs.
