### ISSUE TITLE
Local files don't update

### ISSUE THREAD

**Issue by SeanDKendle** [microsoft/vscode-pull-request-github#3939]
When you save a file, the local files don't update, leading to confusion and frustration when you see the same file in two different clients with completely different contents. What kind of "feature" is this!?

**Comment by alexr00** [comment]
> When you save a file

Is this when you have a file open in VS Code?

>  the local files don't update, leading to confusion and frustration when you see the same file in two different clients

What are the two different clients in this scenario?
