### ISSUE TITLE
Failing to create a comment because there's no pending review

### ISSUE THREAD

**Issue by irenepc** [microsoft/vscode-pull-request-github#3942]
- Extension version: 0.50.0
- VSCode Version: 1.71.0
- OS: Windows 10

Steps to Reproduce:

1. In a PR on which you have not started a review
2. Reply to a comment someone else has made on your PR and click "add comment"

This is my own pull request which I hardly ever open reviews on. It does not happen every time, but this is how I triggered it.
![image](https://user-images.githubusercontent.com/44209602/189945082-acb36312-a932-4526-8298-3853f5de9da7.png)

**Comment by alexr00** [comment]
I haven't been able to reproduce this. If you still see it please ping the issue and I will re-open!
