### ISSUE TITLE
Unable to select a repository when submodules are present

### ISSUE THREAD

**Issue by Dzejkop** [microsoft/vscode-pull-request-github#3950]
I have a project which had a submodule added recently. For some reason the Pull Requests and Issues tabs now only display the PRs and issues from the sumbodule repository and the extension doesn't link with the root repository.

I would like to be able to set (either in config or via a command) the repository used by the extension.

**Comment by alexr00** [comment]
Can you share the output from `git remote -v`?

**Comment by Dzejkop** [comment]
I get the following
```
origin  git@github.com:XXX/yyy.git (fetch)
origin  git@github.com:XXX/yyy.git (push)
```

Where `XXX/yyy` is the correct repository I'm working on. But in the pull requests tab I see issues and PRs from the submodule repo.

**Comment by eevleevs** [comment]
Similar here, only I get only the issues from the main module and not the sub. 
Strangely, if I uninstall/reload/install it works again for a while. If I happen to open another folder then open the one with the subrepo, the sub is gone again from the extension.

**Comment by alexr00** [comment]
The fix should cause all submodules to be properly detected.
