### ISSUE TITLE
"viewed" checkboxes don't always propagate 

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#3959]
1. Check out a PR and mark all the files in a folder as read.
2. Reload.
3. Expected: The parent folder of the files you marked as viewed will be checked.
    Actual: All the children are checked, but the parent is not.

**Comment by alexr00** [comment]
Found the actual problem. Real repro steps:
1. Open a PR that has folders that get collapsed onto one line. Example (see that folder2 is nested under folder1 but they get shown on one line):
![image](https://user-images.githubusercontent.com/38270282/191779783-ba5e9765-7b11-4d0b-8c02-ee54b7760141.png)
2. Mark all the files in the folders as viewed
3. See that the check doesn't get propagated to the parent folder.

**Comment by roblourens** [comment]
Most of these select the parent folder when all the children are selected, except for the top level

![Recording 2022-09-30 at 13 21 14](https://user-images.githubusercontent.com/323878/193350370-b869a63c-e599-4171-bc16-7be1652c9fee.gif)
