### ISSUE TITLE
Review Mode view doesn't activate on Codespaces

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode-pull-request-github#3962]
Opening a PR in github.dev vs Codespace looks different. And there is no UI indicator in how I would "enter" PR review mode that gives me the comment box in the sidebar.

<img width="818" alt="image" src="https://user-images.githubusercontent.com/8599/191138651-7dd12969-dfbe-4085-8e98-7a3c10e3811c.png">

Maybe I need to click the ➡ icon _Checkout Pull Request_, but that doesn't do anything (why would it, I already have the branch open).

<img width="394" alt="image" src="https://user-images.githubusercontent.com/8599/191139043-3dbd0378-9977-40ba-ae46-7be7b5003279.png">

**Comment by alexr00** [comment]
Not opening the changes view and focus view was something that the Codespaces folks specifically asked for, so this is actually controlled by Codeapces through a command at the moment:

https://github.com/microsoft/vscode-pull-request-github/blob/0ff8205cc3d6ba06ab3945e494e1756a0f82bf6d/src/extension.ts#L238-L242

We can revisit this decision, but we should talk to the Codespaces folks and make sure they're ok reversing that.

The changes view and focus view are in another view container (circled below):
![image](https://user-images.githubusercontent.com/38270282/191250514-300a178c-381d-4a83-b467-ff8a4ea53e00.png)
