### ISSUE TITLE
Project filter options for search queries

### ISSUE THREAD

**Issue by ced-f** [microsoft/vscode-pull-request-github#3968]
Is it possible to filter issues by project attribute fields? E.g. I would like to only see issues in the current iteration. In my project I can filter issues by iteration with something like `iteration:@current`.
I think this is not possible with the `githubIssues.queries` setting right now.

**Comment by alexr00** [comment]
All of github.com's searth terms should work there: https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests#about-search-terms
