### ISSUE TITLE
Edit descriptions / task lists updates

### ISSUE THREAD

**Issue by stilliard** [microsoft/vscode-pull-request-github#398]
It'd be useful to be able to edit pull requests markdown descriptions directly from VS Code in case you notice a mistake. 

Also support for [task lists / checkboxes](https://help.github.com/articles/about-task-lists/) would be super useful, e.g. a reviewer could use these to run through tests or tick off objectives.

-----

Minor but also noticed the task lists display checkboxes but also display bullet points atm:

On GitHub:
![image](https://user-images.githubusercontent.com/77454/45326686-83e89580-b54c-11e8-9e93-99b21d2c36f4.png)

On VS Code:
![image](https://user-images.githubusercontent.com/77454/45326706-9531a200-b54c-11e8-9619-bec66221a2e8.png)

**Comment by alexr00** [comment]
You can always edit the markdown to check off your check boxes.
