### ISSUE TITLE
Enterprise: Not Found error when opening PR description

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-pull-request-github#3992]
Testing #3985

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/876920/192597840-246cdc78-2f99-4673-8447-ea2fb6f24f7b.png">

**Comment by alexr00** [comment]
I can repro, here are the steps:
1. Have a GitHub Enterprise repo open where the settings.json doesn't have the `enterprise-uri` setting set.
2. Make a PR to add the `enterprise-uri`
3. Check out main (now `enterprise-uri` is no longer set)
4. Try to open the description

The `enterprise-uri` is essential to enterprise support, so if it's not set then I think it's fair for things not to work. I'll see if I can have a better error.

**Comment by alexr00** [comment]
@TylerLeonhardt does it makes sense to have some warning in the GitHub Enterprise Authentication extension when the `enterprise-uri` disappears from an in-use workspace while a user is signed in with GitHub Enterprise?
