### ISSUE TITLE
When logged in to non-enterprise account, cannot log in to enterprise account

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode-pull-request-github#3995]
Testing #3985

The extension wants me to sign in even though I'm already signed in (though on the non-enterprise account). The extension is on the trusted extension list in Manage Trusted Extensions.

![UI indicates to sign in even though I'm already signed in](https://user-images.githubusercontent.com/7199958/192644534-98cf6f6b-5229-421c-8742-a2a6f74c3a7b.PNG)

**Comment by alexr00** [comment]
@rzhao271 That sign in button should prompt you to sign in with GitHub Enterprise when you click it if you have a folder open to a Enterprise repo (you may need to wait a few seconds after opening the folder for this to happen though as we have to wait for information from the git extension).

**Comment by rzhao271** [comment]
Resolved offline

**Comment by alexr00** [comment]
In case anyone else comes across this: I recommend cloning your Enterprise repo in an external terminal so that the git credential manager modal dialog shows.
