### ISSUE TITLE
Larger text box when composing a comment

### ISSUE THREAD

**Issue by dnut** [microsoft/vscode-pull-request-github#3998]
Whenever I try to add a comment that's more than a few sentences, the text box is too small. I have to keep scrolling to read my comment. I can't just view the whole thing in its entirety.

I need to see a high level view of my entire comment. I need to see all the paragraphs so I can skim the entire thing. When all I see is a tiny snippet from the middle of one paragraph, I just get lost.

This is annoying enough that I jump to the github ui to type my comments. Github allows you to expand the text box to an arbitrary size.

The box should be manually expandable, or it should automatically scale to the size of the full body of text you have typed.

**Comment by alexr00** [comment]
Closing in favor of the upstream issue: https://github.com/microsoft/vscode/issues/110403
