### ISSUE TITLE
Cannot expand the electron 2 vscode PR

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#40]
![image](https://user-images.githubusercontent.com/2193314/41940989-7cb1a8e4-794f-11e8-9d73-d4399585491a.png)

https://github.com/Microsoft/vscode/pull/52782

**Comment by rebornix** [comment]
We ran into exceptions when dealing with file changes returned from GitHub. When a file or change is large, GitHub will not return the diff hunk for that change but we didn't protect that.

**Comment by rebornix** [comment]
There are several cases that GitHub pull request api doesn't return a file change with proper patches/diffs

1. file or diff is too large
2. file is binary

For the first case, we can probably fetch the blob content from github, but we don't know for sure if we can open the binary content successfully in vscode. So for now we will open the file directly in browser.

Reopen it and see if we can have enhancement from the api side.

**Comment by mjbvz** [comment]
I also see this for a small PR: https://github.com/microsoft/vscode/pull/73775

![Screen Shot 2019-05-17 at 9 59 29 AM](https://user-images.githubusercontent.com/12821956/57944051-94df6880-788a-11e9-9126-672dd305bbde.png)

**Comment by RMacfarlane** [comment]
@mjbvz 👍 this looks like https://github.com/microsoft/vscode-pull-request-github/issues/1059, sent out a fix for it

**Comment by RMacfarlane** [comment]
Closing since we should now handle file changes that don't have blob content by showing a notification to open them on GitHub
