### ISSUE TITLE
Possibly add a warning for Settings Sync users

### ISSUE THREAD

**Issue by timroes** [Microsoft/vscode-pull-request-github#400]
I know, that this is kind of a strange request and not sure what repository best to report that.

If you use the (rather popular - 1.7M installs) Settings Sync plugin and login via this plugin to GitHub, the OAuth token will easily end up in a public Gist with the next (auto) sync. Of course everyone should be aware of those issues using that plugin (though maybe not everyone read in advance that the OAuth token will be saved into the settings and thus end up in the Gist).

I see a huge potential here for a lot of leaked OAuth tokens via Settings Sync configurations in the future. Since the Settings Sync extension is so popular I am not sure if it's worth adding a warning about this (or even store the token somewhere else - which would be related to #368).

Since Settings Sync currently have no potential to exclude specific settings from syncing (which of course is an issue of that extension), with saving the token in the setting it seems that those two plugins are currently rather incompatible to each other, if you don't want to sync your OAuth token to a Gist.

**Comment by auchenberg** [comment]
Thanks for opening this issue @timroes. On what OS do you see the oAuth token being stored in your `settings.json`? 

We _should_ store your tokens in an encrypted store per https://github.com/Microsoft/vscode-pull-request-github/issues/190

**Comment by NavyAdmiral** [comment]
@timroes Iirc, the gist is set to private by default in `Settings Sync`.

**Comment by timroes** [comment]
@auchenberg Thanks for the quick response and thanks for the hint. Indeed the token is correctly saved in my keystore if I unlock it properly. I am using Archlinux and often click away the keystore unlock, in case I don't see the obvious reason why it needs to be unlocked at that moment. This was the case yesterday and in this case the plugin felled back to storing it in the settings directly - which imho is the reasonable behavior here.

Since I think my system setup is rather custom and most people will have the keystore integrated with their login (on Linux) I think there is no need to change anything here.

@NavyAdmiral I think no matter if the Gist is private or public, something like a password or OAuth token should not end up there "by default", since I assume the GitHub Gist infrastructure has not the same security level, that we could expect from the actual OAuth token infrastructure of GitHub.
