### ISSUE TITLE
Mark file as not viewed doesn't work

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode-pull-request-github#4003]
Testing #3985

Clicking on the mark file as not viewed button in the top-right toolbar doesn't work.
Unchecking the checkbox in the treeview works, though.
![Mark file as not viewed button](https://user-images.githubusercontent.com/7199958/193077308-cd43d3c9-303e-4599-8028-ee99826fe24a.png)

**Comment by alexr00** [comment]
I'm not able to repro this, though I do see a slight delay before the tree checkbox is checked. Do you have the PR currently checked out?

**Comment by rzhao271** [comment]
Closing as I don't have an instance set up to reconfirm this
