### ISSUE TITLE
Can't add comments to PR when using Zen Mode

### ISSUE THREAD

**Issue by hnipps** [microsoft/vscode-pull-request-github#4005]
Type: <b>Bug</b>

In Zen Mode, enter pull request mode.

There is no option to add comments to the PR.

On exiting zen mode I can add comments.

Extension version: 0.50.0
VS Code version: Code 1.71.2 (Universal) (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:05:37.721Z)
OS version: Darwin arm64 21.5.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 3, 4|
|Memory (System)|16.00GB (0.46GB free)|
|Process Argv|--crash-reporter-id b368e6dd-73fc-44e4-b85c-d7303120f077|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30557514
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
i497e931:30553904
pyindex848cf:30577861
fc301958:30573243

```

</details>

**Comment by alexr00** [comment]
Commenting is disabling in Zen mode. You can toggle it on with the command "Comments: Toggle Editor Commenting".

**Comment by hnipps** [comment]
> Commenting is disabling in Zen mode. You can toggle it on with the command "Comments: Toggle Editor Commenting".

Ok, I tried that and the command isn't available in the command palette.

I used to be able to add PR comments in zen mode, did something change?

**Comment by alexr00** [comment]
@hnipps can you share a screen recording? I'm able to run the "Comments: Toggle Editor Commenting" when I have a PR file open in the editor while in zen mode.

**Comment by hnipps** [comment]
@alexr00 I think I was behind a version or something, updated and I can now see the "Comments: Toggle Editor Commenting" option. Thanks!
