### ISSUE TITLE
Active PR view has wrong title after switching PRs

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-pull-request-github#4007]
- Open a single folder on https://github.com/roblourens/testrepo
- Checkout PR #3
- Checkout PR #4
- This view still has the title for 3, it's fixed if I reload

<img width="343" alt="image" src="https://user-images.githubusercontent.com/323878/193162432-2c8056fd-f229-4630-9d38-6ab2b7b80bc2.png">

**Comment by alexr00** [comment]
Thanks for reporting, this was a major regression.
