### ISSUE TITLE
Block comments not rendering correctly

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode-pull-request-github#4013]
I was playing around with GitHub Enterprise support and noticed this:

Steps to Reproduce:

1. add a comment with:
```
    ```
    wat
    ```
```

3. 
![image](https://user-images.githubusercontent.com/2644648/193367976-91012b20-9407-4054-939e-a12137b68bb1.png)

**Comment by alexr00** [comment]
I see this:

![image](https://user-images.githubusercontent.com/38270282/194064605-2a8b2263-1cfb-487d-b2cf-85d405951170.png)

Which is consistent with what the markdown preview does:

![image](https://user-images.githubusercontent.com/38270282/194064749-2475c7fb-47c9-403d-960a-cd2b2ff4d82f.png)

@mjbvz can you confirm if this is intentional?

**Comment by TylerLeonhardt** [comment]
@alexr00 I did mention I saw this in GH Enterprise... though I'm not sure why that would matter

**Comment by mjbvz** [comment]
This is expected for the example markdown

Indenting text with four or more spaces implicitly creates a code block. In this case, the code block consists of the markup for the fenced code block, which is likely why you were confused

**Comment by TylerLeonhardt** [comment]
No I had the spaces only to get them to show up on GitHub

**Comment by alexr00** [comment]
What is the exact spacing you used in your example?

**Comment by TylerLeonhardt** [comment]
<img width="736" alt="image" src="https://user-images.githubusercontent.com/2644648/194151185-4f82a728-5f87-4364-af05-3b7de0a9faeb.png">
get's me:
<img width="758" alt="image" src="https://user-images.githubusercontent.com/2644648/194151214-5889155a-a237-4de1-91da-c1a903c52673.png">

and
<img width="783" alt="image" src="https://user-images.githubusercontent.com/2644648/194151307-af8d5fff-4f46-4fcb-be2b-4e757125fb3b.png">

**Comment by TylerLeonhardt** [comment]
I'm reopening this since it still reproduces. Happy to provide more details/video chat

**Comment by TylerLeonhardt** [comment]
<img width="990" alt="image" src="https://user-images.githubusercontent.com/2644648/194938048-beee3375-a726-4cfc-8da4-ee8bb69876a5.png">
That looks ok to me. Anything else I can provide to help?

**Comment by alexr00** [comment]
What OS do you use?

**Comment by TylerLeonhardt** [comment]
macOS

**Comment by alexr00** [comment]
Thanks, it's a line ending bug so I couldn't repro on Windows. I can repro with WSL.
