### ISSUE TITLE
Status checks not rendering

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-pull-request-github#4015]
Here's the PR view:

![image](https://user-images.githubusercontent.com/22350/193829525-3c766dff-7f20-40e7-9c3e-e753393cbd72.png)

Here the same PR in GH:

![image](https://user-images.githubusercontent.com/22350/193829638-d205a0d5-fd4e-4a09-a82f-7ec7caa616fe.png)

**Comment by alexr00** [comment]
This is what's happening:

https://github.com/microsoft/vscode-pull-request-github/blob/eac1aee806f92f855e99306387520fd21b8d19cf/src/github/pullRequestModel.ts#L1065-L1067

Folks like us who have multiple organizations to SAML with are more likely to hit this. I'll follow up with GitHub to try to understand what's happening.
