### ISSUE TITLE
Tooltip on files should show full path

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode-pull-request-github#402]
Issue Type: <b>Bug</b>

Tooltips on files in both file explorer and git view show complete path. The ones in the Github PR view show the same text as the label on the node. Plus in Windows, it uses the wrong path separator

![image](https://user-images.githubusercontent.com/16890566/45329435-52a0a300-b515-11e8-81ab-2704750c074c.png)

Extension version: 0.1.1
VS Code version: Code - Insiders 1.28.0-insider (96854113091424c07b28ba84b82b75a88b8455cb, 2018-09-10T05:18:57.119Z)
OS version: Windows_NT x64 10.0.17134

**Comment by RMacfarlane** [comment]
Fixed by https://github.com/Microsoft/vscode-pull-request-github/pull/737
