### ISSUE TITLE
`NewIssue.md` is empty

### ISSUE THREAD

**Issue by ris58h** [microsoft/vscode-pull-request-github#4024]
- Extension version: v0.50.0
- VSCode Version: 1.71.2
- OS: macOS Monterey 12.6

When I click `Create an Issue` VSCode opens blank `NewIssue.md` file. First time it had some "fields" (Author, Title and so on) but now it's empty. Is it intended?
<img width="325" alt="Screenshot 2022-10-07 at 10 03 56" src="https://user-images.githubusercontent.com/511242/194465574-22c4dd43-6f77-4e4f-8374-241792f8d85a.png">

**Comment by alexr00** [comment]
And now I was just able to repro it.
