### ISSUE TITLE
User completion in commit box is wrong when manually triggered

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-pull-request-github#4026]
When typing `@`, I get suggestions for users, but once I typed a few characters pressing <kbd>Ctrl D</kbd> will show me issue suggestions.

![4eeea7ac-c585-4a7f-985d-f34366efa2c2](https://user-images.githubusercontent.com/22350/194566221-8bb0a9f1-083b-46bb-b45b-ad91344c3473.gif)

**Comment by alexr00** [comment]
I think if you scroll down in that issues list you'll see the users below the issues. Since it wasn't triggered by a trigger character we show both.

**Comment by joaomoreno** [comment]
Correct, they are all there. But why is this useful behavior? In other words, why do all those suggestions appear as possibilities for the `@sand` input? Scrolling down, not even `@sandy081` is highlighted in that case:

![image](https://user-images.githubusercontent.com/22350/195049732-c748ba54-39fa-48c6-a279-e46948f3a0bb.png)

**Comment by joaomoreno** [comment]
The bug seems to be that the filtering only happens from the moment the widget pops up (either automatically or manually). Notice this example:

![Recording 2022-10-11 at 11 17 22](https://user-images.githubusercontent.com/22350/195050265-8fde3841-0212-48da-b9ba-d517cb3cb46d.gif)

The widget only filters on the `moreno` sequence that I type after manually opening it and even fails to properly render highlights on user names. The expected behavior is: when manually opening it, it should be filtered on my initial input (`joao`) and should further filter down as I type the rest (`moreno`). This is exactly how it works in the editor:

![Recording 2022-10-11 at 11 20 20](https://user-images.githubusercontent.com/22350/195050977-c29c407d-f217-4b06-abe3-3b46cc0f56cc.gif)

**Comment by alexr00** [comment]
This occurs for all suggests, not just in the commit box.

**Comment by alexr00** [comment]
@jrieken I think `CompletionProvider` would need to add some support for this. Is there a way for an extension to tell the suggest widget what text before the cursor should be used for filtering?

**Comment by jrieken** [comment]
>  Is there a way for an extension to tell the suggest widget what text before the cursor should be used for filtering?

Yes, it the `CompletionItem#range` property.

**Comment by joyceerhl** [comment]
In a codespace and desktop RemoteHub I get user suggestions in the commit box, but I can't trigger suggestions automatically or manually in web at all.

**Comment by alexr00** [comment]
Opened https://github.com/microsoft/vscode-pull-request-github/issues/4119 to fix.
