### ISSUE TITLE
Polish Extension UI

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode-pull-request-github#4029]
Creating this polish issue to track a number of quick wins I think I/we can tackle. Some initial ideas:
- Full pass on all webview UI from typography to alignment
- See how we can bridge the gap from GH to VS Code design languages
- Polish comments input element to feel more like other inputs in VS Code 
- Explore introducing webview UI toolkit (ref #3035)

<img width="934" alt="CleanShot 2022-10-09 at 20 03 13@2x" src="https://user-images.githubusercontent.com/25163139/194793907-1871c922-cf0f-480e-8cf0-c2975f407da6.png">

<img width="315" alt="CleanShot 2022-10-09 at 20 03 28@2x" src="https://user-images.githubusercontent.com/25163139/194793899-2cc42f31-769e-48e5-8c00-8af187b2d26c.png">

<img width="558" alt="CleanShot 2022-10-09 at 20 06 59@2x" src="https://user-images.githubusercontent.com/25163139/194794113-45de0f43-ac70-4ff0-b837-7438ceb6ef65.png">

cc @digitarald

**Comment by digitarald** [comment]
cc @alexr00: any areas where you'd like to see design opportunities explored?

@daviddossett one aspect to pull in is how we represent actions, checks and statuses; happening in https://github.com/microsoft/vscode-pull-request-github/issues/681

**Comment by daviddossett** [comment]
That's a good point @alexr00. I think maintaining the general GH layout structure makes enough sense unless we have good reasons to change that.

As for the specific components and elements I feel like we can bias towards VS Code design language as a gut reaction.

It seems like we should also split this effort into two distinct parts:
1) UI polish (mostly CSS + perhaps swapping out components)
2) UX changes (like #681)

For `2`, I think it makes sense to track those in the specific issues. I'll happily help with that work, but I think the main focus of this issue is to polish what's already there.

**Comment by daviddossett** [comment]
Spent some time looking at the description page today to see how we could refresh the overall visual language and fix some responsive issues. This does not yet go into the weeds of how markdown and code is rendered within the feed. Just looking for at the overall impression to start.

A couple of things I'm trying to do:
- Visually align the header and metadata column (assignees, labels, etc.) with the extension detail page
- Clean up layout of header (button placement, typography, PR status tag, etc.)
- Modernize feed, checks, and metadata visual design
- Use Webview UI Toolkit components (buttons, icon buttons—especially for proper dimensions and feedback on hover/focus)

## Large Screen

<img width="1792" alt="CleanShot 2022-10-11 at 16 50 32@2x" src="https://user-images.githubusercontent.com/25163139/195218733-7cd0c297-28a1-485a-a775-4e08640df0bb.png">

## Small screen + details

<img width="1331" alt="CleanShot 2022-10-11 at 16 49 50@2x" src="https://user-images.githubusercontent.com/25163139/195218758-bedd7628-079e-4562-bd3b-4d6a6ec451b4.png">

<img width="1332" alt="CleanShot 2022-10-11 at 16 49 56@2x" src="https://user-images.githubusercontent.com/25163139/195218764-85cc6da8-cebb-4266-bc50-409ff73ff002.png">

<img width="899" alt="CleanShot 2022-10-11 at 16 50 05@2x" src="https://user-images.githubusercontent.com/25163139/195218774-61dfb1b4-36bc-4826-883e-ae47abf9b8d0.png">

<img width="634" alt="CleanShot 2022-10-11 at 16 50 16@2x" src="https://user-images.githubusercontent.com/25163139/195218784-1a6e91ef-1373-4405-8ff2-61ec4ff97659.png">

<img width="277" alt="CleanShot 2022-10-11 at 16 50 11@2x" src="https://user-images.githubusercontent.com/25163139/195218793-e633ce24-e00f-4217-9e14-eff511f1ffcd.png">

**Comment by digitarald** [comment]
@daviddossett good to see the extra care to check small screens. Maybe we can also check the design updates for these cases:

- Even smaller viewport: The design has a responsive breakpoint for moving the sidebar items on top of the description.
- How longer titles and lines (… wants to merge changes into …) break.

**Comment by daviddossett** [comment]
@digitarald addressed the second bullet in #4050. Will do the same for the sidebar 🙏

**Comment by daviddossett** [comment]
Closing this as finished since the bulk of this work has been done. Will track scoped polish items in their own issues going forward 👍
