### ISSUE TITLE
I cannot sign in to GitHub from VS Code

### ISSUE THREAD

**Issue by alexandair** [Microsoft/vscode-pull-request-github#403]
- Extension version: 0.1.1
- VSCode Version: 1.27.1
- OS: Windows 10 1803, build 17134.165

Steps to Reproduce:

1. There is a notification "In order to user Pull Requests functionality, you need to sign in to GitHub.com
2. When I click "Sign in", I immediately get "Error signing in to GitHub.com", Try again?
3. Trying again doesn't change anything

**Comment by RMacfarlane** [comment]
Potentially related: https://github.com/Microsoft/vscode-pull-request-github/issues/384

**Comment by shana** [comment]
This should be fixed in release 1.0.5

**Comment by FilipB-immalle** [comment]
fdf
