### ISSUE TITLE
Extension periodically refreshes the file under review, resetting the view position

### ISSUE THREAD

**Issue by RikkiGibson** [microsoft/vscode-pull-request-github#4031]
### Description

1. Install both GitHub Pull Requests (v0.50.0) and https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens (v12.2.2).
2. Open a pull request in the extension and begin reviewing a file
3. Proceed with review for about 1-2 minutes

Expected behavior: editor view position is only affected by user actions (e.g. navigation commands, scrolling)
Actual behavior: editor view position is periodically reset, disrupting the review.

Note that this behavior only occurs when *both* the GitLens and GitHub extensions are enabled. When I disable the GitLens extension, the bad behavior stops. I am not sure which extension is to "blame" in this scenario, so I'm taking the liberty of filing a bug both here and at gitkraken/vscode-gitlens#2259.

### VS Code Version

Version: 1.72.0 (user setup)
Commit: 64bbfbf67ada9953918d72e1df2f4d8e537d340e
Date: 2022-10-04T23:20:39.912Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

### Git Version

git version 2.30.0.windows.2

### Logs, Screenshots, Screen Captures, etc

This recording roughly shows the bad behavior, which occurs once every 1-2 minutes. Note that several different activity indicators are popping up in the left sidebar before the editor tab goes blank and refreshes.
![ghpri-refresh-bug-3](https://user-images.githubusercontent.com/5833655/194938256-59190ba8-7b50-4355-a923-06a379152ed1.gif)

**Comment by alexr00** [comment]
I haven't yet been able to reproduce this issue. I'll keep an eye out for it.

**Comment by alexr00** [comment]
And now I was just able to repro it.

**Comment by eamodio** [comment]
@alexr00 is this a GHPR issue?

**Comment by alexr00** [comment]
@eamodio I found a GHPR issue that caused it. I don't know why the issue would only repro with Gitlens. I would assume that was a fluke as it didn't occur 100% of the time for me.

**Comment by jpspringall** [comment]
Do you we know when this fix is going available in the insiders build?

As it also appears reset comments, which is a bit of a PITA :-)

**Comment by alexr00** [comment]
@jpspringall the fix has been in the pre-release build of the extension (which requires that you use VS Code Insiders) for about 2 weeks.
