### ISSUE TITLE
Prompt for sign in on activity bar?

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode-pull-request-github#4035]
Looking at a fresh install of GHPRI and was wondering if we should prompt for sign in in the activity bar accounts item? I'm not familiar with the API but thought I've seen other extension use it to similar effect.

<img width="381" alt="CleanShot 2022-10-10 at 16 38 13@2x" src="https://user-images.githubusercontent.com/25163139/194967901-9900b945-9c68-45ca-9acb-054c7d8af628.png">

<img width="361" alt="CleanShot 2022-10-10 at 16 40 19@2x" src="https://user-images.githubusercontent.com/25163139/194968076-8ab7f4a0-6a86-4b72-b12d-839a5b605b43.png">

**Comment by alexr00** [comment]
We deliberately don't do this because GHPRI is installed by default in vscode.dev and github.dev, and we didn't want to have the blue badge there out of the box.

**Comment by daviddossett** [comment]
Oh, TIL!
