### ISSUE TITLE
Long delay when opening PR categories in tree

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode-pull-request-github#4036]
I'm guessing this is the result of an API call, but I'm wondering if there are any quick wins to improve perf here? It's probably my #1 challenge when using the extension. Here's an example on a small repo with no PRs/issues associated with it yet:

![CleanShot 2022-10-10 at 16 45 46](https://user-images.githubusercontent.com/25163139/194968658-3c4e157d-7f1e-4ff9-9da5-a52b71a8f958.gif)

**Comment by alexr00** [comment]
I'll take a look and see if there are opportunities for improvement!

**Comment by alexr00** [comment]
I was able to remove one GitHub API call with https://github.com/microsoft/vscode-pull-request-github/pull/4080, but that wasn't the slowest call.

**Comment by daviddossett** [comment]
Closing given the work above. Feel free to re-open if there is more work planned here.
