### ISSUE TITLE
"Show Changes Since Last Review" is not working (endless loadind state)

### ISSUE THREAD

**Issue by CombeeMike** [microsoft/vscode-pull-request-github#4037]
- Extension version: `v0.50.0`
- VSCode Version: `1.72.0`
- OS: `Windows 10`

Steps to Reproduce:

1. Click on `Show Changes Since Last Review` button above tree of GitHub Pull Requests pane
2. The pane goes into loading state which never ends (Loading indicator in left bar and above tree):
  ![image](https://user-images.githubusercontent.com/30658772/195014581-041e6b93-f1be-4e46-bbee-869fa2d36e13.png)

This does always happen & the feature never worked for me yet.
Are there any logs I can give you?

FYI, there are other situations where I also get to this "infinite loading state" but I was not able to figure out what triggers them and therefore have no reproduction steps yet.

Whenever I'm in this state, the only way to get out of it is by restarting VSCode or using its "Reload Window" action.

**Comment by CombeeMike** [comment]
FYI, the extensions output pane is not showing any activity at all when clicking on the button:

https://user-images.githubusercontent.com/30658772/195016307-836af0fb-ceda-477a-8f76-a9d740c2fbc9.mp4

**Comment by alexr00** [comment]
@CombeeMike I tried this out and I haven't been able to reproduce the issue. Can you set `	"githubRepositories.logLevel": "debug"`, reproduce the issue, then share the output from GitHub Pull Request and the dev tools?

**Comment by CombeeMike** [comment]
@alexr00 Here's the output:

**Output Window:**
> [Debug 1667540625.082s] GitHubRepository> Fetch pull request 911 - enter
[Debug 1667540625.082s] RateLimit> API call count: 115 (PullRequest)
[Debug 1667540625.882s] RateLimit> Rate limit remaining: 4663
[Debug 1667540625.882s] GitHubRepository> Fetch pull request 911 - done
[Debug 1667540898.85s] GitHubRepository> Fetch pull request 911 - enter
[Debug 1667540898.85s] RateLimit> API call count: 116 (PullRequest)
[Debug 1667540899.738s] RateLimit> Rate limit remaining: 4662
[Debug 1667540899.738s] GitHubRepository> Fetch pull request 911 - done

**Dev Tools Console:**
![image](https://user-images.githubusercontent.com/30658772/199900923-c053c799-e186-4c6b-8605-0570e8f61c8b.png)

So it seems to be a rights issue. I just realized that I never really use VSCode itself for any kind of git actions with the remote like pull etc. because I perform them in the console, so I'd guess that I never setup the correct credentials etc. in VSCode itself 🙈.

This issue can be closed then I guess.
However, some info etc. from the extension would have been nice.

**Comment by alexr00** [comment]
> However, some better feedback from the extension would have been nice.

Agreed. I've added an error notification.
