### ISSUE TITLE
Frequent sign-in requests - although I am signed in

### ISSUE THREAD

**Issue by cfiderer** [microsoft/vscode-pull-request-github#4049]
Type: <b>Bug</b>

Scenario:

- I use VS Code with GHPRI on Windows and MacOS.
- I have Settings Sync turned on.
- I am logged on to GitHub, to our GitHub Enterprise and to Microsoft.
![2022-10-13_09-43-46 VSCode signed in](https://user-images.githubusercontent.com/40199723/195547808-822d055b-aac2-4530-a4c6-ed6c40e59147.png)

- GHPRI shows up in the "Manage Trusted Extensions" list only for GitHub.

Every few minutes, I get a pop-up:
![2022-10-13_09-43-46 VSCode signin request](https://user-images.githubusercontent.com/40199723/195547548-a284b5ea-ee36-4d7c-b29b-29fab3922e03.png)

When clicking "Allow", I get an authentication request in my browser, and I accept it. 

Nevertheless, the Pop-up comes up every some minutes, the frequency seems to increase when I have more than one instance of VS Code running.

When I turn off the "Settings Sync", the pop-up frequency seems to drop.

How can I get rid of these pop-ups?

Extension version: 0.50.0
VS Code version: Code 1.72.1 (129500ee4c8ab7263461ffe327268ba56b9f210d, 2022-10-10T17:22:48.346Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.70GB (7.40GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by alexr00** [comment]
Thanks for trying out the newly improved GitHub Enterprise support! A few questions:
- Do you have a folder with a GitHub Enterprise repository open?
- Can you share the output from GitHub Enterprise Authentication and GitHub Pull Request?
