### ISSUE TITLE
Add counter badge to each PR group

### ISSUE THREAD

**Issue by pke** [microsoft/vscode-pull-request-github#405]
Would be nice to have a badge next to each PR group (Local, Waiting for review, Assigned to me, Created by me and all) that shows the number of PR under this grouping.
Also the title itself could have a counter badge before the refresh button.

**Comment by voxpelli** [comment]
Especially so for the "Waiting for review" and "Assigned to me" – the ones that requires ones action specifically – would be good to be able to configure which groups that would have badges so one can pick oneself.

**Comment by pke** [comment]
Since moving to trunk based development this is no longer a concern for me ;)
