### ISSUE TITLE
Commit & Create PR failed to push new commit

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-pull-request-github#4055]
Repro:

1. Create a new branch
2. Create a commit on it
3. Publish the branch to the remote
5. Create another commit on it but this time use the `Commit & Create Pull Request` option from the SCM view

🐛 A PR will be created but only containing the first commit. I expected the second commit to have been pushed before creating the PR.

cc @lszomoru

**Comment by lszomoru** [comment]
@alexr00, do let me know if you need any assistance with this one. Thanks!

**Comment by alexr00** [comment]
Seems safe to push the branch when the "Commit & Create Pull Request" action is run.
