### ISSUE TITLE
Opened up a Codespace with a GH PR and was asked to sign in to GHES

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode-pull-request-github#4056]
I think this is because I have settings sync turned on and it picked up the GHES setting from when I was testing it out.

<img width="753" alt="image" src="https://user-images.githubusercontent.com/2644648/195899143-2678cb8c-7731-4d81-bd9b-b4bbc3363325.png">

I don't think this should happen in Codespaces at all.

**Comment by alexr00** [comment]
I think the GHES setting should probably a workspace only setting. @TylerLeonhardt what do you think?

**Comment by TylerLeonhardt** [comment]
@alexr00 I actually can't make it a workspace yet because I don't store the GHES uri with the session at the moment. Actually storing the GHES uri along with the session would probably be help in https://github.com/microsoft/vscode-pull-request-github/issues/3992#issuecomment-1287298096

**Comment by TylerLeonhardt** [comment]
@alexr00 as discussed we can't actually make something "workspace setting" only... so we'll need to handle this somehow.

**Comment by alexr00** [comment]
Hmm. Does it make sense to set this setting to not sync? I can also prioritize the "is github.com" check over the "has enterprise uri" check.

**Comment by TylerLeonhardt** [comment]
> Does it make sense to set this setting to not sync?

Can I do that while still allowing it to be set in workspace settings? I don't think so... @sandy081?

**Comment by sandy081** [comment]
Settings scoped to `machine` or  `machine-overridable` are not synced by default.
