### ISSUE TITLE
Flash of unlocalized content opening a PR

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-pull-request-github#4060]
1. Open a PR on insiders.vscode.dev
2. Notice a quick flash in the PR tree view:

<img width="275" alt="image" src="https://user-images.githubusercontent.com/2230985/195942400-3511da6c-ffee-4f82-985e-4bf068f570fd.png">

**Comment by alexr00** [comment]
Will be fixed by https://github.com/microsoft/vscode-pull-request-github/pull/4087
