### ISSUE TITLE
[checks view] Status icon gets smaller if check name needs to wrap

### ISSUE THREAD

**Issue by Thomas1664** [microsoft/vscode-pull-request-github#4064]
- Extension version: master
- VSCode Version: 1.72.2
- OS: Windows 10

Steps to Reproduce:

You should be able to reproduce by checking out any PR from microsoft/vcpkg-tool .

![image](https://user-images.githubusercontent.com/46387399/195952980-214af0ae-bfd2-40b2-b163-72501489c32e.png)

Additional context:

The issue occurred after #4052 was merged. CC @daviddossett

**Comment by daviddossett** [comment]
Nice catch. FWIW I expect to do a cleanup pass after these three PRs are in.
