### ISSUE TITLE
Width breakpoint issue on smaller devices

### ISSUE THREAD

**Issue by Thomas1664** [microsoft/vscode-pull-request-github#4067]
- Extension version: master
- VSCode Version: 1.72.2
- OS: Windows 10

Steps to Reproduce:

1. Using a 12 inch device
2. Resize left sidebar to ~236px

![image](https://user-images.githubusercontent.com/46387399/195977430-3b243ffa-9515-4c13-9c96-a2663a43359b.png)

Note that although @daviddossett increased the width to `1280px` in #4050 after I originally reported the issue in #4052 it turned out to be not caused by this change.

**Comment by daviddossett** [comment]
I'm not able to repro this. This looks unrelated to the width of the layout given that the main content is expanding indefinitely. Are you only seeing this on that specific device?

**Comment by Thomas1664** [comment]
> I'm not able to repro this. This looks unrelated to the width of the layout given that the main content is expanding indefinitely. Are you only seeing this on that specific device?

I only have one device (Surface Pro 7). Maybe you can reproduce it there.

**Comment by daviddossett** [comment]
And this was not happening before? I don't have access to that device so it will be hard for me to see the root cause. The main layout is using a grid with the main timeline content set to `1fr`. It should shrink until the content reflows if the sidebar is expanded.

**Comment by daviddossett** [comment]
> you either made the sidebar a bit wider or messed up the grid layout.

Happy to review a PR that solves for this. What I'm seeing in your screenshot is not possible for me to reproduce, even simulating a Pro 7 in dev tools. 

![CleanShot 2022-10-17 at 15 38 01](https://user-images.githubusercontent.com/25163139/196296759-127aeaa9-0044-488c-bde5-b0256213bcc8.png)

**Comment by daviddossett** [comment]
@Thomas1664 Could you share that particular PR with me? I fixed an issue in #4078 that could be related here.

**Comment by Thomas1664** [comment]
https://github.com/microsoft/vcpkg-tool/pull/695
