### ISSUE TITLE
Multiline commit message not rendered correctly in commits tree

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-pull-request-github#4074]
This is https://github.com/microsoft/vscode-jupyter/pull/11668

<img width="492" alt="image" src="https://user-images.githubusercontent.com/323878/196320300-1924c28d-5769-406c-9200-539297a05406.png">

**Comment by alexr00** [comment]
Upstream issue, which has a fix ready: https://github.com/microsoft/vscode/issues/163224
