### ISSUE TITLE
Add a button to iterate through all diffs in a review

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode-pull-request-github#4089]
Currently I have to iterate through all diffs in a file and after the last diff to go to the next file.

In Github, it is much easier to review all changes in a linear way.

It would be helpful if the experience in VS Code could be improved here, maybe with a button that iterates over all diffs in all files.

@alexdima

**Comment by alexr00** [comment]
Would you expect this button/command to be circular (go back to the first file once you've reached the last)?

I'm not sure what the right approach is. On the one hand, if you started reviewing from a file in the middle, then you would want it loop around to the first file. But then it would be very easy to not notice when you're back at the file that you started with.
