### ISSUE TITLE
Please show branch name and PR # in the list of pull requests or in tooltip

### ISSUE THREAD

**Issue by abierbaum** [Microsoft/vscode-pull-request-github#410]
It would be very helpful to be able to see the pull request number and branch name from the list of pull requests.  Currently to get to this information I think you have to expand the PR item and click on description.

The reason is for findability.  At least for our team we tend to refer to the PRs by the name of the branch or by PR numbers, not by the description line from the PR.  For example we have a CI system setup that sends messages to slack with a link to the PRs saying the build status.  This link includes the PR number and the branch name, but not the description.  

Ideas:
  * prefix the PR description in the list with the PR number.  (ex: "#1234: (bugfix) Fix nasty bug in backend"
  * Show branch name in the tooltip
  * Could allow users to configure what to show for name.  For our team we may go with PR #, branch name, message

**Comment by rebornix** [comment]
We already have this feature ;)
