### ISSUE TITLE
Improve `Create PR view` startup UX

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-pull-request-github#4100]
Every time I create a Pull Request I get a similar UX to this:

![Recording 2022-10-24 at 12 27 31](https://user-images.githubusercontent.com/22350/197506000-05ce9590-34de-4742-9584-26a73edce1c5.gif)

It appears that the view immediately renders to some previous state. In this example I had just created a PR from `joao/tall-elephant` 5 minutes prior, then checked a different branch `joao/widespread-tarantula` and tried creating a PR for it.

Some thoughts:

- If the view is loading, should it report progress somewhere in the UI?
- If the view is loading, should the UI elements be disabled and render some loading state instead?
- Even better, could we be smarter and render what we already know on first render? The local branch name is already known. I guess the loading is for the title and description mostly.

**Comment by alexr00** [comment]
@mjbvz if I set the `context` here should that get passed to by webview, or is that meant to be used to pass previous state of the webview to the extension?

https://github.com/microsoft/vscode/blob/b11bb04298ca55c73976cc820985a9b84792a9af/src/vscode-dts/vscode.d.ts#L8835-L8836

**Comment by mjbvz** [comment]
@alexr00 You should never need to set the context yourself, it should be set by VS Code. The `state` in the context is that `state` that you set inside the webview using `setState`: https://code.visualstudio.com/api/extension-guides/webview#persistence

**Comment by alexr00** [comment]
Makes sense, thanks @mjbvz.

Getting the commit info for the title and description is not fast and is the reason for the delay. We can add some loading animation.
