### ISSUE TITLE
Test localization

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#4103]
Refs: https://github.com/microsoft/vscode-pull-request-github/issues/3913

- [x] anyOS @TylerLeonhardt
- [ ] anyOS @joaomoreno

Complexity: 1

[Create Issue](https://github.com/microsoft/vscode-pull-request-github/issues/new?body=Testing+%234103%0A%0A&assignees=alexr00)

---

1. Install the pre-release build of the extension
2. Set your VS Code display language to something other than English (if you don't already have a language pack installed, you'll need to do so).
3. Verify that strings that come from this extension (but **not** the extension's webviews) are localized. Some ideas for strings to check: status bar entries, view titles, welcome view content, command titles.

**Comment by TylerLeonhardt** [comment]
It would be worthwhile to test this on both Desktop & Web since it should work in both places now. FYI @joaomoreno

**Comment by TylerLeonhardt** [comment]
@alexr00 I have opened https://github.com/microsoft/vscode-pull-request-github/pull/4107 to add more strings that I noticed weren't being localized.

**Comment by joaomoreno** [comment]
Tested both https://insiders.vscode.dev as well as Windows x64 desktop.

**Comment by joaomoreno** [comment]
@TylerLeonhardt, @rzhao271, I noticed some extensions have their names translated in the Settings view. What's your preference here?

![image](https://user-images.githubusercontent.com/22350/197737801-8439c8ca-3a40-4d73-95b3-cc3b1f5b691f.png)

The extension itself is translated in some places:

![image](https://user-images.githubusercontent.com/22350/197737891-42e30f0d-4368-41f6-9d4f-760f694c0017.png)

But not others:

![image](https://user-images.githubusercontent.com/22350/197737950-dfa358ed-40ba-4ec6-a06a-10e1eef5c886.png)

**Comment by rzhao271** [comment]
I don't mind more of the program being translated.
