### ISSUE TITLE
Mutiroot workspace: creating PRs for different workspace should not reuse description webview

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-pull-request-github#4106]
* Create a multi root workspace with two repositories
* Make changes to both repositories and create PR
* Creating the first PR opens a description webview
* Creating the second PR for another repo updates the content of the preview PR

IMHO in multi root workspace, PRs for different repos should not share the same webview.

**Comment by alexr00** [comment]
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/3058
