### ISSUE TITLE
Strange `undefined` logging in Output

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-pull-request-github#4109]
My output for GHPRI has these log messages:

![image](https://user-images.githubusercontent.com/22350/197759063-cd6f2cbb-49ef-42a3-aa7f-ce68aa339ac7.png)

**Comment by IanMatthewHuff** [comment]
I'm on today's insiders with Pre-release GitHub Pull Requests and Issues and I still see these:

<img width="1001" alt="image" src="https://user-images.githubusercontent.com/812783/198359796-fa80fe38-b7ec-420f-bb47-61ad469aa370.png">

Versions:
<img width="259" alt="image" src="https://user-images.githubusercontent.com/812783/198359933-c534c8a3-326b-46ba-87d6-79cc3f4a3156.png">
<img width="788" alt="image" src="https://user-images.githubusercontent.com/812783/198359982-26bfb0f0-dc90-4646-b4be-44ea8f66a690.png">
