### ISSUE TITLE
Extension says I'm not signed in when cloning using Gitlab.com

### ISSUE THREAD

**Issue by mrleblanc101** [microsoft/vscode-pull-request-github#4111]
Clone a Github project, open the Github pannel, everything work.
Clone a Gitlab project, open the Github pannel, it says I'm not sigged in.

This is confusing as I am siggned-in. It's simply that this project is unsupported.
The message error message should reflect that and say something like "Unsupported Git project. This is not a Github project."

**Comment by alexr00** [comment]
@mrleblanc101 I'm sad to say that I don't know of a way to tell the difference between a GitHub Enterprise project and a non-GitHub (for example, Gitlab) project. A GitHub Enterprise server can have any URL and might not respond to unauthenticated requests in a known way. 

There are a few known urls that we can check for here though, like bitbucket.org and gitlab.com. For those we can know that they're not GitHub Enterprise and avoid showing the sign in.

**Comment by mrleblanc101** [comment]
Yes, I think that would be a good start. Maybe don't match "gitlab.com" and match any URL that contain Gitlab.

For exemple, the company I work for has a self-hosted Gitlab which is `gitlab.company-name.com`.

**Comment by alexr00** [comment]
Theoretically, `gitlab.company-name.com` could be a GitHub Enterprise server. 

Instead of showing the sign in buttons we'll show our standard message about how none of the remotes for the repo are GitHub remotes. There's still room for improvement on the message there.

**Comment by aeschli** [comment]
The message now says: `No remote matches the current setting`



![Image](https://user-images.githubusercontent.com/6461412/204846007-f7a2bfe8-86ed-4e20-a55c-35d6809adaa3.png)
