### ISSUE TITLE
GHPR view shows two `...` menus

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode-pull-request-github#4114]
Also:

![image](https://user-images.githubusercontent.com/2193314/192626354-0bafaaa1-5eae-41e9-8617-c19ed287b0d6.png)

Could we consolidate them in a single menu with a separator?

cc @sbatten @daviddossett

_Originally posted by @Tyriar in https://github.com/microsoft/vscode/issues/162006#issuecomment-1259998688_

**Comment by andreamah** [comment]
still seeing this when hiding a button or two:

<img alt="image" src="https://user-images.githubusercontent.com/31675041/198160221-e28c374c-0993-492f-a870-a6e5fd23c9d0.png">

**Comment by alexr00** [comment]
New pre-release build wasn't available yet.

**Comment by TylerLeonhardt** [comment]
@alexr00 when will a new pre-release be available to test?

**Comment by alexr00** [comment]
New version is available now.
