### ISSUE TITLE
Create issue fails in non-english case

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode-pull-request-github#4116]
While verifying https://github.com/microsoft/vscode-pull-request-github/issues/4027, I noticed that the Assignees and Tags text are localized. When trying to create the issue, it fails to parse properly but I'm not sure why. I'm guessing it should not be localized or we need better string comparison.

<img width="245" alt="image" src="https://user-images.githubusercontent.com/6561887/198113062-1f0d5120-262b-42d7-a9a7-a313e3a46d30.png">

<img width="317" alt="image" src="https://user-images.githubusercontent.com/6561887/198113256-cd334a95-cd71-449a-bfbb-11b54c472670.png">

**Comment by alexr00** [comment]
@TylerLeonhardt is there a way I can force VS Code to use the localized strings for a locally build extension that I'm debugging?

**Comment by TylerLeonhardt** [comment]
This is fairly simple to do with the pseudolanguage command:

```
npx @vscode/l10n-dev export -o l10n ./src
npx @vscode/l10n-dev generate-pseudo -o ./l10n/ ./l10n/bundle.l10n.json ./package.nls.json
```

Then you run vscode using the pseudo language pack and your debugged extension should be translated.

alternatively, fetch the respective `package.nls.*.json` and `./l10n/bundle.l10n.*.json` from your release of GHPR and put them in those places in your repo and just make sure you run vscode with the `*` language pack. Whatever language you wanna use.

**Comment by alexr00** [comment]
I tested with French, and I wasn't able to reproduce the issue. @sbatten is there anything in the console when this happens?

**Comment by sbatten** [comment]
Cannot reproduce today, was reliable yesterday 🤷🏻 will take a look again if it comes back
