### ISSUE TITLE
PR view gets stuck in loading view and requires refresh to show async details

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode-pull-request-github#4118]
Oftentimes a PR when opened first will check if it can be merged. On the GH website, this information is fetched in the background and the mergable state quickly updates.

In VS Code's PR view this often leads to a stale merge state that lacks the merge buttons:

<img width="644" alt="image" src="https://user-images.githubusercontent.com/8599/198164216-e52603a8-3e65-4d8e-9ba2-a71e8dca3eaf.png">

I had cases where it took a fresh refreshs to get out of this state.

**Comment by eleanorjboyd** [comment]
I tried to verify this but was unable to repro the message "checking if this branch can be merged"

**Comment by alexr00** [comment]
Verification steps:
1. Install the pre-release version of the extension
2. Open a folder that's a clone of a GitHub repository with PRs and that has some kind of branch protection on the main branch. The microsoft/vscode repo works well for this.
3. In the Pull Requests view, repeat the following several times:
  a. Expand a PR
  b. Open the description
  c. Scroll to the bottom and verify that if you see the "checking if this branch can be merged" message that it goes away on it's own in a second or two. Or, verify that you never see that message (meaning that the state was fetched and displayed quickly).

**Comment by joao-casas-fernandes-NOS** [comment]
It's happening to our repository on some PRs, right now. Is this related to the outage that occurred 2 weeks ago? Is anyone else having the same issues?

**Comment by oreqizer** [comment]
yep happens to me too for the past 2 hours
