### ISSUE TITLE
"Copy github permalink" is using a link to a remote

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-pull-request-github#4135]
This just started happening- I think it usually links to `microsoft/vscode`

- Run "Github Issues: Copy Github Permalink"
- I get a link like https://github.com/Balastrong/vscode/blob/38ced53c0ba769b228f2396e5078c442c09199e3/src/vs/workbench/services/search/browser/searchService.ts#L187

Did I change a setting or something by mistake?

**Comment by alexr00** [comment]
Do you currently have a PR from that remote checked out?

**Comment by roblourens** [comment]
Nope
