### ISSUE TITLE
Support notebooks for permalink commands

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-pull-request-github#4143]
1. Open https://insiders.vscode.dev/github.com/bamurtaugh/python-tuples/blob/614d461702fe41eb06db69165df4774dea4e1b28/Tuples.ipynb
2. `Copy GitHub Permalink`
3. :bug: GHPRI says the file isn't part of the repo

**Comment by alexr00** [comment]
Not specific to RemoteHub as there's no active text editor in desktop local either.
