### ISSUE TITLE
Error signing in to Github. Try Again doesn't try again

### ISSUE THREAD

**Issue by sguilliaci** [microsoft/vscode-pull-request-github#4148]
- Extension version: v0.54.0
- VSCode Version: 1.73
- OS: macOS 12.3

I'm unable to log in with the extension.

<img width="535" alt="Capture d’écran 2022-11-03 à 15 04 50" src="https://user-images.githubusercontent.com/100221771/199743239-b778a72d-b91a-4d3b-9b2e-6075f2458fc1.png">

The Try Again button doesn't even attempt to open the browser in order to perform the standard login flow.

This is what I did:

1. Install the extension
2. Log in with an account part of an org that enforces SAML without granting that org.
3. Observe the following error message which is expected:

 > Fetching pull requests failed: Resource protected by organization SAML enforcement. You must grant your OAuth token access to this organization.

4. Look through this repo issues to find out how to fix the issue (feature request: please add a button to fix this problem)
5. Revoke the app in github.com
6. Observe "bad credentials" in the extension
7. Uninstall the extension
8. Install the extension again
9. Observe "Error signing in to GitHub"

How can I perform the regular login flow?
Thank you

**Comment by joyceerhl** [comment]
@alexr00 could we have an action to `Reauthenticate` on this error notification?

![image](https://user-images.githubusercontent.com/30305945/214952018-3466079a-9ef2-40e9-b942-81a6ab817b42.png)

**Comment by alexr00** [comment]
👍 https://github.com/microsoft/vscode-pull-request-github/issues/4471
