### ISSUE TITLE
Git Hub User Per Workspace

### ISSUE THREAD

**Issue by scrossan-crown** [microsoft/vscode-pull-request-github#415]
I work on my personal and work projects on the same machine and would like to be able to use a different user specified by a setting per workspace in the same way that extensions can be disabled per workspace.

**Comment by alexr00** [comment]
@TylerLeonhardt is this possible using just the auth UX? I think the answer is no, but I wanted to check.

**Comment by TylerLeonhardt** [comment]
GitHub doesn't support multiple accounts at the moment:

https://github.com/microsoft/vscode/issues/127967

**Comment by alexr00** [comment]
Duplicate of the upstream https://github.com/microsoft/vscode/issues/127967 then.
