### ISSUE TITLE
feature: support search in branch name when creating a new pull request

### ISSUE THREAD

**Issue by xianshenglu** [microsoft/vscode-pull-request-github#4153]
As for the title, when creating a new pull request, we can not search branch names in the branch name select.

Because we have lots of branches, even if we don't have lots of branches it will also be helpful to have this function.

![image](https://user-images.githubusercontent.com/23273077/199945502-8dffc985-ed00-453e-9b14-d3d701a28d1b.png)

**Comment by alexr00** [comment]
If expand the drop down and just start typing it will filter.

**Comment by xianshenglu** [comment]
@alexr00 I tried, no. Can you show me a gif or video that proves it is?

**Comment by alexr00** [comment]
Sure, here I typed "alexr00"

![Recording 2022-11-17 at 14 15 23](https://user-images.githubusercontent.com/38270282/202456411-84b56150-c686-4fc6-a212-4384a17d1a38.gif)
