### ISSUE TITLE
Cannot load avatars from GitHub Enterprise URLs

### ISSUE THREAD

**Issue by lumaxis** [microsoft/vscode-pull-request-github#416]
- Extension version: 0.1.2
- VSCode Version: 1.28.0-insider
- OS: macOS 10.13.6

Steps to Reproduce:

1. Open a Pull Request from a GitHub Enterprise repo
2. Add a PR comment

Screenshot:

<img width="252" alt="image" src="https://user-images.githubusercontent.com/406937/45371435-df696080-b5ea-11e8-9682-78f16fe998a7.png">

This is likely because the `user.avatar_url` is used without authentication.

**Comment by shana** [comment]
Ah, enterprise avatars. There's some scenarios where retrieving avatars from enterprise will always fail regardless of authentication, and others where it will potentially spam the enterprise instance repeatedly if there are a lot of avatars to load - enterprise has a very short cache time for avatars (so they'll update quickly when you change them), which is a problem for clients loading them without caching.

GitHub Desktop has some workarounds for this in https://github.com/desktop/desktop/blob/master/app/src/lib/gravatar.ts and related calls.

**Comment by lumaxis** [comment]
Personally, I would even prefer not showing an avatar at all if it's not possible to load the actual one. This placeholder is not very pretty.

**Comment by StanleyGoldman** [comment]
Just to document what isn't working

![image](https://user-images.githubusercontent.com/417571/56305166-b45d6700-610d-11e9-902c-cf5542018d55.png)

**Comment by ELLIOTTCABLE** [comment]
This is still occuring for me in Nightly, several years later?

Based on #1148, it looks like VScode shouldn't even be *attempting* to load an avatar — and yet it still is:

<img width="186" alt="Screen Shot 2022-04-13 at 3 39 10 PM" src="https://user-images.githubusercontent.com/200/163266487-19dca9f0-bd5c-4625-80a7-0b3d0b9fb688.png">
