### ISSUE TITLE
Details PR view in sidebar stuck in "Loading ..."

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode-pull-request-github#4161]
Type: <b>Bug</b>

Occasionally the details in the sidepanel don't load and require hitting the reload button on the panel. No errors in the DevTools console.

The last times this happened was desktop VS Code running against a Codespace.

<img width="406" alt="image" src="https://user-images.githubusercontent.com/8599/200188006-c9e6fb61-88f4-4706-a27c-817d353e5b0d.png">

Extension version: 0.55.2022110309
VS Code version: Code - Insiders 1.74.0-insider (e764c5b816a99eb8673b2fc4fc028827f202872f, 2022-11-04T05:19:54.097Z)
OS version: Darwin x64 22.1.0
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.4.0-1094-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|6, 4, 3|
|Memory (System)|64.00GB (6.02GB free)|
|Process Argv|--enable-proposed-api donjayamanne.kusto --log trace --crash-reporter-id 4cf0a6f0-aaf8-4da3-9b2b-81f6c639c12b|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Codespaces|
|OS|Linux x64 5.4.0-1094-azure|
|CPUs|Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz (4 x 2793)|
|Memory (System)|7.77GB (5.61GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vscaac:30438845
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pylantcb52:30590116
vscccc:30564267
pyindex848cf:30577859
nodejswelcome1:30587009
gswce1:30602633
34cci188:30599831
iaj6b796:30602301
pyind779:30600159
dbltrim-noruby:30604474

```

</details>

**Comment by connor4312** [comment]
@digitarald can you verify whether you've seen this since the fix (3 weeks ago)?

**Comment by digitarald** [comment]
Yes, have not seen it in my PRs since.
