### ISSUE TITLE
PR view was blank

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode-pull-request-github#4164]
Not sure how I got here but felt like I should document it 

<img width="792" alt="image" src="https://user-images.githubusercontent.com/4544166/200396613-143976b5-52fd-469d-b073-68222ea34d75.png">

**Comment by lramos15** [comment]
Reloading didn't fix this, this PR had to be made on github.com

**Comment by roblourens** [comment]
Same

**Comment by alexr00** [comment]
This is the Create view? Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/4174
