### ISSUE TITLE
Issue autocomplete breaks after unexisting issue number

### ISSUE THREAD

**Issue by ris58h** [microsoft/vscode-pull-request-github#4166]
- Extension version: v0.54.0
- VSCode Version: 1.73.0
- OS: MacOS Ventura

Steps to Reproduce:

1. Type `#` and then an unexisting issue number in Commit Message field.
2. Delete the issue number (but not `#`) using `Backspace`.
3. Type an existing issue number.
4. Autocomplete is broken now.

https://user-images.githubusercontent.com/511242/200513854-3713d922-c156-464e-848d-d189e7e9d757.mov

**Comment by alexr00** [comment]
This is how VS Code suggest works, even for other suggestions and suggest locations.

**Comment by alexr00** [comment]
@jrieken in case I'm missing something.

**Comment by ris58h** [comment]
> even for other suggestions and suggest locations
@alexr00 I've checked HTML tag autocomplete. It works as expected and doesn't break after invalid tag name. Did I miss something?

https://user-images.githubusercontent.com/511242/204447097-303d4df0-7194-46c6-84d9-ebc448bb92b7.mov

**Comment by ris58h** [comment]
@alexr00 thank you for detailed explanation. Should I create an issue in VSCode instead?

**Comment by alexr00** [comment]
I would wait to hear the response to https://github.com/microsoft/vscode-pull-request-github/issues/4166#issuecomment-1329367405 first.

**Comment by jrieken** [comment]
Yes - automatically triggered suggestions (e.g those that just show up while typing) hide when not having a match. @ris58h you can counter this by manually suggesting completions via ctrl+space in that mode the UI won't hide when typing something that doesn't match
