### ISSUE TITLE
Create Pull-Request shows up empty in pre-release version 0.55.2022110809

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode-pull-request-github#4167]
- execute `Create Pull request`
- observe:
   The Changes in Pull Request #xxxx viewlet (the upper part) comes up emty

**Comment by dbaeumer** [comment]
@sandy081 FYI

**Comment by andreamah** [comment]
I also see an empty viewlet

<img width="457" alt="image" src="https://user-images.githubusercontent.com/31675041/200644869-038c457b-0f49-4d13-b58e-1dd8ca7acff2.png">

**Comment by lramos15** [comment]
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/4164

**Comment by dbaeumer** [comment]
Closing as dup then.
