### ISSUE TITLE
Change order of autocomplete for having [FIX|REF|...] #<ID> <TITLE> (issue linking)

### ISSUE THREAD

**Issue by henry2man** [microsoft/vscode-pull-request-github#4170]
Change the order in issue autocomplete from "<TITLE> #ID" to "#ID <TITLE>" in order to allow proper issue linking (https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)

- Extension version: 0.54.0
- VSCode Version: 1.73.0
- OS: MacOS Ventura

Steps to Reproduce:

1. Checkout a Github repo with open issues
2. Make some changes
4. Go to Source Code changes section
5. You want to "FIX" this issue using the formulae "FIX #ID", so you write "FIX #"
6. The issue autocomplete shows, so you select the desired issue
7. When you autocomplete you have "FIX <TITLE> #ID", so this breaks issue linking in github (https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)

**Comment by alexr00** [comment]
There's a setting to configure this: `githubIssues.issueCompletionFormatScm`
