### ISSUE TITLE
Comment on a Jupyter Notebook

### ISSUE THREAD

**Issue by serghiou** [microsoft/vscode-pull-request-github#4178]
I love how I can see a Jupyter Notebook in VS Code PR requests in a familiar format. However, I cannot add any comments to this code, unlike code from other files (e.g., .py). I wonder if adding comments to Notebook files in a PR could be made available. Thanks very much in advance!

**Comment by alexr00** [comment]
duplicate https://github.com/microsoft/vscode-pull-request-github/issues/3462
