### ISSUE TITLE
After installing, I don't see the PR panel, not prompted to login, as if nothing happened

### ISSUE THREAD

**Issue by JonathanGes** [Microsoft/vscode-pull-request-github#418]
- Extension version: 0.1.2
- VSCode Version: 1.27.1
- OS: OS X High Sierra 10.13.4

Steps to Reproduce:

1. Go to extensions tab.
2. Install GitHub Pull Requests extension.
3. Reload VS Code.
4. Go to SCM.

Result:

1. All that's available is the Sourec Control Providers and the Changes under it.

Expected:

1. The Pull Request panel is shown there as well.

**Comment by RMacfarlane** [comment]
@JonathanGes Thanks for reporting!

I assume you have a repository open with some remote that points to GitHub, correct?
Can you include the log that's in the output panel, seen by selected `Github Pull Request` from the dropdown?

**Comment by ricard0ff** [comment]
having this issue as well, I do have remotes in github, the output does not show any errors.

**Comment by RMacfarlane** [comment]
Could you share the output of `git remote -v`? I want to make sure that there's no issue in parsing them.

Even though there's no error in the logs, they should give some indication of what code was reached

**Comment by felixfbecker** [comment]
Having the same problem. Output of `git remote -v`:
```
origin  github.com:sourcegraph/codeintellify (fetch)
origin  github.com:sourcegraph/codeintellify (push)
```

In the output panel I see
```
Looking for git repository
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
Git repository found, initializing review manager and pr tree view.
> git config --local --get branch.master.github-pr-owner-number
Review> no matching pull request metadata found for current branch master```

**Comment by JonathanGes** [comment]
> @JonathanGes Thanks for reporting!
> 
> I assume you have a repository open with some remote that points to GitHub, correct?
> Can you include the log that's in the output panel, seen by selected `Github Pull Request` from the dropdown?

Looking for git repository
> git symbolic-ref --short HEAD
> git rev-parse HEAD
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
Git repository found, initializing review manager and pr tree view.

**Comment by jamonkko** [comment]
For some, this might also be just UX problem. At least I was wondering why I don't have that PR panel but it was just at the very bottom of the `Source Control` tab. Maybe if that accordion component would not render closed items to bottom it would be easier to spot! :)

I actually found it by accident when clicking the item that has `Changes` in it which collapsed that item and magically the PR item appeared below it! (it was of course visible all the time, just at the bottom and I missed it)

**Comment by JonathanGes** [comment]
Doesn't seem to be the same issue (unless i'm missing something):
<img width="308" alt="screen shot 2018-09-11 at 20 12 09" src="https://user-images.githubusercontent.com/13386629/45375925-1a758f00-b5ff-11e8-9243-75b891e49cc4.png">

**Comment by RMacfarlane** [comment]
I have a repro using the remote @felixfbecker provided. Thanks! We're not handling remotes of that format correctly. If you append `@git` to the beginning so that it's `git@github.com:sourcegraph/codeintellify`, the panel should show up

**Comment by JonathanGes** [comment]
Would this solve it for this case as well?
```
Jonathans-MacBook-Pro:ControlRoom jonathangescheit$ git remote -v
origin  https://JonathanGes@github.com/Wibbitz/ControlRoom.git (fetch)
origin  https://JonathanGes@github.com/Wibbitz/ControlRoom.git (push)
```

Where do i edit it? (Perhaps it was created this way because of Tower Git)

**Comment by RMacfarlane** [comment]
You can run `git remote remove origin` and then `git remote add origin https://github.com/Wibbitz/ControlRoom.git` to change it. I'll have a fix soon

**Comment by felixfbecker** [comment]
Or just `git remote set-url origin`.

**Comment by ricard0ff** [comment]
@RMacfarlane 
```
PS C:\Users\rsFF\Documents\Projects\mouldy> git remote
origin
upstream
PS C:\Users\rsFF\Documents\Projects\mouldy> git remote -v
origin  git@github.com:ricard0ff/mouldy.git (fetch)
origin  git@github.com:ricard0ff/mouldy.git (push)
upstream        git@github.com:ricard0ff/mouldy.git (fetch)
upstream        git@github.com:ricard0ff/mouldy.git (push)
```

**Comment by JonathanGes** [comment]
@RMacfarlane Yes 👍

**Comment by JonathanGes** [comment]
@RMacfarlane Is there a workaround when there's multiple folders open? Thanks!

**Comment by ricard0ff** [comment]
@RMacfarlane this along with the others were closed, so whats the fix for our case, just have one folder open at a time?

**Comment by RMacfarlane** [comment]
We haven't yet added support for multiple folders (tracked here: https://github.com/Microsoft/vscode-pull-request-github/issues/386). The extension currently only looks at the first folder, so if this has no GitHub remotes, nothing would be shown. Opening one folder at a time is a workaround, we'll work on the support for multiple soon. Sorry for the inconvenience!

**Comment by btkfrank** [comment]
I got the similar issue that Github Pull Requst Tab not even show up.

here is the screenshot for the PR in web
![image](https://user-images.githubusercontent.com/5600309/46699415-bdfa9500-cbe7-11e8-93c6-cbf8cee554de.png)

I am on windows 7 using gitbash in VSCode terminal

VSCode: 1.28.0
Github Pull Request extension: 0.1.7
we are using github on-premises AKA github enterprise

```
YYang@NB-DTP-320 MINGW64 /c/Code/ng/Web/NetBrainNGClient/src/NetBrainNG (7.1b)
$ git remote -v
origin  https://git.netbraintech.com/dev/ng.git (fetch)
origin  https://git.netbraintech.com/dev/ng.git (push)
```

In my Output tab, I got this
```
Looking for git repository
> git symbolic-ref --short HEAD
> git rev-parse 7.1b
> git rev-parse --symbolic-full-name 7.1b@{u}
> git rev-list --left-right 7.1b...refs/remotes/origin/7.1b
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
Git repository found, initializing review manager and pr tree view.
No GitHub remotes found
> git config --local --get branch.7.1b.github-pr-owner-number
Review> no matching pull request metadata found for current branch 7.1b
```

**Comment by stoinov** [comment]
I too have similar issue. I had multiple folders, but I can see that they have been fixed. Even though I removed them and tested just with one. I cloned with Git Desktop and by command line - same result.
**VSCode**: 1.28.2
**Extension**: 0.2.1
**GitHub**: 2.14.5 Enterprise

```
PS C:\Users\user\Documents\GitHub\Repo> git remote
origin
PS C:\Users\user\Documents\GitHub\Repo> git remote -v
origin  https://github.domain.com/Name/Repo.git (fetch)
origin  https://github.domain.com/Name/Repo.git (push)
```
As for the response on pull:
```
> git pull --tags -r origin master
From https://github.domain.com/Name/Repo
 * branch            master     -> FETCH_HEAD
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
```

**Comment by adieldar** [comment]
Same problem. Pull Request panel not shown

**Comment by danielmrussell** [comment]
Same in 2019.

**Comment by RMacfarlane** [comment]
@danielmrussell Can you please open a new issue and include the following information

1. Version of VSCode and if this is the official VSCode build or VSCodium, arch linux community build, etc.
2. Version of the extension
3. Result of running `git remote -v` in the folder you currently have open
4. Anything in the output channel of the extension (Choose "GitHub Pull Requests" from dropdown on the output panel)

**Comment by danielmrussell** [comment]
I discovered that it's due to the setting "Show in SCM," which older
documentation that dominates search results on Google do not mention and
assume that's how it's done by default.
