### ISSUE TITLE
PR Panel isn't Showing

### ISSUE THREAD

**Issue by scrossan-crown** [Microsoft/vscode-pull-request-github#419]
I've logged in and it showed up the first time I installed the extension. It's now not showing up at all.

Extension output:
```
Looking for git repository
> git symbolic-ref --short HEAD
> git rev-parse 61_account
> git rev-parse --symbolic-full-name 61_account@{u}
> git rev-list --left-right 61_account...refs/remotes/origin/61_account
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
Git repository found, initializing review manager and pr tree view.
> git config --local --get branch.61_account.github-pr-owner-number
Review> no matching pull request metadata found for current branch 61_account
```
There is defiantly a pr for this branch, see image below.

![image](https://user-images.githubusercontent.com/30405149/45374071-f4dd8b00-b5e8-11e8-8f36-7f329b33257e.png)

- Extension version: 0.1.2
- VSCode Version: 
```
1.27.1
5944e81f3c46a3938a82c701f96d7a59b074cfdc
x64       
```
- OS: Windows

![image](https://user-images.githubusercontent.com/30405149/45374139-28201a00-b5e9-11e8-836e-0524d90ed0a1.png)

Steps to Reproduce:

1. Install `Git Hub Pull Requests` extension sign in and have an issue showing pr's in the panel
2. Restart vscode to see if it helps, pr panel doesn't show in SC Panel

**Comment by RMacfarlane** [comment]
@scrossan-crown Thanks for all of the details. What's the output of running `git remote -v` in that repository?

**Comment by cmackenz** [comment]
@RMacfarlane seems to be an issue when vscode workspaces. Opening up a single repo works as expected, opening a workspace does not.

**Comment by scrossan-crown** [comment]
@RMacfarlane 
```
$ git remote -v
origin  https://github.com:/thecrowngroup/tenogo-web (fetch)
origin  https://github.com:/thecrowngroup/tenogo-web (push)
```

@cmackenz I'm having the same issue if I open one of the folders on it's own in vscode
```
Looking for git repository
> git symbolic-ref --short HEAD
> git rev-parse 61_account
> git rev-parse --symbolic-full-name 61_account@{u}
> git rev-list --left-right 61_account...refs/remotes/origin/61_account
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
Git repository found, initializing review manager and pr tree view.
> git config --local --get branch.61_account.github-pr-owner-number
Review> no matching pull request metadata found for current branch 61_account
```

![image](https://user-images.githubusercontent.com/30405149/45386026-3cc0da00-b60a-11e8-94c2-efeca19b7618.png)

**Comment by scrossan-crown** [comment]
After looking around in a couple of other issues I've found the issue was the format of my remote url. Would it work if I had origin using `ssh` format and another remote using the `https://` format?

**Comment by scrossan-crown** [comment]
It's working now thanks. I'm really liking using it. I have a huge pr to review and it's making things so much easier. I'm going to use another remote name for ssh until it's supported
