### ISSUE TITLE
Let the section headers be clickable as well

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-pull-request-github#4196]
GH supports to click on e.g. "Milestone"

<img width="415" alt="image" src="https://user-images.githubusercontent.com/900690/202113957-e49834c3-7cae-4e7b-9462-459e7fbe1c3c.png">

//cc @daviddossett

**Comment by daviddossett** [comment]
I like the idea. I suppose that means making the entire section header effectively a button and styling the children on hover/focus/etc. vs just the icon button.

**Comment by alexr00** [comment]
To verify:

1. Install the pre-release version of the extension
2. Open a pull request overview/description
3. Verify that click the Reviewer, Assignees, Labels, and Milestone headers are clickable and open their respective pickers.

**Comment by bpasero** [comment]
@alexr00 works great, but should the link render like all the other links, with hover feedback and underline?

**Comment by alexr00** [comment]
@bpasero I'm not sure. I don't think the underline looks good, but there should maybe be some hover feedback. GitHub changes the color of the text. @daviddossett do you have any thoughts on this?
