### ISSUE TITLE
Prompt to sign in is too eager

### ISSUE THREAD

**Issue by ramya-rao-a** [microsoft/vscode-pull-request-github#420]
Issue Type: <b>Bug</b>

Looks like the extension gets activated on start-up. And so, the prompt to sign in to github appears as soon as a workspace is opened.

I might have opened the workspace with no intention of using the PR extension. In this case, the prompt would be annoying.

Can we instead have the prompt show up when any of the PR related commands are run or when the git viewlet is opened?

Extension version: 0.1.1
VS Code version: Code - Insiders 1.28.0-insider (96854113091424c07b28ba84b82b75a88b8455cb, 2018-09-10T05:18:57.119Z)
OS version: Windows_NT x64 10.0.17134

**Comment by alexr00** [comment]
I think this is fixed now.
