### ISSUE TITLE
Include Changelog

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode-pull-request-github#421]
Since we are updating this extension very often, it would help users who don't have auto-update of extensions enabled to know what changes are coming in each update.

Having a Changelog.md file is all it takes for the changelog to appear in the extensions editor in VS Code

**Comment by RMacfarlane** [comment]
@rebornix just added this yesterday 👍 https://github.com/Microsoft/vscode-pull-request-github/commit/8a5ebbb589c61cdc039df1f3163aa20b485d563e

**Comment by ramya-rao-a** [comment]
@rebornix Text like `Fix for https://github.com/Microsoft/vscode-pull-request-github/issues/395` will appear as is because this is markdown.

I would suggest to change it to `Fix for [Bug 395](https://github.com/Microsoft/vscode-pull-request-github/issues/395)`
