### ISSUE TITLE
Mimic GitHub PR sidebar click areas

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-pull-request-github#4210]
On GitHub these entire areas are clickable. This is one of those issues that I hit pretty much daily but never really got around to file it, it's just so etched in my muscle memory.

![image](https://user-images.githubusercontent.com/22350/202553879-c4bacdca-9928-4fa8-b5b1-a2c7fc1fe87b.png)

**Comment by alexr00** [comment]
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/4196
