### ISSUE TITLE
Copying a permalink fails for a repo with an SSH remote

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-pull-request-github#4212]
![image](https://user-images.githubusercontent.com/2230985/202571500-af0719f0-268a-435f-aafe-0eb2b0852915.png)

**Comment by alexr00** [comment]
@connor4312 is there anything you can think of about your setup that's out of the ordinary? I can't reproduce this with just an ssh remote:

![image](https://user-images.githubusercontent.com/38270282/203069444-abeaca9c-c840-4eb4-8571-5738e32b9234.png)

**Comment by alexr00** [comment]
In that case, should be fixed by d344871a337098047e9d7f357b18de18c3761ae7
