### ISSUE TITLE
Headers like milestone, assignee in PR details should be clickable

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#4214]
Currently only the gear is clickable, I naturally click the text as it works on GitHub

![image](https://user-images.githubusercontent.com/2193314/202794702-fefe86e7-7193-4a50-a50e-efb47cbbf485.png)

**Comment by alexr00** [comment]
Duplciate of https://github.com/microsoft/vscode-pull-request-github/issues/4196
