### ISSUE TITLE
Better management of folded folders

### ISSUE THREAD

**Issue by Elrendio** [microsoft/vscode-pull-request-github#4215]
Hello,

Thanks for this amazing extension :star_struck: 

On pull request I often add some changes while reviewing code from junior developers. My process is to:
- Fix the code
- Commit and push the fix
- Click on viewed the validated files

On large pull requests, the view on the left then reloads and re-open all previously toggled files :cry: Would it be possible to:
- Keep the toggle state upon reload unless the viewed state changed
- On first load, have folders on which all the sub files have been viewed folded by default

Thanks a lot 🙏

**Comment by alexr00** [comment]
> Keep the toggle state upon reload unless the viewed state changed

When you say toggle are you referring to the expand/collapse state of the tree node?

**Comment by alexr00** [comment]
> On large pull requests, the view on the left then reloads and re-open all previously toggled files

I'm not able to reproduce this. Are you talking about the expand/collapse state of the tree node? Can you share a screen shot?
