### ISSUE TITLE
The "All" node refreshes way too often when expanding child nodes

### ISSUE THREAD

**Issue by ramya-rao-a** [microsoft/vscode-pull-request-github#422]
Issue Type: <b>Bug</b>

I am working on the vscode-go repo and have the "All" node expanded. Every other time I expand a PR under it, the "All" node refreshes.

This seems unnecessary at best and annoying at worst when one of the remotes dont exist anymore.

Then you keep getting the warning "Fetching pull requests for remote ... failed, please check if the url..."

Extension version: 0.1.2
VS Code version: Code - Insiders 1.28.0-insider (96854113091424c07b28ba84b82b75a88b8455cb, 2018-09-10T05:18:57.119Z)
OS version: Windows_NT x64 10.0.17134

**Comment by RMacfarlane** [comment]
Closing, as this no longer reproduces. The tree should refresh infrequently now
