### ISSUE TITLE
Support filtering PR request changed-files by extension?

### ISSUE THREAD

**Issue by ihnorton** [microsoft/vscode-pull-request-github#4221]
It would be helpful if the file review list could support filtering a PR file list by file extension -- or, for more generality, by regex.

Use-case: for some languages, such as C++, it is often prudent to review header changes first in order to understand the scope and shape of a changeset before digging in to the implementation details. This might also apply to reviewing interface definition files for a language like OCaml (`.mli` files).

**Comment by kopach** [comment]
Just figured out, it's partially already implemented with VSCode's native "[Explorer search](https://code.visualstudio.com/docs/getstarted/userinterface#_advanced-tree-navigation)" feature.
> press Ctrl+Alt+F (Cmd+Alt+F on macOS) to open the Find control and type part of the file name you want to match.
So you would type extension only there.

The only missing feature for me is batch mark/unmark those filtered files as viewed

**Comment by alexr00** [comment]
Support for multiselect to mark as viewed is tracked by https://github.com/microsoft/vscode-pull-request-github/issues/6082!
