### ISSUE TITLE
vscode.dev button doesn't seem to do anything when clicked

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode-pull-request-github#4222]
- Should this button be framed as a verb e.g. "Open in vscode.dev"?
- It didn't do anything when clicked
- Reminds me to fix that broken button background color once clicked 😉

![CleanShot 2022-11-21 at 15 11 39](https://user-images.githubusercontent.com/25163139/203176565-d076a376-ec7e-4699-83d5-334994ab2a12.gif)

**Comment by daviddossett** [comment]
Also wondering if this button group should overflow after some limit cc @alexr00

**Comment by alexr00** [comment]
It should have copied a link, I hope it did that and you just didn't notice! I didn't want to make the button text to long, but this is clearly too short. I'll update to "Copy vscode.dev Link".

**Comment by alexr00** [comment]
For overflow, where would they overflow to? I think everything that we have in this button group is very important and needs to be visible.

**Comment by daviddossett** [comment]
> It should have copied a link, I hope it did that and you just didn't notice! 

Ah, I didn't notice. I probably wouldn't have expected any sort of toast confirmation if it had the "Copy..." verbiage. So that should be fine now 👍 

> For overflow, where would they overflow to? I think everything that we have in this button group is very important and needs to be visible.

Instead of burying them, we could also do something like the extensions detail view which uses additional icons for secondary actions 

<img width="402" alt="CleanShot 2022-11-22 at 11 31 13@2x" src="https://user-images.githubusercontent.com/25163139/203404647-f365ecf0-cfe3-4e32-be22-f842eccbbffc.png">

**Comment by alexr00** [comment]
Icons for overflow make sense. "Refresh" is probably the best candidate for this as it has the most obvious icon association.
