### ISSUE TITLE
Comment and submit button should be disabled when text area is empty

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode-pull-request-github#4231]
1. View a PR
2. Click the Comment and Submit button in the PR view on the sidebar
3. 🐛 You get an error notification because you cannot submit an empty comment

Here's the view I'm talking about in case my description is bad
<img width="305" alt="image" src="https://user-images.githubusercontent.com/4544166/203424973-fa5b7a3b-5601-4d9e-8454-17e577ffe431.png">

**Comment by mijamo** [comment]
Just a little point here: it is valid to submit when the textarea is empty if you have made some code comments somewhere.

**Comment by alexr00** [comment]
Indeed it is, which is why we don't disable it at all. However, we should be able to tell the difference between these two states and disable as appropriate.
