### ISSUE TITLE
Ctrl+enter to accept renamed pull request title

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-pull-request-github#4232]
1. Rename PR from PR overview page
2. Ctrl+enter to apply the changed name
3. :bug: change is not accepted

I realize it's a webview and we likely don't want to have to get into supporting all the VS Code keybindings, but figured I'd try my luck with this feature request because we have added support for ctrl+enter elsewhere e.g. https://github.com/microsoft/vscode-pull-request-github/issues/3572

**Comment by alexr00** [comment]
Just `Enter` works now as this is not a multiline input.
