### ISSUE TITLE
Ability to @ someone when doing PR review like in github web review 

### ISSUE THREAD

**Issue by chenq920** [microsoft/vscode-pull-request-github#4233]
I like to use this extension to do the PR review. But I didn't find a way to @ someone when doing comment.
It can't list the guys when I type @ like github we did. 
It'll be very nice if you add this support or tell me how can I accomplish this.

**Comment by alexr00** [comment]
@chenq920 can you share a screenshot of where you're trying to @ mention someone?

**Comment by chenq920** [comment]
@alexr00 thanks for look into this issue, please refer to below captures
1. There's no member listed after I type "@"
![image](https://user-images.githubusercontent.com/91521417/203881236-90609486-baae-47e6-bd9f-1f8171467aa6.png)
2. also no list on PR page
![image](https://user-images.githubusercontent.com/91521417/203881534-6e1f6908-990a-4cb7-b38b-6732720ec7a0.png)


3. while I do same review on github web , it'll list the memebers for you.
![image](https://user-images.githubusercontent.com/91521417/203881354-cc91013e-fc6f-4af6-b17c-43765dfb0170.png)

**Comment by alexr00** [comment]
Thanks for the screen shots! 
For the first one: this is a bug. I've started a fix that will be part of the next release.
For the second one: This is https://github.com/microsoft/vscode-pull-request-github/issues/2401#issuecomment-968894898, which we likely will never be able to add as there is no support for suggestions in VS Code webviews.

**Comment by chenq920** [comment]
@alexr00 Thanks, able to mention someone will be very helpful.
