### ISSUE TITLE
A11y_Visual Studio Code Web Extensions_Github Pull request_Create Pull request_AI4W: Ensures <iframe> and <frame> elements have an accessible name (frame-title - https://accessibilityinsights.io/info-examples/web/frame-title).

### ISSUE THREAD

**Issue by sspatil123** [microsoft/vscode-pull-request-github#4234]
“[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

**GitHubTags:**#A11yMAS;#A11yTCS;#GH_Visual Studio Code Web Extensions_Nov2022;#Visual Studio Code Web Extensions ;#ChromiumEdge;#DesktopWeb;#A11ySev3;#AI4W;#Win11;#A11yAuto;#WCAG4.1.2;#External;#External:GitHub;#External:Bug170440;

## Environment Details:
Application Name: Visual Studio Code Web Extensions
URL: https://insiders.vscode.dev/github/microsoft/vscode-pull-request-github
Windows Version: Win11
Edge version:107.0.1418.56

## Repro Steps:
1. Please do not close this bug. This bug should only be closed by TCS, C+AI Accessibility tester after verification of the fix
2. Open https://insiders.vscode.dev/github/microsoft/vscode-pull-request-github environment and login with git hub account.
3. tab to 'Github Pull request' and press enter.
4. tab to 'Create Pull request' and press enter.  
5. Run Accessibility Insights for Web.

## Issue:
Ensures <iframe> and <frame> elements have an accessible name (frame-title - https://accessibilityinsights.io/info-examples/web/frame-title)

Target application: Get Started - vscode-pull-request-github [GitHub] - Visual Studio Code - Insiders - GitHub - https://insiders.vscode.dev/github/microsoft/vscode-pull-request-github

Element path: .webview

Snippet: <iframe name="4995ce0b-9468-439a-b0a3-823e28c80feb" class="webview ready" sandbox="allow-scripts allow-same-origin allow-forms allow-pointer-lock allow-downloads" allow="cross-origin-isolated; autoplay; clipboard-read; clipboard-write" style="border: none; width: 100%; height: 100%; pointer-events: auto;" src="https://124rq7bps8ga8bl2oslntdv927iq0j91o3l8r0bvu26bn3gk7udh.vscode-cdn.net/insider/f730160c5d5fe36a7ad8db51f74f40a9d316e8b2/out/vs/workbench/contrib/webview/browser/pre/index.html?id=4995ce0b-9468-439a-b0a3-823e28c80feb&amp;origin=647c9522-dc58-4ad4-9a6b-0ce8cdea29e8&amp;swVersion=4&amp;extensionId=GitHub.vscode-pull-request-github&amp;platform=browser&amp;vscode-resource-base-authority=vscode-resource.vscode-cdn.net&amp;parentOrigin=https%3A%2F%2Finsiders.vscode.dev&amp;purpose=webviewView">

## How to fix:
Fix any of the following:
  Element has no title attribute
  aria-label attribute does not exist or is empty
  aria-labelledby attribute does not exist, references elements that do not exist or references elements that are empty
  Element's default semantics were not overridden with role="none" or role="presentation"

Environment: Microsoft Edge version 107.0.1418.56

====

This accessibility issue was found using Accessibility Insights for Web 2.35.0 (axe-core 4.4.1), a tool that helps find and fix accessibility issues. Get more information & download this tool at http://aka.ms/AccessibilityInsights.

**Similar issue observed in 'Github_Description' Scenario also.**

## User Impact:
Screen reader users will not get to hear the correct announcement for the control.

## Attachment:

![AI Iframe](https://user-images.githubusercontent.com/85863999/203507583-51b2af10-3687-4fce-ae92-5fefaaf20f6c.png)
![AiBugs](https://user-images.githubusercontent.com/85863999/203509256-1760179f-f18b-41a0-af68-04156ab40ee5.png)

**Comment by fsteffi** [comment]
external bug:https://github.com/microsoft/vscode/issues/170440

**Comment by sspatil123** [comment]
The issue is till reproing in https://insiders.vscode.dev/github/microsoft/vscode-pull-request-github environment. Please refer attachment below.
![image](https://user-images.githubusercontent.com/85863999/213680874-9c38f511-3c83-42ed-8a14-00a651845570.png)

**Comment by alexr00** [comment]
Closing as the upstream issue has been fixed.
