### ISSUE TITLE
Make it clear auth endpoint don't store tokens

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode-pull-request-github#424]
From twitter:

> Quick question - in the auth flow, you authorize against (link: https://github-editor-auth.herokuapp.com) github-editor-auth.herokuapp.com. Does that service store any auth tokens or is it stateless and simply passes them back to the editor? A bit cautious about granting access to private repos :)

We should make it clear in the auth-endpoint front-end that the token doesn't get stored there, but within the editor, and is encrypted in keychain.

**Comment by shana** [comment]
Good point, yes, I'll add that information to the frontend 👍

**Comment by shana** [comment]
This is fixed, forgot to update the issue. I've also added information about which server we're connecting to, so it's clearer.

![auth-server-message-tweak](https://user-images.githubusercontent.com/310137/46233442-e3c7a480-c372-11e8-8558-79a3a0a86777.png)
