### ISSUE TITLE
A11y_Visual Studio Code Web Extensions_Github_Description_DeveloperTool: Role assigned for 'Image' present under the text before associated with the comment shared by Thomus1664 is as link instead of button.

### ISSUE THREAD

**Issue by sspatil123** [microsoft/vscode-pull-request-github#4243]
“[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

**GitHubTags:**#A11yUsable;#A11yTCS;#GH_Visual Studio Code Web Extensions_Nov2022;#Visual Studio Code Web Extensions ;#ChromiumEdge;#DesktopWeb;#A11ySev4;#Win11;#DeveloperTool;

## Environment Details:
Application Name: Visual Studio Code Web Extensions
URL: https://insiders.vscode.dev/github/microsoft/vscode-pull-request-github
Windows Version: Win11
Edge version:107.0.1418.56

## Repro Steps:

1. Please do not close this bug. This bug should only be closed by TCS, C+AI Accessibility tester after verification of the fix
2. Open https://insiders.vscode.dev/github/microsoft/vscode-pull-request-github environment and login with git hub account.
3. tab to 'Github' and press enter.
4. tab to 'All Open' and press enter.
5. Tab to any pull request and press enter 'Description'.
6. Tab till 'Image' link and press enter.
7. Check role provide for 'Image' control is correct or not.

## Actual:
Role assigned for 'Image' present under the text before associated with the comment shared by Thomus1664 is as link instead of button.

## Expected:
Role assigned for 'Image' Control should be button.

## User Impact:
Screen reader users will not get the correct information of thecontrol.

## Attachment:

![RoleIncorrect](https://user-images.githubusercontent.com/85863999/203892486-7e626c96-eee5-4678-b310-0cde863f9f2c.png)

**Comment by alexr00** [comment]
This is external user content that we just directly display without processing. Awaiting confirmation from the accessibility testers that this can be closed.

**Comment by fsteffi** [comment]
as discussed with SME this bug can be closed
