### ISSUE TITLE
Copy As GitHub Permalink not working for enterprise GitHub

### ISSUE THREAD

**Issue by kitd** [microsoft/vscode-pull-request-github#4245]
Type: <b>Bug</b>

Assuming "Github Pull Requests and Issues" extension is installed:

1. Open a file cloned from an enterprise GitHub repo.
2. Select a line and right-click "Copy As > Copy GitHub Permalink"

The URL in the clipboard uses the "github.com" domain, not the correct enterprise one.  

Extension version: 0.50.0
VS Code version: Code 1.71.2 (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:12:14.256Z)
OS version: Linux x64 4.18.0-372.9.1.el8.x86_64
Modes:
Sandboxed: No

**Comment by alexr00** [comment]
@kitd a few questions:
1. Do you have the setting `github-enterprise.uri` set to your enterprise host?
2. Have you cloned with https or ssh?

**Comment by kitd** [comment]
Hi @alexr00 

Thanks for you help.

`github-enterprise.uri` is set to the correct top-level URL for our enterprise GH instance.
The git remote fetch/push uri in the repo is using `ssh`, though the `Git Protocol` setting in VSCode is unchanged, so defaulting to `https` I believe. Not sure which gets used. `ssh` I presume.
The copied URL has `https` on the front, just the wrong domain name.

Not sure if that helps at all.

**Comment by alexr00** [comment]
@kitd does your fetch/push uri start with `git@`?

**Comment by kitd** [comment]
@alexr00 

`ssh://git@<ghe-host>/...`
