### ISSUE TITLE
0 PRs found message shown even before attempting to find the PRs

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode-pull-request-github#425]
Issue Type: <b>Bug</b>

- Expand the All node
- We immediately see the "0 PRs found" message
- Then the node refreshes, and the tree is updated

The "0 PRs found" message should be shown only when **really** 0 PRs found. Else something like "Looking for PRs...." should be shown

Extension version: 0.1.2
VS Code version: Code - Insiders 1.28.0-insider (96854113091424c07b28ba84b82b75a88b8455cb, 2018-09-10T05:18:57.119Z)
OS version: Windows_NT x64 10.0.17134

**Comment by wyze** [comment]
I don't think this is an issue any more. As soon as I click to expand, it shows a loading state before expanding.

**Comment by ramya-rao-a** [comment]
Agreed.
