### ISSUE TITLE
Test Copy vscode.dev PR link command 

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#4252]
Refs: https://github.com/microsoft/vscode-pull-request-github/issues/4113

- [ ] anyOS @digitarald
- [x] anyOS @rebornix
- [x] anyOS @brettcannon (Optional)

Complexity: 1

[Create Issue](https://github.com/microsoft/vscode-pull-request-github/issues/new?body=Testing+%234252%0A%0A&assignees=alexr00)

---

1. Install the prerelease version of GitHub Pull Requests and Issues
2. Open a folder in VS Code that contains a GitHub repository with some PRs
3. Open the PR overview page for a PR (can be found in the Pull Requests view)
4. Find the button "vscode.dev Link"
5. Verify that clicking the button copies a vscode.dev link to the PR.

**Comment by brettcannon** [comment]
In case anyone else had a hard time finding it, the overview page is labeled "Description" in the UI:

![image](https://user-images.githubusercontent.com/54418/204672131-bfff3099-1317-4cb4-9d85-86d851c29288.png)

**Comment by digitarald** [comment]
Agreeing with https://github.com/microsoft/vscode-pull-request-github/issues/4268 , it also confused me. Also, I wish we had toasts to confirm these small interactions (just a quick "Link for vscode.dev is now in your clipboard").

Already used this multiple times during this iteration 🚀.

**Comment by alexr00** [comment]
Thanks for testing! I'll change the wording to "Copy vscode.dev Link".

> Also, I wish we had toasts to confirm these small interactions (just a quick "Link for vscode.dev is now in your clipboard").

I thought doing this is explicitly against our notification guidelines (I actually just removed this for one of our other copy commands). I can't find any documentation to support this, but I could have sworn it was discussed at some point. I've also gotten feedback that the "successfully copied!" notification is annoying 🤷‍♀️

**Comment by daviddossett** [comment]
Will be exploring lightweight toasts, separate from notifications, here: https://github.com/microsoft/vscode/issues/166891
