### ISSUE TITLE
Test command to iterate through all diffs in a review

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#4254]
Refs: https://github.com/microsoft/vscode-pull-request-github/issues/4089

- [x] anyOS @hediet 
- [x] anyOS @cwebster-99
- [x] anyOS @sandy081 

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode-pull-request-github/issues/new?body=Testing+%234254%0A%0A&assignees=alexr00)

---

1. Install the pre-release version of GitHub Pull Requests and Issues
2. Open a folder that contains a GitHub repository
3. Check out a pull request (this feature only works on checked out PRs)
4. Use the command "Go to Next Diff in Pull Request" to view the changes in the PR. Verify that it works in a way that you'd expect.

**Comment by alexr00** [comment]
@cwebster-99 can you share a link to the PR you're testing with? I've only been able to repro this occationally.

**Comment by alexr00** [comment]
Figured out the problem, no further info needed.

**Comment by hediet** [comment]
Works now!
