### ISSUE TITLE
Test PR diff LHS commit is reported as missing

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#4256]
Refs: https://github.com/microsoft/vscode-pull-request-github/issues/3941

- [x] anyOS @kieferrm
- [x] anyOS @bpasero
- [x] anyOS @brettcannon (Optional)

Complexity: 1

[Create Issue](https://github.com/microsoft/vscode-pull-request-github/issues/new?body=Testing+%234256%0A%0A&assignees=alexr00)

---

1. Open a PR in a Codespace (make sure that it's a PR you haven't opened in a Codespace before, as the Codespace needs to be new)
2. Immediately try to open a PR diff.
3. Verify that there's a LHS to the diff.

**Comment by alexr00** [comment]
Just some clarification: the full git history isn't available in a fresh PR branch Codespace for about 2 minutes. If you can open a PR diff within the first 1-2 minutes and have it show a diff (as opposed to an empty file on the left), then the test was successful.

**Comment by brettcannon** [comment]
![image](https://user-images.githubusercontent.com/54418/204672612-64b61fbc-4eec-41cf-b8e2-26fb6949ae4a.png)

**Comment by kieferrm** [comment]
This is working as of @alexr00's clarification. But it's still a bit awkward since I can still see the missing commit notification and I do have to know to wait a bit to be in a better spot.

**Comment by alexr00** [comment]
@kieferrm you shouldn't be seeing the notification, and you shouldn't need to wait to see the diff (well, once the Active PR view is visible you shouldn't have to wait any longer). Can you confirm that you were using the pre-release build of the extension?
