### ISSUE TITLE
We should allign the icons with the Github icons

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode-pull-request-github#4260]
Testing #4257

For example requesting a change

<img width="420" alt="image" src="https://user-images.githubusercontent.com/1931590/204499904-40f9f92c-fbde-437b-9fd4-755ca72caf4e.png">

<img width="280" alt="image" src="https://user-images.githubusercontent.com/1931590/204499953-a75d12b8-f8e7-43dd-a375-834e2c147f52.png">

**Comment by alexr00** [comment]
We have a balance to maintain here. Our UI does look identical to GitHub's so our goal is to maintain our own look and feel, while still having recognizable icons. 

I will defer to @daviddossett on this, but I think this is as-designed.

**Comment by daviddossett** [comment]
I'm open to updating that icon since we also now have a similar icon for new changes:

<img width="263" alt="CleanShot 2022-11-29 at 15 30 25@2x" src="https://user-images.githubusercontent.com/25163139/204671200-c103ef0c-8f18-48d5-8b07-6b3d9649e7a3.png">

**Comment by dbaeumer** [comment]
I think we would profit from allignment.

**Comment by alexr00** [comment]
Upstream PR has been merged: https://github.com/microsoft/vscode-codicons/pull/153
