### ISSUE TITLE
The command does not go to the next file in the PR

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode-pull-request-github#4262]
Testing #4254

The command does not go to the next file in this PR:

https://github.com/microsoft/vscode/pull/167476

**Comment by alexr00** [comment]
To verify:
1. Checkout a PR which contains changes across multiple files.
2. Open a PR diff that isn't in the last file
3. **Click into the left hand side of the diff**
4. Run the command "Go to Next Diff in Pull Request" until a diff in the next file is opened.
