### ISSUE TITLE
Should the reviewer quick pick ignore focus out?

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-pull-request-github#4267]
Testing #4255

If I select multiple reviewers and accidentally hit esc, nobody is assigned and I have to start over. I wonder if it might help to make the quick pick ignore focus out here.

**Comment by alexr00** [comment]
I'm leaning towards leaving this as is. Most of our quick picks don't ignore focus out and I've found with the simple file picker that users can be confused when it does ignore focus out.
