### ISSUE TITLE
Review required status seems to take precedence over CI in progress status

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode-pull-request-github#4269]
Testing #4257

I tried creating a new PR to get the CI in progress status, but it seems to default to the review required status.

![Screenshot showing that the CI is running on GitHub, but that the extension shows the review required status only.](https://user-images.githubusercontent.com/7199958/204621644-e5247a57-d0ee-4d15-9bb1-a3ac92a5468c.png)

**Comment by alexr00** [comment]
Yes, the review required status does take precedence over the CI in progress status. My reasoning was that if a review is required then there is some action that can be taking. However, I can see why you'd want the CI status to take precedence if you want to wait to review PRs until CI has complete. I will switch it.

**Comment by alexr00** [comment]
That version doesn't have the fix in it.
