### ISSUE TITLE
Add ability to sign out

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode-pull-request-github#427]
We should add the ability to sign-out from a command and the status bar item.

- Clean up settings
- Clean up keychain

**Comment by ramya-rao-a** [comment]
This can be covered as part of #360?

**Comment by auchenberg** [comment]
@ramya-rao-a I think we should keep this issue open to track this independently on whether we are keeping the status bar item or not.

**Comment by RMacfarlane** [comment]
This was added as part of https://github.com/Microsoft/vscode-pull-request-github/pull/659
