### ISSUE TITLE
Go to Next Diff in Pull Request command is not iterating through all diffs

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-pull-request-github#4275]
Testing #4254

- Check out the PR - https://github.com/microsoft/vscode/pull/164085
- Use `Go to Next Diff in Pull Request` command to navigate

🐛 When it reaches to third file `src/vs/platform/request/browser/requestService.ts` file, it only gets executed once, even though there are two changes.

It navigates to all changes in the next file which is `src/vs/platform/request/node/requestService.ts` it gets executed twice once per each change.

Now, select the first file and start navigating again. This time this command gets executed only once in the last file

**Comment by alexr00** [comment]
@sandy081 this is currently by design as both diffs are in the view port in that third file.
