### ISSUE TITLE
Why does all checks passed use a double tick instead of a single tick?

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#4282]
The double tick confuses me, not sure if it's meant to differentiate from a single check or it just uses a different icon?

![image](https://user-images.githubusercontent.com/2193314/205381999-a48509de-fc4f-4655-8258-b5afb87b314b.png)

vs

![image](https://user-images.githubusercontent.com/2193314/205382025-b8a1d61a-f72f-4914-bbf6-09a14b067d94.png)

**Comment by alexr00** [comment]
The double check icon is called `check-all`, which logically made more sense to me to use here instead of `check` since there are multiple checks here. I'm open to changing it if there's frequent confusion around it.

**Comment by Tyriar** [comment]
I would have guessed it means approved and other checks passed, but it just means checks passed. So I think it's confusing as it is atm.

**Comment by alexr00** [comment]
PR review is one of the checks, so it does mean approved and other checks passed.

**Comment by daviddossett** [comment]
Do we use the regular `check` if >=1 check has passed then? I don't recall seeing it used yet.

**Comment by Tyriar** [comment]
But it's a circle if checks pass and a review is required?

<img width="571" alt="Screenshot 2022-12-05 at 5 32 46 pm" src="https://user-images.githubusercontent.com/2193314/205786425-acc6b6e5-a41f-4854-a839-3a78310b7f40.png">

Do you never see a check if your repo requires reviews?

**Comment by alexr00** [comment]
No, single check is never used. I didn't distinguish between "all checks passed and you have more than one check" and "all checks passed and you only have one check".

**Comment by Tyriar** [comment]
Ah ok, well personally I find it confusing but I'll leave whether you change it up to you and @daviddossett.
