### ISSUE TITLE
PR view for a branch still opens after PR branch is deleted and recreated with different contents

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-pull-request-github#4294]
1. Create a branch off main in Remote Repos and use it to create a PR
2. Make some commits to main 
3. Delete the branch (e.g. because PR was resolved)
4. Create a branch with the same name in Remote Repos
5. :bug: the PR view for the merged PR appears

My expectation in this context is that we do not attempt to open the PR view for a branch by default if the associated PR has already been merged. It should still be possible to get to the PR view though.

**Comment by alexr00** [comment]
By default we no longer show the active PR view for merged PRs now.
