### ISSUE TITLE
+ comment button is misaligned again

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-pull-request-github#430]
os: macos
ext: 0.1.2
vscode: ee6a21fa49bd1906bd1378c2f2714cd656409e5c, 2018-09-11T05:05:39.654Z

<img width="65" alt="screen shot 2018-09-11 at 11 21 17 am" src="https://user-images.githubusercontent.com/2193314/45379399-d8276000-b5b4-11e8-8b37-864293e5e1c8.png">

**Comment by RMacfarlane** [comment]
should be fixed by https://github.com/Microsoft/vscode/commit/8fb320d4a42594679f569e772c28a3cb8bc25207
