### ISSUE TITLE
Is GitHub Enterprise Authentication over remote SSH broken since recent versions (0.52.0+?)

### ISSUE THREAD

**Issue by notatallshaw-gts** [microsoft/vscode-pull-request-github#4301]
Since VS Code I can no longer provide my Personal Access Token to VSCode Pull Request and the GitHub Enterprise authentication flow does not seem to work when VS Code is setup in a remote SSH environment.

Is there a way I can force using Personal Access Token or are there any more details I can provide to diagnose why this no longer works?

**Comment by alexr00** [comment]
> the GitHub Enterprise authentication flow does not seem to work when VS Code is setup in a remote SSH environment.

Let's see if we can figure out what's going on here, as the new flow should be a better experience than providing your PAT was. Before trying anything else, can you open the folder that your enterprise repository is in and sign out of your GitHub Enterprise account using the "Accounts" icon in the bottom left corner of VS Code?

Can you describe and/or share screenshots of what's not working?

**Comment by notatallshaw-gts** [comment]
**Update:** After waiting 10+ minutes not touching VS Code because I was editing the description here an additional dialogue popped up in VS Code in the bottom right saying, "You have not finished signing into GitHub, would you like to continue?", I clicked yes. A dialogue box opened and gave me a onetime code and had a couple of options and I clicked "Copy Code and open GitHub". The Github Enterprise URL was actually opened, and I was able to paste in the onetime code and it successfully linked.

Unfortunately, I did not take screenshots of this additional set of dialogues, and it's not ideal that I have to wait ~10 minutes for this to appear after going through two failed attempts.  Let me know if you would like me to try to reproduce and take more screenshots, and if there is a way to immediately force this third authentication attempt straight away so I can provide it to my colleagues.

**Comment by alexr00** [comment]
@notatallshaw-gts thank you for this detailed response!

@TylerLeonhardt does this help with tracking down any GitHub Enterprise auth issues? This isn't the first report I've seen where the only way to successfully sign in was the copy code option. Would it be possible to always make that the first fallback for Enterprise auth?

**Comment by realqpat** [comment]
Had the same issue and fixed also with coy/paste the code

**Comment by TylerLeonhardt** [comment]
First off I want to say that you have provided amazing detail in this issue and I really appreciate it!

Secondly I want to call out that this issue is tracked over here:
https://github.com/microsoft/vscode/issues/168338

/duplicate https://github.com/microsoft/vscode/issues/168338
