### ISSUE TITLE
Option to disable discussion

### ISSUE THREAD

**Issue by ScrubN** [microsoft/vscode-pull-request-github#4302]
It would be really nice to have a setting to disable the discussion bar/button on the left of the editor. I personally find it's more annoying than useful as it makes miss-clicking the line diff icons open the discussion panel, to which the close button is on the other side of the editor.

![image](https://user-images.githubusercontent.com/72096833/206370258-a3e35cf5-5d23-49f6-928f-fbcd3aeda0f2.png)

**Comment by alexr00** [comment]
The new setting `comments.visible` does this.
