### ISSUE TITLE
404 when authenticating with GH enterprise

### ISSUE THREAD

**Issue by pmwisdom** [Microsoft/vscode-pull-request-github#432]
- Extension version: 0.1.2
- VSCode Version: 1.27.1
- OS: Mac OSX

Steps to Reproduce:

1. Add GH enterprise to user settings hosts 
ex: 	"github.hosts": [
		{
			"host": "https://github.example.com/"
		}
	]
2. Launch VS Code
3. Go To SCM Panel
4. Authentication popup is displayed
5. Click sign in
6. Click continue on browser tab that opens up
7. 404 page appears for the redirected url to our enterprise instance

**Comment by ultimatemonty** [comment]
We ran into the same issue. While troubleshooting we discovered a couple of things:

1) I could get rid of the 404 if I created an OAuth app under my account with `https://github-editor-auth.herokuapp.com` as the callback URL. I then replaced the clientId in the URL that Code opens up when signing in with the clientId for my new app. Boom no more 404! Unfortunately auth still fails likely because it doesn't know the clientSecret of my app :(

2) When trying the workaround specified in https://github.com/Microsoft/vscode-pull-request-github/issues/384#issuecomment-419993453 I found that it worked just fine for forked repos under user accounts but it did not work for any repos under our org. I tried both with the specific grants as well as the ALL THE THINGS grant and had the same results. Are there are specific org-wide permissions that need to be enabled for this extension to work?

Note all this was tested locally using vsce to package the latest code from master ( specifically for #411 )

**Comment by kballard** [comment]
When I try the workaround specified in #384, after closing and reopening VSCode my settings.json is updated to remove the token from `github.hosts` (leaving just the host URL) and it asks me to sign in.

**Comment by roboticai** [comment]
I got the same issue when connecting my Github Enterprise account. Pls keep us posted if there is any workaround or fix. I would use the extension because it seems be useful. 
Thanks.

**Comment by zliu** [comment]
Exactly same issue here.  I got the link below when I saw 400, replace IDs with _XXXX_

https://github.ibm.com/login/oauth/authorize?state=action%3Acode%3Bguid%3A_XXXX_&scope=read%3Auser%20user%3Aemail%20repo%20write%3Adiscussion&response_type=code&client_id=_XXXX_&redirect_uri=https%3A%2F%2Fgithub-editor-auth.herokuapp.com

**Comment by ultimatemonty** [comment]
I've found a way to work around the token disappearing issue. Go through the sign-in process like normal and let it fail. After it fails go into your settings.json and setup your hosts:

```
github_hosts: [
  {
    host:'https://your.host.here',
    username: 'your.username',
    token: 'your.token'
  }
]
```
Then go into the SCM tab and refresh your PRs and you should be good to go.

This should work for multiple hosts as well if you have to connect to multiple GHE instances.

**Comment by reverbc** [comment]
Thanks @ultimatemonty for the workaround. I got my plugin working by creating token with the following permission: `read:user`, `repo`, `user:email`, `write:discussion`. Got these permission from the queries of 404 request (original: `scope=read%3Auser%20user%3Aemail%20repo%20write%3Adiscussion`)

**Comment by anduong96** [comment]
> I've found a way to work around the token disappearing issue. Go through the sign-in process like normal and let it fail. After it fails go into your settings.json and setup your hosts:
> 
> ```
> "github.hosts": [
>   {
>     "host": "https://your.host.here",
>     "username": "your.username",
>     "token": "yourtoken"
>   }
> ]
> ```
> Make sure to use your GHE username and _not_ `oauth` as the comment recommends. Then go into the SCM tab and refresh your PRs and you should be good to go.
> 
> This should work for multiple hosts as well if you have to connect to multiple GHE instances.

This doesn't work for me. The username and token attribute get automatically removed every time I save the setting file.

**Comment by lukefan6** [comment]
i did not see the scope `write:discussion`, is it because GHE admin turned it off or simply GHE version thing? mine is `GitHub Enterprise 2.11.18`

**Comment by konguycodes** [comment]
Thanks to @ultimatemonty and @reverbc. I got mine working, but I did have to restart VS Code.

**Comment by reid** [comment]
@lukefan6 It's too old. [Enterprise 2.11.x is deprecated](https://enterprise.github.com/releases/series/2.11) and contains [serious unpatched security vulnerabilities](https://enterprise.github.com/releases/2.11.23). Request your administrator to [upgrade](https://help.github.com/enterprise/admin/guides/installation/upgrading-github-enterprise/) as soon as possible.

**Comment by carmanchris31** [comment]
I'm also getting the 404 error. Tried creating the personal token manually as @reverbc mentioned but did not have the write:discussion scope available as @lukefan6 described. Version is 2.12

**Comment by kingdomax** [comment]
@ultimatemonty @reverbc These solution solved my issue.
**GHE 2.14**

**Comment by shana** [comment]
The versions of GHE that support signing in with the Sign In popup are:

- 2.14.5 and above
- 2.13.11 and higher 2.13.x
- 2.12.19 and higher 2.12.x
- 2.11.25

Other versions will need a personal access token configured with the scopes `read:user`, `repo`, `user:email`, `write:discussion`, as mentioned above.

> i did not see the scope `write:discussion`, is it because GHE admin turned it off or simply GHE version thing? mine is GitHub Enterprise 2.11.18

Oh this is a good point, some versions of GHE might not have this scope available, in which case the personal token might fail. I think we can ease restrictions on the scope validation for this so it won't fail (`write:discussion` is not essential at this time).

**Comment by carmanchris31** [comment]
@shana Ah the patch version makes all the difference. Thank you

**Comment by shana** [comment]
The wiki has updated instructions on how to sign in to GitHub Enterprise, check them out at https://github.com/Microsoft/vscode-pull-request-github/wiki#2-is-github-enterprise-supported!

If you're still having problems, please open a new issue with the details
