### ISSUE TITLE
Comments not Appearing when there are 101+ comments

### ISSUE THREAD

**Issue by jonathan-shahen** [microsoft/vscode-pull-request-github#4323]
- Extension version: 0.56.0
- VSCode Version: 1.74.0
- OS: Windows

Steps to Reproduce:

1. Have a large PR (hundreds of files and hundreds of comments)
2. Open the Comment window
3. New comments and old comments do not appear. It stops at 100 comments (and these are all resolved)
4. Opening the file in VSCode shows no comments in the left hand bar, but for some files they do appear
     - Visiting the file in the PR on github.com I can see the comments

![image](https://user-images.githubusercontent.com/32882794/207143529-3764c920-4a9d-4a47-a5ce-40408f793bdb.png)

![image](https://user-images.githubusercontent.com/32882794/207143258-91b39b00-7c35-4e4a-b010-1caf2ce49167.png)

Possible Fixes:

1. Request more comments
2. Sort the comments requests to be the oldest that are not resolved (better to allow this to be changeable in case someone wants the newest comments that are (un)resolved)

**Comment by jonathan-shahen** [comment]
Any followup on this?

**Comment by jonathan-shahen** [comment]
I found where in the code this is happening:

File: `src/github/queries.gql`
```
query PullRequestComments($owner: String!, $name: String!, $number: Int!, $first: Int = 100) {
	repository(owner: $owner, name: $name) {
		pullRequest(number: $number) {
			reviewThreads(first: $first) {
				nodes {
					id
					isResolved
					viewerCanResolve
					viewerCanUnresolve
					path
					diffSide
					startLine
					line
					originalStartLine
					originalLine
					isOutdated
					comments(first: 100) {
						edges {
							node {
								pullRequestReview {
									databaseId
								}
							}
						}
						nodes {
							...ReviewComment
						}
					}
				}
			}
		}
	}
	rateLimit {
		limit
		cost
		remaining
		resetAt
	}
}
```

File: `src/github/pullRequestModel.ts`
```
	/**
	 * Get all review comments.
	 */
	async initializeReviewComments(): Promise<void> {
		const { remote, query, schema } = await this.githubRepository.ensure();
		try {
			const { data } = await query<PullRequestCommentsResponse>({
				query: schema.PullRequestComments,
				variables: {
					owner: remote.owner,
					name: remote.repositoryName,
					number: this.number,
				},
			});

			const comments = data.repository.pullRequest.reviewThreads.nodes
				.map(node => node.comments.nodes.map(comment => parseGraphQLComment(comment, node.isResolved, this.githubRepository), remote))
				.reduce((prev, curr) => prev.concat(curr), [])
				.sort((a: IComment, b: IComment) => {
					return a.createdAt > b.createdAt ? 1 : -1;
				});

			this.comments = comments;
		} catch (e) {
			Logger.appendLine(`Failed to get pull request review comments: ${e}`);
		}
	}
```

As you can see the `schema.PullRequestComments` only grabs the first 100, and there is no for loop in `initializeReviewComments()` to change `first` to get any other variables.

Should be a quick fix, loop until an empty result is returned, though there might need to be further updates as `getReviewThreads()` also utilizes this graphql query.

**Comment by jonathan-shahen** [comment]
An alternative solution and much faster solution is to pass in `first` and have this be a configurable number. That way I could set it to 1000, and others can leave it as is

**Comment by jonathan-shahen** [comment]
If I can get some direction on what is preferred, then maybe I can submit a pull request to help move this into the next version

**Comment by jonathan-shahen** [comment]
Any followup on this would be welcome. I am willing to create a pull request for this.

**Comment by jonathan-shahen** [comment]
Any followup? or even a message would be great

**Comment by jonathan-shahen** [comment]
@alexr00 if I can get direction I will submit a PR for this

**Comment by alexr00** [comment]
@jonathan-shahen I think ideally we'd implement paging for comments. So if you have 100 we fetch 100, and you have 500 we fetch 500. We should still have an upper limit though since loading many comments could be costly. We could show a warning notification if that limit is hit.

**Comment by fsevenm** [comment]
Any updates on this? Actually, I tried to increase the number, but it returned an error "Requesting 200 records on the `reviewThreads` connection exceeds the `first` limit of 100 records.".

**Comment by alexr00** [comment]
I'll take a look at comments paging in June.

**Comment by fsevenm** [comment]
Great, thanks @alexr00!

**Comment by alexr00** [comment]
Starting with the next pre-release build we will get up to 1000 comment threads.

**Comment by TylerLeonhardt** [comment]
I take it to verify I need to add 1001 comments to a PR, @alexr00? 😅

**Comment by alexr00** [comment]
Just 101 will be enough to test that paging is working :D
