### ISSUE TITLE
The checked out marker on a PR should change as soon as the branch is changed

### ISSUE THREAD

**Issue by ramya-rao-a** [microsoft/vscode-pull-request-github#433]
Issue Type: <b>Bug</b>

- Checkout a PR
- Note the check mark on the PR node
- Change branch
- The first level node refreshes

The check mark on the PR node only goes away after the refresh on the first level node completes which can take a few seconds.

Since we know that the branch has changed, the check mark should go away immediately without waiting for the refresh to complete

Extension version: 0.1.2
VS Code version: Code - Insiders 1.28.0-insider (96854113091424c07b28ba84b82b75a88b8455cb, 2018-09-10T05:18:57.119Z)
OS version: Windows_NT x64 10.0.17134

**Comment by RMacfarlane** [comment]
With the tree data provider api, the only way we're able to update nodes is by calling `refresh` on the parent so that its `getChildren` method is called. We could cache parts of the tree or the request to get PRs to make this update faster

**Comment by alexr00** [comment]
Closing as designed.
