### ISSUE TITLE
Allow to checkout as worktree with a post script

### ISSUE THREAD

**Issue by Norfeldt** [microsoft/vscode-pull-request-github#4332]
I very much enjoy using this extension together with github projects. I really like the option to start working on an issue.

<img width="808" alt="Screenshot 2022-12-15 at 08 54 56" src="https://user-images.githubusercontent.com/678806/207803733-aca21ce7-3ae7-4d7e-8a11-cdbc853dee22.png">

Lately I stated using `git worktree` like this

```sh
$ git worktree add ~/Desktop/336-release-50x-for-android 336-release-50x-for-android
$ rsync --archive --human-readable --recursive --exclude=".git" . ~/Desktop/336-release-50x-for-android
```

(the latter to copy any dot files like `.env`)

It would be fantastic if this was possible to do with a one click like this "start working on" feature. 

This means that it gotta do the steps described, after creating the branch (not checking it out).

**Comment by alexr00** [comment]
Closing as out of scope since we don't intend to address this.
