### ISSUE TITLE
Collapse comments on resolve

### ISSUE THREAD

**Issue by MartinBernstorff** [microsoft/vscode-pull-request-github#4333]
Love the new "resolve conversation" button! 

![image](https://user-images.githubusercontent.com/8526086/207833249-073cc277-a307-4ab7-9fdd-71816f3c5921.png)

Even better would be if I could set a setting for automatically collapsing the conversations when I press resolve :-)

**Comment by brettcannon** [comment]
I think this and https://github.com/microsoft/vscode-pull-request-github/issues/5031 are duplicates of each other.

**Comment by alexr00** [comment]
@brettcannon you are correct. Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/5031.
