### ISSUE TITLE
Creating a PR and choosing the commit changes action leads to error notifs

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode-pull-request-github#4338]
Not sure if this is reproducible every time, but here are the steps.
1. Create a branch and push the branch
2. Make some changes, but don't commit them
3. Go to create a PR. It will tell you that you have no changes committed
4. Choose commit changes
5. 🐛 Pr is properly created but not previewed. You also get some errors
<img width="499" alt="image" src="https://user-images.githubusercontent.com/4544166/207892467-ac200906-8fc2-4286-acaf-84a8d375b28f.png">

**Comment by alexr00** [comment]
I'm not able to repro this. If you see it again can you check if there's anything in the console?

**Comment by lramos15** [comment]
I did check the console when I reproed this the first time and it didn't contain anything helpful, so feel free to close for now and I will reopen if I see it again.
