### ISSUE TITLE
A completed PR disappears from tree but corresponding editors dont go away

### ISSUE THREAD

**Issue by ramya-rao-a** [microsoft/vscode-pull-request-github#434]
Issue Type: <b>Bug</b>

- Open a PR
- Click on one of its files
- Approve the PR. At this point both the file and the description are open as editors
- Merge the PR in Github
- Change branch in VS Code
- Tree refreshes and the node for above PR disappears as it should

At this point the editor for PR is still open which is not too much of a problem
But the diff view for the file from this PR is also open which is confusing to the user if they come back to it after a while.
There is no context or indication that this is part of an old PR.

At this point if I checkout another PR, and look at its file changes, its all the more confusing to have an artifcat from the old PR

Extension version: 0.1.2
VS Code version: Code - Insiders 1.28.0-insider (96854113091424c07b28ba84b82b75a88b8455cb, 2018-09-10T05:18:57.119Z)
OS version: Windows_NT x64 10.0.17134

**Comment by alexr00** [comment]
I would disagree. Open file tabs should not disappear.
