### ISSUE TITLE
Mix of new and old `request-changes` icons.

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode-pull-request-github#4341]
It looks like some parts of the UI still use the old `request-changes` icon. Perhaps because we've added hardcoded SVG?

<img width="369" alt="CleanShot 2022-12-15 at 11 06 31@2x" src="https://user-images.githubusercontent.com/25163139/207946089-d3cf20be-8172-408e-8992-87348f6225e7.png">

**Comment by eleanorjboyd** [comment]
Where was the old UI located? Not sure where to look to verify

**Comment by alexr00** [comment]
The "Reviewers" section is in the pull request description/overview.
