### ISSUE TITLE
Add a setting to prevent fetch on checkout

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#4346]
From @tristan957  in https://github.com/microsoft/vscode-pull-request-github/issues/4202:

@alexr00 now that I have used the extension more with this fix, I have one more piece of feedback. Would it be possible to get the extension to turn off auto fetching in all situations? As of right now, like you said in an above comment, the extension will fetch when you checkout a branch connected to a PR. While an improvement, it is still annoying to be pestered for an SSH password when I checkout a PR branch.

For my workflow, I am usually the owner of the PR branch, so I know when it has been updated and when I need to fetch updates. In the vast majority of cases, I only ever interact with a branch on the same computer, so the latest that I have locally is always at least equal to or more recent than what is on the remote.

**Comment by Unknovvn** [comment]
Hey. I would like to handle this issue. Could you assign it to me?

**Comment by unknovvn** [comment]
@alexr00 I think, that after [PR](https://github.com/microsoft/vscode-pull-request-github/pull/4759) has been merged this ticket can be closed

**Comment by roblourens** [comment]
Should it be "fetch pull request branch before checkout"?

**Comment by roblourens** [comment]
What I see is that with that setting `false`, if I just do a checkout to that branch, it doesn't pull to the branch. But if I right click the PR and do "Checkout to", it still pulls to update the branch, is that what I should expect?

**Comment by alexr00** [comment]
@roblourens that's not what's expected. What should happen:
- When you checkout a PR branch from the PRs tree for the first time, changes will always be pulled.
- `"githubPullRequests.pullPullRequestBranchBeforeCheckout": true`
  -  When you checkout a PR branch from the PRs tree that you've checked out before, changes will be pulled.
- `"githubPullRequests.pullPullRequestBranchBeforeCheckout": false`
  - When you checkout a PR branch from the PRs tree that you've checkout out before, changes **will not** be pulled.

**Comment by alexr00** [comment]
> Should it be "fetch pull request branch before checkout"?

The equivalent git setting is "Pull Before Checkout".
