### ISSUE TITLE
Add CONTRIBUTING guidelines

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode-pull-request-github#435]
Add CONTRIBUTING guidelines.

Inspiration: https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md

**Comment by RMacfarlane** [comment]
Did some editing of the contributing section of the wiki: https://github.com/Microsoft/vscode-pull-request-github/wiki/Contributing

Edit it further if you think anything is missing or could be clearer
