### ISSUE TITLE
Opening multi-root workspace triggers rate-limiting error

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [microsoft/vscode-pull-request-github#4351]
Type: <b>Bug</b>

1. Create a multi-root workspace with several repos checked out from GitHub (I have 10-20)
2. Close vscode
3. Open it back up

This extension pops a notification:

> You have exceeded a secondary rate limit. Please wait a few minutes before you try again.

And one or more notifications about failing to resolve pull requests in the repos in the workspace.

Seems like the extension ought to be able to recognize rate-limiting errors and back off and try again.

Extension version: 0.56.0
VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:27:19.253Z)
OS version: Linux x64 6.0.0-6-amd64
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz (8 x 4500)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 1, 1|
|Memory (System)|31.20GB (16.41GB free)|
|Process Argv|--unity-launch --crash-reporter-id 9e173b1d-a097-4ad7-aa26-9a9bb4af3128|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome-xorg|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome-xorg|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1:30587005
3biah626:30602489
gswce1:30612156
3d0df643:30613357
89544117:30613380
fim-prod:30623723
vscsbc:30628655

```

</details>

**Comment by tedwardd** [comment]
Can confirm this issue as well. Using Github Enterprise with a multi-root workspace in VSCode and rate limits on the GHE server _disabled_ produces enough API calls to cripple the entire GHE instance. At the very least there should be a way to tweak the polling frequency in the plugin to avoid this.

**Comment by mgabeler-lee-6rs** [comment]
Since it's the same API and user under the hood, this also means that large parts of the `gh` cli are non-functional when I have such a workspace open, or $deity forbid a few of them.

This is basically a "disable / uninstall until fixed" for me, since the extension breaks both itself and other tools :(

**Comment by mgabeler-lee-6rs** [comment]
Also I'm not seeing the popups any more, but it's still very definitely causing rate limits to be exceeded

**Comment by davibe** [comment]
Fetching pull requests failed: GraphQL error: API rate limit exceeded for user ID XXXX.

**Comment by RobCannon** [comment]
I get this issue when I open more than one VS Code instance.  I regularly have 3 or 4 repos in different instances open at any given time.  This did not used to be an issue.

**Comment by Logan-Cormier** [comment]
I have been experiencing this issue as well. I update a meta repo so sometimes I have 30-50 repositories open so it's not surprising. (I am on enterprise as well so the error is still visible). 

I haven't seen gh get disabled like the above comment so it's not a breaking issue for me. 

It would be nice however to be able to change the polling frequency or disable issue polling altogether since I don't track issues on github.
