### ISSUE TITLE
Copy PR number

### ISSUE THREAD

**Issue by christinachimi** [microsoft/vscode-pull-request-github#4353]
I have some automation in GitHub that uses the PR number to generate an environment, and I would like to be able to write a launch config to talk to that environment. I can get the PR number for the current pull request from `${command:pr.copyVscodeDevPrLink}`, but I need the bare number. I see a command exists to do this for issues, but not for PRs. Would it be possible to add a command like `copyPrNumber` for this purpose?

**Comment by aidoskanapyanov** [comment]
Hi, I can work on this feature if it is still needed. @christinachimi @alexr00

**Comment by aidoskanapyanov** [comment]
@alexr00 I've opened a PR, the code is basically the same as for `pr.copyVscodeDevPrLink` command: https://github.com/microsoft/vscode-pull-request-github/blob/5b3c4f5e6ce15cf6b94f856c55258a6e2a1c445c/src/commands.ts#LL1150C1-L1180C1

**Comment by christinachimi** [comment]
Sorry, I missed the earlier conversation on this. I no longer have the need for this that I did when I opened it. It still seems useful to me, but I can't make a strong case for it right now.
