### ISSUE TITLE
relative paths in remotes are parsed as host ".", and prevent GHE login

### ISSUE THREAD

**Issue by cshorler** [microsoft/vscode-pull-request-github#4355]
- Extension version:  v0.56.0, also prerelease - now built from source to debug issue - github branch main
- VSCode Version:  1.74.2
- OS:  Windows 10

Steps to Reproduce:

1.  configure GHE server in settings github-enterprise.uri
2.  setup remotes as follows:
```
$ git remote -v
abc  ./bundles/abc-def.bundle (fetch)
abc  ./bundles/abc-def.bundle (push)
origin  https://github.ghi.corp/orga/repo.git  (fetch)
origin  https://github.ghi.corp/orga/repo.git  (push)
```

result:

github extension page shows:
"Loading..." rather than logging in and displaying PRs and issues

debugging shows gitProtocol.host == "." for the relative path.

~ here:
src/common/remote.ts:66
```
if (gitProtocol.host) {
  return new Remote(...)
}
```

perhaps the protocol scheme should also be checked?

WORKAROUND:
specify the bundle remote without leading `./` i.e.

```
$ git remote -v
abc  bundles/abc-def.bundle (fetch)
abc  bundles/abc-def.bundle (push)
origin  https://github.ghi.corp/orga/repo.git  (fetch)
origin  https://github.ghi.corp/orga/repo.git  (push)
```

**Comment by alexr00** [comment]
@cshorler thanks for debugging into this. I'm not able to reproduce the issue at all unfortunately. My steps:
1. Clone a GitHub Enterprise repo using the command line. 
2. Add a relative remote `abc`.
3. Properly set `github-enterprise.uri` to my enterprise remote url.
4. Open the cloned folder in VS Code.

I still correctly get the "Sign in" prompt in the GitHub view. Can you set `"githubPullRequests.logLevel": "debug"`, reproduce the issue, then share the output of GitHub Pull Request? Can you also open the developer tools and share anything that's in the console?

**Comment by cshorler** [comment]
@alexr00  after pressing sign-in I'm directed to github.com rather than the github enterprise URI previously configured

I guess we should add a point 5 for the test - 
5.  Perform sign-in (to GHE)

attached (logs - sanitised):

[ghauth.log](https://github.com/microsoft/vscode-pull-request-github/files/10339714/ghauth.log)
[gheauth.log](https://github.com/microsoft/vscode-pull-request-github/files/10339719/gheauth.log)
[ghpr.log](https://github.com/microsoft/vscode-pull-request-github/files/10339721/ghpr.log)

**Comment by alexr00** [comment]
@cshorler thank you for the additional details. I'm still not sure what's going on. As far as I can see we'll always offer you Enterprise login if one of your git remotes matches `github-enterprise.uri`. 

In your original post you say that the GitHub Pull Requests view just shows "Loading...". Where are you clicking "Sign in" from if the view just shows "Loading..."?
