### ISSUE TITLE
GitHub features do not appear when repos are in subfolders

### ISSUE THREAD

**Issue by radix** [microsoft/vscode-pull-request-github#436]
- Extension version:  0.1.2
- VSCode Version: 1.27.1
- OS: Windows 10

Steps to Reproduce:

1. Open a folder *containing* repos (not a repo directly; e.g., `~/work` folder which contains `~/work/ProductA`, `~/work/ProductB`, each of which are repos)
2. Navigate to the SCM sidebar
3. Notice that it shows a list of "Source Control Providers" with `ProductA`, and `ProductB` listed

VSCode supports multiple git repositories in subdirectories very well, but this extension doesn't seem to run at all in this scenario.

This may or may not be related to #386. That issue talks about multi-root workspaces, but my scenario involves only one root.

**Comment by davidrocks88** [comment]
Seeing this too on my environment:

- Extension version: 0.1.4
- VSCode Version: 1.27.1
- OS: MacOS High Sierra (10.13.6)

**Comment by dannyk81** [comment]
@radix @davidrocks88 this is currently not supported and is indeed related to #386, which I hope will be added soon 🙏

**Comment by RMacfarlane** [comment]
This should be fixed with the changes for https://github.com/microsoft/vscode-pull-request-github/issues/1936
