### ISSUE TITLE
Expansion slow in PULL REQUEST view

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-pull-request-github#4360]
The expansion in the PULL REQUEST view is slow because of the GH back and forth. Have we considered doing some requests to GitHub up front so we make the tree expand experience smoother?
Clicking on the `description` node also takes around a second.

For example, could we always request GH data for all visible nodes in advance to their expansion? So as the tree call render on the node (it becomes visible) we could request its expand state. Not sure how aggressive this would be, just an idea that we "predict" what the user might click and get that data in advance...

IMHO this would greatly help in the direction of making the experience butter smooth 🧈 

![Recording 2022-12-22 at 18 25 21](https://user-images.githubusercontent.com/1926584/209191550-d2ec871e-e543-4ce8-8d14-14b608ac6a1b.gif)

**Comment by alexr00** [comment]
How fast would our target be for expanding a PR? I am very hesitant to pre-fetch all the files and comments for all visible PRs since a PR could have many changes in it. 

I did find one call that we could defer slightly, which may save us 10s of milliseconds.

**Comment by isidorn** [comment]
@alexr00 ok. I will be happy to try it out once we have that improvement. 
As for the hesitation to pre-fetch all files and comments for visible PRs - is the concern that pre-fetching might take a long time or that it ends up being unnecessary?

**Comment by alexr00** [comment]
> As for the hesitation to pre-fetch all files and comments for visible PRs - is the concern that pre-fetching might take a long time or that it ends up being unnecessary?

The concern is that we would pre-fetch a lot of stuff that wouldn't be needed. 

Closing, as there has been a small improvement here. We can always re-open if we want to make further perf improvements.
