### ISSUE TITLE
RegExp error when parsing string containing ".(10725.01.1" 

### ISSUE THREAD

**Issue by robinmattern** [microsoft/vscode-pull-request-github#4367]
- Extension version: v0.57.2022122310
- VSCode Version:  v1.74.2
- OS:  Windows 10 

Steps to Reproduce:

1. Disable the extension: GitHub Pull Requests and Issues
2. Reload VSCode -- no problem 
3. Enable the extension: GitHub Pull Requests and Issues
4. Reload VSCode -- get the error see in the screen capture below 

![2022-12-23_19-22-36](https://user-images.githubusercontent.com/1158299/209415363-6f198f93-0fa0-4448-b078-f52e60cb90a4.png)

Even though I don't find this particular string, `.(10725.01.1 ...` when I search all the files in my repo, I do use this pattern, `.(YMMDD>NN USR Comment...` on almost every line of my code.  And lately I was using it in Commit comments, but I have stopped since Git converts parentheses into periods`.`  From time to time, I too get this RegExp error when creating a RegExp from data that might contain a parentheses.  Is this something you are willing to protect against?   Or could you tell me how to perhaps purge this string from my Repo's Git's history?  Other Repos that have they same pattern, don't fail.

**Comment by robinmattern** [comment]
After spending the holidays creating a repository by copying a folder with 51 files and 60 folders (most empty with just a .gitkeep file), this error would occur at random times.  But in the end, clicking on the GitHub Activity icon would just bring up the Loading... message.  Checking DevTools would always show the same invalid regular expression error.  Bottom line I was never able to use the your GitHub Pull Request feature.

So this morning I decided to copy in one folder at a time and it worked!!  I even tried initializing a repository for all the sub-folders and it worked.  I had a bunch of repository folder that I got the error in last week, but now the list of GitHub options always comes up.  Since I told you that I could not find that string in any file in any of the repositories that failed to load GitHub, I always assume there was some global stuff somewhere that git was finding, but it must be gone now.  I did reboot this morning, but I'm pretty sure I rebooted while I was getting the error.

**Comment by alexr00** [comment]
I think this a (fixed) upstream issue in one of our dependencies: https://github.com/cyjake/ssh-config/issues/34. I can't reproduce the issue you're seeing @robinmattern but I've updated the dependency to get the fix. If you can try out the pre-release version of the extension tomorrow (requires VS Code insiders) and see if you encounter the issue that would be very helpful!

**Comment by alexr00** [comment]
@robinmattern if you could try out the pre-release build and reply back on whether the issue still occurs for you that would be very helpful!
