### ISSUE TITLE
GitHub Pull Request Tree View not visible

### ISSUE THREAD

**Issue by will-tao** [Microsoft/vscode-pull-request-github#437]
- Extension version: 0.1.2
- VSCode Version: 1.27.1
- OS: Windows 10 Enterprise 
Steps to Reproduce:

1. Installed GitHub PullRequests extension
2. Restarted/reloaded vscode and app
3. Opened folder in branch and can see GIT is connected

Extension output:
Looking for git repository
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
Git repository found, initializing review manager and pr tree view.
> git config --local --get branch.master.github-pr-owner-number
Review> no matching pull request metadata found for current branch master
> git config --local --get branch.master.github-pr-owner-number
> git config --local --get branch.master.github-pr-owner-number

Is there an internal alias to use to debug? I do not want to post much debug data in a public forum.

**Comment by RMacfarlane** [comment]
Please have a look at https://github.com/Microsoft/vscode-pull-request-github/issues/418 and https://github.com/Microsoft/vscode-pull-request-github/issues/419, which are likely related

**Comment by will-tao** [comment]
I have, and there are no extra colons in the url for in the output for "git remote -v"
git config --get remote.origin.url has the same output

**Comment by RMacfarlane** [comment]
@will-tao could you provide the output of `git remote -v`, perhaps replacing the actual owner and repository with just `owner` and `repo`?

**Comment by RMacfarlane** [comment]
Got remote information from @will-tao, remote was pointing to VSTS instead of GitHub. Closing as this extension only adds support for GitHub Pull Requests

**Comment by omatrot** [comment]
I have to reopen this issue as VSTS uses git in my scenario.

**Comment by RMacfarlane** [comment]
Hi @omatrot, this extension only adds support for GitHub pull requests, not VSTS pull requests. VSTS is a separate backend and has slightly different data models, so we do not intend to add support for it within this extension. Instead, we will create a separate extension for it. Thanks

**Comment by omatrot** [comment]
Again, I am not using VSTS (TFS)  as source control, but git.

Every single git command works fine with these repos I showed you, VSCode git integration works perfectly.

Please at least elaborate on where VSTS comes interfere here.

Thanks in advance.
