### ISSUE TITLE
Pre-release version is changed after reloading

### ISSUE THREAD

**Issue by yhmtsai** [microsoft/vscode-pull-request-github#4372]
- Extension version: v0.57.2022122310 or v0.56
- VSCode Version: 1.74.2 
- OS: MacOS Mojave 10.14.6 

Steps to Reproduce:

1. click the button "switch to the pre-release version", which shows v0.57.2022122909
![image](https://user-images.githubusercontent.com/19565938/209986932-fcd2bbab-c096-4119-a8e3-1e441a1751c4.png)
it also shows reload required
2. click reload, and then it shows v0.57.2022122310
![image](https://user-images.githubusercontent.com/19565938/209987080-81aa2c2e-5de9-4b2b-becc-81fb1b4cdc68.png)
Install another version shows up to v0.57.2022122310

I switched the prerelease first time 1~2 days ago. VSCode Extension Markets already shows the later version than v0.57.2022122310, but I still get this version only.

**Comment by alexr00** [comment]
@yhmtsai the latest pre-release version often requires VS Code insiders. This is because the extension sometimes adopts new VS Code extension API that is only available in insiders.
