### ISSUE TITLE
Option not to add fork remotes to local repository

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-pull-request-github#4374]
One can fetch refs from a remote without adding the remote to the local repo: https://gist.github.com/yob/2bd96e979f2eee1d95c9d757ebc0d74b

IMO this should be the default when one checks out a PR: the remote refs are fetched and a local branch is created on them. I never really want to keep the fork's remote on my remotes list, despite there being a garbage collection util to remove them.

**Comment by alexr00** [comment]
We also now automatically clean up forks when you use the "Checkout main" button.

**Comment by alexr00** [comment]
You created the same issue 3 years ago 😆 https://github.com/microsoft/vscode-pull-request-github/issues/75
