### ISSUE TITLE
Update PULL_REQUEST_TEMPLATE file pattern

### ISSUE THREAD

**Issue by epanipinto** [microsoft/vscode-pull-request-github#4382]
We use `.github/PULL_REQUEST_TEMPLATE` without the `.md` file extension which is also supported by the GitHub UI. Since our repos don't have the file extension when I create a pull request using the VSCode extension the template file is not picked up. I would like to request that either the extension pick up the file with out the extension or to allow for this pattern to be configurable via user settings. 

https://github.com/microsoft/vscode-pull-request-github/blob/30ea44d3f18b5c221bfc23df03988ae12e7263cb/src/github/folderRepositoryManager.ts#L1211

Thanks!

**Comment by alexr00** [comment]
To verify:

1. Add a PULL_REQUEST_TEMPLATE (no file extension) file in the .github folder of a cloned GitHub repo. You don't need to commit or push the change.
2. Make sure you have `"githubPullRequests.pullRequestDescription": "template"` set.
3. Run the "Create Pull Request" command. Verify that the description of the PR is populated with the contents of your template.
