### ISSUE TITLE
Support GitHub Enterprise 2.2

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#4385]
Currently we support back to GitHub Enterprise 3.1 (https://github.com/microsoft/vscode-pull-request-github/wiki#2-is-github-enterprise-supported). This decision was made by considering the following:
- The version number of actual users filing issues on GitHub (collected by just asking users in issues what version they were using).
- The difficulty in supporting older version (known issues in GHES 2 and test infra only goes back to 3.1).
- Data that indicates that most Enterprise users are on 3.3 or higher.

This issue is intended to gauge the need/interest in support version 2.2.

**Comment by SuibianP** [comment]
@alexr00 Here is a non-comprehensive list of missing GraphQL object fields that I got on a quick try on GHE 2.21:
- `PullRequest.{viewerCanDisableAutoMerge, viewerCanEnableAutoMerge, autoMergeRequest, titleHTML}`
- `PullRequestReviewThread.{isOutdated, path}`
- `PullRequestChangedFile.viewerViewedState`

The support definitely cannot reach all the way back to 2.2 (circa 2015, was it a typo?), but I wonder if the final releases of GHE 2 can be supported? In the general case, could the introspectivity of GraphQL schemas be used to provide graceful fallback? Also, was there any past release that actually supported GHE 2? (0.28 as the first attempt for GHE support does not work, complaining about the missing `isOutdated` field).

While there is the deprecation cycle, Enterprises are notoriously bad at keeping up to date for various reasons, so I suppose there might be more such cases in hide among all GHES installations.

**Comment by tjx666** [comment]
I'm Github Enterprise 2.17.5 user. I can't login in by token.

**Comment by alexr00** [comment]
Looks like the interest in GitHub Enterprise 2 is very low, which I'm happy to see because it has been deprecated for a while. Closing as out of scope.
