### ISSUE TITLE
checkout pull request feature not working

### ISSUE THREAD

**Issue by corey-cosman** [microsoft/vscode-pull-request-github#4386]
keep getting error:

"Failed to execute git. Please check git output for more details" when checking out pull request. Tried reinstalling. Started happening a few months ago

- Extension version: v0.52.0
- VSCode Version:  1.72.2
- OS: macOS Mojave v10.14.2

Steps to Reproduce:

1. right click dropdown on a PR in the "ALL OPEN" tab
2. click Checkout Pull Request
3. error appears in bottom right corner of vscode with text "Failed to execute git. Please check git output for more details" and no additional output available in vscode output tab

**Comment by alexr00** [comment]
@corey-cosman could you try the latest version of VS Code and the latest version of the extension? If you still see the error, can you set `"githubPullRequests.logLevel": "debug"`, repro, then share the output from "git" and "GitHub Pull Request"?
