### ISSUE TITLE
Support for Start a Review workflow

### ISSUE THREAD

**Issue by jarshwah** [microsoft/vscode-pull-request-github#439]
Sorry if I missed it, but I'd like to see support for the "Start a Review" workflow when reviewing pull requests.

Rather than submitting each comment as you go, I'd like to batch the comments and send them off at once using the Start a Review feature of github PRs.

![start-review](https://user-images.githubusercontent.com/541083/45396302-19377700-b67e-11e8-9c88-42c19affbd0e.png)

**Comment by CoryWritesCode** [comment]
⬆️ vote
