### ISSUE TITLE
Add Branch Search Functionality

### ISSUE THREAD

**Issue by galezra** [microsoft/vscode-pull-request-github#4396]
I would like to suggest a feature to search through the list of branches when creating a pull request from the extension.

Currently, the list of branches is not searchable, making it slightly difficult to quickly find and select the desired branch, especially when working with a large number of branches. A search feature would allow users to easily filter the list of branches based on specific keywords or phrases, making it more efficient and user-friendly. 

This feature would be a nice addition to the extension as it would make the pull request process smoother and less time-consuming, particularly for those who work with a large number of branches.

**Comment by alexr00** [comment]
@galezra you can start typing when the branch dropdown is open to navigate quickly to a branch.

**Comment by galezra** [comment]
When one types a few characters in the list, the context of the search is disjointed, so a branch-specific search box would be useful, like this:

![image](https://user-images.githubusercontent.com/21019104/215263827-3440f9d5-b25b-4c3d-a990-bd7411c15ab9.png)

**Comment by alexr00** [comment]
This has moved into a quick pick, making it much more searchable.

**Comment by galezra** [comment]
Awesome! 🚀
