### ISSUE TITLE
Re-think PR creation flow

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-pull-request-github#4403]
Feedback from @burkeholland: "Why do we have an intermediate view in the viewlet when creating a PR, why not just use a Custom Editor to make it look like something users on GitHub are used to?" Using the Custom Editor in the Editor view that looks like the final Summary view would also make the transition calmer.

A benefit of showing the Creation view in the viewlet is that it makes it easy for users to preview the files their PR is touching.

I would just like if we re-think this, and if we decide that the leaving it in the Viewlet is the way to go then we should see how to polish the current experience.

@alexr00 ideally we should add some telemetry to see what percentage of users see the Creation view and do not finish creating it. And then explore how can we improve those numbers? 

fyi @daviddossett for ideas

Current view:
![Screenshot 2023-01-17 at 15 08 50](https://user-images.githubusercontent.com/1926584/212939061-68246750-a18e-4876-8bfc-e5d55d9ae194.png)

**Comment by alexr00** [comment]
We will continue to polish this, but the create flow has been significantly updated:
<img width="314" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/38270282/e9579fc4-e8a0-40f4-a8c5-e608e388f541">

**Comment by isidorn** [comment]
Awesome!
