### ISSUE TITLE
Rename GHPRI extension view hover

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode-pull-request-github#4404]
When I see the GHRPI extension view icon in the Activity bar, I see it's an Octocat that says `GitHub` on hover:

![image](https://user-images.githubusercontent.com/25310137/213002254-5debc03a-79ab-46b5-b44c-358c6d78a3d3.png)

I had just installed Copilot and thought this view was related to Copilot until I tried signing in and saw the permissions would be for GHPRI.

A hover title like `GitHub Pull Requests` would be helpful. There could also be perhaps more info, like extension name, in the viewlet before a user signs in (right now just mentions `GitHub` here too):

![image](https://user-images.githubusercontent.com/25310137/213002476-892ff12b-55ed-4868-85df-b230a13da071.png)

cc @isidorn @digitarald

**Comment by isidorn** [comment]
This is slightly related to the naming of the extension discussion @alexr00 and me had. The current name "GitHub Pull Requests and Issues" is a mouthful.

@alexr00 how about we call this view Pull Requests? And we keep the icon. I think the term "Pull Request" is already associated with GitHub so a GitHub prefix is not needed. I believe that and the icon will make it clear to the users.
Alternative names "Pull Requests", "Pull Requests and Issues".

fyi @burkeholland

**Comment by alexr00** [comment]
We changed it to "GitHub" from "GitHub Pull Requests" three years ago to better include the Issues view. 

I would tackle this in conjunction with the renaming the extension. If we rename the extension to "GitHub Pull Requests" then let's also rename the view to "GitHub Pull Requests". Users seem to have a mental model of each activity bar icon mapping directly to an extension so this would line up with that well.
