### ISSUE TITLE
Treeview do not appear when defining host aliases in .ssh/config

### ISSUE THREAD

**Issue by cssho** [Microsoft/vscode-pull-request-github#441]
- Extension version: `0.1.3`
- VSCode Version: `1.27.1`
- OS: `Windows 10`

Steps to Reproduce:

1. Setting git remote
```
$ git remote -v
origin  git@github.com.cssho:cssho/vscode-svgviewer.git (fetch)
origin  git@github.com.cssho:cssho/vscode-svgviewer.git (push)
```

2. Defining host aliases in .ssh/config
```
Host github.com.cssho
    HostName github.com
    ~
```

3. Opened the SCM sidebar
4. No Pull Request treeview appeared and no alert to login either.

**Comment by WNemencha** [comment]
Confirmed, same bug here. :(

**Comment by RMacfarlane** [comment]
This should be fixed with https://github.com/Microsoft/vscode-pull-request-github/pull/621, please give the newest version (0.2.3) a try

**Comment by AyaMorisawa** [comment]
Confirmed in
- Extension version: 0.2.3
- VSCode Version: 1.29.1
- OS: Linux
