### ISSUE TITLE
File context menu items show up without GitHub remote

### ISSUE THREAD

**Issue by remcohaszing** [microsoft/vscode-pull-request-github#4412]
Type: <b>Bug</b>

Create a git repository and a file

```sh
mkdir example
cd example
git init
touch foo
code .
```

Right click on the file named `foo` in the file explorer.

There should be no GitHub related context menu items, but there are.

Extension version: 0.56.0
VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:57:40.428Z)
OS version: Linux x64 6.0.12-76060006-generic
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 4000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|31.07GB (20.85GB free)|
|Process Argv|--goto . --crash-reporter-id 3d3e1416-1695-47d1-a8ee-a1301fe0769b|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pop|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30577860
nodejswelcome1cf:30587006
282f8724:30602487
pyind779:30647091
f6dab269:30613381
fim-prod:30623723
vscsbc:30628655

```

</details>

**Comment by mjbvz** [comment]
I'm still seeing `Copy Github Permalink` and `Copy GitHub Head link` showing up in v0.57.2023012411

Running these commands shows

![Image](https://user-images.githubusercontent.com/12821956/214443816-5642c663-1b84-46ff-8e78-dc0958d19586.png)

**Comment by alexr00** [comment]
@mjbvz are you finding those commands in the command palette? I'll remove them from there too.
