### ISSUE TITLE
Extra line shown in PR review editor that doesn't exist in source

### ISSUE THREAD

**Issue by geoff-va** [microsoft/vscode-pull-request-github#4419]
- Extension version: v0.56.0
- VSCode Version: 1.74.3 
- OS: MacOS Ventura 13.1

Steps to Reproduce:

1. Checked out a PR
2. Clicked a file to do a diff on in the PR review panel

The file diff on github shows the following:
![image](https://user-images.githubusercontent.com/11033703/213537320-f7b3ca68-7eec-4e86-8612-40c87facd7bf.png)

The diff in VsCode shows an extra line that doesn't seem to exist at all
![image](https://user-images.githubusercontent.com/11033703/213537433-b10a203b-a289-4093-8d7a-ddce869874c8.png)

So on github.com it shows line 170 is the new line (correct as far as I can tell), but VsCode is showing line 171 as the new line (but that line doesn't actually exist).

The only change to this file was adding the additional empty line at the end of the file (line 170)

**Comment by alexr00** [comment]
@geoff-va is this PR in a public repo? Ideally I'd be able to take a look at the PR itself to repro the issue since I haven't seen this before.

**Comment by geoff-va** [comment]
Unfortunately no it is not. Ia there anything I can try and otherwise provide?

**Comment by geoff-va** [comment]
Ah ok. Using vscode installed on MacOS. 

I’ll create an open source repo and see if I can construct a similar scenario to see if it is reproducible in any way.
