### ISSUE TITLE
After updating vscode insiders, getting `wants API proposal 'commentsResolvedState'` with Github Extension

### ISSUE THREAD

**Issue by rdbisme** [microsoft/vscode-pull-request-github#4425]
Type: <b>Bug</b>

1. Run vscode insiders (using `scoop`)
2. Get error in loading extensions during the load of extension

```
Extension 'github.vscode-pull-request-github' wants API proposal 'commentsResolvedState' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
```

Extension version: 0.57.2023011911
VS Code version: Code - Insiders 1.75.0-insider (9ccc2b3b30c122afe45bc6722bef0e3901fb2806, 2023-01-20T05:23:24.298Z)
OS version: Windows_NT x64 10.0.22623
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 5.15.83.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600X 6-Core Processor              (12 x 3700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.93GB (17.58GB free)|
|Process Argv|--crash-reporter-id db8c06e1-fb8a-4da0-98f2-cada77288243|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Arch|
|OS|Linux x64 5.15.83.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 5 5600X 6-Core Processor (12 x 3700)|
|Memory (System)|15.59GB (13.82GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12cf:30622697

```

</details>

**Comment by alexr00** [comment]
Thanks for the reminder to remove this!

**Comment by sylvzhz** [comment]
This still happens to me, can anyone tell me want to do exactly :(

**Comment by Denta-ai** [comment]
> This still happens to me, can anyone tell me want to do exactly :(

Same here, I still don't know how to fix it

**Comment by sylvzhz** [comment]
> 

The downgrade method doesn't work for me so I guess I'll have to wait until the next update if that's correct. Thanks anyway!

**Comment by sylvzhz** [comment]
> > This still happens to me, can anyone tell me want to do exactly :(
> 
> Same here, I still don't know how to fix it.
> 
> Edit: this is the answer `https://github.com/microsoft/vscode-pull-request-github/issues/4518`

The downgrade method doesn't work for me so I guess I'll have to wait until the next update if that's correct. Thanks anyway!
