### ISSUE TITLE
Monorepo support

### ISSUE THREAD

**Issue by ajkl2533** [microsoft/vscode-pull-request-github#443]
I'm working on only one project in monorepo. So I have open in VS Code only the folder I'm working on.

E.g.
```
Repo
| - Project 1
| - Project 2 --> this one I have open in VS code as a project
```

If I try to open a file from Comments tab VS Code throws an error.
```
Unable to open 'file': File not found (file:///path-to-file).
```

Could be there a feature where I can set the root folder for the project and use it for opening files?

**Comment by borekb** [comment]
In the current version, I get most of the functionality but there are no gutter decorations so that I could use to leave comments. I have to open the monorepo root in VSCode to get this functionality, subdirectories don't work.

**Comment by RMacfarlane** [comment]
This should be fixed with the changes for https://github.com/microsoft/vscode-pull-request-github/issues/1936
