### ISSUE TITLE
Test `githubPullRequests.postCreate` set to `checkoutDefaultBranch`

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#4430]
Refs: https://github.com/microsoft/vscode-pull-request-github/issues/4400

- [x] anyOS @eleanorjboyd
- [x] anyOS @joaomoreno 

Complexity: 1

[Create Issue](https://github.com/microsoft/vscode-pull-request-github/issues/new?body=Testing+%234430%0A%0A&assignees=alexr00)

---

1. Install the pre-release build of GitHub Pull Requests and issues.
2. Set `githubPullRequests.postCreate` to `checkoutDefaultBranch`.
3. Open a folder with a clone of a GitHub repo.
4. Create a topic branch and then create a PR.
5. Verify that the PR is created and the default branch of your repo is checked out.

**Comment by roblourens** [comment]
@joaomoreno is listed as N/A for TPIs this month, so I had to remove him. This is only 1 point though so if he wants to test it he can just take over from someone else

**Comment by roblourens** [comment]
Actually I will remove the test slot entirely then we can add him after assignment...

**Comment by joaomoreno** [comment]
Works like a charm, thanks @alexr00!

One small nit: it would be great if this respected the [`git.fetchBeforeCheckout` setting from the Git extension](https://github.com/microsoft/vscode/pull/160181), introduced by @lszomoru. Let me know if you'd like an issue for it.
