### ISSUE TITLE
Test "suggest a change" flow

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#4434]
Refs: https://github.com/microsoft/vscode-pull-request-github/issues/603

- [x] anyOS @gregvanl
- [x] anyOS @bhavyaus
- [x] anyOS @bpasero

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode-pull-request-github/issues/new?body=Testing+%234434%0A%0A&assignees=alexr00)

---

1. Install the pre-release version of the extension.
2. Open a folder that contains a GitHub repository.
3. Open a file from a pull request (this can be done from the "Pull Requests" view).
4. Start to leave a comment.
5. Verify that you see a button to "make a suggestion"
6. Verify that when you click the "make a suggestion" button the lines associated with the comment that you're leaving get added to the comments editor. Try this out with selections of varying lengths. 
7. Complete your comment. Verify that the suggestion renders in a reasonable way and is recognizable as a suggestion.
8. Verify that if you edit a comment with a suggestion it shows the original comment text.
9. Verify that you see a "gift" action to apply the suggestion on comments that contain a suggestion.
10. Verify that if you apply a suggestion that the suggestion is applied locally.

**Comment by albertusdev** [comment]
@alexr00 thank you so much for the great work here! I tested the ```suggest``` block on the latest release version and it was working great! But I'm curious about this "make a suggestion" button which you mentioned is available on the latest pre-release.

I'm currently on v0.57.2022122310 but I'm not able to see this button anywhere though
![CleanShot 2023-01-24 at 16 59 59](https://user-images.githubusercontent.com/25892469/214262655-a91147e5-1d5a-4416-8708-01e81e5181d5.png)

Am I missing something here or is that not the right place to expect the suggestion button?

**Comment by alexr00** [comment]
@albertusdev there's a bug, which I plan to fix today: https://github.com/microsoft/vscode-pull-request-github/issues/4438
