### ISSUE TITLE
Keyboard shortcuts don't work in Pull Request views

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode-pull-request-github#4436]
Testing #4432

1. Bind pr.openModifiedFile to Ctrl+J Ctrl+U

You can see the keybinding in the GHPRI "Changes in Pull Request" view:

![image](https://user-images.githubusercontent.com/12818376/214218452-4b4163d8-02e6-42ca-9fd8-9b63bcd3c176.png)

2. From the Pull Request view try the keyboard shortcut Ctrl+J Ctrl+U.

No response. You can select the command from the context menu but even though the keybinding is shown in the context menu, it does not open the modifed file.

The same issue is present in the regular "Pull Request" view

**Comment by alexr00** [comment]
This is currently how all keyboard shortcuts work in tree views.
