### ISSUE TITLE
Gift icon to apply a change is a bit hard to figure out

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-pull-request-github#4439]
Testing #4434

Maybe a different icon should be used or is this the official GH icon?

**Comment by alexr00** [comment]
It's not the official GH icon, I just picked it. I'm not sure which other icon would be better though: https://microsoft.github.io/vscode-codicons/dist/codicon.html

**Comment by bpasero** [comment]
//cc @daviddossett

**Comment by alexr00** [comment]
We have almost 3 times as many users who make a suggest as who apply a suggestion. Looks like we might have a problem here.

**Comment by alexr00** [comment]
@hbons in case you have thoughts on this.

**Comment by alexr00** [comment]
I can add the "Apply suggestion" to the right click context menu if the comment has a suggestion. Let's see if that helps.
