### ISSUE TITLE
Don't offer to add labels when I don't have permission to do so

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-pull-request-github#4444]
Testing #4433

I'm offered to add labels to a PR on a repository I don't have permissions for. Admittedly didn't hit "Create PR", but I don't have permissions here: https://github.com/microsoft/python-sample-vscode-django-tutorial from what I see.

**Comment by bhavyaus** [comment]
The "Add labels" icon still shows but disappears when I try to click it when I try to create a pull request in a repo I dont have permissions on. 

https://user-images.githubusercontent.com/25044782/214958932-a1e02d81-5e5f-4c2e-a0b2-0c32b5426230.mp4
