### ISSUE TITLE
PR quick diff: Mix of PR diff and current working changes

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-pull-request-github#4449]
Testing #4435

The mix of PR diff and current working changes is difficult to understand. I guess when I start working on top of the PR, I might be more interested in my current changes than the PR's changes.

Also: The 'revert' button is missing in my current changes' peek widget when I have a PR checked out.

**Comment by sbatten** [comment]
I could see moving to a mode where you only see your changes in the gutter, but I would not expect this to be the default. The quick diffs give a good understanding of all changes in the PR including your fresh changes which is pretty cool. I personally would probably rely on the PR view and the SCM view for seeing changes scoped to just me|PR

**Comment by alexr00** [comment]
Multi quick diff UX has been added and polished:

![Recording 2023-02-16 at 15 43 06](https://user-images.githubusercontent.com/38270282/219398534-dead7007-b3aa-41e6-974a-69506777c8ee.gif)
