### ISSUE TITLE
Make file paths in description clickable

### ISSUE THREAD

**Issue by jaygraygray** [Microsoft/vscode-pull-request-github#445]
![image](https://user-images.githubusercontent.com/20447909/45428123-87743d80-b66e-11e8-8ac2-604865f898d1.png)

It'd be nice to be able to click the file path to be taken directly to the file that's being commented on.

**Comment by rebornix** [comment]
Duplicate of https://github.com/Microsoft/vscode-pull-request-github/issues/742, let's track it there. Thanks for reporting this issue!
