### ISSUE TITLE
Too many labels has unexpected results

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode-pull-request-github#4452]
Testing #4433

I tried creating a PR and adding all 450 labels to the PR at creation time. The labels show up in the view as if this is fine. Once, I created the PR it looked like a no-op but the PR was actually opened with no labels on .com

**Comment by sbatten** [comment]
@alexr00 thanks for the change, one small tweak since in my testing no labels could were added to the resulting PR: instead of "Not all labels could be added..." maybe "Some or all labels could not be added..."

**Comment by alexr00** [comment]
Updated!
