### ISSUE TITLE
Adding new line to a suggestion is ignored

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode-pull-request-github#4455]
Testing #4434

Somehow GHPRI suggestions aren't preserving new lines and aren't able to add them back.

For example, this change happened when just updating Markdown text. https://github.com/microsoft/vscode-docs/pull/5970/commits/dc67f08d17df0b5e97339d2de38687a3a1e2a85e

If I try to create a suggestion adding back the new line, the suggestion is ignored and the gift button does nothing.

**Comment by gregvanl** [comment]
A little hard to see what's going on but applying a suggestion to add a new line above the "GDPR and VS Code" H2 ended up removing the line below the H2?

![image](https://user-images.githubusercontent.com/12818376/214446198-d44852fb-ec60-4f86-8980-dc24317d0fd5.png)

**Comment by alexr00** [comment]
@gregvanl did you have other local changes in the file at this time? I think what happened is the line that the comment was originally on got changed by local changes, then we you tried to apply the suggestion it did something weird.
