### ISSUE TITLE
Should edit pencil be disabled on suggestions?

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode-pull-request-github#4457]
Testing #4434

I might be misunderstanding use of the pencil button on a suggestion but if you edit the suggestion and select Save, the edits are not kept.

Step 8 of the test plan item makes it sound like this is "by design" but I'm confused why there is an enabled pencil button if that is the case.

**Comment by alexr00** [comment]
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/4454
