### ISSUE TITLE
Comment text should wrap

### ISSUE THREAD

**Issue by redders6600** [microsoft/vscode-pull-request-github#446]
Appreciate that comments support markdown, but I think the default behaviour for comment text should be that it wraps. If this is an unpopular opinion then perhaps add an option to the extension to enable wrapping.

**Example screenshot** - I would expect the text to wrap when it reaches the end of the box rather than adding horizontal scroll.
![Text should wrap here](https://user-images.githubusercontent.com/2893500/45430549-75f65a00-b69d-11e8-972a-32595903ec08.png)

**Comment by connorshea** [comment]
I would also expect it to wrap, as that's what happens with the GitHub web interface (and most other markdown input fields I've seen)

**Comment by alexr00** [comment]
Seems like this has changed since the issue was filed. Comments wrap now.
