### ISSUE TITLE
`gh pr checkout` isn't recognized as checkouted PR branch anymore

### ISSUE THREAD

**Issue by xxchan** [microsoft/vscode-pull-request-github#4464]
- Extension version: v0.56.0
- VSCode Version: 1.74.3 
- OS: MacOS

Steps to Reproduce:

1. Use [GitHub CLI](https://github.com/cli/cli) to checkout a PR  (gh version 2.21.2 (2023-01-03))

**Comment by alexr00** [comment]
It looks like that just checks out the PR branch, which I'm still seeing recognize as a PR. Are you using the `branch` arg in the CLI?

**Comment by xxchan** [comment]
Here's an example: https://github.com/risinglightdb/sqllogictest-rs

```
❯ gh pr checkout 157
Switched to branch 'cli-multi-files'
```
<img width="84" alt="image" src="https://user-images.githubusercontent.com/37948597/214838961-2ba7b032-88fe-445a-b45e-7401349126c8.png">

There's no "Pull request" sidebar.

If I click 
<img width="379" alt="image" src="https://user-images.githubusercontent.com/37948597/214839136-e5eeecfa-5e0d-4b23-8f5b-215d315c701a.png">

It will checkout `pr/2010YOUY01/157`, and the sidebar occurs.

<img width="315" alt="image" src="https://user-images.githubusercontent.com/37948597/214839281-95f9cbf7-1c5d-455e-b01f-86e6f243f3ed.png">

**Comment by alexr00** [comment]
We should be able to match the remote of the PR branch with a PR.

**Comment by alexr00** [comment]
The GitHub CLI doesn't add a new remote for PRs checked out like this, but this extension currently requires that there be a remote for the repo of the fork. 

First we need to do https://github.com/microsoft/vscode-pull-request-github/issues/75, then this issue is easily addressed.

**Comment by alexr00** [comment]
Tentatively adding for July. I don't think the number of upvotes/comments here accurately represent how much of a pain point this is.

**Comment by alexr00** [comment]
Rather than do the big refactor to not depend on having a git remote for forks, I have made a much smaller change that will add a git remote for the new PR branch and update the remote of the branch to use the new git remote.
