### ISSUE TITLE
Make a suggestion sometimes only works once

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#4470]
From @eleanorjboyd:

The `make suggestion` button is clickable multiple times when first creating the comment then when editing the comment you can only click it once.

https://user-images.githubusercontent.com/26030610/214892515-6933053c-19fe-4a55-bd0a-d856848fd54d.mov

**Comment by andreamah** [comment]
I'm still running into this:
[![Image from Gyazo](https://i.gyazo.com/f3dcf4997b5fed67396c66b89a50b4bf.gif)](https://gyazo.com/f3dcf4997b5fed67396c66b89a50b4bf)

I notice that I can only add a suggestion again when I unfocus the textbox and re-focus it.

**Comment by karrtikr** [comment]
I'm still able to repro the issue, is that because the fix hasn't been released yet?

**Comment by rzhao271** [comment]
LGTM. @karrtikr are you on the latest pre-release? v0.59.20230224

**Comment by karrtikr** [comment]
Ah, that was the issue, thanks.
