### ISSUE TITLE
Sign in button does not appear

### ISSUE THREAD

**Issue by kevinwasie** [microsoft/vscode-pull-request-github#4474]
- Extension version: 0.56.0
- VSCode Version:1.74.3
- OS:Mac Monteray 12.0.1

Steps to Reproduce:

1. Install GitHub extension

The login button never displays in the extension. It simply states "Not git repositories found" but I have no ability to login. There is no button.

**Comment by alexr00** [comment]
@kevinwasie did you open a folder that contains a git repository?
