### ISSUE TITLE
No horizontal scrollbar when trying to view long suggested changes in a pull request

### ISSUE THREAD

**Issue by bhavyaus** [microsoft/vscode-pull-request-github#4480]
- Extension version:
- VSCode Version: insiders.vscode.dev
- OS:

Steps to Reproduce:

1. Open a pull request with suggested code changes with longer lines of text.
2. Resize the window and observe that the suggested changes text does not resize (other text such as description/comments resizes). I'm also unable to scroll horizontally (via mouse/keyboard) to view the rest of the suggested change. 

<img width="614" alt="image" src="https://user-images.githubusercontent.com/25044782/215581943-be13c487-4c83-40cf-b510-59312c0654a6.png">

**Comment by alexr00** [comment]
Upstream issue: https://github.com/microsoft/vscode/issues/172363
