### ISSUE TITLE
GHPRI does not render <img> tags in comments on desktop

### ISSUE THREAD

**Issue by bhavyaus** [microsoft/vscode-pull-request-github#4485]
- Extension version:
- VSCode Version:
- OS:

Sample comment with image in GHPRI
<img width="2193" alt="image" src="https://user-images.githubusercontent.com/25044782/216139519-f4718a22-e4a9-4416-961d-26d1a2c70fb9.png">

On GitHub:
<img width="964" alt="image" src="https://user-images.githubusercontent.com/25044782/216139572-061f2d5c-64a1-444b-99cd-347c1bc33731.png">

**Comment by alexr00** [comment]
Can you share a link to the PR you're seeing this with? I'm not able to reproduce it.

**Comment by alexr00** [comment]
Got a link offline. It turns out that the images in that PR are `img` tags and not markdown images. We only support markdown images, so these images don't render. The next question is: how did these end up as `img` tags and not markdown images.

**Comment by bhavyaus** [comment]
I inserted the image via paste (Ctrl+V) after taking a screenshot. I do this with the all GitHub PRs and Issues (including this one) and see that it was also inserted with the <img> tag.

`img` appears to be supported in the description which is why I assumed we supported in the comments as well. Example pr with `img` in the description https://github.com/microsoft/vscode/pull/173128

**Comment by alexr00** [comment]
The PR description page directly uses GitHub's HTML for the comment so it renders fine there. The comment only supports makrdown though, and `img` isn't included in that support. 

I wonder if GitHub changed something here. I've never seen an `img` inserted before, only the markdown syntax for an image. I'll follow up with them to see what's changed.

**Comment by vittorius** [comment]
Hit the same thing today. Would be great to have this fixed, please 🙄

**Comment by alexr00** [comment]
Fix will go into pre-release next week, but it will only work for public repos.

**Comment by alexr00** [comment]
To verify:
1. Add a code comment, not just a comment in the PR timeline, to a public PR with an `img` tag in it, where the `img` points to a file that was uploaded to github by pasting.
2. Open that comment in GHPR and verify you can see the img.

**Comment by rzhao271** [comment]
Not working, e.g. https://insiders.vscode.dev/github/microsoft/vscode/pull/223104

**Comment by alexr00** [comment]
Looks like this is a COI issue. The fix is still good on desktop.
