### ISSUE TITLE
Adding issue in file from submodule opens issue in main repo

### ISSUE THREAD

**Issue by Adspectus** [microsoft/vscode-pull-request-github#4487]
- Extension version: v0.56.0
- VSCode Version: 1.74.3
- OS: Ubuntu 20.04

Steps to Reproduce:

1. Open a project with submodule(s)
2. Open file which is contained in submodule
3. Add TODO anywhere
4. Add issue from popup

The issue is created in the main repo, not in submodule repo

**Comment by alexr00** [comment]
Should be fixed by the recent submodule improvements!
