### ISSUE TITLE
Allow user to start a new comment thread on line that already has a comment

### ISSUE THREAD

**Issue by jongio** [microsoft/vscode-pull-request-github#450]
Problem: If anyone adds a comment to a line of code, then no one else can comment on that line.
Solution: Allow multiple comments per line.

**Comment by RMacfarlane** [comment]
Hey @jongio, this should already be supported. Comments are grouped into threads based on line position, as they are on GitHub. To comment on the same line you can respond to the existing thread

**Comment by jongio** [comment]
Here's further clarification on the request:

1. VS Code allows only allows you to respond to an existing comment, which adds it to the thread.
2. GitHub.com allows you to add another comment to the same line, which starts a new thread.  Make sure you are using the "Files Changed" tab to see this.

I also updated the title.
