### ISSUE TITLE
Allow me to checkout a PR in vscode.dev from the GHPRI PR view

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-pull-request-github#4500]
<img width="582" alt="image" src="https://user-images.githubusercontent.com/30305945/217057060-a7bd0a85-6332-4977-9c23-4ba2def50083.png">

We have the ability to checkout a PR or open the PR on GitHub from the PR view context menu. I would love an `Open/Checkout PR on vscode.dev` button in this context menu, so that I can review a PR without blowing away my local checkout.

**Comment by alexr00** [comment]
Fixed by https://github.com/microsoft/vscode-pull-request-github/pull/4591
