### ISSUE TITLE
Got an error "Activating the Pull Requests and Issues extension failed. Please make sure you have git installed."

### ISSUE THREAD

**Issue by tmorgan497** [microsoft/vscode-pull-request-github#4501]
- Extension version: v0.58.0
- VSCode Version: 1.75.0
- OS: Windows 11 Pro 22H2

Steps to Reproduce:

1. Open VS Code Source Control
2. Get error message "Activating the Pull Requests and Issues extension failed. Please make sure you have git installed."
![image](https://user-images.githubusercontent.com/21185911/217058396-916ded83-e43c-41ce-ad00-69459acefcd2.png)
![image](https://user-images.githubusercontent.com/21185911/217058264-381eb44b-4a7c-4468-b430-5446206e9aca.png)
3. Attempt to enable git in settings
![image](https://user-images.githubusercontent.com/21185911/217058586-391edc7d-7740-4776-9ced-e48f4f370d6d.png)
4. Get error message "Unable to write to User Settings because git.enabled is not a registered configuration."
![image](https://user-images.githubusercontent.com/21185911/217058650-624c72af-2ee4-4f66-8a40-97bc9c62f54b.png)
5. Check if git is installed
![image](https://user-images.githubusercontent.com/21185911/217058829-951240c9-a0bc-4908-b226-5011da0aff0a.png)

**Comment by alexr00** [comment]
@tmorgan497 do you have the built in Git extension enabled (search for `@builtin git` in the input box in the "Extensions" view)?
