### ISSUE TITLE
Re-request review button has strange UI treatment in narrow viewports

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-pull-request-github#4502]
<img width="280" alt="image" src="https://user-images.githubusercontent.com/30305945/217064574-40b307d6-69c3-4cd0-9585-b03a53655890.png">

Awesome that I can re-request a review on a PR from the GHPRI view 🎉 I initially didn't realize that this was the button to re-request a review from a specific reviewer because I was surprised to see that it had a blue background and also appeared to render on top of the reviewer's GitHub handle. 

I'd expect a treatment more similar to our other toolbar actions--background on hover and pointer--as well as for the reviewer's GitHub handle to have `text-overflow: ellipsis`. I'd also expect the refresh codicon to be vertically aligned with the checkmark codicon.
<img width="83" alt="image" src="https://user-images.githubusercontent.com/30305945/217064959-4deae789-1505-434a-a076-caec90ea0ac5.png">

**Comment by joshuaobrien** [comment]
Want me to grab this one @alexr00?

**Comment by alexr00** [comment]
@joshuaobrien that would be great. The goal is to make it look like the same button/icon in the description/overview.

![image](https://user-images.githubusercontent.com/38270282/217250211-1beba95d-ff3f-45c4-bc61-525f3c37c757.png)

**Comment by alexr00** [comment]
@joshuaobrien I'm going to fix this on Monday if I haven't seen a PR from you by then! We're getting ready to release and this one needs to be fixed before we do.

**Comment by joshuaobrien** [comment]
I've raised a fix in #4539. During the process, I think I found a bug where the associated command doesn't get handled. I've tried to address that in #4540. Please me know if you'd like me to make an issue for it :)
