### ISSUE TITLE
Adding more line links in an already created issue 

### ISSUE THREAD

**Issue by davidRFB** [microsoft/vscode-pull-request-github#4506]
HI ! I was wondering if it is possible to add another comment into an issue that was already created using the TODO comment. 

Example 
```
def func1():
    #TODO #5 Modification 1
    etc
```
then after created the issue #5. I would like to know if it possible to add a new comment in other part of the code 

```
def func2():
    #TODO #5 Modification 2 that is related with issue  ( THIS COMMENT WOULD BE APPENDED TO THE ISSUE)
    etc
```

**Comment by alexr00** [comment]
Currently not possible. The idea is to look for places that start with the same content as the line the issue was original created from and then append all those lines to the issue.
