### ISSUE TITLE
Pull request incorrectly associated with "main" in "Local Pull Request Branches" list

### ISSUE THREAD

**Issue by neoGeneva** [microsoft/vscode-pull-request-github#4508]
I have a pull request that thinks the branch it's on is `main`, even though it has its own branch `neoGeneva/issue4013`. 

The list of files changed shown in the sidebar is correct, and the message "neoGeneva merged changes into main from neoGeneva/issue4013" is correct. But when I select "Checkout Pull Request" it attempts to switch to `main`, and the pull request is forever stuck in "Local Pull Request Branches" even though the actual branch is deleted.

- Extension version: 0.58.0
- VSCode Version: 1.75.0
- OS: Windows_NT x64 10.0.22623

Steps to Reproduce:

1. I'm unsure what I did, though it's likely I submitted the create pull request form while it was still loading.

**Comment by alexr00** [comment]
@neoGeneva is the pull request in a public repo, and if so can you share a link?

**Comment by neoGeneva** [comment]
@alexr00 private repo sorry, though the pull request mentioned above looks like this, which is normal as far as I can tell.
![image](https://user-images.githubusercontent.com/804724/218894784-3355b33b-7107-4ed0-8eb2-ef94ac2d9adf.png)

Today though I'm now getting a new, presumably related error. When I attempt to expand the "Local Pull Request Branches" collapse its content never loads and I get the following error for a totally unrelated pull request:
 `Element with id Local Pull Request Brancheshttps://github.com/Rubber-Monkey/Rubber-Monkey/pull/4054 is already registered` 

![image](https://user-images.githubusercontent.com/804724/218895118-a0681632-7d53-48d4-9b6c-ecd5cf8bef04.png)

Which again is just a regular pull request:

**Comment by alexr00** [comment]
Thanks @neoGeneva. I haven't been able to reproduce the issue. Can you set `"githubPullRequests.logLevel": "debug"`, reproduce the issue, then share the output from "GitHub Pull Request"? The output will have info like your repository name in it in case you want to redact before sharing.

**Comment by neoGeneva** [comment]
Here's the log, but I don't think there's much useful in there: [log.txt](https://github.com/microsoft/vscode-pull-request-github/files/10761044/log.txt)

I've figured out where that pr / branch data is stored, and when I run `git config --local branch.main.github-pr-owner-number` I get `Rubber-Monkey#Rubber-Monkey#4054`, and running `git config --local --unset branch.main.github-pr-owner-number` clears the issue for me.

And it's a bit more obvious why I was getting the `Element with id Local Pull Request Brancheshttps://github.com/Rubber-Monkey/Rubber-Monkey/pull/4054 is already registered` error, because the actual branch was still local:
![image](https://user-images.githubusercontent.com/804724/219492273-c0cd6124-ed3f-4bef-a8b4-899a56b30643.png)

So I'm pretty sure this is a race condition of some form, I do have a habit of clicking "Commit & Create Pull Request" and then submitting the create form before it has a chance to finish loading (which can sometimes be a couple of seconds), which usually just errors. I'm unsure how easy it would be to replicate, but I guess it would be nice if the "Create" button on the "Create Pull Requests" form was disabled while it was loading.

**Comment by Faith11maaga** [comment]
![IMG-20230216-WA0001](https://user-images.githubusercontent.com/125629509/219551205-9de43e7c-6425-4ca7-9f5f-eb513436ce24.jpg)

**Comment by Faith11maaga** [comment]
Request for errors issue and Recovery

**Comment by alexr00** [comment]
@neoGeneva I think your hunch that the association between main and the PR could be related to a timing issue with the "create PR" view makes sense. I'll take this as an issue to disable the submit button until it's finished loading.
