### ISSUE TITLE
VSCode crashes with error code 133

### ISSUE THREAD

**Issue by rhaschke** [microsoft/vscode-pull-request-github#4515]
See https://github.com/microsoft/vscode/issues/174047 for the original issue report.

- Extension version: 0.58.0 and 0.58.1 (Reverting to 0.56.0 fixes the problem)
- VSCode Version: 1.75.1
- OS: Ubuntu 20.04

Steps to reproduce:
1. `git clone https://github.com/ubi-agni/moveit_task_constructor.git mtc`
2. create `mtc/.vscode/c_cpp_properties.json` with the following content:
    ```json
    {
    "env": {
        "WorkspaceIncludePath": [
            "${workspaceFolder}/../../../devel/include",
            "${workspaceFolder}/core/include",
            "${workspaceFolder}/core/python/pybind11/include",
            "${workspaceFolder}/rviz_marker_tools/include",
            "${workspaceFolder}/visualization/motion_planning_tasks",
            "${workspaceFolder}/visualization/visualization_tools/include",
            "${workspaceFolder}/demo/include"
        ],
        "SystemIncludePath": [
            "/usr/include/eigen3",
            "/usr/include/OGRE",
            "/usr/include",
            "/usr/include/x86_64-linux-gnu/qt5",
            "/usr/include/x86_64-linux-gnu/qt5/QtCore",
            "/usr/include/x86_64-linux-gnu/qt5/QtGui",
            "/usr/include/x86_64-linux-gnu/qt5/QtWidgets"
        ]
    },
    "configurations": [
        {
            "name": "Noetic",
            "browse": {
                "databaseFilename": "",
                "limitSymbolsToIncludedHeaders": true
            },
            "includePath": [
                "${WorkspaceIncludePath}",
                "/opt/ros/noetic/include",
                "${SystemIncludePath}"
            ],
            "compilerPath": "/usr/lib/ccache/gcc"
        }
    ],
    "version": 4
    }
    ```
3. Run VSCode: `code mtc`
4. Wait a while for the crash to occur.

The extension attempts to link the `master` branch to https://github.com/ros-planning/moveit_task_constructor/pull/387, which is already weird. This PR has been merged a while ago and `master` has seen many further commits since then.

Note, that the `c_cpp_properties.json` file was required to trigger the bug. I don't see why, though.

**Comment by alexr00** [comment]
The log in the original issue makes this looks like it has the same cause as https://github.com/microsoft/vscode-pull-request-github/issues/4595. @rhaschke are you able to try again with the latest [pre-release](https://github.com/microsoft/vscode-pull-request-github/wiki/Pre-release-Build) version of the extension?

**Comment by rhaschke** [comment]
I can confirm that the error is fixed with the pre-release version (but was still present in 0.62)

**Comment by alexr00** [comment]
Thanks @rhaschke! We'll have a new stable release next week and the fix will be included there.
