### ISSUE TITLE
When a file is new in the PR, do not show a diff

### ISSUE THREAD

**Issue by waynebrantley** [microsoft/vscode-pull-request-github#452]
When you click on a newly added file in the PR, it shows a diff view.  The left have is blank except for one red line and the right half is the new file.

Instead - just show the new file - there is no need to 'compare' new files.

Potentially indicate clearly that it is a new file.

**Comment by eamodio** [comment]
Personally I prefer the consistency of this -- always opening a diff view for added/modified/deleted files.

**Comment by waynebrantley** [comment]
I respect the consistency argument, but just don't see the use of wasting half my screen real-estate for something that is always blank?

**Comment by wesleybowman** [comment]
It could be an option that could be modified in the setting, that way people could have either.

**Comment by alexr00** [comment]
I'm going with the consistency argument. It's how new files are show in git when opened from the SCM viewlet too.
