### ISSUE TITLE
batch mark/unmark file as viewed silently fails for large file sets

### ISSUE THREAD

**Issue by mfulton26** [microsoft/vscode-pull-request-github#4520]
- Extension version: 0.58.1
- VSCode Version: 1.75.1
- OS: macOS Ventura 13.1

Steps to Reproduce:

1. Open a pull request containing 300+ file changes in a single folder
2. Click the checkbox on the folder to mark all 300+ files as viewed
- There will be error logs in the console and if you reload the editor or view the PR on github.com you'll see that not all files were marked as read

I suggest adding support for marking/unmarking a set of files as viewed so that's its a single API call instead of what I think is being done through lots of tiny calls.

**Comment by joshuaobrien** [comment]
This one looks fun. Mind if I take a look @alexr00?

**Comment by alexr00** [comment]
Sure, thanks @joshuaobrien. Here's where we respond to the checkbox state change and mark the file as viewed. It's exactly as @mfulton26 suggested: if you mark 300 files as viewed we're calling the GitHub API 300 times.

https://github.com/microsoft/vscode-pull-request-github/blob/a42163688c6f82bf5fb3aa5781a25cbe62dbbb30/src/view/treeNodes/fileChangeNode.ts#L188
