### ISSUE TITLE
Azure Repo sign-in fails GH Enterprise error

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode-pull-request-github#4524]
Type: <b>Bug</b>

While having an Azure git repo open.

The GH PRI view should probably show that it doesn't work in non-GH repos, but instead it asks me to sign in – which fails with an error. Important to note is that I did not click the enterprise button, but the first sign in button.

![image](https://user-images.githubusercontent.com/8599/218583627-9b585610-723a-4bcc-84f1-fb85c2805871.png)

Extension version: 0.59.2023021309
VS Code version: Code - Insiders 1.76.0-insider (f718f1ace394dba4255774ac3f1c9321f629f8ff, 2023-02-13T05:27:04.434Z)
OS version: Darwin x64 22.3.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|4, 4, 4|
|Memory (System)|64.00GB (26.48GB free)|
|Process Argv|--enable-proposed-api donjayamanne.kusto --log trace --crash-reporter-id 4cf0a6f0-aaf8-4da3-9b2b-81f6c639c12b|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by bhavyaus** [comment]
Verified that I no longer see the sign in page.

<img width="702" alt="image" src="https://user-images.githubusercontent.com/25044782/221258211-eb65b14d-c69b-4a38-9146-526d86751eaa.png">


Should we add a message informing the user that the extension does not work on Azure repos?
