### ISSUE TITLE
Unable to login - Extension failed activating

### ISSUE THREAD

**Issue by gandroz** [microsoft/vscode-pull-request-github#4525]
- Extension version: 0.52.0
- VSCode Version: 1.72.2
- OS: Ubuntu (via SSH, host is Windows_NT x64)

Steps to Reproduce:

1. Install extension
2. Try to login

Eventually the login is established (I cannot confirm that) but got a blank content (no PR, no issue). In the debug log of the extension I got this

![image](https://user-images.githubusercontent.com/38106881/218584529-500c7066-f80e-4e8d-bff1-844b98ba8b81.png)

**Comment by alexr00** [comment]
@gandroz it looks like you're on old versions of VS Code and the extension. Are you able to reproduce the issue with the latest versions of VS Code and the extension?

**Comment by gandroz** [comment]
Sadly no, I dont have control on vscode deployment neither on the version of the extension. Maybe I am looking at a workaround ?

**Comment by alexr00** [comment]
Based on the stack trace, it's failing when it tries to parse the URI you have set for the setting `"github-enterprise.uri"`. Specifically, the scheme of the URI is invalid. Are you using GitHub Enterprise? What do you have `"github-enterprise.uri"` set to?

**Comment by gandroz** [comment]
Yes I use Github enterprise with a URI like « git@github.my.url:Lab/my_repo.git »

**Comment by alexr00** [comment]
I'm pretty sure that the scheme of a your URI can't contain `@`. The URI should be similar to what you'd put in your browser URL bar if you wanted to view your repo in the browser. In this case, it looks like you should just remove the `git@`.
