### ISSUE TITLE
New releases may cause vscode stuck at discovering Python Interpreters

### ISSUE THREAD

**Issue by triostones** [microsoft/vscode-pull-request-github#4526]
- Extension version: 0.58.0, 0.58.1
- VSCode Version: 1.75.1
- OS: a Debian(bullseye) container running on windows10 wsl2

Steps to Reproduce:

1. run a bullseye container that starts with sshd
2. connect to the container via remote ssh, install vscode-pull-request-github(version is v0.58.1) and vscode-python(v2023.2.0)
3. open a python file to activate the vscode-python extension, then vscode will be stuck at discovering python interpreters

I downgraded vscode-pull-request-github to v0.56, then these two extensions work well.

**Comment by alexr00** [comment]
@triostones can you share the output from GitHub Pull Request:
- from 0.58.1 and lower:
  - Set the setting `"githubPullRequests.logLevel": "debug"`
  - Reproduce the issue
  - Share the output from GitHub Pull Request
- from 0.59.* (pre-release builds)
  - command: Developer: Set Log level 
  - choose "GitHub Pull Request"
  - then click the little "Set as default log level" button to the right of the work "Debug"
  - Reproduce the issue
  - share the output from "GitHub Pull Request"
