### ISSUE TITLE
Code Block is interpreted as GitHub username

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode-pull-request-github#4527]
- Extension version: v0.58.1
- VSCode Version: 1.76.0-insider / 01d2cc631490d923f0c232daa2d0f076d8a6cc70
- OS: macOS

Steps to Reproduce:

1. Checkout a PR for reviewing
2. Write a comment with the content `` Use `@internal` to avoid this interface showing up in monaco.d.ts, where it isn't used. ``
3. Click "Start Review"
4. Observe that the comment appears to reference the GitHub user called `@internal`:

<img width="932" alt="image" src="https://user-images.githubusercontent.com/5047891/219017959-2307784d-3096-4986-aefe-1e7780c2938c.png">

**Comment by alexr00** [comment]
The username replacing is always going to be imperfect, but this one is at least easy to fix.
