### ISSUE TITLE
Permission error with a remote (dockerized) repository

### ISSUE THREAD

**Issue by navels** [microsoft/vscode-pull-request-github#4529]
- Extension version: v0.58.1
- VSCode Version: 1.75.1 (Universal)
- OS: M1 Mac Ventura 13.2.1

I am using the Dev Containers extension to connect to a dockerized repository and am encountering this error from the Pull Request extension:

> An error occurred when fetching the repository: fatal: detected dubious ownership in repository at '/app' To add an exception for this directory, call: git config --global --add safe.directory /app

I have plumbed my `$USER` and `$UID` through `docker-compose.yml` to the `Dockerfile` and used them to create my container user (from `Dockerfile`, edited for brevity):

```
ENV UID $UID
ENV USER $USER
...
useradd -u $UID -m -s /bin/zsh $USER
...
USER $UID
WORKDIR /home/$USER
WORKDIR /app
```

and the repository cloned on my host and mounted into the container (from `docker-compose.yml`):

```
volumes:
  - .:/app:cached
```

This has all been working for some time and is sufficient to make editing/ownership transparently the same whether I am editing files on the host or in the container.

However, I get this aforementioned error popup every time I start VSCode.  The extension seems to otherwise be working fine, so I can just ignore this but am wondering if there is some configuration I'm missing or possibly there is a bug in the extension.

I realize I could do the `git config` thing suggested by the error message, but it seems unnecessary given my setup.

Thanks!

**Comment by alexr00** [comment]
@navels could this be the same as https://github.com/microsoft/vscode/issues/172669? We're likely just surfacing the error from git.

**Comment by navels** [comment]
Okay woot I just ran into this error using the built-in Git plugin, so closing this issue and will continue to investigate.
