### ISSUE TITLE
Show files by commit

### ISSUE THREAD

**Issue by waynebrantley** [Microsoft/vscode-pull-request-github#453]
In larger PR, we will do different commits around groups of functionality.
For example if we update the data access layer - that would be one commit.
This helps speed the reviews up - by grouping logical commits.

Another use case is when I have requested changes to a PR - the developer creates a new commit and pushes that to the PR.  I do not want to have to re-review the entire PR - just the last commits, etc.

Love that the current implementation just shows the LATEST file - calculated from all the commits, so do not want to lose that - but perhaps use/show the commits in the view to help group the files, etc.

**Comment by rebornix** [comment]
We already show commits in **Changes in Pull Request** section but we didn't show that in Pull Request list view yet. Close this one for now but we can reopen the discussion if we think showing commits in Pull Request list view is necessary.
