### ISSUE TITLE
Show images in preview

### ISSUE THREAD

**Issue by waynebrantley** [microsoft/vscode-pull-request-github#454]
When a new image (png/jpg/etc) is added to a PR, clicking on it should show the image in vscode.

Currently it opens it up in a webpage (and that works), just no reason cannot preview this type of file.

Potentially add an extension point - where custom 'previewers' can be added for files (even to show a diff of modified images, etc)

**Comment by JacksonKearl** [comment]
Now seeing that clicking to open it will just throw an error, not open a webpage. (so #1461 has resurfaced)

**Comment by alexr00** [comment]
This should be working now.
