### ISSUE TITLE
Test re-requesting a review from the PR description page

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#4547]
Refs: https://github.com/microsoft/vscode-pull-request-github/issues/4092

- [x] anyOS @TylerLeonhardt 
- [x] anyOS @hediet
- [ ] anyOS @deepak1556 (Optional)

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode-pull-request-github/issues/new?body=Testing+%234547%0A%0A&assignees=alexr00)

---

Similar to github.com, you can re-request a review:
![image](https://user-images.githubusercontent.com/38270282/220160921-94c3bc00-9c0b-4f56-aa27-8ce090962aed.png)

1. Install the latest pre-release of GitHub Pull Requests and Issues
2. Open a folder in VS Code that contains a clone of a GitHub repo.
3. Open the PR description/overview of a PR
4. Verify that if a review has already been requested you can't re-request from that person. Verify that if someone has already approved or requested changes that you can re-request a review.

**Comment by TylerLeonhardt** [comment]
Closing since all required testers are done.
