### ISSUE TITLE
Test rendered permalinked lines

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#4548]
Refs: https://github.com/microsoft/vscode-pull-request-github/issues/4229

- [x] anyOS @sbatten
- [x] anyOS @bpasero
- [x] anyOS @andreamah
- [ ] anyOS @deepak1556 (Optional)

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode-pull-request-github/issues/new?body=Testing+%234548%0A%0A&assignees=alexr00)

---

Permalinked lines are now rendered in two places: Comments and the PR description.

Setup:
1. Install the latest pre-release of GitHub Pull Requests and Issues
2. Open a folder in VS Code that contains a clone of a GitHub repo.
3. Open a file that was changed in the PR.
4. Leave a comment in that file that contains a permalink to some lines that occur in the repo.
  a. You can easily create a permalink using the command "Copy GitHub Permalink"
5. Submit the comment

To verify in Comments:
6. Verify that after a brief delay the permalinked lines show in the comment.

To verify in the description:
6. Open the PR description
7. Verify that your comment from step 5 shows the permalinked lines as code lines and that they look reasonable. It is a known issue that there isn't any syntax highlighting.

**Comment by TylerLeonhardt** [comment]
Closing since all required testers have finished
