### ISSUE TITLE
Dropdown Menu Hard to See While Changes Menu Expanded

### ISSUE THREAD

**Issue by lummish** [microsoft/vscode-pull-request-github#455]
Issue Type: <b>Bug</b>

### Steps to Reproduce
1. Open Source Control manager
2. Try to find ```Github Pull Requests``` menu

### Expected Results
Menu should appear directly below current changeset

### Actual Results
The ```Changes``` menu takes up virtually the whole screen, relegating the ```Github Pull Requests``` dropdown to the very bottom of the screen.

![github pr](https://user-images.githubusercontent.com/8981664/45445804-189fe000-b680-11e8-9be9-3a3a19264884.png)

Extension version: 0.1.3
VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:14:32.385Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (1.90GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by dylmye** [comment]
IIRC this is standard vscode behaviour. Unsure if they provide an override.

**Comment by RMacfarlane** [comment]
Closing this, as the extension has been changed to add a new icon to the activity bar that will show the "GitHub Pull Requests" tree expanded by default
