### ISSUE TITLE
Test permalinked lines: no permalinked lines in comment in code file when permalink is only one line

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode-pull-request-github#4555]
Testing #4548

I see the permalinked lines in the PR description, but not when I browse to the comment itself. Testing on Ubuntu. 

<img width="943" alt="image" src="https://user-images.githubusercontent.com/31675041/220424630-6d7785bf-aed9-4303-80cc-081521af3ae2.png">

**Comment by sbatten** [comment]
I see the same

**Comment by alexr00** [comment]
To verify, make sure your permalink only contains a start line number (no end line number).
