### ISSUE TITLE
comments from an old / different PR are showing 

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode-pull-request-github#4558]
I checked out a PR that has no comments. The comments view is showing stale comments from an unrelated PR

![Screenshot 2023-02-21 at 12 26 18 PM](https://user-images.githubusercontent.com/29464607/220428753-22e03a7c-bf29-4e5c-8d94-b3ab95084c80.png)
Testing microsoft/vscode#174853

**Comment by alexr00** [comment]
Fixed by https://github.com/microsoft/vscode-pull-request-github/pull/4554

**Comment by meganrogge** [comment]
I have not checked out a PR within the last day but am seeing comments here - @alexr00 is that expected?

<img width="1652" alt="Screenshot 2023-02-22 at 2 56 17 PM" src="https://user-images.githubusercontent.com/29464607/220757118-be586ff6-514e-4879-bb04-67b47c66e76c.png">

**Comment by alexr00** [comment]
@meganrogge do you have the latest GHPRI pre-release version installed?

**Comment by meganrogge** [comment]
I did yes but am not seeing the comments hanging around today, so considering this fixed
