### ISSUE TITLE
Add status checks to the pull request description

### ISSUE THREAD

**Issue by patocallaghan** [microsoft/vscode-pull-request-github#457]
It would great to expose PR status checks in the description. For example in Github we see

![image](https://user-images.githubusercontent.com/685034/45452498-0c467200-b6d6-11e8-9ec3-c8f726467fa2.png)

**Comment by glemaitre** [comment]
+1 for this one

**Comment by Skowt** [comment]
+1 - Definitely a make or break for this extension

**Comment by hemlok** [comment]
+1 one of the key values of making a pr on GitHub's ui

**Comment by cat-turner** [comment]
+1 yass

**Comment by RMacfarlane** [comment]
With the change for https://github.com/microsoft/vscode-pull-request-github/issues/1105 now merged, all status checks should show up on the description page. This isn't released yet but will be available in the nightly version of the extension tomorrow.
