### ISSUE TITLE
Breadcrumb navigation doesn't work for newly created files

### ISSUE THREAD

**Issue by noalbalint** [microsoft/vscode-pull-request-github#4570]
Type: <b>Bug</b>

When reviewing PRs, it is sometimes helpful to view adjacent files. The easiest way to do that is through the breadcrumb menus. Unfortunately this is currently not possible.

Trying to open the breadcrumb navigation menu doesn't work. I'm pretty sure it used to, so maybe this is a regression? But I'm not certain.

Steps to Reproduce:

1. Open the extension
2. Select a PR you need to review
3. Try to click the breadcrumbs, to look at other files in that dir
4. See that it is not possible - menu does not open

<img width="737" alt="Screen Shot 2023-02-24 at 12 11 47 PM" src="https://user-images.githubusercontent.com/45208632/221165344-02e9b80d-8adb-4fc1-ad41-a42c556ecc59.png">

Extension version: 0.58.2
VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:34:59.000Z)
OS version: Darwin x64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|8, 9, 9|
|Memory (System)|32.00GB (0.03GB free)|
|Process Argv|--crash-reporter-id d176c4f9-07b7-4983-9468-326789314a76|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848:30662994
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983

```

</details>

**Comment by alexr00** [comment]
@noalbalint did you check-out the PR? Breadcrumbs are provided by your language extension, and most language extensions can't deal with the unchecked-out PR files as they don't really exist locally.
