### ISSUE TITLE
Not showing any PRs in workspaces

### ISSUE THREAD

**Issue by gevorggalstyan** [Microsoft/vscode-pull-request-github#458]
Issue Type: <b>Bug</b>

1. Create a workspace with more than one repos clones into it
2. Create some PRs for the second repo in the workspace list
3. Go to Source Control and in GITHUB PULL REQUESTS panel observe the values to be 0

If you only open the repo as a folder, the PRs are visible, but if you open it in a workspace the values are 0.

Extension version: 0.1.4
VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:14:32.385Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (3.09GB free)|
|Process Argv|/private/var/folders/by/z23k5y5n0gj156wj520kxy4c0000gn/T/AppTranslocation/1D71EB54-F5F2-4C95-975F-9958290B1607/d/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by RMacfarlane** [comment]
This extension doesn't yet support multi-root folders, please see https://github.com/Microsoft/vscode-pull-request-github/issues/386
