### ISSUE TITLE
Allow opening files with large diffs

### ISSUE THREAD

**Issue by bsShoham** [microsoft/vscode-pull-request-github#4580]
Hi! 

Currently, the behavior is, that on a very large diff, you can only open the file on GitHub (see image).
This is kind of frustrating, because the reason for me to get the extension was exactly large diffs that the GitHub website cannot handle and gets laggy, stuck or crashes in

I would wish I could open and review the files directly in vs-code through the extension, because he handles them better and smoother.

![image](https://user-images.githubusercontent.com/91195275/221898326-c26a0ca4-44e4-44ea-b35c-b7fb9e42a15f.png)

**Comment by atkeranov** [comment]
Any updates here? This defeats the whole purpose of the extension, as often times the files with the most changes are the essence of the PR.

**Comment by alexr00** [comment]
Should be fixed with https://github.com/microsoft/vscode-pull-request-github/issues/5827!
