### ISSUE TITLE
Closed PR not sync'ing to GitHub PR Extension

### ISSUE THREAD

**Issue by UCSBMike** [microsoft/vscode-pull-request-github#4593]
Type: <b>Bug</b>

Steps to reproduce —

- Create PR
- Review > Approve > Close on GitHub.com
- Open VS Code > Source Control extension
- Observe missing icon for Create New PR on branch
- Switch branches
- Observe that icon is back for Create New PR
- Deduce the closed PR on other branch is not sync'ing and not allowing new PR

VS Code Version: 1.75.1
GitHub Pull Request and Issues Version: V0.58.2

![image](https://user-images.githubusercontent.com/6609056/223456434-23720a74-17cf-4120-bc2f-745b331b168e.png)

Extension version: 0.58.2
VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.17763
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Platinum 8168 CPU @ 2.70GHz (4 x 2694)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|16.00GB (2.92GB free)|
|Process Argv|--crash-reporter-id cb293b82-1640-4624-8ed8-7b217054bcf0|
|Screen Reader|no|
|VM|100%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
2i9eh265:30646982

```

</details>

**Comment by alexr00** [comment]
We don't take into account whether the current PR is closed when we show the "Create" icon. If you don't care about having review mode for merged PRs you can set the following setting:
```
"githubPullRequests.useReviewMode": {
  "merged": false
}
```

**Comment by UCSBMike** [comment]
OK, thank you.
Under what scenario would the 'Create' icon return for that branch? Does this have anything to do with the `Main` branch and `Develop` branch being at the same commit? I guess I could create a new feature branch with a commit or two and switch back to `Develop` and see if the 'Create' icon returns.

**Comment by alexr00** [comment]
The "create" button will show if you're not on the default branch (regardless of commit) and if the current branch has no PR associated with it.
