### ISSUE TITLE
`Delete branch` button shown even though the branch was automatically deleted

### ISSUE THREAD

**Issue by brettcannon** [microsoft/vscode-pull-request-github#4594]
- Extension version:
- VSCode Version:
- OS: Linux (via Codespaces on vscode.dev)

The extension is showing me the button to delete a branch after the PR is merged (even after manually refreshing multiple times):
![image](https://user-images.githubusercontent.com/54418/223585953-a9c10423-18ba-4332-b401-d8a655f801f2.png)

But GitHub already automatically deleted the branch for me for the [PR](https://github.com/brettcannon/microvenv/pull/20):
![image](https://user-images.githubusercontent.com/54418/223585987-bc2d9f5e-2b09-4f5c-98a5-018b7917f543.png)

Maybe GitHub is sending data that is mixing "branch" with "codespace" for the button?

**Comment by alexr00** [comment]
@brettcannon we should only show the "Delete branch..." button when either the local or the remote branch still exists. Did you try clicking the button?

**Comment by brettcannon** [comment]
No, but if it also shows for the local branch then that was probably was it was for. Would like me to close this as me misunderstanding or change it to be a feature request to label which branch the button is referring to?

**Comment by brettcannon** [comment]
I just tried the button and noticed it offered to delete the remote branch (which was already deleted by virtue of the PR being merged), delete the local branch, and stop the Codespace. The last option was a pleasant surprise! I was a bit worried about triggering an error due to the remote branch already being deleted, but it was fine in the end.

Maybe the button could be named "Cleanup..." to signify how it does more than just delete branches when you're in a Codespace?

**Comment by alexr00** [comment]
I'd prefer to leave it as "Delete branch..." since that's what it will mean for most users and because we offer to delete both local and remote. Since we show a quick pick when the button is used you can quickly see what's going to happen the first time you try it too.
