### ISSUE TITLE
`org` in issue query causes crash

### ISSUE THREAD

**Issue by rohime** [microsoft/vscode-pull-request-github#4595]
- Extension version: 0.60
- VSCode Version: 1.76.0
- OS: Linux x86_64

```
Version: 1.76.0
Commit: 92da9481c0904c6adfe372c12da3b7748d74bdcb
Date: 2023-03-01T10:25:16.105Z
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.76.0 Chrome/102.0.5005.196 Electron/19.1.11 Safari/537.36
```

Steps to Reproduce:

1. Set `githubIssues.queries` as shown below in `settings.json` (repro seems more consistent with more queries but it's also possible with a single one)

    ```json
    "githubIssues.queries": [
        {
            "label": "All issues of microsoft/vscode 1",
            "query": "org:microsoft state:open repo:microsoft/vscode"
        },
        {
            "label": "All issues of microsoft/vscode 2",
            "query": "org:microsoft state:open repo:microsoft/vscode"
        },
        {
            "label": "All issues of microsoft/vscode 3",
            "query": "org:microsoft state:open repo:microsoft/vscode"
        },
        {
            "label": "All issues of microsoft/vscode 4",
            "query": "org:microsoft state:open repo:microsoft/vscode"
        },
    ]
    ```
2. Wait for the next issue refresh (on settings.json save event, manually triggered by clicking the refresh button or when restarting VSCode)
3. VSCode crashes with _The window terminated unexpectedly (reason: 'crashed', code '133')_

Logfile created with `code <workspace> --profile <repro_profile> --log trace --verbose &> trace.log`: [trace.log](https://github.com/microsoft/vscode-pull-request-github/files/10915221/trace.log)

I used a empty VSCode profile with only `GitHub.vscode-pull-request-github` installed and `githubIssues.queries` set as mentioned above.

Extension version 0.56 is the last version that does not crash.

**Comment by alexr00** [comment]
It looks like the issue isn't `org`, but rather that if you set an `org` then `repo` isn't used. So with the above queries, you end up trying to retrieve all issues in all `microsoft` repos _times 4_. This is a lot of issues, and it's this that is causing the crash, not the use of `org`. 

We shouldn't crash if there are so many issues, but instead warn that we can't fetch them all.

**Comment by alexr00** [comment]
> So with the above queries, you end up trying to retrieve all issues in all microsoft repos times 4. This is a lot of issues, and it's this that is causing the crash, not the use of org.

This ended up being incorrect. The slowness and crash are actually caused by the number of internal objects and listeners we create.

**Comment by roblourens** [comment]
With the stable extension, I see the window stop responding. With the pre-release, this doesn't happen and it is able to load and show results. It stopped loading at some point and I got an error about the extension making too many requests, but that's probably expected? 

<img width="285" alt="image" src="https://user-images.githubusercontent.com/323878/235032965-5a106820-2f3b-4d0b-9edc-bfefec0a97e2.png">

**Comment by alexr00** [comment]
Yes, the notification about too many requests is expected.
