### ISSUE TITLE
Add "Reviewed by me" as a top-level filter in viewlet

### ISSUE THREAD

**Issue by msorens** [microsoft/vscode-pull-request-github#460]
The list of top-level filters (waiting for my review, assigned to me, etc.) is nice,
but would like to add one more: "reviewed by me". As it stands, once I complete a review with "approved" or "request changes" it no longer appears in "waiting for my review". That makes sense, but it makes it inconvenient to return to that PR--particularly if I did a "request changes". So until the PR is closed, it should show up in a new filter "reviewed by me".

**Comment by thomas0306** [comment]
Hi, may I help on this issue?

**Comment by RMacfarlane** [comment]
Thanks @thomas0306! The code for that sets the query is here:
https://github.com/Microsoft/vscode-pull-request-github/blob/778be8188cbfb8e65300d7571b60eeaca700509c/src/github/githubRepository.ts#L201-L218

**Comment by thomas0306** [comment]
Done! Please let me know for any improvements required.

**Comment by RMacfarlane** [comment]
Thanks @thomas0306 so much for submitting a PR, I’m sorry we ended up closing it! There’s now a setting that allows configuring the categories available in the tree, more info here: https://github.com/microsoft/vscode-pull-request-github#configuring-the-extension

As an example, you could change it to something like
```
"githubPullRequests.queries": [
	{
		"label": "Waiting For My Review",
		"query": "is:open review-requested:${user}"
	},
	{
		"label": "Assigned To Me",
		"query": "is:open assignee:${user}"
	},
	{
		"label": "Created By Me",
		"query": "is:open author:${user}"
	},
	{
		"label": "Reviewed by me”,
		"query": "is:open reviewed-by:${user}"
	}
]
```

**Comment by msorens** [comment]
Wow! This is great @RMacfarlane ! That (a) goes well above and beyond my original request, and (b) works great!

For other readers, I would just reiterate what the VSCode settings themselves say: if you want to add to the defaults, you have to explicitly include them. @RMacfarlane has done that in the example above. The first three are the defaults; the fourth one is the custom one requested by this issue.
