### ISSUE TITLE
Pull Review Comments need updating while refactorting. 

### ISSUE THREAD

**Issue by ldelossa** [microsoft/vscode-pull-request-github#4608]
Hello,

When refactoring code to address PR comments, the comments are not intelligently moved and adjusted for the line changes. 

In Neovim, there is a concept of "ext marks", which are marks in a buffer which retain their original position as their line number may change. For instance, if you place a mark on line 2 and add two lines above it, the mark is moved to line 4. 

This is used in https://github.com/ldelossa/gh.nvim to ensure that comments "make sense" as you refactor code to address it. 

Does a concept like this exist in VSCode, and if it does would it be possible to apply it to the comment's widgets.

**Comment by ldelossa** [comment]
Hey there, I wanted to refine what actually occurs here. 

When the gutter is painted with the comments on a file in a PR and lines are added, the gutter icon does infact move forward. This is good, like it would with ext marks. 

However, the state in the gutter icon does not update, resulting in the comment bubble show in the wrong place in the editor. 

Here is a quick demo:


https://github.com/microsoft/vscode-pull-request-github/assets/5642902/78f1b3fd-e725-4701-bbcf-3703a54a78de

**Comment by amunger** [comment]
the comment moves down when open, but if newlines were added while the comment is closed, it will open again in the old position 
<img width="527" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/2019016/19d0fbda-be61-4c27-b938-426d15df15b1">

**Comment by alexr00** [comment]
Looks like I only fixed half the problem.
