### ISSUE TITLE
Repo cloned from Git bundle shows error parsing remote

### ISSUE THREAD

**Issue by sentience** [Microsoft/vscode-pull-request-github#461]
Issue Type: <b>Bug</b>

After cloning a repository from a Git Bundle file (https://git-scm.com/book/en/v2/Git-Tools-Bundling), you get a remote like this:

$ git remote -v
origin	/Users/kyank/Downloads/front-end-coding-test.bundle (fetch)
origin	/Users/kyank/Downloads/front-end-coding-test.bundle (push)

When you open this repo in VS Code, the GitHub Pull Requests bundle displays an error saying it was unable to parse the remote.

Extension version: 0.1.4
VS Code version: Code - Insiders 1.28.0-insider (96854113091424c07b28ba84b82b75a88b8455cb, 2018-09-10T05:12:30.432Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.27GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by RMacfarlane** [comment]
Fixed by https://github.com/Microsoft/vscode-pull-request-github/commit/869387e62d4c47e31eae65d91a0335aa2b8a6006, will release a new version of the extension soon
