### ISSUE TITLE
`@type` within code block rendering as link to GitHub user

### ISSUE THREAD

**Issue by asportnoy** [microsoft/vscode-pull-request-github#4611]
- Extension version: `v0.61.2023030709`
- VSCode Version: `1.76.1` (microsoft/vscode@5e805b79fcb6ba4c2d23712967df89a089da575b)
- OS: macOS Ventura 13.2.1 (22D68)

![Screenshot 2023-03-10 at 09 45 58](https://user-images.githubusercontent.com/14863373/224362364-b463a08c-a5a5-400f-954e-93e8798aff53.png)

Seems like the extension is treating the `@type` within the suggestion as a GitHub mention. The comment looks fine on github.com, the extension is just trying to render it as a mention within the code block.

Steps to Reproduce:

- Write a review comment with a code block or suggestion containing  `@type` (or `@anything`)

**Comment by sliechti** [comment]
Interesting issue. Checkout the list of contributors to the last release.
https://github.com/microsoft/vscode-pull-request-github/releases/tag/v0.62.0

**Comment by alexr00** [comment]
@sliechti thanks for the heads up. I added backticks to the `@type` in release to fix it.
