### ISSUE TITLE
Sign in error in GitHub entreprise

### ISSUE THREAD

**Issue by GrandStrateguerre** [microsoft/vscode-pull-request-github#4612]
Hello,

- Extension version:
![image](https://user-images.githubusercontent.com/86523070/224492609-845e0ff9-c83d-4f22-8281-c911cc3c364b.png)

- VSCode Version, OS:
Version: 1.76.1 (user setup)
Commit: 5e805b79fcb6ba4c2d23712967df89a089da575b
Date: 2023-03-08T16:32:00.131Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

Steps to Reproduce:

1. click on :
![image](https://user-images.githubusercontent.com/86523070/224492678-df1730c9-6d58-4394-a5d1-a5651e4ea97d.png)

2. 
![image](https://user-images.githubusercontent.com/86523070/224492744-d69bc8b0-2b31-4817-a84f-9309ffae69c7.png)

3.
![image](https://user-images.githubusercontent.com/86523070/224492774-0ff5c37d-0c97-4c0a-bdc9-99037d292721.png)
4.
![image](https://user-images.githubusercontent.com/86523070/224492791-bfaac10c-3f85-4bd4-bd64-d3075dcaaf35.png)
5.
![image](https://user-images.githubusercontent.com/86523070/224492826-e68897a7-9d17-41d4-97de-24c470a14cca.png)
6. fill with the PAT
![image](https://user-images.githubusercontent.com/86523070/224492883-38e3dc25-4abf-4f63-8155-f14af5748af4.png)
7.
![image](https://user-images.githubusercontent.com/86523070/224492945-1bbb7868-9895-4310-aa95-25ae34e32a89.png)

Best regards

**Comment by alexr00** [comment]
@GrandStrateguerre thank you for providing screen shots! Can you reproduce the issue again and share the output from "GitHub Pull Request" and from "GitHub Enterprise Authentications"?

**Comment by GrandStrateguerre** [comment]
Hello,

here is :
![image](https://user-images.githubusercontent.com/86523070/225905777-55b0eee2-d43c-47b8-83ea-290aa10594a1.png)

![image](https://user-images.githubusercontent.com/86523070/225906057-60eed80a-7c5c-47ca-bc37-75f85584b413.png)

![image](https://user-images.githubusercontent.com/86523070/225906365-800bdf35-7cf6-45e0-ae5f-63e6fab31692.png)

Best regards

**Comment by TylerLeonhardt** [comment]
@GrandStrateguerre can you tell me what version of GitHub Enterprise your company uses? You can get the version by going to: `https://YOUR_GITHUB_ENTERPRISE_URL/api/v3/meta`

**Comment by GrandStrateguerre** [comment]
@TylerLeonhardt  
![image](https://user-images.githubusercontent.com/86523070/226571893-571538bf-3c5a-40ed-81bf-5f81bf84ca2d.png)

**Comment by TylerLeonhardt** [comment]
It seems like we are having a hard time talking to your GHES instance. Do you have some sort of Corporate Proxy? 

Additionally, are these logs from after you put in your PAT? I would have expected a line that says "Trying to retrieve PAT..." but I don't see it in your most recent comment.

**Comment by GrandStrateguerre** [comment]
Hello @TylerLeonhardt ,

Yes we have a corporate proxy.

And the error comes before entering the PAT.

Here is the sequence I did  :

![image](https://user-images.githubusercontent.com/86523070/227535623-d558ebc2-f4c8-488f-a8ed-ec7433d0ca11.png)

![image](https://user-images.githubusercontent.com/86523070/227535760-02f5bb60-4c8b-497e-85af-95240709acf5.png)

![image](https://user-images.githubusercontent.com/86523070/227536005-e3d76efb-b5a0-4d0b-9d02-4510abc2449a.png)

![image](https://user-images.githubusercontent.com/86523070/227536038-1a4e144b-dac0-4811-ba75-1da2b93146d4.png)

Best regards

**Comment by GrandStrateguerre** [comment]
@TylerLeonhardt :
after : 
![image](https://user-images.githubusercontent.com/86523070/228535394-3e0f944a-5021-4d34-90fd-1a624309b0d0.png)

![image](https://user-images.githubusercontent.com/86523070/228535957-d8a668b3-90c3-4b2d-89c0-117879f2ce32.png)

![image](https://user-images.githubusercontent.com/86523070/228536206-af368578-8fea-4ec7-aa3a-fd795a0bd7ba.png)

after entenred the PAT :

![image](https://user-images.githubusercontent.com/86523070/228536743-a6e19c62-dc01-4066-badd-c5c8e0c58a54.png)

**Comment by TylerLeonhardt** [comment]
Interesting. @GrandStrateguerre do you have the `http.proxy` setting defined? Or maybe if you open a PowerShell instance in VS Code, can you run `$env:HTTP_PROXY` and tell me if you have any value there?

 My suspicion is that this is a proxy related issue... any details on your proxy would be helpful.

**Comment by TylerLeonhardt** [comment]
Additionally, some other proxy related ideas: https://github.com/microsoft/vscode/issues/160649#issuecomment-1489176027

**Comment by GrandStrateguerre** [comment]
Hello @TylerLeonhardt ,

I set it this option from override to off :
![image](https://user-images.githubusercontent.com/86523070/234522241-b0d14892-81a7-485d-9bad-e2e2951a2c49.png)

And after it had worked.

Code version : 1.77.3

Thanks for your help :)

Best regards
