### ISSUE TITLE
Pull request where head is deleted not listing

### ISSUE THREAD

**Issue by justint** [microsoft/vscode-pull-request-github#4613]
Type: <b>Bug</b>

1. Clone `justint/papaya` (https://github.com/justint/papaya) repository to local computer.
2. Open the cloned repository in VSCode.
3. Click the "GitHub" sidebar icon; note that no pull requests display in the list, even though there is a currently open pull request in that repository (`#8: Add dark mode, anchor links, utterances support`). Refreshing the list does not fix it.

_Side note_: that PR was once closed and had been re-opened by me a while ago, perhaps that has something to do with it not showing up?

---

Extension version: 0.60.0
VS Code version: Code 1.76.1 (Universal) (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:32:09.831Z)
OS version: Darwin arm64 21.6.0
Modes:
Sandboxed: No

**Comment by alexr00** [comment]
The key to why this happens is this:

![image](https://user-images.githubusercontent.com/38270282/224688383-89799157-9fc2-4e41-8471-84f2a19139eb.png)

We don't show PRs in the tree if the head was deleted. When the head is deleted we don't let you check on the PR in the extension, leaving you with minimal benefit from having it in the list.

**Comment by alexr00** [comment]
It does seem that this is confusing though. Leaving open to address in the future.

**Comment by kohanyirobert** [comment]
In the comment section of #4800 you've written @alexr00 that
> When the head branch of the PR is deleted GitHub is missing some of the properties of the PR that we currently require in the extension. Because of this, we filter out PRs where the head was deleted

Above you wrote
> When the head is deleted we don't let you check on the PR in the extension

Indeed it is confusing, could you elaborate what is missing that would be otherwise required by the extension. For future reference for other if for anything else?

For my use-case it'd be enough to see the PR's title/provide a link even if the head is deleted, I wouldn't need any other details.

**Comment by seanroelofs** [comment]
➕ Would love to have the ability to filter for closed PRs and see them locally

**Comment by alexr00** [comment]
These show now! You just can't check them out.
