### ISSUE TITLE
Unable to authentify : ETIMEDOUT

### ISSUE THREAD

**Issue by philippart-s** [microsoft/vscode-pull-request-github#462]
- Extension version: 0.1.4
- VSCode Version: 1.27.1
- OS: Win 7

Steps to Reproduce:

1. Install extension
2. Restart VSCode
3. Open project
4. Clique on "Sign in to github.com"

Error message in console : 
```
Error signing in to github.com: Error: connect ETIMEDOUT 52.202.245.247:443
Error: connect ETIMEDOUT 52.202.245.247:443
	at Object._errnoException (util.js:1024:11)
	at _exceptionWithHostPort (util.js:1046:20)
	at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
```

My proxy is configured in VSCode and works (I can install extensions) and pull / push from / to github.com works fine in the VSCode terminal.

**Comment by philippart-s** [comment]
Note : when I don't use a proxy (with my personal connection for instance) it's working.
The problème, I think is to know which proxy configuration the extension use ?

**Comment by edward-agarwala** [comment]
I am behind a proxy and getting the same error. I tried setting the `http.proxy` variable in settings.json and turning `ssl-strict` to false for both git and the http. The problem was the same.

**Comment by shana** [comment]
Maybe the proxy is not handling websocket connections correctly? Is this a company proxy?

**Comment by edward-agarwala** [comment]
It is a company proxy.

**Comment by edward-agarwala** [comment]
When I try to sign in, I am now
1. sent github.com to authorize (I click continue)
1. I get a message in VSCode, "Allow an extension to open this URL?" I accept.
1. The OUTPUT of Github Pull Requests is
  ```
  Looking for git repository
  Git repository found, initializing review manager and pr tree view.
  No GitHub remotes found
  Found GitHub remote
  ```

However none of my pull requests show up in the `github pull requests` section of the source control panel.

**Comment by alexr00** [comment]
The auth stack has completely changed since this issue was filed.
