### ISSUE TITLE
PR Page UI Inconcistency

### ISSUE THREAD

**Issue by samrland** [microsoft/vscode-pull-request-github#4623]
(really not sure how to name this)

When you open the page for a pull request, where it asks you how to merge the pull request you have a dropdown list:

![dropdown](https://user-images.githubusercontent.com/79730498/224886208-5f3fd950-6e72-4ba5-a4db-e782e7af8370.png)

The font family doesn't look right, and the dropdown itself doesn't seem to follow anything else in the UI.

- Extension version: 0.60.0
- VSCode Version: 1.76.1
- OS: Windows 11

Steps to Reproduce:

1. Open the page for a pull request that has no merge conflicts and is ready to merge
2. The dropdown where you can select method of merging is in a different font.

**Comment by alexr00** [comment]
Closing as as-designed since this is just the native dropdown.
