### ISSUE TITLE
Notification Badge for 'waiting for my review' PRs

### ISSUE THREAD

**Issue by noalbalint** [microsoft/vscode-pull-request-github#4628]
I think many teams struggle with timely PR reviews. It might be helpful to show a notification badge with the number of PRs that are waiting for your review, to help us remember to open this tab and take a look at them. 

Other items in the Primary Side Bar also have notification badges, for example `Extensions`. I would propose to add something just like that to GitHub.

<img width="64" alt="REPORT github vscode needs notification when you have PRs awaiting your review" src="https://user-images.githubusercontent.com/45208632/225134191-2382b98e-1da0-4d2d-a659-93073a680615.png">

Thanks :)

**Comment by alexr00** [comment]
We have the setting `"githubPullRequests.notifications": "pullRequests"`, which adds a counter badge to your activity bar as you suggested. It only counts PRs that result in a GitHub notification though, so you need to make sure your GitHub notifications are configured in such a way that you get notified when someone requests your reivew.
