### ISSUE TITLE
`git status` being called on every modification

### ISSUE THREAD

**Issue by d10c** [microsoft/vscode-pull-request-github#4631]
Type: <b>Performance Issue</b>

I've extension-bisected this issue, and narrowed it down to this extension.

In an open file view in VSCode, for a file tracked by git, whenever I change one character in the file, even without saving, the Git output pane shows several git operations, typically including `git status` and `git diff`. Occasionally they take a long time (500ms up to 5s), and they apparently run with a higher priority than even some cursor movement commands, which leads to atrocious performance and typos when doing basic text editing.

Extension version: 0.61.2023030709
VS Code version: Code 1.76.1 (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:48:08.231Z)
OS version: Darwin arm64 22.3.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|114, 77, 62|
|Memory (System)|64.00GB (16.00GB free)|
|Process Argv|--crash-reporter-id 6f8a7096-51b4-4f6a-b128-20c9c10e119b|
|Screen Reader|yes|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   22	   393	 70739	code main
   11	   197	 70745	   gpu-process
    0	    66	 70748	   utility-network-service
   88	  1376	 70750	   window (DataFlowPrivate.qll — d10c-codeql (Workspace))
   24	   393	 70857	   utility-process
    0	    66	 70860	     ptyHost
    0	     0	 68056	       /bin/zsh -il
    0	     0	 68949	       /bin/zsh -il
    0	     0	 70298	       /bin/zsh -il
    0	     0	 71625	       /bin/zsh -il
    0	     0	 72538	       /bin/zsh -il
    0	     0	 72829	       /bin/zsh -il
    0	     0	 73271	       /bin/zsh -il
    0	     0	 73286	       /bin/zsh -il
    0	     0	 74512	       /bin/zsh -il
    0	     0	 75984	       /bin/zsh -il
    1	     0	 77460	       /bin/zsh -il
    0	     0	 77825	         (zsh)
    0	     0	 85115	       /bin/zsh -il
    0	     0	 77820	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    66	 76813	   issue-reporter
   57	   393	 76816	   utility-process
    0	    66	 76871	     electron-nodejs (/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/d10c/.vscode/extensions/formulahendry.auto-rename-tag-0.1.10/packages/server/dist/serverMain.js --node-ipc --clientProcessId=76816)
    0	     0	 77287	     /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/sourcekit-lsp
  134	   197	 77455	     /Users/d10c/Library/Application Support/Code/User/globalStorage/github.vscode-codeql/distribution5/codeql/tools/osx64/java-aarch64/bin/java --add-modules jdk.unsupported -cp /Users/d10c/Library/Application Support/Code/User/globalStorage/github.vscode-codeql/distribution5/codeql/tools/codeql.jar com.semmle.cli2.CodeQL execute cli-server -v --log-to-stderr
    1	    66	 77507	     electron-nodejs (structured-evaluator-log.js )
  154	   131	 77535	     /Users/d10c/Library/Application Support/Code/User/globalStorage/github.vscode-codeql/distribution5/codeql/tools/osx64/java-aarch64/bin/java --add-modules jdk.unsupported -cp /Users/d10c/Library/Application Support/Code/User/globalStorage/github.vscode-codeql/distribution5/codeql/tools/codeql.jar com.semmle.cli2.CodeQL execute language-server --check-errors ON_CHANGE -v --log-to-stderr
    0	     0	 77817	     (git)
    0	     0	 77818	     <defunct>
    0	     0	 77819	     /opt/homebrew/bin/git show --textconv :swift/ql/lib/codeql/swift/dataflow/internal/DataFlowPrivate.qll
    0	     0	 77821	     <defunct>
    0	   131	 76817	   window (undefined)
    0	    66	 76818	   utility-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (DataFlowPrivate.qll — d10c-codeql (Workspace))
|    Folder (codeql-zip-archive://0-142/Users/d10c/Library/Application%20Support/Code/User/workspaceStorage/f964bda493beded1dbc610825dc41108/GitHub.vscode-codeql/cpp/codeql_db/src.zip): Workspace stats not available.
|    Folder (codeql-zip-archive://0-142/Users/d10c/Library/Application%20Support/Code/User/workspaceStorage/e6b2f990b5753d74a3e120ea74e6928e/GitHub.vscode-codeql/cpp/codeql_db/src.zip): Workspace stats not available.
|    Folder (codeql-zip-archive://0-144/Users/d10c/Library/Application%20Support/Code/User/workspaceStorage/e6b2f990b5753d74a3e120ea74e6928e/GitHub.vscode-codeql/cpp-1/codeql_db/src.zip): Workspace stats not available.
|    Folder (codeql-zip-archive://0-144/Users/d10c/Library/Application%20Support/Code/User/workspaceStorage/e6b2f990b5753d74a3e120ea74e6928e/GitHub.vscode-codeql/cpp-2/codeql_db/src.zip): Workspace stats not available.
|    Folder (codeql-zip-archive://0-144/Users/d10c/Library/Application%20Support/Code/User/workspaceStorage/e6b2f990b5753d74a3e120ea74e6928e/GitHub.vscode-codeql/cpp-3/codeql_db/src.zip): Workspace stats not available.
|    Folder (codeql-zip-archive://0-144/Users/d10c/Library/Application%20Support/Code/User/workspaceStorage/e6b2f990b5753d74a3e120ea74e6928e/GitHub.vscode-codeql/cpp-4/codeql_db/src.zip): Workspace stats not available.
|    Folder (codeql-zip-archive://0-138/Users/d10c/Library/Application%20Support/Code/User/workspaceStorage/e6b2f990b5753d74a3e120ea74e6928e/GitHub.vscode-codeql/cpp-5/cpp/src.zip): Workspace stats not available.
|    Folder (codeql-zip-archive://0-138/Users/d10c/Library/Application%20Support/Code/User/workspaceStorage/e6b2f990b5753d74a3e120ea74e6928e/GitHub.vscode-codeql/cpp-6/cpp/src.zip): Workspace stats not available.
|    Folder (codeql-zip-archive://0-47/Users/d10c/src/git-scm/CODEQL_DATABASE/src.zip): Workspace stats not available.
|    Folder (codeql-zip-archive://0-144/Users/d10c/Library/Application%20Support/Code/User/workspaceStorage/e6b2f990b5753d74a3e120ea74e6928e/GitHub.vscode-codeql/cpp-7/codeql_db/src.zip): Workspace stats not available.
|    Folder (codeql-zip-archive://0-144/Users/d10c/Library/Application%20Support/Code/User/workspaceStorage/e6b2f990b5753d74a3e120ea74e6928e/GitHub.vscode-codeql/cpp-8/codeql_db/src.zip): Workspace stats not available.
|    Folder (codeql-zip-archive://0-142/Users/d10c/Library/Application%20Support/Code/User/workspaceStorage/86375e90bc9aabd998bffc759fec09fb/GitHub.vscode-codeql/cpp/codeql_db/src.zip): Workspace stats not available.
|    Folder (codeql-zip-archive://0-63/Users/d10c/Downloads/db-calleluks_Tofu%40c465feb-b6a4a92/src.zip): Workspace stats not available.
|    Folder (codeql-zip-archive://0-31/Users/d10c/src/Tofu/db/src.zip): Workspace stats not available.
|    Folder (d10c-codeql): more than 21270 files
|      File types: pack(3124) rel(1330) checksum(1330) ql(649) qll(535) d(487)
|                  qhelp(339) cpp(264) md(175) br(138)
|      Conf files: github-actions(33) cmake(4) devcontainer.json(2) csproj(2)
|                  dockerfile(1) settings.json(1) tasks.json(1);
```

</details>
<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewvextcfv2:30681851
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1:30587005
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30672706
vsccsb:30677849
vscodedisable:30660115
pythonb192cf:30669361
funwalk2cf:30682975
pythonms35:30686772

```

</details>

**Comment by alexr00** [comment]
I'm not able to reproduce this. Do you have any other steps?

Worth noting: The built in git extension will run a `status` every time the file changes even when GitHub Pull Requests and Issues isn't installed.

**Comment by aUsABuisnessman** [comment]
> 
> Type: <b>Performance Issue</b>
> 
> I've extension-bisected this issue, and narrowed it down to this extension.
> 
> In an open file view in VSCode, for a file tracked by git, whenever I change one character in the file, even without saving, the Git output pane shows several git operations, typically including `git status` and `git diff`. Occasionally they take a long time (500ms up to 5s), and they apparently run with a higher priority than even some cursor movement commands, which leads to atrocious performance and typos when doing basic text editing.
> 
> Extension version: 0.61.2023030709
> VS Code version: Code 1.76.1 (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:48:08.231Z)
> OS version: Darwin arm64 22.3.0
> Modes:
> Sandboxed: Yes
> 
> <details>
> <summary>System Info</summary>
> 
> |Item|Value|
> |---|---|
> |CPUs|Apple M1 Max (10 x 24)|
> |GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
> |Load (avg)|114, 77, 62|
> |Memory (System)|64.00GB (16.00GB free)|
> |Process Argv|--crash-reporter-id 6f8a7096-51b4-4f6a-b128-20c9c10e119b|
> |Screen Reader|yes|
> |VM|0%|
> </details><details>
> <summary>Process Info</summary>
> 
> ```
> CPU %	Mem MB	   PID	Process
>    22	   393	 70739	code main
>    11	   197	 70745	   gpu-process
>     0	    66	 70748	   utility-network-service
>    88	  1376	 70750	   window (DataFlowPrivate.qll — d10c-codeql (Workspace))
>    24	   393	 70857	   utility-process
>     0	    66	 70860	     ptyHost
>     0	     0	 68056	       /bin/zsh -il
>     0	     0	 68949	       /bin/zsh -il
>     0	     0	 70298	       /bin/zsh -il
>     0	     0	 71625	       /bin/zsh -il
>     0	     0	 72538	       /bin/zsh -il
>     0	     0	 72829	       /bin/zsh -il
>     0	     0	 73271	       /bin/zsh -il
>     0	     0	 73286	       /bin/zsh -il
>     0	     0	 74512	       /bin/zsh -il
>     0	     0	 75984	       /bin/zsh -il
>     1	     0	 77460	       /bin/zsh -il
>     0	     0	 77825	         (zsh)
>     0	     0	 85115	       /bin/zsh -il
>     0	     0	 77820	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
>     0	    66	 76813	   issue-reporter
>    57	   393	 76816	   utility-process
>     0	    66	 76871	     electron-nodejs (/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/d10c/.vscode/extensions/formulahendry.auto-rename-tag-0.1.10/packages/server/dist/serverMain.js --node-ipc --clientProcessId=76816)
>     0	     0	 77287	     /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/sourcekit-lsp
>   134	   197	 77455	     /Users/d10c/Library/Application Support/Code/User/globalStorage/github.vscode-codeql/distribution5/codeql/tools/osx64/java-aarch64/bin/java --add-modules jdk.unsupported -cp /Users/d10c/Library/Application Support/Code/User/globalStorage/github.vscode-codeql/distribution5/codeql/tools/codeql.jar com.semmle.cli2.CodeQL execute cli-server -v --log-to-stderr
>     1	    66	 77507	     electron-nodejs (structured-evaluator-log.js )
>   154	   131	 77535	     /Users/d10c/Library/Application Support/Code/User/globalStorage/github.vscode-codeql/distribution5/codeql/tools/osx64/java-aarch64/bin/java --add-modules jdk.unsupported -cp /Users/d10c/Library/Application Support/Code/User/globalStorage/github.vscode-codeql/distribution5/codeql/tools/codeql.jar com.semmle.cli2.CodeQL execute language-server --check-errors ON_CHANGE -v --log-to-stderr
>     0	     0	 77817	     (git)
>     0	     0	 77818	     <defunct>
>     0	     0	 77819	     /opt/homebrew/bin/git show --textconv :swift/ql/lib/codeql/swift/dataflow/internal/DataFlowPrivate.qll
>     0	     0	 77821	     <defunct>
>     0	   131	 76817	   window (undefined)
>     0	    66	 76818	   utility-process
> ```
> 
> </details>
> <details>
> <summary>Workspace Info</summary>
> 
> ```
> |  Window (DataFlowPrivate.qll — d10c-codeql (Workspace))
> |    Folder (codeql-zip-archive://0-142/Users/d10c/Library/Application%20Support/Code/User/workspaceStorage/f964bda493beded1dbc610825dc41108/GitHub.vscode-codeql/cpp/codeql_db/src.zip): Workspace stats not available.
> |    Folder (codeql-zip-archive://0-142/Users/d10c/Library/Application%20Support/Code/User/workspaceStorage/e6b2f990b5753d74a3e120ea74e6928e/GitHub.vscode-codeql/cpp/codeql_db/src.zip): Workspace stats not available.
> |    Folder (codeql-zip-archive://0-144/Users/d10c/Library/Application%20Support/Code/User/workspaceStorage/e6b2f990b5753d74a3e120ea74e6928e/GitHub.vscode-codeql/cpp-1/codeql_db/src.zip): Workspace stats not available.
> |    Folder (codeql-zip-archive://0-144/Users/d10c/Library/Application%20Support/Code/User/workspaceStorage/e6b2f990b5753d74a3e120ea74e6928e/GitHub.vscode-codeql/cpp-2/codeql_db/src.zip): Workspace stats not available.
> |    Folder (codeql-zip-archive://0-144/Users/d10c/Library/Application%20Support/Code/User/workspaceStorage/e6b2f990b5753d74a3e120ea74e6928e/GitHub.vscode-codeql/cpp-3/codeql_db/src.zip): Workspace stats not available.
> |    Folder (codeql-zip-archive://0-144/Users/d10c/Library/Application%20Support/Code/User/workspaceStorage/e6b2f990b5753d74a3e120ea74e6928e/GitHub.vscode-codeql/cpp-4/codeql_db/src.zip): Workspace stats not available.
> |    Folder (codeql-zip-archive://0-138/Users/d10c/Library/Application%20Support/Code/User/workspaceStorage/e6b2f990b5753d74a3e120ea74e6928e/GitHub.vscode-codeql/cpp-5/cpp/src.zip): Workspace stats not available.
> |    Folder (codeql-zip-archive://0-138/Users/d10c/Library/Application%20Support/Code/User/workspaceStorage/e6b2f990b5753d74a3e120ea74e6928e/GitHub.vscode-codeql/cpp-6/cpp/src.zip): Workspace stats not available.
> |    Folder (codeql-zip-archive://0-47/Users/d10c/src/git-scm/CODEQL_DATABASE/src.zip): Workspace stats not available.
> |    Folder (codeql-zip-archive://0-144/Users/d10c/Library/Application%20Support/Code/User/workspaceStorage/e6b2f990b5753d74a3e120ea74e6928e/GitHub.vscode-codeql/cpp-7/codeql_db/src.zip): Workspace stats not available.
> |    Folder (codeql-zip-archive://0-144/Users/d10c/Library/Application%20Support/Code/User/workspaceStorage/e6b2f990b5753d74a3e120ea74e6928e/GitHub.vscode-codeql/cpp-8/codeql_db/src.zip): Workspace stats not available.
> |    Folder (codeql-zip-archive://0-142/Users/d10c/Library/Application%20Support/Code/User/workspaceStorage/86375e90bc9aabd998bffc759fec09fb/GitHub.vscode-codeql/cpp/codeql_db/src.zip): Workspace stats not available.
> |    Folder (codeql-zip-archive://0-63/Users/d10c/Downloads/db-calleluks_Tofu%40c465feb-b6a4a92/src.zip): Workspace stats not available.
> |    Folder (codeql-zip-archive://0-31/Users/d10c/src/Tofu/db/src.zip): Workspace stats not available.
> |    Folder (d10c-codeql): more than 21270 files
> |      File types: pack(3124) rel(1330) checksum(1330) ql(649) qll(535) d(487)
> |                  qhelp(339) cpp(264) md(175) br(138)
> |      Conf files: github-actions(33) cmake(4) devcontainer.json(2) csproj(2)
> |                  dockerfile(1) settings.json(1) tasks.json(1);
> ```
> 
> </details>
> <details>
> <summary>A/B Experiments</summary>
> 
> ```
> vsliv368cf:30146710
> 
> vsclangdf:30486550
> c4g48928:30535728
> dsvsc012cf:30540253
> pynewvextcfv2:30681851
> azure-dev_surveyone:30548225
> pyindex848:30662994
> nodejswelcome1:30587005
> 282f8724:30602487
> pyind779:30671433
> f6dab269:30613381
> pythonsymbol12:30671437
> showlangstatbar:30672706
> vsccsb:30677849
> vscodedisable:30660115
> pythonb192cf:30669361
> funwalk2cf:30682975
> pythonms35:30686772
> 
> ```
> 
> </details>
> 
>

**Comment by d10c** [comment]
> Worth noting: The built in git extension will run a status every time the file changes even when GitHub Pull Requests and Issues isn't installed.

You're right, while it's true that these git updates are still happening, it has not been nearly as egregious since I uninstalled [another buggy extension](https://github.com/microsoft/sarif-vscode-extension/issues/472).

So probably this issue can be closed. Thanks!
