### ISSUE TITLE
Missing auto merge options in a forked repo that I have permissions on

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-pull-request-github#4638]
In a forked repo, eg https://github.com/microsoft/vscode-proxy-agent:

1. Start to create a PR
2. Notice there's no auto-merge button, since there are no permissions to write on the default upstream repo
3. Switch to the forked upstream, where there are permissions to write to

:bug: The auto merge button should appear

**Comment by bamurtaugh** [comment]
I was about to file an issue for what I believe is this same scenario - I'll just paste it here in case it's helpful or actually different

1. Start to create a PR on my local repo I have push access on
2. GHPRI suggests I merge changes into the default upstream, which I don't have push access on. I assume this is why I don't see the checkbox for auto-merge
3. Switch the destination to my repo I do have push access on, but I still don't see the checkbox
4. Try setting the auto merge setting, but this doesn't seem to make a difference

**Comment by alexr00** [comment]
😅
https://github.com/microsoft/vscode-pull-request-github/blob/7a4f4d6f168d48a1f7a4b2b58e1fca0037117506/src/github/createPRViewProvider.ts#L390-L391
