### ISSUE TITLE
Activating the Pull Requests and Issues extension failed. Please make sure you have git installed.

### ISSUE THREAD

**Issue by Rayvenhaus** [microsoft/vscode-pull-request-github#4641]
- Extension version: Prerelease 0.60.0
- VSCode Version: 1.77.0-insider
- OS: Windows 11 Home, Version 22H2, OS build 22621.1413
 

Steps to Reproduce:

1. Start VS Code

This is the same as Issue #4440. However, that one never went beyond the initial report.  I've installed several git extensions on my system, including this one. I have git running on my system and use Git Desktop and VS Code very successfully.

As you can see in the attached images, I have successfully opened a remote repository in VS Code. I have also made changes to the code and have been able to commit those changes to the repo as well.

Git: Enabled is checked in my settings, so I am not sure why your extension is unable to initialize. 

![2023-03-19 09_14_52-weewx-divumwx  GitHub  - Visual Studio Code - Insiders](https://user-images.githubusercontent.com/4164076/226143062-2f4191b4-e8e9-4be6-978e-384411173c6b.png)
![2023-03-19 09_15_09-](https://user-images.githubusercontent.com/4164076/226143065-19dd5acf-c6fc-4e42-9e6b-ead0cfec5d28.png)
![2023-03-19 09_16_00-Extension_ GitHub Pull Requests and Issues - weewx-divumwx  GitHub  - Visual Stu](https://user-images.githubusercontent.com/4164076/226143066-1ed39d9a-975f-4c52-a4b2-2b41e93dda3b.png)

**Comment by Rayvenhaus** [comment]
Hello?  Sorry to bump, but is this something anyone knows about or can help with?

**Comment by alexr00** [comment]
@Rayvenhaus can you confirm that you have the built in git extension installed and share the output from "Git"?

**Comment by ZorroHZR** [comment]
Hi, did you fix this issue, if yes, plz let me know as well! Thx a lots

**Comment by alexr00** [comment]
This error can show if git isn't installed or if you have disabled the built in Git extension. To solve, install git and enable the built in Git extension.

**Comment by ZorroHZR** [comment]
> Thank you for your reply!
I  instilled Git And all the built-in Git extensions. Is any extension I still need to add it?
![Terminal](https://user-images.githubusercontent.com/132423097/235856918-d4043080-f3f8-457e-beca-12ab1b5636a0.png)
