### ISSUE TITLE
Test internal GitHub rate limit

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#4646]
Refs: https://github.com/microsoft/vscode-pull-request-github/issues/4546

- [x] anyOS @meganrogge
- [x] anyOS @hediet
- [ ] anyOS @connor4312
- [x] anyOS @aiday-mar 

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode-pull-request-github/issues/new?body=Testing+%234646%0A%0A&assignees=alexr00)

---

We now have an internal local rate limit for GitHub Pull Requests and Issues. We also now throw an exception and show an error when the GitHub API rate limit is hit. There are two goals to this test plan item:
- Ensure that the internal rate limit is high enough that you never see an error message about it during normal (if intentionally aggressive) use.
- Hit the GitHub API rate limit and make sure that you see an error message and that if we were running API calls in a loop it stops.

Steps:
1. Install the pre-release build of GitHub Pull Requests and Issues.
2. Set the log level of the extension to trace (Developer: Set Log Level -> GitHub Pull Request -> Trace)
3. Open the output for GitHub Pull Request.
4. Make sure you won't need to use the extension for normal work for the next hour.
5. Open a folder with a clone of a GitHub repo in VS Code. 
6. Cause the extension to make lots of GitHub API requests and verify that you _never_ see a notification that says "The GitHub Pull Requests extension is making too many requests to GitHub. This indicates a bug in the extension. Please file an issue on GitHub and include the output from "GitHub Pull Request"." Try to come up with various ways to make the extension make API requests. Some examples: 
  - Modifying and/or refreshing the queries in the Issues and Pull Requests views. _**NOTE:**_ hitting "Refresh" on the Pull Requests view repeatedly will cause the rate limit to be hit. This is a known issue! https://github.com/microsoft/vscode-pull-request-github/issues/4767 In your testing, please find other ways to make lots of requests.
  - Refreshing the overview/description of a PR
  - Expanding lots of PRs in the Pull Requests view
8. Keep repeating step 6 until you hit GitHub's API rate limit. You'll know you've hit it when you see an error notification that says " API call count has exceeded a rate limit." Verify that the output opened in step 3 stops printing at this point. It is expected that it prints again if you run something else from the extension, but it should again error out early with the "API call count has exceeded a rate limit." error.

**Comment by alexr00** [comment]
Reopening to test again with the new rate limit mechanism.

**Comment by meganrogge** [comment]
I'm going to wait to test until the above has been fixed

**Comment by alexr00** [comment]
@meganrogge I have no plan to fix https://github.com/microsoft/vscode-pull-request-github/issues/4767 at the moment.

**Comment by roblourens** [comment]
This got an extra tester, I think it's good
