### ISSUE TITLE
Test auto merge setting

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#4647]
Refs: https://github.com/microsoft/vscode-pull-request-github/issues/4308

- [x] anyOS @gregvanl
- [x] anyOS @joaomoreno

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode-pull-request-github/issues/new?body=Testing+%234647%0A%0A&assignees=alexr00)

---

1. Install the pre-release build of GitHub Pull Requests and Issues.
2. Open a clone of a GitHub repo that you have push permissions for in VS Code.
3. Start to create a PR. 
4. Verify that the "Auto-merge" check box is unchecked by default.
5. Close the "Create" view.
6. Set `"githubPullRequests.setAutoMerge": true`. 
7. Start to create a PR.
8. Verify that the "Auto-merge" check box is checked by default.
9. Close the "Create" view.
10. Unset the setting from step 6.
11. Repeat steps 3-4 again.

**Comment by joaomoreno** [comment]
At first I thought this wasn't working at all... when I was about to comment here I just realized the checkbox appeared 😨 Here's a recording of that in action, showing 15 seconds elapsed before the checkbox appears:


https://user-images.githubusercontent.com/22350/226614234-038805fe-6ed4-4eef-ae55-aa86ee005cdd.mov

Also, I don't see any option to set the type of merge in the setting. Aren't we missing that? Ie, `Squash and Merge` vs others. I guess now we're just assuming the last set value?

**Comment by alexr00** [comment]
> Also, I don't see any option to set the type of merge in the setting. Aren't we missing that? Ie, Squash and Merge vs others. I guess now we're just assuming the last set value?

We have the existing setting `"githubPullRequests.defaultMergeMethod"`.

The slowness is unexpected. I'm looking into it now.

**Comment by joaomoreno** [comment]
@alexr00 has pushed https://github.com/microsoft/vscode-pull-request-github/pull/4654 to address this.

I can still reproduce the slowness though, so I'm creating an actual issue and close this one instead:  https://github.com/microsoft/vscode-pull-request-github/issues
