### ISSUE TITLE
Hitting GitHub API rate limit clears received PR lists

### ISSUE THREAD

**Issue by davkal** [microsoft/vscode-pull-request-github#465]
- Extension version: 0.1.4
- VSCode Version: 1.27.1
- OS: Mac

Steps to Reproduce:

1. Open Code on a Grafana clone
2. Expand Github Pull Requests (syncs fine, PR numbers show up)
3. Expand All PRs list
4. Click on a PR, and select some files.

Result: 

- a rate limit warning is displayed.
![screen shot 2018-09-13 at 13 41 23](https://user-images.githubusercontent.com/859729/45486577-e5328380-b75b-11e8-973f-d7567b2ffebe.png)

- the PR lists are cleared.

Expected:

- keeping the lists
- even better: a way to get around the rate limit

**Comment by davkal** [comment]
![screen shot 2018-09-14 at 09 54 07](https://user-images.githubusercontent.com/859729/45537331-3bf39800-b804-11e8-97d2-211217901ba7.png)

Hmm, that didn't do the trick.

**Comment by rebornix** [comment]
Same issue as #745
