### ISSUE TITLE
Broken: verify that you never see a notification that says  "The PR extension is making too many requests [...]"

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode-pull-request-github#4652]
Testing #4646

![image](https://user-images.githubusercontent.com/2931520/226609966-95d2bcc7-1250-4a2e-9c19-86a39a6af043.png)

I expanded all PRs (~300+) for the VS Code repo and clicked on this button a couple of times:

![image](https://user-images.githubusercontent.com/2931520/226610338-71b24b30-d338-47e6-9ca4-ffda20ec82a8.png)

**Comment by alexr00** [comment]
Looks like I set the internal rate limit too low.

**Comment by rebornix** [comment]
From what I read, this can still happen but less often as we increased the limit, can we call this `verified` now? @alexr00

**Comment by alexr00** [comment]
To verify:
1. Install the pre-release version of the extension
2. Open the Pull Requests view and expand all of the "All Open" query. You'll have to use the "Load more" at the end of the list many times.
3. Hit the Refresh button on the Pull Requests view _once_. Verify that you don't get an error notification.

**Comment by rzhao271** [comment]
On the microsoft/vscode repo, after clicking "load more" a few times I get the error notification "Échec de la récupération des demandes de tirage (Pull requests) : You have exceeded a secondary rate limit. Please wait a few minutes before you try again."
Pressing refresh after that doesn't cause another error notification to show up.
