### ISSUE TITLE
Auto-merge checkbox is still delayed

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-pull-request-github#4657]
Testing #4647

1. Enable `githubPullRequests.setAutoMerge`
2. Attempt to create PR, notice the checkbox is set
3. Cancel the PR creation
4. Attempt to create PR again, checkbox only becomes checked after >10 seconds

**Comment by alexr00** [comment]
I'm not able to reproduce this. What version of the extension were you using?

**Comment by alexr00** [comment]
I still haven't been seeing this, and now https://github.com/microsoft/vscode-pull-request-github/commit/0118be81c2fb7292ee3aa7d733ff3ef8bd531f0c should also prevent this. Let me know if you still see it after today!
