### ISSUE TITLE
Husky hooks are not executed

### ISSUE THREAD

**Issue by Balastrong** [microsoft/vscode-pull-request-github#4662]
I'm not sure if it's only me, but when I `git commit` I get these warnings on console and husky hooks are not executed:

```
hint: The '.husky/pre-commit' hook was ignored because it's not set as executable.
hint: You can disable this warning with `git config advice.ignoredHook false`.
```

According to the [answers here](https://stackoverflow.com/questions/8598639/why-is-my-git-pre-commit-hook-not-executable-by-default) a simple `chmod ug+x .husky/*` fixes the issue. I tested it locally and it worked.

Also, after running `chmod` the husky file is marked as changed so probably creating a PR with that should fix the issue for everyone. I can submit it in a PR if this makes sense :)

**Comment by Balastrong** [comment]
Hey @alexr00, sure!

I just created the PR :)

**Comment by DonJayamanne** [comment]
Verified on mac
