### ISSUE TITLE
Command 'GitHub Issues: Create Issue From Selection' resulted in an error - Not Found

### ISSUE THREAD

**Issue by richlaing** [microsoft/vscode-pull-request-github#4667]
- Extension version: Version: v0.60.0
- VSCode Version: Version: 1.76.2
- OS: Mac OS

Steps to Reproduce:

1. Create a TODO
2. Click on lightbulb
3. Click on Create Github Issue

<img width="776" alt="Screenshot 2023-03-23 at 10 19 51" src="https://user-images.githubusercontent.com/114079626/227173593-d5f4dd7c-d948-4edf-a40d-de3d9c8e6532.png">

<img width="776" alt="Screenshot 2023-03-23 at 10 20 46" src="https://user-images.githubusercontent.com/114079626/227173835-d60fbbb8-062b-4909-ba7a-926472aafd4f.png">

**Comment by alexr00** [comment]
@richlaing, do you see a quick input show that asks for the issue title?

**Comment by richlaing** [comment]
No, but now when I click on 'Create Github issue' nothing happens, but there is no error.

**Comment by richlaing** [comment]
There is apparently no response and no output - see screenshots:

![Screenshot 2023-04-13 at 12 01 39](https://user-images.githubusercontent.com/114079626/231739252-8a044e86-b584-404e-8393-9a8e3b878b61.png)

![Screenshot 2023-04-13 at 12 00 17](https://user-images.githubusercontent.com/114079626/231739037-625795cb-99bb-4f44-a17f-204d2f700e3f.png)
