### ISSUE TITLE
Reviewer GitHub handles render on top of re-request review buttons

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-pull-request-github#4669]
![image](https://user-images.githubusercontent.com/30305945/227386699-057e3f2d-a0fd-4f36-b869-27b170b51524.png)

**Comment by TylerLeonhardt** [comment]
<img width="184" alt="image" src="https://user-images.githubusercontent.com/2644648/227619351-b12e1608-4bb0-487b-afdd-2ea1011e9dc5.png">

Hate to be that guy with a long name, but I see this with the pending indicator still.

**Comment by TylerLeonhardt** [comment]
Filed https://github.com/microsoft/vscode-pull-request-github/issues/4672 for that. Marking verified for this specific issue
