### ISSUE TITLE
Expose a command to create a comment thread

### ISSUE THREAD

**Issue by mlewand** [Microsoft/vscode-pull-request-github#467]
When reviewing the code I'd like to be able to start a comment thread with a hotkey, so that I don't have to use mouse for that.

I have checked contributed commands and I don't see any command for starting new thread/bringing up a thread that is already associated with currently selected line.

I think that also some sort of condition that could be passed to `when` property of a hotkey would be helpful, so that it is impossible to trigger the command outside of review extension.

In case it is confirmed and you guys are willing to see that added I'm willing try to contribute a PR for that.

**Comment by RMacfarlane** [comment]
@mlewand This should be available in VS Code 1.32 and above! The command is `workbench.action.addComment`, there's no default hotkey but you can configure any keybinding for it from the keyboard shortcuts editor

**Comment by mlewand** [comment]
Amazing, thank you @RMacfarlane and the entire team for improving VSCode experience!
