### ISSUE TITLE
Automatic Rebase when switching to main from merged pull request.

### ISSUE THREAD

**Issue by adambirds** [microsoft/vscode-pull-request-github#4679]
I use a rebase workflow on all my projects and it would be great if the plugin could have an optional setting to have the plugin automatically fetch and rebase to upstream/main (or a specified remote and branch in the settings) when switching back to main from a rebase and merged pull request. It then means I'm ready to create a new branch from main with the latest changes from upstream.

**Comment by alexr00** [comment]
Please correct me if I'm misunderstanding, but I think this a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/4450.
