### ISSUE TITLE
Publishing branch reset target branch to main

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-pull-request-github#4681]
Type: <b>Bug</b>

- Create PR with the PR branch not published yet.
- Change the target ("into") branch to a release branch.
- Click "Publish Branch" in the Compare Changes view.
- Observe: The target branch resets to main.

Extension version: 0.61.2023032809
VS Code version: Code - Insiders 1.77.0-insider (Universal) (21ae43efaeaa83fe42d29903740bc322a53a8f0d, 2023-03-24T11:37:05.817Z)
OS version: Darwin arm64 22.3.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|19, 11, 9|
|Memory (System)|64.00GB (4.24GB free)|
|Process Argv|--log debug|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by roblourens** [comment]
I think "Create PR" just means to open the Create Pull Request view without submitting the PR. This flow works for me now
