### ISSUE TITLE
PRs for only one repo show in a multi root workspace

### ISSUE THREAD

**Issue by irenepc** [microsoft/vscode-pull-request-github#4682]
Type: <b>Bug</b>

I have a workspace with multiple repos, two of them pulled into a folder called `src` on different paths. 
Two `src` pull downs are displayed in the sidebar, but only one of them populates with PRs
Based on other issues I've read, it seems the repos displayed should use the repo name and not the folder name
Either way I'd like to see the PRs for all repos
Thank you!

Extension version: 0.61.2023030709
VS Code version: Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:55:54.936Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1660 v4 @ 3.20GHz (16 x 3193)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.92GB (16.81GB free)|
|Process Argv|--crash-reporter-id cfc3eb24-5f7a-49fa-af5b-bb8990b68867|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
nodejswelcome1:30587005
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
vsctsb:30677850
azdwalk:30687957
pythonms35cf:30686773

```

</details>

**Comment by alexr00** [comment]
Thank you for all the details (and for being a pre-release user of the extension)! Fix should be available in the pre-release build next week.
