### ISSUE TITLE
✨ Allow submision when pressing cmd + enter while reviewing th PR

### ISSUE THREAD

**Issue by jd-solanki** [microsoft/vscode-pull-request-github#4687]
While adding a comment for PR it is common to submit the comment via `cmd` + `enter` but unfortunately it just adds the new line.

Sorry, I am unable to record the video ATM but I guess you got the point

**Comment by alexr00** [comment]
@jd-solanki can you share a screenshot of where you're adding the comment from? We should support cmd/ctrl+enter in most places already.

**Comment by jd-solanki** [comment]
@alexr00 Thanks for your response.

Here's the video where I'm commenting on PR
https://user-images.githubusercontent.com/47495003/229156139-fca100a9-236d-4eb9-b900-b5777f398be1.mov

**Comment by alexr00** [comment]
That should already work. I see you have the Copilot extension installed. That extension steals the ctrl/cmd +enter keybinding. You can remove the Copilot keybinding in your keybindings.json.

**Comment by jd-solanki** [comment]
Hi @alexr00 

I don't have anykeybings that captures the cmd + enter on mac.

<img width="1008" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/47495003/250d1a96-ad8d-449f-9651-171ece70163c">

Can you please confirm once, Thanks.

**Comment by alexr00** [comment]
Looks like you have several, including the one that you want (which is the very last one). You can see what command is actually getting called when you do cmd+enter by running the command "Toggle Keyboard Shortcuts Troubleshooting" before you do cmd+enter.
