### ISSUE TITLE
Add support for git submodules

### ISSUE THREAD

**Issue by pinuke** [microsoft/vscode-pull-request-github#4688]
Currently my repository uses git submodules for continuous integration

This allows me to make contributions and patches to other libs/tools right from within my own repository.

It would be nice, if this extension would recognize submodules.

**Comment by DFelten** [comment]
We are working on several apps that use a shared framework. This is included as a submodule. Since we often work on both in parallel, we usually create a pull request for the app and the framework. 

It would be great if the extension could also handle pull requests for submodules.

**Comment by oleg-liatte** [comment]
There actually IS support of submodules, somewhat limited and probably unintended. See #5148 workaround.

It seems that it could be enough to just sync to Source Control panel to "see" all checked out nested repos, including submodules.

**Comment by alexr00** [comment]
Submodules should work much better now. If you see specific issues with submodules, please file new issues and I will investigate!
