### ISSUE TITLE
Question: Does this extension store my GitHub credential on remote machine when I use it in VSCode Remote?

### ISSUE THREAD

**Issue by zzh1996** [microsoft/vscode-pull-request-github#4691]

**Comment by alexr00** [comment]
This extension uses the built-in GitHub Authentication extension for auth. @TylerLeonhardt should be able to answer where anything is stored for that.

**Comment by TylerLeonhardt** [comment]
@zzh1996 Are you connecting to the remote with VS Code Desktop? If so, it should use the client side credential store.

**Comment by TylerLeonhardt** [comment]
@zzh1996 the credentials are _stored_ on the client using the built-in GitHub Authentication extension. The GitHub Pull Request extension may run on the remote side, and we will give the auth token to the remote side, but it won't be stored there.

**Comment by zzh1996** [comment]
> @zzh1996 the credentials are _stored_ on the client using the built-in GitHub Authentication extension. The GitHub Pull Request extension may run on the remote side, and we will give the auth token to the remote side, but it won't be stored there.

So if the remote server is untrusted, could it fully take control of my GitHub in theory (by intercepting my token)?

**Comment by TylerLeonhardt** [comment]
No. The connection between the server and the client is using a secure connection protocol like SSH. Once the token gets the remote, it never touches the file system and is only exists memory.
