### ISSUE TITLE
'Commit & Create Pull Request' automatically pushes when working on a PR

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-pull-request-github#4692]
Type: <b>Bug</b>

'Commit & Create Pull Request' automatically pushes when I'm already working on a PR which is problematic because I might have forgotten that I'm on a PR branch and really want to create a new PR or I might want to continue working on the commit before I push it to the existing PR.

Extension version: 0.63.2023033019
VS Code version: Code - Insiders 1.77.0-insider (Universal) (21ae43efaeaa83fe42d29903740bc322a53a8f0d, 2023-03-24T11:37:05.817Z)
OS version: Darwin arm64 22.3.0
Modes:
Sandboxed: Yes
Connection to 'dev-container+7b22686f737450617468223a222f55736572732f6368726d617274692f446576656c6f706d656e742f7265706f732f7673636f64652d70726f78792d6167656e74222c22636f6e66696746696c65223a7b22246d6964223a312c22667350617468223a222f55736572732f6368726d617274692f446576656c6f706d656e742f7265706f732f7673636f64652d70726f78792d6167656e742f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2265787465726e616c223a2266696c653a2f2f2f55736572732f6368726d617274692f446576656c6f706d656e742f7265706f732f7673636f64652d70726f78792d6167656e742f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2270617468223a222f55736572732f6368726d617274692f446576656c6f706d656e742f7265706f732f7673636f64652d70726f78792d6167656e742f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a2266696c65227d7d' could not be established
Connection to 'dev-container+7b22686f737450617468223a222f55736572732f6368726d617274692f446576656c6f706d656e742f7265706f732f736d6b747374222c22636f6e66696746696c65223a7b22246d6964223a312c22667350617468223a222f55736572732f6368726d617274692f446576656c6f706d656e742f7265706f732f736d6b7473742f2e646576636f6e7461696e65722f627567726570726f2f646576636f6e7461696e65722e6a736f6e222c2270617468223a222f55736572732f6368726d617274692f446576656c6f706d656e742f7265706f732f736d6b7473742f2e646576636f6e7461696e65722f627567726570726f2f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a2266696c65227d7d' could not be established

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 4, 6|
|Memory (System)|64.00GB (8.07GB free)|
|Process Argv|--log debug|
|Screen Reader|no|
|VM|0%|

Connection to 'dev-container+7b22686f737450617468223a222f55736572732f6368726d617274692f446576656c6f706d656e742f7265706f732f7673636f64652d70726f78792d6167656e74222c22636f6e66696746696c65223a7b22246d6964223a312c22667350617468223a222f55736572732f6368726d617274692f446576656c6f706d656e742f7265706f732f7673636f64652d70726f78792d6167656e742f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2265787465726e616c223a2266696c653a2f2f2f55736572732f6368726d617274692f446576656c6f706d656e742f7265706f732f7673636f64652d70726f78792d6167656e742f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2270617468223a222f55736572732f6368726d617274692f446576656c6f706d656e742f7265706f732f7673636f64652d70726f78792d6167656e742f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a2266696c65227d7d' could not be established

Connection to 'dev-container+7b22686f737450617468223a222f55736572732f6368726d617274692f446576656c6f706d656e742f7265706f732f736d6b747374222c22636f6e66696746696c65223a7b22246d6964223a312c22667350617468223a222f55736572732f6368726d617274692f446576656c6f706d656e742f7265706f732f736d6b7473742f2e646576636f6e7461696e65722f627567726570726f2f646576636f6e7461696e65722e6a736f6e222c2270617468223a222f55736572732f6368726d617274692f446576656c6f706d656e742f7265706f732f736d6b7473742f2e646576636f6e7461696e65722f627567726570726f2f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a2266696c65227d7d' could not be established
</details>

**Comment by Yoyokrazy** [comment]
Tried to verify this without the pre-release... Sorry bout the confusion, verified 👍
