### ISSUE TITLE
How to change the color of vertical lines (located on the left side along the code changes)?

### ISSUE THREAD

**Issue by milan-r-shah** [microsoft/vscode-pull-request-github#4697]
- Extension version: v0.62.0
- VSCode Version: 1.77.0
- OS: Ubuntu 18.04.6 LTS

Steps to Reproduce:

1. Draft a PR on GitHub.
2. Check out that PR/branch locally.
3. Open that one in VSCode.
4. Earlier, there used to be a bright white line on the left side along the code changes. However, now I noticed there is a very faint and easy-to-miss gray line. (I was about to create an issue stating that the white line got disappeared. But then I noticed that gray line)

e.g. 

![image](https://user-images.githubusercontent.com/44414437/229200045-1c5e3f4b-8b1d-4fc8-a6a8-6d9039b60a26.png)

So, mine is more of a question: how can I change the color of that line back to bright white so that I can easily see the changes on checked-out PRs?

**Comment by alexr00** [comment]
You can add a color customization in your settings for your theme. For example, this is what I have for the theme I use, "One Dark Pro":
```json
	"workbench.colorCustomizations": {
		"[One Dark Pro]": {
			"editorGutter.commentRangeForeground": "#202025",
		}
	},
```

**Comment by milan-r-shah** [comment]
It worked (even without specifying `"[One Dark Pro]"`)!
Thank you so much @alexr00 :pray:
