### ISSUE TITLE
Copy As GitHub Permalink not working for enterprise GitHub

### ISSUE THREAD

**Issue by hellige** [microsoft/vscode-pull-request-github#4698]
Type: <b>Bug</b>

This is a variation on #4245, which took me awhile to figure out.

I have `github-enterprise.uri` set to the correct enterprise host, call it `https://git.foobar.com`. However my repo was cloned without the FQDN, so my remote looked like `git@git:org/repo.git`. Github permalinks were pointing to `github.com` rather than `git.foobar.com`. It took me quite awhile to figure out what the problem was, but editing the remote URL in `.git/config` fixed the issue.

I think it would be ideal if the permalinks were correctly generated regardless of the domain name used to clone the repo, but if that's not possible, it would be great if there were some way to provide a hint of what the problem is.

Regardless, I absolutely love this feature! :heart_eyes: 

Extension version: 0.62.0
VS Code version: Code 1.77.0 (7f329fe6c66b0f86ae1574c2911b681ad5a45d63, 2023-03-29T10:05:35.165Z)
OS version: Linux x64 4.15.0-208-generic
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz (24 x 1680)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|125.82GB (118.17GB free)|
|Process Argv|--crash-reporter-id 8d88996b-5509-4503-a902-c9771ae124cb|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|xsession|
|XDG_CURRENT_DESKTOP|GNOME-Flashback:GNOME|
|XDG_SESSION_DESKTOP|xsession|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
vsctsb:30677850
pythonb192:30669360
azdwalk:30687957
pythonms35:30701012

```

</details>

**Comment by alexr00** [comment]
@hellige are you using url aliasing like in https://github.com/microsoft/vscode-pull-request-github/issues/4551?

**Comment by hellige** [comment]
@alexr00 no, I don't think the situation in that issue applies to me. I've never used `insteadOf` or `pushInsteadOf`, and have no `[url]` sections in my config. It's only that I access GHE from my office workstation where we have DNS search domains configured, so the host `git` automatically resolves to `git.foobar.com`.

**Comment by meganrogge** [comment]
Verified with code review
