### ISSUE TITLE
Expanding PR from `All Open` section does nothing

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode-pull-request-github#4706]
- Extension version: Prerelease v0.63.2023040609
- VSCode Version:
Version: 1.78.0-insider (user setup)
Commit: 3e0b354932b8ddeb099c68ed3b7dfac25350dde2
Date: 2023-04-06T05:20:25.265Z
Electron: 22.4.3
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.25330
Sandboxed: Yes
- OS: Windows 11

Steps to Reproduce:

1. Open `GitHub` view in activity bar
2. In the `All Open` section, click on the > carat next to a PR
3. The carat opens but doesn't show anything:

![image](https://user-images.githubusercontent.com/25310137/230503064-c4bd7e50-fa0e-483f-ac36-c85d07297dec.png)

It's been a bit since I've tried this interaction, so maybe I'm forgetting an additional action to take or what the expected outcome is when clicking on > next to a PR in this section.

When I try expanding one of the local PRs, I do see additional info:

![image](https://user-images.githubusercontent.com/25310137/230503259-63b2a130-3f01-4d0c-a357-4a8b42b719cf.png)

I know a rate limit was introduced last iteration (https://github.com/microsoft/vscode-pull-request-github/issues/4646), and I tried refreshing a bunch in this view to see if I'd hit the limit and get the warning. I never got the warning, but I wanted to mention this in case that's impacting anything.

**Comment by alexr00** [comment]
@bamurtaugh I had to revert the rate limit right before release. Can you share the output from "GitHub Pull Request"?
