### ISSUE TITLE
When assigned to multiple reviewers, the PR is not listed

### ISSUE THREAD

**Issue by dramosc-psl** [Microsoft/vscode-pull-request-github#471]
Issue Type: <b>Bug</b>

When a PR is assigned to multiple reviewers, it is not shown in the list of pull requests in the extension.

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:14:32.385Z)
OS version: Darwin x64 17.7.0

Steps to Reproduce:

1. Assign a PR to two reviewers.
2. Check the list in the `GITHUB PULL REQUESTS` section on any of the reviewers' vscode extension.

![image](https://user-images.githubusercontent.com/24554239/45506797-efea1a00-b755-11e8-9927-1e7653283afc.png)

![image](https://user-images.githubusercontent.com/24554239/45507156-e614e680-b756-11e8-8c10-2e55be84f080.png)

**Comment by RMacfarlane** [comment]
That's interesting, the query we're using for "Assigned to Me" is `assignee:${user}`, which I would expect to work in this case. Apparently not. I'll take a look

**Comment by RMacfarlane** [comment]
I haven't been able to reproduce this - when I assign a PR to multiple people including myself, I see it appear under "Assigned To Me". Are PRs correctly appearing under "All"?

**Comment by dramoslfl** [comment]
Yes, they are... take a look:

![image](https://user-images.githubusercontent.com/42557522/45560567-1c13a280-b80b-11e8-88e0-c5b5dc7607d0.png)

**Comment by dramosc-psl** [comment]
You are right. Even when I add a comment it stops showing. I removed the comments and it shows again. I assume it's the expected behavior so I'm proceeding to close the issue. 

Thanks a lot for your insight!
