### ISSUE TITLE
Copy github.dev Link is giving a github.com link in VS Code insiders

### ISSUE THREAD

**Issue by aditya30394** [microsoft/vscode-pull-request-github#4715]
- Extension version: v0.62.0
- VSCode Version: 1.78.0-insider
- OS: MacOS

<img width="287" alt="image" src="https://user-images.githubusercontent.com/8336542/231316414-a47bcec8-4c05-4619-a966-1fe3b08ccb2a.png">

Steps to Reproduce:

1. Create a codespace using VS Code Insiders
2. Connect to it and open any file
3. Right click -> Share -> "Copy github.dev Link"

I was expecting a github.dev link but got a github.com link

![image](https://user-images.githubusercontent.com/8336542/231316930-28b2f1bc-3172-4ee9-b267-92dd19aa54da.png)

**Comment by joyceerhl** [comment]
@alexr00 what version of GHPRI do you have in Codespaces? I think Codespaces always bundles the stable version of GHPRI by default, and there is no way to switch to pre-release in product. May require installing from VSIX?

**Comment by joyceerhl** [comment]
> I don't see github.dev as an option at all

Yes, that's the intended behavior

**Comment by TylerLeonhardt** [comment]
Oops :) thought he fix was fixing it to actually go to github.dev instead of github.com. In that case, verified!

**Comment by alexr00** [comment]
The version that shows is different in different places, but given that @TylerLeonhardt verified the issue it seems likely that the actual version is stable. I am following up about the inconsistent version:

<img width="1149" alt="image" src="https://user-images.githubusercontent.com/38270282/235079741-7fcc21c1-903f-4f31-ad73-dcdf0d40ddf7.png">
