### ISSUE TITLE
Authentication with PAT fails due to mismatch of token scopes

### ISSUE THREAD

**Issue by jens-auer** [microsoft/vscode-pull-request-github#4718]
I am trying to authenticate with a GHES instance using a PAT. After clicking on "Sign In" in the vs code plugin, I select "continue to Github" and then generate the token with pre-selected permissions. 
![image](https://user-images.githubusercontent.com/9391718/231722289-d8b5b797-f0fc-4464-a23f-5ad18f828d92.png)

When I paste the generated token into the input box in vs code, login fails with the following message in the output:

```
2023-04-13 11:45:07.782 [info] Trying to retrieve PAT... (read:user repo user:email workflow)
2023-04-13 11:46:49.562 [info] Getting token scopes...
2023-04-13 11:46:50.026 [error] Error: The provided token does not match the requested scopes: read:user repo user:email workflow
```

**Comment by alexr00** [comment]
@jens-auer do you know what version of GitHub Enterprise you're using?

@TylerLeonhardt the scopes that are checked look correct, but `repo` is greyed out, which seems weird.

**Comment by jens-auer** [comment]
Sure, it is GitHub Enterprise Server 3.8.1

**Comment by jens-auer** [comment]
Is there a way to print the reply for "Getting token scopes"? Maybe the error message is misleading.

**Comment by jens-auer** [comment]
I could resolve the issue. I need to use a proxy to connect to the GHES instance. I guess that there is an indirect that misinterpreted as the result of the "Getting token scopes ..." request which is hidden. You can actually see that there is a redirect when Github Pull Request tries to login into GHES as it fails and logs the redirect.

The only problem now is that I have to set the proxy globally as http proxy which I don't want because it is only needed to access the GHES instance. Is there a way to set a proxy in the plugin settings?

**Comment by TylerLeonhardt** [comment]
@chrmarti can you chime in here with your proxy knowledge?

**Comment by chrmarti** [comment]
This could be done (with some effort) by setting up a PAC script that only returns a proxy for the hostnames you need one for. You can add the PAC script URL in your OS' proxy settings. Not sure if the script needs to have an `http/s:` URL or if a local `file:` URL will work (on Windows it won't: https://learn.microsoft.com/en-us/troubleshoot/developer/browsers/administration/cannot-read-pac-file). See, e.g., https://developer.mozilla.org/en-US/docs/Web/HTTP/Proxy_servers_and_tunneling/Proxy_Auto-Configuration_PAC_file.

There is the `NO_PROXY` environment variable to exclude hosts from being proxied, but there is no env variable to only include certain hosts.
