### ISSUE TITLE
Horizontal scrolling with trackpad doesn't work on macOS

### ISSUE THREAD

**Issue by connorshea** [microsoft/vscode-pull-request-github#472]
- Extension version: 0.1.4
- VSCode Version: 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc)
- OS: macOS 10.13.6 (High Sierra)
- Device: Late 2013 MacBook Pro (this should be reproducible on any Mac with a trackpad / Magic Trackpad, potentially also the Magic Mouse?)

Steps to Reproduce:

1. Open a Pull Request in VSCode (e.g. https://github.com/mdn/browser-compat-data/pull/2770)
2. Go to a comment with a wide code block (in this case it's JSON, though I don't think that matters, also note that you may need to reduce the width of the window to make the scrollbar appear)
3. Attempt to scroll horizontally within the code block using the trackpad, note that this doesn't work.

Clicking and dragging the scrollbar itself works, but not scrolling with the scroll gesture. Vertical scrolling works fine as far as I can tell.

Example image:
<img width="1003" alt="screen shot 2018-09-13 at 12 25 31 pm" src="https://user-images.githubusercontent.com/2977353/45507949-af3bd200-b750-11e8-9b2a-723a5b8336b0.png">

This may be a problem with VSCode, apologies if I should have opened this upstream 🙇

**Comment by alexr00** [comment]
I'm not able to reproduce on Windows with the trackpad. If you're still seeing the issue please comment!
