### ISSUE TITLE
quickDiff setting is ignored

### ISSUE THREAD

**Issue by nathaniel-palmer-simplisafe** [microsoft/vscode-pull-request-github#4726]
Type: <b>Bug</b>

When `githubPullRequests.quickDiff` is disabled I still see the quick diff annotations in the gutter for PR changes even after reloading VSCode. Sometimes I have a PR checked out locally that I'm still working on and without this setting I can't use the gutter annotations to reliably tell what I've changed locally.

Extension version: 0.62.0
VS Code version: Code 1.77.3 (Universal) (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:19:37.325Z)
OS version: Darwin x64 22.4.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 3, 2|
|Memory (System)|32.00GB (0.96GB free)|
|Process Argv|--crash-reporter-id ed50f89e-497f-43cd-86f3-a73119f730ed|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1:30587005
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
defaultazurewalk:30687958
pythonms35:30701012
pythonfmttext:30710681
pythonclientmvcf:30713944

```

</details>

**Comment by alexr00** [comment]
@nathaniel-palmer-simplisafe did you reload after setting `githubPullRequests.quickDiff` to false? That setting requires a reload to change.

**Comment by diminutivesloop** [comment]
@alexr00 Yes I did

**Comment by alexr00** [comment]
I could also repro because I had the old setting `githubPullRequests.experimental.quickDiff` still set. As a fix, I've stopped reading that old setting in the extension.

**Comment by nathaniel-palmer-simplisafe** [comment]
It would still be helpful to have a way to switch between PR and local changes globally rather than having to toggle between them when viewing individual changes although that would probably work better as a command rather than a setting. Would it make sense to open that as a feature request here or on the main VSCode repo?

**Comment by alexr00** [comment]
@nathaniel-palmer-simplisafe can you confirm that this is the flow you want?
1. You're looking at a file that has quick diffs from multiple places (ex. git and pull request)
2. You want to globally set only one of these to show in the gutter (ex. just pull request)
3. You use the (currently non-existent feature) toggle active quick diff to only show one type of quick diff
4. Now you want to see all quick diffs again, so use the feature to toggle all quick diffs back on

**Comment by meganrogge** [comment]
Where are the `quickDiffs` shown?

**Comment by alexr00** [comment]
This is a quick diff:
<img width="491" alt="image" src="https://user-images.githubusercontent.com/38270282/235085379-abf23d40-0671-4a91-aa50-1b80396aac0f.png">

To verify:
- Install the pre-release version of this extension
- Open a GitHub repo in VS Code
- Check out a pull request
- Open a file from the pull request _not in a diff editor_
- Make a change in the file so that you have git quick diffs
- Set `"githubPullRequests.quickDiff": false`
- Set `"githubPullRequests.experimental.quickDiff": true`
- Verify that you _only_ git quick diffs and no GitHub Pull Request quick diffs

**Comment by ulugbekna** [comment]
@alexr00 Just a heads up: the settings changes related to quickdiffs aren't picked up without reloading the vscode window
