### ISSUE TITLE
Approve button should be disabled when PR is alreay approved

### ISSUE THREAD

**Issue by mike-pt** [microsoft/vscode-pull-request-github#473]
Issue Type: <b>Bug</b>

Enter Review mode for a PR

Type your'e comment (or not) and press "approve".

The button is still enabled and there's no indication that you've already approve this.

The UI should show the user if a PR was already approved/requested changes (possibly like GH does with the green_checkmark / red cross)

And if it was already approve it doesn't make much sense to still allow the user to "approve again" 

Extension version: 0.1.4
VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:14:32.385Z)
OS version: Darwin x64 17.7.0

**Comment by RMacfarlane** [comment]
This is actually the same behavior as GitHub, there's no restriction on approving something multiple times. But this has been reported several times so is worth fixing to line up with people's expectations

**Comment by MartinDM** [comment]
Agreed, this threw me off initially too as it's unexpected.
Not only can you keep 'approving', but another activity is added each time, which looks buggy.

**Comment by rishab-pdx** [comment]
I could see the Overview panel has no idea about the review status of the PR to know when to enable/disable the approve button.  So we need to add it to the Model and access it in the view.
