### ISSUE TITLE
Enable "Add suggestion to batch" feature for suggestions.

### ISSUE THREAD

**Issue by protoEvangelion** [microsoft/vscode-pull-request-github#4746]
Currently the Github UI allows you to "Add suggestion to batch":

![image](https://user-images.githubusercontent.com/20076677/233141488-c276b221-bcb4-4cb3-8bbf-cb4331520621.png)

However, I'm not able to see this in the extension ui, or in available as a vs code action:

![image](https://user-images.githubusercontent.com/20076677/233141388-ccb009d3-8afa-4890-81ca-4cc1e10b40d8.png)

Maybe we could just add an additional button next to the "Apply Suggestion" present icon:

![image](https://user-images.githubusercontent.com/20076677/233142045-ffbf4249-d23e-4d23-93c0-19a8de2e67d9.png)

And additionally, we can show a count of number of items in the batch when hovering over the icon to mirror Github ui.

**Comment by alexr00** [comment]
@protoEvangelion we don't commit the suggestion when you accept it in the extension. Instead, we apply the change locally. You can apply as many suggestions as you want before committing them, effectively allowing you to make a batch.

**Comment by alexr00** [comment]
Closing as as-designed since you can batch your suggestions however you want.
