### ISSUE TITLE
Issues are shown twice when `githubIssues.queries` is missing a repository

### ISSUE THREAD

**Issue by jespertheend** [microsoft/vscode-pull-request-github#4747]
- Extension version: `v0.62.0`
- VSCode Version: 1.77.3
- OS: Ubuntu 22.10

Steps to Reproduce:

1. Click the pen icon to open `settings.json` and start editing `githubIssues.queries`
2. Set the query to `"is:open assignee:${user}"`

This results in the list off issues being displayed twice:
![image](https://user-images.githubusercontent.com/2737650/233226014-b5a60551-2b92-4039-98d2-2009b93e4250.png)

Setting the query to `"is:open assignee:${user} repo:${owner}/${repository}"` seems to fix it

**Comment by alexr00** [comment]
I can no longer repo this issue.
