### ISSUE TITLE
Trying to open a diff with a package-lock.json file instead sent me to GitHub

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode-pull-request-github#475]
Issue Type: <b>Bug</b>

Was reviewing a PR with changes to `package-lock.json` and when clicking on the file in the tree it sent me to GitHub rather than opening the diff in vscode.

Extension version: 0.1.4
VS Code version: Code - Insiders 1.28.0-insider (8330a695712c43f861ce5c47533d82637d3cb374, 2018-09-13T11:25:00.283Z)
OS version: Windows_NT x64 10.0.17758

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (18.94GB free)|
|Process Argv|C:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by RMacfarlane** [comment]
For some changes, the GitHub api doesn't return back an actual patch of the change, for example when it's particularly large or an unsupported file type. We fall back to opening it on GitHub in this case.

We need to improve the UX for this to make it clear why this is happening - there's an item tracking this [here](https://github.com/Microsoft/vscode-pull-request-github/issues/442), so I'll close this as a duplicate
