### ISSUE TITLE
Nudge users towards sign-in

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-pull-request-github#4756]
Currently 31% of users that have GH PR extension installed in VS Code are NOT logged in to GitHub. Thus they are missing on all the great GH PR extension functionality. This is a large number and we need to look into product changes on the extension side to better nudge users towards sign-in.

One of the simple first steps is to show a badge in the accounts menu when the user is not signed in after installing the GH PR extension. 

@alexr00 you probably have better ideas :) You also shared that historically we did not do this for the vscode.dev flow so users would not get a lot of badges on the Account menu when they open it for the first time. However since majority of GH PR extension is in VS Code desktop we should gear the experience towards that.

fyi @joaomoreno

**Comment by alexr00** [comment]
> One of the simple first steps is to show a badge in the accounts menu when the user is not signed in after installing the GH PR extension.

I would definitely start here. We could also show a badge on the "GitHub" activity bar icon, which is even more visible than the Accounts menu.

**Comment by isidorn** [comment]
Agreed. Let's start with the accounts menu. We see how it affects numbers and then we can decide on next steps?

**Comment by isidorn** [comment]
Let's see what @joaomoreno thinks about the vscode.dev experience. Do you remember who was previously pushing for this experience in vscode.dev, so we also include them in this discussion.
