### ISSUE TITLE
Rendering of GH source code links are a bit messed up

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode-pull-request-github#4757]
- Extension version: v0.63.2023042009
- VSCode Version: 1.78.0-insider
- OS: macOS

Steps to Reproduce:

1. Open a PR with GitHub source links in it
2. See the following:

<img width="789" alt="image" src="https://user-images.githubusercontent.com/2644648/233752266-7eb5e40e-c834-4444-9352-70d6a5e38062.png">

_This is from [this PR](https://github.com/microsoft/vscode/pull/180585)._

Note that "Line" is cut off.

**Comment by alexr00** [comment]
This is caused by the link being in a list. I can't figure out what's going on with the CSS though. It's more than just "Line" that's off.
