### ISSUE TITLE
Test team reviewers

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#4764]
Refs: https://github.com/microsoft/vscode-pull-request-github/issues/1126

- [x] anyOS @meganrogge
- [x] anyOS @lszomoru
- [x] anyOS @karthiknadig
- [x] anyOS @aiday-mar 

Complexity: 5

[Create Issue](https://github.com/microsoft/vscode-pull-request-github/issues/new?body=Testing+%234764%0A%0A&assignees=alexr00)

---

### Background

You can have 2 kinds of reviewers on a GitHub PR: users and teams. We now newly support adding team reviewers to a PR from within the extension. There were two major issues to work around: we need additional auth scopes and getting team reviewers can be very slow.

### Setup

If you work in a repo that uses team reviewers, then please verify this issue in that repo. Otherwise, you can use https://github.com/microsoft/vscode-pull-request-github/pull/3509 for adding and removing reviewers. The team you can use on https://github.com/microsoft/vscode-pull-request-github/pull/3509 is microsoft/github-pull-request-test.

### To verify

Test with a repo that is part of an org:

1. Open your repo and install the pre-release version of GitHub Pull Requests and Issues.
2. Open the description/overview page of the PR you want to use for testing from the "Pull Requests" view.
3. Start to add a reviewer by clicking on the gear next to "Reviewers"
4. You should see a quick pick with _user_ reviewers come up. Verify that you see a "teams" icon in the top right of the quick pick.
5. Click on the "teams" icon to fetch team reviewers.
6. Verify that you're prompted to auth.
7. Complete the auth. Verify that after a few seconds you see a message in the quick pick about fetching team reviewers being slow.
8. Verify that you _eventually_ see team reviewers in the quick pick. Verify that icons are added for all possible reviewers to make it easy to distinguish between teams and users.
9. Choose one of the team reviewers. Go to github.com and verify that the team reviewer was added.
10. Reload
11. Try to add a reviewer again. Verify that the team reviewers are cached and are already there without you having to wait for them.
12. Remove the team reviewer. Go to github.com and verify that the team reviewer was removed.

Test with a repo that is not part of an org:

1. Open your repo and install the pre-release version of GitHub Pull Requests and Issues.
2. Open the description/overview page of the PR you want to use for testing from the "Pull Requests" view.
3. Start to add a reviewer by clicking on the gear next to "Reviewers"
4. You should see a quick pick with _user_ reviewers come up. Verify that you **do not** see a "teams" icon in the top right of the quick pick.

**Comment by karthiknadig** [comment]
I am not able to pull up Overview page from the "pull request" view:
![image](https://user-images.githubusercontent.com/3840081/234375437-9c7d2d2d-f3fd-4194-87f1-33871ec60922.png)

Clicking on the pull request title does nothing.

**Comment by karthiknadig** [comment]
Since I cannot bring up the PR page to select reviewers I am blocked.

**Comment by alexr00** [comment]
@karthiknadig I've fixed the error and the fix will be available in the next pre-release build, though I wouldn't expect that to cause the PR description to not show. Can you install the latest pre-release, repro the issue, then share the output of GitHub Pull Request?

**Comment by karthiknadig** [comment]
@alexr00 Clicking this status item would not open the issue:
![image](https://user-images.githubusercontent.com/3840081/234641214-d720fd7a-f0c5-4539-ac44-4666f06468af.png)
 
I had to un-install and re-install the same version, and it started working.

This worked fantastically for me now. Thanks.

**Comment by meganrogge** [comment]
@karthiknadig did you have to use a PAT? It's using the wrong one for me
