### ISSUE TITLE
cannot access teams feature

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode-pull-request-github#4770]
Testing #4764

Using this repo and #3509, it's still saying I can't access the teams feature

![Screenshot 2023-04-25 at 1 54 05 PM](https://user-images.githubusercontent.com/29464607/234401258-953e37f6-ccb4-442b-9c58-a0d357deacf6.png)

here's what I tried:

![Screenshot 2023-04-25 at 2 08 22 PM](https://user-images.githubusercontent.com/29464607/234404399-f07fc5f0-867a-4586-9a64-b45c0970fa8f.png)

The 403 is weird because I can edit the repo directly 🤔 

![Screenshot 2023-04-25 at 1 40 34 PM](https://user-images.githubusercontent.com/29464607/234401107-cf6de925-3a93-4ea1-ae91-4f2c4692b099.png)

**Comment by karthiknadig** [comment]
I am getting the same error:
![image](https://user-images.githubusercontent.com/3840081/234401882-a9ff35d2-ce96-4c2e-8d8e-ea4b184a1d14.png)

**Comment by alexr00** [comment]
@meganrogge are you using a PAT that you created? If so, can you please:
- Sign out from your github account in VS Code
- Clone microsoft/vscode-pull-request-github again, without using that token. Instead, clone with https or ssh
- Open the cloned repo in VS Code
- Open the GitHub view and sign in
- Proceed with the test plan item.

@karthiknadig did you also somehow use a PAT?

**Comment by alexr00** [comment]
Found the issue after a quick call about https://github.com/microsoft/vscode-pull-request-github/issues/4773

**Comment by meganrogge** [comment]
@alexr00 when will this be available for retesting?

**Comment by alexr00** [comment]
It is already available in the pre-release build!
