### ISSUE TITLE
Cannot View Pull Request Description after a few days.

### ISSUE THREAD

**Issue by dreens** [microsoft/vscode-pull-request-github#4783]
Using GitHub Pull Request and Issues Extension v0.63.2023042009 (or v0.62)
Using Github Enterprise 3.2.20. 
I'm having an issue where I can't load the description page of open pull requests after a day or two. Clicking on "Description" beneath the expanded view of the pull request has no effect, nor does clicking on the smaller "Open Pull Request Description to the Side" button. 
![image](https://user-images.githubusercontent.com/5703503/234969199-0c2a372d-b52c-4bca-be26-5d22f6ac98a6.png)

When I look at the output of GitHub Pull Request in vscode, I find an error that appears:
[error] PullRequestModel> Failed to get pull request review comments: Error: GraphQL error: Field 'subjectType' doesn't exist on type 'PullRequestReviewThread'
![image](https://user-images.githubusercontent.com/5703503/234969504-780d0d74-d8d9-4b10-969f-81fbbe1b9927.png)

This seems similar to an older closed issue, https://github.com/microsoft/vscode-pull-request-github/issues/2772.

Rebooting vscode, or the computer, doesn't address the issue.
It never happens when I first view a pull request, or newly create one myself.
It always happens eventually, after a few days.
I've had it happen with a dozen or so pull requests so far over last two months.

**Comment by dreens** [comment]
I have discovered an important piece related to this issue.
Specifying a default web browser and rebooting vscode has resolved the issue, at least temporarily.
Does github pull request depend upon there being a default web browser specified on the machine?
Would it be possible to specify a browser to use with a local setting instead of relying on the global windows setting?
My windows 10 image is slightly faulty and forgets the default web-browser after every reboot.

**Comment by alexr00** [comment]
@dreens do your git remotes use ssh? If so, not being able to open the description could be https://github.com/microsoft/vscode-pull-request-github/issues/4768

> [error] PullRequestModel> Failed to get pull request review comments: Error: GraphQL error: Field 'subjectType' doesn't exist on type 'PullRequestReviewThread'

I will likely need to make a fix for this.

**Comment by dreens** [comment]
Hi @alexr00 thanks for your reply. No, I am not using SSH. I can confirm that specifying a default web browser in my windows 10 settings resolves this issue. 

Perhaps I should close the issue? It would be nice, though, if some appropriate error message were registered relating to the lack of a default web browser, rather than the nearly silent failure at present.

**Comment by alexr00** [comment]
> It would be nice, though, if some appropriate error message were registered relating to the lack of a default web browser, rather than the nearly silent failure at present.

I don't see why specifying a default web browser should make a difference. 

The PR description is displayed using a webview. Next time you see this issue with the PR description can you open another webview (such as the release notes by running the command to show the release notes) and see if that webview shows properly?
