### ISSUE TITLE
Welcome view when you are in subfolder of a repo

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode-pull-request-github#4784]
Steps to Reproduce:

1. create a codespace for https://github.com/microsoft/vscode-extension-samples
2. `File -> open folder` on one of the extension samples

Git will tell you it's not working:
![image](https://user-images.githubusercontent.com/2644648/235010762-006cecec-45cc-4401-8f65-df3ea96dc2ce.png)
![image](https://user-images.githubusercontent.com/2644648/235010782-3b8d76b2-d02d-435f-bc3e-02407f8c237b.png)

But GHPR says nothing too useful:
![image](https://user-images.githubusercontent.com/2644648/235010817-ae2fe6e5-ee08-45e0-bd2b-cea8574db428.png)

Could GHPR have a better welcome view here?

cc @joyceerhl

**Comment by alexr00** [comment]
@TylerLeonhardt what kind of message would you expect here?

**Comment by TylerLeonhardt** [comment]
I think what's confusing to me is that it says "no git repo found" but there _is_ a git repo, it's just above this workspace. I wish that was clearer in the message... ideally, I wonder if a button that would open the repo help here as well.

**Comment by alexr00** [comment]
@lszomoru Is there a way I can tell that the git extension has found a repo in a parent folder from the git extension API?

**Comment by lszomoru** [comment]
Could you use the `git.parentRepositoryCount` context key that is set in the git extension?

**Comment by alexr00** [comment]
@lszomoru that works great, thank you. I basically just copied your git welcome views.
