### ISSUE TITLE
Enterprise Login  not working

### ISSUE THREAD

**Issue by ArtixZ** [microsoft/vscode-pull-request-github#4789]
- Extension version: v0.63.2023042009
- VSCode Version:1.77.3
- OS: MacOS

Steps to Reproduce:

Can't login even after configured company URL. Tried out all the login methods.
Got this error:
>We've made some updates to our authentication process for VS Code and GitHub. Please upgrade to the latest release of VS Code (1.66+) or download from [here](https://code.visualstudio.com/).

And Then when using code, got this error:
>Sign in failed: Error: network error

**Comment by alexr00** [comment]
@ArtixZ Are you using the official release build of VS Code?
@TylerLeonhardt FYI.

**Comment by luyu12** [comment]
Is there any update or fix for this issue? Im seeing the same error on my end.

**Comment by macrosszhao** [comment]
We have also meet this issue:
We have an Github enterprise workspace like mygithub.xxx.com.
But when I trying sign in GitHub Pull Requests and Issues by option sign in with github Enterprise, it always lead me to sign in to github.com, someone can tell me how to solve this issue?

Extension version: v0.64.0
VSCode Version:1.78.2
OS: Windows 10

**Comment by macrosszhao** [comment]
> 
@macrosszhao can you share a screen shot of what you're clicking in VS Code to start the sign in?

@alexr00  sure.
below is my operation step.
![屏幕截图 2023-05-25 113108](https://github.com/microsoft/vscode-pull-request-github/assets/127573343/ba48be5d-e789-4411-bf45-967eb8767b68)
![屏幕截图 2023-05-25 113202](https://github.com/microsoft/vscode-pull-request-github/assets/127573343/990628a5-6994-489e-b8d3-7608fc23262e)
![屏幕截图 2023-05-25 113023](https://github.com/microsoft/vscode-pull-request-github/assets/127573343/7f639662-3279-4ff6-af7e-928a9e23a6a8)

**Comment by alexr00** [comment]
Thanks @macrosszhao. I think I see what's happening. The next pre-release build (should be some time much later today or early tomorrow) will have the fix.
