### ISSUE TITLE
Activating the Pull Requests and Issues extension failed

### ISSUE THREAD

**Issue by ZorroHZR** [microsoft/vscode-pull-request-github#4797]
<! Help > Report Issue: Activating the Pull Requests and Issues extension failed. Please make sure you have git. Source: GitHub Pull Requests and Issues (Extension)
And I already have that GitHub account, and try to install the pre-release version, but nothing turned into a good situation. 

Name: GitHub Pull Requests and Issues
Id: GitHub.vscode-pull-request-github
Description: Pull Request and Issue Provider for GitHub
Version: 0.62.0
Publisher: GitHub
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github

**Comment by alexr00** [comment]
Do you have the built in git extension enabled?
