### ISSUE TITLE
Rename node "Description" node under a PR to something more descriptive

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode-pull-request-github#480]
Right now the first node under a PR node just says "Description", I would suggest something more descriptive like, "Open Pull Request" or "View Pull Request" -- so much good stuff is hidden under that innocuous "Description" title 😄

**Comment by NavyAdmiral** [comment]
@eamodio agreed, initially I couldn't actually tell what `Description` stood for before clicking it.

**Comment by auchenberg** [comment]
Suggestion: "Overview"

**Comment by eamodio** [comment]
Isn't it more than just an Overview though? Its where you perform a bunch of actions, check out, review, comments, etc. I think it would also be nice to have some state in that name -- like if the PR is checked out, etc

**Comment by auchenberg** [comment]
@eamodio What do you call this page in GitHub? The PR overview page? Permalink?

**Comment by eamodio** [comment]
Pull Request page. Since the command to open page that from the tree item's menu is `Open Pull Request in GitHub`, I why I suggested the same but without the `in GitHub` part. Or since `Open` has its own connotation with regards to PRs, maybe change both to View.

**Comment by Dan503** [comment]
Another suggestion:  "Details"

**Comment by dylmye** [comment]
I suggest that the link to the description/overview/details be the parent rather than a child. Please refer to my handy diagram ;)

![diagram showing how the link to the 'Description' tab will be replaced by just clicking on the parent of the PR tree](https://user-images.githubusercontent.com/7024578/45634782-2ba91a80-ba9b-11e8-9ab0-f2485121f114.png)

**Comment by alexr00** [comment]
Given the lack of consensus (and the fact that this issue is 2 years old and we're still using "Description"), closing in favor of keeping "Description".
