### ISSUE TITLE
Comments are not resolved on GitHub after being marked resolved on desktop

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-pull-request-github#4808]
1. Checkout a PR with unresolved comments locally
2. Make changes to resolve the comments and commit
3. Mark comments resolved locally inside VS Code
4. Open PR on github.com again
5. :bug: comments are not resolved

**Comment by Danp2** [comment]
FWIW, I am also seeing the opposite where conversations marked resolved via the web don't ever show as resolved in VSC.

**Comment by joyceerhl** [comment]
@alexr00 will do, thank you!

**Comment by joyceerhl** [comment]
> FWIW, I am also seeing the opposite where conversations marked resolved via the web don't ever show as resolved in VSC.

This still repros for me, even closing and reopening the diff editor where changes were made doesn't force a refresh

**Comment by joyceerhl** [comment]
But the original issue of comments being resolved in VS Code and not on GitHub is fixed. I'll file a new issue for the inverse
