### ISSUE TITLE
PR from Main branch acts a little odd

### ISSUE THREAD

**Issue by joshka** [microsoft/vscode-pull-request-github#4809]
- Extension version: v0.63.2023050409
- VSCode Version:Version: 1.78.0
- OS: Mac

Steps to Reproduce:

1. Create a pull request from your local main branch and merge it from github
2. Checkout another PR (2)
3. Click the checkout main button. Saw a "Pull request successfully merged" message (related to the previous PR

That was a bit confusing for a sec, and I thought I'd inadvertently merged PR 2.

The UI then offers kindly to let you delete your main branch (which doesn't work because that's the branch that's checked out.

Is there some way to disassociate that PR with my main branch?

https://github.com/tui-rs-revival/ratatui/pull/133 is the issue

**Comment by alexr00** [comment]
@joshka it's not quite what you're looking for, but this setting should work:
```
	"githubPullRequests.useReviewMode": {
		"merged": false,
		"closed": false
	},
```

If you never want to associate PRs with your main branch you could set:
```
	"githubPullRequests.ignoredPullRequestBranches": [
		"main"
	],
```

**Comment by alexr00** [comment]
Leaving open as a feature request to ignore specific PRs.
