### ISSUE TITLE
it is not clear at all how this is supposed to operate

### ISSUE THREAD

**Issue by ericblade** [Microsoft/vscode-pull-request-github#481]
So, I've tried this out in about a dozen repos, with varying states of pull requests, and it just shows "0 pull requests in this category" for all of them.  

A step-by-step guide to seeing something happen, would be pretty handy.

**Comment by ericblade** [comment]
Yes -- that is exactly the configuration that I have for pretty much everything.  Does it use a specific remote name for the upstream (such as 'upstream' :-D ) or does it just basically not work like that?  

Considering that the github workflow, generally, is to fork something, then use your fork as what you work with, I think there's not too many people hanging around with clones of the upstream repo that they're doing work in.  So it would be good to have an ability to figure out what is "my" repo and what is the "upstream" repo.

**Comment by RMacfarlane** [comment]
Hmm, if you have a remote tracking the upstream repo, then it should work.

The extension looks at all of the remotes, regardless of name, and tries to identify those that are associated with GitHub. (code here: https://github.com/Microsoft/vscode-pull-request-github/blob/master/src/github/pullRequestManager.ts#L59) For each GitHub remote, it requests PRs: if the result is less than a page size of PRs, it requests from the next one. Are you seeing any failures in the output channel after selecting "GitHub Pull Requests" from the dropdown?

**Comment by ericblade** [comment]
... ok, that makes sense.  I feel like that should be in the readme, or if it is, then it needs to be bigger. :-D
