### ISSUE TITLE
GH-actions run overview

### ISSUE THREAD

**Issue by simonblund** [microsoft/vscode-pull-request-github#4815]
I want to view GH-action runs in the extension view.

I am working on big python projects where local testing is complicated to set up and run. I usually set up a gha that runs on each push to the branch I am working on that runs tests and linting. It'd be great to be able to view the latest runs directly in the extension and see the outputs of the run easily.

Thanks for a great extension!

**Comment by alexr00** [comment]
This seems like a feature https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-github-actions might have!
