### ISSUE TITLE
Search PR by id/number in sidebar

### ISSUE THREAD

**Issue by valdineifer** [microsoft/vscode-pull-request-github#4818]
I know that exists a command to checkout PR using the Command Palette (#1062), but I think that the possibility of search using Ctrl+F in GitHub Pull Requests sidebar would be useful.

![image](https://github.com/microsoft/vscode-pull-request-github/assets/9989376/4d69d699-df60-4ea3-ade5-8b73dad233f1)

**Comment by alexr00** [comment]
Closing as out of scope because we don't intend to address this in the near future.
