### ISSUE TITLE
Provide commands that jump to the next changed section in the PR

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#483]
I have the following keybindings to make it quick to jump between git diffs in the active file without touching the mouse:

```json
{ "key": "alt+f3",           "command": "workbench.action.editor.nextChange", "when": "editorTextFocus" },
{ "key": "shift+alt+f3",     "command": "workbench.action.editor.previousChange", "when": "editorTextFocus" },
{ "key": "alt+f3",           "command": "workbench.action.compareEditor.nextChange", "when": "textCompareEditorVisible" },
{ "key": "shift+alt+f3",     "command": "workbench.action.compareEditor.previousChange", "when": "textCompareEditorVisible" }
```

I would like two commands to do the same when in both a regular editor (like `workbench.action.editor.*Change`) and the compare editor (like `workbench.action.compareEditor.*Change`).

Note that ideally this would be done with https://github.com/Microsoft/vscode-pull-request-github/issues/392 and use those lines as the chunks to jump to. In the meantime maybe it could jump to the commentable range instead?

**Comment by plchampigny** [comment]
A shortcut to move to next file in PR would be nice too

**Comment by JacksonKearl** [comment]
Running into this with https://github.com/microsoft/vscode/pull/115119, hard to navigate a large PR via the tree.

**Comment by alexr00** [comment]
We now have the command "Go to Next Diff in Pull Request".
