### ISSUE TITLE
Sometimes the PR description page doesn't open

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-pull-request-github#4834]
<img width="542" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/323878/88924f77-be9a-4368-b0d3-79f6edd12e16">

I've been seeing this sometimes after I click the status bar item. No errors in devtools or the network panel. Reloading vscode fixes it but just clicking the status bar item again doesn't.

<img width="417" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/323878/6a1498ec-cab1-4424-bffd-4fce3e604fad">

**Comment by alexr00** [comment]
@roblourens is this in vscode.dev, github.dev, or desktop?

**Comment by roblourens** [comment]
This was in desktop

**Comment by alexr00** [comment]
Next time you see this can you share any errors in the dev console and the output from GitHub Pull Request?
