### ISSUE TITLE
Reassigning same reviewers causes desync with GitHub

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode-pull-request-github#4836]
- Extension version: v0.65.2023051809
- VSCode Version: 1.79.0-Insiders
- OS: Windows 11

Steps to Reproduce:

1. In a PR, add two reviewers A and B.
2. Click on the Reviewers heading to open the quickpick. Notice that A and B are selected in the quickpick. Press OK.
3. In the PR view, A and B are still reviewers of the PR.
4. :bug: Open the PR on GitHub and notice that A and B have been unassigned from the PR.

**Comment by alexr00** [comment]
The GitHub API we're using appears to be removing all reviewers that haven't reviewed yet even when I include them in the re-request. I am following up with GitHub folks about this.

**Comment by alexr00** [comment]
Related https://github.com/microsoft/vscode-pull-request-github/issues/4830
