### ISSUE TITLE
Checking out a PR doesn't refresh comment actions

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#4839]
1. Have a PR that has a suggested change in it
2. Do not check out the PR
3. Open the file with the suggestion from the PRs view
4. See the suggestions and leave the file open
5. Now check out the PR
6. The action to accept the suggestion doesn't appear on the comment even though the PR is now checked out.

**Comment by andreamah** [comment]
<img width="980" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/31675041/60ab9ea1-c293-45c0-b5f5-d1736e0773fb">
 I'm not seeing the accept suggestion button even though I'm checked out to the PR. Am I doing something wrong?

**Comment by alexr00** [comment]
@andreamah the screenshot actually has the accept action visible in it. It's the gift icon in the comment title actions.
