### ISSUE TITLE
Don't force me to sign in

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-pull-request-github#4856]
I get this when I open the copilot extension repo- I'm not trying to open a PR or do anything with the PR extension but this dialog keeps popping up and getting in my way. Ideally it wouldn't be a modal dialog at all, unless I am blocked, but I would settle for it only appearing once per session too

<img width="591" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/323878/fd467579-b320-45f6-9f32-26a8369dd692">

**Comment by alexr00** [comment]
I don't think this will be a common occurrence, so I implemented this in the easiest way possible:
- You will get prompted for SAML each time you open the workspace
- If you hit "cancel" then that whole repo will be removed from GHPRI until you reopen or reload the workspace.
