### ISSUE TITLE
Test blue badge on accounts menu

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#4861]
Refs: https://github.com/microsoft/vscode-pull-request-github/issues/4756

- [x] anyOS @eleanorjboyd
- [x] anyOS @aiday-mar

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode-pull-request-github/issues/new?body=Testing+%234861%0A%0A&assignees=alexr00)

---

This feature is behind an experiment that isn't turned on yet. You'll need to opt-in to the experiment for every platform you test on by setting the hidden setting `"githubPullRequests.experimental.accountBadge": true`.

1. On desktop, sign out of GitHub in VS Code.
2. Reload. Make sure you're still signed out of GitHub.
3. Install the pre-release version of the extension.
4. Verify that you see a blue badge on the accounts menu and that GitHub Pull Requests and Issues is listed in the menu when you click on it.
5. Repeat 1-3 on insiders.vscode.dev.
6. Verify that you _don't_ see a blue badge on the accounts menu.

**Comment by aiday-mar** [comment]
Hi, 

I am testing this issue. I signed out of GitHub on desktop and I saw the dialog sign-in with GitHub in editor. When I click on the accounts icon, I see the following menu:

<img width="1298" alt="Screenshot 2023-05-30 at 11 30 10" src="https://github.com/microsoft/vscode-pull-request-github/assets/61460952/95134be5-ed01-4b89-9a0a-53b23f3ca65a">

On one hand I appear to still be signed in with the possibility to sign-out and on the other hand I also see the option to `Sign in with GitHub to use GitHub Pull Requests and Issues`. If I click on sign-out again, then I get the expected account menu.

**Comment by alexr00** [comment]
This is not currently testable as I haven't filled in the TBD yet! There is currently no way to opt in to the experiment to test this.

**Comment by aiday-mar** [comment]
Ah I see! I didn't catch onto that. I'll do the test once it is ready.

**Comment by alexr00** [comment]
This is testable now with the latest pre-release build of the extension.

**Comment by aiday-mar** [comment]
Hi @alexr00, thanks for the heads up. I tested on desktop and it works, I am currently testing on vscode.insiders.dev, and I also see the blue badge (you mentioned it should not appear). Below is a gif of my testing. I have GHPR pre-release installed.

https://github.com/microsoft/vscode-pull-request-github/assets/61460952/87f50fcc-0117-4b8c-88d4-4704691296d1

**Comment by eleanorjboyd** [comment]
seeing the same issue as @aiday-mar on insiders.vscode.dev
