### ISSUE TITLE
Guide users from old "Suggest Edit" command to new suggestion feature

### ISSUE THREAD

**Issue by daniel-montalvo** [microsoft/vscode-pull-request-github#4862]
1. Pick up a PR you want to suggest changes to.
2. Edit a file and add some changes.
3. Press F1 to get to the command palette.
4. Use the "Suggest edits" command to apply your suggestions.
5. Then select "Open on GitHub" to open the PR on GitHub and view the pr "Conversations" tab on the web.

I would expect the suggestions to show up just as if they'd been created using the web interface (attached to the line or lines they belong to). Instead, they appear as a single diff comment.

**Comment by alexr00** [comment]
@daniel-montalvo how are you suggesting edits? If you're doing this from the source control view, then this is the old way and isn't very good. I'll add something that directs you the new way, which properly mirrors the way it's done on GitHub.com:
https://github.com/microsoft/vscode-pull-request-github/blob/main/documentation/changelog/0.58.0/suggest-a-change.gif

**Comment by daniel-montalvo** [comment]
Thanks much @alexr00 
I used the command palette

**Comment by alexr00** [comment]
Looks like there are still a number of users using the old "Suggest Edit" flow. I've added a modal dialog that will show once per machine to let users of that command know that there's a better option. I've also removed the command from the command palette.

**Comment by daniel-montalvo** [comment]
Thanks @alexr00  for your quick action on this.

Slightly unrelated. I've been reviewing the related PR and it seems the documentation for this and other extension features point to images which I've not been able to find the description for. Is there any text that describes these images that are in the documentation folder?

Thanks.

Best.

**Comment by alexr00** [comment]
The images in the documentation folder should all be referenced in the documentation (either in a changelog or in another markdown file). Are you looking for more than that?

**Comment by alexr00** [comment]
To verify:
1. Install the pre-release version of the extension
2. Open a folder that contains a clone of a GitHub repo
3. Check out or create a PR
4. Make a change in a file
5. Open the git SCM view and click on the `...` menu in the "Source control" title. Choose "Suggest Edit"
6. Verify that you see a modal dialog informing you of the better way to suggest changes in a PR.
