### ISSUE TITLE
Create PR view doesn't handle workspace with multiple repos well

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-pull-request-github#4872]
Type: <b>Bug</b>

1. Open the vscode repo
2. Run Create Pull Request command, this brings up the PR creation view
3. File > Add folder to workspace > pick another repo (I chose vscode-docs)
4. :bug: the create PR view goes blank, then displays indefinite progress

Extension version: 0.65.2023053109
VS Code version: Code - Insiders 1.79.0-insider (fa8eefda18bf099d82b58453f8fe5d3010196fa0, 2023-05-31T03:06:45.096Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.59GB (14.94GB free)|
|Process Argv|--crash-reporter-id 74b7cb3c-94df-4c4f-b17a-395ea7723411|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
vstes627:30244334
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
vscrpc:30624061
pythonsymbol12:30651887
showlangstatbar:30737417
pythonms35:30671666
j16hj152:30680472
7ij38806:30687742
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30724385
showsbindicator:30724477
pythongtdpath:30726887
welcomewidgett:30755871

```

</details>

**Comment by alexr00** [comment]
@joyceerhl I think it's just not handling the transition of adding a folder to the workspace when the view is open. If you open the create view after adding the second folder it should work fine.

**Comment by alexr00** [comment]
@mjbvz, to hide the webview view provider I usually just dispose it. It seems like this doesn't work when the extension host is restarted when folders are added to the workspace:
1. Open a folder 
2. command "Create Pull Request"
3. Leave the create view open
4. Add a folder to the workspace.
5. The extension's `deactivate` gets called, and the webview view provider get disposed by the extension
6. At this point I'd expect the view to hide, but it doesn't. Is there something I'm missing here?

**Comment by alexr00** [comment]
@mjbvz any ideas on https://github.com/microsoft/vscode-pull-request-github/issues/4872#issuecomment-1573555380?

**Comment by mjbvz** [comment]
@alexr00 Can you please open an issue on the main VS Code repo

**Comment by alexr00** [comment]
Created https://github.com/microsoft/vscode/issues/188257
