### ISSUE TITLE
PR description node has Checkout default branch in context menu

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-pull-request-github#4873]
Context menu for PR item: 
<img width="463" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/30305945/a0b56661-14d8-475a-9ea9-5c28d2412f2d">

Context menu for description node under PR item:
<img width="581" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/30305945/860f40b5-e233-4c64-881f-c5e1779c4ff6">

**Comment by bhavyaus** [comment]
Changes are not in insiders yet.
