### ISSUE TITLE
User hover shows null when writing the @username

### ISSUE THREAD

**Issue by SKPG-Tech** [microsoft/vscode-pull-request-github#4891]
When writing the username of someone that doesn't have a name, just a username, the user hover will show null in place of the name.
![image](https://github.com/microsoft/vscode-pull-request-github/assets/42890752/95d01fbd-c2da-44ed-a56d-e0ef397e13f8)

I happen to look at the code and notice that in the `userHoverProvider` it doesn't show the hover if the user doesn't have a name, maybe it could still show the hover just replace the null with a space
https://github.com/microsoft/vscode-pull-request-github/blob/8396110f2812b3fa040c977d0b227a4f4b3c8fc4/src/issues/userHoverProvider.ts#L62

**Comment by meganrogge** [comment]
verified via code review
