### ISSUE TITLE
Why does clicking some files open on a comment and some not?

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-pull-request-github#49]
PR: https://github.com/xtermjs/xterm.js/pull/1460

Clicking the top file will open the file at the top, clicking the bottom one will open at the first comment.

![image](https://user-images.githubusercontent.com/2193314/41948346-1b756328-7971-11e8-9491-4a27e08ab10e.png)

I'm guessing it's since the second one has a comment but this feels weird. I read the comment earlier so I don't want to skip a bunch of lines in the diff every time I look at the file again.

**Comment by rebornix** [comment]
Diff editor will try to scroll to the first diff hunk, when there are comments in the first diff hunk, you have the feeling that it scrolls to the comments ;)

We are going to introduce a command for comment navigation, which allows us to navigate to the first comment in the editor.

**Comment by Tyriar** [comment]
> you have the feeling that it scrolls to the comments

This wasn't the case though, it was very inconsistent whether it would scroll to the comments or not. I later opened another one which had replies to me and it didn't scroll.
