### ISSUE TITLE
Pull request description code block syntax highlighting

### ISSUE THREAD

**Issue by Dan503** [microsoft/vscode-pull-request-github#490]
A big feature of this project is that it allows you to review a pull request with the syntax highlighting of your favourite VS-Code theme.

However when you view code blocks in the Pull Request description they are completely void of any syntax highlighting:

![pull-request-description-code-block](https://user-images.githubusercontent.com/10610368/45616151-f1974300-bab1-11e8-80ad-22f31b6d9004.png)

It shouldn't be too hard to apply the users preferred syntax highlighting to pull request description code blocks if the language is known.

**Comment by alexr00** [comment]
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/54
