### ISSUE TITLE
Provide a comment preview button on the description page

### ISSUE THREAD

**Issue by Dan503** [microsoft/vscode-pull-request-github#492]
On GitHub there is a Preview button that lets you view your message in it's fully formatted form before sending.

![github-preview-button](https://user-images.githubusercontent.com/10610368/45617561-0f66a700-bab6-11e8-8fc3-4d686f77fb84.png)

There is currently no Preview button in the VS Code extension. This makes it more difficult to review what you have written before submitting your comment.

**Comment by alexr00** [comment]
Closing, as we have no plans to address this feature request. For the full description experience, github.com is always going to have more features :).
