### ISSUE TITLE
GH user showed up in intellisense after "@param "

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#4925]
Reproduced twice in a row, probably a race condition when you type fast?

![image](https://github.com/microsoft/vscode-pull-request-github/assets/2193314/e721e42a-f9ed-4ff9-b4f8-ca11a42ed347)

v0.67.2023061509
Pre-Release

Version: 1.80.0-insider (user setup)
Commit: 61ba389b0a7108af0411c73ab30c7e4350051645
Date: 2023-06-16T09:46:56.229Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by alexr00** [comment]
As far as I can tell, I can't remove the suggestion after it has been made.

**Comment by alexr00** [comment]
@jrieken, should the suggestions be cleared when `space` is typed? I only see my completion provider called once when the `@` is typed.
