### ISSUE TITLE
Support VS Code for MacOS

### ISSUE THREAD

**Issue by PKPublicCode** [microsoft/vscode-pull-request-github#4929]
I installed extension on VS Code MacOS, and can't find any traces of this extension. Meaning I can't find any UI elements related to pull requests, and so can't use any of mentionend features.
If MacOS is not supported, then it would be nice to have it.
If it's supported, but extension has MacOS specific UI experience, then Getting Started documentation should be updated accordingly.

**Comment by alexr00** [comment]
The extension is supported. You need to install it from the VS Code Extension Marketplace.
