### ISSUE TITLE
There was an error creating the pull request: GraphQL error: ["Pull request Pull request is in unstable status"]

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-pull-request-github#4938]
1. Created this PR using GHPRI on VS Code desktop https://github.com/microsoft/vscode/pull/185810
2. :bug: saw this error message which I haven't seen before:

<img width="424" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/30305945/10b2c81e-dc1b-4915-b9d1-f024f9d19c4f">

**Comment by alexr00** [comment]
I haven't seen that one either. It's coming directly from the GitHub GraphQL API. Do you have debug level output from this? It seems likely that setting labels, setting auto merge, or setting an assignee failed.

**Comment by joyceerhl** [comment]
I did not have debug level output turned on when this happened unfortunately. If it happens again I will update this issue with the logs.

**Comment by alexr00** [comment]
Thanks! I can add a check for this when setting labels, auto merge, and assignees, and then retry after 5 seconds if it occurs, but it would be better to know for sure that that's where it's coming from.

**Comment by lramos15** [comment]
How should I verify this if it's an issue that only occurs on occasion

**Comment by alexr00** [comment]
Let's call this "verified by silence". I haven't gotten another report about it.
