### ISSUE TITLE
GraplQL error: must be a collaborator 

### ISSUE THREAD

**Issue by ttduyk13** [microsoft/vscode-pull-request-github#4950]
- Extension version: v0.66.1
- VSCode Version: 1.79.2
- OS: windows 11

Steps to Reproduce:

1. Open Github Pull Request
2. Press create

![image](https://github.com/microsoft/vscode-pull-request-github/assets/115893846/840eaeba-bf8e-417d-a69a-b722a8886c2c)

**Comment by alexr00** [comment]
@ttduyk13 do you have permission to create pull requests in that repo?
