### ISSUE TITLE
Progress feedback on PR description actions

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#4954]
For example, when you change the automerge state we should show some progress then show the updated value. This is how github.com does it:

![chrome_a9OpnVnu1i](https://github.com/microsoft/vscode-pull-request-github/assets/38270282/6d86504d-abd9-4211-8fa0-db618d7bc80b)

**Comment by alexr00** [comment]
New behavior:
![Recording 2023-08-28 at 16 09 13](https://github.com/microsoft/vscode-pull-request-github/assets/38270282/80dffd8b-e840-417d-b359-d91a96b3e5f1)

**Comment by meganrogge** [comment]
@alexr00 i'm not seeing that... on version `v0.71.2023082809`
https://github.com/microsoft/vscode-pull-request-github/assets/29464607/7217959a-e2e9-4ccb-af00-c1ab822fc40f

**Comment by alexr00** [comment]
`v0.71.2023082809` is from yesterday, you'll need today's build for the change.

**Comment by alexr00** [comment]
Looks like today's build failed. Looking...
