### ISSUE TITLE
Images Not Displaying Correctly In Comments

### ISSUE THREAD

**Issue by scrossan-crown** [microsoft/vscode-pull-request-github#496]
- Extension version: 0.1.5
- VSCode Version:
```
1.27.2
f46c4c469d6e6d8c46f268d1553c5dc4b475840f
x64
```
- OS: Windows 10

Steps to Reproduce:

1. Image in pr comment. It doesn't display correctly 
![image](https://user-images.githubusercontent.com/30405149/45630615-f1d31680-ba90-11e8-81ff-be157143f2ff.png)

**Comment by scrossan-crown** [comment]
Strangely after a second refresh of the pr it's now displaying the images perfectly
![image](https://user-images.githubusercontent.com/30405149/45631864-d289b880-ba93-11e8-9bc2-37099c33c920.png)

**Comment by alexr00** [comment]
Can no long repro this issue.
