### ISSUE TITLE
Remote "microsoft" seems redundant

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-pull-request-github#4965]
Testing #4961

In this example I would not have expected to see the remote:

![image](https://github.com/microsoft/vscode-pull-request-github/assets/900690/7dd38bf1-6981-4cec-bdab-06f7beb8b8f1)

**Comment by alexr00** [comment]
If you only have 1 remote, you would like the remote to be hidden?

**Comment by bpasero** [comment]
Yes ✅

**Comment by hbons** [comment]
Seems like a good idea. I do think we should only hide the repository part when there is only one remote like Alex says, but not when just comparing inside a single fork when there are multiple remotes.

**Comment by alexr00** [comment]
Fixed by bfc07690e0072a0286a36dbd04ea3126834c4386
