### ISSUE TITLE
Telemetry setting isn't namespaced

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode-pull-request-github#497]
Noticed that the setting we have to opt out from telemetry isn't namespaced, which makes it look like a built-in setting in VS Code.

<img width="477" alt="screen shot 2018-09-17 at 2 47 25 pm" src="https://user-images.githubusercontent.com/173559/45652308-0d3a2380-ba89-11e8-819a-47946572c968.png">

I suggest renaming it to `"github.pullrequests.telemetry.optout": true`

**Comment by wyze** [comment]
I did the fix that adds the namespace, but would you like some sort of migration to check if they have the old setting and migrate their setting to the new one?
