### ISSUE TITLE
PR title won't auto fill from last commit

### ISSUE THREAD

**Issue by AmirHosseinKarimi** [microsoft/vscode-pull-request-github#4970]
Unlike #4701, I want GHPR auto fill  PR title from last commit. When there is more than 1 commit ahead of destination branch it will auto fill title from last commit. But it won't auto fill when there is only one commit to add in PR!

- Extension version: 0.66.1
- VSCode Version: 1.79.2
- OS: Manjaro

Steps to Reproduce:

1. Click on create new PR
2. Change destination branch which is 1 commit behind from source branch

**Comment by alexr00** [comment]
I'm having trouble reproducing this issue. Is there a step that I'm missing?
1. Checkout the default branch of my repo.
2. Checkout the n-1 commit from that branch
3. `git checkout -b main2` , `git push`
4. `git checkout -b alexr00/mergeIntoMain2`
5. Make a change and commit
6. "Create Pull Request"
7. Change the into branch to `main2`

**Comment by AmirHosseinKarimi** [comment]
Looks like it works now. I close this issue and reopen it when it happened again. Thanks.

**Comment by AmirHosseinKarimi** [comment]
Hi again. Looks like there is a situation where the plugin fills the PR title, otherwise it doesn't.
But, I can't understand what is it!

Can you tell me how it works?
