### ISSUE TITLE
Reply to Comment Not Displaying

### ISSUE THREAD

**Issue by scrossan-crown** [Microsoft/vscode-pull-request-github#498]
- Extension version: 0.1.5
- VSCode Version:
```
1.27.2
f46c4c469d6e6d8c46f268d1553c5dc4b475840f
x64
```
- OS: Windows 10
Steps to Reproduce:

1. A reply has been added to my comment and it's not showing on in vscode.

![image](https://user-images.githubusercontent.com/30405149/45683273-f6eca000-bb3a-11e8-9e09-ae29bc65d4e8.png)

I've tired refreshing the pull request list and checking out another branch, then re-checking this one out and closing the editor and re-opening it.

![image](https://user-images.githubusercontent.com/30405149/45683380-577bdd00-bb3b-11e8-9354-12d62af88c6b.png)

**Comment by RMacfarlane** [comment]
@scrossan-crown With the change I just made, using the "Refresh Pull Request" action from right clicking on a PR in the tree should make the reply show up. When refreshing the entire list, the reply should show up after closing and re-opening the editor
