### ISSUE TITLE
Missing UI feedback, checkout action clickable multiple times

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode-pull-request-github#4980]
Testing microsoft/vscode#186170

When clicking on "Check out" you can actually keep clicking, as the hover does not disappear immediately and there is no direct UI feedback:

![Code_-_Insiders_Cm2kR95kK1](https://github.com/microsoft/vscode/assets/2931520/c40f459e-3534-4822-a1f3-8f966cc047dc)

I suggest to hide the hover immediately on click and to make sure the notification that checking out is in progress shows quicker (without delay).

**Comment by alexr00** [comment]
Fixed by https://github.com/microsoft/vscode-pull-request-github/pull/4981

**Comment by sandy081** [comment]
Waiting for new insiders to verify

**Comment by alexr00** [comment]
The new pre-release version of the extension is available for verifcation now!
