### ISSUE TITLE
File gets duplicated in PR tree view

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode-pull-request-github#4982]
Follow up from #4323 I noticed that the files get duplicated... my guess is that this happens when the PR refreshes automatically and you have a tonnnnn of comments.

![image](https://github.com/microsoft/vscode-pull-request-github/assets/2644648/ce2910a3-e011-496a-bb79-859cdf56ad5d)

Hitting the refresh button in the PR view makes it go back to normal

**Comment by alexr00** [comment]
I want to understand what's going on here, but I can't repo. Do you recall if this happened as you were making all the comments?

**Comment by TylerLeonhardt** [comment]
I can't seem to repro either. I'll close this until I see it again.
