### ISSUE TITLE
(JS/TS) Incorrect Information when hovering over a modified variable in a PR

### ISSUE THREAD

**Issue by pmanal1** [microsoft/vscode-pull-request-github#4983]
- Extension version: v0.64.0
- VSCode Version: 1.79
- OS: Ventura 13.4

Steps to Reproduce:

1. Go to a Pull Request and find lines that have been modified, added, or removed in the modified file.
2. Hover over any variable to get more information about the variable.
3. The information provided over the hovered variable and the hovered variable itself do not match.

I'm currently working with TypeScript files, some of which are utilizing the Angular framework.

**Comment by alexr00** [comment]
This is a bug with VS Code's built in JS extension: https://github.com/microsoft/vscode/issues/185854
