### ISSUE TITLE
create new releases

### ISSUE THREAD

**Issue by Vincenzoferrara** [microsoft/vscode-pull-request-github#4989]
hello in reolata and a question but I did not know where to write it.
I would like to create the release with the command "dotnet publish" is it possible? or some alternative

**Comment by alexr00** [comment]
This doesn't seem like a question about this extension.

**Comment by Vincenzoferrara** [comment]
actually i would like an option to load on "relase" and create the actual tag, with the name of the release.
 if the "dontnet publish" command is used, a request to create the new version in github should come out if possible
