### ISSUE TITLE
Commented icon not displaying / Comments not displaying

### ISSUE THREAD

**Issue by scrossan-crown** [microsoft/vscode-pull-request-github#499]
- Extension version: 0.1.5
- VSCode Version:
```
1.27.2
f46c4c469d6e6d8c46f268d1553c5dc4b475840f
x64
```
- OS: Windows 10

Steps to Reproduce:

1. Add a comment and refresh the list and commented icon isn't displayed

![image](https://user-images.githubusercontent.com/30405149/45684769-42a14880-bb3f-11e8-9309-95811aaffa9b.png)

2. Missing comments added to a file

Comment shown on github.
![image](https://user-images.githubusercontent.com/30405149/45684643-dfafb180-bb3e-11e8-8351-79ce50e943fc.png)

No comments in vscode. I've tried closing vscode, checking out another branch and refreshing pr list.
![image](https://user-images.githubusercontent.com/30405149/45684693-fe15ad00-bb3e-11e8-9f54-9a479ac7ee53.png)

**Comment by RMacfarlane** [comment]
For 2, did you add the comment within vscode, or on github?

**Comment by scrossan-crown** [comment]
I added my comment within vscode. It was happening on a lot of files by the time I had reviewed the pr. Also when closing vscode and re-opening it the some files didn’t have any comments at all that I’d previously added, but  I could still view the comments on github.

Scott Crossan
Developer
t: 01617621819
s.crossan@crownoil.co.uk<mailto:s.crossan@crownoil.co.uk>
www.crownoil.co.uk<http://www.crownoil.co.uk/>

[Description: cid:BBDC52DE-BFB3-4947-AEC4-D900A598E80F]

**Comment by rebornix** [comment]
@scrossan-crown can you share more about the pull request or repository? Is the pull request containing many file changes?

**Comment by scrossan-crown** [comment]
It was a pull request with a lot of files changes. I've updates to 0.17 and when I have another large pr I'll see if it's still an issue

**Comment by rajatkantinandi** [comment]
I'm also seeing missing comments when the PR is large & has many files.
Some of the files have comments & after a certain number of files in the list any other file is just showing my comments & any comment by a co-worker is missing.
I can't post a screenshot as it is a private repo.

**Comment by alexr00** [comment]
We've had a lot of changes and improvements since this issue was last seen. Please feel free to comment in this issue if you're still seeing it, but for now I will close the issue.

**Comment by sallyjdevitry** [comment]
I am still having this issue. I'm on version 0.27.0. My supervisor showed me that they have commented on my PR code, but the comments do not appear on my end.
