### ISSUE TITLE
Changes in pull request explorer seems redundant

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#50]
I didn't even notice it was there, I think you can do everything in the GitHub Pull Requests explorer already.

**Comment by Tyriar** [comment]
Also you open a pull request by right clicking and opening it, doing this will already expand the node.

**Comment by RMacfarlane** [comment]
Closing this, as I don't think we will remove this view. Having it be it's own view is useful if you're returning to a PR when reloading VS Code and also for the new focused mode
