### ISSUE TITLE
[Accessibility] Pressing Ctrl+S does not create an GitHub issue or PR

### ISSUE THREAD

**Issue by jooyoungseo** [microsoft/vscode-pull-request-github#5006]
Type: <b>Bug</b>

When creating an GitHub issue or PR in VSCode, the button says Ctrl+S to create an issue, but the accelerator key does not work when tested on Windows. Interestingly, the key works as expected when used in the Chrome browser in github.dev.

Extension version: 0.66.2
VS Code version: Code - Insiders 1.80.0-insider (660393deaaa6d1996740ff4880f1bad43768c814, 2023-07-04T10:57:02.727Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz (8 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.71GB (6.18GB free)|
|Process Argv|--crash-reporter-id b05b88e5-8894-4031-ae34-fa034ebddea9|
|Screen Reader|yes|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
py29gd2263:30776702
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
pythonsymbol12:30651887
a9j8j154:30646983
showlangstatbar:30737417
pythonms35:30671666
ecj1e332:30687743
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30771523
hideindicator:30766887
pythongtdpath:30726887
bgfeh915:30780428
gsofa:30778558
pythonnosmt12:30779711
pythonidxpt:30768918
pythondjangots:30768917
pythonnoceb:30776497
copilotsettingt:30767686
e537b577:30772214
h0f32768:30779712
synctok:30776453
dsvsc013:30777762
dsvsc014:30777825

```

</details>

**Comment by jooyoungseo** [comment]
No, I don't see that in my keybindings.json

**Comment by alexr00** [comment]
Thanks @jooyoungseo. Can you try the following:
1. Run the command "Developer: Toggle Keyboard Shortcuts Troubleshooting"
2. Reproduce the issue
3. Share the output that was shown for the keyboard shortcuts troubleshooting.

**Comment by alexr00** [comment]
Thanks @jooyoungseo! I just saw this in your original post:

> When creating an GitHub issue or PR in VSCode

Are you trying to create an issue or a PR? `ctrl+s` only works for issues. For PRs, we use `ctrl+enter`.

**Comment by alexr00** [comment]
On github.dev, auto save is enabled by default. Since it is a web editor we felt that it made sense to auto save as most people expect things to automatically save on the web.

**Comment by jooyoungseo** [comment]
I see. I now understand this thanks to your kind explanation, but other keyboard-only users, such as screen reader users, may get confused by this different behavior.
