### ISSUE TITLE
Buffer is not defined when adding labels

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode-pull-request-github#5009]
- Extension version: v0.68.0
- VSCode Version: Insiders (2 days ago)
- OS: github.dev

Steps to Reproduce:

1. Create a PR in microsoft/vscode-jupyter
2. Press the label button to try and add a label after creating the PR
3. :bug: A notification shows up with the error "Buffer is not defined"

**Comment by alexr00** [comment]
To verify:
1. Open a GitHub repo on insiders.vscode.dev
2. Make sure you have the latest pre-release version of the extension
3. Open a PR description
4. Add a label to it

**Comment by alexr00** [comment]
Everyone who tries to verify this is hitting https://github.com/microsoft/vscode/issues/187722. However, I don't hit that issue and I verified it, so we're going to call this verified.
