### ISSUE TITLE
No authorization prompt, GH PR never shown in the Git Viewlet

### ISSUE THREAD

**Issue by agonzalezjr** [Microsoft/vscode-pull-request-github#502]
- Extension version: 0.1.5
- VSCode Version: 1.27.2
- OS: Mac OS X 10.13.4

Steps to Reproduce:

1. Using GH Enterprise
2. Host settings is set correctly
3. Go to the Git Viewlet, the GH PR section is not there:

![screen shot 2018-09-18 at 4 23 19 pm](https://user-images.githubusercontent.com/8965941/45714322-404ee680-bb5f-11e8-96f8-d2d69db900f5.png)

There aren't any "Sign In" commands in the Commands Palette either.

Here is what's in the GH PR log:
```
Looking for git repository
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
Git repository found, initializing review manager and pr tree view.
> git config --local --get branch.master.github-pr-owner-number
Review> no matching pull request metadata found for current branch master
> git config --local --get branch.master.github-pr-owner-number
...
```

**Comment by RMacfarlane** [comment]
What's the output of `git remote -v` in that repository? The tree view is only shown when there are remotes pointing to GitHub

**Comment by agonzalezjr** [comment]
Hi @RMacfarlane , here is the output of that:

```
$ git remote -v 
origin	https://github.<$myenterprise>.corp/<$myorg>/<$myrepo>.git (fetch)
origin	https://github.<$myenterprise>.corp/<$myorg>/<$myrepo>.git (push)
```

**Comment by appscfid** [comment]
I have the same issue, no sign in authentication. Output of command is:

> $ git remote -v
> origin  https://github01.<$myenterprise>.com/<$myorg>/<$myrepo>.git (fetch)
> origin  https://github01.<$myenterprise>.com/<$myorg>/<$myrepo>.git (push)

**Comment by RMacfarlane** [comment]
Thanks for the additional details, this should be fixed by https://github.com/Microsoft/vscode-pull-request-github/commit/51b6355aac949522ff418b9089d412d174420be1. Just published a new version of the extension with the change. Let me know if you still see any issues with it!
