### ISSUE TITLE
GHPRI shows error message on activation if git is not installed

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-pull-request-github#5021]
1. Be setting up VS Code on a new machine that doesn't have git yet
2. Have GHPRI synced to settings sync
3. Turn on settings sync
4. GHPRI is installed, activates, and immediately shows an error message 

IMHO we should show an info message and/or welcome views instead of an error message, which feels overly aggressive.

**Comment by alexr00** [comment]
<img width="304" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/38270282/14c8f7f1-7e1e-4cf0-a944-43d8cfd57a2a">
