### ISSUE TITLE
New PR View: Wrong checkbox state

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-pull-request-github#5026]
1. Create a new Draft PR
2. Create another PR

The button will show `Create Draft` but 🐛  the checkbox will reflect the wrong state:

<img width="304" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/22350/f250da7e-e3c1-44f5-94c1-1cae52ae11dc">

**Comment by alexr00** [comment]
Fixed by https://github.com/microsoft/vscode-pull-request-github/pull/5042
