### ISSUE TITLE
New PR View: Merge Method button is too nuanced

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-pull-request-github#5027]
I find this button to be very minimalistic:

<img width="271" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/22350/072f7dbc-78ac-464e-bac6-ab264609b9d0">

I argue that it shouldn't even be a button at all, since it's a "choice UX", not an "action UX".

**Comment by alexr00** [comment]
I am going to remove this menu and instead put all merge options in the "Create" button.
