### ISSUE TITLE
New PR View: Improve disabled state of controls

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-pull-request-github#5028]
The view's disabled state should be more dramatic:

- The input boxes should have a more _fading out_ style, not just the placeholder text
- The branch pickers should not react on mouse hover
- The `Cancel` button should be disabled

<img width="1149" alt="Screenshot 2023-07-10 at 15 02 52" src="https://github.com/microsoft/vscode-pull-request-github/assets/22350/03a8e9be-302f-4ecc-94b3-c8125bb8e345">

**Comment by alexr00** [comment]
It is still a valid action to cancel even when the view is loading. I can disable it, but I am not sure it is needed.

**Comment by joaomoreno** [comment]
Agreed!

**Comment by mjbvz** [comment]
In v0.69.2023072609, I noticed that the branch pickers still react on hover while loading. Clicking on them has no effect

Also should the assignee, label, and other title buttons be disabled while the view is loading? Clicking on them doesn't seem to have any effect

**Comment by alexr00** [comment]
Getting the assignee, label, and other title buttons in sync is going to be imperfect. It's enough that they do nothing. The branch picker buttons need to be fixed though.
