### ISSUE TITLE
New PR View: Split button appears to be triggering a create

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode-pull-request-github#5029]
I opened the split button to try and decide if I wanted a draft or auto merge before finishing my PR description, but it appears that clicking the option triggers the create which is a downside compared to the checkboxes. For example, I went back to the view just to play around with it when I already have a PR made and I get a notification saying `PR Successfully Created` before it failing saying the PR already exists. Why does it tell me it was successfully created then 🤔.

**Comment by alexr00** [comment]
> I opened the split button to try and decide if I wanted a draft or auto merge before finishing my PR description, but it appears that clicking the option triggers the create which is a downside compared to the checkboxes. 

This is a feature 😁. It is intended to reduce the number of clicks.

> For example, I went back to the view just to play around with it when I already have a PR made and I get a notification saying PR Successfully Created before it failing saying the PR already exists. Why does it tell me it was successfully created then 🤔.

This is a bug.
