### ISSUE TITLE
Automatically collapse comments once they are resolved

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-pull-request-github#5031]
1. Have an unresolved comment on a pull request that is open in VS Code
2. Click 'Resolve Conversation'
3. Comment remains open, I still have to manually click collapse

I'd expect that resolving a comment also collapses the comment so that it no longer takes up space, which is what happens on github.com

**Comment by alexr00** [comment]
This is going to need VS Code API to enable collapsing a comment. Just like the tree view, the comment thread collapsible state cannot be modified by the extension once set to prevent conflict between user state and extension state.

**Comment by alexr00** [comment]
The setting to control this is `comments.collapseOnResolve`. It is `true` by default.

**Comment by alexr00** [comment]
To verify:
1. Install GitHub Pull Requests and Issues
2. Open a PR file and leave a comment
3. Resolve the comment
4. Verify that the comment immediately closes
5. Unresolve the comment
6. Set `"comments.collapseOnResolve": false`
7. Resolve the comment again
8. Verify that the comment is not closed.

**Comment by meganrogge** [comment]
🎉 works well! such a great feature, thank you
