### ISSUE TITLE
Bug: latest version broke comments

### ISSUE THREAD

**Issue by roi007leaf** [microsoft/vscode-pull-request-github#5034]
- Extension version: latest
- VSCode Version: latest
- OS: windows 11

Steps to Reproduce:

1. open vscode
2. make sure a PR is selected
3. go to comments tab
4. no comments

when using 1 version before latest comments are shown

**Comment by alexr00** [comment]
Are you using GitHub Enterprise? If so, you're hitting https://github.com/microsoft/vscode-pull-request-github/issues/4995. A new version with the fix will be available later today.
