### ISSUE TITLE
Our team is unable to see few branches while publishing. 

### ISSUE THREAD

**Issue by Preety-kumari-aligntech** [microsoft/vscode-pull-request-github#5044]
- Extension version:
- VSCode Version:
- OS:

Steps to Reproduce:

1.
2.

**Comment by alexr00** [comment]
Should be fixed in the new Create PR view, which I will enable by default on Monday.

**Comment by alexr00** [comment]
I was a day late updating this. The new create view is now in the latest insiders (from today).

**Comment by Preety-kumari-aligntech** [comment]
Still same issue @alexr00

**Comment by alexr00** [comment]
@Preety-kumari-aligntech can you share a screenshot of where you're seeing this problem?

**Comment by Preety-kumari-aligntech** [comment]
![branchesnotvisible](https://github.com/microsoft/vscode-pull-request-github/assets/132752331/1b622106-3719-47a6-95fa-dda0de35c550)
If you seen in the screen short after branches names which start with p it ios not showing other branches.

**Comment by alexr00** [comment]
@Preety-kumari-aligntech can you please try out the [pre-release build](https://github.com/microsoft/vscode-pull-request-github/wiki/Pre-release-Build) where I think this is fixed?

**Comment by Preety-kumari-aligntech** [comment]
I have tried above fix but no luck.

**Comment by Preety-kumari-aligntech** [comment]
Hi @alexr00  could help us  on this.

**Comment by alexr00** [comment]
Did you try out the pre-release build with VS Code insiders?

**Comment by Preety-kumari-aligntech** [comment]
Yes @alexr00 yes, I have tried pre-release build but no luck. Please help on this.

**Comment by alexr00** [comment]
@Preety-kumari-aligntech can you please share a new screenshot with the pre-release build?

**Comment by SRIDIVYAACHUTHA** [comment]
Hi @alexr00 , As preety is on leave for next week, i'm dealing this ticket for now.

so, alex we have tried with the pre - release build, please find the below screenshots and we are having 1300+ branches in our repo, we are thinking if this might be the issue, can you investigate this also.

<img width="1321" alt="Screenshot 2023-07-28 at 6 09 15 PM" src="https://github.com/microsoft/vscode-pull-request-github/assets/95206702/b9c25bc7-7ac0-4882-94eb-b0a9b4fb0eae">
<img width="1792" alt="Screenshot 2023-07-28 at 6 12 20 PM" src="https://github.com/microsoft/vscode-pull-request-github/assets/95206702/44f8b07b-66e3-43ba-a945-b25cf0f3d071">

**Comment by SRIDIVYAACHUTHA** [comment]
Hi @alexr00 , we have tried, the vscode insider with the latest pre- release version, but we are facing the same issue, Adding a screenshot here, please check.

<img width="1792" alt="Screenshot 2023-08-02 at 1 54 27 PM" src="https://github.com/microsoft/vscode-pull-request-github/assets/95206702/6a93ef34-39af-41bd-bc18-98230eaa8b37">

**Comment by alexr00** [comment]
Thanks for confirming with pre-release! We try to page in all branches, but if it takes too long we time out and we log that we couldn't fetch all branches. Can you please share the output of GitHub Pull Request so I can see if the timeout was hit?

**Comment by Preety-kumari-aligntech** [comment]
Hi @alexr00 
any update?

**Comment by alexr00** [comment]
We try to page in all branches, but if it takes too long we time out and we log that we couldn't fetch all branches. Can you please share the output of GitHub Pull Request so I can see if the timeout was hit?
