### ISSUE TITLE
Create dropdown hard to read on Light Modern theme

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode-pull-request-github#5052]
<img width="377" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/31675041/62d4fccb-1f78-47e0-a4d0-8ad391df51e6">

This is on the pull request creation view with the `Light Modern` theme. I'm on `v0.69.2023071212` pre-release.

**Comment by hbons** [comment]
It looks like the custom styling that we set on the <select> element is also being applied to the <options> within it.

**Comment by hbons** [comment]
This was fixed by #5085.
