### ISSUE TITLE
Create button dropdown wraps disconcertingly while creating PR 

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-pull-request-github#5053]
1. Create a PR using GHPRI's new create PR view
2. :bug: While creating, the dropdown wraps to a newline 
<img width="281" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/30305945/1f8e1ffa-bdbb-4603-8645-23e073e7ee12">

**Comment by hbons** [comment]
@alexr00 let's make this button always say 'Create' to be more consistent with other multi-action buttons in the product?

**Comment by joyceerhl** [comment]
Actually the SCM commit action button does not always say Create, it just does a `text-overflow: ellipses` 
![image](https://github.com/microsoft/vscode-pull-request-github/assets/30305945/2ed68dc5-f3b0-424c-b978-07507ad6d221)

**Comment by alexr00** [comment]
I would like to keep the long title so you know exactly what you are doing when you press that button (and it is consistent with the Commit button).

**Comment by hbons** [comment]
@alexr00 I see. Fixes in #5057 and #5054.
