### ISSUE TITLE
Update docs for Github Enterprise support

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode-pull-request-github#506]
Update docs for Github Enterprise support.
- steps to enable
- required GH Enterprise version,
- links to existing docs

**Comment by shana** [comment]
The versions of GHE that support sign in are:

2.14.5 and above
2.13.11 and higher 2.13.x
2.12.19 and higher 2.12.x
2.11.25

Other versions will need a personal access token configured with the scopes read:user, repo, user:email, write:discussion. Looks like there are a few enterprise versions that don't have the write:discussion scope available, so I think I'll need to do something about that (the scope is not absolutely essential so it's not a hard requirement).

**Comment by shana** [comment]
@ryanspletzer I've opened issue #512 to track your problem with some questions.

**Comment by cederfjard** [comment]
> The versions of GHE that support sign in are:
> 
> * 2.14.5 and above
> * 2.13.11 and higher 2.13.x
> * 2.12.19 and higher 2.12.x
> * 2.11.25
> 
> Other versions will need a personal access token configured with the scopes read:user, repo, user:email, write:discussion. Looks like there are a few enterprise versions that don't have the write:discussion scope available, so I think I'll need to do something about that (the scope is not absolutely essential so it's not a hard requirement).

So just to clarify: We're on version 2.12.13, and there's no write:discussion scope when I generate access tokens. This is probably the reason that I can't sign in, then? (Also see here: https://github.com/Microsoft/vscode-pull-request-github/issues/382#issuecomment-420639536)

**Comment by shana** [comment]
@cederfjard The latest release (0.1.6) has a fix for the problematic scopes, so you should be able to login to GHE 2.12.13 with a personal access token now.

**Comment by maurofranchi** [comment]
What permission do we need to grant to the token for GitEnterprise v2.13.4?

**Comment by shana** [comment]
@maurofranchi `read:user`, `repo` and `user:email`

**Comment by maurofranchi** [comment]
@shana thanks it worked!!

**Comment by shana** [comment]
The docs have been updated with all the information gathered here, https://github.com/Microsoft/vscode-pull-request-github/wiki#2-is-github-enterprise-supported

**Comment by auchenberg** [comment]
🎉
