### ISSUE TITLE
Pull Request UI: Missing Hover / No Action On Click

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode-pull-request-github#5074]
![Code_-_Insiders_4VM2ZEecFP](https://github.com/microsoft/vscode/assets/2931520/8b7e069f-402c-4fa2-95a4-5515e87f4b36)

**Comment by hediet** [comment]
While there is an action on click, I think the hover could say what it means or what would happen when I click on it.
Maybe "Change reviewers" would do it.

Showing a hover just for the icon is confusing, as it is unrelated to the click action:

![Code_-_Insiders_ZFTzErhX5q](https://github.com/microsoft/vscode-pull-request-github/assets/2931520/148b48df-0049-47dd-8155-1cf948b7bf4d)

**Comment by alexr00** [comment]
Icon alignment will be fixed by https://github.com/microsoft/vscode-pull-request-github/pull/5101, as will the not helpful hover for the icon.

**Comment by hbons** [comment]
Fixes have been merged.
