### ISSUE TITLE
Update settings to reflect new Create PR view

### ISSUE THREAD

**Issue by hbons** [microsoft/vscode-pull-request-github#5081]
I went through the settings and found some options that no longer make sense. We could merge them into one like this:

<img width="755" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/103326/4edc1ec4-b4b9-42c5-a188-6819e8edce5c">

If `Default Merge Method` is independently used in the PR overview we can keep that one.

**Comment by hbons** [comment]
We should probably add "if available" to the description as this will depend on the repository.

**Comment by alexr00** [comment]
The new setting is `githubPullRequests.defaultCreateOption`. To verify, please check:
- That each setting value is respected (dependent on what is actually available in the repo).
- That the setting name, description, and value descriptions make sense.
