### ISSUE TITLE
Prevent pull request and comments panel from showing after creating a PR

### ISSUE THREAD

**Issue by dtwilliamsWork** [microsoft/vscode-pull-request-github#5083]
After creating a PR within VSCode, the Pull Request and Comments panel always appears and it's annoying having to close them every time.

Could we have an option to disable these from showing?

**Comment by alexr00** [comment]
`"githubPullRequests.postCreate": "none"` might do what you want. Could you try it out and see if it works for you?

**Comment by alexr00** [comment]
I thought you meant the Comments view, but we don't open that. Do you mean this thing?

<img width="308" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/38270282/48c55bf6-d4ac-478f-9de4-20746b20713f">

**Comment by dtwilliamsWork** [comment]
no this panel

<img width="1212" alt="Screenshot 2023-07-21 at 14 42 04" src="https://github.com/microsoft/vscode-pull-request-github/assets/23117123/a0376670-e78f-4241-837e-6377438eb44c">

**Comment by alexr00** [comment]
Ah that view opens itself when a file with commenting is opened. You can use this setting to disable it: `"comments.openView": "never"`

**Comment by dtwilliamsWork** [comment]
great, thanks for your help
