### ISSUE TITLE
PR Reviewers get removed when new added

### ISSUE THREAD

**Issue by tymik** [microsoft/vscode-pull-request-github#5084]
I have repositories with CODEOWNERS for automatic assigning of the reviewers on a group basis.
Sometimes I need to alter the people assigned adding some additional people.
Every time I do it from this extension, on the page that opens as a tab in my VSCode, I get people originally assigned removed from the reviewers.
They are checked when the list opens, I check another person and eventually only that person is in the list of reviewers, prior reviewers are removed.
Moments ago I tried to be smart and I unchecked then checked back original assigners, but they still got removed and I had only 1 reviewer assigned after the operation - the new one that was supposed to be additional reviewer.

- Extension version: v0.66.2
- VSCode Version: 1.79.2
- OS: Ubuntu 22.04

Steps to Reproduce:

1. Open PR in a repo with CODEOWNERS
2. Add another reviewer
3. Automatically added reviewers get removed

**Comment by alexr00** [comment]
This has been fixed in version 0.68: https://github.com/microsoft/vscode-pull-request-github/issues/4830

**Comment by tymik** [comment]
When will it be in the official release?
It seems I have the most recent version available for VSCode.
![image](https://github.com/microsoft/vscode-pull-request-github/assets/1670525/0c1032f5-0abb-43e5-9ac6-a60fb6d298f8)
Or I don't know how to refresh the version.

**Comment by alexr00** [comment]
> VSCode Version: 1.79.2

You first need to update VS Code. 0.68.0 is not compatible with the old version you are using.

**Comment by tymik** [comment]
All works, great job!
Thank you!
