### ISSUE TITLE
Error code 810 on Authentication

### ISSUE THREAD

**Issue by ryzngard** [Microsoft/vscode-pull-request-github#509]
- Extension version: 0.1.5
- VSCode Version: 1.27.2 (user setup)
- OS: Windows 10 1803

Steps to Reproduce:

1. Install extension
2. Click "Sign In" prompt after restarting VS Code
3. Approve OAuth access on GitHub
4. Get the below page

![image](https://user-images.githubusercontent.com/475144/45840328-7b6e2880-bccb-11e8-802b-839727584737.png)

Tried with Microsoft Edge. 

I do see GitHub for VSCode as an authorized OAuth app in my GitHub settings.

**Comment by dstrome** [comment]
I'm also getting this if you need an internal repro. Alias is the same as my github account.

cc: @RMacfarlane @shana

**Comment by dstrome** [comment]
@ryzngard I finally got this to authorize after several attempts. What finally seemed to work for me was to revoke the authorization for the GitHub for VSCode app here - https://github.com/settings/applications. Then in VSCode I went to the extensions tab and clicked "reload" on the GitHub Pull Requests extension. That popped up a new "you need to sign in" dialog and that finally succeeded. This was after manually restarting VSCode several times.

Anyhoo, thought I'd pass it along in case it happens to work for you too.

**Comment by ryzngard** [comment]
Looks like a new version got pushed that fixed it. I have 0.1.6 now and it worked

**Comment by shana** [comment]
This error means that there's a mismatch between the IP that started the login process and the IP that loaded the web page. That could mean that you're running a VPN that's only handling traffic for your browser, or you have some other set up that's causing the IP to change between the two requests.

**Comment by yesmeck** [comment]
@shana Thanks, finally got this to authorize after turn off the proxy. I think this reminder should be written on the 810 page.

**Comment by carmanchris31** [comment]
The only way for me to get past this on enterprise was to follow https://medium.com/@brianhague/viewing-github-pull-requests-in-vscode-with-github-enterprise-859a07e6d353 with the personal access token and the very subtle step of closing the authentication popup and just refreshing the PRs inside VSCode after updating the settings manually.
