### ISSUE TITLE
I thought the Close Pull Request context menu option was going to checkout master for me

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-pull-request-github#51]
"close PR on GitHub" would have cleared that up.

![image](https://user-images.githubusercontent.com/2193314/41948464-c37ae9f8-7971-11e8-813f-545c3c0f7d8e.png)

**Comment by RMacfarlane** [comment]
Updated wording:

![screen shot 2018-07-11 at 5 06 24 pm](https://user-images.githubusercontent.com/3672607/42605450-d9b19ca0-852c-11e8-8e8f-396b23e8eaa5.png)
