### ISSUE TITLE
Re-checking out a PR that has been rebased results in conflicts

### ISSUE THREAD

**Issue by andrewiggins** [microsoft/vscode-pull-request-github#510]
Issue Type: <b>Bug</b>

Steps:
1. PR Author: Opens a PR to repo
2. PR Reviewer: Checks out the PR using this extension, leaves some comments, then exits review mode
3. PR Author: Responds to comments on PR and rebases her commits
4. PR Reviewer: Tries to checkout the PR again, but can't due to conflicts

(I may be missing a step above about pulling... I forget exactly what I did to do this).

Expected:
A reviewer who made no local changes to a PR, but merely checked out the PR to review, should be able to check out the PR again without any conflicts.

Workaround:
Delete the local branch before re-checking out the PR.

My understanding:
Checking out a PR creates a local branch. When you exit review mode, the local branch remains. Future check outs require pulling the updated changes. If the remote branch has been rebased, this results in local conflicts.

Normally, I get around this by just deleting my local branch and re-checking out the remote one. It would be nice if as a PR reviewer, who only leaves comments, I can checkout PRs multiple times without having to worry about merging changes.

Suggestion:
Perhaps if the extension created the branch on checkout, and the user didn't make any changes to the branch, the extension could delete the local branch when exiting review mode, so future checkouts get latest without conflicts.

or perhaps the guidance is to not rebase remote branches :) I'm uncertain what the general practice is with rebasing PRs. Would appreciate your thoughts!

Searched for: rebase
Related: #75 

Extension version: 0.1.5
VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

**Comment by andrewiggins** [comment]
Also! I really love this extension. Thanks for doing this. It's really made reviewing GitHub PRs a lot nicer 🙌

**Comment by RMacfarlane** [comment]
Combining this with https://github.com/microsoft/vscode-pull-request-github/issues/802
