### ISSUE TITLE
No way to remove Milestone

### ISSUE THREAD

**Issue by hbons** [microsoft/vscode-pull-request-github#5102]
Forgot to add a way to remove a milestone. :)

We could add an item to the quick pick: "Clear Milestone" followed by a separator when a milestone is already set.
Also, we don't currently focus the picked Milestone.

**Comment by alexr00** [comment]
To verify: 
- Install the pre-release version of the extension
- Open a folder that contains a GitHub repo
- Run the "Create Pull Request" command (you won't actually need to create a PR, just run the command).
- Add a milestone to the PR that you're creating
- Verify that you can remove the milestone.

**Comment by hbons** [comment]
Verified I can remove the milestone after adding.
