### ISSUE TITLE
Assignee/reviewers quickpick should stay open when the focus leaves

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-pull-request-github#5108]
Testing #5100

Occasionally I need to go to another window to look up someone's GH handle, it would be nice if the quick inputs for these stayed open when focus leaves the screen. (Maybe we should have [design guidance](https://code.visualstudio.com/api/ux-guidelines/quick-picks) on when to do this in general?)

**Comment by alexr00** [comment]
This is interesting. I think most of our quick picks don't stay open when focus leave the screen, so I would expect most muscle memory to assume that they've closed. I would love to have design guidance on what to do here.

**Comment by hbons** [comment]
cc @daviddossett. I can see a global case for keeping quick pick open when switching apps.

**Comment by alexr00** [comment]
Closing as out of scope for this extension. Keeping the quick pick open when switching apps would need to be handled at the VS Code level.
