### ISSUE TITLE
Have an inline action for adding label/milestone/etc?

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-pull-request-github#5109]
Testing #5100

I've been using the new PR flow in VS Code for a while and honestly never noticed the extra buttons for assigning metadata. It is also slightly weird that the action happens in the title and then causes an effect elsewhere in the body. Maybe there could be inline actions kind of like this to add them?

![image](https://github.com/microsoft/vscode-pull-request-github/assets/2230985/7372044e-b6f9-4364-892b-9c521f841df0)

**Comment by hbons** [comment]
GitHub web does have this: 
<img width="269" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/103326/14b6cbf4-7552-4e83-b9b1-e5fca74b4625">

**Comment by alexr00** [comment]
Closing as out of scope. We only need one way to let users set reviewers/labels/etc.
