### ISSUE TITLE
Commented added at position in file instead of position in diff after pulling new changes

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode-pull-request-github#511]
- Extension version: 0.1.6
- VSCode Version: 1.28

When I was reviewing https://github.com/Microsoft/vscode-pull-request-github/pull/485 I tried to leave a comment on the fourth line of the diff and it ended up getting added on the fourth line of the file:
![screen shot 2018-09-21 at 10 01 56 am](https://user-images.githubusercontent.com/3672607/45895213-6b1a8400-bd85-11e8-9cc3-adbe21128117.png)
![screen shot 2018-09-21 at 10 02 23 am](https://user-images.githubusercontent.com/3672607/45895226-77064600-bd85-11e8-863f-87f322e6cdcb.png)

I think I had the file open, pulled new changes, and then added the comment, so I suspect commenting ranges are not getting properly updated in that case

**Comment by alexr00** [comment]
Closing as not reproducible.
