### ISSUE TITLE
No padding between profile image and name

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode-pull-request-github#5113]
Testing #5100

No gap between profile pic and name
![image](https://github.com/microsoft/vscode-pull-request-github/assets/3840081/b7879bc7-334c-429d-a531-9a3e385a801c)

Should look like this:
![image](https://github.com/microsoft/vscode-pull-request-github/assets/3840081/ef0347e6-bb3d-4f8c-b897-e7b6c0452c85)

**Comment by hbons** [comment]
Has been fixed in main.
