### ISSUE TITLE
Tabbing on to profile image briefly triggers the Quickpick for assignees/reviewers

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode-pull-request-github#5115]
Testing #5100

![image](https://github.com/microsoft/vscode-pull-request-github/assets/3840081/78d28ea3-bbbe-49f2-8104-c5b0b9621dbc)

Pressing enter there triggers Quickpick and the browser.

**Comment by hbons** [comment]
This has been fixed in main.
