### ISSUE TITLE
Provide a way to self assign

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode-pull-request-github#5116]
Testing #5100

**Comment by hbons** [comment]
You mean you want a dedicated entry in the Assignee quick pick that says "Self Assign"?

**Comment by alexr00** [comment]
We also have a setting `"githubPullRequests.assignCreated": "${user}"`

**Comment by karthiknadig** [comment]
> You mean you want a dedicated entry in the Assignee quick pick that says "Self Assign"?

Yes.

**Comment by hbons** [comment]
I think this is a good idea. @alexr00 how about `Assign Yourself` as the first item followed by a separator? This is the same wording as on GH web.

**Comment by alexr00** [comment]
![image](https://github.com/microsoft/vscode-pull-request-github/assets/38270282/f0e6c339-5850-4938-a357-29d73407a0e5)

**Comment by alexr00** [comment]
To verify:
- Install the pre-release version of GitHub Pull Requests and Issues
- Open the description/overview of a PR
- Add an assignee. Verify that you see an "Assign yourself" option at the top of the quick pick.

**Comment by andreamah** [comment]
<img width="260" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/31675041/e2028f42-2c75-4298-9883-796d2f8886e1">
I don't think I see it. Does it need to be my own PR?

**Comment by karthiknadig** [comment]
I see this:
![image](https://github.com/microsoft/vscode-pull-request-github/assets/3840081/92922240-9012-493a-9da0-9a7adc5401a7)

And I see my self as the first option:
![image](https://github.com/microsoft/vscode-pull-request-github/assets/3840081/67303b9b-4949-43ec-8096-853f2aca237d)

**Comment by alexr00** [comment]
My verification steps were incorrect:
- Install the pre-release version of GitHub Pull Requests and Issues
- ~~Open the description/overview of a PR~~ Checkout a topic branch, make a commit, and run the command "Create Pull Request"
- Add an assignee from the "Create" view. Verify that you see an "Assign yourself" option at the top of the quick pick.

**Comment by aiday-mar** [comment]
Just verified, it works:

![Screenshot 2024-01-24 at 13 00 22](https://github.com/microsoft/vscode-pull-request-github/assets/61460952/33c86624-6a8d-472f-87e5-292200e7fd2d)

Although I see myself twice in that list now
