### ISSUE TITLE
Create button did not remember the choice

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode-pull-request-github#5117]
Testing #5100

**Comment by alexr00** [comment]
What choice did you pick and what choice did it give you the next time? Was this in the same folder?

**Comment by alexr00** [comment]
If it was `draft` that will be fixed by https://github.com/microsoft/vscode-pull-request-github/pull/5123

**Comment by karthiknadig** [comment]
Yes it was Draft.
