### ISSUE TITLE
The publish modal dialog is a bit confusing

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode-pull-request-github#5118]
Testing #5100

I had a unpublished branch:
![image](https://github.com/microsoft/vscode-pull-request-github/assets/3840081/aa2f1769-4572-424b-863d-2b395ceec8a8)

This is my PR setup:
![image](https://github.com/microsoft/vscode-pull-request-github/assets/3840081/23870c56-eeb2-494d-8dd9-16b7f857bec8)

These are the possible remotes:
![image](https://github.com/microsoft/vscode-pull-request-github/assets/3840081/a2730d8f-f0ac-43a7-a8b9-9c7f55c3eb48)

This is the dialog:
![image](https://github.com/microsoft/vscode-pull-request-github/assets/3840081/1111c2c3-507b-4864-bfe7-93c22eaa5b8f)

The word "upstream" here is referring the actual `origin` remote. i.e, if I say publish it will create `origin/use-api` branch not `upstream/use-api` branch. The text should probably say that it will publish the branch to "<remote name>".

**Comment by karthiknadig** [comment]
This error message should also be improved:
![image](https://github.com/microsoft/vscode-pull-request-github/assets/3840081/6925e35f-fa63-4190-b04c-d193c52f7c6e)

**Comment by hbons** [comment]
> New dialog wording: <img alt="image" width="437" src="https://user-images.githubusercontent.com/38270282/256193730-bd1fec9b-41a3-40c3-8451-b60d9a3db610.png">
> 
> And error: <img alt="image" width="275" src="https://user-images.githubusercontent.com/38270282/256194119-b1fe1921-0dbf-45b4-9e89-2573abae0c2e.png">

Shouldn't we avoid the word 'upstream' and use the word 'remote' here?

`There is no remote branch on alexr00/playground for 'alexr00/testPublishPrompt'.`
and
`No remote branch on alexr00/playground for the merging branch.`

**Comment by Tyriar** [comment]
:+1: to not calling it upstream as it's talking about the `origin` remote, not the `upstream` remote.

**Comment by Tyriar** [comment]
Verified via code review
