### ISSUE TITLE
File changes shown but no local commits

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode-pull-request-github#5119]
Testing #5100

![image](https://github.com/microsoft/vscode-pull-request-github/assets/3840081/669360fc-60e5-41c1-b086-376fbc9edcd7)

**Comment by alexr00** [comment]
This is currently by design. We need new git extension API before we can have local commits. Once https://github.com/microsoft/vscode/pull/188500 is merged I will adopt the API here.
