### ISSUE TITLE
Fetching PRs fails with "The header content contains invalid characters"

### ISSUE THREAD

**Issue by shana** [microsoft/vscode-pull-request-github#512]
From https://github.com/Microsoft/vscode-pull-request-github/issues/506#issuecomment-423529904

![](https://user-images.githubusercontent.com/1481108/45883781-158fa880-bd80-11e8-95b3-916711e71e24.png)

@ryanspletzer You can just fill out the token directly in the settings.json file token field instead of putting it in the credential manager.

With that said, it looks like everything is correctly filled out, and this doesn't feel like an authentication issue, feels like the response that the server is returning is breaking in some way. It could be the authorization token being invalid and breaking the request, of course, but that should fail way before you get to the point where you're trying to get pull requests, so I suspect something else is going on.

Could you run curl and see what the headers return? Curl for Windows is available at https://curl.haxx.se/download.html and you can just unzip it and run from the command line, no installation needed, and then run

`curl -I -H 'authorization: token [your token]' https://[your-server.com]/api/v3/repos/[repo owner]/[repo name]/pulls > headers.txt`

This will run the same request that is failing above and save the headers to the `headers.txt` file. If you could sanitize the `Server` name and post the contents of the text file so I can check it out? If you'd rather not post it publicly, you can send it to shana at github dot com instead.

**Comment by ryanspletzer** [comment]
Hey @shana thanks for opening the issue, I used curl through WSL and this is what I saw (again for reference we're on GitHub Enterprise 2.13.4), weirdly the server name said github.com though this was definitely an internal call to our Github Enterprise instance:

```
HTTP/1.1 200 OK
Server: GitHub.com
Date: Mon, 24 Sep 2018 16:59:06 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 5
Status: 200 OK
X-RateLimit-Limit: 999999999
X-RateLimit-Remaining: 999999998
X-RateLimit-Reset: 1537811946
Cache-Control: private, max-age=60, s-maxage=60
Vary: Accept, Authorization, Cookie, X-GitHub-OTP
ETag: "1f8b8652dc3399784825118524e20b0c"
X-OAuth-Scopes: read:user, repo, user:email, write:discussion
X-Accepted-OAuth-Scopes: 
X-GitHub-Enterprise-Version: 2.13.4
X-GitHub-Media-Type: github.v3; format=json
Access-Control-Expose-Headers: ETag, Link, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
Access-Control-Allow-Origin: *
X-GitHub-Request-Id: dd3a6e7e-bb97-43f7-b941-bc35ddb4f4b9
Content-Security-Policy: default-src 'none'
Strict-Transport-Security: max-age=31536000; includeSubdomains
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-Runtime-rack: 0.073235
```

**Comment by shana** [comment]
Hmmm, I'm stumped, I have no idea why requests would fail with these headers. The token is valid (and if you take out the `-I` flag you'll see the json data that gets returned). The server field I think returns GitHub.com for some enterprise instances, btw, so that's normal. 

When does this error show up? Are you expanding the "All" list or one of the other lists?

**Comment by shana** [comment]
Also, could you open the Output tab on the GitHub Pull Request dropdown and paste the contents here? There should be other errors in there that might help figure this out

**Comment by Gnugumel** [comment]
I have the same issue, from the output tab:
e.g. [Debug 7130s 388ms] GitHubRepository> Fetch pull request catogory Mine - enter
[Debug 7130s 390ms] GitHubRepository> Fetching all pull requests failed: TypeError: The header content contains invalid characters

the headers look very much the same:
`
HTTP/1.1 200 OK
Server: GitHub.com
Date: Thu, 10 Jan 2019 10:44:20 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 296165
Status: 200 OK
Cache-Control: private, max-age=60, s-maxage=60
Vary: Accept, Authorization, Cookie, X-GitHub-OTP
ETag: "e97fce23440ed57812a9a846c8086245"
X-OAuth-Scopes: read:user, repo, user:email, write:discussion
X-Accepted-OAuth-Scopes:
X-GitHub-Enterprise-Version: 2.14.6
X-GitHub-Media-Type: github.v3; format=json
Access-Control-Expose-Headers: ETag, Link, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
Access-Control-Allow-Origin: *
X-GitHub-Request-Id: 73769801-82cd-4772-a5ea-e036f357438f
Strict-Transport-Security: max-age=31536000; includeSubdomains
X-Frame-Options: deny
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
Content-Security-Policy: default-src 'none'
X-Runtime-rack: 0.524205
`
