### ISSUE TITLE
Files Changes not updated after changing base branch

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-pull-request-github#5121]
Type: <b>Bug</b>

Using the new Create PR UI.

Extension version: 0.69.2023072509
VS Code version: Code - Insiders 1.81.0-insider (fda972663af87b4d1dab87845e36c357738b44f9, 2023-07-25T08:14:58.320Z)
OS version: Darwin arm64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|64.00GB (0.37GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by chrmarti** [comment]
<img width="461" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/9205389/7cb80cc6-b837-4b49-9476-591f158afd6e">

**Comment by alexr00** [comment]
I'm not able to reproduce this. My steps:
1. Make some changes on a topic branch. Do not push the branch.
2. "Create Pull Request"
3. See a diff between main and my topic branch
4. In the Create view, change the base branch to something else
5. See the diffs in "Files Changed" update.

Were these also your steps @chrmarti?

**Comment by ahmadHadizadeh** [comment]
👍

**Comment by chrmarti** [comment]
I started from a branch of an already merged PR (not noticing at first) and create a new commit there before creating  a new branch. Can't reproduce the issue now. Ok to close for me.
