### ISSUE TITLE
Create PR view: one extra horizontal line between CREATE and BASE name

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-pull-request-github#5133]
I feel like the BASE and MERGE part could go a bit higher.
It feels to me like there is unused space at the top of the view.
Is this space reserved for something that I am missing?

![Screenshot 2023-07-27 at 14 06 55](https://github.com/microsoft/vscode-pull-request-github/assets/1926584/d2200b49-ca43-4ab2-b7c6-8b64cc293573)

**Comment by karthiknadig** [comment]
This looks better now:
![image](https://github.com/microsoft/vscode-pull-request-github/assets/3840081/8352131c-362a-43fb-964f-ca9fc0241ded)
