### ISSUE TITLE
Unable to open a file

### ISSUE THREAD

**Issue by Siegrift** [microsoft/vscode-pull-request-github#515]
- Extension version: 0.1.6
- VSCode Version: 1.27.2
- OS: Linux mint

Checkout the branch to go in review mode and try to open a file. I get an error that a file cannot be opened (and the path in error message is correct + file is present).

**Comment by RMacfarlane** [comment]
Can you check if there's anything in the dev console when this happens? Does this happen for every file, or only specific files?

**Comment by ajkl2533** [comment]
@Siegrift do you have a monorepo?

**Comment by Siegrift** [comment]
@RMacfarlane @ajkl2533 Hello and sorry for late reply, I was busy at work. 

Unfortunately, there is nothing in a dev console. It happens for every file that I've received comments on. When I click on the comment I can see the file appearing for a split second, but then the error is shown. The project is private, so I can't give much details, however I am adding a screenshot for more context.
![pr](https://user-images.githubusercontent.com/22679154/46032577-4ebb7600-c0fc-11e8-9e4e-9a84c3f59feb.png)

**Comment by RMacfarlane** [comment]
I'm clearing out some old issues and am going to go ahead and close this since I can't currently reproduce it and there haven't been further reports of it
