### ISSUE TITLE
Config to disable the start discussion "plus" sign near the line numbers

### ISSUE THREAD

**Issue by bonniesimon** [microsoft/vscode-pull-request-github#5151]
How can I remove the start discussion plus sign ? I digged through and UI settings and found nothing to disable it. 

I'm talking about this
![image](https://github.com/microsoft/vscode-pull-request-github/assets/49012815/15405508-e223-4693-9ab1-c3551195f0e4)

It is super annoying when paired up with certain themes. I would love to have a way to disable it.

Another user felt the same: https://stackoverflow.com/questions/74618751/how-to-disable-the-plus-sign-next-to-the-line-number-that-allows-me-to-comment-o

**Comment by alexr00** [comment]
Check out the setting `"comments.visible": false` and the command "Comments: Toggle Editor Commenting".
