### ISSUE TITLE
pull request base repo resets to origin everytime

### ISSUE THREAD

**Issue by crimx** [microsoft/vscode-pull-request-github#5153]
Type: <b>Bug</b>

Settings:

```json
{
  "githubPullRequests.pullRequestDescription": "commit",
  "githubPullRequests.remotes": ["upstream"],
  "githubPullRequests.defaultMergeMethod": "squash",
  "githubPullRequests.defaultCreateOption": "create"
}
```

Steps to Reproduce:

1. Fork a repo(origin) from upstream.
2. Publish a new branch to origin in vscode.
3. Click the Create Pull Request button on notification.
   <img width="463" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/6882794/b122c536-c4c6-4e81-a39f-6e256be00976">
5. The base resets to origin.
   <img width="398" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/6882794/1fb3c04c-b3e3-446c-bcd0-b1c664435621">

Extension version: 0.70.0
VS Code version: Code 1.81.0 (Universal) (6445d93c81ebe42c4cbd7a60712e0b17d9463e97, 2023-08-02T12:40:02.782Z)
OS version: Darwin arm64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|32.00GB (0.17GB free)|
|Process Argv|--crash-reporter-id 54f4f295-1c79-4208-b032-1438ce3b9094|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30792226
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
282f8724:30602487
f6dab269:30613381
showlangstatbar:30737416
vsctsb:30748421
03d35959:30757346
57b77579:30736110
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
e537b577:30795824
dsvsc013:30795093
dsvsc014:30804076

```

</details>

**Comment by alexr00** [comment]
We now try to guess the base branch better by tracking where you branched off from. Maybe we need a setting to disable this, or maybe we need to improve the logic around it. What branch did you have checked out when you created branch `test3`?

**Comment by crimx** [comment]
I always create branches from origin main and make PR to upstream main.

**Comment by alexr00** [comment]
> I always create branches from and push to origin main and make PR to upstream main.

I'll either add a setting or adapt the branch guessing to do better here.

**Comment by adambirds** [comment]
Yeah this is terrible currently. Most people have workflows where the master repository is upstream and each developer works in their own origin before submitting PRs back to upstream. It used to work perfectly.

**Comment by alexr00** [comment]
Before I add yet another setting, let's try the following fix: if the predicted merge base is the default branch of a fork, use the default branch of the upstream repo instead.

**Comment by adambirds** [comment]
@alexr00 when will this be available to test?

**Comment by alexr00** [comment]
Probably around 9 Pacific time tomorrow. I'll post again when it's available.

**Comment by alexr00** [comment]
Fix is available in the latest pre-release build. I'm not currently planning on making a new stable build with the fix, but if I see a few more folks say this is a problem for them then I can release a new stable.

**Comment by adambirds** [comment]
Thanks @alexr00, can confirm it works as expected. Happy to use pre-release for now.

**Comment by crimx** [comment]
Thanks for the quick fix! Also confirm it works.
