### ISSUE TITLE
Comment Text Stays After Commenting

### ISSUE THREAD

**Issue by jamesqquick** [Microsoft/vscode-pull-request-github#516]
- Extension version: 0.1.6
- VSCode Version: 1.27.2
- OS: Mac OS High Sierra 10.13.6

Steps to Reproduce:

1. Open a pull request
2. Type a comment and click the comment button
3. The comment text stays even after commenting

![image](https://user-images.githubusercontent.com/5391915/45935199-ab892600-bf6e-11e8-9218-68a5911092bb.png)

**Comment by deep110** [comment]
Hi, I would like to take this up as my first issue if there is no problem. If yes would love to get some pointers from where to start. Thanks!!

**Comment by RMacfarlane** [comment]
Thanks @deep110! I haven't been able to reproduce this yet. The code that creates the webview is in [pullRequestOverview.ts](https://github.com/Microsoft/vscode-pull-request-github/blob/8a512673110bdc68758dbdab029ec89912f6e3ee/src/github/pullRequestOverview.ts) and the script that gets loaded within the webview is [index.ts](https://github.com/Microsoft/vscode-pull-request-github/blob/8a512673110bdc68758dbdab029ec89912f6e3ee/preview-src/index.ts).

The click handler for the comment button is in `index.ts`, which posts the value to `pullRequestOverview.ts`. The comment is created and then `pullRequestOverview.ts` should send a message back to `index.ts`, which then clears the text area.

Here's where messages from the webview get handled:

https://github.com/Microsoft/vscode-pull-request-github/blob/8a512673110bdc68758dbdab029ec89912f6e3ee/src/github/pullRequestOverview.ts#L208-L228

And here's the piece that appends the created comment in the webview:

https://github.com/Microsoft/vscode-pull-request-github/blob/8a512673110bdc68758dbdab029ec89912f6e3ee/preview-src/index.ts#L248-L256

I think the likely problem is that we're not properly handling errors on comment create.

**Comment by rebornix** [comment]
My suspicion is we didn't clear `pendingComments` on the cached pullrequest model in webview, after the comment is created successfully. So any following pull request refresh event will reload the webview with the cached `pendingComments`

Steps to reproduce:

* Comment, and once the comment is submitted successfully, the textarea is clean.
* Switch to another editor
* Refresh the Pull Request treeview
* Switch back the description page, the comment shows up again in the textarea.
