### ISSUE TITLE
PR stuck and loading forever after code review and when calculating the merge changes (on some PRs, not all)

### ISSUE THREAD

**Issue by joao-casas-fernandes-NOS** [microsoft/vscode-pull-request-github#5160]
I noticed that in the last couple of weeks we started having the same problem that was closed (issue 4118) about a year ago.
Basically we get the message "checking if this branch can be merged" and it stays loading forever. I think it is happening when there is some conflict. Even if it is an auto merge it stays stuck.

![image](https://github.com/microsoft/vscode-pull-request-github/assets/110121140/83799842-e3a5-4244-b5af-1bce6cd05f11)

Currently we are doing the PR and then removing the "require a PR to merge" flag and do a merge request from VS Code, but it is not ideal because it can cause serious problems with PRs that are opened but are not reviewed and they stay there for 2 days or something like that.

**Comment by alexr00** [comment]
@joao-casas-fernandes-NOS I'm not able to reproduce this. Can you do the following:
1. Set the log level of GitHub Pull Request to "debug"
    a. command: Developer: Set Log level
    b. Choose GitHub Pull Request
    c. Choose debug
2. Next time you see the issue happen, share the output of "GitHub Pull Request". If you don't want to share the whole thing, the lines I'm looking for will begin with "Fetch pull request mergeability" and  "Unable to fetch PR Mergeability".

**Comment by helly25** [comment]
It is getting useless:

```
2023-10-13 16:42:40.435 [debug] GitHubRepository> Fetch repo permissions and available merge methods - done
2023-10-13 16:42:40.435 [debug] RateLimit> Extension rate limit remaining: 140, /repos/{owner}/{repo}/compare/{base}...{head}
2023-10-13 16:42:40.850 [debug] RateLimit> REST Rate limit remaining: 4985, /repos/{owner}/{repo}/compare/{base}...{head}
2023-10-13 16:47:32.359 [debug] CreatePullRequestViewProvider> Total commits: 1
2023-10-13 16:47:32.360 [info] CreatePullRequestViewProvider> Initializing "create" [...]
```

So now I was stuck between `2023-10-13 16:42:40.850` and `2023-10-13 16:47:32.359`. So about 5 minutes for an operation that should take a second if that.

**Comment by alexr00** [comment]
We do 3 things in that window: 
- Count the total number of commits (comes from GitHub API)
- Get the last commit message (comes from git API)
- Get the PR template (comes from reading the file system)

I bet it's getting stuck getting the last commit title+description. I'll add a timeout for that and logging for how long each of the three parts is taking.

**Comment by helly25** [comment]
Thanks. Let me know when I should update and I can report back.

**Comment by alexr00** [comment]
@helly25 your issue seems totally unrelated to the original issue. Let's move this over to https://github.com/microsoft/vscode-pull-request-github/issues/5374.
