### ISSUE TITLE
Button spacing

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-pull-request-github#5166]
I feel there is quite the gap between these two buttons at the bottom:

![Image](https://github.com/microsoft/vscode-pull-request-github/assets/900690/7ae12c45-c5d2-4d30-93ac-537397dc1e98)

**Comment by bpasero** [comment]
Hm, I guess this is done to separate the concerns that are clearly different? What is the reason to have a button to "Check out main", should that maybe be just removed? I wonder how related that action is to the PR?

**Comment by alexr00** [comment]
The "Checkout 'main'" used to be "Exit review mode", which still just checked out main but which users found confusing. Since we checkout a branch when you check out a PR, we want to have a way to guide users off of that branch too when they're done working with the PR.

**Comment by alexr00** [comment]
@hbons as well in case you have thoughts on this.

**Comment by hbons** [comment]
Adding some grouping and changing the checkout button to secondary could help here. Quick mockup: 

<img width="415" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/103326/f604f77f-584b-47c9-83e6-060ca299bffe">

**Comment by alexr00** [comment]
Closing as I don't plan to address this.
