### ISSUE TITLE
Can't query for closed PRs

### ISSUE THREAD

**Issue by roiweinreb** [microsoft/vscode-pull-request-github#5167]
I added the query `is:closed` to `githubPullRequests.queries` but I see only one draft PR.
Not sure whether it matters or not but the repo is in my work's organization account. The other default queries (i.e. "Assigned To Me", "Waiting For My Review" etc) work fine.

- Extension version: v0.62.0
- VSCode Version: 1.77.3
- OS: Darwin arm64 22.5.0

Steps to Reproduce:

1. Add `{"label": "Closed", "query": "is:closed"}` to `githubPullRequests.queries` in settings.
2. Look for the closed PRs in the side bar

**Comment by alexr00** [comment]
You're likely running in to https://github.com/microsoft/vscode-pull-request-github/issues/4613.
