### ISSUE TITLE
getPullRequestChangedFiles does not get all changed files

### ISSUE THREAD

**Issue by ADyson** [microsoft/vscode-pull-request-github#517]
I am reviewing a pull request with 550 changed files but not all of them are appearing in the list of changed files. 

Inside `async getPullRequestChangedFiles(pullRequest: IPullRequestModel): Promise<FileChange[]>` It makes the first request and then requests an additional page only twice (`while (response.headers.link && octokit.hasNextPage(response.headers)) {`) resulting in only the first 300 changes.

- Extension version: 0.1.5
- VSCode Version: 1.28.0-insider
- OS: Win10 Enterprise v1607

Steps to Reproduce:

1. Open a pull request with > 300 files changed.
2. Check if the files changes contains all of the files it should.

**Comment by cyrusmg** [comment]
It seems there has been an update on this one. The linked github documentation mentions limit of 3000 changed files, not 300 which seems to be the limit now (I see this issue being triggered with 320 changed files).

**Comment by alexr00** [comment]
Thanks for the update @cyrusmg!
