### ISSUE TITLE
Focus in list of changes resets when opening file

### ISSUE THREAD

**Issue by marc-eggers** [microsoft/vscode-pull-request-github#5173]
- Extension version: 0.70.0
- VSCode Version: 1.81.1
- OS: macOS 13.2.1 (22D68)

**Expected behaviour**
When opening a file from the changed files tree/list, the "passive sidebar focus" should stay on the selected file/list element. This means that triggering the VSCode command `workbench.action.focusSideBar` should focus the file in the tree which was previously opened.

After opening `index.ts`, the tree view should look like this:
<img width="255" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/63095979/ee7e6c7f-8e38-4836-8ff4-24eefe18daac">

**Actual behaviour**
The moment a file is opened from the tree, the sidebar's focus shifts to the tree view itself. This means that, in order to navigate back to the opened file using the keyboard, you have to start from the very top every time. This is very tedious. The only way to keep focus on the opened file is to click it after it's already been opened, which is of course not ideal when trying to use keyboard navigation.

After opening `index.ts`, the tree view looks like this (notice the focus outline around the whole view):
<img width="255" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/63095979/ca2dbc01-afe1-47da-b845-57633624f3d3">

While I don't know exactly when, I could swear this used to work as expected a few months ago.

Steps to Reproduce:

1. Open list of changes in sidebar
2. Either click a file to open it, or navigate there with arrow keys and open it with spacebar
3. The "passive" sidebar focus has now moved to the tree view
4. Focus sidebar by executing either of these commands: `workbench.action.focusSideBar`, `prStatus:github.focus`
5. Press the "down" arrow key
6. You should now be focused on the highest element in the list, instead of where you left off

Thanks for your consideration :)

**Comment by alexr00** [comment]
Should be fixed by https://github.com/microsoft/vscode/pull/193346

**Comment by marc-eggers** [comment]
Thanks so much @alexr00, this is gonna make my review process much smoother. Can't wait to try it out when it hits pre-release :)
