### ISSUE TITLE
Localized text breaks command

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode-pull-request-github#5175]
The git push command is broken in the French translation

![Screenshot of modified files viewlet suggesting to git push, but the link doesn't work](https://github.com/microsoft/vscode-pull-request-github/assets/7199958/c49e6d57-c8b8-4973-ad48-27afe20b97a8)

**Comment by TylerLeonhardt** [comment]
@alexr00 can you add a lock comment for this?

```
"{Locked='](command:git.publish)'}"
