### ISSUE TITLE
Can nit install on macOS

### ISSUE THREAD

**Issue by budarin** [Microsoft/vscode-pull-request-github#518]
- Extension version: latest
- VSCode Version: 1.24.1 (1.24.1)
- OS: MacOS

Steps to Reproduce:

1. try to install extention -> it throws error: Failed to install 'github.vscode-pull-request-github'.Download manually.

2.Have downloaded the extention & try to open it with Visual Studio Code -> it opens as unknow file

**Comment by RMacfarlane** [comment]
Please update VSCode to version 1.27 or higher

**Comment by budarin** [comment]
I do check for updates & it says that there is no any updates... (

**Comment by budarin** [comment]
After installing the latest version of VS Code extention is successfully installed.
Thanks!
