### ISSUE TITLE
PRs and Issues can not load for any Github repo

### ISSUE THREAD

**Issue by chenyukang** [microsoft/vscode-pull-request-github#5180]
- Extension version: v0.70.0
- VSCode Version: 1.81.1 
- OS: MacOs

Steps to Reproduce:

1. Install the Github PR extension
2. Open with any Github repo

The log is:
<img width="1254" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/230646/b15347ee-d9a5-4378-9fa9-7d0d840126dc">

I have login with my account:
<img width="595" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/230646/47936687-bf95-4bc0-b682-7e1c8068f26b">

**Comment by chenyukang** [comment]
here is my settings:

```json
"githubPullRequests.logLevel": "debug",
    "githubPullRequests.queries": [
        {
            "label": "Waiting For My Review",
            "query": "is:open review-requested:${user}"
        },
        {
            "label": "Assigned To Me",
            "query": "is:open assignee:${user}"
        },
        {
            "label": "Created By Me",
            "query": "is:open author:${user}"
        }
    ]
```

**Comment by chenyukang** [comment]
More logs:

<img width="761" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/230646/b2010754-acee-4fda-baef-a1a3a04463b0">

**Comment by alexr00** [comment]
Do you have the built in git extension enabled?
