### ISSUE TITLE
Generates a large number of uncaught errors on WSL2.

### ISSUE THREAD

**Issue by killshot13** [microsoft/vscode-pull-request-github#5184]
Type: <b>Bug</b>

Expected: 
The extension works normally, like most other extensions installed on WSL2, w/o generating many uncaught errors.

Actual:
Extension consistently generates considerable uncaught errors during normal day-to-day VS Code operations in WSL2. During the time it took to create this PR, and with no apparent interaction on my part, errors have increased from 29 to 36; I can see the counter incrementing in the background while I type.

Repro:
- Install the `GitHub Pull Requests and Issues` extension on VS Code in WSL2. 
- Grant the requested permissions, thereby adding the extension to the list of Trusted Extensions.
- Perform normal VS Code operations for a minute or two.
- Open VS Code workbench command input and select `Developer: Restart Extension Host`.
- Action should fail, generating a prompt; choose the option to reload. 
- Wait for the extension host to perform the initial load sequence. 
- Open the Extensions tab in the Sidebar, click the `...` icon in the upper right corner, and select `Show Running Extensions` from the popup menu.
- Use the view that opens in the main editor to scroll until `GitHub Pull Requests and Issues` is located.
- Check for either a **_hung extension_** (status will show "activating" even after 10-15 minutes) or **_one or more uncaught extension errors_** (possibly actively incrementing higher and higher).

Additional details:
This is not necessarily a new issue. I have uninstalled this extension several times due to uncaught errors and the accompanying latency (real or perceived) it creates in VS Code. However, I cannot be sure the cause of the errors has remained identical since I have never attempted to debug it.

Extension version: 0.70.0
VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.90.4-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G4 CPU @ 1.10GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.60GB (1.10GB free)|
|Process Argv|--file-uri=vscode-remote://wsl+Ubuntu/home/sth13/code/reporg/galactic/hl/helplisted/helplisted.code-workspace --remote=wsl+Ubuntu --crash-reporter-id 4da9c5cf-4181-4cf3-92d8-15b99c279d21|
|Screen Reader|yes|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.90.4-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-1035G4 CPU @ 1.10GHz (6 x 1497)|
|Memory (System)|5.36GB (2.92GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
282f8724:30602487
f6dab269:30613381
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30812748

```

</details>

![Screenshot 2023-08-18 020135](https://github.com/microsoft/vscode-pull-request-github/assets/47695475/53cea3b2-b6b9-4c51-957c-f1854742ca88)

**Comment by alexr00** [comment]
@killshot13 I've tried to reproduce the errors, but I don't get any when I follow your steps. Can you share some of the errors?

**Comment by killshot13** [comment]
@alexr00 thanks for looking into this. To be completely honest, since I opened the PR the extension hasn't given me many issues to speak of. It's probably the old bit about how your car never makes strange noises while at the mechanic. 

But if you leave this PR open for a short while I'll definitely send you what I can, if I can. Any logs in particular that you're interested in?

**Comment by alexr00** [comment]
The errors should show up in the dev console (command "Developer: Toggler Developer tools" to show the dev console).

**Comment by killshot13** [comment]
I now realize I have been experiencing two errors related to this extension, the more egregious of which is the original subject of this PR.

At least in this instance, it appears to have been triggered by my errant attempt at using the `@username` syntax to assign a GitHub user and a team within the owning org to a PR draft. I used the extension to create the initial template for this draft within VS Code. 

When I tried to create the PR on GitHub using the details provided within the template, the extension could not reconcile the team with any known users. This caused the fetch call to fail, triggered a subsequent firestorm of concurrent fetch attempts, and generated hundreds of error messages in seconds. 

---
![invalid_assignee_error](https://github.com/microsoft/vscode-pull-request-github/assets/47695475/9698bdef-1352-4ed1-b10f-45f030c8e90e)
---

The other issue involves the extension requesting me to enter the passphrase for my SSH key multiple times, and even then, sometimes abruptly disconnecting, despite my careful entry of the characters to be confident of the accuracy. I also have a couple of screenshots and an error log related to this, but I'll let you decide whether I should create a separate PR for that. 

Please take a look at the attached log file. Let me know if you can repro this issue and whatever else you need. Thank you!

[invalid_assignee_error.log](https://github.com/microsoft/vscode-pull-request-github/files/12501923/invalid_assignee_error.log)

**Comment by alexr00** [comment]
> At least in this instance, it appears to have been triggered by my errant attempt at using the @username syntax to assign a GitHub user and a team within the owning org to a PR draft. I used the extension to create the initial template for this draft within VS Code.

I tried this out, and as expected I get a warning notification saying that the issue couldn't be created. Did you see some other behavior?

> The other issue involves the extension requesting me to enter the passphrase for my SSH key multiple times 

@lszomoru could this be coming from the git extension when GHPRI tries to use the git extension API?

**Comment by lszomoru** [comment]
@alexr00, yes it could, as VS Code does not store the passphrase when authenticating with an SSH key that uses a passphrase (similar as we do not store the password). When using an SSH key we always recommend following [this documentation](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/working-with-ssh-key-passphrases), to avoid entering the passphrase on every request.
