### ISSUE TITLE
this extension add remotes to my git repo

### ISSUE THREAD

**Issue by clembo590** [microsoft/vscode-pull-request-github#5186]
- Extension version: GitHub.vscode-pull-request-github v0.70.0
- VSCode Version: Version: 1.81.1
- OS: macos 13.5

Steps to Reproduce: see gif

0. UNISTALL THIS EXTENSION!!!
1. take any repo on github with a few commits and PRs and fork it. (you can take [vscode-pull-request-github](https://github.com/microsoft/vscode-pull-request-github)  as an example)
2. clone it locally on your machine
3. execute 'git remote -vv' check there is only one remote url
4. launch vscode  --> check that there is still only one remote url when you execute  'git remote -vv'
5. install the extension 
6. execute  'git remote -vv' --> you will now see two remotes.

That is NOT ok, this extension should not add remotes to my repo. At least it should not add any remote without asking me first.
As you see in the video I end up with multiple remotes but I cannot remove them (every time I relaunch vscode a remote is added)

![anim](https://github.com/microsoft/vscode-pull-request-github/assets/10899818/644ff5d6-742c-4e80-a016-8aeee044674c)

**Comment by alexr00** [comment]
You can disable adding the remote with `"githubPullRequests.upstreamRemote": "never"`.
