### ISSUE TITLE
Release asset missing for `0.70.0`

### ISSUE THREAD

**Issue by filiptronicek** [microsoft/vscode-pull-request-github#5188]
Hey there 👋,
https://github.com/microsoft/vscode-pull-request-github/releases/tag/v0.70.0 does not have a `.vsix` attached to it like all of the earlier releases. It could have been intended, but I figured I'd give it a shot (the release assets are really helpful 🙏)

**Comment by alexr00** [comment]
@filiptronicek I appreciate the ping! Leaving out the `.vsix` was intended. We figure individual users can always download the `.vsix` from the VS Code extension marketplace if they want it.
