### ISSUE TITLE
Cannot authorise plugin with custom Github domain/ enterprise Github account

### ISSUE THREAD

**Issue by im-philbrant** [Microsoft/vscode-pull-request-github#519]
- Extension version: Github pull requests 0.1.6
- VSCode Version: 1.27.2
- OS: MacOS Sierra 10.12.6

Steps to Reproduce:

1. Install Github pull requests plugin for VS Code
2. Try authorise the plugin with Github, brings you to a page that says "Authorize Visual Studio Code to access GitHub"
3. When I click this, I get a 404 page on our custom github domain

**Comment by shana** [comment]
@im-philbrant That error means that your GitHub Enterprise is too old to do the integrated sign in process. I've just updated the docs with information on how to authenticate in these cases, check it out at https://github.com/Microsoft/vscode-pull-request-github/wiki#i-get-a-404-when-trying-to-sign-in
