### ISSUE TITLE
Select upstream (as default) repository

### ISSUE THREAD

**Issue by cbrnr** [microsoft/vscode-pull-request-github#5195]
- Extension version: v0.70.0
- VSCode Version: 1.81.1
- OS: Darwin macOS 13.5.1 (arm64 22.6.0)

Steps to Reproduce:

1. Clone any forked repository via "Clone Git Repository" – "Clone from GitHub" – enter repository URL (this sets up both `origin` and `upstream`).
2. Make a small change on a new branch, commit, and publish the branch on `origin`.
3. Select "Create Pull Request". This will now show the `main` branch on `origin` as the base, which is not what I want (since this is a PR of a fork, I want my changes to be merged in `upstream`).

I know I can select a new base (i.e. `upstream/main`), but I don't want to do that with every new PR I make. Also, this did work as expected previously, but I cannot pinpoint exactly when this changed.

Another affected behavior: I often use the "Copy GitHub Head Link" functionality (e.g. by right-clicking on a line number). This now also only redirects to the `origin` repository, whereas I want the link to `upstream` in almost all cases. This too used to work in some previous version.

**Comment by alexr00** [comment]
In the "Create" view, your issue is fixed in the pre-release build. The next stable release should be next week.

It looks like "Copy GitHub Head Link" will never try to get the fork's upstream. This seems like it could be reasonable as the "head" should mean the head of your current branch.

**Comment by cbrnr** [comment]
> In the "Create" view, your issue is fixed in the pre-release build. The next stable release should be next week.

Thank you, I'm looking forward to trying it out!

> It looks like "Copy GitHub Head Link" will never try to get the fork's upstream. This seems like it could be reasonable as the "head" should mean the head of your current branch.

I think this worked at some point too, meaning that I was able to get a link to upstream. Do you mean that this does not make sense? In my workflow, I almost always want to share links to upstream, which is the repository all contributors request to merge their PRs. A link to origin is pretty much useless.

**Comment by alexr00** [comment]
The permalink command will make a link to your upstream, but I'm not sure if the head command has ever done this. Would the permalink command work for you?

**Comment by cbrnr** [comment]
You are right, the permalink links to upstream, but head links to origin. It's not a big deal, maybe I'm the only one who would like an "upstream head" link, but a permalink is also fine. I guess at some point some customization would be nice, such as

- which options to show in the context menu
- offer permalink and head options for both origin and master and let users decide what they want to see in their context menu

**Comment by cbrnr** [comment]
Regarding the default repository when creating a PR, the extension was using `upstream` as the default choice (which is great and probably what most people want). However, with some recent update of the extension, the default repository has changed to `origin`. Unless this was intentional, would it be possible to investigate and revert this change? If it was intentional, what is the rationale behind setting `origin` as the default repo for a PR?

BTW, #829 seems to be related.

**Comment by alexr00** [comment]
Adding a "auto" option that will solve this here: https://github.com/microsoft/vscode-pull-request-github/pull/5860
