### ISSUE TITLE
Design feedback on Description editor

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-pull-request-github#52]
![image](https://user-images.githubusercontent.com/2193314/41948576-41e92e4e-7972-11e8-8a47-ba1ddcf67eba.png)

- Everything is far too wide, long line lengths make text hard to ready
- Icon is ugly
- The text should match the markdown preview defaults, this should make it look a lot better'
- Blockquotes have 0 vertical padding
- @ people should be bold (+links?)
- Line heights are inconsistent

    ![image](https://user-images.githubusercontent.com/2193314/41948687-bddf5280-7972-11e8-94ac-69e693d05b67.png)

**Comment by kieferrm** [comment]
The icon needs to be the official GH pull request icon.

**Comment by rebornix** [comment]
Close this issue as we have detailed issues tracking the overview page design.
