### ISSUE TITLE
Allow to mark a file as "reviewed"

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-pull-request-github#520]
My workflow with pull requests goes typically like this:
* download a patch of the change
* apply it locally
* go to the changes view
* review a file
* once done with a file, stage it

I am missing the last part and this blocks me from using this extension in my day to day workflow for more complex changes.

**Comment by Tyriar** [comment]
@bpasero can you not just review the files in order and keep track of which file you're up to?

**Comment by bpasero** [comment]
@bpasero I like to jump around a lot when reviewing and typically go in order that is not reflected by the alphabetic sort order

**Comment by justinliew** [comment]
I may look into this, as I definitely like to use this sort of workflow when doing PRs.

**Comment by justinliew** [comment]
Cool, that's great inspiration! I will start looking into this.

**Comment by justinliew** [comment]
If anyone wants to take this one, I'm having a bit of trouble as the decoration type UI stuff I'm super unfamiliar with. I will keep looking at it if nobody else does but I'm taking on some easier ones to get more familiar with the project first.

**Comment by Tyriar** [comment]
@justinliew this one is probably best to go through our UX people first as it's not clear what the flow will look like.

**Comment by justinliew** [comment]
Sounds good. I'll keep watching this one but leave the design for the people with the know-how/expertise to ensure consistency.

**Comment by lmenus** [comment]
Hello, are there any updates on this? +1, would love to use this feature!

**Comment by doupp-adsk** [comment]
This gets a +1 from me as well.

**Comment by doupp-adsk** [comment]
Coming back to this to point out that there is UI already in the web to do something like this. Details are here: 

https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/reviewing-proposed-changes-in-a-pull-request#marking-a-file-as-viewed

![Mark as read on github.com](https://help.github.com/assets/images/help/pull_requests/viewed-checkbox.png)

I could easily see this as a checkbox in the tree view.

**Comment by dentuzhik** [comment]
This issue relates to [this issue](https://github.com/microsoft/vscode-pull-request-github/issues/1278) as well, and for me I have to review PR in two places, one in VSCode because of a nice tree structure and editor, and another in Github to mark file as viewed. Would be great to have it in VSCode.

Can somebody maybe point to the place in source where one might think implementing this?
\cc @RMacfarlane sorry for direct ping, maybe you can help :)

**Comment by RMacfarlane** [comment]
Hey @dentuzhik!

There isn't a way to render a checkbox in the tree, but we could show a checkmark decoration next to files that are marked as viewed. In the below screenshot, the diamond and letter indicating the git status are tree decorations:
![Screen Shot 2020-02-04 at 10 22 19 AM](https://user-images.githubusercontent.com/3672607/73774108-4df71300-4738-11ea-8213-aff69cce6a09.png)
These are implemented [here](https://github.com/microsoft/vscode-pull-request-github/blob/2285fdc17d20ce325163c23215f5fabc7a923be9/src/view/treeDecorationProvider.ts) and [here](https://github.com/microsoft/vscode-pull-request-github/blob/2285fdc17d20ce325163c23215f5fabc7a923be9/src/view/fileTypeDecorationProvider.ts).

We could have an inline action or an entry in the context menu for marking the file as viewed, there are some examples of that [here](https://github.com/microsoft/vscode-pull-request-github/blob/2285fdc17d20ce325163c23215f5fabc7a923be9/src/commands.ts).

I just tried looking through the GitHub API docs (both v3 and v4) to see what calls we would need to make to get which files are already marked as viewed, and I wasn't able to find anything about it. I'm not sure if the API is not publicly available, or if I just missed it. Let me know if you're able to find it! I'd love to take a PR for this.

**Comment by dentuzhik** [comment]
Much appreciated help, thank you 🙌 
I will look over the code and see if I can make something work :)

**Comment by dentuzhik** [comment]
I'm glad that this got into the backlog :D

A year has passed, but it seems that there's actually a v4 version of this API available, so 🤞🏼  we'll see this some time soon!
https://docs.github.com/en/graphql/reference/mutations#markfileasviewed

**Comment by RMacfarlane** [comment]
Viewed files are now decorated with a checkmark, and there's an inline action to mark them as viewed/not viewed:
![mark-as-viewed](https://user-images.githubusercontent.com/3672607/115309347-fff1e380-a120-11eb-8bb6-60ebf7ad10bd.gif)

**Comment by jillesmc** [comment]
@RMacfarlane. Could you tell me how can I enable that?
I'm using version 0.25.1, but there is no inline actions for me.

**Comment by RMacfarlane** [comment]
This hasn't been released yet, we follow the same shipping schedule as VS Code, so should have a new version two weeks from now.

In the meantime if you want to try it out, you can use the Nightly version of the extension: https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github-insiders

(Note that the Nightly and Stable versions of the extension can't be installed side by side since their commands will conflict, so you will have to uninstall the Stable version to use Nightly)

**Comment by jillesmc** [comment]
Thank you @RMacfarlane. You guys are doing an amazing job.
