### ISSUE TITLE
GitHub Pull Requests extension is making too many requests to GitHub

### ISSUE THREAD

**Issue by cristianderudi** [microsoft/vscode-pull-request-github#5202]
I am receiving this notification:

The GitHub Pull Requests extension is making too many requests to GitHub. This indicates a bug in the extension. Please file an issue on GitHub and include the output from "GitHub Pull Request".

When I open a pull request, the extension makes many requests to GitHub. This causes delays and errors in Visual Studio Code.

I have tried restarting Visual Studio Code and uninstalling and reinstalling the GitHub Pull Requests extension, but the problem persists.

I hope you can help me resolve this issue.

**Comment by cristianderudi** [comment]
I'm still learning how to use GitHub. This is happening when I open Visual Studio Code and go to the "Source control" section. The text I mentioned in my first message appears below at that moment. I'll try to send you a screenshot. Please let me know how to proceed depending on what you need.
![screenshot-cdn discordapp com-2023 08 31-18_09_55](https://github.com/microsoft/vscode-pull-request-github/assets/124323516/5b487c5a-6c83-4178-9bff-463117c74bba)

**Comment by mauritz-lovgren** [comment]
Getting the same, I am suspecting the reason is that I have many folders (15) open in the workspace, and that this plugin is querying PRs for all of them too quickly?

**Comment by alexr00** [comment]
> Getting the same, I am suspecting the reason is that I have many folders (15) open in the workspace, and that this plugin is querying PRs for all of them too quickly? 

You're probably right! I've removed this error for non-enterprise repos. The error was intended to prevent too many requests in too short a time, but it has turned out to be too noisy. The new version with the error removed should be available later today.
