### ISSUE TITLE
Action permission in Repo settings

### ISSUE THREAD

**Issue by SRIDIVYAACHUTHA** [microsoft/vscode-pull-request-github#5207]
Hi Team,
We want to change the version in our github repo settings (Allow specified actions and reusable worfklow), but we don't have the permissions to change it. This is for codescan upgrade,Can you please help on this.

Please find the attached screenshot.

Thanks,
Sri Divya

<img width="1249" alt="Screenshot 2023-08-29 at 12 20 35 PM" src="https://github.com/microsoft/vscode-pull-request-github/assets/95206702/ae00b715-5e33-4d13-9082-da40f384c711">

**Comment by alexr00** [comment]
This repository is for the GitHub Pull Requests and Issues VS Code extension. It looks like you're referencing something on github.com.
