### ISSUE TITLE
Get a list of all (unresolved) comments

### ISSUE THREAD

**Issue by brettcannon** [microsoft/vscode-pull-request-github#5209]
I have two reasons why I would love to have a view in the side panel that lists all comments, especially unresolved ones (or even just unresolved; I don't really care about resolved comments).

First is GitHub has a setting to block merges on any PR that have unresolved comments. That means having an easy way to make sure you have resolved every comment can be important.

Two is if I read the comments on github.com and then open up VS Code, I typically want to jump to a specific comment, but right now I have to cycle through all comments to find it. Have a direct way to view all comments so I can jump straight to the one I'm interested in would be handy.

**Comment by alexr00** [comment]
I think the existing Comments view does what you want:
![Recording 2023-08-29 at 14 23 26](https://github.com/microsoft/vscode-pull-request-github/assets/38270282/697861f5-6c27-4499-9861-b145f62885ad)

**Comment by alexr00** [comment]
By default, we open the Comments view the first time you open a file with commenting enabled in a session. Do you have this disabled? The setting is `comments.openView`.
