### ISSUE TITLE
x-github-request-id not in the rate_limit response

### ISSUE THREAD

**Issue by vcfvct** [microsoft/vscode-pull-request-github#521]
- Extension version: 0.16
- VSCode Version: 1.27.2
- OS: MacOS High Sierra

Steps to Reproduce:

@shana , Thanks for this great extension. It works great for my personal github. However whenI was trying to set it up against our Enterprise github, the ui does not show up. 

Below is the response Header I get from `curl -I https://github.MyOrg.com/api/v3/rate_limit`
```
HTTP/1.1 401 Unauthorized
Cache-Control: no-cache
Content-Type: text/html
WWW-Authenticate: Basic realm="GitHub"
Connection: keep-alive
```

When I debug the extension, looks like [`x-github-request-id`](https://github.com/Microsoft/vscode-pull-request-github/blob/master/src/authentication/githubServer.ts#L145) header for the `/rate_limit` call. Hence the `host` will get a `false`.

In the `OUTPUT` of this extension, I get `No GitHub remotes found`. 

Any ideas? Thanks!

**Comment by shana** [comment]
@vcfvct That's all the headers you get, nothing else? Any other headers that might have start with `x-github`?

Looks like the `WWW-Authenticate` might be a good fallback in this case.

**Comment by shana** [comment]
@vcfvct What do you get if you run `curl -H 'content-type: application/json' https://yourserver.com/api/v3/meta`. Does it return something?

@queerviolet Desktop does this check differently by using the `/meta` endpoint (https://github.com/desktop/desktop/blob/master/app/src/lib/api.ts#L753), this might be a good fallback if it works.

**Comment by vcfvct** [comment]
@shana , the response I get from `curl -H 'content-type: application/json' https://yourserver.com/api/v3/meta` is:
```
<html><body><h1>401 Unauthorized</h1>
You need a valid user and password to access this content.
</body></html>
```

No luck, Thanks.
