### ISSUE TITLE
Can't view any comments in comments view

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode-pull-request-github#5210]
Testing #5206

I wasn't able to view comments outside of the description page, either on initial load or after refreshing either the full PR or the comments view.

https://github.com/microsoft/vscode-pull-request-github/assets/25163139/edd48bd4-cd8b-4ed0-a5bb-e81a84c4ac6f

**Comment by alexr00** [comment]
I cloned your repo but I still can't reproduce the issue. Can you:
- Set the log level of GitHub Pull Request to debug
- Hit the refresh button on the comments view 
- Share the output from GitHub Pull Request

**Comment by daviddossett** [comment]
Tried this several more time and can't repro this issue. Closing but will let you know if I see this ever again.
