### ISSUE TITLE
GHPRI doesn't render suggestions in comments containing one-line deletions

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-pull-request-github#5211]
1. Open this review comment in GitHub and VS Code https://github.com/microsoft/vscode/pull/191505#discussion_r1307778662
2. :bug: the suggestion doesn't appear in VS Code

On GitHub

![Image](https://github.com/microsoft/vscode-pull-request-github/assets/30305945/4d8a9edf-5138-403e-a0ff-7a5a7144bc99)

In VS Code

![Image](https://github.com/microsoft/vscode-pull-request-github/assets/30305945/c810b0ae-afb3-4d86-86fe-1517ae5f0159)

**Comment by rzhao271** [comment]
Maybe, though it might be better to include a `-` for users with colour vision deficiency
![New change showing a red rectangle with the line number, indicating the suggestion is to remove that line](https://github.com/microsoft/vscode-pull-request-github/assets/7199958/4b084c4c-9fe5-4293-9fab-f6f2503b314d)
