### ISSUE TITLE
When using the arrow keys with a screen reader enable in the "Comment" field, screen readers read the whole comment instead of reading the character where the cursor is located

### ISSUE THREAD

**Issue by daniel-montalvo** [microsoft/vscode-pull-request-github#5214]
Type: <b>Bug</b>

To replicate.

1. Checkout a PR
1. Open an editor with a changed file where you want to make comments
1. Select the part  of the text where you want to comment
1. Use the "Add comment on current selection" command.
1. Type some text.
1. Use the right, left, up, and down arrow keys to move through the text to proofread it.

Expected result: Right, left, up, and down arrow keys behave just like in the regular editor. 

- Pressing up or down arrow keys makes screen reader speak the line where the cursor is located.
- Pressing right or  left arrow keys makes screen readers speak the character where the cursor is located.
- Pressing CTRL + left or right arrow key makes screen readers speak the word where the cursor is located.

Obtained behavior: Whatever combination of arrow keys is pressed, screen readers seem to either read the whole text comment or to say "blank".

- Both NVDA and JAWS read the whole comment text when pressing left and arrow keys
- NVDA reads the first character of the text when pressing up or down arrow keys
- JAWS says "blank" when pressing up or down arrow keys

Extension version: 0.71.2023083009
VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (6.35GB free)|
|Process Argv|--crash-reporter-id 1f62659b-b510-4103-8662-f773a43c0887|
|Screen Reader|yes|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|Memory (System)|7.67GB (6.58GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
3biah626:30602489
f6dab269:30613381
showlangstatbar:30737416
a2ce3375:30757347
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofb:30804716
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572

```

</details>

**Comment by alexr00** [comment]
Will be fixed by https://github.com/microsoft/vscode/pull/191828
