### ISSUE TITLE
Failure to edit a pending comment

### ISSUE THREAD

**Issue by spangaer** [microsoft/vscode-pull-request-github#5216]
- Extension version: v0.70.0
- VSCode Version: 1.81.1
- OS: Win 10.0.19045

Steps to Reproduce:

1. Start a review
2. Submit a (pending) comment
3. Try to edit and save the comment

![image](https://github.com/microsoft/vscode-pull-request-github/assets/677147/11b87f1d-ec56-4c20-bcaf-f135cc3e10ee)

So somehow it seems to detect the edit as a reply, which is weird twice, because:

1. I can just edit the comment in the GH web UI in browser
2. I can also add pending replies to pending comments in the GH web UI in browser

So it looks like the client side state and constraints are somewhat bogus.

**Comment by alexr00** [comment]
The issue is that the comment has not yet been submitted on GitHub at the time that you're trying to edit it. I'll disable the Edit, delete, and copy actions until the comment has been fully submitted.
