### ISSUE TITLE
Add +/- to added/deleted lines in PR description

### ISSUE THREAD

**Issue by griggi-ws** [microsoft/vscode-pull-request-github#5224]
Type: <b>Bug</b>

1. Start a review by adding some comments with multi-line suggestions. 
2. View the PR by double-clicking the comment in the Comments tab below.

How it looks in the changed file view:
<img width="851" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/108762141/34ba08fd-454d-4cbc-ab95-7b76e90cb207">

How it looks in the PR view:
<img width="584" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/108762141/629145d2-5a4e-4d4b-84a7-2148a6f1e78c">

This is not useful formatting, at a glance it should be obvious what the actual suggested change is - at minimum a minus prepended would be a huge difference. With suggested changes that are just removals, the suggestion appears to be nothing more than restating what's already there. 

Extension version: 0.70.0
VS Code version: Code 1.81.1 (Universal) (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:20:33.924Z)
OS version: Darwin x64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 5, 5|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|--crash-reporter-id e20ab28d-80b8-49ba-88d3-d1bb6ae9ddd9|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30792227
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
3biah626:30602489
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
a2ce3375:30757347
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
synctok:30821570
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572

```

</details>

**Comment by alexr00** [comment]
It looks like you're one version behind on the extension. The latest version includes colors here: 
<img width="306" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/38270282/44eaae13-b6f0-4b98-81d6-6942c1e3ac2e">

Looks like the +/- should be easy to add too!

**Comment by alexr00** [comment]
With +/-:

<img width="290" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/38270282/47be2e2f-08c7-453d-953b-d34a4e9a863e">
