### ISSUE TITLE
Open default editor for added files instead of diff editor

### ISSUE THREAD

**Issue by CombeeMike** [microsoft/vscode-pull-request-github#5227]
When opening a file for review from the pull requests view, it always opens in the diff editor, which is perfectly fine for files with changes, but rather inconvenient for files which have been newly added in the PR for a few reasons:

* When having the diff editor set to "split mode", one half of the screen (editor) is always empty without any kind of gain.
  I usually use the "split mode", so I'd always have to toggle between split & inline mode when going from a newly added file to a changed file and vice versa to "work around this".
* Split & inline mode: All lines are highlighted as "newly added" (some background color which covers the whole editor area in my current color theme) which I conceive as unnecessarily distracting and which makes it harder for me to concentrate on the code at hand.

ATM, I'm not opening added files from the pull requests view anymore but open them in the normal editor using VS Codes file search etc.

Whilst this basically works since I can comment and see existing comments there as well it has the downside that I have to switch between 2 "usage modes" (open from pull requests view & using "VSCode built ins") which is a minor but nonetheless additional mental burden and distraction from the review task at hand.

# Feature request

Either always open the normal editor instead of the diff editor when reviewing newly added files or add some setting to make this behavior configurable.

**Comment by alexr00** [comment]
There's already an action in the tree to open the file and not the diff: 
<img width="383" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/38270282/22c9ff84-1381-435e-b3e3-55052b33d0a2">

Is this enough, or do you still think we should have a way to always open added files as files, not as diffs?

**Comment by CombeeMike** [comment]
@alexr00 Thanks for pointing that out, I completely missed this until now 🙈
Whilst this does help & makes things noticable easier, I'd still love to see the default behavior changed or have an option for it as explained in my initial post simply because I don't see no gain in opening the diff editor in those situations but only drawbacks.

**Comment by CombeeMike** [comment]
@alexr00 Thank you very much for implementing this 🎉!

The explicit "Open file" button turned out to be a very good alternative but it doesn't really make it into my "muscle memory" which is why I oftentimes still open the diff view first, close it & then use this button.

Off topic:
I really like the way you're handling issues reported here in general. Always fast feedback, always helpful, always looking for meaningful solutions, always very friendly 👌🙏

**Comment by alexr00** [comment]
To verify:
- Install the pre-release version of GitHub Pull Requests and Issues
- Find a PR that has an added file
- Click on the tree node for the added file. Verify that a diff isn't opened and instead the file is just opened.

**Comment by alexr00** [comment]
@CombeeMike thanks for verifying!
