### ISSUE TITLE
Consider not showing issue / user completions in SCM input box without trigger character

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-pull-request-github#5228]
1. Open SCM input box, clear input
2. Ctrl+space to bring up suggest widget
3. :bug: there are issue and user completions even though I do not have a # or @ character preceding the cursor

This seems to have been intentional but it does result in the completion list having lots of items, could we consider not returning these if there's no trigger character even in the SCM input or comments widget? I would also be happy with a language ID filter similar to `githubIssues.ignoreCompletionTrigger`, such as `githubIssues.ignoreCompletionsForLanguage`, as I do find these completions useful, I just don't want them in the SCM input without the trigger character.

https://github.com/microsoft/vscode-pull-request-github/blob/43aab2df2314f9d34fd2f753a05c814e54ac2510/src/issues/issueCompletionProvider.ts#L57-L66

**Comment by alexr00** [comment]
It was intentional, but it's early in the milestone. Let's change it and see if anyone has a problem with it.

**Comment by alexr00** [comment]
Someone has a problem with it :) ttps://github.com/microsoft/vscode/issues/193513

I'm going to revert.
