### ISSUE TITLE
Command to go to next diff section in PR

### ISSUE THREAD

**Issue by ThomsonTan** [microsoft/vscode-pull-request-github#5238]
Is there a command which could move focus to the next section of diff in a PR? "workbench.action.compareEditor.nextChange" can do this but it is only for a given file, and cannot move focus to the diff in the next file if it reaches the end of current source file.

Not sure if "pr.goToNextDiffInPr" can do it and haven't tried it successfully.

**Comment by alexr00** [comment]
`pr.goToNextDiffInPr` is the way to do this. Can you share of gif of this not working for you?

**Comment by ThomsonTan** [comment]
I added below keyboard mapping below which seems does nothing for the shortcut, tried change to to the commented out command which seems working but it does navigation in a single file. Is it used correctly here?

{
    "key":      "ctrl+n",
    // "command":  "workbench.action.compareEditor.nextChange",
    "command": "pr.goToNextDiffInPr",
},

**Comment by alexr00** [comment]
That should work across files until it gets to the last change in the "last" file, at which point it shows a notification. Do you see the nofication?

**Comment by ThomsonTan** [comment]
Thanks for a pointer, does the same config on another device and it worked. Close it for now.
