### ISSUE TITLE
No bottom padding in view

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-pull-request-github#5239]
The view is scrolled all the way down:

![Image](https://github.com/microsoft/vscode-pull-request-github/assets/22350/ac4f0add-e5cc-41f0-b184-770d73200491)

**Comment by alexr00** [comment]
There is bottom padding, it's just the first thing to go when the view gets too small

<img width="270" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/38270282/23ae8180-9751-42e6-b3d3-b471694b7cc9">

**Comment by joaomoreno** [comment]
I'm not sure "removing bottom padding when the view needs to scroll" is an established pattern. We don't do it for other scrollable views in the workbench (editor, trees, settings editor, etc.). And feels inconsistent to do it for the bottom padding and not for the top padding. Ultimately I think it just looks inelegant, as if we actually just forgot to add padding there.

**Comment by hbons** [comment]
Agree the bottom padding shouldn't disappear when the view is small. I can have a look.
