### ISSUE TITLE
Cache PR metadata to reduce requests/wait time

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#524]
Repro:

1. Open a repo
2. Expand "All", wait several seconds for it to complete
3. Expand "Created by Me" and "Assigned to Me", they take several seconds to expand as well when all the data should have been fetched when expanding "All"?

**Comment by alexr00** [comment]
We do cache the PR data now. However, we still need run the query on GitHub to see which PRs actually satisfy the query.
