### ISSUE TITLE
Support commenting on code removals

### ISSUE THREAD

**Issue by bradycharron** [microsoft/vscode-pull-request-github#5241]
There does not appear to be a way to comment on code removals with the VSCode plugin.  This is a function of github.com pull requests.

![code-removal-inability-to-comment](https://github.com/microsoft/vscode-pull-request-github/assets/46324860/df16f2e5-4763-44e8-9fa1-0dadedb8579c)

**Comment by alexr00** [comment]
You can comment on deleted lines if you change your diff to side-by-side: `"diffEditor.renderSideBySide": true`

**Comment by bradycharron** [comment]
Thanks for the information @alexr00, this does appear to work.  Is there any documentation about this?

**Comment by alexr00** [comment]
Just in issues. This came up in another place recently and I opened https://github.com/microsoft/vscode/issues/192990 to track this.
