### ISSUE TITLE
SCM commit message issue integration doesn't work well for <user>/<repo>#

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#5247]
It references issues from the current repo:

![Image](https://github.com/microsoft/vscode-pull-request-github/assets/2193314/88d4e39f-55b3-4305-9bb4-01d9b1c32748)

Ideally it would pull in the corresponding repo, but it would be better to do nothing instead of the current behavior.

**Comment by alexr00** [comment]
> Ideally it would pull in the corresponding repo, but it would be better to do nothing instead of the current behavior.

Running a new query when suggest is triggered is a bit slow. If you already have queries set up to get issues from the `owner/repo` that precede the `#`, then I can filter to just include those.

**Comment by joyceerhl** [comment]
This doesn't work for me :/ 
<img width="585" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/30305945/17793c4c-0808-49a9-8440-22b96ec5cfc3">

**Comment by alexr00** [comment]
@joyceerhl which repo did you have open and what do you have `githubIssues.queries` set to? We still use the values you have for `githubIssues.queries` to populate the suggest.

**Comment by Tyriar** [comment]
Autocomplete doesn't work for me at all on the vscode repo, 

xterm.js:

![image](https://github.com/microsoft/vscode-pull-request-github/assets/2193314/95d99c3c-b5f2-4afa-8b05-6ad94c6b345a)

VS Code:

![image](https://github.com/microsoft/vscode-pull-request-github/assets/2193314/74a39f12-b180-4718-b59e-1df794e5193c)

Queries:

```json
  "githubIssues.queries": [
    {
      "label": "My Issues",
      "query": "default"
    },
    {
      "label": "Created Issues",
      "query": "author:${user} state:open repo:${owner}/${repository}"
    },
		{
			"label": "Luna",
			"query": "is:open repo:lunapaint/luna sort:updated-desc"
		}
  ],
```

I expect the vscode ones to be pulled in from created issues + my issues.

FWIW The Luna query does work in the xterm.js window, not the vscode window though.

**Comment by alexr00** [comment]
@joyceerhl and @Tyriar can you both please:
- Share a screenshot of the Issues view. Does it show the results from your queries?
- Set the default log level of GitHub Pull Request to debug, reload, wait a moment for the extension to activate and the queries to run, repro, then share the output of GitHub Pull Request?

**Comment by Tyriar** [comment]
Mine doesn't load in the vscode window:

![image](https://github.com/microsoft/vscode-pull-request-github/assets/2193314/c65d550f-76ee-497d-a67f-e2a526148459)

[ghpri.log](https://github.com/microsoft/vscode-pull-request-github/files/12750332/ghpri.log)

**Comment by alexr00** [comment]
@Tyriar since you don't have any issues in the Issues view it makes sense that the issue suggestions don't work. I don't see why the issues view is broken, but I'm adding some logging to try to understand why.

**Comment by joyceerhl** [comment]
I initially misunderstood the feature, this worked for me in microsoft/vscode:

```
  "githubIssues.queries": [
    {
      "label": "My Issues",
      "query": "default"
    },
    {
      "label": "Created Issues",
      "query": "author:${user} state:open repo:${owner}/${repository}"
    },
		{
			"label": "GHPRI",
			"query": "is:open repo:microsoft/vscode-pull-request-github sort:updated-desc"
		}
  ],
```
![image](https://github.com/microsoft/vscode-pull-request-github/assets/30305945/998e9b69-22d2-4289-bf10-0ddf821e01d8)

**Comment by alexr00** [comment]
Thanks for verifying @joyceerhl! 

@Tyriar I've moved everything related to your new issue into https://github.com/microsoft/vscode-pull-request-github/issues/5311.
