### ISSUE TITLE
Using "Create an Issue" a 2nd time does not create a new issue, but a NewIssue.md with tons of numbers

### ISSUE THREAD

**Issue by rbability** [microsoft/vscode-pull-request-github#5253]
- Extension version: 0.72.0
- VSCode Version: 1.82.2
- OS: Windows

Steps to Reproduce:

1. With an opened Repo, Switch to the GitHub Extension
2. In the Issues Section click on the + to create a new issue.
3. It creates a new issue template that looks fine.
4. Close the issue Tab that just opened without editing anything and without saving it.
5. Click on the + to create a new issue again.
6. The outcome is what I will try to attach as a screenshot.

![image](https://github.com/microsoft/vscode-pull-request-github/assets/59822243/08ccc2ab-81f3-4b1b-b402-4233934fe4c6)

You have to restart VS Code to get it working again.

**Comment by alexr00** [comment]
Thanks for reporting this!
