### ISSUE TITLE
Open pull request without opening a local repo

### ISSUE THREAD

**Issue by ThomsonTan** [microsoft/vscode-pull-request-github#5255]
It seems currently that a local git repo is required and should be opened before listing and opening the PRs in the repo. Is it possible to give a PR URL on github and open it in this extension, even this repo is not cloned and opened in vscode?

**Comment by alexr00** [comment]
@ThomsonTan you might be interested in https://marketplace.visualstudio.com/items?itemName=GitHub.remotehub, which this extension is compatible with. You can browse GitHub repos easily without cloning a repo using that extension. You might also be interested in https://vscode.dev/ which uses that same extension to let you view GitHub repos in VS Code from your browser.
