### ISSUE TITLE
Auto populate PRs with specified labels

### ISSUE THREAD

**Issue by kkornienko-aparavi** [microsoft/vscode-pull-request-github#5258]
I'm always have to manually specify a couple of labels for ALL PRs. It's boring.
It'd be really handy if the GitHub Pull Requests extension do it for me!

Proposed configuration:
```
"githubPullRequests.pullRequestLabels": ["devops", "new feature"] 
```

Maybe other users of this brilliant extension also find this feature useful.
In case one or more labels are not applicable for a repository, they just can be skipped.

**Comment by kkornienko-aparavi** [comment]
I know that it's can be done using GitHub Actions, but is not very convenient in my case, because we have a lot of different repositories and GitHub Action should be copied into all of them

**Comment by Ari-Kishon** [comment]
This would be very useful for me aswell!

**Comment by umakantv** [comment]
I would like to work on this.

**Comment by umakantv** [comment]
@kkornienko-aparavi @alexr00 

While working on this issue, I observed that 

- If a user wants to keep these settings on workspace level in `.vscode/settings.json` and  
- If `.vscode/settings.json` is added to version control (which is not uncommon)

Workspace level settings would cause conflict in the preferences for other team members using this configuration, as other members might want to have different preferences.

<img width="1399" alt="Screenshot 2024-01-25 at 1 34 57 AM" src="https://github.com/microsoft/vscode-pull-request-github/assets/41837826/108d971e-9cbc-45c0-91af-d9b28ba3441d">

In that case, the others options are to either move to user-level configurations or to remove `.vscode/settings.json` from the version control. In my opinion, the first option is still feasible to some extent, given the use-case that one would want to configure this setting for all projects.

One slight detail that helps us is that we could filter only the labels that are present in the repository from the configured default labels in the user-level settings.

**Comment by umakantv** [comment]
> One slight detail that helps us is that we could filter only the labels that are present in the repository from the configured default labels in the user-level settings.

By this, I mean the following:
```ts
// Fetch labels from the repo and filter with case-sensitive comparison to be safe,
// dropping any labels that don't exist on the repo.
const labels = await this._folderRepositoryManager.getLabels();
const defaultLabels = labels.filter(label => defaultLabelValues.includes(label.name));
```

**Comment by alexr00** [comment]
To verify: 
- Install the pre-release version of the GitHub Pull Request extension
- Look at the setting `githubPullRequests.labelCreated`. Verify that you understand what it does.
- Try out `githubPullRequests.labelCreated`. Verify that labels included in that setting are automatically added to PRs that you create.
