### ISSUE TITLE
support for creating a new pull request

### ISSUE THREAD

**Issue by softprops** [Microsoft/vscode-pull-request-github#526]
I've looked and was surprised I couldn't find any documentation on how to open a new pr. I was wondering if this is possible. If not, I've love to see support for it. I could picture the pull request template experience to be pretty great in vscode.

**Comment by RMacfarlane** [comment]
This is currently not supported, but something we plan to add. There's an existing issue on this (https://github.com/Microsoft/vscode-pull-request-github/issues/283), so I'll close this as a duplicate. Thanks!
