### ISSUE TITLE
add a `Make suggestion` command

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode-pull-request-github#5261]
@jooyoungseo was wondering if we could add a command to make a suggestion vs having to go through the create comment command and tabbing. 

@alexr00, I imagine you want to align with the git experience, as it currently does. 

What do you think of this?

**Comment by alexr00** [comment]
> I imagine you want to align with the git experience, as it currently does.

I'm not sure I know what this is. How do you make a suggestion with git?

Suggestions are a GitHub PR concept, so the command would need to come from the extension. This seems like a reasonable request.  

I don't think it's currently possible with the comments API we have, but I think we can easily accomplish it by allowing the `workbench.action.addComment` to take an additional argument for `initialBody` or `initialContent`.

**Comment by alexr00** [comment]
> I don't think it's currently possible with the comments API we have, but I think we can easily accomplish it by allowing the workbench.action.addComment to take an additional argument for initialBody or initialContent.

Adding the `initialBody` argument is non-trivial. A quicker solution would be allowing the "Make suggestion" command to be run with a keybinding when the comment widget is open. So the flow would be:
1. Find a commenting range
2. "Create comment" command
3. "Make suggestion" command

What do you think?

**Comment by meganrogge** [comment]
I think that makes sense. 

Then, a user can use the `runCommands` feature to chain the commands together if they so choose.

**Comment by alexr00** [comment]
Another options: In VS Code core can we have commands for "run first action on comment", "run second action on comment'...?

**Comment by meganrogge** [comment]
I believe in this case, JooYoung was hoping that it would create a new comment and trigger the make a suggestion action for that one. When a comment is created, I would imagine you could set that as the active one and thus know which comment this command applies to?

**Comment by alexr00** [comment]
That is one of my suggestions in https://github.com/microsoft/vscode-pull-request-github/issues/5261#issuecomment-1924088603. I will bring to the next API meeting to determine the best approach. I see 3 options:

- Run nth action commands for comments
- Let extension's provide an ID
- Add the concept of an "active" comment
