### ISSUE TITLE
Feature Request: Integrate GitHub Discussions with the GitHub Pull Requests for Visual Studio Code Extension

### ISSUE THREAD

**Issue by asilverman** [microsoft/vscode-pull-request-github#5264]
## Description:
I'd like to request the integration of GitHub Discussions functionality within the "GitHub Pull Requests for Visual Studio Code" extension. The main purpose is to allow users to participate in, manage, and keep track of discussions in their repositories without leaving the VSCode environment.

## Challenges:
**Complexity:** GitHub Discussions, though similar in some ways to issues, have their unique characteristics (e.g., categories, upvotes). The design and integration should account for these nuances.

**Real-time Updates:** Discussions are dynamic, with potential for rapid new posts and comments. Ensuring that users get real-time or near-real-time updates might be a challenge.

**UI/UX Design:** Since Discussions can have varied lengths and nested comment threads, an intuitive and effective display will be crucial.

## Opportunities:

**All-in-One Workspace:** Developers can seamlessly move from writing code to participating in discussions, streamlining their workflow.
**Increased Engagement:** By lowering the barrier to entry (no need to switch tools or platforms), developers might be more likely to engage in discussions, fostering a better community.
**Notifications:** With proper notification integration, developers can be alerted about new discussion posts or replies directly in VSCode.

## Value Proposition:
**Competitive Edge:** Many extensions offer GitHub issue and PR integration, but by incorporating Discussions, this extension can further differentiate itself in the marketplace.
**User Retention & Growth:** Current users will find added value, reducing the chances of them moving to a different extension, and new users might be attracted to this unique feature.

**Enhanced Collaboration:** GitHub Discussions is becoming an essential tool for community discussions. Integrating it will significantly enhance the collaboration capabilities of this extension.

## Closing thoughts:

The integration of GitHub Discussions will make the "GitHub Pull Requests for Visual Studio Code" extension even more powerful and helpful. Recognizing that it's a sizable undertaking, I believe the potential benefits for users and maintainers alike justify the effort.

Thank you for considering this feature request, and I'm excited to see how this extension evolves!

**Comment by asilverman** [comment]
I'm not sure why is this out of scope??

**Comment by alexr00** [comment]
We don't plan to implement this, so I've closed it as out of scope. We're currently going through all the issues that the VS Code team owns: https://github.com/microsoft/vscode/wiki/Issue-Grooming

**Comment by jonpeake** [comment]
@alexr00 is there any chance of this feature request being revisited? It seems like many developers are switching to GitHub discussions as a first step for triage and Q&A to avoid diluting the Issues pool. Having access to these through the IDE would be very helpful for keeping track of development in repos of interest.

**Comment by alexr00** [comment]
Based on our current roadmap, I don't think this would get implemented in even the next 2 years. I'll reopen, as I do see that there's more use of Discussions, but there's no plan to implement it at this time.

**Comment by asilverman** [comment]
@alexr00 maybe you could share a link to the roadmap or describe at a high level what it is assuming that you are seeking transparency ❤️

**Comment by alexr00** [comment]
Team iterations plans are always posted here, and are updated weekly: https://github.com/microsoft/vscode/issues?q=is%3Aissue%20state%3Aopen%20label%3Aiteration-plan

Roadmap is here, and sadly is way out of date. It's usually updated once or twice per year: https://github.com/microsoft/vscode/wiki/Roadmap#scm--pull-requests
Our focus right now in this extension, which can be gleaned by reading consecutive team iteration plans (yes, not the most obvious way to state our focus), is on integrating the GitHub coding agent and maintaining/improving quality.
