### ISSUE TITLE
Unexpected error when commenting on PR changes

### ISSUE THREAD

**Issue by JordanLongstaff** [microsoft/vscode-pull-request-github#5267]
I just tried to view some changes in a pull request in VS Code and leave a comment. As soon as I clicked the `+` on a line, VS Code tried to open something on the side, but failed, and it showed this instead: 
![Screenshot 2023-09-21 at 6 29 17 PM](https://github.com/microsoft/vscode-pull-request-github/assets/7563922/973c9739-14c5-46b6-86b1-aa42f159650e)

- Extension version: 0.72.0
- VSCode Version: 1.82.2
- OS: macOS Ventura 13.5.2

Steps to Reproduce:
1. Open any file listed in a pull request to open the diff editor.
2. Find any section of changes in either side of the editor and click the `+` next to the line number to start a comment.
3. Boom, unexpected error.

**Comment by alexr00** [comment]
This is strange, it looks like something is trying to open the comment editor, which should only show within the comment widget, to the side, as a full editor.

Can you please do the following:
- disable all other extensions and see if the issue still occurs when you try to leave a comment
- share you settings.json file.

**Comment by JordanLongstaff** [comment]
Sorry for not seeing this sooner.

I found the offending extension: [Markdown All in One](https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one). Its purpose is for viewing Markdown files with Markdown formatting, which I find useful because my company's workspace has multiple Markdown files. This setting opens up previews of Markdown files automatically, but it is also what is causing this issue:
```
"markdown.extension.preview.autoShowPreviewToSide": true,
```

**Comment by JordanLongstaff** [comment]
So, a workaround is to simply turn that setting off and open Markdown previews manually.

**Comment by alexr00** [comment]
Thanks for sharing the cause!

**Comment by alexr00** [comment]
I took a look at that markdown extension and also filed this issue: https://github.com/yzhang-gh/vscode-markdown/issues/1342.

I think in general that setting would work better with a fix like the one I suggested there.
