### ISSUE TITLE
Expose command to toggle review mode off / hide UX

### ISSUE THREAD

**Issue by joshuatz** [microsoft/vscode-pull-request-github#5268]
Considering how drastically this extension can change the UX of VS Code if review mode is active (especially with the gutter highlighting), it would be really nice to have an exposed command to toggle the review mode on or off - with 'off' essentially forcing the extension UX to look like it does when there is no PR attached to the current branch, even if there really is.

There are a few justifications / use-cases for this:

- Draft PRs: In many repositories, the use of "draft" PRs are encouraged (either with GitHub's official "draft" feature, or just as a PR that is not marked ready). These are often put up well in advance of a review being ready, but the second you put it up, this extension is going to drastically change the UX while you continue to work on your branch.
- As a PR reviewer: If there are a lot of changes and comments already, sometimes while doing a re-review you really need some time where you have a more minimal UX so you can really focus on the code itself.

A workaround for this is to just create a throwaway branch locally to work off, that is not linked to the remote that has a PR, or just completely disable the extension, but neither of those is an ideal workflow. Code's Zen Mode can also help temporarily hide clutter, but again, not ideal for all scenarios.

PS: This issue aside, this extension has been awesome!

**Comment by alexr00** [comment]
It sounds like the thing you really want is to hide everything related to commenting. You have 2 options:
- The setting `comments.visible`
- The command "Comments: Toggle Editor Commenting"

**Comment by vuon9** [comment]
Thank you! Is there an available way to make it as a shortcut on the status bar? If it's not there yet, would you consider that?

For now, I use the `statusbar-commands` extension with the below settings to quickly toggle this feature; however, official support would be preferable.

```json
"statusbar_command.applicationCommands": [
        {
            "text": "$(eye)",
            "tooltip": "Toggle PR review comments",
            "alignment": "left",
            "command": "workbench.action.toggleCommenting"
        }
    ],
```
