### ISSUE TITLE
Add a setting to disable automatic fetching to detect changes on PR branches

### ISSUE THREAD

**Issue by sascha-wolf** [microsoft/vscode-pull-request-github#5285]
Type: <b>Bug</b>

1. Protect ssh keys
2. Set `githubPullRequests.pullBranch` to `never` and `githubPullRequests.pullPullRequestBranchBeforeCheckout` to `false`
3. Restart VSCode
4. You'll get prompted that VSCode wants to access the SSH key, upon refusal this is logged:

```
2023-09-26 11:17:14.993 [error] FolderRepositoryManager> Error when fetching: sign_and_send_pubkey: signing failed for ED25519 "/Users/sascha-wolf/.ssh/github/sascha.pub" from agent: agent refused operation
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Extension version: 0.72.0
VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T06:00:27.244Z)
OS version: Darwin arm64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by alexr00** [comment]
`githubPullRequests.pullBranch` only controls whether the branch is pulled, not fetched. You get the above log when the extension tries to `fetch` to see if there are any changes.

**Comment by sascha-wolf** [comment]
@alexr00 so how can I disable automatic fetching?

**Comment by alexr00** [comment]
Current, it's not possible.

**Comment by bhardwajakshit** [comment]
Hi @alexr00, I'd love to work on adding this setting into the extension. 

Explored the code and noticed the `updatePullRequest` method, I think we need a pre-execution check in this. More pointers would be awesome! 

<img width="784" alt="Screenshot 2023-11-25 at 5 26 14 AM" src="https://github.com/microsoft/vscode-pull-request-github/assets/66516548/3ed9bd19-b9bf-4448-922e-e56034564550">
<img width="789" alt="Screenshot 2023-11-25 at 5 26 47 AM" src="https://github.com/microsoft/vscode-pull-request-github/assets/66516548/50ad221f-cb0d-42e3-810a-747f39093df6">

**Comment by alexr00** [comment]
@bhardwajakshit thanks for your interest in contributing! I actually already added this feature last month: https://github.com/microsoft/vscode-pull-request-github/issues/5439
