### ISSUE TITLE
Space Toggles Tree View item Collapsed State

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode-pull-request-github#5287]
Testing #5282

![Image](https://github.com/microsoft/vscode-pull-request-github/assets/2931520/f3d85fa3-ff68-4be8-b2c6-3df4b5ef30fc)

**Comment by hediet** [comment]
I thought the test plan item said space would open the details page without focusing it?

**Comment by alexr00** [comment]
It does say that, and that is incorrect. I was thinking of the "Pull Requests" tree, where the description is not an expandable node. I have removed that from the test.
