### ISSUE TITLE
Editor not opening when selecting file in commits view

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode-pull-request-github#5288]
Testing #5283

![Image](https://github.com/microsoft/vscode-pull-request-github/assets/1931590/62a3fef6-496e-4566-9504-048534617a2e)

**Comment by dbaeumer** [comment]
Worked in the files view.

**Comment by dbaeumer** [comment]
Both work after the branch has been published.

**Comment by bhavyaus** [comment]
verified from build artifact
