### ISSUE TITLE
Github Enterprise: Can't Add Comments On Pre Release Extension

### ISSUE THREAD

**Issue by jpspringall** [microsoft/vscode-pull-request-github#5291]
Github Enterprise: Can't Add Comments On Pre Release Extension

- Extension version: v0.73.2023092609
- VSCode Version: Version: 1.83.0-insider (system setup)
- OS: Windows 10
- GHE Version: 3.7.16

Steps to Reproduce:

1. Attempt to add comment to PR as normal, no + button appears  so unable to add comment

FYI, Works correctly in Pre Release Version: v0.73.2023092509 (previous pre release version)

**Comment by jpspringall** [comment]
Looks to have been resolved as part of: v0.73.2023100209
Will close

**Comment by alexr00** [comment]
@jpspringall I'm not able to repro this. I've tested with the same GHE version: 3.7.16 (also accidentally tested with 3.7.17) first.
Some questions:
- Do you see any error in the dev console? 
- Is this for a checked out PR or a non-checked out PR?
- Does the issue persist if you reload?
