### ISSUE TITLE
Github Issues not loading

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode-pull-request-github#5292]
- Extension version: v0.73.2023092609
- VSCode Version: insiders-1.83
- OS: windows

Steps to Reproduce:

1. Open the vscode repository
2. Click on the GitHub icon in the activity bar and notice that the Issues viewlet is infinitely loading.

![Image](https://github.com/microsoft/vscode-pull-request-github/assets/31675041/f6ecaee3-249b-4528-ad7e-b2bd166bb3e0)

No matter how long I wait, it seems to still be loading for some reason.

**Comment by alexr00** [comment]
Can you share the value you have for the setting `githubIssues.queries`

**Comment by andreamah** [comment]
```
  "githubIssues.queries": [
		{
			"label": "September 2023",
			"query": "assignee:${user} state:open milestone:\"September 2023\""
		},
		{
			"label": "My Issues",
			"query": "default"
		}
  ],
```

**Comment by andreamah** [comment]
Seems it's loading now after the newest insiders update. Not sure what changed, I'll keep monitoring it.
