### ISSUE TITLE
Don't discard Description when closing create view

### ISSUE THREAD

**Issue by hbons** [microsoft/vscode-pull-request-github#5294]
When I write a PR description in then select a different view in the Activity Bar the description I wrote gets discarded. There is no warning that this will happen. I'm ok with this happening when pressing the Cancel button, but I expect to be able to return to my PR when moving between activity views to check other things.

Possible solutions:
- Add a warning when closing the view.
- Save the description and PR state when switching views

**Comment by alexr00** [comment]
This was caused by @hbons moving or hiding the view at some point. The issue was resolved by resetting view locations.
