### ISSUE TITLE
Selecting PR review submission option erroneously submits review

### ISSUE THREAD

**Issue by seantleonard** [microsoft/vscode-pull-request-github#5300]
## Due diligence
- Searched for terms like "review submission" "comment" "approve" "request changes" with no observed similar issues.

- Extension version: 
> 0.72.0

- VSCode Version:
>  Version: 1.82.2 (user setup)
> Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
> Date: 2023-09-14T05:55:25.390Z
> Electron: 25.8.1
> ElectronBuildId: 23779380
> Chromium: 114.0.5735.289
> Node.js: 18.15.0
> V8: 11.4.183.29-electron.0
> OS: Windows_NT x64 10.0.22621

- OS:

> Edition	Windows 11 Enterprise
> Version	22H2
> Installed on	‎5/‎24/‎2023
> OS build	22621.2283
> Experience	Windows Feature Experience Pack 1000.22662.1000.0

### Issue summary

When I have accumulated comments for my PR review and am ready to submit, I go to the bottom left corner of (my) screen to find the review submission options along with the comment i want to submit with my review:
![image](https://github.com/microsoft/vscode-pull-request-github/assets/6414189/2f5d7e72-3efe-4db4-a14d-f8c3dfc93281)

Steps to Reproduce:

1. The blue downwards arrow lets me select a different option if the main blue button is something I don't want. In the image above, the main button says "comment". I don't want that, I want to 'approve.
2. I select the dropdown and then select approve, so that the main button can update and I type in my review comment in the text box. 
![image](https://github.com/microsoft/vscode-pull-request-github/assets/6414189/aa96792b-63f2-4102-98c2-69090b2fcb12)

3. I click the main blue button that now says "approve." and my review submits.
4. I check the PR in Github UI, and **my review has submitted twice**! It seems that selecting an option in the PR review submission option dropdown actually submits the review. This is a bit misleading because I would assume clicking the big blue button would do that.

**Comment by alexr00** [comment]
Selecting an option in the dropdown does execute the option. This is to reduce the number of clicks needed to submit a review.

**Comment by seantleonard** [comment]
ah, I see. The reason why it seemed off to me was because selecting an option from the dropdown changes the blue button. So if you're intending to perform an option that is different than the blue button, the option will only execute by not selecting the blue button and instead selecting from the dropdown.

**Comment by seantleonard** [comment]
This experience resembles what was brought up in #3888

**Comment by alexr00** [comment]
Closing as we are consistent with VS Code's Commit & button.
