### ISSUE TITLE
network error on window reload: 403

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode-pull-request-github#5303]
Testing microsoft/vscode#194015

This happened twice

![Image](https://github.com/microsoft/vscode/assets/29464607/9c4e0ee6-c4b0-4d68-b749-720946a6bb49)

**Comment by meganrogge** [comment]
I haven't seen this recently and will reopen if I do

**Comment by alexr00** [comment]
@IllusionMH command "Developer: Set Log Lever..." then choose "GitHub Pull Request". You can change the defaujt log level with the icon to the far right of level label.

One possible cause of always getting errors is that you have a clone of a fork but you don't have permissions to the upstream repo. You can disable the upstream by setting `"githubPullRequests.upstreamRemote": "never"`. This should be something we can detect from the extension. I'll see if I can add it.

**Comment by IllusionMH** [comment]
Thank you for instructions, and suggested setting.
Unfortunately, setting didn't prevent 403 and from logs it unclear what exactly causes it.

Will try to experiment with setup, other logs and create separate issue if it's not my setup.
