### ISSUE TITLE
Task list checkboxes aren't rendered

### ISSUE THREAD

**Issue by johnknoop** [microsoft/vscode-pull-request-github#5310]
If a PR comment contains a task list, such as:

```
- [ ] Add validation
```
then the GitHub web UI will render it as a checkbox:

<img width="108" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/3394270/3151b121-ada3-4a0b-82d2-adba3f107a0c">

But your VS Code extension just renders it as a bullet:

<img width="88" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/3394270/cfd8f568-f504-4a07-a444-e1354d70f9c5">

And the bullet affords no interactivity, so in order to check that box, I have to open up github.com in the browser.

**Comment by alexr00** [comment]
@johnknoop you can edit the comment by using the pencil icon in the comment.

@mjbvz would you expect our markdown renderer to render checkboxes?

**Comment by alexr00** [comment]
To verify:
1. Install the pre-release version of GitHub Pull Requests and Issues
2. Open a file from a PR.
3. Add a PR review comment in that file. In your comment include task-list/checkbox syntax. Example:
```markdown
- [ ] not done yet
- [x] already done
```
4. Once your comment is saved, verify that the markdown is rendered as a checkbox.

**Comment by johnknoop** [comment]
I saw this was fixed in the latest stable (not pre-release) version earlier today, or a few days ago. Nice, thanks!
