### ISSUE TITLE
Reviewer dropdown never hits cache

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-pull-request-github#5316]
I always have to wait.

<img width="625" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/900690/b7810ad7-134a-433d-b85c-379cdce8eb73">

**Comment by alexr00** [comment]
The logs indicate that the slowness is coming from downloading avatars. I will add real caching for avatars.

**Comment by bpasero** [comment]
This works fast for me now, 🆒 . Not sure if related, but I see no avatar images for most entries:

![image](https://github.com/microsoft/vscode-pull-request-github/assets/900690/0966dc73-8ecc-4e60-9c5f-e0ea48a5fc01)

I guess this is only being updated as long as the picker is opened and not in the background?
