### ISSUE TITLE
Element with id already registered

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode-pull-request-github#5321]
Not really sure how I got in this state, but every time I reload my page on the PR view I get a few error notifications

```
Element with id Local Pull Request Brancheshttps://github.com/microsoft/vscode-copilot/pull/1707lramos15/compact-swift is already registered
```

I also see 
```
mainThreadExtensionService.ts:82 TypeError: Cannot read properties of undefined (reading 'commit')
    at jt.getStatusChecks (/Users/lramos15/.vscode-insiders/extensions/github.vscode-pull-request-github-0.75.2023100509/dist/extension.js:1672:12236)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 2)
    at b0._getChecks (/Users/lramos15/.vscode-insiders/extensions/github.vscode-pull-request-github-0.75.2023100509/dist/extension.js:1805:18865)
```

Apologies for the very generic and not helpful repro.

**Comment by alexr00** [comment]
For the first error you're seeing: is there anything special about your setup, like multi root workspace?

**Comment by lramos15** [comment]
> For the first error you're seeing: is there anything special about your setup, like multi root workspace?

No nothing special. I also no longer see it so it's probably inactionable, but was just mentioning in case it rung any bells. I understand this was a very mediocre issue report with no real repro.

**Comment by alexr00** [comment]
Closing then, but if you see it again, can you grab logs and a screenshot of your Pull Requests view?

**Comment by meganrogge** [comment]
@alexr00 how should this be verified?

**Comment by lramos15** [comment]
> [@alexr00](https://github.com/alexr00) how should this be verified?

I went ahead and verified this, since I was seeing this error pretty much daily and now don't see it anymore

**Comment by alexr00** [comment]
@lramos15 I think this is fixed with c764f4b7b5195ed669be64e09c61476d5a29459a. Thanks for letting me know each time I thought this was fixed that it was still happening!

**Comment by frediaz** [comment]
Hello, 

I am getting:

Error: Element with id Local Pull Request Branches is already registered
    at j5.db (/c:/Program%20Files/VsCode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:170:15277)
    at /c:/Program%20Files/VsCode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:170:14126
    at Array.map (<anonymous>)
    at j5.Y (/c:/Program%20Files/VsCode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:170:14108)
    at j5.getChildren (/c:/Program%20Files/VsCode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:170:10425)
    at oG.$getChildren (/c:/Program%20Files/VsCode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:170:6969)

**Comment by onexey** [comment]
I have the same problem with version 0.114.3 on vsCode 1.102.2.

In my case it was due to duplicate queries in the config. After removing the duplicate queries (queries with the same label), it's working as expected.

I have no idea if this was the state from the beginning or something changed/broke it. But I am %100 sure I didn't add those.

original:
```json
    "githubPullRequests.queries": [
        
        {
            "label": "Local Pull Request Branches",
            "query": "default"
        },
        {
            "label": "Local Pull Request Branches",
            "query": "repo:${owner}/${repository} default"
        },
        {
            "label": "Waiting For My Review",
            "query": "repo:${owner}/${repository} is:open review-requested:${user}"
        },
        {
            "label": "Assigned To Me",
            "query": "repo:${owner}/${repository} is:open assignee:${user}"
        },
        {
            "label": "Created By Me",
            "query": "repo:${owner}/${repository} is:open author:${user}"
        },
        {
            "label": "All Open",
            "query": "repo:${owner}/${repository} default"
        },
        {
            "label": "All Open",
            "query": "default"
        }
    ],
```

corrected:
```json
        {
            "label": "Local Pull Request Branches",
            "query": "repo:${owner}/${repository} default"
        },
        {
            "label": "Waiting For My Review",
            "query": "repo:${owner}/${repository} is:open review-requested:${user}"
        },
        {
            "label": "Assigned To Me",
            "query": "repo:${owner}/${repository} is:open assignee:${user}"
        },
        {
            "label": "Created By Me",
            "query": "repo:${owner}/${repository} is:open author:${user}"
        },
        {
            "label": "All Open",
            "query": "repo:${owner}/${repository} default"
        }
```
