### ISSUE TITLE
Should be able to select email associated with merge commit

### ISSUE THREAD

**Issue by Callek** [microsoft/vscode-pull-request-github#5326]
In github UX you can select an e-mail associated with your merge commit. 

![image](https://github.com/microsoft/vscode-pull-request-github/assets/1415602/a0408874-2059-4aef-b2dd-d356aa28f600)

Unfortunately using the UX in VSCode I'm never presented with that dropdown (nor is it remembering my default for the repo as I set it on github) therefore I just merged something with the wrong e-mail for this organization.

![Screenshot 2023-10-09 at 2 02 39 PM](https://github.com/microsoft/vscode-pull-request-github/assets/1415602/f1adce40-f039-41bd-b46e-0ce018e1b88e)

**Comment by alexr00** [comment]
As far as I can tell, there's no way to get all your email addresses with GitHub's API (graphQL or REST). To prevent accidentally using the wrong email though, we should show which email will be used in the UI.

**Comment by alexr00** [comment]
@hbons here's what I'm adding:

![image](https://github.com/microsoft/vscode-pull-request-github/assets/38270282/6305ec35-920e-499e-8079-6b519d7b8b96)

**Comment by alexr00** [comment]
Maybe it makes sense to allow free-form input for the email so that it can be set to something else if the default email from GitHub isn't what you want...

**Comment by alexr00** [comment]
Using the same input-box style button as in the "Create" view to show a quick pick to chose an email:

![image](https://github.com/microsoft/vscode-pull-request-github/assets/38270282/4371113c-0978-4ba3-8939-1c1b9a300a3c)

**Comment by rzhao271** [comment]
The UI glitches out for me for both Merge and Squash + Merge. I'm assuming there is a single option and it is my noreply email.

![Email picker is a blank square instead of a rectangle with an email in it](https://github.com/microsoft/vscode-pull-request-github/assets/7199958/72c7131c-d38e-4a7a-95bc-cdad4d945596)

**Comment by alexr00** [comment]
With https://github.com/microsoft/vscode-pull-request-github/pull/5777, if there is no default email then the "Commit will be associated with" will not show at all.

**Comment by alexr00** [comment]
Fix is now available in pre-release.

**Comment by rzhao271** [comment]
I have verified the no email case.
