### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Apex-Incarna** [microsoft/vscode-pull-request-github#5327]
- Issue Type: `Performance`
- Extension Name: `vscode-pull-request-github`
- Extension Version: `0.74.0`
- OS Version: `Windows_NT x64 10.0.22621`
- VS Code version: `1.83.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/ECGSTU~1/AppData/Local/Temp/GitHub.vscode-pull-request-github-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by alexr00** [comment]
Can you please include the file `file:///c%3A/Users/ECGSTU~1/AppData/Local/Temp/GitHub.vscode-pull-request-github-unresponsive.cpuprofile.txt`?
