### ISSUE TITLE
Revisit showing side-by-side icon so prominently?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-pull-request-github#5333]
I am curious for why the "Open Summary to the Side" action is so prominent:

<img width="509" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/900690/26126607-3831-4529-b6a0-3e68a705a018">

I do not recall other locations in the UI where we do that in trees. Since we have well established patterns for opening something to the side from a tree/list via `Alt`-click, I would remove it.

Somewhat related, the icon is a lot different from the normal icon to open description:

<img width="260" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/900690/1f5df64d-554d-4464-866e-ee06be3f8008">

**Comment by alexr00** [comment]
This was added before we handled click modifiers in extension trees. It's fine to remove now.

**Comment by alexr00** [comment]
I need to revert this because click modifiers are not passed to this command. Full context: https://github.com/microsoft/vscode-pull-request-github/issues/5332#issuecomment-1757299591

**Comment by alexr00** [comment]
Closing as out of scope since this would require that it be possible to open a webview via a URI.
