### ISSUE TITLE
Use a dropdown for finishing review?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-pull-request-github#5334]
Here is how GH shows it:

<img width="777" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/900690/c0df51ab-6129-49f3-af62-9ffca3574304">

And here is ours:

<img width="534" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/900690/26bc5ad1-b578-4b3d-8ed6-d5b9c8f845d7">

I find it strange that we use multiple buttons and pick "Comment" as the default, while in 99% of the cases the action picked is likely "Request Changes" or "Approve".

I would suggest turning this into a dropdown button where you then pick your choice.

**Comment by bpasero** [comment]
@alexr00 I am not sure, but should we be using a dropdown here as well?

![image](https://github.com/microsoft/vscode-pull-request-github/assets/900690/c7272c25-e8df-43ff-82aa-82f5adc1ed18)

**Comment by alexr00** [comment]
Good point. I will not be able to add it for this release, but I will add it in December.
