### ISSUE TITLE
Assign quick pick should not be canceled on blur

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-pull-request-github#5342]
Create a PR, click on the Assignee button. That opens a quick pick. Choose a person. Click outside of the quick pick to close it. My choice is not preserved. It looks like you require the OK button to be pressed.

We should preserve choice on blur quick pick close here. It does not have to be so explicit imho

![Screenshot 2023-10-13 at 11 09 35](https://github.com/microsoft/vscode-pull-request-github/assets/1926584/7bf89073-0e2b-48e6-bf53-bda12531cdae)

**Comment by alexr00** [comment]
We consistently interpret not hitting `enter` or clicking "OK" as cancel. Hide can be triggered by `esc`, and we should not be treating `esc` as "OK".

**Comment by isidorn** [comment]
Makes good sense.
What bothers my soul here is that I have explicitly clicked on a checkbox.

Just curious @TylerLeonhardt did you get feedback like this before? That clicking on a checkbox in quick pick and then closing the quick pick via blur should preserve the click, and not treat it as cancel?

**Comment by TylerLeonhardt** [comment]
I think this particular multi-select feels so jarring because GitHub.com has the behavior that you describe.

Having said that, I haven't received this feedback before. In all cases `ESC` and focus out are one in the same... I don't think that hitting `ESC` here make sense to actually accept what you've checked.

**Comment by isidorn** [comment]
Thanks for the explanation. So let's leave it as it is, as you both suggest.
And yes, it is jarring for me because I am used to gh.com behaviour.
