### ISSUE TITLE
On Desktop, when you log in to the extension it asks for the old set of scopes

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode-pull-request-github#5344]
I'm not sure if the logic here changed recently... but we really want GHPR to sign in as the same scopes as GitHub Repos & other extensions.

Steps to reproduce:
* Sign out of VS Code
* reload the window
* click on the badge for GHPR

![Image](https://github.com/microsoft/vscode-pull-request-github/assets/2644648/d6179def-2889-4eca-89b0-ca9ff4701768)

* that opens a url with this as the scopes: `&scope=read%3Auser+repo+user%3Aemail`

That's the old scopes:
https://github.com/microsoft/vscode-pull-request-github/blob/main/src/github/credentials.ts#L30C16-L30C16

I was expecting the `SCOPES` to be used here:
https://github.com/microsoft/vscode-pull-request-github/blob/main/src/github/credentials.ts#L31

so that GH Repos and other extensions that are trusted could piggy back off of that

**Comment by alexr00** [comment]
This is a regression.
