### ISSUE TITLE
Status bar shows merged PRs

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode-pull-request-github#5345]
Type: <b>Bug</b>

Status bar shows old merged PRs. It should either marked them as merged or only show if there are open PRs.
![image](https://github.com/microsoft/vscode-pull-request-github/assets/3840081/710fa978-de0e-4a48-b3e1-ee38d374e7c7)

This is the PR that it is pointing to: https://github.com/microsoft/vscode-pylint/pull/1

Extension version: 0.75.2023101209
VS Code version: Code - Insiders 1.84.0-insider (4678919d52909efc7c4ab958a2e5c8f45d50ffc3, 2023-10-13T05:34:13.175Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.60GB (17.14GB free)|
|Process Argv|--log info --log ms-python.python:trace --crash-reporter-id 4fb1ebc1-cf4c-4880-a88a-47738ec3768d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627cf:30244335
vslsvsres303:30308271
pythontb:30258533
vsc_aacf:30263846
pythonptprofiler:30281269
vsdfh931:30280409
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
vscrpc:30624061
a9j8j154:30646983
showlangstatbar:30737417
7ij38806:30687742
pythonfmttext:30716741
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
copilotsettingt:30808721
dsvsc013:30777762
dsvsc014:30777825
diffeditorv1:30786205
pythonmpsinfo:30859869
dsvsc015:30821418
pythontestfixt:30859590
pythonregdiag:30859652
pythonmypyd1:30859725
pythoncet0:30859736

```

</details>

**Comment by karthiknadig** [comment]
Trace level logs here:
[ghpr.trace.log](https://github.com/microsoft/vscode-pull-request-github/files/12899210/ghpr.trace.log)

**Comment by alexr00** [comment]
You can control this with the setting `githubPullRequests.useReviewMode`.
