### ISSUE TITLE
Cannot check out PR for Classroom repos

### ISSUE THREAD

**Issue by BrianEmilius** [Microsoft/vscode-pull-request-github#536]
- Extension version: 0.1.6
- VSCode Version: 1.27.2
- OS: Linux Mint Cinnamon 64-bit

Steps to Reproduce:

1. Create classroom assignment with a starter-code repository.
2. Students accept assignment, do their work, commit, push and create a PR with me as reviewer.
3. I download all assignment repositories via Classroom Assistant.
4. When I check out the PR I get this error:
fatal could not read Username for 'https://github.com'
no such device or address

This error comes from the PR extension.
Screenshot: https://imgur.com/a/9zZzGfD

I am the owner of the classroom and default owner of all repos in the organization connected with the classroom. I verified that I am owner of the repos in question.

I am logged in on GitHub with the PR extension.

**Comment by RMacfarlane** [comment]
Hey @BrianEmilius, thanks for the info. This looks related to https://github.com/Microsoft/vscode-pull-request-github/issues/273. When the extension is trying to check out a PR and the remote doesn't exist locally, it creates one in `https` format.

Can you take a look at the `config` file in the `.git` folder of the repository? Each remote should have a section that looks like
```
[remote "6A"]
   url = https://github.com/6A/vscode
   fetch = +refs/heads/*:refs/remotes/6A/*
   github-pr-remote = true
```

As a workaround, you can try changing the url to match the format of `[remote "origin"]`, probably something like `git@github.com:<owner>/<repository>`.

I'll close this as a duplicate and track this bug in https://github.com/Microsoft/vscode-pull-request-github/issues/273, but please respond here if the workaround doesn't work or you aren't using ssh

**Comment by BrianEmilius** [comment]
I am not exactly sure how the repos are cloned (ssh or otherwise), as I do it through the Classroom Assistant.

**Comment by BrianEmilius** [comment]
The `[remote "origin"]`section is present in the config file.
However, the URL part includes an accesstoken, which is currently how repos are cloned through the classroom assistant. I suspect this might be what is causing issues (expired tokens).
