### ISSUE TITLE
Show progress and transition into created PR from "Create PR" view

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-pull-request-github#5361]
When you create a PR you are in this view:

<img width="399" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/900690/c49bf522-93ff-4efe-ba40-4ef2c792a52a">

I often want to follow up on something in the created PR and today, the view closes and then later appears again.

Here is a suggestion:
* never close the view, keep it open and swap the contents with the created view once created
* show some kind of progress, maybe in the activity bar (there is extension API for it) and maybe show a progress bar in the view and disable the elements

//cc @hbons

**Comment by bpasero** [comment]
🆒

**Comment by bpasero** [comment]
This works very well. At some point though the progress bar stops and its still not done. Maybe try it out if you see the same. I would have expected the progress to last all the way until the new view opens.

**Comment by alexr00** [comment]
Maintaining the progress longer will be added with https://github.com/microsoft/vscode-pull-request-github/pull/5388
