### ISSUE TITLE
Provide an option not to hide lines of a PR

### ISSUE THREAD

**Issue by chakravarthi-bb** [microsoft/vscode-pull-request-github#5368]
Searched and didn't found any

I have observed hidden lines from the last few days while checking the diff. The whole point of me reviewing PR in VS Code is so I can jump to other places of code and understand. it's annoying to click show all lines for all the diffs. It would be nice to have a setting for this, so if anyone like me who wants to see the whole file, instead of hidden lines that would be great

**Comment by alexr00** [comment]
Can you share a screenshot of this? There shouldn't be any hidden lines.

**Comment by chakravarthi-bb** [comment]
something like this 
<img width="1263" alt="Screenshot 2023-10-27 at 3 16 15 PM" src="https://github.com/microsoft/vscode-pull-request-github/assets/110885295/64097358-1c8a-47be-b441-59b80aa3aeed">

**Comment by alexr00** [comment]
Looks like you toggled on "collapse unchanged regions"

<img width="509" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/38270282/1163ed27-72ac-4710-94a5-1ab28a6ae493">

**Comment by SergiuTalnaci** [comment]
For the next person finding this, this options has it's own icon: 
![image](https://github.com/microsoft/vscode-pull-request-github/assets/3950633/0e2316db-98a9-4c21-9742-7bf766d80c5e)
