### ISSUE TITLE
Show the id of the pull request

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode-pull-request-github#537]
Issue Type: <b>Feature Request</b>

It would be helpful to see the ids of the PRs to be able to quickly spot the sorting order of PRs.

Extension version: 0.1.6
VS Code version: Code - Insiders 1.28.0-insider (60db21f08b81f03c15bb5c9395755ad3620a62bd, 2018-10-02T13:19:14.638Z)
OS version: Darwin x64 16.7.0

**Comment by justinliew** [comment]
Are you thinking of the id like (#537) of this one? I can try to take this on.
![image](https://user-images.githubusercontent.com/613567/46390648-ad996600-c68d-11e8-8f6e-eda20401d2c3.png)
So in the above example, the top level tree item would say `(#537) Automate Kit's ability` ?

**Comment by justinliew** [comment]
How does this look?

![image](https://user-images.githubusercontent.com/613567/46391274-d3743a00-c690-11e8-9ce2-43a17507f39e.png)

**Comment by justinliew** [comment]
Added a potential PR to address this. Happy to receive comments, concerns.
