### ISSUE TITLE
Review Thread Comment Title: Jump to right file and line

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode-pull-request-github#5378]
The title of the comments should allow the user to jump to the file at the correct line and not just open the file.
The title could be changed to filepath#linenumber

<img width="783" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/44439583/4382f0db-8b40-410d-b54b-c9d9c753adc6">

**Comment by roblourens** [comment]
What's this referring to?

**Comment by alexr00** [comment]
To verify:
1. Open a PR
2. Make a PR comment on some line of code somewhere
3. Open the PR description, you should see your comment there too
4. Click on the file link at the top of your comment in the description. It should take you to the line in the file that your comment is on.
