### ISSUE TITLE
Test setting a project when viewing a PR

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#5383]
Refs: #4926

- [x] anyOS @Tyriar 
- [x] anyOS @TylerLeonhardt  (for GitHub Enterprise)
- [x] anyOS @amunger 

Complexity: 3

---

Setup

- Install the pre-release version of GitHub Pull Requests and Issues.
- Clone a GitHub repo that has projects (not required for Enterprise)

Testing (not GitHub Enterprise)
1. View a PR on GitHub.com and set a project on it.
2. Open your clone of the repo in VS Code
3. From the Pull Requests view, expand the tree node for the PR in step 1. If it doesn't show, you can edit or add the queries in that tree by using the inline action to "Edit Query".
4. Open the PR Description.
5. Verify that the PR description shows and that there is **no project** displayed and instead there's a prompt to sign in.
6. Follow the sign in prompt
7. Verify that the Project now shows.
8. Open other PR descriptions. Verify that you can set and see Projects on them.

Testing (GitHub Enterprise)
1. Verify that you can open a PR description.

**Comment by amunger** [comment]
I can't set a new project because of the linked issue, but I can at least remove them.
