### ISSUE TITLE
If I try to "Sign in with more permissions to see projects" the extension shows an error notification

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode-pull-request-github#5389]
Testing https://github.com/microsoft/vscode-pull-request-github/issues/5383

![Image](https://github.com/microsoft/vscode-pull-request-github/assets/2644648/8ed4e2d6-feb8-447a-a3e7-f6bc8c1918e1)

Note, this happens only on a GitHub Enterprise Server... not a hosted instance.

From the description of the TPI, it sounds expected that this shouldn't work... however, I think that if that's the case, we shouldn't show this section for GHES users.

**Comment by alexr00** [comment]
Currently by design. None of the currently available versions of Enterprise Server support projects v2. I'm still trying to avoid adding actual enterprise version checking, but we can probably to better than that error.

**Comment by alexr00** [comment]
I'm going to remove the whole Projects section for ES.
