### ISSUE TITLE
projects not listed for repository

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-pull-request-github#5390]
testing https://github.com/microsoft/vscode-pull-request-github/issues/5383

Steps to Reproduce:

1. Added a new project to a repository
2. Created a PR on GH, and added that project
3. Open the PR in vscode
The description shows that the project is set
🐛 clicking projects to edit shows no projects

![Recording 2023-10-24 at 10 48 30](https://github.com/microsoft/vscode-pull-request-github/assets/2019016/d25f7919-4ce7-42ff-a4df-f9f442b72210)

**Comment by alexr00** [comment]
> Added a new project to a repository

@amunger did you add a project to the repo or to the org? If org, then this is a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/5393

**Comment by amunger** [comment]
ah, yes. After adding a project to the repository I can see and add it to a PR through the extension. closing
