### ISSUE TITLE
Cannot set the only project I care about

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#5393]
Testing https://github.com/microsoft/vscode-pull-request-github/issues/5383

I use a project (which is private to me and megan) and it doesn't show up in this list:

![Image](https://github.com/microsoft/vscode-pull-request-github/assets/2193314/a66bc860-716d-4013-a1c4-ced1c4fe7648)

This makes the feature unusable for me.

**Comment by alexr00** [comment]
Huh, I didn't realize that some projects were scoped to a user and some to a repo. I'll see if I can add the user ones.

**Comment by alexr00** [comment]
@Tyriar I'm guessing your projects are at the organization level, not at the user level, as it doesn't appear to be possible to set a user level project on an org owned repo.

**Comment by meganrogge** [comment]
Guessing this is unreleased - I can see the `VS Code Terminal` project on the PR's description page, but it's still not showing up in the dropdown.


![Image](https://github.com/microsoft/vscode-pull-request-github/assets/29464607/6c611081-246b-4507-954c-cf4f75464184)

**Comment by alexr00** [comment]
This has been released. You should see around 100 projects in there now.
