### ISSUE TITLE
"Create a Pull Request" view should be instantly available for interaction

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode-pull-request-github#5403]
Following up on discussion in https://github.com/microsoft/vscode-pull-request-github/issues/5399, it would be great if create PR view could be instantly available for interaction, ie editing PR name & description, and create PR buttons. (I wouldn't mind if it errored out because of upstream issues (eg I'm blocked from sending PRs) because it would happen rarely)

cc @jrieken @joaomoreno

**Comment by alexr00** [comment]
A new setting value will skip the work we do to provide a title and description if you want it to be faster: `"githubPullRequests.pullRequestDescription": "none"`.

**Comment by bhavyaus** [comment]
Verified with `"githubPullRequests.pullRequestDescription": "none".`
