### ISSUE TITLE
Unable to sign in; browser never triggered

### ISSUE THREAD

**Issue by morgansimonsen** [Microsoft/vscode-pull-request-github#541]
- Extension version: 0.1.6
- VSCode Version: 1.27.2
- OS: Windows 10 64-bit 1803

Any attempt at signing in to GitHub to authorize the extension never triggers the browser to render the page. Sign in silently fails and displays error.
In this case we are enforcing SSO with Azure AD for GitHub and use personal access tokens to authenticate the built in git client. This works without issues. Other apps requiring authorization on GitHub.com works.

**Comment by morgansimonsen** [comment]
In the environment where this behavior is observed WebSockets are blocked by the enterprise proxy solution, so seems consistent with the issue @queerviolet referenced.

**Comment by rebornix** [comment]
We released 0.2.0 with the improvement @queerviolet brought in for authentication. This issue should be gone now.
