### ISSUE TITLE
Unable to open more included files after viewing one

### ISSUE THREAD

**Issue by MartinDM** [microsoft/vscode-pull-request-github#542]
- Extension version: 0.1.2
- VSCode Version: 1.27
- OS: Mac HS 10.12.6

Steps to Reproduce:

1. Click 'Description' entry in PR panel.
2. Click an included file to see diff view
3. Click another file
4. No further files or 'Description' can be opened, even when closing all tabs.

**Comment by RMacfarlane** [comment]
@MartinDM Is there anything in the dev console when this happens? Can you try upgrading to the latest extension version, 0.1.6?

**Comment by MartinDM** [comment]
I have done that; still getting the issue when running 0.1.6 (I think I was already running this, my mistake).

It's intermittent, which makes this difficult to reproduce consistently, but after checking out a couple of PRs one after the other and switching between the changes in them, I am still able to trigger the issue.

Nothing is output to the console unfortunately. Not expecting a resolution as a result, but wanted to raise as a potential issue for others too?

Will update this info if I discover anything that seems to cause it.
