### ISSUE TITLE
can't see PR content, just a title

### ISSUE THREAD

**Issue by NarHakobyan** [microsoft/vscode-pull-request-github#5436]
- Extension version: 0.76
- VSCode Version: 1.84.0
- OS: Macos
- Repository Clone Configuration (single repository/fork of an upstream repository): wrokspace
- Github Product (Github.com/Github Enterprise version x.x.x):

Steps to Reproduce:

1. Open PR section
2. Click on any PR

<img width="477" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/1781506/21853ac2-737a-403b-802b-e736929b0a4a">

**Comment by alexr00** [comment]
Are you using GitHub Enterprise? If this is a public repo, can you share a link to the repo?

**Comment by leonid-s-usov** [comment]
I experience the same. Using my private github account, part of a github org.
```
» git remote -v 
...
leo     git@github.com:leonid-s-usov/ceph-ceph.git (fetch)
leo     git@github.com:leonid-s-usov/ceph-ceph.git (push)
origin  git@github.com:ceph/ceph.git (fetch)
origin  git@github.com:ceph/ceph.git (push)
...
```

**Comment by leonid-s-usov** [comment]
@NarHakobyan please check the output for GitHub Pull Request, does it show rate limiting errors? That is likely the cause for me

<img width="253" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/3144935/48a46373-5b36-45a0-a8f6-3d192b169e78">
<img width="313" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/3144935/f3427679-ba84-4ea0-be70-15d2bf59f715">

**Comment by alexr00** [comment]
@leonid-s-usov can you share the output?
