### ISSUE TITLE
The extension ignores git.autofetch and periodically fetches all remotes

### ISSUE THREAD

**Issue by toh-ableton** [microsoft/vscode-pull-request-github#5439]
- Extension version: v0.76.0
- VSCode Version: 1.83.1 (Universal)
- OS: macOS Sonoma 14.1 Beta
- Repository Clone Configuration (single repository/fork of an upstream repository): Huh?
- Github Product (Github.com/Github Enterprise version x.x.x): github.com

Steps to Reproduce:
1. Install the extension

Expected Results:
The configured remotes are only fetched on explicit user interaction.

Actual Resulst:
The configured remotes are periodically fetched in the background, whether the users wants or not.

This is a an issue in at least two separate ways:
1. As a user, I never consented to this behavior. It took me hours and hours to track down which extension violated my explicitly stated preference to not fetch in the background (`"git.autofetch": false`).
2. It breaks my workflow. I periodically need to rebase my branches, and I'm often working on more than one computer on the same branch and/or I'm collaborating with a co-worker on the same branch. I rely on `git push --force-with-lease` when I need to force-push a branch to not accidentally overwrite a push from a different computer or a from a co-worker. This relies on me, the human developer, having full control on when which branches are fetched from origin. I do not want automatic fetching in the background, and I expect you to honor my stated preferences.

**Comment by alexr00** [comment]
> The configured remotes are periodically fetched in the background

It should just be the remote for the branch you're currently. Are you seeing it do otherwise?

**Comment by alexr00** [comment]
Additionally, the fetch should only be happening in the following cases:
- The extension activates
- You check out a PR from the PRs view
- You switch to a branch associated with a PR 
- You open the PR description
-

**Comment by toh-ableton** [comment]
It could be that it's just fetching the current remote, but I also don't want that done in the background. If it's necessary for the extension, could you fetch into your own namespace (instead of updating the default remote tracking branch)? I.e. instead of (the command line equivalent of)
```
git fetch <remote> <branch>
```
you'd do something like
```
get fetch <url> <branch>:vscode-github-pr/<branch>
```
Otherwise, I'd really strongly prefer an option to just turn off any automatic fetching. Thank you.

**Comment by alexr00** [comment]
Ok. I will add a setting that you can change so that we never fetch if the branch already exists locally.

**Comment by alexr00** [comment]
@toh-ableton starting in the pre-release version of the extension tomorrow, you can use the following two settings to get the behavior you're looking for:
```
"githubPullRequests.pullPullRequestBranchBeforeCheckout": false
"githubPullRequests.allowFetch": false
```

**Comment by toh-ableton** [comment]
@alexr00 Wow amazing thanks for the quick turnaround! This is great. 💐

**Comment by alexr00** [comment]
@toh-ableton if you do try out the pre-release version of the extension then it would be helpful if you could comment back here in the issue to say whether the changes work the way you expected!

**Comment by toh-ableton** [comment]
@alexr00 I tried the preview, and it's working exactly as I expected. Thank you very much again for the quick fix!

**Comment by alexr00** [comment]
Glad to hear, thanks for trying it out!
