### ISSUE TITLE
Commits view lists oldest commit first

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-pull-request-github#5442]
1. Have a PR with many commits
2. Open the GHPRI commits view
3. :bug: the most recent commit is all the way at the bottom of the view

I think I would expect that the most recent commit is at the top so that I can easily validate whether the PR contains the latest commits that I added (in this case I was creating a PR from a topic branch into a release branch, the base branch was autoselected as main instead of release, and I couldn't see the commit I'd added at a glance).

**Comment by alexr00** [comment]
I don't have a strong opinion here. The best analogy I can think of is running `git log` and that shows the newest commit first.

**Comment by kj-weber-2** [comment]
hi @alexr00 @joyceerhl , could we have a QOL toggle somewhere in settings that allows us to reverse this? (**newest commit** shows as the first row in a pull request's and repository's "Commits" (included in) list, as opposed to this default which shows the oldest?

As someone who is a bit addicted to committing as I code, and reviewing others', the fact there's no way in the web UI to change this is driving me nuts, especially if the commits list includes multiple dates (and hence sections)

Thoughts?

**Comment by kj-weber-2** [comment]
the cherry on top would also be if the action button (such as "Create Pull Request", or "MERGE") followed me as I scrolled down the list, so I didn't need to scroll all the way back up to the top after wondering "did my latest commit make it into this one?" and heading on down there to find out
