### ISSUE TITLE
Include repo name in PR tree view

### ISSUE THREAD

**Issue by johnknoop** [microsoft/vscode-pull-request-github#5453]
The team I'm working in has a process where a single work item often results in a few different PRs in different repositories. And we normally give all PRs for a work item the same title. Just now I opened up four different repos to have a look at pull requests that I'm reviewing. But since they all have the same title, the "GitHub Pull Requests" panel in VS Code becomes hard to use. If I want to focus on changes the repo `tm-capacity-api-v2`, then I have to click all of them and hover the PR number to check the URL until I find the repo I'm looking for. Here's a screen grab of me doing just that:

< Images redacted >

**Comment by alexr00** [comment]
To verify:
- Open a folder with more than one repo (could be submodules or a multiroot workspace)
- Check out a PR in more than one of the repos
- In the "Changes in Pull Request" view, verify that the PR's repo now shows next to the PR's title.
- Check out the default branch in all but one of your repos.
- Verify that the repo no longer shows in the "Changes n Pull Request" view.

**Comment by andreamah** [comment]
<img width="411" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/31675041/85b86cb1-f6d2-4f20-b017-9467030104dc">

I'm not seeing the PR's repo here, nor do I see the second PR here. For context, I have a multiroot where PR's are checked out in both workspace roots.
<img width="407" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/31675041/5b845263-fef1-4380-bd1a-562adec3273b">

**Comment by andreamah** [comment]
strangely, when I try to open the repo with the PR that didn't appear as a single-root workspace, the PR view won't load.
<img width="217" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/31675041/3954f69f-4341-468e-a3ca-c4c76a29c01b">

**Comment by andreamah** [comment]
Tried with a different multi-root and it seems that it works!

<img width="348" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/31675041/cd3a821d-040f-4f80-a0af-45e1e9318605">

Seems that it was just a weird bug with one of the repos that I was using in the multi-root.

**Comment by alexr00** [comment]
Was the PR that didn't show closed? By default, only open PRs are shown now.

**Comment by andreamah** [comment]
No, it was an open PR. I tested with https://github.com/microsoft/vscode/pull/199194

**Comment by alexr00** [comment]
It doesn't look like you're being rate limited, but it does look like the wrong host is being used. Will investigate in December: https://github.com/microsoft/vscode-pull-request-github/issues/5528

**Comment by johnknoop** [comment]
Thanks for implementing this! A bit of feedback though:

Screen recording of a set of pull requests I'm reviewing atm:

![862eaf45-64db-411c-a87a-562d2061d161](https://github.com/microsoft/vscode-pull-request-github/assets/3394270/a49d1a42-9288-47c5-86fa-0444efac2266)

As you can see, the repo names aren't visible unless I make the workbench panel really wide. And there's no keyboard shortcut for maximizing the workbench (like there is for maximizing the right-hand side panel) so I have to do it by mouse every time I wish to see the repo names.

**I suggest two improvements:**

1. Make sure the repo name is visible without having to make the workbench really wide, by truncating the name of the PR.
2. Display organization name only if the repos are from different orgs.

I made a mockup of how it would work:

![8cf0412e-8fa6-43c0-885a-6f6e8db5f713](https://github.com/microsoft/vscode-pull-request-github/assets/3394270/70c186f9-817d-49b4-b799-efa35e5fb325)

**Comment by johnknoop** [comment]
Ping @alexr00 ⬆️

**Comment by alexr00** [comment]
> 1. Make sure the repo name is visible without having to make the workbench really wide, by truncating the name of the PR.
> 2. Display organization name only if the repos are from different orgs.

You first feedback point is not implementable with the tree view API that VS Code currently offers. We would need https://github.com/microsoft/vscode/issues/107183 first. With the current API we would only be able to guess at a reasonable length to cut off the title at. For now, I will add the length guessing if all the PRs in the tree have the same title. 

The second point I can address.

**Comment by alexr00** [comment]
Actually, cutting off the title doesn't look too bad. I will add it even if all the titles aren't the same

![image](https://github.com/microsoft/vscode-pull-request-github/assets/38270282/adf31102-9210-403c-b658-e16e7c8f630f)

**Comment by johnknoop** [comment]
@alexr00 Thanks ❤️!
