### ISSUE TITLE
"Git is not installed or otherwise not available" even though it is

### ISSUE THREAD

**Issue by Reedbeta** [microsoft/vscode-pull-request-github#5454]
After installing the extension and logging into Github in VSCode, the extension side panel says "Git is not installed or otherwise not available." Git is installed (via Fork) and is available on my system path, so I'm not sure why the extension can't find it.

- Extension version: v0.76.1
- VSCode Version: v1.84.2
- OS: Windows
- Repository Clone Configuration (single repository/fork of an upstream repository): single
- Github Product (Github.com/Github Enterprise version x.x.x): Github Enterprise Server 3.8.8

**Comment by alexr00** [comment]
Thanks for your patience! This actually indicates that we can't find the built-in git extension, not that git just isn't installed. I'm updating the language now.

You may have disabled the built-in git extension. Just re-enabling it should resolve your issue.

**Comment by alexr00** [comment]
After looking further, it seems my previous statement is incorrect. Does the Source Control view work for you?

**Comment by Reedbeta** [comment]
OK, I had Git disabled in my settings. I'll give it another try with that turned back on.

**Comment by DanTup** [comment]
@alexr00 do you still plan on updating this text? It just caught me out too... it makes it sound like `git` is not available, but it is, and my issue was also just that I had `"git.enabled": false` in my settings.

<img width="466" height="218" alt="Image" src="https://github.com/user-attachments/assets/859c832a-b60d-4492-a505-a80f5b91f912" />

**Comment by alexr00** [comment]
Here you go: https://github.com/microsoft/vscode-pull-request-github/pull/8006

**Comment by alexr00** [comment]
To verify:
1. Install the pre-release version of GitHub Pull Request.
2. Set `git.enabled` to `false`
3. Verify that you see a useful message in the Pull Requests view.
