### ISSUE TITLE
Request for Multi Diff Editor Open Icon / Open changes button doesn't fit with other icons

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#5461]
The icon here doesn't look like it fits, particularly because of the thick stroke width of the lines:

![image](https://github.com/microsoft/vscode/assets/2193314/679779a9-6f68-438c-9b2f-262571434de6)

This might just be a codicon request 🙂 

cc @hediet

**Comment by alexr00** [comment]
The icon for this is definitely not final. @hediet is currently using the magnifying glass, but I'm not a fan of that because it is used so prominently for search.

**Comment by hediet** [comment]
@hbons I think we need a new icon here.

**Comment by hbons** [comment]
how about something like this? I think GitHub also uses this.
<img width="219" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/103326/af896476-8eb5-4109-b396-2595215a5fbd">

**Comment by hbons** [comment]
<img width="302" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/103326/2a320485-d062-4970-b5c1-4102c59e9598">
thoughts?

**Comment by jrieken** [comment]
Unsure, it doesn't really convey that this is about many files/editors

**Comment by Tyriar** [comment]
It is indeed what GH uses so it's definitely better than the current:

![image](https://github.com/microsoft/vscode-pull-request-github/assets/2193314/2a001807-e0f5-4e87-8e48-7cd1ddef2ee9)

How about basing it off `files`?

![image](https://github.com/microsoft/vscode-pull-request-github/assets/2193314/0b010752-f27f-4d38-9392-969e1cf5a2c6)

**Comment by hbons** [comment]
<img width="648" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/103326/2cfdf915-7569-4fe4-b83b-2614824be86b">

**Comment by alexr00** [comment]
It looks very similar to some icons we already have, and which already show in the same place in GHPRI that the "open multi-diff editor" action is.

![image](https://github.com/microsoft/vscode-pull-request-github/assets/38270282/a9cd5098-0744-4e81-89b1-11edcaf4b560)

**Comment by hbons** [comment]
@alexr00 yes, it's the same one. :) GitHub also uses these for difference cases (diffs + changes requested) so I think we're fine doing the same.

**Comment by alexr00** [comment]
👍 sounds good. In GHPRI these icons will show right next to each other, so I like the `diff-multiple` icon to disambiguate.

**Comment by jrieken** [comment]
👍 for all and specifically for `diff-single` for inline chat's new toggle changes feature

**Comment by hbons** [comment]
PR for the icons here: https://github.com/microsoft/vscode-codicons/pull/211

**Comment by Tyriar** [comment]
@hbons shouldn't we offset it up and to the right like `files` since that's an established way to show the concept of "multiple" already? There are also the breakpoints and collapse all which use similar diagonal offsets.

**Comment by hbons** [comment]
@Tyriar yes, but there's no space for that in this case...

**Comment by alexr00** [comment]
Adopted in GHPR. Here's how it looks:

<img width="540" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/38270282/9acd835d-07b1-4a34-a30e-bd3621bec5d0">

**Comment by jrieken** [comment]
And for inline chat with live3

<img width="783" alt="Screenshot 2023-11-29 at 11 20 08" src="https://github.com/microsoft/vscode-pull-request-github/assets/1794099/94ebe124-00ea-43df-871d-ce519124f5a1">

**Comment by hediet** [comment]
Also adopted for all the other multi diff commands.

**Comment by hbons** [comment]
Go team! :D

>
