### ISSUE TITLE
Unable to select default branch (`main`) on upstream repo, when working off a fork

### ISSUE THREAD

**Issue by RasmusWL** [microsoft/vscode-pull-request-github#5470]
- Extension version: v0.76.1
- VSCode Version: 1.84.2
- OS: linux
- Repository Clone Configuration (fork of an upstream repository): origin (my fork): https://github.com/RasmusWL/codeql, upstream: https://github.com/github/codeql
- Github Product: Github.com

Steps to Reproduce:

0. Work on a fork of a repo.
1. Create a branch on top of a non-main branch on your own fork
    <details>

    ```
    $ git log --oneline --graph
    * d93926291d - (HEAD -> example-pr) dummy (33 seconds ago) <Rasmus Wriedt Larsen>
    * 69453aa144 - (origin/clean-tests, clean-tests) Python: Fix missing newline in `.expected` (26 minutes ago) <Rasmus Wriedt Larsen>
    * 55f5b26ba6 - Python: Accept new ordering of query predicates in `.expected` (27 minutes ago) <Rasmus Wriedt Larsen>
    * 721bde1ce8 - Python: Delete orphaned `.expected` files (37 minutes ago) <Rasmus Wriedt Larsen>
    *   2e9d548083 - (upstream/main, upstream/HEAD, origin/main, main) Merge pull request #14706 from RasmusWL/class-attribute-flow (2 hours ago) <Rasmus Wriedt Larsen
    ```
    </details>
2. Use extension to start creating a PR.
   - it initially suggested to use the non-main branch as the target for this PR. ![Image](https://github.com/microsoft/vscode-pull-request-github/assets/1054041/9394d34f-cabe-4555-80b3-2a925e4f8cee)
3. Use the `Change Repository...` feature of the branch selector of the base branch, set it to upstream (github/codeql)
4. Search for `main` on upstream
    - but get no results 😞 
    ![Image](https://github.com/microsoft/vscode-pull-request-github/assets/1054041/0ae67646-f025-4c02-a3de-47b5d35a8f14)

(I am able to select `main` on the `origin` remote, but that just files a PR against the `main` branch on my own fork 🙈)

**Comment by alexr00** [comment]
@RasmusWL the initial suggestion is expected: If you are on a fork, and you create a branch from a branch that isn't the default branch (exactly as you did), then the suggested base branch will be the branch that you branched off of. 

Branches from the upstream repo should be listed in the "Base" picker" as you expected. However, it looks like we aren't detecting your upstream repo at all. Can you share the output of `git remote -v`?

**Comment by RasmusWL** [comment]
Sure thing :+1:

```
$ git remote -v
amammad	git@github.com:amammad/codeql (fetch)
amammad	git@github.com:amammad/codeql (push)
origin	git@github.com:RasmusWL/codeql.git (fetch)
origin	git@github.com:RasmusWL/codeql.git (push)
upstream	git@github.com:github/codeql.git (fetch)
upstream	git@github.com:github/codeql.git (push)
```

**Comment by alexr00** [comment]
Thanks, can you also share the value of `githubPullRequests.remotes`?

**Comment by RasmusWL** [comment]
Hope it's just the value from `Settings` 🤞 

![Image](https://github.com/microsoft/vscode-pull-request-github/assets/1054041/8d3f9885-d8b2-49df-abca-fe606052203b)

```
"githubPullRequests.remotes": [
  "origin",
  "upstream"
]
```

**Comment by alexr00** [comment]
I can repro. We don't fetch all branches if it takes more than 5 seconds to fetch them all. Even when this happens, we should still include `main`.

**Comment by TylerLeonhardt** [comment]
<img width="656" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/2644648/ccf7c3fb-7bd0-43d6-861e-5d2d98add3f2">
Looks good!
