### ISSUE TITLE
Create-PR view: sparkle icon doesn't visually indicate that it has focus

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode-pull-request-github#5471]
https://github.com/microsoft/vscode-pull-request-github/assets/16353531/c78b45fd-0f33-4d0e-ab1f-f763326015f5

GHPR v0.77.2023111509

```
Version: 1.85.0-insider
Commit: 54821ee1f14beca4866abd7de86175b4794b030d
Date: 2023-11-14T12:58:56.073Z
Electron: 25.9.4
ElectronBuildId: 25127168
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.1.0
```

**Comment by ulugbekna** [comment]
@alexr00 A heads up: the focus is hardly visible & seems to have margin issues. Would you like me to create another issue?

<img width="403" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/16353531/f048e992-061d-447d-9fba-03d354ecd808">

**Comment by alexr00** [comment]
SCM is using the same hover background, so I will stay consistent with that. The size of the hover can be improved though.

**Comment by ulugbekna** [comment]
> SCM is using the same hover background

It's just `tab`ing on the sparkle shows blue background

https://github.com/microsoft/vscode-pull-request-github/assets/16353531/d9baa996-93da-4fd7-80e0-73ffed2b89b2

**Comment by alexr00** [comment]
This border has proven to be difficult to replicate in a webview.
