### ISSUE TITLE
Merge queue flow on GH doesn't have squash/rebase/etc. dropdown?

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode-pull-request-github#5475]
GH and GHPR UI for merging using merge queues differs -- the former doesn't allow picking between squashing/rebasing/using a merge commit. Is that intended? 

GH UI: 

![Image](https://github.com/microsoft/vscode-pull-request-github/assets/16353531/92e74b95-83bd-40b6-8762-ce3ec534dd26)

GHPR UI: 

![Image](https://github.com/microsoft/vscode-pull-request-github/assets/16353531/cfd982c3-02f3-4069-9182-211050e2cc09)

GHPR v0.77.2023111514

**Comment by alexr00** [comment]
Already fixed in main!
