### ISSUE TITLE
Missing additional info from GH UI for merge queues

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode-pull-request-github#5476]
Merge queues have additional info in GH UI -- explanation that the repo uses merge queues & usual time to merge. Should it be shown by GHPR as well? 

![Image](https://github.com/microsoft/vscode-pull-request-github/assets/16353531/b15dd717-770f-4855-bba8-fdc33469af31)

**Comment by alexr00** [comment]
Here's what we show when the CI hasn't yet completed/hasn't been reviewed:

<img width="701" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/38270282/bca3b946-205a-49bb-be60-6c44674ef87f">

and when it's ready:

<img width="749" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/38270282/84d7f978-3036-4936-9e90-0525096c5e01">

I can certainly add the "This repository uses the merge queue..." text.

Do you find the dropdown on github.com useful?

**Comment by alexr00** [comment]
Closing as out of scope since I don't feel like that additional text adds much value.
