### ISSUE TITLE
Add a setting to prevent comment window from opening when creating a PR

### ISSUE THREAD

**Issue by Buzzkill-McSquare** [microsoft/vscode-pull-request-github#5479]
When creating a PR using this extension the comment panel pops up. It's a little jarring, especially since there wouldn't be comments on a PR that was just opened. My request is to add a setting to prevent the panel from opening whenever creating a pull request.

**Comment by alexr00** [comment]
This setting already exists 🙂: `"comments.openView": "never"`

**Comment by Buzzkill-McSquare** [comment]
Thanks for pointing this out! I didn't realize there was a setting for this that wasn't tied to the extension.
