### ISSUE TITLE
Checkout PR stuck due to wrongful association of a PR with master branch

### ISSUE THREAD

**Issue by ramya-rao-a** [microsoft/vscode-pull-request-github#548]
Issue Type: <b>Bug</b>

- Create a fork of a repo, make changes, push to the `master` branch of the forked repo, create a PR to the original repo
- Open the original repo in VS Code, add remote to the fork manually, fetch the master branch from the fork, create a branch from this master branch
- Checkout back to your own master from the original repo
- Checkout the PR using the PR extension. The button is stuck at `Checking out...`

At this point, the PR extension finds that there is a local branch already associated with the PR. But it wrongly assumes that the local `master` branch is the one associated with the PR

![image](https://user-images.githubusercontent.com/16890566/46492716-35cd5780-c7c3-11e8-8be0-ca1f97690267.png)

Extension version: 0.1.6
VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-04T16:47:36.731Z)
OS version: Windows_NT ia32 10.0.17134

**Comment by rebornix** [comment]
Did some mitigation for this bug, we will create new branches if this situation happens. The next step is asking git for local branch which is already linked with the fork remote and directly switch to that branch. The reason we don't do it right now is we lack of API from git (our internal git api).

**Comment by ramya-rao-a** [comment]
@rebornix This is still happening.

My local master branch keeps getting associated with a PR I am trying to checkout if the PR is coming from the master branch of another fork.

<img width="559" alt="screen shot 2018-12-03 at 10 08 03 am" src="https://user-images.githubusercontent.com/16890566/49392478-69553100-f6e3-11e8-8bfe-79733e6dcefb.png">
