### ISSUE TITLE
A11y_Visual Studio Code Web Extensions_ GitHub Pull request_ Create Pull request _High Contrast: At high contrast mode "Create with option" arrow button is not visible.

### ISSUE THREAD

**Issue by tripathiakhil429** [microsoft/vscode-pull-request-github#5480]
**GitHub Tags:**  #A11yUsable;#A11yTCS;#BM_Visual Studio Code Web Extensions_Nov2023;#Visual Studio Code Web Extensions;#ChromiumEdge;#DesktopWeb;#A11ySev4;#Win11;#Highcontrast;
 
“[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

**Environment Details**
Application Name: Visual Studio Code Web Extensions
URL: https://insiders.vscode.dev/github/microsoft/vscode-pull-request-github
Operating System: Windows 11 Enterprise Insider Preview(23H2)
OS Build: 25997.1000
Edge version: 120.0.2210.7 (Official build) stable app, dev channel (64-bit)

**Pre-Requisites**

Settings<Accessibility<Contrast Themes<Aquatic Mode.

**Repro Steps**

1.Hit the URL: https://insiders.vscode.dev/github/microsoft/vscode-pull-request-github and login with git hub account.
2.Tab to "More Options" button present in the left navigation panel.
3.Tab to GitHub Pull request and press enter.
4.Tab to Create Pull request and press enter
5.Tab to "Create with Option" arrow button.
6.Observe at high contrast mode "Create with option" arrow button is not visible.

**Actual**

At high contrast mode "Create with option" arrow button is not visible.

**Expected**

At high contrast mode also "Create with option" arrow button should be visible clearly.

**User Impact**

low visibility users will not be able to see the "issue causing control" clearly if the control is not visible in aquatic mode.

**Attachment**
[5480 A11y_Visual Studio Code Web Extensions_ GitHub _Description _High Contrast At high contrast mode Create with option arrow button is not visible.webm](https://github.com/microsoft/vscode-pull-request-github/assets/85679252/29740b00-24a6-4fda-9f86-2f7c1d728c4d)

**Comment by alexr00** [comment]
Occurs with "Desert" high contrast theme, not "Aquatic"

**Comment by tripathiakhil429** [comment]
@alexr00 Verified the issue in given environment(https://insiders.vscode.dev/github/microsoft/vscode-pull-request-github)
The issue is still repro in desert mode.                                                                                                                                                                
Edge Version:121.0.2220.3 (Official build) stable app, dev channel (64-bit)

**Comment by alexr00** [comment]
@tripathiakhil429 the fix was not available yet at that time. To retest:
- Open the environment
- Open the Extensions view
- Look for GitHub Pull Requests and Issues
- If it says a reload is required, reload
- At this point, the fix will be available.
