### ISSUE TITLE
Queries apart from "All Open" don't work, output is full of rate limit errors

### ISSUE THREAD

**Issue by leonid-s-usov** [microsoft/vscode-pull-request-github#5496]
- Extension version: `0.76.1`
- VSCode Version: `Version: 1.84.2 (Universal)`
- OS: `macOs Sonoma 14.1 (23B74)`
- Repository Clone Configuration (single repository/fork of an upstream repository): fork of an upstream with multiple remotes
- Github Product (Github.com/Github Enterprise version x.x.x): `github.com`

The viewlet currently lists the repo and its submodules, with some loaded PRs in the "All Open" section, not showing any pr's content and the custom queries are not loading any PRs. The output shows a sea of rate-limiting errors

Steps to Reproduce:

The plugin didn't ask for a login. just started loading the repo I've opened now (ceph) and all its submodules. I don't know where it took the creds from, maybe from a token in my ~? 
The output below, and the graph QL rate limiting errors appeared within minutes after installing the plugin.

```
2023-11-21 13:09:40.359 [info] RateLimit> Extension rate limit remaining: 4, IssuesWithoutMilestone
2023-11-21 13:09:40.359 [info] RateLimit> Extension rate limit remaining: 3, IssuesWithoutMilestone
2023-11-21 13:09:40.359 [info] RateLimit> Extension rate limit remaining: 2, IssuesWithoutMilestone
2023-11-21 13:09:40.359 [info] RateLimit> Extension rate limit remaining: 1, IssuesWithoutMilestone
2023-11-21 13:09:40.359 [error] RateLimit> API call count has exceeded 140 concurrent calls.
2023-11-21 13:09:40.359 [error] RateLimit> API call count has exceeded 140 concurrent calls.
2023-11-21 13:09:40.359 [error] RateLimit> API call count has exceeded 140 concurrent calls.
2023-11-21 13:09:40.359 [error] RateLimit> API call count has exceeded 140 concurrent calls.
2023-11-21 13:09:40.361 [error] GitHubRepository> Unable to fetch issues: Error: Network error: Response not successful: Received status code 403
2023-11-21 13:09:40.361 [error] GitHubRepository> Unable to fetch issues: Error: Network error: Response not successful: Received status code 403
2023-11-21 13:09:40.361 [error] GitHubRepository> Unable to fetch issues: Error: Network error: Response not successful: Received status code 403
2023-11-21 13:09:40.361 [error] GitHubRepository> Unable to fetch issues: Error: Network error: Response not successful: Received status code 403
2023-11-21 13:09:40.361 [error] GitHubRepository> Unable to fetch issues: Error: Network error: Response not successful: Received status code 403
2023-11-21 13:09:40.362 [error] RateLimit> API call count has exceeded 140 concurrent calls.
2023-11-21 13:09:40.362 [error] RateLimit> API call count has exceeded 140 concurrent calls.
2023-11-21 13:09:40.362 [error] RateLimit> API call count has exceeded 140 concurrent calls.
2023-11-21 13:09:40.362 [error] RateLimit> API call count has exceeded 140 concurrent calls.
2023-11-21 13:09:40.362 [error] RateLimit> API call count has exceeded 140 concurrent calls.
2023-11-21 13:09:40.365 [error] GitHubRepository> Unable to fetch issues with query: Error: Network error: Response not successful: Received status code 403
2023-11-21 13:09:40.365 [error] GitHubRepository> Unable to fetch issues with query: Error: Network error: Response not successful: Received status code 403
2023-11-21 13:09:40.365 [error] GitHubRepository> Unable to fetch issues with query: Error: Network error: Response not successful: Received status code 403
```

tons of these now:

```
2023-11-21 13:19:10.729 [error] Error: GraphQL error: API rate limit exceeded for user ID <my user id>.
	at new e (/Users/leonidus/.vscode/extensions/github.vscode-pull-request-github-0.76.1/dist/extension.js:1837:140)
	...
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by alexr00** [comment]
> and its submodules

The extension definitely has problems with submodules that I need to fix.

Do you have the setting `githubPullRequests.queries` set?

**Comment by leonid-s-usov** [comment]
Yes, I do have it set. I've tried playing with it to see what the problem was but then realized they were not running due to the rate-limiting errors.

Is there a way to prevent the plugin from processing the submodules?

**Comment by leonid-s-usov** [comment]
<img width="991" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/3144935/fa69dfe9-ff03-4e4e-8d5a-6b745f49b9a2">

**Comment by leonid-s-usov** [comment]
Nope. It's just a project with too many submodules :)

**Comment by leonid-s-usov** [comment]
BTW, just noticed that the plugin is listing the same submodules multiple times, e.g. look for `googletest`. A few submodules reference that as their own submodules

**Comment by alexr00** [comment]
It's definitely the submodules then. The rate limit for "search", which is the GitHub api we use for running those queries, is very low, but even if "search" had the standard rate limit I think you might still hit it. Thanks for all the info. Let me look into adding a way to ignore submodules and then I can work on better submodule support in general later.

**Comment by leonid-s-usov** [comment]
I'd like to mention though that I'd expect a controlled rate of requests regardless of the number of submodules, or the number of folders in the workspace. As a potential plugin user, I really don't expect it to load everything at once in parallel. It's OK if the loading is lazy as I browse through the plugin's UI, or if it's in the background, I'd still not expect more than, say, 5 concurrent requests. Even if it's one at a time, I'd be OK

**Comment by alexr00** [comment]
The reasoning behind the current mass fetching of issues is that they are used for the issue completion provider (type `#` and the suggest widget will show issues). The API is too slow to fetch issues after `#` is pressed. When there are this many repos though we definitely need to do better.

**Comment by alexr00** [comment]
I've fixed a few submodules issues, but I've also found that in a multi-repo setup (includes submodules) that we're refreshing the whole PRs way too often. Next fix will be to solve that.

**Comment by alexr00** [comment]
With https://github.com/microsoft/vscode-pull-request-github/pull/5501, the pre-release build tomorrow should be much better. 
You will still need to set something like
```
    "githubIssues.queries": [
        {
            "label": "Test",
            "query": "assignee:${user} is:open"
        },
]
```
as I have not yet address the problem with pre-fetching issues, but the PRs tree should work much better. Note that if you expand all the nodes in the PRs tree and then try to refresh the tree you could still hit a rate limit, but in the default state (where many nodes are collapsed) the tree should work.

**Comment by rondales** [comment]
> * Extension version: `0.76.1`
> * VSCode Version: `Version: 1.84.2 (Universal)`
> * OS: `macOs Sonoma 14.1 (23B74)`
> * Repository Clone Configuration (single repository/fork of an upstream repository): fork of an upstream with multiple remotes
> * Github Product (Github.com/Github Enterprise version x.x.x): `github.com`
> 
> The viewlet currently lists the repo and its submodules, with some loaded PRs in the "All Open" section, not showing any pr's content and the custom queries are not loading any PRs. The output shows a sea of rate-limiting errors
> 
> Steps to Reproduce:
> 
> The plugin didn't ask for a login. just started loading the repo I've opened now (ceph) and all its submodules. I don't know where it took the creds from, maybe from a token in my ~? The output below, and the graph QL rate limiting errors appeared within minutes after installing the plugin.
> 
> ```
> 2023-11-21 13:09:40.359 [info] RateLimit> Extension rate limit remaining: 4, IssuesWithoutMilestone
> 2023-11-21 13:09:40.359 [info] RateLimit> Extension rate limit remaining: 3, IssuesWithoutMilestone
> 2023-11-21 13:09:40.359 [info] RateLimit> Extension rate limit remaining: 2, IssuesWithoutMilestone
> 2023-11-21 13:09:40.359 [info] RateLimit> Extension rate limit remaining: 1, IssuesWithoutMilestone
> 2023-11-21 13:09:40.359 [error] RateLimit> API call count has exceeded 140 concurrent calls.
> 2023-11-21 13:09:40.359 [error] RateLimit> API call count has exceeded 140 concurrent calls.
> 2023-11-21 13:09:40.359 [error] RateLimit> API call count has exceeded 140 concurrent calls.
> 2023-11-21 13:09:40.359 [error] RateLimit> API call count has exceeded 140 concurrent calls.
> 2023-11-21 13:09:40.361 [error] GitHubRepository> Unable to fetch issues: Error: Network error: Response not successful: Received status code 403
> 2023-11-21 13:09:40.361 [error] GitHubRepository> Unable to fetch issues: Error: Network error: Response not successful: Received status code 403
> 2023-11-21 13:09:40.361 [error] GitHubRepository> Unable to fetch issues: Error: Network error: Response not successful: Received status code 403
> 2023-11-21 13:09:40.361 [error] GitHubRepository> Unable to fetch issues: Error: Network error: Response not successful: Received status code 403
> 2023-11-21 13:09:40.361 [error] GitHubRepository> Unable to fetch issues: Error: Network error: Response not successful: Received status code 403
> 2023-11-21 13:09:40.362 [error] RateLimit> API call count has exceeded 140 concurrent calls.
> 2023-11-21 13:09:40.362 [error] RateLimit> API call count has exceeded 140 concurrent calls.
> 2023-11-21 13:09:40.362 [error] RateLimit> API call count has exceeded 140 concurrent calls.
> 2023-11-21 13:09:40.362 [error] RateLimit> API call count has exceeded 140 concurrent calls.
> 2023-11-21 13:09:40.362 [error] RateLimit> API call count has exceeded 140 concurrent calls.
> 2023-11-21 13:09:40.365 [error] GitHubRepository> Unable to fetch issues with query: Error: Network error: Response not successful: Received status code 403
> 2023-11-21 13:09:40.365 [error] GitHubRepository> Unable to fetch issues with query: Error: Network error: Response not successful: Received status code 403
> 2023-11-21 13:09:40.365 [error] GitHubRepository> Unable to fetch issues with query: Error: Network error: Response not successful: Received status code 403
> ```
> 
> tons of these now:
> 
> ```
> 2023-11-21 13:19:10.729 [error] Error: GraphQL error: API rate limit exceeded for user ID <my user id>.
> 	at new e (/Users/leonidus/.vscode/extensions/github.vscode-pull-request-github-0.76.1/dist/extension.js:1837:140)
> 	...
> 	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> ```

**Comment by alexr00** [comment]
I've checked the issue query path, and it looks like it actually isn't subject to the low rate limit that causes this issue. 

The last fix here is to not run too many PR queries in a workspace with multiple repos.

**Comment by andreamah** [comment]
@alexr00 is there a way to verify this issue?

**Comment by alexr00** [comment]
To verify:
- Install the pre-release version of the extension
- Open a workspace with many (at least 6) folders containing GitHub repos.
- Open the Pull Requests view and wait for it to populate
- Open the output of GitHub Pull Request and make sure you don't see any rate limit errors.

**Comment by aiday-mar** [comment]
I am verifying this issue and I see the following:

https://github.com/microsoft/vscode-pull-request-github/assets/61460952/679d4e33-dc46-48b5-ab6b-465b1cb81bc1

I see some rate limit errors. I am wondering if I am supposed to see that?

**Comment by alexr00** [comment]
It looks like the PRs tree loaded ok though. Can you try again and set  this first?
```
    "githubIssues.queries": [
        {
            "label": "Test",
            "query": "assignee:${user} is:open"
        },
]
```

**Comment by aiday-mar** [comment]
With that addition, I do not see the rate limit errors in the output view
