### ISSUE TITLE
Only the first code snippet in a review is shown

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-pull-request-github#55]
Review: https://github.com/xtermjs/xterm.js/pull/1460#pullrequestreview-130283025

![image](https://user-images.githubusercontent.com/2193314/41948766-24c9bdc8-7973-11e8-9728-5c440935ad0c.png)

**Comment by RMacfarlane** [comment]
Duplicate of https://github.com/Microsoft/vscode-pull-request-github/issues/81
