### ISSUE TITLE
GitHub thinks I'm not signed in when I am

### ISSUE THREAD

**Issue by JordanLongstaff** [microsoft/vscode-pull-request-github#5500]
- Extension version: 0.76.1 (latest)
- VSCode Version: 1.84.2 (latest)
- OS: macOS Ventura 13.6.1

After closing and reopening VS Code, the GitHub pane in the Activity bar says I'm not signed in with GitHub, but the Accounts badge down below says that I am. I was before closing VS Code, and I figure that I should be still.

The `Sign in` button in the GitHub pane does nothing when I click it.

To fix: sign out of GitHub in VS Code.

**Comment by angadn** [comment]
Also affected by this issue. It was quite confusing at first because the `Sign in` button shows up only after you `git init` or `git clone` something. I can also confirm that VSCode has my GitHub token (as the Accounts badge shows me as logged in), but the Pull requests and Issues plugin asks me to sign in again. @JordanLongstaff's workaround seems to do the trick

**Comment by angadn** [comment]
@JordanLongstaff any chance this happens because the original GitHub Auth Token that VSCode is initialised with doesn't have the permissions for pull requests and issues? 🤔

**Comment by alexr00** [comment]
This is almost certainly because of what @angadn said about the original token not having the correct scopes.

**Comment by angadn** [comment]
Thanks for confirming @alexr00 - is there a list of required scopes you could share for me to check against?

**Comment by alexr00** [comment]
Scopes are here:

https://github.com/microsoft/vscode-pull-request-github/blob/f852964601f279ef54a5f0c99cd7f0c387fdcb33/src/github/credentials.ts#L30-L32

We need at least `SCOPES_OLDEST` for things to work. In some cases, if you signed in with the extension before though, we'll remember which scopes you had at that time and require that set of scopes for the next sign in.
