### ISSUE TITLE
Unclear repository formatting rules

### ISSUE THREAD

**Issue by Balastrong** [microsoft/vscode-pull-request-github#5505]
Is prettier still being used to format the repo? 

An example, this line is really long:
https://github.com/microsoft/vscode-pull-request-github/blob/5c7d2760d1c0a238c84a31668fb8dd3aa89e9c81/src/issues/issueFile.ts#L157

While prettier config says `"printWidth": 120`
https://github.com/microsoft/vscode-pull-request-github/blob/5c7d2760d1c0a238c84a31668fb8dd3aa89e9c81/.prettierrc#L5

I also tried to run `npm run pretty` and in fact 163 files gets changed/formatted.

---

Besides, in the pre-commit hook running `hygiene.js` the files are checked with [`typescript-formatter`](https://www.npmjs.com/package/typescript-formatter).

**Comment by alexr00** [comment]
Prettier is not being used. I'll remove all references to it.
