### ISSUE TITLE
Test merge queue support

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#5507]
Refs: https://github.com/microsoft/vscode-pull-request-github/issues/5402

- [x] anyOS @joyceerhl 
- [x] anyOS @ulugbekna 
- [x] anyOS @alexdima 

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode-pull-request-github/issues/new?body=Testing+%235507%0A%0A&assignees=alexr00)

---

## Setup

- Testers, I chose you specifically because I know you regularly commit to a repo that uses merge queues. If this is incorrect then feel free to trade!
- Install the pre-release version of GitHub Pull Requests and Issues.

There are two webviews that merge queues need to be tested in:

## Testing in the Create PR view

1. Make a commit or some commits on a topic branch
2. Run the command "Create Pull Request"
3. In the "Create" view, verify that you have the option to create the PR and the option to create the PR and merge it when it's ready. 
4. Verify that if you choose the option the merge the PR when it's ready, that the PR gets automatically added to the merge queue when all branch protection has passed.

## Testing in the PR description

1. Open the PR description of an existing PR and scroll down to the "checks" section
2. Verify that you have an option to merge the PR when it's ready. Verify that you can set and unset this option. Verify that you are not able to select a merge method.
3. Once your PR has been added to the merge queue, verify that you can refresh the PR description and the "checks" section shows that the PR is in the merge queue. Verify that you can remove the PR from the merge queue. Verify that you can re-add the PR to the merge queue.

**Comment by alexdima** [comment]
Works nicely!
