### ISSUE TITLE
Conversations are always expanded

### ISSUE THREAD

**Issue by AndreasArvidsson** [microsoft/vscode-pull-request-github#5512]
Type: <b>Bug</b>

Comments/conversations, resolved and unresolved are shown even though I have collapsed all as the expand state setting.

`"githubPullRequests.commentExpandState": "collapseAll"`

This looks to be a problem when the comment is on the whole file and not a specific line as far as I can tell. Maybe even that there is a comment on the file and the first line but I haven't confirmed this.

Extension version: 0.76.1
VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:51:52.184Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 7900X 12-Core Processor             (24 x 4691)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.15GB (18.97GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by alexr00** [comment]
I'm not sure how we could show collapsed file comments. They would still be visible in the Comments view, but there wouldn't be an entry point for getting to them from the editor.

**Comment by AndreasArvidsson** [comment]
I see. That also has the problem that if you collapse the comment there is no in editor way to get it back. Except for the comments view as you said. 

I just tested the `Add File Comment` button in the top right above the editor. That actually showed the previously collapsed file comment again. I don't know if that is intentional or not. Maybe this icon could change color if there is a file comment?
