### ISSUE TITLE
Button label "Merge when ready" can be confusing

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode-pull-request-github#5514]
Testing #5507

<img width="486" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/16353531/ebfdf0bc-c92f-4995-88fe-a45bd9bfe4f3">

It can be confusing for 2 reasons: 

1. It doesn't match the label in the dropdown which says "Create + Merge when ready" 
2. It doesn't say "create", so user may not expect that the button will create the PR (instead of just toggling "merging when ready")

**Comment by alexr00** [comment]
Unintentional, they should match!
