### ISSUE TITLE
Clicking one file in a PR always opens the file on github, instead of showing the diff

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-pull-request-github#552]
- See this PR https://github.com/Microsoft/vscode-chrome-debug/pull/740/files
- Click package-lock.json
- The file opens in the browser instead of in an editor

I don't think I've seen that before so I'm not sure whether it's supposed to happen in this case for some reason.

**Comment by rebornix** [comment]
We open the file in browser as we don't get the proper content back from GitHub's API, and the API doesn't provide content as the diff is potentially too large.

**Comment by roblourens** [comment]
Oh ok that makes sense

**Comment by roblourens** [comment]
I think this even happened after I checked out the PR. In that case it seems like you have all the content locally?

**Comment by rebornix** [comment]
that's bad, it's definitely a bug.
