### ISSUE TITLE
How do you get to the view that shows all the PRs?

### ISSUE THREAD

**Issue by parched** [microsoft/vscode-pull-request-github#5523]
In the readme it shows this starting view with all the PRs
![image](https://github.com/microsoft/vscode-pull-request-github/assets/5975405/7b203efe-59fe-443c-a756-2c3d458a2181)

But when I open the extension I only see one PR like this
![image](https://github.com/microsoft/vscode-pull-request-github/assets/5975405/9c999c32-8ff4-484a-9761-d98e810c7630)

I'm sure it must be something simple, but I'm not finding it very intuitive.

**Comment by Balastrong** [comment]
Hey @parched, if I see it correctly in your screen, your current branch has an open PR and you're currently looking at the (single) PR view
![image](https://github.com/microsoft/vscode-pull-request-github/assets/7253929/bd8bf374-3743-4862-8f18-ada769186d8b)

However, the view you're referring to from the first screenshot is the actual overview of the extension that has a different icon
![image](https://github.com/microsoft/vscode-pull-request-github/assets/7253929/e6308a56-e282-43ae-bd6b-42d4f039b16f)
If you click there the overview should open.

If you can't see it (in fact, it's not in your screenshot):
A) If you have many extensions (more than the available space) some will be hidden behind this icon 
![image](https://github.com/microsoft/vscode-pull-request-github/assets/7253929/6d6cc2c2-7d4c-4d41-bdd3-6b0613135cce)
Click on it and look for "GitHub"

or

B) If the extension is hidden, try to right click on the PR icon and you should find "Github" unchecked. Click there and the icon will appear.

**Comment by parched** [comment]
Thanks @Balastrong, yes I had it hidden for some reason.

I'll leave this open in case the maintainers want to update the readme as that only shows one icon. Also, it says
> 3. A new viewlet will appear on the activity bar which shows a list of pull requests and issues.

but there are actually 2 viewlets. I'm guessing there used to be one, but that's changed since the readme was written.

**Comment by alexr00** [comment]
Thanks @Balastrong for responding!
