### ISSUE TITLE
[Accessibility] Expose all available actions to command palette, such as review start and approve

### ISSUE THREAD

**Issue by jooyoungseo** [microsoft/vscode-pull-request-github#5527]
Type: <b>Feature Request</b>

CC @meganrogge 

For screen reader users, it looks like there is no way to start reviewing and approve PR using command palette without assigning keybindings like below:

```json
[
  {
    "key": "ctrl+shift+g r",
    "command": "pr.startReview"
  },
  {
    "key": "ctrl+shift+g a",
    "command": "review.approve"
  }
]
```

Please expose as many relevant commands in the command palette as possible for keyboard users for better discoverability and navigability.

Extension version: 0.77.2023112911
VS Code version: Code - Insiders 1.85.0-insider (8762127fc97b8aaae5f3a0dd6a6d853d9a1b7574, 2023-11-29T17:38:23.440Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by alexr00** [comment]
There's no need to run `pr.startReview`, that command is just an implementation detail so that the text on a button is correct when you add your first comment to a PR.

For approving and requesting changes, those buttons are available in the "Active Pull Request" view and pull request description. @jooyoungseo and @meganrogge is it fair to say that for approving or requesting changes it makes sense to keep them out of the command palette so that users can use the input boxes to add a comment when they approve or request changes?

**Comment by meganrogge** [comment]
@jooyoungseo, could you pls help us understand your flow?

@alexr00 it can take a lot of effort for SR / keyboard only users to tab to various buttons. I am wondering if that is why JooYoung is assigning keybindings for these.

**Comment by jooyoungseo** [comment]
I will demonstrate how I use GH PR/issue extension with SR in the meeting with Megan. We can share the recording later.

**Comment by meganrogge** [comment]
Indeed, JooYoung showed that he is often in an editor when he wants to comment on & approve / request changes for a PR. 

I suggest we add commands, with default keybindings when in screen reader mode for:
1. focusing the input box of the PR's review view
2. approving / requesting changes on the PR

@alexr00 I will share the recording when JooYoung has sent it to me.

**Comment by alexr00** [comment]
> 1. focusing the input box of the PR's review view
> 2. approving / requesting changes on the PR
> 3. focusing the PR view
> 4. focus issues

1 will be addressed by https://github.com/microsoft/vscode-pull-request-github/pull/5980, which adds a command to focus the review input in the PR description when the PR description is visible. 
For 2, I would not add commands for this as I think it makes sense to go through the PR description or focus view for these where you can add a review summary comment.
Commands already exist for 3 and 4.

**Comment by alexr00** [comment]
To verify:
- Install the latest pre-release of the extension
- Open a PR description that is long enough for the final input box to be scrolled out of view
- Run the command "GitHub Pull Requests: Focus Pull Request Description Review Input"
- Verify that the review input is scrolled into view and focused.
