### ISSUE TITLE
"Your local changes would be overwritten by checkout" even if they wouldn't

### ISSUE THREAD

**Issue by queerviolet** [Microsoft/vscode-pull-request-github#553]
- Extension version: master
- VSCode Version: insiders (2018-09-25T07:23:31.537Z fe8d9d2470ddffb9dc2da604b23f5bd8a185cd66)
- OS:macOS

Steps to Reproduce:

1. Clone a repo with pull requests
2. `touch this_file_is_unrelated_to_anything`
3. On some PR's description page, click `Checkout`.

You'll see this:

<img width="584" alt="screen shot 2018-10-05 at 4 49 36 pm" src="https://user-images.githubusercontent.com/7763406/46559785-62669980-c8bf-11e8-84a3-12762337bab6.png">

Which is a damned lie. The message suggests stashing, which of course doesn't help, because the files in question aren't tracked.

Another repro, arguably worse:

1. Clone a repo with pull requests
2. Check out a branch that has an active PR
3. `touch this_file_is_unrelated_to_anything`
4. On the description page of the PR you're already on, click `Checkout`.

This incarnation is particularly mind-bending (for me as a user), because to make it work, I have to because we don't have to do anything with git to satisfy the user's intent, which is entering review mode.

Anyway, when the user clicks that checkout button, we should probably just call into git and see what it says about changing branches, rather than trying to do its work for it.

**Comment by rebornix** [comment]
We used to run git ourselves so we have this shortcut for checking local content change. Now we are using VSCode's internal git so we can ask git to do the work for us.
