### ISSUE TITLE
better UI Design

### ISSUE THREAD

**Issue by mannfuri** [microsoft/vscode-pull-request-github#5530]
![图片](https://github.com/microsoft/vscode-pull-request-github/assets/91338215/bcc7fdee-160f-46a7-b6c6-f7a0f83f5265)

I think there is a missing separator line here.

**Comment by aeschli** [comment]
![image](https://github.com/microsoft/vscode-pull-request-github/assets/6461412/26af31d8-7c11-45b7-93ea-f25d00e62343)
