### ISSUE TITLE
PR number in the status bar does not automatically update when I create a new PR.

### ISSUE THREAD

**Issue by kenedyolisi** [microsoft/vscode-pull-request-github#5531]
- Extension version: v0.76.1
- VSCode Version: 1.84.2
- OS: Windows_NT x64 10.0.19045
- Repository Clone Configuration (single repository/fork of an upstream repository):
- Github Product (Github.com/Github Enterprise version x.x.x):

Steps to Reproduce:

1. Open your project in VS Code
2. Create a PR
3. Merge PR
4. Create another PR

**Comment by alexr00** [comment]
I'm not able to reproduce this issue. What steps are you talking between steps 3 and 4 to create a new PR?

**Comment by kenedyolisi** [comment]
Turns out it was a problem with the editor not the extension.
