### ISSUE TITLE
Cannot review PRs with 0.78.0 / VSCode 1.85.0, "GraphQL error: Field 'mergeQueueEntry' doesn't exist

### ISSUE THREAD

**Issue by janakjjp** [microsoft/vscode-pull-request-github#5544]
- Extension version: 0.78.0
- VSCode Version: 1.85.0
- OS: macOS Sonoma 14.1.2
- Repository Clone Configuration (single repository/fork of an upstream repository): N/A (doing pull requests on a single repo)
- Github Product (Github.com/Github Enterprise version x.x.x): GHE 3.7.0 (on-prem)

Steps to Reproduce:

1. Update the extension and VSCode to the aforementioned versions
2. Go to the Pull Request view
3. Receive the error `Fetching pull requests failed: GraphQL error: Field 'mergeQueueEntry' doesn't exist on type 'PullRequest' GraphQL error: No such type MergeQueueEntry, so it can't be a fragment condition`
4. I do not see listed under "Waiting For My Review."

(Is this a dependency on a newer version of GitHub/GHE?)

**Comment by janakjjp** [comment]
Reverting to v0.76.1 fixes the issue.

**Comment by janakjjp** [comment]
My settings.json shows, for the queries section:

```
  "githubPullRequests.queries": [
    {
      "label": "Waiting For My Review",
      "query": "is:open user-review-requested:${user}"
    },
    {
      "label": "Waiting For Team Review",
      "query": "is:open review-requested:${user} draft:false"
    },
    {
      "label": "Assigned To Me",
      "query": "is:open assignee:${user}"
    },
    {
      "label": "Created By Me",
      "query": "is:open author:${user}"
    }
  ],
```

**Comment by alexr00** [comment]
Yes, looks like this isn't available in your version of GHE.

**Comment by alexr00** [comment]
@janakjjp I'm not able to reproduce this issue. I've made a possible fix and it is available in the pre-release build. Would you be able to try out the latest pre-release build and see if the issue still occurs there.

**Comment by janakjjp** [comment]
> @janakjjp I'm not able to reproduce this issue. I've made a possible fix and it is available in the pre-release build. Would you be able to try out the latest pre-release build and see if the issue still occurs there.

I can confirm the newest pre-release works!

**Comment by alexr00** [comment]
@janakjjp that's great news! Thank you for trying it out. I will include the fix in the recovery release this week.

**Comment by theredpea** [comment]
Nice, thanks, fixes for me too! (on Windows 11)
For those who didn't know, you can manage VSCode Pull Request extension in your VS Code extensions
Click on the gear/settings icon to choose "Switch to Pre-Release Version"
![image](https://github.com/microsoft/vscode-pull-request-github/assets/1369723/7ab0f286-db14-41d4-a10f-eba1594239f2)

**Comment by maicss** [comment]
GitHub Enterprise Server 3.9.10

<img width="1423" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/9784767/79381040-66c2-4fc9-8cca-b654c6b87423">

**Comment by alexr00** [comment]
I'm not able to reproduce this. Are you somehow also signed in with a non-enterprise GH account?

**Comment by maicss** [comment]
> I'm not able to reproduce this. Are you somehow also signed in with a non-enterprise GH account?

Sorry, I cannot reproduce this too, because two weeks passed by, and I have tried again, it works fine. Thanks.
