### ISSUE TITLE
Files changed doesn't properly reflect changes against non base branch

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode-pull-request-github#5545]
Type: <b>Bug</b>

Using the VS Code repo as reference
1. Create a branch off the release branch such as release/1.85
2. Make some changes
3. Create a PR
4. :bug: The files changed view shows a ton of changes diffing between main and your branch rather than the proper base.
5. Create PR and realize only your files changed
<img width="399" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/4544166/304d9390-f7d8-430a-b8ec-63e372951ece">

Extension version: 0.79.2023121209
VS Code version: Code - Insiders 1.86.0-insider (Universal) (72cb92fdc5d08101d65d59e4b1c046d397896dd2, 2023-12-12T05:37:56.079Z)
OS version: Darwin x64 23.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|32.00GB (7.79GB free)|
|Process Argv|--crash-reporter-id 7170f6db-7270-442f-945e-4508c02991d4|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
vsc_aacf:30263846
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
showlangstatbar:30737417
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
pythonmpswarning:30901777
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30902439
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
aa_t_chat:30882232

```

</details>

**Comment by alexr00** [comment]
Caused by the refactor I did to support the Copilot sparkle action.

**Comment by lramos15** [comment]
This bug seems back
![image](https://github.com/microsoft/vscode-pull-request-github/assets/4544166/9e76c6b3-951d-421c-abb0-02d0d9138034)

<img width="738" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/4544166/0e780c38-3e74-45e7-83a3-97d3e4851b2e">

**Comment by alexr00** [comment]
I'm not able to repro this. If you see it again, can you switch to the git SCM view, hit refresh, and see if that resolves it?

**Comment by lramos15** [comment]
That does not resolve it

**Comment by alexr00** [comment]
@lramos15 I found a place where I left out a model update from a bad merge last week. Do you still see this? If so, what is `githubPullRequests.createDefaultBaseBranch` set to and are you creating the PR from desktop?

**Comment by JohnRDOrazio** [comment]
I am also seeing the same problem. I make a new Pull Request for feature branch against the `development` branch, but the **files changed** is showing all files changed from the `main` branch, not the `development` branch. Which look pretty scary, and prevents me from continuing to create the PR from VSCode.

![Image](https://github.com/user-attachments/assets/f5f93e31-f306-476c-9312-f362d8d17420)

All those deleted files were already removed / refactored in the `development` branch. They shouldn't be showing in a PR against the `development` branch.

**Comment by lramos15** [comment]
I saw this the other day as well but forgot to loop back to this issue!

**Comment by alexr00** [comment]
@lramos15 what do you have `githubPullRequests.createDefaultBaseBranch` set to and are you creating the PR from desktop?

**Comment by lramos15** [comment]
<img width="698" alt="Image" src="https://github.com/user-attachments/assets/78ebc94d-bf9f-4c5f-b433-76e23ba6bebb" />
@alexr00 Here I hit this due to trying to make a PR with no commits, realizing it, and then going to commit and coming back to the PR view. Refreshing SCM view didn't do anything to help this and no way to refresh PR view
