### ISSUE TITLE
0.79 (probably 0.78 too?) collapses an open PR review tree on refresh

### ISSUE THREAD

**Issue by janakjjp** [microsoft/vscode-pull-request-github#5556]
- Extension version: 0.79 prerelease
- VSCode Version: 1.85.0
- OS: macOS Sonoma 14.1.2
- Repository Clone Configuration (single repository/fork of an upstream repository): N/A (PR review)
- Github Product (Github.com/Github Enterprise version x.x.x): GHE 3.7.0

Steps to Reproduce:

1. Go to the GH Pull Requests & Issues pane.
2. Expand a pull request to review. (Optionally, choose a file.)
3. Hit the refresh button next to the "PULL REQUESTS" header. (Or, just wait until an auto-refresh triggers.)

Expected behavior:

Your current pull request stays open so you can continue reviewing it. This was the behavior in 0.76.

Actual behavior:

The tree closes and refreshes from scratch. This means, if you're mid-review, you must re-expand the PR and find your spot. This is exacerbated by the auto-refresh. If I'm reviewing a PR with many files, I have to keep on expanding and scrolling to my current review spot.

**Comment by alexr00** [comment]
Thanks for reporting this!
