### ISSUE TITLE
"Bad credentials" with no additional information to help resolve

### ISSUE THREAD

**Issue by pgr-tim-rozmajzl** [microsoft/vscode-pull-request-github#5576]
- Extension version: v0.78.1
- VSCode Version: 1.85.1
- OS: Mac Ventura 13.6.1
- Repository Clone Configuration (single repository/fork of an upstream repository):
- Github Product GitHub.com

Steps to Reproduce:

1. Stopped working a few weeks ago
2. Uninstall/Reinstall (and reload vs code)
3. Click on the extension icon on left panel
4. Error message pops up in lower right

![image](https://github.com/microsoft/vscode-pull-request-github/assets/36241595/ada72dea-5a1a-4eaf-a5b6-98ae3b6ca605)

5. Viewed extension logs:

> 2023-12-21 17:30:13.032 [error] GitHubRepository> Fetching all pull requests failed: HttpError: Bad credentials
> 2023-12-21 17:30:13.053 [warning] GitHubRepository> Fetching default branch failed: HttpError: Bad credentials

The problem could well be on my end in some messed up configuration, though I suspect I've entered some weird state not due to my configuration per se.  The "bug" in this bug report (imo) is lack of any guidance/detail that can direct me to potential root causes of this behavior.

btw, I am never at any point prompted for GitHub credentials.

**Comment by alexr00** [comment]
We should definitely have guidance on how to proceed.

In the meantime, if you sign out of GitHub in VS Code then sign back in I expect it will resolve the issue.

**Comment by andreamah** [comment]
@alexr00 are there some minimal verification steps for this?

**Comment by alexr00** [comment]
I'm not sure how to cause the auth token to go bad. Marking as verified.
