### ISSUE TITLE
Timeout occurred while validating state

### ISSUE THREAD

**Issue by scarf005** [microsoft/vscode-pull-request-github#5577]
Type: <b>Bug</b>

> A known error has occurred refreshing the repository state. Please share logs from "GitHub Pull Request" in the [tracking issue](https://github.com/microsoft/vscode-pull-request-github/issues/5277).

[GitHub Pull Request.log](https://github.com/microsoft/vscode-pull-request-github/files/13761184/GitHub.Pull.Request.log)

Extension version: 0.77.2023110909
VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:50:47.800Z)
OS version: Linux x64 6.5.0-14-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600G with Radeon Graphics (12 x 4117)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|17, 9, 6|
|Memory (System)|30.68GB (18.03GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by alexr00** [comment]
Thanks for reporting! I've added more logging since your report which will help narrow it down. If you encounter this again please do share more logs.
