### ISSUE TITLE
PR extension leaves remotes behind

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode-pull-request-github#558]
- Extension version: 0.1.6
- VSCode Version: 1.28-insider
- OS: mac

Steps to Reproduce:

1. open a PR
2. enter review mode
3. exit review
4. :bug: your repo now has one more remote

**Comment by rebornix** [comment]
Agreed that remotes/branches cleaning is one thing we should often do when the extension is running.

**Comment by jrieken** [comment]
Well, I explicit say exit review mode and I think that it leaves garbage behind is a bug

**Comment by alexandrudima** [comment]
This is getting very annoying after a while, when you have 10 remotes which you need to delete one by one from the command line

**Comment by jrieken** [comment]
@rebornix can we get this fixed? this is the reason why I am not the PR extension anymore

**Comment by alexr00** [comment]
Branches and remote will be deleted when you use the "Checkout <default branch>" action.

**Comment by jrieken** [comment]
Thanks @alexr00
