### ISSUE TITLE
Default Create Option: createDraft

### ISSUE THREAD

**Issue by brettcurtis** [microsoft/vscode-pull-request-github#5584]
- Extension version: v0.79.2023122012
- VSCode Version: 1.8.6.0-insider (same issue on stable)
- OS: Windows
- Repository Clone Configuration (single repository/fork of an upstream repository): single repo
- Github Product (Github.com/Github Enterprise version x.x.x): Github.com

Steps to Reproduce:

1. Set: GitHub Pull Requests: Default Create Option to: `createDraft`

3. Publish and use pop-up to create PR

![image](https://github.com/microsoft/vscode-pull-request-github/assets/1610100/8cc0721d-a93e-4092-b8a2-380cb5f816d9)

**Comment by alexr00** [comment]
Fixed by https://github.com/microsoft/vscode-pull-request-github/pull/5635
