### ISSUE TITLE
Allow reviewing closed PRs on github.dev

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode-pull-request-github#5585]
E.g. https://github.dev/microsoft/vscode/pull/201328 - currently there seems to be no way for me to review the changes in this PR in github.dev anymore, because the PR is closed.

**Comment by alexr00** [comment]
This can already be done if you set `githubPullRequests.useReviewMode` to include merged PRs. I think we should change the default for of that setting for vscode.dev and github.dev though.

**Comment by alexr00** [comment]
To verify:
1. Find a merged PR on github.com
2. Open `insiders.vscode.dev` to that PR
3. Verify that the `insiders.vscode.dev` shows the PR in review mode
