### ISSUE TITLE
PR Commits with the same author don't show avatar

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode-pull-request-github#559]
![image](https://user-images.githubusercontent.com/35271042/46620569-f14efe00-cad9-11e8-84ec-5f6fb88073b8.png)

![image](https://user-images.githubusercontent.com/35271042/46620591-0166dd80-cada-11e8-9d7a-2a7306c309fa.png)

Unsure why this is happening on the GitHub side (maybe the user used a different username/account from their GH one?) but GitHub shows an avatar that is not being shown in the PR extension.

**Comment by RMacfarlane** [comment]
This is the default avatar when the committer doesn't match a GH account - we don't have the default avatar asset in the extension so we're just not showing an avatar in this case

**Comment by misolori** [comment]
Can we add the asset to the extension and then use that as a default when we can't show an avatar? Or does that need to come from the API?

**Comment by RMacfarlane** [comment]
This should be fixed as part of https://github.com/microsoft/vscode-pull-request-github/pull/1125
