### ISSUE TITLE
Very Urgent Bug- Close Pull request Button is not working . It must be fixed fast....

### ISSUE THREAD

**Issue by goldbright00000** [microsoft/vscode-pull-request-github#5598]
After i get pull request, i can't close the PR myself. Close button is not working . 
![Screenshot_2](https://github.com/microsoft/vscode-pull-request-github/assets/32250988/438380c5-48fa-490f-8bd0-9d8bc4ca1865)

**Comment by goldbright00000** [comment]
did you fix this bug?

**Comment by alexr00** [comment]
Already fixed by https://github.com/microsoft/vscode-pull-request-github/commit/3faacda5af1630da1f009a2f8838e034cf2cd0cf
