### ISSUE TITLE
Show All Buttons Comment/Request Changes/Approve when there is enough space

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode-pull-request-github#5611]
Currently it looks like this:

![Image](https://github.com/microsoft/vscode-pull-request-github/assets/2931520/cbbefcd1-d7fd-4dee-8e30-bbebbbc5e4ed)

I think it would be nice if it looked like this when there is enough horizontal space:

![Image](https://github.com/microsoft/vscode-pull-request-github/assets/2931520/650bd0f0-d29f-4e15-958d-3388ae8260fc)

[I think I lose some mental energy](https://youtu.be/cUbIkNUFs-4?t=33) when I want to approve, but I have to first click on the drop down of "Request changes".

**Comment by alexr00** [comment]
@hbons in case you also have thoughts on this!

**Comment by alexr00** [comment]
It's a bit funny because I actually just removed these in the full sized view: https://github.com/microsoft/vscode-pull-request-github/issues/5334

**Comment by alexr00** [comment]
@bpasero you recently requested that I move the three buttons into the dropdown menu in the full editor webview in https://github.com/microsoft/vscode-pull-request-github/issues/5334. Now, I've gotten the request to expand the dropdown out into 3 buttons when space permits in the sidebar webview. If I make this change in the sidebar, I would also move the 3 options back into 3 buttons in the editor webview, since space always permits there. Do you have any opinion on this?

**Comment by bpasero** [comment]
I still like and prefer the dropdown for reducing UI complexity.

**Comment by hediet** [comment]
@benibenj also noted that it is difficult to find the approve button.

> I still like and prefer the dropdown for reducing UI complexity.

I agree that it reduces UI complexity, but I would argue that this comes at the cost of increased mental complexity.
"Approve" and "Request Changes" are not suboptions of "Comment", they are primary actions with opposite effects.

Especially when "Request Changes" is pre-selected, it causes mental resistance to click on its drop-down to select "Accept", as they have opposite effects.

**Comment by alexr00** [comment]
To verify: 
- Install the pre-release version of GitHub Pull Requests.
- Open a folder that contains a GitHub repository and some pull requests.
- Check out a pull request that isn't yours
- Open the active pull request view (this is the webview in the sidebar) and drag it larger and smaller. Verify that when it's "small" you get one button with the drop down caret for completing your review. Verify that when it's "big enough" you get all three buttons in a row (comment, approve, request changes).
