### ISSUE TITLE
Input Validation Error Has the Wrong Foreground Color

### ISSUE THREAD

**Issue by pouyakary** [microsoft/vscode-pull-request-github#5620]
- Extension version: 0.78.1
- VSCode Version: 1.85.1
- OS: Irrelevant
- Repository Clone Configuration (single repository/fork of an upstream repository): Irrelevant
- Github Product (Github.com/Github Enterprise version x.x.x): Irrelevant

This may seem small, but the vscode's color for input validation error is `inputValidation.errorForeground`. This extension however, uses:

<img width="397"  src="https://github.com/microsoft/vscode-pull-request-github/assets/2157285/ea8949ff-53c2-4029-8b28-13db89481238">

Which, when it comes to my theme breaks both the beauty and readability of the validation widget: 

<img width="376" src="https://github.com/microsoft/vscode-pull-request-github/assets/2157285/7bb17cad-b765-45de-bbe6-cf08ec71bc46">

**Comment by eleanorjboyd** [comment]
@pouyakary are you able to verify if this bug is now fixed?

**Comment by mjbvz** [comment]
Also took a look but not sure how to trigger the validation dialog to test this

**Comment by rzhao271** [comment]
Got one by changing around the merge (non-base) branch to an already-merged branch and trying to create a PR from there.

![Example validation dialog with correct colours](https://github.com/microsoft/vscode-pull-request-github/assets/7199958/b7eb6040-ca89-46ba-80c5-0c22b675602e)

**Comment by pouyakary** [comment]
@eleanorjboyd I have tested the code, and it works. should I also test any release?

**Comment by eleanorjboyd** [comment]
Testing this code is great, thanks so much!
