### ISSUE TITLE
Do not require read and write access to all private repos

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode-pull-request-github#563]
Really, it's bad enough that almost every GitHub integration demands read/write access to private repos, but for Github's own projects to do the same is a really poor example.

![screen shot 2018-10-09 at 8 44 34 am](https://user-images.githubusercontent.com/1078012/46654293-66850680-cba0-11e8-86f9-4f205d973ef8.png)

It should be possible to use this extension with just public repos without granting full access to everything. I'm aware that GitHub essentially already have access to private repos, but that's not the point. If GH won't bother to support public-repos only, what hope do we have from 3rd parties? This doesn't help educate users to be careful with their permissions.

**Comment by sguthals** [comment]
👋  @DanTup 

Thanks for opening up this issue. Unfortunately, we aren't going to limit the repository access to only public repos at this time. When you authenticate with GitHub through our extension, you are authenticating for all of your repositories.

**Comment by DanTup** [comment]
Understood. I think it's a bad decision (honestly, I'm as disappointed in the example being set than missing out on the extension - given users are already conditioned to just blindly accept permissions for everything) but of course it's your call. Thanks for the response.

**Comment by sguthals** [comment]
Definitely something we will continue to keep in mind as we iterate on this and our other extensions.

**Comment by queerviolet** [comment]
In principle, I agree, and we're definitely looking into offering more granular permissions for all apps.

This particular case is a bit of a weird hill to die on, though. The server sends back the token and promptly forgets it; the token is stored locally in your system keychain. The additional exposure from holding onto it is that an attacker who gains access to your system keychain can access your private GitHub repos—which, sure, isn't great, but it's pretty far down the list of not-great things happening to you at that point.

The other concern is that if we don't request access to all repos, and a user later tries to push to one, we either fail, or we have to go through the auth flow again. The former will feel broken. Like literally, here I am, in my editor, trying to make a pull request on a repo I own, and this dumb extension can't do it? The latter seems arguably worse than what we have now, from a security UX standpoint. If you're concerned about training users to thoughtlessly click through oauth approval screens, we probably want to present fewer of those screens, not more of them.

All that said, we're definitely aware of the issues with excessive scope requests for apps in general, and we're looking into ways of handling auth situations like these in a more graceful, granular way in the future.

**Comment by trusktr** [comment]
Opening a bigger than needed attack surface area is no good.

Make the plugin request per-project maybe, associated to one repo (or only the repos in the project) maybe?

**Comment by balboah** [comment]
Not sure if this is the right place for this rant.
But the authentication screen for copilot chat also wants write access to private repos, and refers to https://github.com/Visual-Studio-Code which is an empty repo.

Almost looks like a fishing attempt to gain write access into private repos, until looking more carefully when you can see on the members list and X (twitter) verification that it might be legit.

<img width="420" alt="Skärmavbild 2024-02-09 kl  13 50 58" src="https://github.com/microsoft/vscode-pull-request-github/assets/294690/47b4e5c2-5cb6-46c3-9bd9-2657a71a1136">

**Comment by mcissel** [comment]
GitHub apps offer this by default. Maybe in 2018 it didn't make sense to cater to the security minded folks. But now, authorizing a GitHub app is a simple and straight forward flow, where users are seemlessly guided through a couple easy steps to authorize the GH app on only specific repos.

It might be required to switch these extensions from using GitHub OAuth to being GitHub Apps. I'd prefer the extensions' interactions with my repo be branded with the GH App name vs. my own username, so there's another boon.

**Comment by ckarsan** [comment]
The same now for AntiGravity IDE , does it now mean google will also have a way to access to private repos ?
