### ISSUE TITLE
Pull Request #null when exiting review mode

### ISSUE THREAD

**Issue by bm-stschneider** [Microsoft/vscode-pull-request-github#564]
Issue Type: <b>Bug</b>

When exiting review mode I see `Pull Request #null` in the bottom status bar.

![image](https://user-images.githubusercontent.com/30625381/46677001-f8f9ca00-cbe1-11e8-9551-38282e4d368b.png)

Extension version: 0.1.7
VS Code version: Code - Insiders 1.29.0-insider (5bd6ebe2dbc4dee510699020a25f70a69784ce8c, 2018-10-09T09:24:52.091Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|-psn_0_884952|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by RMacfarlane** [comment]
@bm-stschneider Does this happen every time you exit review mode? Does the status bar item continue to show after that, or is it eventually removed? When you exit, do you return to master, or a different branch?

**Comment by bm-stschneider** [comment]
It does not happen every time.
It does not get removed.
I do return to master.

**Comment by rebornix** [comment]
@RMacfarlane do you think we didn't clear `this._validateStatusInProgress` ever and the `else` path is never executed?

https://github.com/Microsoft/vscode-pull-request-github/blob/ac8861dd9f2524a1cadcab56f99ff3e26879eec1/src/view/reviewManager.ts#L188-L194

**Comment by bm-stschneider** [comment]
Did you just break the PR feature?
