### ISSUE TITLE
Test `githubPullRequests.createDefaultBaseBranch` setting

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#5644]
Refs: https://github.com/microsoft/vscode-pull-request-github/issues/5425

- [x] anyOS @TylerLeonhardt
- [x] anyOS @lszomoru

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode-pull-request-github/issues/new?body=Testing+%235644%0A%0A&assignees=alexr00)

---

## Setup

Clone a GitHub repo and open your clone in VS Code.
Install GitHub Pull Requests and Issues pre-release

## Testing

Default setting value
1. Make sure `githubPullRequests.createDefaultBaseBranch`  is not set.
2. Create a topic branch, switch to it, and push it. This will be branch A.
3. Create another topic branch and switch to it. This will be branch B.
4. Run the command "Create Pull Request"
5. Verify that the "into" (base) branch for the PR defaults to branch A.

`repositoryDefault` setting value
1. Set `"githubPullRequests.createDefaultBaseBranch": "repositoryDefault"`
2. Create a topic branch, switch to it, and push it. This will be branch A.
3. Create another topic branch and switch to it. This will be branch B.
4. Run the command "Create Pull Request"
5. Verify that the "into" (base) branch for the PR defaults to the repo's default branch (likely `main` or `master`).

**Comment by alexr00** [comment]
Updated the TPI to include pushing branch A in step 2 of both test paths.

**Comment by lszomoru** [comment]
Works as described. Great work 👏🏻

**Comment by TylerLeonhardt** [comment]
Works nicely :)
