### ISSUE TITLE
Test local file links in PR review comments

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#5646]
Refs: https://github.com/microsoft/vscode-pull-request-github/issues/4569

- [x] anyOS @justschen
- [x] anyOS @bhavyaus 

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode-pull-request-github/issues/new?body=Testing+%235646%0A%0A&assignees=alexr00)

---

1. Install the pre-release version of GitHub Pull Requests and Issues
2. Open a clone of a GitHub repo in VS Code. Check out a PR.
3. Open a file from the repo. Select some lines and use the "Copy Permalink" command to create a permalink.
4. Open a file that's in the PR and leave a comment. Paste your permalink into the comment.
5. Verify that when you save the comment it shows a link for the file. Verify that if you click on the link it takes you to the local file. Verify that there's an option to open the file on github.com. Verify that opening the file on github.com works.

**Comment by justschen** [comment]
testing with https://github.com/Yoyokrazy/clean-nb-imports-ext/pull/7

path was this:
<img width="360" alt="Screenshot 2024-01-23 at 11 09 25 AM" src="https://github.com/microsoft/vscode-pull-request-github/assets/54879025/4abd4df1-c456-4699-9b16-b1213397f57e">

lgtm!
