### ISSUE TITLE
Test merging base branch on check out with new values of `githubPullRequests.pullPullRequestBranchBeforeCheckout`

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#5647]
Refs: https://github.com/microsoft/vscode-pull-request-github/issues/4375

- [x] anyOS @bhavyaus  
- [x] anyOS @rzhao271  

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode-pull-request-github/issues/new?body=Testing+%235647%0A%0A&assignees=alexr00)

---

1. Install the pre-release version of GitHub Pull Requests and Issues
2. Look at the setting `githubPullRequests.pullPullRequestBranchBeforeCheckout`. Verify that you can understand the options for the setting.

Test `pullAndMergeBase`
1. Open a folder that contains a clone of a GitHub repo
2. Set `"githubPullRequests.pullPullRequestBranchBeforeCheckout": "pullAndMergeBase"`
3. Checkout a PR from the "Pull Requests" view that is behind it's base branch. For example, the base branch of the PR is `main`, and `main` has had more commits since the PR was made.
4. After checkout, run `git log`. Verify that you see a local commit that merged the base branch into the PR.

Test `pullAndUpdateBase`
1. Open a folder that contains a clone of a GitHub repo
2. Set `"githubPullRequests.pullPullRequestBranchBeforeCheckout": "pullAndUpdateBase"`
3. Checkout a PR from the "Pull Requests" view that is behind it's base branch. For example, the base branch of the PR is `main`, and `main` has had more commits since the PR was made.
4. After checkout, open the PR on GitHub. Verify that there is a commit from you that merges the base branch into the PR.

**Comment by joaomoreno** [comment]
Thank you @bhavyaus for taking this.
