### ISSUE TITLE
Test resolving conflicts on a checked out PR

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#5648]
Refs: https://github.com/microsoft/vscode-pull-request-github/issues/1562

- [x] macOS @anthonykim1
- [x] linux @deepak1556
- [x] windows @sandy081

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode-pull-request-github/issues/new?body=Testing+%235648%0A%0A&assignees=alexr00)

---

To test, you'll need to have a PR with merge conflicts. If you have such a PR already, you can skip step 2.
1. Install the pre-release version of GitHub Pull Requests and Issues
2. Checkout or make a PR that has merge conflicts. To make a PR with merge conflicts:
  a. Look at what the most recent commit on `main` has changed. Take note of this.
  b. Do `git log` and copy the second most recent commit sha
  c. `git checkout the-commit-sha-you-copied`
  d. `git checkout -b topic-branch-name-of-your-choice`
  e. Modify the same code that you noted in step a. Commit this and make a PR.
3. Open the PR's description/overview page. 
4. Verify that you see a button to "Resolve Conflicts". Verify that you only see this button when the PR is checked out.
5. Use the button to "Resolve Conflicts". Verify that you can resolve the conflicts. Verify that the button from step 4 no longer shows once you're done.

**Comment by deepak1556** [comment]
The scroll glitch is making it hard to work with the conflicts view, will wait for it to get fixed.

**Comment by anthonykim1** [comment]
I think it is working for Mac? I tried to record my testing and I didn't see the scroll glitch. See attached

<img width="351" alt="Screenshot 2024-01-23 at 10 34 27 AM" src="https://github.com/microsoft/vscode-pull-request-github/assets/62267334/27f7b9b2-5db7-44fc-b01b-daf250dc5af1">

https://github.com/microsoft/vscode-pull-request-github/assets/62267334/544cc423-d646-499a-9c4b-d0c24d6c5569

**Comment by deepak1556** [comment]
The issue happens depending on the number files involved with conflicts. I was able to test the flow with a PR that had a single file conflict.
