### ISSUE TITLE
Test bringing a checked out PR up to date with base

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#5649]
Refs: https://github.com/microsoft/vscode-pull-request-github/issues/200

- [x] macOS @bhavyaus
- [x] linux @deepak1556
- [x] windows @jrieken 

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode-pull-request-github/issues/new?body=Testing+%235649%0A%0A&assignees=alexr00)

---

To test, you'll need to have a PR that's out of date with it's base. If you have such a PR already, you can skip step 2.
1. Install the pre-release version of GitHub Pull Requests and Issues
2. Checkout or make a PR that is out of date with base, but doesn't have conflicts. To make a PR that's out of date with base:
  a. Do `git log` and copy the second most recent commit sha
  b. `git checkout the-commit-sha-you-copied`
  c. `git checkout -b topic-branch-name-of-your-choice`
  d. Modify a file that hasn't been touched recently, commit, and make a PR.
3. Open the PR's description/overview page. 
4. Verify that you see a button to "Update with Merge". Verify that you only see this button when the PR is checked out.
5. Use the button to "Update with Merge". Verify this merges the base branch into the PR branch. Verify that the button from step 4 no longer shows once you're done.

**Comment by andreamah** [comment]
Oops, didn't notice that Joh already started testing this- I'll let him finish testing it.
