### ISSUE TITLE
In pull request description, links are not inline

### ISSUE THREAD

**Issue by szhu** [Microsoft/vscode-pull-request-github#565]
Issue Type: <b>Bug</b>

| What it looks like on GitHub | What it looks like in the extension | 
| --- | --- |
| ![image](https://user-images.githubusercontent.com/1570168/46691811-993bf880-cbba-11e8-85b8-eecb34fa8bc5.png) | ![image](https://user-images.githubusercontent.com/1570168/46691844-a9ec6e80-cbba-11e8-9775-07b310db2f49.png) |

Note that "readme" and "common mistakes" are on their own line.

Extension version: 0.1.7
VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-04T16:40:40.180Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (3.99GB free)|
|Process Argv|-psn_0_40970|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by RMacfarlane** [comment]
@szhu Can you copy and paste the markdown text here?

**Comment by szhu** [comment]
```markdown
<!-- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/29395 -->

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://www.npmjs.com/package/query-string
- [ ] Increase the version number in the header if appropriate. _Do I need to?_
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.
```
