### ISSUE TITLE
githubIssues.queries `groupBy` not shown

### ISSUE THREAD

**Issue by ntrogh** [microsoft/vscode-pull-request-github#5651]
Testing #5650

Insiders, latest pre-release, Windows

Repro steps:
1. Open user settings
2. Search for `githubIssues.queries`
3. Select **Edit in settings.json**
4. The three queries have no `groupBy` value in them
![vscode-issues-queries-groupby](https://github.com/microsoft/vscode-pull-request-github/assets/1908215/4c94bfa0-a333-40c3-b554-492117f4fa6f)

**Comment by alexr00** [comment]
@ntrogh it looks like you have some extension updates pending. Can you make sure that GitHub Pull Requests and Issues is on the very latest pre-release version? I just made the change for this yesterday.

**Comment by ntrogh** [comment]
@alexr00 This issue is indeed fixed with the extension update. Apologies!
