### ISSUE TITLE
`githubIssues.queries` setting - invalid `groupBy` value adds milestone grouping

### ISSUE THREAD

**Issue by ntrogh** [microsoft/vscode-pull-request-github#5652]
Testing #5650

insider, pre-release, Windows

Repro steps:

1. In `settings.json`, add `groupBy` value `assignee` or any value other than `milestone` or `repository`
2. When you add an invalid value, a grouping by milestone is added to the list of issues. If multiple invalid values are added, additional groupings are added.

![vscode-issues-queries-groupby2](https://github.com/microsoft/vscode-pull-request-github/assets/1908215/205b94b7-5400-4306-9f88-2ae6c3cb896f)
![vscode-issues-queries-groupby3](https://github.com/microsoft/vscode-pull-request-github/assets/1908215/d42e8f7c-32e4-480e-b795-378623d5b128)

**Comment by alexr00** [comment]
Nice find!
