### ISSUE TITLE
Local link doesn't work if the permalink is from a fork

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#5655]
Testing #5646

Example: https://github.com/microsoft/vscode-docs/pull/6962#discussion_r1463158177

**Comment by bhavyaus** [comment]
I'm still the permalink opening in the browser and not in my workspace when I checked out [the pr mentioned above](https://github.com/microsoft/vscode-docs/pull/6962#discussion_r1463158177) and clicked on the permalink mentioned in the comments.

**Comment by alexr00** [comment]
I can't repro this. @ntrogh could you try verifying this?

**Comment by ntrogh** [comment]
Unable to repro this either (running on GHPRI v0.79.2024012510 ) @alexr00 @bhavyaus
