### ISSUE TITLE
Linkify issue references

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode-pull-request-github#566]
Issue Type: <b>Feature Request</b>

If a PR has a title lile `fix issue #46816` then we should linkify the issue reference in the title.

Extension version: 0.1.7
VS Code version: Code - Insiders 1.29.0-insider (5bd6ebe2dbc4dee510699020a25f70a69784ce8c, 2018-10-09T09:31:07.090Z)
OS version: Windows_NT x64 10.0.17763

**Comment by emtei** [comment]
It looks like nice enhancement but I have one thought here: how we can recognise if this is a PR or an issue id?

**Comment by RMacfarlane** [comment]
From https://github.com/Microsoft/vscode-pull-request-github/pull/831, content on the description page should now use HTML from GitHub
