### ISSUE TITLE
`Update with merge commit`button does not go away despite merging

### ISSUE THREAD

**Issue by bhavyaus** [microsoft/vscode-pull-request-github#5661]
Testing #5649

I used the button to merge in newer changes from the base. After which I expected the button to disappear but the button remains.

https://github.com/microsoft/vscode-pull-request-github/assets/25044782/2399bc25-790c-4a89-9ae4-ba125983d1b5

**Comment by alexr00** [comment]
@bhavyaus did you also push you merge?

**Comment by bhavyaus** [comment]
> [@bhavyaus](https://github.com/bhavyaus) did you also push you merge?

No. I did not take any other actions besides click on the "Update with merge commit". Would that not also push my merge?

**Comment by alexr00** [comment]
You're correct, it should push your merge. I was confusing this with the "resolve conflicts" button. I think the only issue is that it's a little slow to update. I'll add button disablement and make it a bit faster to update.
