### ISSUE TITLE
Github permalinks not opening file in vscode

### ISSUE THREAD

**Issue by bhavyaus** [microsoft/vscode-pull-request-github#5663]
Testing #5646

Testing on the Mac. Pasting worked fine, but clicking on the link is no-op. See gif below:

![Image](https://github.com/microsoft/vscode-pull-request-github/assets/25044782/59f1893f-3baf-471f-92f1-8204b141870c)

**Comment by alexr00** [comment]
Looks like the file is already open. You can see that it's selecting the first line, as is expected for the permalink you used.
