### ISSUE TITLE
Pull request description page does not show resolve conflict action when checkout branch and current branch are same

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode-pull-request-github#5665]
Testing #5648

* Check out branch locally to the one that has conflicts
* In the PR view, see the action to check out pull request
* Nothing happens as the expected branch and current branch are same
* I would expect the checkout action to work or the pull request description should be updated

https://github.com/microsoft/vscode-pull-request-github/assets/964386/eeac5371-2a47-44dd-89b0-990d2db3cb68

**Comment by alexr00** [comment]
It seems we're not associating the current branch with that PR. Can you share the output from GitHub Pull Request and from Git?

**Comment by alexr00** [comment]
Closing as no further information was provided.
