### ISSUE TITLE
Completing the merge action still shows notification that there are pending conflicts in scm view

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode-pull-request-github#5666]
Testing #5648

In the screenshot below you can see there are no pending conflicts in the scm view but the notification indicates there is.

![Screenshot 2024-01-24 at 14 05 00](https://github.com/microsoft/vscode-pull-request-github/assets/964386/9d27bdc3-87dd-4c94-8533-59abc6773368)

**Comment by alexr00** [comment]
@deepak1556 did you commit the merge?

**Comment by deepak1556** [comment]
Yes I did, the line `Merge branch 'main' into robo/test` is from the merge commit.

**Comment by alexr00** [comment]
Did you commit via the command line?

**Comment by deepak1556** [comment]
Nope, I did it from the SCM view

**Comment by alexr00** [comment]
I assume then that you resolved the merge without using the merge editor.
