### ISSUE TITLE
Show more details in tree view tooltip

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-pull-request-github#568]
Right now it just re-displays the PR title, it would be nice to also show the author as sometimes it's not obvious (hard to diff the top and bottom avatars):

![image](https://user-images.githubusercontent.com/2193314/46769484-d4b0f280-cca0-11e8-930a-400455efaa24.png)

**Comment by jerrymajewski** [comment]
I added a PR to show more tooltip details here: https://github.com/Microsoft/vscode-pull-request-github/pull/577
