### ISSUE TITLE
Pull request list empty

### ISSUE THREAD

**Issue by bm-stschneider** [microsoft/vscode-pull-request-github#569]
Issue Type: <b>Bug</b>

Seems like there is an issue that no pullrequests are received from github?

![image](https://user-images.githubusercontent.com/30625381/46788811-450c5200-cd3b-11e8-89b6-f0c59aa66245.png)
```json 
{
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 70,
		"activateCallTime": 2,
		"activateResolvedTime": 41,
		"activationEvent": "*"
	}
}
```
[CPU-20181011T075358.129Z.cpuprofile.txt](https://github.com/Microsoft/vscode-pull-request-github/files/2467862/CPU-20181011T075358.129Z.cpuprofile.txt)

Extension version: 0.2.0
VS Code version: Code - Insiders 1.29.0-insider (f151c46b1783cf4f9a4ca934a85f78846f08688e, 2018-10-11T05:11:48.238Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.28GB free)|
|Process Argv|-psn_0_1315137|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by bm-stschneider** [comment]
Private, sorry

**Comment by rebornix** [comment]
It would be great if you share the log in output panel (sanitizing the repo info is okay) to help us better troubleshoot.

**Comment by bm-stschneider** [comment]
```
Found GitHub remote
Review> no matching pull request metadata found for current branch <branch>
GithubRepository> Unable to fetch PR: {"message":"Not Found","documentation_url":"https://developer.github.com/v3/pulls/#get-a-single-pull-request"}
GithubRepository> Unable to fetch PR: {"message":"Not Found","documentation_url":"https://developer.github.com/v3/pulls/#get-a-single-pull-request"}
GithubRepository> Unable to fetch PR: {"message":"Not Found","documentation_url":"https://developer.github.com/v3/pulls/#get-a-single-pull-request"}
GithubRepository> Unable to fetch PR: {"message":"Not Found","documentation_url":"https://developer.github.com/v3/pulls/#get-a-single-pull-request"}
GithubRepository> Unable to fetch PR: {"message":"Not Found","documentation_url":"https://developer.github.com/v3/pulls/#get-a-single-pull-request"}
GithubRepository> Unable to fetch PR: {"message":"Not Found","documentation_url":"https://developer.github.com/v3/pulls/#get-a-single-pull-request"}
GithubRepository> Unable to fetch PR: {"message":"Not Found","documentation_url":"https://developer.github.com/v3/pulls/#get-a-single-pull-request"}
GithubRepository> Unable to fetch PR: {"message":"Not Found","documentation_url":"https://developer.github.com/v3/pulls/#get-a-single-pull-request"}
GithubRepository> Unable to fetch PR: {"message":"Not Found","documentation_url":"https://developer.github.com/v3/pulls/#get-a-single-pull-request"}
GithubRepository> Unable to fetch PR: {"message":"Not Found","documentation_url":"https://developer.github.com/v3/pulls/#get-a-single-pull-request"}
GithubRepository> Unable to fetch PR: {"message":"Not Found","documentation_url":"https://developer.github.com/v3/pulls/#get-a-single-pull-request"}
GithubRepository> Unable to fetch PR: {"message":"Not Found","documentation_url":"https://developer.github.com/v3/pulls/#get-a-single-pull-request"}
```

**Comment by bm-stschneider** [comment]
![image](https://user-images.githubusercontent.com/30625381/47640611-38be2c80-db64-11e8-96cc-ec2d65920817.png)
is still a thing

**Comment by einord** [comment]
Any news on this? I have perhaps the same, or a similar issue.

When using Visual Studio (with the GitHub extension), I can see all current pull requests
<img width="342" alt="skarmavbild 2019-02-21 kl 11 24 10" src="https://user-images.githubusercontent.com/19638376/53162012-6b84a880-35cb-11e9-963e-49d86bed464e.png">

But in vscode (macOS), I see nothing.
<img width="276" alt="image" src="https://user-images.githubusercontent.com/19638376/53161669-b3570000-35ca-11e9-8a8d-d0b64f17e8b8.png">

This is also a private repository.

From my output panel:
```
[Info] /Users/[username]/.ssh/config: ENOENT: no such file or directory, open '/Users/[username]/.ssh/config'
[Info] Looking for git repository
[Info] Git repository found, initializing review manager and pr tree view.
[Info] Found GitHub remote
[Info] https://api.github.com: GraphQL support detected
[Info] {
  "data": {
    "viewer": {
      "login": "[username]",
      "__typename": "User"
    }
  },
  "loading": false,
  "networkStatus": 7,
  "stale": false
}
[Info] Review> no matching pull request metadata found for current branch master
[Info] Found GitHub remote
[Info] Review> no matching pull request metadata found for current branch master
```

**Comment by einord** [comment]
On further investigation on this issue, it seems like this depends on the fork.

When I clone my own fork, but add the original repository as a secondary remote it does not work.
But if I clone the original repository, it finds all pull requests.

**Comment by RMacfarlane** [comment]
@einord From a recent change, the extension now looks for remotes named `origin` and `upstream` by convention and displays PRs from those - you can configure this with the `githubPullRequests.remotes` setting

**Comment by einord** [comment]
@RMacfarlane Works like a charm. Thank you!

**Comment by PoisonousJohn** [comment]
I have a bit different case

```
[Info] Looking for git repository
[Info] Git repository found, initializing review manager and pr tree view.
[Info] No GitHub remotes found
[Info] Review> no matching pull request metadata found for current branch master
[Info] Found GitHub remote
[Info] https://api.github.com: GraphQL support detected
[Info] Review> no matching pull request metadata found for current branch master
```
I have multiple source control providers, can it be because of that?

![image](https://user-images.githubusercontent.com/1488281/55644037-5f505580-57dd-11e9-9561-b69d9c540838.png)

**Comment by RMacfarlane** [comment]
@PoisonousJohn Yes, I think the multiple source control providers is the issue. There was a bug in VSCode 1.33 that prevented selection change events from reaching this extension (https://github.com/Microsoft/vscode-pull-request-github/issues/1111), so choosing a different provider wasn't updating the PR list. It should be already fixed in the [VS Code Insiders](https://code.visualstudio.com/insiders/)

**Comment by RMacfarlane** [comment]
Closing this issue since I think this has been fixed now.
