### ISSUE TITLE
Append PR number to merge commit message

### ISSUE THREAD

**Issue by cegekaJG** [microsoft/vscode-pull-request-github#5690]
When merging a pull request on the GitHub web client, the suggested commit message (at least in the case of a squash commit, which we always use) will automatically include the number of the PR in parentheses, like so:
`Update project files (#123)`
However, when merging using this extension, the first line of the commit message will look like this:
`Update project files`
You can still edit it, but the number has to be added manually. I feel like this used to be the case - which is why I had half a mind to make this a bug report, not a feature request - but in any case, I'd prefer it if the extension behaved like the site.

**Comment by alexr00** [comment]
Fix will be available in tomorrow's pre-release build of the extension.

**Comment by cegekaJG** [comment]
When will this be added to the release? I noticed `v0.80.1` still doesn't have it.

**Comment by alexr00** [comment]
Yes, it will be in 0.82.0, which will be going out shortly (will require you to also update VS Code).
