### ISSUE TITLE
Invalid `enabledApiProposal`

### ISSUE THREAD

**Issue by Malix-off** [microsoft/vscode-pull-request-github#5691]
## Subject

https://github.com/microsoft/vscode-pull-request-github/blob/1bf5b8959941c9af3dd1020eb77533b81e3b71f6/package.json#L17

### Message

> Value is not accepted. Valid values: "aiRelatedInformation", "authGetSessions", "authSession", "canonicalUriProvider", "chat", "chatAgents2", "chatAgents2Additions", "chatProvider", "chatRequestAccess", "chatTab", "chatVariables", "codeActionAI", "codiconDecoration", "commentsDraftState", "contribCommentEditorActionsMenu", "contribCommentPeekContext", "contribCommentThreadAdditionalMenu", "contribEditSessions", "contribEditorContentMenu", "contribLabelFormatterWorkspaceTooltip", "contribMenuBarHome", "contribMergeEditorMenus", "contribNotebookStaticPreloads", "contribRemoteHelp", "contribShareMenu", "contribSourceControlInputBoxMenu", "contribStatusBarItems", "contribViewsRemote", "contribViewsWelcome", "createFileSystemWatcher", "customEditorMove", "debugFocus", "defaultChatAgent", "diffCommand", "diffContentOptions", "documentFiltersExclusive", "documentPaste", "dropMetadata", "editSessionIdentityProvider", "editorInsets", "extensionRuntime", "extensionsAny", "externalUriOpener", "fileComments", "fileSearchProvider", "findTextInFiles", "fsChunks", "handleIssueUri", "idToken", "inlineCompletionsAdditions", "interactive", "interactiveUserActions", "interactiveWindow", "ipc", "languageStatusText", "mappedEditsProvider", "multiDocumentHighlightProvider", "notebookCellExecutionState", "notebookControllerAffinityHidden", "notebookDeprecated", "notebookExecution", "notebookKernelSource", "notebookLiveShare", "notebookMessaging", "notebookMime", "notebookVariableProvider", "portsAttributes", "profileContentHandlers", "quickDiffProvider", "quickPickItemTooltip", "quickPickSortByLabel", "readonlyMessage", "resolvers", "saveEditor", "scmActionButton", "scmHistoryProvider", "scmInputBoxActionButton", "scmInputBoxValueProvider", "scmSelectedProvider", "scmTextDocument", "scmValidation", "shareProvider", "showLocal", "speech", "tabInputTextMerge", "taskPresentationGroup", "telemetry", "terminalDataWriteEvent", "terminalDimensions", "terminalExecuteCommandEvent", "terminalQuickFixProvider", "terminalSelection", "testCoverage", "testObserver", "testingActiveProfile", "textSearchProvider", "timeline", "tokenInformation", "treeViewActiveItem", "treeViewMarkdownMessage", "treeViewReveal", "tunnelFactory", "tunnels", "windowActivity", "workspaceTrust".

### Log

```
[{
	"resource": "/microsoft/vscode-pull-request-github/package.json",
	"owner": "_generated_diagnostic_collection_name_#2",
	"code": "1",
	"severity": 4,
	"message": "Value is not accepted. Valid values: \"aiRelatedInformation\", \"authGetSessions\", \"authSession\", \"canonicalUriProvider\", \"chat\", \"chatAgents2\", \"chatAgents2Additions\", \"chatProvider\", \"chatRequestAccess\", \"chatTab\", \"chatVariables\", \"codeActionAI\", \"codiconDecoration\", \"commentsDraftState\", \"contribCommentEditorActionsMenu\", \"contribCommentPeekContext\", \"contribCommentThreadAdditionalMenu\", \"contribEditSessions\", \"contribEditorContentMenu\", \"contribLabelFormatterWorkspaceTooltip\", \"contribMenuBarHome\", \"contribMergeEditorMenus\", \"contribNotebookStaticPreloads\", \"contribRemoteHelp\", \"contribShareMenu\", \"contribSourceControlInputBoxMenu\", \"contribStatusBarItems\", \"contribViewsRemote\", \"contribViewsWelcome\", \"createFileSystemWatcher\", \"customEditorMove\", \"debugFocus\", \"defaultChatAgent\", \"diffCommand\", \"diffContentOptions\", \"documentFiltersExclusive\", \"documentPaste\", \"dropMetadata\", \"editSessionIdentityProvider\", \"editorInsets\", \"extensionRuntime\", \"extensionsAny\", \"externalUriOpener\", \"fileComments\", \"fileSearchProvider\", \"findTextInFiles\", \"fsChunks\", \"handleIssueUri\", \"idToken\", \"inlineCompletionsAdditions\", \"interactive\", \"interactiveUserActions\", \"interactiveWindow\", \"ipc\", \"languageStatusText\", \"mappedEditsProvider\", \"multiDocumentHighlightProvider\", \"notebookCellExecutionState\", \"notebookControllerAffinityHidden\", \"notebookDeprecated\", \"notebookExecution\", \"notebookKernelSource\", \"notebookLiveShare\", \"notebookMessaging\", \"notebookMime\", \"notebookVariableProvider\", \"portsAttributes\", \"profileContentHandlers\", \"quickDiffProvider\", \"quickPickItemTooltip\", \"quickPickSortByLabel\", \"readonlyMessage\", \"resolvers\", \"saveEditor\", \"scmActionButton\", \"scmHistoryProvider\", \"scmInputBoxActionButton\", \"scmInputBoxValueProvider\", \"scmSelectedProvider\", \"scmTextDocument\", \"scmValidation\", \"shareProvider\", \"showLocal\", \"speech\", \"tabInputTextMerge\", \"taskPresentationGroup\", \"telemetry\", \"terminalDataWriteEvent\", \"terminalDimensions\", \"terminalExecuteCommandEvent\", \"terminalQuickFixProvider\", \"terminalSelection\", \"testCoverage\", \"testObserver\", \"testingActiveProfile\", \"textSearchProvider\", \"timeline\", \"tokenInformation\", \"treeViewActiveItem\", \"treeViewMarkdownMessage\", \"treeViewReveal\", \"tunnelFactory\", \"tunnels\", \"windowActivity\", \"workspaceTrust\".",
	"startLineNumber": 17,
	"startColumn": 3,
	"endLineNumber": 17,
	"endColumn": 19
}]
```

**Comment by alexr00** [comment]
This is by design. The extension needs VS Code version 1.86 to run out of source.

**Comment by Malix-off** [comment]
Okay, thanks!

Btw this is closed as completed instead of not planned

**Comment by alexr00** [comment]
It's two clicks to close as not-planned and only one click to close as completed, so I close everything as completed 🤷‍♀️

**Comment by Malix-off** [comment]
Based

https://x.com/Malix_off/status/1752017687167779197?s=20
