### ISSUE TITLE
Empty Pull request and empty ISSUES Menu, settings for queries done

### ISSUE THREAD

**Issue by ecgehrke** [microsoft/vscode-pull-request-github#5697]
Hi,

- Extension version: v0.79.2024011609 Pre-Release
- VSCode Version: 1.85.2 (user setup)
- OS: Windows 11
- Repository Clone Configuration (single repository/fork of an upstream repository):
- Github Product (Github Enterprise version):

I have configured the extension but it just is not working, neither Pullrequests nor issues

![image](https://github.com/microsoft/vscode-pull-request-github/assets/156888721/87177542-1b4b-4381-9dee-cd4a391fa8f3)

I am trying to use it with github enterprise.

Best regards
Eckard.

**Comment by ecgehrke** [comment]
After some reloads I see now the different queries but no entries.

**Comment by majsi** [comment]
Try to see if you have the builtin git extension enabled. You can find it by entering @builtin in the search box in extensions.

**Comment by ecgehrke** [comment]
In the meantime I see also PRs but no issues :-(   and I do have some.  

![image](https://github.com/microsoft/vscode-pull-request-github/assets/156888721/a281f34c-bf99-4379-b667-60d175d8870e)

**Comment by alexr00** [comment]
@ecgehrke can you share the output from GitHub Pull Request?

**Comment by alexr00** [comment]
Closing as no further info was provided.
