### ISSUE TITLE
Reply "button" uses a strange color

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-pull-request-github#57]
Is this color used anywhere?

![image](https://user-images.githubusercontent.com/2193314/41948865-b2629394-7973-11e8-841b-02f4344e82aa.png)

Why not use this color?

![image](https://user-images.githubusercontent.com/2193314/41948872-be5200d6-7973-11e8-99a0-2f6dd576efc7.png)

**Comment by misolori** [comment]
@rebornix is this suppose to be a button or a text area? It's a button in the code but it's styled to look like a text area.

**Comment by misolori** [comment]
This was fixed with [PR #56595](https://github.com/Microsoft/vscode/pull/56595)

![image](https://user-images.githubusercontent.com/35271042/44797840-05135600-ab65-11e8-9898-57fdd66c3268.png)
