### ISSUE TITLE
[Accessibility] Remove redundant prefix-style info from PR change view

### ISSUE THREAD

**Issue by jooyoungseo** [microsoft/vscode-pull-request-github#5705]
Type: <b>Bug</b>

@meganrogge 

When `prStatus:github.focus` is triggered, screen reader users can navigate changed files in the treeview.

However, we have to listen to all the redundant prefix-type instruction before target file name like below:

> View diffs and comments for file codeEditorWidget.ts 

This means we have to digest this redundant info each time we arrow-down every single file. If there are multiple changed files, it gets even worse and tedious.

I think "View diffs and comments for file"instruction is redundant because users already know they are in the changed treeview. Please consider taking this out. Or, please turn off this info when `accessibility.verbosity.diffEditor` setting value is false.

![image](https://github.com/microsoft/vscode-pull-request-github/assets/19754711/2ba594f0-4320-4bf8-98b3-07ccc4c7dd9c)

Extension version: 0.79.2024013010
VS Code version: Code - Insiders 1.86.0-insider (05047486b6df5eb8d44b2ecd70ea3bdf775fd937, 2024-01-31T03:29:50.526Z)
OS version: Windows_NT x64 10.0.22631
Modes: Restricted
Connection to 'ssh-remote+7b22686f73744e616d65223a2244656c7461227d' could not be established

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz (8 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.71GB (6.18GB free)|
|Process Argv|--crash-reporter-id b05b88e5-8894-4031-ae34-fa034ebddea9|
|Screen Reader|yes|
|VM|0%|

Connection to 'ssh-remote+7b22686f73744e616d65223a2244656c7461227d' could not be established
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscod805cf:30301675
vsaa593:30376534
py29gd2263:30784851
c4g48928:30535728
a9j8j154:30646983
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
8082a590:30953407
edj9j583:30943796
fegfb526:30952798
7j2b6412:30951517
e3gdj431:30946825
ccp2r3:30950906

```

</details>

**Comment by alexr00** [comment]
@jooyoungseo and @meganrogge what if we changed it to this:

> codeEditorWidget.ts pull request diff

I don't really feel that the `accessibility.verbosity.diffEditor` setting really applies here, and I'd prefer not to introduce a new PR setting if possible.
