### ISSUE TITLE
Multi File Diff Editor Opens Many Times

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode-pull-request-github#5712]
* set `"githubPullRequests.focusedMode": "multiDiff",`
* Open a PR, e.g. `https://insiders.vscode.dev/github/microsoft/vscode/pull/204119`
* Pin the multi file diff editor and open a new tab
* Reload the page

![chrome_rInLbKnBab](https://github.com/microsoft/vscode-pull-request-github/assets/2931520/168d4540-d892-42dd-9d15-56e8d99a0285)

If you set a multiDiffEditorSourceUri per PR, this will not happen. However, if the PR changes new files, these new files will not be picked up.
I think this is one reason why extensions should be able to contribute multiDiffEditorSourceProviders.

**Comment by alexr00** [comment]
> If you set a multiDiffEditorSourceUri per PR, this will not happen. However, if the PR changes new files, these new files will not be picked up.

Opening many times is not intentional behavior, but in the short term I think it's better to open more than once rather than miss new files.

**Comment by alexr00** [comment]
Will be resolved by https://github.com/microsoft/vscode-pull-request-github/issues/5761
