### ISSUE TITLE
Is there any proxy support ? (with Github Enterprise)

### ISSUE THREAD

**Issue by yoh1496** [Microsoft/vscode-pull-request-github#572]
Nothing is shown in my project cloned from GitHub Enterprise behind a proxy of company. Can you let me know how to resolve this problem?

- Extension version: 0.2.0
- VSCode Version: 1.28.0
- OS: Windows 10 1803

Steps to Reproduce:

1. Write `github.hosts` in setting file.
2. Cloning repository, open the project folder.
3. Nothing is shown.

The output of this extension is below

```
Looking for git repository
Git repository found, initializing review manager and pr tree view.
No GitHub remotes found
No GitHub remotes found
No GitHub remotes found
Review> no matching pull request metadata found for current branch master
``` 

In my environment, a repository cloned from GitHub was shown correctly.

```
Looking for git repository
Git repository found, initializing review manager and pr tree view.
No GitHub remotes found
No GitHub remotes found
Found GitHub remote
```

Reading some sources in this extension, I thought that there was no considering about being used behind proxy. Is there any way to use this extension behind a proxy?

**Comment by queerviolet** [comment]
This should be fixed by #590. Please reopen if there are any issues!
