### ISSUE TITLE
vscode:// url redirect does not open vscode. No alternatives offered.

### ISSUE THREAD

**Issue by diddledan** [Microsoft/vscode-pull-request-github#573]
Issue Type: <b>Bug</b>

1. On Ubuntu run `snap install vscode` to install from the snap store
2. Start vscode using the icon in the dashboard
3. Install the GitHub Pull Requests plugin and click the popup to login
4. Login to GitHub and click the "Continue" button
5. If the browser prompts to run `xdg-open` approve the request (this is the Linux mechanism to launch URL handlers
6. VSCode does not receive the URL trigger because snaps don't provide an interface for this feature yet.
7. Try to find an alternative way to trigger vscode with the URL directly, such as on the commandline, but realise there is no documentation on how to do such things :-)
8. That's it.

The vscode cannot be triggered via the URL handling mechanism as mentioned because of snap limitations currently. There is no alternative mechanism to get the URL to vscode that is readily identifiable to a user. It would be handy to provide a command line snippet that will achieve the same as the URL handler for cases where the URL handler fails.

Extension version: 0.2.0
VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-05T14:52:58.945Z)
OS version: Linux x64 4.15.0-36-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3834)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|2, 2, 2|
|Memory (System)|31.30GB (0.40GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by rebornix** [comment]
Sorry we didn't mention that anywhere but you can use personal access token for authentication by setting

```
    "github.hosts": [
        {
            "host": "https://github.com",
            "username": "",
            "token": ""
        }
    ]
```

could you give it a try?

**Comment by queerviolet** [comment]
Aw, crap.

**Comment by queerviolet** [comment]
We can add a copy-paste fallback for if the protocol handler fails.

**Comment by TonyCusano** [comment]
Just tried with adding the token but unfortunately still experiencing same problem.

**Comment by pdf** [comment]
What permissions are required when using a PAT?

**Comment by queerviolet** [comment]
Hi! I think this flow should be fixed by https://github.com/Microsoft/vscode-pull-request-github/pull/659

The uri handler may not open, but the auth server and newest version of the extension now provide an alternative route.

Please open a new issue if there are any problems.

**Comment by queerviolet** [comment]
@pdf — It needs read/write on all your repos, public and private.  I'll update the docs with that information.
