### ISSUE TITLE
PR branch "Delete" button is shown even if the branch is already deleted

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode-pull-request-github#5733]
Repro: 
1. create a pr using the create-PR view with "create + auto-rebase"
2. when PR is merged and branch is deleted, you still see the button "delete branch..."

<img width="2560" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/16353531/0a473e0b-d613-46c3-adfb-29b6227516b5">

GHPRI v0.81.2024020808

Version: 1.87.0-insider
Commit: 9db1b0571e119289a2264971bdac75793965e063
Date: 2024-02-07T05:48:10.997Z
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.2.0

**Comment by ulugbekna** [comment]
I realized that the PR view in vscode can get stale (and hence has "refresh" button). 

I was wondering under what conditions does it can get stale. I'm also curious if "refresh" button should be more prominent to prompt the user to refresh to get latest info

**Comment by alexr00** [comment]
@ulugbekna it looks like your local branch still exists. The "Delete Branch" button can also delete your local branch.

**Comment by alexr00** [comment]
- [ ]
