### ISSUE TITLE
Next Change icon is missing when viewing a Markdown document in PR

### ISSUE THREAD

**Issue by s-kovacs** [microsoft/vscode-pull-request-github#5734]
Type: <b>Bug</b>

When I click on a **Markdown** document in a **PR** then at the top right side of the **Preview Editor** displays the *Previous Change* icon among others without the *Next Change* icon in spite of there are more changes in the document. I guess there is an icon limit (maybe **8** currently) so there is no space left to show the missing icon.

Actual:
![Missing arrow](https://github.com/microsoft/vscode-pull-request-github/assets/106159074/07fbfac1-73d4-47e3-beb0-1adb49b046f2)

Expected:
![Two arrows](https://github.com/microsoft/vscode-pull-request-github/assets/106159074/1ec663b6-afb0-4aae-a2d7-fe7923861558)

Extension version: 0.80.0
VS Code version: Code 1.86.1 (31c37ee8f63491495ac49e43b8544550fbae4533, 2024-02-07T09:08:57.920Z)
OS version: Darwin arm64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|32.00GB (1.67GB free)|
|Process Argv|--disable-extensions --crash-reporter-id 574eaadd-d944-49b1-a856-5843d2e40dc7|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww1:30959800
dsvsc019bcf:30953938
b1063948:30958189
3ef8e399:30949928

```

</details>

**Comment by alexr00** [comment]
It should be in the ... menu if the overflow is hit. Do you see it there?

**Comment by alexr00** [comment]
Closing because no further information was provided.
