### ISSUE TITLE
please help to solve it git config failed: Failed to execute git

### ISSUE THREAD

**Issue by YaznonovMirzabek** [microsoft/vscode-pull-request-github#5743]
![Screenshot 2024-02-11 162850](https://github.com/microsoft/vscode-pull-request-github/assets/133767941/95764c90-89c1-4e48-820b-f2380323c44e)

1st problem

[warning] No such branch: master.
[info] > git config --local branch.master.github-pr-owner-number
[warning] git config failed: Failed to execute git

2nd:

 Please enter the commit message for your changes. Lines starting
 with '#' will be ignored, and an empty message aborts the commit.

 On branch master

 Initial commit

 Changes to be committed:
	new file:   .dvc/.gitignore
	new file:   .dvc/config
	new file:   .dvcignore

  Untracked files:
	.vscode/

**Comment by YaznonovMirzabek** [comment]
what abt 

[info] > git config --local branch.master.github-pr-owner-number
[warning] git config failed: Failed to execute git

how to solve this?

**Comment by Aleksandr-P** [comment]
It's very strange. No one uses this plugin?

**Comment by Aleksandr-P** [comment]
I got the same errors.

**Comment by Aleksandr-P** [comment]
Надо держать клавишу Альт

**Comment by Aleksandr-P** [comment]
Сегодня заработала

**Comment by vbem** [comment]
Same ...
![image](https://github.com/microsoft/vscode-pull-request-github/assets/5989600/2f8fed3f-98a3-4a56-a1e3-3671d1419301)

**Comment by eedeebee** [comment]
seeing this error too.

**Comment by prbjkp** [comment]
help me too

**Comment by leeebo** [comment]
same, which makes my vscode stuck

![image](https://github.com/microsoft/vscode-pull-request-github/assets/16922815/9f3220a9-f143-461b-8b5d-abd4ac445c90)
