### ISSUE TITLE
Use custom tab icon for PRs

### ISSUE THREAD

**Issue by hbons** [microsoft/vscode-pull-request-github#5751]
VS Code now supports setting an icon name for the editor tab icon. It would be nice to show the `pr` icon instead of the generic text file one.

<img width="230" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/103326/5e6c077b-3a69-46fc-a72a-d896198b9a89">

**Comment by alexr00** [comment]
To verify:
- Install the latest pre-release version of GitHub Pull Requests
- Open your local clone of a GitHub repo in VS Code.
- Open the "Pull Requests" and expand a PR.
- Click on the PR's "Description" verify that the editor tab that is opened shows the "pull request" icon.
