### ISSUE TITLE
GitHub pull request view does not show up in side bar with GitHub Enterprise 2.14.5 or newer

### ISSUE THREAD

**Issue by isaaccheng8** [Microsoft/vscode-pull-request-github#576]
GitHub pull request view does not show up in side bar

- Extension version: 0.2.1
- VSCode Version: 1.28.1
- OS: macOS High Sierra 10.13.6
- GitHub Enterprise 2.14.5

Steps to Reproduce:

1. Install GitHub Pull Requests extension.
2. Reload VS Code.
3. Follow all the sign-in steps to grant GitHub Enterprise permissions to the VS Code extension.

GitHub pull request view still does not show up in side bar.

**Comment by isaaccheng8** [comment]
![image](https://user-images.githubusercontent.com/31190595/46899869-01563d00-ce4e-11e8-8771-46e2f6061b64.png)
Despite the message "Review> no matching pull request metadata found for current branch crud-er," I am sure that I created a pull request (using a web browser) hours ago.
![image](https://user-images.githubusercontent.com/31190595/46899887-53975e00-ce4e-11e8-8fc9-9d229578a314.png)

**Comment by isaaccheng8** [comment]
@rebornix Do you need more information from me besides https://github.com/Microsoft/vscode-pull-request-github/issues/576#issuecomment-429501309?

**Comment by wxianxin** [comment]
I also have the same issue. Enterprise Github version `2.14.6`.
I guess it's either an issue on the server side or an authentication issue.

**Comment by philosowaffle** [comment]
Same for Enterprise Github version `2.14.7`

**Comment by donortega** [comment]
I also have this issue. Also followed all of the steps in the wiki granting access to GH Enterprise to VS Code.

- Extension version: 0.2.1
- VS Code version: 1.28.2
- OS: macOS High Sierra 10.13.6
- GitHub Enterprise: 2.14.6

![samplevscode](https://user-images.githubusercontent.com/1423784/47173125-16a1f000-d2c2-11e8-8b07-4539e7c5ac3b.png)
![samplepr](https://user-images.githubusercontent.com/1423784/47173130-1b66a400-d2c2-11e8-9cd3-f534dff9ddc5.png)

**Comment by donortega** [comment]
@rebornix
> can you open Output channel and choose "GitHub Pull Request" from the dropdown list and share the log with us? You may want to sanitize the content first.

I have attached the requested info in https://github.com/Microsoft/vscode-pull-request-github/issues/576#issuecomment-431099796. Does this issue still need the `needs more info` tag?

**Comment by rebornix** [comment]
@donortega thanks for your help, I don't have GitHub Enterprise instance to further troubleshoot, @queerviolet can you help on this?

**Comment by wxianxin** [comment]
The issue still persists. Could someone please fix this?

```
/Users/memememe/.ssh/config: ENOENT: no such file or directory, open '/Users/memememe/.ssh/config'
Looking for git repository
Git repository found, initializing review manager and pr tree view.
No GitHub remotes found
No GitHub remotes found
No GitHub remotes found
Review> no matching pull request metadata found for current branch xxxxxxxx
```

**Comment by queerviolet** [comment]
Hi @wxianxin,

Thanks for your patience! Would you mind including the following information to help with debugging?

1. The output of `git remote -v`, run from inside that repo
2. The output of `git config --get-regex 'branch\.${pr_branch}'`, where `$pr_branch` is some branch you know a PR exists for
3. The output of `curl -v ${your_enterprise_instance}`. `$your_enterprise_instance` should be one of the URLs from (1)

Thank you!

**Comment by wxianxin** [comment]
Thanks for the attention.

1. `git remote -v`
```
origin	https://github.xxxx.com/yyyy/zzzz.git (fetch)
origin	https://github.xxxx.com/yyyy/zzzz.git (push)
```

2.  `~/wd/github/BEAST2$git config --get-regex 'branch\.overwrite'`
```
branch.overwrite.remote origin
branch.overwrite.merge refs/heads/overwrite
```
3. `curl -v https://github.xxxx.com/rate_limit`
```
*   Trying 10.ppp.ppp.ppp...
* TCP_NODELAY set
* Connected to github.xxxx.com (10.ppp.ppp.ppp) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=*.xxxx.com
*  start date: Jan 23 00:00:00 2018 GMT
*  expire date: Feb 23 12:00:00 2019 GMT
*  subjectAltName: host "github.xxxx.com" matched cert's "*.xxxx.com"
*  issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
*  SSL certificate verify ok.
> GET /rate_limit HTTP/1.1
> Host: github.xxxx.com
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 401 Unauthorized
< Cache-Control: no-cache
< Content-Type: text/html
< WWW-Authenticate: Basic realm="GitHub"
< transfer-encoding: chunked
< Connection: keep-alive
< 
<html><body><h1>401 Unauthorized</h1>
You need a valid user and password to access this content.
</body></html>
* Connection #0 to host github.xxxx.com left intact
```

**Comment by queerviolet** [comment]
Mmm, yeah, that is definitely the issue.

**Comment by wxianxin** [comment]
I am able to use git in terminal without the need of passwords once SSO is setup though.

**Comment by queerviolet** [comment]
Okay, #708 should fix this. Once the next version of the extension is out, you'll be able to get a personal access token for your GHE instance and add it manually (⇧⌘P > Github Pull Requests Manually Provide Authentication Response). Your GHE instance should be recognized as such thereafter.

If you feel like cloning the extension down and trying it before the next release, you're of course welcome to, and we'd appreciate the feedback!

**Comment by ershov** [comment]
Hmmm... I'm having this issue in 2021.. Is it fixed?

**Comment by nacesprin** [comment]
Me too

**Comment by RonyKordahi** [comment]
Mine was working fine a minute ago then suddenly stopped. I can't access any files or the pull request itself anymore. The pull request tab doesn't show up, but the GitHub extension does. When I checkout a pull request, my local branch changes but nothing else responds.

**Comment by JotaRata** [comment]
I report the same issue
