### ISSUE TITLE
Handle renamed files

### ISSUE THREAD

**Issue by jsoref** [microsoft/vscode-pull-request-github#5767]
Improve handling for renamed files

Currently when I click on a `png` file that's listed as `R` (which is apparently a `Renamed` file), I get:
<img width="461" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/2119212/a0b67f37-1b28-40af-aaa8-fdb1e298b3bc">
<img width="661" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/2119212/0eb08132-e087-40e3-b54f-3a775c6acfc7">
<img width="460" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/2119212/bbedc5a8-5c44-4f50-b6c7-e90d43d89c19">
<img width="779" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/2119212/b400e6ae-a35c-457e-bf97-a9887104b984">

Ideally:
* I should be able to view the file locally and have a thing that tells me its renamed at the top/bottom of the view
* I should be able to add comments on the file change (as I can in the GitHub web ui)

In the interim, it'd be nice if the floating message at the bottom said "because it's a rename" -- so it's clear it's because of the `R` and not, e.g. because it's a `.png`.

**Comment by alexr00** [comment]
I'm not able to repro this with a rename. Do you have a public PR I could look at that shows this issue?

**Comment by jsoref** [comment]
The repository in question is/was https://github.com/check-spelling-sandbox/GraphScope/ 
https://github.com/check-spelling-sandbox/GraphScope/commit/1f8d832fd832bf36565d28136af6362d410c8ce1 is a commit with the change.

**Comment by alexr00** [comment]
I can repro, thanks!

**Comment by roblourens** [comment]
This is working for a text file, but not an image

<img width="1438" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/323878/1be6cf2b-d6e0-492b-921d-9734d0c10180">

In this PR that just does a basic rename of two files

https://github.com/roblourens/testrepo/pull/13
