### ISSUE TITLE
Test keyboard shortcuts in the comments widget

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#5768]
Refs: https://github.com/microsoft/vscode-pull-request-github/issues/5261

- [x] macOS @Tyriar
- [x] linux @bpasero
- [x] windows @luabud

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode-pull-request-github/issues/new?body=Testing+%235768%0A%0A&assignees=alexr00)

---

1. Install the pre-release version of the GitHub Pull Requests extension
2. In VS Code, open a folder containing a clone of a GitHub repository
3. Open a file that's in a PR. This can be a currently checked out PR or a file from a PR in the "Pull Requests" view
4. Start to leave a comment in the file by using the `+` in the editor gutter. This will open the comment widget.
5. One of the buttons in the comment widget will say "Make a Suggestion". Hover over this. Verify that you can see a keybinding listed in the hover.
6. Try out that keybinding. Verify that it works.

**Comment by jcanton** [comment]
I know this is closed (should I open a new issue?) but  the shortcut(s) is currently not working for me on the pre-release version (no shortcut is assigned and I cannot manage to create new shortcuts)

GitHub.vscode-pull-request-github v0.79.2024011609

macOS 14.6.1

Code info:
Version: 1.85.2
Commit: 8b3775030ed1a69b13e4f4c628c612102e30a681
Date: 2024-01-18T06:40:11.430Z
Electron: 25.9.7
ElectronBuildId: 26354273
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.6.0
