### ISSUE TITLE
Test .github repository PR templates

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#5769]
Refs: https://github.com/microsoft/vscode-pull-request-github/issues/3414

- [x] anyOS @chrisdias
- [x] anyOS @benibenj

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode-pull-request-github/issues/new?body=Testing+%235769%0A%0A&assignees=alexr00)

---

GitHub allows PR templates to live in `.github` repositories. Example: `https://github.com/microsoft/.github` (I don't think there's actually a PR template at that location, but there could be). When the current repo doesn't have a PR template, a PR template from that owner's `.github` repo will be used instead. In the previous example `microsoft` is the owner.

To test this, you'll need to have a `.github` repository somewhere. You can always create your own (ex: `https://github.com/alexr00/.github`) and add a PR template there. Naming requirements for PR templates: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

1. Install the pre-release version of GitHub Pull Requests
2. Set this setting if you don't already have it set `"githubPullRequests.pullRequestDescription": "template"`
3. Open a folder that contains a clone of a GitHub repository that belongs to the owner you ensured has a `.github` repo and also *does not* have a PR template in the repository.
4. Create a PR. Verify that the template in your `.github` repository was used. (Note: if this is a folder you've created a PR in before, this may take 2 tries as PR templates are cached).
5. Now, open a folder that contains a clone of a GitHub repository that belongs to the owner you ensured has a `.github` repo and also *does* have a PR template in the repository. 
6. Create a PR. Verify that the PR template for the current repo is used.

**Comment by chrisdias** [comment]
This cool!  Worked great!

**Comment by rzhao271** [comment]
Closing the issue based on Chris's feedback above.

**Comment by chrisdias** [comment]
sorry, I wasn't done testing yet but now I am :)  didn't find anything new.
