### ISSUE TITLE
Test adding a project when creating PRs and issues

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#5770]
Refs: https://github.com/microsoft/vscode-pull-request-github/issues/3062

- [x] anyOS @anthonykim1
- [x] anyOS @ulugbekna

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode-pull-request-github/issues/new?body=Testing+%235770%0A%0A&assignees=alexr00)

---

1. Install the pre-release version of GitHub Pull Requests
2. Open a folder containing a clone of a GitHub repository. The repository should have at least one project in it (or you can have user level projects).
3. From the "Issues" view, use the + to open the new issue markdown file
4. Verify that you can add a project when you create an issue using the issue markdown file
5. From the "Pull Requests" view, use the action to "Create Pull Request"
6. Verify that you can add a project when you create a pull request.

**Comment by anthonykim1** [comment]
Was able to get it to work, Cool feature! 
<img width="1573" alt="Screenshot 2024-02-20 at 12 39 49 AM" src="https://github.com/microsoft/vscode-pull-request-github/assets/62267334/15d46ac5-656a-463d-9f9b-5fd8944fd1c9">
<img width="1111" alt="Screenshot 2024-02-20 at 12 37 55 AM" src="https://github.com/microsoft/vscode-pull-request-github/assets/62267334/8f72a2a6-62e0-4de8-b8c1-5e2dcffd807b">
