### ISSUE TITLE
Create-issue markdown file doesn't suggest same projects I see in github.com

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode-pull-request-github#5771]
Testing #5770

I should see a lot more projects (e.g.., `hediet-vs-code-issues`) here: 

![Image](https://github.com/microsoft/vscode-pull-request-github/assets/16353531/f60d3974-3988-4d2a-90a9-592ecda7e462)

In PR view projects: 

![Image](https://github.com/microsoft/vscode-pull-request-github/assets/16353531/b5e1d81a-dd2e-4183-ad34-5d01d35a2ce2)

v0.81.2024022009 (pre-release)

Version: 1.87.0-insider
Commit: 01ce8d869e4220577e194b2dd57bfa12437dfcf5
Date: 2024-02-20T02:04:15.870Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.3.0

**Comment by eleanorjboyd** [comment]
@ulugbekna are you able to verify this fix?

**Comment by rzhao271** [comment]
I still see the issue. Might have to wait for the next release.

**Comment by aiday-mar** [comment]
Hi @alexr00 I am pinging about this issue. Would you like to make this issue a candidate or move it out to the `March 2024` milestone?

**Comment by rzhao271** [comment]
Moving out the issue for now. Feel free to move it back as a candidate if needed.

**Comment by alexr00** [comment]
@rzhao271 I'm not able to repro this. You might need to trigger the suggest more than once to force the cache to be updated.

**Comment by aiday-mar** [comment]
I just tried to test this with the latest pre-release version of Github Pull Requests and Issues and I see only three projects proposed? I don't see `hediet-vs-code-issues` either.

https://github.com/microsoft/vscode-pull-request-github/assets/61460952/c8d8b22f-558a-4b40-a7cf-52748af708b6

**Comment by ulugbekna** [comment]
Sorry for not verifying earlier. Seems fixed for me
