### ISSUE TITLE
Emoji aren't rendered in code review

### ISSUE THREAD

**Issue by jsoref** [microsoft/vscode-pull-request-github#5776]
Type: <b>Bug</b>

1. Have a clone of https://github.com/CrunchyData/postgres-operator/
2. Open it in VS Code
3. Open the Pull Requests extensions view
4. Expand the https://github.com/CrunchyData/postgres-operator/pull/3856 PR
5. Scroll to and select internal/controller/postgrescluster/pgbackrest_test.go
6. Scroll to the comment on line 732
7. Click on the comment indicator (note that this won't work anymore as the comment has been resolved, but it worked at the time -- and I have a screenshot)
8. See the comment with `:wrench:` instead of :wrench:

Extension version: 0.80.1
VS Code version: Code 1.86.2 (Universal) (903b1e9d8990623e3d7da1df3d33db3e42d80eda, 2024-02-13T19:42:13.651Z)
OS version: Darwin arm64 23.2.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|6, 6, 6|
|Memory (System)|64.00GB (0.04GB free)|
|Process Argv|--crash-reporter-id 1fc67ee2-0174-4598-9f98-4537df0dd32c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
d6fi2104:30959263
fegfb526:30961430
7j2b6412:30967274
e3gdj431:30958358
ccp2r3:30958157

```

</details>

![image](https://github.com/microsoft/vscode-pull-request-github/assets/2119212/4d24290c-051f-4a0b-9294-aec97a96ffb6)

**Comment by alexr00** [comment]
@mjbvz it would be cool if our markdown renderer supported this. 

Note for later if I want to add support in the extension: https://emojipedia.org/shortcodes

**Comment by mjbvz** [comment]
This extension adds support for the markdown preview: https://marketplace.visualstudio.com/items?itemName=bierner.markdown-emoji

However this rendering comes from core, so we're unlikely to add support there. What you could potentially do is do a prepass to replace the `:emoji:` in the markdown you pass to core

**Comment by alexr00** [comment]
Fix courtesy of https://github.com/microsoft/vscode/pull/236051 being pointed out to me!

**Comment by alexr00** [comment]
To verify:
- Install the latest pre-release version of GitHub Pull Requests
- Open your local clone of a GitHub repo in VS Code.
- Open the "Pull Requests" view and expand a PR that you don't mind leaving a comment in.
- Open one of the file diffs in the PR and use the editor comment bar to leave a comment.
- Use the `:emoji-name:` syntax to include an emoji in your comment.
- Submit the comment.
- Verify that the emoji is rendered in the comment.
