### ISSUE TITLE
Add Pull request filter for "open"

### ISSUE THREAD

**Issue by xmatthias** [Microsoft/vscode-pull-request-github#578]
currently, the topmost items in the treeview are:

* Local Pull Requests
* Waiting for My Review
* Assigned To Me
* Created By Me
* All

Having an option for "all open" would be great (including a "assign to me" button maybe) so the whole workflow can be done within VSCode.

Currently i either see only pr's assigned to me - or all (including closed) - which can end up in a mess if a ton of closed PR's exist, but only a vew open ones.

**Comment by RMacfarlane** [comment]
Hey @xmatthias, the current "All" category should only be showing open pull requests. If that's not what you're seeing, then this is a bug 🐛 

Do you consistently see closed or merged pull requests in that category?

**Comment by xmatthias** [comment]
you're right, i saw a long, unfamiliar list (but not the complete list) ... 

however after looking closer now - it's PR's done to forks I have a remote for as i had (or have) a branch from it in my repository.

It should be limited to the main branch (or possible to configure which one) - but it's a different request i guess
