### ISSUE TITLE
Comment error on submodule repository (Creating comment failed: Error: File has been deleted.)

### ISSUE THREAD

**Issue by DFelten** [microsoft/vscode-pull-request-github#5784]
- Extension version: 0.80.1
- VSCode Version: 1.87.0-insider (c11a2dd4d52e38cb92b8c464f47a7b02bb7c8762)
- OS: macOS 14.3.1
- Repository Clone Configuration (single repository/fork of an upstream repository): -
- Github Product (Github.com/Github Enterprise version x.x.x): Github.com

Steps to Reproduce:

We have a project with two Git repositories. A main repository and a submodule. As soon as both repositories on the checked out branch have a pull request, there are problems. Comments cannot be written in the pull request of the submodule if the associated branch is checked out.

It is possible to write comments in VSCode when the branch is not checked out. But as soon as I check out a pull request, I get the following error when submitting a comment: `Creating comment failed: Error: File has been deleted.`

It's possible to write comments, if I switch with the main repository branch to an other one without a pull request.When opening the submodule folder in an other VSCode instance, it's also possible to write comments even if the branch is checked out. 

<details>
<summary>Error notification</summary>

![CleanShot 2024-02-26 at 17 20 54@2x](https://github.com/microsoft/vscode-pull-request-github/assets/1169185/faedf762-fbe0-4e96-9b14-6a07595cbbdc)

</details>

**Comment by ajb-oce** [comment]
Looks like "protoc" isn't available on the CICD build perhaps?

**Comment by alexr00** [comment]
@DFelten thanks for your patience and for the clear steps! Fix will be available in the next pre-release build (and the next stable release).

**Comment by DFelten** [comment]
Issue appears again. The error notification for a deleted file appears again:

![CleanShot 2024-07-19 at 11 23 44@2x](https://github.com/user-attachments/assets/eb4378e6-7305-4e73-972a-8bf3787c7d58)

I've created a new issue for this since I thought it's an other issue. But the notification appears now again. The new issue: https://github.com/microsoft/vscode-pull-request-github/issues/6096
