### ISSUE TITLE
Open new pull request?

### ISSUE THREAD

**Issue by dcosson** [Microsoft/vscode-pull-request-github#580]
I've searched through all the issues and documentation, and I am surprised not to find a way to do this or even any conversation about this so far since it is such an obvious feature for a pull request extension. Maybe I just missed it so apologies if this is a duplicate.

Can this extension add support for creating a new pull request from the current branch?

**Comment by jongio** [comment]
This is in the Oct iteration plan: https://github.com/Microsoft/vscode-pull-request-github/issues/544

**Comment by dcosson** [comment]
Great, thanks for the response 👍
