### ISSUE TITLE
Show workflow summary in UI

### ISSUE THREAD

**Issue by dkfellows** [microsoft/vscode-pull-request-github#5805]
It would be really nice if the summary page for a workflow was visible in the VSCode UI. Yes, I see the link, but being able to pick up on warnings and errors issued by the workflow more obviously would be _great_ as improving visibility for problems discovered by tooling is always useful (though not to the point of raising it to obnoxiousness).

----

For example, I have a step in one of my workflows that effectively issues:
```
##[warning](mainwindow.cpp):TODO: check what this csv file was for
```
to the workflow log, which gets surfaced in the Github UI as:
![image](https://github.com/microsoft/vscode-pull-request-github/assets/1155878/baa9f5b3-539d-42e8-b0bc-5e7d13cd3703)
What I'd like is to be able to see that sort of thing when I click on the workflow (and not one of its components) in the Github Actions panel in the sidebar. Effectively, it would be just loading a webpage that already exists, or at least part of it. (Mind you, I don't know if that information is conveniently surfaced in the Github API. If it isn't, that's an omission there too.)

**Comment by alexr00** [comment]
@dkfellows do you already have a GitHub Actions view in the sidebar? If so, that's coming from a different extension!
