### ISSUE TITLE
Easy way to see how a comment was addressed (e.g. changes to file since comment)

### ISSUE THREAD

**Issue by tboddyspargo** [microsoft/vscode-pull-request-github#5809]
I often find myself re-reviewing something that I've already given feedback on to see if all my comments were appropriately addressed.

I'd love to have an easy way to pull up a diff view that includes my comment and changes made since I submitted the comment. This would allow me to very quickly evaluate the revisions against my feedback and either reply to the same thread, or resolve it.

**Comment by tboddyspargo** [comment]
Please let me know if this is already possible!

**Comment by alexr00** [comment]
@tboddyspargo is this for outdated comments? If so, I just added this in the Comments view:

![image](https://github.com/microsoft/vscode-pull-request-github/assets/38270282/b69b1d20-f5c4-4931-95ba-aba4639f76bc)

**Comment by tboddyspargo** [comment]
Hi, @alexr00 - "outdated" comments would be a good start (although, there could be value in this applying to any comment). 

However, I've installed the pre-release version but I can't seem to find those icons/buttons, even for "outdated" comments. Can you clarify how I should be accessing the "comments" view or if this is a setting I need to enable somewhere?

**Comment by alexr00** [comment]
@tboddyspargo you also need to use VS Code Insiders to get the latest pre-release version of the extension.
