### ISSUE TITLE
Cannot read property 'fileOperationResult' of null

### ISSUE THREAD

**Issue by scrossan-crown** [Microsoft/vscode-pull-request-github#582]
- Extension version: 0.2.1
- VSCode Version: 1.28.1
- OS: Windows 10

Steps to Reproduce:

1. Click on second repo in `Source Control Providers` tab
2. Open `Changes In Pull Request` section open `commits` sub menu and a file in the commit

When trying to open a file I am getting the below error.
```
Unable to open 'database/seeds/PermissionsPermissionGroupsSeeder.php from 318d76cd': Cannot read property 'fileOperationResult' of null.
```

![image](https://user-images.githubusercontent.com/30405149/47067582-bf2c5300-d1e1-11e8-8e95-5c589ef39780.png)

**Comment by Henribou** [comment]
Same problem for me.

VSCode version: 1.28.2 (1.28.2)
OS : MacOS mojave
Extension version : 0.2.3

**Comment by bm-stschneider** [comment]
I still have this.
Unable to open 'xxx': Cannot read property 'fileOperationResult' of null.
When trying to open files in 'Changes in pull request'

**Comment by bm-stschneider** [comment]
Seems I had to uninstall, delete, install to make it work.

**Comment by bm-stschneider** [comment]
Recent insider update brought it in again -.-
Version 1.30.0-insider (1.30.0-insider)
456e8e64beb2dceac66743959f6802b66e18e300

**Comment by Iodine-** [comment]
Confirmed still an issue in 1.31.0 as well

Version 1.31.0-insider (1.31.0-insider)
edf1090b8546ad0d17f30bf6f8075613e37e1b37

clicking the 'open file' icon next to the file however does seem to open the file as expected.
