### ISSUE TITLE
Possibly an incorrect hardcoded string

### ISSUE THREAD

**Issue by mohamedamara1** [microsoft/vscode-pull-request-github#5821]
in the issueOverview.ts file is this line correct ? 

	`public static ID: string = 'PullRequestOverviewPanel';` 

 isn't it supposed to be `public static ID: string = 'IssueOverviewPanel';`

**Comment by alexr00** [comment]
That's fair, the string is incorrect. The IssueOverviewPanel doesn't really get used anywhere except as a parent class though.
