### ISSUE TITLE
Pull request 'hide' button has an unusual focused text color in light mode

### ISSUE THREAD

**Issue by jespertheend** [microsoft/vscode-pull-request-github#5830]
- Extension version: `v0.78.1`
- VSCode Version: `1.85.2 (Universal)`
- OS: `Darwin arm64 23.2.0`
- Repository Clone Configuration (single repository/fork of an upstream repository): fork of upstream
- Github Product (Github.com/Github Enterprise version x.x.x): Github.com

Steps to Reproduce:

1. Enable light color theme
1. Create a pull request in a repository that runs pull request checks
1. Click the 'hide' button or use tab to focus the hide button

https://github.com/microsoft/vscode-pull-request-github/assets/2737650/4d6f8b2b-65c9-4810-b1d7-ddd305040cd5

**Comment by jespertheend** [comment]
The buttons at the top seem to have it too:

https://github.com/microsoft/vscode-pull-request-github/assets/2737650/0d3ab5c8-b69f-4e16-80cd-6340c64ef17a

**Comment by alexr00** [comment]
Which light theme are you using? I tried, Light Modern, Light+, and Light (Visual Studio), but I couldn't repro this issue.

**Comment by jespertheend** [comment]
My settings.json contains `"workbench.colorTheme": "Default Light Modern"` but I can reproduce it with `Default High Contrast Light` as well. I'll check if maybe another extension is causing this.

**Comment by jespertheend** [comment]
Seems like I was using an old version of vscode 😓 sorry!
