### ISSUE TITLE
Cannot read property 'fileName' of undefined

### ISSUE THREAD

**Issue by scrossan-crown** [microsoft/vscode-pull-request-github#584]
- Extension version: 0.2.1
- VSCode Version: 1.28.1
- OS: Windows 10

Steps to Reproduce:

1. Open file using the opne file button in the pr changes diff view
2. Try to add a comment to the file

![image](https://user-images.githubusercontent.com/30405149/47081956-0c212100-d204-11e8-93d3-50d643559599.png)

**Comment by alexr00** [comment]
No longer repros.
