### ISSUE TITLE
There is no upstream branch for Pull request XXX

### ISSUE THREAD

**Issue by boubou158** [microsoft/vscode-pull-request-github#5844]
Hi,

I have an issue after configuring the plugin. I can see properly the different pull requests but whenever i try to checkout a PR, i have this error

![image](https://github.com/microsoft/vscode-pull-request-github/assets/4662832/32f6cf83-54e7-498a-ba7b-d7a2186cc02e)

Do you have any clue on how to fix this one?

Thank you :)

**Comment by alexr00** [comment]
Looks like this is coming form the Azure Devops Pull Request extension, not the GitHub Pull Request extension.
