### ISSUE TITLE
Consider optimizing readme for the marketplace

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-pull-request-github#585]
There's a bunch of repeated information when you view the extension on the marketplace or via VS Code:

![image](https://user-images.githubusercontent.com/2193314/47107562-8353b680-d1fe-11e8-9ad1-1b6d28b5cf27.png)

This could look like this instead:

![image](https://user-images.githubusercontent.com/2193314/47107677-be55ea00-d1fe-11e8-8dd3-57d6644b93e7.png)

**Comment by sup95** [comment]
Hi! I have updated the ReadMe to conform to the requirements as outlined in the comment above. Let me know if it looks good, or any more changes are to be made.

Additionally, I feel the sub-headers "How to get started?" could be modified to the more concise "Getting Started" and "Extension" could be renamed to "Issues" as the content pertains to issues and I feel extensions sounds generic for a sub-header. 
Let me know your thoughts on these, and I can add these changes into this PR too, if required!

Thanks!
