### ISSUE TITLE
Add "auto" option for create base branch

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#5859]
https://github.com/microsoft/vscode-pull-request-github/issues/5195#issuecomment-2014461726

When the repo is a fork, it makes more sense to make a PR against the upstream repo instead of the branch that the current branch was branched off from.

**Comment by alexr00** [comment]
To verify:
- Make sure that `githubPullRequests.createDefaultBaseBranch` is set to `auto`
- Open a folder that contains a clone of a forked GitHub repository
- Check out the `main` branch of the repo
- Create a new branch
- Run the command "Create Pull Request" (you won't actually need to create the PR, just run the command)
- Verify that the base branch for the PR is set to the upstream repo's main branch, not the fork's main branch.

**Comment by lszomoru** [comment]
@alexr00, the behaviour works as expected but `auto` does not seem to be a valid value for the setting. 
<img width="499" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/3372902/0a57696e-62d6-4723-bb0c-a6ad6c42d4c9">

**Comment by alexr00** [comment]
@lszomoru I just released a new version of GHPR a few minutes ago. You will need to very latest to test with.
