### ISSUE TITLE
Failed to install 

### ISSUE THREAD

**Issue by butterfly-pn** [Microsoft/vscode-pull-request-github#586]
When I tried to install the extension it displayed an alert `Failed to install 'github.vscode-pull-request-github'.`. It also said that I can install it manually, but after following this steps it does also nothing.

- Extension version: not installed
- VSCode Version: 1.25.1
- OS: macOS Mojave 10.14

Steps to Reproduce:

1. Click on the install button on the extension page

**Comment by RMacfarlane** [comment]
Hi @butterfly-pn, the extension requires VSCode version 1.27 or higher. Please try upgrading VSCode and installing.

// @sandy081 Are we able to distinguish this kind of installation failure from others? Is it possible to show more information to the user about the required version?

**Comment by butterfly-pn** [comment]
It works! Thanks

**Comment by sandy081** [comment]
Ok.. then it was broken as it used to work before
