### ISSUE TITLE
Test display of outdated comments

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#5861]
Refs: https://github.com/microsoft/vscode-pull-request-github/issues/5760

- [x] anyOS @DonJayamanne
- [x] anyOS @ntrogh
- [x] anyOS @amunger

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode-pull-request-github/issues/new?body=Testing+%235861%0A%0A&assignees=alexr00)

---

Setup
- Install the pre-release version of GitHub Pull Requests
- Create some outdated comments:
  1. Create a PR or check out an existing PR
  2. Leave a comment on a line or lines in the PR
  3. Modify those lines, then commit and push your change
  4. Your comments should now show as outdated. You may need to refresh the comments.

Verify
- That you can quickly and easily distinguish outdated comments from not-outdated comments in the "Comments" view
- That outdated comments have an inline action in the "Comments" view to "Diff Comment with HEAD". This action should also be in the context menu. Verify that this action does what you'd expect

**Comment by ntrogh** [comment]
LGTM on Windows!

**Comment by DonJayamanne** [comment]
> That you can quickly and easily distinguish outdated comment

Yes I can, works well.
