### ISSUE TITLE
The icon for un-resolve is too close to undo

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode-pull-request-github#5868]
Testing #5862

That is very minor. But the icon for un-resolve reminds me of undo and it is actually not an undo IMO. The action is more a re-open conversation. 

I do prefer re-open over un-resolve but it looks like GitHub is using the same name. So feel free to close if this doesn't justify to make us different from GitHub

**Comment by alexr00** [comment]
It currently uses the `discard` icon, but we can probably do better. Maybe the `debug-restart` icon? @hbons in case you have some suggestions!

**Comment by hbons** [comment]
@dbaeumer can you add a screenshot for context? Maybe we should stick to a label here if we can't find the right icon.

**Comment by alexr00** [comment]
@hbons labels for inline actions are technically supported, but I think we don't use them in any of our extensions. Screenshot:

![image](https://github.com/microsoft/vscode-pull-request-github/assets/38270282/584b8921-caaa-46cb-ad21-f45970bbfee6)

**Comment by hbons** [comment]
@alexr00 thanks! on GitHub reopening issues and rerequesting reviews uses a refresh like icon. so `refresh` could work? 
<img width="39" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/103326/67242a0d-c366-4e0c-93c7-a6533f8c26ac">

**Comment by hbons** [comment]
or `sync`:
<img width="212" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/103326/0a59f402-104d-4a96-9044-3e58513ff6ae">

**Comment by alexr00** [comment]
`sync` seems good, I'll switch to that.
