### ISSUE TITLE
Wrong number in comments

### ISSUE THREAD

**Issue by paulacamargo25** [microsoft/vscode-pull-request-github#5869]
Testing #5862

In the last comment, as you can see, it shows the first comment with its text, and then it says `3 comments`. That makes me think that in addition to the one shown first there are 3 more, when that is not the case.

It makes more sense for me to say 2 comments.

<img width="1336" alt="Screenshot 2024-03-25 at 10 45 37 AM" src="https://github.com/microsoft/vscode-pull-request-github/assets/17892325/2baf55ca-6d30-4f1e-8cf0-2455d1027b7e">

**Comment by alexr00** [comment]
That's intentional, but I can see how it would be confusing.

**Comment by eleanorjboyd** [comment]
@paulacamargo25 - can you verify this issue since you have already experienced it?
