### ISSUE TITLE
Continuously asks to login to GitHub over and over

### ISSUE THREAD

**Issue by diberry** [microsoft/vscode-pull-request-github#5874]
- Extension version: v0.12.2
- VSCode Version: Codespaces
- OS: Linux/Codespaces
- Repository Clone Configuration (single repository/fork of an upstream repository): Fork of upstream repository
- Github Product (Github.com/Github Enterprise version x.x.x): where would I see this? 

Steps to Reproduce:

1. Logged into GitHub as `diberry`
2. Open new Codespace such as [https://github.com/diberry/mslearn-advocates.azure-functions-and-signalr](https://github.com/diberry/mslearn-advocates.azure-functions-and-signalr)
3. Login to GitHub from popup several times - it just doesn't stop

I am a member of GitHub enterprise which I noticed as caused weirdness. This issue has been on going for a few weeks now.

**Comment by alexr00** [comment]
@diberry you say you are a member of GitHub enterprise. When you log in, do you log in with a `<username>@<your-enterprise-org>.<tld>` email?

It looks like you're at Microsoft, so I have another question: When you log in, do authorize VS Code to access your Microsoft org (SAML)? Can you try the following:
1. Set `"githubPullRequests.upstreamRemote": "never"` in your VS Code/Codespace settings.
2. In your Codespace, open a terminal and use the command line to delete the upstream `MicrosoftDocs` remote that the GitHub Pull Request extension added. 
  a. Get the name of the remote with `git remote -v`
  b. Delete the remote with `git remote remove MicrosoftDocs` and substitute the name you found in step with for `MicrosoftDocs`
  c. If you want this to get automatically added back at some point, just reset the setting in step 1. 
3. Reload the Codespace. 
4. Do you still get the issue?

**Comment by diberry** [comment]
@alexr00 let me try.

**Comment by diberry** [comment]
```
origin  https://github.com/diberry/mslearn-advocates.azure-functions-and-signalr (fetch)
origin  https://github.com/diberry/mslearn-advocates.azure-functions-and-signalr (push)
upstream        https://github.com/MicrosoftDocs/mslearn-advocates.azure-functions-and-signalr.git (fetch)
upstream        https://github.com/MicrosoftDocs/mslearn-advocates.azure-functions-and-signalr.git (push)
```

The cyclical login prompt isn't happening now.

**Comment by alexr00** [comment]
Ok, if you see it again we can re-open and take another look. But based on the previous steps we went through, you shouldn't have an `upstream` remote.
