### ISSUE TITLE
In the PR view, the review action selector next to 'Comment' also submits the PR

### ISSUE THREAD

**Issue by joshuaobrien** [microsoft/vscode-pull-request-github#5896]
I don't expect the selector to submit the review when I make a selection. Instead, I expect it to change the behaviour of the button next to the dropdown. This has caught me quite a few times. If there's consensus that this would be a better experience, I'd be happy to submit a PR

https://github.com/microsoft/vscode-pull-request-github/assets/7654793/c6a9d533-d48d-42fd-906e-e43251b67c27

**Comment by alexr00** [comment]
There's been some discussion on this before: https://github.com/microsoft/vscode-pull-request-github/issues/3785
The short version is that this is consistent with the behavior in VS Code core in the SCM view. 

If there's a strong desire form multiple users to change this then we can add a setting, but my preference would just be to stay consistent with the SCM view.

**Comment by joshuaobrien** [comment]
Makes sense. Thanks for the context

**Comment by alexr00** [comment]
Given the lack of engagement from other users I'm going to say that there isn't a strong desire from users to add a setting here.
