### ISSUE TITLE
Add option to hide submodules from Pull Requests / Issues tree

### ISSUE THREAD

**Issue by mmgeorge** [microsoft/vscode-pull-request-github#5906]
First off, thanks for the extension! Our repository has a large number of submodules, but these submodules don't have PRs / issues & therefore just end up cluttering the UI. Would be great if there was a user config option to either hide all submodules from the tree, or maybe some workspace-configurable option to filter specific submodules out. 

![image](https://github.com/microsoft/vscode-pull-request-github/assets/16738762/d7f7b6e5-5d05-44b3-9824-91a0f34e37bb)

**Comment by alexr00** [comment]
Let me know if that doesn't work!

**Comment by ThomsonTan** [comment]
Seems it also works by setting `git.detectSubmodules` to `false`.
