### ISSUE TITLE
Extension asks to login every time I open vscode

### ISSUE THREAD

**Issue by tairosonloa** [microsoft/vscode-pull-request-github#591]
Every time I open vscode, a pop up appears on the bottom right corner with the message: "In order to use the Pull Requests functionality, you need to sign in to github.com" and a button "Sig in".

![captura de pantalla de 2018-10-19 09-37-58](https://user-images.githubusercontent.com/14878189/47204088-b45cf400-d382-11e8-8d53-68906af8fdaf.png)

Of course, that happened the first time I installed the extension, and I clicked the button to authorize the extension to access my github account. I checked it is authorized with full permissions. However, when I authorized the extension from my web browser (tried firefox and chromium), the web page turned white and nothing happened, so maybe the auth process wasn't completed successfully.

Now, every time I open vscode the same pop up appears. Clicking on "Sign in" button the request authorization web page opens on my browser, but clicking on continue does nothing (I suppose because it is already authorized).

I'm able to login on github from vscode by clicking on the options "Sign in to github.com" on the bottom left corner.

![captura de pantalla de 2018-10-19 09-36-13](https://user-images.githubusercontent.com/14878189/47204052-9099ae00-d382-11e8-9329-4b3d69ea3a4d.png)

Edit: I have 2FA on my github.com since always. I don't know if that matters.

- Extension version: 0.2.1
- VSCode Version: 1.28.2
- OS: GNU/Linux (ArchLinux with kernel 4.14.76-1-lts)

Steps to Reproduce:

1. Install the extension and sign in github (authorize extension)
2. Close vscode
3. Open vscode

**Comment by johnpapa** [comment]
THis happens for me too. I open VS Code Insiders, it prompts me to authorize github, I follow the steps (in the browser), then it's fine. If I reload VS Code or close and re-open, i have to go through it again.

**Comment by lehnerchristian** [comment]
I experienced the same problem, too. Today I gave it a try again and now it works for me :+1:

**Comment by kitfit-dave** [comment]
Do you have a network filter active?

I use LittleSnitch and have seen the above issue. I found that the rules for VSC, though they looked fine, seemed to be blocking the response from github, somehow... (they seemed like they were set up to allow connection until quit, so logging in once would work, then the next restart of VSC it would fail and ask again.) Anyway, I found that removing all the rules and regenerating them has worked. You could try disabling the filter to begin with and see if that is the problem (that's what I started with)

**Comment by logan-han** [comment]
Having the same issue here. 
Pasting the config `githubPullRequests.hosts` into config.json manually will result the plugin auto-remove the config item every time it starts up.
It also doesn't leave anything useful in the debug log.

**Comment by pnmcosta** [comment]
Yup, same here, with Ubuntu 19.04, latest vscode 1.35.0 and extension 0.8.0.

I'm actually using the `ssh-agent` to authenticate with github, see instructions [here](https://help.github.com/en/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#adding-your-ssh-key-to-the-ssh-agent) and was hoping the extension would use it too.

**Comment by RMacfarlane** [comment]
I'm no longer able to reproduce this in the latest version of the extension. If you see this problem again, please reopen the issue. Thank you!

**Comment by PatakiViktor** [comment]
Now I seem to have the problem again :(

**Comment by patrickhlauke** [comment]
Same. this also happens when switching between different github projects - every time requiring a roundtrip to the github auth page

**Comment by mxcl** [comment]
Uninstalled this nonsense because of this. This is in the same category of irritations as websites that block content begging you to sign up to their mailing list when you visit them.

Learn to use non intrusive popups.

**Comment by nsde** [comment]
I'm having the same issue. Linux user here.

**Comment by hatamiarash7** [comment]
I'm having the same issue. Ubuntu 20
