### ISSUE TITLE
Slash commands doesn't work when entered in the comments box.

### ISSUE THREAD

**Issue by hnaganur** [microsoft/vscode-pull-request-github#5913]
The extension does not trigger the action for the slash commands when entered in the comments section like it would do in the PR web link.  the extension treats it as contributor leaving a comment instead of triggering the action.

- Extension version: 0.86.1 ( any version)
- VSCode Version: 1.88.0
- OS: Windows
- Repository Clone Configuration (single repository/fork of an upstream repository): Enterprise repo
- Github Product (Github.com/Github Enterprise version x.x.x): Github.com

Steps to Reproduce:

1. Create a PR
2. Enter a slash command ( in my case its custom slash command ) and click comment.

**Comment by hnaganur** [comment]
it basically takes a reviewer/contributor leaving review instead of actions
![image](https://github.com/microsoft/vscode-pull-request-github/assets/111370769/c5fff15e-ca8b-4575-860c-9ac8f7c29040)

**Comment by hnaganur** [comment]
![Screenshot 2024-04-08 153805](https://github.com/microsoft/vscode-pull-request-github/assets/111370769/7291c5a2-f47e-4c03-abcb-48c69c8d9a66)

**Comment by hnaganur** [comment]
Yes. it goes through organization's auth page for sign in

**Comment by alexr00** [comment]
@hnaganur do you have a button to "authorize" VS Code for your organization on that sign in page? If so, is it possible you skipped clicking on this "authorize" button and just signed in without authorizing?

**Comment by alexr00** [comment]
Closing because no further info was provided.
