### ISSUE TITLE
Ctrl+Enter doesn't add comment

### ISSUE THREAD

**Issue by johnknoop** [microsoft/vscode-pull-request-github#5914]
- Extension version: 0.82.1
- VsCode:
Version: 1.87.2 (system setup)
Commit: 863d2581ecda6849923a2118d93a088b0745d9d6
Date: 2024-03-08T15:20:17.278Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.22631

Steps to Reproduce:

1. Enter some text into the Reply textbox of a comment
2. Hit ctrl+enter

Expected result:
The reply would be saved

Observed result:
Nothing happens

![53414686-1de8-420b-b36c-b91dc3755ea3](https://github.com/microsoft/vscode-pull-request-github/assets/3394270/46bdf8ec-b265-4467-a0d7-15e1e3230e64)

**Comment by alexr00** [comment]
I'm not able to reproduce this. Do you have another extension installed that's taking that keybinding. You can check by running the command "Developer: Toggle Keyboard Shortcuts Troubleshooting" and looking at the logs that are shown.

**Comment by johnknoop** [comment]
I found that the extension `GitHub Copilot` has added this keyboard shortcut, which was being invoked:

```json
{
  "key": "ctrl+enter",
  "command": "github.copilot.generate",
  "when": "editorTextFocus && github.copilot.activated && !inInteractiveInput && !interactiveEditorFocused"
}
```

However, I don't understand why the `editorTextFocus` predicate would be satisfied when it's the comment textbox that has focus. But that would be a VS Code bug, not a bug in your extension so let's not re-open this issue.

**Comment by alexr00** [comment]
The input where you enter your comment counts as `editorTextFocus`. Let me see if I can get the Copilot folks to add `!commentEditorFocused` to their keybinding.

**Comment by johnknoop** [comment]
Should it really count as an editor though? Isn't that the problem?

**Comment by alexr00** [comment]
Yes, it is a code editor. This is how we get nice things like markdown syntax highlighting pasting markdown links in the comment widget input.

**Comment by alexr00** [comment]
Copilot folks have fixed the issue and it should be in one of their upcoming releases.

**Comment by danielo515** [comment]
> Yes, it is a code editor. This is how we get nice things like markdown syntax highlighting pasting markdown links in the comment widget input.

But that is very annoying, an unnecessary. Can you consider an option to making it a simple text input? I don't want any of the fancy features you mention
