### ISSUE TITLE
Links are rendered incorrectly

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-pull-request-github#5924]
- Extension version: v0.63.2024022201
- VSCode Version: 1.89 Insiders
- OS: macOS
- Repository Clone Configuration: single repo
- Github Product : github.com

Steps to Reproduce:

On https://github.com/microsoft/vscode-hexeditor/pull/503, I tried to leave a comment:

![Image](https://github.com/microsoft/vscode-pull-request-github/assets/2230985/312d74bf-0d7a-4df3-ae87-105184cc6fc1)

Is rendered as

![Image](https://github.com/microsoft/vscode-pull-request-github/assets/2230985/ad9f3397-3235-48d3-b3d8-b9378f72cf0f)

**Comment by alexr00** [comment]
Happens because the url contains and `@`.

**Comment by benibenj** [comment]
- The link I used: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion
- The link it rendered: https://developer.mozilla.org/en-US/docs/Web/CSS/%5B@media%5D(https:_github.com/media)/prefers-reduced-motion

![Image](https://github.com/microsoft/vscode-pull-request-github/assets/44439583/a91d2ef0-6771-47bc-b871-971006e7a29b)
