### ISSUE TITLE
cant able to authentication

### ISSUE THREAD

**Issue by Shreeedalvi** [microsoft/vscode-pull-request-github#5927]
Type: <b>Feature Request</b>

I am trying to get connect my visual studio with github but im not getting access

Extension version: 0.86.1
VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:41:02.734Z)
OS version: Windows_NT x64 10.0.18363
Modes:

**Comment by alexr00** [comment]
There aren't enough steps here for me to try to repro the issue.
