### ISSUE TITLE
Squash or Rebase Merge PR

### ISSUE THREAD

**Issue by jeremygaither** [Microsoft/vscode-pull-request-github#593]
If a repository has protections that disallow merge commits, this plugin is unable to merge the PR. It fails with error:

```
Unable to merge pull request. Merge commits are not allowed on this repository.
```

Please add an option to squash/rebase merge...

**Comment by kyleroush** [comment]
created a pr for this feature https://github.com/Microsoft/vscode-pull-request-github/pull/599

**Comment by kyleroush** [comment]
I think we should change the merge button to an input like 
<img src=https://user-images.githubusercontent.com/9557174/47308097-46b8fe00-d5f6-11e8-9ecd-52987a476a9d.png>
And that then that will cause a div below to show like 
<img src=https://user-images.githubusercontent.com/9557174/47308096-46b8fe00-d5f6-11e8-8728-43ea79190477.png>
