### ISSUE TITLE
Option to disable auto showing comments panel on checkout

### ISSUE THREAD

**Issue by diminutivesloop** [microsoft/vscode-pull-request-github#5938]
When checking out a PR I would like to disable auto-showing the comments panel. Frequently when checking out a PR I have to run commands in the terminal to update my environment but currently I have to wait until the comments panel displays so I can switch back to the terminal. I can set `githubPullRequests.focusedMode` to `false` as a workaround, but ideally this would be a separate setting in case I still want to auto-open a diff or the overview.

**Comment by alexr00** [comment]
The extension will check the setting `comments.openView` for this!

**Comment by diminutivesloop** [comment]
So setting `comments.openView` gets me the desired behavior, however I think the way that setting is described doesn't quite match w/ this extension's behavior. The other values reference opening the comments view when a file with comments is opened but when I check-out a PR the comments view is opening even if no file is open and only the PR overview is visible. So if `comments.openView` was set to "file" I still would expect the comments view to stay hidden after checking out a PR until I opened a file with comments.
