### ISSUE TITLE
check out PR merges into current working branch

### ISSUE THREAD

**Issue by jeremygaither** [Microsoft/vscode-pull-request-github#594]
- Extension version: 0.2.1
- VSCode Version: 1.28.2
- OS: macOS High Sierra

Steps to Reproduce:

1. check out a branch other than default branch with changes
2. make changes, commit, push, etc...
3. check out PR without those changes

Expected Result:
PR is checked out into clean branch

Actual Result: 
Branch is created from current branch and PR is merged in, and VSCode syncs automatically if there is not a merge conflict, polluting pull requests.

**Comment by rebornix** [comment]
Good catch, we checkout from current branch indeed 

https://github.com/Microsoft/vscode-pull-request-github/blob/5024a85bfcfa8525fcf8b8322d34d6e706570b96/src/github/pullRequestGitHelper.ts#L44

**Comment by rebornix** [comment]
I'm trying to find a good reproduce and it would be great if @jeremygaither can help with that. Firstly let me describe what's happening

1. We are on branch A with some local changes
2. We commits all the changes with commit SHA_1 and push the master
3. Checkout to PR B which doesn't have SHA_1

Under the hood we will fetch the remote branch for PR B and directly saves to a new local branch by running command

```
git fetch <remote> <rbranch>:<lbranch>
```

and then we checkout to `lbranch`. So we are not creating a branch from branch A ideally. @jeremygaither can help confirm this is not what you are seeing? Based on the issue report, it seems that after checking out the PR B, you are on a new branch which still has SHA_1, right?

**Comment by rebornix** [comment]
I can reproduce this issue, will investigate.

**Comment by rebornix** [comment]
Fixed via https://github.com/Microsoft/vscode/commit/6d923688da888f590b2b02ed0873d5620c0edac1
