### ISSUE TITLE
Resolve conflicts: No GitHub repository found for owner

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#5945]
Testing #5939

First try testing:

![image](https://github.com/microsoft/vscode-pull-request-github/assets/2193314/f02f1eb0-0f75-4b7b-9be7-ef3035e3deee)

Both the repo and branch do indeed exist: https://github.com/tisilent/xterm.js/tree/vivid-curly

PR: https://github.com/xtermjs/xterm.js/pull/4880

**Comment by Tyriar** [comment]
Still failing:

![image](https://github.com/microsoft/vscode-pull-request-github/assets/2193314/76cb59e6-2867-4da5-ba20-78a9a1ef2518)

Does this only work on branches in the same repo?

**Comment by alexr00** [comment]
Good find!
