### ISSUE TITLE
Show/hide checks button uses heavier font weight than the larger buttons

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#5948]
Testing #5939

This looks wrong as the smaller/less prominent toggle button (Show) uses a heavier font weight than the larger more important buttons:

![image](https://github.com/microsoft/vscode-pull-request-github/assets/2193314/6edc6121-3f92-4ff0-ba6f-d40a21408fd3)

**Comment by eleanorjboyd** [comment]
Where can I find this screen? / @Tyriar could you verify this?

**Comment by Tyriar** [comment]
@eleanorjboyd I think this should show by opening any VS Code PR on the pre-release of GHPR
