### ISSUE TITLE
Frequently getting all conflicts have been resolved after clicking Resolve conflicts

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#5952]
Testing #5939

https://github.com/microsoft/vscode/pull/195255

![image](https://github.com/microsoft/vscode-pull-request-github/assets/2193314/e34e1460-b4f9-4672-9baa-50ac41db9c71)

Can we merge this diff automatically but only do it when requested, and .com can't?

![image](https://github.com/microsoft/vscode-pull-request-github/assets/2193314/0f3dc4eb-4353-4ea3-8678-497b50ac132a)

---

Another example:

https://github.com/microsoft/vscode/pull/195255

![Recording 2024-04-23 at 11 49 07](https://github.com/microsoft/vscode-pull-request-github/assets/2193314/fc2db3c5-aed9-489c-a133-f13cc3e4b8c1)

**Comment by alexr00** [comment]
This is the 300 file limit. New behavior will be to show this error dialog (and it will be faster):

![image](https://github.com/microsoft/vscode-pull-request-github/assets/38270282/7abd17b8-79bd-411f-bb79-266e6ab459a9)

**Comment by alexr00** [comment]
Anyone can verify this by opening one of the examples in the OP in insiders.vscode.dev:
- Make sure you have the pre-release version of the extension installed
- Set ` "githubPullRequests.experimentalUpdateBranchWithGitHub": true`
- Open the PR description and scroll down to click on the "resolve conflicts" button
- Verify that a message shows saying that this conflict can't be resolved here.

**Comment by Tyriar** [comment]
The button is no longer there:

![image](https://github.com/microsoft/vscode-pull-request-github/assets/2193314/8729a97b-09a6-44bf-80e3-ba3569539cee)

@alexr00 the wording doesn't give the user a hint on how/where to do it though
