### ISSUE TITLE
Completing merge didn't do anything

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#5953]
Testing #5939

Repro:

- For https://github.com/microsoft/vscode/pull/195255
- Click resolve conflicts
- Wait ~10 seconds 
- Showed that there were no conflicts left, click complete merge

🐛 nothing seemed to happen, no merge happened, resolve conflicts button remains disabled.
 
![image](https://github.com/microsoft/vscode-pull-request-github/assets/2193314/32695358-b22c-4a1f-8ff4-cc6a7403a76c)

**Comment by alexr00** [comment]
Same cause as https://github.com/microsoft/vscode-pull-request-github/issues/5952
