### ISSUE TITLE
Show some loading indicator when switching PR descriptions

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#5954]
Testing #5939

Repro:

1. Open GHPR view
2. Click the description of a PR
3. Click the description of another PR, 🐛 nothing happens for ~2 seconds and then the custom editor switches suddenly. Could we show a loading indicator here?

![Recording 2024-04-23 at 11 58 22](https://github.com/microsoft/vscode-pull-request-github/assets/2193314/beff1726-190d-4b27-8e7b-0ab6c51b60f5)

**Comment by alexr00** [comment]
Adding view progress.
