### ISSUE TITLE
I cannot set the Personal Access Token

### ISSUE THREAD

**Issue by brettforbes** [microsoft/vscode-pull-request-github#5979]
Your documentation [here ](https://code.visualstudio.com/docs/sourcecontrol/github)does not describe how to add a Personal Access Token at all, instead it send us to [this page](https://github.com/Microsoft/vscode-pull-request-github/issues/93) 2018, which doesn't tell you either. The page is 6 years old, so how can we have confidence in it?

I have installed Github Pull requests, v0.86.1, but this doesn't seem to solve this problem.

Scanning the issues page reveals many issues, but no direct resolution.

Why is it so hard to use the PAT in VS Code, when PyCharm makes it so easy???????  

I am trying to switch to VS Code, but you guys make this step so unnecessarily hard.

Please provide simple steps on how to insert a PAT into vs code. Consider putting this in your documentation. It seems crazy and self-defeating that it is not described in absolute detail, so even beginners like me can set it up.

Oh well, back to PyCharm then :(

**Comment by alexr00** [comment]
Looks like I got it wrong the first time. Actually fixing here: https://github.com/microsoft/vscode-docs/pull/7244

**Comment by brettforbes** [comment]
Right, thanks for that. What a disappointment the result is. Looks like its easier to copy my tokens into PyCharm, and use that to authenticate VS Code, since VS Code does not allow input of tokens
