### ISSUE TITLE
Can't filter PRs properly

### ISSUE THREAD

**Issue by eyaleizenberg** [microsoft/vscode-pull-request-github#5982]
- Extension version:
- VSCode Version: 0.86.1
- OS: Mac OS 14.4.1 
- Repository Clone Configuration (single repository/fork of an upstream repository): Single repo (Turbo monorepo)
- Github Product (Github.com/Github Enterprise version x.x.x): Paid Github

Steps to Reproduce:

I have the following in my settings.json

```javascript
  "githubPullRequests.queries": [
      {
      "label": "Waiting for Review",
      "query": "is:open label:'Ready for Review'"
    },
    {
      "label": "Assigned To Me",
      "query": "is:open review-requested:${user}"
    },
    {
      "label": "Created By Me",
      "query": "is:open author:${user}"
    },
    {
      "label": "Mentions Me",
      "query": "is:open mention:${user}"
    }
]
```

However, I always get 0 results even though there are many PRs in our repo with the lavel "Ready for Review". I've tried setting it as: Ready+for+Review and also changing the name of the label to "Ready" but it didn't work. The "Mentions Me" doesn't work for me either. I only get results for "Created by me" and "assigned to me".

**Comment by alexr00** [comment]
```
    {
      "label": "Mentions Me",
      "query": "is:open mention:${user}"
    }
```

This should be `mentions`, not `mention`.

**Comment by alexr00** [comment]
```
      {
      "label": "Waiting for Review",
      "query": "is:open label:'Ready for Review'"
    },
```
This should be  `"query": "is:open label:/"Ready for Review/""`
