### ISSUE TITLE
Extension cannot fetch pull requests on VSCode's fork cursor

### ISSUE THREAD

**Issue by felix-droese** [microsoft/vscode-pull-request-github#5990]
- Extension version:
v0.80.1
- VSCode Version:
1.89.0
- cursor Version:
0.32.2
- cursor VSCode Version:
1.86.2
- OS:
13.5.1 (22G90)

- Repository Clone Configuration (single repository/fork of an upstream repository):
single repository, cloned via git@github.com:...

- Github Product (Github.com/Github Enterprise version x.x.x):
github.com

Fresh install of the extension, clicking the refresh pull requests lists icon yields the following error:
![image](https://github.com/microsoft/vscode-pull-request-github/assets/149673650/fcc91587-2cfd-4bad-a008-c5496b1ffddb)

Error:
![image](https://github.com/microsoft/vscode-pull-request-github/assets/149673650/c21bf627-0eaf-4ff0-9dbe-c64ca92c0d7e)

**Comment by felix-droese** [comment]
> alexr00

Hey alex, thanks for answering.

In the my issue title, I am referring to Visual Studio Codes "fork" (I thought it was a fork) https://github.com/getcursor/cursor https://cursor.sh/

The repository I am hitting is **not** a fork. It is a private single repository

**Comment by alexr00** [comment]
We only test the extension with VS Code. Can you also reproduce the issue with VS Code?

**Comment by felix-droese** [comment]
@alexr00 on VSCode it works

**Comment by alexr00** [comment]
Thanks @felix-droese! Sounds like a bug in cusor then.
