### ISSUE TITLE
Same color for renamed files with web UI

### ISSUE THREAD

**Issue by azihsoyn** [microsoft/vscode-pull-request-github#5993]
Thanks to this plugin, my review process has become much more efficient. 
After reviewing numerous PRs, I've noticed that the file movements are represented differently than in the web UI.

Since the web UI provides a clearer view of file movements, I suggest changing the colors to improve visibility (adding icons might also be helpful).

- VS Code
<img width="283" alt="CleanShot 2024-05-07 at 10 13 35@2x" src="https://github.com/microsoft/vscode-pull-request-github/assets/1225998/a97f64f5-f4ef-4c38-bfe5-af9e9f467ada">

- Web UI

<img width="243" alt="CleanShot 2024-05-07 at 10 14 19@2x" src="https://github.com/microsoft/vscode-pull-request-github/assets/1225998/4623f6e4-a69f-4d4c-b104-55d528c567bc">

**Comment by alexr00** [comment]
While we do want the extension feel familiar to web users, we also want it to feel like VS Code. The color + the "R" badge is consistent with how renamed files look in the Git view in VS Code.
