### ISSUE TITLE
Fail to fetch pull requests due to IP restriction

### ISSUE THREAD

**Issue by eml-c2829** [microsoft/vscode-pull-request-github#5998]
- Extension version: 0.88.1
- VSCode Version: 1.89.1
- OS: Windows
- Repository Clone Configuration (single repository/fork of an upstream repository): https://github.com/EMLTeams/testing-injured-worker-app-mobile/tree/dev
- Github Product (Github.com/Github Enterprise version x.x.x): Github.com

Steps to Reproduce:

1. All VSCode source control features are working well e.g. sync, push,.. are good.
2. Install the extension Github Pull Request
3. Select the tab Github Pull Request and take a look at the window Output. The same error keeps throwing.

> 2024-05-11 21:51:43.044 [debug] VariableSubstitution> ${user} -> ${user}
2024-05-11 21:51:43.045 [debug] GitHubRepository> Fetch pull request category is:open author:${user} - enter
2024-05-11 21:51:43.045 [debug] GitHubRepository> Fetch metadata - enter
2024-05-11 21:51:43.045 [debug] GitHubRepository> Fetch metadata for repo - enter
2024-05-11 21:51:43.045 [debug] RateLimit> Extension rate limit remaining: 139, /repos/{owner}/{repo}
2024-05-11 21:51:43.208 [error] GitHubRepository> Fetching all pull requests failed: HttpError: Although you appear to have the correct authorization credentials, the `EMLTeams` organization has an IP allow list enabled, and your IP address is not permitted to access this resource.

I did try:
1. Remove and install Github Pull Request extension.
2. Some actions mentioned here https://github.com/github/vscode-github-actions/issues/77

Nothing works.

**Comment by alexr00** [comment]
Have you tried adding your IP to the allow list?

**Comment by eml-c2829** [comment]
It would be impossible to ask the IT department to whitelist my home's IP address. However, my point is that the Pull Request extension does not work, meanwhile, others work.

My account belongs to an organization, that has enabled the IP whitelist feature, that's why I have to enable my VPN when I need to access some organization-owned repositories on GitHub.com or push my codes to Github.com. Once the VPN is enabled, everything works perfectly.

However, somehow the Pull Request extension did not work. I kept receiving the error of IP restriction.

That's why I think there's something wrong with the Pull Request itself. Maybe I am wrong !?

**Comment by eml-c2829** [comment]
Just realized that the Pull Request extension worked when I was in the company office but not at my home. It's obviously about IP thing.

However, I would like to emphasize again that the Pull Request extension itself has the problem. :(

**Comment by alexr00** [comment]
> Just realized that the Pull Request extension worked when I was in the company office but not at my home. It's obviously about IP thing.
>
> However, I would like to emphasize again that the Pull Request extension itself has the problem. :(

It sounds like GitHub is intentionally limiting the IPs that can use GitHub API base on your org's settings. I don't think there's anything that this extension can do to change this.
