### ISSUE TITLE
Offensive / Profane Comment Completion

### ISSUE THREAD

**Issue by mpjovanovich** [microsoft/vscode-pull-request-github#5999]
- Extension version: 0.88.1
- VSCode Version: 1.89.1
- OS: Ubuntu

Steps to Reproduce:

Refer to the screenshot. This is obviously not a clear repro scenario, and I'm not even sure if this is part of your extension.

![example](https://github.com/microsoft/vscode-pull-request-github/assets/10914696/1269781e-9acd-4dc7-85c1-cdbccd9c8c88)

Gotta love Internet training data...

**Comment by alexr00** [comment]
@mpjovanovich do you have the GitHub Copilot extension installed?

**Comment by mpjovanovich** [comment]
Yes, I do.

**Comment by alexr00** [comment]
Thanks @mpjovanovich, I've reported this the GitHub Copilot folks!
