### ISSUE TITLE
UX when checking out a PR

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-pull-request-github#6]
When I checkout a PR, we add the "Changes in PR" section to the SCM view. It's added below the "GitHub Pull Requests" section and it is collapsed by default. It should be above the "GH PR" section and expanded by default. (There are API constraints right now.)

**Comment by bpasero** [comment]
I verified that the "Changes in Pull Request" appears to the top, but it is no longer in the SCM viewlet.

**Comment by RMacfarlane** [comment]
Thanks @bpasero, that's expected, it should show up in the GitHub viewlet!
