### ISSUE TITLE
Allow to open PR on web from PR view when showing multiple

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-pull-request-github#6000]
Here I really miss a way to click on the 🌐 icon to open the PR externally:

![image](https://github.com/microsoft/vscode-pull-request-github/assets/900690/47e60319-1d7e-476e-9f6c-9621c7648141)

**Comment by alexr00** [comment]
@bpasero you just want to open github.com to the PR?

**Comment by bpasero** [comment]
Yeah like this one:

![image](https://github.com/microsoft/vscode-pull-request-github/assets/900690/8de2065f-6e0d-4025-8665-a49fb505995d)

**Comment by Santhoshmani1** [comment]
Hey there. I would like to contribute to this project and this issue would be a good starting point.

I have build the extension locally. For opening the pr on github, we can modify the `menus` -> `view/item/context` to use the existing `pr.openPullRequestOnGithub` command in package.json file.

![Screenshot 2024-05-27 211734](https://github.com/microsoft/vscode-pull-request-github/assets/119673958/1fd8d9ba-7f17-4732-8660-04ea76934a21)

![Screenshot 2024-05-27 210617](https://github.com/microsoft/vscode-pull-request-github/assets/119673958/11637f16-85ae-4267-a3ea-5b65c6f7494f)

I am happy to send a pull request with the required changes.

**Comment by alexr00** [comment]
It shows here when there's only one:



![Image](https://github.com/user-attachments/assets/9700c89e-5d9f-4d68-a702-4424fac8860f)

**Comment by aiday-mar** [comment]
Ah yes I see
