### ISSUE TITLE
An error occured while loading the image (renamed picture)

### ISSUE THREAD

**Issue by jsoref** [microsoft/vscode-pull-request-github#6008]
Type: <b>Bug</b>

1. Load https://github.com/fireship-io/fireship.io/pull/1745 in VS Code Pull Requests
2. Browse to content/lessons/firestore-nosql-data-modeling-by-example/img/root-col-firestore-08.png
3. See `An error occured while loading the image`

Extension version: 0.86.1
VS Code version: Code 1.88.1 (Universal) (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:42:52.765Z)
OS version: Darwin arm64 23.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|64.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id 1fc67ee2-0174-4598-9f98-4537df0dd32c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
tftest:31042121
vswsl492:30256859
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelc:31048052
dsvsc021:30996838
945dj816:31013170
a69g1124:31046351
pythonprc:31047982
dwnewjupytercf:31046870
26j00206:31048877

```

</details>

**Comment by jsoref** [comment]
<img width="1815" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/2119212/91dc5977-20d5-40f5-89e3-43d61bf03178">

**Comment by alexr00** [comment]
I see the right, but not the left. Still a bug though.

![image](https://github.com/microsoft/vscode-pull-request-github/assets/38270282/4867b204-36f6-46d0-b80c-b8488ae578f3)

**Comment by andreamah** [comment]
![image](https://github.com/user-attachments/assets/be319555-5519-40ca-bdb4-b66e6fa33c8a)

I'm seeing this. Am I doing something wrong?

**Comment by alexr00** [comment]
I can't repro. Please make sure that you're using the latest pre-release version of the extension!

**Comment by andreamah** [comment]
I'm using the latest prerelease and am still running into this. 
![Image](https://github.com/user-attachments/assets/62077c68-ffca-46a0-9fad-d0b9e5a667b1)
@alexr00 I can hop on a call to try to help debug if it helps.

**Comment by alexr00** [comment]
Ah I think I see what happened (thanks for the full window screenshot!). It is fixed if the PR is checked out, but not if the diff is opened without checking out the PR.

**Comment by alexr00** [comment]
To verify:
1. Go to insiders.vscode.dev/github/fireship-io/fireship.io
2. Make sure you have the latest pre-release version of GitHub Pull Requests installed
3. In the "Pull Requests" view, expand the PR "Spelling", which is #1745
4. Scroll through that PR to find `content/lessons/firestore-nosql-data-modeling-by-example/img/root-col-firestore-08.png` and open the diff

Verify that both sides of the diff show (they'll be the same image).

**Comment by jsoref** [comment]
@alexr00 note that in step 3, the correct PR is https://github.com/fireship-io/fireship.io/pull/1745
