### ISSUE TITLE
Avoid preselecting PR branch as base

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-pull-request-github#6016]
Type: <b>Bug</b>

I sometimes submit a PR and then immediately create a new branch because my next change depends on or conflicts with the submitted change. When I later create a PR from this new branch (after rebasing against `origin/main`), the PR extension preselects the previous PR's branch as the base branch. This is almost never the correct base branch. It would make sense to ignore PR branches when trying to find a good candidate for the base branch.

Extension version: 0.89.2024051504
VS Code version: Code - Insiders 1.90.0-insider (e82e806f172f30aecb0e6bb04c01f37780c16f22, 2024-05-24T05:49:11.911Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|6, 5, 4|
|Memory (System)|64.00GB (3.24GB free)|
|Process Argv|--log trace --crash-reporter-id 7aad610c-0e6b-48aa-ba87-b704b1b543cf|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
vscod805cf:30301675
vsaa593:30376534
py29gd2263:31024238
c4g48928:30535728
a9j8j154:30646983
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pythonmypyd1:30859725
pythoncet0:30859736
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
showvideot:31016890
chatpanelt:31014475
9c06g630:31013171
a69g1124:31018687
dvdeprecation:31040973
pythonprt:31036556
dwnewjupyter:31046869
impr_priority:31057980
26j00206:31048877

```

</details>

**Comment by alexr00** [comment]
There are flows in which using a PR branch as the base is desired. I think we can use the following heuristic though:
- "parent" branch is a PR branch
- "parent" branch is deleted or has an open PR to another branch.
