### ISSUE TITLE
Error upgrading from v0.61.2023030915 to v0.89.2024051504

### ISSUE THREAD

**Issue by hsbatra63** [microsoft/vscode-pull-request-github#6018]
- Extension version: v0.89.2024051504
- VSCode Version: 1.89.1
- OS: Windows 10 22H2 (OS Build 19045.4412
- Repository Clone Configuration (single repository/fork of an upstream repository):
- Github Product (Github.com/Github Enterprise version x.x.x): git version 2.45.1.windows.1

Steps to Reproduce:

1. choco upgrade vscode-pull-request-github -y
2. ERROR
3. `Installing Visual Studio Code extension C:\ProgramData\chocolatey\lib\vscode-pull-request-github\tools\**C:\**projects\chocolatey-packages\automatic\vscode-pull-request-github\tools\GitHub.vscode-pull-request-github-0.89.2024051504.vsix in C:\Program Files\Microsoft VS Code\bin\code.cmd...
a [Error]: ENOENT: no such file or directory, open 'c:\ProgramData\chocolatey\lib\vscode-pull-request-github\tools\**C:\**projects\chocolatey-packages\automatic\vscode-pull-request-github\tools\GitHub.vscode-pull-request-github-0.89.2024051504.vsix'
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cliProcessMain.js:18:14842
    at v (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cliProcessMain.js:18:13405)
    at FSReqCallback.oncomplete (node:fs:202:23) {
  type: undefined,
  cause: [Error: ENOENT: no such file or directory, open 'c:\ProgramData\chocolatey\lib\vscode-pull-request-github\tools\C:\projects\chocolatey-packages\automatic\vscode-pull-request-github\tools\GitHub.vscode-pull-request-github-0.89.2024051504.vsix'] {
    errno: -4058,
    code: 'ENOENT',
    at C:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\yauzl\index.js:37:21
    syscall: 'open',
    path: 'c:\\ProgramData\\chocolatey\\lib\\vscode-pull-request-github\\tools\\**C:\\**projects\\chocolatey-packages\\automatic\\vscode-pull-request-github\\tools\\GitHub.vscode-pull-request-github-0.89.2024051504.vsix'
  }
}
Failed Installing Extensions: file:///c%3A/ProgramData/chocolatey/lib/vscode-pull-request-github/tools/**C%3A/**projects/chocolatey-packages/automatic/vscode-pull-request-github/tools/GitHub.vscode-pull-request-github-0.89.2024051504.vsix
ERROR: Running ["C:\Program Files\Microsoft VS Code\bin\code.cmd" --install-extension C:\ProgramData\chocolatey\lib\vscode-pull-request-github\tools\C:\projects\chocolatey-packages\automatic\vscode-pull-request-github\tools\GitHub.vscode-pull-request-github-0.89.2024051504.vsix] was not successful. Exit code was '1'. See log for possible error messages.
The upgrade of vscode-pull-request-github was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\vscode-pull-request-github\tools\chocolateyinstall.ps1'.
 See log for details.`

**Comment by alexr00** [comment]
We don't explicitly support installing via chocolaty.
