### ISSUE TITLE
Missing personal access token scope in Wiki documentation

### ISSUE THREAD

**Issue by csdhome** [Microsoft/vscode-pull-request-github#602]
Hello,

I was following your Wiki article about creating a personal access token and noticed it was missing what appears to be an optional scope "write:discussion" that I found was also used in the code.

Code line from https://github.com/Microsoft/vscode-pull-request-github/blob/master/src/authentication/githubServer.ts#L8
```
const SCOPES: string = 'read:user user:email repo write:discussion';
```
Could you please update the Wiki documentation to include that scope?

Thanks,
Chris Hansen

**Comment by RMacfarlane** [comment]
Thanks @csdhome! I've updated the documentation.
