### ISSUE TITLE
Initially failed to switch to PR mode when checking out PR

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-pull-request-github#6022]
In my multiroot workspace, I found PR `212501` in "Assigned to Me", right clicked, "Checkout Pull Request". It seems like it checked out the PR but didn't show the UI for the current PR. I see a bunch of errors in the log. Not sure why I got the 403s. I reloaded the window, and then it worked as expected. 

The log shows checking out the PR and then reloading the window.

[ghpr2.log](https://github.com/user-attachments/files/15488762/ghpr2.log)

**Comment by alexr00** [comment]
This looks like GitHub had a temporary issue. I think you probably already have the default log level set to `debug` for GitHub Pull Request now, but if you don't, would you mind setting it? I've added more debug logging to confirm that we're asking GitHub for the correct PR.
