### ISSUE TITLE
Should PR webview support search?

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode-pull-request-github#6029]
Since the layout of a PR webview different from GH, would it help users to have ability to search on the page to adapt to the new view faster if they could search? 

I couldn't find "convert to draft" button and had to look very very closely at every button. 

It could also be interesting: 

- I would love if search would leave the focus on the element/button that it finds so that pressing "Enter" would trigger that button (it would serve as a kb shortcut of sorts) 

- I don't think we diverge in button labels from gh.com too much but we could allow search  to also match our button using gh.com button labels; a bit of artifical example: "Edit" button on gh.com which allows renaming a PR is named "Rename" 

![Image](https://github.com/microsoft/vscode-pull-request-github/assets/16353531/46a7acba-1f21-49e3-8b1a-69ec5ba0bf7b)

(feel free to close if that doesn't match your vision)

**Comment by alexr00** [comment]
Turns out that enabling the find widget is super simple.
