### ISSUE TITLE
PR right-click menu entries appear doubled

### ISSUE THREAD

**Issue by ronjouch** [Microsoft/vscode-pull-request-github#604]
- Extension version: 0.2.1
- VSCode:
Version: 1.29.0-insider
Commit: d1f5894892e3719846bbd4bd0dd75f117f211ab5
Date: 2018-10-23T05:14:53.945Z
Electron: 2.0.11
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Steps to Reproduce**:

1. Open Source control pane
2. In side pane "Github Pull requests", expand "All", expand an existing PR.

**Expected**: N menu entries

**Actual**: N * 2 menu entries.

![screenshot_double-labels-right-click-github-pr_2018-10-23-11 14 25](https://user-images.githubusercontent.com/522085/47371118-387de700-d6b5-11e8-9d0b-45da19169ad5.png)

**Comment by RMacfarlane** [comment]
Hmm, I haven't been able to reproduce this yet. Is this on windows or linux? Is `"window.titleBarStyle": "custom"` set?

**Comment by ronjouch** [comment]
Problem still present with version 0.2.2: All PR context menu entries are duplicated ("Check Out Pull Request", "Refresh Pull Request", "Open Pull Request in GitHub"), except "Close Pull Request"

- VSCode info
Version: 1.29.0-insider
Commit: 2b06dd1ca31e407abed24f65e1804ae86180401d
Date: 2018-10-30T11:07:40.142Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
- OS: Ubuntu 18.04.1 LTS
- window.titleBarStyle = "native"

**Comment by ronjouch** [comment]
@RMacfarlane @sbatten problem still present with version 0.2.2: All PR context menu entries are duplicated ("Check Out Pull Request", "Refresh Pull Request", "Open Pull Request in GitHub"), except "Close Pull Request"

- VSCode info
Version: 1.29.0-insider
Commit: 2b06dd1ca31e407abed24f65e1804ae86180401d
Date: 2018-10-30T11:07:40.142Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
- OS: Ubuntu 18.04.1 LTS
- window.titleBarStyle = "native"

**Comment by RMacfarlane** [comment]
@ronjouch Did you ever manually install an early version of the extension? At one point, we changed the id of the extension, but this was before we published the extension to the marketplace. Since the id is different, it's possible to have a very old version of the extension side-by-side with the current one. Can you check your installed extension list?

**Comment by ronjouch** [comment]
> *"Did you ever manually install an early version of the extension? At one point, we changed the id of the extension, but this was before we published the extension to the marketplace. Since the id is different, it's possible to have a very old version of the extension side-by-side with the current one. Can you check your installed extension list?"*

@RMacfarlane ha! Yes! Nice catch! Fixed after uninstalling the old one 🙂.

![screenshot_two-githubpr-extensions_2018-10-31-09 20 51](https://user-images.githubusercontent.com/522085/47790796-7a7ade80-dcee-11e8-98d4-b30934d61853.png)
