### ISSUE TITLE
Make "Make a Suggestion" more clear

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode-pull-request-github#6040]
I already clicked so many times on "Make a Suggestion" when I just wanted to click on "Add Review Comment" instead.

I think this is because my comment is usually a suggestion and my brains sees "Make a suggestion" and that is exactly what I want (except that the button action does something else).

Can we rename the button to make it more clear? (though I don't have a good suggestion here)
Or put the button somewhere else?

**Comment by alexr00** [comment]
The may help: `ctrl+enter` will submit the comment.

**Comment by alexr00** [comment]
Renaming to "Make Code Suggestion"
