### ISSUE TITLE
Sign In issue

### ISSUE THREAD

**Issue by SucceedIT** [microsoft/vscode-pull-request-github#6044]
- Extension version: 0.88.1
- VSCode Version: 1.90.1
- OS: Version	Win 10.0.19045 Build 19045
- Repository Clone Configuration (single repository/fork of an upstream repository):
- Github Product (Github.com/Github Enterprise version x.x.x):

We are using DevOps  with GitHub repositories.  URL https://dev.azure.com/{{companyname}}.  All repos are private and have such URL https://{{companyname}}@dev.azure.com/{{companyname}}/{{Project Name}}/_git/{{Repo Name}}
I have one windows work account to sign in to devops and second account with same email for GitHub.

"github-enterprise.uri" has been added in user setting .json
![image](https://github.com/microsoft/vscode-pull-request-github/assets/58585145/7f6f3bd3-6655-42ec-acba-4b8fc1aba7d7)

Steps to Reproduce:

1. Press Sign In button
2. ![image](https://github.com/microsoft/vscode-pull-request-github/assets/58585145/0bb37cd0-b190-40af-884f-a7078080bd56)
3.
![image](https://github.com/microsoft/vscode-pull-request-github/assets/58585145/5394d320-ff45-4a15-88bc-40a31d536323)
![image](https://github.com/microsoft/vscode-pull-request-github/assets/58585145/3c51eeef-4eea-43ae-b9aa-d1f56b1b6c27)
![image](https://github.com/microsoft/vscode-pull-request-github/assets/58585145/3b7a4c93-e3a9-43b1-9851-083124cc36db)
![image](https://github.com/microsoft/vscode-pull-request-github/assets/58585145/51925b1b-0331-4d4c-9c54-a8d724c27235)
![image](https://github.com/microsoft/vscode-pull-request-github/assets/58585145/370d243f-a7ca-4c51-902b-0ef405ec48ce)
![image](https://github.com/microsoft/vscode-pull-request-github/assets/58585145/ce517100-14ed-44bc-a821-533d29dc457a)

Which permission should i have?  Why URL for token does not contain company name?

if i press create new PR icon i see the following errors
![image](https://github.com/microsoft/vscode-pull-request-github/assets/58585145/d9991b2a-f288-41e4-8118-f9490fb2c2cf)
![image](https://github.com/microsoft/vscode-pull-request-github/assets/58585145/5a2cbbaf-7c38-4769-8ee5-e59e3e0388c8)
new icon appears in left bar  with forever progress bar
![image](https://github.com/microsoft/vscode-pull-request-github/assets/58585145/e411d238-2ebd-496d-a93c-8202afe070a5)

but repo contains origin remotes
![image](https://github.com/microsoft/vscode-pull-request-github/assets/58585145/ba770ecd-6b15-4338-94c6-933bbd294e7b)

Kind regards,
Gregory

**Comment by alexr00** [comment]
@SucceedIT this looks like a _git_ repository on Azure Dev Ops, not a _GitHub_ repository. This extension only supports GitHub, not azure dev ops.

**Comment by msolcia** [comment]
Is there a plan to extend the support to Azure DevOps repos?
