### ISSUE TITLE
Use notification progress when deleting branches and remotes

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#6050]
Trying to delete branches and remotes via the command and I'm seeing this:

![image](https://github.com/user-attachments/assets/8b3ba1f0-8150-457f-8985-4d5fa79f9e3b)

It's been there for a minute or so and I have no idea how long it's going to be blocking my work for and am a little worried about corruption if I cancel it. Can this be in a notification with its content being updated to show which branch/remote is being deleted?

**Comment by meganrogge** [comment]
This is a handy command and I like the notification / progress updates.
