### ISSUE TITLE
Rate limiting when deleting branches and remotes

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#6051]
Related: https://github.com/microsoft/vscode-pull-request-github/issues/6050

I'm trying to delete _a lot_ of branches and remotes:

![image](https://github.com/user-attachments/assets/1aed5059-7495-4788-8ff2-b8009dcafc09)

From the logs it looks like I'm quickly being rate limited without user feedback:

[delete.log](https://github.com/user-attachments/files/15915409/delete.log)

Additionally eventually (3-5 minutes later?) I got this error:

![image](https://github.com/user-attachments/assets/9b5d900d-92a8-4fc2-b49b-890eebfddb64)

**Comment by Tyriar** [comment]
When I try again I see it only got through a small amount of branches:

![image](https://github.com/user-attachments/assets/b451355d-9f2d-4412-9c3d-448dfc61dd25)

**Comment by alexr00** [comment]
This is happening because of a git related file being locked.

**Comment by andreamah** [comment]
Can this be repro-ed with just one branch? Are there minimal repro steps for this?
