### ISSUE TITLE
Show date next to commits in PR view

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-pull-request-github#6058]
Would be nice if commits showed the date:

![image](https://github.com/user-attachments/assets/88a2138e-3ff8-4997-8876-fe138ad5f88a)

Similar to GH:

![image](https://github.com/user-attachments/assets/2075de99-4f4e-4e75-94f9-6e62d5822108)

**Comment by alexr00** [comment]
New behavior:

![image](https://github.com/user-attachments/assets/8783d14f-92ec-438d-a318-3881845bd67b)

**Comment by alexr00** [comment]
Sure, we already have a library we're using for relative dates. I don't have a strong preference.

**Comment by bpasero** [comment]
I felt it would be best to match what GH does 👍

**Comment by alexr00** [comment]
I was trying to match what GH does with the concrete date. After seeing the relative date, I strongly prefer the concrete date:

![image](https://github.com/user-attachments/assets/259e2f51-fedc-4072-90d8-027b7831e49f)

**Comment by bpasero** [comment]
I guess this is a case for a setting then. My preference is for relative dates because that gives me an immediate feedback how "recent" a change is.

**Comment by alexr00** [comment]
We exclusively show the relative date in the PR description. For internal consistency I'll update the commits subtree to do the same. If anyone besides me wants the non-relative format then I'll add a setting.

![image](https://github.com/user-attachments/assets/4e41f7d9-398b-4c75-9586-81c04b7ca8bb)
