### ISSUE TITLE
After adding comments, the profile picture changes to default Identicon that was present during account creation

### ISSUE THREAD

**Issue by magesh-tph** [microsoft/vscode-pull-request-github#6061]
- Extension version:
- VSCode Version: 1.90.2 (system setup)
- OS: Windows_NT x64 10.0.22631 (WSL2 with Ubuntu 22.04)
- Repository Clone Configuration (single repository/fork of an upstream repository):  ??
- Github Product (Github.com/Github Enterprise version x.x.x): N/A

Steps to Reproduce:

1. I have multiple Github accounts signed in, one account for settings sync, one account for GitHub PR extension
2. Create a PR with the extension
3. Add comment, while adding the comment the profile picture stays for few seconds and then it changes to default Identicon that was present during the creation of this account

Video:
[Here is the screen recording of the issue](https://youtu.be/1JECQCR4Txg) as GitHub is not allowing me to upload it as it is more than 10MB

The PR shown in the video: https://github.com/magesh-tph/vscode-pull-request-github/pull/1

**Comment by alexr00** [comment]
Thanks for including the video! Having multiple GitHub accounts isn't supported by VS Code, and by extension, this extension, right now. It might be coming soon the VS Code, at which point I'll immediately adopt it for the extension. @TylerLeonhardt FYI since they somehow managed to get two different GitHub accounts signed in.

**Comment by alexr00** [comment]
Refs: https://github.com/microsoft/vscode/issues/152399, https://github.com/microsoft/vscode/issues/127967

**Comment by magesh-tph** [comment]
Thanks for clearing it out 👍

**Comment by pWoLiAn** [comment]
@alexr00 It looks like the feature was merged to upstream but I still see the issue with latest versions of vscode and extension
