### ISSUE TITLE
fetching pull requests failed in infinite loop when proxy is unavailable

### ISSUE THREAD

**Issue by jsoref** [microsoft/vscode-pull-request-github#6063]
Type: <b>Bug</b>

1. Open a terminal
2. Run `export http_proxy=http://localhost:3128;export https_proxy=http://localhost:3128`
3. Do not have anything listening on that port.
4. Have a clone of https://github.com/fireship-io/fireship.io
5. Have 3 remotes in it:
```sh
fireship.io % git remote -v
check-spelling  https://github.com/check-spelling-sandbox/fireship.io.git (fetch)
check-spelling  https://github.com/check-spelling-sandbox/fireship.io.git (push)
jsoref  https://github.com/jsoref/fireship.io.git (fetch)
jsoref  https://github.com/jsoref/fireship.io.git (push)
origin  git@github.com:fireship-io/fireship.io.git (fetch)
origin  git@github.com:fireship-io/fireship.io.git (push)
```
6. Use `code .` to open the repository in vscode (inheriting the proxy)
7. Open the Pull Requests sidebar
8. Expand Pull Requests
9. Click `Created By Me` to expand
10. See infinite loop of things
 
https://github.com/microsoft/vscode-pull-request-github/assets/2119212/a4232b14-407c-4c58-9f78-fa83fc6884d9

Expected results:
1. Do not have an infinite loop
2. Error messages should be visible long enough for a user to do something to them
3. Whatever the underlying error is also shouldn't happen, but I'm more concerned by the first two points.

Extension version: 0.90.0
VS Code version: Code 1.90.2 (Universal) (5437499feb04f7a586f677b155b039bc2b3669eb, 2024-06-18T22:37:41.291Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|5, 5, 5|
|Memory (System)|64.00GB (0.70GB free)|
|Process Argv|--crash-reporter-id 1fc67ee2-0174-4598-9f98-4537df0dd32c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
945dj816:31013170
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31082723

```

</details>

The underlying error is:
> Fetching pull requests failed: request to https://api.github.com/repos/fireship-io/fireship.io/pulls?per_page=20&page=1 failed, reason: Failed to establish a socket connection to proxies: ["PROXY localhost:3128"]

<img width="467" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/2119212/4cc9700b-c3fa-4d58-a45d-523812d4281e">

**Comment by jsoref** [comment]
Fwiw, there appears to be one notification, 
<img width="485" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/2119212/9ab38214-75b4-479e-9614-3767ead6fe60">

... but I can't click the 🔔 to see it.

**Comment by jsoref** [comment]
... This is similar to #5814, but I'm on macOS, not in China, and there is no proxy, ...
so testing, fixing, and validating should be easy to do, and I should be responsive for at least the next month...

**Comment by TylerLeonhardt** [comment]
Can you all try the pre-release version of the GitHub PR extension? We'd like to verify that the fix that was made works for you.

Find the extension in the extensions view and then choose "Switch to pre-release version"
