### ISSUE TITLE
Comments not visible in private PR

### ISSUE THREAD

**Issue by scarf005** [microsoft/vscode-pull-request-github#6066]
- Extension version: v0.91.2024062604 (pre-release)
- VSCode Version:  1.90.0
- OS: macOS Monterey 12.5 arm64
- Repository Clone Configuration (single repository/fork of an upstream repository):
- Github Product (Github.com/Github Enterprise version x.x.x):

Steps to Reproduce:

1. Create a private repo.
2. as user A: Create a PR.
3. as user B: Create a review comment.
4. as user A: open VSCode, go to `Github Pull Request` tab, check comment made by user B.

<img width="1254" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/54838975/9ce63d24-9ffa-407d-863d-9b12b8436b5e">

<img width="332" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/54838975/58a381e9-20f3-4cfb-b6ad-400dd10bb75f">

6. despite having comment text (as seen in edit menu), it is not visible.

---

extension log: [github-pull-request.log](https://github.com/user-attachments/files/16006994/github-pull-request.log)

**Comment by alexr00** [comment]
I'm not able to repro this. Can you share the text of the comment? We do a bunch of processing on the comment to make it display nicely, and I suspect that it's going wrong and we're not displaying it at all.

**Comment by alexr00** [comment]
Closing because no further info was provided. I'm happy to take another look if you can share the text of the comment!
