### ISSUE TITLE
Stuck in switching to review mode on checkout

### ISSUE THREAD

**Issue by st-schneider** [microsoft/vscode-pull-request-github#608]
Issue Type: <b>Bug</b>

When I try to enter review mode by hitting checkout in the PR and I'm already on that branche I get stuck in `Switching to Review Mode`.
It would be nice if I could enter review mode of a PR without checkout if I'm already on that branch.
![image](https://user-images.githubusercontent.com/30625381/47414811-3037b180-d772-11e8-9b59-66bfd54e536d.png)

Extension version: 0.2.1
VS Code version: Code - Insiders 1.29.0-insider (43823dae97f07760958ffbb5e16c7f219307159c, 2018-10-24T05:11:32.976Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by queerviolet** [comment]
Hi! Thanks for the report, this is indeed annoying.

If you're already on the branch, switching into review mode is essentially a no-op. As a workaround, you can review changes without clicking `Checkout`.

**Comment by bm-stschneider** [comment]
The thing is, if I'm not in review mode, I don't get the tab in the sidebar for `changes in this pr` which is then the only option to jump to the files of that pr.

**Comment by msamsel** [comment]
I've got the same issue under MacOS HighSierra.

**Comment by alexr00** [comment]
We automatically enter review mode on branch checkout so this should be fixed now. If you're still seeing the problem feel free to ping this issue!

**Comment by bkmeneguello** [comment]
I got this error today when using WSL and trying to checkout from the "Pull Requests" panel > All > PR (right click + "Checkout Pull Request").
Latest VSCode and plugin version
