### ISSUE TITLE
Auth issue causes endless notifications

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode-pull-request-github#6081]
There is some kind of authentication issue this morning. All extensions using GH have issues but GHPR is very aggressively retrying causing endless notifications spam. 

https://github.com/user-attachments/assets/c7c305c0-ce92-44ca-bda3-337b8aa90df6

@TylerLeonhardt The renderer/api-impl should prevent this from happening

**Comment by TylerLeonhardt** [comment]
This is not something that that auth stack can help with because it is not in control of requests, only minting auth tokens. This needs to be handled in the extension.

**Comment by alexr00** [comment]
@jrieken if you see this again please share GitHub Pull Request logs.
