### ISSUE TITLE
Files changed shows up twice

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode-pull-request-github#6083]
- Extension version: v0.93.2024070904 (pre-release)
- VSCode Version: Version: 1.92.0-insider (user setup) b23e791eb5afbd95f05aa24da7693ce89344a079
- OS: Windows 11
- Repository Clone Configuration (single repository/fork of an upstream repository): microsoft/vscode
- Github Product (Github.com/Github Enterprise version x.x.x): N/A

Steps to Reproduce:

1. Bump distro
2. See that package.json shows up twice in the PR

![package.json showing up twice under Files Changed viewlet](https://github.com/user-attachments/assets/cf5d5d76-3c08-4137-a992-5329ea584bae)

**Comment by alexr00** [comment]
I've added logging to track this down as I'm unable to repro or see what could cause this. @rzhao271, starting with Thursday's pre-release could you set the default log level  of GitHub Pull Request to "Debug" and then share logs when you see this again?

**Comment by alexr00** [comment]
Closing because no further info was provided.
