### ISSUE TITLE
Fetching pull requests failed: Protocol "https:" not supported. Expected "http:"

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-pull-request-github#6088]
Steps to Reproduce:

1. Open GHPR pull requests view
2. :bug: See a lot of error notifications:

![Image](https://github.com/user-attachments/assets/27787880-a94e-40d4-8bea-56b56131667c)
![Image](https://github.com/user-attachments/assets/b6361989-5e2d-4f7b-8631-fab9c2940083)

**Comment by alexr00** [comment]
- I went back to commits from May, and the issue happens even there. 
- I tried across several repos, some Microsoft, some not and the issue only occurred in https://github.com/microsoft/vscode
- I don't see any `settings.json` changes that would have affected this.

@joyceerhl did you also only see this in https://github.com/microsoft/vscode?

**Comment by alexr00** [comment]
I suspect some setting that is set with a delay. If you open the PRs view, then reload, you'll actually see all the queries succeed the first time.

**Comment by alexr00** [comment]
Found that this is caused to ms-vscode.extension-test-runner thanks to extension bisect.

**Comment by alexr00** [comment]
Issue for Extension Test Runner: https://github.com/microsoft/vscode-extension-test-runner/issues/42
