### ISSUE TITLE
Long commit descriptions overflow off page

### ISSUE THREAD

**Issue by JeffreyCA** [Microsoft/vscode-pull-request-github#609]
- Extension version: 0.2.1
- VSCode Version: 1.28.2
- OS: macOS 10.14

Steps to Reproduce:

1. View Pull Request with long commit description

<img width="863" alt="screen shot 2018-10-24 at 12 06 38 pm" src="https://user-images.githubusercontent.com/9157833/47444863-75b1aa00-d785-11e8-9f47-fb990ba90a76.png">

**Comment by Tyriar** [comment]
Related #302
