### ISSUE TITLE
translation in zh-cn is wrong

### ISSUE THREAD

**Issue by chenqiongqiong** [microsoft/vscode-pull-request-github#6099]
![image](https://github.com/user-attachments/assets/3a0ddbaa-8247-4716-b61f-0753b1f7b952)
'斗士' should be '都是'

**Comment by chenqiongqiong** [comment]
I cannot find the source code of i18n

**Comment by alexr00** [comment]
@TylerLeonhardt, how can I report a possibly incorrect translation?

**Comment by TylerLeonhardt** [comment]
We are now tracking this internally and will work with our Localization team to address this

**Comment by alexr00** [comment]
Looks like the internal issue has been resolved.
