### ISSUE TITLE
Extension state does not track git state

### ISSUE THREAD

**Issue by queerviolet** [microsoft/vscode-pull-request-github#610]
Tracking bug for updating extension state to correspond with git state. Current issues that manifest this:

- https://github.com/Microsoft/vscode-pull-request-github/issues/608 — Review state doesn't appropriately track branches checked out elsewhere
- https://github.com/Microsoft/vscode-pull-request-github/issues/607 — We don't refresh remotes when remotes are updated.

I'm connecting these because I have a sense that they have a common fix: observe `.git` and refresh our state on changes.

**Comment by RMacfarlane** [comment]
We do have some code listening for git state changes in the review manager:

https://github.com/Microsoft/vscode-pull-request-github/blob/0cefc3724f64e482b5f3f1a1b87c253a950c3ac3/src/view/reviewManager.ts#L84-L123

This `repository.state.onDidChange` event is coming from the git extension API, this should be fired for any git changes, we should only fire an event to update the UI if the branch or remotes have changed.

Not sure what would be going wrong here, just wanted to point to that as a starting place

**Comment by RMacfarlane** [comment]
Closing this issue as the extension is tracking git state for both of those cases
