### ISSUE TITLE
Test reverting a PR

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#6102]
Refs: https://github.com/microsoft/vscode-pull-request-github/issues/2103

- [x] anyOS @meganrogge
- [x] anyOS @hediet

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode-pull-request-github/issues/new?body=Testing+%236102%0A%0A&assignees=alexr00)

---

Make sure to install the latest pre-release version of GitHub Pull Requests.

1. Set your queries so that you can get a merged PR to show. Ex:
```
	"githubPullRequests.queries": [
...
		{
			"label": "Merged",
			"query": "is:closed is:merged author:${user}"
		},
	],
```
2. Open a folder that contains your clone of a GH repo.
3. From the "Pull Requests" view, expand a merged PR and open the dscription.
4. In the description, find the "Revert" button and click it.
5. Verify that a simplified "Create" view opens. Verify that you can set reviewers, assignees, etc., just like on a regular PR.
> Note: it would be nice if we showed a diff of the files that will be reverted, but the GitHub API doesn't provide a nice way to get this.
6. Verify that you can create the revert PR and set it to draft or auto-merge, depending on what your repo supports. 
7. Verify that once the PR is created the description of this new PR is opened.

**Comment by meganrogge** [comment]
Works great, even when I reload the window 👏
