### ISSUE TITLE
Extension causes re-opening of closed read-only buffer

### ISSUE THREAD

**Issue by sezna** [microsoft/vscode-pull-request-github#6109]
I believe this _might_ be a duplicate of #6087 but it also might not be.

- Extension version:  0.92.0
- VSCode Version: 1.91.1
- OS: Darwin arm64 23.5.0
- Repository Clone Configuration (single repository/fork of an upstream repository): single repo
- Github Product (Github.com/Github Enterprise version x.x.x): Github.com

Steps to Reproduce:

We publish an extension called `Azure Quantum Development Kit`. To reproduce this issue, use our latest development pre-release build and go-to def on a file.

1. Install VS Code extension `quantum.qsharp-lang-vscode-dev`
2. Open a `.qs` file
3. Type "shor" and select "Shor sample" from the autocomplete
4. go-to definition on any standard library function. For example, `ApplyXorInPlace`
5. Close the read-only buffer that was just opened to render the standard library. Note that an additional event is triggered that re-opens the file and brings the diagnostics back.

This error disappears when we uninstall the pull requests extension.

Thanks for your help!

**Comment by alexr00** [comment]
Sounds similar to https://github.com/microsoft/vscode-pull-request-github/issues/6087

**Comment by alexr00** [comment]
Just like https://github.com/microsoft/vscode-pull-request-github/issues/6087, I can't repro this. Can you set the log level of GitHub Pull Request to trace, repro, then share the output of GitHub Pull Request? I'm not sure that there will be anything in there that shows what's going on, but it's easy to collect.

**Comment by alexr00** [comment]
Closing because no further info was provided.
