### ISSUE TITLE
<details> and <summary> don't render in PR descriptions / comments

### ISSUE THREAD

**Issue by queerviolet** [Microsoft/vscode-pull-request-github#611]
In particular, `<details>` and `<summary>` appear to get escaped, when they should be passed through:

- Extension version: 0.2.1
- VSCode Version: Version 1.29.0-insider (1.29.0-insider)
- OS: macOS Mojave

Steps to Reproduce:

1. Behold:

![screen shot 2018-10-24 at 3 25 13 pm](https://user-images.githubusercontent.com/7763406/47455921-1bbedd80-d7a1-11e8-9df6-15f35a38ff87.png)

**Comment by queerviolet** [comment]
<details>
  <summary>Do they work in comments too?</summary>
  Apparently.
</details>

**Comment by RMacfarlane** [comment]
I'm still able to reproduce this in 0.2.3
