### ISSUE TITLE
Using "Create Pull Request" command clears entered data

### ISSUE THREAD

**Issue by Ghostbird** [microsoft/vscode-pull-request-github#6114]
- Extension version: 0.92.0
- VSCode Version: 1.91.1 f1e16e1e6214d7c44d078b1f0607b2388f29d729 x64
- OS: Debian 12 (Bookworm)
- Repository Clone Configuration: Single repository
- Github Product: Github.com

Steps to Reproduce:

1. Use the command _GitHub Pull Requests: Create Pull Request_
2. Start writing
3. Check something in another sidebar tab in the UI
4. The tab "Github Pull Request" in de sidebar has disappeared, which is better than that it stays when I'm _not_ making a PR.
5. Re-issue the command _GitHub Pull Requests: Create Pull Request_ to continue your PR
6. UI loads, with all entered data visible
7. UI resets all entered fields automatically

While it is understandable that this happens, it is extremely obnoxious. The UI taunts me with the data I just entered, and then quickly throws it away before I can do anything. Most PRs I make in VSCode I have to write twice or thrice. You'd think I'd learn.

Is it possible that step 7 is prevented when the tab is re-entered from _GitHub Pull Requests: Create Pull Request_ if the source and target branches haven't changed?

Note: I don't want the sidebar tab _Github Pull Request_ to be visible in the sidebar normally:

- It's visually indistinct (maybe even indistinguishable?) from the _Github Pull Requests_ tab.
- There's hardly ever any use for it, except for when actively using it.

Note: It's easier to reproduce, but the steps above also show the workflow that causes me to run into this issue. The simplest reproduction:

1. Use the command _GitHub Pull Requests: Create Pull Request_
2. Start writing
3. Use the command _GitHub Pull Requests: Create Pull Request_
4. UI resets all entered fields automatically

**Comment by alexr00** [comment]
With this change, if you actually exit the "Create" view, then you'll still lose your data. However, if you just open another side bar item, find that you're lost and you don't see the "Create" view anymore, then re-run the "Create Pull Request" command, you'll keep your already entered text.

**Comment by Ghostbird** [comment]
Thanks!
