### ISSUE TITLE
Offer issue suggest in PR title input field

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-pull-request-github#6130]
This suggest:

![Image](https://github.com/user-attachments/assets/263e5f8b-9d99-4006-b88e-9e5fb6e5fca1)

Would be great to have in the PR title input field:

![Image](https://github.com/user-attachments/assets/13433d10-6ce3-4d53-a325-e4fde02ec649)

**Comment by alexr00** [comment]
Would be great to have this in many places. Upstream issue: https://github.com/microsoft/vscode/issues/196705

**Comment by alexr00** [comment]
Closing as upstream.
