### ISSUE TITLE
git config --local branch.main.github-pr-owner-number

### ISSUE THREAD

**Issue by TomasKrouzel** [microsoft/vscode-pull-request-github#6134]
Dear All,

  tried to commit/pull my project to GitHub. This was processed well. Anyway system fails on "configure?" smtg like pr-owner number:

2024-08-07 11:56:33.845 [info] > git config --local branch.main.github-pr-owner-number [196ms]
2024-08-07 11:56:33.846 [warning] git config failed: Failed to execute git
2024-08-07 12:01:34.147 [info] > git config --local branch.main.github-pr-owner-number [258ms]

![image](https://github.com/user-attachments/assets/6a6dcf72-7e9d-4ff3-a04b-e53fc2187df3)

 This task attempt runs every 5mins. This project runs on node.js and is written using VS Code. Could you help how to solve that?

 Thanks for help,

 Tom

 I am attaching content of config file:

[core]
	repositoryformatversion = 0
	filemode = false
	bare = false
	logallrefupdates = true
	symlinks = false
	ignorecase = true
[remote "origin"]
	url = https://github.com/TomasKrouzel/ServerOne.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "main"]
	remote = origin
	merge = refs/heads/main

**Comment by alexr00** [comment]
Can you also share the output from GitHub Pull Request?
