### ISSUE TITLE
Make comment dates clickable, just like in GitHub

### ISSUE THREAD

**Issue by jmg-duarte** [microsoft/vscode-pull-request-github#6154]
As the title states, the following "1 hour ago" should be clickable, or at the very least right-clickable to get a permalink to the GH comment.

<img width="142" alt="Screenshot 2024-08-22 at 11 12 18" src="https://github.com/user-attachments/assets/3bca1f09-9a81-45a3-b93b-9f2c69ce6b94">

I'm keen on implementing this, is there anything I should know beforehand or can I just try to make it a link by wrapping it in a `<a>` tag?

**Comment by jmg-duarte** [comment]
The following line seems to indicate that already happens but even though my comments have URLs, it's still not clickable.
https://github.com/microsoft/vscode-pull-request-github/blob/328512e45bd5aea8d5bbd71fb7a7241cbf6823be/webviews/components/comment.tsx#L148

Sadly, I can't put a breakpoint on that line and none of the guides in the wiki seem very helpful. One of the more adequate ones on the Architecture - `registerWorkspaceCommentProvider` — doesn't even yield results when searched on in the codebase 😕

**Comment by alexr00** [comment]
Is this in the comment widget that shows in the comment editor, or in the PR description/overview?

**Comment by jmg-duarte** [comment]
This one (sorry, I don't know the name)
<img width="710" alt="Screenshot 2024-08-30 at 16 41 17" src="https://github.com/user-attachments/assets/5fcf68e2-14fc-42f9-9c5c-4df4d9af0d12">

**Comment by alexr00** [comment]
Thanks, that's the comment widget.

**Comment by alexr00** [comment]
The date isn't clickable, but you can already copy a link:

![Image](https://github.com/user-attachments/assets/a3321c97-7b6b-4a94-aa11-9d593a8553d3)
