### ISSUE TITLE
Diff Comment with HEAD button in Comments view sometimes disappears

### ISSUE THREAD

**Issue by jo-mpac** [microsoft/vscode-pull-request-github#6157]
- Extension version:
   v0.94.0
- VSCode Version:
   Version: 1.92.2 (Universal)
   Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
   Date: 2024-08-14T17:29:30.058Z
   Electron: 30.1.2
   ElectronBuildId: 9870757
   Chromium: 124.0.6367.243
   Node.js: 20.14.0
   V8: 12.4.254.20-electron.0
   OS: Darwin arm64 23.6.0

Steps to Reproduce:

When a review comment is outdated, `Diff Comment with HEAD` button will show up and let me quickly check what are the changes that made this comment outdated.

However I noticed sometimes the button is gone, and I have to checkout to main and then back to the PR to get it appear again.

I believe there are multiple triggers for this, and refreshing the PR (like the attached video shows) is the most consistent trigger I found. However, when I tried to clone this repo(`microsoft/vscode-pull-request-github`) and recreate the exact scenario for reporting this issue, it didn't happen in my newly forked repo. That's why I couldn't provide reliable reproducing steps here and as a workaround I am attaching a screen recording to show the issue that is only happening in my repo:

https://github.com/user-attachments/assets/b56137a5-4902-4c67-81c3-56b3a7b9102b

I am a bit lost now and not sure how I should further debug this issue. I rely on this awesome feature a lot, so please let me know about anything else I can do to help debug this issue. Thanks a lot!

**Comment by alexr00** [comment]
I also can't repro it, but I can see where this could happen.

**Comment by jo-mpac** [comment]
> I also can't repro it, but I can see where this could happen.

Thank you for looking into it. Please kindly let me know if you would like me to test out the fix.

**Comment by TylerLeonhardt** [comment]
@jo-mpac can you try the latest pre-release version of the GitHub Pull Request? You can get it in the Extension Marketplace

**Comment by jo-mpac** [comment]
> @jo-mpac can you try the latest pre-release version of the GitHub Pull Request? You can get it in the Extension Marketplace

Hey I have been using the pre-release for a while and I believe the issue was fixed! Thank you very much folks ❤️
