### ISSUE TITLE
Do not resize text box when editing PR in the editor

### ISSUE THREAD

**Issue by sfc-gh-paguiar** [microsoft/vscode-pull-request-github#6158]
- Extension version:
- VSCode Version: v0.95.2024082204 (pre-release)
- OS: MacOS
- Github Product (Github.com/Github Enterprise version x.x.x): Enterpise

Steps to Reproduce:

1. View github PR information in VSCode:
![image](https://github.com/user-attachments/assets/c5bffcc2-6a94-4051-8ebe-4dd00b122b48)
2. Click on the edit pencil
3. Box gets resized:
![image](https://github.com/user-attachments/assets/86b6cae1-7c83-45e4-9b94-865087fd0ed9)

**Comment by alexr00** [comment]
I think github.com does the same thing.
