### ISSUE TITLE
Convert to Pull Request Suggestion hard to find in context menu

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-pull-request-github#6168]
Testing #6160

<img width="584" alt="image" src="https://github.com/user-attachments/assets/3059b41b-4480-4dc8-9a7d-cbd752a12f9c">

It took me quite a while to find this action

**Comment by alexr00** [comment]
This does belong with the git related actions. I think this is just a problem with our context menu.

**Comment by alexr00** [comment]
The action is also available from the SCM view.
