### ISSUE TITLE
Indicate when a PR has been merged on the description page

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-pull-request-github#617]
I just merged this PR from the Description page but it doesn't tell me that it's been merged:

![image](https://user-images.githubusercontent.com/2193314/47466766-b6221f80-d7a7-11e8-8562-3dc1bf3790a6.png)

![image](https://user-images.githubusercontent.com/2193314/47466779-c20de180-d7a7-11e8-923c-f4ec0e66d6b6.png)

**Comment by rebornix** [comment]
We should show Merge timeline event in the description page.

**Comment by RMacfarlane** [comment]
Completed with https://github.com/Microsoft/vscode-pull-request-github/pull/831
