### ISSUE TITLE
FR: "create issue" code action (triggerable on FIXME's) could mention the filename for the code block

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode-pull-request-github#6177]
because the commit link attached may be broken if it's not pushed or deleted

**Comment by alexr00** [comment]
To verify:
- Install the latest pre-release version of GitHub Pull Requests
- Open a folder that contains a GitHub repository clone
- Leave a comment in a file that contains a TODO. Ex: `// TODO: Fix this bad thing`
- Run the "Create issue" code action that shows on the TODO.
- Verify that in the issue that's created you see the file mentioned.

**Comment by joyceerhl** [comment]
Works 👍  https://github.com/microsoft/vscode-copilot/issues/9584 I was expecting a notification with a link to the created issue as well
