### ISSUE TITLE
Commit description can overflow off page

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-pull-request-github#618]
Related https://github.com/Microsoft/vscode-pull-request-github/issues/302

![image](https://user-images.githubusercontent.com/2193314/47466871-406a8380-d7a8-11e8-9793-6698f0e8a3c5.png)

**Comment by Tyriar** [comment]
This is actually a really well formed commit message as well, nicely wrapped and everything:

![image](https://user-images.githubusercontent.com/2193314/47466917-7dcf1100-d7a8-11e8-8faf-c31d3a9d93e8.png)

**Comment by RMacfarlane** [comment]
Duplicate of https://github.com/Microsoft/vscode-pull-request-github/issues/609
