### ISSUE TITLE
Parent checkboxes not checked after reload

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-pull-request-github#6193]
Seen on github.dev.
 
1. Set a PR for review
2. Check all files within a folder, notice the folder's checkbox correctly gets checked as well
3. Reload

🐛 Parent checkboxes aren't checked:

![Image](https://github.com/user-attachments/assets/65b3700c-38d8-4655-ab22-21a9a15cafc9)

**Comment by alexr00** [comment]
@joaomoreno I can't reproduce this. Do you always see it? I also tested with PR from your screenshot.

**Comment by joaomoreno** [comment]
Also can't repro by now, let's close it!
