### ISSUE TITLE
Disallow `Make a suggestion` button press if already have a suggestion in the comment

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-pull-request-github#6195]
I often hit this situation

1. Start a PR comment
2. Press `Make a suggestion`
3. Type the suggestion
4. Get confused and think that the `Make a suggestion` button will submit the suggestion. Press it. Retract in shame.

We should disable this button once a suggestion is in the comment.

https://github.com/user-attachments/assets/94223707-45d7-48a1-a60a-8cc121d9259a

**Comment by alexr00** [comment]
Until the comment has been submitted we don't have the contents of the comment in the comment API. We'll need to watch for if the active editor is a comment editor and check the contents of the editor for a suggestion.

**Comment by mfulton26** [comment]
GitHub web UI allows making multiple suggestions in a single comment. With this change will that still be possible? Maybe `Make a Suggestion` should only be disabled when the cursor is inside the suggestion code block/fence.
