### ISSUE TITLE
The shortcut(s) for making a suggestion is currently not working for me on macOS using the pre-release version

### ISSUE THREAD

**Issue by jcanton** [microsoft/vscode-pull-request-github#6199]
Ref  #5768 

- Extension version: v0.79.2024011609
- VSCode Version: 1.85.2 Commit: 8b3775030ed1a69b13e4f4c628c612102e30a681
- OS: macOS 14.6.1
- Repository Clone Configuration (single repository/fork of an upstream repository):
- Github Product (Github.com/Github Enterprise version x.x.x):

Steps to Reproduce:

1. In VS Code, open a folder containing a clone of a GitHub repository
2. Open a file that's in a PR. This can be a currently checked out PR or a file from a PR in the "Pull Requests" view
3. Start to leave a comment in the file by using the + in the editor gutter. This will open the comment widget.
4. Hover over the button "Make a Suggestion". Cannot see a keybinding listed in the hover.
5. Try the suggested `ctrl+k m` keybinding anyway (doesn't work)
6. Try with `cmd` instead of `ctrl`, also doesn't work
7. Open the list of shortcuts for the extension: none is assinged

https://github.com/user-attachments/assets/b8729007-81a5-4f7b-a42e-cb533ddbef24

**Comment by alexr00** [comment]
@jcanton, based on the keybinding logs (thanks for including those in your recording!), it looks like you have `cmd+k` mapped to `workbench.action.focusAboveGroup`, maybe from a vim extension. If you disable that extension, or delete that other keybinding, then the default keybinding for making a suggestion should work.

**Comment by jcanton** [comment]
@alexr00 thank you for the answer but that's not the issue:
even if I delete that keybinding (or remamp it to something else) make a suggestions still doesn't work:

 - when searching for its keyboard shortcuts none is assigned
 - if I manually assing `ctrl+k m` to make a suggestion then I get a `cannot read properties`... error:
 
(the shift + 4 + meta you see afterwards are for taking the screenshot)
 
<img width="2116" alt="Screenshot 2024-09-04 at 18 34 51" src="https://github.com/user-attachments/assets/231e05bd-486f-4fbe-aec3-f4bb67b3362f">

<img width="2552" alt="Screenshot 2024-09-04 at 18 33 36" src="https://github.com/user-attachments/assets/5bd4f0fb-ef70-42c3-a416-7a02546cbb59">

**Comment by alexr00** [comment]
@jcanton it looks like the command is getting executed with your keybinding, however, it looks like you ran the keybinding while your cursor was not in the comment widget editor.

**Comment by jcanton** [comment]
@alexr00 it doesn't work even when the cursor is in the comment widget editor

**Comment by jcanton** [comment]
https://github.com/user-attachments/assets/bac74f15-243b-4d02-bd99-9ed60fa9b4c4

**Comment by alexr00** [comment]
Should have realized this sooner: you're on an old version of VS Code, which means you're on an old version of the extension too. You'll need to use a more recent version of the extension to get this feature, which means you'll also need to update to a more recent version of VS Code.

**Comment by jcanton** [comment]
ah crap, you're right, I had VS Code on manual update... (I have a feeling I'll find out why soon because something will break...)

now updated both VS Code and the extension and everything works as intended (including hovering over the `make a suggestion` button)

thanks a lot! (and good work on the extension, it's very nice ;-) )
