### ISSUE TITLE
Pull Request Template is not populated when new Pull Request is created from github.dev

### ISSUE THREAD

**Issue by dmilburn** [microsoft/vscode-pull-request-github#6210]
- Extension version:
- VSCode Version:
- OS: MacOS Sanoma v14.5
- Repository Clone Configuration (single repository/fork of an upstream repository):
- Github Product (Github.com/Github Enterprise version x.x.x): github.com

Hi, this issue was escalated from GitHub's support team. We believe you're the owners of the github.dev so we're transferring it here:

Customer is reporting that their Pull Request Template - which is stored in the default branch - is not loaded in new Pull Requests created from within github.dev.

Pull Requests created from the regular Repository UI work just fine.

The customer has shared a screen recording demonstrating the issue. (It contains the name of a user's private repository so I didn't include it in this issue. It can be seen in the original [issue](https://github.com/github/codespaces/issues/18661) or please reach out to me through internal channels if you can't see that issue.)

OS: MacOS Sanoma v14.5
Web Browser: Chrome Version 126.0.6478.62 (Official Build) (arm64)

Customer Impact

Include information about customer impact, including which key/strategic customers are impacted.
Include org/repo/user information for this issue where possible.
Link to Zendesk Ticket(s) : [2892807](https://github.zendesk.com/agent/tickets/2892807)

**Comment by alexr00** [comment]
Based on the video this doesn't look like it's using the GitHub Pull Request extension. @joyceerhl, it looks like it's using the Remote Repositories extension's PR flow. I imagine that this just isn't something that Remote Repositories supports.

**Comment by joyceerhl** [comment]
@alexr00 would it make sense for GHPRI offer this action so we can remove it from RemoteHub?

**Comment by alexr00** [comment]
GHPR does offer a way to create a PR from the SCM view. I think we left in in RemoteHub too for the cases where GHPR isn't installed.

**Comment by joyceerhl** [comment]
But GHPRI is installed in github.dev by default 🤔 so in this scenario there shouldn't be a RemoteHub create PR flow

**Comment by alexr00** [comment]
It looks like the user in the screen recording might have disabled "GitHub Pull Requests" @dmilburn would you be able to confirm this?

@joyceerhl, it looks like RemoteHub already tries to do the right thing:
https://github.com/microsoft/vscode-remotehub/blob/fd911c88373583c8995082d7d5cd3293de822da8/extensions/remotehub/package.json#L815-L819

Do we want to keep this, or if the embedder is vscode.dev or github.dev should we prevent the action from getting added?

**Comment by dmilburn** [comment]
> It looks like the user in the screen recording might have disabled "GitHub Pull Requests" @dmilburn would you be able to confirm this?

@danielhardej could you reach out to them please?

**Comment by danielhardej** [comment]
Sure thing @dmilburn - just asked them and will let you know.

**Comment by danielhardej** [comment]
Hi again @dmilburn @alexr00 . Customer says yes, it's enabled.

**Comment by alexr00** [comment]
@danielhardej it doesn't look like it's enabled. Can you have them share a screen shot of the Extensions view with GitHub Pull Request in the view? Ex: 
![Image](https://github.com/user-attachments/assets/c5870016-b27f-4c11-8b04-5cdf07738f64)

**Comment by danielhardej** [comment]
Hey @alexr00 This is what they shared with me:

![Image](https://github.com/user-attachments/assets/dee49630-8bdb-4930-8a22-ffefa3292ad5)

**Comment by alexr00** [comment]
Thanks! Have they signed in to GitHub Pull Requests? They can check by going to the Accounts menu:

![Image](https://github.com/user-attachments/assets/e323e37c-10e9-41f6-ac49-609383db35f9)

**Comment by danielhardej** [comment]
Checking that for you now...

**Comment by danielhardej** [comment]
okay, this is strange. The extension is installed and enabled for them, but doesn't appear under their `Trusted Extensions` list

![Image](https://github.com/user-attachments/assets/3a642863-3388-4161-a0d9-8d683c083f23)

**Comment by alexr00** [comment]
It looks like they haven't signed in yet. They should just be able to open the Pull Requests view and use the sign in button. If they can't find the view, then the command "GitHub Pull Requests: Sign in with GitHub" should get them signed in.
