### ISSUE TITLE
Comments not collapsing even when Expanded State is set to collapseAll

### ISSUE THREAD

**Issue by muchisx** [microsoft/vscode-pull-request-github#6211]
https://github.com/user-attachments/assets/cb654137-2529-49e8-8304-671b7b089242

- Extension version:  0.94.0
- VSCode Version: 1.92.2
- OS: Windows 11
- Repository Clone Configuration (single repository/fork of an upstream repository): 🙇🏼‍♂️
- Github Product (Github.com/Github Enterprise version x.x.x): Github normal?

Steps to Reproduce:

1. Turn off the setting like in the video
2. See it not work

**Comment by alexr00** [comment]
If the comments have been added by the extension before you changed that setting then they will stay uncollapsed until you reload or the extension removes them.  Setting description will be improved with https://github.com/microsoft/vscode-pull-request-github/pull/6213
