### ISSUE TITLE
PR with one new file does not show preview diff properly

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode-pull-request-github#6215]
Type: <b>Bug</b>

1. Add a new Markdown file with some text in a new branch.
2. Commit + Create a PR for it.
3. A Create viewlet shows up, and below that is a Files Changed viewlet.
4. Click on the one new file in the Files Changed viewlet.
5. An error shows up while trying to preview the Markdown file: "The editor could not be opened due to an unexpected error: Git relative path not found. Was looking for test-shorter.md among [list of files here]"

Extension version: 0.97.2024090514
VS Code version: Code - Insiders 1.93.0-insider (4849ca9bdf9666755eb463db297b69e5385090e3, 2024-09-04T13:13:15.344Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-1370P (20 x 2189)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.66GB (13.37GB free)|
|Process Argv|--log vscode.git=trace --crash-reporter-id a3a7e014-dd23-4c90-b27e-2284166f4c15|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
vsaa593cf:30376535
py29gd2263:31024238
c4g48928:30535728
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonnoceb:30776497
asynctok:30898717
dsvsc014:30777825
dsvsc015:30821418
pythonregdiag2:30926734
pythonmypyd1:30859725
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
01bff139:31013167
a69g1124:31018687
dvdeprecation:31040973
dwnewjupytercf:31046870
legacy_priority:31057981
nativerepl1:31104042
refactort:31084545
pythonrstrctxt:31093868
flighttreat:31119334
wkspc-onlycs-t:31111718
nativeloc1:31118317
wkspc-ranged-c:31125598
cf971741:31111988
jh802675:31132134
e80f6927:31120813
fje88620:31121564

```

</details>

**Comment by alexr00** [comment]
I'm not able to reproduce this error. Does it happen every time for you?

**Comment by rzhao271** [comment]
Unable to repro now
