### ISSUE TITLE
When there is a link to a GitHub profile, screen readers read the link twice, first the plain URI and then the profile name

### ISSUE THREAD

**Issue by daniel-montalvo** [microsoft/vscode-pull-request-github#6220]
Type: <b>Bug</b>

With a screen reader running:

open a PR on VS Code and navigate to the PR page.
Arrow down through until you get, for example,  to the person that open the PR, or to any other link to a GitHub profile for that matter.

Expected behavior is to hear the link text "John Doe", and then however the screen reader announces the link role.
Obtained behavior is: you first hear "https://github.com/john-doe, [link role announcement]", and then you do get the link text "John Doe + [ link role announcement]"

I would expect this to work just like on the GitHub website, where the link text only is read by the screen readers.

Extension version: 0.97.2024090514
VS Code version: Code 1.93.0 (4849ca9bdf9666755eb463db297b69e5385090e3, 2024-09-04T13:02:38.431Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-13700H (20 x 2918)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.74GB (49.14GB free)|
|Process Argv|--crash-reporter-id 5cd24c78-daef-41a6-93ba-9dfb6fafae88|
|Screen Reader|yes|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: ubuntu|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|13th Gen Intel(R) Core(TM) i7-13700H (20 x 0)|
|Memory (System)|31.22GB (29.01GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl2:31104044
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31125599
ei213698:31121563

```

</details>

**Comment by alexr00** [comment]
On github.com, for my comments, this is read:

```
alexr00  visited  link    heading    level 3
```

In the extension, this is read:

```
alexr00  link    https://github.com/alexr00
```

**Comment by alexr00** [comment]
We put the full link in the element's `title`, which is why it's getting read. I tried adding an `aria-label`, but the `title` still gets read by NVDA. This appears to be by design according to NVDA: https://github.com/nvaccess/nvda/issues/7841.

I'll add the `aria-label`, but I don't think the behavior you experience will change.

**Comment by daniel-montalvo** [comment]
> On github.com, for my comments, this is read:
> 
> ```
> alexr00  visited  link    heading    level 3
> ```
> 
> In the extension, this is read:
> 
> ```
> alexr00  link    https://github.com/alexr00
> ```

I presume we want the behavior that's currently on github.com replicated in the extension, to enhance efficiency for screen reader users.

**Comment by alexr00** [comment]
We also want to have the `title` to show for sighted users, and we don't want to cause inconsistencies with how screen readers read `aria-label` and `title`. These things are in conflict.

**Comment by dbaeumer** [comment]
Verified that VS Code reads as @alexr00 pointed out.
