### ISSUE TITLE
Consistent and repeated JS/TS language service crashes

### ISSUE THREAD

**Issue by CComparon** [microsoft/vscode-pull-request-github#6231]
My CPU spins up hard with the JS/TS indexer spinning and warning me that "The JS/TS language service crashed 5 times in the last 5 minutes" in a neverending loop.
I'm on my VSCode + Win11 + WSL2 on Ubuntu 22.04.

- Extension version: 0.96
- VS Code version: Code 1.93.1 (https://github.com/microsoft/vscode/commit/38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
- OS: Windows_NT x64 10.0.22635
- Repository Clone Configuration (single repository/fork of an upstream repository): private
- Github Product (Github.com/Github Enterprise version x.x.x):

Steps to Reproduce:

1. Disabled all installed extensions except remote extensions. No symptoms.
2. Reenabled extensions one by one. As soon as vscode-pull-request-github is enabled, the symptoms appear.

Many thanks for your consideration!

**Comment by alexr00** [comment]
Interesting! Does this happen when you have any particular files open?

**Comment by alexr00** [comment]
Closing because no further information was provided.
