### ISSUE TITLE
Contribute to `scm/historyItem/context` menu

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode-pull-request-github#6236]
>  The graph is becoming amazing. Links in GH-provided commit messages would take it to the next level:

![image](https://github.com/user-attachments/assets/7aea8824-71e0-457e-ba39-6d9b87539333)

>  Maybe less complex than parsing commit messages and adding inline links, how about simply having GHPR extension contribute an action to the scm/historyItem/context menu to open the commit at GH?

![image](https://github.com/user-attachments/assets/9522358b-d4c9-482f-928c-e59bba4df311)

_Originally posted by @gjsjohnmurray in https://github.com/microsoft/vscode/issues/226427#issuecomment-2360590015_

**Comment by gjsjohnmurray** [comment]
> I think this will help you.
> 
> `<redacted>`
>
> I put the necessary dlls in the archive

Reported to GH as spam probably conveying malware.

**Comment by alexr00** [comment]
Closing as the PR has moved into microsoft/vscode
