### ISSUE TITLE
"Go to Next Diff in Pull Request" command fails with error

### ISSUE THREAD

**Issue by TaldykinVyacheslav** [microsoft/vscode-pull-request-github#6237]
"Go to Next Diff in Pull Request" command fails with error

- Extension version: 0.96.0
- VSCode Version: 1.93.1
- OS: Windows 11
- Repository Clone Configuration (single repository/fork of an upstream repository): https://github.com/microsoft/vscode-pull-request-github
- Github Product (Github.com/Github Enterprise version x.x.x): Gihub.com

Steps to Reproduce:

1. Cloned https://github.com/microsoft/vscode-pull-request-github
2. Created key binding for "GitHub Pull Requests: Go to Next Diff in Pull Request"
3. Opened first file diff
4. Pressed mentioned hotkey, expecting to be navigated to the next file with the diff
5. Nothing happens, `Current file isn't a pull request diff.` error message pops up 
![Screenshot 2024-09-19 170620](https://github.com/user-attachments/assets/41771681-9c35-4e0f-9259-1704d331ba05)

**Comment by TaldykinVyacheslav** [comment]
Also, "Mark file as Viewed" is not opening next non-viewed file automatically. Is it intended behavior?

**Comment by alexr00** [comment]
> Also, "Mark file as Viewed" is not opening next non-viewed file automatically. Is it intended behavior? 

This is intended behavior, we don't open the next file.
