### ISSUE TITLE
"Apply Suggestion with Copilot" modifies entire file

### ISSUE THREAD

**Issue by burkeholland** [microsoft/vscode-pull-request-github#6238]
- Extension version: v0.97.2024091904 (pre-release)

Version: 1.93.1
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
Date: 2024-09-11T17:20:05.685Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0

- Repository Clone Configuration: single repository
- Github Product (Github.com)

Steps to Reproduce:

1. Open this PR in VS Code https://github.com/microsoft/vscode-docs/pull/7614
2. Go to the comment on line 28
3. Click the sparkles
4. Copilot will add in some odd markup about "Do not change" and then will make the suggestion, but then re-writes the entire article word for word as part of the diff.

**Comment by alexr00** [comment]
@chrmarti is this one that you're aware of?

**Comment by alexr00** [comment]
Sorry about the noise @chrmarti!

**Comment by aiday-mar** [comment]
Hi @burkeholland thank you for filing this issue. Yes so I believe you clicked on the icon which applies the suggestion using Copilot, so it rewrites the whole file. This is therefore expected. I will close this issue, but let me know if there is anything else I can clarify
