### ISSUE TITLE
PRs do not refresh after changing account preferences in dropdown

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode-pull-request-github#6244]
Testing https://github.com/microsoft/vscode/issues/229420

On https://insiders.vscode.dev/github/microsoft/vscode, I logged into two GitHub accounts by signing into one for one extension and signing into an alt one for another extension.
I switched from my main account to the alt account for GHPRI by going to the extension preview, clicking on the gear icon, and selecting Account Preferences.
Then, I pressed refresh on the pull request viewlet, expecting the "Created By Me" section to go blank, but my main account PR was still there.

**Comment by alexr00** [comment]
Super cool that this is supported now! Looks like it needs adoption. @TylerLeonhardt FYI, I'll try to do it in October.
