### ISSUE TITLE
Keybinding for pr.goToNextDiffInPr and pr.goToPreviousDiffInPr Doesn't work

### ISSUE THREAD

**Issue by TristenFielding** [microsoft/vscode-pull-request-github#6247]
Version: 1.93.1 (system setup)
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
Date: 2024-09-11T17:20:05.685Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.19045

- Extension version:0.96.0

Steps to Reproduce:

1. Open the Keyboard Shortcuts file
2. Search for "pr.goto"
3. Set 
    1. Goto Next Diff in Pull Request to `Ctrl+F6`
    4. Goto Previous Diff in Pull Request to `Ctrl+Shift+F6`
2. Open a local pull request under the Local Pull Request Branches node.
5. Select a file that contains files above and below the currently selected file.
6. Try either shortcut.
7. Expected result: to move to the next/prev item in the PR tree and open that file.
8. Actual results: The current file flashes as if it is being reloaded.

**Comment by alexr00** [comment]
Those command only work for checked out PRs. I'll add some error handling so that we show an error when you try to use them outside for this.

**Comment by alexr00** [comment]
Actually, there's already error handling for this. You get an error notification "Current file isn't a pull request diff.".
