### ISSUE TITLE
pr.markFileAsViewed doesn't update the parent nodes.

### ISSUE THREAD

**Issue by TristenFielding** [microsoft/vscode-pull-request-github#6248]
Version: 1.93.1 (system setup)
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
Date: 2024-09-11T17:20:05.685Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.19045

Steps to Reproduce:

1. Create key binding like
    {
        "key": "f6",
        "command": "pr.markFileAsViewed"
    }
2. use the keybinding
    1. the open file will be closed
    2. the file node in the PR tree will be marked as View
    3. Expected Results: If this is the last marked file in the folder, I would expect the parent node also to be marked (recursively up the tree). It should be the same logic as if I clicked on the node's check box.

**Comment by alexr00** [comment]
Fixed by https://github.com/microsoft/vscode/pull/230376

**Comment by TylerLeonhardt** [comment]
verified I think but opened ^^ as a followup
