### ISSUE TITLE
Mark Current File as Viewed and Move to the Next File in the Pull Request

### ISSUE THREAD

**Issue by TristenFielding** [microsoft/vscode-pull-request-github#6249]
I am trying to create a single command (F6) that will

1. Mark the file as Viewed and then
2. Move to the next file in the PR.

Yet, I am having issues with both commands; see #6248 and #6247.

Here's the full command definition.
```
    {
        "key": "f6",
        "command": "runCommands",
        "when": "textCompareEditorVisible",
        "args": {
            "commands": [
                "pr.markFileAsViewed",
                "pr.goToNextDiffInPr"
            ]
        }
    }
```

Is there a better way to achieve this goal?

**Comment by alexr00** [comment]
Those commands both only work if you have checked out the PR. Does your command work if you check out the PR?

**Comment by alexr00** [comment]
Closing because no further info was provided.
