### ISSUE TITLE
Consider having non-blue hyperlinks

### ISSUE THREAD

**Issue by JeffreyCA** [microsoft/vscode-pull-request-github#625]
If we want to replicate the GitHub feel, maybe consider having certain hyperlinks like the username, commit  ID, as regular text colour instead of blue, but underline it when hovered.

**Comment by alexr00** [comment]
Since within VS Code we try to maintain a consistent look, this is something that could be solved by a theme, or by individual users with
```
	"workbench.colorCustomizations": {
		"textLink.activeForeground": "#ff0000", 
		"textLink.foreground": "#ff0000"
	},
``
