### ISSUE TITLE
Plugin Freeze Up

### ISSUE THREAD

**Issue by TristenFielding** [microsoft/vscode-pull-request-github#6250]
When the plugin calls GitHub to load the next set of changes, it appears to freeze for several minutes before finally showing the next file.

It would create a better UX if the indeterminate status (shown at the top of the plugin during the first load) was used to indicate that the plugin is busy and not frozen.

**Comment by alexr00** [comment]
First, thank you for taking the time to file all these issues!

> When the plugin calls GitHub to load the next set of changes

Can you share exactly what you're doing when this happens?

**Comment by alexr00** [comment]
Closing because no further info was provided.
