### ISSUE TITLE
Resolve Conversation Button not work

### ISSUE THREAD

**Issue by TristenFielding** [microsoft/vscode-pull-request-github#6252]
Version: 1.93.1 (system setup)
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
Date: 2024-09-11T17:20:05.685Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.19045
Steps to Reproduce:

1. Start a new Review
2. Create a comment and click on Add Review Comment.
3. Finish the Review
4. Externally, resolve the comment
5. Refresh the plugin
6. open the comment
7. Click on the Resolve Conversation button
    1. Actual Results: 
        1. Check GitHub - notice that it wasn't resolved.
        2. The GUI didn't change. 
    3. Expected Results: 
        1. GitHub is notified about this resolution.
        3. The comment icon should change to something different - like: <img width="13" alt="image" src="https://github.com/user-attachments/assets/325deb91-1330-45a5-a04a-e8da90533f0b">
        4. The "Resolve Conversation" button should either be disabled or changed to "Unresolve Conversation" and perhaps show a green check mark and/or a "Resolved" label at the top of the dialog box. Like so:        
<img width="514" alt="image" src="https://github.com/user-attachments/assets/6037affa-ab62-454b-8989-bc5eb923296c">

**Comment by alexr00** [comment]
The only part of this I can reproduce is that using the "refresh" button on the active PR view doesn't refresh the comments.
