### ISSUE TITLE
Extension should ignore gist.github repositories

### ISSUE THREAD

**Issue by Ash258** [microsoft/vscode-pull-request-github#626]
- Extension version: 0.2.1
- VSCode Version: Code - Insiders 1.29.0-insider (5d68db08cda5accef740c69541178911b865d069, 2018-10-26T05:19:44.837Z)
- OS: Windows_NT x64 10.0.17134

Steps to Reproduce:

1. Clone some gist ([if you dont have one, find some here](https://gist.github.com/discover))
    1. `git clone "git@gist.github.com:7f3b34ad89a159e6daa1.git" "someGist"`
1. Open folder `someGist` with vscode
1. See notification about signing
    ![img](https://i.imgur.com/uxNlVxb.png)
1. When click `Sign In` see 404 error

**Comment by RMacfarlane** [comment]
This should be fixed in the latest version of the extension - we should not prompt for sign in and not try to sign into `gist.github.com`.
