### ISSUE TITLE
How do I actually approve a PR?

### ISSUE THREAD

**Issue by dmrickey** [microsoft/vscode-pull-request-github#6268]
I'm looking at this PR. I've clicked through all of the files and I'm good with the changes. I have no comments for this PR (which I did find how to add by watching the gif in the readme). I looked at the bullet points for each section in the YouTube video but none of them appear to address this question (based on "titles" of the timestamps)--but text is preferable to a video. 

![image](https://github.com/user-attachments/assets/5d641752-0a4e-4315-a7f7-c6a0e92d4b37)

**Comment by alexr00** [comment]
If you open the PR description you can complete your review with an approval from there: 
![Image](https://github.com/user-attachments/assets/ed063777-20fd-484a-86e7-c29d4ba5412a)

**Comment by alexr00** [comment]
Maybe we could show something if we notice that you've marked all files as read.

**Comment by alexr00** [comment]
I haven't gotten other feedback recently that this is hard to find. Closing as wont fix.
