### ISSUE TITLE
Support comment/description revision history

### ISSUE THREAD

**Issue by JeffreyCA** [microsoft/vscode-pull-request-github#627]
1. View previous edits/changes
<img width="779" alt="screen shot 2018-10-26 at 10 25 21 am" src="https://user-images.githubusercontent.com/9157833/47572666-8db23680-d909-11e8-9249-ee532cadfa85.png">

2. View diff

3. Delete revision from history

<img width="661" alt="screen shot 2018-10-26 at 10 25 39 am" src="https://user-images.githubusercontent.com/9157833/47572667-8db23680-d909-11e8-9c23-cdd05da264b6.png">

**Comment by alexr00** [comment]
Reasonable request, but closing as out of scope as we don't intend to address this in the near future.
