### ISSUE TITLE
Long loading times

### ISSUE THREAD

**Issue by joaoKuchnir** [microsoft/vscode-pull-request-github#6271]
The extension takes a long time to load the components and even longer to create a pull request.

This started to happen with the latest vscode update.

![Image](https://github.com/user-attachments/assets/ba4715cf-ff80-4669-82b3-e44757fa7646)

- Extension version: 0.98.0
- VSCode Version: 1.94.1
- OS: Linux manjaro

**Comment by alexr00** [comment]
The activation time seems about the same to me. Do you have other extension installed that could be hogging resources?

**Comment by alexr00** [comment]
Closing because no further info was provided.
