### ISSUE TITLE
Show absolute dates if more than a month ago

### ISSUE THREAD

**Issue by JeffreyCA** [Microsoft/vscode-pull-request-github#631]
Right now all dates/times are shown relative to the current date. It would be nice to have absolute dates (no year) for dates more than a month ago, and absolute dates (with year) for those more than a year old. This is how GitHub currently handles it.

For dates a month or more ago:
<img width="999" alt="screen shot 2018-10-26 at 11 44 41 am" src="https://user-images.githubusercontent.com/9157833/47577519-171b3600-d915-11e8-8876-964a753b5e7f.png">

For dates more a year or more ago:
<img width="991" alt="screen shot 2018-10-26 at 11 44 49 am" src="https://user-images.githubusercontent.com/9157833/47577387-c9063280-d914-11e8-8ce5-c0ea62184379.png">

**Comment by devanshhu** [comment]
Is anyone working on it ? I would like to take it . Would need some guidance though as I am a beginner .

**Comment by JeffreyCA** [comment]
Yes I was working on it, there's a Pull Request up
