### ISSUE TITLE
Test: GHPRI - Notifications view

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode-pull-request-github#6329]
Refs: https://github.com/microsoft/vscode-internalbacklog/issues/5100

- [x] any @TylerLeonhardt
- [x] any @benibenj
- [x] any @rzhao271

Complexity: 4

Authors: @lszomoru, @alexr00, @aiday-mar

[Create Issue](https://github.com/microsoft/vscode-pull-request-github/issues/new?body=Testing+%236329%0A%0A&assignees=lszomoru,alexr00,aiday-mar)

---

This milestone we have added a new Notifications view (experimental) to assist with dealing with GitHub notifications. The new view is powered by VS Code's LLM capabilities to help summarize, and prioritize notifications. 

### Prerequisites
* Install the latest VS Code Insiders release
* Install the latest pre-release of the GHPRI extension
* Set the following settings:
    * `"githubPullRequests.experimental.chat": true`
    * `"githubPullRequests.experimental.notificationsView": true`

### Notifications view
* Launch VS Code Insiders and open a folder/workspace with a GitHub repository
* Switch to the "GitHub Pull Requests" view container
    * Confirm that a "Notifications" view is being shown
* Expand the "Notifications" view is not already expanded     
    * Confirm that a list is being shown containing your unread notifications
 
### Notifications view (actions) 
* Launch VS Code Insiders and open a folder/workspace with a GitHub repository
* Switch to the "GitHub Pull Requests" view container
* Expand the "Notifications" view is not already expanded
* Click on a Notification in the list
    * Confirm that the quick chat widget is opened and the notification is summarized. Review the provided summary.
* Hover over a notification and click on the "Summarize with Copilot" action
    * Confirm that the quick chat widget is opened and the notification is summarized. Review the provided summary.
* Hover over a notification and click on the "Open on GitHub" action 
    * Confirm that the issue/pull request to which the notification belongs is being opened on GitHub
* Hover over a notification and click on the "Mark as Read" action 
    * Confirm that the notification is not shown in the list any more
    * Confirm that the notification is marked as read (you can use https://github.com/notifications to confirm)

### Notifications view (load more)
* Launch VS Code Insiders and open a folder/workspace with a GitHub repository
* Open your user settings and set `"githubPullRequests.experimental.notificationsViewPageSize": 1`
* Switch to the "GitHub Pull Requests" view container
* Expand the "Notifications" view is not already expanded
    * Confirm that the list only contains one notification
    * Confirm that a "Load More Notifications..." item is shown at the bottom of the list
* Click on the "Load More Notifications..." item in the list
    * Confirm that the next notification is loaded

### Notifications view (Prioritize with Copilot)
* Launch VS Code Insiders and open a folder/workspace with a GitHub repository
* Open your user settings and set `"githubPullRequests.experimental.notificationsScore": true`
* Switch to the "GitHub Pull Requests" view container
* Expand the "Notifications" view is not already expanded
* In the view's `...` click on "Sort by Priority using Copilot"
* It will take a bit of time as each notification is being scored and the notifications are reordered
    * Confirm that each notification has a badge with its score
    * Confirm that the notifications are being sorted by scope descending
    * Confirm that hovering over the score shows the reasoning for the score

**Comment by TylerLeonhardt** [comment]
![Image](https://github.com/user-attachments/assets/0f749989-df6e-4308-8e5f-cc8bd5b90cb5)

Currently getting this having Copilot summarize

**Comment by rzhao271** [comment]
I love that the notifications viewlet provides the opportunity to look through notifications from within VS Code!
I know that Tyler filed issues for what I am about to write already, but I would like to reiterate that adding the ability to view read notifications and mark them as Done would greatly increase the functionality and capability of the viewlet, allowing users to go through and clear out their entire inbox from within VS Code.
