### ISSUE TITLE
Auth notification pops up twice on start up

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#633]
When you install and reload to activate the extension, this popup will appear, then dismiss and reappear again:

![notification](https://user-images.githubusercontent.com/2193314/47582373-0238a580-d909-11e8-8673-9d38a3db200b.gif)

Tested on Windows 10, ext v0.2.1

**Comment by RMacfarlane** [comment]
I can no longer repro this issue, this should be fixed in the latest version of the extension 0.12.0
