### ISSUE TITLE
I actually thought the ✅ would "Done" a notification, but it just marks as "Read"

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode-pull-request-github#6336]
Testing #6329

This was a bit confusing for me because the notification page shows a ✔  which "Done"s a notification. ![Image](https://github.com/user-attachments/assets/d1aae90f-5e97-4cc4-ab77-ab7928be1be7)

but it's marking as read here:
![Image](https://github.com/user-attachments/assets/a7541893-2574-4143-aa79-9527dfbc2eb1)

**Comment by alexr00** [comment]
@TylerLeonhardt what if we change the icon?

![Image](https://github.com/user-attachments/assets/07ba8245-aac9-4b23-80a7-c557a0f4c56a)
![Image](https://github.com/user-attachments/assets/0f41e1ef-6a29-4c16-95e3-27cb47fda07b)

Are either of these better?

**Comment by alexr00** [comment]
Looks like GitHub uses the open envelope icon. We should switch to that to align better.

**Comment by TylerLeonhardt** [comment]
Pending latest pre-release
