### ISSUE TITLE
Provide a command to focus the GitHub Pull Requests explorer

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#634]
Currently when I want to review PRs I do this:

1. ctrl+shift+g
2. Click to hide the git pane
3. Click to open the github PR pane
4. Click "All" or "Assigned To Me" (depending on repo)

I'd like to do this:

1. Some custom keybinding to open and focus the PR pane
2. Down to "All" or "Assigned To Me"
3. Right arrow to expand

Related: https://github.com/Microsoft/vscode/issues/58272

**Comment by RMacfarlane** [comment]
Closing this, as there is now a `GitHub: Focus on Pull Requests View` command
