### ISSUE TITLE
Add a `prepareInvocation` for summarize notification tool

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#6340]
Looks like I missed this one.

![Image](https://github.com/user-attachments/assets/d4cfd9b7-48c6-4621-ba60-03f303447312)

**Comment by eleanorjboyd** [comment]
What is the expected outcome here? Seeing this when I searched:

![Image](https://github.com/user-attachments/assets/f5fcd103-57e6-44e8-91f9-c32677e64f6f)

**Comment by TylerLeonhardt** [comment]
It's the `Fetching item #... ` text
![Image](https://github.com/user-attachments/assets/50179fb5-df63-403c-8018-ce04cccbaef4)

**Comment by aiday-mar** [comment]
The prepare invocation text is there as expected. But the notification summary is not correct, investigating.
