### ISSUE TITLE
Showing notification of different repository, but clicking on it causes an error

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode-pull-request-github#6341]
Testing #6329

I was in the `vscode-commander` repository and saw a notification from the `vscode` repository. Clicking on it caused an error s can be seen bellow.

![Image](https://github.com/user-attachments/assets/8c27f077-e359-4dce-a325-e8b3bc37de4c)

**Comment by benibenj** [comment]
I clicked on it again a couple minutes later and it worked

![Image](https://github.com/user-attachments/assets/acf21c1f-e7ad-4f97-8572-833f12dea16c)

**Comment by aiday-mar** [comment]
So from what I know, to summarize a notification, the corresponding repo should be resolved in the FolderManager. In your case you were in the vscode-commander repository and trying to summarize a notification from the vscode repo, which was not resolved, hence the error. I think this should be fixed as generally you should be able to resolve any notification. It seems like fixing this will require rewriting the folder manager logic, so perhaps we should push this out to the november milestone.

**Comment by alexr00** [comment]
I think I fixed this yesterday! Would you mind trying again?

**Comment by alexr00** [comment]
Closing for verification.

**Comment by rzhao271** [comment]
It doesn't error, but it doesn't seem to give a summary either
![Participant responds with Got it and asks for more instructions as needed](https://github.com/user-attachments/assets/0f4b9a6e-b65e-46f5-82ea-70458d22c730)

**Comment by aiday-mar** [comment]
Something is wrong, I will have a look at this.

**Comment by aiday-mar** [comment]
should be fixed with the PR https://github.com/microsoft/vscode-pull-request-github/pull/6421
