### ISSUE TITLE
PR chat participant: Fails trying to list my issues

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-pull-request-github#6342]
Testing #6321

The query seems to contain `<del>`?

![Image](https://github.com/user-attachments/assets/1e289880-95e8-4627-9b73-b5b21f3098f0)

**Comment by aiday-mar** [comment]
This seems to be related to the search issues tool. More specifically looking at the query in the grey message, it would seem the query contains the <del> tag which is not correct. Pinging @alexr00 about it.

**Comment by alexr00** [comment]
Wow, it's the `~info-needed` label. The `~` is the `<del>` tag in markdown.
