### ISSUE TITLE
Message too long

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode-pull-request-github#6343]
Testing #6331

Tried the question `What are my most popular issues?` in a repository with only 16 issues and the model responded with `this message is too long`.

![Image](https://github.com/user-attachments/assets/cc2add8a-ade1-4a73-a22a-38faf17f48e8)

**Comment by alexr00** [comment]
Worked around by https://github.com/microsoft/vscode-pull-request-github/pull/6349#pullrequestreview-2384704973, new pre-release on it's way.

**Comment by alexr00** [comment]
New pre-release with the work around is available.

**Comment by anthonykim1** [comment]
![Image](https://github.com/user-attachments/assets/9e519019-15f2-4ca0-94b8-00db5513f5f9)
I think this is working now. Tried in vscode repo.
