### ISSUE TITLE
Issue summarization does not include info about different authors

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-pull-request-github#6345]
Testing #6321

The comments section in the example below summarizes the back and forth of the conversation well, but it misses an indication who the authors where, so it is not clear that this was a conversation between multiple authors and who brought up which arguments.
![Image](https://github.com/user-attachments/assets/a2f4b0a5-3aa2-4d42-a074-444b2e38866e)

**Comment by aiday-mar** [comment]
With PR https://github.com/microsoft/vscode-pull-request-github/pull/6389 the summarization looks as follows: 

![Image](https://github.com/user-attachments/assets/7fc62935-ff80-4894-81a1-23e785ec4c7c)
