### ISSUE TITLE
Fix with Copilot: Promising too much?

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-pull-request-github#6355]
Testing #6321

It didn't come up with valid fixes for the few real world examples I used it with. Maybe it could instead try to identify the relevant source files and try to explain what might be going wrong. That might then help a user new to the code get into it.

**Comment by lszomoru** [comment]
Agree that "Fix" may set the incorrect expectations with the user but I think that this is a general problem with any feature that is driven by an LLM. Is there an established for such actions in the Copilot Chat extension? Should we use "Try to fix" or "Suggest a fix" or something along these lines?
