### ISSUE TITLE
Commit hash in comment panel looks like part of the path

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#636]
![image](https://user-images.githubusercontent.com/2193314/47582802-437d8500-d90a-11e8-8572-f325ad862947.png)

One of these would be better imo:

- `src (43e9911)`
- `43e9911 - src`
- `(43e9911) src`

Also normally the commit is shorted to 7 characters, not 8 (the description page shows 7 currently)

**Comment by alexr00** [comment]
Closing as it isn't possible to fix this with the current VS Code resource formatter contribution point.
