### ISSUE TITLE
Redundant information in the markdown table

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode-pull-request-github#6361]
Testing #6331

**prompt:** @githubpr How many issues are closed with the tree view label

**table:**

![Image](https://github.com/user-attachments/assets/02010b08-34e4-485b-880f-82754e6d4fd8)

I asked it for closed issues, so I would not expect to see that in the table. Similarly, I asked it to use a specific label and it did not render it in the table (this is the expected behaviour)

**Comment by lszomoru** [comment]
@alexr00, could you try to suggest a nowrap for the number and state columns?
