### ISSUE TITLE
Inaccurate result when asking for authored issues

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode-pull-request-github#6362]
Testing #6331

I cloned electron/electron and asked "`@githubpr` What are some issues I authored in the repo??"
Expected: `repo:electron/electron is:issue author:@me sort:updated`
Actual: `repo:electron/electron is:issue author:@me sort:updated authored` with no results found.

**Comment by alexr00** [comment]
Fixed by https://github.com/microsoft/vscode-pull-request-github/pull/6393

**Comment by rzhao271** [comment]
Does not seem to be fixed
![vscode repo showing same issue as above](https://github.com/user-attachments/assets/8c918e6a-2e46-402e-875e-891fbe60c34f)

**Comment by rzhao271** [comment]
It turns out the participant can't handle the actual response in the first place, so I'm unsure whether this issue is out of scope.
![response too long once it gets the query right](https://github.com/user-attachments/assets/0920d330-fc5b-43a7-8973-c7e06c5d3ec7)

**Comment by alexr00** [comment]
My fix was to try to remove `authored` from the search that got generated, and that clearly failed.
