### ISSUE TITLE
Error about microsoft/vscode when current open folder is electron/electron

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode-pull-request-github#6365]
Testing #6331

I have electron/electron checked out and open. I searched `@githubpr most critical issues assigned to deepak1556 but do not show the assignees column` and got back the response `No folder manager found for microsoft/vscode. Make sure to have the repository open.`

**Comment by alexr00** [comment]
Is it possible that you tried to make the request before the extension was activated?

**Comment by rzhao271** [comment]
Cannot repro now
