### ISSUE TITLE
Asking to hide the number column results in number being undefined for all entries

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode-pull-request-github#6369]
Testing #6331

With electron/electron open, I asked `@githubpr most popular issues in this repository sorted by created date descending but with the title and number columns hidden` and got the query `repo:electron/electron is:issue sort:created`. The chat participant then displayed the first ten results with the columns number, labels, state, and created At. For all shown bugs, the number said `undefined` but was actually a link that pointed to the proper issue on GitHub. It sorted the issues by created date in descending order, at least.

**Comment by alexr00** [comment]
That's funny, I always add in the number column and make it a link, but in this case that back fires.
