### ISSUE TITLE
Fetching local pull requests failed: this.repository.getRefs is not a function

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode-pull-request-github#6373]
- Extension version: v0.99.2024102213 (pre-release)
- VSCode Version: 1.95.0-insider
- OS: Web
- Repository Clone Configuration (single repository/fork of an upstream repository): https://insiders.vscode.dev/github/microsoft/vscode
- Github Product (Github.com/Github Enterprise version x.x.x): github.com

Steps to Reproduce:

1. Open the PR viewlet.
2. The error notification "Fetching local pull requests failed: this.repository.getRefs is not a function" shows up.

**Comment by alexr00** [comment]
Wow, no one has tried to view local PR branches on vscode.dev ever.
