### ISSUE TITLE
unable to get copilot to search with a specific label

### ISSUE THREAD

**Issue by eleanorjboyd** [microsoft/vscode-pull-request-github#6375]
Testing #6331

I wanted to find out:  what are issues with the label area-testing that are not assigned to me?
and I explicitly included "label" and the correct name of an existing label "area-testing" but it still didn't look for that label instead just included it in the search. Additionally it didn't understand the "not assigned to me" and added no search criteria for that

https://github.com/issues/?q=repo%3Amicrosoft%2Fvscode-python%20is%3Aissue%20sort%3Aupdated%20%20area-testing

![Image](https://github.com/user-attachments/assets/fea4646f-f994-4193-8c91-043d8bdbb6ad)

**Comment by eleanorjboyd** [comment]
tried these ways too:
![Image](https://github.com/user-attachments/assets/27346125-ff52-409e-9870-adc2fb6c5124)
![Image](https://github.com/user-attachments/assets/068a0b57-9645-4035-b183-2c7be1eaf86e)

**Comment by alexr00** [comment]
I can't repro the missing label, but I can see the missing `-assignee:@me`.
