### ISSUE TITLE
status message for table streaming

### ISSUE THREAD

**Issue by eleanorjboyd** [microsoft/vscode-pull-request-github#6376]
Testing #6331

I liked the status messages that told me it was getting the query and added a link to the query but then I felt like I sat there for a minute waiting for the table to be outputted and then rendered. I even looked to see if the query was still running or if it had errored out but the answer being it was still running. I would have loved a message like "streaming in and formatting issue table" or something so I knew why it was taking so long.

**Comment by alexr00** [comment]
We do have this, but unfortunately the part that's slow here happens outside of the markdown table tool. The llm is extremely slow to _decide_ to call the markdown table tool. While it's trying to figure out that out, you just get the "Generating..." animation:

![Image](https://github.com/user-attachments/assets/e83ae093-3e85-4c30-8e32-b86e0a953a62)

As soon as the markdown table tool is called, you get the status message:

![Image](https://github.com/user-attachments/assets/c73baa65-40c6-4fc0-9774-87e5e0613a1d)
