### ISSUE TITLE
Unexpected chat message content type when running other tools in participant

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#6379]
We don't limit the tools we use in our chat participant, which means that we could run tools that use prompt-tsx.

**Comment by rzhao271** [comment]
@alexr00 what are some verification steps for this issue?

**Comment by alexr00** [comment]
To verify:
1. Install pre-release of GHPR, VS Code Commander, and Copilot Chat
2. In the chat view: `@githubpr Open the file explorer view`
3. Verify that there are no errors (arguably, it should say "I can only help with GitHub stuff", but this bug was just about making sure there are no errors).
