### ISSUE TITLE
Empty comments should be dismissed automatically when another comment is made

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#638]
Repro:

Open a comment, leave it empty:

![image](https://user-images.githubusercontent.com/2193314/47584029-e71c6480-d90d-11e8-9289-a207cf8c4b28.png)

Click to make another comment:

![image](https://user-images.githubusercontent.com/2193314/47584056-f69bad80-d90d-11e8-8c5b-eb09cac5762c.png)

I expect it to dismiss that automatically as it has no content.

**Comment by alexr00** [comment]
No longer repros.
