### ISSUE TITLE
Unable to open PR editor: Cannot read properties of undefined (reading 'toLowerCase'

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-pull-request-github#6385]
Version: 1.95.0-insider
Commit: fe997185b5e6db94693ed6ef5456cfa4e8211edf
Date: 2024-10-23T05:06:13.568Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Linux x64 5.15.0-124-generic

GHPR extension: v0.99.2024102304 (pre-release)

- open branch 'digitarald/primary-meerkat` in the copilot repo
- click on the 'Pull Request #9261'. Editor starts opening, but no content. Error nortification: 'Cannot read properties of undefined (reading 'toLowerCase''
- I don't find any stack traces in the dev tools or logs

**Comment by aeschli** [comment]
Reproduces on both Linux and Windows

**Comment by alexr00** [comment]
Thank you for sharing the repo+branch!

**Comment by bhavyaus** [comment]
Tried this on a few different prs from various repos.

**Comment by alexr00** [comment]
Fix was not yet released, and that specific PR should be tested as there is something different about it.

**Comment by rzhao271** [comment]
When I check out PR #9261 by number, I get a notification saying "The remote branch for this pull request has been deleted. The file contents may not match the remote."

Is this enough for verification, or do we have to find or create another PR to test?

**Comment by alexr00** [comment]
That's enough to verify, thank you!
