### ISSUE TITLE
Getting reading `length` of undefined when summarizing notifications

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode-pull-request-github#6423]

**Comment by aiday-mar** [comment]
fixed by https://github.com/microsoft/vscode-pull-request-github/pull/6421

**Comment by TylerLeonhardt** [comment]
@aiday-mar can we have some verification steps?

**Comment by aiday-mar** [comment]
Hi @TylerLeonhardt apologies I didn't respond earlier. I was OOF yesterday. Thanks @rzhao271 for verifying.
