### ISSUE TITLE
Sugestão: Adicionar Convensão de commits no Guia de Contribuição.

### ISSUE THREAD

**Issue by Roniv18** [microsoft/vscode-pull-request-github#6425]
**Sua sugestão está relacionada a um problema? Por favor descreva.**
N/A.
**Descreva a solução que você gostaria**
Adicionar informações referentes a padronização das mensagens dos commits no [Guia de Contribuição](https://github.com/digitalinnovationone/dio-lab-open-source/blob/main/CONTRIBUTING.md).

**Descreva as alternativas que você considerou**
Inserir uma tabela demonstrando os tipos de commits e uma declaração à respeito do seu uso.

**Contexto adicional**
N/A.

**Comment by Roniv18** [comment]
Foi difícil chegar até aqui, porém está sendo muito gratificante, estou encarando como uma excelente oportunidade! MUITO OBRIGADO ELI E A DIO.

**Comment by Roniv18** [comment]
Foi difícil chegar até aqui, mas está sendo uma excelente oportunidade de aprendizagem! MUITO OBRIGADO ELI e DIO...

**Comment by alexr00** [comment]
Could you please provide an English translation?
