### ISSUE TITLE
"The current repository does not have a push remote" after repo rename

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-pull-request-github#6427]
Type: <b>Bug</b>

I previously cloned `microsoft/vscode-websearchparticipant`, now it's renamed to `microsoft/vscode-websearchforcopilot`, and I get this error when trying to create a PR. I assume it's related to the repo rename.

```
$ git remote -v
origin  git@github.com:microsoft/vscode-websearchparticipant.git (fetch)
origin  git@github.com:microsoft/vscode-websearchparticipant.git (push)
```

![Image](https://github.com/user-attachments/assets/ee4783cc-21d6-4bc3-bee7-b29695a031e7)

I can "publish branch" with no problem.

Extension version: 0.99.2024102513
VS Code version: Code - Insiders 1.95.0-insider (c0f27916ad81d8de78b62bd0aa0eab3f8cd99178, 2024-10-25T09:02:38.980Z)
OS version: Darwin arm64 24.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 Max (14 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|5, 4, 4|
|Memory (System)|36.00GB (0.07GB free)|
|Process Argv|--log vscode.git=trace --log github.copilot-chat=trace --crash-reporter-id fb555057-0224-46cf-bd9a-23995ec9a069|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
vscod805:30301674
vsaa593:30376534
py29gd2263:31024238
c4g48928:30535728
2i9eh265:30646982
962ge761:30841072
pythongtdpath:30726887
pythonnoceb:30776497
asynctok:30898717
dsvsc014:30777825
dsvsc015:30821418
pythonmypyd1:30859725
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:30980852
pythonait:30973460
f3je6385:31013174
dvdeprecation:31040973
dwnewjupytercf:31046870
nb_pri_only:31057983
nativerepl1:31134653
refactort:31084545
pythonrstrctxt:31093868
wkspc-onlycs-t:31132770
nativeloc1:31118317
wkspc-ranged-t:31151552
cf971741:31144450
e80f6927:31120813
autoexpandse:31146404
i21gd607:31141543
iacca1:31150324
notype1:31143044
dwcopilot:31158714
g7688163:31155431

```

</details>

**Comment by alexr00** [comment]
I think this can only happen if you rename the repo, then don't reload VS Code. This seems pretty rare, and will be fixed by a reload. Closing as wont-fix.

**Comment by stephenfuqua** [comment]
I encountered this error today in a repo for which I have three remotes setup. I had pushed my branch to `origin` from the command line before using the GitHub Pull Request extension. Resolved the problem by using VS Code / Git extension to also push the branch - doing so forced me to select a remote first. Now the PR request knew which remote to use, and it worked fine.
