### ISSUE TITLE
Only color is used to differentiate between various links present on "Description" screen with surrounding text: A11y_Visual Studio Code Web Extensions_Github Pull request_Description_Use Of Color

### ISSUE THREAD

**Issue by Rama8345** [microsoft/vscode-pull-request-github#6452]
### GIT Hub Tags:
#A11yTCS; #A11ySev3; #Visual Studio Code Web Extensions; #BM_Visual Studio Code Web Extensions_Web_Oct2024; #DesktopWeb; #A11yMAS; #WCAG1.4.1; #UseOfColor; #Win11; #Chrome; #FTP;

### Environment and OS details:
Application name: Visual Studio Code Web Extensions
Chrome Version: Version 130.0.6723.92 (Official Build) (64-bit)
URL: https://insiders.vscode.dev/github/microsoft/vscode-pull-request-github

### Reproduction Steps:

1. Open url https://insiders.vscode.dev/github/microsoft/vscode-pull-request-github environment and login with git hub account.
2. TAB to 'Github Pull request' and press enter.
3. TAB to "All open" control and hit ENTER.
4. TAB to "Description" control and hit ENTER.
5. TAB to "adding code" link.
6. Observe the issue whether Only color is used to differentiate between various links present on "Description" screen with surrounding text or not.

### Actual behavior:
Only color is used to differentiate between various links present on "Description" screen with surrounding text.

### Expected behavior:
There should be at least two ways to differentiate links with surrounding text so that users with color blindness will also be able to differentiate links with surrounding text.

### User Impact:
Color blindness users will not be able to differentiate links with surrounding text if only color will be used to differentiate them.

### Attachment:
![Image](https://github.com/user-attachments/assets/58299135-2521-475e-b969-e342f8dc57cb)

**Comment by alexr00** [comment]
This is by design. You can set `"accessibility.underlineLinks": true` to have underlines on links.
