### ISSUE TITLE
Allow "Create Pull Request Suggestions" to submit suggestions directly instead of Pending suggestions

### ISSUE THREAD

**Issue by sdevilliers** [microsoft/vscode-pull-request-github#6458]
It would be nice if there was a button like "Create Pull Request Suggestions" but instead of creating "Pending" comments, it would actually submit the comments.

![Image](https://github.com/user-attachments/assets/583fd75b-843a-4078-a08e-ab714b478803)

![Image](https://github.com/user-attachments/assets/59277908-64f6-47fe-9278-59f9b313f8cc)
This is the button I am referring to ^

I have had a lot of issues where I have been unable to convert the pending suggestions to actual suggestions. Maybe it has something to do with [this bug](https://github.com/microsoft/vscode-pull-request-github/issues/1317) in any case I would rather submit the changes directly instead of creating pending ones.

It would be nice if it could use the commit message or ask for a message that could be used to identify the batch of suggestions that was submitted

**Comment by alexr00** [comment]
> unable to convert the pending suggestions to actual suggestions

Can you share a bit more about this? Is this the right flow?
- Check out the PR
- Change the code
- Hit the "Create Pull Request Suggestions" button
- "Pending" comments get created
- What happens when you try to submit the review?

**Comment by alexr00** [comment]
I fixed the issue with suggestions that would get stuck pending. It's available in the lastest release.
