### ISSUE TITLE
Fail to delete local pull request branch

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode-pull-request-github#646]
- Extension version: 0.2.1
- VSCode Version: 1.29 Insiders
- OS: Windows 10

```
Deleting local pull request branch failed: Failed to execute git {
  "exitCode": 1,
  "gitErrorCode": "BranchNotFullyMerged",
  "gitCommand": "branch",
  "stdout": "",
  "stderr": "error: The branch 'rmacfarlane/description-edit' is not fully merged.\nIf you are sure you want to delete it, run 'git branch -D rmacfarlane/description-edit'.\n"
}
```

**Comment by RMacfarlane** [comment]
Before we moved to using the git extension API, we were using the '-D' flag to always delete even if the branch hadn't been fully merged

**Comment by RMacfarlane** [comment]
Fixed with https://github.com/Microsoft/vscode-pull-request-github/commit/a6b1d0c772961a63b568a0116ed53fbc3bd6f79e
