### ISSUE TITLE
Cannot view or create review comments for PR

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/vscode-pull-request-github#6464]
- Extension version: 0.101.2024110711
- VSCode Version: 1.96.0-insider (4a98be2738be4ad8647feb52d1e6845e06515dea, 2024-11-08T09:56:49.748Z)

- OS: Windows 11 23H2
- Repository Clone Configuration (single repository/fork of an upstream repository): fork of upstream repo
- Github Product (Github.com/Github Enterprise version x.x.x): Github.com

Steps to Reproduce:

1. Open file changed in PR, add and then try to save a comment
2. Error notification appears "Creating comment failed: Error: GraphQL error: Fragment ReviewComment was used, but not defined"

In logs:
```
2024-11-08 17:00:51.377 [error] GitHubRepository+0> Error querying GraphQL API: GraphQL error: Fragment ReviewComment was used, but not defined. useAndDefineFragment
2024-11-08 17:00:51.881 [error] GitHubRepository+0> Error querying GraphQL API: GraphQL error: Fragment ReviewComment was used, but not defined. useAndDefineFragment
2024-11-08 17:00:51.881 [error] PullRequestModel> Failed to get pull request review comments: Error: GraphQL error: Fragment ReviewComment was used, but not defined
```

I was thinking it was duplicate of #6441 but that one verified as fixed, and commenting worked fine for me on Nov 6 (2 days ago, before that fix)

**Comment by marty0678** [comment]
Also getting this same error as of today.

**Comment by basicdays** [comment]
Same here, tried to use latest release and pre-release version with same error result.

**Comment by amirreza-asadzadeh** [comment]
Same here, getting exactly the same error. It just happened today and was working fine yesterday.

**Comment by janakjjp** [comment]
I'm getting something very similar:

![Image](https://github.com/user-attachments/assets/5e77570f-56c9-4465-8070-ff065dc1dfe3)

@alexr00 seems to be one more regression in the new release (either v100 or v100.1)

**Comment by arvindh123** [comment]
![Image](https://github.com/user-attachments/assets/a5ecfcd5-52c6-44de-baf1-6ff8659aed84)

I’m also encountering the same error since today.

**Comment by JordanAlanMak** [comment]
Same exact issue/error since yesterday.

**Comment by aayushchugh** [comment]
Same problem

![Image](https://github.com/user-attachments/assets/3e657e91-3f10-4fd6-8b23-6e888d1b646d)

**Comment by kyzinatra** [comment]
+ same problem

**Comment by bibullo** [comment]
same issue

**Comment by akr99799** [comment]
Same issue

**Comment by BenGale** [comment]
Same as #6467

**Comment by albiosz** [comment]
Same issue

**Comment by nguyenlc1993** [comment]
Same issue

**Comment by YashBhardwajAdpushup** [comment]
getting same issue

**Comment by sdevilliers** [comment]
Same issue. Upvote

**Comment by bverhoeve** [comment]
I have the same problem, I tried to go back to `0.100` but then I get another error:
![Image](https://github.com/user-attachments/assets/6de2cc20-cd4d-4192-87fc-bdd19365209c)

**Comment by pedro-mass** [comment]
> I have the same problem, I tried to go back to `0.100` but then I get another error: ![Image](https://github.com/user-attachments/assets/6de2cc20-cd4d-4192-87fc-bdd19365209c)

`0.98.0` worked for me

**Comment by sanderegg** [comment]
same

**Comment by beicause** [comment]
`0.100.0` worked for me (arch linux).

**Comment by gokulk16** [comment]
same issue here as well.

**Comment by gokulk16** [comment]
`0.100` worked. (mac silicon)

**Comment by tim-lucera** [comment]
Same here, rolled back to 0.100.0 and the problem doesn't happen

**Comment by ipg0** [comment]
Same issue on Arch

**Comment by samnbd** [comment]
Same issue for me...

**Comment by CarlosAlfaroSyneos** [comment]
The same issue, rolled back to 0.100.1 worked on Mac intel

**Comment by rivaser** [comment]
I had same issue on Windows 11 Pro

![Image](https://github.com/user-attachments/assets/b81bf634-a6fb-4e57-8a2a-df7c93d43bef)

I had to go back to version 0.100.0
![Image](https://github.com/user-attachments/assets/ffd5846f-6b45-4d48-97dc-9522d387e4ba)
