### ISSUE TITLE
File-level comments expand on navigation to the file despite `collapseAll`

### ISSUE THREAD

**Issue by MetRonnie** [microsoft/vscode-pull-request-github#6465]
- Extension version: v0.100.0
- VSCode Version: 1.95.1
- OS: Windows_NT x64 10.0.19045 / Linux x64 5.14.0-427.40.1.el9_4.x86_64
- Repository Clone Configuration (single repository/fork of an upstream repository): It's a clone with both the original repo and personal fork as remotes
- Github Product (Github.com/Github Enterprise version x.x.x): github.com

Steps to Reproduce:

1. Set vscode://settings/githubPullRequests.commentExpandState to `collapseAll` (I did this a long time ago)
2. When reviewing a PR with a (resolved) file-level comment, navigating to that file always expands the comment

https://github.com/user-attachments/assets/0906e87a-6db7-42a3-adb7-ef77a71a3925

This appears to be the same issue as #5512 but was not fixed in #5540, or is a regression?

**Comment by MetRonnie** [comment]
Additional context: this is happening on a PR that has >100 comments already

**Comment by alexr00** [comment]
File level comments can be a bit difficult to find, so we always expand them. I'll change it.
