### ISSUE TITLE
Create Issue in VSCode does not honor the GH Issue Templates configured in .github/ISSUE_TEMPLATE

### ISSUE THREAD

**Issue by askpatrickw** [microsoft/vscode-pull-request-github#6466]
GitHub Pull Requests  v0.100.1 
VSCode: Latest insiders
MACOS: Sequioa

Steps to Reproduce:

1. Click Create Issue

You get a template which is not one that is configured in .github/ISSUE_TEMPLATE. 

This leads to a lack of consistency, creates confusion and re-work.

#1792  may have regressed.

**Comment by alexr00** [comment]
You should be getting a picker. What do you see instead?

![Image](https://github.com/user-attachments/assets/48f67dc6-b366-4769-8b3f-aa49e9dc3834)

**Comment by alexr00** [comment]
Closing because no further info was provided.

**Comment by askpatrickw** [comment]
I get no picker, it just goes right to this template.



```markdown
Issue Title

Assignees: 
Labels: 
Milestone: 
Projects: 



<!-- Edit the body of your new issue then click the ✓ "Create Issue" button in the top right of the editor. The first line will be the issue title. Assignees and Labels follow after a blank line. Leave an empty line before beginning the body of the issue. -->
```

**Comment by alexr00** [comment]
@askpatrickw is your repo public, and if so can you share a link?

**Comment by askpatrickw** [comment]
Private repo. Sorry.
