### ISSUE TITLE
Can't start a review from a comment due to GraphQL error

### ISSUE THREAD

**Issue by yoavbls** [microsoft/vscode-pull-request-github#6467]
When starting a review from a comment:

<img src="https://github.com/user-attachments/assets/d7dd59fc-995b-449f-9ed4-e1613a8f414b" width="600px" />

A GraphQL error appears:
<img src="https://github.com/user-attachments/assets/5888f10c-3125-4a27-b7ef-07dba62f1b7e" width="250px" />

```
2024-11-09 22:52:00.572 [error] GitHubRepository+0> Error querying GraphQL API: GraphQL error: Fragment ReviewComment was used, but not defined. useAndDefineFragment
2024-11-09 22:52:00.572 [error] PullRequestModel> Failed to get pull request review comments: Error: GraphQL error: Fragment ReviewComment was used, but not defined
```

I thought it related to this: https://github.com/microsoft/vscode-pull-request-github/issues/6441 but it happens also in the pre-release version

- Extension version: v0.100.1
- VSCode Version:  1.95.2 
- OS: macOS
- Repository Clone Configuration (single repository/fork of an upstream repository): Private repository
- Github Product (Github.com/Github Enterprise version x.x.x): Github.com

Steps to Reproduce:

1. Write a comment
2. Click on "Start Review"

**Comment by yoavbls** [comment]
Update: it also affects the load of existing comments.
Everything is fine in the version of November 5 so I think it is this change that moves the fragment out of reach of the query: https://github.com/microsoft/vscode-pull-request-github/commit/843497347738856383fa5e7c93470de7ec6c5f51

**Comment by valajczech** [comment]
Yup I have the same problem

**Comment by christianvari** [comment]
Same issue

**Comment by DavidLangva** [comment]
same. I also can't leave one off comments

**Comment by michel-smarticket** [comment]
Same

**Comment by YashBhardwajAdpushup** [comment]
same

**Comment by koliyo** [comment]
Workaround, rollback to older version locally: Right click the extension in the marketplace tab, select "Install Specific Version", and pick `v0.100.0`.

**Comment by jpomfret** [comment]
I have the same issue - confirmed the workaround works for me.

**Comment by tristanbiesecker** [comment]
Same problem for me as well. [Workaround](https://github.com/microsoft/vscode-pull-request-github/issues/6467#issuecomment-2467542338) fixed it.

**Comment by jacobharrison93** [comment]
Same problem for me as well

**Comment by JoeLyga** [comment]
Same problem. The workaround avoids the issue.

**Comment by ian-blankinship-FHR** [comment]
Same problem for me.

**Comment by assafmo** [comment]
Rolling back to `v0.100.0` fixed it, thanks @koliyo!

**Comment by Shamik-07** [comment]
Add me to this list as well 

![Image](https://github.com/user-attachments/assets/6a5d8b1d-2bb4-4c68-a9f4-1e9374e77f40)

**Comment by dwillhelm** [comment]
Same

**Comment by Shamik-07** [comment]
> Rolling back to `v0.100.0` fixed it, thanks [@koliyo](https://github.com/koliyo)!

This works for now

**Comment by pelord** [comment]
Rolling back to v0.100.0 fixed it.

**Comment by sg-tanner** [comment]
Rollback noted, just wanted to add that for weeks now I have had trouble with the extension in general loading the files changed when trying to expand the PR in the "Requests" pane. Wondering if this is related. Because I tried to skip the loading issue by right clicking the PR and selecting "Checkout pull request"

**Comment by baruchiro** [comment]
It's the same in review mode on the browser. Can revert to the previous version there

**Comment by gihankarunarathne** [comment]
![Image](https://github.com/user-attachments/assets/015f66ac-fbcd-4f14-9400-6ff44076b50f)
Facing the same issue when trying to add a comment.

Need quick support!

**Comment by UrielZohar** [comment]
BE CAREFUL WITH DOWNGRAD THE EXTENTION YOU WILL LOSE THE COMMENTS YOU ALREDY WROTE

**Comment by BenGale** [comment]
When I was running into the issue it looked like those comments are gone anyway, they never get through to GitHub.

**Comment by pereyra-m** [comment]
Same here

**Comment by patricio-hondagneu-simplisafe** [comment]
Experiencing the same issue. Installing version `v0.100.0` fixes it so it appears to be a regression.

**Comment by rubenarturopj** [comment]
Same issue

**Comment by ysuzuki19** [comment]
## temporary solution

1. If you have failed comment locally, you should memo it.
2. Open `Extensions` (Ctrl+Shift+X)
3. Find `GitHub Pull Requests`
4. Open pull-down on `Uninstall` button
5. Select `Install Specific Version...`
6. Select `0.100.0`
7. Client `Restart Extensions`

**Comment by joaomoreno** [comment]
Thanks @ysuzuki19 for providing steps for a workaround for the time being. We will release a fixed version early next week.

**Comment by arjentraas** [comment]
Rolling back to a previous version doesn't work for me. Using VSCode in WSL.

**Comment by klausbadelt** [comment]
Downgrading is not an option in GitHub Codespaces - "Install Specific Version..." is disabled for this extension. 

Revewing PRs in Codespaces is therefore 100% broken, with no workaround.

![Image](https://github.com/user-attachments/assets/a325327b-9db8-4946-9dd9-46fa4e4c1c13)

**Comment by klausbadelt** [comment]
Hi @alexr00 - since all PR reviews are broken in Codespaces, without any workaround (posted here), could this get a priority boost?

**Comment by bmlaw** [comment]
GitHub Education user: Now we are unable to leave feedback on any of our students' work, since the GitHub Education feedback mechanism is through a pull request. It's the middle of November. This is not a good time to not be able to leave feedback on any of our students' work.

**Comment by michaelk-redis** [comment]
Same issue for me. Roll back to 0.100.0 version helps.

**Comment by rahul-rzp** [comment]
If we review on `https://github.dev/`, then its not possible to install a specific version.

**Comment by alexr00** [comment]
Fixed by https://github.com/microsoft/vscode-pull-request-github/pull/6481. New release coming out in just a few minutes.

**Comment by faenuccio** [comment]
Worked here as well, downgraded to previous version.

**Comment by petemill** [comment]
github.dev is still not updated

**Comment by andrew-reeman-sf** [comment]
Seems to be ok on github.dev now
