### ISSUE TITLE
Auth flow is bad on Linux

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#647]
Microsoft/vscode#62184

Tested on a relatively clean 18.04 VM.

Not sure you can do anything about this but, undefined?

![image](https://user-images.githubusercontent.com/2193314/47756401-1fe67180-dc5f-11e8-8f44-66c159301c58.png)

Really long, due to the URL. Buttons are off screen, some people may not know to press the buttons or may be scared to on security grounds?

![image](https://user-images.githubusercontent.com/2193314/47756418-3260ab00-dc5f-11e8-8eb1-6d98517f8b49.png)

I don't want a keyring so I pressed cancel

![image](https://user-images.githubusercontent.com/2193314/47756424-3ab8e600-dc5f-11e8-94c3-62d9f065f364.png)

It still signed in without the keyring?

![image](https://user-images.githubusercontent.com/2193314/47756436-47d5d500-dc5f-11e8-8228-38d96ab72f72.png)

**Comment by Tyriar** [comment]
@queerviolet It should be stored in local storage, never the settings file as many people sync that to the cloud publicly. https://github.com/Microsoft/vscode-pull-request-github/issues/368

I think `vscode.ExtensionContext.globalState` is the API for this.

**Comment by queerviolet** [comment]
Ah, okay, that's reasonable. I'll grab that bug.

**Comment by k1nghat** [comment]
im having this issue as well on kubuntu with chrome. every time i click the 'reload window and open' button it reloads the window from what i can tell and gives me the same message and never resolving:
![image](https://user-images.githubusercontent.com/16073360/49665200-c6b9ec80-fa19-11e8-808d-b7b4dec54a7a.png)
so it obviously has the super wide notification but im not sure how to complete the auth?

**Comment by nicolo-ribaudo** [comment]
I am facing the same problem. After the last VSCode update this extension is asking me to login again, but with xdg it opens a big popup that I am forced to close using Alt+F4. I have read in other issue that there should be a fallback way to login, but the auth page isn't providing it.

**Comment by k1nghat** [comment]
> Auth flow is _really_ bad on Ubuntu. After the last VSCode update this extension is asking me to login again, but with xdg it opens a big popup that I am forced to close using Alt+F4. I have read in other issue that there should be a fallback way to login, but the auth page isn't providing it.
> 
> EDIT: I just have to figure out how to click on the button far outside of my screen (VSCode is fullscreen in this picture)
> ![](https://camo.githubusercontent.com/56a1a302ae93add13aadbaa42b4522d32ce225eb/68747470733a2f2f692e696d6775722e636f6d2f506a337a744b302e706e67)
> 
> EDIT: If anyone is in my situation, click on the white modal, thatn right arrow, right arrow, enter.

this doesnt work for me. i just get in a reload loop unfortunately. unless im misunderstanding what the 'white modal' is? i have KDE as a desktop so there may be a difference there.

**Comment by nicolo-ribaudo** [comment]
I'm on Gnome. Arrow-Arrow-Enter was to "click" on the left button ("Open")

**Comment by nicolo-ribaudo** [comment]
You can try https://github.com/Microsoft/vscode-pull-request-github/wiki#personal-access-token-authentication

**Comment by k1nghat** [comment]
i think @queerviolet fixed this? https://github.com/Microsoft/vscode-pull-request-github/pull/715 will it be in the next release?

**Comment by cardonator** [comment]
I have this issue in 1.30 for sure. Based on the above comment I installed the insiders build and tried it there. And it looks like it will finally work correctly in 1.31 :+1:

**Comment by k1nghat** [comment]
@cardonator thats good to hear!

> Interestingly, once I connected the Insiders build, it also started working on the stable release.

that seems odd.

**Comment by cardonator** [comment]
I think it's because it added some kind of token to my Wallet and the non-insider build can also read that same value.

**Comment by k1nghat** [comment]
can confirm i got auth in new code version out today. still get the super long notification but it works now. tyvm!

**Comment by k1nghat** [comment]
im not sure what happened but it asked me to set a default token? i didnt screenshot that but i did give it a password as requested. now after every reboot its asking me to enter that password. i did install live share and this is when it started happening. i can actually just cancel this popup, twice, and then GH PR logs in fine. did live share bork something with the auth of GH PR?

![screenshot--03-06-2019--13-54-26](https://user-images.githubusercontent.com/16073360/53910212-f8425400-4018-11e9-8843-c037737339b2.png)

**Comment by alexr00** [comment]
Auth has moved into VS Code core.
