### ISSUE TITLE
What are these commands for?

### ISSUE THREAD

**Issue by MrOxMasTer** [microsoft/vscode-pull-request-github#6470]
- Extension version:
- VSCode Version: 1.95.2
- OS: windows 11
- Repository Clone Configuration (single repository/fork of an upstream repository): signle repository
- Github Product (Github.com/Github Enterprise version x.x.x): Github.com

Steps to Reproduce:

![Image](https://github.com/user-attachments/assets/1a0da409-0760-4681-9ca5-7df19fd1d5ef)
![Image](https://github.com/user-attachments/assets/8437c257-740e-4f18-bece-4898e1a34bfc)

Any of these commands, even if I hover over the `issue` in the window of this extension, it doesn't care

![Image](https://github.com/user-attachments/assets/41d7a199-09e7-4a83-a7f7-25e3b682de54)

**Comment by alexr00** [comment]
They're used for the menu items in the issues view. It's not possible to create keyboard shortcuts for tree items like this.
