### ISSUE TITLE
I can't post a comment on a pull request

### ISSUE THREAD

**Issue by Yasuo-Sakai** [microsoft/vscode-pull-request-github#6471]
- Extension version: 0.100.1
- VSCode Version: October 2024 (version 1.95)
- OS: MacOS
- Repository Clone Configuration (single repository/fork of an upstream repository):
- Github Product (Github.com/Github Enterprise version x.x.x):

Steps to Reproduce:

1.I can't post a comment on a pull request
![Image](https://github.com/user-attachments/assets/88b63d87-7e8f-4353-85cf-9c7ed3c250a4)

2.

**Comment by beeb** [comment]
Same here
