### ISSUE TITLE
Have to reload when switching accounts.

### ISSUE THREAD

**Issue by o-l-a-v** [microsoft/vscode-pull-request-github#6472]
It would be great with a dropdown to select what account to use when creating a PR from VSCode if logged in to the GitHub Pull Requests extension with \> 1 account.

Currently one have to:

1. Change default account by going to VSCode ➡️ Extensions ➡️ GitHub Pull Requests ➡️ Manage (⚙️ icon) ➡️ Account preferences.
1. F1 ➡️ ">" ➡️ "Developer: Reload Window"
   * Else "GitHub Pull Requests" extension won't pick up the change.

**Comment by alexr00** [comment]
You shouldn't need to reload. I'll take a look this month.

**Comment by alexr00** [comment]
I can't repro needing the reload.

**Comment by o-l-a-v** [comment]
How I think I was able to repro:

* Try to create PR with wrong account in GitHub Pull Requests, it will fail.
* Change default account by going to VSCode ➡️ Extensions ➡️ GitHub Pull Requests ➡️ Manage (⚙️ icon) ➡️ Account preferences.
* Try to create PR with corrent account, it will fail with the same error.
* Fix: F1 ➡️ ">" ➡️ "Developer: Reload Window"

I don't have time to test this right now, I'll reopen this issue later if I confirm that this still happens.
