### ISSUE TITLE
Add command and shortcut to copy PR link

### ISSUE THREAD

**Issue by albireox** [microsoft/vscode-pull-request-github#6473]
In the PR page it's possible to copy the link to the PR (something like `https://github.com/org/repo/pull/14`). But as far as I can see there is no command to do that from the command palette and it's not possible to assign it a shortcut. This would be very useful when writing change logs. Ideally it would also be possible to copy the link in Markdown, for example `[#14](https://github.com/orgrepo/pull/14)`.

**Comment by alexr00** [comment]
I'll add a command, then you can add your own shortcut.
