### ISSUE TITLE
Clicking on PR description shows error

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode-pull-request-github#6475]
- Extension version: 0.101.2024111304
- VSCode Version: Version: 1.96.0-insider, Commit: 399779942db4d7ab1bd6f6ae976482d0020f10ca , Date: 2024-11-13T05:04:32.098Z
- OS: macOS
- Repository Clone Configuration (single repository/fork of an upstream repository):
- Github Product (Github.com/Github Enterprise version x.x.x):

Steps to Reproduce:

1. Expand PRs "Waiting for my review"
2. Click on Description

![Image](https://github.com/user-attachments/assets/201c336c-ccfd-4d2c-96ea-2cdc90eede49)

**Comment by alexr00** [comment]
I'm not able to reproduce this issue. Do you still see it?
