### ISSUE TITLE
Files changed doesn't properly reflect changes against non base branch

### ISSUE THREAD

**Issue by JohnRDOrazio** [microsoft/vscode-pull-request-github#6479]
Creating a new issue seeing that #5545 was closed, but is not resolved.

I have a `main` branch with the stable, production ready code, which reflects the latest published release.

I have a `development` branch where all of the latest PR's for features and non-security bugfixes are merged.

When I create a new PR from VSCode against the `development` branch, the **files changed** is showing files changed in comparison to the `main` branch, not the `development` branch. Which makes it look scary, and prevents me from continuing to create the PR from VSCode.

See https://github.com/microsoft/vscode-pull-request-github/issues/5545#issuecomment-2479021196 : 

![Image](https://github.com/user-attachments/assets/f5f93e31-f306-476c-9312-f362d8d17420)

All those deleted files were already removed / refactored in the `development` branch. They shouldn't be showing in a PR against the `development` branch.

**Comment by JohnRDOrazio** [comment]
I found a workaround for now, if I switch the base to `main`, then switch the base back to `development`, the **Files changed** then show correctly. They just wasn't picked up right away, as they should be (since the base was automatically detected as `development`).

**Comment by JohnRDOrazio** [comment]
Another thing I noticed, is that after Merging the PR and deleting both local and remote branches, I am automatically brought back to the `main` branch instead of the `development` branch. Perhaps it would make more sense to checkout the base branch for the merge (in this case, `development`) rather than the `main` branch? That way the user / developer is brought back to where he started from when the feature branch was first created.

**Comment by alexr00** [comment]
I just pushed a new fix for https://github.com/microsoft/vscode-pull-request-github/issues/5545, which should also fix this issue. 

Checking out the target branch instead of the default branch is a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/4582
