### ISSUE TITLE
Delete comment dialog should have VS Code as the title

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-pull-request-github#648]
Microsoft/vscode#62184

![image](https://user-images.githubusercontent.com/2193314/47756540-c6327700-dc5f-11e8-8494-ac82099dfd16.png)

Compare to the file delete dialog:

![image](https://user-images.githubusercontent.com/2193314/47756587-f8dc6f80-dc5f-11e8-9dd8-032cac1463fb.png)

**Comment by RMacfarlane** [comment]
Fixed by https://github.com/Microsoft/vscode/commit/adade079ed5099d001ed9fde4281b4f4934bec64
