### ISSUE TITLE
Suggestions end up in unsubmittable pending state

### ISSUE THREAD

**Issue by MetRonnie** [microsoft/vscode-pull-request-github#6494]
- Extension version: v0.100.0
- VSCode Version: 1.95.3 (system setup)
- OS: Windows_NT x64 10.0.19045
- Repository Clone Configuration: fork of an upstream repository
- Github Product: Github.com

Steps to Reproduce:

1. Make multiple changes to different "hunks" in a file and click the "Create pull request suggestions" button in the Source Control panel

    Here my suggestions ended up as **4** pending comments:

    https://github.com/user-attachments/assets/d2b85688-b315-4241-9fb8-c5dc623a57a7

2. This can lead to multiple individual reviews being started on GitHub and only being able to submit a subset of the suggestions in the review

    On the GH website only **1** comment is in the review:

    https://github.com/user-attachments/assets/1e368a61-3c32-4a7b-9595-6f6aa52685c8

    The other comments end up stuck as pending and cannot be submitted in a review

This is superficially similar to #4291, but in this case the comments clearly are making their way to the server in the pending state, but cannot be submitted.

https://github.com/microsoft/vscode-pull-request-github/issues/1317 may also be relevant

**Comment by alexr00** [comment]
To verify:
1. Check out a PR with at least 15 changed lines across at least 2 files.
2. Make at least 4 changes on lines that you can comment on. Make these changes in such a way that there are 2 unchanged lines between changed lines. Make these changes across at least two files.
3. From the SCM view, use the action in the original post to convert your changes to suggestions. 
4. Verify that all your changes were converted to suggestions.
5. Submit your review. Verify that all your suggestions no longer say "Pending".
