### ISSUE TITLE
Review/Comment Suggestions are offset by one line if you make local changes first

### ISSUE THREAD

**Issue by gabeseltzer** [microsoft/vscode-pull-request-github#6495]
- Extension version: v0.100.3 and v0.101.2024111911
- VSCode Version: 1.95.3
- OS: Windows
- Repository Clone Configuration: single repository
- Github Product Github.com

Steps to Reproduce:

See video:

https://github.com/user-attachments/assets/5b4624e9-f562-41c9-9113-4c8fbd5d9283

1. Create a simple repo
2. (open vscode with temporary profile, so no conflicting extensions)
3. (log in to github, all that jazz)
4. Create a branch + PR for your simple repo (here's mine from the video: https://github.com/gabeseltzer/tv-mode/pull/1)
5. Refresh the PR viewer so that it sees the open PR
6. Make a change to a line that was modified in the PR (or a line nearby)
7. Save the file (optional, I did it in the video, but I have tested and it isn't necessary)
8. Press the `+` icon in the gutter to create a comment
9. Press "Make a Suggestion" (you can add additional comments, it doesn't matter)
10. Confirm the suggestion with either "Start Review" or "Add Comment" (Also works if you already have a review open)
11. **Open Github and refresh the PR, and you'll see the suggestion is on the wrong line, it's one line down!**
12. (not in video) If you close and re-open VSCode, the comment will show in the line below the one you added it to, just like the Github website.

**Comment by alexr00** [comment]
Thank you for reporting!
