### ISSUE TITLE
[Accessibility] Take out redundant URL label from semantic heading in pull request description page

### ISSUE THREAD

**Issue by jooyoungseo** [microsoft/vscode-pull-request-github#6496]
Type: <b>Bug</b>

CC @meganrogge   @alexr00 

## Reproducible Steps

1. Checkout any pull request in any repo

2. Run "GitHub Pull Requests: View Pull Request Description"

In this pull request description page, each comment is marked up with semantic heading tag, which is great! However, noisy GitHub uri is presented before each user name.

Please take a look at what it looks/sounds like to screen reader users.

![Image](https://github.com/user-attachments/assets/5a33304c-74b7-4545-b4b9-745ad162327c)

## Expected Behavior

Only user name needds to be included in the semantic heading without the noisy GitHub uri.

Extension version: 0.101.2024111911
VS Code version: Code - Insiders 1.96.0-insider (91bf2f3b96a337c05fdd30dbfe609ae780b74706, 2024-11-19T05:04:26.087Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz (8 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.71GB (2.88GB free)|
|Process Argv|--crash-reporter-id b05b88e5-8894-4031-ae34-fa034ebddea9|
|Screen Reader|yes|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
vsaa593:30376534
py29gd2263:31024238
c4g48928:30535728
a9j8j154:30646983
962ge761:30841072
pythonnoceb:30776497
asynctok:30898717
dsvsc014:30777825
dsvsc015:30821418
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
cppperfnew:30980852
pythonait:30973460
01bff139:31013167
dvdeprecation:31040973
dwnewjupyter:31046869
nativerepl1:31134653
pythonrstrctxt:31093868
nativeloc1:31118317
cf971741:31144450
e80f6927:31120813
12bdf347:31141542
iacca1:31150324
notype1:31143044
dwcopilot:31158714
h409b430:31177054
cf1a2727:31183122
5b1c1929:31184661

```

</details>

**Comment by alexr00** [comment]
This is the same as https://github.com/microsoft/vscode-pull-request-github/issues/6220.

Seems like this is intentionally done by screen readers: https://github.com/microsoft/vscode-pull-request-github/issues/6220#issuecomment-2393185263

But we also need to include the url in the `title`: https://github.com/microsoft/vscode-pull-request-github/issues/6220#issuecomment-2393350020

I don't see a good way to fix this given that NVDA is intentionally doing it.
