### ISSUE TITLE
The icon for github pull request installation is passing successfully, but extension icon doesn't load

### ISSUE THREAD

**Issue by shai-ostshega** [microsoft/vscode-pull-request-github#6499]
- Extension version:
- VSCode Version: 1.95.3
- OS:
Ubuntu 22

Steps to Reproduce:
1. Install the extension (for other people it works on similar env) . I don't know what is different

**Comment by alexr00** [comment]
Can you share a screenshot?

**Comment by JayDeline** [comment]
Having same issue
