### ISSUE TITLE
Diffing `OUTDATED` comments with HEAD doesn't work in `github.dev`

### ISSUE THREAD

**Issue by tamuseanmiller** [microsoft/vscode-pull-request-github#6500]
Looks like this is specific to GitHub.dev

- Extension version: v0.100.3
- VSCode Version: 1.95.3
- OS: N/A (Web version github.dev)
- Repository Clone Configuration (single repository/fork of an upstream repository): single repo
- Github Product (Github.com/Github Enterprise version x.x.x): Github.com org

Steps to Reproduce:

1. Open Github.dev for a pull request in an org
2. Login
3. Open the comments view
4. Try and diff an outdated comment with HEAD

Shows this:
![Image](https://github.com/user-attachments/assets/7a4c3170-146d-4d73-984f-d2734918c85e)

Doubt this is an error here, I don't see any logs that are pertinent to this but just wanted some feedback as we would love to use this mechanism in github.dev.

**Comment by amunger** [comment]
looks fine on desktop, but I don't seem to be able to load comments in insiders .dev at the moment, but I'm having other issues with GH as well

**Comment by alexr00** [comment]
Blocked on https://github.com/microsoft/vscode-pull-request-github/issues/6590

**Comment by alexr00** [comment]
New prerelease is out and testing this is unblocked.
