### ISSUE TITLE
Exit review mode stays in disabled state if you cancel quick pick

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode-pull-request-github#651]
Testing https://github.com/Microsoft/vscode/issues/62184

- Extension version: 0.2.2
- VSCode Version: 1.29-insiders
- OS: macOS

Steps to Reproduce:

1. Checkout a PR with the extension
2. Click exit review mode on discussion page
3. Step through to create a branch to exit to
4. ESC the quick pick to cancel

🐛 => Exit review mode is incorrectly disabled

**Comment by alexr00** [comment]
I don't think this happens anymore.
