### ISSUE TITLE
error when adding file comment to renamed file w/o other changes

### ISSUE THREAD

**Issue by diminutivesloop** [microsoft/vscode-pull-request-github#6516]
- Extension version: 
- VSCode Version: 1.95.3
- OS: Darwin x64 23.6.0
- Repository Clone Configuration (single repository/fork of an upstream repository): single repository
- Github Product (Github.com/Github Enterprise version x.x.x): Github.com

Steps to Reproduce:

1. In a pull request open a change diff for a file that was renamed without any other changes.
2. Click the "Add file comment" editor action button.

The following error shows: "The cursor must be within a commenting range to add a comment"

**Comment by alexr00** [comment]
🙏 a huge thank you for reporting this. I have been unable to find the source of https://github.com/microsoft/vscode/issues/230642, but your steps cause it!
