### ISSUE TITLE
Option to view changed files in a tree instead of a list

### ISSUE THREAD

**Issue by devhawk** [microsoft/vscode-pull-request-github#653]
Currently, the list of changed files appears as a flat list. Can it be in a hierarchy according to repo folder?

Current experience:

![capture1](https://user-images.githubusercontent.com/8965/47818513-5979b400-dd15-11e8-806d-2139aff52e1e.PNG)

Requested experience (screen shot from [Tree Explorer for GitHub Chrome Extension](https://chrome.google.com/webstore/detail/tree-explorer-for-github/caffoilocbbhnkdlpdcfanpbeholjdii)

![capture2](https://user-images.githubusercontent.com/8965/47818573-73b39200-dd15-11e8-8c49-c2b71df4bc1c.PNG)

**Comment by rebornix** [comment]
Good idea! We can probably several different ways to display the file changes

1. flat list

```
- src/extension.ts
- src/view/tree/prNode.ts
```

2. tree
```
- src
  - extension.ts
  - view 
    - tree
      - prNode.ts
```

3. tree but skipping single node folders

```
- src
  - extension.ts
  - view/tree/
    - prNode.ts
```

cc @misolori

**Comment by jerrymajewski** [comment]
I submitted a PR that demonstrates `Option 3`: #655.

**Comment by misolori** [comment]
I like the idea. If we're going to add this, we should definitely provide an option/setting to allow the user to change it based upon their preferences.

**Comment by borekb** [comment]
[Git Tree Compare](https://marketplace.visualstudio.com/items?itemName=letmaik.git-tree-compare) does this nicely, e.g.:

<img width="349" alt="Screenshot 2019-05-27 at 10 38 44" src="https://user-images.githubusercontent.com/101152/58407280-ba7b2780-806b-11e9-9263-049af4b978de.png">

**Comment by Kligerr** [comment]
> [Git Tree Compare](https://marketplace.visualstudio.com/items?itemName=letmaik.git-tree-compare) does this nicely, e.g.:
> 
> <img alt="Screenshot 2019-05-27 at 10 38 44" width="349" src="https://user-images.githubusercontent.com/101152/58407280-ba7b2780-806b-11e9-9263-049af4b978de.png">

[GitLens](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens) knows to do it even cooler (in addition to various other things):

![2019-06-02 16_26_13-get js (master) ⟷ get js (bug_596-Hidden-Tags-are-lost-when-saving-product-in-MP](https://user-images.githubusercontent.com/7114898/58762006-5537a280-8553-11e9-9d95-23c4278d25ef.png)

**Comment by yulrizka** [comment]
@rebornix, any reason this is not being picked up? This is super useful, especially when looking at big changes.
I like the 2nd implementation in #655
I tried to create basic implementation the 3rd options in #1358.
