### ISSUE TITLE
Exit PR: No need to ask for which repo in a multi-root setup

### ISSUE THREAD

**Issue by octref** [microsoft/vscode-pull-request-github#654]
- Extension version: 0.2.2
- VSCode Version: 1.28
- OS: macOS High Sierra

Steps to Reproduce:

1. Exit PR in a multi-root workspace.
2. It asks which repo do I want to change branch.
3. A PR is already associated with a specific workspace. For example, if I'm working on repo A/B/C and I'm exiting pr A/<contributor-id>/100, I wouldn't expect the Exit to ask me whether I want to switch branch for B or C.

**Comment by RMacfarlane** [comment]
Closing as I believe this was fixed as part of https://github.com/microsoft/vscode-pull-request-github/commit/b629b113f28050d5f311fae196b4297029eb7c89, I can no longer repro this
