### ISSUE TITLE
Primary action to "Start Review" is not looking as such

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-pull-request-github#6553]
My feeling is that "Start Review" is typically the primary action on a PR:

![Image](https://github.com/user-attachments/assets/0beb1fb1-7fdd-443d-8f6e-e22d35fd6e72)

But here the button looks secondary. I would make "Start Review" green and the others dark.

**Comment by alexr00** [comment]
You can choose which one is primary: `githubPullRequests.defaultCommentType`

**Comment by alexr00** [comment]
The "Make a Suggestion" button shouldn't be a primary button though.

**Comment by bpasero** [comment]
Should we make `review` the default?

**Comment by alexr00** [comment]
I think we'll end up with a lot of confused users since it's very easy to make a bunch of "review" comments and then forget to submit the review. This results in a bunch of comments that no one but you ever sees since they are associated with an unsubmitted review.
