### ISSUE TITLE
Comments don't show on non-checked out PR when closing and re-opening the file from the PRs veiw

### ISSUE THREAD

**Issue by catskul** [microsoft/vscode-pull-request-github#6571]
When working on stacked PRs it's common to want to address comments on a lower PR in the stack while having the branch from a higher PR checked out.

At the moment it seems that GithubPullRequests extension will not allow this *even when* a PR file or diff is opened in preview mode from the Pull Requests sidebar.

IMO the comments should still appear in these editor windows at the very least, and ideally in any file with comments.

**Comment by catskul** [comment]
This might actually be a bug?

Sometimes I can see the comments and sometimes I cant see the comments when opening the file from the pull requests panel. (the editor says `file_name.cc (Pull Request)`)

**Comment by alexr00** [comment]
It is a bug, and apparently it's been around for nearly a year. Thanks for reporting!

**Comment by alexr00** [comment]
To verify:
1. Install the latest pre-release version of GitHub Pull Requests
2. Open your clone of a GitHub repo in VS Code
3. Checkout branch A.
4. Create a new branch B and make a commit on branch B.
5. Create a pull request from branch B in to branch A.
6. Create a new branch C based on branch B.
7. Make a commit on branch C.
8. Create a pull request from branch C into branch B.
9. From the Pull Requests view, open code diffs from both the pull requests that you just created. Verify that you can leave comments in these files and that the comments get set on the correct PR.
