### ISSUE TITLE
Issue links in description/comments are not linkified

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-pull-request-github#66]
See the link at the bottom. repo/user#num format should also be covered

![image](https://user-images.githubusercontent.com/2193314/41949192-2d72f118-7975-11e8-8c0e-f9ebda2a7310.png)

**Comment by rebornix** [comment]
related https://github.com/Microsoft/vscode-pull-request-github/issues/74 

Right now the description we get from GitHub v3 API is plain text (markdown) so we can render the content to HTML but we didn't do any conversion like converting `#1518` to `https://github.com/${owner}/${repo}/issues/1518`, or truncating the label for links.

As we are using Markdown-it, we can customize the markdown rendering to support this or maybe GitHub API can provide content similar to what they already have in web pages.

**Comment by Tyriar** [comment]
@rebornix couldn't you run the markdown through a filter which converts the links before passing it to markdown-it?

**Comment by rebornix** [comment]
@Tyriar markdown grammars are ambiguous so writing a markdown-it extension which takes care link token can solve this problem better.

**Comment by rebornix** [comment]
As raised in https://github.com/Microsoft/vscode-pull-request-github/issues/105, links in comments are not linkified as well.

**Comment by RMacfarlane** [comment]
Completed by https://github.com/Microsoft/vscode-pull-request-github/pull/831
