### ISSUE TITLE
Gutter decorations slightly off-centre

### ISSUE THREAD

**Issue by JeffreyCA** [microsoft/vscode-pull-request-github#660]
- Extension version: 0.2.3
- VSCode Version: 1.28.2
- OS: macOS 10.14.1

The `+` symbol skews towards the left and the `♦` symbol skews towards the top ever so slightly.

<img width="42" alt="screen shot 2018-11-02 at 7 58 24 pm" src="https://user-images.githubusercontent.com/9157833/47945728-554ac380-deda-11e8-878f-eab30482af4c.png">

**Comment by RMacfarlane** [comment]
I checked in a fix for the `+` button centering in VSCode (https://github.com/Microsoft/vscode/commit/8fb320d4a42594679f569e772c28a3cb8bc25207). Does the `♦` icon still appear skewed to the top for you?

**Comment by JeffreyCA** [comment]
Yes, it's more noticeable when the font size is bigger:

<img width="137" alt="screen shot 2018-11-30 at 2 56 36 pm" src="https://user-images.githubusercontent.com/9157833/49311843-50186e80-f4b0-11e8-9b66-7684ec8fe45a.png">

<img width="137" alt="screen shot 2018-11-30 at 2 56 45 pm" src="https://user-images.githubusercontent.com/9157833/49311842-4f7fd800-f4b0-11e8-8215-e87b9b840ea3.png">

The `+` also exceeds the width of the grey rectangle if font size is large enough. And is that horizontal line supposed to be there in the second image? It isn't visible on smaller font sizes.

**Comment by alexr00** [comment]
Can no longer repro.
