### ISSUE TITLE
Hide all comments command/setting

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-pull-request-github#665]
- Extension version: 0.2.3
- VSCode Version: 1.29
- OS: macOS

![image](https://user-images.githubusercontent.com/876920/48036759-9cc19180-e11e-11e8-9f99-75bd5ad1a1d5.png)

Without a way to hide all comments, I have to hide them one by one in order to have a quick view of the diff.

**Comment by stefan-toubia** [comment]
This issue kills me, nearly makes it unusable on PRs with many comments.

**Comment by Math3v** [comment]
Yes, please! :) What is the state of this request? Can we create a PR? 🙏

**Comment by Mystic8b** [comment]
Not solved in 2 years?)

**Comment by alexr00** [comment]
Checkout the issue timeline and Milestone. It's already in progress for this month :)

**Comment by alexr00** [comment]
With this change there are several ways you can expand/collapse all:

1. From the command palette with "GitHub Pull Requests: Toggle Comment Expansion".
2. From your user settings with `"githubPullRequests.commentExpandState"` (setting name may change before release).
3. From the title action in any comment
![image](https://user-images.githubusercontent.com/38270282/129726883-7423cf2c-6fc0-429d-b8fc-44692fd6cde4.png)

**Comment by pravic** [comment]
Just came to create an issue and stumbled upon it being resolved. Thanks!

**Comment by pedro-lino** [comment]
Hi, I am aware we already have the command to expand all comments, after collapsing them. However, it would be nice to have a button to execute that command, in the same way we have for collapsing all. Thanks

**Comment by timothysheee** [comment]
NOTE: Command is currently called `Comments: Collapse All Comments`
