### ISSUE TITLE
Resolve conversation command

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode-pull-request-github#666]
- Extension version: 0.2.3
- VSCode Version: 1.29
- OS: macOS

Now GitHub pull request commenting system has *Resolve conversation* command, similarly to Codeflow. Right now we have to go back .com to perform this operation.

**Comment by RMacfarlane** [comment]
Duplicate of https://github.com/Microsoft/vscode-pull-request-github/issues/339
