### ISSUE TITLE
Allow usage with multiple accounts

### ISSUE THREAD

**Issue by AdrianKoshka** [microsoft/vscode-pull-request-github#667]
I have a rather unique use-case I guess. I'd like to be able to sign into multiple github accounts with the extension, and change which one is currently being used.

**Comment by AdrianKoshka** [comment]
This seems to be fixed from my experience.

**Comment by AdrianKoshka** [comment]
I was wrong.

**Comment by linamarin** [comment]
How do I logout of my husbands account of the ext, so I may login as me please

**Comment by RMacfarlane** [comment]
You can log out of the extension by clicking on the username shown in the statusbar, or by pressing F1 and running the `GitHub Pull Requests: Sign out of GitHub` command

**Comment by mhtrinhLIC** [comment]
Please re-open the issue: the current solution is to sign-out then sign back in again with different account. This means that you are using a single account at the time. The feature would be having multiple account signin and allow user to choose which account to do a Pull requets, etc ... without logout and login each time.
