### ISSUE TITLE
Duplicates of pull request API calls

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-pull-request-github#685]
Issue Type: <b>Bug</b>

Found this while adding more logging #684.

```
[Debug 971210s 767ms] GitHubRepository> Fetch pull request catogory 2 - enter
[Debug 971211s 510ms] GitHubRepository> Fetch pull request catogory 2 - done
[Debug 971211s 596ms] GitHubRepository> Fetch pull request catogory 2 - enter
[Debug 971213s 866ms] GitHubRepository> Fetch pull request catogory 2 - done
[Debug 971218s 797ms] GitHubRepository> Fetch pull request catogory 1 - enter
[Debug 971220s 638ms] GitHubRepository> Fetch pull request catogory 1 - done
[Debug 971220s 716ms] GitHubRepository> Fetch pull request catogory 1 - enter
[Debug 971221s 209ms] GitHubRepository> Fetch pull request catogory 1 - done
[Debug 971235s 705ms] PullRequestManager> Fetch comments of PR #60922 - enter
[Debug 971235s 841ms] PullRequestManager> Fetch comments of PR #60922 - done
```

Extension version: 0.316.0
VS Code version: Code - Insiders 1.29.0-insider (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-10T00:34:03.196Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.92GB (5.93GB free)|
|Process Argv|-r --enable-proposed-api GitHub.vscode-pull-request-github-insiders|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by rebornix** [comment]
Actually false alarm, I have multiple remotes locally which trigger multiple requests.

**Comment by rebornix** [comment]
https://github.com/Microsoft/vscode-pull-request-github/blob/29210cfed4a22295a4d8551460df2ac9ce8b636c/src/github/pullRequestManager.ts#L274 our paging feature fetch PRs from remotes in sequence so even http requests can be run in multiple threads, we are not benefiting from that.

**Comment by RMacfarlane** [comment]
Closing as I think this isn't relevant anymore since we only fetch from the remotes specified in the `githubPullReqests.remotes` setting
