### ISSUE TITLE
Markdown comment block appear in PR content

### ISSUE THREAD

**Issue by ZeroX-DG** [Microsoft/vscode-pull-request-github#689]
First of all, thank you for the amazing extension. It makes reviewing a lot easier.

- Extension version: 0.2.3
- VSCode Version: 1.28.2
- OS: Linux Mint 18.2 Cinnamon 64-bit

Steps to Reproduce:

1. Open a pull request with a comment block in its' content
2. That's it. Here's a screenshot of how it looks

![image](https://user-images.githubusercontent.com/12984316/48462660-9eb8de00-e80b-11e8-9c84-f583ca5f4151.png)

**Comment by JeffreyCA** [comment]
I looked into this and it's due to `markdown-it-sanitizer` the MD sanitizer plugin we use.

It treats comment tags `<!-- -->` as *unknown*. In `mdRenderer.ts` if `removeUnknown` is set to `true` then comment tags will be removed. Would changing this setting be okay?

**Comment by ZeroX-DG** [comment]
> For not whitelisted tags and tags that don't have a matching opening/closing tag you can define whether you would like to remove or escape them.

I don't think setting it to `true` is a good idea. Should we just remove the comments? Using this package for example: https://www.npmjs.com/package/markdown-it-inline-comments
