### ISSUE TITLE
Merge base or better base.sha in GitHub Pull Request API

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode-pull-request-github#698]
Right now the bottleneck of viewing pull requests is fetching the merge base most of the time

```
[Debug 491053s 954ms] PullRequestManager> Fetch comments of PR #62869 - enter
[Debug 491054s 186ms] PullRequestManager> Fetch comments of PR #62869 - done
[Debug 491054s 186ms] PullRequestManager> Fetch changed files of PR #62869 - enter
[Debug 491054s 493ms] PullRequestManager> Fetch changed files of PR #62869 - done
[Debug 491054s 493ms] PullRequestManager> Fullfill pull request missing info - start
[Debug 491054s 493ms] PullRequestGitHelper> Get merge base of 0dcc8e4dc46c5cbaeb473a5db7632f97ae77cbdf, 75187ba0ef9409631f11399983808910e946838a
[Debug 491054s 573ms] PullRequestGitHelper> Get merge base of 0dcc8e4dc46c5cbaeb473a5db7632f97ae77cbdf, 75187ba0ef9409631f11399983808910e946838a failed, start fetching from remote
[Debug 491057s 478ms] PullRequestGitHelper> Get merge base of 0dcc8e4dc46c5cbaeb473a5db7632f97ae77cbdf, 75187ba0ef9409631f11399983808910e946838a again
[Debug 491057s 549ms] PullRequestManager> Fullfill pull request missing info - done
```

As you can see above, it took 500ms to get comments, diff hunks from GitHub but since the `base.sha` is not always the merge base of the pull request, we have to do the math ourselves (finding the merge base). Most of the time, since we don't have the code of that pull request, we have to fetch first, which took 3 seconds on my machine with VSCode repository.

In total, viewing a newly created pull request from VSCode repository will take around 4 seconds. But there is no way for us to avoid calculating merge base as we don't when `base.sha` is updated to the correct value. It seems that GitHub.com has some cache or not-always-up-to-date of `base.sha`.

**Comment by shana** [comment]
More context about this at https://github.com/Microsoft/vscode-pull-request-github/issues/203#issuecomment-413958275

**Comment by rebornix** [comment]
Thanks @shana . As we discussed offline, the underling problem is 

* patch is against `merge base`
* base and head are updated in time

Probably `patch` should be updated whenever base and head are updated, instead of providing a `merge base`.

**Comment by rebornix** [comment]
Close it for now as we already adopt the commit compare api and it looks good enough.
