### ISSUE TITLE
Need to look back at merged pull request

### ISSUE THREAD

**Issue by linkdesu** [microsoft/vscode-pull-request-github#704]
Hi, THX for all your effort, this plugin really helps a lot when I take a review!

After a few days of experience, I hope it has a new category named "merged" so that I be able to review merged PR.

**Comment by alexr00** [comment]
You can do this by editing your queries setting. Example:
```
	"githubPullRequests.queries": [
		{
			"label": "Waiting For My Review",
			"query": "is:open review-requested:${user}"
		},
		{
			"label": "Assigned To Me",
			"query": "is:open assignee:${user}"
		},
		{
			"label": "Merged By Me",
			"query": "is:merged author:${user}"
		}
	],
```
