### ISSUE TITLE
Comments on PR reviews are not shown

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-pull-request-github#71]
![image](https://user-images.githubusercontent.com/2193314/41949386-100948f6-7976-11e8-99a1-05a0d60ab4cc.png)

vs

![image](https://user-images.githubusercontent.com/2193314/41949394-1b2dd030-7976-11e8-8137-e46ebd6bba9e.png)

**Comment by rebornix** [comment]
If an user leave a comment by using "Add single comment" button, it will create a review, which contains a single comment. When we get "Someone left a review" timeline event, we can only get the related single comment by the review id.

**Comment by kieferrm** [comment]
@RMacfarlane fixed yesterday that you see the comments on files. Overview page still open. See #159.
