### ISSUE TITLE
Cannot authenticate via URI handler

### ISSUE THREAD

**Issue by sbatten** [Microsoft/vscode-pull-request-github#710]
Issue Type: <b>Bug</b>

1. Click sign in to github in the status bar
2. Follow the steps to authenticate
3. Let uri handler in vs code open authentication uri

:bug: => stuck signing in. the extension does not handle the uri and store the token

Extension version: 0.333.1
VS Code version: Code - Insiders 1.30.0-insider (cd5b4d1bb3fc7e509fba077095b2b280b8ff7161, 2018-11-29T06:32:54.872Z)
OS version: Windows_NT x64 10.0.17763

**Comment by geekpete** [comment]
I see similar issue.
Can't auth to github, went through the process and came back to the editor but it's stuck signing in, clicking on github icon at the bottom pops a token input, tried creating a personal access token to paste in here and didn't seem to help

**Comment by JetBitz01** [comment]
Am also facing the same issue. It does not seem to get pass the continue page and on the rare occasion that it does, can't get pass the authenticate page either. On linux here.

**Comment by RMacfarlane** [comment]
If you're using VSCode insiders, change the `Http: System Proxy` setting to `off`

https://github.com/Microsoft/vscode/issues/60773

**Comment by JetBitz01** [comment]
@RMacfarlane I am not using VSCode insiders nor is System Proxy on.
