### ISSUE TITLE
PR view: explorer overlay

### ISSUE THREAD

**Issue by troshko111** [microsoft/vscode-pull-request-github#712]
There are existing items (#653 #655) aiming to improve the PR changelist view by showing some sort of a tree, I'd like to propose to take this idea further and generalize it a bit:

When selecting a PR from the list, add an option to "Overlay the {working copy} or maybe {specific commit}" which applies the PR as a layer on top of your working changes or the selected commit similar to applying a patch. 

This way you get the best review experience possible since the changes appear as you've made them and you have the full editor awareness. In case of a non-working copy overlay, a shadow repo copy needs to be maintained probably and a new vscode instance can be opened with that repo as a single workspace directory with the PR overlay applied.

Inspired by a neat [blogpost](https://blog.janestreet.com/putting-the-i-back-in-ide-towards-a-github-explorer/) which I believe more ideas can be borrowed from.

**Comment by alexr00** [comment]
We allow you to check out the PR, which checkout out the PR branch and shows a tree with the file diffs.
