### ISSUE TITLE
Applying patch fails without proper error message

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-pull-request-github#722]
Issue Type: <b>Bug</b>

Testing https://github.com/Microsoft/vscode/issues/64262.

1) Check out a PR
2) `Suggest Edit` for  a local change
3) Create a change that conflicts with the suggested edit.
4) Open the Overview page of the PR
5) Apply change
=> Error
```
Applying patch failed: Error
```
The actuall error message contains more information (althouth some duplicated):
```
error: patch failed: <filePath>:<lineNumber>\nerror: <filePath>: patch does not apply\n
```

Extension version: 0.337.0
VS Code version: Code - Insiders 1.30.0-insider (fa87e67ebfd6b8014ba697ddbc6c2d6c0e2cb970, 2018-12-04T09:26:33.257Z)
OS version: Darwin x64 18.0.0

**Comment by roblourens** [comment]
Is this what I'm supposed to see now?
![image](https://user-images.githubusercontent.com/323878/144338142-b9922146-7a2c-4d1c-9edb-a70776b42f09.png)

**Comment by alexr00** [comment]
Yes, that's what you should see now!

**Comment by baraBlz** [comment]
I need help
