### ISSUE TITLE
Commenting ranges remain after leaving review mode

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode-pull-request-github#727]
Issue Type: <b>Bug</b>

Testing https://github.com/Microsoft/vscode/issues/64262.

1) Create a PR using the extension
2) Open a file that's part of the PR (and make it stick)
3) Open the overview page of the PR
4) Merge the PR on the overview page
5) Hit the `Exit Review Mode` button
6) Switch to the editor from step 2)
-> Commenting range indicators are still there.

Extension version: 0.3.1
VS Code version: Code - Insiders 1.30.0-insider (fa87e67ebfd6b8014ba697ddbc6c2d6c0e2cb970, 2018-12-04T09:26:33.257Z)
OS version: Darwin x64 18.0.0

**Comment by RMacfarlane** [comment]
Review state is not getting cleaned up when the branch you switch to doesn't have an upstream
