### ISSUE TITLE
Allow branch to be checked out when exiting review mode to be configurable

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-pull-request-github#729]
Testing https://github.com/Microsoft/vscode/issues/64262

- Check out a PR
- Exit Review Mode

I should be back to my branch I was in before instead of asking me to which branch I have to check out

**Comment by alexr00** [comment]
We automatically checkout the default branch now.

**Comment by ortonomy** [comment]
Ah, @alexr00 -- can't you make this configurable? Our default branch is set to `main` but the working trunk is develop. It's really annoying that exiting review mode goes to the default branch. Prefer configurable.

**Comment by alexr00** [comment]
We have this now: `githubPullRequests.overrideDefaultBranch`
