### ISSUE TITLE
Use description for parent paths

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode-pull-request-github#730]
Testing https://github.com/Microsoft/vscode/issues/64262

![image](https://user-images.githubusercontent.com/10746682/49509234-03a0aa80-f885-11e8-88fe-81ff28bd3389.png)

![image](https://user-images.githubusercontent.com/10746682/49509286-2af77780-f885-11e8-8e36-d1a01e8fa29b.png)

TreeItem has description property which can be used for this

**Comment by rebornix** [comment]
@sandy081 thanks! I tested the new TreeItem features and description works great, will adopt this for both PR node and file change node.

**Comment by RMacfarlane** [comment]
Fixed by @rebornix with https://github.com/Microsoft/vscode-pull-request-github/commit/b354fe8bb98ab3848432eba734517682dbe3e020
