### ISSUE TITLE
Ability to open the file directly

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode-pull-request-github#731]
Testing https://github.com/Microsoft/vscode/issues/64262

![image](https://user-images.githubusercontent.com/10746682/49509520-e15b5c80-f885-11e8-9f93-6e76389aa1fc.png)

It would be nice if I can open the file (not just diff) directly from here, just like in SCM changes view

**Comment by rebornix** [comment]
@sandy081 do you prefer an action in context menu or inline actions like resource item in SCM changes view? For the latter, our current tree view doesn't support that, right?

**Comment by sandy081** [comment]
It makes sense to be consistent with scm changes view. Tree view support inline actions - https://github.com/Microsoft/vscode-extension-samples/blob/master/tree-view-sample/USAGE.md#view-actions

**Comment by rebornix** [comment]
@sandy081 thanks! I didn't even know it's possible, it's helpful that we have you as a tester this time.

**Comment by RMacfarlane** [comment]
fixed by https://github.com/Microsoft/vscode-pull-request-github/commit/a52f39bbe5203c4773b27a6ea38e7b3ef2c6fb69
