### ISSUE TITLE
Suggesting changes flow is not discoverable

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-pull-request-github#732]
Testing https://github.com/Microsoft/vscode/issues/64262

I think current Suggest changes was not the beset in the flow of review and not discoverable. As a reviewer I would

- Open a file diff and start reviewing
- I see there is a change needed, I would like to start editing the file inline
- Do the changes and save it
- I might look for an action in the diff editor, or may be in the title, or in the SCM view a primary action (not in context menu) to suggest these changes. I suppose changes I do in this review mode/branch is to always suggest, is not it? If so, this action has to be prominent rather hidden in context menu.

By the way is not this action can be called Suggest Changes instead of Suggest Edit?

**Comment by queerviolet** [comment]
+1 to this. I just tried to do it and had to go look at the PR to figure out how 🙈

**Comment by mauriciabad** [comment]
I can't find how to suggest changes. 😢 

What is the "proper" way of doing it?

**Comment by tanhakabir** [comment]
+1

**Comment by alexr00** [comment]
Closing in favor of supporting https://github.com/microsoft/vscode-pull-request-github/issues/603
