### ISSUE TITLE
Auth error when trying to create  

### ISSUE THREAD

**Issue by jongio** [Microsoft/vscode-pull-request-github#735]
Version: 1.30.0-insider (user setup)
Commit: 85f805acf9436381b878cab5ab6c5146beec7893
Date: 2018-12-05T06:19:36.555Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17134

## Steps to Reproduce:

1. Fork and clone
1. Make change
1. Add/commit/push
1. Click Create PR + icon
1. Select remote and branch
1. Get error

## Output:

[Info] GitHubRepository> Creating pull requests failed: {"message":"Validation Failed","errors":[{"resource":"PullRequest","field":"head","code":"invalid"}],"documentation_url":"https://developer.github.com/v3/pulls/#create-a-pull-request"}

**Comment by jongio** [comment]
I tried again on a diff branch and got further, but it appears to have hung here: 
![image](https://user-images.githubusercontent.com/2163001/49538058-62fbbc00-f87f-11e8-83a6-03eb231d89ae.png)


I was able to create a PR with the extension to my fork...but not to the upstream. Both are private repos.

**Comment by jongio** [comment]
Thoughts on this?  Would love to start using this feature 😃

**Comment by RMacfarlane** [comment]
Just checked in a fix for it, I think we will try to release a new version of the extension soon
