### ISSUE TITLE
Comment and issue links should be truncated

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#74]
![image](https://user-images.githubusercontent.com/2193314/41949595-ee4ce816-7976-11e8-9ea6-0a45fccca17f.png)

The first is shown as `mintty/mintty#88 (comment)` and the second as `#1467 (comment)` in GitHub.

**Comment by RMacfarlane** [comment]
This has already been fixed, we're now using markdown returned from the GitHub graphql api that has already truncated these links
