### ISSUE TITLE
Comments out of sync

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-pull-request-github#740]
Issue Type: <b>Bug</b>

See attached image.

![image](https://user-images.githubusercontent.com/4674940/49664013-6faa1c80-fa05-11e8-844c-d4a0e57ab8ec.png)

I made the comment in the editor. I closed the comment and navigated somewhere else. I then executed "Go to next comment thread".

Extension version: 0.3.1
VS Code version: Code - Insiders 1.30.0-insider (a152a5c7818a13666a5879b4450eb26a4d45fbde, 2018-12-07T10:25:53.709Z)
OS version: Darwin x64 18.0.0

**Comment by RMacfarlane** [comment]
I'm not able to repro this now
