### ISSUE TITLE
Allow to navigate from overview page to comment thread

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode-pull-request-github#742]
Issue Type: <b>Feature Request</b>

See attached image. 

![image](https://user-images.githubusercontent.com/4674940/49664604-32df2500-fa07-11e8-9bbd-07d9c9e33b72.png)

We should have an action link on the right of the beginning of the comments thread that allows me to directly navigate to the comment in the source file in my workspace when the PR is checked out, or it should open the file in the diff view (just like clicking it in the PR viewlet).

Extension version: 0.3.1
VS Code version: Code - Insiders 1.30.0-insider (a152a5c7818a13666a5879b4450eb26a4d45fbde, 2018-12-07T10:25:53.709Z)
OS version: Darwin x64 18.0.0

**Comment by RMacfarlane** [comment]
This was implemented with cfcb1f74f06669fe42087216f2b0b10be0285d65
