### ISSUE TITLE
Pull requests should be checked out without adding a remote locally

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-pull-request-github#75]
It's possible to fetch PR changes without adding a remote:

```
git pull --no-rebase origin refs/pull/PR_NUMBER/head
```

https://help.github.com/articles/checking-out-pull-requests-locally/

**Comment by rebornix** [comment]
We created remotes for the remote branch just in case if you want to make changes and push to that branch. AFAIK, `refs/pull/PR_NUMBER/head` is a readonly copy of the Pull Request so users need additional steps (for example knowing which remote/branch it should be bind to) when they want to push.

**Comment by peppy** [comment]
I work an an environment where we *do* have push permissions on the remotes we are reviewing (this is the default on github for [repository maintainers](
https://user-images.githubusercontent.com/191335/64845073-3366b500-d644-11e9-9950-261835a2965b.png)) and would really appreciate this functionality.

It is one of the blockers for me to use the github pull request plugin over `hub` (https://github.com/github/hub). With hub's checkout functionality, it will checkout and add push support without adding remotes. This avoids local clutter (having hundreds of remotes locally after reviewing many PRs from different users). This is done by specifying the `remote` inside `.git/config`:

```
[branch "use-gameplay-clock-current-time"]
    remote = https://github.com/iiSaLMaN/osu.git
    merge = refs/heads/use-gameplay-clock-current-time
```

**Comment by phil-blain** [comment]
See also https://github.com/microsoft/vscode-pull-request-github/issues/2030

**Comment by alexr00** [comment]
Tentatively adding to February.

**Comment by alexr00** [comment]
Remotes are now automatically cleaned up when you use the "checkout default branch" button within the extension.

**Comment by joaomoreno** [comment]
Closing as out of scope.
