### ISSUE TITLE
Must, not Need

### ISSUE THREAD

**Issue by jwargo** [microsoft/vscode-pull-request-github#757]
In the login Notification pop-up:
![image](https://user-images.githubusercontent.com/30843404/50015927-caa7ba80-ff95-11e8-8af1-572c412e4e65.png)
 It's not that you **Need to**  sign-in, you **must** sign-in for this to work. Changing the phrase from `need to` to `must` makes it less passive, clearer that it's not optional, and removes one extra word from the dialog. :-)

**Comment by jwargo** [comment]
@RMacfarlane  closed because? Fixed? Don't care about it? Stupid suggestion?

**Comment by RMacfarlane** [comment]
@jwargo Fixed, it will be part of the next release. Thanks!
