### ISSUE TITLE
New section/category for suggested code changes

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-pull-request-github#759]
Issue Type: <b>Feature Request</b>

Right now the only way to see a suggested code change is through description view, but before I apply the code change, I can't easily have an overall view of what the code change is like, the diffhunk in description view doesn't help a lot.

Extension version: 0.3.2
VS Code version: Code - Insiders 1.31.0-insider (d315b31c6b5cdca082b0a6e193306e4001586509, 2018-12-19T08:03:47.112Z)
OS version: Darwin x64 18.2.0

**Comment by alexr00** [comment]
Since we now support GitHub's suggestion flow there's a good way to see the proposed changes.
