### ISSUE TITLE
Extension not starting

### ISSUE THREAD

**Issue by blackHatMonkey** [Microsoft/vscode-pull-request-github#760]
Issue Type: <b>Bug</b>

The extention fails to start.

Extension version: 0.2.3
VS Code version: Code - OSS 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-12-06T23:12:09.502Z)
OS version: Linux x64 4.19.8-2-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz (8 x 2457)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|15.36GB (12.07GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details>

I have included the log files

[1.log](https://github.com/Microsoft/vscode-pull-request-github/files/2699855/1.log)
[2.log](https://github.com/Microsoft/vscode-pull-request-github/files/2699856/2.log)

Let me know if you need any more information.

**Comment by RMacfarlane** [comment]
@blackHatMonkey Thanks for the logs! This looks like the same issue as https://github.com/Microsoft/vscode-pull-request-github/issues/525#issuecomment-429972858. Can you try launching VSCode with the flag `--enable-proposed-api GitHub.vscode-pull-request-github`?

**Comment by blackHatMonkey** [comment]
@RMacfarlane Thanks. The extension did start properly with the `--enable-proposed-api GitHub.vscode-pull-request-github` but I'm wondering is this is going to be fixed in the future?

**Comment by RMacfarlane** [comment]
Yes, this should eventually be fixed. Right now some of the VSCode commenting APIs are still under development, but once they have been promoted to stable, the extension won't need the flag anymore. But I think it will take on the order of months to reach that point, unfortunately
