### ISSUE TITLE
Add support for issues

### ISSUE THREAD

**Issue by wsmelton** [microsoft/vscode-pull-request-github#764]
It seems an initial extension was created for GitHub PR/issues before this one was under [microsoft/vscode-github-issues-prs](https://github.com/Microsoft/vscode-github-issues-prs). Which that extension started out focusing on interacting with issues and not directly with PRs. The maintainer has seem to have been put on other priorities with that extension as activity has pretty much stopped.

There is a gap not having support for interacting with issues between that extension and this one that if filled would allow us to never leave VS Code for GitHub workflow. Is there any roadmap to add support for interacting with repo issues to this extension *or* will the other extension start getting updates to resolve all the bugs?

**Comment by RMacfarlane** [comment]
We've now added issues related features, here's documentation on what is supported so far: https://github.com/microsoft/vscode-pull-request-github/blob/master/documentation/IssueFeatures.md
