### ISSUE TITLE
Support copying commit hash from commit list

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#765]
I wanted to revert the latest commit in the PR, my first thought to use the extension was to go to the commit list and right click to copy the commit hash:

<img width="372" alt="screen shot 2019-01-02 at 7 24 30 am" src="https://user-images.githubusercontent.com/2193314/50598421-89514f00-0e5f-11e9-8c1e-32fb28a28b67.png">

**Comment by RMacfarlane** [comment]
Closing, this was added with https://github.com/microsoft/vscode-pull-request-github/pull/879
