### ISSUE TITLE
Strange refresh menu item contributed to the SCM menu

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode-pull-request-github#77]
Shouldn't this menu item only be contributed to the PR view?

![image](https://user-images.githubusercontent.com/22350/41967468-fcb873f8-7a01-11e8-9a69-6fc03f85ea9e.png)

**Comment by RMacfarlane** [comment]
This was an interesting issue 😄 

The refresh command itself had the "when" clause `"view == pr"`. However, the "pr" view contributed to the SCM viewlet had no when clause, so even when no folder was opened, `"view == pr"` was evaluating to true. I was expecting the truthiness of the view to be based on its visibility
