### ISSUE TITLE
"you are now signed in" but "Token is no longer valid for host" for GitHub Enterprise

### ISSUE THREAD

**Issue by sgarg7** [Microsoft/vscode-pull-request-github#777]
I see the following messages when I enter my token and server name

![image](https://user-images.githubusercontent.com/1569480/50978385-49731300-14c2-11e9-9e45-6c501dfada30.png)

and the following messages in output window

> Authentication> Token is no longer valid for host https://github.example.com.

- Extension version: 0.3.2
- VSCode Version: 1.30.1
- OS: Windows 7

Steps to Reproduce:

1.  click on bottom left "sign in to github.factset.com"
2. enter token and server name as prompted

I'm not sure what is going wrong. I don't use https://vscode-auth.github.com to authenticate because I get the same error as #662

**Comment by RMacfarlane** [comment]
@shana 	@queerviolet 	Can you help looking into this?

**Comment by queerviolet** [comment]
Hi, @sgarg7. When you visit your GHE instance in an incognito window, do you pass through an authentication proxy of some kind?

**Comment by sgarg7** [comment]
We use LDAP for our GHE authentication. I don't think there's a proxy before the GHE instance. Is there a test I could run to be sure?

**Comment by sparky005** [comment]
I'm getting a similar error here when I try to use a token to authenticate to our GHE instance.
Extension version: 0.3.2
vscode version: 1.30.2
OS: Windows 10, CentOS 7
Debug log output:
```
[Debug 849610s 30ms] C:\Users\<username>\.ssh\config: ENOENT: no such file or directory, open 'C:\Users\<username>\.ssh\config'
[Debug 849610s 92ms] Looking for git repository
[Debug 849610s 92ms] Git repository found, initializing review manager and pr tree view.
[Debug 849610s 92ms] Migrating https://github.org.com from githubPullRequests.hosts to keychain
[Debug 849610s 282ms] PullRequestManager> update repositories
[Debug 849610s 633ms] No GitHub remotes found
[Debug 849611s 31ms] PullRequestManager> update repositories
[Debug 849611s 33ms] Found GitHub remote
[Debug 849611s 159ms] Authentication> Token is no longer valid for host https://github.org.com.
[Debug 849611s 159ms] PullRequestGitHelper> Get user created remotes - start
[Debug 849611s 828ms] PullRequestGitHelper> Get user created remotes - end
[Debug 849611s 828ms] GitHubRepository> Fetch metadata - enter
[Debug 849611s 949ms] Authentication> Token is no longer valid for host https://github.org.com.
[Debug 849665s 274ms] Error signing in to github.org.com: TypeError: Cannot set property 'text' of undefined
```

Obviously changed the github URL in the log ;)
