### ISSUE TITLE
Should use pointer cursor when hovering successful checks dropdown

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-pull-request-github#779]
ext version 1.7.1

Hovering this:

![image](https://user-images.githubusercontent.com/2193314/50786385-4250c880-1268-11e9-85b9-dcf48935fa51.png)

Will show the default cursor for the left part and the text cursor for the text, it should be to hand pointer to indicate it's interactive.

**Comment by RMacfarlane** [comment]
Should be fixed by https://github.com/Microsoft/vscode-pull-request-github/pull/775
