### ISSUE TITLE
Successful check avatar link goes somewhere unexpected

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-pull-request-github#781]
ext version 1.7.1

Clicking this:

![image](https://user-images.githubusercontent.com/2193314/50786601-dde23900-1268-11e9-945e-108c3152bbff.png)

Goes here: https://api.github.com/repos/Microsoft/vscode/statuses/42e3171a71ae4b6963e47318fd289a66eb48a96a

It should go to https://msght/ like on .com

**Comment by RMacfarlane** [comment]
Fixed by https://github.com/Microsoft/vscode-pull-request-github/commit/afe64bb41b8cd470bbcd8b8148e0648a84b06b1e, the API response doesn't contain a link to https://msght, just to the details of the check, so I'm using that url instead
