### ISSUE TITLE
Checks dropdown focus color is wrong

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-pull-request-github#783]
ext version: 1.7.1

Theme: https://marketplace.visualstudio.com/items?itemName=Tyriar.theme-sapphire

This border should either not show or be blue:

![image](https://user-images.githubusercontent.com/2193314/50786774-5ba64480-1269-11e9-8610-72fbfa279ed7.png)

Theme focus color:

![image](https://user-images.githubusercontent.com/2193314/50786787-63fe7f80-1269-11e9-81fa-ce28a5321a8c.png)

**Comment by RMacfarlane** [comment]
Should be fixed as there is now a Show/Hide button instead of a summary element.
