### ISSUE TITLE
Prompt when checking out another PR when there are pending comments

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#787]
ext version: 1.7.1

Repro:

1. Make a pending comment
2. Check out another PR

It feels like it would be very easy to forget about pending comments so a prompt might be a good idea. On .com I'll typically check the main PR page to make sure I've published the comments (https://github.com/Microsoft/vscode-pull-request-github/issues/786), it's harder here as they don't show up on that page.

**Comment by alexr00** [comment]
Pending comments do now show on the description page.
