### ISSUE TITLE
"Updating the comment failed: Not Found" if you checkout another branch before publishing the pending comment

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#788]
ext version: 1.7.1

Repro:

1. Make a pending comment
2. Checkout another branch
3. Checkout the original branch
4. Edit the comment

![image](https://user-images.githubusercontent.com/2193314/50787512-7aa5d600-126b-11e9-8dc4-2d770f1e821f.png)

**Comment by alexr00** [comment]
I'm not able to reproduce this now.
