### ISSUE TITLE
Seeing partial files when exploring a pull request

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode-pull-request-github#79]
Given the PR is from another branch in the same repository, could we not fetch from it as needed?

![image](https://user-images.githubusercontent.com/5047891/41967590-360fe622-7a02-11e8-86df-aa7d04dafa3e.png)

**Comment by RMacfarlane** [comment]
I duplicated this with https://github.com/microsoft/vscode-pull-request-github/issues/2070, this should now be fixed
