### ISSUE TITLE
Failing checks not showing up at all

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#790]
ext version: 1.7.1

I reloaded the window just to make sure it wasn't a sync issue.

Repro:

1. Checkout https://github.com/xtermjs/xterm.js/pull/1890
2. View description

PR:

![image](https://user-images.githubusercontent.com/2193314/50787980-e9376380-126c-11e9-8624-b7715f772a03.png)

.com:

![image](https://user-images.githubusercontent.com/2193314/50788030-0cfaa980-126d-11e9-96d8-d2da6fb03496.png)

output:

```
[Info] C:\Users\daimms.REDMOND\.ssh\config: ENOENT: no such file or directory, open 'C:\Users\daimms.REDMOND\.ssh\config'
[Info] Looking for git repository
[Info] Git repository found, initializing review manager and pr tree view.
[Info] No GitHub remotes found
[Info] No GitHub remotes found
[Info] Found GitHub remote
[Info] Review> current branch pr/juancampa/1890 is associated with pull request #1890
[Info] Review> register comments provider
[Info] Review> display pull request status bar indicator and refresh pull request tree view.
```

**Comment by RMacfarlane** [comment]
@Tyriar Are the checks in xtermjs GitHub actions? Wondering if this is the same as https://github.com/microsoft/vscode-pull-request-github/issues/1105

**Comment by Tyriar** [comment]
@RMacfarlane xterm.js only uses ADO pipelines now, I see this now:

![image](https://user-images.githubusercontent.com/2193314/90152343-92ddb100-dd3c-11ea-9d03-16c761c1520c.png)
