### ISSUE TITLE
Error when trying to load PR list

### ISSUE THREAD

**Issue by cobrabr** [microsoft/vscode-pull-request-github#795]
- Extension version: 0.3.2
- VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
- OS: Win7 x64

Steps to Reproduce:

1. Install GitHub Pull Requests extension.
2. Reload VS Code.
3. Follow all the sign-in steps to grant GitHub Enterprise permissions to the VS Code extension.

The extension shows the following (sanitized) error message whenever I open VS Code or try to refresh the **GitHub Pull Requests** tree:
```
Fetching pull requests for remote 'origin' failed, please check if the url git@github.com:XXXX/YYYY.git is valid.
```

No PRs ever show up on the tree, either.

The Output console shows the following (sanitized) messages:
```
[Debug 17144s 821ms] C:\Users\ZZZZ\.ssh\config: ENOENT: no such file or directory, open 'C:\Users\ZZZZ\.ssh\config'
[Debug 17144s 833ms] Looking for git repository
[Debug 17144s 833ms] Git repository found, initializing review manager and pr tree view.
[Debug 17144s 834ms] PullRequestManager> update repositories
[Debug 17144s 870ms] Found GitHub remote
[Debug 17145s 218ms] PullRequestGitHelper> Get user created remotes - start
[Debug 17145s 390ms] PullRequestGitHelper> Get user created remotes - end
[Debug 17145s 390ms] GitHubRepository> Fetch metadata - enter
[Debug 17145s 502ms] Unable to resolve remote: {"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/#get"}
[Debug 17145s 527ms] Review> no matching pull request metadata found for current branch master
[Debug 17186s 623ms] PullRequestGitHelper> Check if remote 'origin' is created for pull request - start
[Debug 17186s 654ms] GitHubRepository> Fetch all pull requests - enter
[Debug 17186s 770ms] GitHubRepository> Fetching all pull requests failed: {"message":"Not Found","documentation_url":"https://developer.github.com/v3/pulls/#list-pull-requests"}
```

The URL _is_ correct (it's the one we use regularly with everything else for that repo); `C:\Users\ZZZZ\.ssh\config` doesn't exist (neither as a folder nor as a file), and nothing else needs anything like that to access the repo.

**Comment by RMacfarlane** [comment]
Hmm, we display that error message when we receive a 404 when trying to fetch pull requests. Do you see this for expanding a particular category in the tree, or all of them? When signing in, were you able to use the "Sign In" button, or did you provide a personal access token?

**Comment by cobrabr** [comment]
I see it right as I open VS Code, and whenever I expand any category, including the "All" category, and was able to sign in using the "Sign In" button and approving access on GitHub.

**Comment by alexr00** [comment]
Closing now since we can't repro. Please feel free to ping if it is still happening.
