### ISSUE TITLE
Unable to open - Cannot read property 'fileOperationResult' of null.

### ISSUE THREAD

**Issue by scrossan-crown** [Microsoft/vscode-pull-request-github#797]
- Extension version: 0.3.2
- VSCode Version:Version: 1.31.0-insider (user setup)
- OS: Windows 10

Steps to Reproduce:

1. Check out a PR in review mode
2. Click a file in the `Changes In Pull Request` list

![image](https://user-images.githubusercontent.com/30405149/50818573-4a1f7400-131f-11e9-8e9c-aed96c895129.png)

**Comment by bm-stschneider** [comment]
I can confirm that this error still persist.

**Comment by RMacfarlane** [comment]
Fixed by https://github.com/Microsoft/vscode-pull-request-github/pull/920
