### ISSUE TITLE
Pull request template not working

### ISSUE THREAD

**Issue by tcigrand** [microsoft/vscode-pull-request-github#798]
Issue Type: <b>Bug</b>

I'm working in a repo with a [pull request template](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/) and the description doesn't get pre-populated with the template, like it does on GitHub.

Extension version: 0.3.2
VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:48:31.260Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (2.73GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by johndangerstorey** [comment]
I also run into this.  We have a template that would be nice to include when PR is created from VScode.  Thanks :)

**Comment by ammorrise** [comment]
Same here. It would be amazing to be able to edit the PR description before creating but at very least including PULL_REQUEST_TEMPLATE.md as the default description so it can be edited later is a must for me to be able to use this to create PRs.

**Comment by DocEmmetBrown** [comment]
I would enjoy having this feature too, it would be super helpful.
Thanks ! ;)

**Comment by RMacfarlane** [comment]
Just checked in a change for this, when creating a pull request, the extension will now look for a PR template and use it as the default description (or show a quick pick if the repo has multiple templates).

There are still open issues on improving the create experience to allow editing the title and description before create, so we still have work to do there.

**Comment by bmbermn** [comment]
Im not sure why but when I create PR's via VSCODE I am still not getting the template pulled in, is there anything I need to do to enable this functionality?

**Comment by RMacfarlane** [comment]
@bmbermn This is with version 0.12.0 of the extension? Can you open a new issue and include the name and relative location of your template to the root of the repository?
