### ISSUE TITLE
PR action buttons should not grow when title is long

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode-pull-request-github#799]
Issue Type: <b>Bug</b>

![image](https://user-images.githubusercontent.com/876920/50853812-33d1e200-1338-11e9-95da-b87ab8001853.png)

Extension version: 1.8.0
VS Code version: Code - Insiders 1.31.0-insider (7b375fcb821bee9342656c39492223c7b5fc8830, 2019-01-08T09:30:46.424Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.92GB (10.89GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by RMacfarlane** [comment]
Fixed with https://github.com/Microsoft/vscode-pull-request-github/pull/872
