### ISSUE TITLE
Unable to build extension

### ISSUE THREAD

**Issue by wsmelton** [Microsoft/vscode-pull-request-github#8]
I'm not an expert in node.js but trying to build this extension on my machine is failing and I'm not seeing red flag as to why.

Just running `npm install` when I'm in the cloned directory is showing multiple `ERR_STREAM_WRITE_AFTER_END` errors. I'm not sure if I'm just missing some pre-req packages or not.

The last bit of the log shows this information (attached the full log below):

```
10628 verbose stack Error [ERR_STREAM_WRITE_AFTER_END]: write after end
10628 verbose stack     at writeAfterEnd (_stream_writable.js:237:12)
10628 verbose stack     at PassThrough.Writable.write (_stream_writable.js:287:5)
10628 verbose stack     at PassThrough.Writable.end (_stream_writable.js:572:10)
10628 verbose stack     at ReadEntry.entry.on (C:\Users\wshaw\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\lib\extract-stream.js:19:41)
10628 verbose stack     at ReadEntry.emit (events.js:185:15)
10628 verbose stack     at ReadEntry.emit (C:\Users\wshaw\AppData\Roaming\npm\node_modules\npm\node_modules\tar\node_modules\minipass\index.js:296:25)
10628 verbose stack     at ReadEntry.[maybeEmitEnd] (C:\Users\wshaw\AppData\Roaming\npm\node_modules\npm\node_modules\tar\node_modules\minipass\index.js:249:12)
10628 verbose stack     at ReadEntry.end (C:\Users\wshaw\AppData\Roaming\npm\node_modules\npm\node_modules\tar\node_modules\minipass\index.js:162:27)
10628 verbose stack     at Unpack.[consumeBody] (C:\Users\wshaw\AppData\Roaming\npm\node_modules\npm\node_modules\tar\lib\parse.js:210:13)
10628 verbose stack     at Unpack.[consumeChunkSub] (C:\Users\wshaw\AppData\Roaming\npm\node_modules\npm\node_modules\tar\lib\parse.js:391:40)
10628 verbose stack     at Unpack.[consumeChunk] (C:\Users\wshaw\AppData\Roaming\npm\node_modules\npm\node_modules\tar\lib\parse.js:362:30)
10628 verbose stack     at Unzip.(anonymous function).on.chunk (C:\Users\wshaw\AppData\Roaming\npm\node_modules\npm\node_modules\tar\lib\parse.js:291:59)
10628 verbose stack     at Unzip.emit (events.js:180:13)
10628 verbose stack     at Unzip.emit (C:\Users\wshaw\AppData\Roaming\npm\node_modules\npm\node_modules\tar\node_modules\minipass\index.js:296:25)
10628 verbose stack     at Unzip.write (C:\Users\wshaw\AppData\Roaming\npm\node_modules\npm\node_modules\tar\node_modules\minipass\index.js:99:17)
10628 verbose stack     at Unzip.write (C:\Users\wshaw\AppData\Roaming\npm\node_modules\npm\node_modules\tar\node_modules\minizlib\index.js:284:29)
10629 verbose cwd C:\git\vscode-pull-request-github
10630 verbose Windows_NT 10.0.17134
10631 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\wshaw\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
10632 verbose node v9.8.0
10633 verbose npm  v6.0.1
10634 error code ERR_STREAM_WRITE_AFTER_END
10635 error write after end
10636 verbose exit [ 1, true ]
```

[2018-06-18T03_34_25_649Z-debug.log](https://github.com/Microsoft/vscode-pull-request-github/files/2109825/2018-06-18T03_34_25_649Z-debug.log)

**Comment by RMacfarlane** [comment]
@wsmelton Try downgrading to `npm@5.6.0`, I think that should fix it. I'll add a note to the README if it does

**Comment by wsmelton** [comment]
Removed 6.0.1 and installed 5.6.0 but doing `npm install` gives me this error:

C:\Users\wshaw\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js:79
      let notifier = require('update-notifier')({pkg})
      ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:140:18)
    at node.js:1001:3

**Comment by RMacfarlane** [comment]
Hmm, what did you do to remove and install? Are you using anything like https://github.com/coreybutler/nvm-windows?

Do you get the same error when you do `npm -v`?

**Comment by wsmelton** [comment]
I went into Apps and Features and uninstalled Node.js. Downloaded the 5.6.0 package for x64 Windows and ran the install.

Yeah the same error shows up for `npm -v`.

**Comment by wsmelton** [comment]
I downloaded node.js from here: https://nodejs.org/en/download/releases/

**Comment by RMacfarlane** [comment]
Well, I'm glad it's working for you now but I'm not entirely sure how it got fixed :)

Here's the issue tracking the original error in npm: https://github.com/npm/npm/issues/19989

Out of curiosity, does `node -v` still print v9.8.0 for you?

**Comment by wsmelton** [comment]
I get `v8.11.3` as output.

**Comment by wsmelton** [comment]
![image](https://user-images.githubusercontent.com/11204251/41573288-9e6932ea-7341-11e8-8264-3d3ed30f759a.png)
