### ISSUE TITLE
"outdated" comments merged into one thread

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-pull-request-github#801]
Name: GitHub Pull Request Nightly Build
Version: 1.9.0

- Checked out this PR: https://github.com/Microsoft/vscode-chrome-debug-core/pull/388
- We created a few comment threads
- The PR branch was updated and force-pushed
- Now some of the comment threads appear merged into one:

![image](https://user-images.githubusercontent.com/323878/50935509-1c225880-1421-11e9-9849-7aa032b5ca33.png)

Not sure if this is because they are "outdated" threads or because of the force-push

**Comment by alexr00** [comment]
Seems to have been fixed in the intervening years:

![image](https://github.com/microsoft/vscode-pull-request-github/assets/38270282/7ad20d8f-0498-4292-82b8-d4c6d6527f52)
