### ISSUE TITLE
Show current repository name in panel bar

### ISSUE THREAD

**Issue by tom-thorne** [microsoft/vscode-pull-request-github#805]
When working with multiple repositories in a window, the standard git panel bar shows the current repo name - see image.

It would be great if the GITHUB PR panel bar did too. 

Why? I have found that the PR panel may not be displaying the correct repo, or any repo, especially if there are network or auth issues, or just after launch. Currently the only way of telling if it is looking at the correct repo is to click the '+' button

<img width="273" alt="screen shot 2019-01-10 at 11 29 52" src="https://user-images.githubusercontent.com/20596930/50965841-1719e380-14cb-11e9-9cff-b0865856455e.png">

**Comment by RMacfarlane** [comment]
This has been fixed as part of https://github.com/microsoft/vscode-pull-request-github/issues/1936, now if multiple repos are open, there should be a separate tree item for each in the pull requests view. Thanks!
