### ISSUE TITLE
Links overflow the description comment box

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-pull-request-github#806]
This is the nightly extension version

- Open the description page for this PR: https://github.com/Microsoft/vscode/pull/66189
- Make the window a bit narrow
- Links in comments can overflow:

![image](https://user-images.githubusercontent.com/323878/50984346-8b965780-14b6-11e9-953e-d79cd8a6c228.png)

**Comment by lifez** [comment]
I will take this
