### ISSUE TITLE
Chrome OS cannot login

### ISSUE THREAD

**Issue by DBiles** [microsoft/vscode-pull-request-github#808]
- Extension version: 0.3.2
- VSCode Version: 1.30.2
- OS: Chrome OS
 
Steps to Reproduce:

1. Open desired Github repo
2. Presented with Github login redirect
3. Click Sign in
4. Click Continue to authorize VScode to access Github
5. The message displayed Chrome OS can't open the page

![screenshot 2019-01-10 at 7 11 21 pm](https://user-images.githubusercontent.com/11972764/51005817-73522700-150e-11e9-94e0-a7f168aea8ad.png)

**Comment by DBiles** [comment]
Issue does allow a successful login now but not a successful redirect

**Comment by cellx** [comment]
Still same issue with newer version: 

```
Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:22.494Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 4.19.98-08076-g24ab33fb8e14
```

**Comment by jonassch2903** [comment]
I installed the Opera Browser and Gnome Keyring.
https://www.opera.com/de/download
sudo apt install gnome-keyring 
Then the tab opens in the other browser and it worked for me.

**Comment by xoxocactus** [comment]
omgggggggggggggggggggggg

**Comment by xoxocactus** [comment]
wtffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 
sameeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
ughhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh

**Comment by peace-blaster** [comment]
Same issue with brand new device
