### ISSUE TITLE
Overview page out of sync after merge

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-pull-request-github#809]
Issue Type: <b>Bug</b>

I merged  a pull request I had not checked out from the overview page. 
First the tree view still showed the PR but without file changes. After a while the tree view cleared out. However, the overview page showed the following:

![image](https://user-images.githubusercontent.com/4674940/51006364-a9d07780-14f7-11e9-8c82-8b8ec67e0b22.png)

The PR page one GH showed that the PR was merged successfully.

Extension version: 1.9.0
VS Code nightly
OS version: Darwin x64 18.0.0

**Comment by alexr00** [comment]
This appears to be fixed now.
