### ISSUE TITLE
Two separate comments merged into a single comment

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode-pull-request-github#81]
https://github.com/Microsoft/vscode/pull/52812

![image](https://user-images.githubusercontent.com/5047891/41967762-ae68ad02-7a02-11e8-9288-cd2942963b77.png)

![image](https://user-images.githubusercontent.com/5047891/41967782-b8fb4a22-7a02-11e8-85fe-3cd13a59ba65.png)

**Comment by rebornix** [comment]
My current fix is drawing corresponding diff hunk for the second comment but if someone leaves more comments in a review, they will not be displayed as right now we don't have a straight forward API to fetch them.
