### ISSUE TITLE
Create PR - "choose target branch" should show list of branches

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-pull-request-github#814]
- Create PR
- Try to send PR to a branch with a long name that isn't `master`
- I have to copy/paste it or type from memory.

I should see a list of branches like "Git: Checkout to..."

![image](https://user-images.githubusercontent.com/323878/51051922-0aa89000-158a-11e9-9dbc-9c8a445f7e59.png)

**Comment by mix3d** [comment]
Def bumping this one. If VSCode has access to it as part of the native VCS implementation, wouldn't there be an API to grab that list with?

**Comment by burkeholland** [comment]
This one is kinda old so bumping it with a comment @RMacfarlane. When working against a feature branch with a long name, it's easy to mess this up or forget it. I've done it 3 times today already.

**Comment by bm-stschneider** [comment]
I create branches with the Jira integration, I always have to copy the branch names from github if I want to make a PR to a feature branch instead of master.
