### ISSUE TITLE
Missing remote from create PR flow

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-pull-request-github#815]
- Create new branch
- Do Create PR flow
- On the step "Pick a remote to publish the branch to:", I only see 2 of my 3 remotes:

![image](https://user-images.githubusercontent.com/323878/51052056-6d9a2700-158a-11e9-934e-ac5f8fd1499b.png)

```
$ git remote -v
digeff  git@github.com:digeff/vscode-chrome-debug-core.git (fetch)
digeff  git@github.com:digeff/vscode-chrome-debug-core.git (push)
origin  git@github.com:Microsoft/vscode-chrome-debug-core.git (fetch)
origin  git@github.com:Microsoft/vscode-chrome-debug-core.git (push)
robl    git@github.com:roblourens/vscode-chrome-debug-core.git (fetch)
robl    git@github.com:roblourens/vscode-chrome-debug-core.git (push)
```

Why doesn't the third one appear?

@RMacfarlane @rebornix I can show you my setup if you can't repro it.

**Comment by RMacfarlane** [comment]
Should be fixed as part of https://github.com/microsoft/vscode-pull-request-github/commit/34a23f9d8e8e32edf802b96f128504668cb8e701
