### ISSUE TITLE
Hide creating review button in existing threads

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-pull-request-github#817]
Issue Type: <b>Bug</b>

On .com we can create a new review under an existing comment thread, however the core now has no way to control the when to show the buttons or not.

Extension version: 1.11.1
VS Code version: Code - Insiders 1.31.0-insider (ccdd2997a66965c7104fe180207d9a710ea50fa5, 2019-01-11T06:13:56.256Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.18GB free)|
|Process Argv|-psn_0_8169418|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by RMacfarlane** [comment]
This should already be fixed with the latest commenting API
