### ISSUE TITLE
GH PR tree is broken

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode-pull-request-github#820]
Issue Type: <b>Bug</b>

See screenshot. There is only one PR. In some branches it can be expanded, in others it can't.

![image](https://user-images.githubusercontent.com/4674940/51214113-da3a5c00-18d1-11e9-8d65-68071070ce47.png)

Extension version: 1.14.0
VS Code version: Code - Insiders 1.31.0-insider (b4fc71b972eae2425d39ac4041df0c36cfa1bb37, 2019-01-15T06:12:40.322Z)
OS version: Darwin x64 18.0.0

**Comment by rebornix** [comment]
Fixed in Nightly 1.14.1 . It's an `noImplicitAny` bug and we should guarantee that we don't run into this sort of issue again, will send a pr out for adding `noImplicitAny: true`.
