### ISSUE TITLE
Unable to comment on PR

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-pull-request-github#83]
I made a comment and nothing happened. Here's the UI after the comment:

![image](https://user-images.githubusercontent.com/2193314/41981577-182cad44-79de-11e8-95bf-b9c4a62f8ba6.png)

**Comment by Tyriar** [comment]
Another one that didn't go through on GH

![image](https://user-images.githubusercontent.com/2193314/41981670-510da924-79de-11e8-87c5-6165032c7d94.png)

**Comment by Tyriar** [comment]
May be related to https://github.com/Microsoft/vscode-pull-request-github/issues/82

**Comment by Tyriar** [comment]
It made all these comments on a different PR on unrelated lines (PR 1525):

![image](https://user-images.githubusercontent.com/2193314/42050969-631f2d04-7abf-11e8-903a-403873fc90f9.png)

**Comment by RMacfarlane** [comment]
This should be fixed by https://github.com/Microsoft/vscode-pull-request-github/commit/ac934843c5023bd83e98cd20e546d2286976ab99
