### ISSUE TITLE
dont get notification

### ISSUE THREAD

**Issue by MathiasAC** [Microsoft/vscode-pull-request-github#835]
Issue Type: <b>Bug</b>

i dont get notification when i install and reload Github Pull Requests
so i cant add my github account

Extension version: 0.3.2
VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|23.95GB (18.67GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by RMacfarlane** [comment]
@MathiasAC What's the result of running `git remote -v` in the folder you have open? Can you paste the text shown in the Output panel when GitHub Pull Request is selected from the dropdown?

**Comment by MathiasAC** [comment]
@RMacfarlane the result of running git remote -v  is "The term 'git' is not recognized"
but I can't connect my vs code account with my GitHub account
so I don't get the GitHub Pull Request stuff

**Comment by RMacfarlane** [comment]
To use the extension, you need to have git installed locally. You can download it here: https://git-scm.com/download/win

The prompt to sign in will show up when the extension detects that the folder you are in is under `git` source control, and that a remote for it is associated with `GitHub`. I'll update the README to include this
