### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by st-schneider** [microsoft/vscode-pull-request-github#841]
- Issue Type: `Performance`
- Extension Name: `vscode-pull-request-github`
- Extension Version: `0.3.2`
- OS Version: `Darwin x64 17.7.0`
- VSCode version: `1.31.0-insider`\
[GitHub.vscode-pull-request-github-unresponsive.cpuprofile.txt](https://github.com/Microsoft/vscode-pull-request-github/files/2802387/GitHub.vscode-pull-request-github-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by paustint** [comment]
I have been having problems with this as well and I was able to capture a CPU profile while I had 100% CPU from this extension. I was not even using the extension at all, so it was running in the background and looks like it was stuck in garbage collection. The profile was for about 10-20 seconds.

[CPU-20200318T155400.148Z.cpuprofile.txt](https://github.com/microsoft/vscode-pull-request-github/files/4349967/CPU-20200318T155400.148Z.cpuprofile.txt)

**Comment by brianminsk** [comment]
Same issue. I've attached the automatically generate profile.
VSCode version: 1.46.0

[GitHub.vscode-pull-request-github-unresponsive.cpuprofile.txt](https://github.com/microsoft/vscode-pull-request-github/files/4790479/GitHub.vscode-pull-request-github-unresponsive.cpuprofile.txt)

**Comment by edoardo-molinatti** [comment]
Same here on Windows 10

Version: 1.62.3 (system setup)
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T08:11:14.551Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044

[GitHub.vscode-pull-request-github-unresponsive.cpuprofile.txt](https://github.com/microsoft/vscode-pull-request-github/files/7625791/GitHub.vscode-pull-request-github-unresponsive.cpuprofile.txt)

**Comment by amigowifigh** [comment]
awgh

**Comment by DillonB07** [comment]
Same issue here on macOS:

<details>
<summary>System details</summary>

Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:37:28.172Z (4 days ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 19.6.0 - _macOS Catalina 10.15.7_
</details>

Gist - https://gist.github.com/DillonB07/5ae1a3259f1d789d08469f33db39be93

**Comment by alexr00** [comment]
I've started looking through several of the profiles in this issue (thanks everyone who added one!). The high CPU seems to occur when several extensions are activating at once. ritwickdey.liveserver in particular seems to coincide with the high CPU, so folks who have that installed might try disabling it.

Is everyone seeing this high CPU associated with GitHub Pull Requests and issues shortly after starting or reloading VS Code?

**Comment by DillonB07** [comment]
Yes. I do have the liveserver extension installed but I'll try disabling that and see how it works.

I am seeing the issue after starting/reloading VSC though.

**Comment by DillonB07** [comment]
However, disabling the liveserver extension didn't seem to help. 

CPU Log - https://gist.github.com/DillonB07/72bef869458babec53e19efd0127373b

**Comment by alexr00** [comment]
Thanks for trying that @DillonB07 and for the new profile. After further digging, it looks like one of the modules we include may be slow (https://www.npmjs.com/package/vscode-extension-telemetry). I'm following up with the owners to see if that's the case and if it can be improved.

**Comment by alexr00** [comment]
Module has been updated, and I've pulled the update in to this extension.

The [pre-release build](https://github.com/microsoft/vscode-pull-request-github/wiki/Pre-release-Build) will have the fix tomorrow (the version number will be 0.35.20211228*). If folks in this thread could try it out after that build is ready tomorrow and comment your results it would help confirm whether we've tracked the perf issue down or if the issue should be reopened for further investigation.

**Comment by alexr00** [comment]
Once I get confirmation that the perf issue is fixed from someone in this thread, I'll release 0.34.3 with the change!

**Comment by DillonB07** [comment]
I haven't got the issue anymore. Seems like it's fixed.

Thanks!

**Comment by alexr00** [comment]
Thanks @DillonB07, I'll release 0.34.3 with the fix.
