### ISSUE TITLE
Incredibly hard to get into review mode

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-pull-request-github#848]
Refs: https://github.com/Microsoft/vscode/issues/67294

I find it incredibly hard from a ux perspective to get into review mode.
The main issue I find is that I can not do this from the main description page. I understand that GitHub also does not allow this but we should have at least some affordance on how to go from the main description page to the "file review mode".
I would expect to see my pending comments and be able to navigate to them from the description page.

I think this should be presented in a UX meeting where we could think alltogether more about this.

fyi @misolori

**Comment by alexr00** [comment]
A few things that should already have made this better:
- You can check out a PR from the description page
- You can open file comments from the description page.
