### ISSUE TITLE
GraphQL Error: no correct permissions

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-pull-request-github#849]
Refs: https://github.com/Microsoft/vscode/issues/67294

When I try to edit a pending review comment I get the following error.
I got into this state by starting a review on this PR from VSCode https://github.com/auchenberg/pullrequest-demo/pull/29
Adding a review comment in GitHub website and trying to uptate that comment in VSCode.

![screenshot 2019-01-29 at 12 49 07](https://user-images.githubusercontent.com/1926584/51906402-5c437e00-23c4-11e9-8c9a-05221af96824.png)

**Comment by gregvanl** [comment]
Hit this as well +1

**Comment by rebornix** [comment]
@queerviolet does our GraphQL API requires more scopes than the REST API? I'm wondering if we didn't ask for enough scopes previously.

**Comment by alexr00** [comment]
Closing as scopes have since changed.
