### ISSUE TITLE
Reply... font looks too small

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode-pull-request-github#851]
Refs: https://github.com/Microsoft/vscode/issues/67294

![screenshot 2019-01-29 at 12 51 43](https://user-images.githubusercontent.com/1926584/51906559-a7f62780-23c4-11e9-8d4d-0fab63cbb002.png)

Especially since when I click in the reply... area the font completely changes and the Reply looks huge

**Comment by misolori** [comment]
Fixed via https://github.com/Microsoft/vscode/commit/16e58d25d008976c8a36867f4b638c07f750794e
