### ISSUE TITLE
Finish review vs Request Changes

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-pull-request-github#853]
Refs: https://github.com/Microsoft/vscode/issues/67294

In the UX in the editor the action is called `Finish Review`, while in the description it is called `Request Changes`.
I do not understand the exact difference.
Also what does Finish Review actually do?

IMHO it is not easy to differentiate between the two and should we actually have two different actions?
This just contributes to the overall confusion in the UX imho

**Comment by RMacfarlane** [comment]
Closing from https://github.com/microsoft/vscode-pull-request-github/pull/2670, have removed the `Finish Review` button in favor of an `Open Review` button which shows the whole review in the description page where there are "Approve", "Request Changes", and "Comment" options
