### ISSUE TITLE
Comment widget focus needs a lot of improvment

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-pull-request-github#855]
Refs: https://github.com/Microsoft/vscode/issues/67294

PR extension in a lot of cases wrongly treats focus. Not sure if there is more we could do here but the focus eaisly gets lost.

Some examples:
1. Pressing escape while comment box is empty
2. Clicking on the + in the glyph margin - the focus should pass to the comment box
3. Clicking on a comment I am unable to up / down to go thourhg all comments

**Comment by alexr00** [comment]
Tried this out and all three focus issues appear to be fixed.
