### ISSUE TITLE
Changes in pull request does not show changed files

### ISSUE THREAD

**Issue by misolori** [Microsoft/vscode-pull-request-github#863]
Issue Type: <b>Bug</b>

Refs: https://github.com/Microsoft/vscode/issues/67297

The PR in question is only changing two files. In the regular viewlet the files are shown not in the other when a pr is checked out.

![image](https://user-images.githubusercontent.com/35271042/51934137-c73a8800-23b7-11e9-8b43-ef4033591c2c.png)

<img width="330" alt="image" src="https://user-images.githubusercontent.com/35271042/51934069-9e19f780-23b7-11e9-803c-adb6331c7c00.png">

Extension version: 1.29.0
VS Code version: Code - Insiders 1.31.0-insider (acc7365e41f9cb380e79bf78d7d102184f1ffe0d, 2019-01-29T06:13:57.866Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|22%|

</details>

**Comment by RMacfarlane** [comment]
Fixed with https://github.com/Microsoft/vscode-pull-request-github/commit/d851c01cad7579294799680fe731874dafe9d24a
