### ISSUE TITLE
Auto-detect npm project upstream repositories

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#864]
microsoft/vscode#67294

Consider checking for a package.json and reading the `repository` entry to discover the upstream repository automatically:

https://github.com/xtermjs/xterm.js/blob/cc531f19334f735b2aa0b0785afbfb0494a17e90/package.json#L7

(or [homepage](https://docs.npmjs.com/files/package.json#homepage))

**Comment by alexr00** [comment]
We do some checking to find your upstream repository now.
