### ISSUE TITLE
Cannot view PRs

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#865]
https://github.com/Microsoft/vscode/issues/67294

Not sure if I'm doing something wrong here but I can't see PRs. I have this checked out: https://github.com/Tyriar/pullrequest-demo

![image](https://user-images.githubusercontent.com/2193314/51938224-7334a100-23c1-11e9-9ae8-eab985a63613.png)

I added the upstream and it's definitely detected when I click new PR:

![image](https://user-images.githubusercontent.com/2193314/51938268-89426180-23c1-11e9-9f07-800b708c4a34.png)

Remotes:

```
$ git remote -v
origin  https://github.com/Tyriar/pullrequest-demo (fetch)
origin  https://github.com/Tyriar/pullrequest-demo (push)
ups     https://github.com/auchenberg/pullrequest-demo (fetch)
ups     https://github.com/auchenberg/pullrequest-demo (push)
```

Output:

```
[Info] /home/daniel/.ssh/config: ENOENT: no such file or directory, open '/home/daniel/.ssh/config'
[Info] Looking for git repository
[Info] Git repository found, initializing review manager and pr tree view.
[Info] No GitHub remotes found
[Info] Review> no matching pull request metadata found for current branch master
[Info] Found GitHub remote
[Info] Found GitHub remote
[Info] Review> no matching pull request metadata found for current branch master
[Info] Review> no matching pull request metadata found for current branch master
```

**Comment by pgonzal** [comment]
Check the bottom status bar of the VS Code window to see if you are logged into GitHub.  When you first install the extension, it asks you to provide your VS Code password in a very non-obvious way.  It took me a while to figure that out...

**Comment by Tyriar** [comment]
It was related to a recent change that needs you to set `githubPullRequests.remotes` when your remote is not "origin" or "upstream"

**Comment by rebornix** [comment]
@RMacfarlane We can be smart when checking `upstream`, by finding the parent of `origin` if it's a fork.

**Comment by Tyriar** [comment]
That would be even better if you can get to that 👍

**Comment by alexr00** [comment]
We find the parent of `origin` when it is a fork in many cases now.
