### ISSUE TITLE
No way to edit the file being diffed

### ISSUE THREAD

**Issue by octogonz** [microsoft/vscode-pull-request-github#868]
- Extension version: 0.3.2
- VSCode Version: 1.30.2
- OS: OS X

Steps to Reproduce:

1. Edit a file, commit your change, and push it, and create a new PR
2. In the "GITHUB PULL REQUESTS" pane, find your PR
3. Click on the edited file to display the diff
4. Decide you want to edit this file

**Expected:** There should be a button or command or something that opens up your local copy of that file in the editor, ideally positioning your cursor on the closest location to wherever you clicked in the diff view

**Actual:** I need to examine the relative path shown in the file tab for the diff, and then manually dig around in the project tree to open that source file.

**Comment by pgonzal** [comment]
BTW I noticed that if I right+click on the file in the GITHUB PULL REQUESTS pane, there is an option for "Open File in GitHub".  Why doesn't that menu have an option for "Open File locally"?

**Comment by mledom** [comment]
Looks like there is a PR for that already @octogonz [PR589](https://github.com/Microsoft/vscode-pull-request-github/pull/589)

**Comment by Simran-B** [comment]
This would actually be the only feature of the extension that would make it useful for me, but the PR is pending since months 😞

**Comment by RMacfarlane** [comment]
Making this work is a bit more involved than the open PR, I think @adrian-ci is correct about what the proper behavior would be.

To explain a bit about the diff that’s shown - to open it, the extension passes two different URIs to the documents it wants to open. These URIs can either be to a file that’s on actually on a disk, something like file://some/path, or a URI with some custom scheme, like pr://some/path. If the URI has a custom scheme, VSCode will look to see if there is a content provider that has been registered to supply the actual text for such files. For the “GitHub Pull Requests” tree, the files we open are all “pr” scheme and the extension actually supplies the file contents for them. This handles when you don’t have the pull request checked out, i.e. you don’t have the correct version of the file/may not even have pulled the commit that its part of. If you do have the PR checked out, we show the additional “Changes in Pull Request” tree, which does actually open the local file on the right hand side of the diff editor, which is editable. So to properly fix this, we would need to mimic that behavior, and use the local file URI when opening the diff when the PR is already checked out.

**Comment by melink14** [comment]
I'm also looking forward to this change but curious about what RMacfarlane meant wrt "Changes in Pull Request" tree.

In my Pull Requests section the checked out PR lists all the files changed but none of them can be opened in an editable fashion... am I looking in the wrong place?

Thanks for looking!

**Comment by MetRonnie** [comment]
In the source control pane there is a straightforward option in the context menu to open file (locally).

![image](https://user-images.githubusercontent.com/61982285/142027367-824af627-d829-4c95-ae8f-e8e76f43363d.png)

This is sorely missing from the GitHub pane - the only options only open read-only versions of the file. 

![image](https://user-images.githubusercontent.com/61982285/142027439-c17452ae-6dd0-42b0-828f-e8b72aae3fbe.png)

**Comment by alexr00** [comment]
If you are already on the PR branch then this has worked for a while. Additionally, if you aren't on the PR branch you will see a message when you try to edit the read only file prompting you to check out the PR.

**Comment by octogonz** [comment]
> If you are already on the PR branch then this has worked for a while. Additionally, if you aren't on the PR branch you will see a message when you try to edit the read only file prompting you to check out the PR.

Great, thanks! 👍
