### ISSUE TITLE
githubPullRequests.remotes default value should be []

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#869]
Microsoft/vscode#67294

It would make it more clear what to do here:

![image](https://user-images.githubusercontent.com/2193314/51941117-a4fd3600-23c8-11e9-907a-15d0d45e51c1.png)

Then just treat [] the same as null now?

**Comment by RMacfarlane** [comment]
The default has been changed to ["origin", "upstream"]
