### ISSUE TITLE
Never exiting "Switching to Review Mode", comments all on same line

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-pull-request-github#87]
No errors in console, I can't seem to fully get into review mode on my mac.

<img width="855" alt="screen shot 2018-06-30 at 9 39 37 am" src="https://user-images.githubusercontent.com/2193314/42127254-96b84c96-7c49-11e8-9ebc-5fbb53c13df9.png">

**Comment by RMacfarlane** [comment]
Can you paste any content from the "GitHub Pull Request" output channel?

**Comment by Tyriar** [comment]
Will do if I see it again

**Comment by kieferrm** [comment]
Can't reproduce.
