### ISSUE TITLE
Allow setting title and description when creating PR

### ISSUE THREAD

**Issue by peacememories** [microsoft/vscode-pull-request-github#880]
Thanks for creating this great timesaver of an extension. :)

Right now when I create a PR using this extension I first create it, then change the title and description. This is fine for the most part, but a few of our Waffle hooks don't fire when editing the description, which means I have to go to the dashboard and drag issues around. It would be much nicer to be able to create the PR with the right title and description in the first place :)

**Comment by phifa** [comment]
https://github.com/microsoft/vscode-pull-request-github/issues/906

**Comment by grm34** [comment]
It's ok for title but seems not for description (or i forgot something?).

**Comment by alexr00** [comment]
Yes, this is done for the title now. For description, we will leave it as is.
