### ISSUE TITLE
Commenting ranges don't appear on file changes in PR tree on checked out node

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode-pull-request-github#883]
Issue Type: <b>Bug</b>

1. Check out a pull request
2. Open a file change using the GitHub Pull Requests tree for that PR

No comments/commenting ranges are shown

Extension version: 1.30.0
VS Code version: Code - Insiders 1.31.0-insider (2c987b20a4d65ee51c48b9e4eb8f50c926199468, 2019-01-30T06:17:39.118Z)
OS version: Darwin x64 18.0.0

**Comment by Tyriar** [comment]
Happened to me too:

![image](https://user-images.githubusercontent.com/2193314/51996759-3f618600-246a-11e9-8787-4b530ef340c2.png)

**Comment by RMacfarlane** [comment]
Looks like the root cause is the same as https://github.com/Microsoft/vscode-pull-request-github/issues/876, will be fixed when https://github.com/Microsoft/vscode-pull-request-github/pull/877 is merged
