### ISSUE TITLE
Description buttons get very fall when header wraps

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-pull-request-github#884]
https://github.com/Microsoft/vscode/issues/67509

![image](https://user-images.githubusercontent.com/2193314/51996803-5a33fa80-246a-11e9-90e5-8ea67ef897c3.png)

**Comment by Tyriar** [comment]
Variant on this:

![image](https://user-images.githubusercontent.com/2193314/51998607-d2e88600-246d-11e9-8098-a07664cbd3df.png)

**Comment by RMacfarlane** [comment]
Duplicate of https://github.com/Microsoft/vscode-pull-request-github/issues/850
