### ISSUE TITLE
Discussion button style is inconsistent

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-pull-request-github#885]
https://github.com/Microsoft/vscode/issues/67509

![image](https://user-images.githubusercontent.com/2193314/51996973-ada64880-246a-11e9-8f95-5660da5e7e90.png)

I think we use sharp edges everywhere?

![image](https://user-images.githubusercontent.com/2193314/51997008-beef5500-246a-11e9-8d74-6ba8177ef5ef.png)

**Comment by RMacfarlane** [comment]
Fixed by https://github.com/Microsoft/vscode/commit/498eb67b0c2d7bd29f8a724d619675a18a988687
