### ISSUE TITLE
Emoji don't render in diff view

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#887]
https://github.com/Microsoft/vscode/issues/67509

![image](https://user-images.githubusercontent.com/2193314/51997212-2907fa00-246b-11e9-8d28-24a57a0a6753.png)

vs description:

![image](https://user-images.githubusercontent.com/2193314/51997250-37eeac80-246b-11e9-9a66-dc43a268a6e0.png)

**Comment by rebornix** [comment]
That's GitHub specific syntax and our editor doesn't understand that, probably we should convert that to emojis before we send the markdown content to VSCode.

**Comment by alexr00** [comment]
Just added this!
