### ISSUE TITLE
Disallow approve/request on own PR

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#888]
https://github.com/Microsoft/vscode/issues/67509

.com:

![image](https://user-images.githubusercontent.com/2193314/51997341-62406a00-246b-11e9-995d-3e3953cf138f.png)

When I hit request changes:

![image](https://user-images.githubusercontent.com/2193314/51997378-784e2a80-246b-11e9-96ec-b17f0b78ecbf.png)

**Comment by Tyriar** [comment]
This applies to both the review buttons and the overall PR buttons

**Comment by saif003** [comment]
There is no setting or configuration which allows modifying this restriction?
I do understand this is against the essence of PRs but since github's UI does allow authors to approve their own PRs, I believe there should be some sort of configurability which allows turning this off.

**Comment by Tyriar** [comment]
@saif003 this is a bug in the extension imo, request changes shouldn't be an option or it should give a nicer error message.

**Comment by saif003** [comment]
@Tyriar agreed on request changes option but regarding approving, I think that should be configurable.

**Comment by Tyriar** [comment]
@saif003 GitHub doesn't work like that so the extension could not allow it if it wanted to.

**Comment by saif003** [comment]
@Tyriar i'm not sure what do you mean by,

> GitHub doesn't work like that 

because I'm able to approve and merge my own PRs, 
![Screenshot (1023)](https://user-images.githubusercontent.com/36731927/68377023-7a1beb80-016b-11ea-9fa4-89772cba341d.png)

semantically does approve here means some thing else?

**Comment by Tyriar** [comment]
That screenshot is just showing the merge button, approve is greyed out as shown in the top screenshot:

![image](https://user-images.githubusercontent.com/2193314/68404540-900dba00-0133-11ea-9bc7-fb7debf44a09.png)

**Comment by saif003** [comment]
@Tyriar my bad you are right,

**Comment by Merovex** [comment]
Then, why can't I "Merge Pull Request" from this extension? It seems the extension is limited to code reviews, not the full monty.

**Comment by Tyriar** [comment]
@Merovex ?

![image](https://user-images.githubusercontent.com/2193314/84074078-d3a8fa80-a986-11ea-9916-6384975eaef4.png)

I'm on the Insiders version but I think the extension has been able to do this for a long time.

**Comment by Merovex** [comment]
Okay, so I created a pull request on GH, then pulled it. I tried to approve it and got the same error message as displayed in this screenshot. Unable to approve own pull request. Now, if there is a configuration to nerf that, or if it's an "Insider" thing, then how do I get there?  I'm still fairly new to VSC...though I started with VIM 20 years ago and figured that out, so...

<img width="806" alt="screenshot of inability to approve own pull request" src="https://user-images.githubusercontent.com/108851/84206371-ffa6a780-aa7c-11ea-8818-041a468cad9d.png">

**Comment by JamesGosling** [comment]
This change has a problem: I'm working on a project that only has one active engineer working on it.  There are many people on the team, but that team spans many repositories.  If I want to fix bugs through the issue mechanism, I need to create a PR and have it approved to close it cleanly.  But now I can't do that with fix #888. I have to find some random engineer in the team, who doesn't know the code, to push the "approve" button.  A proper fix to #888 would have added a setting to control this behavior.

**Comment by RMacfarlane** [comment]
@JamesGosling I'm unsure how this was working for you before - GitHub should throw an error when you try to approve your own pull request. Was it not erroring before when you did this in the extension? These buttons are also disabled on GitHub.com:
<img width="466" alt="Screen Shot 2021-05-07 at 8 08 01 AM" src="https://user-images.githubusercontent.com/3672607/117470191-63df1f00-af0b-11eb-94c0-6113d229c225.png">

**Comment by jaypatrick** [comment]
I know this is an old thread, but I wanted to chime in that I find it utterly ridiculous that PR submitters cannot approve their own PR's. We have dozens of projects with only one developer on them (Think: maintenance mostly), and we *must* follow the standard PR lifecycle as part of our contracts with clients/customers. Having to get an admin to approve "already approve" PR's is an enormous time waster, and then how do we explain the line items in billing for admin PR approvals?

We were going to start migrating hundreds of projects from Azure to Github, but this is a complete dealbreaker for us. Thus, you will not be getting our business or our money until you lift this requirement.
