### ISSUE TITLE
Check write access before showing merge PR button

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#889]
https://github.com/Microsoft/vscode/issues/67509

.com:

![image](https://user-images.githubusercontent.com/2193314/51997527-c105e380-246b-11e9-87f6-fe5939d0e24a.png)

ext:

![image](https://user-images.githubusercontent.com/2193314/51997501-b64b4e80-246b-11e9-900e-38980daf1e42.png)

Error when merging:

![image](https://user-images.githubusercontent.com/2193314/51997550-cf53ff80-246b-11e9-8d7b-e209e0b41652.png)

**Comment by RMacfarlane** [comment]
This has already been fixed with https://github.com/microsoft/vscode-pull-request-github/commit/1f8901776fdb0a88e54b40c268df88980d08ac2e
