### ISSUE TITLE
Confusing looking at comments from older commits

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#89]
Some UX feedback. I was reviewing this PR https://github.com/xtermjs/xterm.js/pull/1543 and this is what I did:

1. See notification in octobox
2. Checkout PR
3. Click comments panel
4. See my old comment which I thought had been actioned because of notification
5. `git pull` in terminal
6. Close the diff editor and click the comment again
7. Close the diff editor and open SelectionRendererLayer.ts and see the change was made

Perhaps an "Outdated" label somewhere would help with this.

**Comment by JacksonKearl** [comment]
Closed with #1417
