### ISSUE TITLE
Why are comments focusable?

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#891]
Microsoft/vscode#67509

![image](https://user-images.githubusercontent.com/2193314/51997830-5dc88100-246c-11e9-9a61-f89dc2771131.png)

Since they are not interactive, why can I focus them?

**Comment by rebornix** [comment]
You should be able to use arrow keys to navigate through comments in a comment thread.

**Comment by Tyriar** [comment]
@rebornix isn't that what tab is for? Elsewhere in the workbench you would focus a list with tab and then navigate it with arrows, but it only takes up a single item in the tab order.

**Comment by alexr00** [comment]
> Elsewhere in the workbench you would focus a list with tab and then navigate it with arrows, but it only takes up a single item in the tab order.

Unless I'm misunderstanding the issue, this is exactly how the comments widget works now. You focus the thread with tab, then you can use the arrow keys to move between comments in the thread.
