### ISSUE TITLE
Comment reply box doesn't resize when you resize the diff view

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-pull-request-github#895]
Microsoft/vscode#67509

Repro:

1. Focus the reply text area
2. Resize the diff view sash (while focused)

![image](https://user-images.githubusercontent.com/2193314/51998440-8604af80-246d-11e9-85cd-d42ef6b3ef5f.png)

**Comment by RMacfarlane** [comment]
Reverted by https://github.com/Microsoft/vscode/pull/67792
