### ISSUE TITLE
Comment gutter bar is inaccessible from the keyboard

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-pull-request-github#896]
Microsoft/vscode#67509

Maybe I just couldn't figure it out, but I don't think you can tab to the gutter per line and I couldn't see a command to leave a comment/toggle the comment on the current line.

**Comment by RMacfarlane** [comment]
In VSCode 1.32, we exposed `workbench.action.addComment`, `workbench.action.submitComment`, and `workbench.action.hideComment`, so this should be fully keyboard accessible now
