### ISSUE TITLE
Live share integration doesn't work at all on Linux

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#898]
https://github.com/Microsoft/vscode/issues/67299

Host:

![image](https://user-images.githubusercontent.com/2193314/51999839-85b9e380-2470-11e9-93fb-4be07470fb4c.png)

Guest (myself):

![image](https://user-images.githubusercontent.com/2193314/51999866-9407ff80-2470-11e9-9879-adb65d1e09c0.png)

Checking out a PR and reloading the guest window didn't change anything, the SCM view is empty.

**Comment by rebornix** [comment]
@Tyriar do you see any error log in Dev Tools?

**Comment by Tyriar** [comment]
@rebornix can't reproduce anymore, seems to work now 😕
