### ISSUE TITLE
Explorer should reveal the file shown in the diff view

### ISSUE THREAD

**Issue by ramya-rao-a** [microsoft/vscode-pull-request-github#90]
- Checkout a PR
- Click on one of the files part of the PR to open the diff view
- Open the file explorer

**Expected**: The file in the diff view is revealed in the explorer. Just like how the file in a normal diff view is revealed.
**Actual**: The last opened file is revealed in the explorer and the focus moves to the editor with this file. If this file is not opened in any of the editor, then a new editor is opened for it.

**Comment by ramya-rao-a** [comment]
The `Open File` option available in the simple diff view is also missing in the PR diff view

![image](https://user-images.githubusercontent.com/16890566/45378410-31da5b00-b5b2-11e8-85d8-df788c742b35.png)

@rebornix @RMacfarlane Would you want to me to log a separate issue for this? 

Since we cannot have the go to definition or find all references feature in the diff view, I keep finding myself wanting to go to the underlying file. And there is no quick way to do that currently

**Comment by rebornix** [comment]
@ramya-rao-a what's the expected behavior of that action? Go to the file in current workspace if it exists?

**Comment by ramya-rao-a** [comment]
Yes

**Comment by RMacfarlane** [comment]
Closing this as out-of-scope.

However, the actual file on disk should be opened on the right side of the diff view when a PR is checked out now, so go to definition should work there and the `Open File` option is available
