### ISSUE TITLE
"Hot" installing the extension does not populates the view

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-pull-request-github#902]
- Open a MR Workspace in VS Code. I have VS Code, VS Code Docs, VS Code Internal Backlog and VS Code Distro repos
- Install the pull request extension
- Open SCM view
- Pull requests view is available now ✔️ 
- Open the Pull requests view
🐛 All queries shows empty results.

Queries are populated after I switch the repos

**Comment by RMacfarlane** [comment]
Closing as I'm no longer able to reproduce this issue with the latest version of the extension
