### ISSUE TITLE
Fail to detect remote is github when it has www subdomain

### ISSUE THREAD

**Issue by jrwrigh** [microsoft/vscode-pull-request-github#903]
- Extension version: 0.3.2
- VSCode Version: 1.30.2
- OS: Windows 10

Steps to Reproduce:
1. Install extension
2. Try to do anything with the extension

List of symptoms/issues:
1. There's no sign in popup, nor is there a command to do the sign in from command palette. I have no idea if I'm signed in or not or how to force the sign in. The only related option from the command palette is to sign *out*, which isn't helpful.
2. The "Pull Request" tree view thing doesn't appear. I've tried with multiple GitHub repositories to no avail.

Here's log from doing `git remote -v`:
```
λ git remote -v
origin  https://www.github.com/jrwrigh/phd_apps (fetch)
origin  https://www.github.com/jrwrigh/phd_apps (push)
```

However, on the "GitHub Pull Request" output log, I see:
```
[Info] Git repository found, initializing review manager and pr tree view.
[Info] No GitHub remotes found
[Info] No GitHub remotes found
[Info] Review> no matching pull request metadata found for current branch master
[Info] No GitHub remotes found
```

Overall, seems suspiciously like #502, but that was supposedly fixed.

**Comment by RMacfarlane** [comment]
Thanks for reporting this, it looks like there's some branching logic for handling `github.com` versus remotes with other domains that doesn't handle the `www` subdomain. A temporary workaround is `git remote set-url origin https://github.com/jrwrigh/phd_apps`
