### ISSUE TITLE
Git Pull Requests Issue with GHE with proxy behind

### ISSUE THREAD

**Issue by alphaseenu** [Microsoft/vscode-pull-request-github#905]
This is extension to https://github.com/Microsoft/vscode-pull-request-github/issues/432

I wanted to use git pull requests extesnion to pull the PRs from GHE. 

Vs code : 1.30.2
When i click sign on popped up right corner , it is taking me to oauth flow. How this GIT pull requests extension has to be registed with github.mycompany.com ? as the call back uri is vscode:github.vscode-pull-request-github which was default configured extension source code. Can any body help me here to come out of this.?

**Comment by alphaseenu** [comment]
Issue Continue.....
When hitting the "sign in " and "authorise", seems it is taking the "clientId" from github.com, which is an open domain. But how to make it consider github.mycompany.com and register the extension in enterprize domain?  What is call back url for an extension to be registered as oauth application in gurthu.mycompany.com? 

Help us.. please.!!

**Comment by StanleyGoldman** [comment]
Hi @alphaseenu. Sorry it's taken a while for us to catch up on this.

The method of authentication you are attempting is the Integrated Sign In. We have it documented [here](https://github.com/Microsoft/vscode-pull-request-github/wiki#integrated-sign-in). 

If you are unable to use that method, the alternative is to create a Personal Access Token documented [here](https://github.com/Microsoft/vscode-pull-request-github/wiki#personal-access-token-authentication).

I'm going to close this issue, feel free to re-open if you have additional questions.
