### ISSUE TITLE
GraphQL is still used on GH Enterprise

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode-pull-request-github#907]
Issue Type: <b>Bug</b>

We try to verify if a github repository supports GraphQL by checking 

```
supportsGraphQl(): boolean {
	return !!(this.hub && this.hub.graphql);
}
```

however we always create an AplloClient in `hub`

```
return {
	octokit,
	graphql: new ApolloClient({
		link: link(baseUrl, creds.token || ''),
		cache: new InMemoryCache,
		defaultOptions: {
			query: {
				fetchPolicy: 'no-cache'
			}
		}
	})
};
```

Extension version: 1.31.0
VS Code version: Code - Insiders 1.31.0-insider (8f56013e8f66650c1b0b65cc5c502691e307db21, 2019-02-01T18:28:27.157Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.43GB free)|
|Process Argv|-psn_0_3179272|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by rebornix** [comment]
@queerviolet do you know the proper way to test whether an endpoint support GraphQL or not?

**Comment by queerviolet** [comment]
Probably the most straightforward way is just to try making a query.
