### ISSUE TITLE
Review comments are missing in description view on GH Enterprise

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode-pull-request-github#908]
Issue Type: <b>Bug</b>

I manually force the extension to use REST API on Enterprise. Review Comments are missing

* Current * 

![image](https://user-images.githubusercontent.com/876920/52146006-67421c80-2617-11e9-8456-91fdc0ec7d29.png)

* Before *

![image](https://user-images.githubusercontent.com/876920/52146022-73c67500-2617-11e9-86b7-2e17fdf3de67.png)

Extension version: 1.31.0
VS Code version: Code - Insiders 1.31.0-insider (8f56013e8f66650c1b0b65cc5c502691e307db21, 2019-02-01T18:28:27.157Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.43GB free)|
|Process Argv|-psn_0_3179272|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by RMacfarlane** [comment]
fixed by https://github.com/Microsoft/vscode-pull-request-github/pull/910

**Comment by yulrizka** [comment]
@RMacfarlane, Is adding comments in a pending review for Github Enterprise not supported?

I tried to play around to make it work, I managed to create pending 'Review' by using octokit.
but got error while trying to add comment. 

```
user_id can only have one pending review per pull request
```

or it should use a different API?

**Comment by RMacfarlane** [comment]
@yulrizka It should be, though it's possible it's not in older versions.

There are several different versions of GitHub's API - the [REST one](https://developer.github.com/v3/) that octokit uses (v3), and a new [graphql one](https://developer.github.com/v4/)(v4). The v3 version doesn't support adding comments to pending reviews, you have to create the review all at once. So we're using the v4 version for adding pending comments instead: https://github.com/microsoft/vscode-pull-request-github/blob/aae86fdfd2045e1250cef44782b08c047e9a6a85/src/github/pullRequestManager.ts#L1038

When the extension first starts, it tries to detect if the current repository supports the v4 API or not. Some things have been added to the v4 API over time, so what I'm not sure about is if there's a GitHub Enterprise version that has graphql support, but not that feature
