### ISSUE TITLE
File appears to be selected in PR view even when the file is not open

### ISSUE THREAD

**Issue by ramya-rao-a** [microsoft/vscode-pull-request-github#91]
- Checkout a PR
- Click on one of the files to open the diff view
- Close the diff view and open another file from the file explorer
- Come back to the scm viewlet to find the file still in "selected" mode

![image](https://user-images.githubusercontent.com/16890566/42481878-769ba3de-8399-11e8-99d3-32b952c54447.png)

**Comment by rebornix** [comment]
Good catch. The problem here is we are using custom tree view to display file entries, which is not actually bind to real editors and we don't know when to unfocus the tree item.

**Comment by alexr00** [comment]
This is true of all custom tree views. Closing as as-designed.
