### ISSUE TITLE
Command to delete branches that got created by the extension

### ISSUE THREAD

**Issue by ramya-rao-a** [microsoft/vscode-pull-request-github#911]
Issue Type: <b>Feature Reuqest</b>

After using the extension for quite a while, I now find myself with a whole bunch of branches corresponding to all the code reviews that I checked out.

It would be super helpful if there was a command by the extension to delete such branches.

It can open up a quick pick with all such branches, and user can choose to delete all or a selected few.

Extension version: 0.3.2
VS Code version: Code - Insiders 1.31.0-insider (acc7365e41f9cb380e79bf78d7d102184f1ffe0d, 2019-01-29T06:20:23.551Z)
OS version: Windows_NT x64 10.0.17763

**Comment by alexr00** [comment]
Already exists now!
