### ISSUE TITLE
Scroll bar in add comment textarea constantly scrolling to top

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-pull-request-github#913]
vscode: insiders 2019-02-01T18:22:20.564Z, 8f56013e8f66650c1b0b65cc5c502691e307db21
ext: 1.31.0 nightly

This made the comment textarea unusable, reloading did not fix the problem

![scrollbar_freakout](https://user-images.githubusercontent.com/2193314/52159786-20c3e080-265e-11e9-8aaf-e51957cff804.gif)

**Comment by RMacfarlane** [comment]
Fixed by https://github.com/Microsoft/vscode/pull/67792
