### ISSUE TITLE
Squashed comment box when closing a file without saving

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#918]
vscode: insiders 2019-02-05T10:03:57.911Z
ext version: 1.31.0
macOS

Repro:

1. Start a mutli-line comment on a PR
2. Open a file (eg. README.md)
3. Make an edit
4. Close the editor, press do not save

Expected:

<img width="565" alt="screen shot 2019-02-05 at 11 47 06 am" src="https://user-images.githubusercontent.com/2193314/52300108-e4350500-293b-11e9-9b30-f055071a2af8.png">

Actual:

<img width="556" alt="screen shot 2019-02-05 at 11 45 46 am" src="https://user-images.githubusercontent.com/2193314/52300126-ec8d4000-293b-11e9-89f6-ba3859809598.png">

**Comment by alexr00** [comment]
I'm not able to reproduce this issue.
