### ISSUE TITLE
Adding comment failure doesn't handle the error case correctly

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#919]
vscode: insiders 2019-02-05T10:03:57.911Z
ext version: 1.31.0
macOS

I don't know why this failed but this happens after hitting "Start review", you're not handling the error case correctly and reverting to the original start review/add comment buttons:

<img width="559" alt="screen shot 2019-02-05 at 11 51 35 am" src="https://user-images.githubusercontent.com/2193314/52300334-73421d00-293c-11e9-87d2-738cfe4b42e8.png">

**Comment by Tyriar** [comment]
The error was fixed after I did a git pull in terminal, between these 2 commits in https://github.com/xtermjs/xterm.js/pull/1878

<img width="1230" alt="screen shot 2019-02-05 at 11 58 25 am" src="https://user-images.githubusercontent.com/2193314/52304250-2a439600-2947-11e9-9414-246f1d2ab9e7.png">

**Comment by alexr00** [comment]
I'm not able to reproduce this.
