### ISSUE TITLE
Extension statusbar button missing unless PR checked out

### ISSUE THREAD

**Issue by tomerMP** [microsoft/vscode-pull-request-github#922]
- Extension version: 0.3.2
- VSCode Version: 1.30.2
- OS: Windows 10 Pro v1803 (build 17134.523)

Note: Issue is intermittent 
Even when button is present it usually gets stuck on default "non-PR-branch" button

Steps to Reproduce:

1. Open VSCode
2. checkout Master branch => button is missing
3. go to SCM > Pull Requests
4. Checkout a PR => button appears white (no color based on merge conflicts)
5. Exit review mode => button disappears
6. Checkout branch without active PR => no "CreatePR" button
7. Checkout branch with active PR => no green/red PR button

**Comment by RMacfarlane** [comment]
This is by design - the status bar item shows actions related to the currently check out pull request, so it only appears when there is an active pull request.
