### ISSUE TITLE
Signing in on Github Enterprise errors out

### ISSUE THREAD

**Issue by mkonikov** [microsoft/vscode-pull-request-github#923]
- Extension version: 0.3.2
- VSCode Version: 1.30.2 (1.30.2)
- OS: macOS Mojave

Steps to Reproduce:

When trying to login on my Enterprise GitHub, every time I click sign in it leads me to a page on https://vscode-auth.github.com which errors out:

![image](https://user-images.githubusercontent.com/7562285/52348181-b7432980-29f1-11e9-9702-6918c08e1d2e.png)

**Comment by pcastellazzi** [comment]
Same here, my guess is this is happening because our enterprise GitHub server is on premise and can't be accessed from internet. It looks like VS Code is trying OAuth from a Heroku app.

**Comment by mkonikov** [comment]
@pcastellazzi I did follow those steps and while the token did get copied to my keychain, I'm still finding it requesting me to login when I launch VSCode and integration not working.

(As a side note it should prob. highlight that after relaunch the token gets moved to keychain. I kept on checking my settings.json and after seeing it missing assuming that was the broken part. Maybe I'll PR to docs with slightly clearer language)

**Comment by stinnux** [comment]
I have the same issue using Extension Version 0.4.0 and Visual Studio Code 1.31.1 on macOS 10.14.3

The workaround also doesn't work. I can see the token in the keychain but it keeps me asking for login credentials. 

I can also see in GHE that the token has never been used. 

The GHE instance is not reachable from the internet.

**Comment by akbyrd** [comment]
Same issue.

**Comment by ProLoser** [comment]
Can we have the server instead of timing out and showing a 404 redirect to the alternative instructions and/or maybe add a link to the instructions that combines the attempted enterprise host combined with `/settings/tokens/new?scopes=repo,read:user,user:email,write:discussion&description=VSCode%20Github%20Extension` which will autofill the entire token form for you. People would just hit 'generate' and then copy-paste the token.

It's a little annoying that alt-tabbing away from VSCode after you enter the token cancels the flow (I have to type in the enterprise host without letting VSCode lose focus).

**Comment by StanleyGoldman** [comment]
@ProLoser while working to debug some of these GitHub Enterprise issues, I ran into this scenario. I'm looking to fix it for the next release. Hopefully fixing this is a start to better understanding some of these authentication issues.

@mkonikov I'm working to figure out the issue you have been having, but as mentioned earlier, the error might be a consequence of the setup. In the meantime things have changed in the plugin as far as authentication goes, would you mind updating to the latest version and starting again from scratch?

@stinnux did you try the workaround that was mentioned in the wiki. https://github.com/Microsoft/vscode-pull-request-github/wiki#personal-access-token-authentication

@akbyrd can you be a bit more specific, same issue as whom?

Also, what version of GitHub Enterprise are you all using?

**Comment by mkonikov** [comment]
@StanleyGoldman Seems to work for me now.

**Comment by StanleyGoldman** [comment]
Hey @mkonikov I'm glad it's working for you, but so I can be sure of what I'm debugging, can you be a bit more specific.

- What steps did you go through that worked for you?
- What version of the extension are you running?
- What version of GitHub Enterprise do you have?

**Comment by mkonikov** [comment]
Honestly nothing. Just tried again with the latest version.

**Comment by timedroid** [comment]
I'm still seeing this issue. 
GitHub Pull Requests 0.11.2, GitHub Enterprise 2.15.18.

**Comment by knotthere** [comment]
Still broken with version 0.15.0 & GitHub Enterprise ???.

**Comment by RMacfarlane** [comment]
We have discontinued support for GitHub Enterprise. https://github.com/microsoft/vscode-pull-request-github/wiki#2-is-github-enterprise-supported
