### ISSUE TITLE
404 error when trying to log in to Enterprise account

### ISSUE THREAD

**Issue by mymikemiller** [Microsoft/vscode-pull-request-github#930]
Issue Type: <b>Bug</b>

My VSCode is set up to use my company's github enterprise (github.mycompany.com). I'd like to use this extension to manage my PRs there. After clicking Sign In in the initial popup dialog, I'm taken to a Continue button on a vscode-auth.github.com webpage, but clicking just takes me to a 404 error at github.mycompany.com/login.

Install the extension
Reload VSCode
Window pops up in bottom right corner asking you to sign in to github
Click Sign In
Click Continue
404

The page that the popup's Sign In button takes me to is:

https://vscode-auth.github.com/authorize?authServer=https://github.mycompany.com/&callbackUri=vscode://GitHub.vscode-pull-request-github/did-authenticate&scope=read:user%20user:email%20repo%20write:discussion

After clicking Continue, I'm taken to the 404 "This is not the web page you are looking for" page at the following URL:

https://github.mycompany.com/login/oauth/authorize?response_type=code&client_id=[a-hash]&scope=read%3Auser%20user%3Aemail%20repo%20write%3Adiscussion&state=[a-bunch-of-letters]

Does this extension work with Enterprise accounts hosted on my company's servers, or just on github.com?

Extension version: 0.3.2
VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:48:31.260Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (11.47GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by mkonikov** [comment]
I flagged that here https://github.com/Microsoft/vscode-pull-request-github/issues/923

**Comment by uphy** [comment]
I had same problem and I had solved by manually providing authentication response.

https://github.com/Microsoft/vscode-pull-request-github/wiki#personal-access-token-authentication

**Comment by StanleyGoldman** [comment]
Hey @mymikemiller in this scenario you have to manually provide the authentication reponse (as @uphy noted).

Check the link and let us know if you have any other problems with that.

https://github.com/Microsoft/vscode-pull-request-github/wiki#2-is-github-enterprise-supported
