### ISSUE TITLE
Changes in pull request previous version

### ISSUE THREAD

**Issue by st-schneider** [microsoft/vscode-pull-request-github#932]
Issue Type: <b>Bug</b>

It seems that the version that the current state is compaared against is always blank
![screen shot 2019-02-08 at 13 03 28](https://user-images.githubusercontent.com/30625381/52477400-0d56cf00-2ba2-11e9-86b2-7435719dfdc0.png)

Extension version: 0.4.0
VS Code version: Code - Insiders 1.32.0-insider (1c50a87561055485d93a3961160902308497f1e3, 2019-02-08T06:15:19.612Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 5, 4|
|Memory (System)|16.00GB (0.23GB free)|
|Process Argv|-psn_0_15302295|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by RMacfarlane** [comment]
A "Couldn't find commit x locally." error notification is also shown then, the target branch has become out of date and we should pull so that we have the merge base commit locally

**Comment by scrossan-crown** [comment]
I'm also having this issue when clicking on a file in changes in pull request view.
```
We couldn't find commit 7bbffed7f65a2560336bcabf680bb634ff0abca8 locally. You may want to sync the branch with remote. Sometimes commits can disappear after a force-push
```

**Comment by scrossan-crown** [comment]
I'm still having this issue in version 0.7.0.

```
We couldn't find commit 0abb4559e0790f1871358b01cf03bd9f2a43a16a locally.
```

**Comment by dameunbite** [comment]
I am having the same problem. The branch is out of date but when I merge lastest master changes it keeps saying the same thing

<img width="1440" alt="Screen Shot 2020-07-31 at 1 33 57 AM" src="https://user-images.githubusercontent.com/48269003/89003537-078d0600-d2ce-11ea-8205-c46fbb02f6cb.png">

This only happens in the section "changes in pull request". When I see the changes in the section "Pull Request" it displays the correct changes.

<img width="1439" alt="Screen Shot 2020-07-31 at 1 36 32 AM" src="https://user-images.githubusercontent.com/48269003/89003629-46bb5700-d2ce-11ea-981c-87a2fe5bd268.png">

**Comment by alexr00** [comment]
The error message has since been updated to recommend that you sync your branch with the remote.
