### ISSUE TITLE
Couldn't find commit x locally. Error notification

### ISSUE THREAD

**Issue by scrossan-crown** [Microsoft/vscode-pull-request-github#935]
- Extension version: 0.4.0
- VSCode Version: 1.31.0-insider
- OS: Windws 10

Steps to Reproduce:

1. Check out a pr in review mode
2. Click on a file in the CHANGES IN PULL REQUEST area

**Comment by RMacfarlane** [comment]
This is the same root cause as https://github.com/Microsoft/vscode-pull-request-github/issues/932, so I'm going to consolidate into that issue. If master/whatever the target branch is for the PR is out of date, we show this error. Instead we should pull so that we have the commit locally
