### ISSUE TITLE
Description Clears When Switching Tabs

### ISSUE THREAD

**Issue by ecbrodie** [microsoft/vscode-pull-request-github#940]
- Extension version: 0.4.0
- VSCode Version: 1.31.0
- OS: MacOS 10.14.3

## Steps to Reproduce:

1. Create a new PR from VS Code
1. Start typing stuff in the *Description* field
1. Switch tabs (I may need to do this for reasons such as quickly checking the contents of a particular code change, so that I can write an accurate description for the PR)
1. Come back to the PR tab
1. WELP, the description is now blank (it looks like the entire tab gets refreshed, perhaps due to a fetch from GitHub?). I would have expected the description to remain. Now I have to type the same X sentences into the description, annoying...

## NOTES

* This may be a dupe of #337, but that Issue was reported several months ago and was supposedly marked as fixed. I'm judging at this point that this bug is worthy enough of a new Issue report.

**Comment by RMacfarlane** [comment]
This was fixed with https://github.com/microsoft/vscode-pull-request-github/pull/1201. However, if instead of switching tabs, you completely close and reopen the page, text is lost. I've filed a new issue for that: https://github.com/microsoft/vscode-pull-request-github/issues/1373
