### ISSUE TITLE
"Cannot toggle word wrap in a diff editor"

### ISSUE THREAD

**Issue by octogonz** [Microsoft/vscode-pull-request-github#941]
The diff view is always side-by-side.  However if you have long lines, you have to scroll horizontally to see what has changed.  My monitor is actually in "portrait" not "landscape" dimensions (1600x1200), so the side-by-side view already provides a fairly narrow view.

**Feature request:**  The experience would be much better if I could enable word-wrap in this view.  When I try VS Code's command **"Toggle Word Wrap"**, I get an error message:  `"Cannot toggle word wrap in a diff editor"`

**Comment by octogonz** [comment]
Another option would be to support inline diffs like the GitHub web site.

**Comment by RMacfarlane** [comment]
Hey @octogonz, there is an upstream issue in VSCode asking for word wrap in diff views: https://github.com/Microsoft/vscode/issues/11387.

It is currently possible to toggle to an inline diff, if you run the `Compare: Toggle Inline View` command. The `diffView.renderSideBySide` setting can also be used for this. There's an issue with the commenting widget when inlined, where comments on the base file are hidden (https://github.com/Microsoft/vscode-pull-request-github/issues/160), which we don't have a good solution to right now but hope to fix.

Hope that helps, please go thumbs-up those issues and add any feedback there. Thanks!

**Comment by octogonz** [comment]
> It is currently possible to toggle to an inline diff, if you run the `Compare: Toggle Inline View` command. The `diffView.renderSideBySide` setting can also be used for this.

@RMacfarlane  This was pretty helpful, thanks!
