### ISSUE TITLE
Unable to add comment to removed lines

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/vscode-pull-request-github#945]
- Extension version: `0.4.0`
- VSCode Version: `1.32.0-insiders`
- OS: Windows 1903

Steps to Reproduce:

1. Open review for PR
1. _Checkout PR (this is required step, otherwise works fine)_
1. Open file with removed lines _(and removed lines should be closer to the end or a lot of removed lined)_
1. Click on Create comment (+) in the right panel _on line that has higher line number, that total lines left in the right panel_.
1. Enter comment and click Start review

Buttons row replaced with review buttons (Delete review, Add comment, Finish review) and erro is displayed below field.

_In this case after changes only 8 lines left, however comment is placed on line 16_
![image](https://user-images.githubusercontent.com/1312662/52634802-d13caa80-2ed0-11e9-83a3-7191e47539ca.png)

There are no problems with adding comments on GitHub _or when PR isn't checked out_

**UPD.** Edits in italic text should clarify repro steps.

**Comment by alexr00** [comment]
This appears to work now.
