### ISSUE TITLE
Enable emoji selector on PR description/title textareas

### ISSUE THREAD

**Issue by Yurickh** [microsoft/vscode-pull-request-github#949]
When I use mac's shortcut to open the native emoji selector (⌘^space), nothing happens.

Since it works on the commit message box, I expected it would work on this extension as well.

**Comment by bnb** [comment]
Just hit this as well. Would love to see this ✨ 

Additionally, it would be really cool if the GitHub emoji syntax/selector could be added!

**Comment by Yurickh** [comment]
Just checked and it seems to still be an issue as of this date.

**Comment by bnb** [comment]
@RMacfarlane any update on this?

**Comment by Yurickh** [comment]
I took some time to dig a bit deeper on this, and I think it might to be in vscode's side to fix it actually.
You see, no context menu actually pops up inside the web view, and it's not related to any handler/style in this extension, rather it seems it's an issue with web views in vscode itself (e.g. https://github.com/microsoft/vscode/issues/12215)

**Comment by alexr00** [comment]
This works for me on Windows. If this is still happening on macOS, please comment!
