### ISSUE TITLE
Show removed file with some indication

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode-pull-request-github#950]
I suggest either crossing the filename out or mark is as read with a red D to the right:

![image](https://user-images.githubusercontent.com/4033249/52735703-0b638600-2f7d-11e9-93d2-8f7d97c98ad9.png)

For example, `vue-html.json` should either show as crossed out, or in red with a red `D` below the `M` of `vue-html.YAML`.

**Comment by RMacfarlane** [comment]
Hmm, we should already be rendering a `D` decorator for these files, so this sounds like a bug:
![Screen Shot 2019-03-08 at 4 19 00 PM](https://user-images.githubusercontent.com/3672607/54062918-fcf43d00-41bd-11e9-87b1-88e2f8a1a2fa.png)
You wouldn't happen to remember if the files were modified in some other way, like a move or rename?

**Comment by octref** [comment]
Cool, if this comes up I can open another issue.
