### ISSUE TITLE
`Pull Request #xxx` editor not refresh automatically when PR change

### ISSUE THREAD

**Issue by lihuanshuai** [microsoft/vscode-pull-request-github#956]
Issue Type: <b>Bug</b>

1. open PR on a repo, merge it or other operations
2. rebase, push some commits, open another PR with same branch on same repo

Then, the title of `Pull Request #xxx` editor changed, yet content of editor is still old, you need to click `Refresh` button manually. That is not a smooth experience, shall the refreshment on content be triggered at same time?

Extension version: 0.4.0
VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6660U CPU @ 2.40GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|8.00GB (0.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by alexr00** [comment]
Closing as we have no plans to address this issue in the future.
