### ISSUE TITLE
Adding a comment failed: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by scrossan-crown** [microsoft/vscode-pull-request-github#957]
- Extension version: 0.4.0
- VSCode Version: 1.32.0-insider
- OS: Windows 10

Steps to Reproduce:

1. Start a review when commenting on a line 
2. Add another comment to the review

![image](https://user-images.githubusercontent.com/30405149/52860996-ffb4c280-3128-11e9-89f0-f149773c1b63.png)

The comment does get created though 
![image](https://user-images.githubusercontent.com/30405149/52861028-1a873700-3129-11e9-9dca-c09de11949c1.png)

**Comment by RMacfarlane** [comment]
Closing as I'm not able to repro this in the latest version of the extension and believe this has been fixed. Please let me know if you see this again. Thanks!
