### ISSUE TITLE
Requesting changes failed.

### ISSUE THREAD

**Issue by scrossan-crown** [microsoft/vscode-pull-request-github#958]
- Extension version: 0.4.0
- VSCode Version: 1.32.0-insider
- OS: Windows 10

Steps to Reproduce:

1. Request changes in a pull request description view
2. Error will pop up but request of changes was successfull

Error that was given in vscode
```
Requesting changes failed. GraphQL error: Something went wrong while executing your query. Please include `BF75:4420:12FC5D3:269B681:5C66DC66` when reporting this issue.
```

![image](https://user-images.githubusercontent.com/30405149/52867033-e8c99c80-3137-11e9-98ef-654c2b26cc62.png)

**Comment by eramdam** [comment]
I'm experiencing the same issue, but with the following message

```
Requesting changes failed. GraphQL error: Something went wrong while executing your query.
Please include `E84B:9603:347890:3F3C91:5C6CA62D` when reporting this issue.
```

**Comment by justasitsounds** [comment]
Ditto;

> Requesting changes failed. GraphQL error: Something went wrong while executing your query. Please include `BB18:0469:499A20:596308:5C885C0C` when reporting this issue.

extension version: 0.5.0
vscode:
- Version: 1.32.1
- Commit: 05f146c7a8f7f78e80261aa3b2a2e642586f9eb3
- Date: 2019-03-08T00:46:10.898Z
- Electron: 3.1.3
- Chrome: 66.0.3359.181
- Node.js: 10.2.0
- V8: 6.6.346.32
- OS: Linux x64 4.15.0-46-generic
OS: Ubuntu 18.04.2 LTS

**Comment by zaunermax** [comment]
Same here: 
> Requesting changes failed. GraphQL error: Something went wrong while executing your query. Please include `EBBF:1F74:27808FF:512BFB1:5CDA73B8` when reporting this issue.

**Comment by alexr00** [comment]
I don't see this happening anymore. If you're still seeing the problem please ping this issue!
