### ISSUE TITLE
Provide commands for checking out / exiting review mode

### ISSUE THREAD

**Issue by octref** [microsoft/vscode-pull-request-github#959]
I'd like to have a command `Check out pull request` that opens another list of pull requests to pick from.

Also a command `Exit review mode` so I don't have to open tree, click description, and click "Exit" manually.

**Comment by octref** [comment]
@RMacfarlane What's the operations done by "Exit Review" mode behind the scenes? Can I simply do a `git checkout master` and the PR extension can handle that fine?

**Comment by RMacfarlane** [comment]
@octref Yes, that should be handled. "Exit Review" is just calling the git extension's checkout command

**Comment by RMacfarlane** [comment]
Since exiting review mode is equivalent to changing branches, I think we don't want to add another command to do this
