### ISSUE TITLE
[Live Share] Error occurs when a guest selects a file for a checked out PR

### ISSUE THREAD

**Issue by lostintangent** [microsoft/vscode-pull-request-github#961]
**Steps to Reproduce:**

1. Open up a project, and checkout a PR locally
2. Start a new Live Share session
3. Join the session from another instance of VS Code
4. From the guest-side, expand the `Files` node in the `Changes in Pull Request` view, and attempt to select a file.

**Expected:** For the file to be opened
**Actual:** The following error is displayed. Seems like the file path just needs to be translated to use the `vsls` scheme and not `file`?

![image](https://user-images.githubusercontent.com/116461/52879642-81e6bc00-3114-11e9-9a16-4d5f83a4cd6f.png)

*Note: If you attempt to open up a file underneath a commit node, that works. So this issue seems to only impact the `Files` node.*

// CC @rebornix

**Comment by rebornix** [comment]
@lostintangent good catch! I think we used literal `file` scheme for this case instead of the scheme the workspace is using.

**Comment by alexr00** [comment]
looks like this was fixed
