### ISSUE TITLE
Find Pull Requests by tracked branches not by local branches

### ISSUE THREAD

**Issue by st-schneider** [microsoft/vscode-pull-request-github#963]
Issue Type: <b>Feature Request</b>

Currently the github pull requests view compares the local branch name with the remote branch name neglecting that the local branch name might have gotten renamed but is still tracking the same remote branch. In order to have a consistant behaviour between local customized branches and static remote branches it would be great if the primary key would be the tracked branch.

Extension version: 0.4.0
VS Code version: Code - Insiders 1.32.0-insider (4e68ba25fbc752e3d7da488b8d3db374029577d6, 2019-02-18T06:15:59.901Z)
OS version: Darwin x64 17.7.0

**Comment by alexr00** [comment]
This has since been fixed!
