### ISSUE TITLE
GitHub viewlet should show up once a repository is added

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-pull-request-github#970]
Issue Type: <b>Bug</b>

Right now, when we open a workspace, we can't see the GitHub viewlet even when the SCM loads a git repository successfully. It takes around another few seconds for the GitHub viewlet to show up, while all other viewlets show up real quick, e.g., GitLens, LiveShare.

Extension version: 1.50.0
VS Code version: Code - Insiders 1.32.0-insider (a75cf6e4b4317de0bf38284af255bdf0089deb68, 2019-02-19T06:15:45.796Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 5, 8|
|Memory (System)|16.00GB (2.65GB free)|
|Process Argv|-psn_0_3261212|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by RMacfarlane** [comment]
Closing since the viewlet is now always visible
