### ISSUE TITLE
PR view shown empty after switching between SCM and PR viewlet

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode-pull-request-github#974]
Issue Type: <b>Bug</b>

Testing https://github.com/Microsoft/vscode/issues/69255

![feb-25-2019 11-03-52](https://user-images.githubusercontent.com/9205389/53329814-4060c880-38ed-11e9-9f0f-62f2ed871279.gif)

Extension version: 1.50.0
VS Code version: Code - Insiders 1.32.0-insider (393b48d4a5de85b6fa1d2ad0a59588d6715e12ea, 2019-02-25T01:33:51.804Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.93GB free)|
|Process Argv|--extensions-dir /Users/chrmarti/Development/repos/tmp/ext --user-data-dir /Users/chrmarti/Development/repos/tmp/user pullrequest-demo|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by chrmarti** [comment]
Only when already expanded, it works fine if it is collapsed in the SCM viewlet.

**Comment by joaomoreno** [comment]
Yup same here.

**Comment by RMacfarlane** [comment]
Should already be fixed by https://github.com/Microsoft/vscode-pull-request-github/pull/969
