### ISSUE TITLE
Create Activity Bar for extension

### ISSUE THREAD

**Issue by wsmelton** [Microsoft/vscode-pull-request-github#976]
Pull the extension contents out of the Source Control and into a dedicated Activity/Side Bar pane. 

Right now you should also assign viewing this side bar shortcut to `CTRL+SHIFT+G` as I do not see that being taken out-of-the-box by anything in Code.

**Comment by wsmelton** [comment]
I believe this is being explored in #921 

> * Explore setting to move consolidated tree view to activity bar

**Comment by RMacfarlane** [comment]
Thanks @wsmelton! I've linked to this from the plan.

A setting for adding showing it to a separate pane was added with https://github.com/Microsoft/vscode-pull-request-github/issues/976. The keybinding `View: Show GitHub Pull Requests` shows up from that but doesn't have a default binding - it looks like `CTRL+SHIFT+G` is focusing the SCM view by default

**Comment by wsmelton** [comment]
I would recommend a default keybinding of just `CTRL+SHIFT+P R` 😁

**Comment by RMacfarlane** [comment]
Sorry, I neglected to close this issue!

This has been completed, there's no default keybinding on Windows, `Ctrl+Shift+P` on Mac/Linux. You can change it by searching "View: Show GitHub Pull Requests" in the keyboard shortcuts editor.
