### ISSUE TITLE
Removing reaction feels slow

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode-pull-request-github#980]
re [Microsoft/vscode#69321](https://github.com/Microsoft/vscode/issues/69321)

* add a reaction
* select the reaction to remove it
* :bug: it feels slow, like removal isn't happening optimistically but only after the server has responded. I have actually seen myself selecting a reaction multiple times so that it gets removed

**Comment by alexr00** [comment]
Even if we don't await the GitHub API call this still feels slow. It seems that this is mostly caused by the round trip to the extension host.
