### ISSUE TITLE
Reactions don't update when changed on GH

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode-pull-request-github#981]
re [Microsoft/vscode#69321](https://github.com/Microsoft/vscode/issues/69321)

* use extension to add a reaction
* use browser to remove that reaction
* extension doesn't update

**Comment by alexr00** [comment]
We update the PR data for checked out PRs on a interval, and I've verified that the comment reactions are part of that. 

For PRs that aren't checked out, the PR data is updated when you refresh the PRs tree.
