### ISSUE TITLE
Rendering of reactions isn't pretty

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode-pull-request-github#982]
re [Microsoft/vscode#69321](https://github.com/Microsoft/vscode/issues/69321)

The horizontal alignment seems off, the emoji seems small in comparison to the number, the border seems too strong

<img width="100" alt="screenshot 2019-02-25 at 11 34 20" src="https://user-images.githubusercontent.com/1794099/53331497-553f5b00-38f1-11e9-9c4c-6643430e08d7.png">

**Comment by RMacfarlane** [comment]
Fixed with https://github.com/microsoft/vscode/commit/747ed274094a5f989444d490df3591a8c3bf1911
