### ISSUE TITLE
Add button in sidebar looks out of place

### ISSUE THREAD

**Issue by misolori** [Microsoft/vscode-pull-request-github#983]
Testing https://github.com/Microsoft/vscode/issues/69254

<img width="208" alt="image" src="https://user-images.githubusercontent.com/35271042/53357294-6765cd00-38e2-11e9-9181-84a9c4e5f239.png">

The sidebar icons are using Octicons while the add icon is VS Code's plus button, which has a thicker stroke and is larger, which makes it look out of place with the rest of the icons.

Suggestion would be to use the [Octicon plus](https://octicons.github.com/icon/plus/):

<img width="228" alt="image" src="https://user-images.githubusercontent.com/35271042/53357431-c1669280-38e2-11e9-86ff-a5f74527b2a7.png">

**Comment by RMacfarlane** [comment]
I prefer matching the VS Code plus button to be consistent with the rest of VS Code
