### ISSUE TITLE
Reviewer list unordered, Labels are alphabetical

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode-pull-request-github#986]
- Extension version: Nightly 1.56.0
- VSCode Version: 1.32 Insiders
- OS: Windows

Found while testing https://github.com/Microsoft/vscode/issues/69254

Steps to Reproduce:

1. In vscode-docs open an existing PR.
2. Look at both the Labels and Reviewers dropdowns.

Labels is alphabetical with uppercase first.
Reviewer list seems to be unordered.

**Comment by RMacfarlane** [comment]
The ordering of the reviewer list is less clear, but it should be trying to imitate GitHub - all reviewers that have left a review are alphabetical, and then all reviewers that have a pending review request (dot icon) are shown after them in alphabetical order

**Comment by RMacfarlane** [comment]
Closing as designed.
