### ISSUE TITLE
Rendering issue when opening multiple PRs

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode-pull-request-github#987]
Issue Type: <b>Bug</b>

Testing https://github.com/Microsoft/vscode/issues/69254

Not sure how to repro this, but I've have encountered this a few times so far where the page renders oddly:

<img width="1562" alt="image" src="https://user-images.githubusercontent.com/35271042/53358473-5074aa00-38e5-11e9-85a3-6f8d168f2d80.png">

<img width="1069" alt="image" src="https://user-images.githubusercontent.com/35271042/53358482-59657b80-38e5-11e9-9580-695ac1a065a7.png">

Extension version: 1.56.0
VS Code version: Code - Insiders 1.32.0-insider (393b48d4a5de85b6fa1d2ad0a59588d6715e12ea, 2019-02-25T01:33:51.804Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|-psn_0_569483|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by alexr00** [comment]
I haven't see this recently. Please feel free to reopen if you're still seeing this issue!
