### ISSUE TITLE
User alias should appear in bold like they do in github

### ISSUE THREAD

**Issue by ramya-rao-a** [microsoft/vscode-pull-request-github#99]
Testing https://github.com/Microsoft/vscode/issues/55396 on Ubuntu

View comments that mention a github alias in the PR description view.
Notice that the alias/user-name has the same font as rest of the text. Github displays alias/user-name with a bolder font-weight

<img width="554" alt="screen shot 2018-07-31 at 2 24 34 pm" src="https://user-images.githubusercontent.com/16890566/43488115-833736a4-94cd-11e8-86be-bf367f6878f2.png">

<img width="688" alt="screen shot 2018-07-31 at 2 25 33 pm" src="https://user-images.githubusercontent.com/16890566/43488163-a286f512-94cd-11e8-8851-490f22efca72.png">

_Copied from original issue: Microsoft/vscode#55518_

**Comment by rebornix** [comment]
Related #66 . Right now the content we get from github is markdown format but it doesn't convert user id, issue links, etc to links in advance.

**Comment by RMacfarlane** [comment]
Usernames within comments are now linkified on the description page, so they stand out visually from other text:
![Screen Shot 2019-10-08 at 2 39 21 PM](https://user-images.githubusercontent.com/3672607/66435324-6f89fd00-e9d9-11e9-893a-56b3f1332aa7.png)
