### ISSUE TITLE
Comments can shift around or become taller on hover

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode-pull-request-github#996]
Testing Microsoft/vscode#69321

**Repo**
- Open a file with some reaction comments
- Hover over the comment

**Bug**
![feb-25-2019 13-21-05](https://user-images.githubusercontent.com/12821956/53369588-6479d500-3900-11e9-8031-77fb572c525b.gif)

**Comment by rebornix** [comment]
![hover-no-shifting](https://user-images.githubusercontent.com/876920/53519674-a33a9700-3a88-11e9-9e13-29b1cab1d4c2.gif)

should be fixed now.
