### ISSUE TITLE
Clicking on reaction can shift other reactions over slightly

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode-pull-request-github#998]
Microsoft/vscode#69321

**Repo**
1. Open comment with multiple reactions
1. Click on the first one to add your reaction

**Bug**
When the border is added, the other reactions are shifted over by a pixel or two:

![feb-25-2019 13-27-23](https://user-images.githubusercontent.com/12821956/53369903-25984f00-3901-11e9-83a9-e30a1acfb92f.gif)

**Comment by rebornix** [comment]
Fixed in upstream.
